feat: science module
faker-js/faker pull request #1014
Opened 2022-05-27 20:28 UTC by import-brain

closes #944

2022-05-28 14:12 UTC, ST-DDT requested changes

2022-05-28 14:12 UTC, ST-DDT commented on src/definitions/science.ts
> +  shortUnit: string[];
Maybe unitAbbr, as we already use that term elsewhere.

2022-05-28 14:12 UTC, ST-DDT commented on src/definitions/science.ts
> +  element: Element[];
I think we should explicitly refer to chemical elements. As `element` is kind of generic.

2022-05-28 14:12 UTC, ST-DDT commented on src/modules/science/index.ts
> +  unit(options?: { long?: boolean }): string {
```suggestion
  unit(options: { long?: boolean } = {}): string {
```

2022-05-28 14:12 UTC, ST-DDT commented on src/modules/science/index.ts
> +    options = { long };
```suggestion
```

2022-05-28 14:12 UTC, ST-DDT commented on src/modules/science/index.ts
> +    const { long = true } = options || {};
```suggestion
    const { long = true } = options;
```

2022-05-28 15:07 UTC, Shinigami92 commented on src/definitions/science.ts
> +  shortUnit: string[];
How about structuring it like `unit: { full, abbr }`? That way, the data can be coupled.
SO you could use 

```ts
const { abbr, full } = science.unit()
```

2022-05-28 16:01 UTC, ST-DDT commented on src/definitions/science.ts
> +  shortUnit: string[];
That doesn't match up with our other methods like date.month and weekday.
And I dont see a usecase for it either.

2022-05-28 16:23 UTC, Shinigami92 commented on src/definitions/science.ts
> +  shortUnit: string[];
The use-case would be that you just want one unit and show it in a table or whatever
So you have e.g. `Take 200 g (gram) of salt`

2022-05-28 16:35 UTC, Shinigami92 commented on src/definitions/science.ts
> +  shortUnit: string[];
I may want to design the httpStatus call in a same way
But you are right as currently we don't have that yet (maybe currency?)
I wont gave a veto if it gets merged as is, but it would be a bit better UX in my eyes :shrug:

2022-05-29 10:58 UTC, pkuczynski commented on src/definitions/science.ts
> +  chemicalElement: Element[];
Is it worth changing the name? Do we have other `element` function we would like to develop? If we make the change, we should also change `Element` type to `ChemicalElement`, but I doubt the value in this change tbh.

2022-05-29 11:02 UTC, pkuczynski commented on src/definitions/science.ts
> +  shortUnit: string[];
I agree with @Shinigami92 it would be better. Gave the same feedback to `element` in the #944. Otherwise you could not get both short and long name for the unit. And if user wants only one, he could do: `faker.unit().short`

2022-05-29 11:04 UTC, pkuczynski requested changes

2022-05-29 11:04 UTC, pkuczynski commented on src/modules/science/index.ts
> +  elementName(): string {
Haven't you agreed in #944 to implement it as `faker.element().name`?

2022-05-29 11:04 UTC, pkuczynski commented on src/modules/science/index.ts
> +  elementSymbol(): string {
`faker.element().symbol`

2022-05-29 11:04 UTC, pkuczynski commented on src/modules/science/index.ts
> +  unit(options: { long?: boolean } = {}): string {
`faker.unit().long`, `faker.unit().short`

2022-05-29 11:47 UTC, Shinigami92 commented on src/definitions/science.ts
> +  chemicalElement: Element[];
IMO yes, we should use `chemicalElement` and `ChemicalElement`

2022-05-29 20:46 UTC, import-brain commented on src/modules/science/index.ts
> +  elementName(): string {
*facepalm* Whoops, I forgot

2022-05-29 21:01 UTC, pkuczynski commented on src/definitions/science.ts
> +  element: Element[];
In science? What other elements in science there are?

2022-05-29 21:03 UTC, pkuczynski commented on src/definitions/science.ts
> +  chemicalElement: Element[];
I am wondering if we should not use just `element` as what other elements there might be in the science module? Its even called `periodic table of elements` isn't it?

2022-05-29 21:57 UTC, import-brain commented on src/definitions/science.ts
> +  chemicalElement: Element[];
> I am wondering if we should not use just `element` as what other elements there might be in the science module? Its even called `periodic table of elements` isn't it?

Yeah, I can't recall any other thing commonly referred to as an "element" that's widely-used in science.

2022-05-29 21:59 UTC, pkuczynski commented on src/definitions/science.ts
> +  chemicalElement: Element[];
Me neither, that's why I would keep it as discussed initially: `element`. @ST-DDT @Shinigami92 wdyt?

2022-05-30 07:27 UTC, ST-DDT commented on src/modules/science/index.ts
> +    return this.faker.definitions.science.chemicalElement[index];
Why don't you use `helpers.arrayElement`?
```suggestion
    return this.faker.helpers.arrayElement(this.faker.definitions.science.chemicalElement);
```

2022-05-30 07:37 UTC, ST-DDT commented on src/definitions/science.ts
> +  chemicalElement: Element[];
I agree with you, that's it's the most common one in science.
But it's not the only one: https://en.wikipedia.org/wiki/Electrical_element
Even wikipedia refers to it as https://en.wikipedia.org/wiki/Chemical_element

Similar to `statusCode`s in the internet referring mostly to http status codes, but there are also other status codes such as `grpc`'s one.

Should we discuss this in one of our next team meetings?

2022-05-30 10:13 UTC, Shinigami92 commented on src/locales/en/science/unit.ts
> +    short: 'Ω',
Should we also name `short` just `symbol`?

2022-05-30 10:13 UTC, pkuczynski commented on src/definitions/science.ts
> +  chemicalElement: Element[];
Wikipedia is a bit different than us because they do not have namespaces, so they sometimes need a bit longer article names. The elements are equally chemical and physical, so I don't think this is a nice prefix. Electrical elements would probably be included in a different module I can imagine as the more for designing devices then pure scientific data, isn't it. Even in Wikipedia it says _periodic table of the (chemical) elements_ https://en.wikipedia.org/wiki/Periodic_table, where _chemical_ is in brackets...

2022-05-30 10:14 UTC, Shinigami92 requested changes

2022-05-30 10:14 UTC, Shinigami92 commented on src/modules/science/index.ts
> +};
```suggestion
export interface Element {
  name: string;
  symbol: string;
};
```

2022-05-30 10:14 UTC, Shinigami92 commented on src/modules/science/index.ts
> +};
```suggestion
export interface Unit {
  long: string;
  short: string;
};
```

2022-05-30 10:16 UTC, Shinigami92 requested changes
Remember to re-export the interfaces ChemicalElement and Unit in `src/index.ts`

2022-05-30 15:20 UTC, import-brain commented on src/locales/en/science/unit.ts
> +    short: 'Ω',
If we rename `short` to `symbol`, should we rename `long` to `full` or `name`?

2022-05-30 15:27 UTC, Shinigami92 commented on src/locales/en/science/unit.ts
> +    short: 'Ω',
yes (😉 => _not sure whether `full` or `name`_)

2022-05-30 15:29 UTC, Shinigami92 requested changes

2022-05-30 15:29 UTC, Shinigami92 commented on src/modules/science/index.ts
> +    return this.faker.definitions.science.unit[index];
pls use `arrayElement` for such things

2022-05-30 15:29 UTC, Shinigami92 commented on test/science.spec.ts
> +          const name = faker.science.elementName();
tests need updates

2022-05-30 15:29 UTC, Shinigami92 commented on src/modules/science/index.ts
> +};
run `pnpm run format`

2022-05-30 15:44 UTC, Shinigami92 commented on src/modules/science/index.ts
> +};
`pnpm run clean && pnpm install && pnpm run format`

2022-05-30 16:18 UTC, pkuczynski commented on src/locales/en/science/unit.ts
> +    short: 'Ω',
I vote for `name`

2022-05-30 16:33 UTC, ST-DDT commented on src/locales/en/science/unit.ts
> +    short: 'Ω',
I also prefer `name`.

2022-05-30 16:34 UTC, Shinigami92 commented on src/modules/science/index.ts
> +};
is something broken with prettier?

2022-05-30 16:43 UTC, Shinigami92 commented on src/modules/science/index.ts
> +};
it's already solved :thinking:

2022-05-30 19:07 UTC, import-brain commented on src/locales/en/science/unit.ts
> +    short: 'Ω',
Okay, changing to `name`

2022-05-31 11:31 UTC, ST-DDT commented on src/modules/science/index.ts
> +}
Should we reuse the types in the definitions (or vice versa)?

2022-05-31 18:20 UTC, Shinigami92 commented on src/locales/en/science/chemicalElement.ts
> +    symbol: 'H',
Should we add a third field `atomicNumber`?

2022-05-31 19:00 UTC, ST-DDT requested changes

2022-05-31 19:02 UTC, import-brain commented on src/locales/en/science/chemicalElement.ts
> +    symbol: 'H',
Sure. Should the number be a string or an number type?

2022-05-31 23:11 UTC, ST-DDT approved these changes, later dismissed

2022-06-01 11:16 UTC, import-brain commented on src/locales/en/science/chemicalElement.ts
> +export default [
By "freeze", do you mean use `Object.freeze()`?

2022-06-01 11:29 UTC, ST-DDT commented on src/locales/en/science/chemicalElement.ts
> +export default [
Yes, so that unit().name = 123 doesnt do anything unexpected.

2022-06-01 11:31 UTC, Shinigami92 commented on src/locales/en/science/chemicalElement.ts
> +    symbol: 'H',
Mh... I think a number would fit here, or are there special cases?

2022-06-01 20:02 UTC, Shinigami92 approved these changes

2022-06-01 23:33 UTC, ST-DDT approved these changes

2022-06-05 05:35 UTC, pkuczynski approved these changes

2022-06-05 10:22 UTC, merged