docs: rework readme
faker-js/faker pull request #1017
Opened 2022-05-28 12:45 UTC by Shinigami92

2022-05-28 13:52 UTC, ST-DDT submitted a review, later dismissed

2022-05-28 13:54 UTC, import-brain approved these changes, later dismissed

2022-06-04 22:18 UTC, xDivisionByZerox commented on CONTRIBUTING.md
> +```shell
Maybe some words what framework we use for testing (like line 26) or why we think tests are important.

2022-06-04 23:13 UTC, prisis commented on README.md
Can we add algolia, they Sponsoring our search

2022-06-05 05:59 UTC, pkuczynski commented on CONTRIBUTING.md
> +```shell
For me it would be more important to mention that you always have to run build when changing the code, as tests are run from built code, not from source, which was quite unusual for me...

I would not mention `install` as this seems to be quite obvious step.

2022-06-05 06:28 UTC, pkuczynski requested changes

2022-06-05 06:28 UTC, pkuczynski commented on CONTRIBUTING.md
> +# build the Faker dist
This should be mention as a text, and not inside the code example I think...

2022-06-05 06:28 UTC, pkuczynski commented on CONTRIBUTING.md
> +## Building and serving the docs statically
It would be nice to explain why this is needed and how this differ from the docs:dev

2022-06-05 06:28 UTC, pkuczynski commented on CONTRIBUTING.md
> +## Deploying Documentation
```suggestion
## Deploying documentation
```

2022-06-05 06:28 UTC, pkuczynski commented on README.md
> +## 🚀 Features
I don't think it's worth to mention specific features. They keep changing, we are constantly adding new stuff. This list will get outdated quite quickly. And even now it does not cover everything.

It would be better to mention philosophy behind faker, that we try to generate sensible, realistic data when possible, we offer localization in many languages and ability to pin the generated by setting seed value - I didn't know about this feature until I started to work on faker.

2022-06-05 06:28 UTC, pkuczynski commented on README.md
> +## 📦 Install
Those icons look childish, do not bring value and are hard to provide for every section. I wouldn't add them...

2022-06-05 06:28 UTC, pkuczynski commented on README.md
> +export function createRandomUser(): User {
Why not using arrow function here too?

2022-06-05 06:28 UTC, pkuczynski commented on README.md
> +Array.from({ length: 10 }).forEach(() => {
`Array.from({ length: 10 }, createRandomUser)`

Would be shorter...

2022-06-05 06:28 UTC, pkuczynski commented on README.md
> +// import { faker } from '@faker-js/faker/locale/de';
We have a separate section about localization so I would not leave this comment here...

2022-06-05 06:28 UTC, pkuczynski commented on README.md
> +## Modules
I would drop this whole section. In favor of something like "Check documentation for complete list of data you can generate"

2022-06-05 06:28 UTC, pkuczynski commented on README.md
>  ### faker.fake()
Name it "Templates"?

2022-06-05 06:31 UTC, pkuczynski requested changes

2022-06-05 06:31 UTC, pkuczynski commented on CONTRIBUTING.md
> +The website is kindly hosted for free by the Netlify team under their Open Source plan. See the [netlify.toml](netlify.toml) for configuration.
This is already mentioned on the main Readme so is this worth the repetition? It's not connected with contribution to the project, right?

**localisation**

I would add new section documenting how to add a new locale. People ask about it. See https://discord.com/channels/929487054990110771/929544823109742593/981252262515060817

2022-06-05 06:37 UTC, pkuczynski requested changes

2022-06-05 06:37 UTC, pkuczynski commented on README.md
> +```ts
We should mention that user needs to load the locale first. Correct?

2022-06-05 06:37 UTC, pkuczynski commented on README.md
>  See our documentation for a list of [provided languages](https://fakerjs.dev/api/localization.html#localization)
Should we also mention that not all locales provide data for every method and then we fallback to English (do we?)? And also encourage users to provide PR with locale data pointing them to dedicated section in the contributing guide.

2022-06-05 09:16 UTC, ST-DDT commented on README.md
> +## 🚀 Features
I think we should keep the feature list, as it easier to understand than our philosphy. Kind of a TLDR.

We should still explain our philosophy though as it provides deeper insides into what we might consider to be a part of faker.

2022-06-05 09:19 UTC, ST-DDT commented on README.md
> +- 🔢 Numbers - Of course, we can also generate random numbers and strings.
I think we should also add 
`- 🧍 Names - Generate virtual humans with a complete online and offline identity`

2022-06-05 09:26 UTC, ST-DDT commented on README.md
> +## 📦 Install
IMO they loosen the atmosphere and highlight the different sections very distictively.
In presentations, you also have images on your slides to retain the viewers attention.

We should do it consistently for all headlines though (All or none).

2022-06-05 09:32 UTC, ST-DDT commented on README.md
> +// import { faker } from '@faker-js/faker/locale/de';
IMO most users don't read that far:
- They will read whether it suits they needs.
- Then they will check how to use it
- Then they will explore the API from within their IDE or search for specific terms

So if we plant this knowledge in their minds early on they at least notice, that there are more ways to do things.
I would potentially include a `// faker.locale = 'en'` as well.

2022-06-05 09:37 UTC, ST-DDT commented on README.md
>  See our documentation for a list of [provided languages](https://fakerjs.dev/api/localization.html#localization)
> Should we also mention that not all locales provide data for every method and then we fallback to English (do we?)?

Yes, and yes for now.

> And also encourage users to provide PR with locale data pointing them to dedicated section in the contributing guide.

Yes, but I would like to also have a section like build your own locale dynamically/indepently.
Althoug we would have to rewrite it soon.

2022-06-05 10:14 UTC, pkuczynski commented on README.md
> +## 🚀 Features
If we would mention earlier that faker is localized i to X languages, if they need it, they will seek it. TOC at the top would also build some expectations.

Leaving commented code looks like someone forgot to remove it...

2022-06-05 10:14 UTC, pkuczynski requested changes

2022-06-05 10:14 UTC, pkuczynski commented on README.md
Add TOC here

2022-06-05 11:16 UTC, Shinigami92 commented on README.md
> +## 📦 Install
I tried to find icons for now for all first lvl headlines
Please check them out and check if the fit

2022-06-05 11:18 UTC, Shinigami92 commented on README.md
> +export function createRandomUser(): User {
This is my personal style I always use in projects :thinking: 
I never export arrow functions but only real functions.

Do you have any reason why I should change that?

2022-06-05 11:20 UTC, Shinigami92 commented on README.md
> +Array.from({ length: 10 }).forEach(() => {
This would not push the users into the `USERS` array.
Also it could be that something inside the function accesses the `USERS` array, and that's why I don't create first all at once and then push them all at once into the array.

2022-06-05 11:23 UTC, Shinigami92 commented on README.md
> +// import { faker } from '@faker-js/faker/locale/de';
If we mention more like `faker.locale = 'en'` we may also need to mention `seed` :thinking: 
But that way the usage would get longer and longer :confused:

2022-06-05 11:26 UTC, Shinigami92 commented on README.md
> +## Modules
I would like to drop this section a bit later after:
1. we finished the whole migration to VitePress v1 final (currently it's still in alpha) (#993)
2. then create a site that is searchable like https://vuejs.org/api/

2022-06-05 11:45 UTC, Shinigami92 commented on README.md
> +- 🔢 Numbers - Of course, we can also generate random numbers and strings.
Will add this as suggested for now, but I really want to switch that to `person` in the future (rename the module).

2022-06-05 11:48 UTC, Shinigami92 commented on README.md
Did you know that GitHub as an auto-toc?
<img src="https://user-images.githubusercontent.com/7195563/172048998-99283c39-4667-4122-8f79-68a588de5e8c.png" width="300px"/>

IMO we don't need a toc

2022-06-05 11:52 UTC, Shinigami92 commented on CONTRIBUTING.md
> +After you have updated the locale definitions, you need to run `pnpm run generate:locales` to generate/update the related files.
@ST-DDT please check this section and provide suggestion or even update this yourself as you have access to the branch :slightly_smiling_face:

2022-06-05 11:52 UTC, Shinigami92 commented on README.md
> +```ts
:eyes: You somewhat got a point here, but instead of documenting that, we should throw a warning or even an error that the requested locale cannot be switched to due to it was forgotten to get loaded :thinking: 
This should be it's own PR

2022-06-05 13:36 UTC, ST-DDT commented on CONTRIBUTING.md
> +After you have updated the locale definitions, you need to run `pnpm run generate:locales` to generate/update the related files.
```suggestion
After adding new or updating existing locale data, you need to run `pnpm run generate:locales` to generate/update the related files.
```

2022-06-05 13:36 UTC, ST-DDT commented on README.md
> +```ts
Since we are about to remove the current way of setting locaes, there is no need to mention it now.

2022-06-05 13:36 UTC, ST-DDT commented on README.md
> +## 💵 Sponsors
Maybe?

```suggestion
## 🤝 Sponsors
```

2022-06-06 08:33 UTC, pkuczynski commented on README.md
> +## 📦 Install
I dont like those icons, so I will just remain silent...

2022-06-06 08:40 UTC, pkuczynski commented on README.md
> +export function createRandomUser(): User {
We should give example on faker usage, and not how to make a module. Those exports are not really needed as they are irrelevant to the faker. I prefer the minimalistic approach.

Btw. why do you choose to export function over arrow? In all my projects always use arrow and have not really seen people using old plain `function`...

2022-06-06 08:42 UTC, pkuczynski commented on README.md
> +Array.from({ length: 10 }).forEach(() => {
It would. Have a look at this example: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#using_arrow_functions_and_array.from - you provide options and mapper.

2022-06-06 08:43 UTC, pkuczynski commented on README.md
> +// import { faker } from '@faker-js/faker/locale/de';
That's why I think TOC and simple short examples targeting the section subject are better.

2022-06-06 08:45 UTC, pkuczynski commented on README.md
> +## Modules
But we already have the documentation at https://fakerjs.dev/api/company.html, which is already better than readme and more "auto-updated" with the code...

2022-06-06 08:47 UTC, pkuczynski commented on README.md
I know, but it's not that visible to the user, I think.

2022-06-06 08:54 UTC, pkuczynski requested changes

2022-06-06 08:54 UTC, pkuczynski commented on README.md
> +```ts
We should show the user a working example, and not something which throws a warning...

2022-06-06 08:54 UTC, pkuczynski commented on README.md
>  Faker is an MIT-licensed open source project with its ongoing development made possible entirely by the support of these awesome backers
```suggestion
Faker is an open source project with its ongoing development made possible entirely by the support of these awesome backers
```

2022-06-06 10:11 UTC, import-brain commented on CONTRIBUTING.md
> +Before you can run the tests, you need to install all dependencies and also need to build the project, because some tests depend on the bundled content.
```suggestion
Before you can run the tests, you need to install all dependencies and build the project, because some tests depend on the bundled content.
```

2022-06-06 10:11 UTC, import-brain commented on CONTRIBUTING.md
> +You can view a code coverage report generated in `coverage/index.html`.
```suggestion
You can view a generated code coverage report at `coverage/index.html`.
```

2022-06-06 10:13 UTC, Shinigami92 commented on README.md
>  Faker is an MIT-licensed open source project with its ongoing development made possible entirely by the support of these awesome backers
I'm missing the **why** here, but if another maintainer is okay with removing this, I will apply the suggestion

2022-06-06 10:22 UTC, Shinigami92 commented on README.md
> +export function createRandomUser(): User {
You may have misinterpreted something here :thinking: 
This is not a module but a function that generates an object e.g. for a database tuple.

---

I normally write TypeScript code all the day and the code is shorter when using a function.
I'm also not fully sure, but I think when using `function` it will be correctly named in debug or source maps, where as an arrow-function is anonymous.
Other projects like VueUse also use the same kind of exported function.
I only use arrow functions for lambda syntax like in a Array.map function or when I really need to prevent a collision with `this` keyword. But in most cases when I externalize a function, it doesn't depend on the `this` keyword.

2022-06-06 10:25 UTC, Shinigami92 commented on README.md
> +Array.from({ length: 10 }).forEach(() => {
Yes, I use this myself, but only when I need to return an Array.
In this case, I use a terminating `forEach` which doesn't return an Array but void.

2022-06-06 10:28 UTC, Shinigami92 commented on README.md
> +// import { faker } from '@faker-js/faker/locale/de';
> Re-reviewing it now again and it really looks weird that we keep this commented line...

Please suggest something that explains that it's also possible to use our pre-made locale faker instances which results in much smaller bundle size.
This line is somewhat important for us to be mentioned such high in the readme as we answer many times that this is possible. In GitHub Discussions and in Discord we get asked again and again and in 99% this was the solution.

2022-06-06 11:57 UTC, pkuczynski commented on README.md
> +export function createRandomUser(): User {
Well, if it's a plain function as an example, no need to export. If you export, it becomes a module :) And I agree it should be just a plain function, that's why I am suggesting removing all those exports.

Not sure what do you mean by shorter as arrow functions are much shorter:

```js
export function createRandomUser(): User {
  return {
     userId: faker.datatype.uuid(),
     ...
   };
 }
 ```

vs

```js
export const createRandomUser = (): User => ({
     userId: faker.datatype.uuid(),
     ...
})
```

Not sure about `Vue` not using it. React (and many other libraries) use arrow functions everywhere. I use them everywhere, hardly every use old plan `function`.

2022-06-06 11:59 UTC, pkuczynski commented on README.md
> +Array.from({ length: 10 }).forEach(() => {
I know, but instead of writing this like you did:

```ts
export const USERS: User[] = [];

Array.from({ length: 10 }).forEach(() => {
  USERS.push(createRandomUser());
 });
```

this can be shortened to:

```ts
export const USERS: User[] = Array.from({ length: 10 }, createRandomUser)
```

Isn't that nicer? (Although I would drop `export`)

2022-06-06 12:04 UTC, pkuczynski commented on README.md
> +// import { faker } from '@faker-js/faker/locale/de';
I would remove the commented code and add new subsection to usage:

```ms
### Optimizing size

By default faker loads all locales. If you only use few of them or care about the size of your bundle, you should rather use single-locale instances:

```ts
import { faker } from '@faker-js/faker/locale/de';

faker.street.name() // ...
```

or for multiple locale usage:

```ts
import { faker as en } from '@faker-js/faker/locale/en';
import { faker as de } from '@faker-js/faker/locale/de';

const faker = { en, de }

faker.en.street.name() // ...
faker.de.street.name() // ...
```
```

(code examples from top of my head, but you get the drill)

2022-06-06 12:06 UTC, pkuczynski commented on README.md
>  Faker is an MIT-licensed open source project with its ongoing development made possible entirely by the support of these awesome backers
You think adding licence type creates this *why*?

2022-06-06 12:36 UTC, Shinigami92 commented on README.md
> +export function createRandomUser(): User {
I think we can agree here that this is opinionated and doesn't serve anymore any valuable stuff to the context itself. I will mark this as resolved now, let's move on.

2022-06-06 12:37 UTC, Shinigami92 commented on README.md
> +Array.from({ length: 10 }).forEach(() => {
https://github.com/faker-js/faker/pull/1017#discussion_r889681341

2022-06-06 12:46 UTC, Shinigami92 commented on README.md
>  Faker is an MIT-licensed open source project with its ongoing development made possible entirely by the support of these awesome backers
I mean why removing this. Please provide a reason why removing this info is valuable for this sentence.
It tells the valuable info that it is licensed under MIT license within the sponsor/contribution section.

2022-06-06 14:01 UTC, pkuczynski commented on README.md
> +export function createRandomUser(): User {
The value in my proposal was to keep things simple to focus on the faker example. No exports, shortest code. You argue into "this is my personal style and I want to keep it". There are no arguments to why your personal style is better. Exposing personal style does not sound like a good open source cooperative atmosphere... You didn't even let other maintenances raise their voice...

2022-06-06 15:02 UTC, pkuczynski approved these changes

2022-06-06 19:05 UTC, Shinigami92 commented on README.md
>  Faker is an MIT-licensed open source project with its ongoing development made possible entirely by the support of these awesome backers
_resolve to allow merge, we could improve in another PR_

2022-06-06 19:05 UTC, Shinigami92 commented on README.md
> +## Modules
_resolve to allow merge, we could improve in another PR_

2022-06-06 19:05 UTC, Shinigami92 commented on README.md
> +// import { faker } from '@faker-js/faker/locale/de';
_resolve to allow merge, we could improve in another PR_

2022-06-06 19:06 UTC, prisis approved these changes

2022-06-06 19:07 UTC, merged