feat: migrate word
faker-js/faker pull request #102
Opened 2022-01-12 15:32 UTC by MohdImran001

Part of #72.
Test with `npm run build && npx mocha test/word.unit.js`

2022-01-13 07:38 UTC, Shinigami92 requested changes

2022-01-13 07:38 UTC, Shinigami92 commented on src/word.ts
> +   * @param {number} [length] - optional length of word to return
Please remove the JSDoc types

like 
```suggestion
   * @param optional length of word to return
```

any many more below

2022-01-13 07:38 UTC, Shinigami92 commented on src/word.ts
> +      wordList = this.faker.definitions.word.adjective.filter(function (
convert to arrow functions to not mess with `this`

2022-01-13 09:38 UTC, MohdImran001 commented on src/word.ts
> +      wordList = this.faker.definitions.word.adjective.filter(function (
are you talking about `filter` function ?

2022-01-13 11:23 UTC, Shinigami92 commented on src/word.ts
> +      wordList = this.faker.definitions.word.adjective.filter(function (
yes :)

2022-01-13 21:33 UTC, prisis approved these changes

2022-01-14 16:18 UTC, Shinigami92 approved these changes

2022-01-14 16:18 UTC, merged