feat: add en_JP locale
faker-js/faker pull request #1026
Opened 2022-05-31 18:12 UTC by revmischa

Not sure if I did this correctly

Added the amazing Japanese interpretations of American-sounding names from https://docs.google.com/spreadsheets/d/1KOP4mNAX5R0N_dODE6j2gHTK2oTXCIrhAQ0dEniaYFw/edit#gid=0

![image](https://user-images.githubusercontent.com/245131/171256180-ca1b1d4f-3416-49bc-8b96-a2a3319f53e2.png)

2022-05-31 18:44 UTC, ST-DDT commented on src/locales/en_JP/index.ts
> +  title: 'English Names - 1994 Fighting Baseball (SNES) Japan Full Rosters',
I'm not sure about this name.
Maybe `English (Japanese)`?

2022-05-31 18:47 UTC, ST-DDT commented on src/locales/en_JP/name/first_name.ts
> +  'Derrick',
Are these "westernized" versions of Japanese names?

2022-05-31 18:56 UTC, revmischa commented on src/locales/en_JP/index.ts
> +  title: 'English Names - 1994 Fighting Baseball (SNES) Japan Full Rosters',
As you wish, but it's just from this one source..

2022-05-31 18:57 UTC, revmischa commented on src/locale/en_JP.ts
> +export = faker;
No I had an old fork, let me export it properly

2022-05-31 18:59 UTC, revmischa commented on src/locales/en_JP/name/first_name.ts
> +  'Derrick',
https://www.reddit.com/r/baseball/comments/8klxnf/the_full_fighting_baseball_snes_rosters_more_than/

2022-05-31 19:01 UTC, Shinigami92 commented on src/locales/en_JP/index.ts
> +  title: 'English Names - 1994 Fighting Baseball (SNES) Japan Full Rosters',
Yeah, but maybe... just maybe, someone in the future would like to add something else to the en_JP set and they definitely will not think about this `title` field :wink: 
All out other locales have this not-written-down convention :thinking: 
Something in me tend more to `English (Japanese)`

2022-05-31 21:31 UTC, ST-DDT requested changes

2022-05-31 21:31 UTC, ST-DDT commented on src/locales/en_JP/name/index.ts
> +} as Partial<NameDefinitions>;
Please run `pnpm run generate:locales` again.

2022-05-31 21:31 UTC, ST-DDT commented on src/locales/en_JP/index.ts
> +  title: 'English Names (Japan)',
```suggestion
  title: 'English (Japan)',
```

@Shinigami92 What do you think?

2022-05-31 21:57 UTC, revmischa commented on src/locales/en_JP/name/index.ts
> +} as Partial<NameDefinitions>;
ok done

2022-05-31 23:04 UTC, ST-DDT commented
Blocked by #1027 and I cannot push the fix directly to this branch.

2022-05-31 23:38 UTC, revmischa commented
> Blocked by #1027 as I cannot push the fix directly to this branch.

I rebased and regenerated

2022-06-09 13:55 UTC, Shinigami92 commented on src/locales/en_JP/index.ts
> +  title: 'English Names (Japan)',
```suggestion
  title: 'English (Japan)',
```

2022-06-09 13:58 UTC, Shinigami92 commented
@revmischa Please use `English (Japan)` instead of `English Names (Japan)` because we use the same of e.g. `English (Ghana)` or `English (India)`
I cannot apply suggestions on your PR, you may have set your branch to not allow maintainers edit

2022-06-09 18:30 UTC, ST-DDT reviewed
Let me ask a few more questions regarding how the westernized names work in Japanese.

Is the list you provided (a subset of) a defined list of allowed names that Japanese people can use or is this just a fun/famous list of names in a Japanese context?

2022-06-09 18:32 UTC, revmischa commented
> Let me ask a few more questions regarding how the westernized names work in Japanese.
> 
> Is the list you provided (a subset of) a defined list of allowed names that Japanese people can use or is this just a fun/famous list of names in a Japanese context?

The latter. I know of no "allowed list" that exists

2022-06-09 18:53 UTC, Shinigami92 commented
> The latter. I know of no "allowed list" that exists

In that case, please explain deeply why this is worthfull to be included in Faker. Do you need it for your own app?
Is this needed by others not just your app? Otherwise you also could just use `faker.helpers.arrayElement(yourNameArray)` :thinking:

2022-06-09 19:17 UTC, revmischa commented
> > The latter. I know of no "allowed list" that exists
> 
> In that case, please explain deeply why this is worthfull to be included in Faker. Do you need it for your own app? Is this needed by others not just your app? Otherwise you also could just use `faker.helpers.arrayElement(yourNameArray)` 🤔

Because it produces amusing names. Others will enjoy and appreciate it. Same reason we have en_BORK.  https://github.com/faker-js/faker/blob/main/src/locales/en_BORK/lorem/words.ts

2022-06-09 20:35 UTC, xDivisionByZerox commented
The problem with intruducing locales is: They are hard to maintain (like really hard). If you introduce this new locale we have to support this best case all features we have. This does not only include names but any module (like interent, finance, etc). If you would currently load an instance of your locale most faker methods would fail (or fall back to english). 

Thats why we have to be very thoughtfull about introducing new locales. 

For existing locales its a bit harder (like en_BORK). They are already out in the wild, we need to keep supporting them unless we drop them. But that would require us to make major releases with not much impact.

Hope that clearyfication helps.

2022-06-09 23:14 UTC, kid-icarus commented on src/locales/en_JP/name/first_name.ts
> +  'Bobby',
There are many duplicate entries here which is very wasteful and bandwidth intensive. Just search for 'Bob' or 'Bobby'.

2022-06-09 23:17 UTC, ST-DDT commented
Some statistics for future reference:
From the firstnames 190 out of 310 are also present in `en`, the remaining 120 names mostly only differ in the spelling of the name.
The lastname look like mutated original names.

These names might be funny when matching first and last names are returned because you can guess the original player name. However randomly shuffled together, they are just random names.
If you think the missing first names are important, then we can consider adding them directly to `en`
For the last names, I'm not sure as I'm not sure whether these are/feel like English last names (I'm probably not the best one to judge that).

2022-06-09 23:42 UTC, kid-icarus commented on src/locales/en_JP/name/first_name.ts
> +  'Bobby',
Specifically, there are 118 duplicate first names, and 30 duplicate laste names.

2022-06-10 00:18 UTC, kid-icarus commented
> These names might be funny when matching first and last names are returned because you can guess the original player name. However randomly shuffled together, they are just random names. If you think the missing first names are important, then we can consider adding them directly to `en` For the last names, I'm not sure whether these are/feel like English last names (I'm probably not the best one to judge that).

As an english speaker I can confirm these are English-sounding last names.

2022-06-14 03:29 UTC, revmischa commented
I think random names are fine. I could remove the duplicates.

2022-08-05 13:12 UTC, ST-DDT commented
I'm closing this as the additional maintenance efforts outweighs the benefits/fun.

2022-08-05 13:12 UTC, closed without merging