feat: :sparkles: rewrite name module in typescript
faker-js/faker pull request #103
Opened 2022-01-12 15:47 UTC by MohdImran001

Part of #72. @Shinigami92 Please review.

2022-01-12 15:50 UTC, Shinigami92 requested changes

2022-01-12 15:50 UTC, Shinigami92 commented on src/name.ts
> +   * @param {mixed} gender
Please remove the param JSDoc types

2022-01-12 15:52 UTC, Shinigami92 commented on src/name.ts
> +          //Fall back to non-gendered names if they exist and gender wasn't specified
Would be cool if we already format a bit such comments

```suggestion
          // Fall back to non-gendered names if they exist and gender wasn't specified
```

2022-01-12 15:52 UTC, Shinigami92 commented on src/name.ts
> +    firstName = firstName || this.faker.name.firstName(gender);
I already improved such code with `||=` in the other PRs

2022-01-12 15:54 UTC, MohdImran001 commented on src/name.ts
> +   * @param {mixed} gender
we should keep only `@method faker.name.firstName` right?

2022-01-12 15:55 UTC, Shinigami92 commented on src/name.ts
> +   * @param {mixed} gender
param is actually okay, we can add doc messages/descriptions later

2022-01-13 11:26 UTC, Shinigami92 commented on src/name.ts
> +   * @param  gender
```suggestion
   * @param gender
```

2022-01-13 11:26 UTC, Shinigami92 commented on src/name.ts
> +    lastName ||= lastName || this.faker.name.lastName(gender);
```suggestion
    lastName ||= this.faker.name.lastName(gender);
```

2022-01-13 11:29 UTC, Shinigami92 approved these changes

2022-01-13 20:33 UTC, prisis approved these changes

2022-01-13 21:26 UTC, prisis commented on src/name.ts
> +    switch (r) {
Just a note, this should be later transformed to a if

2022-01-13 21:26 UTC, prisis approved these changes

2022-01-14 16:01 UTC, merged