chore: remove unused const in unsplash.ts
faker-js/faker pull request #1046
Opened 2022-06-09 14:38 UTC by import-brain

This is a todo on "source code todo list v2"

2022-06-09 14:45 UTC, Shinigami92 commented on src/modules/image/providers/unsplash.ts
> -  categories = [
This could be used like `faker.image.unsplash.categories`, but I assume no one in the world does this :thinking:

2022-06-09 14:47 UTC, xDivisionByZerox commented on src/modules/image/providers/unsplash.ts
> -  categories = [
Even if, this isn't any kind of data you would relate with faker. So a removal should be fine. 

Still a breaking change.

2022-06-09 23:30 UTC, ST-DDT commented on src/modules/image/providers/unsplash.ts
> -  categories = [
This could potentially be used for: https://github.com/faker-js/faker/blob/3f49ac1e38263064372fc1970d08f23e00cd580b/src/modules/image/providers/unsplash.ts#L40-L45

So we should follow the normal deprecation procedure.

2022-06-10 13:06 UTC, import-brain commented on src/modules/image/providers/unsplash.ts
> -  categories = [
Do you want the const itself to be somehow deprecated, or do you want the parameter to be deprecated?

2022-06-10 21:15 UTC, xDivisionByZerox commented on src/modules/image/providers/unsplash.ts
> -  categories = [
> This could potentially be used for:
> 
> https://github.com/faker-js/faker/blob/3f49ac1e38263064372fc1970d08f23e00cd580b/src/modules/image/providers/unsplash.ts#L40-L45
> 
> So we should follow the normal deprecation procedure.

In this case, the `imageUrl()` `category` parameter should be made more strict with a `TemplateLiteral<currentCategoryConst>`

2022-06-10 21:28 UTC, ST-DDT commented on src/modules/image/providers/unsplash.ts
> -  categories = [
> In this case, the `imageUrl()` `category` parameter should be made more strict with a `TemplateLiteral<currentCategoryConst>`

The category is an external thing, so I don't know how feasible this is.
If there is a limited set of values that are supported, then we could use them.

> The parameter is fine IMO.

Yes

> Do you want the const itself to somehow be deprecated


Replace the field with a getter that is deprecated.

2022-06-11 02:03 UTC, import-brain commented on src/modules/image/providers/unsplash.ts
> -  categories = [
https://github.com/faker-js/faker/pull/1046/commits/94e655dd9ef3abf4952a6e96b10a5e6acab7f44a#diff-cca52b6b29e5adca3e58806e1cfcf625710fc61b723a23ad8b86468880869f7fR18-R37

You mean like this?

2022-06-11 10:21 UTC, xDivisionByZerox commented on src/modules/image/providers/unsplash.ts
> +  category(): Category {
The `get` keyword is missing. See [typescript getter/setter].(https://www.typescriptlang.org/docs/handbook/2/classes.html#getters--setters)

Otherwise, you would convert the field/property to a callable function and thus have a breaking change.

2022-06-11 10:25 UTC, xDivisionByZerox commented on src/modules/image/providers/unsplash.ts
> -  categories = [
No, you just removed the current field and return ONE element instead of the entire array. This is a breaking behavior. We still need to support the current syntax (`faker..image.unsplash.categories`). For your (now function) you would need to call `faker.image.unsplash.category()`. You have provided a new feature, not a rework.

2022-06-11 11:10 UTC, import-brain commented on src/modules/image/providers/unsplash.ts
> -  categories = [
Ohhhh, now I see what you mean, sorry for the confusion. I'll change it.

2022-06-11 23:19 UTC, xDivisionByZerox commented on src/modules/image/providers/unsplash.ts
> +    return ['food', 'nature', 'people', 'technology', 'objects', 'buildings'];
Still needs the deprecation log by calling the internal `deprecated()` method.

2022-06-12 05:38 UTC, import-brain commented
@xDivisionByZerox Would you prefer I write a test case for the deprecation log, or is it fine in this case?

2022-06-12 07:46 UTC, xDivisionByZerox commented
Normally our procedure when deprecating something consists of 3 steps:
1. Use the internal `deprecated` function
2. Add a `@deprecated` JSDoc parameter
3. Add a test case that ensures that the deprecation log is being printed to the console

So I guess to be exact a test would be required, if you don't mind.

2022-06-12 13:23 UTC, import-brain commented
> Normally our procedure when deprecating something consists of 3 steps:
> 
> 1. Use the internal `deprecated` function
> 2. Add a `@deprecated` JSDoc parameter
> 3. Add a test case that ensures that the deprecation log is being printed to the console
> 
> So I guess to be exact a test would be required, if you don't mind.

Sure, I'll get on it :)

2022-06-12 14:53 UTC, xDivisionByZerox submitted a review, later dismissed

2022-06-12 15:36 UTC, ST-DDT submitted a review, later dismissed

2022-06-12 19:47 UTC, Shinigami92 requested changes

2022-06-12 19:47 UTC, Shinigami92 commented on src/modules/image/providers/unsplash.ts
> +      since: 'v7.2.0',
```suggestion
      since: 'v7.3.0',
```

2022-06-13 19:37 UTC, ST-DDT submitted a review, later dismissed

2022-06-14 08:05 UTC, Shinigami92 submitted a review, later dismissed

2022-06-14 08:05 UTC, Shinigami92 commented on test/image.spec.ts
> +    describe('categories', () => {
We discussed in several other PRs that we don't need these deprecation tests anymore
So we should revert this test file

2022-06-14 19:06 UTC, ST-DDT approved these changes

2022-06-16 21:09 UTC, xDivisionByZerox approved these changes

2022-06-17 07:16 UTC, merged