feat: mime-db as optional peer dependency
faker-js/faker pull request #1048
Opened 2022-06-09 18:49 UTC by Shinigami92

2022-06-09 18:55 UTC, xDivisionByZerox commented on src/modules/system/index.ts
> +          .catch((error) => {
If we catch here we shouldn't need a try-catch block around this.

2022-06-09 19:00 UTC, xDivisionByZerox commented on src/modules/system/index.ts
>      return this.faker.helpers.arrayElement(mimeTypeKeys);
```suggestion
    return this.faker.helpers.objectKey(mimeTypes);
```

2022-06-09 19:09 UTC, xDivisionByZerox commented on src/modules/system/index.ts
> +      return this.faker.helpers.arrayElement(mimeTypes[mimeType].extensions);
Not this PR, but this can potentially return `undefined`.

2022-06-09 19:19 UTC, Shinigami92 commented
At least for the esm version, this doesn't seem to work at all :eyes: 

![Screenshot_20220609_211734](https://user-images.githubusercontent.com/7195563/172926802-9a9abb46-c69c-428f-90c9-ea10a1c000d8.jpg)

The file gets just embedded into the dist :eyes: :shrug:

2022-06-09 19:19 UTC, Shinigami92 commented on src/modules/system/index.ts
> +          .catch((error) => {
I'm testing... this is a draft PR

2022-06-09 20:10 UTC, ST-DDT requested changes

2022-06-09 20:10 UTC, ST-DDT commented on src/modules/system/index.ts
> +        console.warn(error);
Could we use like 10 common mime types as default? If the db is absent, so that at least the file extension work without the entire lib?

2022-06-09 20:39 UTC, xDivisionByZerox commented on src/modules/system/index.ts
> +        console.warn(error);
That was exactly the proposal in the [poll](https://github.com/faker-js/faker/discussions/1009) we made.

2022-06-10 21:34 UTC, ST-DDT commented
> I have a new idea 🤔
> We could try to allow the user to pass mime-db object to faker.system from outside.

I will only allow this if we treat it as locale data. 
I don't want multiple ways to provide user-specific/custom data to faker (asside from method params).
The one and only way should be locale data.

2022-06-11 12:03 UTC, Shinigami92 commented
I hoped for an easy solution that could also deliver a good DX.
I put to much work from my side to tackle this task and in the end, I don't use this functionality for my own projects.
Therefore if someone else need this, want to provide a better DX and reduce the bundle size by solving this, feel free to tackle this issue and earn credits for that.

2022-06-11 12:03 UTC, closed without merging