refactor(unsplash.avatar): deprecate
faker-js/faker pull request #1062
Opened 2022-06-11 23:09 UTC by xDivisionByZerox

Is listed in #1044.

This PR deprecates `faker.image.unsplash.avatar()`  by m,making the following changes:
- use internal `deprecated()` function
- adding the `@deprecated` JSDoc parameter 
- adding a test case for the deprecation log

2022-06-11 23:09 UTC, xDivisionByZerox commented
Is this a `refactor` or `chore`?

2022-06-11 23:18 UTC, import-brain commented
> Is this a `refactor` or `chore`?

Most of the previously merged deprecation PRs have been `chore`, so I'm leaning towards that.

2022-06-12 08:57 UTC, ST-DDT requested changes

2022-06-12 08:57 UTC, ST-DDT commented on src/modules/image/providers/unsplash.ts
> +   * @deprecated
Please add `@see faker.image.avatar`

2022-06-12 08:57 UTC, ST-DDT commented on src/modules/image/providers/unsplash.ts
> +      since: 'v7.2.0',
The next version would be 7.3.0.

2022-06-12 09:24 UTC, xDivisionByZerox commented on src/modules/image/providers/unsplash.ts
> +   * @deprecated
done dac19f3

2022-06-12 09:24 UTC, xDivisionByZerox commented on src/modules/image/providers/unsplash.ts
> +      since: 'v7.2.0',
done 23d9c4c

2022-06-12 11:52 UTC, xDivisionByZerox commented on src/modules/image/providers/unsplash.ts
> +      proposed: 'faker.image.avatar()',
I'm just seeing that the actual implementation is faker.internet, not faker.image... gonna fix this

2022-06-12 13:38 UTC, import-brain approved these changes

2022-06-12 15:40 UTC, ST-DDT approved these changes

2022-06-12 19:45 UTC, Shinigami92 commented on test/image.spec.ts
> +    describe('avatar()', () => {
@ST-DDT same question as in the other PR (test for deprecation message needed?)

2022-06-13 20:04 UTC, ST-DDT commented on test/image.spec.ts
> +    describe('avatar()', () => {
As mentioned in the other PR.
I consider the deprecation check covered by the generic `test-examples-and-deprecations` check, so the extra test is optional and I wouldn't add it myself.

2022-06-14 07:56 UTC, Shinigami92 requested changes

2022-06-14 07:56 UTC, Shinigami92 commented on test/image.spec.ts
> +    describe('avatar()', () => {
Yeah, let's revert this file as I would say we don't need to pollute our tests with that anymore

2022-06-14 09:39 UTC, xDivisionByZerox commented on test/image.spec.ts
> +    describe('avatar()', () => {
done 4b74651

2022-06-14 15:24 UTC, import-brain submitted a review, later dismissed

2022-06-14 15:45 UTC, Shinigami92 approved these changes

2022-06-14 19:35 UTC, ST-DDT commented on src/modules/image/providers/unsplash.ts
> +      until: 'v8.0.0',
```suggestion
      since: '7.3',
      until: '8.0',
```

Changed in preparation #1067 .

2022-06-14 19:36 UTC, ST-DDT approved these changes

2022-06-16 17:37 UTC, merged