refactor(phone): rename phoneNumber to number
faker-js/faker pull request #1063
Opened 2022-06-12 01:27 UTC by xDivisionByZerox

Listed as a todo in #1044.

This PR does the following things:
- move the implementation from `phone.phoneNumber()` into a new function called `phone.number()`
- deprecate `phone.phoneNumber()` via the internal deprecated method
- add a `@deprecated` JSDoc parameter to the `phone.phoneNumber()` signature documentation
- duplicates the test checks from `phoneNumber()` to `number()`
- add a test case for `phoneNumber()` deprecation log

2022-06-12 01:43 UTC, xDivisionByZerox commented
The ci is failing with an error I couldn't figure out. 
```
FAIL  test/scripts/apidoc/examplesAndDeprecations.spec.ts > examples and deprecations > Phone > number
AssertionError: expected "warn" to not be called at allexpected "warn" to not be called at all
Received: 
    1st warn call:
    Array [
❯test/scripts/apidoc/examplesAndDeprecations.spec.ts:107:26
      "[@faker-js/faker]: faker.phone.phoneNumber() is deprecated since v7.2.0 and will be removed in v8.0.0. Please use faker.phone.number() instead.",
    ]
105|       } else {
106|         for (const spy of consoleSpies) {
107|           expect(spy).not.toHaveBeenCalled();
   | ^
108|         }
109|       }
    2nd warn call:
    Array [
      "[@faker-js/faker]: faker.phone.phoneNumber() is deprecated since v7.2.0 and will be removed in v8.0.0. Please use faker.phone.number() instead.",
Test Files 1 failed | 32 passed (33)
    ]
    3rd warn call:
     Tests 2 failed | 37156 passed | 9 todo (37167)
    Array [
      "[@faker-js/faker]: faker.phone.phoneNumber() is deprecated since v7.2.0 and will be removed in v8.0.0. Please use faker.phone.number() instead.",
    ]
Number of calls: 3
```

The error states that `phone.number()` is logging to the console, but if you have a look at the message (and the source code) you can clearly see that `phone.phoneNumber()` is the one doing the log. 

What am I missing?

2022-06-12 15:15 UTC, ST-DDT requested changes

2022-06-12 15:15 UTC, ST-DDT commented on src/modules/phone/index.ts
> +   * @deprecated
Add `@see`

2022-06-12 15:17 UTC, ST-DDT requested changes

2022-06-12 15:17 UTC, ST-DDT commented on src/modules/phone/index.ts
> +      since: 'v7.2.0',
The next version is 7.3

2022-06-12 15:20 UTC, ST-DDT requested changes

2022-06-12 15:20 UTC, ST-DDT commented on src/modules/phone/index.ts
> +   * faker.phone.phoneNumber() // '961-770-7727'
You have to update the examples.

2022-06-12 15:55 UTC, xDivisionByZerox commented on src/modules/phone/index.ts
> +      since: 'v7.2.0',
done eaa71c0

2022-06-12 15:55 UTC, ST-DDT requested changes
Faker.fake still uses this method in the example.

2022-06-12 16:10 UTC, xDivisionByZerox commented
> Faker.fake still uses this method in the example.

I understand, I usually search with "Find All References" when replacing something. Obviously, these references do not get found.

2022-06-12 16:15 UTC, ST-DDT commented
> > Faker.fake still uses this method in the example.
> 
> I understand, I usually search with "Find All References" when replacing something. Obviously, these references do not get found.

Thats why the test is there 😉

2022-06-12 16:16 UTC, ST-DDT submitted a review, later dismissed

2022-06-12 16:19 UTC, xDivisionByZerox commented
> Thats why the test is there 😉

Yeah, but I was totally lost when looking at the error message since I wasn't able to find any (direct) call reference. We could potentially extend the message for these cases (faker.fake)? Not this PR tho.

2022-06-12 19:35 UTC, Shinigami92 commented on test/phone.spec.ts
> +        it('should log a deprecation message to the console', () => {
@ST-DDT correct me if I'm wrong, but I thought you wrote a test suite that automatically checks for these deprecations 🤔 
So I assume we don't need this test (?)

2022-06-12 19:58 UTC, xDivisionByZerox commented on test/phone.spec.ts
> +        it('should log a deprecation message to the console', () => {
I'm not aware of a dx feature like this. And last time I did a deprecation this kind of test was required. But yeah, wait for @ST-DDT to give some insights.

2022-06-12 20:18 UTC, ST-DDT commented on test/phone.spec.ts
> +        it('should log a deprecation message to the console', () => {
Yes, the deprecations and examples test that failed before contains the deprecation checks.
I consider the extra deprecation tests optional and wouldnt add them myself.

2022-06-12 20:32 UTC, xDivisionByZerox commented on test/phone.spec.ts
> +        it('should log a deprecation message to the console', () => {
Good to know :/

2022-06-16 18:51 UTC, Shinigami92 requested changes

2022-06-16 18:51 UTC, Shinigami92 commented on src/modules/phone/index.ts
> +      until: 'v8.0.0',
New schema `7.3` and `8.0`? Or was that a not yet merged PR 🤔

2022-06-16 18:51 UTC, Shinigami92 commented on test/phone.spec.ts
> +          expect(phoneNumber).toMatch(/\d/);
IMO this is not a good check, it could just contain one digit and it would be valid

2022-06-16 19:24 UTC, xDivisionByZerox commented on test/phone.spec.ts
> +          expect(phoneNumber).toMatch(/\d/);
Yes, I'm with you. But I don't see the responsibility to change this in this PR, since it only renames the `phone.number()` function and doesn't change any implementation logic.

2022-06-16 19:52 UTC, Shinigami92 approved these changes

2022-06-16 19:53 UTC, ST-DDT approved these changes

2022-06-16 19:53 UTC, merged