chore(lorempicsum.avatar): deprecate
faker-js/faker pull request #1065
Opened 2022-06-12 12:25 UTC by xDivisionByZerox

Listed as a todo in #1044.

This PR deprecates `faker.image.lorempicsum.avatar()` in favor of `faker.internet.avatar()`.

2022-06-12 12:49 UTC, xDivisionByZerox commented
The failing pipeline is due to some problem in the post-install script for `simple-git-hooks`. So not due to my implementation changes.

2022-06-12 13:48 UTC, import-brain commented on src/modules/image/providers/lorempicsum.ts
> +      proposed: 'this.faker.internet.avatar()',
Should `this` be here?

2022-06-12 14:00 UTC, xDivisionByZerox commented on src/modules/image/providers/lorempicsum.ts
> +      proposed: 'this.faker.internet.avatar()',
Yeah probably copied it from the implementation below. You are right.

2022-06-12 15:38 UTC, ST-DDT approved these changes

2022-06-13 00:24 UTC, import-brain submitted a review, later dismissed

2022-06-14 08:09 UTC, Shinigami92 requested changes

2022-06-14 08:09 UTC, Shinigami92 commented on test/image.spec.ts
> +      it('should log a deprecation message', () => {
Please revert this file, as we don't need these direct tests anymore

2022-06-14 09:37 UTC, xDivisionByZerox commented on test/image.spec.ts
> +      it('should log a deprecation message', () => {
done 9eeddb9

2022-06-14 15:25 UTC, import-brain approved these changes

2022-06-14 15:45 UTC, Shinigami92 submitted a review, later dismissed

2022-06-14 19:39 UTC, ST-DDT commented on src/modules/image/providers/lorempicsum.ts
> +      until: 'v8.0.0',
```suggestion
      since: '7.3',
      until: '8.0',
```

Changed in preparation of #1067 .

2022-06-14 19:43 UTC, Shinigami92 approved these changes

2022-06-16 17:24 UTC, Shinigami92 approved these changes

2022-06-16 17:30 UTC, merged