chore: Allow coordinate parameter to be [string, string] (#1044)
faker-js/faker pull request #1066
Opened 2022-06-12 19:40 UTC by samm459

Hello! This is my first contribution to this great repo 🙏. Hope it helps!

Opted for :
`coordinate?: [longitude: number | string, latitude: number | string]`
instead of this:
`coordinate?: [longitude: number, latitude: number] | [longitude: string, latitude: string]`

Made sense to me given my approach coerces both into numbers either way. Hopefully this is what you were looking for.

Thank you!

2022-06-13 15:36 UTC, xDivisionByZerox requested changes
Can you provide one extra test with mixed (`[number, string]`) parameters on the coordinate property? Just to ensure that nothing breaks during runtime.

2022-06-13 15:38 UTC, xDivisionByZerox commented
I changed the title to a `refactor`, hope you don't mind.

2022-06-13 18:49 UTC, samm459 reviewed
Thanks for the feedback! Added another loop to the current test which runs the assertions against all 4 possible type combinations. Does this solution work for you?

2022-06-13 19:31 UTC, ST-DDT submitted a review, later dismissed
Looks good to me. Thanks for your contribution!

2022-06-13 22:16 UTC, ST-DDT commented
We should discuss whether we want to support string coordinates:

See also: https://github.com/faker-js/faker/pull/1061#issuecomment-1154397273

2022-06-13 22:19 UTC, ST-DDT commented
Cross referencing related PRs: 
- https://github.com/faker-js/faker/pull/1066
- https://github.com/faker-js/faker/pull/1064
- https://github.com/faker-js/faker/pull/1061

2022-06-14 08:59 UTC, xDivisionByZerox approved these changes

2022-06-14 15:52 UTC, import-brain approved these changes

2022-06-23 16:27 UTC, xDivisionByZerox commented
@samm459 We had a team meeting today, where we discussed this PR. We came to the conclusion, that we currently don't feel responsible for providing a wide variety of input types. That means that the PR as-is will not be merged. In the #1044 you can see that this todo is updated to "will not fix".

But, this is your first PR in our project we want you to have a positive feeling of achievement.
Since the todo will no longer be fixed it needs to be removed from the code base. 
So would you be so kind and revert your changes and then push an additional commit where you remove the comment?

2022-06-23 16:31 UTC, xDivisionByZerox requested changes
@samm459 We had a team meeting today, where we discussed this PR. We came to the conclusion, that we currently don't feel responsible for providing a wide variety of input types. That means that the PR as-is will not be merged. In the https://github.com/faker-js/faker/issues/1044 you can see that this todo is updated to "will not fix".

But, this is your first PR in our project we want you to have a positive feeling of achievement.
Since the todo will no longer be fixed it needs to be removed from the code base.
So would you be so kind and revert your changes and then push an additional commit where you remove the comment?

2022-07-28 21:37 UTC, xDivisionByZerox commented
@samm459 are you still willing to update your PR? Just wanted to make sure, was just checking open PRs. 
You are allowed to take your time.

2022-08-05 13:26 UTC, ST-DDT commented
Superseded by #1234

2022-08-05 13:26 UTC, closed without merging