feat(system.fileName): file extension count
faker-js/faker pull request #1101
Opened 2022-06-22 12:39 UTC by xDivisionByZerox

Implementation is discussed in #395 ([direct comment ref](https://github.com/faker-js/faker/pull/395#discussion_r843866722)).

This is implemented in a non-breaking manner.

2022-06-22 14:16 UTC, prisis commented
> Since @pkuczynski somewhat provided the implementation in his PR, I want to make them coauthor in this PR. How would this be possible? Is assigning them to the PR enough?

It is possible if you merge the commit to add a coauthor

2022-06-22 14:17 UTC, prisis commented on src/modules/system/index.ts
> +    const extCount = options.extensionCount;
can you move this call after the if?

2022-06-22 14:23 UTC, xDivisionByZerox commented on src/modules/system/index.ts
> +    const extCount = options.extensionCount;
I first had the mapping in line 62 implemented as a `while` loop and outsourced the count in this constant to not mutate the potential input object. But since this is no longer the case, I think the const is obsolete. 

I will remove it instead and pass the array length directly from the options.

2022-06-22 14:40 UTC, xDivisionByZerox commented on src/modules/system/index.ts
> +    const extCount = options.extensionCount;
Nvm, I saw that I never default `extensionCount` if an empty object is provided. Guess I will implement a test case for that.

2022-06-22 21:15 UTC, ST-DDT requested changes
Please add a seeded test, that uses the new option.

2022-06-22 21:15 UTC, ST-DDT commented on src/modules/system/index.ts
> +    }
```suggestion
  fileName(options: {
    /**
     * Define how many extensions the file name should have. A negative number will be treated as `0`. Defaults to `1`.
     */
    extensionCount?: number;
  } = {}): string {
```

2022-06-22 23:49 UTC, ST-DDT commented
> So by adding new test cases, existing ones (not the new one) are randomly failing? This doesn't seem right to me. I also can reproduce the values in the test by setting the seed to the one in the test.

The random seeded tests are less random than one would like. I will try to have a look at the randomness issue soon.
The test previously passing was probably a false positive.

2022-06-23 13:37 UTC, xDivisionByZerox commented
> Please add a seeded test, that uses the new option.

Honestly, no. I don't see the point in the seeded tests. No other function has an extra seeded test case for their argument, why would this have? I already added some test cases that check for the argument options in the non-seeded test runs. They are much more valuable IMO.

2022-06-24 09:27 UTC, Shinigami92 commented on test/system.spec.ts
> +        it('should return filenames without a extension when extensionCount is 0', () => {
```suggestion
        it('should return filenames without an extension when extensionCount is 0', () => {
```

2022-06-24 09:27 UTC, Shinigami92 commented on test/system.spec.ts
> +        it('should return filenames without a extension when extensionCount is negative', () => {
```suggestion
        it('should return filenames without an extension when extensionCount is negative', () => {
```

2022-06-24 09:27 UTC, Shinigami92 commented on test/system.spec.ts
> +          'should return filenames with a %s extensions',
```suggestion
          'should return filenames with %s extensions',
```

2022-06-24 09:27 UTC, Shinigami92 commented on test/system.spec.ts
> +              extensionCount: extCount,
```suggestion
          (extensionCount) => {
            const fileName = faker.system.fileName({
              extensionCount,
```

2022-06-24 09:39 UTC, xDivisionByZerox commented on test/system.spec.ts
> +              extensionCount: extCount,
done in 0bd31da

2022-06-24 09:40 UTC, xDivisionByZerox commented on test/system.spec.ts
> +          'should return filenames with a %s extensions',
fixed in d2ecae9

2022-06-24 09:40 UTC, xDivisionByZerox commented on test/system.spec.ts
> +        it('should return filenames without a extension when extensionCount is negative', () => {
fixed in d2ecae9

2022-06-24 09:40 UTC, xDivisionByZerox commented on test/system.spec.ts
> +        it('should return filenames without a extension when extensionCount is 0', () => {
fixed in d2ecae9

2022-06-24 09:42 UTC, xDivisionByZerox commented on src/modules/system/index.ts
> +    }
Done in aa351b26e7765d9e1a78cd65557fbf10e8d70cff

2022-06-24 09:43 UTC, xDivisionByZerox commented on src/modules/system/index.ts
>     * @example
Is there a possibility to automate this spacing preference via a linter/formatter?

2022-07-04 21:15 UTC, xDivisionByZerox commented
The failing test is expecting a common file extension to be included in an array provided in the test. According to our implementation of `system.commonFileExt()` all of the following would be valid common file types
```ts
[
  'gif', 'htm', 'html', 'jpe',
  'jpeg', 'jpg', 'm1v', 'm2a',
  'm2v', 'm3a', 'mp2', 'mp2a',
  'mp3', 'mp4', 'mp4v', 'mpe',
  'mpeg', 'mpg', 'mpg4', 'mpga',
  'pdf', 'png', 'shtml', 'wav',
]
```

But our expected values are only:
[
  'gif', 'htm', 'html', 'jpeg',
  'm2a', 'm2v', 'mp2', 'mp3',
  'mp4', 'mp4v', 'mpeg', 'mpg',
  'pdf', 'png', 'shtml', 'wav',
]
```

2022-07-05 22:16 UTC, ST-DDT commented
Then update the expected values!?
I'm not sure whether I would consider all of them "common".

2022-07-06 07:40 UTC, xDivisionByZerox commented
> [...] I would consider all of them "common".

That's where I wasn't sure about and wanted to have some "backup" from you.

2022-07-06 17:01 UTC, ST-DDT commented
I have rarily/never seen m2a/v mp2 or shtml.
So I  would remove them. Lets discuss this tomorrow with everyone.
I miss json and txt.

2022-07-12 16:34 UTC, xDivisionByZerox commented
For now, I updated the test expectation. In the future we should rework the function to pick extensions from a custom-defined array or something like that.

2022-07-13 02:37 UTC, ST-DDT approved these changes

2022-07-13 04:29 UTC, import-brain approved these changes

2022-07-19 08:57 UTC, xDivisionByZerox commented
This is non-blocking. Can we merge?

2022-07-19 09:45 UTC, Shinigami92 approved these changes

2022-07-19 09:46 UTC, merged