docs(contributing): jsdocs section
faker-js/faker pull request #1104
Opened 2022-06-23 21:40 UTC by xDivisionByZerox

This PR documents coding standards we expect from contributors, that are currently only documented in an intern shared file.

2022-06-23 21:41 UTC, xDivisionByZerox commented
I first wanted to include all our intern documentation in this PR, but I think it's much easier to discuss if we add each section/topic in an extra PR. I also think this will make backtracking in the git history simpler.

2022-06-23 21:44 UTC, xDivisionByZerox commented on CONTRIBUTING.md
> +> We use eslint-plugin-jsdoc to test for rough style and sorting of doc-tags.
I currently highlighted each rule by putting the in a quote (`>`). I'm open to different ideas.

2022-06-23 21:48 UTC, xDivisionByZerox commented on CONTRIBUTING.md
> +> Different decorators have to be separated by an empty line.
What about a description here like:
This rule makes each decorator group more distinctive from the others.

2022-06-23 21:56 UTC, xDivisionByZerox commented
Why does markdown have to be formatted by prettier?^^

2022-06-24 09:23 UTC, Shinigami92 commented on CONTRIBUTING.md
> +JSDoc are comments above any code structure (variable, function, class, etc.) that have big with `/**` and end with `*/`. Multiline comments start (if not being the start or end line) with a `*`.
```
that have big with
          ~~~
```

2022-06-24 09:23 UTC, Shinigami92 commented on CONTRIBUTING.md
> +For more infors checkout [jsdoc.app](https://jsdoc.app/about-getting-started.html).
```suggestion
For more info checkout [jsdoc.app](https://jsdoc.app/about-getting-started.html).
```

2022-06-24 09:34 UTC, xDivisionByZerox commented on CONTRIBUTING.md
> +For more infors checkout [jsdoc.app](https://jsdoc.app/about-getting-started.html).
Fixed in 1560cae

2022-06-25 19:09 UTC, import-brain requested changes

2022-06-25 19:09 UTC, import-brain commented on CONTRIBUTING.md
> +> If a fucntion can throw an error (FakerError) you have to include the `@throws` decorator with an explanation when an error could be thrown
```suggestion
> If a function can throw an error (FakerError) you have to include the `@throws` decorator with an explanation when an error could be thrown
```

2022-06-25 19:09 UTC, import-brain commented on CONTRIBUTING.md
> + */
Please make this JSDoc match with the `foo()` function. Thanks!

2022-06-25 19:23 UTC, xDivisionByZerox commented on CONTRIBUTING.md
> +While single line JSDoc are technically valid, we decided to follow this rule since it makes changes in the git difference much more clear and easier to understand.
I had it as 'git diff' first, but thought: 'Why not be explicit in the docs'. 
TBH, I don't really care, so I would like to get feedback from any other maintainer/member and be fine.

2022-06-25 22:19 UTC, ST-DDT commented on CONTRIBUTING.md
> +JSDoc will be read and automatically processed by generate:api-docs and therefore need to follow some project conventions. Other standards are in place because we think they provide a better code qua
```suggestion
JSDoc will be read and automatically processed by `generate:api-docs` and therefore need to follow some project conventions. Other standards are in place because we think they provide a better code quality in general.
```
I would highlight special things such as commands.

2022-06-25 22:19 UTC, ST-DDT commented on CONTRIBUTING.md
> +> We use eslint-plugin-jsdoc to test for rough style and sorting of doc-tags.
```suggestion
> We use eslint-plugin-jsdoc to test for basic styling and sorting of doc-tags.
```

2022-06-25 22:19 UTC, ST-DDT commented on CONTRIBUTING.md
> +> We use eslint-plugin-jsdoc to test for rough style and sorting of doc-tags.
It's good, it structures the text into small and easy to understand segments.

2022-06-25 22:19 UTC, ST-DDT commented on CONTRIBUTING.md
> +While single line JSDoc are technically valid, we decided to follow this rule since it makes changes in the git difference much more clear and easier to understand.
I prefer `git diff`. We already have `changes` right above it.

2022-06-25 22:19 UTC, ST-DDT commented on CONTRIBUTING.md
> +```
You might want to add that the sentence will get parsed, so the layout/content is important.

2022-06-25 22:19 UTC, ST-DDT commented on CONTRIBUTING.md
> +> Different decorators have to be separated by an empty line.
Good idea.

2022-06-25 22:19 UTC, ST-DDT commented on CONTRIBUTING.md
> + * This is a good JSDoc description.
It might be confusing to refer to a good jsdocs here.

2022-06-25 22:41 UTC, xDivisionByZerox commented on CONTRIBUTING.md
> + * This is a good JSDoc description.
So just `This is a good description`?

2022-06-26 06:36 UTC, ST-DDT commented on CONTRIBUTING.md
> + * This is a good JSDoc description.
No, both the correct amd the bad example claim to be the good one.

2022-06-26 08:11 UTC, Shinigami92 commented on CONTRIBUTING.md
> + * This is a good JSDoc description.
```suggestion
 * This is a bad JSDoc block, because it has no linebreaks between sections.
```

2022-06-26 08:11 UTC, Shinigami92 commented on CONTRIBUTING.md
> + * This is a good JSDoc description.
```suggestion
 * This is a good JSDoc block, because it follows the Faker preferences.
```

2022-06-26 10:17 UTC, xDivisionByZerox commented on CONTRIBUTING.md
> + * This is a good JSDoc description.
Oh, my bad. Was reading in the discussions tab. Didn't notice that this is supposed to be the "bad" example.

2022-06-26 10:21 UTC, xDivisionByZerox commented on CONTRIBUTING.md
> + * This is a good JSDoc description.
Why is "description" wrong? Normally you would set the description by the `@description` tag. But according to the [JSDoc documentation](https://jsdoc.app/tags-description.html) the `@description` can be limited if it is located at the very beginning of the JSDoc comment.

2022-06-26 10:30 UTC, xDivisionByZerox commented on CONTRIBUTING.md
> + * This is a good JSDoc description.
Ok, I understand. With `block` you are referencing the entire JSDoc and not just the description itself. My bad.

2022-06-26 10:54 UTC, xDivisionByZerox commented on CONTRIBUTING.md
> +```
I don't understand what you mean by that :( 
Can you give an example?

2022-06-26 12:57 UTC, import-brain commented on CONTRIBUTING.md
> +JSDoc will be read and automatically processed by `generate:api-docs` and therefore need to follow some project conventions. Other standards are in place because we think they provide a better code q
```suggestion
JSDoc will be read and automatically processed by `generate:api-docs` and therefore need to follow some project conventions. Other standards are in place because we think they increase the code quality.
```

2022-06-26 13:12 UTC, import-brain approved these changes

2022-06-26 19:35 UTC, ST-DDT commented on CONTRIBUTING.md
> +```
If the `@param` texts ends with ``Defaults to `x`.``, then that is removed from the api docs page and the value is used for the `Default` column.

Example:
![grafik](https://user-images.githubusercontent.com/1579362/175830643-2d1d2725-122b-4e51-94fb-7b1d24b5e782.png)
https://github.com/faker-js/faker/blob/85246b90e1a2c76ad66c28b2788dec2748ad1c35/src/modules/date/index.ts#L264

Not sure if this is worth mentioning.

2022-06-26 20:56 UTC, pkuczynski commented on CONTRIBUTING.md
> +```
Btw. apparently, version 0.23 of typedoc parser supports optional params: https://github.com/TypeStrong/typedoc/pull/1810#issuecomment-1166638908

2022-06-28 19:17 UTC, ST-DDT approved these changes

2022-06-30 10:36 UTC, merged