feat(modules): number
faker-js/faker pull request #1122
Opened 2022-07-01 10:16 UTC by xDivisionByZerox

This move all number generators into their own (number) module.

This change was discussed in #805.

2022-07-01 10:17 UTC, xDivisionByZerox commented
Currently, I have removed all functions that were moved to the number module. I guess that wasn't the best move from me since we should deprecate them in v8 and remove them in v9. Correct?

2022-07-01 10:19 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +    }
This is currently not working as expected when non-int ranges are provided. Example `float({ min: 0.1, max: 0.5 })`.

2022-07-01 11:20 UTC, ST-DDT commented on src/modules/number/index.ts
> +  hexadecimal(length = 1): string {
This method shouldnt be here as it produces strings.

2022-07-01 11:23 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +  hexadecimal(length = 1): string {
By that logic `bigInt` shouldn't be located here as well. It does produce a hex number. I don't see anything wrong here.

2022-07-01 11:28 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +  hexadecimal(length = 1): string {
If I as a user want to have a hexadecimal number I would check in the numbers module for it, not in the string module. Also, I think it's okay to put implementations in multiple modules if that makes sense. So `hexadecimal` could be a function in number AND string. But that's a different topic.

2022-07-01 13:08 UTC, xDivisionByZerox commented
Suggestion from a discord user:

> I would love to have a number.int, number.bigInt and something with [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754)

2022-07-06 17:33 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +  int(options: number | Range = {}): number {
What would be the expected behavior when inputs are non-integers? Should they be rounded up/down or round the result from `mersenne.rand()` entirely?

2022-07-06 17:34 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +      throw new FakerError(`Max ${max} should be greater than min ${min}.`);
Testcase for this error is missing.

2022-08-13 11:39 UTC, Shinigami92 requested changes, later dismissed
**BLOCKED**: we cannot name the module `Number` as this is the JavaScript global Number constructor and we would run into the same issues as with `_Date` module (were we actually also want to find a better name for, like e.g. `DateModule` or `Temporal`)

If we name it `NumberModule` please first merge #932

2022-08-18 22:13 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    if (this.faker.number.int({ min: 0, max: 100 }) / 100 < probability) {
Why did you change this?

2022-08-19 07:17 UTC, Shinigami92 commented on src/modules/number/index.ts
> +    return randomInt;
Just nit-picking, but why do you name this `randomInt` but down you name it `float`?
Stick to one convention and make it consistent 🙂

2022-08-19 07:19 UTC, Shinigami92 commented on src/modules/number/index.ts
> +  int(options: number | { min?: number; max?: number } = {}): number {
Should we use overloads with different parameter name?

Like we could do:

```ts
int(): number;
int(max: number): number;
int(options: { min?: number; max?: number }): number;
int(options: number | { min?: number; max?: number } = {}): number {
  // ...
```

That way the DX is slightly increased as this `max` will be shown in editors like VSCode if you turn on the feature for it

2022-08-19 16:25 UTC, xDivisionByZerox commented on src/modules/datatype/index.ts
> +   * faker.number.bigInt({ min: 10n, max: 100n }) // 36n
This documentation is wrong. Prob introduced while rebasing.

2022-08-19 16:26 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +    if (this.faker.number.int({ min: 0, max: 100 }) / 100 < probability) {
Don't know :/ The last rebase was very big, guess I introduced some errors during that. I'll revert to float.

2022-08-19 16:28 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> -        (i + 1) * this.faker.datatype.float({ min: 0, max: 0.99 })
This should use `float`.

2022-08-19 16:30 UTC, xDivisionByZerox commented on src/modules/mersenne/index.ts
> -   * @param max The maximum number. Defaults to `32768`.
This should probably not be in this PR. I mean it's somewhat related but it should be discussed separatly if we want to add this doc snippet (since all other range properties in the codebase are inclusive).

2022-08-19 16:32 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +  int(options: number | { min?: number; max?: number } = {}): number {
I remember we didn't want to do this because it requires a shit ton of duplicated JSDocs for the documentation. Please correct me if I'm wrong.

2022-08-19 16:33 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +    return randomInt;
So `value` all the way. Gotcha!^^

2022-08-19 16:43 UTC, ST-DDT commented on src/modules/mersenne/index.ts
> -   * @param max The maximum number. Defaults to `32768`.
IMO the Mersenne class should be removed from the public api mid term.

2022-08-19 23:35 UTC, xDivisionByZerox commented on src/modules/mersenne/index.ts
> -   * @param max The maximum number. Defaults to `32768`.
Well, it's still nice to know that the max value is exclusive, for intern usage.

2022-08-20 10:27 UTC, Shinigami92 commented on src/modules/number/index.ts
> +  int(options: number | Range = {}): number {
If we don't need to explicitly check it, I would just say: leave it as it behaves on default like yet

2022-08-20 10:28 UTC, Shinigami92 commented on src/modules/number/index.ts
> +      throw new FakerError(`Max ${max} should be greater than min ${min}.`);
If this is also needed in main branch, I would prefer open a separate PR and rebase this one after it got merged

2022-08-21 09:49 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +      throw new FakerError(`Max ${max} should be greater than min ${min}.`);
Nah, we have this test case for `datatype.number`, but I forgot to migrate it.

2022-08-21 16:20 UTC, ST-DDT requested changes

2022-08-21 16:20 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +        (i + 1) * this.faker.number.float({ min: 0, max: 1, precision: 2 })
AFAICT this would be better off with `int(0, i+1)` or whatever it does. I assume the 0.99 is there to prevent the result from overshooting.

2022-08-21 16:20 UTC, ST-DDT commented on src/modules/number/index.ts
> +    const max = options.max ?? min + 99999;
Maybe use:

````suggestion
const { min = 0, max = min + 99999 } = options;
````

2022-08-21 16:20 UTC, ST-DDT commented on src/modules/number/index.ts
> +    return int;
Maybe return directly?

2022-08-21 16:20 UTC, ST-DDT commented on src/modules/number/index.ts
> +
Maybe use the same kind of remapping the options as you do with float?

2022-08-24 16:58 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +
Done as far as possible. I can't do `const { min = BigInt(0), max = BigInt(min + 999999999999999) } = options` since if someone inputs `{min: true, max: true }` properties would be of type `boolean` after destruction.

2022-08-24 17:00 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +  int(options: number | { min?: number; max?: number } = {}): number {
So can I resolve this and we tackle this issue separately?

2022-08-24 17:02 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +    return int;
I'm used to this style due to debugability coding guidelines from my job. But I don't care, so done.

2022-08-24 18:37 UTC, xDivisionByZerox commented on test/__snapshots__/helpers.spec.ts.snap
> +  undefined,
This doesn't look correct.
@ST-DDT guess we can replace the index in `arrayElements` with `int({ min: 0, max: i + 1 })`. 
But `int({ min: 0, max: i })` should work (?)

2022-08-24 18:38 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +        (i + 1) * this.faker.number.float({ min: 0, max: 1, precision: 2 })
Look [here](https://github.com/faker-js/faker/pull/1122/files#r954159610).

2022-08-24 20:29 UTC, ST-DDT commented on test/__snapshots__/helpers.spec.ts.snap
> +  undefined,
Yeah, I probably got confused with the old `(i+1) * x`

2022-08-24 20:29 UTC, ST-DDT commented on test/__snapshots__/helpers.spec.ts.snap
> +  undefined,
Yeah, I probably got confused with the old `(i+1) * x`

2022-08-24 20:42 UTC, xDivisionByZerox commented on test/number.spec.ts
> +    t.describeEach('int', 'hex')((t) => t.it('noArgs'));
"with value" means a primitive and "with options" means with an options object. Just asking so I'm understanding you correctly.

2022-08-24 21:00 UTC, xDivisionByZerox commented on test/__snapshots__/helpers.spec.ts.snap
> +  undefined,
Fixes the problem by applying `int({ min: 0, max: i + 1 })`

2022-08-25 07:01 UTC, Shinigami92 commented on src/modules/number/index.ts
> +    options: number | { min?: number; max?: number; precision?: number } = {}
I currently think about the `precision` value now changed...
This could come into confusion when using it with native JS as there it has another meaning: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toPrecision#parameters

> An integer specifying the number of **significant** digits.

It's different to what e.g. `toFixed` is doing: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed#parameters

> The number of digits to appear **after the decimal point**

So we might want to rename it, or do alternative ways 🤔 
I'm also not sure if we e.g. accept negative exponents, but this might work but lead just to more _roundings_

2022-08-25 10:30 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * @param options.precision Number of digits after the decimal point. Negative numbers will be treated as `0`. Defaults to `2`.
> Negative numbers will be treated as `0`.

Currently I don't see anything related to that in the code.

2022-08-25 10:45 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +   * @param options.precision Number of digits after the decimal point. Negative numbers will be treated as `0`. Defaults to `2`.
So, that's definitly a missing test case

2022-09-09 20:36 UTC, xDivisionByZerox commented on test/number.spec.ts
> +    t.describeEach('int', 'hex')((t) => t.it('noArgs'));
Done in dac2931d4c075921bf605b7a8d7336b3352c2721.

2022-09-09 20:38 UTC, xDivisionByZerox commented on test/number.spec.ts
> +      t.it('noArgs').it('with value', 42);
Is one value and one option test enough here or should there be a test for each possible input type (`string`, `number`, `boolean`, `bigint`, and everything as options)

2022-09-09 20:43 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +   * @param options.precision Number of digits after the decimal point. Negative numbers will be treated as `0`. Defaults to `2`.
Should we discuss this in a meeting? I'm not sure if I should already implement this, because of @Shinigami92's [comment](https://github.com/faker-js/faker/pull/1122#discussion_r954573961).

> I'm also not sure if we e.g. accept negative exponents, but this might work but lead just to more roundings

2022-09-09 21:23 UTC, xDivisionByZerox commented
Is this ready review? #932 was merged, so this is no longer blocked.

2022-09-09 22:06 UTC, ST-DDT commented
Review yes, merge no. We will release "one last" v7.x first.

2022-09-09 22:11 UTC, ST-DDT commented on test/number.spec.ts
> +      t.it('noArgs').it('with value', 42);
No, one for each option as well as all at once is fine.

2022-09-10 00:26 UTC, ST-DDT requested changes

2022-09-10 00:26 UTC, ST-DDT commented on src/modules/mersenne/index.ts
> +   * @param max The maximum number. This value is exclusiv. Defaults to `32768`.
```suggestion
   * @param max The maximum number. This value is exclusive. Defaults to `32768`.
```

2022-09-10 00:26 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * Returns a [hexadecimal](https://en.wikipedia.org/wiki/Hexadecimal) number.
```suggestion
   * Returns a lowercase [hexadecimal](https://en.wikipedia.org/wiki/Hexadecimal) number.
```

2022-09-10 00:28 UTC, ST-DDT commented
Please also include the migration guide docs in this PR.
There are some changes (e.g. precision: 0.01 -> 2) that needs to be documented.

2022-09-10 08:38 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +    }
Do we need these checks? We call `this.int` later, that does these checks anyway.

2022-09-10 08:47 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +      throw new FakerError(`Max ${max} should be greater than min ${min}.`);
Done in 774e1f9f5018f559537e0dee23ae63f07bdfa7a6.

2022-09-10 08:49 UTC, xDivisionByZerox commented
> Please also include the migration guide docs part in this PR. There are some changes (e.g. precision: 0.01 -> 2) that needs to be documented.

I'm not sure. I don't see the responsibility in this PR. There should already be a migration from v7 to v8 where I only need to include these changes.

2022-09-10 09:18 UTC, ST-DDT commented
> I'm not sure. I don't see the responsibility in this PR. There should already be a migration from v7 to v8 where I only need to include these changes.

Documentation is a very important part of our work.
And yes, the migration page itself will already be there before this PR is merged, however we can still "mock" the page for now and just add the migration section related to this module, so it can be reviewed and potential usage caveeats be detected early.
IMO the author of a PR has the best insights into the changes and thus can describe/explain them well.
If we delay the documentation, then we might not write them at all, which would be bad.
What do you think?

2022-09-10 09:28 UTC, xDivisionByZerox commented
> And yes, the migration page itself will already be there before this PR is merged,

In that case, I'm okay with that. But I don't see the responsibility of this PR to create the entire "migration boilerplate".

2022-09-10 16:08 UTC, import-brain commented on src/modules/number/index.ts
> +   *
Maybe we should add an example here with `min` and `max`?

2022-09-10 16:08 UTC, import-brain commented on test/number.spec.ts
> +      it('should throw when min bigger max', () => {
```suggestion
      it('should throw when min > max', () => {
```

2022-11-22 18:35 UTC, Shinigami92 commented on src/modules/number/index.ts
> +    }
I would say fail fast in this case

2022-11-22 18:35 UTC, Shinigami92 commented on src/modules/number/index.ts
> +    options: number | { min?: number; max?: number; precision?: number } = {}
I extracted this to its own issue
- #1591

2022-11-22 18:35 UTC, Shinigami92 commented on src/modules/number/index.ts
> +    }
In this case I would say fail fast and so: yes

2022-11-22 23:14 UTC, xDivisionByZerox commented on src/modules/datatype/index.ts
> +   * @deprecated Use `faker.number.int` instead.
```suggestion
   * @deprecated Use `faker.number.int()` instead.
```

2022-11-22 23:14 UTC, xDivisionByZerox commented on src/modules/datatype/index.ts
> +   * @deprecated Use `faker.number.float` instead.
```suggestion
   * @deprecated Use `faker.number.float()` instead.
```

2022-11-22 23:29 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +    });
Is there a reason this method isn't redirecting to the new method?

2022-11-22 23:29 UTC, ST-DDT commented on src/modules/finance/index.ts
> +    const addressLength = this.faker.number.int({ min: 25, max: 39 });
Instead of calculating that here you can pass it directly to `alphanumeric`.

2022-11-22 23:29 UTC, ST-DDT commented on src/modules/finance/index.ts
> +    return Array.from({ length }, () => this.faker.number.int(9)).join('');
This should use string.numeric instead.

2022-11-22 23:29 UTC, ST-DDT commented on src/modules/commerce/index.ts
> +    const randValue = this.faker.number.int({ max, min });
Please order `min, max` consistently across all modules/invocations.

2022-11-22 23:29 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * @param options.precision Number of digits after the decimal point. Negative numbers will be treated as `0`. Defaults to `2`.
Still nothing related to this in the sources.

2022-11-22 23:29 UTC, ST-DDT commented on src/modules/vehicle/index.ts
> +    })}${this.faker.number.int({ min: 10000, max: 99999 })}` // return five digit #
This should string.numeric instead.

2022-11-23 09:44 UTC, Shinigami92 commented on src/modules/vehicle/index.ts
> +    })}${this.faker.number.int({ min: 10000, max: 99999 })}` // return five digit #
This changes returned result, so not part of this PR 🙅

2022-11-23 09:44 UTC, Shinigami92 commented on src/modules/finance/index.ts
> +    const addressLength = this.faker.number.int({ min: 25, max: 39 });
This changes returned result, so not part of this PR 🙅

2022-11-23 10:58 UTC, Shinigami92 commented on test/number.spec.ts
> +        expect(results).toEqual([0, 0.5, 1, 1.5]);
I found this missing test-case and the previous implementation could handle it to assume values like non `0.1`, `0.01` or `0.001` and so on.
So how would this be supported by the now changed precision parameter?
My brain cannot do the math 😣

I see three options:
1. Revert to use precision with `0.x`
2. Explain me the math and add this to JSDoc
3. Let the user round the result by them self like https://stackoverflow.com/a/34591063/6897682

2022-11-23 17:48 UTC, Shinigami92 commented on src/modules/number/index.ts
> +   * @param options.precision Number of digits after the decimal point. Negative numbers will be treated as `0`. Defaults to `2`.
I added test cases for that: https://github.com/faker-js/faker/pull/1122/commits/f2cf2ce4f743f920b8b5d9423c9fcec7818db964

2022-11-23 17:51 UTC, Shinigami92 commented
@ST-DDT Okay I now added a test case for the `0.5` steps but how would I use steps `0.3` or `0.4`?
Like getting `0.0`, `0.4`, `0.8`, `1.2`, `1.6`, ...

2022-11-23 19:58 UTC, ST-DDT commented
> @ST-DDT Okay I now added a test case for the `0.5` steps but how would I use steps `0.3` or `0.4`? Like getting `0.0`, `0.4`, `0.8`, `1.2`, `1.6`, ...
> 
> I would like to provide JSDoc examples and/or a source for people like me that cannot do the math out of their brain

IIRC Precision = log10(0.4) or ln(0.4) / ln(10)

2022-11-23 20:31 UTC, Shinigami92 commented
> IIRC Precision = log10(0.4) or ln(0.4) / ln(10)

Both wrong and both return the same result :confused: 

```ts
faker.number.float({ min: 0, max: 1.9, precision: Math.log(0.4) / Math.LN10 })
faker.number.float({ min: 0, max: 1.9, precision: Math.log10(0.4) })
// => [0, 2.5] :eyes: 
```

2022-11-23 21:19 UTC, import-brain commented on test/number.spec.ts
> +      });
Should we declare a const variable here and use that to validate bounds of the generated bigint instead of calling `number.bigInt` twice? I think that would keep it consistent with the other tests

2022-11-23 21:19 UTC, import-brain commented on test/number.spec.ts
> +      });
Same here

2022-11-23 21:19 UTC, import-brain commented on test/number.spec.ts
> +      it('should succeed with success-rate', () => {
```suggestion
      it('should succeed with success-rate', () => {
```
What does 'succeed with success-rate' mean?

2022-11-23 21:19 UTC, import-brain commented on src/modules/number/index.ts
> +   * Returns a single random floating-point number for the given precision or range and precision.
```suggestion
   * Returns a single random floating-point number for a given precision or range and precision.
```

2022-11-23 21:34 UTC, Shinigami92 commented on test/number.spec.ts
> +      it('should succeed with success-rate', () => {
I don't know :thinking: 
Somehow it feels like we can just remove this test, can we?

2022-11-23 21:38 UTC, ST-DDT commented
> > IIRC Precision = log10(0.4) or ln(0.4) / ln(10)
> 
> Both wrong and both return the same result 😕
> 
> ```ts
> faker.number.float({ min: 0, max: 1.9, precision: Math.log(0.4) / Math.LN10 })
> faker.number.float({ min: 0, max: 1.9, precision: Math.log10(0.4) })
> // => [0, 2.5] :eyes: 
> ```

Correction
Log10(2.5)

2022-11-23 21:51 UTC, Shinigami92 commented
> Correction
> Log10(2.5)

... well, we have a problem there:

![image](https://user-images.githubusercontent.com/7195563/203651822-40d74f80-e9fd-4097-a5ad-2146884a0a26.png)

So beside that I absolutely do not understand this math magic you are doing with these `log10`s,
it results in values greater then the requested max :eyes:

2022-11-23 23:31 UTC, ST-DDT commented
> > Correction
> > Log10(2.5)
> 
> ... well, we have a problem there:
> 
> ![image](https://user-images.githubusercontent.com/7195563/203651822-40d74f80-e9fd-4097-a5ad-2146884a0a26.png)
> 
> So beside that I absolutely do not understand this math magic you are doing with these `log10`s, it results in values greater then the requested max 👀

Math: 1 / x = 0.4 => x = 2.5

Range: The issue here is probably with number.int
It uses +1 to make max inclusive.

1.9 × 2.5 = 4.75
4.75 + 1 = 5.75 (5 as int)
5 / 2.5 = 2

So instead of adding one we might want to add a very small number and then round up.
Alternatively substract precision from max before passing it  to int. Not sure whether that creates other issues.

2022-11-23 23:39 UTC, ST-DDT commented
We might want to be more strict in number.int anyway and ceil min and floor max before checking and using it. Because then we would pass 5 to mersenne, but since it is exclusive we will only get 4 as max returned value => 4 / 2.5 = 1.6.
Not tested yet.

2022-11-23 23:52 UTC, ST-DDT commented
Also since that math confuses even our own developers how about having both options?
Precision as used previously and decimal digits as used here?

2022-11-24 10:43 UTC, Shinigami92 commented
I ensured together with @ST-DDT that the tests / bugs are already there before this PR and so I extracted it to #1595 so we do not pollute this PR with fixing this bug.

2022-11-24 11:45 UTC, Shinigami92 commented
Due to the confusion with the log10 stuff, @ST-DDT and I decided for now to revert the parameter precision change from this PR.
But we will create a new issue to re-think about the change in another PR. (rename `precision` to `fractionDigits`)

2022-11-24 11:53 UTC, Shinigami92 approved these changes, later dismissed

2022-11-24 18:49 UTC, ST-DDT commented on src/modules/commerce/index.ts
> +    const randValue = this.faker.number.int({ min, max });
Maybe simplify this to:

```suggestion
    const randValue = this.faker.number.float({ min, max, precision: 10 ** -dec });
```

?

2022-11-24 18:49 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +    });
Why don't you forward this method to faker.number.float()?

2022-11-24 18:49 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +    });
Why don't you forward to number.float() here?

2022-11-24 18:49 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * @throws When options define `max < min`.
We don't have that for any of the other methods.

2022-11-24 19:13 UTC, Shinigami92 commented on src/modules/datatype/index.ts
> +    });
Good catch, it was not forwarded because previously the implementation of precision was differently.
Now as we reverted that, we can forward it

2022-11-24 19:28 UTC, Shinigami92 commented on src/modules/number/index.ts
> +   * @throws When options define `max < min`.
This was just copied over from the old JSDocs... so at least there we had it
Instead of removing it, we might more think about to add it to more places :thinking:

2022-11-24 19:50 UTC, ST-DDT approved these changes

2022-11-24 20:07 UTC, import-brain approved these changes

2022-11-24 20:18 UTC, Shinigami92 approved these changes

2022-11-25 15:59 UTC, merged