feat: introduces security module
faker-js/faker pull request #1151
Opened 2022-07-13 21:52 UTC by thisislawatts

2022-07-16 05:44 UTC, ST-DDT commented on src/definitions/security.ts
> +export type SecurityDefinitions = LocaleEntry<{
These definitions arent used anywhere as they are only used for locale depend data. (src/locales)

2022-08-03 14:02 UTC, Shinigami92 requested changes

2022-08-03 14:02 UTC, Shinigami92 commented on src/modules/security/index.ts
> +        .between('1999-01-01T00:00:00.000Z', '2022-01-01T00:00:00.000Z')
I think using a static year of 2022 is bad here :thinking: 
Not sure how we could ensure deterministic here, but setting it to 2022 is not the right way :confused:

2022-08-03 16:01 UTC, import-brain commented on src/modules/security/index.ts
> +        .between('1999-01-01T00:00:00.000Z', '2022-01-01T00:00:00.000Z')
Is there any way we can ensure deterministic results without setting a static year? Can't think of any off the top of my head either

2022-08-03 21:22 UTC, ST-DDT commented on src/modules/security/index.ts
> +        .between('1999-01-01T00:00:00.000Z', '2022-01-01T00:00:00.000Z')
Static ref years are required for reproducible tests. Otherwise we could to use a pattern for assertion.

2022-08-04 07:23 UTC, Shinigami92 requested changes

2022-08-04 07:23 UTC, Shinigami92 commented on src/modules/security/index.ts
> +        .between('1999-01-01T00:00:00.000Z', '2022-01-01T00:00:00.000Z')
Ah! In Date module we use a param `refDate`, so we could do this here as well:
Lets directly start with options param: `cve(options: { refDate?: string | Date | number }): string`
Then the behaviour should be the same as in Date module setting it to today if no refDate is passed.

We might move the `toDate()` utility to somewhere else and called it in a shared way.

2022-08-09 05:40 UTC, thisislawatts commented
Thanks @ST-DDT and @Shinigami92 both for taking the time to review the work here so far. ✨

2022-08-09 05:41 UTC, thisislawatts commented on src/definitions/security.ts
> +export type SecurityDefinitions = LocaleEntry<{
Removed!

2022-08-09 05:42 UTC, thisislawatts commented on src/modules/security/index.ts
> +        .between('1999-01-01T00:00:00.000Z', '2022-01-01T00:00:00.000Z')
Refactored to move toDate under `internals` and introduced an optional `options` object to the cve method so that users can configure things.

2022-08-09 07:33 UTC, ST-DDT requested changes

2022-08-09 07:33 UTC, ST-DDT commented on test/security.spec.ts
> +  for (const seed of seededRuns) {
We now use the seeded test factory for these.
See the animal module tests for example.

2022-08-09 07:33 UTC, ST-DDT commented on src/modules/security/index.ts
> +   * Generates a random CVE between the given boundaries
Please end sentences/jsdocs with a dot.

2022-08-09 07:33 UTC, ST-DDT commented on src/modules/security/index.ts
> +   * @param options
Please add a jsdocs comment.

2022-08-09 07:33 UTC, ST-DDT commented on src/modules/security/index.ts
> +   * @param options.from The early date boundary
Please add ``Defaults to `1999-....`.``

2022-08-09 07:33 UTC, ST-DDT commented on scripts/generateLocales.ts
> +  security: 'SecurityDefinitions',
This is no longer needed.

2022-08-09 16:56 UTC, ST-DDT commented on src/internal/toDate.ts
> + * @param date Date
```suggestion
 * @param date The input to convert to a date.
```

2022-08-09 17:00 UTC, Shinigami92 requested changes

2022-08-09 17:00 UTC, Shinigami92 commented on src/modules/security/index.ts
> +   * Generates a random CWE
```suggestion
   * Generates a random CWE.
```

2022-08-09 17:06 UTC, ST-DDT commented on src/modules/security/index.ts
> +   * Generates a random CWE
Maybe also add the long name for the abbreviation.

```suggestion
   * Generates a random CWE (Common Weakness Enumeration) number.
```

Is it a number?

2022-08-12 06:10 UTC, thisislawatts commented on src/modules/security/index.ts
> +   * Generates a random CWE
You're right here @ST-DDT, this function generates something which matches the format for CWE but doesn't perform any validation on whether that value is a recognised identifier. I would welcome some guidance here on the degree of accuracy to pursue, for instance:
1. There are only 1388 recognised ids at the moment should a max limit be applied here so that this method can not generated an idea > CWE-1388? The implication of applying this limit is that we would need to track new IDs being added to the external CWE register. 
2. Some identifiers have been deprecated, so maybe there should be filtered out as possible responses.

2022-08-12 07:07 UTC, ST-DDT commented on src/modules/security/index.ts
> +   * Generates a random CWE
My comment was more focussed on the jsdoc comment, but if there is a max value then we can use that. There is no need to support all CWE numbers. As for filtering deprecated ones. I wouldnt go that far.

2022-08-17 06:00 UTC, thisislawatts commented on src/internal/toDate.ts
> + * @param date Date
Addressed in 6490751a65c268ab337eacecfe75fba79b2f4506, thank you @ST-DDT

2022-08-17 06:01 UTC, thisislawatts commented on src/modules/security/index.ts
> +   * Generates a random CWE
Original comments on this thread around JSDoc have been addressed, thanks for the time both.

2022-08-17 06:09 UTC, thisislawatts commented on test/security.spec.ts
> +  for (const seed of seededRuns) {
Updated in 2cbbe1aa9f1d9f0abefbf16251ba87d387bc866f

2022-08-17 06:51 UTC, ST-DDT requested changes

2022-08-17 06:51 UTC, ST-DDT commented on src/modules/security/index.ts
> +    const fromMs = toDate(options?.from || '1999-01-01T00:00:00.000Z');
These are dates and not numbers. So I would drop the ms suffix.

2022-08-17 06:51 UTC, ST-DDT commented on test/security.spec.ts
> +  seededTests(faker, 'security', (t) => t.itEach(...functionNames));
Since there are methods with arguments you have to test them too.

````ts
t.describe('cve', (t) -> t.it('with to date', { to: '2022-08-16...'}).it('with from and to date', {...}));
t.it('cwe').it('cvss');
````
Usually there would be a no args test in the describe block as well but we need the to date for reproducible results.

2022-08-31 16:37 UTC, thisislawatts commented on test/security.spec.ts
> +  seededTests(faker, 'security', (t) => t.itEach(...functionNames));
Updated! Thanks @ST-DDT

2022-08-31 16:38 UTC, thisislawatts commented on src/modules/security/index.ts
> +    const fromMs = toDate(options?.from || '1999-01-01T00:00:00.000Z');
Updated

2022-08-31 16:38 UTC, thisislawatts commented
@ST-DDT Can I get approval for these workflows to run and see how it fairs?

2022-08-31 17:54 UTC, thisislawatts commented
Investigating: 

```
⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/scripts/apidoc/examplesAndDeprecations.spec.ts > examples and deprecations > Security > cve
Error: Transform failed with 1 error:
 ❯ failureErrorWithLog node_modules/.pnpm/esbuild@0.14.54/node_modules/esbuild/lib/main.js:1624:15
/home/runner/work/faker/faker/test/scripts/apidoc/temp/Security/cve.ts:3:83: ERROR: Expected "}" but found ")"
 ❯ node_modules/.pnpm/esbuild@0.14.54/node_modules/esbuild/lib/main.js:1413:29
 ❯ node_modules/.pnpm/esbuild@0.14.54/node_modules/esbuild/lib/main.js:678:9
 ❯ handleIncomingPacket node_modules/.pnpm/esbuild@0.14.54/node_modules/esbuild/lib/main.js:775:9
 ❯ Socket.readFromStdout node_modules/.pnpm/esbuild@0.14.54/node_modules/esbuild/lib/main.js:644:7
 ❯ Socket.emit node:events:513:28
```

2022-08-31 17:59 UTC, ST-DDT commented on src/modules/security/index.ts
> +   * faker.security.cve({from:'2020-01-01T00:00:00.000Z', to: '2030-01-01T00:00:00.000Z') // 'CVE-2028-0762'
See the above comment.

2022-08-31 19:57 UTC, ST-DDT requested changes

2022-08-31 19:57 UTC, ST-DDT commented on src/modules/security/index.ts
> +   * faker.security.cve({from:'2020-01-01T00:00:00.000Z', to: '2030-01-01T00:00:00.000Z'}) // 'CVE-2028-0762'
```suggestion
   * faker.security.cve({ from: '2020-01-01T00:00:00.000Z', to: '2030-01-01T00:00:00.000Z' }) // 'CVE-2028-0762'
```

2022-08-31 19:57 UTC, ST-DDT commented on src/modules/security/index.ts
> +   * faker.security.cwe() // 'CWE-####'
Please use an actual example and not a pattern.

2022-08-31 19:57 UTC, ST-DDT commented on src/modules/security/index.ts
> +export class Security {
Missing jsdocs.

2022-08-31 19:57 UTC, ST-DDT commented on src/modules/security/index.ts
> +export interface Cvss {
Missing jsdocs.

2022-08-31 22:54 UTC, ejcheng reviewed
Please add this module to the readme.

2022-09-02 16:40 UTC, ST-DDT requested changes

2022-09-02 16:40 UTC, ST-DDT commented on src/modules/security/index.ts
> +function getRanking(score: number): SeverityRating {
Missing jsdocs
Also please choose a more consistent name `rating` vs `getRanking` -> `getRating` or `toRating`?

2022-09-02 16:42 UTC, ST-DDT commented
**Docs Preview**

<details>
<summary>Click to expand</summary>

![grafik](https://user-images.githubusercontent.com/1579362/188200027-961d0b25-dabc-4a2c-b7c1-60ae73fd9522.png)

</details>

2022-09-02 16:58 UTC, ST-DDT commented
Please also run `pnpm run docs:dev` once.

2022-09-03 20:09 UTC, import-brain commented on src/modules/security/index.ts
> +   */
```suggestion
   * @example
   * faker.security.cve() // 'CVE-2011-0762'
   * faker.security.cve({ from:'2020-01-01T00:00:00.000Z', to: '2030-01-01T00:00:00.000Z' }) // 'CVE-2028-0762'
   */
```
Could you please add two more example function calls, one with only the `from` option and the other one with only the `to` option?

2022-09-03 20:09 UTC, import-brain commented on src/modules/security/index.ts
> +   * faker.security.cvss()
```suggestion
   * faker.security.cvss()
```
Please add the return value here

2022-09-03 20:09 UTC, import-brain commented on src/modules/security/index.ts
> +   * Generates a random CVSS.
```suggestion
   * Generates a random CVSS.
```
Hmm, we should say what CVSS is here, maybe we could rephrase this as "Generates random CVSS (Common Vulnerability Scoring System) data."?

2022-09-08 05:55 UTC, thisislawatts commented on src/modules/security/index.ts
> +   * faker.security.cvss()
Added

2022-09-08 05:56 UTC, thisislawatts commented on src/modules/security/index.ts
> +   * Generates a random CVSS.
Thanks the help, that is a useful suggestion.
Updated to: _Generates random CVSS (Common Vulnerability Scoring System) data._

2022-09-08 06:49 UTC, thisislawatts commented
> Please also run `pnpm run docs:dev` once.

I've run this locally but seeing some breakages, which seem unexpected? 

When attempting to load the API overview:
![Screenshot 2022-09-08 at 08 33 28](https://user-images.githubusercontent.com/472589/189051441-cd246c3f-612c-42bf-82d7-f3862cfffc5f.jpg)

Output when running: `pnpm run generate:api-docs`

```
warning <internal>.CallSite.getTypeName: Comment [[target]] style links are deprecated and will be removed in 0.24
warning Failed to find target: Class
JSON written to ./docs/api/typedoc.json
/Users/luke/oss/faker/scripts/apidoc/moduleMethods.ts:19
    .getChildrenByKind(ReflectionKind.Module)[0]
                                              ^

TypeError: Cannot read properties of undefined (reading 'getChildrenByKind')
    at selectApiModules (/Users/luke/oss/faker/scripts/apidoc/moduleMethods.ts:19:47)
    at null.processModuleMethods (/Users/luke/oss/faker/scripts/apidoc/moduleMethods.ts:34:24)
    at null.build (/Users/luke/oss/faker/scripts/apidoc.ts:38:24)
```

Also seeing the same behaviour when running the `main` branch, so something odd in my local environment. 

Node: v16.16.0
pnpm: 7.9.5

2022-09-08 06:54 UTC, ST-DDT commented
Have you installed the latest dependencies `pnpm install`?

2022-09-08 12:00 UTC, thisislawatts commented
@ST-DDT, I believe so. 
 
 ```bash
$ pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date
 ```

2022-09-08 12:20 UTC, ST-DDT commented
If you are fine with. I will have a look later and update the branch.

2022-09-08 14:59 UTC, ST-DDT approved these changes, later dismissed
Waiting for user interest.

2022-09-09 17:50 UTC, thisislawatts commented
Thanks @ST-DDT ✨ I will squash the commits once @Shinigami92 has had a chance to re-review.

2022-09-09 21:33 UTC, Shinigami92 commented on src/faker.ts
> +import { SecurityModule } from './modules/Security';
```suggestion
import { SecurityModule } from './modules/security';
```

2022-09-09 22:15 UTC, ST-DDT commented
All methods now need a `@since 8.0.0`

2022-09-10 07:27 UTC, thisislawatts commented on src/faker.ts
> +import { SecurityModule } from './modules/Security';
Resolved in https://github.com/faker-js/faker/pull/1151/commits/b72461c8326aacca953959f6ee3e250a0b6fa719

2022-09-10 07:30 UTC, thisislawatts commented
> All methods now need a `@since 8.0.0`

@ST-DDT Doesn't this kind of depend on the module getting user interest? I can see that its an outstanding task before the work is mergeable but seems impossible to know exactly what release version this would land in.

2022-09-10 08:59 UTC, ST-DDT commented
The `@since` is needed to pass the tests.
Sure the version might needs to be changed later/before merging, but at least it is visible.
If the test fail, the PR is less likely to be reviewed and reacted to.

2026-04-06 18:14 UTC, ST-DDT commented
@faker-js/maintainers @faker-js/members Should we push this to completion or close this?

2026-04-07 02:17 UTC, matthewmayer commented
4 years and 4 upvotes on matching issue. I think it's too niche, close.

2026-04-07 06:39 UTC, closed without merging