feat(modules): string
faker-js/faker pull request #1155
Opened 2022-07-15 21:37 UTC by xDivisionByZerox

This PR introduces a new module: `String`. This was heavily discussed in #805.

I did not create any new functions. I just moved a bunch of them into the new module and deprecated the old ones.

## Which functions made it to the `String` module?

| was | now |
| - | - |
| datatype.string() | string.random() |
| datatype.uuid() | string.uuid() |
| datatype.hexadecimal() | string.hexadecimal() |
| random.alpha() | string.alpha() |
| random.alphaNumeric() | string.alphaNumeric() |
| random.numeric() | string.numeric() |

2022-07-16 07:13 UTC, pkuczynski commented
I would avoid word `random`, as everything in faker is random, so it creates impression that this is more random than others... Instead I propose to do `string.any()`

2022-07-16 07:22 UTC, pkuczynski reviewed
Code wise look good, I am not approving only to have a chance to discuss the comments I left...

2022-07-16 07:22 UTC, pkuczynski commented on src/modules/string/index.ts
> +  random(length = 10): string {
I would avoid word `random`, as everything in faker is random, so it creates impression that this is more random than others... Instead I propose to do `string.any()`

2022-07-16 07:22 UTC, pkuczynski commented on src/modules/string/index.ts
> +  alphaNumeric(
It should be written as `alphanumeric`. See https://en.wikipedia.org/wiki/Alphanumericals

2022-07-16 07:22 UTC, pkuczynski commented on src/modules/string/index.ts
> +          bannedChars?: readonly LiteralUnion<AlphaNumericChar>[] | string;
This is not exactly related to this PR, but maybe good moment to propose it. Instead of `bannedChars` and `bannerDigits`, I propose to use common option for such cases: `except`. If I remember well, we also have similar way of excluding some data in other methods too? Alternatively it could be also named  `exclude`, but I prefer `except`. What others think?

2022-07-16 10:49 UTC, xDivisionByZerox commented on src/modules/string/index.ts
> +  random(length = 10): string {
I, myself, have no problem with that. But, I think there were members that disliked the `any` function name in the number module since it has collisions with the typescript `any` keyword. But I really like `any()` as a generic solution, to the problem of the module (generating strings), TBH.

2022-07-16 12:36 UTC, pkuczynski commented on src/modules/string/index.ts
> +  random(length = 10): string {
Well, I don't see a conflict here. I just dbl checked, and typescript also has no problem when variable or function is named `any`. And in practice, this function generates any kind for string, right?

2022-07-16 12:36 UTC, pkuczynski commented on src/modules/string/index.ts
> +  random(length = 10): string {
Those faker members, who didnt like it, please raise your voice or stay silent forever ;)

2022-07-16 13:26 UTC, Shinigami92 commented on src/modules/string/index.ts
> +  random(length = 10): string {
Ok I raise my hand to not be silence, but I'm also not sure what could be better in alternative. It's a little bit same as the discussion about number. It just doesn't feel right.

2022-07-16 13:26 UTC, ST-DDT commented on src/modules/string/index.ts
> +  random(length = 10): string {
This only generates ascii characters and no utf8 characters.
Please give me some time to think about.
I have to connect to a free wifi in order to respond to this, and I would like to spend my holidays with non-faker thoughts as well. 😉

2022-07-16 13:31 UTC, pkuczynski commented on src/modules/string/index.ts
> +  random(length = 10): string {
Hahaha, I didn't meant you have to speak immediately :) No rush, enjoy your stay and we can talk about it when you are both back :)

2022-07-16 18:57 UTC, import-brain commented on src/modules/string/index.ts
> +  random(length = 10): string {
Hmm, this is a really difficult decision for me. I think `random` is more clear, but it implies this function generates "more random" data than other functions, as @pkuczynski said. However, I don't think `any` is a good choice either, it seems a bit ambiguous. Does anyone have any third ideas for this function name?

2022-07-16 18:59 UTC, import-brain commented on src/modules/string/index.ts
> +          bannedChars?: readonly LiteralUnion<AlphaNumericChar>[] | string;
I definitely prefer `except` for this param.

2022-07-16 19:17 UTC, pkuczynski commented on src/modules/string/index.ts
> +  random(length = 10): string {
@import-brain and what's wrong with `any`?

2022-07-16 19:22 UTC, import-brain commented on src/modules/string/index.ts
> +  random(length = 10): string {
> @import-brain and what's wrong with `any`? In which way it is ambiguous?

It just doesn't sit right with me. If I looked at a function named `string.any()`, I would ask "any what?", and I would have to hover over the function and look at the jsdoc before realizing what it does. In that regard, `random` is a lot better, you can tell instantly that the function generates a random string. However, `random()` has the problems you mentioned.

2022-07-16 19:41 UTC, pkuczynski commented on src/modules/string/index.ts
> +  random(length = 10): string {
For my `string.any()` gives me a string with no constraints. Same as `any` in typescript... `random` is more explicit of course, but does not play so nicely with the other functions: `string.(numeric|alphanumeric|alpha)` - or `any` of those three...

2022-07-16 19:47 UTC, import-brain commented on src/modules/string/index.ts
> +  random(length = 10): string {
> For my `string.any()` gives me a string with no constraints. Same as `any` in typescript... `random` is more explicit of course, but does not play so nicely with the other functions: `string.(numeric|alphanumeric|alpha)` - or `any` of those three...

Hmm, you're right, I didn't consider that people would think "no constraints". Honestly, I would be fine with either "random" or "any".

2022-07-17 00:09 UTC, ST-DDT commented on src/modules/string/index.ts
> +          bannedChars?: readonly LiteralUnion<AlphaNumericChar>[] | string;
Or maybe `without`?

2022-07-17 00:45 UTC, ST-DDT commented on src/modules/string/index.ts
> +  random(length = 10): string {
> but does not play so nicely with the other functions: `string.(numeric|alphanumeric|alpha)` - or `any` of those three...

Note its not any of those three its a mixture of them (and more).

2022-07-17 02:04 UTC, Shinigami92 commented on src/modules/string/index.ts
> +          bannedChars?: readonly LiteralUnion<AlphaNumericChar>[] | string;
I'm tempted to exclude but didn't thought about it enough yet

2022-07-21 22:13 UTC, xDivisionByZerox commented on src/modules/string/index.ts
> +  alphaNumeric(
This looks really weird, but done.

2022-08-11 17:15 UTC, Shinigami92 commented on src/modules/random/index.ts
> +      until: '8.0',
```suggestion
      until: '9.0',
```

2022-08-11 22:14 UTC, ST-DDT requested changes

2022-08-11 22:14 UTC, ST-DDT commented on src/modules/database/index.ts
> +    return this.faker.string.hexadecimal(24).replace('0x', '').toLowerCase();
This can be simplified using options.

2022-08-11 22:14 UTC, ST-DDT commented on src/modules/finance/index.ts
> +    return addressPrefix + address;
This can be simplified using options.

2022-08-11 22:14 UTC, ST-DDT commented on src/modules/string/index.ts
> +          count?: number;
Maybe instead of `count` use `length`?

2022-08-11 22:14 UTC, ST-DDT commented on src/modules/string/index.ts
> +          count?: number;
Maybe instead of `count` use `length`?

2022-08-11 22:14 UTC, ST-DDT commented on test/string.spec.ts
> +    describe(`seed: ${seed}`, () => {
This should use the seededTestFactory.

2022-08-13 11:37 UTC, Shinigami92 requested changes
**BLOCKED**: we cannot name the module `String` as this is the JavaScript global String constructor and we would run into the same issues as with `_Date` module (were we actually also want to find a better name for, like e.g. `DateModule` or `Temporal`)

If we name it `StringModule` please first merge #932

2022-09-09 23:54 UTC, ST-DDT commented on src/modules/string/index.ts
> +  hexadecimal(length = 1): string {
Why no `case` option here?

2022-09-09 23:54 UTC, ST-DDT commented on src/modules/string/index.ts
> +      const value = placeholder === 'x' ? random : (random & 0x3) | 0x8;
```suggestion
      const value = placeholder === 'x'
          ? this.faker.datatype.number({ min: 0, max: 15 }) 
          : this.faker.datatype.number({ min: 8, max: 11 });
```

Or however this should be formatted.

2022-09-10 09:12 UTC, xDivisionByZerox commented
We should consider a `string.special` method which returns a string of a given length (or default) with only special characters (example: '!', '"', '$').

2022-09-10 09:21 UTC, xDivisionByZerox commented on src/modules/string/index.ts
> +      const value = placeholder === 'x' ? random : (random & 0x3) | 0x8;
Why is this implemented like this anyway? Can we just do 2 `replace` cycles on the template (one for 'x' and one for 'y')?

2022-09-10 09:29 UTC, ST-DDT commented on src/modules/string/index.ts
> +      const value = placeholder === 'x' ? random : (random & 0x3) | 0x8;
It might be a neglible performance thing.
For me, it isn't that important.
What do the others think is best?

2022-09-10 09:36 UTC, ST-DDT commented
Sounds like a useful method.
It should have a docs comment that it can be used to test value escaping, so that users can tell what the method is for more easily.

I would also suggest a method that returns higher unicode/UTF-8 characters (e.g. `ä¿`, some non latin letters,...) to check for encoding errors.

2022-10-17 17:50 UTC, Shinigami92 commented on src/modules/string/index.ts
> +  random(length = 10): string {
I named it `sample`

2022-10-17 17:57 UTC, Shinigami92 commented on src/modules/string/index.ts
> +      const value = placeholder === 'x' ? random : (random & 0x3) | 0x8;
Uh this looks heavy... 😖
Is it okay if I don't touch this for now in this PR?
Should we add a TODO, create an issue or just open another PR after this got merged?

2022-10-17 17:58 UTC, Shinigami92 commented
> We should consider a `string.special` method which returns a string of a given length (or default) with only special characters (example: '!', '"', '$').

> Sounds like a useful method.
It should have a docs comment that it can be used to test value escaping, so that users can tell what the method is for more easily.
> 
> I would also suggest a method that returns higher unicode/UTF-8 characters (e.g. `ä¿`, some non latin letters,...) to check for encoding errors.

Lets extract this to it's own issue (if not already happen)

2022-10-17 18:01 UTC, Shinigami92 commented
@ST-DDT Okay I think I have done everything except the rewrite of the tests to use the factory.
I run out of time for today, would you like to rewrite them today? Otherwise I will do that tomorrow. 🤗

2022-10-17 20:29 UTC, Shinigami92 commented on src/modules/string/index.ts
> +          bannedChars?: readonly LiteralUnion<AlphaNumericChar>[] | string;
Extracted to https://github.com/faker-js/faker/issues/1465#issue-1412183179

2022-10-17 20:33 UTC, Shinigami92 commented on src/modules/string/index.ts
> +      const value = placeholder === 'x' ? random : (random & 0x3) | 0x8;
Extracted to https://github.com/faker-js/faker/issues/1466

2022-10-17 21:44 UTC, ST-DDT commented
I'm not sure whether `casing` should be `case` instead.
In JS the method is called `to lower/upper case` as well.

If I google for [character case](https://www.google.com/search?q=character+case) I get 6.390.000.000 results.
If I google for [character casing](https://www.google.com/search?q=character+casing) I only get 21.700.000 results.
That's more than two orders of magnitude in difference!

Could a native English speaker comment whether (char) `casing` is a real word and which one is the correct one context wise?

2022-10-17 21:52 UTC, Shinigami92 commented
I decided against case because in some context it can be conflict with switch-case.
I explicitly want to move away from Parameter names that can collide with JS or TS syntax.

If you have another parameter name proposal, please tell us.

2022-10-17 22:12 UTC, import-brain requested changes

2022-10-17 22:12 UTC, ejcheng commented on src/modules/random/index.ts
> +   * @see faker.string.alphaNumeric()
```suggestion
   * @see faker.string.alphanumeric()
```

2022-10-17 22:12 UTC, import-brain commented on src/modules/vehicle/index.ts
> +    })}`.toUpperCase();
```suggestion
    })}${this.faker.string.alpha({
      length: 3,
      casing: 'upper',
    })}`
```
Isn't the `toUpperCase()` call here redundant?

2022-10-17 22:14 UTC, ST-DDT requested changes

2022-10-17 22:14 UTC, ST-DDT commented on src/modules/string/index.ts
> +    const { casing = 'mixed', length = 1 } = options;
Might be nit picky:

```suggestion
    const { length = 1, casing = 'mixed' } = options;
```

For consistency with the signature + other methods.

Alternatively, sort the deconstructors alphabetically, if possible.

2022-10-17 22:14 UTC, ST-DDT commented on test/random.spec.ts
> +              casing: 'lower',
AFAICT this isn't needed because all characters are banned.

2022-10-17 22:14 UTC, ST-DDT commented on test/string.spec.ts
> +        .it('with casing', { casing: 'mixed' })
Please give them unique names, so it doesn't break if you move them.

e.g. `with casing = lower`

2022-10-17 22:14 UTC, ST-DDT commented on test/string.spec.ts
> +        .it('with casing', { casing: 'mixed' })
Same here.

2022-10-17 22:14 UTC, ST-DDT commented on test/string.spec.ts
> +        .it('with casing', { casing: 'mixed' })
And here

2022-10-17 22:14 UTC, ST-DDT commented on test/string.spec.ts
> +        .it('with casing', { allowLeadingZeros: true })
```suggestion
        .it('with allowLeadingZeros', { allowLeadingZeros: true })
```

2022-10-17 22:14 UTC, ST-DDT commented on test/string.spec.ts
> +      t.it('noArgs').itRepeated('repeated', 5, 5);
```suggestion
      t.it('noArgs').itRepeated('with length parameter', 5, 5);
```

2022-10-17 22:14 UTC, ST-DDT commented on test/string.spec.ts
> +    });
```suggestion
    t.itRepeated('uuid', 5);
```

2022-10-17 22:14 UTC, ST-DDT commented on test/string.spec.ts
> +        .itRepeated('repeated', 5, 5)
```suggestion
        .itRepeated('with length parameter', 5, 5)
```

2022-10-17 22:14 UTC, ST-DDT commented on test/string.spec.ts
> +        .it('with length', { length: 6 })
Why no length parameter check here?

```suggestion
        .itRepeated('with length parameter', 5, 5)
        .it('with length', { length: 6 })
```

2022-10-17 22:14 UTC, ST-DDT commented on test/string.spec.ts
> +        .itRepeated('repeated', 5, 5)
```suggestion
        .itRepeated('with length parameter', 5, 5)
```

2022-10-17 22:14 UTC, ST-DDT commented on test/string.spec.ts
> +        .itRepeated('repeated', 5, 5)
```suggestion
        .itRepeated('with length parameter', 5, 5)
```

2022-10-17 22:14 UTC, ST-DDT commented on src/modules/string/index.ts
> +  sample(length = 10): string {
Why doesn't this have options?

2022-10-18 06:32 UTC, Shinigami92 commented on src/modules/string/index.ts
> +  sample(length = 10): string {
We copied it over from `random.string`
Should we enhance the signature in #1349 ?

2022-10-18 06:46 UTC, Shinigami92 commented on test/string.spec.ts
> +        .it('with length', { length: 6 })
`hexadecimal` doesn't have a only number option => also moved to #1349

2022-10-18 11:54 UTC, import-brain commented on test/string.spec.ts
> +        });
```suggestion
        .it('with bannedDigits', { bannedDigits: '12345' })
        .it('with length, allowLeadingZeros and bannedDigits', {
          length: 7,
          allowLeadingZeros: true,
          bannedDigits: '12345',
        });
```
Should this be `bannedDigits` because the parameter is called `bannedDigits`, or are we using `bannedChars` for everything?

2022-10-18 12:40 UTC, Shinigami92 commented on test/string.spec.ts
> +        });
You are right, was a copy paste issue

2022-10-18 12:46 UTC, import-brain approved these changes, later dismissed

2022-10-18 12:50 UTC, Shinigami92 approved these changes

2022-10-18 13:31 UTC, ejcheng approved these changes

2022-10-18 17:16 UTC, ST-DDT approved these changes
There are some inconsistencies in this PR that needs to be resolved in later PRs as part of https://github.com/faker-js/faker/issues/1349 and avoided in future PRs .

e.g. the alphaNumeric function changed its signature during the move, but similar signature adjustments in other methods were moved to new/separate issues.

I only approve this because this is a massive PR, fixing these would make the PR even harder to review than it is already. 
It also blocks further development and we have issues to track the remaining todos.

2022-10-18 17:29 UTC, merged