refactor(fake): move to `helpers`
faker-js/faker pull request #1161
Opened 2022-07-18 15:47 UTC by xDivisionByZerox

This PR moves the `fake()` method from the `Fake` module into the `Helpers` module. The reason is, that there is no reason for it being a standalone module when it is clearly a utility method. 

This was also discussed in #805 ([direct link](https://github.com/faker-js/faker/discussions/805#discussioncomment-2539551)).

2022-07-18 16:44 UTC, pkuczynski submitted a review, later dismissed

2022-07-18 19:54 UTC, Shinigami92 reviewed
Also just add a deprecation JSDoc Tag to the module + its constructor

Did you also update references in docs and readme?

2022-07-18 21:06 UTC, xDivisionByZerox commented
> Also just add a deprecation jedoch Tag to the module + its constructor

This is not possible since this would log a warning on Faker instance creation, which violates one of our test suites. I mean I can still add a JSDoc with a `@deprecated` parameter, but no deprecated function call in constructor.

2022-07-19 00:52 UTC, Shinigami92 commented
> > Also just add a deprecation jedoch Tag to the module + its constructor
> 
> 
> 
> This is not possible since this would log a warning on Faker instance creation, which violates one of our test suites. I mean I can still add a JSDoc with a `@deprecated` parameter, but no deprecated function call in constructor.

Good catch, that's true

2022-07-19 00:53 UTC, Shinigami92 submitted a review, later dismissed

2022-07-19 02:48 UTC, ST-DDT submitted a review, later dismissed

2022-07-20 09:37 UTC, pkuczynski submitted a review, later dismissed

2022-07-22 18:05 UTC, import-brain submitted a review, later dismissed

2022-07-22 21:54 UTC, xDivisionByZerox commented
We had 4 individual approvals and this is non blocking. I think we can merge this.

2022-07-23 04:35 UTC, ST-DDT commented
The tests seem to fail.

2022-07-23 06:46 UTC, xDivisionByZerox commented
That's odd, but I'll have a look.

2022-07-23 14:51 UTC, xDivisionByZerox commented
> The tests seem to fail.

It was a missing test with the new test factory. @ST-DDT can you have a look if I've done this the right way?

2022-07-23 15:18 UTC, ST-DDT requested changes

2022-07-23 15:18 UTC, ST-DDT commented on test/helpers.spec.ts
> +      t.it('with plain string', 'my test string');
Yes, this is correct, but please also try a with an actual template and a template with params.

2022-07-23 18:00 UTC, xDivisionByZerox commented on test/helpers.spec.ts
> +      t.it('with plain string', 'my test string');
But then the test for no seeds is useless or not? In that case, I don't get why we need to do this. May you explain or link to a source where you already gave information for the why? I just want to understand.

2022-07-23 18:04 UTC, xDivisionByZerox commented on test/helpers.spec.ts
> +      t.it('with plain string', 'my test string');
So what would we need all of this for?
https://github.com/faker-js/faker/blob/dd6f5a29d978177864c80438f05231f53b903d89/test/helpers.spec.ts#L487-L609

2022-07-23 18:23 UTC, ST-DDT commented on test/helpers.spec.ts
> +      t.it('with plain string', 'my test string');
The fixed seeded tests are meant to check the values with an equality check.
The random seeded tests are meant to check the values with a regex or a similar vague check.

The tests you quoted would still pass, if the result would be the original input with the template input joined together.

`faker.helpers.fake('{{phone.number}}')` -> `'{{phone.number}}1234'`
The seeded tests uncover these issues, if you read the snap file changes carefully.
The random seeded don't (always) do the same.

2022-07-26 09:47 UTC, ST-DDT approved these changes, later dismissed

2022-07-26 15:41 UTC, import-brain commented on test/helpers.spec.ts
> +        it('should be able to handle reverted brackets', () => {
```suggestion
        it('should be able to handle inverted brackets', () => {
```

2022-07-26 18:44 UTC, pkuczynski commented
I am wondering if we should keep this function public? Whatever this function does is available via string templates. As a downside it requires users to know shape of the definitions and prevent us from strong typings. So what's the point of having it exposed publicly?

2022-07-26 19:57 UTC, xDivisionByZerox commented
> I am wondering if we should keep this function public? Whatever this function does is available via string templates. As a downside it requires users to know shape of the definitions and prevent us from strong typings. So what's the point of having it exposed publicly?

So you propose to deprecate this feature (which would make moving it unnecessary). Do I understand you correctly? If so please open a discussion or issue where we can debate the pros and cons of moving and deprecating. Please also link to this PR and other discussions, issues, and comments where this was already proposed/argued.

This PR has the goal to move the `fake` function into a different module. I don't want to discuss anything groundbreaking different here. 

That said, I will put this PR `on-hold` so there is no work done until your proposal is discussed.

2022-07-26 23:49 UTC, ST-DDT commented
IMO we should move faker.fake short term.

If we are going to remove it, then we need a concept on how to deal with the templates that currently rely on the faker.fake method such as findName, fullName etc. There might be a way to do that, but this requires detailed planning and feedback from the community.
We can discuss the next steps in our next team meeting.

2022-07-30 09:51 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * (e.g. string coming from a user, stored in a database or a file).
We have another issue/pr somewhere that thinks about fully remove `fake`
But this is IMO the reason why we CANNOT remove it at all and why it has an existential purpose!

2022-07-30 09:54 UTC, Shinigami92 approved these changes
The implementation is approved, but I think this PR needs a rebase as it is older than the test overhaul, is it?

2022-07-30 10:14 UTC, pkuczynski commented on src/modules/helpers/index.ts
> +   * (e.g. string coming from a user, stored in a database or a file).
We can remove it from the public interface as it looks to deeply into our localization shapes. It made sense when string templates were not the thing, but now they are, so it can be deprecated in favor of it. I listed all the reasons in our meeting notes from 2022-07-28, have a look...

2022-07-30 10:55 UTC, ST-DDT commented
> but I think this PR needs a rebase as it is older than the test overhaul, is it?

It has been updated since.

2022-07-30 10:57 UTC, ST-DDT approved these changes

2022-07-30 10:57 UTC, merged

2022-09-03 03:06 UTC, 1LISA2 commented
![下载](https://user-images.githubusercontent.com/103248540/188252909-62b73d67-df77-4458-a5f8-483a8bcf1d48.jpeg)
![下载 (1)](https://user-images.githubusercontent.com/103248540/188252910-1593e4a6-8c66-4f4f-94bc-2776f95b49b0.jpeg)
very nice