feat(locales.pl): add pl translation for gender and binary gender
faker-js/faker pull request #1162
Opened 2022-07-18 19:19 UTC by hankucz

2022-07-18 19:59 UTC, Shinigami92 submitted a review, later dismissed

2022-07-19 03:07 UTC, ST-DDT approved these changes

2022-07-19 03:07 UTC, ST-DDT commented on src/locales/pl/name/gender.ts
> +  'Transeksualny mężczyzna',
Just to confirm is this difference in spelling intentional? Google translate seems a bit confused here.

2022-07-20 09:34 UTC, pkuczynski commented on src/locales/pl/name/gender.ts
> +  'Transeksualny mężczyzna',
No, that's error! Very good catch! :)

2022-07-20 09:43 UTC, hankucz commented on src/locales/pl/name/gender.ts
> +  'Transeksualny mężczyzna',
Thank you for noticing, it is an error. Just fixed it :)

2022-07-20 09:54 UTC, pkuczynski approved these changes

2022-07-21 04:50 UTC, ST-DDT approved these changes

2022-07-21 04:56 UTC, ST-DDT requested changes
Please remove the unrelated commits/reverts from this PR by either rebasing/squashing and filtering the commits.

2022-07-21 07:22 UTC, pkuczynski commented
Whats the difference? We will squash on merge anyway, right?

2022-07-21 09:41 UTC, Shinigami92 submitted a review, later dismissed

2022-07-21 09:41 UTC, Shinigami92 commented on .eslintrc.js
> -    ],
This needs to be reverted

2022-07-21 09:41 UTC, Shinigami92 commented on src/modules/date/index.ts
> -// eslint-disable-next-line @typescript-eslint/naming-convention
This needs to be reverted

2022-07-21 09:41 UTC, Shinigami92 commented on src/modules/name/index.ts
> -  // eslint-disable-next-line @typescript-eslint/naming-convention
This needs to be reverted

2022-07-26 16:19 UTC, hankucz commented
All unnecessary changes have been reverted. @ST-DDT @Shinigami92 could you please re-review and merge?

2022-07-26 16:33 UTC, pkuczynski approved these changes

2022-07-26 17:25 UTC, xDivisionByZerox commented
> The current build failure is the timeout in `test/scripts/apidoc/examplesAndDeprecations.spec.ts`, which is not related to my PR. I am not sure if I have to do anything about it?

I opened an issue for it (#1193) since I struggle with it as well.

2022-07-26 17:33 UTC, xDivisionByZerox approved these changes

2022-07-26 18:40 UTC, pkuczynski approved these changes

2022-07-26 21:55 UTC, ST-DDT approved these changes

2022-07-26 22:02 UTC, merged