chore: rename Gender to Sex and use enum instead of string values
faker-js/faker pull request #1163
Opened 2022-07-18 20:26 UTC by hankucz

Fixes #352

Questions:
* I don't know how to deprecate `Gender` type in favor of `Sex`
* I haven't added `Intersex` nor `Nonbinary` to the enum, as I felt that the way it is used, it would be better not to specify the sex, which would lead to randomizing the value despite the sex. For example 'faker.name.firstName()` would provide either a female or male first name, which IMHO would provide inclusivity for non-binary data...
* I could also create a separate category of names, which are not sex-specific, like `Alex, Max, Sam, etc` and then I could add a new enum value for picking them up. Although some (or maybe even many) languages do not have such names (eg. in Polish, every female name must end with an `a`, and if a name does not, it is considered male - there are no exceptions to this rule).
* Some other fixes in this module will follow in a separate PR, for example #352

2022-07-18 20:36 UTC, xDivisionByZerox commented
> I don't know how to deprecate Gender type in favor of Sex

As far as I can tell there is no way to do that other than documentation since the type will be gone as soon as the TypeScript code is compiled to JavaScript.

> I haven't added Intersex nor Nonbinary to the enum, as I felt that the way it is used, it would be better not to specify the sex, which would lead to randomizing the value despite the sex. For example 'faker.name.firstName()` would provide either a female or male first name, which IMHO would provide inclusivity for non-binary data...

> I could also create a separate category of names, which are not sex-specific, like Alex, Max, Sam, etc and then I could add a new enum value for picking them up. Although some (or maybe even many) languages do not have such names (eg. in Polish, every female name must end with an a, and if a name does not, it is considered male - there are no exceptions to this rule).

We have already talked about this possibility in a team meeting. But, you also came to the conclusion that it's not as easy as just providing an extra set of names to pick from (your Polish example). Because of that, we decided to keep the options as they are, for now. When the library is considered stable and easier maintainable we will think about such features.

2022-07-18 20:40 UTC, xDivisionByZerox commented on src/modules/name/index.ts
> +  Male = 'male',
Seems like we do not have any linter rules for this. But, it's common sense/best practice to have enum values written in UPPER_SNAKE_CASE. Might also be that I'm just really biased about formatting. I'd like at least one maintainer to comment on this, before flagging it as required.

2022-07-18 20:52 UTC, xDivisionByZerox commented
The current change would be considered a breaking change since the Gender enum would be removed. But like I said in an earlier comment, I'm not sure if you can deprecate and enum. I'm just pinging @Shinigami92 and @ST-DDT so they will see this (but they are currently on vacation).

One other think is that I'd like to get the additional type (now `SexValue`) removed. But this doesn't belong in this PR. Just leaving this here for reference.

Otherwise this looks good to me.

2022-07-19 00:45 UTC, Shinigami92 commented on src/index.ts
> -export type { GenderType } from './modules/name';
These should not be removed, but just marked as deprecated

So I expect this:

```ts
export { Gender, Sex } from './modules/name';
export type { GenderType, SexType } from './modules/name';
```

2022-07-19 00:45 UTC, Shinigami92 commented on src/modules/name/index.ts
> +  Male = 'male',
That is more a Java thing I think
If you look into https://www.typescriptlang.org/docs/handbook/enums.html it is more driven by C# and they use PascalCase

2022-07-19 00:45 UTC, Shinigami92 commented on src/modules/name/index.ts
> +type SexValue = `${Sex}`;
```suggestion
export type SexValue = `${Sex}`;
```

2022-07-19 00:45 UTC, Shinigami92 commented on src/modules/name/index.ts
> +  sex: Sex | SexValue | undefined,
Theoretically this is duplicated 🤔 
The enum in TypeScript is not really a real thing but will be resolved as its string replacement
So now we have the final type: `'female' | 'male' | 'female' | 'male' | undefined`

I personally would prefer to only use the string value or the types everywhere but not the enum directly
The enum should only be something for an enduser for better UX to be used

I will let decide and discuss with @ST-DDT which strategy we should use (also for future occurrences)

2022-07-19 02:59 UTC, ST-DDT commented on src/modules/name/index.ts
> +  sex: Sex | SexValue | undefined,
IMO we should only apply minimal neccessary changes in this PR e.g. deprecate Gender* and replace it with Sex*.

2022-07-19 10:14 UTC, hankucz commented on src/modules/name/index.ts
> +  Male = 'male',
@pkuczynski also favored using `FEMALE`, but I checked what TypeScript documentation says, and their examples were written with PascalCase. So I am not sure what to do now...

2022-07-19 10:16 UTC, Shinigami92 commented on src/modules/name/index.ts
> +  Male = 'male',
PascalCase

2022-07-19 10:19 UTC, hankucz commented
> The current change would be considered a breaking change since the Gender enum would be removed. But like I said in an earlier comment, I'm not sure if you can deprecate and enum.

I am not sure if anybody would use the enum, as initially, I changed types to use it, and all tests were failing compilation when called with strings like `firstName('female')`, which is how they all were documented. I was thinking whether it makes sense to export the enum at all, and maybe only use the string type? Eventually, I decided to go with both but export only enum. What do you think?

> One other think is that I'd like to get the additional type (now SexValue) removed. But this doesn't belong in this PR. Just leaving this here for reference.

I can't do it, if we want to support param values as strings, eg `firstName('female')` - or I don't know how to do it...

2022-07-19 10:20 UTC, hankucz commented on src/index.ts
> -export type { GenderType } from './modules/name';
How to make it depreacted? Both @pkuczynski and @xDivisionByZerox said it's not possible...

2022-07-19 10:21 UTC, hankucz commented on src/modules/name/index.ts
> +type SexValue = `${Sex}`;
What's the value of exporting it? I thought we would rather like to drive people to use enum?

2022-07-19 10:28 UTC, hankucz commented on src/modules/name/index.ts
> +  sex: Sex | SexValue | undefined,
@Shinigami92 as I explained in the other comment, when I kept using only enum, it was getting type errors in my IDE:

<img width="885" alt="image" src="https://user-images.githubusercontent.com/108692126/179729328-6e72f735-fa25-4773-bb3a-2e2f21d08ca0.png">

Bear in mind, that this enum was not used internally either...

2022-07-19 10:29 UTC, hankucz commented on src/modules/name/index.ts
> +  sex: Sex | SexValue | undefined,
@ST-DDT changing only the enum was not enough, as I also had to change param names and documentation. So I felt that using this enum would make even more sense, as now we have it done properly... Please advise what shall I do?

2022-07-19 10:52 UTC, Shinigami92 commented on src/modules/name/index.ts
> +type SexValue = `${Sex}`;
No, we do not force people to use enums.
Enums in TypeScript are theoretically a design issue, as enums doesn't exist in JavaScript.
At the end of the day only numbers or strings are there after the compiled output.
So these are only there for TypeScript users who like using enums. It's only for UX

2022-07-19 10:52 UTC, Shinigami92 commented on src/index.ts
> -export type { GenderType } from './modules/name';
```ts
/**
 * @deprecated
 */
export enum Gender {
  female = 'female',
  male = 'male',
}
```

2022-07-19 10:52 UTC, Shinigami92 commented on src/modules/name/index.ts
> +  sex: Sex | SexValue | undefined,
Wait what? 👀 I need to test that out, I was not aware that these wont work. Maybe we decided to not use const enums but with non const enums it is not working anymore or something like this.

2022-07-19 10:54 UTC, Shinigami92 commented on src/modules/name/index.ts
> +  sex: Sex | SexValue | undefined,
When I try it in main branch it works fine:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/7195563/179733950-71f6636c-84be-44f0-8969-a05d61a23301.png">

2022-07-19 12:01 UTC, hankucz commented on src/index.ts
> -export type { GenderType } from './modules/name';
Done...

2022-07-19 12:03 UTC, hankucz commented on src/modules/name/index.ts
> +type SexValue = `${Sex}`;
Ok, I understand; however, if we export the enum, should we still export the basic type? Wouldn't this be redundant?

2022-07-19 12:03 UTC, xDivisionByZerox commented on src/modules/name/index.ts
> +  Male = 'male',
TBH, I don't really care, as long as it is consistent. We could use [`@typescript-eslint´/naming-convention`](https://typescript-eslint.io/rules/naming-convention/) to ensure this. But that's a topic for another PR.

2022-07-19 12:09 UTC, xDivisionByZerox commented on src/modules/name/index.ts
> +type SexValue = `${Sex}`;
It's not redundant since a user (that don't like enums) could potentially explicitly type their variables.
```
import { faker, SexValue } from '@faker-js/faker';

const sex: SexValue = 'female';
const name = faker.name.firstName(sex);
```

2022-07-19 12:11 UTC, hankucz commented on src/modules/name/index.ts
> +  sex: Sex | SexValue | undefined,
Yes, this works if I keep definition as `firstName(sex?: Sex | SexValue): string` or  change it to `firstName(sex?: SexValue): string` (as it is currently).

It did not work when I had it as enum: `firstName(sex?: Sex): string`

So should I keep `sex?: Sex | SexValue` or just change it to plain `sex?: SexValue`?

2022-07-19 12:46 UTC, pkuczynski commented on src/modules/name/index.ts
> +type SexValue = `${Sex}`;
Do you really think someone would do that instead of:

```
import { faker, Sex } from '@faker-js/faker';

const sex: Sex = Sex.Female;
const name = faker.name.firstName(sex);
```

I really doubt it. If anybody is into typescript, he would use enums to abstract string values. If he is into plain js, he would use strings.

2022-07-19 12:47 UTC, pkuczynski commented on src/modules/name/index.ts
> +type SexValue = `${Sex}`;
I also think that `SexValue` sucks as a name and having both `Sex` and `SexValue` is odd...

2022-07-19 14:46 UTC, Shinigami92 commented on src/modules/name/index.ts
> +  sex: Sex | SexValue | undefined,
`firstName(sex?: SexType): string`
and rename `SexValue` "back" to `SexType` as previous `GenderType`

2022-07-19 14:49 UTC, Shinigami92 commented on src/modules/name/index.ts
> +  Male = 'male',
@xDivisionByZerox would you like to open a PR for https://typescript-eslint.io/rules/naming-convention/?

2022-07-19 14:50 UTC, Shinigami92 commented on src/index.ts
> -export type { GenderType } from './modules/name';
The `GenderType` is still missing, as same as the `SexType`

2022-07-19 14:52 UTC, Shinigami92 commented on src/modules/name/index.ts
> +  firstName(sex?: Sex | SexValue): string {
```suggestion
  firstName(sex?: SexType): string {
```

2022-07-19 14:52 UTC, Shinigami92 commented on src/modules/name/index.ts
> +  lastName(sex?: Sex | SexValue): string {
```suggestion
  lastName(sex?: SexType): string {
```

2022-07-19 14:53 UTC, Shinigami92 commented on src/modules/name/index.ts
> +  middleName(sex?: Sex | SexValue): string {
```suggestion
  middleName(sex?: SexType): string {
```

2022-07-19 14:54 UTC, Shinigami92 commented on src/modules/name/index.ts
> +    sex?: Sex | SexValue
We need to bring back the gender option property as this is needed as a fallback and a deprecation warning should be logged when using it

2022-07-19 14:54 UTC, Shinigami92 commented on src/modules/name/index.ts
> +    sex?: Sex | SexValue
```suggestion
    sex?: SexType
```

2022-07-19 14:55 UTC, Shinigami92 commented on src/modules/name/index.ts
> +      sex?: Sex | SexValue;
Same here with gender property

+

```suggestion
      sex?: SexType;
```

2022-07-19 14:55 UTC, Shinigami92 commented on src/modules/name/index.ts
> +      sex = this.faker.helpers.arrayElement([Sex.Female, Sex.Male]),
```suggestion
      sex = this.faker.helpers.arrayElement<SexType>(['female', 'male']),
```

2022-07-19 14:56 UTC, Shinigami92 commented on src/modules/name/index.ts
> +  prefix(sex?: Sex | SexValue): string {
```suggestion
  prefix(sex?: SexType): string {
```

2022-07-19 15:00 UTC, xDivisionByZerox commented on src/modules/name/index.ts
> +  Male = 'male',
Yes, I really like having rules and documentation^^

2022-07-20 10:05 UTC, hankucz commented on src/modules/name/index.ts
> +  sex: Sex | SexValue | undefined,
OK. Done

2022-07-21 10:22 UTC, Shinigami92 requested changes

2022-07-21 10:22 UTC, Shinigami92 commented on src/index.ts
> +export type { Gender, GenderType, Sex, SexType } from './modules/name';
`Gender` and `Sex` (the enums) needs to be a **real** export, not a `export type`

2022-07-21 10:22 UTC, Shinigami92 commented on src/modules/name/index.ts
> +
We can remove these unnecessary newline
```suggestion
```

2022-07-21 10:22 UTC, Shinigami92 commented on src/modules/name/index.ts
> +
We can remove these unnecessary newline
```suggestion
```

2022-07-21 10:22 UTC, Shinigami92 commented on src/modules/name/index.ts
> +
We can remove these unnecessary newline
```suggestion
```

2022-07-21 14:59 UTC, pkuczynski commented on src/modules/name/index.ts
> +  findName(firstName?: string, lastName?: string, sex?: SexType): string {
@Shinigami92 it does not make sense what you are saying. It's not a hash, these were just params. So there is no need nor way to deprecate :)

2022-07-21 15:01 UTC, pkuczynski commented on src/modules/name/index.ts
> +
Its a nice separation of the cases and its not against prettier or eslint settings. I like it and I would keep it. Keeps the code more readable.

2022-07-21 15:01 UTC, pkuczynski commented on src/modules/name/index.ts
> +
Its a nice separation of the cases and its not against prettier or eslint settings. I like it and I would keep it. Keeps the code more readable.

2022-07-21 15:01 UTC, pkuczynski commented on src/modules/name/index.ts
> +
Its a nice separation of the cases and its not against prettier or eslint settings. I like it and I would keep it. Keeps the code more readable.

2022-07-21 15:02 UTC, pkuczynski commented on src/modules/name/index.ts
> +      sex = this.faker.helpers.arrayElement([Sex.Female, Sex.Male]),
What's the point of having enum if we can't use it? I am against the suggested change.

2022-07-21 15:02 UTC, pkuczynski commented on src/modules/name/index.ts
> +    case Sex.Female:
What's the point of having enum if we can't use it? I am against the suggested change.

2022-07-26 16:29 UTC, hankucz commented
@xDivisionByZerox @ST-DDT @Shinigami92 is this ready for merge? I left some unresolved comments from @Shinigami92 - can you help me with this, as I am not sure if I should tackle them or not as it seems there are some contradictory opinions...

2022-07-26 17:15 UTC, pkuczynski approved these changes

2022-07-26 18:45 UTC, pkuczynski approved these changes

2022-07-26 22:25 UTC, ST-DDT commented on src/modules/name/index.ts
> +  findName(firstName?: string, lastName?: string, sex?: SexType): string {
@pkuczynski is right, this isn't an options object where the name is important, in this case its only relevant that the index remains the same.

2022-07-26 23:06 UTC, ST-DDT submitted a review, later dismissed
Looks good to me. For me it works with both the enum values and inline string values.

2022-07-27 23:00 UTC, import-brain approved these changes

2022-07-30 10:08 UTC, Shinigami92 approved these changes

2022-07-30 10:50 UTC, xDivisionByZerox commented on src/modules/name/index.ts
> + * @deprecated
In our [deprecation workflow documentation](https://github.com/faker-js/faker/blob/main/CONTRIBUTING.md#deprecation-workflow) we require a human-readable message for the `deprecated` JSDoc parameter.

```suggestion
 * @deprecated Use Sex enum instead.
```

2022-07-30 10:51 UTC, xDivisionByZerox commented on src/modules/name/index.ts
> + * @deprecated
In our [deprecation workflow documentation](https://github.com/faker-js/faker/blob/main/CONTRIBUTING.md#deprecation-workflow) we require a human-readable message for the `deprecated` JSDoc parameter.

```suggestion
 * @deprecated Use SexType instead.
```

2022-07-30 10:59 UTC, xDivisionByZerox commented on src/modules/name/index.ts
> +
Someone should definitely propose a linter setting that handles these cases. IMO, a reviewer should not have to bother with this kind of change. If it is allowed (pipeline doesn't fail), cool - get on.

2022-08-01 13:40 UTC, hankucz commented
Suggestions from @xDivisionByZerox are done. Is this ready for merge?

2022-08-01 13:40 UTC, pkuczynski submitted a review, later dismissed

2022-08-01 14:07 UTC, Shinigami92 commented on src/modules/name/index.ts
> +        proposed: `faker.name.fullName({ sex: '...'})`,
```suggestion
        deprecated: `faker.name.fullName({ gender: '...' })`,
        proposed: `faker.name.fullName({ sex: '...' })`,
```

2022-08-01 14:08 UTC, Shinigami92 approved these changes

2022-08-01 16:27 UTC, ST-DDT approved these changes

2022-08-01 16:27 UTC, merged