Refactor/company/change company name to name
faker-js/faker pull request #1166
Opened 2022-07-19 02:26 UTC by Minozzzi

Hi guys, I applied te deprecated workflow on function `company.companyName()`. And I have a suggestion to the new function created, the parameters could be an object instead array positions. What do you guys think?

2022-07-19 02:37 UTC, Shinigami92 commented
We are already really slowly migrate nearly all functions to using an options object as parameter, so yes 🙂

2022-07-19 02:50 UTC, ST-DDT reviewed
Instead of just copying the method you should call the new method from the old one.

2022-07-19 08:49 UTC, xDivisionByZerox requested changes

2022-07-19 08:49 UTC, xDivisionByZerox commented on src/modules/company/index.ts
> +
Please call `this.name(format);` here instead of "reimplementing" the function as @ST-DDT stated.

2022-07-19 21:10 UTC, xDivisionByZerox submitted a review, later dismissed

2022-07-20 00:44 UTC, import-brain approved these changes

2022-07-20 00:47 UTC, import-brain requested changes
Hmm, deprecation tests are failing...👀

2022-07-20 01:39 UTC, ST-DDT commented
> FAIL  test/scripts/apidoc/examplesAndDeprecations.spec.ts > examples and deprecations > Finance > transactionDescription
> AssertionError: expected "warn" to not be called at allexpected "warn" to not be called at all
> Received: 
>     1st warn call:
>     Array [
>       "[@faker-js/faker]: faker.company.companyName() is deprecated. Please use faker.company.name() instead..",
>     ]

It looks like finance.transactionDescription still calls company.companyName.

https://github.com/faker-js/faker/blob/05712b0c4d6fd6b2433eaa59c090f3f2a9290a17/src/modules/finance/index.ts#L427

2022-07-20 07:14 UTC, xDivisionByZerox commented on src/modules/company/index.ts
> +    });
Could you please add the `since` and `until` properties? `since` represents the version that the deprecation was merged in. So the next version would be `7.4`. `until` is the next major version, since we are allowed to make breaking changes there.

2022-07-20 12:54 UTC, xDivisionByZerox commented on src/modules/company/index.ts
> +    });
Correct

2022-07-20 14:54 UTC, Minozzzi commented
Corrected your comments 😁

2022-07-20 15:07 UTC, xDivisionByZerox approved these changes

2022-07-20 16:02 UTC, import-brain submitted a review, later dismissed

2022-07-21 02:20 UTC, ST-DDT commented on src/modules/company/index.ts
> +   *
Here are two new unnecessary empty lines.

2022-07-21 22:45 UTC, Minozzzi commented on src/modules/company/index.ts
> +   *
Good!

2022-07-22 00:04 UTC, import-brain approved these changes

2022-07-22 02:14 UTC, ST-DDT approved these changes

2022-07-22 03:04 UTC, merged