chore: lint switch case blocks
faker-js/faker pull request #1180
Opened 2022-07-22 10:36 UTC by Shinigami92

2022-07-22 10:44 UTC, ST-DDT reviewed
Not sure about the style itself, but I like to do it consistent.

2022-07-22 11:02 UTC, ST-DDT approved these changes

2022-07-22 13:02 UTC, pkuczynski requested changes

2022-07-22 13:02 UTC, pkuczynski commented on .eslintrc.js
> +        blankLine: 'never',
I am against this change. I really like those blank lines. They nicely separate multiline cases.

2022-07-22 13:02 UTC, pkuczynski commented on .eslintrc.js
> +        prev: ['case', 'default'],
What does it do? Put default as first?

2022-07-22 13:41 UTC, Shinigami92 commented on .eslintrc.js
> +        prev: ['case', 'default'],
There is a full documentation about this rule
Copied the content from there
Please read it

2022-07-22 13:41 UTC, Shinigami92 commented on .eslintrc.js
> +        blankLine: 'never',
I would like to have full consistency over the whole code base, so never or always but not mixed

2022-07-22 13:42 UTC, ST-DDT commented on .eslintrc.js
> +        prev: ['case', 'default'],
If you refer to something that others should read, please link it for simplicity sake.

2022-07-22 13:47 UTC, Shinigami92 commented on .eslintrc.js
> +        prev: ['case', 'default'],
That is currently a bit hard from mobile
If really interested make a 1s google or wait for ~24h until I have a laptop again with internet

2022-07-22 13:59 UTC, ST-DDT requested changes
The PR description is missing information about the source of the config and the available options aka why it is written/configured exactly like that.
Making it harder to understand the PR without looking at the changes and any external documentaion.

2022-07-22 21:36 UTC, xDivisionByZerox commented on .eslintrc.js
> +        prev: ['case', 'default'],
Im sorry, but if it is THAT hard for you to provide additional information of the things you have don't or link do additional source, it it that hard for you to wait 24h with opening this PR?

2022-07-22 21:46 UTC, xDivisionByZerox commented on .eslintrc.js
> +        prev: ['case', 'default'],
To provide information to the original question:

This configuration requires a new line before each `case` and `default` keyword.

2022-07-22 23:05 UTC, pkuczynski commented on .eslintrc.js
> +        blankLine: 'never',
There are cases when new line is good, and there are when its not. Thats how I would like to see formatting:

```js
switch (value) {
  case 'A': return 'a'
  case 'B': return 'b'
}

switch (value) {
  case 'A':
    console.log(value)
    next = some + operation
    break;

  case 'B':
    console.log(value)
    next = some + operation
    break;
}
```

This is more readable when some spacing is added between larger blocks of code. I would not like to be forced to glue them together. So we either leave it as it is or you provide config which supports such cases.

2022-07-22 23:06 UTC, pkuczynski commented on .eslintrc.js
> +        prev: ['case', 'default'],
I think this configuration prevents new line. And I know where its coming from: @hankucz did it with new lines in her PR and @Shinigami92 didnt like it...

2022-07-23 04:48 UTC, Shinigami92 commented
Okay, sorry seems to be my fault that I thought it would be a good idea to stop discussions about code style with an automated rule. But seems you prefer inconsistency 🤷

Also it was my fault to assume it would be a good idea to open a PR within my vacation and try to help with that. But yeah I was very wrong.
I think the best for me and my mental health is to close this and take another week of silence off from faker. Bye 👋

2022-07-23 04:48 UTC, closed without merging

2022-07-23 06:30 UTC, pkuczynski commented
@Shinigami92 don't take it like this! It's not fair, we all try to contribute, and everybody values your input a lot! Stay positive and let's talk about it :)

Do you see my point why it's sometimes ok to have line break in multiline case statements? Or you totally disagree?