fix: remove not allowed char `i` in bitcoinAddress generation
faker-js/faker pull request #1181
Opened 2022-07-22 19:06 UTC by import-brain

According to [the Bitcoin wiki](https://en.bitcoinwiki.org/wiki/Bitcoin_address), Bitcoin addresses "consist of random digits and uppercase and lowercase letters, with the exception that the uppercase letter "O", uppercase letter "I", lowercase letter "i", and the number "0" are never used to prevent visual ambiguity."

I noticed that when generating bitcoin addresses, `finance.bitcoinAddress()` excludes the characters `O`, `I`, and `0` successfully, but it does not exclude the lowercase character `i`.
https://github.com/faker-js/faker/blob/895799b23e8224eb1b623ef1d0ffd508f101389f/src/modules/finance/index.ts#L218-L221

I deleted the character `i` from the generation so that it doesn't show up in our bitcoin addresses. Also, I added regex in the non-seeded tests to check for the four prohibited characters.

2022-07-22 23:00 UTC, pkuczynski approved these changes

2022-07-23 04:47 UTC, ST-DDT requested changes
The refernced wiki page contains an example that contains an `i`:

> Bitcoin address example:
>
> > 14qViLJfdGaP4EeHnDyJbEGQysnCpwk3gd

2022-07-23 05:10 UTC, ST-DDT commented
Maybe we should just match the given validation method:
https://github.com/validatorjs/validator.js/blob/master/src/lib/isBtcAddress.js

2022-07-23 20:03 UTC, import-brain commented
> The refernced wiki page contains an example that contains an `i`:
> 
> > Bitcoin address example:
> > > 14qViLJfdGaP4EeHnDyJbEGQysnCpwk3gd

I just reread the wiki, I completely misread that text section I referenced, Bitcoin addresses do allow the lowercase character `i`. Looking back over the generation code, the function already excludes all prohibited characters, my bad.

2022-07-23 20:03 UTC, closed without merging