feat(image): Add Image placeholder module
faker-js/faker pull request #1186
Opened 2022-07-24 10:42 UTC by Devdre1909

Add support for https://placeholder.com/

width, height, text, format, background color, and text color supported

2022-07-24 12:28 UTC, xDivisionByZerox commented on src/modules/image/providers/placeholder.ts
> +   * @param textColor The text color of the placeholder. Requires `backgroundColor` Supports HEX CODE format
[Our JSDoc rules](https://github.com/faker-js/faker/blob/main/CONTRIBUTING.md#jsdocs) mentions:
> Sentences should always end with a period.

So could you please end any sentence here with one?

2022-07-24 12:35 UTC, xDivisionByZerox commented on src/modules/image/providers/placeholder.ts
> +    url += `/${width}/${height}`;
These lines could be combined. Or did you have any particular thoughts on separating them?

2022-07-24 12:50 UTC, xDivisionByZerox commented on src/modules/image/providers/placeholder.ts
> +   * Generates a new placeholder image url
Missing period.

2022-07-24 12:51 UTC, xDivisionByZerox commented on src/modules/image/providers/placeholder.ts
> +   * @param text The text of the image
Missing period.

2022-07-24 15:09 UTC, import-brain reviewed
We should specify that `width` and `height` are in pixels.

2022-07-24 15:09 UTC, import-brain commented on src/modules/image/providers/placeholder.ts
> +   * @param height The height of the image. Defaults to `480`.
```suggestion
   * @param width The width of the image (in pixels). Defaults to `640`.
   * @param height The height of the image (in pixels). Defaults to `480`.
```

2022-07-24 15:09 UTC, import-brain commented on src/modules/image/providers/placeholder.ts
> +   * @param height The height of the image. Defaults to `width`.
```suggestion
   * @param width The width of the image (in pixels). Defaults to `640`.
   * @param height The height of the image (in pixels). Defaults to `width`.
```

2022-07-24 16:35 UTC, Devdre1909 commented on src/modules/image/providers/placeholder.ts
> +   * @param text The text of the image
Okay, @xDivisionByZerox. Done.

2022-07-25 07:23 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +   * @param height The height of the image (in pixels). Defaults to `480`.
The default is not the same as the one used in the called method.

2022-07-25 17:28 UTC, ST-DDT requested changes

2022-07-25 17:28 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +    textColor?: string
Maybe we should use `options: {...}` here instead of this many parameters.

2022-07-25 17:28 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +  }
IMO this method does nothing extra to the `imageUrl` method and there is no other method that does use the `imageUrl` method, so maybe you can merge them into a single method?

2022-07-25 17:28 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +  }
On the other hand it would be nice, if there was a way to generate an image with random colors and texts, so you can just call it and get unique texts.

2022-07-25 17:28 UTC, ST-DDT commented on test/image.spec.ts
> +          'https://via.placeholder.com/100/200?text=I+love+food'
This image is not `100x200` it is `100x100` and uses the color `200`.

2022-07-25 17:46 UTC, Devdre1909 commented on src/modules/image/providers/placeholder.ts
> +    textColor?: string
Okay, I thought of this but I also thought it better to follow conversion from the other modules. I will use object instead.

2022-07-25 18:52 UTC, xDivisionByZerox commented on src/modules/image/providers/placeholder.ts
> +    textColor?: string
I would suggest to keep it with this many arguments for now so all image helper are consistent. At least for this PR. In the future we should refactor to a single optuons argument.

2022-07-27 15:05 UTC, Devdre1909 commented on src/modules/image/providers/placeholder.ts
> +    textColor?: string
Okay

2022-07-27 15:07 UTC, Devdre1909 commented on src/modules/image/providers/placeholder.ts
> +  }
Hi, @ST-DDT I added this method `randomUrl` in my late update but I'm not sure how to write the test for it since most of the values are generated at random except the width and height. Any suggestions, please?

2022-07-27 15:08 UTC, Devdre1909 commented on test/image.spec.ts
> +          'https://via.placeholder.com/100/200?text=I+love+food'
This is resolved since the method has been removed

2022-07-27 15:28 UTC, xDivisionByZerox commented on src/modules/image/providers/placeholder.ts
> +    return url;
Why can't wrong about:
```ts
return this.imageUrl(
  width,
  height,
  this.faker.lorem.text(),
  format,
  this.faker.color.rgb({
    casing: 'upper',
    prefix: '',
  }),
  this.faker.color.rgb({ casing: 'upper', prefix: '' }),
);
```
?

2022-07-27 15:34 UTC, Devdre1909 commented on src/modules/image/providers/placeholder.ts
> +    return url;
Smart, didn't think of this.
I will implement this now.

2022-07-27 16:06 UTC, ST-DDT requested changes

2022-07-27 16:06 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +   * @param text The text of the image.
Maybe add a hint what is shown if no/an empty text is selected

2022-07-27 16:06 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +   * @param textColor The text color of the placeholder. Requires `backgroundColor` Supports HEX CODE format.
Should we add a hint regarding the default color, if nothing is specified?

2022-07-27 16:06 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +    }
IMO if you write it like this, then it's easier to understand:

```suggestion
    if (backgroundColor != null) {
      url += `/${backgroundColor.replace('#', '').toUpperCase()}`;

      if (textColor != null) {
        url += `/${textColor.replace('#', '').toUpperCase()}`;
      }
    }
```

2022-07-27 16:06 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +   * @param format The file format of the image. Supports `png` `jpeg` `png` `gif` `webp`.
Maybe add a hint regarding the default format?

2022-07-27 17:06 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +  }
Maybe split on `/` and check whether the respective parts match some simple criteria. It doesn't have to be a fancy test.

2022-07-27 17:23 UTC, Devdre1909 commented on src/modules/image/providers/placeholder.ts
> +  constructor(private readonly faker: Faker) {}
I'm not sure what I'm supposed to do on this.

2022-07-27 17:24 UTC, Devdre1909 commented on src/modules/image/providers/placeholder.ts
> +   * @param text The text of the image.
Should I include an example like this?
<img width="712" alt="image" src="https://user-images.githubusercontent.com/49331266/181310415-c4dd7b70-d7a3-4133-a006-6c9e1611ad18.png">

2022-07-27 17:25 UTC, Devdre1909 commented on src/modules/image/providers/placeholder.ts
> +   * @param textColor The text color of the placeholder. Requires `backgroundColor` Supports HEX CODE format.
There is no default color placeholder.com handles the background and text color is none is specified.

2022-07-29 09:18 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +   * @param text The text of the image.
All methods should have an example section.

2022-07-29 09:19 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +  constructor(private readonly faker: Faker) {}
```suggestion
  constructor(private readonly faker: Faker) {
    // Bind `this` so namespaced is working correctly
    for (const name of Object.getOwnPropertyNames(_Date.prototype)) {
      if (name === 'constructor' || typeof this[name] !== 'function') {
        continue;
      }
      this[name] = this[name].bind(this);
    }
  }
```

2022-07-29 12:07 UTC, Minozzzi commented on src/modules/image/providers/placeholder.ts
> +    let url = 'https://via.placeholder.com';
Does it make sense to have a class-scoped variable as a constant instead this? For me this url is immutable

2022-07-29 13:45 UTC, Devdre1909 commented on src/modules/image/providers/placeholder.ts
> +  constructor(private readonly faker: Faker) {}
Hi, @ST-DDT I committed this change, but I don't think it's right. Other image modules didn't do this and there is no `_Date`

2022-07-29 13:50 UTC, xDivisionByZerox commented on src/modules/image/providers/placeholder.ts
> +  constructor(private readonly faker: Faker) {}
You have `_Date` as prototype class. I guess that's an error?

2022-07-29 14:24 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +    for (const name of Object.getOwnPropertyNames(_Date.prototype)) {
```suggestion
    for (const name of Object.getOwnPropertyNames(Placeholder.prototype)) {
```

2022-07-29 14:27 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +  constructor(private readonly faker: Faker) {}
Yeah, sorry thats my bad. I copied it from the date module.
I replaced it with Placeholder (the current class).

2022-07-29 14:28 UTC, ST-DDT commented
Please update the tests so the dont fail anymore.

2022-07-29 15:24 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +    let url = 'https://via.placeholder.com';
But it is only used in a single location, so there is no real benefit there.
Currently the other modules also don't specify a constant for that, so for consistency reasons we can stick to the current variant.

2022-07-29 15:40 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +      this.faker.lorem.text(),
This can generate very long phrases:
https://via.placeholder.com/640x640/DA03F2/B62C6C?text=Error+iusto+necessitatibus+amet+voluptatem.+Dolorum+officia+ratione+ad+a.+Expedita+accusamus+earum+rerum+vel+repellendus+ea.+Ipsum+perspiciatis+sed+dolorum.+Non+consequatur+beatae+et+et+aut+incidunt+impedit.%0AVeritatis+exercitationem+accusamus+laudantium+soluta.+Illo+nostrum+debitis+tempore.+Provident+sit+quaerat+facere+eius+officiis+quidem+aut+vel.+Velit+quaerat+magni.+Ea+optio+illum+porro+natus+quia+corporis.%0AUt+ut+inventore+consequatur+est+quisquam.+Maiores+odit+autem+ut+quis+amet+aut+fuga.+Numquam+vel+temporibus+sed+atque

Maybe a single word is enough?

2022-07-29 15:41 UTC, ST-DDT commented on src/modules/image/providers/placeholder.ts
> +   */
Please add `@examples`.

2022-08-05 13:49 UTC, ST-DDT commented
@Devdre1909 May I go ahead and fix these things to get this merged or do you wish to do this yourselves?

2022-08-06 03:01 UTC, Devdre1909 commented
> @Devdre1909 May I go ahead and fix these things to get this merged or do you wish to do this yourselves?

I will.
Thank you.

2022-08-06 08:55 UTC, ST-DDT approved these changes

2022-08-06 11:32 UTC, Shinigami92 approved these changes

2022-08-08 16:45 UTC, merged

2024-10-07 12:34 UTC, lk77 commented
> Issue #1111 Add support for https://placeholder.com/
> 
> width, height, text, format, background color, and text color supported

Hi @Devdre1909 ,

it seems to me that site does not exist anymore

2024-10-07 13:59 UTC, matthewmayer commented
See https://github.com/faker-js/faker/issues/2477

While the homepage of the site now promotes am unrelated business the images appear to continue to work for now.

2025-01-13 20:23 UTC, carusoray commented
It seems that the via.placeholder.com images API is not longer active. placeholder.com is still alive; however, via.placeholder.com does not resolve. Image URL within the test JSON are no longer valid.

2025-01-13 21:01 UTC, ST-DDT commented
Thanks for the report. We have deprecated it:

- https://github.com/faker-js/faker/pull/3341