workflow(bug-report): new version
faker-js/faker pull request #1205
Opened 2022-07-28 07:34 UTC by xDivisionByZerox

This PR completely reworks the `bug-report` issue template.
This should lead to an overall better experience for the person creating an issue in the bug category as well as the person answering the to it.

2022-07-28 07:34 UTC, xDivisionByZerox commented
I'm not sure how to label this. 🤷‍♀️

2022-07-28 17:43 UTC, xDivisionByZerox commented
I've provided a working example on my fork of the project. You create issues with this template [here](https://github.com/xDivisionByZerox/faker/issues/new?assignees=&labels=s%3A+pending+triage%2Cbug&template=bug_report.yml).
This is mainly because the relative links down work in the yaml preview, but they do as soon as the template is merged.

2022-07-28 17:53 UTC, xDivisionByZerox commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - open a new [discussion](../discussions) and ask your question there
Should we refer to `Stack Overflow` with the `faker-js` label here?

2022-07-29 09:13 UTC, ST-DDT commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +labels: ['s: pending triage', 'bug']
```suggestion
labels: ['s: pending triage', 'c: bug']
```

2022-07-29 09:13 UTC, ST-DDT commented on .github/ISSUE_TEMPLATE/bug_report.yml
>        required: true
Is this intentionally required?

2022-07-29 09:13 UTC, ST-DDT commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - label: Firefox
our code usually doesn't run in browsers. only tests.
Or does it?

2022-07-29 13:03 UTC, xDivisionByZerox commented on .github/ISSUE_TEMPLATE/bug_report.yml
>        required: true
Yes. I thought that if you submit a bug report you should be required to describe to bug you encountered.

2022-07-29 13:07 UTC, xDivisionByZerox commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - label: Firefox
I mean, we promote usage for browsers. So I see no problem with having a specific section for Browser and NodeJS.

2022-07-29 18:08 UTC, xDivisionByZerox commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        This is obviously not required but is greatly appreciated.
Should we link to our contribution guide in this description? Something like:
`If you want are willing to contribute, but are unsure how to do that have a look at our CONTRIBUTION.md or ask one of the core members of faker-js`

2022-07-30 09:42 UTC, Shinigami92 requested changes
I would like that you rework the template based on my suggestions and then we might have a new feedback cycle

2022-07-30 09:42 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +description: "Something isn't working as expected \U0001F914"
We already use an emoji in the "title", so I would be against another emoji in the description

<img src="https://user-images.githubusercontent.com/7195563/181903999-0f89798c-b9e0-4488-959a-b6beaa193425.png" width="200px"/>

```suggestion
description: "Something isn't working as expected"
```

I'm even not sure about the wording saying: _something isn't working_
`Report an issue` is more a call to action, so we might just leave it as is

2022-07-30 09:42 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        If you are not sure that your issue is a bug, you could:
```suggestion
        If you are unsure whether your problem is a bug or not, you can check the following:
```

2022-07-30 09:42 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        ## :warning: We use GitHub Issues to track bug reports, feature requests and regressions
Does this provide any "value"?

2022-07-30 09:42 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - open a new [discussion](../discussions) and ask your question there
Yeah I think mentioning additionally Stack Overflow is a good thing
Check the tags and see what fits better for us

2022-07-30 09:42 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        **NOTE:** You don't need to answer questions that you know that aren't relevant.
What does this mean? It confuses me :confused: 
I mean what's the "value" of this sentence for the issue author?

2022-07-30 09:42 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          required: true
Checklists like these are currently very verbose and just take a huge amount of screenspace
We might think to collapse them into just a list like we did in Vite
https://github.com/vitejs/vite/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml (scroll to bottom section `Validations`)
_sadly GitHub doesn't link me directly what I mean_ :confused:

2022-07-30 09:42 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: 'Current behavior'
A more like call to action would be
```suggestion
      label: 'Describe the bug'
```

2022-07-30 09:42 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: 'https://github.com/...'
This should be a textarea or alternatively **not** required

In our case not all bug reports needs a repo/stackblitz reproducible, this might just lead to not reported bugs dying in silence

2022-07-30 09:42 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        How the issue manifests?
`manifests` is IMO a to advanced english wording and especially in faker we have 56 different languages that we currently provide, so lower the burden for non natives might be considered

2022-07-30 09:42 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        3. See error...
This should be merged with the upper section: provide a repro link or a code example

2022-07-30 09:42 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: 'A clear and concise description of what you expected to happend (or code)'
IMO this can be merged with the upper proposed `Describe the bug` section
That has the benefit that the form in general reduces in screenspace

2022-07-30 09:42 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: 'x.x.x'
We could propose to run `npx envinfo --system --npmPackages '@faker-js/*' --binaries --browsers`
This would give us a more detailed report and is easier to use for the customer

Have a look into the `System Info` section of the Vite template

2022-07-30 09:42 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: 'Other'
I would word this as `Additional Context`

2022-07-30 16:40 UTC, import-brain requested changes

2022-07-30 16:40 UTC, import-brain commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        **NOTE:** You don't need to answer questions that you know that aren't relevant.
```suggestion
        **NOTE:** You don't need to answer questions that aren't relevant.
```

2022-07-30 16:40 UTC, import-brain commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - label: 'I have searched the existing issues'
```suggestion
        - label: 'I have searched existing issues'
```

2022-07-30 16:40 UTC, import-brain commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: 'Please read our [documentation](https://fakerjs.dev/guide) to see if the bug you encountered is a use error'
```suggestion
      description: 'Please read our [documentation](https://fakerjs.dev/guide) to see if the bug you encountered is a use error'
```
Did you mean to say "user error"?

2022-07-30 16:40 UTC, import-brain commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - label: "I have read the documentation for the area I'm reporting the bug in"
```suggestion
        - label: "I have read the docs for the area I'm reporting the bug in"
```

2022-07-30 16:40 UTC, import-brain commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: 'Minimum reproduction code'
```suggestion
      label: 'Minimal reproduction code'
```

2022-07-30 16:40 UTC, import-brain commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        You could leave this blank if you alread write this in your reproduction code/repo
```suggestion
        You could leave this blank if you already wrote this in your reproduction code/repo
```

2022-07-30 16:40 UTC, import-brain commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        How the issue manifests?
Hmm, `manifest` isn't too bad in terms of wording. If we choose to keep `manifest`, I think we should change the wording of the question to "How does this issue manifest?"

2022-07-30 16:40 UTC, import-brain commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        The following question are required if you use our package in NodeJS.
```suggestion
        The following questions are required if you use our package in NodeJS.
```

2022-07-30 16:40 UTC, import-brain commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: 'A clear and concise description of what you expected to happend (or code)'
```suggestion
      description: 'A clear and concise description of what you expected to happen (or code)'
```

2022-07-30 16:40 UTC, import-brain commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: 'Are you willing to provide a PR for to resolve this bug?'
```suggestion
      label: 'Are you willing to provide a PR to resolve this bug?'
```

2022-07-30 18:09 UTC, xDivisionByZerox commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: 'Other'
Can you use the "Add suggestion" feature in the comment? That why you will get referenced as co-author :)

2022-07-30 18:12 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: 'Other'
There are so many proposed changes from my side, that I thought it is made within just one big commit by you anyway

2022-07-30 18:13 UTC, xDivisionByZerox commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: 'Please read our [documentation](https://fakerjs.dev/guide) to see if the bug you encountered is a use error'
I'm sorry I don't know the English term. I was trying to describe an error that occurs because you are the one using the code incorrectly. Is that what a "user error" is? Google was suggesting "use error" for me^^

2022-07-30 18:14 UTC, xDivisionByZerox commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - label: "I have read the documentation for the area I'm reporting the bug in"
I like the explicit "documentation" call out. "docs" sounds so unprofessional for me :/

2022-07-30 18:22 UTC, xDivisionByZerox commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - open a new [discussion](../discussions) and ask your question there
`faker-js` is actually not used at all, so we wouldn't conflict with any existing labels. 
`faker` is already used but not for javascript exclusive. So it could be harder to find issued that really relate to our package.

2022-07-30 18:25 UTC, xDivisionByZerox commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: 'Other'
Nah, I'm a woman that likes to take small but consistent steps. In that case, if we are not sure about a suggestion that was pushed it's way easier to revert that change. That is at least how I work, even tho I know we sqush the final result and it doesn't matter in the end^^

2022-07-30 18:47 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: 'Other'
```suggestion
      label: 'Additional Context'
```

2022-07-30 19:06 UTC, xDivisionByZerox commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        ## :warning: We use GitHub Issues to track bug reports, feature requests and regressions
Yes, I state that this is not the place for the common "Help! faker isn't working because I'm too lazy to read the documentation and I'm unaware of the discussion section" issue.

2022-07-30 19:07 UTC, xDivisionByZerox commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        **NOTE:** You don't need to answer questions that you know that aren't relevant.
It's more or less the duplication of the statements that are mentioned in the "browser" and "NodeJS" specific sections.

2022-07-30 19:15 UTC, xDivisionByZerox commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          required: true
Oh yeah, that looks cool. The only problem I have with this is, that it could give the typical "yes I totally have read the TOS" vibes. Because it's positioned at the end I could have already filled out the entire form and then see that I could have just asked a question in discord. But overall I like the compact look.

But TBH, these are only 2 checkboxes. Not the 7 vite has^^

2022-07-30 20:33 UTC, import-brain commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: 'Please read our [documentation](https://fakerjs.dev/guide) to see if the bug you encountered is a use error'
> I'm sorry I don't know the English term. I was trying to describe an error that occurs because you are the one using the code incorrectly. Is that what a "user error" is? Google was suggesting "use error" for me^^

No worries! It's "user error", I don't know why Google is saying "use error" 😅

2022-07-30 20:34 UTC, import-brain commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - label: "I have read the documentation for the area I'm reporting the bug in"
Hmm, you're right. I just thought it would be a bit shorter because you used the full word "documentation" twice already.

2022-08-03 14:43 UTC, Shinigami92 approved these changes

2022-08-03 15:44 UTC, import-brain submitted a review, later dismissed

2022-08-03 17:25 UTC, pkuczynski submitted a review, later dismissed

2022-08-03 19:24 UTC, ST-DDT commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          Shell: _
These feel kind of useless to me.
AFAICT none of our bug reports were related this.

2022-08-03 19:24 UTC, ST-DDT commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: I am doing ... What I expect is ... What actually happening is ...
IMO this should be split into multiple sections.
By the time the user has written everything for the first step the probably have forgotten, what they should include here as well.

2022-08-04 06:33 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          Shell: _
Seems there is a programatic way of filtering it, but not via CLI 🤔 
https://github.com/tabrindle/envinfo#cli-options
So I don't know how to only get the OS but not the rest

2022-08-04 06:36 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: I am doing ... What I expect is ... What actually happening is ...
So should we move this e.g. in _italic_ to the `description`?
Because opening 3 different sections makes the form to huge and to much to scroll
Also this is just an **indicator / help** how it could be written but **not a only correct way**

2022-08-04 07:59 UTC, ST-DDT approved these changes

2022-08-04 08:07 UTC, Shinigami92 approved these changes

2022-08-04 08:08 UTC, Shinigami92 commented
I count the previous approvals as valid, as nothing changed heavily anymore

2022-08-04 08:09 UTC, Shinigami92 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: I am doing ... What I expect is ... What actually happening is ...
_mark as resolved_ so _merge_ is possible
We can adjust it in future PRs if needed

2022-08-04 08:13 UTC, merged