Add full_name_pattern configuration #1211
faker-js/faker pull request #1216
Opened 2022-07-31 08:41 UTC by satoc0629

2022-07-31 11:06 UTC, ST-DDT commented
Could you please provide the male and female first names in a separate PR?
We would like to keep locale changes separate from implementation changes/new feature to simplify the review process.

2022-07-31 11:18 UTC, ST-DDT commented on src/modules/name/index.ts
> +    return fullNamePattern;
This variant does not support other (especially locale dependent parts) such as prefix and suffix.
Maybe an implementation using faker.helpers.mustache or faker.(helpers.)fake would work on a broader spectrum of usecases.

2022-07-31 11:18 UTC, ST-DDT commented on src/definitions/name.ts
> +];
What is this list used for?

2022-07-31 11:18 UTC, ST-DDT commented on src/definitions/name.ts
> +  full_name_pattern?: string[];
There seems to be a `name/name.ts` in some locales, that seems to be for the same purpose (legacy templates that aren't used in code), maybe we should rename/incorporate these files.

2022-07-31 13:42 UTC, satoc0629 commented
> 別の PR で男性と女性の名前を教えてください。 レビュー プロセスを簡素化するために、ロケールの変更を実装の変更/新機能とは別にしたいと考えています。

We have responded here.

2022-07-31 15:08 UTC, satoc0629 commented
We are changing our policy to take advantage of legacy templates as you have indicated.

And we are considering the following modifications to the fullName function.
```typescript
  fullName(
    options: {
      firstName?: string;
      lastName?: string;
      gender?: GenderType;
    } = {}
  ): string {
    const {
      gender = this.faker.helpers.arrayElement(['female', 'male']),
      firstName = this.firstName(gender),
      lastName = this.lastName(gender),
    } = options;

    const prefix = this.faker.helpers.maybe(() => this.prefix(gender), {
      probability: 0.125,
    });

    const suffix = this.faker.helpers.maybe(() => this.suffix(), {
      probability: 0.125,
    });

    const nameParts = [];
    if (prefix) {
      nameParts.push(prefix);
    }
    nameParts.push(firstName);
    nameParts.push(lastName);
    if (suffix) {
      nameParts.push(suffix);
    }
    const defaultName = nameParts.join(' ');

    if (
      !this.faker.definitions.name.name ||
      this.faker.definitions.name.name.length === 0
    ) {
      return defaultName;
    }
    // if (gender || firstName || lastName) {
    //   return defaultName;
    // }

    const fullNamePattern = this.faker.helpers.arrayElement(
      this.faker.definitions.name.name
    );

    const fullName = this.faker.helpers.mustache(fullNamePattern, {
      'name.gender': () => this.gender(),
      'name.binary_gender': () => this.gender(true),
      'name.prefix': () => this.prefix(gender),
      'name.female_prefix': () => this.prefix(gender),
      'name.male_prefix': () => this.prefix(gender),
      'name.first_name': () => (firstName ? firstName : this.firstName(gender)),
      'name.female_first_name': () =>
        firstName ? firstName : this.firstName(gender ? gender : 'female'),
      'name.male_first_name': () =>
        firstName ? firstName : this.firstName(gender ? gender : 'male'),
      'name.middle_name': () => this.middleName(gender),
      'name.female_middle_name': () =>
        this.middleName(gender ? gender : 'female'),
      'name.male_middle_name': () => this.middleName(gender ? gender : 'male'),
      'name.last_name': () => (lastName ? lastName : this.lastName(gender)),
      'name.female_last_name': () =>
        lastName ? lastName : this.lastName(gender ? gender : 'female'),
      'name.male_last_name': () =>
        lastName ? lastName : this.lastName(gender ? gender : 'male'),
      'name.suffix': () => (suffix ? suffix : this.suffix()),
    });

    return fullName;
  }
```

Retrieve the template from the legacy NameDefinitions.name and convert it.

Do you have a better idea about this?
I have done my best to write it, but I feel something is missing.

Thanks for reading.

2022-07-31 15:10 UTC, satoc0629 commented on src/definitions/name.ts
> +];
That will be removed.

2022-07-31 15:10 UTC, satoc0629 commented on src/definitions/name.ts
> +  full_name_pattern?: string[];
That will be removed.

2022-08-04 14:05 UTC, Shinigami92 requested changes

2022-08-04 14:41 UTC, satoc0629 commented on src/modules/name/index.ts
> -export type GenderType = SexType;
Sorry, I will check.

2022-08-04 15:04 UTC, satoc0629 commented on src/modules/name/index.ts
> +    return fullNamePattern;
The response to the latest commitments has been an improvement. Please confirm.

2022-09-17 08:53 UTC, ST-DDT commented
The full name pattern isnt used in the code and if it will be it should be done constently for all locales

2022-09-17 10:30 UTC, satoc0629 commented
@ST-DDT 

> The full name pattern isnt used in the code and if it will be it should be done constently for all locales

In the most recent commit, the full_name_pattern method was abandoned.
On the contrary, we are changing to a method that refers to the existing legacy asset, the name template.

The name template is located in src/definitions/name.ts.
```
  /**
   * A list of patterns used to generate names.
   */
  name: string[];
```

2022-09-17 11:17 UTC, ST-DDT commented
You seem to have missed one file: src/locales/ja/name/full_name_pattern.ts

2022-09-17 12:09 UTC, satoc0629 commented
@ST-DDT 
Sorry. I pushed one new commit.

2022-09-18 05:39 UTC, satoc0629 commented
@ST-DDT 

In addition to src/definitions/name.ts
src/definitions/female_name.ts and src/definitions/male_name.ts can now be set.
This allows for the conventional behavior of using src/definitions/name.ts as the default, as well as the use of the above when sex is specified.

2022-09-18 10:48 UTC, ST-DDT commented on src/modules/name/index.ts
> +    const fullNamePattern = this.faker.helpers.arrayElement(
The selectDefinition method at the top should do the same in a more readable way..

2022-09-18 10:48 UTC, ST-DDT commented on src/modules/name/index.ts
> +    });
I'm not a fan of this, as this hard to maintain/extend.

2022-09-18 14:46 UTC, satoc0629 commented on src/modules/name/index.ts
> +    });
@ST-DDT 
Is this an implementation issue?
Or is it an idea problem?
Thank you.

2022-09-18 16:54 UTC, ST-DDT commented on src/modules/name/index.ts
> +    });
Yes, it would be nice of you could at least remove/merge the male/female parts and then call it with the (pregenerated) gender option.

2022-09-19 01:07 UTC, satoc0629 commented on src/modules/name/index.ts
> +    });
@ST-DDT 
Please take a look at the following commit.
https://github.com/faker-js/faker/pull/1216/commits/073140a6de9749d589b4c94fd21986b621e04403

2023-01-26 17:47 UTC, ST-DDT commented
Superseded by #1637

2023-01-26 17:47 UTC, closed without merging