feat(locales.pl): add pl translation for directions and directions abbr
faker-js/faker pull request #1225
Opened 2022-08-03 19:08 UTC by hankucz

2022-08-03 19:25 UTC, import-brain approved these changes
Translations verified using Google Translate, lgtm

2022-08-03 19:25 UTC, pkuczynski requested changes

2022-08-03 19:25 UTC, pkuczynski commented on src/locales/pl/address/direction.ts
> +  'Północ',
* add source: https://pl.wikipedia.org/wiki/Strony_świata
* sort alphabetically
* use lower case

2022-08-03 19:25 UTC, pkuczynski commented on src/locales/pl/address/direction_abbr.ts
> +export default ['N', 'E', 'S', 'W', 'NE', 'NW', 'SE', 'SW'];
There are polish abbreviations: pn., pd., ...

See: https://pl.wikipedia.org/wiki/Strony_świata

2022-08-03 19:39 UTC, hankucz commented on src/locales/pl/address/direction_abbr.ts
> +export default ['N', 'E', 'S', 'W', 'NE', 'NW', 'SE', 'SW'];
Done...

2022-08-03 19:39 UTC, pkuczynski submitted a review, later dismissed

2022-08-03 19:39 UTC, hankucz commented on src/locales/pl/address/direction.ts
> +  'Północ',
Done...

2022-08-03 20:21 UTC, import-brain submitted a review, later dismissed

2022-08-03 20:54 UTC, ST-DDT requested changes
The order of the elements is somewhat important:
https://github.com/faker-js/faker/blob/04c9d36cc44fa647f401919c708e550dbe42040d/src/modules/address/index.ts#L411-L453
0-3 => cardinal direction
4-7 => ordinal direction

2022-08-03 21:12 UTC, pkuczynski commented
Wow! I would never expect this and it's really hard to catch on the review. It would be way better if TS could catch it automatically...

Should we change the definition to look more like:

```js
interface Directions {
  cardinal: string[]
  ordinal: string[] // or intercardinal ?
  secondaryIntercardinal?: string[]
}

type DirectionType = keyof Directions
```

And then both `directions` and `directions_abbr` should use this type?

Additionally, I think it makes sense to simplify the usage and change `direction` signature to:

```
direction ({ abbr: boolean, type: DirectionType, types: DirectionType[]})

@examples
faker.address.direction() // 'north'
faker.address.direction({ abbr: true }) // 'N'
faker.address.direction({ type: 'ordinal' }) // 'north west'
faker.address.direction({ abbr: true, type: 'ordinal' }) // 'NW'
faker.address.direction({ abbr: true, types: ['ordinal', 'secondaryIntercardinal']  }) // 'NNW'
```

And then deprecate the other methods? We might also skip `secondaryIntercardinal`...

2022-08-03 21:19 UTC, ST-DDT commented
@pkuczynski Please create a separate issue for that.

2022-08-03 21:33 UTC, pkuczynski commented
> @pkuczynski Please create a separate issue for that.

Sure! https://github.com/faker-js/faker/issues/1228

2022-08-16 09:27 UTC, ST-DDT commented
@hankucz Could you please restore the original order? (N,E,S,W, NE, SE, SW, SE)
That way we can merge this and can easily automatically transform it once we change the implementation.

2022-08-18 20:49 UTC, hankucz commented
@ST-DDT original order restored

2022-08-18 21:31 UTC, pkuczynski approved these changes

2022-08-18 22:03 UTC, ST-DDT approved these changes

2022-08-19 07:22 UTC, Shinigami92 approved these changes

2022-08-19 07:27 UTC, merged