feat(locales.pl): add pl for horses
faker-js/faker pull request #1227
Opened 2022-08-03 19:17 UTC by hankucz

2022-08-03 19:22 UTC, pkuczynski requested changes

2022-08-03 19:22 UTC, pkuczynski commented on src/locales/pl/animal/horse.ts
> +export default [
It would be good to add a source, where this information comes from...

2022-08-03 19:22 UTC, pkuczynski commented on src/locales/pl/animal/horse.ts
> +export default [
And the list should be sorted alphabetically...

2022-08-16 09:28 UTC, ST-DDT commented
@hankucz Could you please perform the requested changes so we can merge this?

2022-08-17 10:23 UTC, Shinigami92 commented
@xDivisionByZerox did you progress on a PR for checking alphabetically sorted locales?
I think we should test it and add a manual filtering step to define if we want to list some specific cases where sorting doesn't make sense (like direction)

2022-08-18 20:41 UTC, hankucz commented on src/locales/pl/animal/horse.ts
> +export default [
Done

2022-08-18 20:41 UTC, hankucz commented
@ST-DDT feedback applied

2022-08-18 20:48 UTC, pkuczynski approved these changes

2022-08-18 22:02 UTC, ST-DDT approved these changes

2022-08-19 07:23 UTC, Shinigami92 approved these changes

2022-08-19 07:39 UTC, merged