feat: `datatype.hexadecimal` signature change
faker-js/faker pull request #1238
Opened 2022-08-07 22:32 UTC by import-brain

closes #954

2022-08-08 06:30 UTC, ST-DDT reviewed
This is a breaking change without our usual deprecation mechanics.

2022-08-08 06:30 UTC, ST-DDT commented on src/modules/finance/index.ts
> +      .toLowerCase();
Maybe add a case option?

2022-08-08 13:42 UTC, Minozzzi approved these changes

2022-08-08 17:37 UTC, ST-DDT requested changes

2022-08-08 17:37 UTC, ST-DDT commented on src/modules/color/index.ts
> +        .slice(prefix.length);
Instead of adding a prefix and then  removing it, you could just omit it directly.

2022-08-08 17:37 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +      | { length?: number; prefix?: string; case?: 'lower' | 'upper' }
This should also support `case: 'mixed'`.

2022-08-08 17:37 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +    const letterCase = options?.case ?? 'upper';
The default should be `mixed`

2022-08-08 17:37 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +      | number
```suggestion
      | number = {}
```

2022-08-08 17:37 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +    const letterCase = options?.case ?? 'upper';
```ts
const {
 length = 1;
 ...
} = options;
```

2022-08-08 22:34 UTC, ST-DDT requested changes
One minor change then it looks good to go.

2022-08-08 22:34 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +   * @param options.case Case of the generated number. Defaults to `'upper'`.
```suggestion
   * @param options.case Case of the generated number. Defaults to `'mixed'`.
```

2022-08-08 22:37 UTC, import-brain commented on src/modules/datatype/index.ts
> +   * @param options.case Case of the generated number. Defaults to `'upper'`.
Whoops, welp this is why we have code review.

2022-08-08 22:40 UTC, ST-DDT approved these changes
<details>
<summary><strong>Docs Preview</strong> (Click to expand)</summary>

![grafik](https://user-images.githubusercontent.com/1579362/183526600-6a65ca39-ffb4-442a-b3da-6acfdd0ca24c.png)


</details>

2022-08-09 14:33 UTC, Shinigami92 requested changes

2022-08-09 14:33 UTC, Shinigami92 commented on src/modules/datatype/index.ts
> +        since: '7.4',
```suggestion
        since: '7.5',
```

2022-08-09 15:35 UTC, ST-DDT submitted a review, later dismissed

2022-08-09 15:48 UTC, Shinigami92 commented on src/modules/datatype/index.ts
> +      : `${prefix}${wholeString.toUpperCase()}`;
Maybe we can shorten this :thinking: 

Something like
```ts
const result = prefix
result += letterCase === 'mixed'
      ? wholeString
      : letterCase === 'lower'
      ? wholeString.toLowerCase()
      : wholeString.toUpperCase()
return result
```

2022-08-10 07:14 UTC, ST-DDT approved these changes

2022-08-10 07:26 UTC, Shinigami92 approved these changes

2022-08-10 07:31 UTC, merged

2022-08-26 21:41 UTC, xDivisionByZerox commented
> This is a breaking change without our usual deprecation mechanics.

Why did this got merged then?
@import-brain you removed the `BREAKING CHANGE` label. Why that?

2022-08-26 21:45 UTC, Shinigami92 commented
> > This is a breaking change without our usual deprecation mechanics.
> 
> Why did this got merged then? @import-brain you removed the `BREAKING CHANGE` label. Why that?
> 
> This PR has an incorrect type as well.

I assume it was just one or few days before we finally defined how we want changelogs to be formatted
so this was one of the last that slept into the changelogs

2022-08-26 21:52 UTC, xDivisionByZerox commented
This explains the PR type (which is my minor concern).

Currently, this `BREAKING CHANGE` is in the `main` branch but we plan to release a new `minor` version on Monday. That's what I'm more concerned about.

2022-08-26 21:54 UTC, import-brain commented
> > This is a breaking change without our usual deprecation mechanics.
> 
> Why did this got merged then? @import-brain you removed the `BREAKING CHANGE` label. Why that?
> 
> This PR has an incorrect type as well.

I changed the code such that it wasn't a breaking change anymore.

2022-08-26 22:00 UTC, xDivisionByZerox commented
Yeah but you changed the default return value to not include the prefix.
Currently, I can do this:
```ts
const hex = faker.datatype.hexadecimal(1);
console.log(parseInt(hex)); // 14
```

This will break now:
```ts
const hex = faker.datatype.hexadecimal(1);
console.log(parseInt(hex)); // NaN
```

2022-08-26 22:05 UTC, import-brain commented
> Yeah but you changed the default return value to not include the prefix. Currently, I can do this:
> 
> ```ts
> const hex = faker.datatype.hexadecimal(1);
> console.log(parseInt(hex)); // 14
> ```
> 
> This will break now:
> 
> ```ts
> const hex = faker.datatype.hexadecimal(1);
> console.log(parseInt(hex)); // NaN
> ```

Oh crap. Should I manually revert this and reimplement the change before we release v8?

2022-08-27 09:03 UTC, ST-DDT commented
I wouldnt revert it entirely, just restore the old defaults.

@xDivisionByZerox Nicely spotted.