docs: add migration guide from v6 to v7
faker-js/faker pull request #1246
Opened 2022-08-09 08:44 UTC by matthewmayer

I saw there was a migration guide from v5 to v6

https://fakerjs.dev/guide/migration-guide-v5.html

But no such guide for the breaking changes from v6 to v7 described at https://github.com/faker-js/faker/releases/tag/v7.0.0

I thought it would be useful to add this as a reference, as I recently upgraded a project and had to do some digging to find details of the changes.

2022-08-09 10:28 UTC, ST-DDT commented on docs/guide/migration-guide-v6.md
> +You require at least Node 14 to run faker
```suggestion
You need at least Node 14 to use faker.
```

2022-08-09 10:28 UTC, ST-DDT commented on docs/guide/migration-guide-v6.md
> +You should instead use
```suggestion
You should instead use:
```

2022-08-09 10:28 UTC, ST-DDT commented on docs/guide/migration-guide-v6.md
> +Several methods were renamed or moved.
Not sure about this one:

```suggestion
Several methods were renamed or moved:
```

2022-08-09 10:31 UTC, ST-DDT commented
Thank you a lot, this migration guide is really overdue.

2022-08-09 10:34 UTC, ST-DDT commented
<details>
<summary><strong>Docs Preview</strong> (Click to expand)</summary>

![grafik](https://user-images.githubusercontent.com/1579362/183627693-e8ef0125-1a92-4cbc-afe6-8cb930803453.png)


</details>

2022-08-09 13:03 UTC, Minozzzi submitted a review, later dismissed

2022-08-09 14:01 UTC, ST-DDT approved these changes, later dismissed

2022-08-09 14:26 UTC, Shinigami92 requested changes

2022-08-09 14:26 UTC, Shinigami92 commented on docs/.vitepress/config.ts
> +              link: '/guide/migration-guide-v6',
For now we can make it like this, but at Vite, we use only one migration file and use the version switch at the top to redirect the user to the older version of the documentation that then include the migration guide of the older version to the old version

2022-08-09 14:26 UTC, Shinigami92 commented on docs/guide/migration-guide-v6.md
> +You need at least Node 14 to use faker.
```suggestion
You need at least Node 14 to use Faker.
```

2022-08-09 14:26 UTC, Shinigami92 commented on docs/guide/migration-guide-v6.md
> +You should instead use:
```suggestion
You must instead use:
```

2022-08-09 16:50 UTC, Shinigami92 approved these changes

2022-08-09 16:52 UTC, ST-DDT approved these changes

2022-08-10 23:12 UTC, import-brain approved these changes

2022-08-11 06:25 UTC, merged