chore(locales-he): extend he locales
faker-js/faker pull request #1257
Opened 2022-08-11 19:29 UTC by orinaveh

## **Description**
As a Hebrew speaker who had to use this great package, I found some issues with the Hebrew locales. In this PR, I tried to fix as many of those issues as possible and make the data generated in Hebrew more realistic. 

## **Changes**

### **Address**

#### **Buidling Number**
I Added common Israeli pattern for semidetached house's Building numbers.

 #### **Cities**
I Added a list of Israeli cities from our local MOI database.
Therefore I removed the prefix_city file.

 #### **Countries**
I updated the list as it seemed to be missing many countries.
In addition, I updated the default country to 'Israel' (instead of 'State of Israel') (lit.)

 #### **State**
I inserted the official regions of Israel to the list.

 #### **Streets**
In Hebrew, there are no suffixes to street's name, so I replaced the suffix with prefix file that includes common prefixes.
In addition, I took a list of streets names from some of cities in Israel and added that to `street_name.ts`

 #### **Direction Abbreviation**
I translated the values.

### **Cell Phones  & Phone numbers**

I added the Israeli patterns for Cell Phones and Phone numbers

### **Color**

The translation had [Niqqud](https://en.wikipedia.org/wiki/Niqqud) although using Niqqud is very uncommon in modern Hebrew, so I removed it.

### **Music**

#### **Genres**
I refined the translation of some of the genres

### **Names**

#### **First & Last Names**
Some names appeared twice or had a suffix of the word 'Family' between parentheses. I also added missing white-spaces.

#### **Prefix**
I translated the values.

2022-08-11 21:57 UTC, ST-DDT reviewed
I reviewed half of this PR and will do the rest tomorrow.
It looks good so far, I only had one word that I couldn't very using google translate.

2022-08-11 21:57 UTC, ST-DDT commented on src/locales/he/music/genre.ts
> +  'מוזיקת עם',
I'm unable to look this up using google translate: `music m`
Can you check whether you typed this one correctly and what the respective English translation is supposed to be?

2022-08-11 21:57 UTC, ST-DDT commented
Thanks for your contribution!

2022-08-12 06:00 UTC, orinaveh commented on src/locales/he/music/genre.ts
> +  'מוזיקת עם',
https://translate.google.co.il/?hl=iw&sl=iw&tl=en&text=%D7%9E%D7%95%D7%96%D7%99%D7%A7%D7%AA%20%D7%A2%D7%9D&op=translate

Google translate automatically detected `מוזיקת עם` as Yiddish term for some reason 😕

2022-08-13 10:51 UTC, ST-DDT requested changes
Looks good to me.

2022-08-13 10:51 UTC, ST-DDT commented on src/locales/he/phone_number/formats.ts
> +  '077-#######',
Could you add a variant containing the international telephone prefix `+972` (?)?

2022-08-13 12:43 UTC, orinaveh commented on src/locales/he/phone_number/formats.ts
> +  '077-#######',
> Could you add a variant containing the international telephone prefix `+972` (?)?

@ST-DDT I have added the International format for both cell and landline numbers.

2022-08-13 12:43 UTC, ST-DDT approved these changes

2022-08-15 22:17 UTC, import-brain approved these changes

2022-08-16 08:39 UTC, merged