ci: verify semantic pull requests
faker-js/faker pull request #1264
Opened 2022-08-12 10:03 UTC by Shinigami92

In our last meeting we discussed that we want to allow only specific defined scopes so the [CHANGELOG.md](https://github.com/faker-js/faker/blob/main/CHANGELOG.md) will get better updated automatically

This PR will add a guideline that explains which are good commit/PR titles and which are not (with historical real world examples and how to write them instead)

Also it will only allow a subset of `types` and `scopes` so the PR title must follow the new convention

Please note that the `verifyCommit` script doesn't need to be absolutely exact, as only the PR title is important at the end when merging the PR because we always use **squash-merge rebase**

Tip: You can check how we wrote commit messages in the history with following command:
```node
git log --pretty=format:%s > commits.md
```

2022-08-12 10:18 UTC, ST-DDT requested changes

2022-08-12 10:18 UTC, ST-DDT commented on .github/workflows/semantic-pull-request.yml
> +            word
I don't think we should have a limited set of scopes here, because then PRs for new modules would be impossible.
(require a pre-change to the pipeline)

2022-08-12 10:18 UTC, ST-DDT commented on .github/workflows/semantic-pull-request.yml
>              refactor
IMO this is confusing, because it won't show up in the changelogs, but in our case it is kind of important.

2022-08-12 10:18 UTC, ST-DDT commented on .github/workflows/semantic-pull-request.yml
> +            infra
IMO we should decide on one of `ci`, `build` or `infra`

2022-08-12 10:19 UTC, ST-DDT commented
> We need to discuss if we want a type `revert` or a scope `revert` (or both)?

IMO we should allow type revert. Although this might be connected to a bugfix usually.

2022-08-12 10:43 UTC, Shinigami92 commented on .github/workflows/semantic-pull-request.yml
> +            word
Yes and no, I already had the same thought
But maybe if we introduce/remove a new/old module, this list just needs to be updated in the exact same PR
We as maintainers just need to keep care of that and tell the contributor
I think introducing a new module is relatively rarely (like the color module)

2022-08-12 10:45 UTC, Shinigami92 commented on .github/workflows/semantic-pull-request.yml
> +            infra
IMO they all have their meanings
- ci: touches e.g. github workflow yaml files, ...
- build: touches build scrips, changing node target, ...
- infra: update issue template, ...

2022-08-12 13:08 UTC, ST-DDT commented on .github/workflows/semantic-pull-request.yml
> +            word
Tested by renaming this PR. It uses the args from main.

2022-08-12 13:12 UTC, ST-DDT commented on CONTRIBUTING.md
> +test: validate @see contents
Please add an example for deprecations somewhere. Plus every supported type.

2022-08-12 13:15 UTC, Shinigami92 commented on .github/workflows/semantic-pull-request.yml
> +            word
That's odd 😕 
So we need to somehow guide contributors to good PR titles to move maintenance away from us
Maybe with a github PR template

2022-08-12 16:46 UTC, import-brain commented on CONTRIBUTING.md
> +Historically real world examples that could be written in a better way:
```suggestion
Previous pull request titles that could have been written in a better way:
```

2022-08-12 16:57 UTC, xDivisionByZerox commented on CONTRIBUTING.md
> +The configured `types` and `scopes` can be found in [.github/workflows/semantic-pull-request.yml](https://github.com/faker-js/faker/blob/main/.github/workflows/semantic-pull-request.yml).
I think conventionally `'type'` is named `'topic'` but I might be wrong. Nevertheless I prefer `'topic'`.

2022-08-12 17:30 UTC, Shinigami92 commented on .github/workflows/semantic-pull-request.yml
> +            word
I have an idea!
If it needs to be just in the main branch before merging the PR, we could create an additional `ci` PR that just adds the new module name

2022-08-12 17:41 UTC, Shinigami92 commented on CONTRIBUTING.md
> +test: validate @see contents
please re-evaluate and make a new review suggestion if needed

2022-08-12 17:42 UTC, Shinigami92 commented on CONTRIBUTING.md
> +The configured `types` and `scopes` can be found in [.github/workflows/semantic-pull-request.yml](https://github.com/faker-js/faker/blob/main/.github/workflows/semantic-pull-request.yml).
https://www.conventionalcommits.org/en/v1.0.0/#summary:~:text=structured%20as%20follows%3A-,%3Ctype%3E,-%5Boptional%20scope%5D%3A%20%3Cdescription

Nope

2022-08-13 06:31 UTC, ST-DDT commented on .github/workflows/semantic-pull-request.yml
> +            word
The issue with that is that the user sees a ci failure but doesnt know how to fix it himself.
Also PRs with red build failure markers are less likely to be reviewed.
If we add the marker asap, zhen we might end up with months of unused scopes which might lead to confusion as well. If the new module PR gets stale/dies then we have a dead scope in our list that we have to remember to remove.

2022-08-13 09:43 UTC, ST-DDT requested changes

2022-08-13 09:43 UTC, ST-DDT commented on CONTRIBUTING.md
> ++ feat(system): add method networkInterface
```suggestion
+ feat(system): add networkInterface method
```

2022-08-13 10:06 UTC, Shinigami92 commented on .github/workflows/semantic-pull-request.yml
> +            word
Yeah I see the problem :confused: 
Okay so I need to move these allowed scopes to a documentation / pr template and tell the @faker-js/members to help us fix wrongly named PR titles

2022-08-13 11:10 UTC, Shinigami92 commented
Cannot name it infra yet, as it's not in the main branch :sweat_smile:

2022-08-13 11:20 UTC, ST-DDT requested changes

2022-08-13 11:20 UTC, ST-DDT commented on CONTRIBUTING.md
> +The configured `types` and `scopes` can be found in [.github/workflows/semantic-pull-request.yml](https://github.com/faker-js/faker/blob/main/.github/workflows/semantic-pull-request.yml).
The scopes aren't listed there anymore.
So I would move this to the **types** section.

2022-08-13 11:20 UTC, ST-DDT commented on scripts/verifyCommit.ts
> +  /^(revert: )?(feat|fix|docs|dx|refactor|perf|test|locale|workflow|build|ci|chore|types|wip|release|deps|infra)(\(.+\))?\!?: .{1,50}/;
IMO we should remove the commit names that aren't valid PR titles, because they will never be in main.

2022-08-13 11:22 UTC, Shinigami92 commented on scripts/verifyCommit.ts
> +  /^(revert: )?(feat|fix|docs|dx|refactor|perf|test|locale|workflow|build|ci|chore|types|wip|release|deps|infra)(\(.+\))?\!?: .{1,50}/;
We could also think about to completely remove the verifyCommit script as we have the Semantic Pull Request action and only the PR title is important
the commits inside the PR can be written absolutely chaotically it doesn't matter

2022-08-13 11:23 UTC, ST-DDT requested changes
Please also add an example commit message for a changed locale file.

2022-08-13 11:28 UTC, ST-DDT commented on scripts/verifyCommit.ts
> +  /^(revert: )?(feat|fix|docs|dx|refactor|perf|test|locale|workflow|build|ci|chore|types|wip|release|deps|infra)(\(.+\))?\!?: .{1,50}/;
Theoretically yes, but I use the commit names as PR titles and sometimes I missspell them or forget about the prefix then the check reminds me to add them. Also I hope that it makes the commits easier to review because you can easier find a particular change if the commits follow a certain naming scheme.
I once worked in a project where someone used `.` as commit messages and it was really hard to check the history for relevant changes. It doesn't really matter if you only have a single commit, but the more it gets, the more important it becomes.

2022-08-13 11:55 UTC, ST-DDT submitted a review, later dismissed

2022-08-13 15:24 UTC, import-brain commented on .github/pull_request_template.md
> +<!-- Help us by directly write a correct PR title following this guide: https://github.com/faker-js/faker/blob/verify-semantic-pull-requests/CONTRIBUTING.md#committing -->
```suggestion
<!-- Help us by writing a correct PR title following this guide: https://github.com/faker-js/faker/blob/verify-semantic-pull-requests/CONTRIBUTING.md#committing -->
```

2022-08-13 20:14 UTC, ST-DDT approved these changes

2022-08-15 00:48 UTC, import-brain approved these changes

2022-08-16 08:52 UTC, merged