refactor(locale): move company.name formats to locales
faker-js/faker pull request #1279
Opened 2022-08-18 00:37 UTC by Minozzzi

2022-08-18 00:43 UTC, Minozzzi commented on src/locales/en/company/index.ts
> +import name_ from './name';
After running `pnpm run generate:locales` name became name_. Why can't it be `name`?

2022-08-18 04:41 UTC, Shinigami92 commented on src/locales/en/company/index.ts
> +import name_ from './name';
It might be historical, but VSCode hat conflicts with import / exports of constants named `name` and marked it as automatically deprecated 
Also `type` has problems and confuses TypeScript so we use `type_`

2022-08-18 04:45 UTC, Shinigami92 commented on src/modules/company/index.ts
> +    const formats = this.faker.definitions.company.name;
This is a full breaking change for Faker instances not using en as fallback ⚠️

2022-08-18 09:11 UTC, ST-DDT requested changes

2022-08-18 09:11 UTC, ST-DDT commented on src/definitions/company.ts
> +   * Company names.
These aren't names. These are patterns to generate names.

2022-08-18 12:33 UTC, Minozzzi commented on src/modules/company/index.ts
> +    const formats = this.faker.definitions.company.name;
This makes sense. What I need to do?

2022-08-18 13:15 UTC, Shinigami92 commented on src/modules/company/index.ts
> +    const formats = this.faker.definitions.company.name;
We could leave the static patterns and only override them with provided definitions if they are defined

In next major we can then fully remove it (could fit to one of our next planned milestones)

2022-08-18 13:16 UTC, Shinigami92 commented on src/definitions/company.ts
> +  name: string[];
Should we rename this to `name_patterns`?

2022-08-18 13:51 UTC, Minozzzi commented on src/definitions/company.ts
> +  name: string[];
I agree with this change, I will rename it

2022-08-18 14:23 UTC, ST-DDT commented on src/modules/company/index.ts
> +    const formats = this.faker.definitions.company.name;
I wouldn't do that.
If you don't want any breakage wait for the next major release. 
If a little bit is okay, keep it like this. There is no point in a temp fallback if you have a breaking change.

2022-08-18 14:24 UTC, ST-DDT commented on src/definitions/company.ts
> +  name: string[];
Please also rename the existing locale files.

2022-08-18 22:02 UTC, Minozzzi commented on src/modules/company/index.ts
> +    const formats = this.faker.definitions.company.name;
I agree with @Shinigami92. We could keep the static patterns and only override them if it has patterns in the current locale.
Could we going to this direction?

2022-08-18 22:29 UTC, ST-DDT commented on src/modules/company/index.ts
> +    const formats = this.faker.definitions.company.name;
IMO the and in the pattern makes it explicitly English. Currently English ist our fallback language anyway so it would be set. If someone explicitly removes the English fallback, then they dont want them, so it use it as a fallback here either.
Note, we are planning to automatically throw an error in that case in the future.

2022-08-19 02:55 UTC, Minozzzi commented on src/modules/company/index.ts
> +    const formats = this.faker.definitions.company.name;
I understand, so in this case are we going to just merge it into the next major version?

2022-08-19 07:06 UTC, ST-DDT commented on src/modules/company/index.ts
> +    const formats = this.faker.definitions.company.name;
I think there is no need to wait.
Its like adding a new locale data for some locales, I dont consider it breaking at all.

2022-08-19 07:09 UTC, Shinigami92 commented on src/modules/company/index.ts
> +    const formats = this.faker.definitions.company.name;
@ST-DDT so we don't do **semver** anymore?

2022-08-19 07:10 UTC, ST-DDT submitted a review, later dismissed

2022-08-19 07:12 UTC, ST-DDT commented on src/modules/company/index.ts
> +    const formats = this.faker.definitions.company.name;
Why do you consider this a breaking change?

2022-08-19 07:12 UTC, Shinigami92 requested changes

2022-08-19 07:12 UTC, Shinigami92 commented on src/modules/company/index.ts
> +        proposed: 'faker.company.name() or faker.fake(format)',
```suggestion
        proposed: 'faker.company.name() or faker.helpers.fake(format)',
```

2022-08-19 07:24 UTC, Shinigami92 commented on src/modules/company/index.ts
> +    const formats = this.faker.definitions.company.name;
https://github.com/faker-js/faker/pull/1279#discussion_r948644676

2022-08-19 07:46 UTC, ST-DDT commented on src/modules/company/index.ts
> +    const formats = this.faker.definitions.company.name;
I think we are running in circles now.

@Minozzzi so lets just do us more work and use the existing format array as fallback for now.
Please also add a TODO comment there that the fallback should be removed eventually.
After the PR is merged we will then create an issue for it, so it doesn't get lost.

2022-08-19 11:36 UTC, Minozzzi commented on src/modules/company/index.ts
> +        proposed: 'faker.company.name() or faker.fake(format)',
Thanks!

2022-08-21 21:41 UTC, ST-DDT commented on src/modules/company/index.ts
> +    // TODO: This `staticFormats` pattern should be removed in the future. It is only used to maintain backwards compatibility.
TODO: Create an issue for this on merge.

2022-08-21 21:41 UTC, ST-DDT submitted a review, later dismissed

2022-08-21 23:31 UTC, Minozzzi commented on src/modules/company/index.ts
> +    // TODO: This `staticFormats` pattern should be removed in the future. It is only used to maintain backwards compatibility.
Can I create the issue?

2022-08-22 00:03 UTC, Minozzzi commented
Guys, I've problems with rebase. I'will close this PR and open another

2022-08-22 00:03 UTC, closed without merging