feat(name): add sexType method
faker-js/faker pull request #1289
Opened 2022-08-19 12:47 UTC by Shinigami92

Requested by @ST-DDT via https://github.com/faker-js/faker/issues/776#issuecomment-1220384286

This function is just a helper for users that want to use faker instead of plain TS

2022-08-19 12:53 UTC, ST-DDT requested changes

2022-08-19 12:53 UTC, ST-DDT commented on src/modules/name/index.ts
> +    return this.faker.helpers.arrayElement(Object.values(Sex));
maybe use: https://fakerjs.dev/api/helpers.html#objectvalue

2022-08-19 12:53 UTC, ST-DDT commented on test/name.spec.ts
> +      'sexType',
This doesn't take any arguments as the test tries to check.

2022-08-19 13:12 UTC, ST-DDT approved these changes

2022-08-21 19:57 UTC, import-brain approved these changes

2022-08-22 08:02 UTC, merged