refactor(unique): move to helpers
faker-js/faker pull request #1298
Opened 2022-08-24 20:13 UTC by xDivisionByZerox

This PR moves the `unique()` method from the `Unique` module into the `Helpers` module. There is no reason for it being a standalone module when it is clearly a utility method.

This was discussed in https://github.com/faker-js/faker/discussions/805 ([direct link](https://github.com/faker-js/faker/discussions/805#discussioncomment-2539551)).

2022-08-24 20:13 UTC, xDivisionByZerox commented on src/modules/unique/index.ts
> +  constructor(private readonly faker: Faker) {
Does this change make the entire PR "breaking"?

2022-08-24 20:31 UTC, Shinigami92 commented on src/modules/unique/index.ts
> +  constructor(private readonly faker: Faker) {
We could be in luck here, as we do not yet export the Module constructors on their own

2022-08-24 21:58 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +import * as uniqueExec from '../unique/unique';
IMO these should be moved the helpers module (folder) too.

2022-08-25 06:48 UTC, Shinigami92 requested changes

2022-08-25 06:48 UTC, Shinigami92 commented on src/modules/unique/index.ts
> +      proposed: 'faker.helpers.fake()',
`fake`?! what? I thought this is `unique` 😆

2022-08-27 20:38 UTC, xDivisionByZerox commented on src/modules/unique/index.ts
> +      proposed: 'faker.helpers.fake()',
Done. Was copying the deprecation from `fake` for convenience reasons^^

2022-08-27 20:38 UTC, Shinigami92 approved these changes

2022-08-29 10:55 UTC, ST-DDT approved these changes

2022-08-29 11:10 UTC, merged