infra: set renovate schedule to weekly
faker-js/faker pull request #1302
Opened 2022-08-25 18:38 UTC by xDivisionByZerox

This PR changes the interval from "at any time" to a weekly basis every Monday morning via a [cron](https://crontab.guru/crontab.5.html) expression. 

Important reference links:
- [Renovate schedule config](https://docs.renovatebot.com/configuration-options/#schedule)
- [Cron expression descriptor (for cron expression validation)](https://crontab.cronhub.io/)

2022-08-25 18:39 UTC, xDivisionByZerox commented on .github/renovate.json5
> +    // Every minute, between 12:00 AM and 12:59 AM, only on Monday (minutes are not suppoted)
I just wanted to leave this here so it's clear why the expression is the way it is. Is this a valid thought or should this be removed?

2022-08-25 18:45 UTC, Shinigami92 submitted a review, later dismissed
Maybe we should use just: https://docs.renovatebot.com/presets-schedule/#scheduleweekly

2022-08-25 18:46 UTC, ST-DDT commented on .github/renovate.json5
> +    // Every minute, between 12:00 AM and 12:59 AM, only on Monday (minutes are not suppoted)
Why every minute?

I also have found this, which might be a bit more readable although I don't know how this could be changed to achieve exactly what we want:

` "after 5pm on the 2nd day of the month"`

2022-08-25 18:51 UTC, xDivisionByZerox commented on .github/renovate.json5
> +    // Every minute, between 12:00 AM and 12:59 AM, only on Monday (minutes are not suppoted)
We want weekly, not monthly (as your phrase suggests).
Weekly would be `"at 12am on Monday"`.

2022-08-25 18:58 UTC, xDivisionByZerox commented on .github/renovate.json5
> +    // Every minute, between 12:00 AM and 12:59 AM, only on Monday (minutes are not suppoted)
> Why every minute?

Line 7. Renovate requires a '*' (translates to `every`) for the minute position.

2022-08-25 18:59 UTC, xDivisionByZerox commented
> Maybe we should use just: https://docs.renovatebot.com/presets-schedule/#scheduleweekly

I don't see why. Cron expressions are a known standard for developers (at least to some degree). This language thing seems nice for readability purposes but has no documentation whatsoever. I also really dislike the idea of expressing what I want in plain English and a machine gets what I want.

I'll not block this, because if this. I just don't see the reason why this would be a required change for a merge on this PR.

2022-08-25 19:08 UTC, Shinigami92 commented
Everyone using renovate is using this syntax
Its the absolutely normal way of configuring renovate

- https://github.com/vitejs/vite/blob/5df788dfe2d89e541461e166f03afb38c2f1dd7e/.github/renovate.json5#L2
- https://github.com/prettier/plugin-pug/blob/d520345569c50dfa3350588bb835dce6ccf4e008/.github/renovate.json5#L3
- https://github.com/vitest-dev/vitest/blob/88d5764894f62449540209567df19926e46a91f3/.github/renovate.json5#L2

And what do you mean by not documented? I linked you the documentation ^^
You can even read more about it here: https://docs.renovatebot.com/config-presets/#how-to-use-preset-configs
And even more: https://docs.renovatebot.com/configuration-options/#schedule

2022-08-25 19:15 UTC, xDivisionByZerox commented
So what does the syntax translates to when I write the following

>Take yourself 3 out times before midnight but only on a full moon in winter

Does this run at all? That's what I mean by documented. You linked just a bunch of examples that are marked as "documentation". If I can just write plain English, what words do actually get picked up for the expression?

But whatever, I will just change the expression.

2022-08-25 20:39 UTC, Shinigami92 requested changes

2022-08-25 20:39 UTC, Shinigami92 commented on .github/renovate.json5
>    "extends": ["config:base", "schedule:daily", "group:allNonMajor"],
```suggestion
  "extends": ["config:base", "schedule:earlyMondays", "group:allNonMajor"],
```

2022-08-25 20:39 UTC, Shinigami92 commented on .github/renovate.json5
> +  "schedule": ["at 12am on Monday"],
```suggestion
```

2022-08-25 20:40 UTC, Shinigami92 approved these changes

2022-08-25 20:50 UTC, ST-DDT approved these changes

2022-08-25 20:50 UTC, merged

2022-08-25 20:53 UTC, xDivisionByZerox commented
If your have such specific standards to workflow configuration or code standards in general please don't ask next time in the meeting who whats to take the task if you insist on doing it your way :)

2022-08-25 20:59 UTC, Shinigami92 commented
> If your have such specific standards to workflow configuration or code standards in general please don't ask next time in the meeting who whats to take the task if you insist on doing it your way :)

But then I couldn't approve it and would need to ask another reviewer :see_no_evil:

2022-09-03 03:17 UTC, 1LISA2 commented
![images (2)](https://user-images.githubusercontent.com/103248540/188253784-aa4ec7d3-7df1-4b8a-9f57-15df18b13a46.jpeg)
![下载 (2)](https://user-images.githubusercontent.com/103248540/188253787-9a24142d-be41-4df9-8380-cb39f10e7b94.jpeg)