fix(datatype): unintentional hex breaking change
faker-js/faker pull request #1306
Opened 2022-08-26 22:53 UTC by import-brain

2022-08-26 22:56 UTC, xDivisionByZerox commented on src/modules/color/index.ts
> +        .slice(2);
Use the explicitly an empty prefix? If we have the feature, use it.
```suggestion
        .hexadecimal({ length: includeAlpha ? 8 : 6, prefix: '' })
```

2022-08-26 22:57 UTC, xDivisionByZerox commented on src/modules/database/index.ts
> +      .replace('0x', '');
You are getting creative with the removes?^^
```suggestion
      .hexadecimal({ length: 24, case: 'lower', prefix: '' });
```

2022-08-26 22:58 UTC, xDivisionByZerox requested changes

2022-08-26 22:58 UTC, xDivisionByZerox commented on src/modules/datatype/index.ts
> -    const { length = 1, prefix = '', case: letterCase = 'mixed' } = options;
Why did you drop the entire feature? Just revert the default value here to `'0x'` instead of `''`.

2022-08-27 08:31 UTC, xDivisionByZerox commented on src/modules/git/index.ts
> +      .substring(2);
Use `prefix` instead of string manipulation.

```suggestion
      .hexadecimal({ length: 40, case: 'lower', prefix: '' });
```

2022-08-27 08:32 UTC, xDivisionByZerox commented on src/modules/git/index.ts
> +      .substring(2);
Use `prefix` instead of string manipulation.

```suggestion
      .hexadecimal({ length: 7, case: 'lower', prefix: '' });
```

2022-08-27 08:37 UTC, xDivisionByZerox submitted a review, later dismissed

2022-08-27 11:33 UTC, Shinigami92 requested changes

2022-08-27 11:33 UTC, Shinigami92 commented on src/modules/git/index.ts
> +    return this.faker.datatype.hexadecimal({
prettier check is asking for a format

2022-08-27 17:00 UTC, import-brain commented
@xDivisionByZerox Thank you for the refactoring help, I missed those instances of string manipulation.

2022-08-28 13:39 UTC, Shinigami92 approved these changes

2022-08-28 13:50 UTC, xDivisionByZerox approved these changes

2022-08-28 13:59 UTC, merged