feat(locale): adding more complexity to es locales
faker-js/faker pull request #1320
Opened 2022-08-30 20:17 UTC by rasputino

Just adding some longer and composite names and last names for persons and a special character town name.

2022-08-30 20:24 UTC, ST-DDT approved these changes

2022-08-30 21:00 UTC, ST-DDT submitted a review, later dismissed

2022-08-31 00:55 UTC, import-brain submitted a review, later dismissed

2022-08-31 10:06 UTC, ST-DDT approved these changes

2022-08-31 10:20 UTC, pkuczynski commented on src/locales/es/date/month.ts
> +  wide_context: [
This is the same as `wide` and is optional, so I would not add it. Makes files bigger for no value.

2022-08-31 10:21 UTC, pkuczynski requested changes

2022-08-31 10:21 UTC, pkuczynski commented on src/locales/es/date/weekday.ts
> +  wide_context: [
Same here...

2022-08-31 16:13 UTC, ST-DDT approved these changes

2022-08-31 17:51 UTC, import-brain approved these changes

2022-08-31 21:02 UTC, pkuczynski approved these changes

2022-08-31 21:56 UTC, merged