docs: add since tags to all public methods, show available since in docs
faker-js/faker pull request #1337
Opened 2022-09-06 18:34 UTC by matthewmayer

Following on from discussion in https://github.com/faker-js/faker/discussions/1241 i added `@since` jsdoc tags to all existing public methods, and exposed this in the documentation:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/152770/188712441-4e94612b-2724-4b8d-89bc-3f82f4d0fb7e.png">

This is a one-off large diff for this initial integration, in future it would just be necessary to add `@since` tags for any newly added methods.

2022-09-06 18:48 UTC, xDivisionByZerox commented on scripts/apidoc/utils.ts
> + * Extracts the "since"
Not sure about this description.

```suggestion
 * Extracts the "since" tag from the provided signature.
```

2022-09-06 18:52 UTC, ST-DDT requested changes
I think I like this.

Please also add a new test case to: https://github.com/faker-js/faker/blob/main/test/scripts/apidoc/signature.example.ts

Also not sure whether there should be an empty line after the `@examples` and before `@since`.

2022-09-06 18:52 UTC, ST-DDT commented on scripts/apidoc/utils.ts
> +/**
```suggestion
}

/**
```

2022-09-06 18:52 UTC, ST-DDT commented on src/modules/color/index.ts
> +   * Returns a random human readable color name
```suggestion
   * Returns a random human readable color name.
```

2022-09-06 19:02 UTC, xDivisionByZerox commented
> Also not sure whether there should be an empty line after the `@examples` and before `@since`.

There definitely should be IMO. Looks a lot better with all topics grouped. Much easier to scan (as a human) as well.

2022-09-06 19:09 UTC, xDivisionByZerox requested changes
Please add spaces around the `@since` tag so it aligns with the other tags.

2022-09-06 19:14 UTC, ST-DDT commented on src/modules/address/index.ts
> +   * @since 2.0.1
https://github.com/faker-js/faker/discussions/1241#discussioncomment-3367044

2022-09-07 00:19 UTC, matthewmayer commented
> I think I like this.
> 
> 
> 
> Please also add a new test case to: https://github.com/faker-js/faker/blob/main/test/scripts/apidoc/signature.example.ts
> 
> 
> 
> Also not sure whether there should be an empty line after the `@examples` and before `@since`.

Sorry my typescript is not really up to this. Maybe someone else can help me with the tests

2022-09-07 05:13 UTC, matthewmayer commented
added the newlines and made the other suggested changes.

2022-09-07 06:48 UTC, ST-DDT reviewed
I will address the test later today.

2022-09-07 06:48 UTC, ST-DDT commented on src/modules/address/index.ts
> +   *
This is one newline too much.

2022-09-07 08:16 UTC, Shinigami92 reviewed
Really cool 👍 
Count me as approved when all the missing requested/required tasks are finished

2022-09-07 08:16 UTC, Shinigami92 commented on src/modules/address/index.ts
> +   *
```suggestion
```

2022-09-07 11:59 UTC, ST-DDT requested changes
faker.fake and faker.unique are missing the `@since` tags.
The `@since` tags won't be picked up for the color module.
I'm not sure why.

2022-09-07 12:05 UTC, ST-DDT commented
The color methods have multiple signatures. You have to add the `@since` either the last one (with jsdocs) or all of them.

2022-09-07 20:45 UTC, xDivisionByZerox approved these changes, later dismissed

2022-09-08 03:08 UTC, matthewmayer commented
In general it seems its only reading the JSDoc for the last version of a method with multiple signatures like `faker.color.rgb()`? So in general should the since tag be only added to the last one, or all of them?

2022-09-08 06:59 UTC, ST-DDT commented
I think the last one is enough.

2022-09-08 07:11 UTC, Shinigami92 commented
Current test results in CI:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/7195563/189058089-830a1780-024c-4b9f-bb72-149c2bc0f88a.png">

2022-09-08 07:14 UTC, matthewmayer commented
i agree maybe all is better. will manually fix the ones in color

2022-09-08 07:15 UTC, matthewmayer commented
@Shinigami92 how can i run those tests locally to make sure I caught everything?

2022-09-08 07:34 UTC, Shinigami92 approved these changes, later dismissed

2022-09-08 07:46 UTC, xDivisionByZerox requested changes

2022-09-08 07:46 UTC, xDivisionByZerox commented on src/modules/color/index.ts
> +   * @since 7.0.0
Duplicated tag in the same signature.

2022-09-08 08:15 UTC, ST-DDT commented on src/modules/color/index.ts
> +   * @since 7.0.0
```suggestion
   *
   * @since 7.0.0
```

2022-09-08 09:38 UTC, matthewmayer commented
fixed those two issues

2022-09-08 09:54 UTC, ST-DDT approved these changes

2022-09-08 10:11 UTC, xDivisionByZerox approved these changes

2022-09-08 16:18 UTC, pkuczynski approved these changes

2022-09-08 16:40 UTC, merged