docs: locales
faker-js/faker pull request #1364
Opened 2022-09-10 11:15 UTC by Shinigami92

closes #1322

2022-09-10 11:20 UTC, xDivisionByZerox commented on docs/guide/locales.md
> +:::
This will be removed VERY soon. Is it really that clever to add this now so ppl potentially read it and get used to it?

If you added it because "currently it is as it is, so we have to work with it" I don't understand why you block #1304 🤔

2022-09-10 11:25 UTC, xDivisionByZerox commented on docs/guide/locales.md
> +This will then just load the german locales with additional english locales as fallback.
We should mention why the English fallback is required.

```suggestion
This will then just load the german locales with additional English locales as fallback. The fallback is required due to not all locales supporting all features. If you encounter a missing locale feature in your required language, feel free to open a Pull Request fixing that issue.
```

2022-09-10 11:28 UTC, xDivisionByZerox commented on docs/guide/locales.md
> +In v7 and earlier versions faker always use english as fallback. The english locales are around 600 KB in size. In v8 we plan to change the behavior and allow to create custom faker instances with e.
I don't think this belongs here, as it should be already described in the roadmap (?). Maybe link to it instead?

2022-09-10 11:37 UTC, Shinigami92 commented on docs/guide/locales.md
> +:::
When switching to v8, we create a v7 github branch for the last tag as we did with v6 (https://v6.fakerjs.dev/)
Then when going to the "old docs" you can read this in there, but when reading the v8 version of the docs, this obviously will be updated/gone

2022-09-10 11:40 UTC, ST-DDT commented on docs/guide/locales.md
> +:::
Also it is wrong. This was already possible in v7.0 and potentially earlier:

https://github.com/faker-js/faker/blob/04117993e8754938f1a5f4543201b2d349b9d2aa/src/faker.ts#L45-L48

2022-09-10 11:45 UTC, ST-DDT reviewed
Please add a newline after each sentence to avoid 200+char long lines.
Please also make sure that you refer to `Faker` consistently (vs `faker`).
Languages are always capitalized.

2022-09-10 11:45 UTC, ST-DDT commented on docs/guide/locales.md
> +And we got you back! You can import specific pre-configured faker instances for each locale by just using e.g. `import { faker } from '@faker-js/faker/locale/de'`.
```suggestion
And we got your back! You can import specific pre-configured faker instances for each locale by just using e.g. `import { faker } from '@faker-js/faker/locale/de'`.  
```

2022-09-10 11:45 UTC, ST-DDT commented on docs/guide/locales.md
> +In v7 and earlier versions faker always use english as fallback. The english locales are around 600 KB in size. In v8 we plan to change the behavior and allow to create custom faker instances with e.
This is only true for the prebuild faker instances.

2022-09-10 11:45 UTC, ST-DDT commented on docs/guide/locales.md
> +You will then safe these 600 KB of memory overhead but might run into issues when there is no value provided in the german locales.
```suggestion
You will then safe these 600 KB of memory overhead but might run into issues when there is no value provided in the german locales yet.
```

2022-09-10 11:53 UTC, Shinigami92 commented on docs/guide/locales.md
> +:::
Oh you are right... we just made it safer...

2022-09-10 11:55 UTC, Shinigami92 commented on docs/guide/locales.md
> +In v7 and earlier versions faker always use english as fallback. The english locales are around 600 KB in size. In v8 we plan to change the behavior and allow to create custom faker instances with e.
Okay I will rewrite this part and write everything from the perspective of v7, so like v8 is "not planned" yet in that perspective

2022-09-10 11:57 UTC, Shinigami92 commented on docs/guide/locales.md
> +And we got you back! You can import specific pre-configured faker instances for each locale by just using e.g. `import { faker } from '@faker-js/faker/locale/de'`.
TIL 😲

2022-09-10 13:45 UTC, ST-DDT requested changes

2022-09-10 13:45 UTC, ST-DDT commented on docs/guide/localization.md
> +This will then just load the German locales with additional English locales as fallback. The fallback is required due to not all locales contain data for all features. If you encounter a missing loca
```suggestion
This will then just load the German locales with additional English locales as fallback. The fallback is required due to not all locales containing data for all features. If you encounter a missing locale entry in your selected language, feel free to open a Pull Request fixing that issue.
```

2022-09-10 13:45 UTC, ST-DDT commented on scripts/generateLocales.ts
>  const pathDocsApiLocalization = resolve(
This is no longer the path for `docs/api/localization`

2022-09-10 13:53 UTC, xDivisionByZerox approved these changes, later dismissed

2022-09-10 16:57 UTC, import-brain commented on README.md
>  Please note that not every locale provides data for every module. In out pre-made locales, we fallback to english in such a case as this is the most complete and most common used language.
```suggestion
Please note: not every locale provides data for every module. In our pre-made locales, we fallback to English in such a case as this is the most complete and most commonly used language.
```

2022-09-10 17:16 UTC, ST-DDT approved these changes, later dismissed

2022-09-10 17:49 UTC, import-brain approved these changes, later dismissed

2022-09-10 17:55 UTC, xDivisionByZerox approved these changes, later dismissed

2022-09-11 12:51 UTC, ST-DDT approved these changes

2022-09-11 13:41 UTC, import-brain approved these changes

2022-09-11 13:41 UTC, merged