docs: `usage` page in `guides`
faker-js/faker pull request #1366
Opened 2022-09-10 14:11 UTC by xDivisionByZerox

This PR moves the usage section from 'Getting started' in it's own page.

2022-09-10 14:47 UTC, Shinigami92 commented on docs/guide/usage.md
> +:::tip Note
```suggestion
:::tip
```

or

```suggestion
:::note
```

2022-09-10 14:47 UTC, Shinigami92 commented on docs/guide/usage.md
> +In order to have faker working properly, you need to check if these `compilerOptions` are set correctly in your `tsconfig` file:
```suggestion
In order to have Faker working properly, you need to check if these `compilerOptions` are set correctly in your `tsconfig` file:
```

2022-09-10 14:52 UTC, Shinigami92 commented on docs/guide/usage.md
> +```
You should mention if someone uses v5 or lower they should look into the v6 TypeScript support docs

2022-09-10 16:53 UTC, import-brain requested changes

2022-09-10 16:53 UTC, import-brain commented on docs/guide/usage.md
> +Faker has native TypeScript support, out of the box. So you don't have to install any extra packages.
```suggestion
Faker supports TypeScript out of the box, so you don't have to install any extra packages.
```

2022-09-10 16:53 UTC, import-brain commented on docs/guide/usage.md
> +Faker mostly generates vales for primitives.
```suggestion
Faker mostly generates values for primitives.
```

2022-09-10 16:53 UTC, import-brain commented on docs/guide/usage.md
> +For our example, we use typescript to strongly type our model.
```suggestion
For our example, we use TypeScript to strongly type our model.
```

2022-09-10 16:53 UTC, import-brain commented on docs/guide/usage.md
> +This is because in the real world most object schemas simply look way too different.
```suggestion
This is because in the real world, most object schemas simply look very different.
```

2022-09-10 16:53 UTC, import-brain commented on docs/guide/usage.md
> +So if you want to create an object you most likely need to write a factory function for it.
```suggestion
So, if you want to create an object, you most likely need to write a factory function for it.
```

2022-09-10 16:53 UTC, import-brain commented on docs/guide/usage.md
> +}
```suggestion
class User {
  _id: string;
  avatar: string;
  birthday: Date;
  email: string;
  firstName: string;
  lastName: string;
  sex: SexType;
  subscriptionTier: SubscriptionTier;
}
```
We should make `firstname` and `lastname` camelCase in this example to keep it consistent with `subscriptionTier`.

2022-09-10 16:53 UTC, import-brain commented on docs/guide/usage.md
> +    lastname: faker.name.lastname(),
```suggestion
    firstName: faker.name.firstName(),
    lastName: faker.name.lastName(),
```

2022-09-14 18:59 UTC, ST-DDT approved these changes, later dismissed

2022-09-15 20:36 UTC, import-brain submitted a review, later dismissed

2022-09-15 20:45 UTC, import-brain commented on docs/guide/usage.md
> +Also, in a real scenario your model should not depend on a type of a third party library (`SexType` in this case).
```suggestion
Also, in a real scenario, your model should not depend on a type of a third party library (`SexType` in this case).
```

2022-09-15 20:45 UTC, import-brain commented on docs/guide/usage.md
> +At this point we have a perfectly working function that will work for most purposes.
```suggestion
At this point, we have a perfectly working function that will work for most purposes.
```

2022-09-15 20:45 UTC, import-brain commented on docs/guide/usage.md
> +Currently all properties are just randomly generated.
```suggestion
Currently, all properties are just randomly generated.
```

2022-09-15 20:45 UTC, import-brain commented on docs/guide/usage.md
> +This can lead to some undesirable values being produces.
```suggestion
This can lead to some undesirable values being produced.
```

2022-09-15 20:45 UTC, import-brain commented on docs/guide/usage.md
> +Lets refactor our current code:
```suggestion
Let's refactor our current code:
```

2022-09-15 20:45 UTC, import-brain commented on docs/guide/usage.md
> +By doing this first we are able to pass both names into the `email` generation function.
```suggestion
By doing this first, we are able to pass both names into the `email` generation function.
```

2022-09-15 20:45 UTC, import-brain commented on docs/guide/usage.md
> +Faker got your back, with another helper method:
```suggestion
Faker has your back, with another helper method:
```

2022-09-15 20:45 UTC, import-brain commented on docs/guide/usage.md
> +But in most use-cases this would be desireable.
```suggestion
But, in most use-cases, this would be desirable.
```
Please double check you mean "desirable" and not "undesirable".

2022-09-15 20:45 UTC, import-brain commented on docs/guide/usage.md
> +By wrapping Faker's `email` function with the [`unique`](../api/helpers.md#unique) helper function we ensure that the return value of `email` is always unique.
```suggestion
By wrapping Faker's `email` function with the [`unique`](../api/helpers.md#unique) helper function, we ensure that the return value of `email` is always unique.
```

2022-09-15 20:45 UTC, import-brain commented on docs/guide/usage.md
> +Congratulation, you should now be able to create any complex object you desire. Happy faking 🥳.
```suggestion
Congratulations, you should now be able to create any complex object you desire. Happy faking 🥳.
```

2022-09-15 20:46 UTC, import-brain commented on docs/guide/usage.md
> +First we generate a `sex` value to use it as input for the generation of `firstName`.
@xDivisionByZerox Sorry for the extreme nitpicking 😬

2022-09-16 18:48 UTC, xDivisionByZerox commented
> Nicely made, reads really fluent like a good tutorial blog post 👍 Would like to ship this soon

Thank you, this is really appreciated. Always discussing with myself if I should do stuff like a blog, but imposter syndrome is way to strong.

2022-09-21 14:35 UTC, ST-DDT approved these changes

2022-09-21 15:16 UTC, import-brain approved these changes

2022-09-26 09:18 UTC, Shinigami92 commented on docs/guide/usage.md
> +```
I still have this concern, but want to merge it for now...
Maybe it will go under 🤷 @ST-DDT how important would you see a mention for v5?

2022-09-26 09:22 UTC, merged