test(finance/bitcoinAddress): use validator.js to test generated data
faker-js/faker pull request #1375
Opened 2022-09-13 01:11 UTC by Minozzzi

Fixes: #1184

2022-09-13 06:39 UTC, Shinigami92 requested changes

2022-09-13 06:39 UTC, Shinigami92 commented on pnpm-lock.yaml
> +      JSONStream: 1.3.5
How did this happen?
If it's not related to the PR, I would suggest to revert it

2022-09-13 06:39 UTC, Shinigami92 commented on test/finance.spec.ts
> +          expect(isValidBtcAddress(bitcoinAddress)).toBeTruthy();
1. This should be below the typeof check as more generic primitive checks should be made first
   Otherwise you already know that it was a `string`
2. I think using `toSatisfiy` is a better fit here

2022-09-13 10:19 UTC, xDivisionByZerox commented on test/finance.spec.ts
> +          expect(isValidBtcAddress(bitcoinAddress)).toBeTruthy();
> 2. I think using `toSatisfiy` is a better fit her

Just to explain: `toSatisfiy` give a much easier  to understand error message then calling the validator function and check if thee result is truthy.

2022-09-13 10:21 UTC, xDivisionByZerox commented on pnpm-lock.yaml
> +      JSONStream: 1.3.5
I guess an auto formater on save. This way, the entries are sorted correctly (A-Z). Still, not related to this PR.

2022-09-16 21:52 UTC, Minozzzi commented on pnpm-lock.yaml
> +      JSONStream: 1.3.5
It happened because i added the validatorjs but i think it was already added and it just formatted. I can remove if needed

2022-09-18 16:55 UTC, Shinigami92 commented on pnpm-lock.yaml
> +      JSONStream: 1.3.5
yeah pls revert the file, it is not depended with the PR itself

2022-09-21 07:05 UTC, ST-DDT approved these changes

2022-09-21 11:19 UTC, import-brain approved these changes

2022-09-21 12:56 UTC, Shinigami92 approved these changes

2022-09-21 12:56 UTC, merged