add first name for zh_CN
faker-js/faker pull request #1376
Opened 2022-09-15 07:28 UTC by kaysonwu

add  `female_first_name` and  `male_first_name` for zh_CN

2022-09-15 18:16 UTC, ST-DDT approved these changes

2022-09-15 19:54 UTC, Shinigami92 commented
Please run `pnpm run format` once

2022-09-15 20:32 UTC, import-brain approved these changes

2022-09-15 20:32 UTC, import-brain commented
Names are legit👌

2022-09-26 16:42 UTC, ST-DDT requested changes
Please run `pnpm run format` or should we do that for you?

2022-09-29 14:59 UTC, Shinigami92 approved these changes

2022-09-29 16:27 UTC, ST-DDT approved these changes

2022-09-29 16:27 UTC, merged