feat(finance): branchCode option in bic()
faker-js/faker pull request #1378
Opened 2022-09-18 15:08 UTC by import-brain

closes #1158

2022-09-18 16:21 UTC, Shinigami92 requested changes

2022-09-18 16:21 UTC, Shinigami92 commented on src/modules/finance/index.ts
> +    const { branchCode = false } = options;
Previously the default was set via `this.faker.datatype.boolean()`
I think we need that back :thinking: 
Now the XXX will never be generated but especially I'm at HASPA they are mostly using `HASP DE HH XXX`

2022-09-18 16:23 UTC, ST-DDT commented on src/modules/finance/index.ts
> +      branchCode?: boolean;
Maybe use `useBranchCode` or `includeBranchCode`?

2022-09-18 17:26 UTC, import-brain commented on src/modules/finance/index.ts
> +      branchCode?: boolean;
Hmm, I really like `branchCode`. What does the team think?

2022-09-18 17:32 UTC, import-brain commented on src/modules/finance/index.ts
> +    const { branchCode = false } = options;
Are you saying you want the options destructuring to be like this?
`const { branchCode = this.faker.datatype.boolean() } = options;`

What do you mean by `XXX` would never be generated? It currently generates three capital alphanumeric characters, so there should be a chance of getting `XXX`. I'm probably misunderstanding what you mean, though

2022-09-18 18:52 UTC, Shinigami92 commented on src/modules/finance/index.ts
> +    const { branchCode = false } = options;
Yes, but `XXX` is a more generic case and should be occur more often

2022-09-18 18:54 UTC, Shinigami92 commented on src/modules/finance/index.ts
> +      branchCode?: boolean;
From a user perspective I think @ST-DDT is right

2022-09-20 06:50 UTC, Shinigami92 commented
Tests dont pass

2022-09-20 11:12 UTC, import-brain commented on test/finance.spec.ts
> +            : expect(bic).toMatch(/^[A-Z]{6}[A-Z0-9]{2}[A-Z0-9]{3}$/);
```suggestion
          bic.length === 8
            ? expect(bic).toMatch(/^[A-Z]{6}[A-Z0-9]{2}$/)
            : expect(bic).toMatch(/^[A-Z]{6}[A-Z0-9]{2}[A-Z0-9]{3}$/);
```
This is a bit janky, any better way to write this?

2022-09-20 12:24 UTC, ST-DDT commented on test/finance.spec.ts
> +            : expect(bic).toMatch(/^[A-Z]{6}[A-Z0-9]{2}[A-Z0-9]{3}$/);
Wrap the last part in parenthesis and add a question mark behind this to mark it as optional.

2022-09-20 12:27 UTC, ST-DDT commented
Also: https://github.com/validatorjs/validator.js/blob/master/src/lib/isBIC.js

2022-09-20 15:09 UTC, import-brain commented
Seems like `validator.isBIC` does not recognize `XK` (Kosovo) as a country code

2022-09-20 15:25 UTC, ST-DDT commented
> Seems like `validator.isBIC` does not recognize `XK` (Kosovo) as a country code, it intermittently fails when `XK` is the country code

Maybe report this to validatorjs for them to fix?

2022-09-20 17:23 UTC, import-brain commented
> > Seems like `validator.isBIC` does not recognize `XK` (Kosovo) as a country code, it intermittently fails when `XK` is the country code
> 
> Maybe report this to validatorjs for them to fix?

https://github.com/validatorjs/validator.js/issues/2045

2022-09-20 17:39 UTC, ST-DDT approved these changes

2022-09-22 16:27 UTC, merged