docs: an update from the faker team
faker-js/faker pull request #138
Opened 2022-01-14 07:43 UTC by JessicaSachs

Hey folks, this is what I was able to put together. I believe this is accurate and inline with things we've previously discussed.

2022-01-14 08:05 UTC, Shinigami92 commented on docs/update.md
> +Faker is funded by an [Open Collective](https://opencollective.com/fakerjs), and so on January 12th, 2022, I contacted Ben Nickolls, the Executive Director at Open Collective.
Could we link somehow `Ben Nickolls`?

2022-01-14 08:05 UTC, Shinigami92 commented on docs/update.md
> +The Faker project was maintained by Marak Squires, an early-days impactful Node enthusiast and professional who went rogue and acted maliciously on January 4th, 2022.
Reading the article top to bottom, we may link `rogue and acted maliciously` to some external source, or rewrite it a bit.
The block below I read "to late"

2022-01-14 08:43 UTC, JessicaSachs commented on docs/update.md
> +Faker is funded by an [Open Collective](https://opencollective.com/fakerjs), and so on January 12th, 2022, I contacted Ben Nickolls, the Executive Director at Open Collective.
Done.

2022-01-14 08:43 UTC, JessicaSachs commented on docs/update.md
> +The Faker project was maintained by Marak Squires, an early-days impactful Node enthusiast and professional who went rogue and acted maliciously on January 4th, 2022.
Done.

2022-01-14 12:54 UTC, Shinigami92 approved these changes, later dismissed

2022-01-14 21:49 UTC, alxndr commented
Thank you for the transparency!

2022-01-14 23:12 UTC, prisis approved these changes, later dismissed

2022-01-15 04:22 UTC, damienwebdev requested changes

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +Faker’s financial support is held on behalf of the project by https://www.oscollective.org/ and managed on https://opencollective.com/fakerjs, and so on January 12th, 2022, we contacted https://twitt
I think we should use Ben's full name here, with a link to his twitter.

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +During the conversation with Ben, he went over the terms and conditions of the Open Collective with me.
`me -> the maintainers`

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +Unanimously, we agreed that we **wanted absolutely no ability to touch the existing funding** and created a cut-over plan with the support of Open Collective.
disambiguate `we` with "all of the maintainers of this project" agreed

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +After the funds were moved we were invited to become admins of the Faker collective. This meant that _we retained the existing sponsors_ of the [Faker](https://opencollective.com/fakerjs) collective
After the funds were moved => After the funds were moved, (Missing comma)

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +We believed that this was the most equitable and transparent way to act. The project's sponsors were able to continue to support the project and its ongoing development. Marak and Brian were able to
Tense should be present, "We believed that this is the most equitable and transparent way to act. The project's sponsors are able to continue to support the project and its ongoing development and Marak and Brian are able to retain the $11,652.69 USD previously donated to the project and can do with as they see fit."

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +An e-mail from our team will also arrive in the next few days notifying Open Collective sponsors that the maintainer team has changed.
The should be moved above near the chunk about "This meant that _we retained the existing sponsors_"

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +For those who were sponsoring the fakerjs open collective as a way to personally sponsor Marak, please donate to the [fakerjs-legacy open collective](https://opencollective.com/fakerjs-legacy) OR [Ma
I think 

> We don't know which is his preferred one. We will update this notice and post a new link if we hear otherwise from Marak.

Is unnecessary.

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +This project **can** have a fresh start and it will become _even cooler_.
Opinion:

This project **can** have a fresh start and it will become _even cooler_.

To:

This is a fresh start.

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +We felt we needed to do a public announcement because of all of the attention the project received in the media and from the community.
This is implicit because we wrote this, I think this is unnceccesary.

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +_\- Jessica Sachs and the Faker Team_
Opinion:

You're a member of the Faker team. 

> The Faker Team.

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +We want the project to have a fresh start and become _even cooler_.
Opinion:

> We want the project to have a fresh start and become _even cooler_.

To: 

> We want the project to have a fresh start.

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +We're referring to it as the official library in the immediate term in order to disambiguate between the many rewrites and forks that are not community-maintained. We've [merged all active forks to d
Conjunctions:

We're -> We are

We'll -> We will

We've -> We have

There's -> There is

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +Faker has never had an official docs website and the awesome [Jeff Beltran](https://github.com/JeffBeltran) has been maintaining a project called "[Un-Official faker.js Documentation](https://github.
Faker has never had an official docs -> Faker never had an official docs

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +He gave us permission to re-use his work to create **[fakerjs.dev](https://fakerjs.dev)**
Link to the permission?

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +Jess posted a [concise and thorough writeup](https://github.com/faker-js/faker/discussions/56#discussioncomment-1958057) of the logic behind our actions and decisions.
Link your Github here?

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +We came to the determination that users unfamiliar with the whole Faker situation wouldn't know that the repository's sponsorship links aren't funding the continued development of the project.
wouldn't -> would not

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +We came to the determination that users unfamiliar with the whole Faker situation wouldn't know that the repository's sponsorship links aren't funding the continued development of the project.
aren't -> are not

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +Ben said that simply, "The funding is attached to the project, not the current maintainer."
Ben said that simply -> Ben simply said

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +Unanimously, we agreed that we **wanted absolutely no ability to touch the existing funding** and created a cut-over plan with the support of Open Collective.
Unanimously, we agreed -> After discussion, we unanimously agreed

2022-01-15 04:22 UTC, damienwebdev commented on docs/update.md
> +:::tip Legacy collective
"Legacy Collective" -> "The Cutover Plan"

2022-01-15 07:36 UTC, JessicaSachs commented on docs/update.md
> +Faker’s financial support is held on behalf of the project by https://www.oscollective.org/ and managed on https://opencollective.com/fakerjs, and so on January 12th, 2022, we contacted https://twitt
He gave me this exact wording, so no.

2022-01-15 07:36 UTC, JessicaSachs commented on docs/update.md
> +During the conversation with Ben, he went over the terms and conditions of the Open Collective with me.
YES I knew I missed one.

2022-01-15 07:52 UTC, JessicaSachs commented on docs/update.md
> +We want the project to have a fresh start and become _even cooler_.
Hmm, this changes the tone. My goal is to have an exciting and uplifting update.

2022-01-15 07:55 UTC, JessicaSachs commented on docs/update.md
> +_\- Jessica Sachs and the Faker Team_
I asked my partner (an editor and author) about this because I wasn't sure. Calling the writer out as speaking on behalf of the group is correct.

2022-01-15 18:55 UTC, damienwebdev approved these changes

2022-01-15 19:10 UTC, Shinigami92 approved these changes

2022-01-15 19:33 UTC, import-brain approved these changes

2022-01-15 20:14 UTC, prisis approved these changes

2022-01-15 20:18 UTC, merged