fix(image): properly lock loremflickr.com images
faker-js/faker pull request #1396
Opened 2022-09-26 18:35 UTC by wesen

https://loremflickr.com requires the lock= parameter to be given
to serve an identical image (at least as long as its cache is not
updated).

2022-09-26 18:49 UTC, ST-DDT approved these changes

2022-09-26 18:53 UTC, ST-DDT requested changes

2022-09-26 18:53 UTC, ST-DDT commented on src/modules/image/index.ts
> +      url += `?lock=0`;
This changes the current behavior. Currently, returning a random picture is intentional.
In the next major version we plan to change the default of randomize to true.

2022-09-26 19:18 UTC, wesen commented on src/modules/image/index.ts
> +      url += `?lock=0`;
does this mean that randomize = false still randomizes the image? I'm sorry if I misunderstood the meaning.

2022-09-26 19:21 UTC, ST-DDT commented on src/modules/image/index.ts
> +      url += `?lock=0`;
Yes, `randomize === false` => no `lock` url suffix.

2022-09-26 19:22 UTC, ST-DDT requested changes

2022-09-26 19:22 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * faker.image.image(1234, 2345) // 'https://loremflickr.com/1234/2345/sports?lock=0'
Please adjust the examples accordingly.

2022-09-26 19:23 UTC, wesen commented on src/modules/image/index.ts
> +      url += `?lock=0`;
Updated!

2022-09-26 19:23 UTC, ST-DDT approved these changes

2022-09-26 19:37 UTC, import-brain approved these changes

2022-09-26 20:14 UTC, Shinigami92 approved these changes

2022-09-27 17:08 UTC, xDivisionByZerox approved these changes

2022-09-29 14:36 UTC, merged