infra: add CI step to detect generate:locales diffs
faker-js/faker pull request #1405
Opened 2022-10-02 02:16 UTC by sunadoi

After running the `generate:locales` command in the workflow/ci pipeline, check for some uncommitted diffs with the following command.

```
git add -N .
git diff --exit-code
```

- `-N` is required to detect untracked files.
- The `--exit-code` option causes it to fail if there are any diffs.

I tested this CI on my repository.
It seems to work well.
ref: https://github.com/sunadoi/faker/actions/runs/3164634036/jobs/5153063988

2022-10-02 10:23 UTC, ST-DDT reviewed
This does not detect deleted files, but I'm not sure whether this is necessary.

2022-10-02 11:22 UTC, sunadoi commented
> This does not detect deleted files

I didn't give it enough thought.
How about checking git diff before and after git add?
The former checks for file updates/deletions, the latter checks for file creation.

```
git diff --exit-code
git add -N .
git diff --exit-code
```

2022-10-02 11:55 UTC, Shinigami92 commented on .github/workflows/ci.yml
> +  generate-locales:
Please add a blank line here

```suggestion

  generate-locales:
```

2022-10-02 12:11 UTC, sunadoi commented on .github/workflows/ci.yml
> +  generate-locales:
Sorry for my simple mistake, I fixed it.

2022-10-02 12:15 UTC, sunadoi commented
To be able to detect deleted files, the method of checking for diffs has been changed to the following command.

```
git add .
git diff --cached --exit-code
```

2022-10-02 16:00 UTC, ST-DDT requested changes

2022-10-02 16:00 UTC, ST-DDT commented on .github/workflows/ci.yml
> +          git diff --cached --exit-code
Should we write an error message for the user with a hint what to do here?

2022-10-02 16:55 UTC, Shinigami92 commented on .github/workflows/ci.yml
> +    name: 'Locales Diff Detection: node-18, ubuntu-latest'
your suggestion makes it a bit better

2022-10-02 19:54 UTC, ST-DDT commented on .github/workflows/ci.yml
> +    name: 'Locales Diff Detection: node-18, ubuntu-latest'
Then lets go for it.

2022-10-03 04:13 UTC, sunadoi commented on .github/workflows/ci.yml
> +    name: 'Locales Diff Detection: node-18, ubuntu-latest'
Thank you for your suggestion!

2022-10-03 04:15 UTC, sunadoi commented on .github/workflows/ci.yml
> +          git diff --cached --exit-code
OK, I'm thinking about doing that using [github-script](https://github.com/actions/github-script),  and prompt the user to run `generate:locales` or `generate:api-docs` command via the comment.
This comment will be deleted if the CI passes.

2022-10-03 13:32 UTC, sunadoi commented on .github/commentCodeGeneration.js
> +  const body = `Uncommitted changes were detected after runnning <code>generate</code> command.\nPlease run <code>pnpm run generate:locales</code> or <code>pnpm run generate:api-docs</code> to genera
I'm not sure if this error message is correct.
If you have a better message, I would appreciate it if you could let me know.

2022-10-03 16:10 UTC, ST-DDT commented
I tried to run it in my fork and it doesn't work:
https://github.com/ST-DDT/faker/actions/runs/3175539763/jobs/5173706263#step:8:17

You might need the PR write permission for that action.
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

2022-10-04 05:31 UTC, sunadoi commented
> Please assign it for the lowest possible scope (e.g. only for this single job).

I gave permissions `pull-requests: write` in this job only, and it seems to work in my fork.
https://github.com/sunadoi/faker/actions/runs/3179609661/jobs/5182304903

2022-10-04 06:42 UTC, ST-DDT submitted a review, later dismissed

2022-10-04 06:59 UTC, Shinigami92 commented on .github/commentCodeGeneration.js
> +module.exports = async ({ github, context, isSuccess }) => {
I have two minor concerns here:
1. If we just have js instead of ts, could we at least use JSDoc typings for these?
2. Not sure if we should store the script here in `<project-root>/.github/` or somewhere else like in `scripts` folder or if possible `.github/workflows/`

2022-10-08 04:46 UTC, sunadoi commented on .github/commentCodeGeneration.js
> +module.exports = async ({ github, context, isSuccess }) => {
> If we just have js instead of ts, could we at least use JSDoc typings for these?

I added a JSDoc.
The purpose, github-script URL, and `@param` are written.

> Not sure if we should store the script here in `<project-root>/.github/` or somewhere else like in `scripts` folder or if possible `.github/workflows/`

I stored the script in `.github/workflows/`.

2022-10-08 10:39 UTC, ST-DDT reviewed
@Shinigami92 Is these Jsdocs what you intended with your request?
Maybe you could give an example of what you would like to have.

2022-10-08 10:39 UTC, ST-DDT commented on .github/workflows/commentCodeGeneration.js
> + * Notifies uncommitted changes generated by the `generate` command.
```suggestion
 * Notifies the PR about uncommitted changes generated by the `generate:*` commands.
```

2022-10-08 10:39 UTC, ST-DDT commented on .github/workflows/commentCodeGeneration.js
> +  const body = `Uncommitted changes were detected after runnning <code>generate</code> command.\nPlease run <code>pnpm run generate:locales</code> or <code>pnpm run generate:api-docs</code> to genera
```suggestion
  const body = `Uncommitted changes were detected after runnning <code>generate:*</code> commands.\nPlease run <code>pnpm run generate:locales</code> and <code>pnpm run generate:api-docs</code> to generate/update the related files, and commit them.`;
```

2022-10-08 14:19 UTC, Shinigami92 commented on .github/workflows/commentCodeGeneration.js
> + * @param isSuccess A boolean indicating whether the workflow was successful
Can we add types here via JSDoc types?

2022-10-08 14:45 UTC, ST-DDT commented on .github/workflows/commentCodeGeneration.js
> + * @param isSuccess A boolean indicating whether the workflow was successful
Please add an example so that it is clearer what you are referring to.

2022-10-08 15:11 UTC, Shinigami92 commented on .github/workflows/commentCodeGeneration.js
> + * @param isSuccess A boolean indicating whether the workflow was successful
https://jsdoc.app/tags-type.html

2022-10-08 16:29 UTC, Shinigami92 commented on .github/workflows/commentCodeGeneration.js
> + * @param isSuccess A boolean indicating whether the workflow was successful
Sorry I didn't had much time

So I expect something like 
`@param {import('the-GH-type-lib').GitHub} github Description text.`

You can see that it works when you hover over the param names.

2022-10-09 04:46 UTC, sunadoi commented on .github/workflows/commentCodeGeneration.js
> + * @param isSuccess A boolean indicating whether the workflow was successful
Thank you for your example.
Now, I clearly understand what to do.

We need install `@actions/github` to add types via JSDoc types.
I could confirmed that params are typed when hovering the param names.
ref: https://github.com/sunadoi/faker/pull/4/commits/9dac32b170dfbab4c7a8481f3fbc86af84ce7919

On the other hand, I noticed that this library is written in ts, so we can write the script in ts file.
In that case, we need transpile before running the github-script.

```
- name: Transpile script ts file
  run: pnpm exec tsc .github/workflows/commentCodeGeneration.ts --outDir .github/workflows
```

It seems to work well.
ref: https://github.com/sunadoi/faker/pull/5/files

Which is better?

2022-10-09 07:20 UTC, Shinigami92 commented on .github/workflows/commentCodeGeneration.js
> + * @param isSuccess A boolean indicating whether the workflow was successful
IMO clearly the TS version is better for us! 👍
For our other scripts we already use `tsx`.

2022-10-09 11:08 UTC, sunadoi commented on .github/workflows/commentCodeGeneration.js
> + * @param isSuccess A boolean indicating whether the workflow was successful
Fixed to TS version!

2022-10-09 12:53 UTC, Shinigami92 approved these changes
Beside that, I think we are good to go :+1: 
So I will already approve so other maintainers know that it counts after you fixed the dep version

2022-10-09 12:53 UTC, Shinigami92 commented on package.json
> +    "@actions/github": "^5.1.1",
Please use `~` instead of `^` as this makes it more robust and long term stable
After that you need to regenerate the lock file

2022-10-09 13:57 UTC, ST-DDT reviewed
Do we have to `.gitginore` the transpiled `.js` script?
- If yes, why is the script not failing?
- If not, why not?

2022-10-09 13:57 UTC, ST-DDT commented on .github/workflows/commentCodeGeneration.ts
> +import { context as ctx, GitHub } from '@actions/github/lib/utils';
```suggestion
import type { context as ctx, GitHub } from '@actions/github/lib/utils';
```

2022-10-09 14:02 UTC, ST-DDT commented
> Do we have to `.gitginore` the transpiled `.js` script?
> 
>     * If yes, why is the script not failing?
> 
>     * If not, why not?

Ah I see, because it is transpiled only after the check.
Please add all `.js` files in the workflows folder to the gitignore anyway, in case somebody transpiles it locally.

2022-10-09 14:25 UTC, sunadoi commented
> (I plan to use your script as a template to automate some more tasks 😻 )

That sounds nice!
I'm so happy to hear that.😘

2022-10-09 15:19 UTC, ST-DDT approved these changes

2022-10-09 20:11 UTC, Shinigami92 approved these changes

2022-10-09 20:11 UTC, merged

2022-10-09 20:19 UTC, ST-DDT commented
@sunadoi It looks like this breaks the main branch.
Could you move the job to a new file e.g. `pr.yml` and run it only for PRs and not main?