feat: lorem null response fix
faker-js/faker pull request #1407
Opened 2022-10-02 19:53 UTC by ST-DDT

Fixes #1131

- Extended and exported the filterWordListByLength to add support for length ranges and fallback strategies
- Use the improved filterWordListByLength function for all `word.*` and `lorem.word` methods

2022-10-02 21:38 UTC, Shinigami92 requested changes

2022-10-02 21:38 UTC, Shinigami92 commented on src/modules/lorem/index.ts
> +        ...(typeof options === 'number' ? { length: options } : options),
Please extract this to its own line

2022-10-02 21:38 UTC, Shinigami92 commented on src/modules/word/filterWordListByLength.ts
> +const strategies = {
This is a _root_-level `const`, so we might want to use UPPER casing

2022-10-02 21:38 UTC, Shinigami92 commented on src/modules/word/filterWordListByLength.ts
> +      data[word.length] = data[word.length] || [];
```suggestion
      data[word.length] ??= [];
```

2022-10-02 21:38 UTC, Shinigami92 commented on src/modules/word/filterWordListByLength.ts
> +    const max = Math.max(...Object.keys(wordsByLength).map(Number));
```suggestion
    const variableName = Object.keys(wordsByLength).map(Number);
    const min = Math.min(...variableName);
    const max = Math.max(...variableName);
```

2022-10-02 21:38 UTC, Shinigami92 commented on src/modules/word/filterWordListByLength.ts
> +      (word) => word.length === Math.min(...wordList.map((word) => word.length))
You shadow the outer `word` variable in the inner `map`, please use different variable names for these two

Also applies for line 40

2022-10-02 22:02 UTC, Shinigami92 requested changes

2022-10-02 22:02 UTC, Shinigami92 commented on src/modules/word/filterWordListByLength.ts
> +      (word) => word.length === Math.min(...wordList.map((w) => w.length))
I think you can extract `Math.min(...wordList.map((w) => w.length)` to its own line, that way it will only iterated once

2022-10-02 22:19 UTC, ST-DDT commented on src/modules/lorem/index.ts
> +    );
I thought about providing this as a standalone function in `faker.helpers`, but I'm not sure how to name it.

````ts
tobedefined(
    worldList: string[],
    options:
      | number
      | {
          length?: number | { min: number; max: number };
          strategy?: 'fail' | 'closest' | 'shortest' | 'longest' | 'any-length';
        } = {}
  ): string
````

`textArrayElement`?

2022-10-02 22:44 UTC, import-brain commented on src/modules/lorem/index.ts
> +   * - `any-length`: Returns a word with any length.
Should we put this below the `@param options.strategy` line?

I think it would make more sense there.

2022-10-03 09:08 UTC, ST-DDT commented
<details>
<summary><strong>Docs-Preview</strong> (Click to expand)</summary>

![grafik](https://user-images.githubusercontent.com/1579362/193540581-78819596-1cf9-4fb4-9d19-e3a17d23c5fd.png)

</details>

2022-10-03 09:24 UTC, Shinigami92 submitted a review, later dismissed

2022-10-03 12:13 UTC, import-brain approved these changes, later dismissed

2022-10-08 14:17 UTC, Shinigami92 commented
Looks like needs a rebase

2022-10-08 14:47 UTC, ST-DDT commented
Updated

2022-10-09 13:03 UTC, Shinigami92 approved these changes

2022-10-09 18:10 UTC, import-brain approved these changes

2022-10-09 19:26 UTC, merged