docs: show next version as special one
faker-js/faker pull request #1438
Opened 2022-10-13 09:31 UTC by ST-DDT

Currently the https://next.fakerjs.dev/ page does not show any hints that it isn't the current version.

![grafik](https://user-images.githubusercontent.com/1579362/195559358-4e93ba0b-445f-4268-b37e-3c90f44a4e24.png)

This PR changes the version number to `Next` and adds a link to the latest released page.

![grafik](https://user-images.githubusercontent.com/1579362/195559640-91a96754-16ca-4aa8-be8f-968d47a5cc05.png)

2022-10-13 09:46 UTC, Shinigami92 commented on docs/.vitepress/versions.ts
> +const isNext = true;
Is it in any way possible that this can be archived dynamically?

2022-10-13 09:56 UTC, ST-DDT commented on docs/.vitepress/versions.ts
> +const isNext = true;
I would like to do something like:

```ts
const hostname = window.location.hostname;
const isNext = hostname === 'next.fakerjs.dev' || hostname === 'localhost';
```

But that isn't possible. Any idea on how to achieve that?

2022-10-13 10:01 UTC, ST-DDT commented on docs/.vitepress/versions.ts
> +const isNext = true;
I added a test that ensures we don't forget it in v8.0.

2022-10-13 10:54 UTC, Shinigami92 commented on docs/.vitepress/versions.ts
> +const isNext = true;
I don't know how overkill this is, but I assume the vitepress config is running in nodejs and not at runtime in browser
So we might use anything we want to, e.g. https://stackoverflow.com/questions/62225567/get-current-git-branch-with-node-js

2022-10-15 13:55 UTC, matthewmayer commented
This seems really subtle unless you really know what to look for. Would it be possible to add something more blatant like a top banner? (rough mockup attached)

<img width="1439" alt="Screenshot 2022-10-15 at 20 52 35" src="https://user-images.githubusercontent.com/152770/195990288-29565ac8-54c9-484a-b8c8-58a41949a272.png">

2022-10-15 17:15 UTC, ST-DDT commented
@matthewmayer Good point. This PR is more about linking the different versions together/making them accessible from our main website, so I created a new issue (#1456) for that to keep track of it.

2022-10-15 18:18 UTC, ST-DDT commented on docs/.vitepress/versions.ts
> +const isNext = true;
Done

2022-10-15 18:39 UTC, Shinigami92 commented on docs/.vitepress/versions.ts
>    { version: 'v6.3.1', link: 'https://v6.fakerjs.dev/' },
Do we already also need to add v7 as we are in v8 now? (I mean in a separate PR)

```suggestion
  isNext ? latestVersion : nextVersion,
  { version: 'v7.6.0', link: 'https://v7.fakerjs.dev/' },
  { version: 'v6.3.1', link: 'https://v6.fakerjs.dev/' },
```

I think this is needed at the time when we switch branches in that way that v7.fakerjs.dev already exists :thinking:

2022-10-15 19:35 UTC, ST-DDT commented on docs/.vitepress/versions.ts
>    { version: 'v6.3.1', link: 'https://v6.fakerjs.dev/' },
This is not possible, because then once we release v8 it will point to v8, 
but the main branch cannot be used with netlify/and it would still point to the same version.
The test ensures that we don't forget to add v7 once v8 is released.

As for automating this, IMO this is not worth it since it only changes very rarely (once every few months).

2022-10-15 20:31 UTC, Shinigami92 commented on docs/.vitepress/versions.ts
>    { version: 'v6.3.1', link: 'https://v6.fakerjs.dev/' },
Partly I see what you mean
But I see an issue if we want to fully automate the release process :thinking: But might be solved by just using the right workflow
We might need to discuss about that in person

2022-10-15 21:53 UTC, ST-DDT commented on docs/.vitepress/versions.ts
>    { version: 'v6.3.1', link: 'https://v6.fakerjs.dev/' },
The release process could add the required changes, since it also decides the version and the tag that the docs will reference.

2022-10-16 08:46 UTC, Shinigami92 commented on docs/.vitepress/versions.ts
>    { version: 'v6.3.1', link: 'https://v6.fakerjs.dev/' },
release-it supports hooks, so yeah we can add scripts how ever we want to :thinking:

2022-10-16 09:01 UTC, ST-DDT commented on docs/.vitepress/versions.ts
>    { version: 'v6.3.1', link: 'https://v6.fakerjs.dev/' },
After a nights worth of thoughts, I think I found an easy way to automate this in every docs build.
Let me check first, whether my idea works in reality as well.

2022-10-16 09:12 UTC, Shinigami92 requested changes

2022-10-16 09:12 UTC, Shinigami92 commented on docs/.vitepress/versions.ts
> +import { execSync } from 'child_process';
I think `child_process` is one of the core node packages
If possible it is now and always recommended to use the node prefix in such cases

```suggestion
import { execSync } from 'node:child_process';
```

2022-10-16 10:19 UTC, ST-DDT commented on docs/.vitepress/versions.ts
>    { version: 'v6.3.1', link: 'https://v6.fakerjs.dev/' },
Done

2022-10-16 10:28 UTC, Shinigami92 commented on docs/.vitepress/versions.ts
> +  let compare = parts1[0].localeCompare(parts2[0]);
The npm package [`semver`](https://www.npmjs.com/package/semver) is a widely used one and when you use `pnpm why semver` you can already see that we have it in our dev-dependencies.
So I think it's okay to explicitly add it to the dev-deps and use it and remove complexity out of our code by doing that.

2022-10-16 10:31 UTC, Shinigami92 commented on docs/.vitepress/versions.ts
> +const NEXT_TEXT = 'Next';
Lets use `next` instead of `Next` because this is the tag of the potential npm package and the branch name and and and ^^

2022-10-16 11:19 UTC, ST-DDT commented on docs/.vitepress/versions.ts
> +  let compare = parts1[0].localeCompare(parts2[0]);
Done

2022-10-16 11:54 UTC, Shinigami92 requested changes

2022-10-16 11:54 UTC, Shinigami92 commented on docs/.vitepress/versions.ts
> +    .filter((tagName) => tagName.startsWith('v'))
I think it's more safe to use `valid` here

```suggestion
    .filter((tag) => semver.valid(tag))
```

2022-10-16 11:54 UTC, Shinigami92 commented on docs/.vitepress/versions.ts
> +  return Object.values(latestReleaseTagNames).sort(semver.rcompare);
I think we can improve it by just grouping all the versions and then use `semver.maxSatisfying`.
This is IMO more understandable in perspective of the code-flow and it might also safe us some nano seconds or performance :stuck_out_tongue_winking_eye: 

```ts
      .reduce<Record<number, string[]>>((acc, tag) => {
        const majorVersion = semver.major(tag);

        if (
          // Only keep track of versions the new Faker Team is responsible for
          majorVersion < 6 ||
          // Ignore current branch as we are already on that branch
          majorVersion === currentMajorVersion
        ) {
          return acc;
        }

        acc[majorVersion] ||= [];
        acc[majorVersion].push(tag);
        return acc;
      }, {});

    const versions = Object.entries(latestReleaseTagNames).map(
      ([major, tags]) => semver.maxSatisfying(tags, `^${major}`)
    );

    return versions;
```

I'm still not quite satisfied with the name `latestReleaseTagNames` :thinking: 
Do you have any better idea?

2022-10-16 11:54 UTC, Shinigami92 commented on test/docs/versions.spec.ts
> +      console.log(oldVersions);
This can be removed, can it?

2022-10-16 22:39 UTC, ST-DDT commented
I created some preview deployments:

- fakerjs.dev: https://634c84829385500009ecdd35--melodious-druid-b57668.netlify.app/ 
  (Please ignore the branchname in the nav bar, this is caused by the way I setup the netlify deployment)
- next.fakerjs.dev: https://634c85fd38583a0009a0502d--melodious-druid-b57668.netlify.app/
- v7.fakerjs.dev: https://634c85871819c70008aea012--melodious-druid-b57668.netlify.app/

2022-10-16 22:46 UTC, ST-DDT commented
Not sure whether `latest` or `next` should be first:
![grafik](https://user-images.githubusercontent.com/1579362/196062011-7604841f-b8b4-489d-b332-b3950f0c1c56.png)

If next is the top one, then it will be in the "correct" version order.

2022-10-17 09:57 UTC, Shinigami92 commented
Looked into the preview deployments and I like them all 👍 
Good job

2022-10-17 10:01 UTC, Shinigami92 reviewed
The code is now MUCH better 👍 
Will approve after rebased

2022-10-17 10:01 UTC, Shinigami92 commented on docs/.vitepress/versions.ts
> +        (acc[majorVersion] = acc[majorVersion] || []).push(tag);
```suggestion
        (acc[majorVersion] ||= []).push(tag);
```

Maybe even `??=` 👀

2022-10-17 10:27 UTC, ST-DDT commented on docs/.vitepress/versions.ts
> +        (acc[majorVersion] = acc[majorVersion] || []).push(tag);
It isn't supported. You told me the same just a few weeks ago.
https://github.com/faker-js/faker/pull/1407#discussion_r985299537
[`09d11f8` (#1407)](https://github.com/faker-js/faker/pull/1407/commits/09d11f8e169b0bf16f0c0105dfc800325afff84f#diff-43806c9d91df883f547b50d72ffc58f389e58df082afa98825ba79217e7bf3ccR17)

2022-10-17 10:29 UTC, ST-DDT commented on docs/.vitepress/versions.ts
> +        (acc[majorVersion] = acc[majorVersion] || []).push(tag);
I can use `??` though.

```suggestion
        (acc[majorVersion] = acc[majorVersion] ?? []).push(tag);
```

2022-10-17 10:42 UTC, Shinigami92 commented on docs/.vitepress/versions.ts
> +        (acc[majorVersion] = acc[majorVersion] || []).push(tag);
> It isn't supported. You told me the same just a few weeks ago. [#1407 (comment)](https://github.com/faker-js/faker/pull/1407#discussion_r985299537) [`09d11f8` (#1407)](https://github.com/faker-js/faker/pull/1407/commits/09d11f8e169b0bf16f0c0105dfc800325afff84f#diff-43806c9d91df883f547b50d72ffc58f389e58df082afa98825ba79217e7bf3ccR17)

The small difference here is, that it is s script on our side and doesn't need to be bundled by esbuild for the end-user

2022-10-17 11:51 UTC, Shinigami92 submitted a review, later dismissed

2022-10-17 12:51 UTC, Shinigami92 approved these changes, later dismissed

2022-10-17 12:52 UTC, ST-DDT commented on docs/.vitepress/versions.ts
> +        (acc[majorVersion] = acc[majorVersion] || []).push(tag);
Netlify seems to support it.

2022-10-17 12:57 UTC, ST-DDT commented
It doesn't pass our CI, so I reverted it.

2022-10-17 12:57 UTC, Shinigami92 commented
🤣 no f*cking way, out TESTS are blocking it 🤣 
Oh my good, okay, no new syntax for us I guess 😭 That's brutal 😖

2022-10-17 12:58 UTC, Shinigami92 approved these changes

2022-10-17 18:55 UTC, ST-DDT commented
Well, we could omit the tests... 🤣

2022-10-17 18:56 UTC, Shinigami92 commented
> Well, we could omit the tests... rofl

Na, lets just upgrade when we move to `^Node16`

2022-10-22 04:00 UTC, import-brain approved these changes

2022-10-23 08:36 UTC, merged