refactor!: cleanup deprecations
faker-js/faker pull request #1440
Opened 2022-10-13 16:44 UTC by Shinigami92

closes #1439

2022-10-13 22:16 UTC, ST-DDT requested changes

2022-10-13 22:16 UTC, ST-DDT commented on src/index.ts
>  export type { MersenneModule } from './modules/mersenne';
This shouldn't be exported anymore as it is internal.

2022-10-13 22:16 UTC, ST-DDT commented on test/address.spec.ts
> +      t.it('noArgs').it('with given index', 1);
`city(index)` is deprecated and should be removed (also from src).

2022-10-13 22:16 UTC, ST-DDT commented on test/company.spec.ts
>        t.it('noArgs').it('with index');
`company(index)` is deprecated and should be removed also from `src`.

2022-10-13 22:16 UTC, ST-DDT commented on test/phone.spec.ts
> +    t.itEach('imei');
Maybe just `t.it()`?

2022-10-13 22:16 UTC, ST-DDT commented on test/phone.spec.ts
> +    t.describeEach('number')((t) => {
Maybe just `t.describe()`?

2022-10-14 13:17 UTC, ST-DDT requested changes

2022-10-14 13:17 UTC, ST-DDT commented on src/modules/address/index.ts
> +    const format = this.faker.datatype.number(formats.length - 1);
Please use `helpers.arrayElement` instead.

2022-10-14 13:17 UTC, ST-DDT commented on src/modules/company/index.ts
> +    const format = this.faker.datatype.number(formats.length - 1);
Please use `helpers.arrayElement` instead.

2022-10-14 13:26 UTC, Shinigami92 commented on src/modules/address/index.ts
> +    const format = this.faker.datatype.number(formats.length - 1);
nice :slightly_smiling_face:

2022-10-14 13:26 UTC, Shinigami92 commented on src/modules/company/index.ts
> +    const format = this.faker.datatype.number(formats.length - 1);
nice :slightly_smiling_face:

2022-10-14 14:16 UTC, ST-DDT approved these changes, later dismissed

2022-10-14 17:45 UTC, xDivisionByZerox commented
How do we handle this as it is marked for removal in v8.0?
https://github.com/faker-js/faker/blob/2914a69f7da9552fd0a58c57d2961e4136dfa7b2/src/modules/address/index.ts#L137-L152

2022-10-14 17:47 UTC, xDivisionByZerox commented
You missed this on:
https://github.com/faker-js/faker/blob/2914a69f7da9552fd0a58c57d2961e4136dfa7b2/src/modules/datatype/index.ts#L220-L235

2022-10-14 17:49 UTC, xDivisionByZerox requested changes
You missed this on:
https://github.com/faker-js/faker/blob/2914a69f7da9552fd0a58c57d2961e4136dfa7b2/src/modules/datatype/index.ts#L220-L235

2022-10-14 17:57 UTC, import-brain submitted a review, later dismissed

2022-10-14 17:57 UTC, import-brain commented
> You missed this on:
> 
> https://github.com/faker-js/faker/blob/2914a69f7da9552fd0a58c57d2961e4136dfa7b2/src/modules/datatype/index.ts#L220-L235

Good catch.

2022-10-14 18:32 UTC, Shinigami92 commented
@xDivisionByZerox nice catch!
I also found streetName :+1:

2022-10-14 18:33 UTC, xDivisionByZerox approved these changes

2022-10-14 19:29 UTC, ST-DDT approved these changes

2022-10-14 19:29 UTC, merged