refactor(person)!: rename name module
faker-js/faker pull request #1445
Opened 2022-10-14 08:01 UTC by Shinigami92

closes #1343

2022-10-14 08:01 UTC, Shinigami92 commented
Blocked by:
- #1440

2022-10-14 10:22 UTC, Shinigami92 commented
@ST-DDT I'm not sure if we want to support `faker.helpers.fake('{{name.firstName}} or {{name.first_name}}')`
It might be really hard for us to maintain that in the long run
We also would need to write extra code to support that but in a way so we don't duplicate the name definitions
So you have any ideas? Or should we just make a hard breaking change?

2022-10-14 10:39 UTC, Shinigami92 commented
Okay, this is now in a _done_ / _ready for review_ state, but I want to first merge the cleanup deprecations as of that will reduce some changes.
So until then, this PR will stay in _draft_.

2022-10-14 13:05 UTC, ST-DDT requested changes

2022-10-14 13:05 UTC, ST-DDT commented on src/faker.ts
> +  readonly name: NameModule = this.person;
Use a getter with a call to deprecated helper method here.

2022-10-14 13:05 UTC, ST-DDT commented on src/locales/de/person/name.ts
> +  '{{female_first_name}} {{last_name}}',
This file got corrupted: `person.` is missing.
Did you convert these files by hand?

2022-10-14 13:14 UTC, Shinigami92 commented on src/faker.ts
> +  readonly name: NameModule = this.person;
You are right :+1:

2022-10-14 13:14 UTC, Shinigami92 commented on src/locales/de/person/name.ts
> +  '{{female_first_name}} {{last_name}}',
Nice catch, thx :+1:

2022-10-14 14:11 UTC, ST-DDT submitted a review, later dismissed

2022-10-14 23:19 UTC, ST-DDT commented
I don't know why this works, but it works.

2022-10-14 23:46 UTC, ST-DDT commented on test/helpers.spec.ts
> +            faker.helpers.fake('{{person.first_name}}')
```suggestion
            faker.helpers.fake('{{name.first_name}}')
```

2022-10-14 23:46 UTC, ST-DDT commented on test/helpers.spec.ts
> +            faker.helpers.fake('{{person.firstName}}')
```suggestion
            faker.helpers.fake('{{name.firstName}}')
```

2022-10-15 00:33 UTC, ST-DDT submitted a review, later dismissed

2022-10-15 17:35 UTC, matthewmayer commented
in addition to the new faker.person tests, why not keep the existing tests for the faker.name module ?
```
test/__snapshots__/name.spec.ts.snap
test/name.spec.ts
```

That will help ensure no unexpected regressions/breaking changes.

2022-10-15 18:32 UTC, Shinigami92 commented
> in addition to the new faker.person tests, why not keep the existing tests for the faker.name module ?
> 
> ```
> test/__snapshots__/name.spec.ts.snap
> test/name.spec.ts
> ```
> 
> That will help ensure no unexpected regressions/breaking changes.

Because it is just an alias, behind it there is exactly the same code, so no need to test it twice.

2022-10-16 14:54 UTC, xDivisionByZerox commented
I'm a bit lost, shouldn't this follow our normal [deprecation workflow](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md#deprecation-workflow)? As now a user has no time-window to migrate, but have to rework their codebase. Is this desired even if this will be in a breaking change?

2022-10-16 14:59 UTC, xDivisionByZerox commented on scripts/apidoc/moduleMethods.ts
> +  return (module.escapedName || module.name).replace(/Module$/, '');
This change doesn't seem related to this PR. If so, how?

2022-10-16 15:03 UTC, xDivisionByZerox commented
> I'm a bit lost, shouldn't this follow our normal [deprecation workflow](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md#deprecation-workflow)? As now a user has no time-window to migrate, but have to rework their codebase. Is this desired even if this will be in a breaking change?

Sorry, too many files. Didn't saw the getter in the Faker class. So if this follows the typical deprecation workflow, we need to keep the tests as @matthewmayer suggested. Even is if is just an alias, how do you confirm that it is that way? The test would also catch breaking changes in the `NameModule` which were designed to only affect the `PersonModule`.

2022-10-16 15:28 UTC, xDivisionByZerox commented on src/index.ts
> +  PersonDefinitions as NameDefinitions,
Exporting it like this means that any change in `PersonDefinition` directly influences the old `NameDefinition` type. This means that no changes to this type can be made in the the entirety of v8 (?).

If we for example add `JobDefinitions` to `PersonDefinitions` I could do the following:

```ts
interface PersonDefinitions {
  // current declaration
  jobNames: string[];
}

const personDefs: NameDefinitions = {
  // [...]
  jobNames: [...],
}
```

Is this desired?

2022-10-16 15:42 UTC, xDivisionByZerox commented on src/locales/ar/name/name.ts
> -export default [
Did you deleted this file by accident instead of renaming it?

2022-10-16 15:43 UTC, xDivisionByZerox commented on src/locales/ar/name/name.ts
> -export default [
Ah ok I see. Git cant track that this is the same as `src/locales/ar/person/name.ts` and only being renamed.

2022-10-16 15:55 UTC, Shinigami92 commented on src/index.ts
> +  PersonDefinitions as NameDefinitions,
> Is this desired?

Yes

2022-10-16 16:02 UTC, ST-DDT commented on scripts/apidoc/moduleMethods.ts
> +  return (module.escapedName || module.name).replace(/Module$/, '');
The `name` attribute is derived/calculated by typedoc.
IMO it is a bug from typedoc, that it uses the alias as the main name (because it is exported first).
If we disable our formatter/linter and swap the order of our imports/exports, then typedoc picks the correct name.
To avoid that issue we use the name that typescript assigns to that type (`escapedName`).
(I don't know why it is called `escapedName` though.)
The `escapedName` can be null (says typescript), but it never is, so basically we always use the `escapedName` instead of `name`. The code is effectively like this:

````ts
return module.escapedName.replace(/Module$/, '');
````

This change is required for the docs to work/generate the correct api docs.

2022-10-16 16:16 UTC, ST-DDT commented on src/index.ts
> +  PersonDefinitions as NameDefinitions,
> Exporting it like this means that any change in PersonDefinition directly influences the old NameDefinition type. 

Yes, we renamed the `NameModule` to `PersonModule`.
`faker.name` returns the `PersonModule`. There is no longer a `NameModule`.

> This means that no changes to this type can be made in the the entirety of v8 (?).

This is not true, because like in any other module non breaking changes can be made to it.
We cannot do breaking changes after v8.0 is released till v9.0, but that would still be the case if we didn't rename the module.

> If we for example add JobDefinitions to PersonDefinitions I could do the following:

That is true, but if you try to add it then ts wouldn't suggest the name module anymore.
You can still add it, like you can add any other information, but faker won't use them.
If you try to access it with faker you will get a notice that you should use `faker.definitions.person` instead.

2022-10-16 16:21 UTC, xDivisionByZerox commented on src/index.ts
> +  PersonDefinitions as NameDefinitions,
Ok, gotcha. Thank you for clearification.

2022-10-16 16:26 UTC, xDivisionByZerox commented on scripts/apidoc/moduleMethods.ts
> +  return (module.escapedName || module.name).replace(/Module$/, '');
I still don't see how this is related (and only now required) to renaming the `NameModule` to `PersonModule`. 
So, if the renaming would be reverted this line (`return module.name.replace(/Module$/, '');`) would break?

2022-10-16 16:30 UTC, ST-DDT commented
> So if this follows the typical deprecation workflow, we need to keep the tests as @matthewmayer suggested. Even is if is just an alias, how do you confirm that it is that way? The test would also catch breaking changes in the `NameModule` which were designed to only affect the `PersonModule`.

I'm not sure whether I get you right.
If we duplicate the tests for `faker.name`, then this would only prevent breaking changes if we freeze the name tests until after v8.0.0.
However, the same applies to the PersonModule.
If we treat it like an existing module and only change things after a deprecation phase, then there is no need for the extra tests.

2022-10-16 16:44 UTC, xDivisionByZerox commented on scripts/apidoc/moduleMethods.ts
> +  return (module.escapedName || module.name).replace(/Module$/, '');
I also had a deeper look into that. `escapedName` is marked as `@internal`, should really use it then?

2022-10-16 17:14 UTC, ST-DDT commented on scripts/apidoc/moduleMethods.ts
> +  return (module.escapedName || module.name).replace(/Module$/, '');
> I still don't see how this is related (and only now required) to renaming the `NameModule` to `PersonModule`.

This is required because typedoc doesn't assign the correct name.
The change is only relevant because we created an alias for the first time.
I don't consider this permanent code, maybe we can add a comment stating we should remove it later on.

> So, if the renaming would be reverted this line (return module.name.replace(/Module$/, '');return (module.escapedName || module.name).replace(/Module$/, '');) would break?

No, it doesn't. If you flip the imports/exports, then also name would show the correct value.

> I also had a deeper look into that. escapedName is marked as @internal, should really use it then?

Yes, the field is internal, but I couldn't find another way to achieve the same result.
(Aside from droping typedoc and using the typescript AST directly)
If you have an idea for a different fix, please tell me.
When I have some time, I will write a minimal reproduction and report this issue to typedoc.

We could write a test, to ensure that `faker.name` doesn't show up and `faker.person` does.

I don't think reversing the import/export order (and disabling the formatter/linter for that) is an acceptable alternative.

2022-10-16 17:38 UTC, ST-DDT commented on scripts/apidoc/moduleMethods.ts
> +  return (module.escapedName || module.name).replace(/Module$/, '');
Should we write instead:

````suggestion
const { name } = module;
if (name === 'NameModule') {
    return 'Person';
} else {
    return name.replace(/Module$/, '');
}
````

(not tested)

2022-10-16 17:45 UTC, Shinigami92 commented on scripts/apidoc/moduleMethods.ts
> +  return (module.escapedName || module.name).replace(/Module$/, '');
This would be a potential solution, but looking forward to address->location rename we would need it for every alias
Your actual solution works and handle all the cases dynamically

2022-10-16 17:45 UTC, xDivisionByZerox commented on scripts/apidoc/moduleMethods.ts
> +  return (module.escapedName || module.name).replace(/Module$/, '');
> Should we write instead:
> 
> ```ts
> const { name } = module;
> if (name === 'NameModule') {
>     return 'Person';
> } else {
>     return name.replace(/Module$/, '');
> }
> ```

The is makes in much easer for me to understand whats happening here.

2022-10-16 18:06 UTC, ST-DDT commented on scripts/apidoc/moduleMethods.ts
> +  return (module.escapedName || module.name).replace(/Module$/, '');
> This would be a potential solution, but looking forward to address->location rename we would need it for every alias Your actual solution works and handle all the cases dynamically

Sure, but we have it for the definitions proxy already.
See also my (future) comment below.

2022-10-16 18:07 UTC, ST-DDT commented
TODO: Create an issue to remove the special handling in v10.0 after this is merged (to get the final line numbers and commit references).

2022-10-16 18:08 UTC, ST-DDT approved these changes

2022-10-16 18:12 UTC, xDivisionByZerox commented on test/helpers.spec.ts
> +          );
The seems to be duplicated.

2022-10-16 18:13 UTC, xDivisionByZerox commented on test/helpers.spec.ts
> +          );
ok... `name.first_name` !== `name.firstName`. 600 files are to much for keep your head working ^^

2022-10-16 18:15 UTC, Shinigami92 commented on test/helpers.spec.ts
> +          );
first_name vs firstName

2022-10-16 18:15 UTC, xDivisionByZerox approved these changes

2022-10-16 20:00 UTC, import-brain approved these changes
LGTM :)

2022-10-16 20:05 UTC, merged