feat: fake from array
faker-js/faker pull request #1453
Opened 2022-10-15 00:25 UTC by ST-DDT

Fixes #1446 

<details>
<summary>Docs Preview</summary>

![grafik](https://user-images.githubusercontent.com/1579362/195960545-65708794-053e-444f-8544-8ea734299ef5.png)

</details>

2022-10-15 06:26 UTC, pkuczynski submitted a review, later dismissed

2022-10-15 11:33 UTC, Shinigami92 requested changes

2022-10-15 11:33 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * @param str The template string that will get interpolated. Must not be empty. If an array is passed, a random element will be picked and interpolated.
I know this will duplicate the whole JSDoc, but can we split the signatures to two overloads?
In that case we can name it str for the first signature and arr for the second.
Also the descriptions can differ.
The arr / second-sig can also have another `@since`

2022-10-15 11:33 UTC, Shinigami92 commented on test/helpers.spec.ts
> +        it('should be able to pass multiple static templates', () => {
In line 525 we have a test for calling fake with no arguments (not possible with ts, but anyway)
I would like to have added a test for what happens when it gets called with an empty string, and one for with empty array.
If we already have these two somewhere, let me know the lines.

2022-10-15 20:33 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * @param str The template string that will get interpolated. Must not be empty. If an array is passed, a random element will be picked and interpolated.
The jsdocs will be tripled (`string`, `string[]`, `string | string[]`). 
What would you write differently for the other signature?

2022-10-15 21:57 UTC, ST-DDT commented on test/helpers.spec.ts
> +        it('should be able to pass multiple static templates', () => {
Added

2022-10-15 21:58 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * @param str The template string that will get interpolated. Must not be empty. If an array is passed, a random element will be picked and interpolated.
Is `template` a better name for the parameter?

2022-10-16 09:02 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * @param str The template string that will get interpolated. Must not be empty. If an array is passed, a random element will be picked and interpolated.
So I want to write two things:

1. For me it's the same as with `faker.seed`
   https://github.com/faker-js/faker/blob/0f9b0c64e556349cd02d54cb78a780373b2ddb97/src/faker.ts#L175-L241
   So the upper two _specific_ signatures are the ones that gets shown when you use an IDE e.g. VSCode.
   The signature that bundles the upper signatures into one (because that's the real JS one) has it's JSDoc only used by TSDoc as far as I remember :thinking: If this is wrong or can be improved to not be needed, please let me know and we might be able to clean some JSDocs out of the project.

2. Now as we have nowadays IDE hints, a user would e.g. see
   ```ts
   const result = faker.helpers.fake(str: ['{{person.firstName}}', '{{person.lastName}}'])
   //                                _____
   ```
   where `str: ` is just provided in grey color by the IDE. But that name might be confusing as it is not a string at all but an array.

---

I immediately also thought about to name it `template`, but reading
https://github.com/faker-js/faker/blob/9a38c37968110b284b25752d8cd3fd4c0a2c6ef6/src/modules/helpers/index.ts#L497
might be weird to have `template`, `element` and `str` here and there, and in some contexts it is named `pattern` :thinking: 
We might decide for one name,
But nevertheless it is a single value or an array, the parameter name would likely end with an `s` if it receives an array.

2022-10-16 11:39 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * @param str The template string that will get interpolated. Must not be empty. If an array is passed, a random element will be picked and interpolated.
Lets discuss the parameter name in the next team meeting.

As for the duplicate jsdocs. I don't see added value here.

2022-10-16 12:16 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * @param str The template string that will get interpolated. Must not be empty. If an array is passed, a random element will be picked and interpolated.
> As for the duplicate jsdocs. I don't see added value here.

You as user or you as maintainer?

IMO the maintenance burden on our side to copy&paste a JSDoc block and slightly alter it is comparable be far to having a better UX/DX for 1.3 million (weekly downloads) individuals.
But if you like, we can discuss this in team as well, as you already also want to wait until meeting based on the param rename.

2022-10-22 10:32 UTC, Shinigami92 requested changes

2022-10-22 10:32 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +  /**
Looks like there was a merge conflict not solved successfully 🤔

2022-10-22 12:24 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * @param str The template string that will get interpolated. Must not be empty. If an array is passed, a random element will be picked and interpolated.
Fixed

2022-10-22 13:19 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * It is also NOT possible to use any non-faker methods or plain javascript in such patterns.
It feels like this should be slightly rewritten to reflect more the usage specifically for passing the patterns array.

2022-10-22 13:19 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +  fake(pattern: string | string[]): string {
I might remember wrongly, but do we really need this doubled signature?
I thought we just need the specific ones and the last generic signature that bundles the specific ones into JS are just for JS and the VitePress generated docs.

2022-10-22 13:19 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +      throw new FakerError('string/string[] parameter is required!');
```suggestion
      throw new FakerError('string or array of strings is required as parameter');
```

Maybe that's more readable :thinking: 
Do we want the exclamation mark at the end? Not sure about that

---

Beside that, why do we check the input here? Is it special or can we remove it and depend on TypeScript?

2022-10-22 13:44 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  fake(pattern: string | string[]): string {
Yes, we do. Because typedoc (we) use the last api signature to generate our api docs. The implementation signature isn't taking into account.

2022-10-22 22:25 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      throw new FakerError('string/string[] parameter is required!');
1) I adjusted it to be closer to other error message.
2) I removed it. I assume this is part of the legacy code.

2022-10-22 22:25 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * It is also NOT possible to use any non-faker methods or plain javascript in such patterns.
Fixed. If want to change it some more you have to be specific.

2022-10-24 14:15 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * const hello = faker.helpers.fake('Hi, my name is {{person.firstName}} {{person.lastName}}!');
Lets use an array example here as well

2022-10-24 14:15 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * const message = faker.helpers.fake('Your pin is {{string.numeric(4, {"allowLeadingZeros": true})}}.');
And here

2022-10-30 23:32 UTC, xDivisionByZerox approved these changes, later dismissed
TBH, I don't see the requirement of this change, as it adds a lot of "unnecessary" complexity ontop of an already complex function.
But I don't see anything wrong with the implementation itself.

2022-10-31 10:01 UTC, ST-DDT commented
@xDivisionByZerox Would you prefer a separate method? Any suggestions for a name? `fakeOneOf`?

2022-10-31 10:57 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * and if that isn't possible, we will fall back to string:
```suggestion
   * and if that isn't possible, it will fall back to string:
```

2022-10-31 10:57 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * and if that isn't possible, we will fall back to string:
```suggestion
   * and if that isn't possible, it will fall back to string:
```

2022-10-31 11:23 UTC, xDivisionByZerox commented
> @xDivisionByZerox Would you prefer a separate method? Any suggestions for a name? `fakeOneOf`?

A separate method would definitely satisfy the single responsibility principle. But I guess that would negate the overall code improvement you had in mind with this changes? As now every function is required to first check the type and then call the according function:
```ts
function foo(options: string | string[]) {
  return Array.isArray(options) ? this.faker.helpers.fakeOneOf(options) : this faker.helpers.fake(options);
}
```

2022-10-31 13:12 UTC, Shinigami92 approved these changes

2022-12-22 21:11 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +      pattern = this.arrayElement(pattern);
Filter empty strings.

```suggestion
      pattern = this.arrayElement(pattern.filter((str) => str));
```

2022-12-23 11:42 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      pattern = this.arrayElement(pattern);
See https://github.com/faker-js/faker/issues/1457
The empty string will be allowed in the future.

2022-12-23 16:25 UTC, xDivisionByZerox approved these changes

2022-12-23 16:28 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +      pattern = this.arrayElement(pattern);
Makes sense, good work 👍

2022-12-23 17:54 UTC, import-brain approved these changes

2022-12-23 19:42 UTC, merged