infra: setup release-it
faker-js/faker pull request #1455
Opened 2022-10-15 17:10 UTC by Shinigami92

closes #1096

2022-10-15 18:14 UTC, Shinigami92 commented
No matter what I do when testing, no `CHANGELOG.md` is generated :thinking: 
Also it doesn't bump the version automatically to e.g. `v8.0.0`
I assume I do something really wrong, but the documentation or verbose logs are also not very helpful 😟

@webpro Would you be so kind and guide us a bit? :slightly_smiling_face:

2022-10-16 10:44 UTC, webpro commented
The `preset` is missing in the plugin config:

```json
"plugins": {
  "@release-it/conventional-changelog": {
    "infile": "CHANGELOG.md",
    "preset": {
      "name": "conventionalcommits",
      "types": [...]
    }
  }
}
```

The issue you were facing is that, without a preset, `conventional-recommended-bump` did not return a recommended bump, in turn making release-it skip the release part (which includes everything you are missing).

However, release-it could certainly help out a little here, e.g. the plugin could throw an exception, but at the very least release-it itself should show an error or warning, so I'll add that.

2022-10-16 11:59 UTC, Shinigami92 commented
> The `preset` is missing in the plugin config:
> 
> ```json
> "plugins": {
>   "@release-it/conventional-changelog": {
>     "infile": "CHANGELOG.md",
>     "preset": {
>       "name": "conventionalcommits",
>       "types": [...]
>     }
>   }
> }
> ```

Oh my god :facepalm: 
Thank you very much, I was so blind
I put `"types" : [...]` next to `"infile"` and didn't wrapped it into `"preset": { "types": [...] }`

2022-10-16 12:09 UTC, Shinigami92 commented
<img src="https://user-images.githubusercontent.com/7195563/196034620-891c5dc0-bae0-4abd-8acb-de5b9f228c65.png" width="400px"/> <img src="https://user-images.githubusercontent.com/7195563/196034660-8bb451dd-ec16-4366-b98f-e3722ef028aa.png" width="400px"/>

:heart_eyes:

2022-10-18 16:07 UTC, Shinigami92 commented
I made a **real-world** test release via https://github.com/Shinigami92/pug-fmt !
For complete automation, we need to setup a auto-workflow that access GH_TOKEN or if we want to release manually, a maintainer needs the right to push to default branch directly

2022-10-22 10:11 UTC, Shinigami92 commented
Please feel free to review the PR, but let's not merge it now

2022-10-22 22:36 UTC, ST-DDT requested changes
IMO the changelog file should be kept, but empty except for a link to the previous version.
Otherwise the v8.0.0 won't have it.

2022-10-22 22:36 UTC, ST-DDT commented on .release-it.json
> +          }
Does this section needs to be extended to meet our requirements?

2022-10-23 09:11 UTC, Shinigami92 commented on .release-it.json
> +          }
Yes, will be done in
- #1304

2022-10-23 09:12 UTC, Shinigami92 commented
> IMO the changelog file should be kept, but empty except for a link to the previous version. Otherwise the v8.0.0 won't have it.

The linkage must somehow be done post-firsttime generation, so it doesn't mess with the release-it generator

2022-10-23 12:38 UTC, ST-DDT commented
> > IMO the changelog file should be kept, but empty except for a link to the previous version. Otherwise the v8.0.0 won't have it.
> 
> The linkage must somehow be done post-firsttime generation, so it doesn't mess with the release-it generator

Lets check whether this breaks the generation first. Somehow, I believe we will forget about that once we actually do the release.
(Also I assume that the release is then already created and we cannot magically add the file afterwards so its in the release.)

2023-01-27 16:42 UTC, Shinigami92 commented
I've lost the strength to continue working on this PR
It's open to be claimed by any other contributor

2023-01-28 13:10 UTC, xDivisionByZerox commented
I'll continue working on this.

2023-04-13 17:22 UTC, ST-DDT commented
**Team Decision**

We don't need this for v8.0.
(We will likely immediately start with v9 after v8.0)

2023-09-17 07:29 UTC, Shinigami92 commented
Right now this PR gets stale and would need anyway a rebase and so on
As well as I'm currently not willing anymore to spend anymore time from my side into this, I will close this PR for now

2023-09-17 07:29 UTC, closed without merging