feat: fake with multiple parameters
faker-js/faker pull request #1459
Opened 2022-10-15 21:50 UTC by ST-DDT

Adds support for method calls with multiple parameters in `fake()`

Example:

````ts
faker.helpers.fake('I rolled the dice and got: {{random.numeric(5, {"bannedDigits": "12345678"})}}')
````

Result:

`I rolled the dice and got: 6`

<details>
<summary>Docs Preview</summary>

![grafik](https://user-images.githubusercontent.com/1579362/196008350-aa1f566b-6154-4631-88d1-1d9c2114ac53.png)

</details>

2022-10-15 21:51 UTC, ST-DDT commented
Blocked by #1458

2022-10-16 09:16 UTC, Shinigami92 requested changes

2022-10-16 09:16 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * faker.helpers.fake('I rolled the dice and got: {{random.numeric(5, {"bannedDigits": "12345678"})}}') // 'I rolled the dice and got: 6'
You rolled a 6 but was banned and it was banned and it was not of length 5?
You are a really lucky guy :stuck_out_tongue_winking_eye:

2022-10-16 10:32 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.fake('I rolled the dice and got: {{random.numeric(5, {"bannedDigits": "12345678"})}}') // 'I rolled the dice and got: 6'
Fixed

2022-10-16 12:19 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +        params = [];
Codecov warns about this line is not covered :thinking:

2022-10-16 19:00 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +        params = [];
Fixed

2022-10-16 19:02 UTC, Shinigami92 approved these changes, later dismissed

2022-10-16 19:07 UTC, Shinigami92 submitted a review, later dismissed

2022-10-16 19:07 UTC, Shinigami92 commented on test/helpers.spec.ts
> +        it.only('replaces a token with a random value for a method with an object parameter', () => {
```suggestion
        it('replaces a token with a random value for a method with an object parameter', () => {
```

2022-10-22 04:03 UTC, import-brain reviewed
Please replace all instances of `random.numeric` with `string.numeric` to fix tests

2022-10-22 13:21 UTC, Shinigami92 approved these changes

2022-10-22 15:30 UTC, import-brain approved these changes

2022-10-23 18:32 UTC, merged