refactor(location)!: rename address module
faker-js/faker pull request #1469
Opened 2022-10-18 18:12 UTC by Shinigami92

closes #1344

2022-10-18 20:33 UTC, Shinigami92 commented
In https://github.com/faker-js/faker/pull/1469/commits/e7961b01c5d80e69800c9a4d2640a5db624e91eb I didn't touched the address tests, so everything was green
Will now rename them

2022-10-18 23:50 UTC, ST-DDT requested changes
Please delete this file: 
- https://github.com/faker-js/faker/blob/1344-rename-address-module-to-location/test/__snapshots__/address.spec.ts.snap

And update the following files:
- https://github.com/faker-js/faker/blob/e0b506f5164688841b790521c4ed748ab7008d67/CONTRIBUTING.md?plain=1#L440
- https://github.com/faker-js/faker/blob/1344-rename-address-module-to-location/README.md?plain=1#L24
- https://github.com/faker-js/faker/blob/1344-rename-address-module-to-location/docs/index.md?plain=1#L27
- https://github.com/faker-js/faker/blob/1344-rename-address-module-to-location/src/modules/helpers/index.ts#L473
- https://github.com/faker-js/faker/blob/e0b506f5164688841b790521c4ed748ab7008d67/test/faker.spec.ts#L97
- https://github.com/faker-js/faker/blob/1344-rename-address-module-to-location/test/helpers.spec.ts#L534 +other lines

2022-10-19 13:00 UTC, Shinigami92 commented
@ST-DDT Nice catches, thx 🙂

2022-10-19 18:08 UTC, ST-DDT submitted a review, later dismissed

2022-10-20 03:42 UTC, import-brain submitted a review, later dismissed

2022-10-20 16:18 UTC, xDivisionByZerox submitted a review, later dismissed

2022-10-20 16:29 UTC, xDivisionByZerox commented
Should we update this as well?
https://github.com/faker-js/faker/blob/79858fea203bce7ada9e9bcc7751f6ab25123977/CONTRIBUTING.md?plain=1#L440

2022-10-21 11:14 UTC, xDivisionByZerox approved these changes

2022-10-21 11:28 UTC, ST-DDT approved these changes

2022-10-21 11:28 UTC, merged