refactor(image)!: rewrite module
faker-js/faker pull request #1477
Opened 2022-10-22 13:54 UTC by Shinigami92

closes #1350

2022-10-22 17:22 UTC, Shinigami92 commented on src/modules/image/index.ts
> +    }
We can also use e.g. `LoremflickrUrlOptions | PicsumUrlOptions` and also reuse them above in `urls`.
But then the web-docs would currently not generated nicely.
It's maybe a bit sad that we need to write such "complex" option types into signatures and cannot extract them into own types and make the code more readable that way. But hopefully there is a solution for this I don't know of.

2022-10-22 17:23 UTC, Shinigami92 commented on src/modules/image/index.ts
> +    const rawPrefix = 'data:image/svg+xml;charset=UTF-8,';
We want to add base64 dataUris

2022-10-22 17:23 UTC, Shinigami92 commented on src/modules/image/index.ts
> +  github: ({ seed }) => `https://avatars.githubusercontent.com/u/${seed}`,
Maybe we need a modulo operation here as well

2022-10-22 17:50 UTC, Shinigami92 commented on src/modules/image/index.ts
> +  github: ({ seed }) => `https://avatars.githubusercontent.com/u/${seed}`,
We can try `(seed % 100_000_000) + 1`
I think this is high enough for a range

2022-10-22 19:49 UTC, ST-DDT commented on src/modules/image/index.ts
> +  github: ({ seed }) => `https://avatars.githubusercontent.com/u/${seed}`,
IMO seed is an implementation detail and should not be settable.

2022-10-22 19:53 UTC, Shinigami92 commented on src/modules/image/index.ts
> +  github: ({ seed }) => `https://avatars.githubusercontent.com/u/${seed}`,
This code it fully internal and not accessible from outside!

2022-10-22 20:48 UTC, ST-DDT commented on src/modules/image/index.ts
> +  github: ({ seed }) => `https://avatars.githubusercontent.com/u/${seed}`,
I know, but you now pass the seed to the method without knowing what the method does with it, that's why you could just pass the faker instance there and generate correct values.

2022-10-28 17:44 UTC, Shinigami92 commented on src/modules/image/index.ts
> +  github: ({ seed }) => `https://avatars.githubusercontent.com/u/${seed}`,
Please resolve if requirements are fulfilled

2022-10-28 21:08 UTC, ST-DDT approved these changes, later dismissed

2022-11-04 16:59 UTC, ST-DDT commented
IMO we should have provider independent methods signatures in `faker.image` that are easy to replace the implementation with a specific provider.
The provider specific implementations will then be in `faker.image.<provider>`.

2022-11-11 13:25 UTC, Shinigami92 commented
@ST-DDT I rewrote `src/modules/image/index.ts` to the new proposal. Please have a look if the implementation satisfies your requirements.
I will start now with rewriting the JSDocs and tests.

2022-11-11 13:36 UTC, ST-DDT commented on src/modules/image/index.ts
> +  }
https://github.com/faker-js/faker/issues/465

2022-11-11 14:22 UTC, Shinigami92 commented on src/modules/image/index.ts
> +    const rawPrefix = 'data:image/svg+xml;charset=UTF-8,';
Extracted to https://github.com/faker-js/faker/issues/1550

2022-11-11 15:34 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image` instead.
```suggestion
   * @deprecated Use `faker.image.urlPlaceholder` instead.
```

2022-11-11 15:34 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image` instead.
```suggestion
   * @deprecated Use `faker.image.urlPicsum` instead.
```

2022-11-11 15:34 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   *
Add more complex examples

2022-11-11 15:34 UTC, Shinigami92 commented on test/image.spec.ts
> +
Missing `url*` tests

2022-11-11 16:46 UTC, ST-DDT commented on test/image.spec.ts
> +  describe('avatarGitHub', () => {
The name is wrong here.

2022-11-11 16:46 UTC, ST-DDT commented on src/modules/image/index.ts
>    urlPicsum(
Maybe call it `urlPicsumPhotos`?

2022-11-11 16:46 UTC, ST-DDT commented on src/modules/image/index.ts
>    urlLoremflickr(
```suggestion
  urlLoremFlickr(
```

2022-11-11 16:46 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * Generates a random image url provided via https://loremflickr.com.
Either quote all urls in the jsdocs or none.

2022-11-11 16:52 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * Generates a random image url provided via https://loremflickr.com.
In the description I use unquote, so you can click on the link

2022-11-11 17:44 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * Generates a random image url provided via https://loremflickr.com.
What about https://github.com/faker-js/faker/blob/27f8797e4cf90e7fa7109fd5544ddf86245baa0e/src/modules/image/index.ts#L84 then?

2022-11-11 17:45 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * Generates a random image url provided via https://loremflickr.com.
Mh, it's "complicated" :D
It's not a working link...

2022-11-15 21:34 UTC, ST-DDT requested changes

2022-11-15 21:34 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * faker.image.url() // 'https://loremflickr.com/640/480'
Please update this example. The `lock` parameter is missing.

2022-11-15 21:34 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * faker.image.urlPicsumPhotos({ blur: 4, grayscale: true }) // 'https://picsum.photos/id/1234/640/480?grayscale&blur=4'
Neither of these links work.

2022-11-15 21:34 UTC, ST-DDT commented on test/image.spec.ts
> +        .it('with custom values', {
```suggestion
        .it('with all options', {
```

2022-11-15 21:34 UTC, ST-DDT commented on test/image.spec.ts
> +        .it('with custom width', { width: 128 })
```suggestion
        .it('with width', { width: 128 })
```

2022-11-15 21:34 UTC, ST-DDT commented on test/image.spec.ts
> +        .it('with custom height', { height: 128 })
```suggestion
        .it('with height', { height: 128 })
```

2022-11-15 21:34 UTC, ST-DDT commented on test/image.spec.ts
> +        .it('with custom width and custom height', { width: 128, height: 128 })
```suggestion
        .it('with width and height', { width: 128, height: 128 })
```

2022-11-15 21:34 UTC, ST-DDT commented on test/image.spec.ts
> +        .it('with custom category', { category: 'cats' })
```suggestion
        .it('with category', { category: 'cats' })
```

2022-11-15 21:34 UTC, ST-DDT commented on test/image.spec.ts
> +        .it('with custom width', { width: 128 })
same here

2022-11-15 21:34 UTC, ST-DDT commented on test/image.spec.ts
> +        .it('with custom width', { width: 128 })
and here

2022-11-20 00:29 UTC, ST-DDT commented on src/modules/image/index.ts
>    readonly lorempixel: Lorempixel;
The provider seems now to be down/entirely offline. Should we hard remove it?
See also: https://github.com/faker-js/faker/issues/1571

2022-11-20 12:23 UTC, ST-DDT approved these changes, later dismissed

2022-11-20 12:23 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * faker.image.urlPicsumPhotos({ blur: 4, grayscale: true }) // 'https://picsum.photos/id/1234/640/480?grayscale&blur=4'
I found out that picsum only has around 1084 ids, I capped it to 1000 and checked that it starts with 0

2022-11-23 23:39 UTC, import-brain commented on test/image.spec.ts
> +      expect(() => new URL(avatarUrl)).not.toThrow();
```suggestion
      expect(avatarUrl).toMatch(/^https:\/\//);
      expect(() => new URL(avatarUrl)).not.toThrow();
```
Is line 421 meant to test that the URL is specifically a `https` url or is it just testing if the url is a url in general?

We could probably use `validator.isURL` here

2022-11-23 23:39 UTC, import-brain commented on test/image.spec.ts
> +      expect(() => new URL(imageUrl)).not.toThrow();
Same here

2022-11-23 23:39 UTC, import-brain commented on test/image.spec.ts
> +      expect(() => new URL(imageUrl)).not.toThrow();
Same here

2022-11-23 23:39 UTC, import-brain commented on test/image.spec.ts
> +      expect(() => new URL(imageUrl)).not.toThrow();
Here

2022-11-23 23:39 UTC, import-brain commented on test/image.spec.ts
> +      expect(() => new URL(imageUrl)).not.toThrow();
Here

2022-11-24 07:25 UTC, Shinigami92 commented on test/image.spec.ts
> +      expect(() => new URL(avatarUrl)).not.toThrow();
It's for testing to ensure it is `https`

2022-11-25 05:43 UTC, import-brain approved these changes, later dismissed

2022-11-26 15:29 UTC, ST-DDT requested changes

2022-11-26 15:29 UTC, ST-DDT commented on src/modules/image/index.ts
> +      { min: 0, max: 1249 }
```suggestion
      1249
```

2022-11-26 15:29 UTC, ST-DDT commented on src/modules/image/index.ts
> +    return avatarMethod();
IMO this should only return `avatarGitHub()` for now.

2022-11-26 15:29 UTC, ST-DDT commented on src/modules/image/index.ts
> +    })}/${width}/${height}`;
```suggestion
    let url = `https://picsum.photos/id/${this.faker.number.int(1000)}/${width}/${height}`;
```

2022-11-26 15:30 UTC, ST-DDT commented
This should be mentioned in the upgrade docs.

2022-11-26 18:56 UTC, ST-DDT commented
I think you have to run the formatter once.

2022-11-27 09:38 UTC, ST-DDT approved these changes
I still think avatar should only point to GH avatars but otherwise this is fine.

2022-11-27 09:39 UTC, Shinigami92 commented on src/modules/image/index.ts
> +    return avatarMethod();
acknowledged
maybe ask the other team members

2022-11-27 10:18 UTC, ST-DDT commented on src/modules/image/index.ts
> +    return avatarMethod();
@faker-js/members What do you think?

2022-11-29 00:46 UTC, import-brain commented on src/modules/image/index.ts
> +    return avatarMethod();
Why should it only point to `avatarGitHub()`? I think I'm missing something

2022-11-29 02:32 UTC, ST-DDT commented on src/modules/image/index.ts
> +    return avatarMethod();
See the discussion in discord.

2022-12-03 19:43 UTC, import-brain approved these changes

2022-12-05 07:13 UTC, Shinigami92 commented on src/modules/image/index.ts
> +    return avatarMethod();
To not block this _rewrite image module_ any further, the general discussion and results should be moved to its own issue and should be targeted by its own PR.
- The `image.avatar` should have more then one datasource, as any other methods that behave like that, so it is not just an alias to another function.
- The _legacy_ data set can only be replaced by actual proofed law or an alternative (e.g. AI generated) human face set.

_I will rewrite this when the issue was created by persons of interest_

2022-12-05 07:15 UTC, Shinigami92 commented
@ST-DDT I will take you out as co-author, even if you have worked with me and there are applied review suggestion.
I'm doing this as if there are really any actual law concerns, you are not under fire and I'm responsible for taking changes to the legacy data set.

2022-12-05 07:15 UTC, merged