docs: add banner to next docs
faker-js/faker pull request #1487
Opened 2022-10-25 18:27 UTC by brc-dd

fixes #1456

2022-10-25 18:39 UTC, Shinigami92 requested changes
The banner should always be shown on non-`https://fakerjs.dev/` sites
But they all have the same source, so we need to check `window.location.host !== 'fakerjs.dev'` or something like that

2022-10-25 20:39 UTC, ST-DDT commented on docs/.vitepress/config.ts
> +        process.env.DEPLOY_PRIME_URL ===
In other contexts we used a different property:

https://github.com/faker-js/faker/blob/64b031a9e385d1461b2c158abfa1851ba11a8397/docs/.vitepress/versions.ts#L32-L40

IMO the `CONTEXT` is suited better for this purpose, as it is easier to understand than this cryptic address.
We could re-export it there and reuse it here.

2022-10-25 20:39 UTC, ST-DDT commented on docs/.vitepress/components/Banner.vue
> +    version visit: <a href="https://fakerjs.dev/">fakerjs.dev</a>
This will also be shown on old pages (e.g. v7 once v8 gets released), so maybe this should be a bit differentiated.

We could theoretically export the text (`the next (unreleased)` / `a previous release`) in the versions.ts and use it here.

2022-10-25 20:54 UTC, Shinigami92 commented on docs/.vitepress/config.ts
> +        process.env.DEPLOY_PRIME_URL ===
Do you have an idea how to expose this `CONTEXT` from the server build step to the client side running version?

2022-10-25 21:04 UTC, ST-DDT commented on docs/.vitepress/config.ts
> +        process.env.DEPLOY_PRIME_URL ===
A simple `export` does the job. The vitepress build steps hardcodes the value into the built page and then can be used there.
It/the condition might even be inlined/resolved at build time.

As you can see [here](https://next.fakerjs.dev/):
![grafik](https://user-images.githubusercontent.com/1579362/197881557-7fd6bad3-0100-43ca-80ad-c8e4bb9f2299.png)

That part is already populated from the build time environment variables.

2022-10-26 16:32 UTC, brc-dd commented
Ready for review guys! 🙏

2022-10-26 17:25 UTC, Shinigami92 commented on docs/.vitepress/versions.ts
> +  return { version: '"a development version"', id: 'fk03' };
```suggestion
    return { version: '"an old version"', id: 'old' };
  }
  if (branchName === 'next') {
    return { version: '"the next (unreleased) version"', id: 'next' };
  }
  return { version: '"a development version"', id: 'dev' };
```

2022-10-26 17:25 UTC, Shinigami92 commented on docs/.vitepress/config.ts
> +  restore(\`faker-banner-\${__FAKER_BANNER_ID__}\`, 'banner-dismissed');
```suggestion
  restore(\`faker-version-banner-\${__FAKER_BANNER_ID__}\`, 'banner-dismissed');
```

2022-10-26 17:25 UTC, Shinigami92 commented on docs/.vitepress/components/Banner.vue
> +    `faker-banner-${(window as any).__FAKER_BANNER_ID__}`,
```suggestion
    `faker-version-banner-${(window as any).__FAKER_BANNER_ID__}`,
```

2022-10-26 17:31 UTC, Shinigami92 commented
Example Screenshot of iPhone XS 

![image](https://user-images.githubusercontent.com/7195563/198095907-36ee0654-8545-4571-810f-56ed5f034972.png)

2022-10-26 17:33 UTC, Shinigami92 commented
I'm thinking about to use the `sessionStorage` instead of `localStorage` :thinking:

2022-10-26 17:48 UTC, brc-dd commented
> I'm thinking about to use the sessionStorage instead of localStorage

It won't be persistent then. One will need to dismiss it each time they open the tab.

2022-10-26 17:53 UTC, Shinigami92 commented
> > I'm thinking about to use the sessionStorage instead of localStorage
> 
> It won't be persistent then. One will need to dismiss it each time they open the tab.

I won't want it for each tab, but for each browser re-open :thinking: 
So next time you visit, it come up again, because after half a year or so, you might missed that it is another version
We could also set a timestamp and then check if older then 1 day or x-days

2022-10-26 18:02 UTC, brc-dd commented
> We could also set a timestamp and then check if older then 1 day or x-days

Maybe some approach like this: https://www.sohamkamani.com/javascript/localstorage-with-ttl-expiry/ ?

2022-10-26 18:05 UTC, Shinigami92 commented
I think we don't need to be that complex, we can use the value directly as expire, as currently it is just `1` or `undefined`
So the check would now just be: `defined && < x days, then don't show, otherwise show`, `on dismiss: set timestamp`

2022-10-26 18:30 UTC, brc-dd commented
done

2022-10-26 18:30 UTC, ST-DDT commented
I think we could just show it always. So the users get annoyed and update to the latest version.

2022-10-26 18:42 UTC, Shinigami92 commented
> I think we could just show it always. So the users get annoyed and update to the latest version. What do you think?

No, as on mobile it is to big to not get dismissed :warning:

2022-10-26 18:45 UTC, Shinigami92 submitted a review, later dismissed
For me it's okay now
even if `8.64e7 * 1` is still `8.64e7` and `Date.now() === new Date().getTime()`

2022-10-26 18:49 UTC, brc-dd commented
> Date.now() === new Date().getTime()

Directly adding number with `Date.now()` will simply concat strings instead of adding the number to the time. 😅

2022-10-26 18:59 UTC, Shinigami92 commented
> > Date.now() === new Date().getTime()
> 
> Directly adding number with `Date.now()` will simply concat strings instead of adding the number to the time. sweat_smile

`typeof Date.now() === 'number'` :thinking: 

> > 8.64e7 * 1 is still 8.64e7
> 
> I kept `1` there if you wanted to customize the number of days (ignoring DST).

Ah I understand, maybe should add a comment? Currently feels like a magic number for not knowing folks.

2022-10-26 19:02 UTC, brc-dd commented
> typeof Date.now() === 'number' 🤔 , anyways, it's a nit-pick 🙂

Ah right, I was doing `new Date() + ...`. Will update that.

2022-10-26 19:07 UTC, Shinigami92 submitted a review, later dismissed

2022-10-26 19:23 UTC, ST-DDT commented
I temporarily deployed these to netlify for easier reviewablilty:

- [prod](https://v7--serene-sprite-f3ef50.netlify.app/)
- [old](https://v6--serene-sprite-f3ef50.netlify.app/)
- [next](https://next--serene-sprite-f3ef50.netlify.app/)
- [dev](https://pr-brc-dd-1487--serene-sprite-f3ef50.netlify.app/)

2022-10-26 20:09 UTC, ST-DDT approved these changes, later dismissed
This looks good to me. How about evaluating the value only once and exporting that?
https://github.com/brc-dd/faker-1/compare/next...faker-js:faker:pr/brc-dd/1487-ST-DDT

2022-10-26 20:25 UTC, ST-DDT approved these changes, later dismissed

2022-10-26 20:36 UTC, Shinigami92 approved these changes, later dismissed

2022-10-27 13:56 UTC, ST-DDT submitted a review, later dismissed

2022-10-27 15:15 UTC, Shinigami92 requested changes

2022-10-27 15:15 UTC, Shinigami92 commented on docs/.vitepress/config.ts
> -        content: description,
Why was this removed? looks unintended to the PR

2022-10-27 15:15 UTC, Shinigami92 commented on netlify.toml
> +  command = "pnpm docs:build:ci"
Would you like to create it's own PR (that we can just merge before this PR, so you can rebase without conflict) to tackle this change separately?
That way we have a specific commit history entry for that change.

2022-10-27 15:24 UTC, brc-dd commented on docs/.vitepress/config.ts
> -        content: description,
There is already `description` option being passed in the config, there is no need to pass it using meta description. It was resulting in duplicate tags. Validator was throwing warnings.

I can move it to different PR if you want.

2022-10-27 15:28 UTC, Shinigami92 commented on docs/.vitepress/config.ts
> -        content: description,
So it's managed by VitePress under the hood?

2022-10-27 15:30 UTC, brc-dd commented on docs/.vitepress/config.ts
> -        content: description,
Yeah, this line is equivalent to that block:

https://github.com/faker-js/faker/blob/09e835664add0a342dd089f31bbae7d880198493/docs/.vitepress/config.ts#L56

2022-10-27 15:36 UTC, Shinigami92 approved these changes

2022-10-27 19:58 UTC, ST-DDT commented
For some reason, this doesn't work for the next branch on netlify anymore.
Do you have an idea why?

2022-10-27 19:59 UTC, ST-DDT approved these changes

2022-10-28 10:01 UTC, merged