docs: add upgrading guide for v8
faker-js/faker pull request #1517
Opened 2022-11-04 06:05 UTC by matthewmayer

2022-11-04 15:40 UTC, ST-DDT commented on docs/guide/upgrading.md
> +## faker.fake removed
It is still available as in the helpers module.

2022-11-04 15:40 UTC, ST-DDT commented on docs/guide/upgrading.md
> +The whole `faker.address` module is now located at `faker.location`, as it contains more information than just names. The `faker.address.*` methods will continue to work as an alias in v8 and v9, but
```suggestion
The whole `faker.address` module is now located at `faker.location`, as it contains more information than just addresses.
The `faker.address.*` methods will continue to work as an alias in v8 and v9, but it is recommended to change to `faker.location.*`
```

2022-11-04 15:40 UTC, ST-DDT commented on docs/guide/upgrading.md
> +The whole `faker.name` module is now located at `faker.person`, as it contains more information than just names. The `faker.name.*` methods will continue to work as an alias in v8 and v9, but it is r
```suggestion
The whole `faker.name` module is now located at `faker.person`, as it contains more information than just names.
The `faker.name.*` methods will continue to work as an alias in v8 and v9, but it is recommended to change to `faker.person.*`
```

2022-11-04 15:40 UTC, ST-DDT commented on docs/guide/upgrading.md
> +    const address = `${faker.location.zipCode()} ${faker.location.city()}`;
Please use code blocks here.

2022-11-04 15:40 UTC, ST-DDT commented on docs/guide/upgrading.md
> +- [Upgrading to v7](https://fakerjs.dev/guide/upgrading.html)
We should create a new issue (once this is merged) or TODO comment here so that we remember to update the link before the release.

2022-11-05 07:53 UTC, matthewmayer commented on docs/guide/upgrading.md
> +- [Upgrading to v7](https://fakerjs.dev/guide/upgrading.html)
Perhaps it would be possible to already set up v7.fakerjs.dev currently as a 302 redirect to fakerjs.dev? Then could already link the v7 docs.

2022-11-05 09:34 UTC, matthewmayer commented on docs/guide/upgrading.md
> +## faker.fake removed
removed this section and added it to 'Other deprecated methods replaced' instead

2022-11-05 09:35 UTC, matthewmayer commented on docs/guide/upgrading.md
> +    const address = `${faker.location.zipCode()} ${faker.location.city()}`;
removed this section and added it to 'Other deprecated methods replaced' instead

2022-11-05 12:14 UTC, ST-DDT commented on docs/guide/upgrading.md
> +- [Upgrading to v7](https://fakerjs.dev/guide/upgrading.html)
Awesome idea. I created a PR that sets these links up:

* https://github.com/faker-js/faker/pull/1522
* https://github.com/faker-js/faker/pull/1523

2022-11-05 12:19 UTC, ST-DDT submitted a review, later dismissed

2022-11-05 23:57 UTC, ST-DDT commented on docs/guide/upgrading.md
> +The `en-IND` (English, India) locale was renamed to `en-IN` for consistency with other locales.
```suggestion
The `en_IND` (English, India) locale was renamed to `en_IN` for consistency with other locales.
```

2022-11-06 15:14 UTC, ST-DDT requested changes
Could you please escape the faker method references/wrap them in code blocks? Some of the references are treated as links:

![grafik](https://user-images.githubusercontent.com/1579362/200178819-85c1df28-dd41-4e5d-aee4-f2944f167e7b.png)

Also the link in the sidebar has the wrong title:

![grafik](https://user-images.githubusercontent.com/1579362/200178908-de4a2497-ed4d-4b3b-bc91-5ad572a3cc88.png)

2022-11-07 03:27 UTC, matthewmayer commented
> Could you please escape the faker method references/wrap them in code blocks? Some of the references are treated as links:
> 
> ![grafik](https://user-images.githubusercontent.com/1579362/200178819-85c1df28-dd41-4e5d-aee4-f2944f167e7b.png)
> 
> Also the link in the sidebar has the wrong title:
> 
> ![grafik](https://user-images.githubusercontent.com/1579362/200178908-de4a2497-ed4d-4b3b-bc91-5ad572a3cc88.png)

done

2022-11-07 09:44 UTC, ST-DDT approved these changes, later dismissed

2022-11-07 09:44 UTC, ST-DDT commented on docs/guide/upgrading.md
> +| `faker.phone.phoneFormats`      | No direct replacement, `faker.phone.number` has a format parameter |
I'm not sure about these ones. What do you or the others think?

IMO these methods have been removed and not replaced.
Sure, the user should use `faker.phone.number` instead, but the format parameter is the place you previously would have put the result of the removed methods. The parameter should be deprecated and removed in a future version.

2022-11-07 10:24 UTC, matthewmayer commented on docs/guide/upgrading.md
> +| `faker.phone.phoneFormats`      | No direct replacement, `faker.phone.number` has a format parameter |
Maybe just say  No direct replacement, see documentation for `faker.phone.number`

I think (seperate issue probably) `faker.phone.number` documentation could be improved to clarify what kind of formats are returned by default, and that you can get different numbers in different locales.

2022-11-07 23:05 UTC, ST-DDT commented on docs/guide/upgrading.md
> +| `faker.phone.phoneFormats`      | No direct replacement, `faker.phone.number` has a format parameter |
1) Yes
2) I created issues #1541 and #1542

2022-11-12 12:32 UTC, matthewmayer commented on docs/guide/upgrading.md
> +| `faker.phone.phoneFormats`      | No direct replacement, `faker.phone.number` has a format parameter |
1. done

2022-11-20 00:23 UTC, ST-DDT commented on docs/guide/upgrading.md
> +- [Upgrading to v7](https://v7.fakerjs.dev/guide/upgrading.html)
IMO: It is more likely for users to migrate from v6 to v7 than from v5 to v6.

```suggestion
- [Upgrading to v7](https://v7.fakerjs.dev/guide/upgrading.html)
- [Upgrading to v6](https://v6.fakerjs.dev/migration-guide-v5/)
```

2022-11-20 00:23 UTC, ST-DDT commented on docs/guide/upgrading.md
> +## faker.mersenne and faker.helpers.repeatString removed
```suggestion
## `faker.mersenne` and `faker.helpers.repeatString` removed
```

2022-11-20 00:23 UTC, ST-DDT commented on docs/guide/upgrading.md
> +## faker.name changed to faker.person
```suggestion
## `faker.name` changed to `faker.person`
```

Otherwise `faker.name` is rendered as a link.

2022-11-20 00:23 UTC, ST-DDT commented on docs/guide/upgrading.md
> +## faker.address changed to faker.location
```suggestion
## `faker.address` changed to `faker.location`
```

2022-11-20 15:41 UTC, ST-DDT approved these changes

2022-11-20 15:47 UTC, Shinigami92 approved these changes

2022-11-20 20:24 UTC, import-brain approved these changes

2022-11-21 12:58 UTC, merged