chore: remove "jalapeño" from `en` locale
faker-js/faker pull request #1520
Opened 2022-11-04 15:49 UTC by schw4rzlicht

The `en` locale includes the word "jalapeño" which is the only one with a special char. Imo this is inconsistent and it leads to other problems as well, see https://github.com/faker-js/faker/issues/1105#issuecomment-1186630351 for example.

This PR removes the word from the locale.

2022-11-04 15:57 UTC, ST-DDT commented
AFAICT: `jalapeño` is a proper English word, isn't it?
For #1105 I think we should rather ansify these characters.

2022-11-04 16:25 UTC, schw4rzlicht commented
> AFAICT: `jalapeño` is a proper English word, isn't it?
> For #1105 I think we should rather ansify these characters.

Yes, might make more sense. I altered the Regex that filteres illegal characters in `Internet.domainWord()`, maybe that's what helps?

2022-11-24 09:12 UTC, matthewmayer commented
if https://github.com/faker-js/faker/pull/1554 gets merged then you would be able to use the new version of `faker.helpers.slugify` to turn `jalapeno` to `jalapeño` automatically in domainWord (as domainWord seems to be a slight variant of slugify really).

2022-12-06 06:47 UTC, schw4rzlicht commented
> if #1554 gets merged then you would be able to use the new version of `faker.helpers.slugify` to turn `jalapeño` to `jalapeno` automatically in domainWord (as domainWord seems to be a slight variant of slugify really).

From what I've seen this is right.

But that would mean:

- in order to fix that our team has to change the usage of faker for ~2000 test cases. And I don't think we're alone with this.
- we cannot call `faker.internet.domainWord()`/`faker.internet.domainName()`/`faker.internet.url()` without using `slugify()` together with it, which imo is counter intuitive, not nice to read and will definitely break in the future again, as at some point someone will forget about it
- it doesn't solve the underlying issue with `domainWord()`

As I said [here](https://github.com/faker-js/faker/issues/1105#issuecomment-1186630351):

> From what I understand, not all TLDs are even accepting internationalized domain names ([wiki](https://en.wikipedia.org/wiki/Internationalized_domain_name#Top-level_domains_accepting_IDN_registration)), so I think it is out of scope for faker to determine which are and keep track of that. Imo, domain words should just not include non-ASCII chars to keep it simple.

Additionally, internationalized domain names are converted to ASCII compatible encoding on the client when using them.

Btw, I noticed I forgot to re-add `jalapeño` after refactoring the regex of `domainWord()`. Will do that once our discussion here moves forward :)

2022-12-06 08:13 UTC, Shinigami92 commented
@schw4rzlicht I highly assume he meant using it inside faker in this PR, not in your code to wrap faker calls.

2022-12-06 08:59 UTC, matthewmayer commented
right could you change domainWord to just be something like

```
domainWord(): string {
    return this.faker.helpers
      .slugify(`${this.faker.word.adjective()}-${this.faker.word.noun()}`)
      .toLowerCase();
  }
```

2022-12-06 12:34 UTC, schw4rzlicht commented
> @schw4rzlicht I highly assume he meant using it inside faker in this PR, not in your code to wrap faker calls.

Ah alright, misunderstood that, sorry 🤦

Thanks @matthewmayer, I will update the PR today or tomorrow :)

2022-12-12 14:48 UTC, matthewmayer requested changes

2022-12-12 14:48 UTC, matthewmayer commented on src/modules/internet/index.ts
>        .replace(/-{2,}/g, '-')
I don't think you need these two lines any more as slugify already converts spaces to - for you

2022-12-12 15:35 UTC, ST-DDT approved these changes

2022-12-12 21:28 UTC, Shinigami92 approved these changes

2022-12-12 22:21 UTC, import-brain approved these changes

2022-12-13 15:32 UTC, merged