test: enforce UTC for tests
faker-js/faker pull request #1537
Opened 2022-11-07 17:24 UTC by Shinigami92

<img src="https://i.ytimg.com/vi/3R0Bn4bEmGw/maxresdefault.jpg" width="400px" />

https://github.com/vitest-dev/vitest/issues/1575

2022-11-07 20:08 UTC, ST-DDT commented
IMO there is something else going on here.
Which timezone do you use for your system?

Is there anyone else that has trouble generating/updating the test snapshots files?

2022-11-07 20:15 UTC, ST-DDT requested changes
Does not work for me:

````diff
- Date: Tue Dec 31 2019 13:03:15 GMT+0000 (Coordinated Universal Time)
+ Date: Tue Dec 31 2019 13:03:15 GMT+0000 (Koordinierte Weltzeit)
````

2022-11-07 20:17 UTC, ST-DDT commented
FFR: This PR broke the tests: https://github.com/faker-js/faker/pull/1512

2022-11-07 20:19 UTC, Shinigami92 commented
Oh yeah you are right, previously we didn't had snapshot tests for that
Okay, lets rewrite the implementation in another PR

2022-11-10 17:32 UTC, ST-DDT commented
**Team decision**

We will add a runner instead, that runs in non-UTC and non-EN to highlight these issues in the future.

2022-11-10 21:29 UTC, ST-DDT commented on .github/workflows/ci.yml
> +          timezoneLinux: 'Asia/Singapore'
Shouldn't there easier ways to set the TZ?

Maybe set the locale to non US as well?

https://github.com/actions/runner-images/issues/762#issuecomment-618507288

2022-11-15 19:38 UTC, ST-DDT approved these changes

2022-11-18 18:07 UTC, import-brain approved these changes

2022-11-19 21:21 UTC, merged