refactor: rename params in string module
faker-js/faker pull request #1551
Opened 2022-11-12 00:32 UTC by import-brain

closes #1465

2022-11-12 07:45 UTC, ST-DDT requested changes
Please remove the obsolete test snapshots.

Also we should adjust the jsdocs and error messages to use the new term.

2022-11-12 07:45 UTC, ST-DDT commented on src/modules/random/index.ts
> +      ...options,
IMO you can just put the casing here directly since it is the only property that is left.

2022-11-12 07:45 UTC, ST-DDT commented on src/modules/vehicle/index.ts
> +      exclude: bannedChars,
Please also rename the variable here.

2022-11-12 12:34 UTC, Shinigami92 commented on test/__snapshots__/string.spec.ts.snap
>  exports[`string > 42 > alpha > with length, casing and bannedChars 1`] = `"fwzcvwj"`;
Run `pnpm run test run -u` and these will go away

2022-11-12 13:17 UTC, ST-DDT commented on test/__snapshots__/string.spec.ts.snap
>  exports[`string > 42 > alpha > with length, casing and bannedChars 1`] = `"fwzcvwj"`;
I think we should add it to our uncommited changes CI.

2022-11-12 18:09 UTC, Shinigami92 approved these changes, later dismissed

2022-11-12 23:17 UTC, ST-DDT submitted a review, later dismissed

2022-11-12 23:17 UTC, ST-DDT commented on src/modules/string/index.ts
> +   * @param options.exclude An array with characters to exclude. Defaults to `[]`.
This description is phrases slightly different than the others. Could you adjust it/the others so it is more uniform?

2022-11-13 06:32 UTC, ST-DDT approved these changes

2022-11-13 11:24 UTC, Shinigami92 approved these changes

2022-11-14 22:56 UTC, merged