fix(internet): use a ascii-only fallback for email addresses in some locales, revert slugify to ascii only
faker-js/faker pull request #1554
Opened 2022-11-13 10:10 UTC by matthewmayer

tentative fix for #1105

2022-11-13 10:57 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    }
IMO this should be part of slugify. Is there a way to do that input dependent? Maybe add a todo for that.

2022-11-13 11:25 UTC, matthewmayer commented on src/modules/internet/index.ts
> +    }
In an ideal world we'd be able to transilterate from names in any script to ascii for example "王东" becomes "Wang Dong", "Владимир Ленин" becomes "Vladimir Lenin" and so on.

But there's not really a good generic way to do that without adding lots of dependencies for different locales (pinyin for Chinese, etc).

So i think either we just fallback to something completely random like this, or (as I suggested at https://github.com/faker-js/faker/issues/1105#issuecomment-1305038744) allow non-ASCII-ish locales to expose a seperate static list of ASCII transliterated firstnames and surnames.

2022-11-13 11:39 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +    //In that case we generate a purely random local part instead
```suggestion
    // In some locales e.g. ja or el, userName contains mostly non-Unicode characters
    // https://github.com/faker-js/faker/issues/1105
    // After slugify it becomes a string with only 0-9, _ and .
    // In that case we generate a purely random local part instead
```

2022-11-13 11:39 UTC, Shinigami92 commented on test/internet.spec.ts
> -        it('should return an email with japanese characters', () => {
There are only removed tests but no new added ones 🤔 
Feels destructive

By the way, as far as I know there can really exists email addresses with non english ascii letters. I don't know how far this goes and I assume mail providers explicitly need to support it, but it's possible.

2022-11-13 11:56 UTC, matthewmayer commented on test/internet.spec.ts
> -        it('should return an email with japanese characters', () => {
if you agree this is the right direction I can add new tests :D

its theoretically possible to have non-ascii email addresses but its exceedingly rare in practice as email clients and servers tend to mess them up. 

it's anecdotal but i lived for 10 years in China and never encountered an email address with Chinese chars.

I think faker should aim to give realistic data where possible, rather than something theoretically possible but unrealistic.

2022-11-13 12:04 UTC, Shinigami92 commented on test/internet.spec.ts
> -        it('should return an email with japanese characters', () => {
yes and no
It's also good to have some edge cases, so if you use faker you can discover those edge cases where you as a software writer hasn't thought about

That's my only concern, if other maintainers from Faker agree with you, I'm also okay with that. That was just my thought.

2022-11-13 14:15 UTC, ST-DDT commented on test/internet.spec.ts
> -        it('should return an email with japanese characters', () => {
Let's discuss this in the next team-meeting.

2022-11-13 14:17 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    }
-> Team-Meeting

2022-11-13 16:49 UTC, matthewmayer commented on test/internet.spec.ts
> -        it('should return an email with japanese characters', () => {
i added a test that in all locales, you get a valid email address. Note this fails for `mk` locale due to #1556

2022-11-20 16:03 UTC, matthewmayer commented on src/modules/internet/index.ts
> +    }
note in https://github.com/faker-js/faker/issues/1437#issuecomment-1277513007 @shu-pf also suggested a simular idea of using an ASCII alternative name set for Japanese for some contexts.

2022-11-20 16:07 UTC, matthewmayer commented on src/modules/internet/index.ts
> +    }
My gut feeling is that the ASCII alternative name set is probably the best long term solution, BUT given that there's a lot of other issues with locales and names (like #547  and #1211 ) I think this current PR might be a good temporary solution for v8 which won't interfere with solving those more thorny issues with names and localization.

2022-11-20 16:38 UTC, matthewmayer commented
I added a further refinement to slugify which strips simple diacritics. This helps in languages like French or Vietnamese, where you have names like Adélaïde or Ngân Hà. Previously those accented letters would get removed completed, leading to email addresses like:

`adlade23@gmail.com`
`ngn.h23@gmail.com`

now instead you'd get
`adelaide@gmail.com`
`ngan.ha23@gmail.com`

which seems nicer. I also added some additional tests for slugify.

2022-11-24 17:49 UTC, Shinigami92 commented
**Team Decision:**

- We wont allow adding a dependency to faker to convert the given parameters to related outputs
  This can be done by the user in front of the method and then just pass the converted args to the method
- We will convert non-ascii chars to ascii chars, in a way that the input is related to the outcome, but not in a literal linguistic way
  How that is done is an implementation detail and in the hand of the PR author
- The method `internet.userName` should only return ascii characters
- A new method `internet.displayName` should have (kinda) the same implementation as `internet.userName` has right now, but we can improve e.g. the options/parameter as we are already making breaking changes in v8.0

2022-11-25 06:16 UTC, matthewmayer commented
"We will convert non-ascii chars to ascii chars, in a way that the input is related to the outcome, but not in a literal linguistic way. How that is done is an implementation detail and in the hand of the PR author"

So I tried a new approach in the latest commit, basically reimplementing the userName function with a few strategies:

Ascii names work as before

> faker.internet.userName("Matt","Mayer")
'Matt_Mayer22'

Simple accents are stripped using Unicode NFD

> faker.internet.userName("Hélene","Müller")
'Helene49'

A simple mapping can be use to transliterate alphabetical languages like Cyrillic (could also add say Greek and Thai).

> faker.internet.userName("Фёдор","Достоевский")
'Fedor.Dostoevskii50'

As a final fallback, just concatenate the hex unicode char codes of each character.

> faker.internet.userName("大羽","陳")
'59277fbd33'

2022-11-25 09:43 UTC, ST-DDT reviewed
Impl wise this looks good to me.
Could you add an example to the jsdocs that uses non ascii input?
Also I think it might be better if you move the char mapping to separate file and import it. Not sure whether it should be ts or json. But that is optional for now IMO.

2022-11-25 10:12 UTC, Shinigami92 commented
We also discusses that we want `displayName` with (for now) the old behavior.
Can we please do this in this PR as well? Otherwise I'm afraid of missing it out.
If you explicitly not want to do this in this PR, please leave a reason and also open a new issue so we can track it and not miss it before v8.0 release.

2022-11-25 14:47 UTC, Shinigami92 reviewed
I think there are missing tests for displayName

2022-11-26 15:15 UTC, ST-DDT requested changes

2022-11-26 15:15 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * @param lastName The optional last name to use - though the last name is not always used. If not specified, a random one will be chosen.
I wouldn't limit this to the last name. IMO we could have a more general note, that the given name parts might be used either fully or partially or even not at all to generate the username.

Maybe also add an `@see` targettign the `username` method.

2022-11-26 15:15 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * faker.internet.userName("大羽","陳") //hlzp8d.tpv45
All the other examples use single quotes:

```suggestion
   * faker.internet.userName('大羽', '陳') // 'hlzp8d.tpv45'
```

2022-11-26 15:15 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * faker.internet.displayName("大羽","陳") //大羽.陳
```suggestion
   * faker.internet.displayName('大羽', '陳') // '大羽.陳'
```

2022-11-26 15:15 UTC, ST-DDT commented on src/modules/internet/index.ts
> +
Instead of creating the base from scratch, should we use `displayName()` as the base?

2022-11-26 15:15 UTC, ST-DDT commented on test/internet.spec.ts
> +      t.it('noArgs').it('with names', 'Jane', 'Doe');
Please also use a non ascii example here. (Same for username and email)

It is also possible to join them, since I think they will always take the same parameters:

````ts
t.describeEach('displayName', 'username', (t) => ...);
````

2022-11-26 15:15 UTC, ST-DDT commented on test/internet.spec.ts
> +      describe('displayName()', () => {
```suggestion
      });

      describe('displayName()', () => {
```

2022-11-26 15:15 UTC, ST-DDT commented on test/helpers.spec.ts
> +      describe('slugify()', () => {
I think this describe block can be merged with the one above.

2022-11-27 04:00 UTC, matthewmayer commented on src/modules/internet/index.ts
> +
personally i would keep them seperate, it makes the logic easier to read and they might diverge in future.

2022-11-27 08:52 UTC, ST-DDT submitted a review, later dismissed

2022-11-29 00:48 UTC, import-brain commented on src/modules/internet/char-mappings.ts
> +//selectively sourced from https://github.com/sindresorhus/transliterate/blob/main/replacements.js (under MIT license)
```suggestion
// selectively sourced from https://github.com/sindresorhus/transliterate/blob/main/replacements.js (under MIT license)
```
Please add a space after the `//` on every comment. Otherwise, this LGTM

2022-11-30 03:25 UTC, import-brain submitted a review, later dismissed

2022-11-30 08:57 UTC, ST-DDT submitted a review, later dismissed

2022-12-01 08:03 UTC, Shinigami92 requested changes

2022-12-01 08:03 UTC, Shinigami92 commented on src/modules/internet/char-mappings.ts
> +// selectively sourced from https://github.com/sindresorhus/transliterate/blob/main/replacements.js (under MIT license)
Maybe use a permalink for this 🤔

2022-12-01 08:03 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +
I'm with @matthewmayer 
Sure we have tests, but IMO `displayName()` solves another use-case and can diverge in future

2022-12-01 08:03 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +      .map(function (char) {
Please use inline lambdas, not `function (char) {`

```suggestion
      .map((char) => {
```

Not sure if you need to reformat after apply suggestion

2022-12-01 08:03 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +        //if we have a mapping for this character, (for Cyrillic, Greek etc) use it
```suggestion
        // If we have a mapping for this character, (for Cyrillic, Greek etc) use it
```

2022-12-01 08:03 UTC, Shinigami92 commented on src/modules/internet/char-mappings.ts
> +// selectively sourced from https://github.com/sindresorhus/transliterate/blob/main/replacements.js (under MIT license)
As I already suggest some things, please start such comments with capital sentences

`// Selecti...`

2022-12-01 08:03 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +    //remove spaces and '
```suggestion
    // Remove spaces and `'`
```

or

```suggestion
    // Remove spaces and ' (single-quotes)
```

2022-12-01 08:03 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +    //remove spaces and '
Or even just don't describe the code, because we all can read code ^^
Normally comments should explain the why, not what it do

2022-12-01 10:49 UTC, ST-DDT approved these changes

2022-12-02 18:28 UTC, Shinigami92 approved these changes

2022-12-03 20:15 UTC, merged