fix: strongly type ethereum address with a `0x${string}` type
faker-js/faker pull request #1564
Opened 2022-11-15 13:07 UTC by RobbyUitbeijerse

Hello!

In our application we would like to strongly type token addresses for ethereum, and instead of type `string` we would like to provide a type that guarantees us with the format 0x${string} throughout our applications

We currently typecast the value that faker.finance.ethereumAddress() provides us to it, that works perfectly fine but it seems like a nice addition to have a stronger type for this coming from faker.

Lmk if you would like to see any changes.

2022-11-15 14:41 UTC, Shinigami92 requested changes

2022-11-15 14:41 UTC, Shinigami92 commented on src/modules/string/index.ts
> +      wholeString[casing === 'upper' ? 'toUpperCase' : 'toLowerCase']();
This doesn't look correct to me ⚠️ 
You missed the `mixed` casing!

2022-11-15 14:44 UTC, RobbyUitbeijerse commented on src/modules/string/index.ts
> +      wholeString[casing === 'upper' ? 'toUpperCase' : 'toLowerCase']();
@Shinigami92 good catch, didn't notice that casing type. I have simply reverted the change for converting the string

2022-11-15 15:31 UTC, Shinigami92 reviewed
We need to decide in a team meeting if we want this change

2022-11-15 15:31 UTC, Shinigami92 commented on src/modules/finance/index.ts
> +
Nothing changed here, I think we can omit this blank line from this PR

```suggestion
```

2022-12-11 01:04 UTC, ST-DDT commented
Looks like we forgot to publish our team decision. Sorry for the wait.

**Team decision**

- We think that this change is not worth the extra maintainance/code readability costs, mainly because the later part of `0x{string}` matches strings that aren't etherium addresses at all e.g. `'0xftgugloöiho!'`.
- There are potentially better ways to ensure that you only get etherium addresses instead of just strings. e.g. `type EtheriumAddress = string & {ZZ_IGNORE_ME: 'EtheriumAddress'}` (@Shinigami92 please correct me if I'm wrong and please add the proper name for that construct). If you have such a type in your sources, then you can only pass `EtheriumAddress`es to your methods, a plain string wouldn't work. That way you can ensure that you have to check (and cast) the user given string before using it anywhere. You can overwrite faker's etheriumAddress method type definitions locally, so that the compiler doesn't complain in your tests (@Shinigami92 could you please add an example for that as well?), alternatively write a wrapper method that casts the result accordingly.

````ts
type EtheriumAddress = string & {zzz_ignoreMe: 'EtheriumAddress'};

function validateEtheriumAddress(input: string): EtheriumAddress {
    // actual validation
    return input as EtheriumAddress;
};
function transfer(source: EtheriumAddress, target: EtheriumAddress, amount: number): void {
    // ...
}
````

2022-12-11 11:10 UTC, Shinigami92 commented
@ST-DDT both your suggestions are slightly not correct but have the right intend

---

The first you are suggesting are branded / nominal types

- https://github.com/Microsoft/Typescript/issues/202

As you can see the issue number is just 3 digits, it's one of the oldest requested features that are sadly still not nativly supported and therefore should only be used in closed context and caution
I wont suggest to export a nominal type from a lib like Faker

There are some libs that can help to construct some branded types and I use them myself for branded IDs in my frontends, but I never export them from a lib to be used outside context

---

The second you are talking of are [type guards](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates)

```ts
type EtheriumAddress = whatever;

function isEtheriumAddress(value: any): value is EtheriumAddress {
	//                                  ^^^^^^^^ this is a type-guard
	return typeof value === 'string' && /the-regexp/.test(value)
}
```

2022-12-11 12:40 UTC, closed without merging