feat(helpers): regexpStyleStringParse character class parsing
faker-js/faker pull request #1569
Opened 2022-11-19 16:47 UTC by wooneusean

Fixes #1359 

Example:
```javascript
faker.helpers.regexpStyleStringParse('Test[a-d1-4]{2,4}'); // 'Testda3'
faker.helpers.regexpStyleStringParse('Test[^a-zA-Z0-8]{2}'); // 'Test99'
faker.helpers.regexpStyleStringParse('Test[-a-z]'); // Test-
```

2022-11-19 23:57 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.regexpStyleStringParse('[1-7]') // '5'
Why did you remove/cahnge that example?
Doesn't it work anymore?

2022-11-20 03:51 UTC, wooneusean commented on src/modules/helpers/index.ts
> +   * faker.helpers.regexpStyleStringParse('[1-7]') // '5'
Yes and no, it will work but it is not the same outcome. RegEx will see [100-200] as 1, 0, 0-2, 0 0. Which means it will accept 0, 1 and 2.

2022-11-20 08:59 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.regexpStyleStringParse('[1-7]') // '5'
So now it is generating a string for proper regexes?
You have to adjust the jsdocs though because it still references the number ranges.
However I think it might be better to introduce it as a new method to the string module e.g. `faker.string.forRegex`.
What do you think?

2022-11-20 09:15 UTC, wooneusean commented on src/modules/helpers/index.ts
> +   * faker.helpers.regexpStyleStringParse('[1-7]') // '5'
> So now it is generating a string for proper regexes?

yep
> You have to adjust the jsdocs though because it still references the number ranges.

Will do

> However I think it might be better to introduce it as a new method to the string module e.g. faker.string.forRegex instead of breaking the behavior of the existing method.
What do you think?

Indeed that would be good for not breaking stuff, but if I were to create a new function, it will practically do the same thing, and users might not immediately know the difference and might cause confusion. I feel, for correctness and also for less confusion, to update the current function with the correct implementation.

2022-11-20 09:31 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.regexpStyleStringParse('[1-7]') // '5'
> Indeed that would be good for not breaking stuff, but if I were to create a new function, it will practically do the same thing, and users might not immediately know the difference and might cause confusion. I feel, for correctness and also for less confusion, to update the current function with the correct implementation.

An alternative for that would be deprecating the old implementation when introducing the new method.
We will discuss the best way in a team meeting.

2022-11-20 10:22 UTC, ST-DDT approved these changes, later dismissed
Looks good to me.

However, we have to decide whether we want to introduce this as a new method (e.g. `faker.string.forRegex`) because it changes the behavior of the method.

2022-11-20 10:59 UTC, ST-DDT submitted a review, later dismissed

2022-11-20 11:20 UTC, Shinigami92 requested changes
Yeah I'm with @ST-DDT, but I would maybe name it `string.fromRegExp`
`from` instead of `for` because it relates to the input parameter
and `RegExp` because that is how the class is named in JS

2022-11-20 11:24 UTC, ST-DDT commented
> and `RegExp` because that is how the class is named in JS

Good idea, then it should accept actual Regexp types as well. `( pattern: RegExp | string)`

````ts
if (pattern instanceof RegExp) {
    pattern = pattern.toString();
}
````

2022-11-20 12:00 UTC, wooneusean commented
> Good idea, then it should accept actual Regexp types as well. ( pattern: RegExp | string)

Looking around online, I came across another library called [RandExp.js](https://github.com/fent/randexp.js) that does exactly this. We can just use this library to facilitate that functionality. What do you guys think?

2022-11-20 12:07 UTC, Shinigami92 commented
`@faker-js/faker` is a dependency-free project right now, just to support this for a function that is used by <1% of our users might be really overkill
I would then more be of the favor of deprecating the function and log a warning to directly use their solution
But our current solution depends on `this.faker.datatype.number`-call and therefore depends on a deterministic seed
I think the `RandExp.js` solution does not provide that, does it?

2022-11-20 12:10 UTC, wooneusean commented
> But our current solution depends on this.faker.datatype.number-call and therefore depends on a deterministic seed
I think the RandExp.js solution does not provide that, does it?

Hmm you have a point. I'm new to open source, so tell me if this sounds crazy or not: I copy their implementation and use calls to faker's random number generation. That way we can have their functionality, and also keep the deterministic nature of the function.

2022-11-20 12:19 UTC, ST-DDT commented
IMO we should use the current implementation as a basic implementation. We can add a comment in the jsdocs that for complete regex support the users can use that library and explain how you can use it with faker.

2022-11-20 12:22 UTC, Shinigami92 commented
For now my first thought would that this is definitely to much code (in terms of `loc`)
But in a later version of faker > 8.0 we want to restructure the project and move every single function to it's own file
Then it would not be anymore such a huge problem as everything is just one file that depends to this regex things

IMO even the current PR looks really long for just one function

Not sure what I can suggest you now to proceed or maybe just wait, but this could take months :confused:

2022-11-20 12:24 UTC, wooneusean commented
I guess there's no rush right? As you mentioned <1% of users probably use this functionality anyways. For now, I'll just wait 😐

2022-12-08 20:41 UTC, ST-DDT commented
Sorry for the long wait.

**Team decision**

- For now we don't change the existing method
- Instead we will add a new method `string.fromRegExp(string | RegExp): string`
- We will create a separate issue regarding deprecation of the old method

2022-12-10 06:05 UTC, wooneusean commented
Alright noted.
 
This seems like it has become a more complex problem as tokenising RegEx is needed to properly generate correct text (according to the previously mentioned library). If I were to try to implement it it might be a huge change.

Whats the course of action now?

2022-12-10 09:39 UTC, ST-DDT commented
IMO We dont require full regex support.
Just mention which features are supported and add a text like `if you need full regexp support, then search for compatible third party libraries.`
If neccessary we can extend our featureset in the future.

2022-12-11 13:43 UTC, wooneusean commented
Alright noted.

As my changes stand now, do you guys think it is enough? Or are there other specific things that are needed to be supported?

2022-12-11 15:41 UTC, ST-DDT commented
> As my changes stand now, do you guys think it is enough? Or are there other specific things that are needed to be supported?

I think it is enough, if we need more features we can do that in a later PR.

2022-12-18 10:36 UTC, wooneusean commented
I reverted the `regexpStyleStringParse` function but I copied over my previous changes with that function and renamed it as I still needed the other functionalities.

2022-12-18 19:58 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.fromRegExp(new RegExp('[A-Z0-9]{4}-[A-Z0-9]{4}')) // 'BS4G-485H'
Maybe use the regex syntax directly.

```suggestion
   * faker.helpers.fromRegExp(/[A-Z0-9]{4}-[A-Z0-9]{4}/) // 'BS4G-485H'
```

2022-12-18 19:58 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * @since 5.0.0
```suggestion
   * @since 8.0.0
```

2022-12-18 19:58 UTC, ST-DDT commented on test/helpers.spec.ts
> +        .it('with RegExp object', new RegExp('[A-D0-9]{4}-[A-D0-9]{4}'));
```suggestion
        .it('with RegExp object', /[A-D0-9]{4}-[A-D0-9]{4}/);
```

+ one with regex options such as case insensitive.

2022-12-18 19:58 UTC, ST-DDT commented
Should we move it to the string module?

2022-12-19 05:50 UTC, wooneusean commented
Will address those changes you suggested.

> Should we move it to the string module?

I'm not sure, but I guess since it almost does the same thing as `regexpStyleStringParse` maybe it should just be left there?

Also, there seems to be this failed test and I am not sure how to fix it

```
 ❯ test/scripts/apidoc/examplesAndDeprecations.spec.ts:106:27
    104|       } else {
    105|         for (const spy of consoleSpies) {
    106|           expect(spy).not.toHaveBeenCalled();
       |                           ^
    107|         }
    108|       }
```

2022-12-19 07:40 UTC, wooneusean commented
New changes a bit messy, but its the only way I could think of adding case insensitive safely.

Also, I found out splicing with negative values remove from the back of the list. So I have to do some ugly code to address that.

2022-12-19 23:43 UTC, ST-DDT reviewed
This method implementation looks longer than expected.

Please note, that we will probably not or be slower to review this PR again during the holidays.

2022-12-19 23:43 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      );
You can probably use `faker.helpers.multiple` + `String.fromCharCode(faker.helpers.arrayElement(...))` + `join('')` for that.

2022-12-20 05:45 UTC, wooneusean commented
> This method implementation looks longer than expected.

I'll try to shorten it

2022-12-23 20:25 UTC, Shinigami92 submitted a review, later dismissed
I assume @ST-DDT also want some non seeded test, does he?
Otherwise, it's a start :+1:

2023-01-03 07:17 UTC, wooneusean commented
Non-seeded tests are referring to the "Random Seeded Tests" right?

2023-01-06 10:03 UTC, ST-DDT requested changes
The tests are failing. Please update the PR and fix the errors.

2023-01-06 20:46 UTC, wooneusean commented
> The tests are failing. Please update the PR and fix the errors.

Will add unseeded tests and fix errors soon.

2023-01-07 07:43 UTC, wooneusean commented
I see a v8 branch, do I merge that into this branch or do I still merge next?

2023-01-07 09:31 UTC, ST-DDT commented
The next branch is the branch for continous development.
The vX branches are for completed release versions.
So the next branch is the correct branch to target.

2023-01-07 10:43 UTC, wooneusean commented
Also, this message shows up even though I have never changed my git config. No idea why this is happening.

![image](https://user-images.githubusercontent.com/20278298/211146249-83aef0ba-f9f7-46b8-8774-857dc4bb8c1f.png)

2023-01-07 10:46 UTC, Shinigami92 commented
> Also, this message shows up even though I have never changed my git config. No idea why this is happening.
> 
> ![image](https://user-images.githubusercontent.com/20278298/211146249-83aef0ba-f9f7-46b8-8774-857dc4bb8c1f.png)

Please run `rm -rf .git/hooks`

2023-01-07 15:39 UTC, ST-DDT commented on pnpm-lock.yaml
> +  '@types/node': 18.11.18
Please revert these changes.

2023-01-08 20:14 UTC, wooneusean commented on pnpm-lock.yaml
> +  '@types/node': 18.11.18
Will update soon.

2023-01-09 05:20 UTC, wooneusean commented on pnpm-lock.yaml
> +  '@types/node': 18.11.18
This change is done by `pnpm install` though, and I am not sure how to forcibly downgrade without changing `package.json` because in that file, the version for `@types/node` is `~18.11.17`

2023-01-09 07:51 UTC, Shinigami92 commented on pnpm-lock.yaml
> +  '@types/node': 18.11.18
Try
```
git checkout origin/next pnpm-lock.yaml
pnpm install
```

2023-01-09 09:54 UTC, wooneusean commented on pnpm-lock.yaml
> +  '@types/node': 18.11.18
got it, thanks.

2023-01-09 12:31 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * @param pattern The template string to to parse.
```suggestion
   * @param pattern The template string/RegExp to generate a matching string for.
```

2023-01-09 12:31 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * Replaces the regex like expressions in the given string with matching values.
```suggestion
   * Generates a string matching the given regex like expressions.
```

2023-01-09 12:31 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  fromRegExp(pattern: string | RegExp = ''): string {
Not sure about the empty string default.

2023-01-09 12:31 UTC, ST-DDT commented on test/helpers.spec.ts
> +        .it('swap range if start is greater than end', '[z-a]')
Could you please remove the parts that are not relevant for the individual test cases?

2023-01-09 13:08 UTC, wooneusean commented on test/helpers.spec.ts
> +        .it('swap range if start is greater than end', '[z-a]')
This is necessary as it still needs to conform to the functionality of `regexpStyleStringParse()`.

What can be done in `regexpStyleStringParse()` should be able to be done in `fromRegExp()` as well is what I mean.

2023-01-09 13:13 UTC, wooneusean commented on src/modules/helpers/index.ts
> +  fromRegExp(pattern: string | RegExp = ''): string {
What is your concern?

2023-01-09 18:49 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  fromRegExp(pattern: string | RegExp = ''): string {
If there is no regex that the result should match, then there isn't a need to generate anything in the first place.

2023-01-09 18:51 UTC, ST-DDT commented on test/helpers.spec.ts
> +        .it('swap range if start is greater than end', '[z-a]')
> This is necessary as it still needs to conform to the functionality of `regexpStyleStringParse()`.
> 
> What can be done in `regexpStyleStringParse()` should be able to be done in `fromRegExp()` as well is what I mean.

I disagree. Both methods are independent of each other.
One is for a custom (non-)regex, the other is for a subset of regex.

2023-01-09 20:06 UTC, wooneusean commented on test/helpers.spec.ts
> +        .it('swap range if start is greater than end', '[z-a]')
I see, noted. Will remove those tests that you marked.

2023-01-09 20:08 UTC, wooneusean commented on src/modules/helpers/index.ts
> +  fromRegExp(pattern: string | RegExp = ''): string {
Ah I see, so what you want me to add is an early return when `pattern` is an empty string?

2023-01-10 21:19 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  fromRegExp(pattern: string | RegExp = ''): string {
No, disallow calling `fromRegExp()` (without any arguments).

2023-01-11 06:53 UTC, wooneusean commented on src/modules/helpers/index.ts
> +  fromRegExp(pattern: string | RegExp = ''): string {
Alright noted, will disallow calling without arguments.

2023-01-11 21:34 UTC, ST-DDT commented
Please fix the failing tests.

2023-01-12 10:09 UTC, wooneusean commented
> Please fix the failing tests.

Weird, testing locally doesn't show that error. Will address it.

2023-01-13 20:34 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    if (pattern == null) return '';
AFAICT pattern should never be null here, if a pattern is given.
And since it is required, this check should be obsolete.

2023-01-15 05:45 UTC, wooneusean commented on src/modules/helpers/index.ts
> +    if (pattern == null) return '';
That is what I thought as well but the failing tests show the pattern is undefined when it is being used with `.match()` a few lines below this. The test that failed isn't written by me though, I think its some automated test thing but I'm not sure.

2023-01-16 00:17 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    if (pattern == null) return '';
One of your examples doesn't have an argument thus causes the illegal invocation:

https://github.com/faker-js/faker/pull/1569/files#diff-3f6b4fc424ba2cedcbf5f612ba256d248f0c05f46314eed1dfa81590bcd429fdR268

If you remove that line, you can also remove this one.

(We have tests that ensure that the jsdocs examples work or at least don't throw an error^^)

2023-01-16 06:51 UTC, wooneusean commented on src/modules/helpers/index.ts
> +    if (pattern == null) return '';
> (We have tests that ensure that the jsdocs examples work or at least don't throw an error^^)

Wow, I learn something new everyday. Will remove that example.

2023-01-17 21:20 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    if (pattern == null) return '';
Please also remove the null check here.

2023-01-18 09:07 UTC, ST-DDT submitted a review, later dismissed
Looks good to me. I'm just ensure whether this should be in the `string` module instead.

2023-01-21 17:20 UTC, Shinigami92 submitted a review, later dismissed

2023-01-22 00:45 UTC, xDivisionByZerox commented on test/helpers.spec.ts
> +        it('flips the range when min > max', () => {
Is this really a desired behavior? Wouldn't the use-case be something like:
```ts
const regex = validator.validationRegExp;
const value = faker.helpers.fromRegExp(regex);
// [...]
const isValid = validator.isValid(value);
```

Since we are working with real `RegExp` here I think an invalid RegExp should be treated as such.

2023-01-22 00:54 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +   * faker.helpers.fromRegExp('[0-9a-dmno]') // '5' | 'c' | 'o'
We don't have multiple example result for a single example in any other place (please correct me if I'm wrong). I see the benefit but would suggest to stick with one example result here as well.

2023-01-22 00:57 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +   * Supported patterns:
Should the list include the use of case insensitivity via an actual `RegExp`?

2023-01-22 16:59 UTC, ST-DDT commented on test/helpers.spec.ts
> +        it('flips the range when min > max', () => {
> Uncaught SyntaxError: numbers out of order in {} quantifier.

Since it isn't supported by js, we shouldn't support it either.

2023-01-23 06:53 UTC, wooneusean commented on test/helpers.spec.ts
> +        it('flips the range when min > max', () => {
What should I do here? Leave it as it is or remove the flipping?

2023-01-23 08:13 UTC, ST-DDT commented on test/helpers.spec.ts
> +        it('flips the range when min > max', () => {
Remove the flipping and throw an error instead.

2023-01-23 14:54 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +          // throw error if min larger than max
From our [docs/contribution guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md#jsdocs)

> If a function can throw an error (FakerError) you have to include the @throws tag with an explanation when an error could be thrown

So could you please:
1. Throw a `FakerError` as well as test for that to be thrown ([example](https://github.com/faker-js/faker/blob/795ca8cc52b357e03447a282469c6d1fb44fc960/test/faker.spec.ts#L16-L20))
2. Add a `@throws` param as well a description to the JSDocs

I should have been more clear on the first comment. Thats my bad.

2023-01-23 15:18 UTC, ST-DDT reviewed
I'm quite unsure which features should be supported in the MVP.

2023-01-23 15:18 UTC, ST-DDT commented on test/helpers.spec.ts
> +        );
```suggestion
      t.it('with static string', 'Hello World!')
        .it('with static RegExp', /Hello World!/)
        .it('with dynamic string', '[A-D0-9]-[A-D0-9]-A')
        .it('with dynamic RegExp', /[A-D0-9]-[A-D0-9]-A/)
        .it('with wildcard character', /./)
        .it('with optional character', /A?-[A-D0-9]?-[a-d0-4]?/)
        .it('with optional repetition', /A*-[A-D0-9]*-[a-d0-4]*/)
        .it('with required repetition', /A+-[A-D0-9]+-[a-d0-4]+/)
        .it('with quantifier', /A{2}-[A-D0-9]{4}-[a-d0-4]{6}/)
        .it('with quantifier ranges', /A{2,6}-[A-D0-9]{4,6}-[a-d0-4]{6,8}/)
        .it('with case insensitive flag', /[A-D0-9]{10}/i)
        .it('with negation and case insensitive flag', /[^a-t0-7]{10}/i)
        .it('with negation', /[^A-Za-y0-9]{10}/);
```

Could you add support for the missing cases as well?

2023-01-23 20:21 UTC, wooneusean commented on test/helpers.spec.ts
> +        );
I could, it will take some time and it will make the function larger and more complex than it currently is which I assume is a concern from previous reviews.

2023-01-23 20:49 UTC, ST-DDT commented on test/helpers.spec.ts
> +        );
@faker-js/maintainers @faker-js/members `@anyone`: Any preferences?

2023-01-23 21:11 UTC, xDivisionByZerox commented on test/helpers.spec.ts
> +        );
I wouldn't actually put any restrictions on the repetition part. I think something like `while (faker.datatype.boolean()) { [...] }` instead. But a static number that gets generated upfront might be easier to handle.

For the wildcard, all functions from the string module (including special characters) can be used IMO.

2023-01-23 21:15 UTC, ST-DDT commented on test/helpers.spec.ts
> +        );
We could use an option to overwrite what `.` is and it can be used as a base for `[^something]`.

2023-01-24 09:53 UTC, wooneusean commented on test/helpers.spec.ts
> +        );
> `while (faker.datatype.boolean()) { [...] }`

Wont this make it so that higher repetitions are rarer?

> But a static number that gets generated upfront might be easier to handle.

I agree but the concern with that is like what I stated above, what should be the maximum number of repetitions? If it randomly generates some large number, it will still work but its kinda unreasonable, no?

> For the wildcard, all functions from the string module (including special characters) can be used IMO.

I see a function `faker.string.sample()`, is this function suitable for generating wildcard characters?
There is also another concern, supposedly `.` matches all characters except `\n`. Chinese, Cyrillic etc characters also need to be included but to include those is also a huge pain, and I have no idea where to start with those. Can I sweep this concern under the rug?

> We could use an option to overwrite what `.` is and it can be used as a base for `[^something]`.

I think this is not appropriate. If the user wants to give their own definition, they can just do it in normal character sets, i.e `/[a-z0-9]/`.

2023-01-24 10:52 UTC, xDivisionByZerox commented on test/helpers.spec.ts
> +        );
> Wont this make it so that higher repetitions are rarer?

Yes, you are right. I wanted to include the current interaction count as a `probability` parameter in the function (but forgot to actually write it). This would then look something like this: `while (faker.datatype.boolean(1 / currentIteration)) { [...] }` which equates to a logarithmic distribution of repetitions.

> I agree but the concern with that is like what I stated above, what should be the maximum number of repetitions? If it randomly generates some large number, it will still work but its kinda unreasonable, no?

If this is way easyer for you to implement for you - go for it and hard code the max number to an arbitrary number (like 25). Don't think to much about it. Altho, one could argue that since it is a wildcard, an infinite number of repetitions is expected by design.

> I see a function faker.string.sample(), is this function suitable for generating wildcard characters?
There is also another concern, supposedly . matches all characters except \n. Chinese, Cyrillic etc characters also need to be included but to include those is also a huge pain, and I have no idea where to start with those. Can I sweep this concern under the rug?

Yes, this is perfect. Altho `.` matches anything I would argue that it is simple enough to return any character from our string methods. Keep in mind that this should be a helper function, not a full blown library on its own^^

> I think this is not appropriate. If the user wants to give their own definition, they can just do it in normal character sets, i.e /[a-z0-9]/.

I'm with you. RegExp lets you do some fantastic things. If you want a specific char set, don't use a wildcard matcher.

2023-01-25 09:22 UTC, wooneusean commented
I suddenly get this error when running tests

![image](https://user-images.githubusercontent.com/20278298/214525635-89130b40-534a-4afc-b622-e4c8464c47fa.png)

2023-01-25 11:38 UTC, ST-DDT commented
Please run `pnpm install`. If that doesn't help merge `next` and run `pnpm install` again.

2023-02-08 19:11 UTC, wooneusean commented
Sorry for the delay guys, I just got past a busy period. Will start back on this soon.

2023-02-11 12:43 UTC, ST-DDT approved these changes

2023-02-11 12:43 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * - `[-...]` => Include dashes in the range. Must be placed after the negate character `^` and before any character sets if used . (e.g. `[^-0-9]` will not get any numeric characters or dashes).
```suggestion
   * - `[-...]` => Include dashes in the range. Must be placed after the negate character `^` and before any character sets if used (e.g. `[^-0-9]` will not get any numeric characters or dashes).
```

2023-02-11 12:43 UTC, ST-DDT commented on pnpm-lock.yaml
> +  '@types/node': 18.11.19
Please revert all changes to this file:

````sh
git fetch --all
git reset origin/next -- pnpm-lock.yaml
````

(Not tested)

2023-02-11 12:43 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +            while (this.faker.datatype.boolean(1 / (repetitions + 1))) {
AFAICT this will always be true on the first run (1 / (0 + 1)= => 1 / 1 => 1 => true.
IMO just ``while( .......boolean())`` should be enough.

Also this favors very small numbers. I suggest using:

````ts
let limit = 1;
while (boolean()) {
 limit *= 2;
}
repetitions = int(min: 0, max: limit);
````

(if the user doesn't want large strings, then they shouldn't use */+ in the first place, because I as a tester love to destroy applications with this kind of loose validation)

2023-02-11 12:43 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +            while (this.faker.datatype.boolean(1 / repetitions)) {
Same here

2023-02-11 12:43 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +            repetitions = 1;
Then lets throw an error here.

2023-02-11 12:43 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +          default:
This is the same as above.

2023-02-11 12:43 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * - `[^...]` => Randomly get a character that is not in the given range. (e.g. `[^0-9]` will get a random non-numeric character).
Please add a hint that this currently refers to ascii characters.

Maybe like this:

```suggestion
   * - `[^...]` => Randomly get a ascii number or letter character that is not in the given range. (e.g. `[^0-9]` will get a random non-numeric character).
```

?

2023-02-11 12:44 UTC, ST-DDT requested changes
Ups, I pressed the wrong button

2023-02-11 13:57 UTC, wooneusean commented on pnpm-lock.yaml
> +  '@types/node': 18.11.19
How do I prevent this from happening again, cause it automatically updates this when I run `pnpm install`.

2023-02-25 08:19 UTC, wooneusean commented
Should I put the code to get the repetitions based on the symbol into an inner function within the `fromRegExp` function? Or is this considered sacrilegious? 

something like:
```typescript
 fromRegExp(pattern: string | RegExp): string {
    function getRepetitionsFromQuantifier(quantifierSymbol: string) {
      switch (quantifierSymbol) {
        case '?': {
          return this.faker.datatype.boolean() ? 0 : 1;
        }

        case '*': {
          let limit = 1;
          while (this.faker.datatype.boolean()) {
            limit *= 2;
          }
          return this.faker.number.int({ min: 0, max: limit });
        }

        case '+': {
          let limit = 1;
          while (this.faker.datatype.boolean()) {
            limit *= 2;
          }
          return this.faker.number.int({ min: 1, max: limit });
        }

        default:
          throw new FakerError('Unknown quantifier symbol provided.');
      }
    }
...
```

2023-02-25 10:32 UTC, ST-DDT commented
> Should I put the code to get the repetitions based on the symbol into an inner function within the `fromRegExp` function?

If you wrap that logic into a function that will reduce code repetition and thus help maintaining code readability. There are two solutions that I would be fine with.

- A big lambda expression inside the method
- A separate function above the class definition that also takes a faker instance as parameter. See also https://github.com/faker-js/faker/blob/11a5f51ddb4ab1163d770c4b12f5fe4711b8e11d/src/modules/person/index.ts#L22

2023-03-03 15:42 UTC, ST-DDT reviewed
Could you please move the marked code to a separate method/move it to the already extracted method as well?

2023-03-03 15:42 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      }
This part also looks very much like the other one.

2023-03-03 15:42 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      }
This one

2023-03-04 23:31 UTC, ST-DDT approved these changes, later dismissed

2023-03-08 16:24 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +  } else if (quantifierMin && quantifierMax) {
Is e.g. `quantifierMin == 0` allowed here?

2023-03-09 16:06 UTC, wooneusean commented on src/modules/helpers/index.ts
> +  } else if (quantifierMin && quantifierMax) {
I would assume yes because `faker.number.int` will handle the error checking if the user makes the `quantifierMin` more than the `quantiferMax` or other problems related to it.

2023-03-09 18:21 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  } else if (quantifierMin && quantifierMax) {
Do we then have to use 

```suggestion
  } else if (quantifierMin != null && quantifierMax != null) {
```

instead?

2023-03-10 07:45 UTC, wooneusean commented on src/modules/helpers/index.ts
> +  } else if (quantifierMin && quantifierMax) {
Oh yeah that makes sense since `(quantifierMin && quantifierMax)` will be false if both of them are 0 which is wrong. I will update this soon.

2023-03-17 22:23 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  let repetitions = 0;
Note to self: Check if `0` is the correct fallback here. `1` might be more correct. Maybe throwing an error would be best?

2023-03-26 07:01 UTC, wooneusean commented on src/modules/helpers/index.ts
> +  let repetitions = 0;
After thinking about it, `1` seems more reasonable, because now it just removes the character completely if there's a problem.

I'll change it to `1`.

2023-03-26 09:05 UTC, matthewmayer requested changes

2023-03-26 09:05 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +   * - `[^...]` => Randomly get an ACSCII number or letter character that is not in the given range. (e.g. `[^0-9]` will get a random non-numeric character).
ACSCII -> ASCII

2023-03-26 09:05 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +   * - `.` => returns a wildcard character that can be any number, character or symbol. Can be combined with quantifiers as well.
maybe also mention that this is ASCII only?

2023-03-26 17:51 UTC, ST-DDT approved these changes

2023-03-27 06:40 UTC, Shinigami92 approved these changes

2023-03-27 06:44 UTC, matthewmayer approved these changes

2023-03-27 12:02 UTC, merged