chore: update license
faker-js/faker pull request #157
Opened 2022-01-15 16:40 UTC by damienwebdev

We have retained the MIT License and added explicit reference to the original codebase of Marak.

2022-01-15 16:47 UTC, Shinigami92 requested changes
We should add a `LICENSE` file (without .md at the end)
This is the expected default file as GitHub want it
Examples: https://github.com/prettier/plugin-pug/blob/main/LICENSE https://github.com/vitejs/vite/blob/main/LICENSE

2022-01-15 16:51 UTC, damienwebdev commented
Agreed @Shinigami92, I have moved the file.

2022-01-15 16:55 UTC, Shinigami92 approved these changes

2022-01-16 16:26 UTC, import-brain approved these changes

2022-01-16 20:25 UTC, griest024 approved these changes

2022-01-16 20:26 UTC, merged