refactor(string)!: swap `allowLeadingZeros` default to `true`
faker-js/faker pull request #1602
Opened 2022-11-25 05:39 UTC by import-brain

closes #1592

2022-11-25 08:07 UTC, Shinigami92 requested changes

2022-11-25 08:07 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * const message = faker.helpers.fake('Your pin is {{string.numeric(4)}}.')
This invalidated the wanted example
> It is also possible to use multiple parameters (comma separated).

2022-11-25 08:07 UTC, Shinigami92 commented on src/modules/random/index.ts
> +   * @param options.allowLeadingZeros If true, leading zeros will be allowed. Defaults to `true`.
```suggestion
   * @param options.allowLeadingZeros Whether leading zeros are allowed or not. Defaults to `true`.
```

I think we should add the `or not` at the end: https://dictionary.cambridge.org/grammar/british-grammar/whether

2022-11-25 08:07 UTC, Shinigami92 commented on src/modules/string/index.ts
> +   * @param options.allowLeadingZeros If true, leading zeros will be allowed. Defaults to `true`.
```suggestion
   * @param options.allowLeadingZeros Whether leading zeros are allowed or not. Defaults to `true`.
```

2022-11-25 08:07 UTC, Shinigami92 commented on test/string.spec.ts
>            });
I think this should be swapped. The test was not to test the default but to test passing the option property

2022-11-25 17:00 UTC, matthewmayer commented
Could you include a change to `docs/guide/upgrading.md` as part of this PR for documenting this behavior change for anyone upgrading from v7 to v8?

2022-11-26 14:49 UTC, ST-DDT requested changes
Should we add a link from string.numeric -> number.int (and vice versa)?

2022-11-26 14:49 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.fake('I rolled the dice and got: {{string.numeric(1)}}') // 'I rolled the dice and got: 6'
This example is about showing the ability to pass multiple arguments:

```suggestion
   * faker.helpers.fake('I rolled the dice and got: {{string.numeric(1, {"allowLeadingZeros": false})}}') // 'I rolled the dice and got: 6'
```

2022-11-26 14:49 UTC, ST-DDT commented on src/modules/random/index.ts
> +   * @param options.allowLeadingZeros Whether leading zeros are allowed or not. Defaults to `true`.
Should we retain the old default for the old method?

2022-11-26 19:04 UTC, import-brain commented
> Should we add a link from string.numeric -> number.int (and vice versa)?

What do you mean by link? A jsdoc @link tag?

2022-11-26 19:14 UTC, ST-DDT commented
> > Should we add a link from string.numeric -> number.int (and vice versa)?
> 
> What do you mean by link? A jsdoc @link tag?

I was referring to `@see`

2022-11-26 19:27 UTC, ST-DDT commented on docs/guide/upgrading.md
> +The `allowLeadingZeros` boolean parameter in `faker.string.numeric` (in the new `string` module) now defaults to `true`, unlike `faker.string.numeric`'s predecessor, `faker.random.numeric`. `faker.st
Could you change it somewhat like this to avoid repeating the fqmn 3 times?

```suggestion
The `allowLeadingZeros` boolean parameter in `faker.string.numeric` (in the new `string` module) now defaults to `true`, unlike its predecessor, `faker.random.numeric`. `faker.string.numeric` will now generate numeric strings that could have leading zeros by default.
```

2022-11-26 19:41 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * @see faker.string.numeric if you would like to generate a string of digits
```suggestion
   * @see faker.string.numeric() If you would like to generate a `string` of digits with a given length (range).
```

2022-11-26 19:41 UTC, ST-DDT commented on src/modules/string/index.ts
> +   * @see faker.number.int() if you would like to generate a number (within a range)
```suggestion
   * @see faker.number.int() If you would like to generate a `number` (within a range).
```

Would make `within a value range` make it more distinct from the `length range`?

2022-11-26 20:43 UTC, Shinigami92 commented on src/modules/number/index.ts
> +   * @see faker.string.numeric if you would like to generate a string of digits
Woopsy, didn't thought of that this is not my PR :facepalm: 
I will leave the rest to @import-brain

2022-11-27 23:57 UTC, ST-DDT submitted a review, later dismissed

2022-11-28 02:36 UTC, matthewmayer requested changes

2022-11-28 02:36 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +   * faker.helpers.fake('I rolled the dice and got: {{string.numeric(1, {"allowLeadingZeros": false})}}') // 'I rolled the dice and got: 6'
This is a weird example. For rolling a dice I'd expect to use number.int with min 1 and max 6. And a one-digit numeric string doesn't have any leading zeros, so the value of the allowLeadingZeros is irrelevant?

2022-11-28 07:39 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * faker.helpers.fake('I rolled the dice and got: {{string.numeric(1, {"allowLeadingZeros": false})}}') // 'I rolled the dice and got: 6'
IMO we should maybe just use another new example.
For context: this PR changed the default to `true`, so it doesn't make anymore sense to use `, {"allowLeadingZeros": false}`

2022-11-28 19:31 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.fake('I rolled the dice and got: {{string.numeric(1, {"allowLeadingZeros": false})}}') // 'I rolled the dice and got: 6'
IMO the example makes sense, because most dices don't have a `0` on them.

2022-11-29 02:50 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +   * faker.helpers.fake('I rolled the dice and got: {{string.numeric(1, {"allowLeadingZeros": false})}}') // 'I rolled the dice and got: 6'
most dice also don't have 7 8 and 9 on them :D

I think the main thing is to show how to pass a options object inline

How about
    faker.helpers.fake('Your PIN number is : {{string.numeric(4, {"exclude": ["0"]})}}') // 'Your PIN number is 4834'

2022-12-03 20:13 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.fake('Your PIN number is : {{string.numeric(4, {"exclude": ["0"]})}}') // 'Your PIN number is 4834'
```suggestion
   * faker.helpers.fake('Your PIN number is: {{string.numeric(4, {"exclude": ["0"]})}}') // 'Your PIN number is: 4834'
```

2022-12-05 16:20 UTC, ST-DDT approved these changes

2022-12-05 17:07 UTC, matthewmayer approved these changes

2022-12-05 20:22 UTC, Shinigami92 approved these changes

2022-12-06 23:13 UTC, merged

2022-12-07 00:06 UTC, ST-DDT commented
@import-brain Looking at the now failing PRs, it looks like we missed some tests.