docs(readme.md): add repository badges
faker-js/faker pull request #161
Opened 2022-01-15 21:06 UTC by fncolon

- provides short information in badges
- clickable badge to opencollective

2022-01-15 21:09 UTC, Shinigami92 approved these changes
NICE

2022-01-15 21:39 UTC, import-brain approved these changes

2022-01-15 22:00 UTC, prisis approved these changes

2022-01-15 22:37 UTC, damienwebdev requested changes

2022-01-15 22:37 UTC, damienwebdev commented on README.md
> +[![contributors](https://img.shields.io/github/contributors/faker-js/faker)](https://github.com/faker-js/faker/graphs/contributors)
Contributors is already a built-in feature of Github, I think we can remove this.

2022-01-15 22:37 UTC, damienwebdev commented on README.md
> +[![Merged PRs](https://badgen.net/github/merged-prs/faker-js/faker)](https://github.com/faker-js/faker)
I don't think a merged PR count is particularly useful.

2022-01-15 22:37 UTC, damienwebdev commented on README.md
> +[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)
License is already a built-in feature of Github, I think we can remove this.

2022-01-16 04:10 UTC, Shinigami92 commented
@damienwebdev you are missing that this will also rendered on npm package site!
So I would use the contributors and license badge.
Also the PR badge shows a healthy activity, at least for now.
We could remove the PR counter when we reached 500+ PRs 🙂

2022-01-19 05:35 UTC, bl0cknumber commented
> @damienwebdev you are missing that this will also rendered on npm package site! So I would use the contributors and license badge. Also the PR badge shows a healthy activity, at least for now. We could remove the PR counter when we reached 500+ PRs 🙂

Which one I should follow? your suggestion or @damienwebdev? or currently we stale it first?

2022-01-19 07:12 UTC, prisis commented
For me only Merged PRs and contributors can be removed, license should be there for npm

2022-01-19 07:37 UTC, Shinigami92 commented
> For me only Merged PRs and contributors can be removed, license should be there for npm

Maybe we should just link it to the license file 
Many repos do it that way

2022-01-19 18:49 UTC, bl0cknumber commented
Do we follow major consensus vote to remove merged PRs and contributors?

2022-01-19 19:24 UTC, damienwebdev commented
> Do we follow major consensus vote to remove merged PRs and contributors?

We decided to move this change to v6.1.0, but I still want to outline a conversation that @Shinigami92 and I had in Discord:

1. We don't need the LICENSE badge, we have it built-in on both NPM and Github.
2. PR Merge count isn't a great ref to project stability, so it should be removed.
3. Contributors should be removed.

The rest seem good.

2022-01-19 19:24 UTC, damienwebdev requested changes

2022-01-19 19:24 UTC, damienwebdev commented on README.md
> +  [![Continuous Integration](https://github.com/faker-js/faker/actions/workflows/ci.yml/badge.svg)](https://github.com/faker-js/faker/actions/workflows/ci.yml)
This is a duplicate.

2022-01-19 19:24 UTC, damienwebdev commented on README.md
> +  [![Chat on Discord](https://img.shields.io/discord/929487054990110771)](https://discord.com/invite/4qDjAmDj4P)
This is a duplicate.

2022-01-20 02:32 UTC, bl0cknumber commented
> > Do we follow major consensus vote to remove merged PRs and contributors?
> 
> We decided to move this change to v6.1.0, but I still want to outline a conversation that @Shinigami92 and I had in Discord:
> 
> 1. We don't need the LICENSE badge, we have it built-in on both NPM and Github.
> 2. PR Merge count isn't a great ref to project stability, so it should be removed.
> 3. Contributors should be removed.
> 
> The rest seem good.

Cool, resolving, thanks @damienwebdev and @Shinigami92 😃

2022-01-20 05:42 UTC, Shinigami92 approved these changes

2022-01-20 13:15 UTC, damienwebdev approved these changes
Lgtm

2022-01-20 13:19 UTC, merged

2022-09-03 03:08 UTC, 1LISA2 commented
![images](https://user-images.githubusercontent.com/103248540/188253592-bde3b932-1593-444f-a369-44b1bcdd45a1.jpeg)
![images (1)](https://user-images.githubusercontent.com/103248540/188253594-1285635a-3737-4483-8846-71f4482ea2df.jpeg)

2022-09-03 03:09 UTC, 1LISA2 commented
![images](https://user-images.githubusercontent.com/103248540/188253635-a2e406ff-29b5-404a-8443-41aec1b148f3.jpeg)