docs: Display actual deprecation method in docs
faker-js/faker pull request #1611
Opened 2022-11-27 10:42 UTC by matthewmayer

fix #1607

2022-11-27 11:15 UTC, Shinigami92 commented
You need to run `pnpm run format` or format the touched files with prettier

2022-11-27 11:55 UTC, ST-DDT requested changes

2022-11-27 11:55 UTC, ST-DDT commented on docs/.vitepress/components/api-docs/method.ts
> +  readonly deprecatedMessage: string;
Since we only deprecate with a message you can remove the boolean.

2022-11-27 11:55 UTC, ST-DDT commented on scripts/apidoc/utils.ts
> + * Extracts the content of the deprecated tag
```suggestion
 * Extracts the content of the `@deprecated` tag.
```

2022-11-27 11:55 UTC, ST-DDT commented on scripts/apidoc/utils.ts
> + * @param signature The signature to check.
```suggestion
 * @param signature The signature to extract it from.
```

2022-11-27 11:55 UTC, ST-DDT commented on scripts/apidoc/utils.ts
> +  return extractTagContent('@deprecated', signature).join().trim();
Maybe only return a string if the method is actually deprecated?
Otherwise return undefined.

2022-11-27 11:55 UTC, ST-DDT commented on scripts/apidoc/utils.ts
> + * @returns the contents of the deprecated tag
AFAICT the other methods dont have a return tag and IMO it doesnt add much value to the jsdocs in this case.

2022-11-27 12:06 UTC, matthewmayer commented on scripts/apidoc/utils.ts
> + * Extracts the content of the deprecated tag
It kept complaining that this method itself was deprecated when I left the @ in 😀

2022-11-27 16:46 UTC, matthewmayer commented on scripts/apidoc/utils.ts
> +  return extractTagContent('@deprecated', signature).join().trim();
switched this to string | undefined

2022-11-27 16:48 UTC, matthewmayer commented on scripts/apidoc/signature.ts
> +    ...(deprecatedMessage && { deprecated: mdToHtml(deprecatedMessage) }),
this is a bit ugly but not sure if there's a nicer way of doing this in JS, basically "if deprecatedMessage is undefined, don't add anything to the dictionary, otherwise add `{deprecated: mdToHtml(deprecatedMessage) }`

2022-11-27 18:17 UTC, ST-DDT commented on scripts/apidoc/signature.ts
> +    ...(deprecatedMessage && { deprecated: mdToHtml(deprecatedMessage) }),
As an alternative you could use:

````ts
let deprecated = extractDeprecated(signature);
if (deprecated) {
  deprecated = mdToHtml(deprecated);
}
````

Or change `mdToHtml` to return instantly if the input is undefined.

2022-11-27 18:25 UTC, ST-DDT requested changes

2022-11-27 18:25 UTC, ST-DDT commented on scripts/apidoc/utils.ts
> +  return deprecated.length === 0 ? undefined : deprecated;
```suggestion
  const deprecated = extractTagContent('@deprecated', signature);
  return deprecated.length === 0 ? undefined : deprecated.join().trim();
```

2022-11-27 18:25 UTC, ST-DDT commented on test/scripts/apidoc/__snapshots__/signature.spec.ts.snap
> -  "deprecated": true,
This method should be marked as deprecated.

2022-11-28 02:32 UTC, matthewmayer commented on test/scripts/apidoc/__snapshots__/signature.spec.ts.snap
> -  "deprecated": true,
hmm the problem is this method is marked as deprecated in the JSDoc but with an empty message (which is impossible in reality because that will fail the test that all @deprecated markers need a message).

2022-11-28 19:28 UTC, ST-DDT commented on test/scripts/apidoc/__snapshots__/signature.spec.ts.snap
> -  "deprecated": true,
It is impossible, then fix/merge the example?

2022-11-29 02:47 UTC, matthewmayer commented on test/scripts/apidoc/__snapshots__/signature.spec.ts.snap
> -  "deprecated": true,
having thought about this a bit more, I think it might actually be better to revert back to boolean and (optional string) for deprecated. I think it makes it clearer the difference between a @deprecated with and without message

So in Method.ts you would have

deprecated:Boolean
deprecatedMessage:string | undefined 

(undefined if deprecated is false, empty string if deprecated is true but message is empty)

2022-11-29 17:21 UTC, matthewmayer commented
going to rethink this

2022-11-29 17:21 UTC, closed without merging