Docs  improving readability of UUID string
faker-js/faker pull request #1622
Opened 2022-12-01 01:22 UTC by Kcops11

Updated comment to be more closely in line with semantic style guide.

2022-12-02 15:24 UTC, ST-DDT requested changes
Sorry for the late response.
We looked over this, and sadly we feel that this is not what the issue is about.

The issue is about the actual implementation of the method using bit operations as described here:
https://github.com/faker-js/faker/issues/1466#issue-1412189473
In [this comment](https://github.com/faker-js/faker/issues/1466#issuecomment-1281505929) we opted for adding a comment to the implementation explaining what the nit magic actually does, so that a future reader knows exactly what happens.

As for the additions to the jsdocs.
Most of the added docs don't add relevant information for the user.
Except for the first sentence that it "is randomly generated".

Please revert the other documentation additions and add a comment to the bit operations in the implementation (don't refer to bits, only values/value ranges).

2022-12-02 19:56 UTC, Kcops11 commented
Okay, I will make changes and get back to you.

2022-12-07 03:36 UTC, Kcops11 commented
I have updated the code with a comment and removed most of the doc comment I previously added. Please let me know if you would like me to make any additional changes or if my changes do not reflect what you are looking for.

2022-12-07 09:54 UTC, ST-DDT commented on src/modules/string/index.ts
> +      //x value is set to any random hex and y value is set to random within {8, 9, A, B}
```suggestion
      // 'x's are set to any random hex and 'y's are set to a random value within {8, 9, a, b}
```

2022-12-07 18:15 UTC, Shinigami92 commented on src/modules/string/index.ts
> +   * A version 4 UUID is randomly generated.
I think this is obvious and not needed.

The PR should aim to just add a comment to the body of the function, not the JSDoc itself

2022-12-07 18:15 UTC, Shinigami92 commented on src/modules/string/index.ts
> +      // 'x's are set to any random hex and 'y's are set to a random value within {8, 9, a, b}
Somehow I find this not explicit enough
Maybe something like

```
// `x`'s will be replaced with random hex characters and the `y` will be replaced with `8`, `9`, `a` or `b`
```

but additionally maybe we need also a **how** and **why** :thinking: 
especially the bit-and and bit-or should be explained

2022-12-08 00:04 UTC, Kcops11 commented on src/modules/string/index.ts
> +   * A version 4 UUID is randomly generated.
Okay I will remove it

2022-12-08 00:06 UTC, Kcops11 commented on src/modules/string/index.ts
> +      // 'x's are set to any random hex and 'y's are set to a random value within {8, 9, a, b}
I was told to avoid talking about the bits, but if you would like me to add something to that effect I can do so.

2022-12-08 00:41 UTC, ST-DDT commented on src/modules/string/index.ts
> +   * A version 4 UUID is randomly generated.
IMO that adds useful information.

2022-12-08 00:56 UTC, ST-DDT commented on src/modules/string/index.ts
> +      // 'x's are set to any random hex and 'y's are set to a random value within {8, 9, a, b}
I'm a bit conflicted here @Shinigami92.
On one hand you dont want to mention that the uuid v4 is random in the description, but then here you want a lot of details.
IMO the why is perfectly clear aka the RFC that is mentioned three lines above this line requires a special character/subset for that place.

Why: Because the RFC_xyz states so.
Where: At the location the rfc specifies.
What: Thats what the comment needs to clarify and does IMO.
How: Using the string replace that you are in and refering to in the comment

IMO we can expect the user/dev to actually read the few lines sourounding that method, because if they dont there is no need to write a comment in the first place.

I'm fine with the rephrasing.

2022-12-08 00:57 UTC, ST-DDT approved these changes

2022-12-08 08:05 UTC, Shinigami92 commented on src/modules/string/index.ts
> +      // 'x's are set to any random hex and 'y's are set to a random value within {8, 9, a, b}
@ST-DDT @Kcops11 Okay let me explain again from the start
The initial issue https://github.com/faker-js/faker/issues/1466#issue-1412189473 was about the bit operations

<img width="666" alt="image" src="https://user-images.githubusercontent.com/7195563/206391536-1cee22d6-3d8d-4a90-82a9-c99e705a0cce.png">

After a meeting, we came to the conclusion that we actually do not want to get rid of it by replacing it with e.g. code we already use for finance iban, like:
```ts
    return [
      this.faker.string.numeric(8),
      this.faker.string.numeric(4),
      `4${this.faker.string.numeric(3)}`,
      `${this.faker.helpers.arrayElement([
        '8',
        '9',
        'a',
        'b',
      ])}${this.faker.string.numeric(3)}`,
      this.faker.string.numeric(12),
    ].join('-')
```
but leave the bit operator as is

But now for other contributors we need a developer to developer comment to explain what's going on and why the bit operations are better (or whatever why it is there)

This comment has nothing to do with a JSDoc facing to users of faker at all

2022-12-08 08:07 UTC, Shinigami92 commented on src/modules/string/index.ts
> +   * A version 4 UUID is randomly generated.
1. Everything in faker is randomly generated
2. `Returns a UUID v4` and the next sentence is `A version 4 UUID [...]`
   IMO this is redundant 🤷

2022-12-08 08:44 UTC, ST-DDT commented on src/modules/string/index.ts
> +   * A version 4 UUID is randomly generated.
> Everything in faker is randomly generated

The comment refers not to a Faker property, but a property of the uuid v4.
Some uuids are generated time based, or system based. This method returns random generated Uuids.
Sure, I could get that information from visiting the link, but that addition sums up the relevant information unless you really want to know in depth about uuids.

> Returns a UUID v4 and the next sentence is A version 4 UUID [...]
IMO this is redundant 🤷

Sure, do you have a suggestion on how to rephrase it/merge it into a single sentence.

2022-12-08 08:57 UTC, Shinigami92 commented on src/modules/string/index.ts
> +   * A version 4 UUID is randomly generated.
Oh the point that I mis-interpreted the intent of the JSDoc description shows that it is phrased wrongly.
So yeah, revert or rephrase it.
For now I will let @Kcops11 think about it to come up with an idea.

2022-12-08 09:50 UTC, ST-DDT commented on src/modules/string/index.ts
> +      // 'x's are set to any random hex and 'y's are set to a random value within {8, 9, a, b}
> to explain what's going on

IMO that it perfectly clear from the comment+context

>  and why the bit operations are better (or whatever why it is there)

They aren't. That's just how it is implemented. The comment explains what it does.
The difference is only on level of personal preference (which I don't have in this case).

- The performance difference is negligible
  (probably a really minuscule penalty, because it is an additional operation even if extremely fast).
- the bits correlate stronger to the specification, than number ranges would

We could change the impl to this without any issues:

````ts
const replacePlaceholders = (placeholder: string) => placeholder === 'x' 
	? this.faker.number.hex()
	: this.faker.number.hex({ min: 8, max: 11 });
````

We could even do it like this:

````ts
const replacePlaceholders = (placeholder: string) => placeholder === 'y' 
	? this.faker.number.hex({ min: 8, max: 11 })
	: this.faker.string.hexadecimal({ length: placeholder.length, casing: 'lower', prefix: '' });
return RFC4122_TEMPLATE.replace(/x+|y/g, replacePlaceholders);
````

Or even:

````ts
const replacePlaceholders = (placeholder: string) => placeholder === 'y' 
	? this.faker.number.hex({ min: 8, max: 11 })
	: this.faker.number.hex(16 ** placeholder.length);
return RFC4122_TEMPLATE.replace(/x+|y/g, replacePlaceholders);
````

(neither tested)

FYI: `y` contains the UUID variant (not version).

2022-12-08 10:16 UTC, Shinigami92 commented on src/modules/string/index.ts
> +      // 'x's are set to any random hex and 'y's are set to a random value within {8, 9, a, b}
All these suggestions are more welcome from my side, to replace this bit operations
Then after that, we can even toggle on https://eslint.org/docs/latest/rules/no-bitwise

2022-12-08 10:47 UTC, ST-DDT commented on src/modules/string/index.ts
> +      // 'x's are set to any random hex and 'y's are set to a random value within {8, 9, a, b}
I think the first of my suggestions is the easiest to read. @faker-js/members any preferences?

2022-12-20 22:52 UTC, Kcops11 commented
Hello @ST-DDT and @Shinigami92. I coming back to this after finishing my finals. Has a consensus been reached amongst the two of you as to the direction this should be taken?

It would seem as though this is it: https://github.com/faker-js/faker/pull/1622#discussion_r1043213403. Let me know!

2022-12-22 09:48 UTC, xDivisionByZerox commented
> Hello @ST-DDT and @Shinigami92. I coming back to this after finishing my finals. Has a consensus been reached between you regarding the direction this should take?
> 
> It would seem as though this is it: [#1622 (comment)](https://github.com/faker-js/faker/pull/1622#discussion_r1043213403). Let me know!

While I'm neither of them I think [the approach](https://github.com/faker-js/faker/pull/1622#discussion_r1043213403) from @ST-DDT is our best shot here.
- It improves readability (the main goal of this PR)
- has negligible performance influence
- allows us to activate the [no-bitwise](https://eslint.org/docs/latest/rules/no-bitwise) eslint rule in error mode

2022-12-27 00:10 UTC, ST-DDT requested changes

2022-12-27 00:10 UTC, ST-DDT commented on src/modules/string/index.ts
>      const replacePlaceholders = (placeholder: string) => {
Please use this instead:

````ts
const replacePlaceholders = (placeholder: string) => placeholder === 'x' 
	? this.faker.number.hex()
	: this.faker.number.hex({ min: 8, max: 11 });
````

2022-12-27 00:29 UTC, Kcops11 commented on src/modules/string/index.ts
>      const replacePlaceholders = (placeholder: string) => {
All right, I will get started on this soon!

2022-12-27 23:17 UTC, Kcops11 commented on src/modules/string/index.ts
>      const replacePlaceholders = (placeholder: string) => {
Forgive my ignorance but if I make the first suggested change, would this need additional testing? It seems to be implied that it would not.

2022-12-28 08:45 UTC, ST-DDT commented on src/modules/string/index.ts
>      const replacePlaceholders = (placeholder: string) => {
There are already tests in place that ensure that the method works as expected.
The suggested change should still fulfill the tests and shluldnt change the tests.

2023-01-02 23:09 UTC, Kcops11 commented on src/modules/string/index.ts
>      const replacePlaceholders = (placeholder: string) => {
With this change, the comment I added previously is also removed, correct?

2023-01-02 23:12 UTC, Kcops11 commented on src/modules/string/index.ts
>      const replacePlaceholders = (placeholder: string) => {
Further question I would leave the return statement in correct?

This is what I am thinking for the change 

`
  /**
   * Returns a UUID v4 ([Universally Unique Identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier)).
   *
   * UUID v4 (randomly generated : https://www.rfc-editor.org/rfc/rfc4122#section-3)
   *
   * @example
   * faker.string.uuid() // '4136cd0b-d90b-4af7-b485-5d1ded8db252'
   *
   * @since 8.0.0
   */
  uuid(): string {
    const RFC4122_TEMPLATE = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx';
    const replacePlaceholders = (placeholder: string) => placeholder === 'x' 
	          ? this.faker.number.hex()
	          : this.faker.number.hex({ min: 8, max: 11 });

    return RFC4122_TEMPLATE.replace(/[xy]/g, replacePlaceholders);
  }
  `

2023-01-05 23:30 UTC, ST-DDT commented on src/modules/string/index.ts
>      const replacePlaceholders = (placeholder: string) => {
Looks good to me.

2023-01-06 02:00 UTC, Kcops11 commented
Okay, I have made changes to the method, taking into consideration all of the feedback from the various development team members that have commented here. 

Please let me know if anything needs to be put in the right place or if any additional changes need to be made.

2023-01-06 09:33 UTC, ST-DDT commented on src/modules/string/index.ts
> +   * UUID v4 (randomly generated; https://www.rfc-editor.org/rfc/rfc4122#section-3)
This looks too much like the first line, maybe omit it for now and if we have a better idea, then we can add it later.

2023-01-06 17:41 UTC, Kcops11 commented on src/modules/string/index.ts
> +   * UUID v4 (randomly generated; https://www.rfc-editor.org/rfc/rfc4122#section-3)
Okay, ill remove it!

2023-01-13 13:18 UTC, ST-DDT commented on src/modules/string/index.ts
> +   *
Please remove the redundant empty lines here (keep only one).

2023-01-19 00:28 UTC, Kcops11 commented on src/modules/string/index.ts
> +   *
Sure can do, ill take care of that now

2023-01-19 01:20 UTC, ST-DDT approved these changes, later dismissed

2023-01-19 01:22 UTC, ST-DDT commented
@Kcops11 Is this PR ready for review? (Because currently it is marked as draft)
IMO it is.

2023-01-19 08:20 UTC, Shinigami92 reviewed
There are lint and snapshot errors

2023-01-24 00:16 UTC, Kcops11 commented
> @Kcops11 Is this PR ready for review? (Because currently it is marked as draft) IMO it is.

It should be. 

> There are lint and snapshot errors

As for this, I am trying to figure out what to do about that. Tests are failing for things I haven't touched. If there is a way to fix this, let me know, but I have seen a lot of your tests failing before and then passing the next time someone approved the tests to run.

2023-01-24 00:31 UTC, Kcops11 commented
I have attempted to fix some of the formatting errors pointed out by Prettier. Ill try fixing any additional errors after I have successfully handled the formatting.

2023-01-24 10:08 UTC, xDivisionByZerox commented
> I have attempted to fix some of the formatting errors pointed out by Prettier. Ill try fixing any additional errors after I have successfully handled the formatting.

It seems like you are fixing those errors on your own...
To fix formatting errors simply run `npm run format`
To fix the failing snapshot test simply run `npx vitest -u` (`-u` updates the snapshots)

2023-02-04 00:50 UTC, ST-DDT approved these changes, later dismissed

2023-02-05 08:42 UTC, matthewmayer requested changes
I'm not sure this is that much readable than the original version.

I think a comment would be helpful, maybe:

```
Each x in the template is replaced with a random hex digit from `0` to `f`, and y is replaced with a random hex digit from the range `{8, 9, a, b}` only.
```

Also could consider
- Writing "11" as 0xb instead
- splitting replacePlaceholders into two seperate functions, one for replacing the x's and one for replacing the y's?

2023-02-07 00:04 UTC, ST-DDT commented
@matthewmayer Like this? (Prettier gives me a hard time to format this in a readable way)

````ts
  uuid(): string {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'
      .replace(/x/g, () => this.faker.number.hex({ min: 0x0, max: 0xf }))
      .replace(/y/g, () => this.faker.number.hex({ min: 0x8, max: 0xb }));
  }
````

I'm not sure about using the hex notation for `min`.

2023-02-07 00:55 UTC, matthewmayer commented
Yeah that seems much more readable to me.

2023-02-07 00:59 UTC, matthewmayer commented
Sometimes I think writing more code makes it easier to read. 

Like, adding the explicit min and max for the x replacement isn't necessary but makes it easier to understand, because you don't need to go check what the result parameter values are for hex() to understand the line of code. And it also makes it easier to see the difference between that line and the line below.

2023-02-07 23:27 UTC, ST-DDT approved these changes

2023-02-08 00:03 UTC, matthewmayer approved these changes

2023-02-08 09:51 UTC, Shinigami92 approved these changes

2023-02-10 20:06 UTC, xDivisionByZerox approved these changes

2023-02-11 11:36 UTC, merged