feat(documentation): Add a documentation page for how to use faker with testing frameworks #1324
faker-js/faker pull request #1623
Opened 2022-12-01 04:04 UTC by brenno263

Add a documentation page about integrating with testing frameworks.

I sort of wish I had more to add besides examples, but Faker is pretty straightforward to use. There were a number of quirks to document with frameworks, but at the time of writing everything significant has been smoothed over to my knowledge.

Please let me know if there's anything I should add.

2022-12-01 11:28 UTC, ST-DDT commented
Please fix the merge conflicts.

2022-12-02 10:04 UTC, ST-DDT reviewed
Could you also add hints regarding faker.seed and test snapshots?

2022-12-02 10:04 UTC, ST-DDT commented on docs/guide/frameworks.md
> +import { faker } from '@faker-js/faker/locale/en';
Could you please add a small hint at the top you why use locale/en as an import?
Maybe include a link to the localization page as well.

e.g.

> These examples only use the `en` variants for better performance. If you want to know more visit `localization`.

2022-12-02 10:04 UTC, ST-DDT commented on docs/guide/frameworks.md
> +test('reverse array', () => {
In this repo we mainly use describe/it, should we use it here as well?
Is there a recommendation what to use in the vitest tests?

2022-12-02 10:04 UTC, ST-DDT commented on docs/guide/frameworks.md
> +  assert.deepEqual(array.reverse(), [animal, name, title]);
Same here. We mainly use `except`.

2022-12-02 10:04 UTC, ST-DDT commented on docs/guide/frameworks.md
> +    console.log('1', array);
I think this line is obsolete.

2022-12-02 10:04 UTC, ST-DDT commented on docs/guide/frameworks.md
> +    cy.get('#password-input').type(password);
Is the `login` click missing here?

2022-12-02 10:04 UTC, ST-DDT commented on docs/guide/frameworks.md
> +Cypress works too:
```suggestion
[Cypress](https://www.cypress.io/) works too:
```

2022-12-02 10:04 UTC, ST-DDT commented on docs/guide/frameworks.md
> +Faker works about exactly as you would expect with Vitest. Here's a minimal example:
```suggestion
Faker works about exactly as you would expect with [Vitest](https://vitest.dev/). Here's a minimal example:
```

2022-12-02 10:04 UTC, ST-DDT commented on docs/guide/frameworks.md
> +Jest integrates similarly:
```suggestion
[Jest](https://jestjs.io/) integrates similarly:
```

2022-12-02 10:04 UTC, ST-DDT commented on docs/guide/frameworks.md
> +Faker can easily be used with a variety of testing frameworks. Here are a few examples with popular frameworks, as well as some edge cases you should be aware of.
Which edge cases?

2022-12-05 01:40 UTC, brenno263 commented on docs/guide/frameworks.md
> +test('reverse array', () => {
Vitest's docs are pretty unopinionated. I looked into describe/it though and I do like the descriptiveness, so I went ahead with describe/it.

I didn't know this syntax was available with Vite, just Jest, so now the two snippets are identical. I left a note about that and left it as is, would you like them combined into a 'Vitest & Jest' section?

2022-12-05 07:36 UTC, Shinigami92 requested changes

2022-12-05 07:36 UTC, Shinigami92 commented on docs/guide/frameworks.md
> +    faker.seed();
It is bad practice to set something like this at the end of a test, because if something within the test before failed, this code will never be reached and then the seed it still set to what it was in line at the start.

Instead use e.g. `beforeEach` or `afterEach` to clean stuff up.

2022-12-05 10:00 UTC, ST-DDT requested changes

2022-12-05 10:00 UTC, ST-DDT commented on docs/guide/frameworks.md
> +  it('should create an account with username and password', function () {
Is it possible to use lambda expressions here as well? e.g. `() => {}`

2022-12-05 10:00 UTC, ST-DDT commented on docs/guide/frameworks.md
> +Since it uses similar notation, [Jest's](https://jestjs.io/) integration looks exactly the same:
@faker-js/maintainers , @faker-js/members Should this be phrased to be independent of vitest?

2022-12-05 10:00 UTC, ST-DDT commented on docs/guide/frameworks.md
> +import { faker } from '@faker-js/faker/locale/en';
Please add the Cypress imports (if needed).

2022-12-05 10:00 UTC, ST-DDT commented on docs/guide/frameworks.md
> +import { faker } from '@faker-js/faker/locale/en';
Please add the Jest imports (if needed).

2022-12-05 10:13 UTC, Shinigami92 commented on docs/guide/frameworks.md
> +  it('should create an account with username and password', function () {
Yes, good catch!

2022-12-05 10:15 UTC, Shinigami92 commented on docs/guide/frameworks.md
> +Since it uses similar notation, [Jest's](https://jestjs.io/) integration looks exactly the same:
Maybe 🤔 

But I think it is a good thing to mention jest explicitly beside vitest as
1. Frameworks like NestJS still depend on jest
2. When searching e.g. via Google, we have one more search-engine hit via combination of jest+faker

2022-12-05 10:16 UTC, Shinigami92 commented on docs/guide/frameworks.md
> +import { faker } from '@faker-js/faker/locale/en';
This is actually correct in most cases
Cypress is normally registered globally within the configured e2e | integration | cypress folder

2022-12-05 10:18 UTC, Shinigami92 commented on docs/guide/frameworks.md
> +import { faker } from '@faker-js/faker/locale/en';
I'm not so sure about that. I think the default for jest is that it is configured globally as well as cypress

Vitest's default it the other way around and you need to set https://vitest.dev/config/#globals explicitly

2022-12-05 10:27 UTC, ST-DDT commented on docs/guide/frameworks.md
> +Since it uses similar notation, [Jest's](https://jestjs.io/) integration looks exactly the same:
Yes, I agree with mentioning it explicitly, I was referring to 

`Since it uses similar notation Jest integration looks exactly the same:`

Which is a back reference to a different test framework.

2022-12-06 00:25 UTC, brenno263 commented on docs/guide/frameworks.md
> +Since it uses similar notation, [Jest's](https://jestjs.io/) integration looks exactly the same:
It could be good to phrase seeding and snapshots in the context of Jest as well. Since these features are nearly identical for both platforms, I think I'll combine them into a single section to reuse the code blocks.

It will still mention both frameworks of course, preserving those sweet search-engine hits.

2022-12-06 08:28 UTC, Shinigami92 approved these changes, later dismissed

2022-12-06 08:52 UTC, ST-DDT commented on docs/guide/frameworks.md
> +These are especially useful in tests that are meant to be deterministic, such as tests.
```suggestion
These are especially useful in tests that are meant to be deterministic, such as tests.
```

IMO there is something missing at the end. I don't remember the name of the tests that require the exact same values/result. Reproducible tests? Gui Tests?

2022-12-06 08:52 UTC, ST-DDT commented on docs/guide/frameworks.md
> +Since [Vitest](https://vitest.dev/) and [Jest](https://jestjs.io/) use an extremely similar notation, this section will cover both at once. All code snippets have been tested in both Vitest and Jest.
Please put each sentence in a new line.

> All code snippets have been tested in both Vitest and Jest.

IMO This doesn't have to be mentioned.

2022-12-06 08:52 UTC, ST-DDT commented on docs/guide/frameworks.md
> +It can sometimes be useful to do seeded tests, where faker will generate the same random value each time.
Maybe add a hint that this is only true within the same version of Faker.

2022-12-06 15:49 UTC, brenno263 commented on docs/guide/frameworks.md
> +These are especially useful in tests that are meant to be deterministic, such as tests.
You're right. I had given 'snapshot tests' as an example, before moving the link to the next line. Fixed.

2022-12-06 16:12 UTC, ST-DDT reviewed
Just some minor nit-picking, other than that this looks good to me.

2022-12-06 16:12 UTC, ST-DDT commented on docs/guide/frameworks.md
> +    // visit the a webpage and create an account.
```suggestion
    // Visit the a webpage and create an account.
```

2022-12-06 16:12 UTC, ST-DDT commented on docs/guide/frameworks.md
> +    //now we try to login with these credentials.
```suggestion
    // Now, we try to login with these credentials.
```

2022-12-06 16:12 UTC, ST-DDT commented on docs/guide/frameworks.md
> +    //we should have logged in successfully to the dashboard page.
```suggestion
    // We should have logged in successfully to the dashboard page.
```

2022-12-06 23:08 UTC, ST-DDT approved these changes

2022-12-07 19:19 UTC, Shinigami92 approved these changes

2022-12-08 20:30 UTC, merged

2022-12-08 20:33 UTC, brenno263 commented
It was a pleasure working with you guys!