docs(index.md): add yarn command in index.md
faker-js/faker pull request #163
Opened 2022-01-15 22:32 UTC by import-brain

This might seem a bit unnecessary, but I think it would be a nice quality-of-life addition for the yarn users out there.

2022-01-15 22:40 UTC, damienwebdev submitted a review, later dismissed
lgtm

2022-01-16 04:14 UTC, Shinigami92 commented
pnpm also gets really popular and I also have all three package managers in my own project docs!
So also add it, all three or only npm or e.g. <packageManager> (but this is not copy-paste-able 👎)

2022-01-16 04:19 UTC, Shinigami92 requested changes

2022-01-16 04:19 UTC, Shinigami92 commented on docs/guide/index.md
> +```
````suggestion

or

```shell
yarn add @faker-js/faker --dev
```

or

```shell
pnpm add @faker-js/faker --save-dev
```
````

2022-01-16 04:59 UTC, Shinigami92 approved these changes

2022-01-16 04:59 UTC, import-brain commented
@Shinigami92 Wow, until you mentioned it, I have never heard of pnpm.

Also, I can copy-paste the commands in the code blocks to my terminal just fine, what do you mean by "this is not copy-paste-able"?

2022-01-16 05:01 UTC, Shinigami92 commented
> Also, I can copy-paste the commands in the code blocks to my terminal just fine, what do you mean by "this is not copy-paste-able"?

I just mean when we would write `<packageManager> add ...`

2022-01-16 05:02 UTC, import-brain commented
> > Also, I can copy-paste the commands in the code blocks to my terminal just fine, what do you mean by "this is not copy-paste-able"?
> 
> I just mean when we would write `<packageManager> add ...`

Oh, I see what you mean, thanks for the clarification.

2022-01-16 06:13 UTC, fncolon commented
I'm not reviewer, but I think you should sync the installation guide in README too.

2022-01-16 16:36 UTC, Shinigami92 approved these changes

2022-01-17 01:25 UTC, clarkerican approved these changes

2022-01-17 01:25 UTC, merged