fix(person): change fullName to use name patterns
faker-js/faker pull request #1637
Opened 2022-12-06 14:39 UTC by matthewmayer

2022-12-06 23:32 UTC, ST-DDT commented on src/modules/person/index.ts
> +      'person.last_name': () => options.lastName || this.lastName(sex),
I prefer using the method notation here e.g. `'person.firstName'` since this effectively does exactly that.

2022-12-07 01:32 UTC, matthewmayer commented on src/locales/en/person/name.ts
> +  ...Array(7).fill('{{person.first_name}} {{person.last_name}}'), //70% of the time we want a first and last name
@ST-DDT any thoughts on a smarter way we could achieve this without duplicates in the array?

2022-12-07 09:29 UTC, ST-DDT commented on src/locales/en/person/name.ts
> +  ...Array(7).fill('{{person.first_name}} {{person.last_name}}'), //70% of the time we want a first and last name
Introduce a new helper method: `weightedArrayElement`
We already considered it before, but didn't have time for that yet.

2022-12-07 11:38 UTC, matthewmayer commented
I have added a new helper function `faker.helpers.weightedArrayElement` as suggested. 

I converted the existing name patterns to use weights (roughly, I tried to have prefixes/suffixes on 10-20% of the names only, people who know the locales better could tweak this later.)

2022-12-09 13:39 UTC, ST-DDT commented
> I have added a new helper function `faker.helpers.weightedArrayElement` as suggested.

Could you please move that to a separate PR? This is getting harder and harder to review.

2022-12-10 10:40 UTC, matthewmayer commented
I will change this back to draft for now and split into some smaller PRs

2022-12-18 05:08 UTC, matthewmayer commented
Note i will redo a simplified version of this PR once #1654 and #1665 have been merged.

One thing i was thinking, person/name.ts is not the most descriptive name. Maybe this could be modified to `person/name_patterns.ts` or `person/full_name_patterns.ts` as part of this PR?

2022-12-18 07:47 UTC, ST-DDT commented
> One thing i was thinking, person/name.ts is not the most descriptive name. Maybe this could be modified to `person/name_patterns.ts` or `person/full_name_patterns.ts` as part of this PR?

You are right. We also considered renaming other pattern files such as location street and city pattern files.

2022-12-18 16:06 UTC, matthewmayer commented
sure, it can wait until a later PR.

2023-01-02 17:24 UTC, matthewmayer commented
now that https://github.com/faker-js/faker/pull/1654 has landed i have updated this PR to use the new method.

2023-01-02 17:26 UTC, matthewmayer commented on src/locales/en/person/name.ts
> +  { value: '{{person.first_name}} {{person.last_name}}', weight: 49 },
note these rather arbitrary numbers are to reproduce the current behavior of fullName in `en`:

1/8 of the time a prefix is added
1/8 of the time a suffix is added

Thus in every 64 names, 1 gets both, 7 get suffix, 7 get prefix, and 49 get neither

2023-01-03 07:59 UTC, Shinigami92 commented on src/locales/en/person/name.ts
> +  { value: '{{person.first_name}} {{person.last_name}}', weight: 49 },
Should we add this as an inline comment instead of here a comment on GitHub?

2023-01-03 10:53 UTC, ST-DDT commented on src/locales/en/person/name.ts
> +  { value: '{{person.first_name}} {{person.last_name}}', weight: 49 },
I don't see a need for it.

2023-01-05 18:49 UTC, ST-DDT requested changes

2023-01-05 18:49 UTC, ST-DDT commented on src/modules/person/index.ts
> +      'person.last_name': () => options.lastName || this.lastName(sex),
Please use the method notation here and in the locales: `'person.firstName'` (for all patterns that get replaced via `mustache`)

2023-01-05 19:04 UTC, matthewmayer commented on src/modules/person/index.ts
> +      'person.last_name': () => options.lastName || this.lastName(sex),
Do we actually need the 'person.' part? Could simplify it by leaving it off.

2023-01-05 23:26 UTC, ST-DDT commented on src/modules/person/index.ts
> +      'person.last_name': () => options.lastName || this.lastName(sex),
"Need": No, but then we couldn't push it through `faker.helpers.fake` anymore.
It makes it a bit more consistent with other patterns.

2023-01-05 23:27 UTC, ST-DDT commented
This also needs a rebase.

2023-01-06 13:54 UTC, ST-DDT commented on src/locales/de/person/name.ts
> +  { value: '{{person.firstName}} {{person.lastName}}', weight: 9 },
What happened with the `nobility_title_prefix` one?

2023-01-06 14:07 UTC, matthewmayer commented on src/locales/de/person/name.ts
> +  { value: '{{person.firstName}} {{person.lastName}}', weight: 9 },
i changed it to use middleName as it was only in one locale.

2023-01-06 16:10 UTC, matthewmayer commented on src/modules/person/index.ts
> +      'person.last_name': () => options.lastName || this.lastName(sex),
done

2023-01-06 22:50 UTC, ST-DDT commented on src/locales/de/person/name.ts
> +  { value: '{{person.firstName}} {{person.lastName}}', weight: 9 },
But this locale doesn't have the middle name one, but has the `nobility_title_prefix` file.

2023-01-07 01:37 UTC, matthewmayer commented on src/locales/de/person/name.ts
> +  { value: '{{person.firstName}} {{person.lastName}}', weight: 9 },
oops that was an oversight. Changed de to work like de_AT

2023-01-07 09:45 UTC, ST-DDT submitted a review, later dismissed

2023-01-10 19:53 UTC, ST-DDT approved these changes, later dismissed

2023-01-23 17:36 UTC, ST-DDT commented
FFR: nl_tussenvoegsel is not gender specific.

2023-01-27 21:45 UTC, xDivisionByZerox commented on src/locales/de/person/female_middle_name.ts
> +export default ['zu', 'von', 'vom', 'von der'];
I don't see how this is "for simplicity". This basically adds a "bug" to the `person.middleName()` function for the locale `de`. Furthermore, by removing the lcoale data, this PR has to be considered a breaking change (due to possible direct access and via `faker.helpers.fake()`).

2023-01-27 22:57 UTC, xDivisionByZerox commented on src/modules/person/index.ts
> +    const sex =
We actually have a rule (sadly not documented so far) to first normalize the `options` to an object (if required) and destruct it afterward and default options while doing so. This makes it easy to see what actually happens with all option parameters.

Could you do that as well here?

2023-01-28 05:01 UTC, matthewmayer commented on src/locales/de/person/female_middle_name.ts
> +export default ['zu', 'von', 'vom', 'von der'];
i reverted the changes to nobility_title_prefix and tusssenvoegsel in de, de_AT and nl. This is probably best addressed instead via the strategy used in #1777 ie move the affixes into the surnames file. But i dont know enough about German to do that personally so can probably be addressed in a seperate follow up PR like #1777

2023-01-28 05:02 UTC, matthewmayer commented on src/modules/person/index.ts
> +    const sex =
dont totally follow, do you have an example from elsewhere in the code

2023-01-28 12:52 UTC, xDivisionByZerox commented on src/modules/person/index.ts
> +    const sex =
Yes, of course, No Problem. Sadly there is no example in the `PersonModule` since its arguments are yet to be standardized according to #1349.

Have a look at the `NumberModule` for example:
Function Signature:
https://github.com/faker-js/faker/blob/86ae8b9d698f5b2c75214b0cfef869122a591001/src/modules/number/index.ts#L41-L58

Handling for the non-object argument (first thing that is done in  the function):
https://github.com/faker-js/faker/blob/86ae8b9d698f5b2c75214b0cfef869122a591001/src/modules/number/index.ts#L59-L61

Destruction and default assignments (directly followed after the argument normalization):
 https://github.com/faker-js/faker/blob/86ae8b9d698f5b2c75214b0cfef869122a591001/src/modules/number/index.ts#L63

2023-01-28 12:56 UTC, xDivisionByZerox commented on src/modules/person/index.ts
> +    const sex =
In the fullName case, this would look like this:
```ts
fullName(options: {...}): string {
  const {
    sex = this.faker.helpers.arrayElement([Sex.Female, Sex.Male]),
    firstName = this.firstName(sex),
    lastName = this.lastName(sex),
  } = options;

  // further implementation
}
```

2023-01-29 20:54 UTC, ST-DDT approved these changes, later dismissed

2023-01-31 18:48 UTC, xDivisionByZerox approved these changes, later dismissed

2023-02-01 16:20 UTC, ST-DDT commented
Could you please fix the new lint error?

2023-02-02 08:02 UTC, ST-DDT approved these changes

2023-02-02 09:13 UTC, xDivisionByZerox approved these changes

2023-02-02 09:28 UTC, Shinigami92 approved these changes

2023-02-02 09:28 UTC, Shinigami92 commented on src/definitions/person.ts
> +  name: { value: string; weight: number }[];
I prefer 
```suggestion
  name: Array<{ value: string; weight: number }>;
```

But we can also turn on an eslint rule for that

2023-02-02 12:56 UTC, merged

2023-02-02 14:03 UTC, matthewmayer commented
Yay! Thanks for all the help with this