fix(image)!: remove lorempixel
faker-js/faker pull request #1641
Opened 2022-12-07 20:46 UTC by Shinigami92

closes #1571

2022-12-07 20:47 UTC, Shinigami92 commented
/ping @matthewmayer please let me know (and approve) if the docs are enough

2022-12-08 00:29 UTC, ST-DDT approved these changes, later dismissed

2022-12-08 02:03 UTC, matthewmayer requested changes

2022-12-08 02:03 UTC, matthewmayer commented on docs/guide/upgrading.md
> +| `faker.image.lorempixum`        | _Removed_                                                         |
i think you mean faker.image.lorempixel?

Maybe "Removed, as the LoremPixel service is no longer available"?

2022-12-08 08:29 UTC, ST-DDT approved these changes

2022-12-09 07:16 UTC, matthewmayer commented
The title of this PR is also incorrect

2022-12-09 11:12 UTC, Shinigami92 commented
> The title of this PR is also incorrect

Thank you @matthewmayer, your reviews are really welcome :heart:

2022-12-10 18:25 UTC, xDivisionByZerox approved these changes

2022-12-10 19:08 UTC, import-brain approved these changes

2022-12-10 19:09 UTC, merged