feat: add new faker.helpers.weightedArrayElement function
faker-js/faker pull request #1654
Opened 2022-12-11 03:36 UTC by matthewmayer

Split from #1637

Adds a new function `faker.helpers.weightedArrayElement` which allows you 
to select a random element from an array, but weighted more to certain 
elements than others. This will be useful for refactoring name patterns, 
where for example you might want to have 

- `FirstName Surname` chosen 90% of the time and
- `FirstName Surname Suffix` chosen 10% of the time

2022-12-11 09:27 UTC, ST-DDT requested changes
I think we should swap the weight and the value (weight first), because the weight is usually much shorter than the value making it easier to spot in longer lists. What do you/the others think?

````ts
[
  [ 5, 'sunny' ],
  [ 4, 'rainy' ],
  [ 1, 'extremely hazardous blizard storm clouds' ]
]
````

````ts
[
  [ 'sunny', 5 ],
  [ 'rainy', 4 ],
  [ 'extremely hazardous blizard storm clouds', 1 ]
]
````

2022-12-11 09:27 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      throw new Error(
Please use FakerError for these errors.

2022-12-11 09:27 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      if (random < current) {
faker.number.int returns inclusive max values, thus you might have to use <=.

2022-12-11 09:27 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    const random = this.faker.number.int({ min: 0, max: total - 1 });
I think some users might want to use it with percentages rather than ratios, so we might want to use float here.

2022-12-11 09:27 UTC, ST-DDT commented on test/helpers.spec.ts
> +    });
Please also add a test using percentages.

2022-12-11 09:27 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([['sunny', 5], ['rainy', 4],['snowy', 1]]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
```suggestion
   * faker.helpers.weightedArrayElement([['sunny', 5], ['rainy', 4], ['snowy', 1]]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
```

Or whatever prettier would produce.

2022-12-11 09:36 UTC, ST-DDT commented
Should we allow weight zero for temporarily disabled or dynamically weighted items or should we expect the user to remove it before passing it to our method?

2022-12-11 11:26 UTC, Shinigami92 requested changes

2022-12-11 11:26 UTC, Shinigami92 commented on test/helpers.spec.ts
> +        it('should throw if the array is empty', () => {
```suggestion
        });

        it('should throw if the array is empty', () => {
```

2022-12-11 11:26 UTC, Shinigami92 commented on test/helpers.spec.ts
> +        it('should throw if any weight is zero', () => {
```suggestion
        });

        it('should throw if any weight is zero', () => {
```

2022-12-11 11:26 UTC, Shinigami92 commented on test/helpers.spec.ts
> +        it('should throw if any weight is negative', () => {
```suggestion
        });

        it('should throw if any weight is negative', () => {
```

2022-12-11 11:26 UTC, Shinigami92 commented on test/helpers.spec.ts
> +      });
The `ReadonlyArray` we are using just indicates that the array passed itself will not be mutated, but not the tuples inside :warning: 

So e.g. it would still be possible to change a value like `array[0][0] = 'override'`

Therefore I would suggest to add a test that freeze the whole array passed to the function and make sure that it doesn't throw

2022-12-11 12:44 UTC, matthewmayer commented on test/helpers.spec.ts
> +      });
One other thing I wasn't sure about how to test that say
```
faker.helpers.weightedArrayElement([["foo",1, "randomextraelement"]])
```
throws?

Because if I write the test in TypeScript it the compiler wont let me do that, but in JS i can obviously pass in a 3rd parameter.

2022-12-11 12:46 UTC, Shinigami92 commented on test/helpers.spec.ts
> +      });
Yeah, you can pass this, but I think we should not throw in that case
It's the same as passing an options object to a function that has an additional unused param

2022-12-11 12:48 UTC, matthewmayer commented
> Should we allow weight zero for temporarily disabled or dynamically weighted items or should we expect the user to remove it before passing it to our method?

i think allowing zeroes causes more confusion, for example what would you expect to happen if your array had three items, all with weight zero?

2022-12-11 12:51 UTC, matthewmayer commented on test/helpers.spec.ts
> +      });
so maybe

```
if (!array.every((elt) => elt.length === 2)) {
      throw new Error(
        'weightedArrayElement expects an array of [value, weight] pairs'
      );
    }
```

should change to
```
if (!array.every((elt) => elt.length >= 2)) {
```

2022-12-11 12:51 UTC, Shinigami92 commented
> > Should we allow weight zero for temporarily disabled or dynamically weighted items or should we expect the user to remove it before passing it to our method?
> 
> i think allowing zeroes causes more confusion, for example what would you expect to happen if your array had three items, all with weight zero?

All have same chance
so 1/3, 1/3 and 1/3

2022-12-11 12:54 UTC, matthewmayer commented
> > > Should we allow weight zero for temporarily disabled or dynamically weighted items or should we expect the user to remove it before passing it to our method?
> > 
> > 
> > i think allowing zeroes causes more confusion, for example what would you expect to happen if your array had three items, all with weight zero?
> 
> All have same chance so 1/3, 1/3 and 1/3

Intuitively yes, but that would require some extra code to deal with that case, which i think adds more complexity and chance for bugs?

2022-12-11 13:45 UTC, matthewmayer commented
I note that `faker.helpers.float` defaults to a precision of 0.01, which means this is biased for small percentages. What's the cleanest way to request the max precision for the random float?

2022-12-11 14:52 UTC, Shinigami92 requested changes

2022-12-11 14:52 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([[5, 'sunny'], [4, 'rainy'], [1, 'snowy']]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
IMO we should switch the values inside the tuples (but first also lets ask @ST-DDT what he thinks)
So we will have `[['sunny', 5], ['rainy', 4], ['snowy', 1]]`

2022-12-11 14:52 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +  weightedArrayElement<T = string>(
I think we should not use a default here, just let TS infer it

2022-12-11 14:52 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +    >
Do we really need this `as unknown as`?

```ts
array: ReadonlyArray<WeightedTuple> = [] // This does not work?
```

On the other side, why even use a default value here? I think we can require it always :thinking: 
Otherwise in line 466 we would throw an error anyway :shrug:

2022-12-11 14:59 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([[5, 'sunny'], [4, 'rainy'], [1, 'snowy']]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
See my reasons here: https://github.com/faker-js/faker/pull/1654#pullrequestreview-1212662634

2022-12-11 15:00 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    >
Yes, there shouldnt be a default.

2022-12-11 15:01 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  weightedArrayElement<T = string>(
I think so too. What was the original intention when adding this?

2022-12-11 15:04 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([[5, 'sunny'], [4, 'rainy'], [1, 'snowy']]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
Interesting, but I must say I would be confused by first using it without reading the manual

2022-12-11 15:09 UTC, ST-DDT commented
> I note that `faker.helpers.float` defaults to a precision of 0.01, which means this is biased for small percentages. What's the cleanest way to request the max precision for the random float?

Maybe open a new issue for that (max precision float)?

2022-12-11 15:18 UTC, ST-DDT commented
> > i think allowing zeroes causes more confusion, for example what would you expect to happen if your array had three items, all with weight zero?
> 
> All have same chance so 1/3, 1/3 and 1/3

While we could technically forward to array element then, I think the usual expectation for zero weight is "dont show up". If everything is weight zero this expectation shouldnt change.
We could treat it as an empty array, but maybe we should just disallow it until someone actually has a need for that.

2022-12-11 15:38 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([[5, 'sunny'], [4, 'rainy'], [1, 'snowy']]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
@JessicaSachs I think you showed a method like this in one of our teammettings. Do you remember where that method was from? Do you have a preference here?

2022-12-11 16:30 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +  weightedArrayElement<T = string>(
sorry my TS is a bit fuzzy, i will need a bit more assistance understanding what i need to change on this line.

2022-12-11 16:30 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +    >
sorry my TS is a bit fuzzy, i will need a bit more assistance understanding what i need to change on this line.

2022-12-11 16:46 UTC, matthewmayer commented
> > > i think allowing zeroes causes more confusion, for example what would you expect to happen if your array had three items, all with weight zero?
> > 
> > 
> > All have same chance so 1/3, 1/3 and 1/3
> 
> While we could technically forward to array element then, I think the usual expectation for zero weight is "dont show up". If everything is weight zero this expectation shouldnt change. We could treat it as an empty array, but maybe we should just disallow it until someone actually has a need for that and then we can discuss the pros and cons in a separate context.

I think "disallow and throw error until someone actually has a use-case for it" is the best approach :)

2022-12-11 17:57 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +  weightedArrayElement<T = string>(
```suggestion
  weightedArrayElement<T>(
```

2022-12-11 17:58 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +    >
```suggestion
    array: ReadonlyArray<[number, T]>
```

2022-12-11 19:11 UTC, ST-DDT commented
Please run the formatter once.

2022-12-11 19:23 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +        'weightedArrayElement expects an array of [value, weight] pairs'
The error message is wrong. (Type needs to bw flipped).

2022-12-11 19:23 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +        'weightedArrayElement expects an array of [value, weight] pairs where weight is a positive number'
Same here.

2022-12-11 19:23 UTC, ST-DDT commented on test/helpers.spec.ts
> +          expect(() => faker.helpers.weightedArrayElement([])).to.throw();
We usually check the actual error. See here for an example:

https://github.com/faker-js/faker/blob/9a1226172fe23aa763c14f5488131373548bba21/test/helpers.spec.ts#L609-L613

2022-12-11 19:23 UTC, ST-DDT commented on test/helpers.spec.ts
> +          ).to.throw();
Same here

2022-12-11 19:23 UTC, ST-DDT commented on test/helpers.spec.ts
> +          ).to.throw();
And here

2022-12-11 19:23 UTC, ST-DDT commented on test/helpers.spec.ts
> +        });
And here

2022-12-11 19:26 UTC, matthewmayer commented on test/helpers.spec.ts
> +        });
We expect it to not throw what 😃

2022-12-11 19:46 UTC, ST-DDT commented on test/helpers.spec.ts
> +        });
Ups, my bad.

2022-12-12 09:32 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([[5, 'sunny'], [4, 'rainy'], [1, 'snowy']]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
> Interesting, but I must say I would be confused by first using it without reading the manual

I searched the internet and also found variants that use two separate arrays, so I think there are many ways to do the same and this is just one like the other. Amd you have to read the example for 1s anyway to know how to use it.

2022-12-12 18:29 UTC, ST-DDT commented on test/helpers.spec.ts
> +    });
Could you please add that test here?

2022-12-13 09:47 UTC, ST-DDT approved these changes, later dismissed

2022-12-13 19:10 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([[5, 'sunny'], [4, 'rainy'], [1, 'snowy']]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
> Also json records/java maps and a lot of other datastructure use key and then value.

I would probably allow a type like `WeightedValue<T> = { value: T; weight: number }` as well. 
This should be more readable over a tuple in a dataset where the value is of type `number`. At least I think so.

2022-12-14 08:21 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([[5, 'sunny'], [4, 'rainy'], [1, 'snowy']]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
This is more verbose, but has the benefit that users can also decide if the want to use `[{value, weight}]` or `[{weight, value}]`

2022-12-14 09:01 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([[5, 'sunny'], [4, 'rainy'], [1, 'snowy']]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
Do you want it exclusively or additionally?

2022-12-14 13:25 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([[5, 'sunny'], [4, 'rainy'], [1, 'snowy']]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
I think allowing additional formats for the weights would be nice, but then we would still need to decide what the best format to use would be when using this method internally like in the full name patterns which I intend to use this for.

2022-12-21 13:18 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([[5, 'sunny'], [4, 'rainy'], [1, 'snowy']]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
Another option could be to make this function internal to start with. Then if we find the selected format is awkward, it's easier to change it without breaking changes.

2022-12-23 20:04 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([[5, 'sunny'], [4, 'rainy'], [1, 'snowy']]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
I'm not a fan of making this internal
I prefer @xDivisionByZerox's solution and I think for now we should even only go with the explicit input
If a faker-user then wants the "short" version, they can just write `[['sunny', 5], ['rainy', 4], ['snowy', 1]].map(x => ({ weigth: x[1], value: x[0] }))` and get what is needed as input

2022-12-24 03:54 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([[5, 'sunny'], [4, 'rainy'], [1, 'snowy']]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
Ok I'll make that change in a few days.

2022-12-24 10:15 UTC, Shinigami92 submitted a review, later dismissed
Reading the tests, I think it was a really good decision to switch to object instead of tuple array
Yes it is more verbose, but by just reading and looking at the code, it is instant more understandable immediately whats going on 👍

2022-12-25 16:28 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * For example, if there are two elements A and B, with weights 1 and 2 respectively, then the probability of picking A is 1/3 and the probability of picking B is 2/3.
Please add a hint that the weight describes the chance of returning that element in relation to the sum/total weight.

2022-12-25 16:28 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    array: ReadonlyArray<{ weight: number; value: T }>
Should we add jsdocs the the nested keys as well? @Shinigami92 has one or two that add them there as well.
https://github.com/faker-js/faker/pull/1644

2022-12-25 16:30 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +    array: ReadonlyArray<{ weight: number; value: T }>
#1644 is not reviewed or merged yet, so I assume it's just important what first get merged into next branch

2022-12-26 09:49 UTC, ST-DDT approved these changes, later dismissed

2022-12-26 11:21 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +    }
I'm unsure if we need to check this, as our general agreement is "we only check, what typescript allows". Also, we are not able to tests this, without making typescript angry.

2022-12-26 11:23 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +    }
Yeah maybe the error message is misleading here
Currently it checks indirectly if any value contains `0` which is a `falsy` value

2022-12-26 12:16 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +    }
> Currently it checks indirectly if any value contains 0 which is a falsy value

I totally missed this. Even more reason to remove this, as `0`, `''`, and/or 'false' should be viable options for `value`

2022-12-26 12:44 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    }
Me too. We should also add a test to ensure falsy values are allowed.

2022-12-26 15:28 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +    }
I removed those lines and added one more test.

2022-12-26 15:30 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * faker.helpers.weightedArrayElement([{ weight: 5, value: 'sunny'}, { weight: 4, value: 'rainy'}, { weight: 1, value: 'snowy'}]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% o
```suggestion
   * faker.helpers.weightedArrayElement([{ weight: 5, value: 'sunny' }, { weight: 4, value: 'rainy' }, { weight: 1, value: 'snowy' }]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
```

2022-12-26 15:30 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +        'weightedArrayElement expects an array of {weight, value} objects where weight is a positive number'
```suggestion
        'weightedArrayElement expects an array of { weight, value } objects where weight is a positive number'
```

2022-12-26 15:30 UTC, Shinigami92 commented on test/helpers.spec.ts
> +              'weightedArrayElement expects an array of {weight, value} objects where weight is a positive number'
```suggestion
              'weightedArrayElement expects an array of { weight, value } objects where weight is a positive number'
```

2022-12-26 15:30 UTC, Shinigami92 commented on test/helpers.spec.ts
> +              'weightedArrayElement expects an array of {weight, value} objects where weight is a positive number'
```suggestion
              'weightedArrayElement expects an array of { weight, value } objects where weight is a positive number'
```

2022-12-26 18:10 UTC, ST-DDT submitted a review, later dismissed

2022-12-29 13:14 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * For example, if there are two values A and B, with weights 1 and 2 respectively, then the probability of picking A is 1/3 and the probability of picking B is 2/3.
<img src="https://user-images.githubusercontent.com/7195563/209955726-878aac13-7378-4cc7-ba39-e25e849a785a.png" width="300px"/>


When hovering over these JSDoc it is very long due to it is rendered as markdown which would need e.g. double-whitespaces at the end to simulate a newline

But instead of doing that and it will get removed by prettier we should maybe use ul-li for this

```suggestion
   * Returns a weighted random element from the given array. Each element of the array should be an object with two keys `weight` and `value`.
   *
   * - Each `weight` key should be a number representing the probability of selecting the value, relative to the sum of the weights. Weights can be any positive float or integer.
   * - Each `value` key should be the corresponding value.
   * 
   * For example, if there are two values A and B, with weights 1 and 2 respectively, then the probability of picking A is 1/3 and the probability of picking B is 2/3.
```

<img src="https://user-images.githubusercontent.com/7195563/209956052-5c7793e9-a15b-41c9-85f0-99a097baa58a.png" width="300px"/>

This makes it much more readable

2022-12-30 09:52 UTC, ST-DDT approved these changes, later dismissed

2022-12-31 00:19 UTC, xDivisionByZerox approved these changes

2022-12-31 00:19 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +    return array[array.length - 1].value;
Can we somehow force this case in a test? I have no idea how sadly.

2022-12-31 00:23 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +    return array[array.length - 1].value;
I could be wrong, but I think because of line 472 and 484-486 it is impossible to reach this code
So it is only more like a fallback to satisfy TypeScript, is it?

2022-12-31 01:26 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +    return array[array.length - 1].value;
https://javascript.plainenglish.io/why-0-1-0-2-0-3-in-javascript-d7e218224a72

Adding floating point numbers in JS is weird

But it's practically not going to happen

2022-12-31 04:23 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +    return array[array.length - 1].value;
Being certain it never happens requires a fairly good understanding of how JS floating point addition works, and the exact implementation of `faker.number.float` so i prefer to have this line as a fail-safe rather than risk returning undefined in certain pathological cases.

2022-12-31 13:55 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +    return array[array.length - 1].value;
> Being certain it never happens requires a fairly good understanding of how JS floating point addition works, and the exact implementation of `faker.number.float` so i prefer to have this line as a fail-safe rather than risk returning undefined in certain pathological cases.

I totally get this and think it's a good way of implementing this. I was just wondering if we could somehow force this to actually prove your statement "look JS float is weird, that's why this is in place". 

I'm more afraid that someone in the future will have the same conclusion as @Shinigami92, remove the fall back, and will then run into a failing test. That's why I was asking for a possible test^^

2022-12-31 13:57 UTC, xDivisionByZerox submitted a review, later dismissed

2022-12-31 17:45 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    return array[array.length - 1].value;
IMO the likelihood of that is low, because we have an explicit comment why it is there.

2022-12-31 17:52 UTC, Shinigami92 approved these changes, later dismissed

2022-12-31 18:21 UTC, ST-DDT commented
The linter now complains about this.

2023-01-01 11:26 UTC, ST-DDT approved these changes

2023-01-01 19:18 UTC, xDivisionByZerox approved these changes

2023-01-02 14:19 UTC, Shinigami92 approved these changes

2023-01-02 14:20 UTC, merged