feat(airline): add airline module
faker-js/faker pull request #1699
Opened 2022-12-30 17:48 UTC by matthewpetro

Added a new module titled 'airline' for generating data pertaining to airlines.

2022-12-30 18:51 UTC, ST-DDT commented on src/locales/en/airline/airport.ts
> +export default [
Please limit the list to 1000 entries.

2022-12-30 18:51 UTC, ST-DDT commented on src/modules/airline/index.ts
> +
```suggestion
```

2022-12-30 18:51 UTC, ST-DDT commented on src/modules/airline/index.ts
> +      aircraftType?: typeof aircraftTypes[number];
Maybe use a proper enum here and also export it as type similar to how we did it with person.SexType.

https://github.com/faker-js/faker/blob/7f7e4428893284efd2df49405e8c98e0eac4b190/src/modules/person/index.ts#L3-L8

2022-12-30 18:51 UTC, ST-DDT commented on src/modules/airline/index.ts
> +    if (!options.allowVisuallySimilarCharacters) {
Please change this to deconstruct this at the beginning of the method to make the default value more obvious:

````ts
const { allowNumerics = false, allowVisuallySimilarCharacters = false } = options;
````

2022-12-30 18:51 UTC, ST-DDT commented on src/modules/airline/index.ts
> +    const visuallySimilarCharacters = ['0', 'O', '1', 'I', 'L'];
Maybe declare them outside of the class as consts.

2022-12-30 18:51 UTC, ST-DDT commented on src/modules/airline/index.ts
> +   * Generates a random record locator.
Please add a wiki or similar link to some extended documentation/definition.

2022-12-31 02:12 UTC, matthewpetro commented on src/locales/en/airline/airport.ts
> +export default [
Done!

2022-12-31 02:12 UTC, matthewpetro commented on src/modules/airline/index.ts
> +      aircraftType?: typeof aircraftTypes[number];
Great suggestion, thanks. I've made the update.

2022-12-31 02:13 UTC, matthewpetro commented on src/modules/airline/index.ts
> +    const visuallySimilarCharacters = ['0', 'O', '1', 'I', 'L'];
Done!

2022-12-31 02:13 UTC, matthewpetro commented on src/modules/airline/index.ts
> +   * Generates a random record locator.
Done!

2022-12-31 02:13 UTC, matthewpetro commented on src/modules/airline/index.ts
> +    if (!options.allowVisuallySimilarCharacters) {
Thanks, that does help with clarity.

2022-12-31 02:47 UTC, import-brain reviewed
Please update the snapshot tests

2022-12-31 10:59 UTC, ST-DDT commented on src/locales/en/airline/airport.ts
> +export default [
Just for future reference: How did you filter these?
By size/importance/random?

2022-12-31 15:51 UTC, matthewpetro commented on src/locales/en/airline/airport.ts
> +export default [
I just randomly pulled them out of OpenFlight's data at https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat

2022-12-31 18:04 UTC, Shinigami92 reviewed
Please rebase and rerun format and fix the lint errors

2022-12-31 18:04 UTC, Shinigami92 commented on README.md
> +| Airline  | `faker.airline.recordLocator()`               | KIFRWE
Lets use `airportCode` instead as example as this is more common and understandable

2022-12-31 18:18 UTC, ST-DDT reviewed
Also please fix the lint error(s).

2022-12-31 18:18 UTC, ST-DDT commented on src/modules/airline/index.ts
> +export type AircraftType = `${Aircraft}`;
Please add a new method that returns a random `AircraftType`:

````ts
aircraftType(): AircraftType {
   return faker.helpers.objectValue(Aircraft);
}
````

(Not tested)

2022-12-31 18:18 UTC, ST-DDT commented on README.md
> +| Airline  | `faker.airline.recordLocator()`               | KIFRWE
Why did you choose this example for the readme?
As an "outsider", I don't know what this is and maybe a seat number is more self explanatory as an example.
What do you think?

2022-12-31 18:18 UTC, ST-DDT commented on src/modules/airline/index.ts
> +   * Generates a random record locator.
Maybe add the link to the top (our other links are also like this). Also maybe add a less technical term for it so it is easier to search on the website.

```suggestion
   * Generates a random [record locator](https://en.wikipedia.org/wiki/Record_locator) (reservation code).
```

What do you think?

2022-12-31 21:41 UTC, matthewpetro commented on README.md
> +| Airline  | `faker.airline.recordLocator()`               | KIFRWE
OK, sounds good.

2022-12-31 21:42 UTC, matthewpetro commented on src/modules/airline/index.ts
> +export type AircraftType = `${Aircraft}`;
Done!

2022-12-31 21:45 UTC, matthewpetro commented on src/modules/airline/index.ts
> +   * Generates a random record locator.
Good suggestion. I added a little more explanatory text as well.

2023-01-01 01:01 UTC, ST-DDT commented on src/modules/airline/index.ts
> +   * faker.airline.aircraftType() // AircraftType.Narrowbody
```suggestion
   * faker.airline.aircraftType() // 'narrowbody'
```

2023-01-01 06:52 UTC, matthewmayer commented
Looks cool.
Would it also be possible to add airlines (e.g. British Airways), codes (BA) and flight numbers (BA123)?

I wonder if `aviation` would be a better name than `airline`?

2023-01-01 08:34 UTC, matthewpetro commented on src/modules/airline/index.ts
> +   * faker.airline.aircraftType() // AircraftType.Narrowbody
Done!

2023-01-01 08:59 UTC, matthewpetro commented
Thanks! It feels more accurate to call the module `airline` since the data relates to things that are specific to airline processes. A name like `aviation` would seem more appropriate for data that relates to the process of flying planes.

Airlines and airline codes are a good addition, but real flight numbers change too often to be a part of Faker. If someone had a use case that required them to have fake flight numbers, they could just generate random numbers in the range(s) they need.

2023-01-01 09:34 UTC, matthewmayer commented
> Thanks! It feels more accurate to call the module `airline` since the data relates to things that are specific to airline processes. A name like `aviation` would seem more appropriate for data that relates to the process of flying planes.
> 
> 


True, another option might be travel I could imagine this expanding to cover other travel related content in future (trains, hotels, car hire)

> 
> Airlines and airline codes are a good addition, but real flight numbers change too often to be a part of Faker. If someone had a use case that required them to have fake flight numbers, they could just generate random numbers in the range(s) they need.

Faker has lots of examples of methods which are basically trivial (say faker.commerce.price) or wrap other methods (like the PNR generation in this PR) but helpful when you are quickly trying to put up a mock up together for a web application in a specific vertical. So if we also add airline codes I think adding in a flight number too by adding a random number would be helpful. 

Could probably add just the most popular 100 airlines in the world, rather than every single one to avoid bloating the data too much.

2023-01-01 17:12 UTC, matthewpetro commented
> > Thanks! It feels more accurate to call the module `airline` since the data relates to things that are specific to airline processes. A name like `aviation` would seem more appropriate for data that relates to the process of flying planes.
> 
> True, another option might be travel I could imagine this expanding to cover other travel related content in future (trains, hotels, car hire)
That sounds good! I'll make that change.
> 
> > Airlines and airline codes are a good addition, but real flight numbers change too often to be a part of Faker. If someone had a use case that required them to have fake flight numbers, they could just generate random numbers in the range(s) they need.
> 
> Faker has lots of examples of methods which are basically trivial (say faker.commerce.price) or wrap other methods (like the PNR generation in this PR) but helpful when you are quickly trying to put up a mock up together for a web application in a specific vertical. So if we also add airline codes I think adding in a flight number too by adding a random number would be helpful.
That's a good point, I'll add that in.
> 
> Could probably add just the most popular 100 airlines in the world, rather than every single one to avoid bloating the data too much.
I'll work on adding airlines as well. I like the idea of adding the most popular airlines as well but it may be impossible to find open-source data that is in a consumable format and includes sortable data like number of passengers carried per year. How important is it for the definition data in Faker to be generated in a scripted and automated way? If it's not that important, I can just build a list of the top 100 airlines by hand based on web searches. If the definition data should be regeneratable via a script, then I could randomly pull 100 airlines out of a dataset that includes all airlines.

Thanks for the feedback!

2023-01-01 17:32 UTC, matthewmayer commented
This might be a good starting point (although it doesn't list the two digit codes)

https://www.flightglobal.com/download?ac=73318

For something like airlines I don't think there is a need to make it scriptable. It's supposed to be an illustrative list for making realistic sample data not a complete list. 

If reasonably big airlines are in the list they are probably less likely to rebrand or go bankrupt over time.

2023-01-01 17:41 UTC, matthewmayer commented
I'll let the maintainers pipe in on the module name too as I'm not a maintainer 😀

2023-01-02 14:22 UTC, Shinigami92 commented
`travel` might be a good name, so we can later also add train or bus data and so on

2023-01-02 14:56 UTC, ST-DDT commented
Do trains, busses and hotels follow some general rules per country?
Trains in Germany do. Busses not so much. Hotels not that I know.

2023-01-02 15:52 UTC, matthewpetro commented
I'm not sure about trains, buses, and hotels. I work for an airline, so have more knowledge in that space than in other travel-related domains.

Would it be safest to keep the module name as `airline` at this time and change it if someone wants to add other travel content in the future?

2023-01-02 16:13 UTC, Shinigami92 commented
> Would it be safest to keep the module name as `airline` at this time and change it if someone wants to add other travel content in the future?

I will leave this decision to @ST-DDT

2023-01-02 16:25 UTC, matthewmayer commented
FWIW faker-ruby recently added a similar module as Travel
https://github.com/faker-ruby/faker/pull/2601

2023-01-02 16:34 UTC, matthewmayer commented
For hotels you could for example have random fake hotel names following certain patterns, random lists of amenities, room types, etc.

2023-01-02 21:19 UTC, ST-DDT commented
> I will leave this decision to @ST-DDT

We will discuss this in our next team meeting as this is something that came up before, but wasn't decided on finally.
(Ref: Submodules + Tree-Shaking; Cloud/AWS)

- faker.travel.airline.airport()
- travel.airline.airport()
- airline.airport()
- airport()

For now, I prefer `faker.airline.x()` as we don't have anything travel related yet.

-------

I do have another question yet though, do you only ever need the airport codes or do you sometimes also need the full name?
E.g. I assume most users don't directly know where `TXL` is and it will probably show up somewhere on the screen anyway.

So should we change the airport method to return an object instead?

````ts
interface Airport {
  name: string;
  code: string;
}
````

Usage: `faker.airline.airport().code`

2023-01-02 21:22 UTC, Shinigami92 commented
Would like to throw in that `...travel.airline...` was never on my "table"
I understand it as a replacement instead of `airline`, so it would be `faker.travel.airport()`

2023-01-02 22:40 UTC, matthewpetro commented
> Would like to throw in that `...travel.airline...` was never on my "table" I understand it as a replacement instead of `airline`, so it would be `faker.travel.airport()`

That was my understanding as well.

For what it's worth, I prefer leaving the module name as `airline` and changing it later if non-airline travel features are added in the future.

2023-01-02 22:46 UTC, matthewpetro commented
> I do have another question yet though, do you only ever need the airport codes or do you sometimes also need the full name? E.g. I assume most users don't directly know where `TXL` is and it will probably show up somewhere on the screen anyway.
> 
> So should we change the airport method to return an object instead?
> 
> ```ts
> interface Airport {
>   name: string;
>   code: string;
> }
> ```
> 
> Usage: `faker.airline.airport().code`
It really depends on the use case. Airport codes are needed for a lot of things (boarding pass barcodes are a prime example), but airport names can also be useful. I like the idea of returning an object with an airport name and code, but I think it would be good to reduce the number of airports in the definition file to just the top 100 airports so that the file isn't too large.

2023-01-03 04:41 UTC, matthewmayer commented
Same for airlines if we add those. Code and name together would be useful.

2023-01-03 12:49 UTC, ST-DDT commented
Yes, yes (please select some airports from around the globe), and yes

2023-01-03 23:57 UTC, ST-DDT requested changes

2023-01-03 23:57 UTC, ST-DDT commented on src/locales/en/airline/airlines.ts
> +// Top 100 airlines in 2019 according to https://www.flightglobal.com/download?ac=73318
Which license applies to the original data?

2023-01-03 23:57 UTC, ST-DDT commented on src/locales/en/airline/airplane.ts
> +// Generated from data at https://raw.githubusercontent.com/jpatokal/openflights/master/data/planes.dat
These data are provided under the terms of the AGPL and incompatible with the MIT license.

2023-01-03 23:57 UTC, ST-DDT commented on src/locales/en/airline/airport.ts
> +// Generated from data at https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat
These data are provided under the terms of the AGPL and incompatible with the MIT license.

2023-01-04 01:25 UTC, matthewpetro commented on src/locales/en/airline/airlines.ts
> +// Top 100 airlines in 2019 according to https://www.flightglobal.com/download?ac=73318
The airline information came from https://github.com/jpatokal/openflights/blob/master/data/airlines.dat, which also is under the AGPL. Is data from Wikipedia compatible with the MIT license?

2023-01-04 02:45 UTC, matthewmayer commented on src/locales/en/airline/airport.ts
> +// Generated from data at https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat
I am very dubious that a list of public airports can be copyrighted at all. Basic facts can't be copyrighted.

2023-01-04 06:05 UTC, matthewpetro commented on src/locales/en/airline/airport.ts
> +// Generated from data at https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat
That is a good point. The data from OpenFlights probably does have some user edits in it, so the list in its entirety may be covered by the AGPL. But the airport names and codes are just facts that can be obtained from numerous sources.

I believe the same is true for the airplane and airline information.

What are everyone's thoughts?

2023-01-04 08:12 UTC, Shinigami92 commented on src/locales/en/airline/airport.ts
> +// Generated from data at https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat
I'm slightly okay with copy them over from multiple sources, so it doesn't count as "we took it from exactly there"
Maybe we could also check the list by hand and only take the e.g. top 10 airports of each country? This would filter out such tiny airports that could only come in via a full list with values of slightly unknown small airports 🤔

2023-01-04 08:27 UTC, matthewmayer commented on src/locales/en/airline/airport.ts
> +// Generated from data at https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat
I agree in this case it's better to have a human compile a list (referring to multiple sources) rather than completely rely on one source of "worlds largest 100 airports" or something as a collection of facts can sometimes be copyright able even if the facts themselves are not.

2023-01-05 06:44 UTC, matthewpetro commented on src/locales/en/airline/airport.ts
> +// Generated from data at https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat
I've updated the airline, airplane, and airport definition files so they are not based on a single collection of information. They now contain a collection of large airlines and airports from around the world and a list of airplanes from major manufacturers.

2023-01-05 08:23 UTC, matthewmayer commented
For airports would there also be value in adding a "city" property? For example BKK might show as Bangkok rather than Suvarnabhumi Airport in a UI.

2023-01-05 10:31 UTC, ST-DDT commented
If we add a city, then what about the country?
I'm not familiar with that area of expertise so I dont know what data are actually needed.

2023-01-05 13:58 UTC, matthewpetro commented
Having the name and IATA code is suitable for many use cases and more data points could be added if users working in the airline domain find a need for them.

2023-01-05 14:25 UTC, matthewmayer commented
It's common to just show the city and not the country to avoid political arguments over say what country Taipei Taoyuan Airport is in.

2023-01-05 18:41 UTC, ST-DDT reviewed
Thanks for replacing the lists with custom ones.

2023-01-05 18:41 UTC, ST-DDT commented on src/definitions/airline.ts
> +  airline: readonly Airline[];
I'm not sure whether the list/array itself should be readonly or only the elements therein.
What do the others think?

2023-01-05 18:41 UTC, ST-DDT commented on src/modules/airline/index.ts
> +    } = {}
Maybe add an option to add the airline code?

`airlineCode: boolean | string` (Defaults to `false`)

````ts
if (typeof airlineCode === 'boolean') {
  airlineCode = airlineCode ? this.airline().code : '';
}
````

2023-01-05 18:41 UTC, ST-DDT commented on src/modules/airline/index.ts
> +   * zeros, often with the airline code prepended (e.g.: AA0425).
```suggestion
   * Returns a random flight number. Flight numbers are always `1` to `4` digits long. Sometimes they are
   * used without leading zeros (e.g.: `American Airlines flight 425`) and sometimes with leading
   * zeros, often with the airline code prepended (e.g.: `AA0425`).
```

2023-01-05 18:41 UTC, ST-DDT commented on src/modules/airline/index.ts
> +    const { addLeadingZeros = false } = options;
You can merge these into a single statement:

```suggestion
    const { length = { min: 1, max: 4 }, addLeadingZeros = false } = options;
```

(Might require formatting)

2023-01-05 18:41 UTC, ST-DDT commented on src/locales/en/airline/airlines.ts
> +export default Object.freeze([
Not sure about freezing the list. Maybe only freeze the entries therein?

2023-01-05 21:52 UTC, matthewpetro commented on src/definitions/airline.ts
> +  airline: readonly Airline[];
That makes sense. The underlying array isn't exposed to a user, but the objects within it are, so they should be read only.

You're thinking something like this, right?
```
airline: Readonly<Airline>[];
```

2023-01-05 21:55 UTC, matthewpetro commented
> Thanks for replacing the lists with custom ones.

You're welcome!

2023-01-05 22:00 UTC, matthewpetro commented on src/locales/en/airline/airlines.ts
> +export default Object.freeze([
That does make sense. As mentioned above, the array probably doesn't have to be frozen, but the entries should be read only.

2023-01-05 22:00 UTC, matthewpetro commented on src/modules/airline/index.ts
> +   * zeros, often with the airline code prepended (e.g.: AA0425).
Done!

2023-01-05 22:01 UTC, matthewpetro commented on src/modules/airline/index.ts
> +    const { addLeadingZeros = false } = options;
Thanks for catching that!

2023-01-05 22:12 UTC, matthewpetro commented on src/modules/airline/index.ts
> +    } = {}
That feels to me like the function would be doing too much and not saving many lines of code for a user. I definitely can add it if anyone feels strongly about it, though.

2023-01-05 23:21 UTC, ST-DDT commented on src/definitions/airline.ts
> +  airline: readonly Airline[];
Not exactly, but close:

````ts
interface Airline {

.... readonly string;

}
````

If the array only contains readonly objects, then the readonly is lost when returning from the method because the method returns the type directly instead of the array elements, alternatively we could return `Readonly<Airline>` from the method, but there isn't any usecase for non-readonly `Airline` entries in the first place.

2023-01-06 04:13 UTC, matthewpetro commented on src/definitions/airline.ts
> +  airline: readonly Airline[];
Sounds good, I just made the change.

2023-01-06 04:14 UTC, matthewpetro commented on src/locales/en/airline/airlines.ts
> +export default Object.freeze([
I removed the `Object.freeze()` calls.

2023-01-06 09:37 UTC, ST-DDT commented on src/definitions/airline.ts
> +  airline: readonly Airline[];
You forgot to remove the `readonly` from the `AirlineDefinitions`. Could you please remove them from there as well?

2023-01-06 11:29 UTC, matthewmayer commented on src/modules/airline/index.ts
> +    } = {}
I would like to see an option for the code. That way if say you are making a fake boarding pass it's easy to first get a random airline then pass the code into the flight number method to get an associated random flight number.

2023-01-06 11:33 UTC, matthewmayer commented on src/modules/airline/index.ts
> +    } = {}
But personally I'd expect flight number to already include a random airline code by default.with option to omit it?

2023-01-06 12:56 UTC, matthewmayer commented on src/modules/airline/index.ts
> +    } = {}
If the consensus is not to include codes in this method, it would be good to include that as a seperate example, e.g.


`${faker.airline.airline().iataCode}${faker.airline.flightNumber()} //AA123`

2023-01-06 13:29 UTC, matthewpetro commented on src/definitions/airline.ts
> +  airline: readonly Airline[];
Thanks for catching that!

2023-01-06 13:56 UTC, ST-DDT commented
There still seems to be some a lint error.

2023-01-06 15:04 UTC, matthewpetro commented
> There still seems to be some a lint error.

Fixed!

2023-01-06 16:27 UTC, ST-DDT commented on src/definitions/airline.ts
> +  airlines: Airline[];
We usually use singular names here, and I understand why you used that alternative:

https://github.com/matthewpetro/faker/blob/e38027d703f1601f87f80b946f7b671f43dc3a63/src/locales/en/airline/index.ts#L10-L11

 but I have to think about that first and discuss with the other team members.

2023-01-06 17:48 UTC, matthewpetro commented on src/definitions/airline.ts
> +  airlines: Airline[];
Yeah, using a plural here seemed to be a good way around the naming conflict, but if there's a better option I'd definitely be in favor of it.

2023-01-09 02:46 UTC, matthewpetro commented on src/definitions/airline.ts
> +  airlines: Airline[];
I haven't been able to find a good way to use a singular name here, other than renaming the module from `airline` to something else like `airtravel` or maybe just `travel` as had been discussed before.

I think it's best to just keep the plural in the definition here.

2023-01-09 03:55 UTC, matthewmayer commented on src/definitions/airline.ts
> +  airlines: Airline[];
FWIW there are currently two other examples of `faker.module.module`: `faker.vehicle.vehicle()` and `faker.image.image()`

2023-01-09 05:04 UTC, matthewpetro commented on src/definitions/airline.ts
> +  airlines: Airline[];
Thanks! I took a look at them and neither have locale definition files with names that match the module name, so they've been able to avoid the problem I'm running into.

2023-01-10 14:23 UTC, matthewpetro commented on src/definitions/airline.ts
> +  airlines: Airline[];
The only way I can think of to use a singular name is to update the generateLocales.ts script so that it can generate a locale index file that looks like:
```
import type { AirlineDefinitions } from '../../..';
import { default as airlines } from './airline';
import airplane from './airplane';
import airport from './airport';

const airline: AirlineDefinitions = {
  airline: airlines,
  airplane,
  airport,
};

export default airline;
```

Are there opinions as to whether I should make those updates or just leave things as the are?

2023-01-10 14:43 UTC, matthewpetro commented on src/modules/airline/index.ts
> +    } = {}
I added an example to the documentation that showed how to combine the airline code and flight number, but I'd be happy to discuss further changes if there are opinions about it.

2023-01-10 21:00 UTC, ST-DDT commented
Please fix the failing tests.

2023-01-11 01:35 UTC, matthewpetro commented
> Please fix the failing tests.

Done!

2023-01-12 15:09 UTC, Shinigami92 commented on src/modules/airline/index.ts
> +  readonly iataTypeCode: string;
```suggestion
  /**
   * The IATA code of the airplane (e.g. `'321'`).
   */
  readonly iataTypeCode: string;
```

What's the difference between an `iataCode` and an `iataTypeCode`

Should `Type` be reflected in the JSDoc?

2023-01-12 16:40 UTC, ST-DDT commented on src/definitions/airline.ts
> +  airlines: Airline[];
**Team decision**

- We will use `airline.airline` for now.
  - Do you want to adjust the `generate:locales` script to suffix the import with `_` in the case of the name collision (in a separate PR, that will be merged before this one)

https://github.com/faker-js/faker/blob/47b2cfc76b790647e398bf9883368a10b2ff5a68/scripts/generateLocales.ts#L183-L190

----------

We are still unsure regarding `airline.airline{ name, iataCode }` vs `airline.name: string[]`.
How important is having the correct airline code and name is for you vs randomly generated codes?

2023-01-13 16:36 UTC, matthewmayer commented on src/definitions/airline.ts
> +  airlines: Airline[];
I feel this is similar to `faker.science.chemicalElement()` where you want both the code and the full name

2023-01-13 20:19 UTC, ST-DDT commented on src/definitions/airline.ts
> +  airlines: Airline[];
That is exactly what we question right now.
Is it important to have these data together or is a little bit randomness fine?

If we have highly realistic data for most parts of the UI, but some mismatching data (e.g. atomic weight is generated randomly), then wouldn't this cause some kind of uncanny valley effect or an increase thereof?
If the data didn't match/or look random in the first place, then you would say "well it's test data".

2023-01-13 22:04 UTC, matthewpetro commented on src/modules/airline/index.ts
> +  readonly iataTypeCode: string;
`iataTypeCode` is what I should have named the field to begin with, as that's a more descriptive name. I've also updated the JSDocs to match, thanks for catching that!

2023-01-13 22:31 UTC, matthewpetro commented on src/definitions/airline.ts
> +  airlines: Airline[];
> So basically this is more a question regarding the scope of this library, than regarding this method in particular. Do we provide lists (of names) or do we provide some kind of a database for all stuff.

Hmm, that's a deep question. Which answer would make Faker more useful to users of the library?

2023-01-13 22:37 UTC, matthewpetro commented on src/definitions/airline.ts
> +  airlines: Airline[];
> **Team decision**
> 
> * We will use `airline.airline` for now.
>   
>   * Do you want to adjust the `generate:locales` script to suffix the import with `_` in the case of the name collision (in a separate PR, that will be merged before this one)
> 

No problem, I'll start on that.
> https://github.com/faker-js/faker/blob/47b2cfc76b790647e398bf9883368a10b2ff5a68/scripts/generateLocales.ts#L183-L190
> 
> We are still unsure regarding `airline.airline{ name, iataCode }` vs `airline.name: string[]`. How important is having the correct airline code and name is for you vs randomly generated codes?

For me right now, it isn't important. So I'm good leaving the data the way it is now or splitting it up into separate `airline.name: string[]` and airline.iataCode: string[]` functions.

2023-01-14 00:19 UTC, ST-DDT commented on src/definitions/airline.ts
> +  airlines: Airline[];
> > We are still unsure regarding `airline.airline{ name, iataCode }` vs `airline.name: string[]`. How important is having the correct airline code and name is for you vs randomly generated codes?
> 
> For me right now, it isn't important. So I'm good leaving the data the way it is now or splitting it up into separate `airline.name: string[]` and airline.iataCode: string[]` functions.

Lets wait for the decision in:

- #1733

2023-01-17 23:08 UTC, ST-DDT commented on src/definitions/airline.ts
> +  airlines: Airline[];
```suggestion
  airline: Airline[];
```

2023-01-18 00:08 UTC, matthewpetro commented on src/definitions/airline.ts
> +  airlines: Airline[];
Good catch, thanks! I just updated the code.

2023-01-18 09:13 UTC, ST-DDT approved these changes, later dismissed
Looks good to me. Thanks for your contribution.

> Lets wait for the decision [regarding complex return objects] in:
>
> Better currencies #1733

2023-01-18 13:47 UTC, matthewpetro commented
> Looks good to me. Thanks for your contribution.

You're welcome. Thanks to everyone for the suggestions for improvements!

2023-01-18 18:16 UTC, import-brain requested changes

2023-01-18 18:16 UTC, import-brain commented on test/airline.spec.ts
> +    }
```suggestion
        it('should return a random flight number with 2 to 4 digits and leading zeros', () => {
          const flightNumber = faker.airline.flightNumber({
            length: { min: 2, max: 4 },
            addLeadingZeros: true,
          });
          expect(flightNumber).toMatch(/^[0-9]{1,4}$/);
        });
      });
    }
```

2023-01-18 18:57 UTC, matthewpetro commented on test/airline.spec.ts
> +    }
Good catch, thank you!

2023-01-18 19:00 UTC, import-brain approved these changes, later dismissed

2023-01-18 19:14 UTC, ST-DDT submitted a review, later dismissed

2023-01-21 17:12 UTC, Shinigami92 commented on src/modules/airline/index.ts
> +      allowVisuallySimilarCharacters?: boolean;
Please update your branch and then add JSDocs to these option params like in other modules

Here it would be something like

```suggestion
      /**
       * Whether to allow numeric characters.
       *
       * @default false
       */
      allowNumerics?: boolean;
      /**
       * Whether to allow visually similar characters such as '1' and 'I'.
       *
       * @default false
       */
      allowVisuallySimilarCharacters?: boolean;
```

2023-01-21 17:12 UTC, Shinigami92 commented on src/modules/airline/index.ts
> +      aircraftType?: AircraftType;
Same here

```suggestion
      /**
       * The aircraft type. Can be one of `narrowbody`, `regional`, `widebody`.
       *
       * @default 'narrowbody'
       */
      aircraftType?: AircraftType;
```

2023-01-21 17:12 UTC, Shinigami92 commented on src/modules/airline/index.ts
> +      addLeadingZeros?: boolean;
and here (as prettier would complain anyways, I'm to lazy now to write this as a suggestion)

2023-01-21 23:59 UTC, matthewpetro commented on src/modules/airline/index.ts
> +      allowVisuallySimilarCharacters?: boolean;
Done! Thanks for the suggestions.

2023-01-21 23:59 UTC, matthewpetro commented on src/modules/airline/index.ts
> +      addLeadingZeros?: boolean;
Done!

2023-01-21 23:59 UTC, matthewpetro commented on src/modules/airline/index.ts
> +      aircraftType?: AircraftType;
Done!

2023-01-22 17:04 UTC, ST-DDT commented on src/modules/airline/index.ts
> +};
Maybe add `satisfies Record<AircraftType, number>`

2023-01-22 17:04 UTC, ST-DDT commented on src/modules/airline/index.ts
> +};
Similarly here: `satifies Record<AircraftType, string[]>`

2023-01-22 17:06 UTC, Shinigami92 commented on src/modules/airline/index.ts
> +      length?:
The `length` param also needs a JSDoc 🙂

2023-01-22 17:54 UTC, matthewpetro commented on src/modules/airline/index.ts
> +      length?:
I've added the JSDoc for that param as well. Should the parameters be documented using JSDocs on the parameters or using the `@param` tag? I currently have both in the code, but I'm not sure if I need to keep both.

2023-01-22 17:55 UTC, Shinigami92 commented on src/modules/airline/index.ts
> +      length?:
both

2023-01-22 19:11 UTC, matthewpetro commented on src/modules/airline/index.ts
> +      length?:
Thanks!

2023-01-22 19:24 UTC, matthewpetro commented on src/modules/airline/index.ts
> +};
Would defining the type of `aircraftTypeMaxRows` be better?
```
const aircraftTypeMaxRows: Record<AircraftType, number> = {
```

2023-01-29 00:22 UTC, ST-DDT approved these changes

2023-01-29 16:22 UTC, import-brain submitted a review, later dismissed

2023-01-29 23:03 UTC, ST-DDT requested changes

2023-01-29 23:03 UTC, ST-DDT commented on src/locales/en/index.ts
> +  separator: ' & ',
This line got removed from the next branch.
Could you please run:

````sh
pnpm run generate:locales
````

to fix it?

2023-01-30 04:28 UTC, matthewpetro commented on src/locales/en/index.ts
> +  separator: ' & ',
Done!

2023-01-30 07:57 UTC, ST-DDT approved these changes

2023-01-30 14:19 UTC, Shinigami92 commented
Should this be merged before we decide if we still want to have "complex" objects in definitions? Or should we wait a bit (could be around 3 weeks due to no meetings)

Here we have `iataCode`s which can be put into global definitions, but airport names are in english and could be translated to their individual locales 🤔 
_I feel not really happy with this design, but it's not an issue by this module itself but faker itself right now_

2023-01-30 14:37 UTC, ST-DDT commented
Lets get this merged, and decide later.
We have all the data we need here and can strip unwanted/restructure them later easily.

2023-01-30 14:50 UTC, Shinigami92 approved these changes

2023-01-30 15:47 UTC, ejcheng approved these changes

2023-01-30 16:07 UTC, Shinigami92 commented
@ST-DDT there is one unresolved discussion
please reevaluate it and decide if we can merge or need to do further actions on that

2023-01-30 21:13 UTC, merged

2023-01-30 21:15 UTC, ST-DDT commented
Thanks for your contribution.

2023-01-30 21:42 UTC, matthewpetro commented
You're welcome!