Feat/string/nano
faker-js/faker pull request #1716
Opened 2023-01-08 12:22 UTC by xDivisionByZerox

Resolves #1426.

2023-01-08 13:24 UTC, ST-DDT requested changes

2023-01-08 13:24 UTC, ST-DDT commented on test.ts
> +console.log(faker.string.nanoid({ min: 13, max: 37 }));
Please remove this debug code.

2023-01-08 13:24 UTC, ST-DDT commented on src/modules/string/index.ts
> +    }
The original implementation doesn't seem to have this limit:

https://github.com/ai/nanoid/blob/6cd578dca8c5c45946eb15796de3e3c91fa187c4/non-secure/index.js#L23-L32

2023-01-08 13:37 UTC, xDivisionByZerox commented on test.ts
> +console.log(faker.string.nanoid({ min: 13, max: 37 }));
ofc, my bad.

2023-01-08 13:39 UTC, xDivisionByZerox commented on src/modules/string/index.ts
> +    }
I got that from their [official website](https://zelark.github.io/nano-id-cc/), where `36` is the maximum size of an id.

2023-01-08 13:57 UTC, ST-DDT commented on src/modules/string/index.ts
> +    }
> More than 1 quadrillion years needed, in order to have a 1% probability of at least one collision.

I assume that after that the math no longer works out regarding their collision detection.
(that page is specifically for collision probability calculation)

Their source code doesn't have a limit so we shouldn't have one either IMO.

2023-01-08 14:09 UTC, xDivisionByZerox commented on src/modules/string/index.ts
> +    }
No problem. I removed the maximum restriction.

2023-01-08 14:20 UTC, ST-DDT approved these changes

2023-01-08 15:40 UTC, import-brain approved these changes

2023-01-09 18:58 UTC, Shinigami92 approved these changes

2023-01-09 18:58 UTC, Shinigami92 commented on src/modules/string/index.ts
> +        value: () => this.faker.helpers.arrayElement(['_', '-']),
I searched if it's allowed to start with `_|-` but I found nothing :shrug: 
So seems it's okay

2023-01-09 18:59 UTC, merged