refactor!: remove dynamic locale switching support
faker-js/faker pull request #1735
Opened 2023-01-13 23:09 UTC by ST-DDT

Implements #1340

- #1340 

Removes the ability to change the locale on existing Faker instances.

# New Features

- Access locales directly from the main index file (`en_AU_ocker`)
- Access to all locales at once (`allLocales.en_AU_ocker`)
- Access faker instances directly from the main index file (`fakerEN_AU_ocker`)
- Access to all faker instances at once (`allFakers.en_AU_ocker`)

# Changed Features

- The main `faker` instance is now `en` **only**

# Lost Features

- Changing locales dynamically
- Getting a random locale from the faker instance (and switch to that)
- UsableLocale, UsedLocale, KnownLocale types

# ToDos for this PR

- Change documentation
- Do more tests
- Write migration guide

# ToDos for later PRs

- Extract `global` locale data into own locale (#1441)
- Actually throw for missing locale entries (#893)
- `findFaker(locale: string): Faker` method?

2023-01-14 00:13 UTC, ST-DDT commented on test/locales.spec.ts
> -import { describe, expect, it } from 'vitest';
This file was renamed to `locale-data.spec.ts`.

2023-01-14 18:50 UTC, Shinigami92 commented on test/internet.spec.ts
> +          for (const [locale, localeFaker] of Object.entries(allFakers)) {
Maybe we should rewrite this test to use `it.each(Object.entries(allFakers))(...)`

2023-01-14 18:50 UTC, Shinigami92 commented on test/scripts/apidoc/examplesAndDeprecations.spec.ts
> -        (_, locale: string) => `faker.locale = '${locales[locale]}';\nfaker.`
Line 91 was removed and so it reports that
line 35 is not used anymore

2023-01-14 18:50 UTC, Shinigami92 commented on test/support/seededRuns.ts
> -    this.faker.locale = 'en';
I haven't checked it but now as we do not have a shared faker instance where we switch the locale at runtime, seededRuns that potentially use another locale need to also set the seed manually

It is likely that this is not a problem right now, but should be remembered if it is or gets a case

2023-01-14 18:50 UTC, Shinigami92 commented on src/modules/random/index.ts
> -  locale(): string {
Not sure about this hard removal without at least a deprecation and/or alternative

Yes we have `countryCode`, but this could be used e.g. to randomly select a locale for e.g. `vue-i18n`
I googled a bit around and we might need something like `ISO 639-1` and/or `ISO 3166`
Maybe this can be implemented in another PR in beforehand and then we can decorate this method `random.locale` to indicate that there is a new alternative

2023-01-14 18:50 UTC, Shinigami92 commented on src/faker.ts
> +  constructor(options: { locale: LocaleDefinition | LocaleDefinition[] }) {
Lets still extract this into `FakerOptions`
We already create very big hard breaking changes with this PR without alternatives, but lets keep it as less as possible

By staying with `FakerOptions` someone can still do:
```ts
const options: FakerOptions = { ... }
// ...
const myFaker = new Faker(options)
```

Otherwise they would be forced to do hard stuff like:
```ts
const options: ConstructorParameters<Faker>[0] = { ... }
// ...
const myFaker = new Faker(options)
```

To me this is less user friendly

2023-01-15 00:04 UTC, ST-DDT commented on src/modules/random/index.ts
> -  locale(): string {
The problem is, that regardless what we do we change the semantic of the method.
Previously, it returned one of the loaded/available locales inside that faker instance, that is no longer possible.

- Returning a country code instead would be an entirely new method, that has nothing in common with the previous one.
- Returning a locale code would also be an entirely new method, that at most returns values that look like the previous ones, but are not
- Returning a supported locale changes the semantics of the method, because previously only "active" locales would be returned.
- Adding a locale metadata to each locale that contains their locale code, would allow this method to return at least one valid result. However, there is no longer a method to use the result in.

2023-01-15 00:09 UTC, ST-DDT commented on src/faker.ts
> +  constructor(options: { locale: LocaleDefinition | LocaleDefinition[] }) {
I'll think about it.

Currently, new Faker is the only method in our entire repo that supports that.
So what is so special about that one? I assume, it isn't even the method that is used the most.

2023-01-15 00:19 UTC, ST-DDT commented on test/support/seededRuns.ts
> -    this.faker.locale = 'en';
Not really, the seed is set for the faker instance that is used for the tests (this.faker), so if the seeded tests run in a different locale, then the references faker instance would be a different one and thus the set here correctly.

https://github.com/faker-js/faker/blob/788fce048f0233552df47f3407c06d8f83c32b0c/test/support/seededRuns.ts#L70-L77

https://github.com/faker-js/faker/blob/788fce048f0233552df47f3407c06d8f83c32b0c/test/animal.spec.ts#L30-L32

````diff
- seededTests(faker, 'animal', (t) => {
+ seededTests(fakerEN_US, 'animal', (t) => {
````

(Theoretically, it is possible to run the seeded tests for all supported locales, with next to no effort, but that will likely explode our test snapshots file beyond review-ability.)

2023-01-15 00:26 UTC, ST-DDT commented on test/scripts/apidoc/examplesAndDeprecations.spec.ts
> -        (_, locale: string) => `faker.locale = '${locales[locale]}';\nfaker.`
Fixed

2023-01-17 05:28 UTC, matthewmayer commented on test/support/seededRuns.ts
> -    this.faker.locale = 'en';
i would suggest doing this for a very small subset of methods which are commonly localized, e.g. names, email addresses, streets and city names, phone numbers.

2023-01-17 07:01 UTC, matthewmayer requested changes

2023-01-17 07:01 UTC, matthewmayer commented on src/faker.ts
> -  setLocale(locale: UsableLocale): void {
I think rather than removing the function, you should keep it and throw a helpful error when called (at least for v8) if trying to call faker.setLocale or faker.locale, for example "You can no longer set the locale of faker at runtime, please see the migration guide at ..."

That helps people upgrading to figure out what's wrong with their code if it breaks. 

```
> faker.locale = "de" //silently fails to do anything
'de'
> faker.setLocale("de")
Uncaught TypeError: faker.setLocale is not a function //ok, but not very informative
```

2023-01-17 07:35 UTC, Shinigami92 commented on src/faker.ts
> -  setLocale(locale: UsableLocale): void {
I 💯% agree with @matthewmayer
Especially in plain JS you wont get just `setLocale is not a function on Faker`, but a helpful message that it is not a bug

2023-01-17 07:43 UTC, Shinigami92 commented on src/faker.ts
> +  constructor(options: { locale: LocaleDefinition | LocaleDefinition[] }) {
The only difference I currently see is that this is a class (constructor) not a function, but tbh this is not the reason

I actually always complained about that we use written out option types for everything just to have nice docs and or IDE hints
But when I e.g. use VueUse and they have not exported named options like this for a function it is a bit of a bad developer experience and I always need to work around such things until they introduce it in their repo
In VueUse or Quasar I can also often do things with types like `QTableProps['columns']` to e.g. reuse them in my own component props and forward them, and if they ever got an update or type change, I can see it by checking with `tsc`

2023-01-17 07:46 UTC, Shinigami92 commented on src/modules/random/index.ts
> -  locale(): string {
tbh it still would be possible by just taking the 56(?) strings and just paste them into the function, then add a deprecation

For the proposed ISO functions, IMO we can create and open new PRs (and/or issues/feature requests)

2023-01-17 08:50 UTC, matthewmayer commented on src/faker.ts
> -  setLocale(locale: UsableLocale): void {
Ideally yes, in 8.0 calling 
`faker.locale = "de"` or `faker.setLocale("de")` would throw a deprecation warning, but still work, and the error message would encourage you to switch to the new method for setting locale when you import/create faker. Then in 9.0 it would be completely removed. I understand doing this over two versions is more work (and you need to plan ahead, to ensure you know what the 'new' syntax will be for setting locale) but i think the payoff in terms of easier upgrading is worthwhile.

2023-01-17 10:04 UTC, ST-DDT commented on src/faker.ts
> -  setLocale(locale: UsableLocale): void {
There is one problem though.
If we use the key to lookup the locale data, then all of our faker instances require all locale data, regardless of whether we/the user want it or not.
Which effectively renders our entire v8's tree shaking mood and worse even if you created a small custom faker instance in v7 yourself, that would now blown up to the entire 5MB(?) at runtime without any way to prevent that.

I'm okay with keeping the method and always throw an error in it (which would worsen the DX for TS users), but beyond that everything else needs serious considerations.

2023-01-17 10:10 UTC, ST-DDT commented on src/faker.ts
> -  setLocale(locale: UsableLocale): void {
As an alternative, we could put the full locale map inside the main faker instance (and their subsets in the respective localized faker instances) to ship only the previous locales and allow our users to still create smaller instances.

2023-01-17 10:16 UTC, ST-DDT commented on src/modules/random/index.ts
> -  locale(): string {
Returning the strings is not the problem, the problem is what (can) you do with the string: https://github.com/faker-js/faker/pull/1735#discussion_r1072008424

2023-01-17 10:36 UTC, Shinigami92 commented on src/modules/random/index.ts
> -  locale(): string {
> Returning the string(s) is not the problem, the problem is what you (can) do with the string: [#1735 (comment)](https://github.com/faker-js/faker/pull/1735#discussion_r1072008424)

Maybe don't think so far, return just strings here and throw an error in `setLocale`
That's it
It's still a deprecation with a breaking change

- setLocale for removal
- random.locale for replacement (other PR)

2023-01-17 11:19 UTC, matthewmayer commented on src/faker.ts
> -  setLocale(locale: UsableLocale): void {
Is there a way to throw an error when faker.locale = "foo" is called (this is the current way that the README recommends setting locales, so you can assume a lot of consumers will have followed that)

<img width="399" alt="image" src="https://user-images.githubusercontent.com/152770/212885751-46b06e1c-fd09-4cb2-b61b-975f0092bcef.png">

2023-01-17 18:44 UTC, Shinigami92 commented on src/faker.ts
> -  setLocale(locale: UsableLocale): void {
> Is there a way to throw an error when faker.locale = "foo" is called

Yes, we can use a `set` accessor for that

2023-01-17 21:27 UTC, ST-DDT commented on src/faker.ts
> +  constructor(options: { locale: LocaleDefinition | LocaleDefinition[] }) {
How about exporting all options as types:

````ts
export FakerOptions = ConstructorParameters<Faker>[0];
````

and later for each method

````ts
export StringAlphaOptions = Parameters<Faker>[index of options parameter];
````

2023-01-17 21:29 UTC, Shinigami92 commented on src/faker.ts
> +  constructor(options: { locale: LocaleDefinition | LocaleDefinition[] }) {
we could try, not sure how that works for overload signatures :thinking:

2023-01-17 23:16 UTC, ST-DDT commented on src/faker.ts
> +  );
@Shinigami92 Any idea why?

2023-01-17 23:16 UTC, ST-DDT commented on src/faker.ts
> -  setLocale(locale: UsableLocale): void {
Done

2023-01-17 23:16 UTC, ST-DDT commented on src/faker.ts
> +  constructor(options: { locale: LocaleDefinition | LocaleDefinition[] }) {
Done

2023-01-17 23:26 UTC, ST-DDT commented on test/support/seededRuns.ts
> -    this.faker.locale = 'en';
Moved the discussion to: https://github.com/faker-js/faker/issues/1749

2023-01-19 01:24 UTC, ST-DDT commented on src/modules/random/index.ts
> -  locale(): string {
I pseudo removed the method for now.
(It won't be shown in the api docs either)

2023-01-19 01:47 UTC, ST-DDT commented on scripts/apidoc/moduleMethods.ts
> +export function selectApiSignature(
TODO: Move to utils

2023-01-19 09:35 UTC, xDivisionByZerox commented on src/modules/random/index.ts
> -  locale(): string {
I'm with @Shinigami92 here. The function itself should still return a locale string from a hardcoded array. Since you can no longer use the string to set the locale I don't see any problem with that. Yes, the use case will most likely be gone, but at least the method itself is still there and doesn't break anything.
We cannot "just" remove a function from our API. 

<details>
<summary>Implementation</summary>

```ts
/**
 * [...]
 */
locale(): string {
  return faker.helpers.arrayElement([
    'af_ZA',
    'ar',
    'az',
    'cz',
    'de',
    'de_AT',
    'de_CH',
    'dv',
    'el',
    'en',
    'en_AU',
    'en_AU_ocker',
    'en_BORK',
    'en_CA',
    'en_GB',
    'en_GH',
    'en_IE',
    'en_IN',
    'en_NG',
    'en_US',
    'en_ZA',
    'es',
    'es_MX',
    'fa',
    'fi',
    'fr',
    'fr_BE',
    'fr_CA',
    'fr_CH',
    'fr_LU',
    'ge',
    'he',
    'hr',
    'hu',
    'hy',
    'id_ID',
    'it',
    'ja',
    'ko',
    'lv',
    'mk',
    'nb_NO',
    'ne',
    'nl',
    'nl_BE',
    'pl',
    'pt_BR',
    'pt_PT',
    'ro',
    'ru',
    'sk',
    'sv',
    'tr',
    'uk',
    'ur',
    'vi',
    'zh_CN',
    'zh_TW',
    'zu_ZA',
  ]);
}
```
</details>

2023-01-19 09:40 UTC, xDivisionByZerox commented on test/all_functional.spec.ts
> +  Record<string, '*' | ReadonlyArray<keyof typeof allLocales>>
I like that change 👍 
Should we also make the module key more strict? Something like `Omit<keyof Faker, 'definitions' | 'helpers'>`

2023-01-19 10:31 UTC, Shinigami92 commented on src/faker.ts
> +  );
I'm not sure if I ever overwrote a constructor like that because I normally do not differ such options that way (outside of Faker)

But I assume the last overload is always needed to implement the real-js signature
Everything above (the actual overloads) are just plain TS and are not real at runtime

2023-01-19 12:36 UTC, ST-DDT commented on src/faker.ts
> +  );
But the implementation signature is the same as this one (duplicate)!?

2023-01-19 13:18 UTC, ST-DDT commented on test/all_functional.spec.ts
> +  Record<string, '*' | ReadonlyArray<keyof typeof allLocales>>
Done but I omitted the omit for readability.

2023-01-19 13:42 UTC, Shinigami92 commented on src/faker.ts
> +  );
Ah I see what you mean

```
1
2
1|2
real 1|2
```

don't know, feel free to ask in StackOverflow or GitHub https://github.com/microsoft/TypeScript/issues

2023-01-19 23:50 UTC, ST-DDT commented on scripts/apidoc/moduleMethods.ts
> +export function selectApiSignature(
Done

2023-01-19 23:51 UTC, ST-DDT commented
Blocked by https://github.com/faker-js/faker/pull/1759

2023-01-23 21:41 UTC, ST-DDT commented on scripts/apidoc/typedoc.ts
> +    .filter((method) => !method.flags.isPrivate);
FFR: @Shinigami92 would like to discuss this in the next team meeting.

Originally posted here: https://github.com/faker-js/faker/pull/1759#discussion_r1082981075

2023-01-26 22:59 UTC, ST-DDT commented on scripts/generateLocales.ts
> +  }
Export this as a function for our users.

2023-01-27 17:51 UTC, Shinigami92 commented on scripts/generateLocales.ts
> +  }
Please extract this to its own PR and maybe even label it with `s: awaiting more info`

This is not blocking this PR from getting merged and this PR should be merged soon as it already blocks the process of v8.0 as well as some already open PRs

2023-01-27 18:34 UTC, Shinigami92 commented on src/index.ts
> +export * as allLocales from './locales';
This export bleeds to a non-treeshaked bundle while e.g. running with vite

I debugged with https://socket.dev/npm/package/vite-bundle-visualizer

We can circumvent this by configuring `sideEffects` in package.json and then move `allLocales` to its own file so it can be reexported from there as standalone without affecting the other ones

We already had once the request for this already

- #1305

We need to _somehow_ test that setting `sideEffects` brings no dark hidden breakings into the project, and I don't know where we could have side effects
So maybe instead of setting it to false, it might be that we need to configure an array of filenames

2023-01-27 19:42 UTC, ST-DDT commented on src/index.ts
> +export * as allLocales from './locales';
Before we start adding flags to the project, we should 
- have an automated test suite that ensures that we don't break this optimization
- or/and preferably understand why there is an issue in the first place.

But thats a different PR/issue from this one.

2023-01-27 20:37 UTC, Shinigami92 commented on src/index.ts
> +export * as allLocales from './locales';
How would you like to proceed?

- we cannot really merge this into next branch as it would introduce a bug that is currently not in the next branch
- if you want to find out why this flag is working and what it is doing, I consider searching a bit around on stack overflow or other documentations (I don't know what and why it is doing)
- I'm not aware of how it could be possible to automate a test that checks the emitted bundle size of a bundled external project that use a bundler like rollup to apply tree-shake to its own project
  at least I'm not sure if this is possible to run inside a PR before merging it into main and then automatically test inside CI (without introducing a separate folder for a whole project just to test something that is touched like twice a year)

It is a bit conflicting, because without this PR merged, we do not have this bug and so cannot really test if it breaks tree-shaking, but merging this without fixing the tree-shaking bug it introduces is also not really possible
the only thing this would lead me to approve is: you give me the word that you also fix the following PR to fix the introduced bug
otherwise we would hang in a state were the project is somewhat unreleaseable

2023-01-29 15:57 UTC, ST-DDT commented on src/index.ts
> +export * as allLocales from './locales';
I did some testing with our playground vite-cjs project.

The bundle size does not really change, if I add this change or note (~700KB).
Unless, I change the imports to import directly from the project root.
Regardless of what I import from the project root, the package size immediately jumps to 3.6MB.
So that issue is a preexisting condition that is NOT caused by this PR although it makes it easier to step into.

I even tried the current code on next with sideEffect: false, it didn't decrease the bundle size.
We have to investigate the reason for that, but IMO that is unrelated to this PR.

2023-01-29 16:39 UTC, Shinigami92 commented on src/index.ts
> +export * as allLocales from './locales';
Issue extracted to =>
- #1791

:+1:

2023-01-29 23:58 UTC, ST-DDT commented
Note to self:

TODO

- Change documentation
- Write migration guide

2023-02-18 12:03 UTC, Shinigami92 commented on README.md
> +If you don't want that or prefer a different fallback, you can also build your own instances.
:heart: :+1:

2023-02-18 12:08 UTC, Shinigami92 commented on docs/guide/localization.md
> +Currently, the imports from the main package have a bug and always cause the entire Faker lib to be imported.
Should we extend this sentence with e.g. a link to the issue + that we currently try to solve this but doesn't have the brain-power right now and looking for help?

2023-02-18 12:58 UTC, xDivisionByZerox commented on docs/guide/localization.md
> +The `Locale` (data) and (Faker) `Import` columns refer to the respective import names:
I'm confused here. `Import` should be `Faker` here to match the header no?

2023-02-18 23:22 UTC, ST-DDT commented on docs/guide/localization.md
> +The `Locale` (data) and (Faker) `Import` columns refer to the respective import names:
I forgot to generate and commit the changes to the columns. Should be fixed now.
(Not sure about the names though)

2023-02-18 23:29 UTC, ST-DDT commented on docs/guide/localization.md
> +Currently, the imports from the main package have a bug and always cause the entire Faker lib to be imported.
Done

2023-02-19 00:19 UTC, ST-DDT commented
So everything should be done now. Please review. thoroughly.

One thing, that I'm not sure about is:
Whether I should export the locale names (keys) as a separate and standalone const (e.g. `allLocaleNames`).
(Some of our [scripts](https://github.com/faker-js/faker/pull/1735/files#diff-56de87ca2ae95ee7c7a031bf487c87288b5dd206b66fed3ab6f551bf58081645R17) and [tests](https://github.com/faker-js/faker/pull/1735/files#diff-f8cd4ea46aecbba86ee9cba1a851bca523aca5e63bf9fa1866e3604a9d2dec26R6) only need the keys, but the code still loads everything (and then discards the unused parts).)

2023-02-19 11:13 UTC, matthewmayer requested changes

2023-02-19 11:13 UTC, matthewmayer commented on docs/guide/upgrading.md
> +
i don't think this is needed for the migration guide, this is advanced usage.

2023-02-19 11:13 UTC, matthewmayer commented on docs/guide/upgrading.md
> +
I think we should also explain how to handle a situation where you previously had one faker instance and were changing the locale dynamically at runtime.

For example if you were doing a mix of locales like

```js
for (let user of users) {
  const lang = faker.helpers.arrayElement(["de","en","fr"]) 
  faker.locale = lang
  user.name = faker.person.fullName()
}
```

2023-02-19 11:13 UTC, matthewmayer commented on docs/guide/localization.md
> +| `fr_BE`       | Français (Belgique)       | `fakerFR_BE`       |
"French (Belgium)" for consistency?

2023-02-19 11:13 UTC, matthewmayer commented on README.md
> +```
i think this more advanced usage can be covered in localization page only?

2023-02-19 11:13 UTC, matthewmayer commented on README.md
> +import { fakerDE as faker } from '@faker-js/faker';
can we also include a CommonJS example?

2023-02-19 11:18 UTC, Shinigami92 commented on test/helpers.spec.ts
> +        // TODO @ST-DDT 2023-01-17: Restore this test when the definitions proxy is restored.
What does this mean?
Should there be opened an issue for that so we do not forget it?

2023-02-19 11:18 UTC, Shinigami92 commented on test/locale-imports.spec.ts
> +      expect(faker.string.alpha()).toBeTypeOf('string');
string.alpha generates values just out of algorithm
Maybe we should use a method that uses locales/definitions so we ensure that also that is loaded correctly
We should also make it somehow safe and ensure that the correct locale was loaded (what the previous test case did)

2023-02-19 11:18 UTC, Shinigami92 commented on test/system.spec.ts
>        });
Not related to this PR, but we should try to find out what this test was purposed for and why it currently doesn't test anything anymore
Currently there is no `expect` call and therefor it could potentially be remove or fixed/reintroduced

2023-02-19 11:23 UTC, matthewmayer requested changes, later dismissed

2023-02-19 11:23 UTC, matthewmayer commented on README.md
> +import { fakerDE as faker } from '@faker-js/faker';
i guess 
```
const { fakerDE : faker } = require("@faker-js/faker")
```
would be the equivalent?

2023-02-19 20:30 UTC, ST-DDT commented on docs/guide/localization.md
> +| `fr_BE`       | Français (Belgique)       | `fakerFR_BE`       |
That is unrelated to this PR/change. Would you like to create a separate PR for this?

2023-02-19 20:31 UTC, ST-DDT commented on test/helpers.spec.ts
> +        // TODO @ST-DDT 2023-01-17: Restore this test when the definitions proxy is restored.
https://github.com/faker-js/faker/issues/893

2023-02-19 20:32 UTC, ST-DDT commented on test/locale-imports.spec.ts
> +      expect(faker.string.alpha()).toBeTypeOf('string');
This test should only test that there is a faker instance at that import, but I can call some other method as well.

2023-02-19 20:57 UTC, Shinigami92 commented on test/locale-imports.spec.ts
> +      expect(faker.string.alpha()).toBeTypeOf('string');
No, I would also like to have it covered that it is not only a Faker instance but the one that is required/imported
Maybe access the `faker.definition.title`? Or something other that identifies the top-base for the configured locale

2023-02-22 18:46 UTC, ST-DDT commented on docs/guide/upgrading.md
> +
Lets discuss this in the next team meeting.

2023-02-22 18:49 UTC, ST-DDT commented on docs/guide/upgrading.md
> +
Not sure whether this is worth mentioning.

````ts
for (let user of users) {
  const faker = faker.helpers.arrayElement([fakerDE, fakerEN, fakerFR ]);
  user.name = faker.person.fullName()
}
````

2023-02-22 18:50 UTC, ST-DDT commented on README.md
> +```
Lets discuss this in the next team meeting.

2023-02-23 09:44 UTC, Shinigami92 commented on docs/guide/upgrading.md
> +
> ```ts
> for (let user of users) {
>   const faker = faker.helpers.arrayElement([fakerDE, fakerEN, fakerFR]);
>   user.name = faker.person.fullName()
> }
> ```

Actually this is genius! Because now this does not (theoretically) load in all the locales but only DE, EN and FR which then comes down to 1-2 mb instead of 5 mb

2023-02-23 14:28 UTC, matthewmayer commented on docs/guide/upgrading.md
> +
I think this is a nice example to add. It wasn't obvious to me that this is the idiom you would use. It makes it clear instead of "one faker object you mutate" it's now "multiple faker objects".

2023-02-23 17:06 UTC, ST-DDT commented on docs/guide/upgrading.md
> +
**Team decision**

Mention multiple fallbacks that are now supported.

Add this example to the old to show the diff:

````ts
const customFaker = new Faker({
 locale: 'de_CH'
 fallbackLocale: 'de',
 locales: { de_CH, de, en }
});
const a = customFaker.firstName();
customFaker.locale = 'en'
const b = customFaker.smiley();
````

2023-02-23 17:10 UTC, ST-DDT commented on docs/guide/upgrading.md
> +
**Team decision**

Add it to the documentation.

2023-02-23 17:19 UTC, ST-DDT commented on README.md
> +```
**Team Decision**

We want to keep this.

2023-02-28 20:22 UTC, ST-DDT commented
I tried to use tables same as the Contribution guide, but that doesn't look good at all.

![grafik](https://user-images.githubusercontent.com/1579362/221968376-87bda73d-27c0-4f96-b2ee-16f72c83ad6b.png)
![grafik](https://user-images.githubusercontent.com/1579362/221968431-1d9edf03-4344-4a8f-a93d-43ab51d6e42b.png)

2023-02-28 20:34 UTC, ST-DDT commented on docs/guide/upgrading.md
> +
Done

2023-02-28 20:34 UTC, ST-DDT commented on docs/guide/upgrading.md
> +
Done

2023-02-28 20:49 UTC, ST-DDT commented on docs/guide/localization.md
> +| `fr_BE`       | Français (Belgique)       | `fakerFR_BE`       |
Done: https://github.com/faker-js/faker/pull/1884

2023-02-28 20:55 UTC, ST-DDT commented on test/system.spec.ts
>        });
Moved to own issue: https://github.com/faker-js/faker/issues/1885

2023-03-01 19:27 UTC, Shinigami92 commented on test/locale-imports.spec.ts
> +      expect(faker.definitions.title).toBe(allLocales[locale].title);
at least this is a little compromise
could we add it for the other 3 cases as well?

2023-03-01 23:30 UTC, ST-DDT commented on test/locale-imports.spec.ts
> +      expect(faker.definitions.title).toBe(allLocales[locale].title);
Done

2023-03-03 13:34 UTC, Shinigami92 submitted a review, later dismissed
Lets move on, release new alpha and iterate in further PRs if needed

2023-03-04 12:36 UTC, matthewmayer commented on README.md
> +But you can also import instances using other locales.
Should we add a warning like in #1886 so as not to confuse people who read this on the README but are using the stable v7?

2023-03-04 14:13 UTC, ST-DDT commented on README.md
> +But you can also import instances using other locales.
#1886 is scheduled to arrive after this to include the warnings.

2023-03-04 14:29 UTC, matthewmayer requested changes

2023-03-04 14:29 UTC, matthewmayer commented on docs/guide/upgrading.md
> +faker.setLocale('de_CH');
i think the "Old" should also include the import statement to make the necessary changes clearer

2023-03-04 14:29 UTC, matthewmayer commented on docs/guide/upgrading.md
> +In order to facilitate better and easier locale fallback mechanics, we removed the methods to change the locales on existing `Faker` instances.
i think we could explicitly mention:

If you are using Faker with just the default `en` locale, you don't need to make any changes to your code.

2023-03-04 14:29 UTC, matthewmayer commented on docs/guide/upgrading.md
> +const b = customFaker.smiley();
what is `faker.smiley()`? you mean `faker.internet.emoji()`?

2023-03-04 14:29 UTC, matthewmayer commented on docs/guide/upgrading.md
> +  locale: [customNames, customAddresses, de_CH, de, en, global],
what is `global` here?

2023-03-04 14:29 UTC, matthewmayer commented on docs/guide/upgrading.md
> +for (let user of users) {
should include the import here

2023-03-04 14:29 UTC, matthewmayer commented on docs/guide/upgrading.md
> +import { Faker, de_CH, de, en } from '@faker-js/faker';
shouldnt think be fakerDE_CH, fakerDE, fakerEN?

2023-03-04 14:37 UTC, Shinigami92 commented on docs/guide/upgrading.md
> +  locale: [customNames, customAddresses, de_CH, de, en, global],
I assume this is a preparation for the followup PR:
- #1748

2023-03-04 15:21 UTC, ST-DDT commented on docs/guide/upgrading.md
> +import { Faker, de_CH, de, en } from '@faker-js/faker';
No as these refer to the locales not the related faker instances.

2023-03-04 20:36 UTC, xDivisionByZerox commented on README.md
> +// import { fakerDE as faker } from '@faker-js/faker';
Since we have the same imports on the "Localization" section I don't see the need to include them here as well.

2023-03-05 03:51 UTC, matthewmayer commented on docs/guide/upgrading.md
> +  locale: [customNames, customAddresses, de_CH, de, en, global],
also `customNames`, `customAddresses` only appear in the "New" code so it's unclear what they are doing. They should either be added to Old or removed from both.

2023-03-05 05:03 UTC, matthewmayer requested changes

2023-03-05 05:03 UTC, matthewmayer commented on docs/guide/upgrading.md
> +const a = customFaker.person.firstName();
we should probably avoid using faker.person.* in this section of the migration guide, because if you are upgrading from 7.x to 8.x you would actually be using faker.name* previously? So the "old" code doesn't actually run correctly in v7 OR v8.

2023-03-05 08:53 UTC, ST-DDT commented on docs/guide/upgrading.md
> +  locale: [customNames, customAddresses, de_CH, de, en, global],
The idea behind this is to show that you can put your own data there, but I'm not sure how to show that best.

Would an `import custom from test-data.ts` + using only custom in the constructor be easier to understand?

2023-03-05 09:45 UTC, matthewmayer commented on docs/guide/upgrading.md
> +  locale: [customNames, customAddresses, de_CH, de, en, global],
I think examples should ideally be self contained. But then I think this becomes too long to have in the migration guide and should be moved to the Localisation guide. 

Something like 

"If the prebuilt faker instances don't match your needs, for example if you want to add custom data, or not have English as the final fallback language, it is now possible to build a more flexible faker instance. For more details see localisation.html

2023-03-05 17:30 UTC, ST-DDT commented on docs/guide/upgrading.md
> +  locale: [customNames, customAddresses, de_CH, de, en, global],
I removed it as I already have a link to the localization guide a few lines below this.
I extended the localization with an actual overwrite.

2023-03-05 17:34 UTC, ST-DDT commented on docs/guide/upgrading.md
> +const a = customFaker.person.firstName();
Done

2023-03-05 18:36 UTC, Shinigami92 approved these changes

2023-03-05 18:48 UTC, xDivisionByZerox approved these changes

2023-03-06 17:15 UTC, Shinigami92 commented
@matthewmayer do you have any more reviews you want to have into the PR before merging?
Otherwise pls approve so your hard blocking `change request` goes away

2023-03-07 01:44 UTC, matthewmayer approved these changes

2023-03-07 01:45 UTC, matthewmayer commented
> @matthewmayer do you have any more reviews you want to have into the PR before merging? Otherwise pls approve so your hard blocking `change request` goes away

sorry my bad i didnt realise that blocked merge. approved now.

I have some further ideas for improving migration guide but that can be saved for a seperate PR.

2023-03-07 09:09 UTC, merged

2023-03-07 09:22 UTC, Shinigami92 commented
🎉 

I will try to find some time the next days to address #1748 again
Thanks to all of you to bring this forward
This was the most huge "bloker" / "stone" in our way to proceed to a new future of Faker 🙂