fix(locale): filter inappropriate words in the en locale - part 2
faker-js/faker pull request #1745
Opened 2023-01-17 02:40 UTC by matthewmayer

Following on from #1633

I ran the remaining words against https://github.com/zacanger/profane-words and found quite a few more words to remove. 

Several of these are borderline, but the existing lists are so long I think there's little disadvantage in removing all of them.

2023-01-17 09:36 UTC, ST-DDT reviewed
I'm quite unsure about the filter and being a non-native speaker doesn't really help either.

Some words gets filtered, some other don't and I have trouble understanding why.
E.g. `lust` got removed but `lustrous` didn't.

2023-01-17 09:36 UTC, ST-DDT commented on src/locales/en/word/noun.ts
> -  'bombing',
If you remove one, please also remove the others.

2023-01-17 09:36 UTC, ST-DDT commented on src/locales/en/word/noun.ts
> -  'terrorist',
If you remove `terrorist`, then you might also want to remove `terrorism`.

2023-01-17 09:36 UTC, ST-DDT commented on src/locales/en/word/verb.ts
>    'whizz',
Maybe remove both variants?

2023-01-17 09:36 UTC, ST-DDT commented on src/locales/en/word/verb.ts
>    'slaver',
Maybe remove `slaver` as well?

2023-01-17 09:36 UTC, ST-DDT commented on src/locales/en/word/verb.ts
>    'kill',
You did remove murder, should we remove kill as well?

2023-01-17 09:36 UTC, ST-DDT commented on src/locales/en/word/noun.ts
>    'crackers',
We should either remove them all or none of them.
(For me a cracker is a salty cockie)

2023-01-17 09:38 UTC, ST-DDT commented
Thanks for your time for checking the word lists.

2023-01-17 10:44 UTC, matthewmayer commented
Lust means strong sexual desire

Lustrous means shiny

Different etymologies!

I am a native English speaker  and I can generally understand why words were removed.

2023-01-17 10:46 UTC, matthewmayer commented
sometimes the words have both innocent and slang meanings, so a `beaver` can be an animal or slang for female genitalia, a `cracker` can be a snack or a rude word for a white person.

2023-01-17 10:48 UTC, matthewmayer commented
agree with your comments about the variants, i'll go through and have a second pass later.

2023-01-17 11:50 UTC, ST-DDT commented on src/locales/en/word/noun.ts
> -  'crackers',
If we remove words with duplicate meanings, then what about crack.
I know it can be a crack in a rock but also the drug. (or is this another lost in translation cases?)

2023-01-17 11:50 UTC, ST-DDT commented on src/locales/en/word/verb.ts
>    'kidnap',
I think we don't need this one either.

2023-01-18 09:05 UTC, ST-DDT approved these changes, later dismissed
Looks good to me, but the tests are failing.

2023-01-18 09:45 UTC, Shinigami92 commented
Looks like CI runs into errors

2023-01-18 10:52 UTC, ST-DDT requested changes

2023-01-18 10:52 UTC, ST-DDT commented on langs.js
> +}
I think you accidentally committed some debug code.

2023-01-18 11:11 UTC, ST-DDT approved these changes

2023-01-18 12:19 UTC, import-brain approved these changes

2023-01-18 13:40 UTC, Shinigami92 approved these changes

2023-01-18 20:15 UTC, merged