feat: add global locale
faker-js/faker pull request #1748
Opened 2023-01-17 20:08 UTC by Shinigami92

closes #1441

this adds a global locale that can later be used as the fallback for everything
it contains just generic data not related to a locale specifically, like e.g. css_space which are the same in every locale in the world

2023-01-17 20:21 UTC, Shinigami92 commented
As we have currently not the possibility to declare multiple stacked `localeFallback`, this PR need to be done in conjunction with

- #1735

there we can finally use e.g. `locale: [en_IN, en, global],`

2023-01-17 20:29 UTC, Shinigami92 reviewed
This is (IMO) currently blocked by #1735, but @ST-DDT please let me know if this is going in the right direction as you expected

2023-01-17 20:29 UTC, Shinigami92 commented on src/definitions/color.ts
> +   */
I'm thinking if we should add a line to indicate that this is intended for the global data
theoretically it is/was possible to call `colorByCSSColorSpace` with `cssSupportedSpace`, but actually `cssSupportedSpace` returns string and therefore needs to be checked manually anyways

2023-01-17 20:34 UTC, Shinigami92 commented on src/locale/global.ts
> +  },
This needs to be
```suggestion
  locale: [global],
```
after #1735 got merged

2023-01-17 20:56 UTC, ST-DDT commented on src/modules/color/index.ts
> +  | 'prophoto-rgb';
AFAICT these types aren't used anywhere.
If we actually need them inside of methods, then I would keep them as an implementation detail and not global data.
Having a matching return type for the other methods option sounds quite useful.

2023-01-17 20:56 UTC, ST-DDT commented on src/definitions/color.ts
> +   */
I wouldn't explicitly mark them as such, because then users might feel discouraged to replace them with their own set.
However, a method takes it as an input parameter so I don't think that the method should use the global data.

(same as we don't put SexTypes enum values into the global list.

2023-01-17 21:01 UTC, Shinigami92 commented on src/definitions/color.ts
> +   */
So should we convert them to enums? :thinking:

2023-01-17 21:04 UTC, Shinigami92 commented
Okay will revert the color, and potentially convert the color related things to enums in another PR
Like SexType.

But I can proceed with stuff like emoji and other already locales that are in `en` right now

2023-01-17 21:06 UTC, ST-DDT commented on src/definitions/color.ts
> +   */
Sounds like a good idea. But maybe in a different PR.

2023-01-17 21:09 UTC, Shinigami92 commented on src/definitions/color.ts
> +   */
yes yes totally in another PR :ok_hand:

2023-01-27 17:24 UTC, Shinigami92 commented
TBD

Maybe move to global?
- finance->currency
- science->chemicalElement
- science->unit

Maybe move to another locale?
- location->state(_abbr) -> en US

Maybe purge?
- business->credit_card_types
- internet->avatar_uri

2023-01-27 20:19 UTC, ST-DDT submitted a review, later dismissed

2023-01-27 21:03 UTC, Shinigami92 commented
@ST-DDT thx for you approval, but before #1735 is not merged, we cannot proceed with this PR as well

2023-03-07 13:26 UTC, ST-DDT commented
https://github.com/faker-js/faker/pull/1735 is merged, so this is no longer blocked.

Most/All(?) of the merge conflicts can be solved by running `pnpm run preflight`.

2023-03-07 13:28 UTC, ST-DDT commented
TODO:

- [ ] Add `global` to the generated fallback locales in the Faker constructor args and adjust the `generate:locales` script to handle the global locale properly.

2023-03-07 13:29 UTC, ST-DDT commented on src/locale/global.ts
> +  },
or just `global`

2023-03-07 14:17 UTC, matthewmayer requested changes

2023-03-07 14:17 UTC, matthewmayer commented on src/locale/global.ts
> +  locale: 'global',
This seems backwards. Shouldn't en fall back to global rather than vice versA?

2023-03-07 14:22 UTC, ST-DDT commented on src/locale/global.ts
> +  locale: 'global',
This is a draft that needs to be rebased.
You commented on the old part.

2023-03-07 14:24 UTC, matthewmayer commented on src/locale/global.ts
> +  locale: 'global',
Ok cool. So every locale will fall back to global at the end?

2023-03-07 14:25 UTC, matthewmayer commented on src/locale/global.ts
> +  locale: 'global',
...but you would never actually choose global as your locale?

2023-03-07 14:34 UTC, ST-DDT commented on src/locale/global.ts
> +  locale: 'global',
> Ok cool. So every locale will fall back to global at the end?

The pre-built faker instances yes.

> ...but you would never actually choose global as your locale?

There will be a fakerGLOBAL instance.

2023-03-07 15:45 UTC, Shinigami92 commented on src/modules/random/index.ts
> +
TODO: This fix need to be outsourced to its own PR

2023-03-07 16:31 UTC, Shinigami92 commented on src/modules/color/index.ts
> -  'rec2020',
Do this in another PR

2023-03-07 16:38 UTC, matthewmayer commented
i don't think color/space should be moved to global? Those are English names, not identifiers. For example in French you say RVB not RGB https://fr.wikipedia.org/wiki/Rouge_vert_bleu

2023-03-07 16:42 UTC, matthewmayer commented
Similarly finance/currency has English names of currencies. A "pound" is a "livre" in French.

2023-03-07 16:44 UTC, matthewmayer commented
also science/chemicalElement and science/unit?

2023-03-07 16:51 UTC, Shinigami92 commented
> Similarly finance/currency has English names of currencies. A "pound" is a "livre" in French.
> also science/chemicalElement and science/unit?

As far as I remember, we discussed in a previous team meeting, that we want to support the third layer of object-values
So we need another PR to e.g. provide the possibility to override `finance.currency.name`

2023-03-07 16:55 UTC, Shinigami92 commented on src/modules/color/index.ts
> -  'rec2020',
https://github.com/faker-js/faker/pull/1910

2023-03-07 17:22 UTC, matthewmayer commented
> > Similarly finance/currency has English names of currencies. A "pound" is a "livre" in French.
> > also science/chemicalElement and science/unit?
> 
> As far as I remember, we discussed in a previous team meeting, that we want to support the third layer of object-values So we need another PR to e.g. provide the possibility to override `finance.currency.name`

but then you'd have to repeat the codes in the other locale anyway, otherwise you wouldnt know which currency "livre" referred to?

2023-03-07 17:28 UTC, Shinigami92 commented
> > > Similarly finance/currency has English names of currencies. A "pound" is a "livre" in French.
> > > also science/chemicalElement and science/unit?
> > 
> > 
> > As far as I remember, we discussed in a previous team meeting, that we want to support the third layer of object-values So we need another PR to e.g. provide the possibility to override `finance.currency.name`
> 
> but then you'd have to repeat the codes in the other locale anyway, otherwise you wouldnt know which currency "livre" referred to?

Ah yeah, so like `code` would serve as a "primary key"... which we originally didn't want (as far as I remember)
We have a meeting upcoming thursday

2023-03-07 20:57 UTC, ST-DDT commented
> As far as I remember, we discussed in a previous team meeting, that we want to support the third layer of object-values
> So we need another PR to e.g. provide the possibility to override `finance.currency.name`

I dont remember that and it would have other side effects that would negatively impact the project.
E.g. you can no longer check whether person.first_name.xyz exists for that locale.

2023-03-07 21:06 UTC, Shinigami92 commented
> I dont remember that and it would have other side effects that would negatively impact the project.
> E.g. you can no longer check whether person.first_name.xyz exists for that locale.

Ah yes, you are right
I confused my own memory with `[...] we should add support for it in the fake method.`
My memory was just wrong

2023-03-11 20:06 UTC, ST-DDT commented
Looks like we didn't publish our team decision here either:

**Team Decision**

- We will keep the names of things as part of the locale data set and won't join different sources to create a single complex object.
- I don't remember and we didn't note our decision regarding the use of English names in the global locale. Does anyone else remember?

2023-03-16 16:24 UTC, ST-DDT commented
**Team Decision**

- We don't want to add/move data to the global locale that contain specifically English names/translations such as currency names.

Pro:

- @xDivisionByZerox 
- @ST-DDT 

Contra:

- @Shinigami92

2023-03-17 08:55 UTC, matthewmayer requested changes

2023-03-17 08:55 UTC, matthewmayer commented on src/locales/global/hacker/abbreviation.ts
This file is already localized e.g. in `ru` 
https://github.com/faker-js/faker/blob/next/src/locales/ru/hacker/abbreviation.ts

2023-03-17 19:32 UTC, Shinigami92 commented on src/locales/global/hacker/abbreviation.ts
globales are always allowed to getting overridden, that is literally the reason why we moved stuff to a global locale instead of using static code

2023-03-17 21:49 UTC, ST-DDT approved these changes, later dismissed

2023-03-18 01:50 UTC, matthewmayer requested changes
Needs documentation in various places
- localisation page
- migration page 

Explain that if you are building custom locale that final should usually be the final fallback

Explain that you shouldn't use the fakerGLOBAL instance alone?

2023-03-18 09:17 UTC, ST-DDT commented
> Explain that if you are building custom locale that final should usually be the final fallback

Yes.

> Explain that you shouldn't use the fakerGLOBAL instance alone?

IMO there is no need for it.
If you think using global is a good choice for using it, then you sure can do that.
You will definitely get a very small bundle size when using it.
We just have to clarify that is intended as a fallback. (maybe add an explanation to the bottom of the locales list in the docs.

2023-03-18 10:26 UTC, matthewmayer commented
> > Explain that you shouldn't use the fakerGLOBAL instance alone?
> 
> IMO there is no need for it. If you think using global is a good choice for using it, then you sure can do that. You will definitely get a very small bundle size when using it. We just have to clarify that is intended as a fallback. (maybe add an explanation to the bottom of the locales list in the docs.

i think without further explanation/documentation `fakerGLOBAL` sounds like it contains *all* data for all the locales, not "a small subset of data which is conmmon to all locales". Could also consider naming it something different like "base" or "root"?

2023-03-18 13:46 UTC, Shinigami92 commented
Here is a vote: https://strawpoll.com/polls/e6Z28p39MnN

2023-03-23 17:46 UTC, ST-DDT commented
**Poll Decision**

- ``base`` has won

2023-03-23 18:08 UTC, matthewmayer commented
Rename the PR title also?

![image](https://user-images.githubusercontent.com/152770/227305642-d6e51010-eee8-4b49-8d46-d1c09cabcfae.png)

2023-03-23 18:13 UTC, ST-DDT submitted a review, later dismissed

2023-03-24 02:44 UTC, matthewmayer commented on docs/guide/localization.md
I think we could add a note here about what the base locale is.

2023-03-24 02:58 UTC, matthewmayer commented on src/locales/base/hacker/abbreviation.ts
this is localized in some languages e.g. `ru`

2023-03-24 07:10 UTC, Shinigami92 commented on docs/guide/localization.md
Please move on and use the suggestion feature in GitHub

<img width="200" alt="image" src="https://user-images.githubusercontent.com/7195563/227449530-d7105239-0ccb-415b-8617-9bfc90029b35.png">

2023-03-24 07:10 UTC, Shinigami92 commented on src/locales/base/hacker/abbreviation.ts
That was resolved here: https://github.com/faker-js/faker/pull/1748#discussion_r1140636887

The team agreed with me that everything is correct: the base locale can be overridden if wanted, and so is here in ru locale

2023-03-28 07:18 UTC, Shinigami92 commented on docs/guide/localization.md
@matthewmayer please suggest something or lead me in the right direction

2023-03-28 07:54 UTC, matthewmayer commented on docs/guide/localization.md
What's the logic on what information is included in the base locale? My understanding is that it would be only data which is not locale specific. But that seems contradicted by the fact that hacker.abbreviation is localised. Whatever the logic is should be documented here.

2023-03-28 08:11 UTC, Shinigami92 commented on docs/guide/localization.md
@matthewmayer please have a look into https://github.com/faker-js/faker/pull/1748/commits/f5901e4bafc6ab633d7ecf9a2dbb6d77e9ac94ae and tell me if this satisfies your needs

@ST-DDT please tell me if this is correct what I wrote

2023-03-28 08:22 UTC, matthewmayer commented on docs/guide/localization.md
I think that will do for now. I still find it a bit unclear why say `faker.hacker.abbreviation` is includes in `base` but not `faker.lorem.*` if the rule is "Content that should work in all languages, but could be overridden in some cases"

2023-03-28 08:22 UTC, matthewmayer approved these changes

2023-03-28 08:27 UTC, matthewmayer requested changes

2023-03-28 08:27 UTC, matthewmayer commented on docs/guide/localization.md
> +- `base` is the base locale definition which contains definitions that can be used in every language (like e.g. a set of emojis).
```suggestion
In this example there are 5 locales. Each of these is checked in order, and the first locale which contains the requested data will be used:

- `customLocale` is your custom locale definition which will override all other fallback definitions.
- `de_CH` is a specific locale definition that overrides some German definitions with `CH` (Switzerland) data.
- `de` is a generic `de` (German) locale definition.
- `en` is a generic `en` (English) locale definition. This is our most complete locale, so we add it to fill some gaps. Depending on your needs, you might want or not want to have it as a fallback.
- `base` is the base locale definition which contains definitions that can be used in every language (e.g. emojis).
```

2023-03-28 08:55 UTC, ST-DDT commented on docs/guide/localization.md
> +- `base` is the base locale definition which contains definitions that can be used in every language (like e.g. a set of emojis).
I would add a newline between the "introduction" and the list.
Also maybe add an additional hint to en like: `This is our most complete locale, so we add it to fill some gaps. Depending on your needs, you might want or not want to have it as a fallback especially for languages with non latin characters.`

2023-03-28 08:58 UTC, matthewmayer commented on docs/guide/localization.md
> +- `base` is the base locale definition which contains definitions that can be used in every language (like e.g. a set of emojis).
agreed although i dont think the "especially for languages with non latin characters" is needed.

2023-03-28 08:58 UTC, matthewmayer commented on docs/guide/localization.md
> +- `base` is the base locale definition which contains definitions that can be used in every language (like e.g. a set of emojis).
updated suggestion

2023-03-28 09:11 UTC, ST-DDT commented on docs/guide/localization.md
I'm also not sure about lorem, but we can adjust that later if needed.

As for `hacker.abbreviation`: I also maintain a repository with Chinese users that also open issues in their native language.
What I noticed is that in most cases IT-components or libraries are still in latin letters making them one of the few parts I can actually read without a translator.

2023-03-28 09:48 UTC, ST-DDT approved these changes

2023-03-28 10:17 UTC, matthewmayer approved these changes

2023-03-29 08:22 UTC, merged