refactor(location): Throw error if state is unknown
faker-js/faker pull request #1760
Opened 2023-01-21 23:16 UTC by 0916dhkim

2023-01-22 09:35 UTC, ST-DDT reviewed
If you have trouble running the tests locally, you can use `CI=true pnpm run test watch`.

2023-01-22 09:35 UTC, ST-DDT commented on src/modules/location/index.ts
> +      throw new Error(`${state} is invalid.`);
Please throw a FakerError instead.
Maybe also add a list with allowed keys and a hint where these keys are comming from.
E.g. `faker.definitions.location.postcode_by_state only contains data for [...]`

2023-01-22 09:47 UTC, matthewmayer requested changes
This documentation needs to be updated to reflect that an error would now be thrown. Also I think it could be make clearer this doesn't work in the default `en` locale, but only in `en_US`.

2023-01-22 09:49 UTC, matthewmayer commented on src/modules/location/index.ts
> +      throw new Error(`${state} is invalid.`);
you might want to have different errors for the 
1. where the locale doesn't support postcode_by_state at all (e.g. en, de)
1. where the locale does support postcode_by_stat, but this is an unknown state (say XX in en_US).

2023-01-22 10:28 UTC, ST-DDT commented on src/modules/location/index.ts
> +      throw new Error(`${state} is invalid.`);
We will handle the first part centrally: https://github.com/faker-js/faker/issues/893#issuecomment-1397329605

- #893

2023-01-22 11:05 UTC, matthewmayer commented on src/modules/location/index.ts
> +      throw new Error(`${state} is invalid.`);
hmm i think this is a weird edge case though where the fallback locale (en) doesn't contain the data, which is unusual.

2023-01-22 16:45 UTC, 0916dhkim commented on src/modules/location/index.ts
> +      throw new Error(`${state} is invalid.`);
@ST-DDT Thanks for the review 🙏 
I'll use `FakeError` instead + attach available keys.

2023-02-03 04:44 UTC, 0916dhkim commented on src/modules/location/index.ts
> +      throw new Error(`${state} is invalid.`);
I have fixed the code to throw FakerError and updated the docstring, but I'm not sure how to make the tests pass. It looks like `en` locale is used as default in `seededTests`, and `zipCodeByState` will always throw with `en`.

2023-02-20 12:17 UTC, Shinigami92 commented
The unresolved conflict brings an issue: the `state` parameter is required and therefore we have two options:

1. We just allow `zipCodeByState({ state: '...', .../* potential other options */ })`
2. We allow `zipCodeByState({ state: '...', .../* potential other options */ })` as well as `zipCodeByState('state', { /* potential other options */ })`

Once we said we only want to have method calls (outside the helpers module) that can always be called without passing any arguments. In this case state is always required otherwise it would always throw an error.

We will discuss this in an upcoming meeting.

2023-02-23 17:38 UTC, ST-DDT commented
**Team Decision**

- We want to merge zipCode and zipCodeByState into a single method instead (https://github.com/faker-js/faker/issues/1346#issuecomment-1407728227)
- It will still throw an error if the state doesn't have a config.

---

Thanks for your contribution anyway!

2023-02-23 17:38 UTC, closed without merging