docs: focus api search immediately
faker-js/faker pull request #1774
Opened 2023-01-23 23:11 UTC by ST-DDT

When visiting the API page I press either `Ctrl+F` or use the build-in search function to search for a specific method.
By focusing the search input directly the user can start typing immediately to apply the filtering.

2023-01-24 13:00 UTC, matthewmayer requested changes

2023-01-24 13:00 UTC, matthewmayer commented on docs/api/ApiIndex.vue
> +          ref="apiFilter"
can't you just use [autofocus](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus), no JS required

2023-01-24 13:04 UTC, xDivisionByZerox commented on docs/api/ApiIndex.vue
> +          ref="apiFilter"
`autofocus` is also much better for accessibility since screen readers get the information and can handle them. They can't do that with JS.

2023-01-24 14:55 UTC, ST-DDT commented on docs/api/ApiIndex.vue
> +          ref="apiFilter"
That property only seems to work when loading the target page directly `http://localhost:5173/api/`
When opening `http://localhost:5173/` and navigating to `api`, then it does not work.

2023-01-24 18:04 UTC, Shinigami92 submitted a review, later dismissed

2023-01-25 05:38 UTC, import-brain submitted a review, later dismissed

2023-01-26 01:44 UTC, matthewmayer commented
The downside of this change is that you can no longer easily navigate the page with up arrow/down arrow etc (i often scroll pages with Down or fast-scroll with Cmd+Down)

2023-01-26 16:02 UTC, Shinigami92 commented
> The downside of this change is that you can no longer easily navigate the page with up arrow/down arrow etc (i often scroll pages with Down or fast-scroll with Cmd+Down)

That is odd :confused: 
Trading one a11y vs another is not really worth it
Does this also apply if only `autofocus` is applied?

2023-01-26 19:08 UTC, ST-DDT commented
> Does this also apply if only `autofocus` is applied?

No, even if you click in the field yourself, the navigation gets unavailable.

---

@matthewmayer How about switching to a keypress event.
If the user types a character a-z, then the input field is focussed automatically and the filter is applied.
If you exit the field, then the key-binding gets disabled.

2023-01-27 00:33 UTC, matthewmayer commented
Sounds good
> > Does this also apply if only `autofocus` is applied?
> 
> 
> 
> No, even if you click in the field yourself, the navigation gets unavailable.
> 
> 
> 
> ---
> 
> 
> 
> @matthewmayer How about switching to a keypress event.
> 
> If the user types a character a-z, then the input field is focussed automatically and the filter is applied.
> 
> If you exit the field, then the key-binding gets disabled.

2023-02-01 18:12 UTC, ST-DDT commented
Current behavior:

* Type ``[a]`` - ``[z]`` to focus the search input
* Press ``[Esc]`` to exit the input
* Press ``[Esc]`` a second time to clear the input

2023-02-13 18:56 UTC, xDivisionByZerox approved these changes
I don't think we need to think too hard about this. Our website doesn't have that much trafik and if someone doesn't like the behavior they can open an issue.

2023-02-14 11:00 UTC, matthewmayer approved these changes

2023-02-14 11:06 UTC, Shinigami92 approved these changes
This needs a maintainer approval to get merged
I don't like it, but I don't want to block it as I don't have better ideas on my side

2023-02-14 14:35 UTC, merged