#1777 Improvements to Dutch name generation, in particular regarding affixes
faker-js/faker pull request #1778
Opened 2023-01-24 15:50 UTC by amarillion

Addresses #1777, plus some minor improvements to Dutch name generation. 
I've based this on PR #1637 (fullname name patterns) assuming that will be approved as well.

2023-02-02 13:46 UTC, ST-DDT commented
https://github.com/faker-js/faker/pull/1637 has been merged. Please rebase.

2023-02-05 12:14 UTC, amarillion commented
Rebased onto next

2023-02-05 13:15 UTC, matthewmayer approved these changes, later dismissed

2023-02-05 20:38 UTC, import-brain submitted a review, later dismissed
Please put the last name list in alphabetical order

2023-02-06 07:33 UTC, amarillion commented
I've sorted the list of names ASCIIbetically. NB this is not the Dutch sorting order.

2023-02-06 15:57 UTC, import-brain commented
> I've sorted the list of names ASCIIbetically. NB this is not the Dutch sorting order.

Thank you! @faker-js/maintainers Should we sort the names ASCIIbetically or the Dutch way?

2023-02-06 19:34 UTC, amarillion commented
Oh, and I misspoke - it's not ASCIIbetical (because that would imply case-sensitive sorting - Z before a). It's currently sorted with regular English case-insensitive sorting.

So, in a nice example of "be careful what you wish for" we have the following sorting options:

1. case sensitive sorting (ASCIIbetical):  Kok < Visser < de Boer
2. case insensitive sorting (English): Kok < de Boer < Visser
3. case insensitive sorting (Dutch): de Boer < Kok < Visser

The one that is implemented with the latest commit is #2. So, which sorting method should I use? Personally, I don't mind either way.

2023-02-06 23:27 UTC, ST-DDT commented
One of the reasons why we want the sorted lists is to aid in the review process to detect similar or identical entries faster.
So I think a case intensive sort is definitely required.
For the start, we should use (2) English locale. We just have to make sure that (our tests/scripts) this also works for non-English users.
@amarillion The "Dutch case insensitive sorting" applies only to names or is the alphabet itself sorted differently from the English one?

2023-02-06 23:36 UTC, ST-DDT requested changes

2023-02-06 23:36 UTC, ST-DDT commented on src/locales/nl/person/last_name.ts
> +// Source: https://nl.wikipedia.org/wiki/Lijst_van_meest_voorkomende_achternamen_van_Nederland
Can you also add one or two other sources for these names into the list, so we just don't copy the entire list 1:1?
(I would like to avoid license issues: Wiki-Commons or whatever the original list was published under != MIT)

2023-02-07 08:13 UTC, amarillion commented
I've added two more sources for the family names.

Since the purpose of sorting is detecting duplicates, I think the current English sorting is fine and we'll leave it at that.

2023-02-07 08:14 UTC, amarillion commented on src/locales/nl/person/last_name.ts
> +// Source: https://nl.wikipedia.org/wiki/Lijst_van_meest_voorkomende_achternamen_van_Nederland
Done.

2023-02-08 23:39 UTC, ST-DDT commented
> I've added two more sources for the family names.

Well, you added more links, but you didn't add any new names, so it is basically still the same list from the first source in the list.
(And thus doesn't solve the legal implications)

[`ff4dee0` (#1778)](https://github.com/faker-js/faker/pull/1778/commits/ff4dee04c2efce1746e1b8ebf2f2594c2f490d9c)

2023-02-09 08:13 UTC, amarillion commented
I don't get what you mean by legal implications. It's quite obvious that wikipedia doesn't own this list, and that the original source is in fact from https://www.meertens.knaw.nl/nfb/documenten/top100.pdf, as stated in the article. 

A list of "top 100 most occurring family names in 2007" are facts, and facts are in fact not copyrightable.

2023-02-09 08:29 UTC, amarillion commented
However, if it helps I've made a small modification to the list so it's no longer exactly the same as the source.

2023-02-09 08:46 UTC, ST-DDT commented
> A list of "top 100 most occurring family names in 2007" are facts, and facts are in fact not copyrightable.

IANAL: The facts itself might not be, but the work to compile it may be or at least, some claim it to be: https://blog.polco.us/copyright-apply-survey

Thanks for your efford to address this, but 1% differnce might not be enough.

2023-02-09 09:09 UTC, matthewmayer commented
Maybe go back to the original `nl` last_name list and just make some changes to add some more tussenvoegsel names, using your own knowledge/judgement rather than relying on a single source?

2023-02-09 13:26 UTC, amarillion commented
All right, I made a major modification to the list. It's now a fully original compilation of names, a random selection of various sources created by me personally.  Any resemblance with any other list you might find is purely coincidental, of course lists of common names are bound to have overlap.

> Maybe go back to the original nl last_name list and just make some changes to add some more tussenvoegsel names, using your own knowledge/judgement rather than relying on a single source?

Funnily enough, after adding the appropriate tussenvoegsels, nearly every name on the original list is also in the top 100 list. I only detected two differences: 'Klein', which I added, and 'Stichting', which isn't a family name.

2023-02-11 12:12 UTC, ST-DDT approved these changes

2023-02-11 12:55 UTC, matthewmayer approved these changes

2023-02-11 22:50 UTC, import-brain approved these changes

2023-02-12 16:40 UTC, merged

2023-02-13 08:08 UTC, amarillion commented
Nice work guys, I appreciate your attention to detail!