refactor(location): normalize signatures
faker-js/faker pull request #1784
Opened 2023-01-26 23:53 UTC by xDivisionByZerox

# This is currently WIP

Part of #1349.

Standardize all function signatures in the `LocationModule` to support an options object.

2023-01-27 00:26 UTC, ST-DDT commented on src/modules/location/index.ts
> +    options:
IMO we should remove the parameter instead.

2023-01-27 00:26 UTC, ST-DDT commented on src/modules/location/index.ts
> +          alphaCode?: 'alpha-2' | 'alpha-3';
Maybe `variant`?

2023-01-28 13:57 UTC, xDivisionByZerox commented on src/modules/location/index.ts
> +    options:
If we want to remove the option entirely, I would suggest to do that in a separate PR since this PR aims to standardize all function signatures, not change the current behavior.

2023-01-28 14:01 UTC, xDivisionByZerox commented
The PR is now open for review. For simplicity (on my side) I literally took the previous parameter and simply wrapped it in an options object.

I highly encourage all reviewers to discuss the "new" property names in the options argument foreach function.

2023-01-28 14:55 UTC, Shinigami92 commented on src/modules/location/index.ts
> +    options:
Yes, I'm with @xDivisionByZerox on that, lets do this in its own PR
If no one want to work on this right now, open an issue for that so we mark this discussion here as "resolved"

2023-01-28 15:15 UTC, Shinigami92 commented on src/modules/location/index.ts
> +           * @default
JSDoc tag `@default` should take a real JS snipped as value as this gets rendered in IDEs as that

But before thinking further about what this could be, lets first see if this gets removed as suggested by @ST-DDT

2023-01-28 15:15 UTC, Shinigami92 commented on src/modules/location/index.ts
> +  zipCodeByState(options: string | { state?: string } = {}): string {
Could you also add JSDoc to the `state` options property itself?

2023-01-28 15:15 UTC, Shinigami92 commented on src/modules/location/index.ts
> +           * @default `'alpha-2'`.
```suggestion
           * @default 'alpha-2'
```

2023-01-28 15:15 UTC, Shinigami92 commented on src/modules/location/index.ts
> +       * @default `90`.
```suggestion
       * @default 90
```

2023-01-28 15:15 UTC, Shinigami92 commented on src/modules/location/index.ts
> +       * @default `-90`.
```suggestion
       * @default -90
```

2023-01-28 15:15 UTC, Shinigami92 commented on src/modules/location/index.ts
> +       * @default `4`.
```suggestion
       * @default 4
```

2023-01-28 15:15 UTC, Shinigami92 commented on src/modules/location/index.ts
> +       * @default `180`.
```suggestion
       * @default 180
```

2023-01-28 15:15 UTC, Shinigami92 commented on src/modules/location/index.ts
> +       * @default `-180`.
```suggestion
       * @default -180
```

2023-01-28 15:15 UTC, Shinigami92 commented on src/modules/location/index.ts
> +       * @default `4`.
```suggestion
       * @default 4
```

2023-01-28 15:15 UTC, Shinigami92 commented on src/modules/location/index.ts
> +           * @default `false`.
```suggestion
           * @default false
```

2023-01-28 15:15 UTC, Shinigami92 commented on src/modules/location/index.ts
> +           * @default `false`.
```suggestion
           * @default false
```

2023-01-28 15:15 UTC, Shinigami92 commented on src/modules/location/index.ts
> +           * @default `false`.
```suggestion
           * @default false
```

2023-01-28 15:19 UTC, xDivisionByZerox commented on src/modules/location/index.ts
> +  zipCodeByState(options: string | { state?: string } = {}): string {
Yes. I simply forgot it at that specific location.

2023-01-28 15:21 UTC, xDivisionByZerox commented on src/modules/location/index.ts
> +           * @default
So in this case it should state `@default this.faker.definitions.location.postcode`. Did I understand you correctly?

2023-01-28 15:23 UTC, Shinigami92 commented on src/modules/location/index.ts
> +           * @default
yes

2023-02-01 22:46 UTC, ST-DDT requested changes

2023-02-01 22:46 UTC, ST-DDT commented on src/modules/location/index.ts
> +   * @param options.alphaCode The code to return. Can be either `'alpha-2'` (2 letter code)
```suggestion
   * @param options.variant The variant to return. Can be either `'alpha-2'` (2 letter code)
```

2023-02-01 22:46 UTC, ST-DDT commented on src/modules/location/index.ts
> +    options: {
This is a breaking signature change.

2023-02-01 22:46 UTC, ST-DDT commented on src/modules/location/index.ts
> +    options: {
This is a breaking signature change.

2023-02-02 09:08 UTC, xDivisionByZerox commented on src/modules/location/index.ts
> +    options: {
I would allow both signatures (multi args and options) in this PR and create a separate PR for each breaking change to make them more visible?

2023-02-02 13:34 UTC, ST-DDT commented on src/modules/location/index.ts
> +    options: {
If you allow both options, then its not breaking. So AFAICT you just have to re-add support for the old signature.

2023-02-02 21:18 UTC, ST-DDT approved these changes

2023-02-02 21:50 UTC, Shinigami92 approved these changes
I assume the deprecation will be done in another PR for better reviewability?

2023-02-02 21:59 UTC, xDivisionByZerox commented
> I assume the deprecation will be done in another PR for better reviewability?

Actually, I wanted to deprecate each method in its own PR so it is visible in the changelog.

2023-02-04 00:18 UTC, merged