test(system): add valid 0 for cron
faker-js/faker pull request #1787
Opened 2023-01-27 16:46 UTC by Shinigami92

While working on
- #1645 

it reports an failure for https://github.com/faker-js/faker/actions/runs/4025222101/jobs/6918173202#step:7:302

but `0` is a valid digit for cron

2023-01-27 18:26 UTC, import-brain submitted a review, later dismissed

2023-01-27 20:00 UTC, ST-DDT requested changes, later dismissed

2023-01-27 20:00 UTC, ST-DDT commented on test/system.spec.ts
> +          const validResults = ['0', '1', '2', '3', '4', '5', '6', '*', '@'];
This can also generate 7-9 (minutes range from 0-59).

https://github.com/faker-js/faker/blob/86ae8b9d698f5b2c75214b0cfef869122a591001/src/modules/system/index.ts#L346
https://github.com/faker-js/faker/blob/86ae8b9d698f5b2c75214b0cfef869122a591001/src/modules/system/index.ts#L366-L369

2023-01-27 21:04 UTC, Shinigami92 commented on test/system.spec.ts
> +          const validResults = ['0', '1', '2', '3', '4', '5', '6', '*', '@'];
okay, I will include just all digits

2023-01-27 23:50 UTC, xDivisionByZerox commented on test/system.spec.ts
> +          const validResults = [...'0123456789'.split(''), '*', '@'];
I'm a bit confused. Numbers are considered non-standard cron expressions?

2023-01-28 15:28 UTC, Shinigami92 commented on test/system.spec.ts
> +          const validResults = [...'0123456789'.split(''), '*', '@'];
Uh, yeah the description text now looks weird to me as well :thinking: 
Did this just slipped to the review while this was added? Or is something differently meant by that or the test implementation shifted away from what it was originally?

Maybe @ST-DDT has some more insites to this as I also think he knows better about cron

2023-01-28 17:59 UTC, ST-DDT commented on test/system.spec.ts
> +          const validResults = [...'0123456789'.split(''), '*', '@'];
IMO the test should be rewritten to actually check that it "can return non standard expressions".

2023-01-28 18:01 UTC, Shinigami92 commented on test/system.spec.ts
> +          const validResults = [...'0123456789'.split(''), '*', '@'];
Okay, what are _non-standard_ cron expressions?

2023-01-28 18:06 UTC, ST-DDT commented on test/system.spec.ts
> +          const validResults = [...'0123456789'.split(''), '*', '@'];
See the implementation. Thats the `@daily` ones.

2023-01-29 13:49 UTC, Shinigami92 commented
This PR targeted the wrong goal and was meant to fix the shuffled tests
Now we want to change the whole implementation of the test itself
Therefore it's up to be grepped by someone who wants to fix it

2023-01-29 14:13 UTC, xDivisionByZerox commented
I'll provide a follow up PR which addresses this test reimplementation.

2023-01-29 14:21 UTC, xDivisionByZerox commented
After checking the source I noticed that the fix for the test was totally valid.
`includeNonStandard` is misleading in that way that it doesn't guarantee that a non standard expression is returned. Thats why we simply have to check whether a number/astrics (standard) or an `@` (non standard) is returned.

The title should probably simply be adjusted to state `'should be able to return non-standard cron expressions'`.

2023-01-29 14:36 UTC, xDivisionByZerox approved these changes

2023-01-29 16:00 UTC, import-brain approved these changes

2023-01-29 16:39 UTC, ST-DDT approved these changes

2023-01-29 16:47 UTC, merged