chore: add node version matrix
faker-js/faker pull request #179
Opened 2022-01-16 17:21 UTC by MohdImran001

Fixes #159 

@prisis please review

2022-01-16 17:25 UTC, Shinigami92 requested changes

2022-01-16 17:25 UTC, Shinigami92 commented on .github/workflows/ci.yml
> +        node_version: [12, 14, 16, 17]
You need to reuse the `node_version` down below in `actions/setup-node@v2`

2022-01-18 12:09 UTC, prisis commented
@MohdImran001 do you need help with it?

2022-01-18 12:12 UTC, MohdImran001 commented
Sorry I was a bit busy , I will complete this today.

2022-01-18 16:41 UTC, Shinigami92 requested changes

2022-01-18 16:41 UTC, Shinigami92 commented on .github/workflows/ci.yml
>            node-version: '16'
```suggestion
          node-version: 16
```

2022-01-18 16:42 UTC, MohdImran001 commented on .github/workflows/ci.yml
> +name: 'CI'
already done

2022-01-18 16:45 UTC, MohdImran001 commented on .github/workflows/ci.yml
> +
remove it from both testing and linting ?

2022-01-18 16:46 UTC, Shinigami92 commented on .github/workflows/ci.yml
> +
No only linting ^^

2022-01-18 17:23 UTC, Shinigami92 commented
We need to find out what the `npm ERR! google-closure-compiler-linux not accessible from google-closure-compiler`-error is
And why it fails with one test in windows :thinking:

2022-01-18 17:29 UTC, poyea commented on .github/workflows/ci.yml
> +            node_version: 16
```suggestion
            node_version: '16.x'
```

2022-01-18 17:33 UTC, poyea commented on .github/workflows/ci.yml
> +            node_version: 16
[Why this](https://github.com/faker-js/faker/blob/main/test/finance.unit.js#L181) is [taking so long](https://github.com/faker-js/faker/runs/4856849312?check_suite_focus=true#step:6:23415) on Windows?

2022-01-18 17:58 UTC, Shinigami92 commented on .github/workflows/ci.yml
> +            node_version: 16
> node_version: '16.x'

Why would this be needed? Theoretically it's the same
So I would suggest to not do that

2022-01-18 18:07 UTC, Shinigami92 commented
@MohdImran001 Please remove the dependency `"node-minify": "*",` and then run `rm -Rf node_modules package-lock.json && npm install`
Then commit both files: `package.json` and `packge-lock.json`

2022-01-18 18:17 UTC, poyea commented on .github/workflows/ci.yml
> +            node_version: 16
Indeed, I believe this is true due to semantic versioning. Well, I think this doesn't matter much, so it's OK

2022-01-18 18:19 UTC, poyea commented on .github/workflows/ci.yml
> +            node_version: 16
Btw, [this or similar options](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes) might be useful, I didn't look into the Windows issue though

2022-01-18 18:44 UTC, Shinigami92 commented
Nice, now node 14 and 12 is working :+1: 
But we need to find out why the one test in windows is failing

2022-01-18 21:28 UTC, Shinigami92 commented
It's actually this test:

https://github.com/faker-js/faker/blob/d72482b0a19c3e98b6c8ea96d6c8407711af60cc/test/finance.unit.js#L283-L299

2022-01-18 22:00 UTC, ST-DDT commented
I am unable to reproduce the test error on both my win11 and win10 computers.

2022-01-18 22:00 UTC, Shinigami92 commented
I hacked around it by conditionally disable the test on `win32`
At least it is better for now to have the other machines running all the tests, so in total we have 4x22k+ more tests running on node 12, 14 and mac and win
I will create an issue so we remember to fix this test later

2022-01-18 22:01 UTC, Shinigami92 approved these changes

2022-01-18 22:03 UTC, ST-DDT approved these changes

2022-01-18 22:05 UTC, griest024 approved these changes

2022-01-18 22:05 UTC, merged