feat(locale): add Serbian (Latin) language
faker-js/faker pull request #1801
Opened 2023-01-31 02:27 UTC by bdimitrovski

2023-01-31 03:24 UTC, import-brain reviewed
Please remove the duplicated values in your locale data as shown here

https://github.com/faker-js/faker/actions/runs/4050174605/jobs/6967813401

2023-01-31 08:43 UTC, bdimitrovski commented
@import-brain Done, the tests should be passing now.

2023-01-31 16:05 UTC, matthewmayer requested changes

2023-01-31 16:05 UTC, matthewmayer commented on src/locales/sr_RS/date/month.ts
> +    'decembar',
you can omit the `wide_context` array if identical to the standard array.

2023-01-31 16:05 UTC, matthewmayer commented on src/locales/sr_RS/date/month.ts
> +    'dec',
you can omit the `abbr_context` array if identical to the standard array.

2023-01-31 16:05 UTC, matthewmayer commented on src/locales/sr_RS/date/weekday.ts
> +    'subota',
can omit

2023-01-31 16:05 UTC, matthewmayer commented on src/locales/sr_RS/date/weekday.ts
> +  abbr_context: ['ned', 'pon', 'uto', 'sre', 'čet', 'pet', 'sub'],
can omit

2023-01-31 16:05 UTC, matthewmayer commented on src/locales/sr_RS/person/last_name.ts
> +  'Abadžija',
7000 names is a bit excessive? Nearly all locales have under 2000. Can it be trimmed?

2023-01-31 16:05 UTC, matthewmayer commented on src/locales/sr_RS/person/name.ts
> +  '{{person.female_first_name}} {{person.last_name}}',
don't need the male and female versions patterns. This will cause problems when [#1637](https://github.com/faker-js/faker/pull/1637) merges soon

2023-01-31 21:40 UTC, bdimitrovski commented on src/locales/sr_RS/person/name.ts
> +  '{{person.female_first_name}} {{person.last_name}}',
Removed.

2023-01-31 22:02 UTC, bdimitrovski commented on src/locales/sr_RS/person/last_name.ts
> +  'Abadžija',
We have very rich surname etymology, and dozens of variants of one single surname can occur, some of which are very unusual and fun, which makes it perfect for randomisation, and the possibilities are wonderful :) Nevertheless, I have reduced this to about 5000 and something, is that still too much? Or can we leave it at that?

2023-01-31 22:02 UTC, bdimitrovski commented on src/locales/sr_RS/date/weekday.ts
> +  abbr_context: ['ned', 'pon', 'uto', 'sre', 'čet', 'pet', 'sub'],
Done.

2023-01-31 22:02 UTC, bdimitrovski commented on src/locales/sr_RS/date/weekday.ts
> +    'subota',
Done.

2023-01-31 22:02 UTC, bdimitrovski commented on src/locales/sr_RS/date/month.ts
> +    'dec',
Done.

2023-01-31 22:02 UTC, bdimitrovski commented on src/locales/sr_RS/date/month.ts
> +    'decembar',
Done.

2023-02-01 01:05 UTC, matthewmayer commented on src/locales/sr_RS/person/last_name.ts
> +  'Abadžija',
In future there will be a limit of 1000 entries per definition, see https://github.com/faker-js/faker/issues/1802#issuecomment-1410953526

2023-02-01 10:23 UTC, bdimitrovski commented on src/locales/sr_RS/person/last_name.ts
> +  'Abadžija',
I see - so are you suggesting that I slash this down even more, and possibly keep it even below 1000?

2023-02-01 10:40 UTC, matthewmayer commented on src/locales/sr_RS/person/last_name.ts
> +  'Abadžija',
Paging @ST-DDT

2023-02-01 16:22 UTC, ST-DDT commented on src/locales/sr_RS/person/last_name.ts
> +  'Abadžija',
1000 is good for now.

2023-02-02 18:26 UTC, bdimitrovski commented on src/locales/sr_RS/person/last_name.ts
> +  'Abadžija',
Done and done. This should now be in mergeable state.

2023-02-02 22:04 UTC, Shinigami92 commented on src/locales/sr_RS/person/name.ts
> +export default ['{{person.first_name}} {{person.last_name}}'];
You need to apply name patterns to our new format using weighted objects

2023-02-03 01:25 UTC, matthewmayer commented on src/locales/sr_RS/person/name.ts
> +export default ['{{person.first_name}} {{person.last_name}}'];
if there's only a single value, should just be

```typescript
export default [
  { value: '{{person.firstName}} {{person.lastName}}', weight: 1 },
];
```

2023-02-06 08:57 UTC, bdimitrovski commented on src/locales/sr_RS/person/name.ts
> +export default ['{{person.first_name}} {{person.last_name}}'];
Done.

2023-02-06 11:00 UTC, bdimitrovski commented
@matthewmayer @ST-DDT when could we expect this to land?

2023-02-06 12:32 UTC, matthewmayer commented
Probably best to use your own fork if you are relying on its functionality in the short term. 

https://blaipratdesaba.com/how-to-use-an-npm-node-module-that-has-been-forked-b7dd522fdd08

Even when it lands it will only be going into 8.0.0 which is still in alpha.

2023-02-09 00:08 UTC, ST-DDT commented
We are currently busy and thus are a little bit slower with the reviews.
AFAIK neither of us has any Serbian skills, so it takes a bit of time for us to review.
We will review/merge it when we have time, probably soon. 
You can speed up the process by getting reviews from a third-party.

As for a release, we might release another v8 alpha in the next month (not sure yet),
but the actual v8 stable release will take **at least** one or two months.

-----------

Also I noticed, that there are two "Serbian" languages, that seem to have the same locale code.

sr-RS@latin + sr-RS (Russian characters + some more?)

https://github.com/validatorjs/validator.js/blob/master/src/lib/alpha.js#L24-L25

I'm not sure what the correct locale code would be here.
Can you give us some insides on this issue? Should we use sr_RS_latin as locale code for clarification?

2023-02-09 09:54 UTC, bdimitrovski commented
> We are currently busy and thus are a little bit slower with the reviews. AFAIK neither of us has any Serbian skills, so it takes a bit of time for us to review. We will review/merge it when we have time, probably soon. You can speed up the process by getting reviews from a third-party.
> 
> As for a release, we might release another v8 alpha in the next month (not sure yet), but the actual v8 stable release will take **at least** one or two months.
> 
> Also I noticed, that there are two "Serbian" languages, that seem to have the same locale code.
> 
> sr-RS@latin + sr-RS (Russian characters + some more?)
> 
> https://github.com/validatorjs/validator.js/blob/master/src/lib/alpha.js#L24-L25
> 
> I'm not sure what the correct locale code would be here. Can you give us some insides on this issue? Should we use sr_RS_latin as locale code for clarification?

That's alright, I understand that you're busy, however, these are mostly just Serbian names, cities and some addresses, nothing fancy. 

You can use the `sr_RS_latin` code, as we also have the Cyrilic alphabet, however, I have not translated it on this occasion. I can add it in another iteration, however, Latin would be more of a priority at this point.

2023-02-09 13:25 UTC, matthewmayer commented
seems `sr_rs_latn` and `sr_rs_cyrl` (or `sr_latn_rs`,`sr_latn_cyrl`) are more common in various software which distinguishes the two

2023-02-09 13:27 UTC, matthewmayer commented
bit of background https://ciklopea.com/blog/localization/should-you-localize-to-serbian-latin-or-to-serbian-cyrillic/

@bdimitrovski one thing i wasn't totally clear on: can you do a perfect 1-1 transliteration between the Latin and Cyrillic scripts? ie a computer should be able to translate character by characters? Or does it require some context/knowledge

2023-02-11 13:04 UTC, ST-DDT commented
> seems `sr_rs_latn` and `sr_rs_cyrl` (or `sr_latn_rs`,`sr_latn_cyrl`) are more common in various software which distinguishes the two

Do you have a source for this?

My search results show otherwise:

https://www.google.com/search?q=%22sr_RS_Latin%22 => 747.000
https://www.google.com/search?q=%22sr_RS_Latn%22 => 55
https://www.google.com/search?q=%22sr-RS-Latin%22 => 5260
https://www.google.com/search?q=%22sr-RS-Latn%22 => 1040

Also I found this entry from the rust sources:

https://docs.rs/pure-rust-locales/0.2.1/x86_64-apple-darwin/pure_rust_locales/sr_RS_latin/LC_TIME/index.html

2023-03-07 13:20 UTC, ST-DDT commented
This PR needs to be updated:

````sh
git fetch --all
git merge origin/next
pnpm run preflight
git add .
git merge --continue
````

2023-03-07 22:46 UTC, bdimitrovski commented
> This PR needs to be updated:
> 
> ```shell
> git fetch --all
> git merge origin/next
> pnpm run preflight
> git add .
> git merge --continue
> ```

Done.

2023-03-07 23:33 UTC, ST-DDT requested changes

2023-03-07 23:33 UTC, ST-DDT commented on docs/guide/localization.md
> +| `zu_ZA`       | Zulu (South Africa)       | `fakerZU_ZA`
This doesn't look right.
Please run ``pnpm run preflight`` again

2023-03-07 23:33 UTC, ST-DDT commented on src/locales/index.ts
> +export { default as zu_ZA } from './zu_ZA';
Same here

2023-03-08 18:16 UTC, bdimitrovski commented on docs/guide/localization.md
> +| `zu_ZA`       | Zulu (South Africa)       | `fakerZU_ZA`
All done.

2023-03-08 18:16 UTC, bdimitrovski commented on src/locales/index.ts
> +export { default as zu_ZA } from './zu_ZA';
Done.

2023-03-08 21:41 UTC, ST-DDT requested changes
One last change (from my side) and then this looks good to me.

2023-03-08 21:41 UTC, ST-DDT commented on src/locales/sr_RS/person/name.ts
> +  { value: '{{person.first_name}} {{person.last_name}}', weight: 1 },
```suggestion
  { value: '{{person.firstName}} {{person.lastName}}', weight: 1 },
```

Ref: https://github.com/faker-js/faker/blob/next/src/locales/en/person/name.ts#L2

2023-03-08 22:41 UTC, bdimitrovski commented on src/locales/sr_RS/person/name.ts
> +  { value: '{{person.first_name}} {{person.last_name}}', weight: 1 },
Done.

2023-03-09 01:38 UTC, matthewmayer requested changes

2023-03-09 01:38 UTC, matthewmayer commented on src/locales/sr_RS/person/first_name.ts
> +  'Ada',
You can make the generic first_name list this with mergeArrays so we don't have to maintain three seperate lists.

```ts
// We don't have a generic first name list for this locale
// So simply concatenate male and female lists and remove any duplicates
// This avoids falling back to fallback locale
import { mergeArrays } from './../../../internal/merge';
import female_first_name from './female_first_name';
import male_first_name from './male_first_name';

export default mergeArrays(female_first_name, male_first_name);
```

2023-03-09 09:05 UTC, ST-DDT approved these changes, later dismissed

2023-03-09 13:28 UTC, ST-DDT approved these changes

2023-03-09 13:34 UTC, matthewmayer submitted a review, later dismissed

2023-03-09 16:00 UTC, Shinigami92 submitted a review, later dismissed

2023-03-11 19:35 UTC, ST-DDT commented
Should we merge this as is or should we rename it to sr_RS_latin?

2023-03-11 19:44 UTC, Shinigami92 commented
> Should we merge this as is or should we rename it to sr_RS_latin?

A little bit of googling showed that `sr_RS_latin` is not a bad idea and theoretically "valid"
If another one also says yes, lets do it :+1:

2023-03-15 22:34 UTC, bdimitrovski commented
@matthewmayer @ST-DDT @Shinigami92 is this ready to go then?

2023-03-16 00:17 UTC, ST-DDT commented
We will discuss the locale key tomorrow in our team meeting.

2023-03-16 16:12 UTC, ST-DDT requested changes
**Team Decision**

[docs.rs/pure-rust-locales/0.2.1/x86_64-apple-darwin/pure_rust_locales/sr_RS_latin/LC_TIME/index.html](https://docs.rs/pure-rust-locales/0.2.1/x86_64-apple-darwin/pure_rust_locales/sr_RS_latin/LC_TIME/index.html)

Based on that source we have decided to use `sr_RS_latin` as locale key.
Please change the locale key accordingly.

2023-03-17 10:04 UTC, bdimitrovski commented
> sr_RS_latin

@ST-DDT How/where would I change that? Which file(s) should be altered?

2023-03-17 10:37 UTC, matthewmayer commented
Basically 
1. rename the whole src/locales/sr_RS to src/locales/sr_RS_latin
2. do a global replace from sr_RS to sr_RS_latin
3. run `pnpm run preflight` to make sure everything's OK

2023-03-17 10:41 UTC, bdimitrovski commented
> Basically
> 
> 1. rename the whole src/locales/sr_RS to src/locales/sr_RS_latin
> 2. do a global text replace from sr_RS to sr_RS_latin
> 3. run `pnpm run preflight` to make sure everything's OK

@matthewmayer Sure thing, that's what my thinking was too. But should I do that even in automatically generated files, like these?

![Screenshot 2023-03-17 at 11 40 11](https://user-images.githubusercontent.com/4244896/225882470-95c2c120-50e4-4d48-bd47-018bfde88a9c.png)

2023-03-17 10:42 UTC, matthewmayer commented
> > Basically
> > 
> > 1. rename the whole src/locales/sr_RS to src/locales/sr_RS_latin
> > 2. do a global text replace from sr_RS to sr_RS_latin
> > 3. run `pnpm run preflight` to make sure everything's OK
> 
> @matthewmayer Sure thing, that's what my thinking was too. But should I do that even in automatically generated files, like these?
> 
> ![Screenshot 2023-03-17 at 11 40 11](https://user-images.githubusercontent.com/4244896/225882470-95c2c120-50e4-4d48-bd47-018bfde88a9c.png)

doesn't really matter, they'll get regenerated by `pnpm run preflight` anyway.

2023-03-17 10:46 UTC, bdimitrovski commented
@matthewmayer @ST-DDT all done.

2023-03-17 11:24 UTC, ST-DDT commented on src/locale/sr_RS.ts
Please delete this file.

2023-03-17 12:52 UTC, bdimitrovski commented on src/locale/sr_RS.ts
Done.

2023-03-17 13:43 UTC, bdimitrovski commented
> bit of background https://ciklopea.com/blog/localization/should-you-localize-to-serbian-latin-or-to-serbian-cyrillic/
> 
> @bdimitrovski one thing i wasn't totally clear on: can you do a perfect 1-1 transliteration between the Latin and Cyrillic scripts? ie a computer should be able to translate character by characters? Or does it require some context/knowledge

Sorry, I've only seen this now - as for the transliteration, yes, it is possible - you can see it in action here https://www.lexilogos.com/keyboard/serbian_conversion.htm

Serbian language is the only European language to use a 2 way lettering system (otherwise known as full synchronic digraphia), the Cyrillic letter is in formal use (government, documents, etc), while informally, almost everyone uses Latin, in everyday communication.

Automatic transliteration to Cyrillic of the work that I've done for the Latin letter, is possible (again, referring to e.g. lexilogos.com):

![Screenshot 2023-03-17 at 14 41 30](https://user-images.githubusercontent.com/4244896/225921826-9d5d5a17-1993-4a87-ad02-b6b3474b6b41.png)

2023-03-17 22:25 UTC, ST-DDT approved these changes

2023-03-18 13:37 UTC, Shinigami92 approved these changes

2023-03-20 19:12 UTC, merged