feat(finance): currency object
faker-js/faker pull request #1809
Opened 2023-02-02 12:35 UTC by matthewmayer

fix #1733

2023-02-02 13:27 UTC, ST-DDT commented on src/modules/finance/index.ts
> +  /**
```suggestion

  /**
```

2023-02-02 13:27 UTC, ST-DDT commented on src/modules/finance/index.ts
> +  }
```suggestion
  }

```

2023-02-16 17:23 UTC, ST-DDT commented
**Team Decision**

Change the locale data to contain [{ name, code, symbol }]

2023-02-18 11:08 UTC, matthewmayer commented
Sorry, had some issues with my branch so had to force-push

2023-02-18 11:10 UTC, matthewmayer commented
This was my script to transform the definitions:

```js
'use strict';
const fs = require('fs');
const langs = ['en','el', 'fr_CH', 'fr', 'fa'];
const { faker } = require('@faker-js/faker');
for (let lang of langs) {
  let c = faker.locales[lang].finance.currency;
  let newCurr = Object.keys(c).map((k) => {
    return { name: k, code: c[k].code, symbol: c[k].symbol };
  });
  let str = JSON.stringify(newCurr, null, 2);
  fs.writeFileSync(
    `./src/locales/${lang}/finance/currency.ts`,
    `export default ${str}`
  );
}
```

2023-02-18 12:02 UTC, Shinigami92 commented on src/modules/finance/index.ts
> +    return this.faker.helpers.arrayElement(
Just an idea, but we could call `this.currency().code`, could we?

2023-02-19 00:32 UTC, ST-DDT requested changes
Please add a random seeded test for the `currency` object.

2023-02-19 00:32 UTC, ST-DDT commented on src/locales/fr_CH/finance/currency.ts
> +    name: 'Dollar',
Why is this a single line in [`en`](https://github.com/faker-js/faker/pull/1809/files#diff-d2590c7cfefec571e5c844e3da8095c10f090b3eb4d2d522ea66d4d7ab9cfa31R148), but multiple here?

2023-02-19 00:32 UTC, ST-DDT commented on src/modules/finance/index.ts
>    /**
```suggestion
  }

  /**
```

2023-02-19 00:32 UTC, ST-DDT commented on src/modules/finance/index.ts
> +  currency(): { name: string; code: string; symbol: string } {
Should we create a named type for this?
(Like we did in the [airline module](https://github.com/faker-js/faker/blob/next/src/modules/airline/index.ts#L102))

2023-02-19 00:32 UTC, ST-DDT commented on src/modules/finance/index.ts
> +   * faker.finance.currency() // {code:'USD', name:'US Dollar' , symbol:'$'}
```suggestion
   * faker.finance.currency() // { code: 'USD', name: 'US Dollar', symbol: '$' }
```

2023-02-19 00:32 UTC, ST-DDT commented on src/modules/finance/index.ts
> +   * Returns a random currency object, containing 'code', 'name' and 'symbol' properties.
```suggestion
   * Returns a random currency object, containing `code`, `name `and `symbol` properties.
```

2023-02-19 00:32 UTC, ST-DDT commented on src/modules/finance/index.ts
>    }
Should we deprecate the old methods in favor of the new one?

2023-02-19 04:51 UTC, matthewmayer commented on src/locales/fr_CH/finance/currency.ts
> +    name: 'Dollar',
i dunno, prettify seems happy with both options?

2023-02-19 04:54 UTC, matthewmayer commented on src/modules/finance/index.ts
> +  currency(): { name: string; code: string; symbol: string } {
there is one already called FinanceCurrencyEntryDefinitions i can rename that to Currency

2023-02-19 04:59 UTC, matthewmayer commented on src/modules/finance/index.ts
> +  currency(): { name: string; code: string; symbol: string } {
or are the definition types supposed to be different to the named types?

2023-02-19 05:32 UTC, matthewmayer commented on src/modules/finance/index.ts
>    }
i dont know if its necessary. the other methods have been around a long time, are trivial and don't cause a maintenance burden.

2023-02-19 05:54 UTC, matthewmayer commented on src/modules/finance/index.ts
> +  currency(): { name: string; code: string; symbol: string } {
i tried that in 09b4c330, if that is the wrong approach i can revert

2023-02-19 09:26 UTC, ST-DDT commented on src/modules/finance/index.ts
> +  currency(): Currency {
When we use them as return types then we usually define the type in the module and use it in the definitions. I kind of dont care where, but I would like to have it consistent.

2023-02-19 09:55 UTC, matthewmayer commented on src/modules/finance/index.ts
> +  currency(): Currency {
moved it in https://github.com/faker-js/faker/pull/1809/commits/731e6c0b44c8a269f0e7f57595f1ea546f0b2d3b

2023-02-19 09:55 UTC, matthewmayer commented
> add a test of the currency object

added in https://github.com/faker-js/faker/pull/1809/commits/844cb203d76c44f303ccd1c788b02fbc70d770bc

2023-02-19 09:57 UTC, matthewmayer commented on src/locales/fr_CH/finance/currency.ts
> +    name: 'Dollar',
changed in https://github.com/faker-js/faker/pull/1809/commits/56da4ac092f954e77c576483d2491827d96dc4f2

2023-02-19 10:15 UTC, matthewmayer commented
i think there are a few "currencies" which could be removed e.g. 

{
    name: 'Codes specifically reserved for testing purposes',
    code: 'XTS',
    symbol: '',
  },

and various metals like Gold, Platinum etc,

Should i include that in this PR or wait and do as a seperate PR

2023-02-19 10:24 UTC, matthewmayer commented
> i think there are a few "currencies" which could be removed e.g.
> 
> { name: 'Codes specifically reserved for testing purposes', code: 'XTS', symbol: '', },
> 
> and various metals like Gold, Platinum etc,
> 
> Should i include that in this PR or wait and do as a seperate PR

comparing https://en.wikipedia.org/wiki/List_of_circulating_currencies with the list i'd suggest the removal of

```
[
  'CUC', 'EEK', 'HRK', 'LTL',
  'LVL', 'MRO', 'SLL', 'SVC',
  'XAG', 'XAU', 'XBA', 'XBB',
  'XBC', 'XBD', 'XDR', 'XFU',
  'XPD', 'XPT', 'XTS', 'ZWL'
]
```

and the addition of 

[ 'MRU', 'SLE', 'SSP'] (and possibly 'VED' )

these are a variety of currencies which got replaced (e.g. EEK -> EUR), changed (e.g. MRO -> MRU) or are non-currencies (e.g. XTS, XAU).

2023-02-19 11:00 UTC, Shinigami92 commented on src/modules/finance/index.ts
> +export interface Currency {
We should re-export this interface from src/index.ts so it can be used from outside (Like e.g. ColorFormat or SexType)

2023-02-19 18:46 UTC, ST-DDT commented
> i think there are a few "currencies" which could be removed e.g.
> 
> { name: 'Codes specifically reserved for testing purposes', code: 'XTS', symbol: '', },
> 
> and various metals like Gold, Platinum etc,
> 
> Should i include that in this PR or wait and do as a seperate PR

Please do that in a separate PR as the removed entries will be lost within the other changes to the locale definitions.

2023-02-19 18:47 UTC, ST-DDT submitted a review, later dismissed
Other than the re-export and the deprecation this looks good to me.

2023-02-22 05:26 UTC, matthewmayer commented on src/modules/finance/index.ts
> +export interface Currency {
added the re-export

2023-02-22 05:28 UTC, matthewmayer commented
> Other than the re-export and the deprecation this looks good to me.

i added the re-export in 86d1ae09

Not planning to deperecate other methods (per https://github.com/faker-js/faker/pull/1809#discussion_r1111168114 ) unless others feel strongly they should be

2023-02-22 08:11 UTC, Shinigami92 approved these changes

2023-02-22 15:57 UTC, ST-DDT commented
Lets discuss this in the next team meeting.

2023-02-23 16:56 UTC, ST-DDT commented
**Team decision**

We won't deprecate the old methods.

--------

Then this PR is ready for review and merge.

2023-02-24 11:57 UTC, Shinigami92 commented on src/modules/finance/index.ts
>    }
=> https://github.com/faker-js/faker/pull/1809#issuecomment-1442114654

2023-02-24 22:59 UTC, ST-DDT approved these changes

2023-02-26 23:17 UTC, merged