feat(person): add Portuguese BR Language to western zodiac sign
faker-js/faker pull request #1814
Opened 2023-02-06 11:31 UTC by Minozzzi

2023-02-06 12:48 UTC, matthewmayer requested changes
you need to run `pnpm run generate:locales` to update the `src/locales/pt_BR/person/index.ts` file

2023-02-06 23:43 UTC, ST-DDT approved these changes
Looks good to me.
We should consider sorting these alphabetically as well (for overall easier review-ability of all locale data), although it might be detrimental for this data set in particular.

2023-02-07 00:54 UTC, matthewmayer commented
> Looks good to me.
> 
> We should consider sorting these alphabetically as well (for overall easier review-ability of all locale data), although it might be detrimental for this data set in particular.

As zodiac signs have an natural order (like months) it seems more sensible to keep them in that order.

2023-02-10 20:09 UTC, xDivisionByZerox approved these changes

2023-02-11 00:40 UTC, import-brain approved these changes

2023-02-11 04:10 UTC, matthewmayer approved these changes

2023-02-11 06:41 UTC, Shinigami92 approved these changes

2023-02-11 11:12 UTC, merged