feat: Added Random Zodiac Signs and Birthday
faker-js/faker pull request #182
Opened 2022-01-17 00:37 UTC by luciferreeves

## This PR adds the functionality of generating random zodiac signs and birthdays

### New Functions:

- `faker.date.birthday()`
- `faker.zodiac.sign()`

### Usage:

#### `faker.date.birthday()`:

```js
// generates a random birthday of a person aged between 18 and 80
console.log(faker.date.birthday()) // 1970-12-22T05:00:00.000Z

// generates a random birthday of a person, between two years
console.log(faker.date.birthday({ min: 1990, max: 2000 });) // 1992-03-06T05:00:00.000Z
```

#### `faker.zodiac.sign()`:

```js
// returns a random zodiac sign
console.log(faker.zodiac.sign()) // Leo

// takes optional 'birthday' parameter, if provided returns the zodiac sign for the given birthday
console.log(faker.zodiac.sign('1997-12-20')) // Sagittarius
```

**Unit tests for both the functions added.**

Fixes #175

2022-01-18 21:07 UTC, Shinigami92 commented
I will review this after 6.0.0 was released

2022-01-23 20:17 UTC, pkuczynski commented
I would expect `faker.date.birthday` to have a bit different signature:

```js
faker.date.birthday(age: number, refDate?: string | Date)
faker.date.birthday(options: { min: number, max: number }, refDate?: string | Date)
```

So instead of providing a year, I would rather expect to provide an age...

2022-01-26 20:24 UTC, luciferreeves commented
> I would expect `faker.date.birthday` to have a bit different signature:
> 
> ```js
> faker.date.birthday(age: number, refDate?: string | Date)
> faker.date.birthday(options: { min: number, max: number }, refDate?: string | Date)
> ```
> 
> So instead of providing a year, I would rather expect to provide an age...

I have added a `mode` options to the `faker.date.birthday` object. Please take a look at the updated description.

2022-01-26 20:54 UTC, ST-DDT commented
Please migrate all js files to ts.

2022-01-26 21:20 UTC, pkuczynski commented
> Please migrate all js files to ts.

I think it was an accidental commit of `lib/*` files...

2022-01-26 22:50 UTC, luciferreeves commented
I removed the older js files

2022-01-27 00:23 UTC, ST-DDT commented
Have the examples files been committed intentionally?

2022-01-27 01:01 UTC, luciferreeves commented
I didn't notice the example files were removed from the newer structure of the repo. I removed them from this PR too.

2022-01-27 11:55 UTC, ST-DDT requested changes

2022-01-27 11:55 UTC, ST-DDT commented on src/date.ts
> +    return new Date(year, month - 1, day);
The age mode may be off, if the day and month of it are in the future.

I wrote a test to confirm this:

````ts
 it('returns a random birthday between two ages', function () {
      const min = 4;
      const max = 5;
      const now = new Date();
      const earlyBound = new Date();
      earlyBound.setFullYear(now.getFullYear() - max);
      const lateBound = new Date();
      lateBound.setFullYear(now.getFullYear() - min);

      for (let i = 0; i < 10000; i++) {
        const birthday = faker.date.birthday({ min, max, mode: 'age' });

        // birthday is a date object
        expect(birthday).to.be.an.instanceof(Date);

        // Generated date is between min and max
        expect(birthday).to.be.at.least(earlyBound);
        expect(birthday).to.be.at.most(lateBound);
      }
    });
````

Please check it for correctness.

2022-01-27 11:55 UTC, ST-DDT commented on src/date.ts
> +   * @param options
Please write a proper description including a hint regarding default values.

See https://github.com/faker-js/faker/pull/230/files#diff-2809d7d9276cfe7f2007cf47a87c64572e3d0a733ca9988e7cb82275c2360a83R275-R279 (and others) for an example.

2022-01-27 11:55 UTC, ST-DDT commented on src/date.ts
> +    }
Please add a comment why you choose these values. If you want to generate only adult birthdays, you have to make sure that it remains true also for the `year` mode

2022-01-27 11:55 UTC, ST-DDT commented on test/date.spec.ts
> +      var max = 2000;
Please use `let` or `const` instead of `var` everywhere.

2022-01-27 11:55 UTC, ST-DDT commented on src/zodiac.ts
> +  sign(birthday: string = undefined): string {
Maybe support also `Date` input.

2022-01-27 15:08 UTC, luciferreeves commented on src/date.ts
> +    return new Date(year, month - 1, day);
Fixed the date function

2022-01-27 15:09 UTC, luciferreeves commented on src/date.ts
> +   * @param options
Added the description

2022-01-27 15:09 UTC, luciferreeves commented on test/date.spec.ts
> +      var max = 2000;
replaced all `var` with `const`

2022-01-27 15:10 UTC, luciferreeves commented on src/zodiac.ts
> +  sign(birthday: string = undefined): string {
Supported `Date` input

2022-01-27 16:05 UTC, ST-DDT requested changes

2022-01-27 16:27 UTC, pkuczynski requested changes

2022-01-27 16:27 UTC, pkuczynski commented on src/date.ts
> +   * @param options
Don't forget about `@example` as for example in here https://github.com/faker-js/faker/blob/main/src/time.ts#L7

2022-01-27 16:28 UTC, pkuczynski commented on test/date.spec.ts
> +      const birthday = faker.date.birthday({ min: min, max: max, mode: 'age' });
```suggestion
      const birthday = faker.date.birthday({ min, max, mode: 'age' });
```

2022-01-28 03:34 UTC, luciferreeves commented
Everything that was suggested is added. Please check

2022-01-28 08:39 UTC, ST-DDT requested changes
One last part, otherwise it looks good to me.
Thanks for your contribution.
Please note that this is scheduled for 6.1 so it might take a while before this gets merged.

2022-01-28 08:39 UTC, ST-DDT commented on src/date.ts
> +    return new Date(+startDate + Math.random() * (endDate - startDate));
Please use `datatype.number` instead of random to support seeded random.
https://github.com/faker-js/faker/blob/32b483920450a5c1a084e83723f1c433db8ff34f/src/datatype.ts#L27-L29

2022-01-28 16:58 UTC, luciferreeves reviewed
Okay, everything is fixed now. Instead of `datatype.number()` as suggested, I used `this.faker.datatype.float({
          min: 0,
          max: 1,
          precision: 0.0000000000000001
       })` to replicate the `Math.random()` behavior.

2022-01-28 16:58 UTC, luciferreeves commented on src/date.ts
> +    return new Date(+startDate + Math.random() * (endDate - startDate));
Okay, everything is fixed now. Instead of `datatype.number()` as suggested, I used `this.faker.datatype.float({
          min: 0,
          max: 1,
          precision: 0.0000000000000001
       })` to replicate the `Math.random()` behavior.

2022-01-28 20:05 UTC, pkuczynski commented
General comment: you should separate zodiac signs and birthday into two separate PR, as they are totally independent.

2022-01-28 20:23 UTC, luciferreeves commented
> General comment: you should separate zodiac signs and birthday into two separate PR, as they are totally independent.

@pkuczynski Maybe from next time, I will target smaller issues/PRs. Too many commits have gone in this PR and it would be hard to undo those changes, split branches and redo again.

2022-01-28 20:27 UTC, pkuczynski commented
> @pkuczynski Maybe from next time, I will target smaller issues/PRs. Too many commits have gone in this PR and it would be hard to undo those changes, split branches and redo again.

You don't need to split branches. Just create a new one and copy 3 files from this PR regarding date, create new PR from them, and delete in this PR. We don't need the whole commit/review history.

2022-01-28 21:22 UTC, luciferreeves commented
I see. Although, I still fail to see the usage of 2 PRs now since this once is almost completed review and is targeted for v6.2 and won't be merged anytime soon either. I will try to split the PRs if I get time.

2022-01-28 23:15 UTC, ST-DDT requested changes

2022-01-28 23:15 UTC, ST-DDT commented on src/date.ts
> +          (endDate - startDate)
`this.faker.datatype.number(startDate, endDate);`

2022-01-28 23:20 UTC, ST-DDT commented
> Okay, everything is fixed now. Instead of `datatype.number()` as suggested, I used `this.faker.datatype.float({ min: 0, max: 1, precision: 0.0000000000000001 })` to replicate the `Math.random()` behavior.

Can you explain why? AFAIK datatype.number should return a value between startDate and endDate.

2022-01-28 23:29 UTC, ST-DDT commented
I replaced your return statement with

````ts
return new Date(
      this.faker.datatype.number({
        min: startDate,
        max: endDate,
      })
    );
````

And the tests still pass.

2022-01-29 00:01 UTC, luciferreeves commented
Okay, done. I used:

```js
return new Date(
  this.faker.datatype.number({
    min: startDate,
    max: endDate,
  })
);
```

2022-01-29 00:06 UTC, ST-DDT approved these changes, later dismissed

2022-01-29 00:15 UTC, pkuczynski requested changes

2022-01-29 00:16 UTC, pkuczynski requested changes, later dismissed

2022-01-29 00:16 UTC, pkuczynski commented on src/date.ts
> +      this.faker.datatype.number({
Why not faker.date.between?

2022-01-29 00:39 UTC, luciferreeves commented on src/date.ts
> +      this.faker.datatype.number({
Tried, does not work with start and end dates. `faker.datatype.number()` as suggested by @ST-DDT works

2022-01-29 00:40 UTC, luciferreeves commented on src/zodiac.ts
> +}
I do not have any idea of those. Probably add it with a later PR?

2022-01-29 00:42 UTC, luciferreeves commented on src/date.ts
> +    options = options || {};
Just used the same syntax used at other places.

2022-01-29 00:42 UTC, luciferreeves commented
I have resolved all the notified issues, and added comments to the unresolved ones.

2022-01-29 01:32 UTC, ST-DDT commented on src/zodiac.ts
> +}
So how do we disambiguate them?

westernZodiac, chineseZodiac, ...?

2022-01-29 01:39 UTC, ST-DDT commented on src/date.ts
> +      this.faker.datatype.number({
The between method currently requires strings. Support for dates will be added in https://github.com/faker-js/faker/pull/200/files#diff-cdc74ab5a2d5c1414321a9e339b60e2e79e1018a99e545d87653e3e0d972fed6R63

2022-01-29 12:16 UTC, ST-DDT commented on src/date.ts
> +  birthday(options?: {
You forgot a `birthday` here.

2022-01-29 15:55 UTC, luciferreeves commented on src/zodiac.ts
> +}
I am no expert in astrology but I think there is no such thing as "western zodiac" - there's only one - the internationally accepted one. The chinese and others are the "other variants". So we can keep the zodiac as it is, and just add functions for chinese, sidereal, etc.

2022-01-29 19:57 UTC, luciferreeves commented on src/date.ts
> +  birthday(options?: {
Renamed it.

2022-01-29 20:05 UTC, luciferreeves commented
Tests pass on my system but are failing here. I am looking into it. Please disregard the review request.

2022-01-29 20:53 UTC, ST-DDT commented
You might have to rebase.

2022-01-30 16:24 UTC, luciferreeves commented
Okay, I think this is now ready to be reviewed.

2022-02-09 21:58 UTC, ST-DDT requested changes

2022-02-09 21:58 UTC, ST-DDT commented on src/zodiac.ts
> +      const day = date.getDate() + 1;
Please check whether my change is correct:

```suggestion
      const day = date.getDate();
```

Code used for testing with (probably) expected values:

````ts
console.log("19/3", faker.zodiac.sign("0000-03-19T00:00:00Z")); // Pisces
console.log("20/3", faker.zodiac.sign("0000-03-20T00:00:00Z")); // Pisces
console.log("21/3", faker.zodiac.sign("0000-03-21T00:00:00Z")); // Aries

console.log("19/4", faker.zodiac.sign("0000-04-19T00:00:00Z")); // Aries
console.log("20/4", faker.zodiac.sign("0000-04-20T00:00:00Z")); // Aries
console.log("21/4", faker.zodiac.sign("0000-04-21T00:00:00Z")); // Taurus
````

2022-02-09 21:58 UTC, ST-DDT commented on src/date.ts
> +      })
This yields wrong values if `min === max` because then it will always return now/refDate instead of a one year range within the bounds. I assume the same applies for the actual date range since it will always miss the one year.

--------------

````ts
faker.date.birthdate({
    mode: "age",
    min: 5,
    max: 5,
    refDate: "2020-01-01T00:00:00.000Z",
  })
````

Actual result:
`2015-01-01T00:00:00.000Z`

Expected result range:
`2014-01-01T00:00:00.001Z` - `2015-01-01T00:00:00.000Z`
(for safety reasons we should probably use `2014-01-02` - ...)

--------------------

````ts
faker.date.birthdate({
    mode: "year",
    min: 2000,
    max: 2000,
    refDate: "2020-01-01T00:00:00.000Z",
  })
````

Actual result:
`2000-01-01T00:00:00.000Z`

Expected result range:
`2000-01-01T00:00:00.000Z` - `2000-12-12T59:59:59.999Z`

2022-02-09 22:03 UTC, ST-DDT commented
Could you please also include the source for the zodiac sign dates above the switch case?
There seems to be different dates based on the page you visit (e.g. German wiki vs English wiki). 😱

2022-04-05 14:26 UTC, Shinigami92 commented
We're starting work on the `v6.2` milestone, but this PR needs a rebase.
Please rebase and resolve all conflicts. Until then, we're moving it to the `v6` milestone, which now serves as the "v6-Backlog".
If this PR no longer contains any conflicts and can certainly be a target for the next release, we will move it to the then active milestone `v6.x`.

2022-04-30 20:57 UTC, ST-DDT commented
I updated the branch and will fix remaining issues.

2022-04-30 22:23 UTC, ST-DDT approved these changes, later dismissed
I applied all fixes, so it should be ready now. Please review.

2022-04-30 22:26 UTC, ST-DDT commented on src/locales/en/zodiac/sign.ts
> +];
Should we use a record here with sign name keys instead of index access?

2022-04-30 22:27 UTC, ST-DDT commented on src/date.ts
> +      );
Should we avoid the change of the year or not.
How should we handle timezones (local or UTC), if not?

2022-05-03 19:30 UTC, Shinigami92 requested changes

2022-05-03 19:30 UTC, Shinigami92 commented on src/modules/date/index.ts
> +   * @param options The options to use to generate the birthdate. If no options are set, then an age between 18 and 80 (inclusive) is generated.
```suggestion
   * @param options The options to use to generate the birthdate. If no options are set, an age between 18 and 80 (inclusive) is generated.
```

2022-05-03 19:30 UTC, Shinigami92 commented on src/modules/date/index.ts
> +   * - `'year'`: The min and max options define the range the birthdate may be in (e.g. `1900` - `2000`).
We should stick to one order:
- age or year
- year or age

2022-05-03 19:30 UTC, Shinigami92 commented on src/modules/date/index.ts
> +   * faker.date.birthdate({min: 1900, max: 2000, mode: 'year'}); // 1995-02-11T03:24:00.000Z
```suggestion
   * faker.date.birthdate({ min: 18, max: 65, mode: 'age' }); // 1994-02-11T03:24:00.000Z
   * faker.date.birthdate({ min: 1900, max: 2000, mode: 'year' }); // 1995-02-11T03:24:00.000Z
```

2022-05-03 19:30 UTC, Shinigami92 commented on src/modules/date/index.ts
> +   * faker.date.birthdate({min: 1900, max: 2000, mode: 'year'}); // 1995-02-11T03:24:00.000Z
We should add one example with given min/max but not mode.
Maybe also one with `refDate`?

2022-05-03 19:30 UTC, Shinigami92 commented on src/modules/date/index.ts
> +      // Avoid generating dates the first and last date of the year.
Would be nice if this comments also point out WHY

2022-05-03 19:30 UTC, Shinigami92 commented on src/modules/date/index.ts
> +    );
This can be written in one line

```suggestion
    return new Date(this.faker.datatype.number({ min, max }));
```

Or do we need `new Date(Date.UTC(this.faker.datatype.number({ min, max }), 0, 1))` here?

2022-05-03 19:30 UTC, Shinigami92 commented on src/modules/zodiac/index.ts
> +          throw new Error(`Invalid date: ${date.toLocaleDateString()}`);
Not sure if `toLocaleDateString` is a good idea, because it can differ very much for different countries
In addition we should throw a `FakerError`

2022-05-03 19:30 UTC, Shinigami92 commented on src/modules/zodiac/index.ts
> +          throw new Error(`Invalid date: ${date.toLocaleDateString()}`);
We need a test to cover this line and check the thrown error

2022-05-04 16:42 UTC, ST-DDT commented on src/modules/date/index.ts
> +    );
> Or do we need `new Date(Date.UTC(this.faker.datatype.number({ min, max }), 0, 1))` here?

No

2022-05-04 17:47 UTC, Shinigami92 commented on src/modules/zodiac/index.ts
> +      }
```suggestion
      const sign: keyof ZodiacDefinitions['sign'] = {
        1: () => (day > 20 ? 'aquarius' : 'capricorn'),
        2: () => (day > 19 ? 'pisces' : 'aquarius'),
        3: () => (day > 20 ? 'aries' : 'pisces'),
        4: () => (day > 20 ? 'taurus' : 'aries'),
        5: () => (day > 20 ? 'gemini' : 'taurus'),
        6: () => (day > 21 ? 'cancer' : 'gemini'),
        7: () => (day > 22 ? 'leo' : 'cancer'),
        8: () => (day > 22 ? 'virgo' : 'leo'),
        9: () => (day > 22 ? 'libra' : 'virgo'),
        10: () => (day > 22 ? 'scorpio' : 'libra'),
        11: () => (day > 21 ? 'sagittarius' : 'scorpio'),
        12: () => (day > 21 ? 'capricorn' : 'sagittarius'),
      }[month]();

      return this.faker.definitions.zodiac.sign[sign];
```

2022-05-04 17:56 UTC, Shinigami92 commented on src/modules/zodiac/index.ts
> +import { FakerError } from '../.../../..';
```suggestion
import type { Faker } from '../..';
import { FakerError } from '../..';
```

2022-05-04 23:21 UTC, ST-DDT commented
<details>
<summary><strong>Docs Preview (Click to expand)</strong></summary>

![grafik](https://user-images.githubusercontent.com/1579362/166840652-b4b01d25-41ed-45d4-b1cc-e5e543db2cf6.png)

![grafik](https://user-images.githubusercontent.com/1579362/166840729-118b905e-e0d2-4683-a103-81219c52f1ee.png)

</details>

2022-05-05 08:52 UTC, Shinigami92 commented
> Please check whether that `FakerError` is generally unsafe to use or just from inside our tests.

at least in the current version (v6.3.1) it is possible 🤔 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/7195563/166890755-c0a11993-6537-496f-b2bd-b16d37f0a63f.png">

if you like you could add an extra test that checks importing the error, but I _trust_ esbuild 🤷

2022-05-05 08:56 UTC, Shinigami92 commented on src/modules/zodiac/index.ts
> +    }
Just a quick question: what's the Faker randomness here? Not sure if I overlook something but I think it will always return the exact same result for each `seed` with a given `birthdate`.
Is this even in scope of Faker?

2022-05-05 08:58 UTC, Shinigami92 commented on test/zodiac.spec.ts
> +    it('returns a random zodiac sign for a given birthday', () => {
Looks like it's not random...

2022-05-05 09:09 UTC, ST-DDT commented
> if you like you could add an extra test that checks importing the error, but I _trust_ esbuild

It might be only an issue if we use it from the faker modules itself (circular reference: module -> error@index.ts -> faker -> module).

2022-05-05 09:31 UTC, Shinigami92 commented on src/modules/zodiac/index.ts
> +    }
Ah I see, should we add that to the function docs?
Something like: use the param together with faker.date.birthdate.

2022-05-05 09:42 UTC, ST-DDT commented on src/modules/zodiac/index.ts
> +    }
No, I dont think so.
We dont have it for emails either.

2022-05-05 09:47 UTC, Shinigami92 commented on src/modules/zodiac/index.ts
> +    }
> No, I dont think so.
> 
> We dont have it for emails either.

❓
Could you link the code you mean that doesn't generate random values with given params?

2022-05-05 10:14 UTC, ST-DDT commented on src/modules/zodiac/index.ts
> +    }
https://github.com/faker-js/faker/blob/3ea64ceeecfe4cac2f2e6708f12a4bee288d1cb6/src/modules/internet/index.ts#L59-L73

The provider is taken as is, the first and last name are transmuted a bit.
Neither of the parameters claim, that you should use a faker method to generate them.

2022-05-05 10:19 UTC, ST-DDT commented on test/zodiac.spec.ts
> +    it('returns a random zodiac sign for a given birthday', () => {
Added a "random" test in [`3b55f84` (#182)](https://github.com/faker-js/faker/pull/182/commits/3b55f848ef0f28efbd3179063e1abb6f1836b312)

2022-05-05 10:37 UTC, ST-DDT commented
@faker-js/members @faker-js/maintainers: As per @Shinigami92's request:
Should we have `faker.zodiac.sign(birthday)` as option or is that too much utility method.
(We would still have `faker.zodiac.sign()`)

2022-05-05 11:51 UTC, import-brain commented
> @faker-js/members @faker-js/maintainers: As per @Shinigami92's request: Should we have `faker.zodiac.sign(birthday)` as option or is that too much of a utility method. (We would still have `faker.zodiac.sign()`)

Hmm, I don't know. I'm leaning towards it being too much of a utility method, but let's see what the other members of the team think.

2022-05-05 12:05 UTC, xDivisionByZerox commented
> @faker-js/members @faker-js/maintainers: As per @Shinigami92's request: Should we have `faker.zodiac.sign(birthday)` as option or is that too much of a utility method. (We would still have `faker.zodiac.sign()`)

Wouldn't that negate the use case of your lib to generate random data? From my understanding providing a specific birthday would result in the same return value for every call (under the condition that the parameter is the same).  If that association is correct, I would suggest dropping the signature.

2022-05-05 12:09 UTC, ST-DDT commented
> From my understanding providing a specific birthday would result in the same return value for every call (under the condition that the parameter is the same). If that association is correct, I would suggest dropping the signature.

The assumption is correct, just keep in mind that you can use faker to generate the birthdate that you pass in there.

2022-05-06 11:30 UTC, Shinigami92 commented
I immediately found several packages on npm helping to get zodiac signs
- https://www.npmjs.com/package/zodiac-signs
- https://www.npmjs.com/package/horoscope
- https://www.npmjs.com/package/zodiac-ts
- https://www.npmjs.com/package/get-zodiac-sign

Without looking to deep into them, I would vote that we remove the signature `sign(birthdate)` and only provide `sign()`

2022-05-06 18:02 UTC, import-brain commented
> I immediately found several packages on npm helping to get zodiac signs
> 
> * [npmjs.com/package/zodiac-signs](https://www.npmjs.com/package/zodiac-signs)
> * [npmjs.com/package/horoscope](https://www.npmjs.com/package/horoscope)
> * [npmjs.com/package/zodiac-ts](https://www.npmjs.com/package/zodiac-ts)
> * [npmjs.com/package/get-zodiac-sign](https://www.npmjs.com/package/get-zodiac-sign)
> 
> Without looking to deep into them, I would vote that we remove the signature `sign(birthdate)` and only provide `sign()`

Yeah, I vote for just `sign()` too.

2022-05-06 21:21 UTC, pkuczynski commented
It makes sense to have a bday param. It wouldn't generate ransom value, but it would let you easily hook into previously generated random date to produce valid data without using another package

2022-05-06 22:54 UTC, xDivisionByZerox commented
> It makes sense to have a bday param. It wouldn't generate ransom value, but it would let you easily hook into previously generated random date to produce valid data without using another package

From our About section
> Generate massive amounts of fake data in the browser and node.js

I don't see how this aligns with the libraries philosophy

2022-05-07 04:45 UTC, pkuczynski commented
It doesn't go against it either. Fake does not mean it has to be invalid. In my projects I use faker in a way that produced output is sensible. It's fake, but correct.

2022-05-07 08:39 UTC, ST-DDT commented
> In my projects I use faker in a way that produced output is sensible. It's fake, but correct.

This also aligns with my expectations. If you dont generate correct data, why distiguish between firstnames and lastnames or names in general? Why can you generate an email from them?

2022-05-15 15:22 UTC, ST-DDT commented
I have split the `birthdate` part in its own PR to simplify the review (and discussions): #962

2022-05-17 17:28 UTC, ST-DDT commented
The birthdate has been merged, so this is now only the zodiac signs.

2022-05-17 17:28 UTC, ST-DDT submitted a review, later dismissed

2022-05-17 17:33 UTC, import-brain submitted a review, later dismissed

2022-05-17 19:08 UTC, Shinigami92 requested changes

2022-05-17 19:08 UTC, Shinigami92 commented on src/modules/zodiac/index.ts
> +  sign(birthdate?: string | number | Date): string {
Until we meet together this week for a team meeting, I want to block this.
I'm still the opinion that we should not allow to pass a birthdate and get a non seeded static value out if that. Reason: not in scope of faker -> use other libs.
(This is a ground-discussion / precedent case / what is the scope of faker)

2022-08-18 17:14 UTC, ST-DDT commented
**Team decision**

- We will soon rename the name module to person and then add the zodiac method there.
- The zodiac method won't provide parameters for dates, so it won't be birthdate related.

2022-10-13 18:56 UTC, Shinigami92 commented
We might want to discuss in team if we want just `zodiacSign` that accepts `'western' | 'chinese'` or if we want two separate methods :thinking:

2022-10-13 20:03 UTC, ejcheng commented
> We might want to discuss in team if we want just `zodiacSign` that accepts `'western' | 'chinese'` or if we want two separate methods 🤔

I would prefer just having `zodiacSign` that accepts `'western' | 'chinese'` or `'western' | 'eastern'`.

2022-10-16 21:31 UTC, Shinigami92 commented
@luciferreeves if you like to, you can already at least move the method to the person module now after a rebase

If you do not have time, please let me know and I can take this PR over

2022-10-20 16:29 UTC, ST-DDT commented
**Team decision**

We will start with `zodiacSign()`, then we are free to introduce parameters with the specific variant.
The locale will use `person.zodiac(sign).western` to ensure, future extensibility.

2022-11-03 23:08 UTC, ST-DDT commented
Done. Ready for Review.

I used `faker.definitions.person.western_zodiac_sign` as that has better fallback behavior over `faker.definitions.person.zodiac_sign.western`.

2022-11-03 23:08 UTC, ST-DDT approved these changes

2022-11-04 04:41 UTC, import-brain approved these changes

2022-11-04 16:35 UTC, Shinigami92 reviewed
Could you at least add german locales as well? :slightly_smiling_face:

2022-11-04 16:46 UTC, ST-DDT commented
> Could you at least add german locales as well? 🙂

I will do that in a separate PR.

2022-11-04 16:46 UTC, Shinigami92 approved these changes

2022-11-07 15:58 UTC, merged