refactor(internet): standardize signatures
faker-js/faker pull request #1845
Opened 2023-02-15 23:54 UTC by xDivisionByZerox

Part of #1349.

Standardize all function signatures in the `InternetModule` to support an options object (if they have parameters).

2023-02-16 01:23 UTC, matthewmayer submitted a review, later dismissed

2023-02-16 01:23 UTC, matthewmayer commented on test/internet.spec.ts
> +      t.it('noArgs').it('with separator', ':').it('with separator option', '-');
shouldn't "with seperator option" test have the "-" wrapped in a object?

2023-02-16 09:46 UTC, xDivisionByZerox commented on test/internet.spec.ts
> +      t.it('noArgs').it('with separator', ':').it('with separator option', '-');
Good catch, thank you.

2023-02-16 13:04 UTC, ST-DDT requested changes

2023-02-16 13:04 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      false;
```suggestion
    const {
      firstName = this.faker.person.firstName(),
      lastName = legacyLastName,
      provider = legacyProvider,
      allowSpecialCharacters = legacyOptions.allowSpecialCharacters ?? false,
    } = options;
```

2023-02-16 13:04 UTC, ST-DDT commented on src/modules/internet/index.ts
> +  exampleEmail(options?: {
The old signature isnt deprecated.
Also first put the new signature then the deprecated one.

2023-02-16 13:04 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      false;
Can be joined.

2023-02-16 13:04 UTC, ST-DDT commented on src/modules/internet/index.ts
> +  userName(options?: {
The old signature isnt deprecated.
Also first put the new signature then the deprecated one.

2023-02-16 13:04 UTC, ST-DDT commented on src/modules/internet/index.ts
> +  displayName(firstName?: string, lastName?: string): string;
The old signature isnt deprecated.
Also first put the new signature then the deprecated one.

2023-02-16 13:04 UTC, ST-DDT commented on src/modules/internet/index.ts
> +  color(options?: {
The old signature isnt deprecated.
Also first put the new signature then the deprecated one.

2023-02-16 13:04 UTC, ST-DDT commented on src/modules/internet/index.ts
> +  mac(options?: {
The old signature isnt deprecated.
Also first put the new signature then the deprecated one.

2023-02-16 13:04 UTC, ST-DDT commented on src/modules/internet/index.ts
> +  password(options?: {
The old signature isnt deprecated.
Also first put the new signature then the deprecated one.

2023-02-16 13:04 UTC, ST-DDT commented on test/internet.spec.ts
> +        .it('with all option', {
```suggestion
        .it('with all options', {
```

2023-02-16 13:04 UTC, ST-DDT commented on test/internet.spec.ts
> +        .it('with all option', {
```suggestion
        .it('with all options', {
```

2023-02-16 13:30 UTC, xDivisionByZerox commented on src/modules/internet/index.ts
> +  exampleEmail(options?: {
Because my goal here is not to deprecate the signatures at all. At least not in this PR. 🤔

2023-02-16 13:46 UTC, xDivisionByZerox commented on src/modules/internet/index.ts
> +  exampleEmail(options?: {
I've moved the "options" signature to be the first signature for all functions you commented on. I closed the other suggestions so that the discussion can stay in one place.

2023-02-19 12:03 UTC, xDivisionByZerox commented on src/modules/internet/index.ts
> +  exampleEmail(options?: {
@ST-DDT Can this be considered resolved?

2023-02-19 19:50 UTC, ST-DDT commented on src/modules/internet/index.ts
> +  exampleEmail(options?: {
No, I would like to discuss this in the next meeting.

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +     * @default faker.person.firstName
```suggestion
     * @default faker.person.firstName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +     * @default faker.person.lastName
```suggestion
     * @default faker.person.lastName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +           * @default faker.person.firstName
```suggestion
           * @default faker.person.firstName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +           * @default faker.person.lastName
```suggestion
           * @default faker.person.lastName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +           * @default faker.person.lastName
```suggestion
           * @default faker.person.lastName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +           * @default faker.person.firstName
```suggestion
           * @default faker.person.firstName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +     * @default faker.person.firstName
```suggestion
     * @default faker.person.firstName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +     * @default faker.person.lastName
```suggestion
     * @default faker.person.lastName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +           * @default faker.person.firstName
```suggestion
           * @default faker.person.firstName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +           * @default faker.person.lastName
```suggestion
           * @default faker.person.lastName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +           * @default faker.person.firstName
```suggestion
           * @default faker.person.firstName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +           * @default faker.person.lastName
```suggestion
           * @default faker.person.lastName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +     * @default faker.person.firstName
```suggestion
     * @default faker.person.firstName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +     * @default faker.person.lastName
```suggestion
     * @default faker.person.lastName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +           * @default faker.person.firstName
```suggestion
           * @default faker.person.firstName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +           * @default faker.person.lastName
```suggestion
           * @default faker.person.lastName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +           * @default faker.person.firstName
```suggestion
           * @default faker.person.firstName()
```

2023-02-20 11:19 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +           * @default faker.person.lastName
```suggestion
           * @default faker.person.lastName()
```

2023-02-20 11:22 UTC, Shinigami92 submitted a review, later dismissed
LGTM, as I understand you want to make the deprecation in a followup PR so the changelog entry gets generated

2023-02-23 17:51 UTC, ST-DDT commented
**Team Decision**

- We want to deprecate the old signatures in this PR as well.

2023-02-27 18:51 UTC, Shinigami92 approved these changes, later dismissed

2023-02-27 23:26 UTC, ST-DDT reviewed
Could you retain the tests for the legacy signatures?

2023-02-27 23:26 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      typeof legacyOptions === 'object'
```suggestion
      legacyLastName !=null ||
      legacyOptions != null
```

2023-02-27 23:26 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      typeof legacyOptions === 'object'
```suggestion
      legacyLastName != null ||
      legacyProvider != null ||
      legacyOptions != null
```

2023-02-27 23:26 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    if (typeof options === 'string' || typeof legacyLastName === 'string') {
```suggestion
    if (typeof options === 'string' || legacyLastName != null) {
```

2023-02-27 23:26 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    if (typeof options === 'string' || typeof legacyLastName === 'string') {
```suggestion
    if (typeof options === 'string' || legacyLastName != null) {
```

2023-02-27 23:26 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      typeof legacyGreenBase === 'number'
```suggestion
      legacyBlueBase != null ||
      legacyGreenBase != null
```

2023-02-27 23:26 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      typeof legacyPrefix === 'string'
```suggestion
      legacyMemorable != null ||
      legacyPattern != null ||
      legacyPrefix != null
```

2023-02-28 21:04 UTC, ST-DDT requested changes, later dismissed
Please retain the tests for the legacy signatures.

````diff
t.describe('email', (t) => {
      t.it('noArgs')
-        .it('with names', 'Jane', 'Doe')
+        .it('with legacy names', 'Jane', 'Doe')
-        .it('with provider', undefined, undefined, 'fakerjs.dev')
+        .it('with legacy provider', undefined, undefined, 'fakerjs.dev')
-        .it('with names and provider', 'Jane', 'Doe', 'fakerjs.dev');
+       .it('with legacy names and provider', 'Jane', 'Doe', 'fakerjs.dev')
+ ...
````

2023-02-28 21:04 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      legacyLastName !=null ||
```suggestion
      legacyLastName != null ||
```

2023-02-28 23:35 UTC, ST-DDT commented
> This is not possible. If I do so the test will fail due to deprecated methods being called (the "examples and deprecations" test suite).

That's odd. It shouldn't, because that test is for the jsdocs examples not other tests. 🤔

2023-03-01 09:11 UTC, xDivisionByZerox commented
> > This is not possible. If I do so the test will fail due to deprecated methods being called (the "examples and deprecations" test suite).
> 
> That's odd. It shouldn't, because that test is for the jsdocs examples not other tests. 🤔
> 
> EDIT: I tested with the above email tests and it works as expected.

Thats weird. I'll try to clean my setup and add the tests again.

2023-03-01 20:29 UTC, Shinigami92 submitted a review, later dismissed

2023-03-07 13:30 UTC, ST-DDT commented
> Thats weird. I'll try to clean my setup and add the tests again.

Any updates so far?

2023-03-07 13:36 UTC, xDivisionByZerox commented
No, sorry. Did not have time so far.

2023-03-07 23:24 UTC, ST-DDT approved these changes

2023-03-08 16:13 UTC, Shinigami92 approved these changes

2023-03-14 19:30 UTC, merged