chore(infra): add preflight script
faker-js/faker pull request #1846
Opened 2023-02-16 11:24 UTC by xDivisionByZerox

Add a `preflight` script that combines multiple necessary scripts for devs to feel safe before committing.

Solves #1636

2023-02-16 12:48 UTC, xDivisionByZerox commented on package.json
> +    "preflight": "run-s format lint build generate:* test:update-snapshots"
Should `build` run after `generate:*`? I'm pretty sure it should but I'm not certain.

2023-02-16 13:06 UTC, ST-DDT commented on package.json
> +    "preflight": "run-s format lint build generate:* test:update-snapshots"
Yes, because the locales get updated and that should be in the build.

2023-02-16 13:09 UTC, ST-DDT commented on package.json
> +    "preflight": "run-s format lint build generate:* test:update-snapshots"
Maybe add pnpm install as well?

2023-02-16 13:09 UTC, ST-DDT reviewed
Maybe add this command as a comment to the PR template and contribution guidelines.

2023-02-16 13:31 UTC, matthewmayer submitted a review, later dismissed
should be documented somewhere e.g. in CONTRIBUTING, or the pull request template

2023-02-16 13:36 UTC, xDivisionByZerox commented on package.json
> +    "preflight": "run-s format lint build generate:* test:update-snapshots"
> Maybe add pnpm install as well?

IDK. From the description of the issue I've read that this should be run on every commit. I don't see why you should reinstall the dependencies every time. But if we decide that this is a "last check before opening a PR" command, then this would be a good idea. 
So which use case should this be applied to?

2023-02-16 13:53 UTC, xDivisionByZerox commented on package.json
> +    "preflight": "run-s format lint build generate:* test:update-snapshots"
If I extend the script to include `\"pnpm install\"` I get an error that `pnpm` was not found.
![image](https://user-images.githubusercontent.com/77127505/219382990-1c1a82a2-64f0-41ed-9800-d430ab4c0749.png)

I never worked with `npm-run-all` before. Any idea why this happens?
BTW, for the same reason I did add the `test:update-snapshots` script. If I tried to run `vitest` inline, it tells me that `vitest` was not found.

2023-02-16 14:11 UTC, matthewmayer commented on package.json
> +    "preflight": "run-s format lint build generate:* test:update-snapshots"
pnpm install should be very fast if nothing has changed so might as well add.

2023-02-16 14:16 UTC, Shinigami92 commented on package.json
> +    "preflight": "run-s format lint build generate:* test:update-snapshots"
It is somewhat irrelevant to use install in this script/place, as you already needed to run install once to already have `run-s` in your node_modules

2023-02-16 15:31 UTC, matthewmayer commented on package.json
> +    "preflight": "run-s format lint build generate:* test:update-snapshots"
But for example if I branch from next, make some changes, a few days later finish my PR, merge in next again, but fail to run `pnpm install` then I may be running with outdated dependencies.

2023-02-16 16:07 UTC, Shinigami92 commented on package.json
> +    "preflight": "run-s format lint build generate:* test:update-snapshots"
@xDivisionByZerox maybe instead of `pnpm install` you just need `install`
`install` is also just a script like all the custom added ones
It's just one of the pre defined ones

2023-02-16 16:17 UTC, matthewmayer requested changes

2023-02-16 16:17 UTC, matthewmayer commented on .github/pull_request_template.md
>  <!-- Help us by writing a correct PR title following this guide: https://github.com/faker-js/faker/blob/verify-semantic-pull-requests/CONTRIBUTING.md#committing -->
sorry i know not really part of this PR, but 
- the https://github.com/faker-js/faker/blob/verify-semantic-pull-requests/CONTRIBUTING.md URL doesn't resolve (i guess branch deleted)
- the two comments are very similar and could be merged?

2023-02-16 16:19 UTC, ST-DDT commented
**Team Decision**

We will name this command `preflight`.

2023-02-16 16:22 UTC, xDivisionByZerox commented on .github/pull_request_template.md
>  <!-- Help us by writing a correct PR title following this guide: https://github.com/faker-js/faker/blob/verify-semantic-pull-requests/CONTRIBUTING.md#committing -->
I already saw that and will fix this separately ;)

2023-02-16 16:44 UTC, xDivisionByZerox commented on .github/pull_request_template.md
>  <!-- Help us by writing a correct PR title following this guide: https://github.com/faker-js/faker/blob/verify-semantic-pull-requests/CONTRIBUTING.md#committing -->
I opened #1849 to resolve this.

2023-02-16 16:51 UTC, matthewmayer submitted a review, later dismissed

2023-02-16 20:40 UTC, ST-DDT reviewed
Please also adjust it here: https://github.com/faker-js/faker/blob/e7230f6f10af9633cf0eca18910cbafaaba9ecba/.github/workflows/commentCodeGeneration.ts#L24

2023-02-16 20:40 UTC, ST-DDT commented on .github/pull_request_template.md
> +<!-- Please run `pnpm run preflight` before opening a Pull Request to ensure that your code fulfils the minimal requirements for our project -->
```suggestion
<!-- Please run `pnpm run preflight` before opening a Pull Request to ensure that your code fulfills the minimal requirements for our project. -->
```

2023-02-16 23:17 UTC, ST-DDT submitted a review, later dismissed

2023-02-17 01:40 UTC, import-brain approved these changes, later dismissed

2023-02-17 09:37 UTC, Shinigami92 approved these changes, later dismissed

2023-02-17 12:08 UTC, ST-DDT commented
We have a merge conflict. Please rebase.

2023-02-17 12:15 UTC, Shinigami92 approved these changes

2023-02-17 12:24 UTC, ST-DDT approved these changes

2023-02-17 13:27 UTC, matthewmayer approved these changes

2023-02-18 00:07 UTC, merged