Add locale ro_MD
faker-js/faker pull request #1848
Opened 2023-02-16 13:38 UTC by botzill

Add a new locale for ro_MD

2023-02-16 15:43 UTC, matthewmayer requested changes

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/date/month.ts
> +  ],
you can omit this as identical

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/date/month.ts
> +  ],
you can omit this as identical

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/date/weekday.ts
> +  ],
you can omit this as identical

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/date/weekday.ts
> +  ],
you can omit this as identical

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/internet/domain_suffix.ts
> +  'ro.ru'
are the ru and ro.ru domains popular in moldova?

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/internet/free_email.ts
> +export default ['mail.ru', 'rambler.ru', 'yandex.ru', 'gmail.com', 'gmail.ru', 'yahoo.com', 'hotmail.com'];
are .ru email addresses popular in Moldova?

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/location/building_number.ts
> +export default ['Bloc ##'];
are there any other common patterns?

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/location/city_name.ts
> +  'Chișinău',
please sort alphabetically

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/location/street_name.ts
> +  'Stefan Cel Mare',
please sort alphabetically

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/location/street_suffix.ts
> +export default ['Aleea', 'Bulevardul', 'Intrarea', 'Str-la'];
should be street_prefix

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/person/female_first_name.ts
> +  'Tatiana',
please sort alphabetically

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/person/last_name.ts
> +  'Rusu',
please sort alphabetically

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/person/male_first_name.ts
> +  'Andrei',
please sort alphabetically

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/person/name.ts
> +  { value: '{{person.lastName}} {{person.firstName}}', weight: 1 },
is it common to write lastName firstName? if not, please remove.

2023-02-16 15:43 UTC, matthewmayer commented on src/locales/ro_MD/person/suffix.ts
> +export default ['Jr.', 'Sr.'];
as this is not used in the name patterns, can be removed.

2023-02-16 16:12 UTC, matthewmayer requested changes
Also run `pnpm run test` and check for errors, CI reports two about duplicate entries:
```
⎯⎯⎯⎯⎯⎯⎯ Failed Tests 2 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/locales.spec.ts > locale > ro_MD > location > city_name > should not have duplicate entries
Error: Duplicated values are [Florești]

 FAIL  test/locales.spec.ts > locale > ro_MD > person > female_first_name > should not have duplicate entries
Error: Duplicated values are [Ianna, Irina]
```

2023-02-17 06:07 UTC, botzill commented on src/locales/ro_MD/date/month.ts
> +  ],
You mean set the array empty and it will take automatically from `ro` locale ?

2023-02-17 06:08 UTC, botzill commented on src/locales/ro_MD/internet/domain_suffix.ts
> +  'ro.ru'
There are some yes

2023-02-17 06:09 UTC, botzill commented on src/locales/ro_MD/person/female_first_name.ts
> +  'Tatiana',
OK

2023-02-17 06:09 UTC, botzill commented on src/locales/ro_MD/person/last_name.ts
> +  'Rusu',
OK

2023-02-17 07:25 UTC, ST-DDT commented on src/locales/ro_MD/date/month.ts
> +  ],
No, don't set the value.
If the entry isn't present then we will automatically fall back to the main one.

2023-02-17 12:00 UTC, ST-DDT commented on src/locales/ro_MD/location/street.ts
> +export default ['{{location.street_suffix}} {{location.street_name}}'];
A (street) suffix should be at the end. Or be called prefix.

2023-02-17 12:02 UTC, ST-DDT commented on src/locales/ro_MD/date/month.ts
> +  ],
Don't remove everything, only the `_context` ones.

2023-02-17 12:15 UTC, matthewmayer requested changes

2023-02-17 12:15 UTC, matthewmayer commented on src/locales/ro_MD/date/weekday.ts
> +  wide: [],
Sorry not what I meant. You need to provide the lists of months/days for the wide and abbr keys but you don't need the wide_context and abbr_context keys at all

2023-02-17 12:22 UTC, matthewmayer commented
Btw recommended you don't force push, that way it's easier to see the history of the PR. It gets squash-merged at the end anyway!

2023-02-17 12:59 UTC, botzill commented on src/locales/ro_MD/date/weekday.ts
> +  wide: [],
I see, I did copy it from `ro`, seems that it needs to be changed in `ro` as well.

2023-02-17 16:20 UTC, ST-DDT commented on src/locales/ro_MD/date/weekday.ts
> +  abbr: ['Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri', 'Sâmbătă', 'Duminică'],
The abbreviations are usually 2 or three characters.
Are you sure there aren't any abbreviations available?

2023-02-17 16:20 UTC, ST-DDT commented on src/locales/ro_MD/location/street.ts
> +export default ['{{location.street_prefix}} {{location.street_name}}'];
Usually `location.street_name` refers to existing street names, maybe rename the file to `location.street_name_part`?
Any alternative suggestions?

2023-02-17 16:20 UTC, ST-DDT commented on src/locales/ro_MD/location/county.ts
> +export default [
This is the same as state. Is that intended?

2023-02-17 17:34 UTC, botzill commented on src/locales/ro_MD/location/county.ts
> +export default [
I removed the states as in MD there are not state and let only county

2023-02-17 19:11 UTC, ST-DDT commented on src/locales/ro_MD/location/state_abbr.ts
> +  'AN',
I assume these are now also wrong?

2023-02-17 19:52 UTC, botzill commented on src/locales/ro_MD/location/state_abbr.ts
> +  'AN',
yes fixed now

2023-02-17 22:56 UTC, ST-DDT commented
I'm almost done with reviewing this, I will do the rest this weekend.
Thanks for your contribution and your quick fixes ❤️ .

2023-02-20 06:03 UTC, botzill commented
> I'm almost done with reviewing this, I will do the rest this weekend. Thanks for your contribution and your quick fixes ❤️ .

Thanks

2023-02-20 12:19 UTC, ST-DDT commented on src/locales/ro_MD/phone_number/formats.ts
> +  '0229#####',
According to [wikipedia](https://en.wikipedia.org/wiki/Telephone_numbers_in_Moldova), 3 is also used for land line telephone numbers. Or just on paper?

2023-02-20 12:33 UTC, botzill commented on src/locales/ro_MD/phone_number/formats.ts
> +  '0229#####',
This is actually the phone code only for the capital, I did not include other locations.

2023-02-20 13:27 UTC, botzill commented on src/locales/ro_MD/phone_number/formats.ts
> +  '0229#####',
@ST-DDT I think is OK to generate only this numbers, as are most common ones.

2023-02-21 06:34 UTC, botzill commented
Hi @ST-DDT, let me know, please, if there are any other changes required. 

Thanks.

2023-02-21 07:13 UTC, Shinigami92 approved these changes, later dismissed

2023-02-21 07:46 UTC, botzill commented
How should I fix this:

```
❯ test/all_functional.spec.ts  (30506 tests | 6 failed) 7505ms
   ❯ test/all_functional.spec.ts > functional tests > ro_MD > location > state()
     → expected undefined to be truthy
   ❯ test/all_functional.spec.ts > functional tests > ro_MD > location > stateAbbr()
     → expected undefined to be truthy
   ❯ test/all_functional.spec.ts > functional tests > ro_MD > person > suffix()
     → expected undefined to be truthy
   ❯ test/all_functional.spec.ts > faker.helpers.fake functional tests > ro_MD > location > state()
     → expected 'undefined' not to be 'undefined' // Object.is equality
   ❯ test/all_functional.spec.ts > faker.helpers.fake functional tests > ro_MD > location > stateAbbr()
     → expected 'undefined' not to be 'undefined' // Object.is equality
   ❯ test/all_functional.spec.ts > faker.helpers.fake functional tests > ro_MD > person > suffix()
     → expected 'undefined' not to be 'undefined' // Object.is equality
```

?

2023-02-21 07:49 UTC, Shinigami92 commented
I assume this test ensures that inside some locale files exporting empty arrays is not allowed
Sadly the test result message is not indicating this in any way

@ST-DDT please tell me if I'm right or wrong

2023-02-21 08:39 UTC, ST-DDT commented
> How should I fix this

For now please add them to the skipped locale entries (with a comment that this locale doesn't have that data.

> I assume this test ensures that inside some locale files exporting empty arrays is not allowed
> Sadly the test result message is not indicating this in any way

That is correct. It will do so when https://github.com/faker-js/faker/issues/893 is merged.

2023-02-22 20:24 UTC, botzill commented
> For now please add them to the skipped locale entries (with a comment that this locale doesn't have that data).

Hi, can you guid on how todo this?

2023-02-22 23:42 UTC, ST-DDT approved these changes

2023-02-22 23:43 UTC, ST-DDT commented
> > For now please add them to the skipped locale entries (with a comment that this locale doesn't have that data).
> 
> Hi, can you guid on how todo this?

Done. Thanks for your patience.

2023-03-14 08:44 UTC, matthewmayer requested changes
Now that #1340 has been closed we have support for multiple fallback languages, so it would make sense to change the fallback languages

ro_MD -> ro -> en, so ro_MD only includes MD-specific data.

2023-03-14 19:24 UTC, xDivisionByZerox approved these changes

2023-03-14 19:53 UTC, closed without merging

2023-03-14 20:00 UTC, ST-DDT commented
@botzill Did you close this PR by accident?

2023-03-14 20:01 UTC, botzill commented
hm, @ST-DDT I think yes,

2023-03-14 20:04 UTC, botzill commented
How can I get it back?

2023-03-14 20:06 UTC, ST-DDT commented
The force push comment contains a reference to the old version: https://github.com/faker-js/faker/commit/91a0aa8e271738596841b4b20718a56b2645c651

You should be able to checkout the commit or reset your branch to that commit.

2023-03-15 12:23 UTC, botzill commented
Hi @ST-DDT, I do not have that comit on my end. I did rebase and I create a new PR, let me know if that helps: #1936