refactor(datatype): legacy float implementation
faker-js/faker pull request #1855
Opened 2023-02-17 13:45 UTC by xDivisionByZerox

Fixes #1596.

Since `datatype.float` and `datatype.number` now have significant differences compared to `number.float` I put the legacy implementation for the `datatype` functions directly into that module, without referencing the new implementation of the `NumberModule`.
This allows us to more freely change the new APIs without having a fear of breaking something in the legacy one.

2023-02-17 16:46 UTC, xDivisionByZerox commented on test/number.spec.ts
> +      it.todo('provides numbers with a given precision of 0.5 steps', () => {
I'm a bit lost on how to achieve this with 'fractionDigits' being present. Any math person can help me out?

2023-02-17 16:46 UTC, xDivisionByZerox commented on test/__snapshots__/number.spec.ts.snap
> +exports[`number > 42 > float > with min, max and fractionDigits 1`] = `-0.426`;
`frictionDigits` being 4 here but decimal places only being 3 due to the last digit being `0` and thus getting trimmed. Is this desired??

2023-02-18 02:18 UTC, xDivisionByZerox commented on test/number.spec.ts
> +      it.todo('provides numbers with a given precision of 0.5 steps', () => {
Should this feature maybe entirely be implemented in its own pull request? I would have some pretty hacky solution to solve this, but I have a feeling it will result in a very big discussion. Thats why I'm askin wether `fractionDigits` and `steps` should be 2 separate concernces.

2023-02-18 02:21 UTC, matthewmayer commented on test/number.spec.ts
> +      it.todo('provides numbers with a given precision of 0.5 steps', () => {
I don't think "steps" is particularly useful. I would not include it in the new method. 

Assuming we only allow integer values for fraction digits then that's equivalent to precisions of the form 10^x only.

2023-02-18 02:25 UTC, xDivisionByZerox commented on test/number.spec.ts
> +      it.todo('provides numbers with a given precision of 0.5 steps', () => {
> Assuming we only allow integer values for fraction digits [...]

I don't think that's the current behavior. There is also no test case for that. What would happen in your opinion if someone passed a float into `frictionDigits`?

2023-02-18 02:52 UTC, matthewmayer commented on test/number.spec.ts
> +      it.todo('provides numbers with a given precision of 0.5 steps', () => {
You can't have a number with "two and a half
" decimal places. It should throw an error.

2023-02-18 06:19 UTC, matthewmayer commented on test/__snapshots__/number.spec.ts.snap
> +exports[`number > 42 > float > with min, max and fractionDigits 1`] = `-0.426`;
As the return value is a number not a string I think that's unavoidable

2023-02-18 06:21 UTC, matthewmayer commented on test/number.spec.ts
> +      it.todo('provides numbers with a given precision of 0.5 steps', () => {
FWIW toFixed seems to just floor its parameter ie

2.1234567.toFixed(2.99) just acts like 2.1234567.toFixed(2)

2023-02-18 10:20 UTC, ST-DDT commented on src/modules/number/index.ts
> +    const { min = 0, max = 1, fractionDigits = 16 } = options;
IMO we should just return the generated float then instead of converting it to string and then back to number.

2023-02-18 10:21 UTC, ST-DDT commented on test/number.spec.ts
> +      it.todo('provides numbers with a given precision of 0.5 steps', () => {
> I don't think "steps" is particularly useful. I would not include it in the new method.

The `precision` aka `step` feature is intended to be used for or in conjunction with HTML's input step feature:

https://www.w3schools.com/tags/att_input_step.asp

> I'm a bit lost on how to achieve this with 'fractionDigits' being present.

I think it is not necessary.

> Any math person can help me out?

See also: least common multiple
I assume there also approximation possible using the log function.

> FWIW toFixed seems to just floor its parameter ie

IMO there is no need to go beyond what JS does itself.

2023-02-18 10:40 UTC, matthewmayer commented on src/modules/number/index.ts
> +    const { min = 0, max = 1, fractionDigits = 16 } = options;
i agree, i would not provide a default and then do something like:

`
if (fractionDigits !== undefined) {
  return parseFloat(real.toFixed(fractionDigits));
} else {
  return real
}

```

2023-02-18 11:55 UTC, Shinigami92 commented
Adding the new parameter `fractionDigits` should have been an addition, not a replacement

Around 3 month ago, with many discussions and looking deeper into it, we finally came to the conclusion that we want to officially want to support this behavior to achieve "steps"
like 0.4 would result in `0.0, 0.4, 0.8, 1.2, ...`
Using equivalent math with some logarithmic functions resulted in just painfully headaches and are not suitable for persons that are not trained in math

But as https://github.com/faker-js/faker/pull/1855#discussion_r1110977702 pointed to https://github.com/faker-js/faker/issues/1596#issuecomment-1326654346 we want to XOR the parameter, so you will get a `FakerError` when you pass both parameters the same time as they are incompatible

2023-02-18 12:10 UTC, matthewmayer commented
Would it be better to make stepped values a seperate method? so faker.number.float takes `{max, min, precision}` and e.g. faker.number.stepped takes `{max, min, step}`. I feel it's trying to stuff too much into one method.

2023-02-18 12:11 UTC, Shinigami92 commented
> Would it be better to make stepped values a seperate method? so faker.number.float takes `{max, min, precision}` and e.g. faker.number.stepped takes `{max, min, step}`. I feel it's trying to stuff too much into one method.

I mark this for `needs decision` and we can discuss next meeting

2023-02-18 12:27 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +    const { min = 0, max = 1, fractionDigits = 16 } = options;
I implemented this without having multiple code pathes/returns.

2023-02-18 19:30 UTC, ST-DDT commented
> > Would it be better to make stepped values a seperate method? so faker.number.float takes `{max, min, precision}` and e.g. faker.number.stepped takes `{max, min, step}`. I feel it's trying to stuff too much into one method.
> 
> I mark this for `needs decision` and we can discuss next meeting

Lets continue the discussion in the related issue to give our community the ability to input their suggestions so we can take them into consideration, we deciding this.

https://github.com/faker-js/faker/issues/1596

2023-02-23 16:36 UTC, ST-DDT commented
**Team decision**

The proposal to move the `precision`/`step` logic into a different method has been rejected.
We will keep this `precision`/`step` option in the float method's single signature and document that the parameters are mutually exclusive.

2023-02-23 16:52 UTC, ST-DDT commented
We will first refactor the method precision -> step.
Then continue with the fractionDigits PR.

2023-02-24 08:56 UTC, matthewmayer commented
I'm still somewhat concerned that "step" is poorly defined.

For example what possible values would you expect to be returned for
`{min: 0.6, max: 2.0, step: 0.5}`

Is it 
`{0.6, 1.1, 1.6}`? ie, `min, min+step, min+2*step....`
or `{1.0, 1.5, 2.0}`? ie `step*X for all integer values of X in max-min`

2023-02-24 10:12 UTC, Shinigami92 commented
> I'm still somewhat concerned that "step" is poorly defined.
> 
> For example what possible values would you expect to be returned for `{min: 0.6, max: 2.0, step: 0.5}`
> 
> Is it `{0.6, 1.1, 1.6}`? ie, `min, min+step, min+2*step....` or `{1.0, 1.5, 2.0}`? ie `step*X for all integer values of X in min-max range`

**For now** we will go with second, because this is how precision is working right now.
In a later Faker version >=8.1 we can discuss if we want to change something on this behavior or if we want to leave as is. But for v8.0 this will fall out of our milestone plans.

```ts
import { faker } from './src';

const result = Array.from({ length: 5 }, () =>
  faker.number.float({ min: 0.6, max: 2.0, precision: 0.5 })
  //                                       ^^^^^^^^^ this will just be renamed
);

console.log(result); // [ 1.5, 1, 2, 2, 1 ]
```

2023-02-24 10:39 UTC, matthewmayer commented
Note this is not how the HTML Input element behaves (which you mentioned at https://github.com/faker-js/faker/pull/1855#discussion_r1110977702 was one of the rationales for including it)

`<input type="number" min=0.6 max=2.0 step=0.5>` allows `{0.6, 1.1, 1.6}`

2023-02-24 10:51 UTC, Shinigami92 commented
> Note this is not how the HTML Input element behaves (which you mentioned at [#1855 (comment)](https://github.com/faker-js/faker/pull/1855#discussion_r1110977702) was one of the rationales for including it)
> 
> `<input type="number" min=0.6 max=2.0 step=0.5>` allows `{0.6, 1.1, 1.6}`

That is good to know, we will bring this into the discussions when discussing this in a team meeting
But please note that this can take some weeks/months because we are currently focusing on v8.0

2023-02-24 11:08 UTC, matthewmayer commented
I think it would be better to not rename the parameter or just remove it completely rather than potentially needing another breaking change to its functionality in the future.

2023-02-24 11:40 UTC, Shinigami92 commented
> I think it would be better to not rename the parameter or just remove it completely rather than potentially needing another breaking change to its functionality in the future.

removing is not an option anymore 🤷
we already agreed from multiple sides that we will NOT remove it
reason: not everyone can handle the math using logarithms to achieve stepping
**period, end of discussion**

renaming it just helps to understand better for what it is considered
we already moved the function into a whole new module (datatype.float -> number.float)
so I don't see a big issue there to directly rename it and just have
```ts
datatype.float({ precision, ... }) => number.float({ steps: precision, ... })
```

2023-02-24 11:53 UTC, matthewmayer commented
could it be something like `legacyPrecision` which doesn't imply it works like the step parameter?

2023-02-24 12:00 UTC, Shinigami92 commented
> could it be something like `legacyPrecision` which doesn't imply it works like the step attribute?

Mh 🤔 I'm not for a `legacy*` prefix, as this is currently used in our code base to indicate parameters that are marked as deprecated.
Do you have alternative names?

2023-02-24 12:06 UTC, matthewmayer commented
roundToMultipleOf?

2023-02-24 23:33 UTC, ST-DDT commented
`multipleOf` would be fine for me.

2023-02-25 02:55 UTC, matthewmayer commented
I think that makes it clearer you can't have arbitrary steps. 

For example you can't use this to return one of

0.25,0.75,1.25,1.75,2.25,2.75

2024-01-05 09:03 UTC, Shinigami92 commented
Is there at least one test-case with a **combination** of `fractionDigits` + `multipleOf`?

2024-01-05 09:59 UTC, xDivisionByZerox commented
> Is there at least one test-case with a **combination** of `fractionDigits` + `multipleOf`?

Now there is. Don't know if it is as expected. We did [decide](https://github.com/faker-js/faker/issues/1596#issuecomment-1326654346) that there should be an error if both parameters are incompatible. What exectly does that mean tho?
Currently I did decide to let `multipleOf` take priority over `fractionDigits`.

2024-01-05 11:34 UTC, matthewmayer requested changes

2024-01-05 11:34 UTC, matthewmayer commented on src/modules/color/index.ts
> +      color.push(this.faker.number.float({ fractionDigits: 2 }));
is there any need to change this? As they do the same thing and neither are deprecated.

2024-01-05 11:34 UTC, matthewmayer commented on src/modules/number/index.ts
> +      real = Number.parseFloat(real.toFixed(fractionDigits));
can we avoid casting to string and back by handling this using the existing precision code and setting precision=10 ** fractionDigits?

2024-01-05 11:34 UTC, matthewmayer commented on src/modules/number/index.ts
> +   * @param options.fractionDigits The number of digits to appear after the decimal point.
this seems slightly misleading, there won't definitely be fractionDigits after the decimal point (for example if you do {min:0, max:1, fractionDigits:2} then any of 0, 0.2 or 0.23 are possible. Only 0.23 actually has 2 digits after the point.

2024-01-05 11:34 UTC, matthewmayer commented on src/modules/number/index.ts
> +   * This parameter is ignored if `multipleOf` is given as well.
i think it would be better if it throws. Providing both options is definitely a programmer error, and it will only happen in newly written code, so better to throw early.

2024-01-05 11:56 UTC, Shinigami92 commented on src/modules/number/index.ts
> +   * This parameter is ignored if `multipleOf` is given as well.
On a TypeScript layer we could even provide conditional interfaces. But I fear that right now it is not possible, due to some decisions made in history and the extensive detailed need of JSDoc.
So right now I would also go with @matthewmayer and suggest to throw a runtime error instead.

2024-01-05 12:30 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +      real = Number.parseFloat(real.toFixed(fractionDigits));
Thanks smart. Didn't thought about that.

2024-01-05 14:01 UTC, ST-DDT commented on src/modules/color/index.ts
> +      color.push(this.faker.number.float({ fractionDigits: 2 }));
I slightly prefer `multipleOf` over `fractionDigits`, but that isn't blocking for me.

2024-01-05 14:08 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +function legacyFloatImplementation(options: {
Could you explain why you extracted this method?
Are there some discussions/incompatible changes that I missed?

2024-01-05 14:09 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * @param options.fractionDigits The number of digits to appear after the decimal point.
Maybe refer to it as max fractionDigits or mention that trailing `0` fraction digits might be hidden during output by JS.

2024-01-05 14:11 UTC, xDivisionByZerox commented on src/modules/datatype/index.ts
> +function legacyFloatImplementation(options: {
I did write about this in the PR description. Don't know if this is still relevant.

2024-01-05 14:14 UTC, xDivisionByZerox commented on src/modules/color/index.ts
> +      color.push(this.faker.number.float({ fractionDigits: 2 }));
This would make the current PR less verbose correct? I can apply the change.

2024-01-05 14:16 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * @throws If `max` is smaller than `min`.
Int uses the old phrasing here:

https://github.com/faker-js/faker/blob/7a1f5bc50f178c10f6cd335432c0c5f1064688c7/src/modules/number/index.ts#L28

I've also found this variant:

https://github.com/faker-js/faker/blob/1328985f36b9e6670aff7704cb1914fd7a4514d4/src/modules/helpers/index.ts#L379

2024-01-05 14:16 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * Defaults to `16`.
IMO this should not have a default.

2024-01-05 14:21 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * This parameter is ignored if `multipleOf` is given as well.
IMO the user should either use the fractionDigits or the multipleOf. I think we should not include instructions how they should combine the two, as that would go to far into simple math that hopefully everybody can do by themselves. it would also be kind of ugly to read. `faker.number.float({ min: min / multipleOf, max: max / multipleOf, fractionDigits }) * multipleOf and please make sure that multpleOf is an integer otherwise you get more fractionDigits`

2024-01-05 14:23 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * @throws If `max` is smaller than `min`.
The error message matches the old @throws as well.

2024-01-05 14:28 UTC, matthewmayer commented on src/modules/number/index.ts
> +   * @param options.fractionDigits The number of digits to appear after the decimal point.
perhaps the *maximum* number of fraction digits to...

2024-01-05 14:29 UTC, ST-DDT commented on test/modules/datatype.spec.ts
> +          }).toThrowError(`Max ${max} should be greater than min ${min}.`);
This test does not match it's description. precision vs min+max

2024-01-05 14:29 UTC, ST-DDT commented on test/modules/number.spec.ts
>          })
IMO this should be a new testcase instead of replacing the old precision one.

2024-01-05 14:29 UTC, ST-DDT commented on test/modules/number.spec.ts
> +          expect(actual).toBe(Number(actual.toFixed(2)));
Should we use `Number.parseFloat` here instead of this?

2024-01-05 14:29 UTC, ST-DDT commented on test/modules/number.spec.ts
> -
IMO we should keep this test till v9.

2024-01-05 14:31 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +function legacyFloatImplementation(options: {
Me neither, we probably have to check if this breaks/changes anything since the last minor version.

2024-01-05 14:36 UTC, matthewmayer commented on src/modules/datatype/index.ts
> +function legacyFloatImplementation(options: {
now we are keeping precision too, probably can get rid of legacyFloatImplementation

2024-01-05 16:05 UTC, matthewmayer requested changes

2024-01-05 16:05 UTC, matthewmayer commented on test/modules/number.spec.ts
> +      it('throws an error for and0', () => {
looks like accidental change

2024-01-05 16:36 UTC, xDivisionByZerox commented on src/modules/datatype/index.ts
> +function legacyFloatImplementation(options: {
I did revert this change.

2024-01-05 17:04 UTC, xDivisionByZerox commented on test/modules/datatype.spec.ts
> +          }).toThrowError(`Max ${max} should be greater than min ${min}.`);
Would changing the error message be considered a regression in the first place?

2024-01-05 17:06 UTC, xDivisionByZerox commented on test/modules/number.spec.ts
>          })
I propably did not mean to relace the old one. The last next merge was pretty big. I guess this slipped in there. 
I'll add this case as a separate test case.

2024-01-05 17:10 UTC, xDivisionByZerox commented on test/modules/number.spec.ts
> +          expect(actual).toBe(Number(actual.toFixed(2)));
I previously checked the floating point digits by doing `value.toString().split('.')[1]?.length ?? 0`. Would that be more appropriate here in general?

2024-01-05 17:12 UTC, xDivisionByZerox commented on test/modules/number.spec.ts
> -
Propably also from the latest next merge. I can see myself skipping over the difference in "multpleOf" and "precision", thus thinking it is the same test. I'll readd it.

2024-01-05 17:30 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +   * @param options.fractionDigits The number of digits to appear after the decimal point.
I liked the suggestion from @matthewmayer and did apply it. It was minimal, but included all information required.

2024-01-05 17:31 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +   * This parameter is ignored if `multipleOf` is given as well.
> On a TypeScript layer we could even provide conditional interfaces.

I thought about that as well, but decide against it due to our current limitations regard the documentation auto generation. I would see this as a potential DX improvment in the future tho.

2024-01-05 18:08 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +   * Defaults to `16`.
Removed the default.

2024-01-05 18:08 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +   * @throws If `max` is smaller than `min`.
Reverted to the message before and adjusted the other throws tags as well.

2024-01-05 18:11 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +    }
I don't really like this extra if statement here. Would you be down for a strategy pattern (fractionDigit, multipleOf, default) here? That would touch more existing code, tho.

2024-01-06 00:13 UTC, ST-DDT commented on test/modules/datatype.spec.ts
> +          }).toThrowError(`Max ${max} should be greater than min ${min}.`);
That is not what I meant:

> it('should throw when precision <= 0'

vs

> `.toThrowError(`Max ${max} should be greater than min ${min}.`);`

2024-01-06 00:15 UTC, ST-DDT commented on test/modules/number.spec.ts
> +          expect(actual).toBe(Number(actual.toFixed(2)));
No, my concern here is more about consistently using `Number.parseFloat(value)` vs `Number(value)`.

2024-01-06 00:17 UTC, ST-DDT commented on test/modules/number.spec.ts
> +          expect(actual).toBe(Number(actual.toFixed(2)));
Well nevermind. We mostly use `Number(value)` in our code.

2024-01-06 00:22 UTC, ST-DDT commented on src/modules/number/index.ts
> +    }
You might be able to simplify this if you decontruct the options to 
````ts
{
  ...
  fractionDigits,
  precision,
  multipleOf = precision ?? fractionDigits == null ? undefined : 10 ** -fractionDigits,
  orginalMulipleOf: multipleOf = precision,
} 
````

and then checking only

````ts
if (typeof fractionDigits === 'number' && typeof orginalMulipleOf === 'number') {
      throw new FakerError(
        'multipleOf and fractionDigits cannot exist at the same time.'
      );
    }
````

2024-01-10 12:46 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +    }
But then you are missing the specific validation for `fractionDigit`. `multipleOf` not allowed to be less than 0, so I expect the same for `fractionDigits`.
Furthermore, currently there is no check that `fractionDigits` is an integer. Should there be validation for that?

2024-01-10 12:53 UTC, xDivisionByZerox commented on test/modules/datatype.spec.ts
> +          }).toThrowError(`Max ${max} should be greater than min ${min}.`);
I see what you mean. 

My question remains: These tests indecate that the behaviour of `datatype.number` (and `datatype.float`) is altering. That would be considered breaking, no? So in theory, there should be no changes in this test files. So in optimal way I reset changes here and fix the current implementation to work as expected by our test. Is that correct?

2024-01-10 13:47 UTC, ST-DDT commented on src/modules/number/index.ts
> +    }
I didn't mean to imply the removal of the other verifications.

2024-01-10 15:10 UTC, matthewmayer commented on src/modules/number/index.ts
> +    }
Yes we should definitely check fractionDigits is an integer

2024-01-10 22:22 UTC, ST-DDT commented on src/modules/number/index.ts
> +    if (fractionDigits !== undefined) {
This and the check in line 189 is indentical. Maybe merge both branches?

````ts
if (fractionDigits !== undefined) {

  if (typeof originalMultipleOf === 'number') {
     [...]
  }

[...]
````

2024-01-10 22:22 UTC, ST-DDT commented on src/modules/number/index.ts
> +      if (fractionDigits % 1 !== 0) {
Maybe use `Number.isInteger(fractionDigits)` instead?

2024-01-10 22:22 UTC, ST-DDT commented on test/modules/datatype.spec.ts
> +          }).toThrowError(`Max ${max} should be greater than min ${min}.`);
AFAICT the current tests for datatype (although slightly changed) test for the same things as before and thus there are currently no breaking changes here. Or am I missing something?

2024-01-11 12:48 UTC, ST-DDT commented on src/modules/number/index.ts
> +      if (typeof originalMultipleOf === 'number') {
Should we use `!== undefined` here as well?

Also I just remembered that we mostly do `value != null` checks instead of `!== undefined`. Should we change the 2 checks in this method to be consistent with the rest?

2024-01-11 12:48 UTC, ST-DDT commented on src/modules/number/index.ts
> +          'multipleOf and fractionDigits cannot exist at the same time.'
```suggestion
          'multipleOf and fractionDigits cannot be set at the same time.'
```

2024-01-11 12:48 UTC, ST-DDT commented on src/modules/number/index.ts
> +        throw new FakerError('fractionDigits should be greater than 0.');
```suggestion
        throw new FakerError('fractionDigits should be greater than or equal to 0.');
```

2024-01-11 15:00 UTC, Shinigami92 commented on src/modules/number/index.ts
> +      if (typeof originalMultipleOf === 'number') {
I didn't wanted to be picky, but thx that someone else mentioned this 💚

2024-01-11 15:28 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +      if (typeof originalMultipleOf === 'number') {
> I didn't wanted to be picky, but thx that someone else mentioned this 💚

It's fine. In most personall projects I handle `null` and `undefined` explicit. Thats a habit that will slip in every now and then. Sorry about that^^

2024-01-13 15:22 UTC, ST-DDT commented
Could please fix the formatting and other CI issues?

2024-01-13 20:34 UTC, xDivisionByZerox commented
> Could please fix the formatting and other CI issues?

I'm not at home during the weekend. Feel free to change the PR.

2024-01-14 10:23 UTC, matthewmayer approved these changes, later dismissed

2024-01-14 11:47 UTC, ST-DDT approved these changes, later dismissed

2024-01-14 12:11 UTC, matthewmayer approved these changes, later dismissed

2024-01-14 16:48 UTC, Shinigami92 commented on src/modules/number/index.ts
> +   * If multipleOf is passed, the upper bound is inclusive and the `fractionDigits` option has to be excluded.
```suggestion
   * If `multipleOf` is passed, the upper bound is inclusive and the `fractionDigits` option has to be excluded.
```

2024-01-14 16:48 UTC, Shinigami92 commented on src/modules/number/index.ts
> +   * If multipleOf is passed, the upper bound is inclusive and the `fractionDigits` option has to be excluded.
Maybe better:

```diff
- and the `fractionDigits` option has to be excluded.
+ and the `fractionDigits` option need to be omitted.
```

2024-01-14 16:48 UTC, Shinigami92 commented on src/modules/number/index.ts
> +   * This parameter has to be excluded if `multipleOf` is provided.
```suggestion
   * This parameter has to be omitted if `multipleOf` is provided.
```

2024-01-14 16:48 UTC, Shinigami92 commented on test/modules/datatype.spec.ts
>          });
Why was this test changed?
1. Why the created git-blame for the min/max?
2. Why not checking anymore that a `FakerError` was returned? But just any kind of `Error`?

2024-01-14 16:48 UTC, Shinigami92 commented on test/modules/datatype.spec.ts
> -          );
Is https://github.com/faker-js/faker/pull/1855/files#diff-7a79dc63c7e78ab49e02d1bb360d4e99f509bfc534e77f659ac3f9895564d6fcR209 not reachable anymore? Or why was this test removed?

2024-01-14 16:48 UTC, Shinigami92 commented on test/modules/datatype.spec.ts
> +          }).toThrowError('multipleOf/precision should be greater than 0.');
Maybe check explicitly for `FakerError`s

2024-01-14 16:48 UTC, Shinigami92 commented on test/modules/number.spec.ts
> +        for (let i = 0; i < 100; i++) {
Instead of a for-loop, we could use a it.each here :thinking:  
_Is `eslint-plugin-vitest` still active? Why did it not report that?_

2024-01-14 17:52 UTC, ST-DDT commented on test/modules/datatype.spec.ts
> -          );
The test has not been removed only changed (`<` -> `<=`).

2024-01-18 10:34 UTC, ST-DDT commented on test/modules/number.spec.ts
> +        for (let i = 0; i < 100; i++) {
https://github.com/faker-js/faker/blob/d71bc47a4a7b127b41068016cbed3584a35b47ea/.eslintrc.js#L193

2024-01-18 10:38 UTC, ST-DDT commented on test/modules/datatype.spec.ts
> +          const max = 1;
```suggestion
          const min = 10;
          const max = 9;
```

2024-01-18 10:40 UTC, ST-DDT commented on test/modules/datatype.spec.ts
>          });
number -> float is a typo.
I reverted the min/max change and fixed the FakerError

2024-01-18 10:43 UTC, ST-DDT approved these changes

2024-01-18 11:13 UTC, matthewmayer approved these changes
i think the documentation to the whole method could still use an overall rewrite, but as its not really specific to this parameter change i'll do that as a seperate PR after this is merged.

2024-01-18 15:23 UTC, Shinigami92 approved these changes

2024-01-18 16:14 UTC, merged