feat: return randomly one of animals different types
faker-js/faker pull request #1871
Opened 2023-02-23 20:00 UTC by yasinpalizban

A new feature  for animal module, The function called ainmal.random() which  select randomly  of  animal types then pick up randomly one of selected animal.

here's  code
`
faker.ainmal.random();

`

2023-02-23 22:52 UTC, ST-DDT commented
Please add some tests for the new method and run `pnpm run preflight`.

2023-02-24 09:00 UTC, matthewmayer requested changes

2023-02-24 09:00 UTC, matthewmayer commented on src/modules/animal/index.ts
> +    switch (choice) {
You should be able to refactor this switch so it's not needed any more using 

const arrayOfCreatures = this.faker.definitions.animal[choice]

2023-02-24 09:05 UTC, matthewmayer requested changes

2023-02-24 09:05 UTC, matthewmayer commented on src/modules/animal/index.ts
> +    const choice: string = typeOfAnimals[index];
you can simplify this to `const choice: string = this.faker.helpers.arrayElement(typeOfAnimals)`

2023-02-24 13:52 UTC, yasinpalizban commented on src/modules/animal/index.ts
> +    const choice: string = typeOfAnimals[index];
thanks you for refactoring code   i apply your change to code

2023-02-24 13:53 UTC, yasinpalizban commented
> Please add some tests for the new method and run `pnpm run preflight`.

 i ran cmd you mentioned and add test functionality too.

2023-02-24 14:13 UTC, matthewmayer commented
See https://github.com/faker-js/faker/actions/runs/4263046776/jobs/7419510093

You can run `pnpm run test` to run the tests locally

You can see there are a couple of problems - your JSDoc needs to include `@since` - as this is a new method for 8.0.0 should have `@since 8.0.0`

Also the snapshot tests are out of date, you should be able to regenerate them by pressing "u" after pnpm run test completes, otherwise `pnpm run preflight` again should also do this.

2023-02-24 14:17 UTC, matthewmayer requested changes

2023-02-24 14:17 UTC, matthewmayer commented on src/modules/animal/index.ts
> +import type {Faker} from '../..';
undo this change

2023-02-24 14:17 UTC, matthewmayer commented on src/modules/animal/index.ts
> +   *   return randomly one of animals different types     .
Remove whitespace at start and end

2023-02-24 14:17 UTC, matthewmayer commented on src/modules/animal/index.ts
> +   * faker.animal.random() // 'bear'
you won't just get "bear" right, you'll get something like "Sloth bear"

2023-02-24 16:16 UTC, yasinpalizban commented
> See https://github.com/faker-js/faker/actions/runs/4263046776/jobs/7419510093
> 
> You can run `pnpm run test` to run the tests locally
> 
> You can see there are a couple of problems - your JSDoc needs to include `@since` - as this is a new method for 8.0.0 should have `@since 8.0.0`
> 
> Also the snapshot tests are out of date, you should be able to regenerate them by pressing "u" after pnpm run test completes, otherwise `pnpm run preflight` again should also do this.

when i run  ` npm run test test/animal.spec.ts` it oky but running this command ` npm run test test`  i get error which so wired

2023-02-24 16:27 UTC, matthewmayer commented
Please paste the output if you get errors and we can help diagnose what the problem is.

2023-02-24 16:45 UTC, yasinpalizban commented
> Please paste the output if you get errors and we can help diagnose what the problem is.

) first error
` 
test/docs/versions.spec.ts  (1 test | 1 failed) 14ms
   ❯ test/docs/versions.spec.ts > docs versions > oldVersions > should have a complete set of oldVersions
     → Cannot read properties of undefined (reading 'version')
`
) second error 
`
 test/faker.spec.ts  (71 tests | 1 failed) 41ms
   ❯ test/faker.spec.ts > faker > should not log anything on startup
     → Cannot find module '/home/hope/githup/faker/dist/cjs/index.js'. Please verify that the package.json has a valid "main" entry

`
) thired error
`
 ❯ test/locale-imports.spec.ts  (236 tests | 177 failed) 952ms
   ❯ test/locale-imports.spec.ts > locale imports > should be possible to directly require('@faker-js/faker/locale/af_ZA')
     → Cannot find module '../dist/cjs/locale/af_ZA'
Require stack:


`

then gose to error

2023-02-24 23:12 UTC, ST-DDT commented
I cannot diagnose the first error because you didn't sent the complete error message, usually it shows the failed line number as well. Like this:

![grafik](https://user-images.githubusercontent.com/1579362/221318486-de05aeab-1930-4af5-9c2d-5f13d75ac21f.png)

(btw you can fix the failing tests by running `pnpm run preflight` or `pnpm run test -u`

For the second and third error, you have to run `pnpm run build` once to fix them.

2023-02-25 16:10 UTC, Shinigami92 commented on src/modules/animal/index.ts
> +  }
I think this can be simplified

```suggestion
  /**
   * Returns a random animal.
   *
   * @example
   * faker.animal.sample() // 'Sloth bear'
   *
   * @since 8.0.0
   */
  sample(): string {
    return this.faker.helpers.objectValue(this.faker.definitions.animal);
  }
```

2023-02-25 16:16 UTC, yasinpalizban commented
after upgrade  node  js to 18.x   and  run this cmd  pnpm run test -u now i got this error 

 test/docs/versions.spec.ts  (1 test | 1 failed) 12ms
   ❯ test/docs/versions.spec.ts > docs versions > oldVersions > should have a complete set of oldVersions
     → Cannot read properties of undefined (reading 'version')

2023-02-25 17:01 UTC, ST-DDT commented
> after upgrade node js to 18.14.2 and run this cmd pnpm run test -u now i got this error
> 
> test/docs/versions.spec.ts (1 test | 1 failed) 12ms ❯ test/docs/versions.spec.ts > docs versions > oldVersions > should have a complete set of oldVersions → Cannot read properties of undefined (reading 'version')

Please post the complete error.

2023-02-25 17:04 UTC, ST-DDT commented on src/modules/animal/index.ts
> +  }
I'm not sure about that.

1. The category.entries are string[] and thus objectValue would return an array and not a simple string thereof.
2. I'm not sure whether we implemented the key set method in our definitions proxy.

2023-02-25 17:11 UTC, yasinpalizban commented
> > after upgrade node js to 18.14.2 and run this cmd pnpm run test -u now i got this error
> > test/docs/versions.spec.ts (1 test | 1 failed) 12ms ❯ test/docs/versions.spec.ts > docs versions > oldVersions > should have a complete set of oldVersions → Cannot read properties of undefined (reading 'version')
> 
> Please post the complete error.

this only error i got now 




 FAIL  test/docs/versions.spec.ts > docs versions > oldVersions > should have a complete set of oldVersions
TypeError: Cannot read properties of undefined (reading 'version')
 ❯ test/docs/versions.spec.ts:23:66
     21|         semver.valid(version)
     22|       );
     23|       const latestMajorRelease = semver.major(releaseVersions[0].version);
       |                                                                  ^
     24|       for (let i = 0; i < releaseVersions.length; i++) {
     25|         const { version, link } = releaseVersions[i];

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed | 35 passed (36)
      Tests  1 failed | 43752 passed | 1042 skipped | 25 todo (44820)
   Start at  20:38:50
   Duration  44.95s (transform 4.52s, setup 785ms, collect 155.86s, tests 44.76s)

 ELIFECYCLE  Command failed with exit code 1.
ERROR: "test:update-snapshots" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.

2023-02-25 17:22 UTC, Shinigami92 commented on src/modules/animal/index.ts
> +  }
I didn't tested it indeed, but `objectValue` seems to _correctly_ return `T[keyof T]`

https://github.com/faker-js/faker/blob/11a5f51ddb4ab1163d770c4b12f5fe4711b8e11d/src/modules/helpers/index.ts#L474

2023-02-25 17:32 UTC, Shinigami92 commented on src/modules/animal/index.ts
> +  }
Oh! You mean we need to use `this.faker.helpers.arrayElement(this.faker.helpers.objectValue(this.faker.definitions.animal))`

2023-02-25 23:50 UTC, ST-DDT commented
I will try to reproduce and fix the error locally.

2023-02-26 17:29 UTC, yasinpalizban commented
> I will try to reproduce and fix the error locally.

i dig in codes and find out the bug,  
`
// version must be number  x.y.z  not string next or latest
// this line of code semver.valid() return null 
// it should be like that semver.valid(semver.coerce('42.6.7.9.3-alpha')) 
const releaseVersions = oldVersions.filter(({ version }) =>
        semver.valid(version)
      );
//this  line code is not working because is empty array 
      const latestMajorRelease = semver.major(releaseVersions[0].version);
    
 

`

2023-02-26 18:37 UTC, ST-DDT commented
You are almost right.
You only forked the next branch, but not the v8 or v7 branches. So it doesnt find them whem you build the project locally. I have to think how I can adjust the test to ensure the test works as expected for us, but doesnt break other users builds.

2023-03-09 18:08 UTC, xDivisionByZerox commented
On hold until user intrest has been confirmed. Please upvote the related issue #1618 if you want this to be pushed.

2024-04-05 15:27 UTC, ST-DDT commented
Superseded by #2786

2024-04-05 15:27 UTC, closed without merging