refactor(location): zip code state
faker-js/faker pull request #1874
Opened 2023-02-24 10:48 UTC by Shinigami92

references https://github.com/faker-js/faker/issues/1346#issuecomment-1407728227

2023-02-24 11:42 UTC, Shinigami92 commented
@faker-js/maintainers @faker-js/members Is the current impl good enough? Or should we still throw a `FakerError` for missing `state` and make therefore a breaking change for the deprecated `zipCodeForState`?

2023-02-24 12:03 UTC, matthewmayer commented
I think in general breaking changes happening at the same time as deprecating a methods is a bad idea. The point of deprecation is "you have one major version where your existing code will continue to work without changes".

2023-02-24 12:17 UTC, Shinigami92 commented
> I think in general breaking changes happening at the same time as deprecating a method is a bad idea. The point of deprecation is "you have one major version where your existing code will continue to work without changes".

Beside that: I'm asking because I don't see the need to throw a FakerError instead of doing a fallback 🤷
It just needs to be documented so if someone asks, we can point to the documentation 🙂

2023-02-24 23:21 UTC, ST-DDT commented on src/modules/location/index.ts
> +      }
````ts
else throw new FakerError
````

2023-02-24 23:21 UTC, ST-DDT commented on src/modules/location/index.ts
> +    return this.zipCode({ state });
IMO there is no need to repackage the options, just pass them along as is.

```suggestion
    return this.zipCode(options);
```

2023-02-24 23:21 UTC, ST-DDT commented on src/modules/location/index.ts
> +           * to the locale's zip format.
IMO this should throw an error instead.

2023-02-24 23:24 UTC, ST-DDT commented on src/modules/location/index.ts
> +      }
We can do that in a separate PR if you want, but if I pass something, then I usually want to actually use it.

Should I reopen: https://github.com/faker-js/faker/issues/1736 ?

2023-03-24 07:53 UTC, Shinigami92 commented on src/modules/location/index.ts
> +      throw new FakerError(`No zip code range found for state "${state}"`);
@ST-DDT Please use GH suggestion to adjust this message to your needs/requirments

2023-03-24 08:02 UTC, Shinigami92 commented on test/location.spec.ts
> +        .it('with options', { state: 'CA', format: '###-###' });
@ST-DDT how do I set the locale for these snapshot tests?

2023-03-24 09:16 UTC, ST-DDT commented on src/modules/location/index.ts
> +           * have a postcode_by_state definition an error is thrown.
IMO this is redundant:

```suggestion
           * If the currrent locale does not have a corresponding `postcode_by_state` definition, an error is thrown.
```

2023-03-24 09:16 UTC, ST-DDT commented on src/modules/location/index.ts
> +      throw new FakerError(`No zip code range found for state "${state}"`);
```suggestion
      throw new FakerError(`No zip code definition found for state "${state}"`);
```

2023-03-24 09:18 UTC, ST-DDT commented on test/location.spec.ts
> +        .it('with options', { state: 'CA', format: '###-###' });
That is currently usupported, and I'm not sure how to change that.

2023-03-24 09:19 UTC, ST-DDT requested changes

2023-03-24 09:19 UTC, ST-DDT commented on test/__snapshots__/location.spec.ts.snap
> -exports[`location > 1337 > zipCodeByState > with string 2 1`] = `"51225"`;
What happened to these snapshots?

2023-03-24 10:32 UTC, Shinigami92 commented on test/location.spec.ts
> +        .it('with options', { state: 'CA', format: '###-###' });
So should I just remove these and ignore snapshot tests for these options?

2023-03-24 10:33 UTC, Shinigami92 commented on test/__snapshots__/location.spec.ts.snap
> -exports[`location > 1337 > zipCodeByState > with string 2 1`] = `"51225"`;
I have not looked into them yet, because the tests are failing at all
For me the end result of this (currently in draft) PR is relevant

2023-03-24 10:34 UTC, Shinigami92 commented on src/modules/location/index.ts
> +    return this.zipCode({ state });
How important is this change to you and do you have a reason for passing the whole options instead only what is needed?

2023-03-24 15:49 UTC, ST-DDT commented on src/modules/location/index.ts
> +    return this.zipCode({ state });
Because it is the same, and even if not, it doesn't matter either.
It is not important to me though.

2023-03-24 15:50 UTC, ST-DDT commented on test/location.spec.ts
> +        .it('with options', { state: 'CA', format: '###-###' });
I would comment them out and add a comment why, but yes.

2023-03-24 15:53 UTC, ST-DDT requested changes

2023-03-24 15:53 UTC, ST-DDT commented on src/modules/location/index.ts
> +   * have a postcode_by_state definition an error is thrown.
```suggestion
   * If the currrent locale does not have a corresponding `postcode_by_state` definition, an error is thrown.
```

2023-03-24 15:53 UTC, ST-DDT commented on src/modules/location/index.ts
>     * Only works for locales with postcode_by_state definition. If a locale does not
```suggestion
   * If the currrent locale does not have a corresponding `postcode_by_state` definition, an error is thrown.
```

2023-03-24 15:53 UTC, ST-DDT commented on src/modules/location/index.ts
> +   * have a postcode_by_state definition an error is thrown.
```suggestion
```

2023-03-24 15:53 UTC, ST-DDT commented on src/modules/location/index.ts
> +   * @deprecated Use `faker.location.zipCode({ state })` instead.
Please add an `@see` to `faker.location.zipCode()` (not sure in which order it should be though).

2023-03-27 08:45 UTC, Shinigami92 commented on test/location.spec.ts
> +        .it('with options', { state: 'CA', format: '###-###' });
Should I open an issue for tackling this?

2023-03-27 08:47 UTC, Shinigami92 commented on test/__snapshots__/location.spec.ts.snap
> -exports[`location > 1337 > zipCodeByState > with string 2 1`] = `"51225"`;
Oh, because the implementation now changed (it uses `zipCode()` which now throws an error) so these were removed by vitest because they do not process a result anymore but an error

2023-03-27 09:25 UTC, Shinigami92 commented
There is an issue that can be better identified by merging

- https://github.com/faker-js/faker/pull/1969

first

2023-04-02 12:40 UTC, ST-DDT approved these changes, later dismissed

2023-04-04 03:08 UTC, matthewmayer commented on src/modules/location/index.ts
> +   * If the current locale does not have a corresponding `postcode_by_state` definition, an error is thrown.
Should this be documented in upgrading.html as a breaking change?

2023-04-04 18:41 UTC, Shinigami92 commented on src/modules/location/index.ts
> +   * If the current locale does not have a corresponding `postcode_by_state` definition, an error is thrown.
pls check again

2023-04-04 20:38 UTC, ST-DDT approved these changes

2023-04-07 11:14 UTC, xDivisionByZerox approved these changes
My comment are non blocking. So feel free to resolve them if you don't think they are important.

2023-04-07 11:14 UTC, xDivisionByZerox commented on test/location.spec.ts
> +          const zipCode1 = +fakerEN_US.location.zipCode({ state });
Maybe `actual`, `result` or `value`? ^^

2023-04-09 06:36 UTC, Shinigami92 commented
To proceed with this, I will merge it for now
We can extract issues or do several PRs like unifying the test variable names

2023-04-09 06:43 UTC, merged