fix(test): commit entry emails dont allow hyphens
faker-js/faker pull request #1876
Opened 2023-02-24 11:55 UTC by matthewmayer

extracted from #1872

2023-02-24 12:12 UTC, Shinigami92 commented
Lets discuss in a meeting if hyphens are valid or at least common enough to be considered as generate-able inside a `commitEntry` or if we should just strip them away and consider them as uncommon

2023-02-24 14:01 UTC, matthewmayer commented
if they are valid in faker.internet.email(), they should also be valid as part of an email address in commitEntry

2023-02-24 14:14 UTC, Shinigami92 commented
> if they are valid in faker.internet.email(), they should also be valid as part of an email address in commitEntry

Or we remove that in email function as well

The implementation is still from v5.5.3 and not written by the new maintainers

2023-02-24 14:18 UTC, ST-DDT commented
I think we can easily test this by using https://github.com/validatorjs/validator.js/blob/master/src/lib/isEmail.js once.

2023-02-24 14:49 UTC, matthewmayer commented
Hyphens are allowed in email addresses through some providers like gmail don't allow registering usernames including a -

2023-02-24 22:58 UTC, ST-DDT approved these changes

2023-02-27 17:45 UTC, xDivisionByZerox submitted a review, later dismissed

2023-02-28 08:35 UTC, Shinigami92 commented
We have another report about "email not valid"
- #1882

I start to feel more and more unsafe about our current email implementation and we should think about to prevent such cases directly inside the email function.
E.g. generating a mail with or without including `-` could be an option that needs to be toggled on explicitly

2023-02-28 08:48 UTC, matthewmayer commented
> We have another report about "email not valid"
> 
> * [email address local part shouldnt start or end with . #1882](https://github.com/faker-js/faker/issues/1882)
> 
> I start to feel more and more unsafe about our current email implementation and we should think about to prevent such cases directly inside the email function. E.g. generating a mail with or without including `-` could be an option that needs to be toggled on explicitly

Perhaps could deprecate `allowSpecialCharacters` and replace it with toggles for individual characters. But i think thats out of scope for this PR.

2023-02-28 08:57 UTC, Shinigami92 commented
It's not fully out of scope, but affected by a side-effect

https://github.com/faker-js/faker/blob/59157a429a1bcde3f78bd9009f6de02358365ba2/src/modules/git/index.ts#L120

Here we don't pass any options to the email function
So because `allowSpecialCharacters` is default to `false`, I would expected that this also strips out special characters like `-`
So therefore the current implementation does not fulfill my expectations

... its getting even madder 👀 
checking these lines:
https://github.com/faker-js/faker/blob/59157a429a1bcde3f78bd9009f6de02358365ba2/src/modules/internet/index.ts#L96-L98

why does the `-` even survive at the end at all?!

2023-02-28 09:44 UTC, matthewmayer commented
- is permitted by the regex

I dislike the current allowSpecialCharacters implementation. It's weird which is why I haven't touched it!

2023-02-28 09:46 UTC, matthewmayer commented
AllowSpecialCharacters is really "substitute some random special chars in which may break things in interesting ways" which is almost certainly never desirable.

2023-02-28 10:04 UTC, Shinigami92 commented
@matthewmayer don't get me wrong, I'm thankful that you bring this forward and are patient to this
But I think we need more in depth decisions with the team of how we should proceed here
This "bug" is currently not in our top prio, so this wont get released in a bug-fix version soon anyway, therefore we have a bit time to no stress the merge of this PR and can focus on try to make it right and analyze not how to fight the symptom but also fix the root-cause

2023-02-28 10:12 UTC, matthewmayer commented
> @matthewmayer don't get me wrong, I'm thankful that you bring this forward and are patient to this But I think we need more in depth decisions with the team of how we should proceed here This "bug" is currently not in our top prio, so this wont get released in a bug-fix version soon anyway, therefore we have a bit time to no stress the merge of this PR and can focus on try to make it right and analyze not how to fight the symptom but also fix the root-cause

understood, though note this blocks #1872. Non-english locales already generate emails with hyphens in them, its just that the tests only check this in `en` at the moment.

2023-02-28 10:23 UTC, matthewmayer commented
So i think there are really two discussions

1. With allowSpecialCharacters=false (the default, so 95% of users will probably be doing this), what characters should be allowed - currently A-Za-z0-9 and then four special chars:  _ - + .

```
_ seems well supported
- is well supported for sending but some providers dont allow registration in local parts
+ has fairly good support, it is used in emails like somebody+extension@gmail.com
. is well supported but has special rules about not being at start and end https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html
```

Once that's decided, the regexes for testing in faker.internet.email and faker.git.commitEntry should be aligned

Then figure out what to do with allowSpecialCharacters

2023-03-01 01:51 UTC, import-brain submitted a review, later dismissed

2023-03-11 19:59 UTC, ST-DDT requested changes
Looks like we forgot to actually post our decision on this PR.

**Team Decision**

Instead of using a custom regex, that might fail with any refactor, we should grep the email address from that line and check it with validatorjs.isEmail.
The validator function has an option `require_display_name`, that can be used to require it to have a display name like the commit entry has.

````ts
expect(parts[n]).toMatch(/^Author: .*$/);
expect(parts[n].substring(8)).toSatisfy(v -> isEmail(v, { require_display_name: true }));
````

We also discussed changing the email function:

- https://github.com/faker-js/faker/issues/1919

2023-03-14 08:39 UTC, matthewmayer commented
> Instead of using a custom regex, that might fail with any refactor, we should grep the email address from that line and check it with validatorjs.isEmail. 

but how are you gonna extract the email address from the line without using a regex in the first place :D

2023-03-14 09:16 UTC, ST-DDT commented
> but how are you gonna extract the email address from the line without using a regex in the first place :D

As written above (using `substring`):

````ts
expect(parts[n]).toMatch(/^Author: .*$/);
expect(parts[n].substring(8)).toSatisfy(v -> isEmail(v, { require_display_name: true }));
````

2023-03-15 12:00 UTC, ST-DDT submitted a review, later dismissed

2023-03-15 12:02 UTC, ST-DDT commented
Any idea why the tests fail? Did I make a mistake with the require_display_name part?

2023-03-15 13:08 UTC, matthewmayer commented
> Any idea why the tests fail? Did I make a mistake with the require_display_name part?

it appears dots in the display name fail the validator. it expects them to be quoted.

> v.isEmail('Mavis.Wunsch57 <Mavis.Wunsch81@hotmail.com>',{allow_display_name:true})
false
> v.isEmail('Mavis Wunsch57 <Mavis.Wunsch81@hotmail.com>',{allow_display_name:true})
true
> v.isEmail('"Mavis.Wunsch57" <Mavis.Wunsch81@hotmail.com>',{allow_display_name:true})
true

2023-03-15 13:48 UTC, matthewmayer commented
it seems git doesnt follow the exact same rules as display names for email addresses per RFC 5322

For example i can run
```
git config --global user.name "Mona,Lisa"
or
git config --global user.name "Mona.Lisa"
```
and then in git log commits show without quoting the display name, although those would be required by RFC 5322

2023-03-15 22:15 UTC, ST-DDT commented
I think for our purposes it is enough if we modify that part to always include the quotes.

````ts
x.replace(/^(.*) </, '"$1" <')
````

Would that work?

2023-03-16 03:43 UTC, matthewmayer commented
You mean replace it in the test? Or replace what commitEntry produces?

2023-03-16 07:46 UTC, ST-DDT commented
> You mean replace it in the test? Or replace what commitEntry produces?

Yes, only in the test as the git output seems to omit the quotes as well.

2023-03-16 09:13 UTC, ST-DDT approved these changes

2023-03-16 16:25 UTC, xDivisionByZerox approved these changes

2023-03-16 17:59 UTC, Shinigami92 approved these changes

2023-03-16 18:04 UTC, merged