fix (internet): dont allow email addresses with . at ends or .. in middle
faker-js/faker pull request #1883
Opened 2023-02-28 09:03 UTC by matthewmayer

fix #1882

2023-02-28 21:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    localPart = localPart.replace(/\.$/, '');
This should also catch multiple dots:

```suggestion
    localPart = localPart.replace(/^\.+/, '');
    localPart = localPart.replace(/\.+$/, '');
```

2023-02-28 21:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    localPart = localPart.replace(/\.$/, '');
Alternatively:

```suggestion
    localPart = localPart.replace(/^\.+|\.+$/g, '');
```

2023-02-28 21:09 UTC, ST-DDT commented on test/internet.spec.ts
> +          const email = faker.internet.email('.Aiden');
```suggestion
          const email = faker.internet.email('...Aiden');
```

2023-02-28 21:09 UTC, ST-DDT commented on test/internet.spec.ts
> +        it('should not allow an email that starts with a .', () => {
Maybe add a similar test that ends with multiple dots / or combine them into one by having both.

2023-03-01 08:42 UTC, matthewmayer commented on src/modules/internet/index.ts
> +    localPart = localPart.replace(/\.$/, '');
but if we already collapsed multiple dots into one on line 113, there can only be max 1 dot at start or end?

2023-03-01 08:44 UTC, matthewmayer commented on test/internet.spec.ts
> +        it('should not allow an email that starts with a .', () => {
the email function appends numbers etc though, so even if the first name and last name ends with dots, the email normally won't like
`faker.internet.email("Matt...","Mayer....")` // Matt.Mayer.63@gmail.com

2023-03-01 10:06 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    localPart = localPart.replace(/\.$/, '');
Yeah, you are right.

2023-03-01 20:14 UTC, Shinigami92 submitted a review, later dismissed

2023-03-01 20:14 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +    //local parts may not contain two or more consecutive . characters
```suggestion
    // local parts may not contain two or more consecutive . characters
```

2023-03-01 20:14 UTC, Shinigami92 commented on src/modules/internet/index.ts
> +    //local parts may not start with or end with a . character
```suggestion
    // local parts may not start with or end with a . character
```

2023-03-03 16:28 UTC, ST-DDT commented on test/internet.spec.ts
> +        it('should not allow an email that starts with a .', () => {
That may be true now, but what if we add a chance that the isn't an appendix to the name?

I think we can test is by changing the following line to (and adjust the test name accordingly):

````ts
const email = faker.internet.email('...Aiden...', '...Doe...');
````
and then test also for:

````ts
expect(prefix).not.toMatch(/\.{2}/);
expect(prefix).not.toMatch(/\.$/);
````

2023-03-03 16:28 UTC, ST-DDT commented on test/internet.spec.ts
> +          expect(prefix).not.toMatch(/^(\.)/);
Is there a reason why you put the dot in parenthesis?

```suggestion
          expect(prefix).not.toMatch(/^\./);
```

2023-03-04 23:34 UTC, ST-DDT requested changes
See above

2023-03-05 08:43 UTC, ST-DDT approved these changes

2023-03-05 08:44 UTC, ST-DDT commented
Thank you for fixing this.

2023-03-08 16:20 UTC, Shinigami92 approved these changes

2023-03-08 17:35 UTC, xDivisionByZerox approved these changes

2023-03-08 21:51 UTC, merged