chore: add support for readonly arrays
faker-js/faker pull request #189
Opened 2022-01-17 03:57 UTC by clarkerican

TODO: Revisit to add TS tests once this PR (https://github.com/faker-js/faker/pull/186/files) is merged. 

I searched for all parameters that have `T[]` and don't modify the array.

2022-01-17 07:38 UTC, Shinigami92 commented
Is this just enough? I expected something like `ReadonlyArray<T> | T[]` :thinking: 
Did you tested it locally? I'm afraid of breaking simple array typing ^^'

2022-01-17 17:20 UTC, Shinigami92 approved these changes
I tested a bit in [TS Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAJwIZgCZwLYwF4CmAPACqIC8iAzlMjGAOYB8AFKsmgJ4BcKBqWMABtOiEgG0AuhUTiA5KjkAaRHIBGy1RDnTUVROADWYOAHckesVICUvMgG8AsAChEfKCGQWOqTuIAMkgDcLgC+Li4QCDSI7MgAjLw0dIxSMvKKKuqactqSEc5RYDHIBFQgQlCJ1LT0DDJomDj4BGwc8dYFRTFxAEy8AEr8giIAgj6cRMl1TOkKORpZeV3RUHzllf01KfWUjVi4hG3IvdZAA) and everything works find :+1:

2022-01-18 14:22 UTC, damienwebdev requested changes

2022-01-19 09:47 UTC, stefanprobst commented on src/helpers.ts
> +  randomize<T = string>(array: ReadonlyArray<T> = ['a', 'b', 'c'] as unknown as ReadonlyArray<T>): T {
why?

2022-01-19 10:19 UTC, Shinigami92 commented on src/helpers.ts
> +  randomize<T = string>(array: ReadonlyArray<T> = ['a', 'b', 'c'] as unknown as ReadonlyArray<T>): T {
I'm with @stefanprobst, cause readonly arrays seem to just say that the function has the "contract" of: "I will not push or remove elements to/from this array you give me"
An `Array` is a subset of a `ReadonlyArray` and not the other way around, therefore an union of `ReadonlyArray<T> | T[]` would just collapse into `ReadonlyArray<T>` anyways.

2022-01-19 18:20 UTC, import-brain approved these changes

2022-01-19 18:43 UTC, damienwebdev approved these changes
lgtm

2022-01-19 18:45 UTC, merged