docs: add reproducible results section
faker-js/faker pull request #1892
Opened 2023-03-04 11:04 UTC by matthewmayer

Improved docs re #1870

2023-03-04 11:44 UTC, ST-DDT approved these changes, later dismissed

2023-03-04 11:50 UTC, Shinigami92 commented on docs/guide/usage.md
> +Note that when upgrading to a new version of Faker, you may get different values for the same seed, as the underlying data (lists of names, words etc) may have changed.
Should we actually embed this into a "note" block?

2023-03-04 14:23 UTC, matthewmayer commented on docs/guide/usage.md
> +Note that when upgrading to a new version of Faker, you may get different values for the same seed, as the underlying data (lists of names, words etc) may have changed.
done

2023-03-04 14:57 UTC, ST-DDT submitted a review, later dismissed

2023-03-07 20:06 UTC, import-brain submitted a review, later dismissed

2023-03-08 16:16 UTC, Shinigami92 submitted a review, later dismissed

2023-03-08 17:31 UTC, xDivisionByZerox requested changes

2023-03-08 17:31 UTC, xDivisionByZerox commented on docs/guide/usage.md
> +There are a few relative date methods for which setting a random seed is not sufficient to have reproducible results, specifically: `faker.date.past`, `faker.date.future`, `faker.date.birthdate`, `fa
I would not specifically list the methods which fit the criteria since we would need to edit this documentation section based on new features or even changes made in the future. I would say something like "Methods which interact with dates" instead.

If we do want to list all methods `faker.git.commitEntry` is missing.

2023-03-14 09:49 UTC, matthewmayer commented on docs/guide/usage.md
> +There are a few relative date methods for which setting a random seed is not sufficient to have reproducible results, specifically: `faker.date.past`, `faker.date.future`, `faker.date.birthdate`, `fa
i added git.commitEntry and changed the wording to make it not sound like this is an exhaustive list (though it currently is), so in the event another relative date method is added, the docs are not wrong.

2023-03-14 10:38 UTC, xDivisionByZerox approved these changes

2023-03-14 11:20 UTC, import-brain approved these changes

2023-03-14 20:01 UTC, ST-DDT approved these changes

2023-03-14 20:09 UTC, merged