wip
faker-js/faker pull request #1897
Opened 2023-03-05 23:53 UTC by beaunus

2023-03-06 03:04 UTC, matthewmayer commented
FYI you could probably make use of faker.system.commonFileName and other methods in faker.system.* for the paths and filenames

2023-03-06 07:43 UTC, Shinigami92 requested changes

2023-03-06 07:43 UTC, Shinigami92 commented on src/modules/git/index.ts
> +  committedFile({ isBinary = false, isNumStat = false } = {}): string {
```suggestion
  /**
   * fill this
   */
  committedFile(options: {
    /**
     * fill this
     */
    isBinary?: boolean,
    /**
     * fill this
     */
    isNumStat?: boolean
  } = {}): string {
    const { isBinary = false, isNumStat = false } = options;
```

2023-03-06 11:19 UTC, beaunus commented
> FYI you could probably make use of faker.system.commonFileName and other methods in faker.system.* for the paths and filenames

Thank you for the pointer!

2023-03-06 11:20 UTC, beaunus commented on src/modules/git/index.ts
> +  committedFile({ isBinary = false, isNumStat = false } = {}): string {
Thank you!

I'll close this PR and re-open when it's ready for review.

I thought that the "Draft" status would not get the attention of the review team. I'll do my best to conform to the CONTRIBUTING doc when it's ready for review.

2023-03-06 13:32 UTC, ST-DDT commented on src/modules/git/index.ts
> +  committedFile({ isBinary = false, isNumStat = false } = {}): string {
Sorry for the trouble. We are currently undecided when and what to review in draft PRs. From my experience, I can tell that the rules vary from repo to repo so it might be best to explicitly mention the own expectations in the description.
Somethink like:
> This is an early draft, feedback and suggestions welcome, but please no reviews yet.

2023-03-06 16:23 UTC, Shinigami92 commented on src/modules/git/index.ts
> +  committedFile({ isBinary = false, isNumStat = false } = {}): string {
Oh that was my bad, it was not my intention to let you close the PR
and setting it to draft is the correct way
I just had the time and will to just write that suggestion/review
And yes, we are a very active repository ^^

2023-04-12 22:16 UTC, ST-DDT commented
How is the status on this PR?

2023-09-21 16:45 UTC, ST-DDT commented
It looks like this PR got stale. I'm closing this. Feel free to comment/create a new PR when you wish to continue.

2023-09-21 16:45 UTC, closed without merging