feat: provide enums for color values
faker-js/faker pull request #1910
Opened 2023-03-07 16:55 UTC by Shinigami92

Extracted from https://github.com/faker-js/faker/pull/1748#discussion_r1128162369

2023-03-07 21:19 UTC, ST-DDT requested changes

2023-03-07 21:19 UTC, ST-DDT commented on src/modules/color/index.ts
> +    return this.faker.helpers.arrayElement(Object.values(CssFunction));
```suggestion
    return this.faker.helpers.objectValues(CssFunction);
```

2023-03-07 21:19 UTC, ST-DDT commented on src/modules/color/index.ts
> +    return this.faker.helpers.arrayElement(Object.values(CssSpace));
```suggestion
    return this.faker.helpers.objectValues(CssSpace);
```

2023-03-08 10:09 UTC, xDivisionByZerox commented on src/modules/color/index.ts
> +  SRGB = 'sRGB',
Should we add additional JSDocs to each key?

2023-03-08 10:09 UTC, xDivisionByZerox commented on src/modules/color/index.ts
> +    return this.faker.helpers.arrayElement(Object.values(CssFunction));
While this works in the current situation, we need to be careful with numeric enums.

```ts
enum Foo {
  BAR = 0;
};

console.log(Foo); // { Foo: 0, "0": "Foo" }, this is the JS object
console.log(faker.helpers.objectValue(Foo)); // 0 | "Foo"
console.log(faker.helpers.objectKey(Foo)); // "0" | "Foo"
```

How do you feel about `enumKey` and `enumValue` as helper function for those use cases?

2023-03-08 12:54 UTC, ST-DDT commented on src/modules/color/index.ts
> +    return this.faker.helpers.arrayElement(Object.values(CssFunction));
@xDivisionByZerox Could you please create a separate issue/PR for that?
Maybe with a hint on how to distinguish between enum keys and values?

2023-03-08 13:09 UTC, xDivisionByZerox commented on src/modules/color/index.ts
> +    return this.faker.helpers.arrayElement(Object.values(CssFunction));
Yes of course. I first wanted to clarify if we do want to be concerned about that topic or if we simply ignore it. 
I'll create an issue for further discussions. Mark my concern as resolved here.

2023-03-08 16:03 UTC, Shinigami92 commented on src/modules/color/index.ts
> +    return this.faker.helpers.arrayElement(Object.values(CssFunction));
Do not use Ordinal Enums in TypeScript, ever
Or at least only if you are not a library but an App that uses these enums internally
Enums in TypeScripts are nearly to antipattern and just pollute the emitted code
There are mostly any time a better way instead of using Enums at all in JS

- https://thoughtbot.com/blog/the-trouble-with-typescript-enums
- https://dev.to/dvddpl/whats-the-problem-with-typescript-enums-2okj
- https://www.reddit.com/r/typescript/comments/yr4vv5/typescript_enums_are_terrible_heres_why/
- https://bluepnume.medium.com/nine-terrible-ways-to-use-typescript-enums-and-one-good-way-f9c7ec68bf15
- https://blog.logrocket.com/why-typescript-enums-suck/

2023-03-08 16:06 UTC, Shinigami92 commented on src/modules/color/index.ts
> +    return this.faker.helpers.arrayElement(Object.values(CssFunction));
> [...]
> 
> How do you feel about `enumKey` and `enumValue` as helper function for those use cases?

Only implement this, if someone from outside the core members is asking for it

2023-03-08 16:08 UTC, Shinigami92 commented on src/modules/color/index.ts
> +  SRGB = 'sRGB',
We also did not for `enum Sex`

I don't think it is necessary

2023-03-08 16:37 UTC, ST-DDT approved these changes

2023-03-08 16:39 UTC, ST-DDT commented on src/modules/color/index.ts
> +    return this.faker.helpers.arrayElement(Object.values(CssFunction));
FYI: My comment was more about implementability than actual implementation.

2023-03-12 11:48 UTC, xDivisionByZerox approved these changes

2023-03-14 17:37 UTC, merged