feat(enum): Add random selector of enum value
faker-js/faker pull request #1920
Opened 2023-03-11 20:30 UTC by ocodista

With this method it is possible to get a random value from an enum.

This is very useful for not having to harcode an enum when generating fake data.

2023-03-11 20:46 UTC, ST-DDT requested changes

2023-03-11 20:46 UTC, ST-DDT commented on test/__snapshots__/datatype.spec.ts.snap
> +exports[`datatype > 1211 > enum > with string enum 1`] = `undefined`;
This doesnt seem right.

2023-03-11 20:46 UTC, ST-DDT commented on test/__snapshots__/datatype.spec.ts.snap
> +exports[`datatype > 1337 > enum > with enum starting from some index 1`] = `undefined`;
Neither does this.

2023-03-12 00:15 UTC, ocodista commented on test/__snapshots__/datatype.spec.ts.snap
> +exports[`datatype > 1337 > enum > with enum starting from some index 1`] = `undefined`;
Fixed

2023-03-12 00:16 UTC, ocodista commented on test/__snapshots__/datatype.spec.ts.snap
> +exports[`datatype > 1211 > enum > with string enum 1`] = `undefined`;
You're right, fixed now!

2023-03-12 09:27 UTC, ST-DDT reviewed
This method closely resembles how helpers.arrayElement and objectValue work, so we should move it to the helpers module instead.

2023-03-12 09:27 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +   * faker.datatype.enum(enum { A, B, C}) // 'A'
These three examples all have the same parameters. Please change them to show different usecases and remove redundant ones.

2023-03-12 09:27 UTC, ST-DDT commented on test/datatype.spec.ts
> +    });
Afaik it is also possible to define mixed enums. Could you please define a test for them too?

2023-03-12 09:27 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +    const randomOption = (enumObject as any)[
You can use helpers.arrayElement(keys) to simplify the code a bit.

2023-03-12 10:24 UTC, Shinigami92 commented on test/datatype.spec.ts
> +      }
1. Please use `PascalCase` for enum names

2. Please use representative example enums like `Color {Red,Green,Blue}` or `Direction {North,East,South,West}` or something like that

2023-03-12 10:25 UTC, Shinigami92 commented on test/datatype.spec.ts
> +    t.describe('enum', (t) => {
Please also add tests below in the `random seeded tests for seed ...` section

2023-03-12 11:01 UTC, matthewmayer commented
How will this method work in JavaScript given that enums are typescript-specific?

2023-03-12 11:20 UTC, xDivisionByZerox commented on src/modules/datatype/index.ts
> +   * faker.datatype.enum(enum { A, B, C}) // 'A'
I suggest explicitly providing one enum with numeric and string values each. Something like:
```ts
* @example
* faker.datatype.enum(enum Strings { HELLO: 'world', FOO: 'bar' }) // 'HELLO'
* faker.datatype.enum(enum Numbers { FOO: 0, BAR, 1, BAZ: 2 }) // 'FOO'
```

2023-03-12 11:20 UTC, xDivisionByZerox commented on src/modules/datatype/index.ts
> +   * Returns a random value from an Enum object
```suggestion
   * Returns a random value from an Enum object.
```

2023-03-12 11:20 UTC, xDivisionByZerox commented on src/modules/datatype/index.ts
> +  enum<GenericEnumType extends Object, SpecificEnumType>(
I would suggest moving the implementation into the `HelpersModule` as we plan on deprecating the `DatatypeModule`.

2023-03-12 11:20 UTC, xDivisionByZerox commented on src/modules/datatype/index.ts
> +   * Returns a random value from an Enum object
The description says that an enum value is returned, but the current implementation returns a key. So which one is correct?

2023-03-12 11:27 UTC, Shinigami92 commented
> How will this method work in JavaScript given that enums are typescript-specific?

Funny answer: That's the funny part, it wont

Technical correct answer:
Enums are converted to JS bloatware code constructs like this:
```ts
enum Color { Red, Green, Blue }

var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Green"] = 1] = "Green";
    Color[Color["Blue"] = 2] = "Blue";
})(Color || (Color = {}));
```

So normally you are BY FAR more better suited with setups like `var Color = Object.freeze({ Red: 0, Green: 1, Blue: 2 })`, which are not only provide less bloated code, but also performs much better at runtime as they can be optimized by JS engines.
Additionally you are bringing just JS over TS into JS and TS doesn't need to first transpile it to something JS-usable.

Then there are `const enums` to prevent generating of such bloatware code but it theoretically disables the need in total of enums and you can just use `type` string literals (like e.g. our `SexType`). These then just check at compile time if the type literal is suitable for the intended call/usage and has zero runtime overhead.

TL;DR: enums in TS are a total misconcept and failure and Microsoft / the TS Team knows that and communicate that in the past already (I just sadly don't find a source directly for that).

So there is only few really case for using enums (and the should be used carefully):
- when your programmer audience is not JS native and have also OOP background like Java or C#
- when you are using them only in your own code and want to over-optimize the readability of your TS code base

When using them in a library (like FakerJS), **always ensure** they are 100% optional and you can always call the function in a readable easy way like using string literals.

2023-03-12 12:16 UTC, xDivisionByZerox commented
> Funny answer: That's the funny part, it wont

I call BS. An enum as you pointed out is simply converted to a JS object. That means you can use it like a JS object. That means you can use all methods as you would in TS. The catch is that those enum objects need to be handled a little bit differently on our side.

String enums work the same as normal objects would.
```ts
// in js
const myObject = Object.freeze({
  FOO: 'bar',
  HELLO: 'world',
});

faker.helpers.objectKey(myObject); // 'FOO' | 'HELLO'
faker.helpers.enumKey(myObject); // 'FOO' | 'HELLO'

faker.helpers.objectValue(myObject); // 'bar' | 'world'
faker.helpers.enumValue(myObject); // 'bar' | 'world'

// in ts
enum MyEnum {
  FOO: 'bar',
  HELLO: 'world',
}

faker.helpers.objectKey(MyEnum ); // 'FOO' | 'HELLO'
faker.helpers.enumKey(MyEnum); // 'FOO' | 'HELLO'

faker.helpers.objectValue(MyEnum ); // 'bar' | 'world'
faker.helpers.enumValue(MyEnum); // 'bar' | 'world'
```

Numeric enums are working (as you pointed out) a bit differently. You have to know this when working with enums (which sucks, no doubt). So while not working as expected, you can make them work!
```ts
// in js
const myObject = Object.freeze({
  FOO: 0,
  BAR: 1,
  // here is the catch
  0: 'FOO',
  1: 'BAR',
});

faker.helpers.objectKey(myObject); // 'FOO' | 'HELLO' | 0 | 1
faker.helpers.enumKey(myObject); // 'FOO' | 'HELLO'

faker.helpers.objectKey(myObject); // 'FOO' | 'HELLO' | 0 | 1
faker.helpers.enumValue(myObject); // 0 | 1

// in ts
enum MyEnum {
  FOO: 0,
  BAR: 1,
}

faker.helpers.objectKey(MyEnum); // 'FOO' | 'HELLO' | 0 | 1
faker.helpers.enumKey(MyEnum); // 'FOO' | 'HELLO'

faker.helpers.objectKey(MyEnum); // 'FOO' | 'HELLO' | 0 | 1
faker.helpers.enumValue(MyEnum); // 0 | 1
```

By providing the helper functions we essentially provide a bridge that allows users to handle enums as they expect.

> [...] but also performs much better at runtime as they can be optimized by JS engines.

Source? 
While the JS code IS bloaty, it's just an IIFE that assigns the object keys and values. Why should that be sooo underperformed in contrast to "plain JS object creation and freezing"? Unless you talking about some nanosecond BS again...

2023-03-12 12:32 UTC, Shinigami92 commented
@xDivisionByZerox please be careful in not getting personally and callout terms like "BS"

Yes indeed I'm talking about nano-seconds performance improvements. But also even on a code readability perspective it's possible to confuse folks with ordinal enums more then it helps. `string literal types` on the other hand are understandable, have no hidden side-effects like getting converted to ordinals in the background and other stuff.

2023-03-12 13:50 UTC, xDivisionByZerox commented
> @xDivisionByZerox please be careful in not getting personally and callout terms like "BS"

You gave out straight-up wrong information. Why am not allowed to call that out? I wasn't calling YOU out but the information you gave.

2023-03-12 14:38 UTC, matthewmayer commented
Could one extend objectKey/objectValue instead to specifically handle the case of it being passed a TS enum?

2023-03-12 14:48 UTC, ST-DDT commented
> Could one extend objectKey/objectValue instead to specifically handle the case of it being passed a TS enum?

This would degrade the usability of those methods for user defined objects, that actually use numeric keys. So no.

2023-03-12 14:56 UTC, matthewmayer commented
This would be the only Faker method which requires typescript to call into right? I think that would be worthy of calling out in the documentation for this function if accepted.

2023-03-12 15:06 UTC, ST-DDT commented
> This would be the only Faker method which requires typescript to call into right? I think that would be worthy of calling out in the documentation for this function if accepted.

AFAICT this will also work with plain json object pseudo enums (it is basically the same as objectValue while ignoring numeric keys).

````js
faker.helpers.enumValue(Color);
````

Works for both:

````ts
enum Color { Red, Green, Blue }
````

and

````js
const Color = { Red: 0, Green: 1, Blue: 2 }
````

And still provides a minuscule readability improvement over `objectValue` by conveying the given value is an "enum" instead of just some magic object.

2023-03-12 15:18 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +   * faker.datatype.enum(enum { A, B, C}) // 'A'
And make sure the examples actually compile.

2023-03-12 20:10 UTC, ocodista commented on src/modules/datatype/index.ts
> +   * faker.datatype.enum(enum { A, B, C}) // 'A'
Fixed, now added the three examples and included similar ones to the tests

2023-03-12 20:10 UTC, ocodista commented on src/modules/datatype/index.ts
> +    const randomOption = (enumObject as any)[
Done.

2023-03-12 20:10 UTC, ocodista commented on test/datatype.spec.ts
> +      }
Done.

2023-03-12 20:10 UTC, ocodista commented on test/datatype.spec.ts
> +    t.describe('enum', (t) => {
Done.

2023-03-12 20:11 UTC, ocodista commented on src/modules/datatype/index.ts
> +  enum<GenericEnumType extends Object, SpecificEnumType>(
Agreed, moved.

2023-03-12 20:11 UTC, ocodista commented on src/modules/datatype/index.ts
> +   * Returns a random value from an Enum object
Fixed this, now the implementation always returns a value from the enum.

2023-03-12 23:47 UTC, ST-DDT requested changes
Please run `pnpm run preflight` to get a list of lint and test errors locally.

2023-03-12 23:47 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    if(!enumObject) return '0' as SpecificEnumType
The parameter is required, no need to handle it being absent.

2023-03-12 23:47 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    const keys = ignoreTypeScriptAddedKeys(Object.keys(enumObject));
IMO you can inline this since you only use it once:

```suggestion
    const keys = Object.keys(enumObject)
        // ignore numeric keys added by TypeScript
        .filter((key) => isNaN(Number(key)));
```

(Not sure about the formatting)

2023-03-12 23:47 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    return enumValue;
IMO you can just return the value:

```suggestion
    return (enumObject as any)[randomKey]
```

2023-03-12 23:47 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  ): SpecificEnumType {
Note to self: Check generic type

2023-03-12 23:47 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * @param enumObject
Missing description

2023-03-12 23:47 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.datatype.enum(enum HttpStatus { Ok = 200, Created = 201, BadRequest = 400, Unauthorized = 401 }) // 200
```suggestion
   * faker.helpers.enumValue(enum Color { Red, Green, Blue}) // 'Green'
   * faker.helpers.enumValue(enum Direction { North = 'North', South = 'South'}) // 'South'
   * faker.helpers.enumValue(enum HttpStatus { Ok = 200, Created = 201, BadRequest = 400, Unauthorized = 401 }) // 200
```

+ please make sure these actually compile

2023-03-13 07:30 UTC, Shinigami92 requested changes

2023-03-13 07:30 UTC, Shinigami92 commented on test/helpers.spec.ts
> +        })
In line 631-632 the docs says:
```ts
enum Color { Red, Green, Blue }
faker.helpers.enumValue(Color) // 'Green'
```

But this seems to be wrong, because it returns `1` and not `'Green'`.

2023-03-13 09:16 UTC, matthewmayer requested changes, later dismissed

2023-03-13 09:16 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +   * faker.helpers.enumValue(Color) // 1
while correct, this example doesn't seem very explanatory. (why 1?). It would be helpful to clarify this equals the value of one of the enum values, something like this?
```
const randomColor = faker.helpers.enumValue(Color) // randomColor is 1 
randomColor === Color.Green // true
```

2023-03-13 10:07 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.enumValue(Color) // 1
IMO we can achieve the same with the comment:

```suggestion
   * faker.helpers.enumValue(Color) // 1 (Green)
```

2023-03-13 10:13 UTC, ST-DDT reviewed
⚠️ Please fix all formatting, lint and test errors/run `pnpm run preflight` before pushing.

2023-03-13 10:13 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   *
```suggestion
   *
   * This does the same as `objectValue` except that it ignores (the values assigned to) the numeric keys added for typescript enums.
   *
```

2023-03-13 15:00 UTC, ocodista commented
> ⚠️ Please fix all formatting, lint and test errors/run `pnpm run preflight` before pushing.

I fixed all of the warnings but this one related to docs version, any idea how I should fix it?
<img width="798" alt="image" src="https://user-images.githubusercontent.com/19851187/224740823-a3b4c49c-cc65-4315-afe9-12e5ab348332.png">

2023-03-13 17:07 UTC, Shinigami92 requested changes

2023-03-13 17:07 UTC, Shinigami92 commented on test/helpers.spec.ts
> +            faker.helpers.enumValue(Color); // 'Green'
I would expect 1 here, as there are no string literals assigned :thinking:

2023-03-13 17:07 UTC, Shinigami92 commented on test/helpers.spec.ts
> +        it('should compile examples', () => {
I'm not sure if we need this test in this way, as here you are just checking that TypeScript works :thinking: do you?

2023-03-13 17:07 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * This does the same as `objectValue` except that it ignores (the values assigned to) the numeric keys added for typescript enums.
> [...] except that it ignores (the values assigned to) the numeric keys [...]

Could you add one test case for that?
Or in other words: can you please add at least one example where `enumValue` is usable and provide a different result as to `objectValue`?
Currently I'm not sure how to use it and get a different, actual useful result.

2023-03-13 18:30 UTC, ST-DDT commented on test/helpers.spec.ts
> +        it('should compile examples', () => {
Looks like debug code to me.

2023-03-13 18:33 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * This does the same as `objectValue` except that it ignores (the values assigned to) the numeric keys added for typescript enums.
`faker.helpers.enumValue(Color) // 1 (Green)`

whereas objectValue might also return Red.

2023-03-13 18:51 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.enumValue(HttpStatus) // 200
```suggestion
   * faker.helpers.enumValue(HttpStatus) // 200 (Ok)
```

2023-03-13 18:56 UTC, ST-DDT commented
> With this method it is possible to get a random value from an enum.
> 
> This is very useful for not having to harcode an enum when generating fake data.

Just a question on the side:
Do you need this feature yourself or do you just consider it useful?
What do you use ordinal enums for?

2023-03-13 19:07 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +   * This does the same as `objectValue` except that it ignores (the values assigned to) the numeric keys added for typescript enums.
A reason more **for me** to 100% prevent usage of ordinal non constant enums

2023-03-13 19:57 UTC, ocodista commented
> > With this method it is possible to get a random value from an enum.
> > This is very useful for not having to harcode an enum when generating fake data.
> 
> Just a question on the side: Do you need this feature yourself or do you just consider it useful? What do you use (non-const) ordinal enums for?

Yes, I would use it.

In fact, I'm using it right now together with faker js code, for enums.

The project I work at have a lot of TypeScript enums. like categories, userTypes, statuses, etc

2023-03-13 23:32 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  >(enumObject: GenericEnumType): SpecificEnumType {
I did a bit of fiddling with typescript and found the correct typing for this method:

````ts
  enumValue<
    EnumType extends Record<string | number, string | number>,
    EnumValueType extends
      | { [K in KeySearch<EnumType, string>]: `${EnumType[K]}` }[KeySearch<
          EnumType,
          string
        >]
      | { [K in KeySearch<EnumType, number>]: EnumType[K] }[KeySearch<
          EnumType,
          number
        >]
  >(enumObject: EnumType): EnumValueType {
````

I used named generic types for readability, not sure whether we want them in the final source code. < @Shinigami92 

Sadly it requires a small helper type:

````ts
type KeySearch<
  T extends Record<string | number, string | number>,
  S extends string | number
> = {
  [K in keyof T]: T[K] extends S ? K : never;
}[keyof T];
````

But on the plus side, this doesn't seem to need an `any` cast anymore either.

[TS-Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcwKZQEoEMwBM4C2AkmFABQExgBciYIBARqgE4A0iBWAHrfU6wCUiAN4BYAFCJpnKogC8iALJYoACwB0EVDAA2FKoIDckmZx4LlqzcF1w4LCj2OmZLdCBZIV6jbfuOPposOPgEZMIAVIhO3IgAtLJIANSIAIyCwqmUYCYSAL6SkqCQsAiIWCwhAJ4AorqoBKikADwAKpYAzlAsVMgAfGSu0pU1tBioWPhgutUAglVY1e39roK0HeJSMhAI3YhUuKhx8sMyo0saDWDI6oj96YgA-Cjo2HiEJOQADBwX1Vdmrc1Al0sJaN88mZ3FBPEh-gBtQ7HAC6UMQhQkkmaDEQAGE4HYWABlUSuCa4SwAcgpVLYrgA4u5mtSmahmnTXAAhXQgVDUnl8zkFbH8fGEhwAOTJ2wpljS30Vv0ZzKQigVSu+aXp20F-PVmoATDrMTiCOKiUoZdI5QalTrpGyWYoqU6wMLpHqBbzUMLMZIoNUAA78gDSqGqxMmLAganaiGOUGauE6iAmuxYuBa3V6N0QAB86AxmOxEDm+gWiwIWP0OKTE8nU+W84X+CWHoottIEaGDkgANYRuDARBtFEbHsohPcJN4VOkl69vioABurDy+QRg+qw9HaKKEkDIcQodJinDkejsZaR9Qu4JROJHGbAzyt5P0vPEajlWvt-vEosJKz49H0-RvsGYZWl+l6-nG-4jg+DhKCBuavgGkEnsSaSWBeP4xvBkEAY+HBtqw4EYceoaSjhMH4X+RGIYBwFVu2EFUUotEnt+V6ESGxHIaRxbkXkkgAPRiYgxJTLMiDqDAqbvvgqCdO6UCIAA7g4-YVKmWCIO4nQgLo6nvjAUCdKgugjmQEBYCAlkGZMnR7IIlH8rU-AAGpYD6bSQS0AAa06zimaaoBmWYvpWZGltFrbCTWHauIWIiID2fbcbBBFBahYHjogAAGAAkIiBZO+SFRiPY8XBuVlqBNz9CiKWiOlvZyHhvH1bFzW0OVoZTpuXV1YFQnVs1omHphABi9hnognkMD5fkBQhFoOMSFHTcec1wJ+i3eb5fL+SGN6MRtQHbe+e3QYdy3Hagp2oOd-FMZa22SLsYD7MA820HtC00qguBUnk32-fYkoA1D8qKkYiASYgkpwOpRnuJpajVHJagKYgymqVS6msCwDhfXs6l-XASgw9TcNKmkU0lNA8BIGaK18i0rhLQQz0hY24WRdmjXIDFiV5S2rHkQ690EBzT2YQ2c5nKl7WZSNOU889EsDAVJUiFrkEVVVw21Zr-Daw1aHNSrbUZZ1ZvXobIbje2BXO6gk7VRrTsW5BrvkS1EiDGaADyjAAFYRVAtAe+ssvy3zXaI5JMDIGADj8vwrAwBAiDbnpuBHJSjDY89xIQL0QZQK4EPqQXljh1H0AaAXZBh5H0eCH4ehJo4ZDbsI8gPApkpYJKZCSolA8RpkLjbHXBmhIQF6WP89SNM05AF-P0gwnCMQd836lYHpYDVIICIhB8BAXlOp8J49z0bgei-cAt7OPWQSEkvPb8HZ-H039mJ-wpogbgd1AF8mAZaeekggA)

<details>
<summary>Docs-Preview</summary>

![grafik](https://user-images.githubusercontent.com/1579362/224854784-cac9ddec-e911-4b3f-801f-92aa7ce2a66b.png)


</details>

2023-03-13 23:43 UTC, ST-DDT commented on test/helpers.spec.ts
> +          const randomColorVAlue = faker.helpers.enumValue(ColorStringEnum);
Please fix the typo here and in the other methods:
```suggestion
          const randomColorValue = faker.helpers.enumValue(ColorStringEnum);
```

Alternatively we sometimes use `actual` as variable name.

2023-03-14 00:00 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  >(enumObject: GenericEnumType): SpecificEnumType {
Never mind, I found an even easier solution:

````ts
  enumValue<
    EnumType extends Record<string | number, string | number>,
    EnumValueType extends {
      [key in keyof EnumType]: EnumType[key] extends string
        ? `${EnumType[key]}`
        : EnumType[key];
    }[keyof EnumType]
  >(enumObject: EnumType): EnumValueType {
````

2023-03-14 17:12 UTC, Shinigami92 commented on test/helpers.spec.ts
> +          ]).toContain(actual);
To absolutely clarify what the intend of the test is, we should pass the native/raw values to the expected.

```diff
  const actual = faker.helpers.enumValue(ColorValueEnum);
- expect([ColorValueEnum.Red, ColorValueEnum.Green, ColorValueEnum.Blue]).toContain(actual);
+ expect([0, 1, 2]).toContain(actual);
```

That way when reading the test, it is much more clear what the intend of the test is.

2023-03-14 18:33 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +   * This does the same as `objectValue` except that it ignores (the values assigned to) the numeric keys added for typescript enums.
capitalization: TypeScript

2023-03-14 19:43 UTC, ST-DDT submitted a review, later dismissed
One last change, then this is good to go IMO.

2023-03-14 19:43 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * @param <EnumValueType> Type of enumObject property, also automatically inferred by TypeScript.
We use the `@template` tags for the generic parameters as this has better readability in VSCode.

```suggestion
   * @template EnumType Type of generic enums, automatically inferred by TypeScript.
   * @template EnumValueType Type of enumObject property, also automatically inferred by TypeScript.
   * @param enumObject Enum to pick the value from.
```

2023-03-14 20:04 UTC, ST-DDT approved these changes, later dismissed

2023-03-14 21:53 UTC, Shinigami92 requested changes
I sadly identified some TypeScript problems: [TS-playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcwKZQEoEMwBM4C2AggE4BGMUJWJAngBQExgBciYIBZqJANIgSwAPNhy48AlIgDeAWABQiJYhLoQJJAFksUABYA6ankL0pAKkSNhiALQDmUgNT2wAbgUBfBQtCRYCFHRsYwIASTAoRmZRTm4+AWEY8RIpOUVlJiQAXkRtPX0IVBgAGyiwCXd0pUEhRBy8g2BiuDgSKyEKhWUVNQ1cnUbm1voGwxx8AlNEC3bbF0RnAEYJJxdKr3kfcGh4JBpqWgBRYtQCVAiAHgAVOsQAZypmZAA+ei7lfaxaNgxULHwwMVaKQDtdnu8JGwbmluhAEA9EMxcKhall3t1PrR9CcwMg9IhnohFogAPyBTDjQjhSIABn4mOx5zxujmy0QbBplW6qig6j2JAOAG0kSiALpcxAbLZ+XaIc6cABqWGKIFQF3RiEOYiutAADqg5UIoOdcHdEL84SRcBcHiQnogAD7sWI8fi2+1OsRxZ68DVaxXK1U6-WG414M0w7qIQUAa1QtERSDjtDgwE12r1qFFbH9BGDqFj8dFoZNZvduI13TJAAMACTSXP5wu0UUeauV5Q5jP65vijUeZup9OcfOi96veUEADyZAAVqhoF2R5nIcOCEqVah8zINQB6XeI5BgVoGsQ8GAQRDJs3-ZG4RBkBP5gDKEDtuqgGrhYAR19uM-naB9GvehJwAhcoAkfRgBKY02noZMpCyQkYDuAA5LA0PoNCXTaRCVglJRvwRIwJgAaXjW5MWOU5zkia9OiqHpeT6MC5wgwVSMICiW0QLAzVzDcg0zCUpXkfdbBsGxvHkSdEAAYTgZoSCE1Bcx3dJflwX10gAcVUc4dKUAAhTcdI2OTFOU1SAHVKF0Z8oBoKBwmRIR1MjLTbgAZiMxB9NQQz3lM1VzIUSylNaRy7VxDz3i8nIAHIMEOAARRK-IC85bkS3SUsONCMuCzccuMgAZABVQ4ivkCyxEQAAxFpNBgIRUFwOL0iauBbjpYKaFuRY-Oi7qcoaqcpxqpRouMgakuMogMBqsTiKgPjiV3Cw2Cs1pVPUswDxySdVPoHaVMDNSxAkBRVr4gAmRBNvZBTIvOzc7L0RznNclF9sOuUxBOs7bPsr6SBcvBfqum74TWrBvMerbEAAIhS1LkcdFG8sOAqMadZHyqqjGDtuY6LtO17oqeXNrvkW6sAAFkR57upatqOrEfRRqdVnWva3N9FmkhMeR8apzxlGFowYn-rJzd6F59maZk26yEWbbXr2+qciwRZXEeg84BjGGfzWsg7o16yLo+hynPBn73O1+79Yko2TYRMhvMtqLHlip34Zdg9dRIOAyBOAh3bNhm2EV-n-YZwPEGD0Pw5k3wdgCCBFnoZhdRAKBvbe1UaZkDZ0-8JAIDunOwDzguXqt97QbtiG3JL6Qy+2CvEAgbya7rwuqb9zhUk7mVM4Z-v85j5q+Y5kfS5V7PdakV3jbp6usDu1fDfX3v6Hhnek5DsPThuyfGaP5PT4j+QgA)

So while the runtime code is okay, the actual return type of the function is not real-world usable and therefore lacks the usability for what the function is originally planned for.

Right now I didn't get the types managed myself, hopefully someone of you have more luck.

2023-03-14 22:17 UTC, ST-DDT reviewed
Those type errors can be fixed with the following changes.
It slightly reduces the DX for the return types of String enums.

@Shinigami92 Any suggestions on how to modify the tests to catch the type errors (for future refactorings)?

2023-03-14 22:17 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * @template EnumValueType Type of enumObject property, also automatically inferred by TypeScript.
```suggestion
```

2023-03-14 22:17 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  }
```suggestion
  enumValue<EnumType extends Record<string | number, string | number>>(
    enumObject: EnumType
  ): EnumType[keyof EnumType] {
    // ignore numeric keys added by TypeScript
    const keys: Array<keyof EnumType> = Object.keys(enumObject).filter((key) =>
      isNaN(Number(key))
    );
    const randomKey = this.arrayElement(keys);
    return enumObject[randomKey];
  }
```

2023-03-15 07:47 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +  }
[TS-Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAUzCAtgNQIYBsTIA8AomugCoCeADsigB5SoAmAzogErIRwBOzhVlF4wwAc0QAfRGQBGyXgBpEQkeKkyM83gD4dACgBQiEyjIB5WQCtuUAFyJSGKrUMBKB04o1kAbQDWyJRwwI5kLsgAuogA3samvMhQILxIaLi4iNjs2GCUANyGAL6GhqgYiADCcLh8OPjIXrHxJlzMii2IAOKJqB2miABCDR0l5ehVNXV4BADqMFAAFgDKUNi8UACSYMzI9E1xA22IALyIAMz9pj3IfZ3DBKNlZJO1vKtqYgedx2cA5BxiAARP5XEw3VCnRB-LqA4gAOVB9waUL+gwAMgBVYhIsYvABicDgAFkYPRkMxvgNCXAoQAGMFDdZQgCMjI+NNR+PM5iRAw+g2Z-0GAEEOLjSoYeGAhFkWYgAPQAKkQDmqb3qBCaSoVUPGmuQ+nV0waXjcUoQsuwACZFSq1VNeAb5ktVustjs9trdWd9TNDcanf6XSs1httrt9mRzdKrec7arXnwPqIvi8dXqyAajY6U+IzRaZVAsgAWBMOGmk8mU9M+swYbOVskUguF2WyFkOjX+ppnbAs-KK3Vwfxt4uya1dk1zBah90Rr0vPvWwcK4ej2Pj85T97CVO9rLnVfrseIWQlitEqstpel4+IEelUCQWAIRAQFn6UTUED2JNB01o1iEpn2geAkAga0vzAH8-0DZ1ZzdcNPSjDA3GAwxQNfCDzmg2CdzzNM0IwrDwPfEs8N-S8SWbGtiJiEopU-ft0LXB8Nygm1WJPCBcOwc5uPYqUKOwEtBMfIA)

I can confirm it fulfills my conditions 👍

2023-03-15 07:48 UTC, Shinigami92 approved these changes

2023-03-15 08:05 UTC, ST-DDT approved these changes

2023-03-15 11:00 UTC, xDivisionByZerox approved these changes

2023-03-15 16:33 UTC, Shinigami92 commented
@matthewmayer please also approve or write a new review comment

2023-03-15 16:35 UTC, merged