feat(locale): add locale TH
faker-js/faker pull request #1922
Opened 2023-03-12 18:20 UTC by munkeawtoast

Fixed all problems with the latter PR #1921 .

2023-03-13 00:55 UTC, matthewmayer requested changes

2023-03-13 00:55 UTC, matthewmayer commented on src/locales/th/phone_number/formats.ts
> +export default ['06 #### ####', '08 #### ####', '09 #### ####'];
Could also add some landline patterns here eg 02...

2023-03-13 05:11 UTC, matthewmayer approved these changes, later dismissed

2023-03-13 05:11 UTC, matthewmayer commented on src/locales/th/person/index.ts
> +  female_first_name,
could maybe also add a prefix definition? e.g. คุณ

otherwise `fakerTH.person.prefix()` falls back to the English prefix list e.g. Mr, Mrs, Ms, Dr

2023-03-29 08:29 UTC, matthewmayer approved these changes, later dismissed

2023-03-29 08:56 UTC, Shinigami92 commented on src/locales/th/location/street_name.ts
> +  'กำแพงเพชร 7',
Why is this?

2023-03-29 08:56 UTC, Shinigami92 commented on src/locales/th/location/street_name.ts
> +  'เฉลิมเขต 4',
Here again

2023-03-29 08:56 UTC, Shinigami92 commented on src/locales/th/location/street_name.ts
> +  'บางบอน 5',
And again

2023-03-29 08:56 UTC, Shinigami92 commented on src/locales/th/location/street_name.ts
> +  'ประชาราษฎร์ สาย 2',
And again

2023-03-29 08:56 UTC, Shinigami92 commented on src/locales/th/location/street_name.ts
> +  'พระรามที่ 6',
And again

2023-03-29 08:56 UTC, Shinigami92 commented on src/locales/th/location/street_name.ts
> +  'พุทธมณฑล สาย 3',
Okay and there is even more below

2023-03-29 08:56 UTC, Shinigami92 commented on src/locales/th/person/last_name.ts
> +const common_isan_full = common_isan_prefix
I'm confused here as non-native why "full" is used inside building a "last" name

2023-03-29 08:56 UTC, Shinigami92 commented on src/locales/th/person/name.ts
> +  { value: '{{person.firstName}} {{person.lastName}}', weight: 100 },
should we use 99 here instead so we have a 100 in sum?

2023-03-29 09:10 UTC, munkeawtoast commented on src/locales/th/location/street_name.ts
> +  'กำแพงเพชร 7',
They are real road names in Thailand. https://en.wikipedia.org/wiki/Kamphaeng_Phet_Road

2023-03-29 09:14 UTC, munkeawtoast commented on src/locales/th/person/last_name.ts
> +const common_isan_full = common_isan_prefix
I thought "common_isan_full_lastname" would be too long so i abbreviated them.

2023-03-29 09:16 UTC, Shinigami92 commented on src/locales/th/location/street_name.ts
> +  'กำแพงเพชร 7',
<img src="https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExMTY2MDQxODNiMDJiMjYyZDVhNDgwMjJiMzhmNWRjOGQzNmEwOWJkNSZjdD1n/jPAdK8Nfzzwt2/giphy.gif"/>

2023-03-29 09:20 UTC, ST-DDT commented on src/locales/th/person/last_name.ts
> +const common_isan_full = common_isan_prefix
Maybe use a different term here to avoid confusion e.g. joined, merged or complete instead of full.

Also I think you can omit the common prefix.

2023-03-29 14:57 UTC, ST-DDT submitted a review, later dismissed

2023-03-29 14:58 UTC, ST-DDT commented on src/locales/th/person/name.ts
> +  { value: '{{person.firstName}} {{person.lastName}}', weight: 100 },
That would be a nice to have thing for me. But not required.

2023-03-29 17:59 UTC, ST-DDT submitted a review, later dismissed

2023-03-31 10:57 UTC, Shinigami92 submitted a review, later dismissed

2023-04-01 19:51 UTC, ST-DDT approved these changes

2023-04-02 08:48 UTC, matthewmayer approved these changes

2023-04-02 11:21 UTC, Shinigami92 approved these changes

2023-04-02 11:28 UTC, merged