docs: Add overview guides to specific modules
faker-js/faker pull request #1929
Opened 2023-03-14 10:19 UTC by matthewmayer

fix #1928

2023-03-17 08:16 UTC, ST-DDT commented
I think the links wont work locally in our IDEs.
Should we use fully qualified links instead (and convert them to absolute links in the docs build)?

2023-03-18 11:22 UTC, ST-DDT requested changes

2023-03-18 11:22 UTC, ST-DDT commented on src/modules/animal/index.ts
> + * For a general type of animal e.g. `'dog'`, use `type()`.
In the other modules you used links to the methods.

2023-03-18 11:22 UTC, ST-DDT commented on src/modules/date/index.ts
> + * To quickly generate a date in the past, use [`recent()`](#recent) (last day) or [`past()`](#past) (last year).
These links cause errors in the IDE when clicked upon.
Please use absolute ones.

2023-03-18 11:22 UTC, ST-DDT commented on src/modules/person/index.ts
> + * ### Overview
```suggestion
 * ### Overview

```

2023-03-18 11:22 UTC, ST-DDT commented on src/modules/person/index.ts
> + * ### Related modules
```suggestion
 * ### Related modules

```

2023-03-19 14:42 UTC, matthewmayer commented
> I think the links wont work locally in our IDEs.
> 
> Should we use fully qualified links instead (and convert them to absolute links in the docs build)?

What would a fully qualified link look like in markdown?

2023-03-19 15:38 UTC, ST-DDT commented
> What would a fully qualified link look like in markdown?

It starts with https. Sorry if I messed up the terms.

2023-03-19 15:55 UTC, matthewmayer commented
Which hostname though?

2023-03-19 17:44 UTC, ST-DDT commented
I thought about using next until we release v8 and adjust the main docs version. In the docs build we should adjust it to absolute links (without hostname) though.
But I'm open to suggestions.

2023-03-21 08:49 UTC, ST-DDT reviewed
Please also add a test to our signature tests

2023-03-21 08:49 UTC, ST-DDT commented on scripts/apidoc/signature.ts
> +}
I'm thinking whether this should this be part of the toBlock method itself, so it will also work for parameter comments.
It should also cover `https://fakerjs.dev`, so it works as expected for all our deployments.

2023-03-21 09:18 UTC, matthewmayer commented on scripts/apidoc/signature.ts
> +}
Wouldn't it be best to always link to next.fakerjs.dev for consistency?

2023-03-21 09:52 UTC, matthewmayer commented
> Please also add a test to our signature tests

the existing signature snapshot tests only seem to be for method signatures, not sure how to add for module comments?

2023-03-21 10:16 UTC, ST-DDT commented on src/modules/color/index.ts
> +   * faker.color.rgb() // '#ffffFF'
Please revert this, we have #1957 for that and there are multiple places that need fixing.

- #1957

2023-03-21 10:24 UTC, matthewmayer commented on src/modules/color/index.ts
> +   * faker.color.rgb() // '#ffffFF'
sorry my bad, committed by mistake

2023-03-22 10:30 UTC, ST-DDT commented on src/modules/image/index.ts
> + * For a random photograph use [`url()`](https://next.fakerjs.dev/api/image.html#url). This will not return the image directly, but a URL pointing to an image from one of two demo image providers "Pi
IMO we should refer to images as these may be generated or drawn as well.

2023-03-22 10:30 UTC, ST-DDT commented on src/modules/science/index.ts
> + *
```suggestion
```

2023-03-22 10:30 UTC, ST-DDT commented on src/modules/random/index.ts
> + * All the methods in this module are deprecated.
IMO we should rather display the deprecation message.

2023-03-22 10:30 UTC, ST-DDT commented on src/modules/airline/index.ts
> + * For a random airline, use [`airline()`](https://next.fakerjs.dev/api/airline.html#airline).
I'm not sure whether we need to mention every method explicitly.

2023-03-22 10:30 UTC, ST-DDT commented on src/modules/airline/index.ts
> + * For a dummy booking, a passenger will generally book a flight on a specific [`flightNumber()`](https://next.fakerjs.dev/api/airline.html#flightnumber) and and [`airplane()`](https://next.fakerjs.d
```suggestion
 * For a dummy booking, a passenger will generally book a flight on a specific [`flightNumber()`](https://next.fakerjs.dev/api/airline.html#flightnumber), [`airplane()`](https://next.fakerjs.dev/api/airline.html#airplane), be allocated a [`seat()`](https://next.fakerjs.dev/api/airline.html#seat), and [`recordLocator()`](https://next.fakerjs.dev/api/airline.html#recordlocator).
```

2023-03-22 10:42 UTC, matthewmayer commented on src/modules/random/index.ts
> + * All the methods in this module are deprecated.
you mean detect if @deprecated is applied to whole module and put a banner at the top?

2023-03-22 10:43 UTC, matthewmayer commented on src/modules/airline/index.ts
> + * For a random airline, use [`airline()`](https://next.fakerjs.dev/api/airline.html#airline).
In general no, but I'm trying to highlight the most important, or logically grouped methods. Its more useful in older modules with lots of methods than more recent better organized modules like this one; but i wanted every module to have an overview for consistency.

2023-03-23 16:13 UTC, matthewmayer commented
> > Please also add a test to our signature tests
> 
> the existing signature snapshot tests only seem to be for method signatures, not sure how to add for module comments?

i will need some help on this, not sure how

2023-03-23 17:20 UTC, ST-DDT commented on scripts/apidoc/signature.ts
> +}
**Team Decision**

- We want to remap ith for both next and the main page urls.
- We will change the next urls to main on release.

2023-03-23 18:04 UTC, ST-DDT commented
> > Please also add a test to our signature tests
> 
> i will need some help on this, not sure how

Sure, as part of this PR or using a separate PR?

2023-03-24 02:07 UTC, matthewmayer commented
> > > Please also add a test to our signature tests
> > 
> > 
> > i will need some help on this, not sure how
> 
> Sure, as part of this PR or using a separate PR?

seperate if you think thats non-blocking

2023-03-24 09:20 UTC, ST-DDT submitted a review, later dismissed

2023-03-24 09:26 UTC, ST-DDT commented
I forgot about [this one](https://github.com/faker-js/faker/pull/1929#discussion_r1146528728), please adjust the code accordingly:

> **Team Decision**
> 
> * We want to remap it for both next and the main page urls.
> * We will change the next urls to main on release.

2023-03-24 09:30 UTC, matthewmayer commented
Sorry not clear what actual code changes are needed for that?

2023-03-24 10:16 UTC, ST-DDT commented on scripts/apidoc/signature.ts
> +}
```suggestion
export function stripAbsoluteFakerUrls(markdown: string): string {
  return markdown.replace(/https:\/\/(next.)?fakerjs.dev\//g, '/');
}
```

2023-03-24 10:19 UTC, ST-DDT approved these changes, later dismissed

2023-03-24 16:08 UTC, ST-DDT approved these changes, later dismissed

2023-03-25 21:33 UTC, ejcheng commented on src/modules/airline/index.ts
> + * Several methods in this module return objects rather than strings. You can use for example `faker.airline.airport().iataCode` to pick out the specific property you need.
```suggestion
 * Several methods in this module return objects rather than strings. For example, you can use `faker.airline.airport().iataCode` to pick out the specific property you need.
```

2023-03-25 21:33 UTC, ejcheng commented on src/modules/airline/index.ts
> + * - For sample passenger data you can use the methods of the [`faker.person`](https://next.fakerjs.dev/api/person.html) module.
```suggestion
 * - To generate sample passenger data, you can use the methods of the [`faker.person`](https://next.fakerjs.dev/api/person.html) module.
```

2023-03-25 21:33 UTC, ejcheng commented on src/modules/animal/index.ts
> + * For a general type of animal e.g. `'dog'`, use [`type()`](https://next.fakerjs.dev/api/animal.html#type).
```suggestion
 * For a general type of animal (e.g. `'dog'`), use [`type()`](https://next.fakerjs.dev/api/animal.html#type).
```

2023-03-25 21:33 UTC, ejcheng commented on src/modules/color/index.ts
> + * For a hex color like `#ff0000` used in HTML/CSS use [`rgb()`](https://next.fakerjs.dev/api/color.html#rgb). There are also methods for other color formats such as [`hsl()`](https://next.fakerjs.de
```suggestion
 * For a hex color like `#ff0000` used in HTML/CSS, use [`rgb()`](https://next.fakerjs.dev/api/color.html#rgb). There are also methods for other color formats such as [`hsl()`](https://next.fakerjs.dev/api/color.html#hsl), [`cmyk()`](https://next.fakerjs.dev/api/color.html#cmyk), [`hwb()`](https://next.fakerjs.dev/api/color.html#hwb), [`lab()`](https://next.fakerjs.dev/api/color.html#lab), and [`lch()`](https://next.fakerjs.dev/api/color.html#lch).
```

2023-03-25 21:33 UTC, ejcheng commented on src/modules/commerce/index.ts
> + * For a long product name like `'Incredible Soft Gloves'`, use [`productName()`](https://next.fakerjs.dev/api/commerce.html#productname). The product names are generated from a list of adjectives, m
```suggestion
 * For a long product name like `'Incredible Soft Gloves'`, use [`productName()`](https://next.fakerjs.dev/api/commerce.html#productname). The product names are generated from a list of adjectives, materials, and products, which can each be accessed separately using [`productAdjective()`](https://next.fakerjs.dev/api/commerce.html#productadjective), [`productMaterial()`](https://next.fakerjs.dev/api/commerce.html#productmaterial), and [`product()`](https://next.fakerjs.dev/api/commerce.html#product). You can also create a description using [`productDescription()`](https://next.fakerjs.dev/api/commerce.html#productdescription).
```

2023-03-25 21:33 UTC, ejcheng commented on src/modules/commerce/index.ts
> + * For a department in a shop, or product category, use [`department()`](https://next.fakerjs.dev/api/commerce.html#department).
```suggestion
 * For a department in a shop or product category, use [`department()`](https://next.fakerjs.dev/api/commerce.html#department).
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/company/index.ts
> + * To generate a random company name use [`name()`](https://next.fakerjs.dev/api/company.html#name). This is localized in many locales.
```suggestion
 * To generate a random company name, use [`name()`](https://next.fakerjs.dev/api/company.html#name). This is localized in many locales.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/company/index.ts
> + * To generate jargon-filled company catchphrases and buzzwords use [`catchPhrase()`](https://next.fakerjs.dev/api/company.html#catchphrase) or [`buzzPhrase()`](https://next.fakerjs.dev/api/company.h
```suggestion
 * To generate jargon-filled company catchphrases and buzzwords, use [`catchPhrase()`](https://next.fakerjs.dev/api/company.html#catchphrase) or [`buzzPhrase()`](https://next.fakerjs.dev/api/company.html#buzzphrase).
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/vehicle/index.ts
> + * If you prefer two wheels you can generate a [`bicycle()`](https://next.fakerjs.dev/api/vehicle.html#bicycle) type instead.
```suggestion
 *
 * ### Overview
 *
 * Most methods are related to cars/automobiles: a [`vehicle()`](https://next.fakerjs.dev/api/vehicle.html#vehicle) name is comprised of a car [`manufacturer()`](https://next.fakerjs.dev/api/vehicle.html#manufacturer) and [`model()`](https://next.fakerjs.dev/api/vehicle.html#model). You can also generate [`fuel()`](https://next.fakerjs.dev/api/vehicle.html#fuel), [`type()`](https://next.fakerjs.dev/api/vehicle.html#type), and [`color()`](https://next.fakerjs.dev/api/vehicle.html#color), as well as typical car registration IDs [`vin()`](https://next.fakerjs.dev/api/vehicle.html#vin) and [`vrm()`](https://next.fakerjs.dev/api/vehicle.html#vrm).
 *
 * If you prefer two wheels, you can generate a [`bicycle()`](https://next.fakerjs.dev/api/vehicle.html#bicycle) type instead.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/science/index.ts
> + * Both methods in this module return objects rather than strings. You can use for example `faker.science.chemicalElement().name` to pick out the specific property you need.
```suggestion
 * Both methods in this module return objects rather than strings. For example, you can use `faker.science.chemicalElement().name` to pick out the specific property you need.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/string/index.ts
> + * For strings of digits, use [`numeric()`](https://next.fakerjs.dev/api/string.html#numeric) (or for other bases, [`binary()`](https://next.fakerjs.dev/api/string.html#binary), [`octal()`](https://n
```suggestion
 * For strings of base-ten digits, use [`numeric()`](https://next.fakerjs.dev/api/string.html#numeric). For other bases, use [`binary()`](https://next.fakerjs.dev/api/string.html#binary), [`octal()`](https://next.fakerjs.dev/api/string.html#octal), or [`hexadecimal()`](https://next.fakerjs.dev/api/string.html#hexadecimal)).
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/string/index.ts
> + * You can also generate standard ID strings using [`uuid()`](https://next.fakerjs.dev/api/string.html#uuid) or [`nanoid()`](https://next.fakerjs.dev/api/string.html#nanoid).
```suggestion
 * You can generate standard ID strings using [`uuid()`](https://next.fakerjs.dev/api/string.html#uuid) or [`nanoid()`](https://next.fakerjs.dev/api/string.html#nanoid).
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/string/index.ts
> + * - The [`faker.helpers`](https://next.fakerjs.dev/api/helpers.html) module includes a number of string related functions.
```suggestion
 * - The [`faker.helpers`](https://next.fakerjs.dev/api/helpers.html) module includes a number of string related methods.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/hacker/index.ts
> + * There are methods for different parts of speech, such as [`abbreviation()`](https://next.fakerjs.dev/api/hacker.html#abbreviation), [`adjective()`](https://next.fakerjs.dev/api/hacker.html#adjecti
```suggestion
 * There are methods for different parts of speech, such as [`abbreviation()`](https://next.fakerjs.dev/api/hacker.html#abbreviation), [`adjective()`](https://next.fakerjs.dev/api/hacker.html#adjective), [`noun()`](https://next.fakerjs.dev/api/hacker.html#noun), [`verb()`](https://next.fakerjs.dev/api/hacker.html#verb), and [`ingverb()`](https://next.fakerjs.dev/api/hacker.html#ingverb). Alternatively, [`phrase()`](https://next.fakerjs.dev/api/hacker.html#phrase) creates a longer phrase combining these words.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/hacker/index.ts
> + * Various other modules allow for generating other types of words and phrases:
```suggestion
 * Various modules allow for generating other types of words and phrases:
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/helpers/index.ts
> + * A particularly helpful method is [`arrayElement()`](https://next.fakerjs.dev/api/helpers.html#arrayelement) which returns a random element from an array. This is useful when adding your own custom
```suggestion
 * A particularly helpful method is [`arrayElement()`](https://next.fakerjs.dev/api/helpers.html#arrayelement) which returns a random element from an array. This is useful when adding custom data that Faker doesn't contain.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/helpers/index.ts
> + * A number of methods can generate strings according to various patterns: [`replaceSymbols()`](https://next.fakerjs.dev/api/helpers.html#replacesymbols), [`replaceSymbolWithNumber()`](https://next.f
```suggestion
 * A number of methods can generate strings according to various patterns: [`replaceSymbols()`](https://next.fakerjs.dev/api/helpers.html#replacesymbols), [`replaceSymbolWithNumber()`](https://next.fakerjs.dev/api/helpers.html#replacesymbolwithnumber), and [`regexpStyleStringParse()`](https://next.fakerjs.dev/api/helpers.html#regexpstylestringparse).
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/image/index.ts
> + * For a random image use [`url()`](https://next.fakerjs.dev/api/image.html#url). This will not return the image directly, but a URL pointing to an image from one of two demo image providers "Picsum"
```suggestion
 * For a random image, use [`url()`](https://next.fakerjs.dev/api/image.html#url). This will not return the image directly but a URL pointing to an image from one of two demo image providers "Picsum" and "LoremFlickr". You can request an image specifically from one of two providers using [`urlLoremFlickr()`](https://next.fakerjs.dev/api/image.html#urlloremflickr) or [`urlPicsum()`](https://next.fakerjs.dev/api/image.html#urlpicsum).
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/image/index.ts
> + * This module previously also contained methods for specifically themed images like "fashion" or "food", but these are now deprecated. If you need more control over image type, you are recommended t
```suggestion
 * This module previously also contained methods for specifically themed images like "fashion" or "food", but these are now deprecated. If you need more control over image type, you are recommended to use an image provider directly or provide your own set of placeholder images.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/internet/index.ts
> + * For websites you can use generate a [`domainName()`](https://next.fakerjs.dev/api/internet.html#domainname) or a full [`url()`](https://next.fakerjs.dev/api/internet.html#url).
```suggestion
 * For websites, you can generate a [`domainName()`](https://next.fakerjs.dev/api/internet.html#domainname) or a full [`url()`](https://next.fakerjs.dev/api/internet.html#url).
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/internet/index.ts
> + * To make your data more 🔥, you can also use [`emoji()`](https://next.fakerjs.dev/api/internet.html#emoji).
```suggestion
 * To make your data more 🔥, you can use [`emoji()`](https://next.fakerjs.dev/api/internet.html#emoji).
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/internet/index.ts
> + * You also have access to a number of more technical elements of web requests, such as [`httpMethod`](https://next.fakerjs.dev/api/internet.html#httpmethod), [`httpStatusCode`](https://next.fakerjs.
```suggestion
 * You also have access to a number of the more technical elements of web requests, such as [`httpMethod`](https://next.fakerjs.dev/api/internet.html#httpmethod), [`httpStatusCode`](https://next.fakerjs.dev/api/internet.html#httpstatuscode), [`ip`](https://next.fakerjs.dev/api/internet.html#ip), [`mac`](https://next.fakerjs.dev/api/internet.html#mac), [`userAgent`](https://next.fakerjs.dev/api/internet.html#useragent), and [`port`](https://next.fakerjs.dev/api/internet.html#port).
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/location/index.ts
> + * Module to generate addresses and locations. Prior to Faker 8.0.0 this module was known as `faker.address`.
```suggestion
 * Module to generate addresses and locations. Prior to Faker 8.0.0, this module was known as `faker.address`.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/location/index.ts
> + * For a typical street address for a locale use [`streetAddress()`](https://next.fakerjs.dev/api/location.html#streetaddress), [`city()`](https://next.fakerjs.dev/api/location.html#city), [`state()`
```suggestion
 * For a typical street address for a locale, use [`streetAddress()`](https://next.fakerjs.dev/api/location.html#streetaddress), [`city()`](https://next.fakerjs.dev/api/location.html#city), [`state()`](https://next.fakerjs.dev/api/location.html#state) (or [`stateAbbr()`](https://next.fakerjs.dev/api/location.html#stateabbr)), and [`zipCode()`](https://next.fakerjs.dev/api/location.html#zipcode). Most locales provide localized versions for a specific country.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/location/index.ts
> + * If you need latitude and longitude coordinates, use [`latitude()`](https://next.fakerjs.dev/api/location.html#latitude) and [`longitude()`](https://next.fakerjs.dev/api/location.html#longitude) or
```suggestion
 * If you need latitude and longitude coordinates, use [`latitude()`](https://next.fakerjs.dev/api/location.html#latitude) and [`longitude()`](https://next.fakerjs.dev/api/location.html#longitude), or [`nearbyGPSCoordinate()`](https://next.fakerjs.dev/api/location.html#nearbygpscoordinate) for a latitude/longitude near a given location.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/lorem/index.ts
> + * In order of increasing size you can generate a single [`word()`](https://next.fakerjs.dev/api/lorem.html#word), multiple [`words()`](https://next.fakerjs.dev/api/lorem.html#words), a [`sentence()`
```suggestion
 * In order of increasing size you can generate a single [`word()`](https://next.fakerjs.dev/api/lorem.html#word), multiple [`words()`](https://next.fakerjs.dev/api/lorem.html#words), a [`sentence()`](https://next.fakerjs.dev/api/lorem.html#sentence), multiple [`sentences()`](https://next.fakerjs.dev/api/lorem.html#sentences), [`lines()`](https://next.fakerjs.dev/api/lorem.html#lines) separated by newlines, one [`paragraph()`](https://next.fakerjs.dev/api/lorem.html#paragraph), or multiple [`paragraphs()`](https://next.fakerjs.dev/api/lorem.html#paragraphs).
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/lorem/index.ts
> + * The generic [`text()`](https://next.fakerjs.dev/api/lorem.html#text) method can be used to generate a text between one sentence and multiple paragraphs, while [`slug()`](https://next.fakerjs.dev/a
```suggestion
 * The generic [`text()`](https://next.fakerjs.dev/api/lorem.html#text) method can be used to generate some text between one sentence and multiple paragraphs, while [`slug()`](https://next.fakerjs.dev/api/lorem.html#slug) generates an URL-friendly hyphenated string.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/number/index.ts
> + * For numbers that are not in base-10 you can use [`hex()`](https://next.fakerjs.dev/api/number.html#hex), [`octal()`](https://next.fakerjs.dev/api/number.html#octal) and [`binary()`](https://next.f
```suggestion
 * For numbers not in base-10, you can use [`hex()`](https://next.fakerjs.dev/api/number.html#hex), [`octal()`](https://next.fakerjs.dev/api/number.html#octal) and [`binary()`](https://next.fakerjs.dev/api/number.html#binary)`.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/person/index.ts
> + * Module to generate people's personal information such as names and job titles. Prior to Faker 8.0.0 this module was known as `faker.name`.
```suggestion
 * Module to generate people's personal information such as names and job titles. Prior to Faker 8.0.0, this module was known as `faker.name`.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/person/index.ts
> + * To generate a full name, use [`fullName`](https://next.fakerjs.dev/api/person.html#fullname). Note that this is not the same as simply concatenating [`firstName`](https://next.fakerjs.dev/api/pers
```suggestion
 * To generate a full name, use [`fullName`](https://next.fakerjs.dev/api/person.html#fullname). Note that this is not the same as simply concatenating [`firstName`](https://next.fakerjs.dev/api/person.html#firstname) and [`lastName`](https://next.fakerjs.dev/api/person.html#lastname), as the full name may contain a prefix, suffix, or both. Additionally, different supported locales will have differing name patterns. For example, the last name may appear before the first name, or there may be a double or hyphenated first or last name.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/person/index.ts
> + * You can also generate the parts of a name seperately, using [`prefix`](https://next.fakerjs.dev/api/person.html#prefix), [`firstName`](https://next.fakerjs.dev/api/person.html#firstname), [`middle
```suggestion
 * You can also generate the parts of a name separately, using [`prefix`](https://next.fakerjs.dev/api/person.html#prefix), [`firstName`](https://next.fakerjs.dev/api/person.html#firstname), [`middleName`](https://next.fakerjs.dev/api/person.html#middlename), [`lastName`](https://next.fakerjs.dev/api/person.html#lastname), and [`suffix`](https://next.fakerjs.dev/api/person.html#suffix). Not all locales support all of these parts.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/person/index.ts
> + * Many of the functions in this module can optionally choose either female, male or mixed names.
```suggestion
 * Many of the methods in this module can optionally choose either female, male or mixed names.
```

2023-03-25 21:33 UTC, import-brain commented on src/modules/person/index.ts
> + * The module can also generate other personal information which might appear in user profiles, such as [`gender`](https://next.fakerjs.dev/api/person.html#gender), [`zodiacSign`](https://next.fakerj
```suggestion
 * This module can also generate other personal information which might appear in user profiles, such as [`gender`](https://next.fakerjs.dev/api/person.html#gender), [`zodiacSign`](https://next.fakerjs.dev/api/person.html#zodiacsign), and [`bio`](https://next.fakerjs.dev/api/person.html#bio).
```

2023-03-26 09:56 UTC, ST-DDT approved these changes

2023-03-26 12:02 UTC, xDivisionByZerox approved these changes, later dismissed

2023-03-26 12:02 UTC, xDivisionByZerox commented on src/modules/image/index.ts
> + * This module previously also contained methods for specifically themed images like "fashion" or "food", but these are now deprecated. If you need more control over image type, you are recommended t
Why should we mention those if they are deprecated anyway?

2023-03-26 12:38 UTC, matthewmayer commented on src/modules/image/index.ts
> + * This module previously also contained methods for specifically themed images like "fashion" or "food", but these are now deprecated. If you need more control over image type, you are recommended t
I think because the majority of this module is now deprecated but it's not otherwise documented how to replace the categorised images.

2023-03-27 13:28 UTC, ST-DDT requested changes

2023-03-27 13:28 UTC, ST-DDT commented on src/modules/date/index.ts
> + * These methods have additional concerns about reproducibility, see [Reproducible Results](../guide/usage.html#reproducible-results).
Looks like you missed one or more relative links.

2023-03-27 15:39 UTC, ST-DDT requested changes

2023-03-27 15:39 UTC, ST-DDT commented on src/modules/date/index.ts
> + * For a realistic birthdate for an adult, use [`birthday()`](https://next.fakerjs.dev/api/date.html#birthday).
```suggestion
 * For a realistic birthdate for an adult, use [`birthdate()`](https://next.fakerjs.dev/api/date.html#birthdate).
```

2023-03-27 15:39 UTC, ST-DDT commented on src/modules/helpers/index.ts
> + * A number of methods can generate strings according to various patterns: [`replaceSymbols()`](https://next.fakerjs.dev/api/helpers.html#replacesymbols), [`replaceSymbolWithNumber()`](https://next.f
Please also mention the new string for regex method: https://next.fakerjs.dev/api/helpers.html#fromregexp

2023-03-29 04:00 UTC, matthewmayer commented on src/modules/helpers/index.ts
> + * A number of methods can generate strings according to various patterns: [`replaceSymbols()`](https://next.fakerjs.dev/api/helpers.html#replacesymbols), [`replaceSymbolWithNumber()`](https://next.f
i replaced regexpStyleStringParse with fromRegExp since it seems to do everything regexpStyleStringParse does and more? Will regexpStyleStringParse be deprecated?

2023-03-29 04:11 UTC, matthewmayer commented on src/modules/helpers/index.ts
> + * A number of methods can generate strings according to various patterns: [`replaceSymbols()`](https://next.fakerjs.dev/api/helpers.html#replacesymbols), [`replaceSymbolWithNumber()`](https://next.f
https://github.com/faker-js/faker/issues/1985

2023-03-29 06:48 UTC, ST-DDT approved these changes

2023-03-29 07:22 UTC, Shinigami92 approved these changes

2023-03-29 11:10 UTC, import-brain approved these changes

2023-03-29 11:17 UTC, Shinigami92 commented on src/modules/image/index.ts
> + * This module previously also contained methods for specifically themed images like "fashion" or "food", but these are now deprecated. If you need more control over image type, you are recommended t
One of @matthewmayer or @xDivisionByZerox should mark this as resolved or continue the discussion

2023-03-29 11:42 UTC, xDivisionByZerox commented on src/modules/image/index.ts
> + * This module previously also contained methods for specifically themed images like "fashion" or "food", but these are now deprecated. If you need more control over image type, you are recommended t
I simply wanted to point this out to avoid potential confusion on the user's side. But I don't have strong feelings about it.

2023-03-29 11:43 UTC, xDivisionByZerox approved these changes

2023-03-29 13:36 UTC, merged