docs(color): fix color rgb docs
faker-js/faker pull request #1958
Opened 2023-03-21 15:11 UTC by Shinigami92

close #1957

2023-03-21 15:38 UTC, matthewmayer requested changes

2023-03-21 15:38 UTC, matthewmayer commented on src/modules/color/index.ts
>     * @param options.casing Letter type case of the generated hex color. Only applied when `'hex'` format is used. Defaults to `'mixed'`.
This also seems wrong. It defaults to lower

2023-03-21 15:38 UTC, matthewmayer commented on src/modules/color/index.ts
> +   * faker.color.rgb() // '#ffffFF'
Shall we make it not ffffff? Doesn't feel very random to always get white!

Also lowercase per other comment

2023-03-22 18:42 UTC, ST-DDT approved these changes

2023-03-22 18:59 UTC, xDivisionByZerox approved these changes

2023-03-23 01:40 UTC, matthewmayer submitted a review, later dismissed

2023-03-23 01:40 UTC, matthewmayer commented on src/modules/color/index.ts
> +   * faker.color.rgb({ format: 'binary' }) // '00110010 00001000 01110110'
can we add some `includeAlpha` examples too?

2023-03-23 01:40 UTC, matthewmayer commented on src/modules/color/index.ts
> +   * @param options.casing Letter type case of the generated hex color. Only applied when `'hex'` format is used. Defaults to `'lower'`.
can we explicitly list what the possible values of `casing` and `format` are? (this is similar to issue we had in #1732 where we said we'd list out values of types manually until we are able to get the automatic extraction working)

<img width="712" alt="image" src="https://user-images.githubusercontent.com/152770/227076830-8d9178d4-a487-424f-9f3c-02a823381599.png">

2023-03-23 08:13 UTC, Shinigami92 commented on src/modules/color/index.ts
> +   * faker.color.rgb({ format: 'binary' }) // '00110010 00001000 01110110'
This PR just fix the current docs
If we want to add something to the docs additionally, I suggest opening a separate PR

2023-03-23 08:16 UTC, Shinigami92 commented on src/modules/color/index.ts
> +   * @param options.casing Letter type case of the generated hex color. Only applied when `'hex'` format is used. Defaults to `'lower'`.
Somehow `options.sex` for `fullName` can also be correctly extracted: https://next.fakerjs.dev/api/person.html#fullname

So maybe @ST-DDT as the author of the docs gen code need to handle this in a separate PR

2023-03-23 08:22 UTC, ST-DDT commented on src/modules/color/index.ts
> +   * @param options.casing Letter type case of the generated hex color. Only applied when `'hex'` format is used. Defaults to `'lower'`.
I'll have a look soon.

2023-03-23 10:43 UTC, ST-DDT commented on src/modules/color/index.ts
> +   * @param options.casing Letter type case of the generated hex color. Only applied when `'hex'` format is used. Defaults to `'lower'`.
I created a PR for that:

- https://github.com/faker-js/faker/pull/1965

But it isn't that simple, so I need some feedback.

2023-03-23 12:54 UTC, ST-DDT commented on src/modules/color/index.ts
> +   * faker.color.rgb({ format: 'binary' }) // '00110010 00001000 01110110'
Done: https://github.com/faker-js/faker/issues/1967

2023-03-23 13:01 UTC, merged