docs: extend Faker class jsdocs
faker-js/faker pull request #1960
Opened 2023-03-22 10:24 UTC by ST-DDT

Extracted from #1940 to make it easier to review.

2023-03-22 10:37 UTC, matthewmayer requested changes

2023-03-22 10:37 UTC, matthewmayer commented on src/faker.ts
> + *
// create a Faker instance with only `de` data and no `en` fallback

2023-03-22 10:37 UTC, matthewmayer commented on src/faker.ts
> + */
customFaker.music.genre() // throws Error as this data is not available in `de`

2023-03-22 10:37 UTC, matthewmayer commented on src/faker.ts
> +   * faker.setDefaultRefDate(() => new Date('2020-01-01'));
there's no real need for this to be a function right? Could just be a fixed value. Maybe if we do a function example it could be something actually dynamic?

2023-03-22 10:46 UTC, xDivisionByZerox commented on src/faker.ts
> + */
I had in mind to review then entire german locale during the next month('s) since I'm from Germany and use the locale frequently.

Could we maybe choose another locale if we want to include a failing example?

2023-03-22 10:49 UTC, xDivisionByZerox commented on src/faker.ts
> +           * DEPRECATED: The locale data to use for this instance.
Why `DEPRECATED` instead of the commonly use `@deprecated`?

2023-03-22 10:51 UTC, matthewmayer commented on src/faker.ts
> + */
es has names but no music

2023-03-22 10:58 UTC, ST-DDT commented on src/faker.ts
> +           * DEPRECATED: The locale data to use for this instance.
So that it will be shown in the api docs page.

I will add the `@deprecated` anyway.

2023-03-22 11:04 UTC, xDivisionByZerox commented on src/faker.ts
> +           * DEPRECATED: The locale data to use for this instance.
Ah I see the warning card (like [here](https://fakerjs.dev/api/fake.html#fake)) only shows up if an entire method is deprecated (?). Gotcha 👍

2023-03-22 11:05 UTC, ST-DDT commented on src/faker.ts
> +           * DEPRECATED: The locale data to use for this instance.
Done

2023-03-22 11:05 UTC, ST-DDT commented on src/faker.ts
> + */
Done

2023-03-22 11:05 UTC, ST-DDT commented on src/faker.ts
> + *
Done

2023-03-22 11:08 UTC, ST-DDT commented on src/faker.ts
> +           * DEPRECATED: The locale data to use for this instance.
Theoretically, I could check if the property is deprecated and add the `DEPRECATED` automatically.
Should I?

2023-03-22 11:18 UTC, xDivisionByZerox commented on src/faker.ts
> +           * DEPRECATED: The locale data to use for this instance.
> Theoretically, I could check if the property is deprecated and add the DEPRECATED automatically.

You are referring to documentation only. Yes?
If so that sounds good, but would be overkill for now. At least I think so.

2023-03-22 11:19 UTC, xDivisionByZerox submitted a review, later dismissed

2023-03-22 18:20 UTC, Shinigami92 commented on src/faker.ts
> + * The main Faker class containing all modules that can be used to generate data.
This doesn't sound correct :thinking: 

> The main Faker class containing all modules that can be used to generate data.

Maybe something like:

This is Faker's main class that contains all the modules that can be used to generate data.

2023-03-22 18:46 UTC, ST-DDT commented on src/faker.ts
> + * The main Faker class containing all modules that can be used to generate data.
Like this?

```suggestion
 * The is Faker's main class containing all modules that can be used to generate data.
```

2023-03-22 19:28 UTC, Shinigami92 submitted a review, later dismissed

2023-03-22 20:24 UTC, ST-DDT commented on src/faker.ts
> +           * DEPRECATED: The locale data to use for this instance.
Done anyway: https://github.com/faker-js/faker/pull/1962

2023-03-23 01:45 UTC, matthewmayer approved these changes

2023-03-24 07:27 UTC, Shinigami92 approved these changes

2023-03-27 11:21 UTC, merged