docs(internet): internet.password doesn't create crypto-secure PWs
faker-js/faker pull request #1961
Opened 2023-03-22 19:37 UTC by deltamualpha

Since this API uses faker.number, which itself is just using a Mersenne Twister implementation, these passwords are not safe for use in cryptographically-sensitive contexts.

2023-03-22 20:03 UTC, ST-DDT approved these changes

2023-03-22 20:09 UTC, Shinigami92 approved these changes, later dismissed

2023-03-22 21:04 UTC, xDivisionByZerox approved these changes, later dismissed

2023-03-23 01:48 UTC, matthewmayer commented on src/modules/internet/index.ts
> +   * Generates a random password. Since the source of the randomness is not cryptographically secure,
I think we could even be a bit stronger?

Generates a random password. Do not use this method for generating real user passwords. Since the source of the randomness is not cryptographically secure, neither is this generator.

2023-03-23 03:22 UTC, deltamualpha commented on src/modules/internet/index.ts
> +   * Generates a random password. Since the source of the randomness is not cryptographically secure,
Would be happy to add stronger language; just didn't want to come in guns blazing on this, since most doc strings in the API tend toward the terse.

2023-03-23 05:41 UTC, matthewmayer commented on src/modules/internet/index.ts
> +   * Generates a random password. Since the source of the randomness is not cryptographically secure,
We are working on more informative docs, i think these kind of usage notes are particularly helpful, i'll let the maintainers pipe in.

2023-03-23 08:40 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * Generates a random password. Since the source of the randomness is not cryptographically secure,
I think adding that additional sentence is more important than the other one. Thanks for bringing this to my attention.
If you are knowlegdable enough to understand what cryptographically secure passwords are, then you probably wouldnt use the method in the first place.
However, if you dont then you might not know what to do with that information alone.

2023-03-23 10:16 UTC, matthewmayer commented on src/modules/internet/index.ts
> +   * Generates a random password. Since the source of the randomness is not cryptographically secure,
Agreed, we should flag up "footguns" (ie features that might allow a novice developer to shoot themselves in the foot)

So for example using this for generating real passwords, or sending real emails to the output of faker.internet.email() etc

2023-03-23 13:39 UTC, ST-DDT requested changes
Please change the description as mentioned above.

2023-03-23 13:47 UTC, deltamualpha commented on src/modules/internet/index.ts
> +   * Generates a random password. Since the source of the randomness is not cryptographically secure,
I've updated the description to both note that the passwords should not be used, and described the generated output as a "password-like string" as opposed to a "password", which also should drive home the point.

2023-03-23 13:58 UTC, ST-DDT approved these changes

2023-03-23 14:10 UTC, xDivisionByZerox approved these changes

2023-03-23 14:25 UTC, Shinigami92 approved these changes

2023-03-23 14:25 UTC, merged