fix(image): use seeded picsum
faker-js/faker pull request #1968
Opened 2023-03-23 14:00 UTC by Shinigami92

closes #1964

2023-03-23 14:05 UTC, ST-DDT submitted a review, later dismissed

2023-03-23 14:13 UTC, xDivisionByZerox submitted a review, later dismissed

2023-03-23 16:00 UTC, matthewmayer requested changes

2023-03-23 16:00 UTC, matthewmayer commented on src/modules/image/index.ts
> +    let url = `https://picsum.photos/seed/${this.faker.number.int()}/${width}/${height}`;
The seed values seem a bit long maybe could do like faker.string.alphanumeric with a fixed length of 4 or 5?

2023-03-23 16:14 UTC, xDivisionByZerox commented on src/modules/image/index.ts
> +    let url = `https://picsum.photos/seed/${this.faker.number.int()}/${width}/${height}`;
Whats the problem with "long" values? 
We are talking about a difference of 15/16 or 4/5 characters...

2023-03-23 16:20 UTC, matthewmayer commented on src/modules/image/index.ts
> +    let url = `https://picsum.photos/seed/${this.faker.number.int()}/${width}/${height}`;
they're just a bit ugly. no big deal :D

2023-03-23 17:01 UTC, ST-DDT commented on src/modules/image/index.ts
> +    let url = `https://picsum.photos/seed/${this.faker.number.int()}/${width}/${height}`;
**Team Decision**

- The length of the link should be variable
- We will use alphaNumeric with mixed case

2023-03-23 18:22 UTC, ST-DDT submitted a review, later dismissed

2023-03-23 18:31 UTC, matthewmayer requested changes

2023-03-23 18:31 UTC, matthewmayer commented on src/modules/image/index.ts
> +   * faker.image.urlPicsumPhotos() // 'https://picsum.photos/seed/241/640/480'
Should also have alphanumeric seeds in the examples

2023-03-23 18:36 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * faker.image.urlPicsumPhotos({ blur: 4, grayscale: true }) // 'https://picsum.photos/seed/241/640/480?grayscale&blur=4'
```suggestion
   * faker.image.urlPicsumPhotos() // 'https://picsum.photos/seed/NWbJM2B/640/480'
   * faker.image.urlPicsumPhotos({ width: 128 }) // 'https://picsum.photos/seed/NWbJM2B/128/480'
   * faker.image.urlPicsumPhotos({ height: 128 }) // 'https://picsum.photos/seed/NWbJM2B/640/128'
   * faker.image.urlPicsumPhotos({ grayscale: true }) // 'https://picsum.photos/seed/NWbJM2B/640/480?grayscale'
   * faker.image.urlPicsumPhotos({ blur: 4 }) // 'https://picsum.photos/seed/NWbJM2B/640/480?blur=4'
   * faker.image.urlPicsumPhotos({ blur: 4, grayscale: true }) // 'https://picsum.photos/seed/NWbJM2B/640/480?grayscale&blur=4'
```

2023-03-23 18:52 UTC, matthewmayer commented on src/modules/image/index.ts
> +   * faker.image.urlPicsumPhotos({ blur: 4, grayscale: true }) // 'https://picsum.photos/seed/241/640/480?grayscale&blur=4'
They shouldn't be the same seed for all?

2023-03-23 18:54 UTC, ST-DDT approved these changes

2023-03-23 20:18 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * faker.image.urlPicsumPhotos({ blur: 4, grayscale: true }) // 'https://picsum.photos/seed/241/640/480?grayscale&blur=4'
Having the same seed here probably makes it easier to see the differences between each invocation.

2023-03-29 09:42 UTC, matthewmayer approved these changes

2023-03-30 15:11 UTC, merged