test: separate jsdoc tag tests
faker-js/faker pull request #1969
Opened 2023-03-23 14:21 UTC by Shinigami92

In the history we had some (mostly newbie) contributors but also myself that got confused by the `examplesAndDeprecations` test.

This PR aims for separating the verification of each JSDoc tag into its own section, so it can faster be identified which problem occurred.

Also this improves the test in that way that for example when a `@param` fails, a `@since` tag will still get validated in the same test run.

2023-03-23 14:22 UTC, Shinigami92 commented on test/scripts/apidoc/examplesAndDeprecations.spec.ts
> +// TODO christopher 2023-03-23: Rename file to verify-jsdoc-tags.spec.ts
Before merging this PR, I would like to rename the file to `verify-jsdoc-tags.spec.ts` to make the intend of the test more clear.
I did not renamed it directly, so the diff does not get confused because of the changes inside the file.

2023-03-23 14:32 UTC, Shinigami92 commented
Right now the loop should be swapped

yet it is: `... > verify JSDoc tags > CompanyModule > verify @deprecated tag > suffixes`

it should be one of:
1. `... > verify JSDoc tags > CompanyModule > suffixes > verify @deprecated tag`
2. `... > verify JSDoc tags > verify @deprecated tag > CompanyModule > suffixes`

2023-03-23 14:57 UTC, ST-DDT commented on test/scripts/apidoc/examplesAndDeprecations.spec.ts
> +    describe('verify @deprecated tag', () => {
```suggestion
    describe('verify @deprecated tag and @examples', () => {
```

2023-03-23 15:03 UTC, Shinigami92 commented on test/scripts/apidoc/examplesAndDeprecations.spec.ts
> +    describe('verify @deprecated tag', () => {
No, I want (try) to achieve that every tag is independent from each other
The `@example` tag is checked in the section above

I'm currently try to rewrite the test so I don't need the `@example` directly but just execute the code. (But I assume I just need the examples for that indirectly)

2023-03-23 15:25 UTC, Shinigami92 commented on test/scripts/apidoc/examplesAndDeprecations.spec.ts
> +    describe('verify @deprecated tag', () => {
Now it might be more clear what is happening
I extracted the write file process out of the tests
What I might need to do here is maybe wrap the `await import(path);` in the example test with a "should not throw" whereas the deprecation test is just running them to execute the potential `console.warn`

2023-03-23 18:01 UTC, ST-DDT reviewed
Maybe add a `beforeAll(deleteTemp);`

2023-03-23 18:21 UTC, ST-DDT submitted a review, later dismissed

2023-03-28 08:05 UTC, matthewmayer submitted a review, later dismissed

2023-03-28 12:33 UTC, xDivisionByZerox commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +  const tempDir = resolve(__dirname, 'temp');
Can we store this in a variable and reuse this in `resolveDirToModules`?

2023-03-28 12:33 UTC, xDivisionByZerox commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +            )} } from '../../../../../src';\n\n${examples}`
This import seems kinda magical here. Could we resolve this with a dynamic, "lazy" import?

I'm on phone, so writing code examples  is kinda hard, sorry.

2023-03-28 12:33 UTC, xDivisionByZerox commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +            ).not.toBe('Missing');
Is `'Missing'` the default value of typedoc? If so, can we somehow decouple that or add least add a comment?

2023-03-28 12:33 UTC, xDivisionByZerox commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +        it('verify @see tag', () => {
How does vitest handle `it` without `expect`? I couldn't find anything in their docs. I know that this test would fail in jest for methods with no see tag, since no expectation would be generated.

2023-03-28 12:33 UTC, xDivisionByZerox commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +          expect(extractSince(signature), '@since to be present').toBeTruthy();
We can (and should) verify for a semver here, no?

2023-03-28 15:12 UTC, Shinigami92 commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +            ).not.toBe('Missing');
I assume this is related to https://github.com/faker-js/faker/blob/8516bfb109741231a49ec8572176e5a12b4c1a37/scripts/apidoc/signature.ts#L44

2023-03-28 15:15 UTC, Shinigami92 commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +            ).not.toBe('Missing');
@ST-DDT correct me if I'm wrong

2023-03-28 15:17 UTC, Shinigami92 commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +            )} } from '../../../../../src';\n\n${examples}`
For now, no

This is just the string content of what will be written into a temp file
It would only break if we move the temp file to another location
But as the temp folder will get cleaned after run anyways, I dont care that much of its content (or at least if it is pretty or not)

2023-03-28 15:19 UTC, Shinigami92 commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +        it('verify @see tag', () => {
Right now it works :shrug: 
The check itself might get improved in another PR, but here I just took the already working test-code

2023-03-28 15:38 UTC, ST-DDT commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +        it('verify @see tag', () => {
```suggestion
        it('verify @see tags', () => {
```

2023-03-28 15:40 UTC, ST-DDT approved these changes, later dismissed

2023-03-28 16:13 UTC, xDivisionByZerox commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +            ).not.toBe('Missing');
I see. Again, I reviewed this on my phone, so getting everything right was kinda hard there.
Still, a variable named `defaultSummary` exported from the `signature.ts` file could be a good idea to make the assumption less magical.

2023-03-28 16:15 UTC, Shinigami92 commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +            ).not.toBe('Missing');
@ST-DDT whats your opinion about that?

2023-03-28 16:22 UTC, xDivisionByZerox commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +            ).not.toBe('Missing');
This would not be blocking from my side, tho.

2023-03-28 16:29 UTC, ST-DDT commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +            ).not.toBe('Missing');
The generated default is `Missing`, but it actually gets markdown parsed.
I guess, it doesn't really hurt to have a constant like that.

2023-03-28 17:07 UTC, ST-DDT requested changes

2023-03-28 17:07 UTC, ST-DDT commented on scripts/apidoc/signature.ts
> +export const DEFAULT_SUMMARY = 'Missing';
This is not really a default. It is missing.

2023-03-28 17:11 UTC, ST-DDT commented on scripts/apidoc/signature.ts
> +export const DEFAULT_SUMMARY = 'Missing';
Is it a summary? Maybe description?

2023-03-28 17:30 UTC, Shinigami92 commented on scripts/apidoc/signature.ts
> +export const DEFAULT_SUMMARY = 'Missing';
Before I try out several names, please suggest one so I don't need to push several commits

2023-03-28 21:18 UTC, ST-DDT commented on scripts/apidoc/signature.ts
> +export const DEFAULT_SUMMARY = 'Missing';
`MISSING_DESCRIPTION`

2023-03-29 07:41 UTC, ST-DDT approved these changes

2023-03-29 19:59 UTC, xDivisionByZerox approved these changes

2023-03-30 15:02 UTC, merged