refactor(locale): introduce metadata
faker-js/faker pull request #1978
Opened 2023-03-26 16:47 UTC by ST-DDT

Removes the special handling of `faker.definitions.title` by moving it to `faker.definitions.metadata.title`.
As this makes it way easier to (type) safely implement #893.

2023-03-26 16:48 UTC, ST-DDT commented
Blocks https://github.com/faker-js/faker/issues/893

- #893

2023-03-27 06:35 UTC, Shinigami92 commented on src/locales/af_ZA/metadata/index.ts
> +  title,
Would it be easy to just inline the string here?
IMO it's a bit to much to generate a whole new file, load it and use its primitive value, and all that just for a string 🤔

2023-03-27 06:35 UTC, Shinigami92 commented on src/locales/de_AT/metadata/title.ts
> +export default 'German (Austria)';
Just an idea/note maybe for another PR: we could now split the values, because now we have just a separate metadata object for it.

2023-03-27 06:35 UTC, Shinigami92 commented on test/faker.spec.ts
> +      expect(faker.definitions.location?.city_name).toBeDefined();
Not sure if this change is related to this PR 🤔

2023-03-27 06:35 UTC, Shinigami92 commented on src/definitions/definitions.ts
> +  Record<string, Record<string, unknown>>;
Why is this so different as before?

Why is this not something like
```ts
MetaEntryDefinitions & LocaleEntry<Definitions>;
// or
{ metadata: MetadataDefinitions; } & LocaleEntry<Definitions>;
```

_side note: I have not checked via IDE, I just see plain text code in GitHub Web UI_

2023-03-27 06:47 UTC, matthewmayer commented
i would like to see more metadata added, for example:
```
{
title:"German (Austria)",
endonym:"Deutsch (Österreich)",
code:"de_AT",
language:"de",
country:"AT",
ltr:false,
script:"Latin"
}
```

2023-03-27 06:59 UTC, Shinigami92 commented
> i would like to see more metadata added, for example:
> 
> ```
> {
> title:"German (Austria)",
> endonym:"Deutsch (Österreich)",
> code:"de_AT",
> language:"de",
> country:"AT",
> ltr:false,
> script:"Latin"
> }
> ```

Yes 🙌 
Absolutely, but this PR is just preparation for this

2023-03-27 07:05 UTC, matthewmayer commented
> > i would like to see more metadata added, for example:
> > ```
> > {
> > title:"German (Austria)",
> > endonym:"Deutsch (Österreich)",
> > code:"de_AT",
> > language:"de",
> > country:"AT",
> > ltr:false,
> > script:"Latin"
> > }
> > ```
> 
> Yes 🙌 Absolutely, but this PR is just preparation for this
> 
> Edit: And this is also why I suggested to not move primitive data into own files It would just explode in data/files that are all just 1 line long

agreed, if there are ~7 metadata items like this it should be in one file total

2023-03-27 08:44 UTC, ST-DDT commented on src/locales/af_ZA/metadata/index.ts
> +  title,
Looks like I cannot remove all special handling related to these data. 😢

2023-03-27 08:44 UTC, ST-DDT commented on src/locales/de_AT/metadata/title.ts
> +export default 'German (Austria)';
Sure

2023-03-27 08:45 UTC, ST-DDT commented on test/faker.spec.ts
> +      expect(faker.definitions.location?.city_name).toBeDefined();
```suggestion
      expect(faker.definitions.location.city_name).toBeDefined();
```

2023-03-27 08:47 UTC, ST-DDT commented on src/definitions/definitions.ts
> +  Record<string, Record<string, unknown>>;
The first because that would cause issues because then title and co would remain on the current level, which causes type safety issues.

LocaleEntry is only meant for modules. Using it for the top level would cause type safety issues again.

2023-03-27 08:51 UTC, ST-DDT commented
> > Yes 🙌 Absolutely, but this PR is just preparation for this
> > Edit: And this is also why I suggested to not move primitive data into own files It would just explode in data/files that are all just 1 line long
> 
> agreed, if there are ~7 metadata items like this it should be in one file total

I did it like this to avoid having to add special handling for any of these, but I will add that back.

2023-03-27 08:53 UTC, Shinigami92 commented on src/locales/af_ZA/metadata/index.ts
> +  title,
Yes, sorry for that but the meta data are not directly locales (as you already also wrote down below)
they are extra data that enriches / decorates the locale data set
So in my assumption it is totally valid that they need to get handled specially

2023-03-27 17:03 UTC, ST-DDT commented on src/locales/af_ZA/metadata/index.ts
> +  title,
Done

2023-03-27 17:11 UTC, ST-DDT commented on src/locales/af_ZA/metadata.ts
> +export default { title: 'Afrikaans' };
Should we use explicit type definitions?

```suggestion
export default <MetadataDefinitions> { title: 'Afrikaans' };
```

2023-03-27 20:11 UTC, Shinigami92 commented on src/locales/af_ZA/metadata.ts
> +export default { title: 'Afrikaans' };
Definitely do **not** use this syntax (`<type> value`), ever
It is TS 2.x historical and deprecated
Use `value as type` instead

Beside that: I would use what is used in the other locale definition files

2023-03-27 20:37 UTC, ST-DDT commented on src/locales/af_ZA/metadata.ts
> +export default { title: 'Afrikaans' };
> It is TS 2.x historical and deprecated

I didn't get a deprecation warning though.

-------

The other files use something like this:

```suggestion
const metadata: MetadataDefinitions = {
  title: 'Afrikaans',
};
export default metadata;
```

2023-03-27 20:38 UTC, ST-DDT commented on src/locales/af_ZA/metadata.ts
> +export default { title: 'Afrikaans' };
Alternatively we could rewrite all index.ts files to look like this:

```suggestion
export default { title: 'Afrikaans' } as MetadataDefinitions;
```

Which should it be?

2023-03-27 20:47 UTC, Shinigami92 commented on src/locales/af_ZA/metadata.ts
> +export default { title: 'Afrikaans' };
> The other files use something like this:
> 
> 
> 
> ```suggestion
> 
> const metadata: MetadataDefinitions = {
> 
>   title: 'Afrikaans',
> 
> };
> 
> export default metadata;
> 
> ```

This one

2023-03-27 20:57 UTC, ST-DDT commented on src/locales/af_ZA/metadata.ts
> +export default { title: 'Afrikaans' };
Done

2023-03-28 05:50 UTC, matthewmayer requested changes
The available metadata should be documented (either on an explicit /api/metadata.html page or in the localization guide).

2023-03-28 05:53 UTC, matthewmayer requested changes, later dismissed
also unless i'm missing something, there's no way to access the metadata from a Faker instance (ref #1908 ). i'd expect to be able to do something like:
```
const {fakerDE} = require("@faker-js/faker")
fakerDE.metadata.title() //German
```

2023-03-28 07:16 UTC, Shinigami92 commented
> also unless i'm missing something, there's no way to access the metadata from a Faker instance (ref #1908 ). i'd expect to be able to do something like:
> 
> ```
> const {fakerDE} = require("@faker-js/faker")
> fakerDE.metadata.title() //German
> ```

I thought it would be `fakerDE.definitions.metadata.title // German`

2023-03-28 08:04 UTC, matthewmayer commented
Ok that works, but it's not documented that you can access the definitions like that.

2023-03-28 08:10 UTC, Shinigami92 commented
> Ok that works, but it's not documented that you can access the definitions like that.

1. If I remember correctly we dont want to document that so it is not supported officially
2. You can use `fakerDE.helpers.fake('{{metadata.title}}')` as far as I know (that was previously not possible like `fakerDE.helpers.fake('{{title}}')` because then `title` would get parsed as "module" instead of entry/function)

2023-03-28 08:29 UTC, matthewmayer commented
> > Ok that works, but it's not documented that you can access the definitions like that.
> 
> 1. If I remember correctly we dont want to document that so it is not supported officially
> 2. You can use `fakerDE.helpers.fake('{{metadata.title}}')` as far as I know (that was previously not possible like `fakerDE.helpers.fake('{{title}}')` because then `title` would get parsed as "module" instead of entry/function)

i think there should be a stable, documented way of accessing the metadata. A faker instance should "know" what metadata is associated with it (you could previously access faker.locale, etc).

2023-03-28 09:29 UTC, ST-DDT commented
I'm torn on this one.
On one hand, having a stable way to access these metadata seems useful, but the very structure of the data make unrelyable with our normal way of accessing them. (Especially so when we merge #893, that would throw an Error for missing optional data, that are likely to be added: https://github.com/faker-js/faker/pull/1978#issuecomment-1484592384.)

There are two ways to access these data:

- `faker.metadata(): MetadataDefinitions`
- `faker.raw(Definitions).metadata` (to be introduced, for accessing optional definitions thus avoiding the thrown error, with an explicit hint: Here be dragons)

2023-03-28 09:45 UTC, Shinigami92 commented
> * faker.metadata(): MetadataDefinitions

I tend totally to this
The metadata is also something that should always be defined and should not contain fallback data
So I consider metadata as stable and something we want to officially support in the future

2023-03-28 09:45 UTC, ST-DDT commented
Since we don't have the API for it yet, I suggest we add it in a separate PR.

2023-03-28 10:04 UTC, ST-DDT commented
We will add it in a separate PR so we have an distinct changelog entry.

2023-03-28 11:05 UTC, ST-DDT commented
> We will add it in a separate PR so we have an distinct changelog entry. (and less importantly, this PR refactors the existing structure, whereas that method is a new feature)

Extracted into: https://github.com/faker-js/faker/issues/1984

2023-03-28 11:16 UTC, Shinigami92 submitted a review, later dismissed

2023-03-28 17:35 UTC, xDivisionByZerox commented on scripts/generateLocales.ts
> +      e
By providing the original error as the second argument it will be joined (with a space) with the previous error message and thus displayed on the same line as first one.
For better readbility we should display it in a new log.

2023-03-28 17:35 UTC, xDivisionByZerox commented on src/definitions/definitions.ts
> +  metadata: MetadataDefinitions;
Why do we need to declare it in both `Definition` AND `LocaleDefinition`. This doesn't seem right to me.

2023-03-28 21:38 UTC, ST-DDT commented on src/definitions/definitions.ts
> +  metadata: MetadataDefinitions;
I merged both together now.

2023-03-28 21:42 UTC, ST-DDT commented on scripts/generateLocales.ts
> +      e
Done.

2023-03-28 22:07 UTC, xDivisionByZerox approved these changes, later dismissed

2023-03-29 07:32 UTC, Shinigami92 approved these changes, later dismissed

2023-03-29 19:54 UTC, xDivisionByZerox submitted a review, later dismissed

2023-03-30 17:29 UTC, xDivisionByZerox approved these changes

2023-03-31 10:50 UTC, Shinigami92 approved these changes

2023-04-01 12:37 UTC, merged