Accept dates as params for Date methods
faker-js/faker pull request #200
Opened 2022-01-17 13:44 UTC by pkuczynski

Fixes #198

2022-01-17 15:04 UTC, Shinigami92 requested changes

2022-01-17 15:04 UTC, Shinigami92 commented on src/date.ts
> +      date = refDate instanceof Date ? date : new Date(Date.parse(refDate));
I assume you wanted to pass `refDate` instead of `date`, do you?

_applies to below too_

2022-01-17 15:05 UTC, Shinigami92 commented
Due to this is a runtime change, I think we will do this in v6.1, because we try to focus on stability of the project itself first (CI, tests, docs etc)

2022-01-17 15:17 UTC, pkuczynski commented on src/date.ts
> +      date = refDate instanceof Date ? date : new Date(Date.parse(refDate));
Ah! Of course! Sorry! Was quickly editing on Github without running locally. Was hoping unit tests would pick it up :) Fixed.

2022-01-17 15:21 UTC, pkuczynski commented
> Due to this is a runtime change, I think we will do this in v6.1, because we try to focus on stability of the project itself first (CI, tests, docs etc)

I only got to this change, because my current code start failing after the upgrade. So this is not strictly a new feature, but restoring functionality working with previous version of faker.

2022-01-17 15:29 UTC, Shinigami92 commented
Speaking about unit tests, could you add one?

2022-01-17 23:31 UTC, pkuczynski commented
> Speaking about unit tests, could you add one?

Done. If you would be using `jest` I could do `it.each` to run the same tests with different examples. Without it, I just had to duplicate some tests

2022-01-17 23:32 UTC, pkuczynski commented
Btw. good that you asked about tests, as I discovered a bug, where original date was incorrectly mutated...

2022-01-21 09:21 UTC, LawrenceWooding commented
> I only got to this change, because my current code start failing after the upgrade. So this is not strictly a new feature, but restoring functionality working with previous version of faker.

I had a similar experience to @pkuczynski  - attempting to replace the old faker-js package with this new one caused errors in previously working code. I am confident that most (if not all) of the Date functions used to support Date() fields. This is supported by the fact that in the [documentation for Dates all of the functions take Date objects instead of strings](https://fakerjs.dev/api/date.html) (or at least the ones that were already documented).

Speaking of which the docs should probably be updated in this branch to better reflect the type definitions (e.g `string | Date` as opposed to `Date`). I am happy to do this if I get a spare moment.

Thank you @pkuczynski for looking into this issue, it is the primary roadblock between my organisation switching our frontend repository to the community faker-js package.

2022-01-21 09:59 UTC, LawrenceWooding commented
I have made a pull request in @pkuczynski 's fork with the updated documentation. :)

2022-01-21 10:11 UTC, pkuczynski commented
> I have made a pull request in @pkuczynski 's fork with the updated documentation. :)

And I just merged it, thanks :)

2022-01-21 10:12 UTC, pkuczynski commented
@Shinigami92 Is there anything else you want me to do to get this PR accepted, merged and released?

2022-01-21 12:37 UTC, Shinigami92 requested changes

2022-01-21 12:37 UTC, Shinigami92 commented on src/date.ts
> +  private createDate(date: string | Date) {
```suggestion
  private createDate(date?: string | Date): Date {
```

2022-01-21 12:37 UTC, Shinigami92 commented on src/date.ts
> +    if (typeof date !== 'undefined') {
For sake of simplicity, I would suggest following:

```suggestion
    if (date != null) {
```

2022-01-21 12:37 UTC, Shinigami92 commented on src/date.ts
> +      from instanceof Date ? new Date(from) : new Date(Date.parse(from));
```suggestion
    let lastDate = this.createDate(from);
```

2022-01-21 12:37 UTC, Shinigami92 commented on src/date.ts
> +    let fromMilli = from instanceof Date ? from.getTime() : Date.parse(from);
You could extract these also to a private helper function

```suggestion
    const toMilli = this.toMillis(to);
    let fromMilli = this.toMillis(from);
```

It could make sense to rename `createDate` to `toDate`

2022-01-21 12:37 UTC, Shinigami92 commented on src/date.ts
> +    const toMilli = to instanceof Date ? to.getTime() : Date.parse(to);
Also use helper here

2022-01-21 12:39 UTC, Shinigami92 commented
> Done. If you would be using `jest` I could do `it.each` to run the same tests with different examples. Without it, I just had to duplicate some tests

You will love our next PR incoming :P
See #235

2022-01-21 12:58 UTC, pkuczynski commented
> You will love our next PR incoming :P See #235

Citing their docs: "It's not recommended to migrate your current testing setups yet" ;) So I am not sure :) Is it jest based?

2022-01-21 13:02 UTC, Shinigami92 commented
> Citing their docs: "It's not recommended to migrate your current testing setups yet" ;) So I am not sure :) Is it jest based?

I'm one of Vite core members and in direct contact with Anthony Fu :slightly_smiling_face: 
Also yes, vitest is a somewhat swap-in-out replacement for jest. But written in more modern syntax and stripped out old legacy stuff. So it's jest but in fast ^^

2022-01-21 13:08 UTC, pkuczynski commented on src/date.ts
> +    let fromMilli = from instanceof Date ? from.getTime() : Date.parse(from);
Done x2

2022-01-21 13:08 UTC, pkuczynski commented on src/date.ts
> +    const toMilli = to instanceof Date ? to.getTime() : Date.parse(to);
Done

2022-01-21 13:09 UTC, pkuczynski commented
@Shinigami92 all feedback applied. Ready for re-review.

2022-01-21 13:10 UTC, pkuczynski commented
> > Citing their docs: "It's not recommended to migrate your current testing setups yet" ;) So I am not sure :) Is it jest based?
> 
> I'm one of Vite core members and in direct contact with Anthony Fu 🙂 Also yes, vitest is a somewhat swap-in-out replacement for jest. But written in more modern syntax and stripped out old legacy stuff. So it's jest but in fast ^^

Happy to try it out :)

2022-01-21 13:26 UTC, Shinigami92 approved these changes

2022-01-21 13:30 UTC, Shinigami92 commented
The windows test is not related and can be ignore

2022-01-21 21:31 UTC, Shinigami92 commented
We merged the vitest branch :partying_face: 
Please re-implement your tests in the new test-suite

2022-01-21 22:16 UTC, pkuczynski commented
You are not making my life easy! ;)

2022-01-21 22:44 UTC, Shinigami92 commented
> You are not making my life easy! ;)

I'm a bit sorry :sweat_smile: 
But we are/were in a process to make the project stable (like milestone for v6.0 is saying)
And all the mini PRs here and there doesn't make my life easy as well :sweat_smile:

2022-01-21 23:54 UTC, pkuczynski commented
> I'm a bit sorry 😅 But we are/were in a process to make the project stable (like milestone for v6.0 is saying) And all the mini PRs here and there doesn't make my life easy as well 😅

I can imagine :) Sorry to interrupt your valuable work. Just wanted to fix the issue encountered after upgrade. Didn't know you would be making such significant changes soon...

Anyway, I think I am done. Let me know if there is anything more I should do?

2022-01-21 23:57 UTC, pkuczynski commented on test/date.spec.ts
> +    });
By the way, I tried to remove test duplication using `it.each`, but it does not seem to be supported? Example test improvement based on jest syntax would be:

```js
    describe('returns a date N years before the date given', () => {
      const refDate = new Date(2120, 11, 9, 10, 0, 0, 0); // set the date beyond the usual calculation (to make sure this is working correctly)

      it.each([
        ['refDate as string', refDate.toJSON()]
        ['refDate as Date', refDate]
      ])('%s', (_, ref) => {
        const date = faker.date.past(75, ref);

        // date should be before date given but after the current time
        expect(date).lessThan(refDate);
        expect(date).greaterThan(new Date());
      })
    });
```

2022-01-22 00:20 UTC, Shinigami92 commented on test/date.spec.ts
> +    });
Progress can be tracked here :slightly_smiling_face: 
https://github.com/vitest-dev/vitest/issues/120

2022-01-22 00:30 UTC, Shinigami92 requested changes

2022-01-22 00:30 UTC, Shinigami92 commented on test/date.spec.ts
> +      expect(date).greaterThan(new Date());
This test would only pass for the next 45 years and then suddenly fail :thinking: 
Should we just hardcode this date?

2022-01-22 00:30 UTC, Shinigami92 commented on test/date.spec.ts
> +      const date = faker.date.recent(days, refDate.toJSON());
**question:** why is toJSON needed here?

2022-01-22 00:30 UTC, Shinigami92 commented on test/date.spec.ts
> +      const date = faker.date.recent(days, refDate.toJSON());
Ah, I think it's better to use `toISOString` here so it's more understandable

2022-01-22 00:30 UTC, Shinigami92 commented on test/date.spec.ts
> +      const date = faker.date.soon(days, refDate.toJSON());
Also better use `toISOString` here

2022-01-22 00:30 UTC, Shinigami92 commented on test/date.spec.ts
> +      const date = faker.date.between(from.toJSON(), to.toJSON());
And here :wink:

2022-01-22 00:30 UTC, Shinigami92 commented on test/date.spec.ts
> +      const dates = faker.date.betweens(from.toJSON(), to.toJSON());
You get the idea

2022-01-23 08:30 UTC, ST-DDT commented on test/date.spec.ts
> +    });
You can use a normal for loop to achieve the same.

2022-01-23 15:49 UTC, pkuczynski commented on test/date.spec.ts
> +    });
I know I could use the loop. It would look like this then:

```
    describe('returns a date N years before the date given', () => {
      const refDate = new Date(2120, 11, 9, 10, 0, 0, 0); // set the date beyond the usual calculation (to make sure this is working correctly)

      ([
        ['refDate as string', refDate.toJSON()],
        ['refDate as Date', refDate]
      ] as [string, string|Date][]).forEach(t => it(t[0], () => {
        const date = faker.date.past(75, t[1]);

        // date should be before date given but after the current time
        expect(date).lessThan(refDate);
        expect(date).greaterThan(new Date());
      }));
    });
```

@Shinigami92 is this something you want me to do?

2022-01-23 15:55 UTC, pkuczynski commented on test/date.spec.ts
> +      expect(date).greaterThan(new Date());
45 years is a pretty long time for a js package ;) This test was like this before, so changing it would not be related to his PR, right?

Let me know what you want me to do about it...

2022-01-23 15:58 UTC, pkuczynski commented on test/date.spec.ts
> +      const date = faker.date.recent(days, refDate.toJSON());
```js
const date = new Date();
console.log(date.toJSON(), date.toISOString())
```

produces `2022-01-23T15:57:05.546Z 2022-01-23T15:57:05.546Z`. So its the same output. `toJSON` was used before in some other tests, so I followed. But I agree `toISOString` looks more readable, so I updated with your suggestion :)

2022-01-23 16:01 UTC, Shinigami92 commented on test/date.spec.ts
> +    });
I would put the loop outside the `describe` block

2022-01-23 16:05 UTC, pkuczynski commented on test/date.spec.ts
> +    });
Why outside of the `describe`? This is a single test with two examples, so it makes sense to be wrapped into a single `describe` and loop with `it`.

2022-01-23 16:11 UTC, Shinigami92 commented on test/date.spec.ts
> +      expect(date).greaterThan(new Date());
We don't want to hold old not useful code, but just improve the project at all and make it robust
So yeah, please use a all-time stable solution :slightly_smiling_face:

2022-01-23 16:13 UTC, Shinigami92 commented on test/date.spec.ts
> +      const date = faker.date.recent(days, refDate.toJSON());
yeah, please use it in all places in this file

2022-01-23 16:54 UTC, Shinigami92 commented on test/date.spec.ts
> +    });
Ah nevermind, you are right

2022-01-23 16:56 UTC, Shinigami92 requested changes

2022-01-23 16:56 UTC, Shinigami92 commented on test/date.spec.ts
> +      expect(date).greaterThan(new Date());
Okay, only this needs to be static not and I think we are good to go with this PR :+1:

2022-01-23 18:27 UTC, pkuczynski commented on test/date.spec.ts
> +    });
I used loops now. Let me know if its any better?

2022-01-23 18:27 UTC, pkuczynski commented on test/date.spec.ts
> +      expect(date).greaterThan(new Date());
Sure. Done.

2022-01-23 18:28 UTC, pkuczynski commented on test/date.spec.ts
> +      expect(date).greaterThan(new Date());
Done!

2022-01-23 18:36 UTC, Shinigami92 approved these changes

2022-01-25 22:57 UTC, prisis commented on src/date.ts
> +      return new Date(date instanceof Date ? date : Date.parse(date));
You new to use new Date(date);  
  
if you call Date.parse('2008/03/20') it returns this 1205967600000

2022-01-25 22:57 UTC, prisis commented on src/date.ts
> +    if (date != null) {
pls use date !== null

2022-01-25 22:58 UTC, prisis commented on src/date.ts
> +    if (date != null) {
pls use date !== null

2022-01-25 23:01 UTC, prisis commented on src/date.ts
> +      return new Date(date instanceof Date ? date : Date.parse(date));
So you can make it simpler return date instanceof Date ? date : new Date(date);

2022-01-25 23:05 UTC, pkuczynski commented on src/date.ts
> +      return new Date(date instanceof Date ? date : Date.parse(date));
> You new to use new Date(date);

I am not sure what do you mean? 

```js
const date = new Date();
const date2 = new Date(date);

console.log(date.toISOString(), date2.toISOString())
=> 2022-01-25T23:01:33.558Z 2022-01-25T23:01:33.558Z
```

> if you call Date.parse('2008/03/20') it returns this 1205967600000

Yes, and? 

```js
new Date(Date.parse('2008/03/20')).toISOString()
'2008-03-20T00:00:00.000Z'
```

(assuming you are on +0 TZ)

2022-01-25 23:05 UTC, Shinigami92 commented
Maybe we should rewrite the the date tests first? #287 
I don't feel comfortable anymore cause of @prisis change requests

2022-01-25 23:06 UTC, pkuczynski commented on src/date.ts
> +    if (date != null) {
`!= null` is equivalent of `!== null && !== undefined`. Should I really change it?

2022-01-25 23:07 UTC, pkuczynski commented
> Maybe we should rewrite the the date tests first? #287
> I don't feel comfortable anymore cause of @prisis change requests

We can, but bear in mind, that those tests do not use any mocks, so not sure what kind of benefit rewrite would bring?

2022-01-25 23:11 UTC, prisis commented on src/date.ts
> +    if (date != null) {
The type says date?: string | Date -> date can be undefined|string|Date

2022-01-25 23:11 UTC, pkuczynski commented on src/date.ts
> +      return new Date(date instanceof Date ? date : Date.parse(date));
I could also do `return date instanceof Date ? date : new Date(date);`, would work pretty much the same way, right?

2022-01-25 23:17 UTC, pkuczynski commented on src/date.ts
> +    if (date != null) {
Indeed! But your comment was a bit different initially ;) I can change it no problem :)

2022-01-25 23:51 UTC, pkuczynski commented on src/date.ts
> +      return new Date(date instanceof Date ? date : Date.parse(date));
I actually can't, just checked. I need to clone the date, as some of the methods mutate it...

2022-01-26 01:18 UTC, damienwebdev commented
This PR is incomplete compared to DefinitelyTyped, see the original type constraints here:

```
date: {
            past(years?: number, refDate?: string | Date): Date;
            future(years?: number, refDate?: string | Date): Date;
            between(from: string | number | Date, to: string | Date): Date;
            recent(days?: number, refDate?: string | Date): Date;
            soon(days?: number, refDate?: string | Date): Date;
            month(options?: { abbr?: boolean; context?: boolean }): string;
            weekday(options?: { abbr?: boolean; context?: boolean }): string;
        };
``` 

Note, specifically `between` was one that I noted was incorrect.

2022-01-27 23:05 UTC, pkuczynski commented
> Note, specifically `between` was one that I noted was incorrect.

I don't think DT was correct. If `from` could be a number (that's what's missing), then `to` should also take `number`. We could possibly accept numbers if it would be a timestamp, as we pass it through `Date.parse`, but then I guess I should add some validations to ensure its really a timestamp and not some random number. Is this something you want me to do?

2022-01-28 10:41 UTC, Shinigami92 commented
Please rebase this PR when #312 was merged

2022-01-28 10:48 UTC, pkuczynski commented
> Please rebase this PR when #312 was merged

I am aware. Waiting for it. :)

2022-01-29 01:42 UTC, ST-DDT commented
> We could possibly accept numbers if it would be a timestamp, as we pass it through `Date.parse`, but then I guess I should add some validations to ensure its really a timestamp and not some random number.

Accepting numbers for the dates sounds useful. See also here https://github.com/faker-js/faker/pull/182#discussion_r794980533

I would only validate Number.isInteger. Everything else can be considered date enough.

2022-01-29 13:46 UTC, ST-DDT approved these changes

2022-02-01 19:18 UTC, Shinigami92 commented
I discussed with @pkuczynski that we will fix also the millisecond issue with `Date.parse` in this PR
See: https://discord.com/channels/929487054990110771/938146569381888010/938150659646177342

2022-02-01 20:15 UTC, pkuczynski commented
> Accepting numbers for the dates sounds useful. See also here [#182 (comment)](https://github.com/faker-js/faker/pull/182#discussion_r794980533)
> 
> I would only validate Number.isInteger as that can be considered date enough.

https://github.com/faker-js/faker/issues/394

2022-02-01 20:15 UTC, pkuczynski commented
This PR is now done and ready for review @ST-DDT @Shinigami92 @prisis

2022-02-01 20:16 UTC, Shinigami92 commented on src/date.ts
>      return newDates;
I thought this would be just something like

```ts
const dates = [];
for (let i = 0; i < num; i++) {
  dates.push(this.between(from, to));
}
return dates.sort();
```

2022-02-01 20:17 UTC, Shinigami92 commented on test/date.spec.ts
> +        default: new Date('2020-10-08T00:10:58.041Z'),
We started to name these `noArgs`, would you like to rename them?

2022-02-01 20:21 UTC, Shinigami92 requested changes

2022-02-01 20:21 UTC, Shinigami92 commented on test/date.spec.ts
>              '2021-04-21T17:11:17.711Z'
Please remove my todo 3 lines above this

2022-02-01 20:21 UTC, Shinigami92 commented on test/date.spec.ts
>              new Date('2021-04-21T17:11:17.711Z')
Please remove my todo 3 lines above this

2022-02-01 20:33 UTC, pkuczynski commented on test/date.spec.ts
> +        default: new Date('2020-10-08T00:10:58.041Z'),
sure! done.

2022-02-01 20:37 UTC, pkuczynski commented on test/date.spec.ts
>              '2021-04-21T17:11:17.711Z'
done x2

2022-02-01 20:40 UTC, pkuczynski commented on src/date.ts
>      return newDates;
Initially, I tried to make the least amount of changes, but sure, can be done as you suggested. I like it more too...

2022-02-01 22:36 UTC, ST-DDT approved these changes

2022-03-10 19:52 UTC, Shinigami92 commented
@pkuczynski This PR needs a rebase

2022-03-22 15:05 UTC, Shinigami92 requested changes

2022-03-22 15:05 UTC, Shinigami92 commented on src/date.ts
> +    if (date !== undefined) {
We want to use smart null checks, would be nice if you directly use `date != null` here so I do not need to check this line when merging #650

2022-03-22 18:46 UTC, pkuczynski commented on src/date.ts
> +  private toDate(date?: string | Date): Date {
OK, will have a look at this tomorrow :)

2022-03-23 20:46 UTC, pkuczynski commented on src/date.ts
> +    if (date !== undefined) {
Done!

2022-03-23 20:46 UTC, pkuczynski commented on src/date.ts
> +  private toDate(date?: string | Date): Date {
Done!

2022-03-23 20:53 UTC, Shinigami92 requested changes

2022-03-23 20:53 UTC, Shinigami92 commented on src/date.ts
> +};
On other places we already used the code-style using functions instead of arrow functions, so lets do here too

```suggestion
function toDate(date?: string | Date): Date {
  if (date != null) {
    return new Date(date instanceof Date ? date : Date.parse(date));
  }

  return new Date();
}
```

2022-03-23 20:53 UTC, Shinigami92 commented on src/date.ts
> +};
```suggestion
function toMilliseconds(date?: string | Date): number {
  if (date != null) {
    return date instanceof Date ? date.getTime() : Date.parse(date);
  }

  return new Date().getTime();
}
```

2022-03-23 21:23 UTC, pkuczynski commented on src/date.ts
> +};
Not a major issue, but sure, why not...

2022-03-23 21:27 UTC, pkuczynski commented
Added missing jsdoc to these new functions, after you converted them form arrow. Anything else @Shinigami92?

2022-03-23 21:29 UTC, Shinigami92 commented
> Anything else @Shinigami92?

I'm in bed now ^^
Will look tomorrow, thx for the JSDocs

2022-03-23 23:51 UTC, ST-DDT approved these changes

2022-03-24 07:22 UTC, Shinigami92 approved these changes

2022-03-24 07:28 UTC, merged