feat: introduce locale access proxy
faker-js/faker pull request #2004
Opened 2023-04-01 22:07 UTC by ST-DDT

Adds #893 

- #893 

## Changes

- Converts `faker.definitions` to a proxy that throws if `faker.definitions.category?.entry` is missing.
- Adds `faker.rawDefinitions` to access optional data

## Types

- `faker.definitions.person.first_name[0]: string`
- `faker.rawDefinitions.person?.first_name?.[0]: string | undefined`

## Usage

- `faker.helpers.arrayElement(faker.definitions.person.first_name)`
- `faker.helpers.arrayElement(faker.rawDefinitions.person?.first_name ?? ['alternatives'])`

2023-04-01 22:22 UTC, ST-DDT commented on src/locale-proxy.ts
> +    },
- [ ] Write test

2023-04-01 22:22 UTC, ST-DDT commented on src/locale-proxy.ts
> +    },
- [ ] Write test

2023-04-01 22:22 UTC, ST-DDT commented on src/locale-proxy.ts
> +    },
When is this used?

2023-04-01 22:22 UTC, ST-DDT commented on src/locale-proxy.ts
> +    },
When is this method used?

2023-04-01 22:22 UTC, ST-DDT commented on src/locale-proxy.ts
> +    },
- [ ] Write test

2023-04-01 22:22 UTC, ST-DDT commented on src/locale-proxy.ts
> +    },
- [ ] Write test

2023-04-01 22:22 UTC, ST-DDT commented on test/all_functional.spec.ts
> +    streetName: [
We should probably add `location.street_name` to our `en` locale.

2023-04-01 22:22 UTC, ST-DDT commented on test/all_functional.spec.ts
> +    streetAddress: ['fr_CH'],
This looks like an actual bug in our locale data to me.

2023-04-01 22:23 UTC, ST-DDT commented
Soft blocked by #2005

2023-04-02 06:06 UTC, matthewmayer commented on test/all_functional.spec.ts
> +    streetName: [
For methods which only have data in a small number of locales, it might be useful to be able to specify "this is 'broken' in all locales EXCEPT xx, yy and zz.

2023-04-02 06:07 UTC, matthewmayer commented on test/all_functional.spec.ts
> +    streetName: [
(i also ran into this when trying to remove the `en` county definitions, if you remove it then most locales lose their fallbacks, so you'll need to specifiy a long list of locales "except" for say en_US, en_GB, etc.)

2023-04-02 06:08 UTC, matthewmayer commented on test/faker.spec.ts
> +    it('locale definition accessability', () => {
```suggestion
    it('locale definition accessibility', () => {
```

2023-04-02 10:13 UTC, matthewmayer commented
Suppose we decide some definitions are not wanted for `en` for example we remove https://github.com/faker-js/faker/blob/next/src/locales/en/location/county.ts and it would only be available in selected locales like en_US.

What would it be replaced by? Completely remove the file? Or 
```
export default [];
```

Do we intend there for there to be a semantic difference between a missing definition and an empty array?

2023-04-02 10:31 UTC, ST-DDT commented
> What would it be replaced by? Completely remove the file? Or
> 
> ```
> export default [];
> ```

I think the `[]` is normally a good solution + a comment that the user should use a country specific variant instead.
But that would cause issues for all other locales 🤔, so maybe some dummy counties (en_US ones as they end in `County`)?

> Do we intend there for there to be a semantic difference between a missing definition and an empty array?

Yes. nullish => Missing. [] => not applicable

https://github.com/faker-js/faker/blob/109ef31da469189b123c6131bb5b9d0b3c379e8d/src/locale-proxy.ts#L70-L80

2023-04-02 10:34 UTC, ST-DDT commented on test/all_functional.spec.ts
> +    streetName: [
Maybe, but we should best do that in a different PR (and maybe make it a requisite of this one?).

2023-04-02 10:43 UTC, ST-DDT commented on test/all_functional.spec.ts
> +    streetAddress: ['fr_CH'],
Will be fixed in https://github.com/faker-js/faker/pull/2007

2023-04-02 11:00 UTC, matthewmayer requested changes
We should document this in migration guide as a breaking change, something like this:

---

Attempting to access a method where Faker has no data will now throw a `FakerError` instead of returning `undefined`. Since the majority of methods have data in at least one fallback language (e.g. English), this error is likely to only happen in two situations

1. Accessing data which is not applicable for the locale, for example Chinese does not use prefixes in names:

```js
import { faker, fakerZH_CN } from '@faker-js/faker';

faker.name.prefix() // 'Mr'
fakerZH_CN.person.prefix() // throws a FakerError
```

2. When using a custom Faker instance rather than one of the prebuilt instances.

```js
import { Faker, fakerES, es } from '@faker-js/faker';

const fakerES_nofallbacks = new Faker({
  locale: [es],
});
fakerES.music.songName() // 'I Want to Hold Your Hand' (fallback from en)
fakerES_nofallbacks.music.songName() // throws a FakerError
```

2023-04-02 11:16 UTC, Shinigami92 reviewed
Looks like there should be merged some other PRs before this to reduce the diff
Maybe mark it as draft or label on hold or whatever, so reviewers are notified again when this PR is ready again

2023-04-02 11:16 UTC, Shinigami92 commented on test/locale-proxy.spec.ts
> +        // @ts-ignore
Please use ts-expect-error instead as this would throw an error when the ts code is valid again (for whatever reason)

2023-04-02 12:37 UTC, ST-DDT commented
> We should document this in migration guide as a breaking change

Done

2023-04-02 12:37 UTC, ST-DDT commented
> Looks like there should be merged some other PRs before this to reduce the diff
> Maybe mark it as draft or label on hold or whatever, so reviewers are notified again when this PR is ready again

All other things are only soft blocking IMO/don't even exist yet and might not even get implemented anytime soon.
So there is nothing explicitly blocking this PR or what are you referring to specifically?

2023-04-02 12:52 UTC, matthewmayer requested changes

2023-04-02 12:52 UTC, matthewmayer commented on docs/guide/upgrading.md
> +These values aren't expected/useful as a fallback and potentially also violate the method's defined return type definitions (in case it doesn't return a `string`).
The first sentence is a bit confusing
* `faker.definitions` was never documented, so this feels like an internal implementation detail. The breaking changes should focus on the changes in the public API rather than the rationale.
* It's not clear if this is something specific to `faker.animal.cat()` - needs a "for example".
* I think it's useful to note that if you're using the pre-packaged Faker instances this normally doesn't affect you.

2023-04-02 13:07 UTC, ST-DDT commented on docs/guide/upgrading.md
> +These values aren't expected/useful as a fallback and potentially also violate the method's defined return type definitions (in case it doesn't return a `string`).
Applied

2023-04-02 13:10 UTC, matthewmayer requested changes

2023-04-02 13:10 UTC, matthewmayer commented on docs/guide/upgrading.md
> +::: note Hinweis
what is Hinweis?

2023-04-02 13:10 UTC, matthewmayer commented on docs/guide/upgrading.md
>  These values aren't expected/useful as a fallback and potentially also violate the method's defined return type definitions (in case it doesn't return a `string`).
hmm, think this still needs some more thought, as `animal.cat` DOES exist in `en` and DOES return a String then i think the example maybe does more harm than good. Maybe could use a completely fictional example, like `faker.animal.unicorn()` or `faker.foo.bar()`

2023-04-02 13:21 UTC, ST-DDT commented on docs/guide/upgrading.md
>  These values aren't expected/useful as a fallback and potentially also violate the method's defined return type definitions (in case it doesn't return a `string`).
Or maybe like this:

````diff
- Previously, for example when `en` doesn't have data for `animal.cat` then `faker.animal.cat()` would have returned one of `a`-`c` (`arrayElement`'s default value).
+ Previously, for example if `en` didn't have data for `animal.cat`, then `faker.animal.cat()` would have returned one of `a`-`c` (`arrayElement`'s default value).
````

2023-04-02 14:35 UTC, matthewmayer commented on docs/guide/upgrading.md
> +::: note Hinweis
I think this is German. Same s Note?

2023-04-02 14:50 UTC, ST-DDT commented on docs/guide/upgrading.md
> +::: note Hinweis
Yes, should be fixed already.

2023-04-02 14:56 UTC, matthewmayer commented on docs/guide/upgrading.md
>  These values aren't expected/useful as a fallback and potentially also violate the method's defined return type definitions (in case it doesn't return a `string`).
better

2023-04-02 14:58 UTC, matthewmayer requested changes

2023-04-02 14:58 UTC, matthewmayer commented on test/location.spec.ts
> +    t.skip('streetName');
maybe should explicitly note in the docstring for streetName that this now throws in the default `en` locale, and in most cases you should be using street() instead?

2023-04-02 17:59 UTC, ST-DDT commented on docs/guide/upgrading.md
>  These values aren't expected/useful as a fallback and potentially also violate the method's defined return type definitions (in case it doesn't return a `string`).
Changed

2023-04-04 01:31 UTC, matthewmayer commented
Maybe we should also mention that this can cause `faker.fake` to throw in certain circumstances?

2023-04-04 06:22 UTC, ST-DDT commented
> Maybe we should also mention that this can cause `faker.fake` to throw in certain circumstances?

While technically true, IMO the same is true for any other faker method.

2023-04-04 08:40 UTC, matthewmayer commented
```
import { faker, fakerZH_CN } from '@faker-js/faker';

faker.name.prefix() // 'Mr'
fakerZH_CN.person.prefix() // throws a FakerError
```

^ as far as I can see, this actually returns undefined in latest build?

2023-04-04 10:04 UTC, ST-DDT commented
> ```
> import { faker, fakerZH_CN } from '@faker-js/faker';
> 
> faker.name.prefix() // 'Mr'
> fakerZH_CN.person.prefix() // throws a FakerError
> ```
> 
> ^ as far as I can see, this actually returns undefined in latest build?

Looks like a side effect of not having https://github.com/faker-js/faker/issues/1677 yet.

- https://github.com/faker-js/faker/issues/1677

But I'm not sure whether I should add some code here to handle that case or implement that feature first.

2023-04-04 10:26 UTC, matthewmayer commented
> > ```
> > import { faker, fakerZH_CN } from '@faker-js/faker';
> > 
> > faker.name.prefix() // 'Mr'
> > fakerZH_CN.person.prefix() // throws a FakerError
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ^ as far as I can see, this actually returns undefined in latest build?
> 
> Looks like a side effect of not having #1677 yet.
> 
> * [Change file structure for gendered lists (names, prefixes etc) #1677](https://github.com/faker-js/faker/issues/1677)
> 
> But I'm not sure whether I should add some code here to handle that case or implement that feature first.

for now we could remove it or replace it with a better example. For example, Ghana doesn't have postcodes/ZIP codes. We could remove the incorrect data at https://github.com/faker-js/faker/blob/next/src/locales/en_GH/location/postcode.ts and then use the example of fakerEN_GH.location.zipCode() throwing.

2023-04-05 19:29 UTC, ST-DDT commented
> Ghana doesn't have postcodes/ZIP codes. We could remove the incorrect data at [`next`/src/locales/en_GH/location/postcode.ts](https://github.com/faker-js/faker/blob/next/src/locales/en_GH/location/postcode.ts?rgh-link-date=2023-04-04T10%3A26%3A52Z)

Please create a separate issue for that or a PR that fixes it.

---

> as far as I can see, this actually returns undefined in latest build?

Instead of dancing around the issue I think we should just address #1677 and be done with it.

2023-04-07 15:33 UTC, ST-DDT commented
Note to self: 
Restore name and address aliases.

2023-04-09 06:47 UTC, Shinigami92 commented on docs/guide/upgrading.md
> +Previously, for example if `en` didn't have data for `animal.cat`, then `faker.animal.cat()` would have returned one of `a`-`c` (`arrayElement`'s default value).
```suggestion
Previously, for example if `en` didn't have data for `animal.cat`, then `faker.animal.cat()` would have returned one of `a`, `b` or `c` (`arrayElement`'s default value).
```

2023-04-09 06:47 UTC, Shinigami92 commented on src/locale-proxy.ts
> + * Creates a proxy for LocaleDefinition that throws an error when a property is accessed that is not defined.
```suggestion
 * Creates a proxy for LocaleDefinition that throws an error if an undefined property is accessed.
```

This suggestion minimizes the doubled "that"

2023-04-09 06:47 UTC, Shinigami92 commented on src/locale-proxy.ts
> + * Creates a proxy for a category that throws an error when a property is accessed that is not defined.
```suggestion
 * Creates a proxy for a category that throws an error when accessing an undefined property.
```

2023-04-09 06:47 UTC, Shinigami92 commented on test/locale-proxy.spec.ts
> +        // @ts-expect-error
You should provide a reason for all `expect-error`s
like `// @ts-expect-error: ... reason ...`

then you should be able to remove the eslint-disable comments

2023-04-09 14:36 UTC, matthewmayer commented
> fakerZH_CN.person.prefix()

Instead of the `fakerZH_CN.person.prefix()` example (which doesn't actually throw yet) we could use the example of fakerBASE which does throw for many methods, for example:
```ts
import { faker, fakerBASE } from '@faker-js/faker';

faker.person.fullName() // 'Shelia Renner'
fakerBASE.person.fullName() // throws a FakerError
```

2023-04-13 17:55 UTC, ST-DDT commented
**Team Decision**

- We decided not to wait on #1677

2023-04-15 16:11 UTC, xDivisionByZerox commented on src/locale-proxy.ts
> +    },
May you explain why this is useful?

2023-04-15 16:11 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +    let currentDefinitions: unknown = this.faker.rawDefinitions;
Why is `helpers.fake()` allowed to bypass the proxy?

2023-04-15 16:11 UTC, xDivisionByZerox commented on test/locale-proxy.spec.ts
> +    it('should be possible to access a missing category', () => {
How is this different from the first test?

2023-04-15 16:11 UTC, xDivisionByZerox commented on src/locale-proxy.ts
> +      throw new FakerError('LocaleAccess is read-only.');
I'm not sure if this error makes sense to the user since they never directly interact with `LocalAccess`. Maybe something more generic like:

```suggestion
      throw new FakerError('Locale data set's are read-only.');
```

2023-04-15 16:11 UTC, xDivisionByZerox commented on test/locale-proxy.spec.ts
> +  const unavailable = createLocaleAccess({
Maybe scope this in the actual test case since it is only used there?
I was a bit confused when reading all test cases as I was expecting both proxies to be used.

2023-04-15 16:11 UTC, xDivisionByZerox commented on test/location.spec.ts
> +    t.skip('streetName');
We normally do not want to mention the locale-specific context in the method description. They are decoupled from each other, so making them aware of each other in the documentation doesn't make sense to me.
(You would need to remember to update the JSDocs for the function when you refactor the locale data set)

2023-04-15 16:14 UTC, xDivisionByZerox commented on src/locale-proxy.ts
> +export type LocaleAccess = Readonly<{
The file name is called `locale-proxy`, so why call it `LocaleAccess` instead of `LocaleProxy`?

2023-04-15 16:51 UTC, Shinigami92 commented on test/locale-proxy.spec.ts
> +    it('should be possible to access a missing category', () => {
<img src="https://user-images.githubusercontent.com/7195563/232238935-e457ae56-4567-4184-9f7f-245698ef0455.png" width="300px"/>

`expect(locale.category).toBeDefined()` checks for `!== undefined` where as `expect('category' in locale).toBe(true)` just checks if the key is defined

2023-04-15 16:53 UTC, Shinigami92 commented on src/locale-proxy.ts
> +function createCategoryProxy<T extends Record<string | symbol, unknown>>(
How about name `T` to `CategoryData`?

2023-04-15 17:32 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    let currentDefinitions: unknown = this.faker.rawDefinitions;
Because it should not throw an error. Because it also has to check the module method and has a custom error message.

2023-04-15 17:45 UTC, ST-DDT commented on src/locale-proxy.ts
> +    },
This can be used to check if the locale data are present without risk getting an error.
The category is proxied so it is always there.

2023-04-15 18:02 UTC, Shinigami92 commented on test/faker.spec.ts
> +import { Faker, faker } from '../src';
:eyes: :thinking:

2023-04-15 18:37 UTC, ST-DDT commented on test/faker.spec.ts
> +import { Faker, faker } from '../src';
```suggestion
import { faker, Faker} from '../src';
```

2023-04-16 11:40 UTC, xDivisionByZerox submitted a review, later dismissed

2023-04-16 11:41 UTC, Shinigami92 submitted a review, later dismissed

2023-04-16 16:40 UTC, Shinigami92 commented
@matthewmayer you requested changes with the blocking version of a PR review
please re-evaluate your request/review

2023-04-16 16:42 UTC, matthewmayer commented
The second example in the upgrading guide (Chinese prefix) is still incorrect as it does not throw. Suggest replacing with a fakerBASE example.

2023-04-20 20:31 UTC, ST-DDT commented on src/locale-proxy.ts
> +      // Categories are always present (proxied), that why we return true.
```suggestion
      // Categories are always present (proxied), that's why we return true.
```

2023-04-20 20:31 UTC, ST-DDT commented on test/locale-proxy.spec.ts
> +        // @ts-expect-error LocaleAccess is read-only.
```suggestion
        // @ts-expect-error: LocaleProxy is read-only.
```

2023-04-20 20:31 UTC, ST-DDT commented on test/locale-proxy.spec.ts
> +        // @ts-expect-error LocaleAccess is read-only.
```suggestion
        // @ts-expect-error: LocaleProxy is read-only.
```

2023-04-20 20:31 UTC, ST-DDT commented on test/locale-proxy.spec.ts
> +        // @ts-expect-error LocaleAccess is read-only.
```suggestion
        // @ts-expect-error: LocaleProxy is read-only.
```

2023-04-20 20:31 UTC, ST-DDT commented on test/locale-proxy.spec.ts
> +        // @ts-expect-error LocaleAccess is read-only.
```suggestion
        // @ts-expect-error: LocaleProxy is read-only.
```

2023-04-20 20:31 UTC, ST-DDT commented on test/locale-proxy.spec.ts
> +        // @ts-expect-error LocaleAccess is read-only.
```suggestion
        // @ts-expect-error: LocaleProxy is read-only.
```

2023-04-20 20:31 UTC, ST-DDT commented on test/locale-proxy.spec.ts
> +        // @ts-expect-error LocaleAccess is read-only.
```suggestion
        // @ts-expect-error: LocaleProxy is read-only.
```

2023-04-20 20:31 UTC, ST-DDT commented on test/locale-proxy.spec.ts
> +        // @ts-expect-error LocaleAccess is read-only.
```suggestion
        // @ts-expect-error: LocaleProxy is read-only.
```

2023-04-20 20:31 UTC, ST-DDT commented on test/locale-proxy.spec.ts
> +        // @ts-expect-error LocaleAccess is read-only.
```suggestion
        // @ts-expect-error: LocaleProxy is read-only.
```

2023-04-20 20:31 UTC, ST-DDT commented on test/locale-proxy.spec.ts
> +        // @ts-expect-error LocaleAccess is read-only.
```suggestion
        // @ts-expect-error: LocaleProxy is read-only.
```

2023-04-20 20:31 UTC, ST-DDT commented on test/locale-proxy.spec.ts
> +        // @ts-expect-error LocaleAccess is read-only.
```suggestion
        // @ts-expect-error: LocaleProxy is read-only.
```

2023-04-20 20:50 UTC, ST-DDT commented
Blocked by #2045 regarding throwing for `fakerZH_CN.person.prefix()` in the migration guide.

2023-04-20 21:36 UTC, xDivisionByZerox commented on src/locale-proxy.ts
> +      return value != null && (!Array.isArray(value) || value.length !== 0);
What about nested object definitions? Is the value `{}` expected to return `true`? If so I would expect `[]` to return `true` as well.

2023-04-20 21:36 UTC, xDivisionByZerox commented on src/locale-proxy.ts
> +      } else {
Same here. What about `{}`?

2023-04-20 22:25 UTC, ST-DDT commented on src/locale-proxy.ts
> +      return value != null && (!Array.isArray(value) || value.length !== 0);
We dont have those yet, so we havent decided on them either.

2023-04-21 18:04 UTC, ST-DDT commented on src/locale-proxy.ts
> +      return value != null && (!Array.isArray(value) || value.length !== 0);
Then we would also have to decide on `''` and `0` and other special keys.
Or is maybe `[]` a bad value for explicitly absent?

2023-04-21 19:09 UTC, xDivisionByZerox commented on src/locale-proxy.ts
> +      return value != null && (!Array.isArray(value) || value.length !== 0);
> Would null be any better?

I mean that's literally what `null` is for. From the [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/null):

> The `null` value represents the intentional absence of any object value.

2023-04-21 19:31 UTC, Shinigami92 commented on src/locale-proxy.ts
> +      return value != null && (!Array.isArray(value) || value.length !== 0);
@xDivisionByZerox That is a really good point :+1: 

However, can we please do this in a separate PR?

2023-04-21 19:53 UTC, Shinigami92 commented on src/locale-proxy.ts
> +      return value != null && (!Array.isArray(value) || value.length !== 0);
@xDivisionByZerox just as a side note, if we want to use `null` for such cases, we need to (internally) support [this](https://github.com/faker-js/faker/pull/2045/files#diff-3f6b4fc424ba2cedcbf5f612ba256d248f0c05f46314eed1dfa81590bcd429fdR807-R812) `null` check also in the future (only at runtime) and the TODO comment would be obsolete

But yes, I'm fine with that and this would get an agree if we would have a "needs-decision"

2023-04-21 20:47 UTC, ST-DDT commented on src/locale-proxy.ts
> +      return value != null && (!Array.isArray(value) || value.length !== 0);
Extracted into: https://github.com/faker-js/faker/pull/2078

2023-04-21 20:50 UTC, Shinigami92 commented on src/locale-proxy.ts
> +      return value != null && (!Array.isArray(value) || value.length !== 0);
nevermind, seems I have not understand the PR in the first place :facepalm: 
ignore my last comment

2023-04-21 20:55 UTC, ST-DDT commented
Blocked by https://github.com/faker-js/faker/pull/2078

2023-04-23 11:03 UTC, xDivisionByZerox commented on src/locale-proxy.ts
> +      } else if (value == null) {
Since we now explicitly check for `null` this check should explicitly be `value === undefined`. 
`value == null` basically is a "shorthand" for `value === undefined || value === null`. It does NOT check for falsely values.

2023-04-23 11:03 UTC, xDivisionByZerox commented on test/all_functional.spec.ts
> -    streetName: [
Why are those no longer broken`?

2023-04-23 11:19 UTC, ST-DDT commented on src/locale-proxy.ts
> +      } else if (value == null) {
```suggestion
      } else if (value === undefined) {
```

2023-04-23 11:28 UTC, ST-DDT commented
Ready to review.

2023-04-23 11:43 UTC, Shinigami92 commented on src/locale-proxy.ts
> +      if (value === null) {
Can we please add test cases to cover this tripple equals null check as well as the tripple equals undefined check below?
That prevents regression and serves as stability so we can point to the test why this tripple equals are necessary

2023-04-23 11:44 UTC, xDivisionByZerox approved these changes

2023-04-23 11:49 UTC, xDivisionByZerox commented on src/locale-proxy.ts
> +      if (value === null) {
Is that not covered by: https://github.com/faker-js/faker/blob/f915d49505f36fa74e6e3045887d9cd407fe67dc/test/locale-proxy.spec.ts#L111-L123

2023-04-23 11:55 UTC, Shinigami92 commented on src/locale-proxy.ts
> +      if (value === null) {
I checked the last two newest commits by @ST-DDT and nothing new were added in terms of test
So somehow it is not covered or nothing subjective have changed to the behavior of the code

2023-04-23 12:10 UTC, ST-DDT commented on src/locale-proxy.ts
> +      if (value === null) {
It is true that nothing substatial has changed since being labelled as on hold previously.
The existing tests should cover all cases AFAICT. Please check the test spec if there are cases that are not or insufficiently covered.

2023-04-23 12:40 UTC, Shinigami92 commented on src/locale-proxy.ts
> +      if (value === null) {
`if (value === null)` on line 72 was already there, so the else-if in line 77 did not get the case for having value === null in any case
thats why everything is working 👍

2023-04-23 12:40 UTC, Shinigami92 approved these changes

2023-04-23 13:03 UTC, matthewmayer requested changes

2023-04-23 13:03 UTC, matthewmayer commented on docs/guide/upgrading.md
> +
suggest removing this example as it doesn't work for gendered data yet.

2023-04-23 13:09 UTC, ST-DDT commented on docs/guide/upgrading.md
> +
I ran the code this morning and it did throw an error due to the arrayElement PR.

2023-04-23 14:11 UTC, matthewmayer commented on docs/guide/upgrading.md
> +
I think it's a confusing example though as it shows a different error to what would be expected

Better to use fakerBASE or we could add a second example later using the en_HK with missing postcodes?

2023-04-23 14:12 UTC, matthewmayer commented on docs/guide/upgrading.md
> +
Anyway I'll remove my blocking review if you want to merge without changing this

2023-04-23 14:13 UTC, matthewmayer approved these changes

2023-04-23 16:50 UTC, ST-DDT commented on docs/guide/upgrading.md
> +
I'll merge this, now so it unblocks the release progress, but I will open an issue to switch the example once en_HK is merged.

2023-04-23 16:51 UTC, merged