docs(image): explain deprecation of category methods
faker-js/faker pull request #2040
Opened 2023-04-12 14:57 UTC by matthewmayer

fix #2019

2023-04-12 15:30 UTC, xDivisionByZerox requested changes
Please update the runtime warning messages in the `proposed` properties as well.
Otherwise looks good.

2023-04-12 16:03 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image.urlLoremFlickr({category: 'abstract'})` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```suggestion
   * @deprecated Use `faker.image.urlLoremFlickr({ category: 'abstract' })` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```

2023-04-12 16:03 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image.urlLoremFlickr({category: 'animals'})` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```suggestion
   * @deprecated Use `faker.image.urlLoremFlickr({ category: 'animals' })` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```

2023-04-12 16:03 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image.urlLoremFlickr({category: 'business'})` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```suggestion
   * @deprecated Use `faker.image.urlLoremFlickr({ category: 'business' })` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```

2023-04-12 16:03 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image.urlLoremFlickr({category: 'cats'})` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```suggestion
   * @deprecated Use `faker.image.urlLoremFlickr({ category: 'cats' })` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```

2023-04-12 16:03 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image.urlLoremFlickr({category: 'city'})` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```suggestion
   * @deprecated Use `faker.image.urlLoremFlickr({ category: 'city' })` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```

2023-04-12 16:03 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image.urlLoremFlickr({category: 'food'})` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```suggestion
   * @deprecated Use `faker.image.urlLoremFlickr({ category: 'food' })` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```

2023-04-12 16:03 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image.urlLoremFlickr({category: 'nightlife'})` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```suggestion
   * @deprecated Use `faker.image.urlLoremFlickr({ category: 'nightlife' })` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```

2023-04-12 16:03 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image.urlLoremFlickr({category: 'fashion'})` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```suggestion
   * @deprecated Use `faker.image.urlLoremFlickr({ category: 'fashion' })` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```

2023-04-12 16:03 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image.urlLoremFlickr({category: 'people'})` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```suggestion
   * @deprecated Use `faker.image.urlLoremFlickr({ category: 'people' })` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```

2023-04-12 16:03 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image.urlLoremFlickr({category: 'nature'})` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```suggestion
   * @deprecated Use `faker.image.urlLoremFlickr({ category: 'nature' })` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```

2023-04-12 16:03 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image.urlLoremFlickr({category: 'sports'})` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```suggestion
   * @deprecated Use `faker.image.urlLoremFlickr({ category: 'sports' })` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```

2023-04-12 16:03 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image.urlLoremFlickr({category: 'technics'})` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```suggestion
   * @deprecated Use `faker.image.urlLoremFlickr({ category: 'technics' })` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```

2023-04-12 16:03 UTC, Shinigami92 commented on src/modules/image/index.ts
> +   * @deprecated Use `faker.image.urlLoremFlickr({category: 'transport'})` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```suggestion
   * @deprecated Use `faker.image.urlLoremFlickr({ category: 'transport' })` if you want an image from LoremFlickr in the correct category, or `faker.image.url()` if you just want any image.
```

2023-04-13 21:39 UTC, xDivisionByZerox approved these changes

2023-04-16 14:09 UTC, ST-DDT approved these changes

2023-04-17 08:29 UTC, merged