feat(datatype): reimplement datatype module
faker-js/faker pull request #2044
Opened 2023-04-13 20:57 UTC by Shinigami92

2023-04-13 21:11 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +        value: () => Promise.resolve(),
If the purpose of the method is `typeof value === 'function'`, then this is unnecessary.
If you think differently please explain why this is more useful than returing a null, string, number or even an empty object.

2023-04-13 21:11 UTC, ST-DDT commented on src/modules/datatype/index.ts
> + * This module provides methods to generate values that can be checked against JavaScript's `typeof` operator.
This is redundant with the sentence above. Either exand on this by listing them/their associated methods or remove it.

2023-04-13 21:16 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +        value: () => Promise.resolve(),
In a different method chose `new Date()`. Why not return `object` or `any`/`unknown`.

2023-04-13 21:19 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +        value: () => Promise.resolve(),
You could litterally implement this via
`return helpers.objectValue(this)`.

2023-04-13 21:26 UTC, ST-DDT commented
Also maybe dont sort the methods for this PR to reduce the diff.
Separate PR.

2023-04-13 21:40 UTC, Shinigami92 commented on src/modules/datatype/index.ts
> +        value: () => Promise.resolve(),
re-check pls

2023-04-13 21:41 UTC, Shinigami92 commented on src/modules/datatype/index.ts
> + * This module provides methods to generate values that can be checked against JavaScript's `typeof` operator.
re-check pls (added below line 9)

2023-04-13 21:42 UTC, Shinigami92 commented
> Also maybe dont sort the methods for this PR to reduce the diff. Separate PR.

This is done explicitly
We have two sections
1. the typeof in sorted order
2. the old deprecated methods (order not changed)

I suggest to just read/review the new code above the `// deprecated methods` comment
everything below did not change and was not touched

2023-04-14 01:59 UTC, matthewmayer requested changes
Any of the methods which previously had a working `options` parameter in 7.4 but are now ignored e.g. array, number should be documented in the Upgrading to v8 guide as breaking changes.

2023-04-14 10:10 UTC, ST-DDT requested changes

2023-04-14 10:10 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +   * Returns a value that will result in `true` when checked against JavaScript's `typeof value === 'boolean'` operator.
Should we add a hint that this method can also be used for generating booleans as there is no specific boolean module?

2023-04-14 10:10 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +   * The probability is limited to two decimal places.
Is this still true?

2023-04-14 10:10 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +        },
This is the same as returning `undefined` / the `undefined` method reference.

2023-04-14 10:10 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +          ](),
Maybe add a todo comment here, that this list the methods explicitly to avoid the deprecated ones and this should be simplified in v9 to `objectValues(this)()`

2023-04-14 10:10 UTC, ST-DDT commented on test/all_functional.spec.ts
> +  'datatype',
Why do you ignore the whole module? Instead of only object and undefined?

2023-04-14 10:10 UTC, ST-DDT commented on test/datatype.spec.ts
> +      describe('function', () => {
This can probably collapsed into a describe.each or some kind of for-loop.

2023-04-14 11:20 UTC, Shinigami92 commented on src/modules/datatype/index.ts
> +   * Returns a value that will result in `true` when checked against JavaScript's `typeof value === 'boolean'` operator.
I think this is implicit + it was the previous way anyway, so we dont need to "point" folks to that

2023-04-14 11:23 UTC, Shinigami92 commented on test/all_functional.spec.ts
> +  'datatype',
because it failed with other datatype methods like number -> NaN as well

2023-04-14 11:24 UTC, Shinigami92 commented
For some of the suggestions, lets talk tomorrow when we do the v8.0 dev-weekend

2023-04-14 11:28 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +   * Returns a value that will result in `true` when checked against JavaScript's `typeof value === 'boolean'` operator.
It is going to be the only method that will take arguments in the whole module, so surely this does more than the other methods?!

2023-04-14 11:28 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +   * The probability is limited to two decimal places.
float() without arguments uses max precision floats don't it?

2023-04-14 11:30 UTC, Shinigami92 commented on src/modules/datatype/index.ts
> +   * Returns a value that will result in `true` when checked against JavaScript's `typeof value === 'boolean'` operator.
understood
so I will not point to the method just because, but I will mention that for boolean you have option

2023-04-14 11:32 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +        value: () => Promise.resolve(),
This still doesn't explain what is special about `Promise.resolve()`.

2023-04-14 11:34 UTC, matthewmayer requested changes

2023-04-14 11:34 UTC, matthewmayer commented on docs/guide/upgrading.md
> +### Behavior of `faker.datatype` module has changed, as has the scope for which it is to be used
these are hard-breaking changes (ie if you were using the old methods, you need to change your code to get the same behavior) so should be in the top Breaking Changes section

2023-04-14 15:31 UTC, ST-DDT commented on docs/guide/upgrading.md
> +### Behavior of `faker.datatype` module has changed, as has the scope for which it is to be used
Should we support the old options during the deprecation period?

2023-04-14 16:49 UTC, matthewmayer commented on docs/guide/upgrading.md
> +### Behavior of `faker.datatype` module has changed, as has the scope for which it is to be used
I think given in faker6 to faker7 various methods were moved from faker.helpers to faker.datatype it's bad if they break again from faker7 to faker8.

2023-04-14 17:11 UTC, Shinigami92 commented on docs/guide/upgrading.md
> +### Behavior of `faker.datatype` module has changed, as has the scope for which it is to be used
> Should we retain support the old options during the deprecation period?

I would like to vote against this (still open for discussion, it's my personal opinion), because this way we make the intend more clear and tell the user to actually move to the specific module

> these are hard-breaking changes (ie if you were using the old methods, you need to change your code to get the same behavior) so should be in the top Breaking Changes section

good hint :+1: will do

2023-04-15 14:22 UTC, matthewmayer commented
The new implementations of these methods seem so different from the old methods that it feels confusing to keep them with the same names. 

I feel if someone proposed "a method which returns a Number, but it could be NaN or POSITIVE_INFINITY so its only useful for checking with typeof" as a new issue it would be tagged as "waiting for user interest". So does it make sense to implement these very limited methods?

2023-04-15 15:54 UTC, Shinigami92 commented
@ST-DDT in the meeting notes we also had defined `unknown(): any of the datatype methods (TS "unknown")`
Can we outsource this to an issue and mark as `awaiting for user interest`?

2023-04-16 09:27 UTC, Shinigami92 commented on src/modules/datatype/index.ts
> +        value: () => Promise.resolve(),
I enhanced the jsdoc a bit to make more clear that the return value of such a function can be empty, throw an error, return a promise or return a value of any type.
This is helpful when you e.g. just want to generate a function that will be passed to a generic function accepting a callback.
That way within a randomized deterministic test case you will find out via faker that you miss a case for e.g. handling promises and or correctly handle error cases if such a callback would throw something.

I know that users out there should cover such cases on specific base, but for example if you come in to a not so good maintained project and introduce faker, you could e.g. start with such a generic way and from there you can then find out e.g. "oh we missed to handle promise cases".

2023-04-16 09:30 UTC, Shinigami92 commented on src/modules/datatype/index.ts
> +        },
We should not try to be efficient and fancy here and indirectly knowing that the undefined case surprisingly covers the empty/void case
while reading the internal code it is more clear that we have several cases we want to cover:
1. void -- the simpliest case of all
2. an "unknown" whatever return value
3. an Error
4. a Promise that is successful
5. a Promise that is not successful

2023-04-16 09:41 UTC, Shinigami92 commented on test/all_functional.spec.ts
> +  'datatype',
we added a comment to document why we exclude the whole datatype module

2023-04-16 09:48 UTC, Shinigami92 commented
> The new implementations of these methods seem so different from the old methods that it feels confusing to keep them with the same names.

We know that, but _sadly_ there is no other option as these methods are explicitly named for what the `typeof` operator supports

> I feel if someone proposed "a method which returns a Number, but it could be NaN or POSITIVE_INFINITY so its only useful for checking with typeof" as a new issue it would be tagged as "waiting for user interest". So does it make sense to implement these very limited methods if we dont know if users actually need them?

Yes this was a team decision on 13. April 2023.

Reasons:
- We dont want to drop the datatype module because we could not find another place for `boolean`
- Then we came up with the idea to make the datatype module valuable for the `typeof` operator

Now it is possible to e.g. use `faker.datatype.number()` to pass to a function that just accepts a `number`.
The test can then check that anykind of number, so also NaN or Infinity, are handled correctly by that function.
This should be mostly (or even only) the case when e.g. you go into a already existing project and introduce faker. Then you can write generic tests with these datatype methods and talk to you project lead and tell them to enhance their error handling or TypeScript definitions (if they are using TypeScript at all).

2023-04-16 09:51 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +        },
What about a promise that is not yet resolved?

2023-04-16 10:19 UTC, matthewmayer commented
Wouldn't it make the migration path much easier if new names were used for the new methods

For example
faker.datatype.numberType instead of faker.datatype.number?

2023-04-16 10:32 UTC, ST-DDT requested changes
I also think, that we might want to move this to v9.0 to let the deprecation sink in for one mayor version, before replacing the methods from one version to another with completely different ones.
(or use new method names as @matthewmayer suggested)

2023-04-16 10:32 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +  function(): () => unknown {
I think we have to put more thought into this as this isn't really usable with TS.

![grafik](https://user-images.githubusercontent.com/1579362/232291310-73a2e36a-c352-455a-a9d8-5ae463431c91.png)

````ts
function test() {
  toTest(faker.datatype.function()); // Type-Error
  nestedCall(faker.datatype.unknown()); // Type-Error
}

function toTest(fn: () => number): number {
  return nestedCall(fn());
}

function nestedCall(value: number): number {
  return value + 1;
}
````

We should either reduce this to the most minimal viable implementation: `return () => ?`
Or give this more options, such as should this throw?
What do I expect as result? Passing the result of this method as an argument violates the genericity of the definition and thus behaves the same as using `unknown`.
This might be a viable test case for plain JS applications, but even then the utility of that seems pretty limited to me.
I assume it most cases passing `faker.datatype.number` as a reference would produce better results.

I could imagine that something like this might produce more useful results:

````ts
function<ResultType = unknown, PromiseWrapped extends boolean>( options: {
  errorRate: number;
  returnType: `${ResultType}`
  promise: PromiseWrapped 
}): PromiseWrapped extends true ? Promise<ResultType> : ResultType;
````

But since this is what I came up with in just an hour, there might be more options that should be considered.
For now, we should stick to the minimal implementation or omit the method entirely with some docs stating for function you should use the other methods as reference.
That way we follow the "Open (for extensions and) Closed (for modifications)" principle and breaking any workflows that depend on the temporary behavior.

2023-04-16 10:56 UTC, Shinigami92 commented on src/modules/datatype/index.ts
> +        },
> What about a promise that is not yet resolved?

Interesting :thinking:

It looks like `new Promise(() => {})` does return immediately,
so we need a sleep like this
```ts
new Promise((resolve) => {
  setTimeout(resolve, 2**31 - 1);
});
```

_side note_: https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#maximum_delay_value
`setTimeout` has a max delay #TIL

2024-02-17 09:40 UTC, Shinigami92 commented
I'm thinking about to move this to v10, because in v9 the deprecated methods will be removed. In v10 we could be sure that all users are moved away from these old methods, because they where not available at all anymore.

Another idea would be to define a new module that makes the new aim more clear, like `faker.typeof.number`, `faker.typeof.string` and so on :thinking:

2024-02-17 09:52 UTC, matthewmayer commented
I would be in favour of a different module name.

2024-02-17 13:18 UTC, matthewmayer commented
Although I think "typeof" is a reserved word so it would have to be something else.

2024-02-17 15:19 UTC, Shinigami92 commented
> Although I think "typeof" is a reserved word so it would have to be something else.

If I would try to, TS shows:
`'typeof' is not allowed as a variable declaration name. ts(1389)`

2024-02-21 13:44 UTC, matthewmayer requested changes

2024-02-21 13:44 UTC, matthewmayer commented on src/modules/datatype/index.ts
> +      { weight: 1, value: () => Number.POSITIVE_INFINITY },
Why two positive infinities?

2024-02-21 13:45 UTC, matthewmayer commented
How about faker.type.*

2024-03-24 15:16 UTC, ST-DDT commented
This is probably no longer blocked.

2024-05-30 16:01 UTC, closed without merging