refactor(helpers): remove default value from arrayElement
faker-js/faker pull request #2045
Opened 2023-04-13 22:52 UTC by xDivisionByZerox

Closes #219.

2023-04-14 02:05 UTC, matthewmayer requested changes

2023-04-14 02:05 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +   * @throws If array is empty.
this doesn't show up in the generated API documentation. Either a note about throwing should be added to the main description, or the HTML template should be modified to automatically show `@throws` information.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/152770/231923066-7fa61094-ed0f-422f-bbb1-3567b29dc27c.png">

2023-04-14 02:05 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +      throw new FakerError('Cannot get value from empty set.');
maybe "array" instead of "set"?

2023-04-14 02:08 UTC, matthewmayer requested changes
regression:
```
faker.helpers.arrayElement(["foo","bar",undefined]) 
```
now throws an error 1/3 of the time.

2023-04-14 07:05 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +   * @throws If array is empty.
If this is the case, it is a bigger problem and not related to this PR.
Other methods already have the `@thorws` tag. For example:
- [datatype.number](https://github.com/faker-js/faker/blob/5aa51d8de46e3d9cfbe84ebf7c6130fb13c67846/src/modules/datatype/index.ts#L36)
- [finance.iban](https://github.com/faker-js/faker/blob/5aa51d8de46e3d9cfbe84ebf7c6130fb13c67846/src/modules/finance/index.ts#L960)
- [helpers.fromRegExp](https://github.com/faker-js/faker/blob/5aa51d8de46e3d9cfbe84ebf7c6130fb13c67846/src/modules/helpers/index.ts#L352-L353)

As per our [contribution guidelines (section JSDocs)](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md#jsdocs):

> If a function can throw an error (FakerError) you have to include the `@throws` tag with an explanation when an error could be thrown

2023-04-14 07:18 UTC, Shinigami92 commented
> regression:
> 
> ```
> faker.helpers.arrayElement(["foo","bar",undefined]) 
> ```
> 
> now throws an error 1/3 of the time.

Interesting case we might now have thought about

I think we can use something like this:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/7195563/231971956-055358fb-f303-41b0-b6f1-b2ea4e852ca9.png">

2023-04-14 07:26 UTC, xDivisionByZerox commented
> I think we can use something like this:

Or we simply check the array length on input and throw? Why get that complex...^^

2023-04-14 07:36 UTC, Shinigami92 commented
> > I think we can use something like this:
> 
> Or we simply check the array length on input and throw? Why get that complex...^^
> 
> If someone provides an array with `undefined` this will be inferred by the generic and correctly type the return type.

Because of 

https://github.com/faker-js/faker/blob/99c16e40c88ae6788eb2bf942fd62c035cbc707e/src/modules/helpers/index.ts#L801-L803

2023-04-14 09:35 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * @throws If array is empty.
Created a new issue for that: https://github.com/faker-js/faker/issues/2048

2023-04-14 09:44 UTC, matthewmayer commented
> > > I think we can use something like this:
> > 
> > 
> > Or we simply check the array length on input and throw? Why get that complex...^^
> > If someone provides an array with `undefined` this will be inferred by the generic and correctly type the return type.
> 
> Because of
> 
> https://github.com/faker-js/faker/blob/99c16e40c88ae6788eb2bf942fd62c035cbc707e/src/modules/helpers/index.ts#L801-L803

can't  you just change the condition for throwing from
```js
const value = array[index];
    if (value === undefined) {
      throw new FakerError('Cannot get value from empty set.');
    }
```

to
```js
    if (array.length === 0) {
      throw new FakerError('Cannot get value from empty set.');
    }
const value = array[index];
```

2023-04-14 09:46 UTC, matthewmayer commented
To clarify, in Faker 7, the behavior was:

```
> faker.helpers.arrayElement([])
undefined
> faker.helpers.arrayElement()
'b'
```

Do we want it to now throw in both these cases (array is empty, array is undefined)?

2023-04-14 10:00 UTC, xDivisionByZerox commented
> can't you just change the condition for throwing from
> 
> ```js
> const value = array[index];
>     if (value === undefined) {
>       throw new FakerError('Cannot get value from empty set.');
>     }
> ```
> 
> to
> 
> ```js
>     if (array.length === 0) {
>       throw new FakerError('Cannot get value from empty set.');
>     }
> const value = array[index];
> ```

Yes and no. This is precisely what I was stating [in my previous comment](https://github.com/faker-js/faker/pull/2045#issuecomment-1508052355). But we have to keep in n mind that this will cause trouble in later versions if we decide to activate more strict typescript features. I'm talking about the [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) rule.

> Do we want it to now throw in both these cases (array is empty, array is undefined)?

Yes, we do want that.
Providing no argument at all doesn't make sense to me. The method is in the helper module so the general consent of "every function has to be callable without arguments" does **NOT** apply here.
If you provide an empty array, typescript correctly infers that the return type is `never`, which basically means "This function never returns anything". This is correct as it throws an error instead f returning.

2023-04-14 11:09 UTC, matthewmayer commented
Whether or not it makes sense, passing an undefined array happens in existing places in the code at the moment and ends up with "b". 

We should add tests for various cases:

Undefined array
Empty array
Array which contains undefined as a possible value

2023-04-14 11:27 UTC, Shinigami92 commented
> Whether or not it makes sense, passing an undefined array happens in existing places in the code at the moment and ends up with "b".
> 
> We should add tests for various cases:
> 
> Undefined array Empty array Array which contains undefined as a possible value

I highly assume that this is the reason why this PR is in "draft", but thanks for also thinking about it 🙂

2023-04-14 13:07 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +      throw new FakerError('Cannot get value from empty set.');
This method (and thus the error) is also used for:
- helpers.objectValues => object input
- helpers.objectKey => object input
- fake => RegExp input

That's why I decided to use "set". I would be weird to get "empty "

2023-04-14 14:10 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +      throw new FakerError('Cannot get value from empty set.');
You could catch and rethrow a more appropriate error in those cases.

2023-04-14 14:28 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +      throw new FakerError('Cannot get value from empty set.');
I don't really want to wrap every method with a try-catch-block if I'm honest. Non-centralized error handling is kind of a code smell for me...

2023-04-14 14:32 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +      throw new FakerError('Cannot get value from empty set.');
Well I mean that's what we are asking consumers of this method to do now right? 😀

I feel having helpful error messages outweighs making the implementation slightly messier.

2023-04-14 14:44 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +      throw new FakerError('Cannot get value from empty set.');
I have to strongly disagree. Even if we try-catch-rethrow, we would have to evaluate that the error is actually the one from `arrayElement`. Else the entire concept of having helpful error messages would be obsolete if we override a fundamental node error with "no empty object allowed". We would need to do that "everywhere". You might know that `arrayElement` is the basic building block for most localized data generation. So yeah, that's a lot of places...

2023-04-14 15:01 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +      throw new FakerError('Cannot get value from empty set.');
don't have to rethrow, could have a guard at the top of the `faker.helpers.objectKey` like:
```
objectKey<T extends Record<string, unknown>>(object: T): keyof T {
    const array: Array<keyof T> = Object.keys(object);
    if (array.length===0) {
       throw new FakerError('Cannot get key from empty object.');
   }
    return this.arrayElement(array);
  }
```

2023-04-14 15:04 UTC, matthewmayer requested changes

2023-04-14 15:04 UTC, matthewmayer commented on docs/guide/upgrading.md
> +
i think we should have an example of how to fix it if you were reliant on the old behavior.

Something like:
```js
let post = {}
post.tags = faker.helpers.arrayElements(["dogs","cats","fish","horses","sheep"],{min:0, max:3})
post.featuredTag = faker.helpers.arrayElement(post.tags)
```

```js
let post = {}
post.tags = faker.helpers.arrayElements(["dogs","cats","fish","horses","sheep"],{min:0, max:3})
post.featuredTag = post.tags.length===0 ? undefined : faker.helpers.arrayElement(post.tags)
```

2023-04-16 11:56 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +      throw new FakerError('Cannot get value from empty set.');
maybe use dataset instead of array or set to distinguish more from JS Set

2023-04-16 11:58 UTC, Shinigami92 commented on test/location.spec.ts
> +    // todo - missing locale data
vitest has a `t.todo`, has it?
Otherwise I would suggest to follow our TODO pattern, so it is more easy to find when searching TODOs through the whole project

2023-04-16 13:11 UTC, ST-DDT commented on docs/guide/upgrading.md
> +
Or we define an overload with an option: { allowEmpty: true } that adds `undefined` to the results.

2023-04-16 16:40 UTC, Shinigami92 commented
@matthewmayer you requested changes with the blocking version of a PR review
please re-evaluate your request/review

2023-04-16 16:44 UTC, matthewmayer requested changes, later dismissed

2023-04-16 16:44 UTC, matthewmayer commented on docs/guide/upgrading.md
> +The methods `faker.helper.arrayElement` and `faker.helper.arrayElements` previously defaulted the `array` argument to a simply string array if non was provided.
simply to simple, non to none

2023-04-16 16:44 UTC, matthewmayer commented on docs/guide/upgrading.md
> +// `featureTag` will will be typed as `string` but could actually be `undefined`
Double "will"

2023-04-16 16:44 UTC, matthewmayer commented on docs/guide/upgrading.md
> +The methods `faker.helper.arrayElement` and `faker.helper.arrayElements` previously defaulted the `array` argument to a simply string array if non was provided.
helper to helpers

2023-04-16 16:45 UTC, matthewmayer commented
Also I feel it still needs more tests. There is no test that actually tests the removal of the default value, or handling arrays containing undefined.

2023-04-16 16:48 UTC, Shinigami92 commented on docs/guide/upgrading.md
> +The methods `faker.helper.arrayElement` and `faker.helper.arrayElements` previously defaulted the `array` argument to a simply string array if non was provided.
```suggestion
The methods `faker.helper.arrayElement` and `faker.helper.arrayElements` previously defaulted the `array` argument to a simple string array if none was provided.
```

2023-04-16 16:48 UTC, Shinigami92 commented on docs/guide/upgrading.md
> +// `featureTag` will will be typed as `string` but could actually be `undefined`
```suggestion
// `featureTag` will be typed as `string` but could actually be `undefined`
```

2023-04-16 16:48 UTC, Shinigami92 commented on docs/guide/upgrading.md
> +The methods `faker.helper.arrayElement` and `faker.helper.arrayElements` previously defaulted the `array` argument to a simply string array if non was provided.
```suggestion
The methods `faker.helpers.arrayElement` and `faker.helpers.arrayElements` previously defaulted the `array` argument to a simple string array if none was provided.
```

2023-04-16 20:47 UTC, xDivisionByZerox commented
> There is no test that actually tests the removal of the default value [...]

How would you do this? By removing the default value TypeScript no longer allows calling the function without an argument. This is the expected behavior. We can't unit-test that since TypeScript will already complain.

> [...] or handling arrays containing undefined

Test for nullish values (`undefined`):
https://github.com/faker-js/faker/blob/909a1e6ea6ac0f2cfa915514e63c3916b74a03a8/test/helpers.spec.ts#L217-L220

2023-04-17 02:28 UTC, matthewmayer commented
> > There is no test that actually tests the removal of the default value [...]
> 
> How would you do this? By removing the default value TypeScript no longer allows calling the function without an argument. This is the expected behavior. We can't unit-test that since TypeScript will already complain.
> 
> > [...] or handling arrays containing undefined
> 
> Test for nullish values (including `undefined`):
> 
> https://github.com/faker-js/faker/blob/909a1e6ea6ac0f2cfa915514e63c3916b74a03a8/test/helpers.spec.ts#L217-L220

I'm not sure what the best way is, if you call it from Javascript you don't get a Faker Error you get a TypeError which is a bit unintuitive. Could this be documented better/provide a better error message for JS?

```
faker.helpers.arrayElement()
Uncaught TypeError: Cannot read property 'length' of undefined

> try {faker.helpers.arrayElement([])} catch (e) {console.log(e instanceof FakerError)}
true

> try {faker.helpers.arrayElement()} catch (e) {console.log(e instanceof FakerError)}
false
```

2023-04-17 03:24 UTC, matthewmayer commented
> > > There is no test that actually tests the removal of the default value [...]
> > 
> > 
> > How would you do this? By removing the default value TypeScript no longer allows calling the function without an argument. This is the expected behavior. We can't unit-test that since TypeScript will already complain.

How about this:
```ts
it('should throw on an undefined array', () => {
          let undefinedArray: string[];
          expect(() =>
            faker.helpers.arrayElement(undefinedArray)
          ).toThrowError();
        });
```

2023-04-17 08:54 UTC, xDivisionByZerox commented
> > > > There is no test that actually tests the removal of the default value [...]
> > > 
> > > 
> > > How would you do this? By removing the default value TypeScript no longer allows calling the function without an argument. This is the expected behavior. We can't unit-test that since TypeScript will already complain.
> 
> How about this:
> 
> ```ts
> it('should throw on an undefined array', () => {
>           let undefinedArray: string[];
>           expect(() =>
>             faker.helpers.arrayElement(undefinedArray)
>           ).toThrowError();
>         });
> ```

That is simply not the expected behavior (on top of being invalid code). TypeScript first. I don't care about JS Users. Sorry for the strong language, but this argument simply annoys me. 

If we want to fully support plain JS, half of the code base requires a refactor, as we only check valid TS types for all method arguments and not the ones that are invalid but still possible in JS.

2023-04-17 10:46 UTC, matthewmayer commented
I do care about JavaScript users! I'm not saying we need to add lots of extra tests to handle weird things being passed into methods that typescript prevents. But in this specific case previously if you passed undefined to this method it would return one of a, b or c. Now it doesn't, it throws instead. From a TDD perspective it makes sense to write a test which would fail before this change is merged and pass after it is merged to ensure correctness and prevent future regressions.

2023-04-17 13:18 UTC, Shinigami92 requested changes

2023-04-17 13:18 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +  arrayElement<T>(array: ReadonlyArray<T>): T {
NOW I understand what @matthewmayer is talking about! 💡

```suggestion
  arrayElement<T>(array?: ReadonlyArray<T>): T {
```

```ts
if (array == null)
  deprecate({ ... })
```

2023-04-17 13:24 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  arrayElement<T>(array: ReadonlyArray<T>): T {
@Shinigami92 I'm confused. The parameter is now required.

I understand @matthewmayer 's suggestion as adding an explicit test for that case.

2023-04-17 13:24 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +  arrayElement<T>(array: ReadonlyArray<T>): T {
But this doesn't make sense considering what this PR wants to achieve. I did in fact think they wanted a change like this, but I'll block that decision. 
This IS a breaking change. It is supposed to do precisely that, break your code if you do not adapt. I don't know why we discuss that at all.

2023-04-17 13:41 UTC, ST-DDT commented on docs/guide/upgrading.md
> +This behavior was undesired and has been removed.
Maybe mention that this violated the typescript definition regarding the default type.

2023-04-17 13:59 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +  arrayElement<T>(array: ReadonlyArray<T>): T {
Why suddenly not make a deprecation for this case, but for all other cases?
Why do we need to make a compile-time breaking change here?

2023-04-17 14:44 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +  arrayElement<T>(array: ReadonlyArray<T>): T {
So we will have them as optional in v8 and make them completely required in v9? I don't this is what @matthewmayer wants. If so, this makes even less sense to me.

2023-04-17 14:47 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +  arrayElement<T>(array: ReadonlyArray<T>): T {
This is what I understand @matthewmayer had requested
If I misunderstood him, yes... I'm with you

I added #2069 and we might want to merge this first, then override/adjust the tests again in this PR
So because we are not releasing a v7.6.1 just for a test, at least it is in the commit history 😆

2023-04-17 14:49 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  arrayElement<T>(array: ReadonlyArray<T>): T {
We might want to throw a specific error for JS users, that the array is now required.
Because JS users dont note the signature change otherwise and get this "cryptic" error instead:

![grafik](https://user-images.githubusercontent.com/1579362/232521987-0e35d006-6eb0-43e0-af01-fe69eebbe4ee.png)

Similar to https://github.com/faker-js/faker/blob/4a095dd407e61e8cea4f9953a8886cd87087f54c/src/faker.ts#L508-L512

2023-04-17 14:52 UTC, ST-DDT commented
There seems to be some misunderstanding about various peoples intentions.
Lets talk about that in Discord later.

2023-04-20 17:18 UTC, ST-DDT commented on docs/guide/upgrading.md
> +This behavior was undesired and has been removed.
```suggestion
This behavior violated the expected return type of the method.
```

2023-04-20 17:20 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * @throws If array is empty.
```suggestion
   * @throws If `array` is empty.
```

2023-04-20 17:20 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * @throws If array is empty.
Or

```suggestion
   * @throws If the given array is empty.
```

2023-04-20 17:20 UTC, ST-DDT commented on src/modules/helpers/index.ts
>     * @param array Array to pick the value from.
```suggestion
   * @param array The array to pick the value from.
```

2023-04-20 17:21 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      throw new Error(
Maybe throw a `FakerError`?

2023-04-20 17:22 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      throw new Error(
Maybe throw a `FakerError`?

2023-04-20 17:23 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +        'Calling `faker.helpers.arrayElement()` without arguments is no longer supported. You would have known this if you used TypeScript :)'
While I would love to have this, this could be considered toxic and in violation of our code of conduct.
So please use neutral language for this.

2023-04-20 17:23 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +        'Calling `faker.helpers.arrayElements()` without arguments is no longer supported. You would have known this if you used TypeScript :)'
While I would love to have this, this could be considered toxic and in violation of our code of conduct.
So please use neutral language for this.

2023-04-20 18:15 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    if (array == null) {
Should we add a `TODO remove in v9 here`?

2023-04-20 18:15 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    if (array == null) {
Should we add a `TODO remove in v9 here`?

2023-04-20 18:15 UTC, ST-DDT commented on src/modules/helpers/index.ts
>    arrayElements<T>(
This doesn't have the `@throws`.

2023-04-20 18:15 UTC, ST-DDT commented on test/helpers.spec.ts
> +          // @ts-ignore
@Shinigami92 told me that you should use `ts-expect-error` here with a comment why.

2023-04-20 18:15 UTC, ST-DDT commented on test/helpers.spec.ts
> +          // @ts-ignore
Same here

2023-04-20 18:15 UTC, ST-DDT commented on test/helpers.spec.ts
> +        });
Please add these two tests also for `arrayElements` if they aren't already there.
(might need some adjustments)

2023-04-20 18:36 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
>    arrayElements<T>(
Because the case it currently thows at is not offically supported.

2023-04-20 18:42 UTC, xDivisionByZerox commented on test/helpers.spec.ts
> +        });
But `helpers.arrayElements` is not supposed to throw with `[]` as argument. But I can add the second test case.

2023-04-20 18:54 UTC, ST-DDT commented on test/helpers.spec.ts
> +        });
> But `helpers.arrayElements` is not supposed to throw with `[]` as argument.

I couldn't find a test for that case, you please add one?

2023-04-20 19:06 UTC, xDivisionByZerox commented on test/helpers.spec.ts
> +        });
It already existed before https://github.com/faker-js/faker/blob/f721e8d38ec175f532523ea3a762d44775a8fdf5/test/helpers.spec.ts#L441-L445

2023-04-20 19:37 UTC, ST-DDT approved these changes, later dismissed

2023-04-20 20:01 UTC, Shinigami92 commented on test/helpers.spec.ts
> +          // @ts-expect-error `arrayElement` without arguments is not supported in TypeScript
```suggestion
          // @ts-expect-error: `arrayElement` without arguments is not supported in TypeScript
```

2023-04-20 20:01 UTC, Shinigami92 commented on test/helpers.spec.ts
> +          // @ts-expect-error `arrayElements` without arguments is not supported in TypeScript
```suggestion
          // @ts-expect-error: `arrayElements` without arguments is not supported in TypeScript
```

2023-04-20 21:28 UTC, ST-DDT approved these changes, later dismissed

2023-04-21 01:39 UTC, import-brain requested changes, later dismissed

2023-04-21 01:39 UTC, import-brain commented on docs/guide/upgrading.md
> +Additionally, by providing an empty array argument (`[]`) the functions previously returned `undefined`.
```suggestion
Additionally, when passing in an empty array argument (`[]`), the functions previously returned `undefined`.
```

2023-04-21 01:39 UTC, import-brain commented on test/helpers.spec.ts
>          it('should return undefined if given object is empty', () => {
```suggestion
        it('should throw if given object is empty', () => {
```

2023-04-21 01:39 UTC, import-brain commented on test/helpers.spec.ts
>          it('does not allow empty array parameters', () => {
```suggestion
        it('should throw with empty array parameters', () => {
```

2023-04-21 16:27 UTC, Shinigami92 approved these changes

2023-04-21 16:46 UTC, ST-DDT approved these changes

2023-04-21 17:06 UTC, ST-DDT commented
> please review again or approve

@Shinigami92 we are not in a hurry.

2023-04-21 17:08 UTC, Shinigami92 commented
> > please review again or approve
> 
> @Shinigami92 we are not in a hurry.

This was not related with being in a hurry in any case?!
I just wrote a message into the dismiss form that GitHub requires to dismiss stale review blockings

2023-04-21 17:17 UTC, ST-DDT commented
> This was not related with being in a hurry in any case?!
> I just wrote a message into the dismiss form that GitHub requires to dismiss stale review blockings

Then please wait with dismissing their review, so they actually have time to review again.
If sufficient time has passed and we actually want to proceed with merging this it is still early enough to dismiss them then.

2023-04-21 20:37 UTC, import-brain approved these changes

2023-04-21 20:53 UTC, merged