chore: rename generics
faker-js/faker pull request #2046
Opened 2023-04-14 08:09 UTC by Shinigami92

This PR renamed generics to a convention suggested by one of the TypeScript experts @mattpocock based on the YouTube video: https://www.youtube.com/watch?v=qA65QjWCl60

Also based on this poll (https://main.elk.zone/mas.to/@jvhellemond@mastodon.social/110124086297164650) by @jvhellemond `entries` are renamed to `elements` when it is in the context of an array/set

2023-04-14 09:28 UTC, ST-DDT reviewed
I'm really torn on this one.

- I like using useful names
- I don't like the TName convention
- I don't think it adds value for methods that only do `T*` -> `T`
- I think `TValue`/`Value` does not transport any additional meaning over `T`

2023-04-14 09:28 UTC, ST-DDT commented on src/definitions/definitions.ts
> +export type LocaleEntry<TRecord extends Record<string, unknown>> =
Note to self:

- Rename `LocaleEntry` to `LocaleCategoryDefinition` or something.

2023-04-14 09:28 UTC, ST-DDT commented on src/definitions/definitions.ts
> +export type LocaleEntry<TRecord extends Record<string, unknown>> =
Maybe name it `BuiltInCategoryDefinition`?

2023-04-14 11:25 UTC, ST-DDT commented
I watched the video and he explicitly mentions that `T` is fine as long as you don't have multiple (RSTUV...) ones.

As for TPrefixed: I see what argument he is trying to make, but if you cannot remember that `NotPrefixed` is your generic, then there are probably more important issues such as bad naming or a too complex method.

2023-04-14 11:29 UTC, Shinigami92 commented
Why might need to activate https://typescript-eslint.io/rules/naming-convention/#enforce-that-type-parameters-generics-are-prefixed-with-t

2023-04-14 11:36 UTC, matthewmayer commented
T is prefixed with T :)

I feel this is unnecessary. `<T>` is very commonly understood in both Typescript and from other languages like Java. If i see <TRecord> i wonder if you are doing something special and different.

2023-04-14 14:04 UTC, xDivisionByZerox requested changes
I sadly can't reject the only request changes. Can I request to change everything back?
All of this is overkill. There are good situations to get verbose with your generic names. The ones changed in this PR do not belong to that category.

2023-04-14 17:01 UTC, Shinigami92 commented
> I'm really torn on this one.
> 
> * I like using useful names

Me either :+1: 
Even while working on this PR, I now more and more respect this naming convention and I'm tempted to use it for all my projects, because you can directly and easily read what the generic type is aimed for instead of first reading the code and try to find it out.

> * I don't like the TName convention

Do you have a reason for that?

> * I don't think it adds value for methods that only do `T*` -> `T`

We have one example for when `T` is the result/return value of a function and one for when it is for the input.
Now with this change it is directly readable from the code for what the generic type is used for.

Yeah okay we could discuss this specific case and maybe just use better names from the start like `Input` and `Result`, but the `T` prefix makes it better in two ways:
1. it does not conflict with other types like if you would have an interface called `Result` (for what ever reason)
2. you can directly find the generic types vs the other types/interfaces used in "more complex" code

> * I think `TValue`/`Value` does not transport any additional meaning over `T`

_read above_

---

> T is prefixed with T :)
> 
> I feel this is unnecessary. `<T>` is very commonly understood in both Typescript and from other languages like Java. If i see `<TRecord>` i wonder if you are doing something special and different.

1. I'm not tempted to follow old ways of doing something just because it was ever done like that without arguments for pro or con
2. Yes, maybe we need to find a better name instead of `TRecord`, and @ST-DDT already pointed to that: https://github.com/faker-js/faker/pull/2046#discussion_r1166569752

---

> I sadly can't reject the only request changes. Can I request to change everything back? All of this is overkill. There are good situations to get verbose with your generic names. The ones changed in this PR do not belong to that category.

These are really very generic (pun not intended) reasons without any real valuable arguments :confused: 
You say `There are good situations to get verbose with your generic names` but doesn't come up with an example but just the statement.
Please substantiate your statement.

2023-04-14 17:09 UTC, Shinigami92 commented on scripts/generateLocales.ts
> +type PascalCase<TString extends string> =
I'm not sure what `S` was holding before
is it just a "string"? is it a "name"? are there any suggestions how we could make it more clear what this actually holds?

/cc @ST-DDT

2023-04-14 17:09 UTC, Shinigami92 commented on src/definitions/definitions.ts
> +export type LocaleEntry<TRecord extends Record<string, unknown>> =
I'm not totally satisfied with `BuiltIn` as these `CategoryDefinition` could also be filled with custom data, can it?
Did you maybe mean something like `TFakerCategoryDefinition` or just a bit more verbose `TCategoryDefinition`?

2023-04-14 17:09 UTC, Shinigami92 commented on src/internal/merge.ts
> +export function mergeArrays<TArgument>(...args: TArgument[][]): TArgument[] {
Are these maybe `TElement` instead of `TArgument`?
I'm currently also a bit confused about the `[][]` :eyes:
it might be better read as `Array<TArgument[]>` (or even `ReadonlyArray<TArgument[]>` :thinking:), but this might conflict with `@typescript-eslint/array-type` (_not tested yet_)

2023-04-14 17:23 UTC, Shinigami92 commented
Addition: This PR aims to reduce the cognitive load of reading the code / using the methods

2023-04-14 22:15 UTC, ST-DDT commented
> > * I don't like the TName convention
> 
> Do you have a reason for that?

Sure, it creates an arbitrary rule to name something in a special way inconsistently.
I could flip this around and ask why don't you prefix **both** types and interfaces with `I`?
What makes a method local type different from a file local (not exported) one or exported ones?

2023-04-14 22:21 UTC, xDivisionByZerox commented on scripts/generateLocales.ts
> +type PascalCase<TString extends string> =
I call cap. If you use a higher order type and don't know what the generic is supposed to be that's bad... like from your side, and you should probably not work with those types in that case.

Furthermore, If we assume you had no idea what `S` was supposed to be, how can you say in all seriousness that now that you named it `TString` (which literally can still mean anything) know what it is supposed be? Renaming the generic doesn't provide any additional context in this example.

If you really wanted a verbose generic name you should go for `StringToMakePascalCase` or something. Then I could at least believe that you now understand the meaning of the generic type.

2023-04-14 22:25 UTC, ST-DDT commented
> but the `T` prefix makes it better in two ways:
> 
> 1. it does not conflict with other types like if you would have an interface called `Result` (for what ever reason)

But what if you have an exported type `TResult` "for what ever reason"? Ambiguous naming is prone to collisions.

> 2. you can directly find the generic types vs the other types/interfaces used in "more complex" code

If the generic type is simple you don't need a full name in the first place.
Both generics and external code can get pretty complex, I often put this complexity into the methods generics, so that TS resolves the result instead of displaying `Whatever<T>`. But it is very easy to outsource the generic complexity to a separate type. And if I can outsource or inline it, why would I name it specially?

2023-04-14 22:25 UTC, xDivisionByZerox commented on src/internal/merge.ts
> +export function mergeArrays<TArgument>(...args: TArgument[][]): TArgument[] {
> I'm currently also a bit confused about the T[][]

That is a personal preference. I for example cannot read `Array<TArgument[]>`.
I read the first one as: "I have a** generic element** in an array x 2 => 2-dimensional array".
While The second one is all over the place in my thought process: "I have an array that consists of **generic elements** in an array".

2023-04-14 22:31 UTC, xDivisionByZerox commented
> I could flip this around and ask why don't you prefix both types and interfaces with I?

This! Excatly this!!!
Why stop there use the correct prefix for **I**nterfaces and **T**ypes.

```ts
export interface IMyInterface {
  // ... definition
}

export type TMyType = // definition
```

I mean it cool, no? You just have to type `I` or `T` and VSCode suggests all possible interfaces or types.

2023-04-14 22:36 UTC, ST-DDT commented
> > I feel this is unnecessary. `<T>` is very commonly understood in both Typescript and from other languages like Java. If i see `<TRecord>` i wonder if you are doing something special and different.
> 
> 1. I'm not tempted to follow old ways of doing something just because it was ever done like that without arguments for pro or con

I'm not tempted to drop proven ways of doing something just because of a single video without arguments for pro or con.

Pro simple generics:

- It is a well understood concept
- It doesn't bloat the code, with `TThisIsSomethingReallyUnimportantName` over "hey this is something dynamic `T`".

> 2. Yes, maybe we need to find a better name instead of `TRecord`, and @ST-DDT already pointed to that:

If you have a suggestion, we can discuss it. Currently the increased length of the name only takes more time to read till the extends clause that already tells me it is a `Record`. And if you try to guess what a method does without at least having a look at the method name/definition is stupid. If the method or generic is poorly named, then a longer name won't help either.

2023-04-14 22:40 UTC, ST-DDT commented
> > I sadly can't reject the only request changes. Can I request to change everything back? All of this is overkill. There are good situations to get verbose with your generic names. The ones changed in this PR do not belong to that category.
> 
> These are really very generic (pun not intended) reasons without any real valuable arguments 😕 You say `There are good situations to get verbose with your generic names` but doesn't come up with an example but just the statement. Please substantiate your statement.

Yes, the reasoning is a bit fussy, but IMO it is a valid point. 
If you want a reason: I assign specific names if the **name** carries value, not just because I can.

2023-04-14 22:48 UTC, xDivisionByZerox commented
> These are really very generic (pun not intended) reasons without any real valuable arguments 😕
You say There are good situations to get verbose with your generic names but doesn't come up with an example but just the statement.
Please substantiate your statement.

Sure. Have a look at the implementation of a JS Generator:

```ts
interface Generator<T = unknown, TReturn = any, TNext = unknown> extends Iterator<T, TReturn, TNext> {
    // NOTE: 'next' is defined using a tuple to ensure we report the correct assignability errors in all places.
    next(...args: [] | [TNext]): IteratorResult<T, TReturn>;
    return(value: TReturn): IteratorResult<T, TReturn>;
    throw(e: any): IteratorResult<T, TReturn>;
    [Symbol.iterator](): Generator<T, TReturn, TNext>;
}
```

This makes to have verbose names as we have multiple generics.

Again, as long as you don't have multiple generic values you don't need to get creative. Please check the video again (time 1:59min to 2:01min):

> For simple types like this I will generally keep this as the single letter T

---

Lastly, I kind of have the feeling that you don't really understand generics. This is based on the last team meeting. Just a friendly hint that you often talk about things you think you understand while multiple ppl tell you that you are obviously wrong. If you really are "not tempted to follow old ways of doing something just because it was ever done like that without arguments for pro or con" please stop suggesting entire project changes every time you saw a new video on how to do things the new way.

2023-04-14 22:50 UTC, ST-DDT commented on scripts/generateLocales.ts
> +type PascalCase<TString extends string> =
`PascalCase` is a notation. If you don't know what `PascalCase` is, then you have other problems (As mentioned earlier).

If you jump in the middle of the definition and don't instantly know what S has, then start from the beginning.
Adding longer names such as `TString extends string` increases the amount I have to read, without adding value, that you would gain anyway, if you look at the code from the start. 

IMO in this case especially, the entire inner type definition is entirely irrelevant, because the name of the type carries all information you need about what the type does.

2023-04-14 22:51 UTC, xDivisionByZerox commented
@mattpocock May you give me/us some insight if this PR is what you wanted to achieve when creating your video [How to Name your Types](https://youtu.be/qA65QjWCl60?t=118)?

2023-04-14 22:58 UTC, ST-DDT commented on src/internal/merge.ts
> +export function mergeArrays<TArgument>(...args: TArgument[][]): TArgument[] {
Element is better than Argument. But it adds weight to the type, that is entirely unimportant.
You want to merge arrays, is important to have a dedicated name for the elements?
No, the method implementation doesn't really care and just shoves them together. It doesn't even appear in the implementation.
You add 20% more code (105->129 chars) that doesn't tell you anymore about it than `T[]`.

2023-04-14 23:01 UTC, ST-DDT commented
> Addition: This PR aims to reduce the cognitive load of reading the code / using the methods

These are really very generic (pun not intended) reasons without any real valuable arguments 😕 You say [...] you don't come up with an example but just the statement. Please substantiate your statement.

2023-04-14 23:05 UTC, ST-DDT commented on src/definitions/definitions.ts
> +export type LocaleEntry<TRecord extends Record<string, unknown>> =
> I'm not totally satisfied

Me neither, it was just an attempt in adding some value to the currently proposed "name".

2023-04-15 07:31 UTC, Shinigami92 commented on scripts/generateLocales.ts
> +    : Capitalize<TValue>;
Should we load this from https://github.com/sindresorhus/type-fest/blob/9feb8c89be9a0f2f688bf2f497230298a8e2472e/source/pascal-case.d.ts#L36 instead of defining it manually in our code base?
We just would need to keep care that we don't use types that would need to be exported tied together from our `src/` code, because I don't know how this would behave when users use them but `type-fest` is just a `devDependencies` in `@faker-js/faker` and therefore doesn't get published with it.

2023-04-15 08:05 UTC, Shinigami92 commented
I would like to remember @xDivisionByZerox and @ST-DDT to read our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md) again.

https://github.com/faker-js/faker/blob/5e421b0cdfd272e9bb96468e80f41152a88d7fbf/CODE_OF_CONDUCT.md?plain=1#L5

Please don't blame me down or make assumptions about **my potential** `level of experience`.

https://github.com/faker-js/faker/blob/5e421b0cdfd272e9bb96468e80f41152a88d7fbf/CODE_OF_CONDUCT.md?plain=1#L9-L13

Please try to write a bit more `respectful` comments especially in terms of `differing viewpoints and experiences`.
Using `welcoming and inclusive language` can also help finding a better path to a more constructive base.

> I call cap. If you use a higher order type and don't know what the generic is supposed to be that's bad... like from your side, and you should probably not work with those types in that case.

(https://github.com/faker-js/faker/pull/2046#discussion_r1167310461)

For example we should prevent using exclamations like `I call crap` and just leave it out of the discussion.
Furthermore we could write with more `welcoming and inclusive language` like:
```diff
- I call cap. If you use a higher order type and don't know what the generic is supposed to be that's bad... like from your side, and you should probably not work with those types in that case.
+ If you use a higher order type, the generic template parameter is only supposed to transfer the given type the user is providing through it. However we should keep care on your side to not over-engineer types if they are getting to complex to used and the intention is not clear in the first place.
```

This would have prevented me from getting attacked on a personal level.

---

Please also think about PRs as a Pull **Request** which is indirectly always a proposal and needs to be accepted by the team/maintainers of a project, but can also get rejected / not merged.

@ST-DDT was telling me the last weeks that I should not open issues for something when I directly can open a PR, because (and I agree with that) in a PR we can discuss on a per code-line level.
In addition to that it prevents managing a flood of more and more issues.

---

I checked the template type of the TS definition `Array/ReadonlyArray` and it is indeed just and only `T`.
Also the `interface Generator<T = unknown, TReturn = any, TNext = unknown>` example is a good showcase for a real-world example.

So yes we should discuss two points:
1. where is it okay to just use `T`, because I gave the argument above that `TValue`/`TInput` vs `TResult` makes it more clear to read the intent out of the name of the generic type without reading left or right from it. But in our cases we have these examples only on separate places and therefore not the case where we would have two generics next to each other.
2. Should we follow the suggestion of @mattpocock and use the `T` prefix for template types in general, or should we not use it, but maybe come to a compromise where we use the non-prefixed but more expressive variant:
   ```diff
   - maybe<T>(callback: () => T, options: ...): T | undefined;
   + maybe<Result>(callback: () => Result, options: ...): Result | undefined;
   ```

2023-04-15 08:53 UTC, ST-DDT commented
> I would like to remember @xDivisionByZerox and @ST-DDT to read our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md?rgh-link-date=2023-04-15T08%3A05%3A43Z) again.

Thanks for pointing this out. I'll try to improve on this.
But I would also like to ask yourself to do the same regarding your prior rude comments.
Lets talk about this in person as to not further get off topic with the discussion.

2023-04-16 10:07 UTC, Shinigami92 commented
From yesterdays discussion in Discord voice chat, I found out you are not at all against renaming some of these generic template parameters to some more verbose names, but you are especially more against the `T` prefix itself.

So maybe a good solution is to find the compromise between single letter values and the T prefixed verbose naming as we only want the more verbose naming if it is not instantly obvious what T is (like for an array).
So if we have e.g. an input (that is not an array element), a value, a result etc. we would prefer meaningful names.
We already did good for some cases like instead of using `T` or `C` we use `CategoryData` (https://github.com/faker-js/faker/blob/385d4fae52956778b9d856ef2a6f39a779a7d07f/src/locale-proxy.ts#L59)
This makes it (and maybe I just speck for me as myself, but I'm also one of the contributor of this project that needs to work with the code and mostly read not write it) by far more readable especially when it comes into the body of this function where the generic type is reused below
https://github.com/faker-js/faker/blob/385d4fae52956778b9d856ef2a6f39a779a7d07f/src/locale-proxy.ts#L70

If you would just read `get(_, entryName: keyof T): T[keyof T] {`, yes this is shorter, but you are absolutely loosing the context of what is going on.

The T prefix naming convention helped me to find all these places in the whole code base, not only the `src` code, because it is an automated eslint rule.
Maybe we could redefined this setting to our own needs to accept `T` as a single value, or a at least two length letter PascalCase named typename.
That way, we would get support from eslint for future PR reviews.

2023-04-20 16:58 UTC, ST-DDT commented
**Team Decision**

- We want to name our generics `T` or `TPrefixed`.
- We only use `TPrefixed` if this adds value to the declaration, decided on a case by case role
  - if there are multiple generic paramters

2023-04-20 17:25 UTC, Shinigami92 commented
@faker-js/members @faker-js/maintainers Please write new review comments on each remaining rename with a reason why or why not it should be named T / not T, if it hurts you in your soul

2023-04-20 18:04 UTC, ST-DDT commented on scripts/generateLocales.ts
> +type PascalCase<TValue extends string> =
Maybe `TName` or just `T`?

2023-04-20 18:04 UTC, ST-DDT commented on src/modules/helpers/unique.ts
> +    // TODO christopher 2023-02-14: This `any` type can be fixed by anyone if they want to.
```suggestion
```

2023-04-20 18:04 UTC, ST-DDT commented on src/modules/person/index.ts
> +function selectDefinition<TValue>(
IMO this can just be `T`.

2023-04-20 18:04 UTC, ST-DDT commented on src/utils/types.ts
> +export type LiteralUnion<TUnion extends TBase, TBase = string> =
Maybe use `TSuggested` instead of `TUnion`, but not sure?

2023-04-20 18:09 UTC, Shinigami92 commented on scripts/generateLocales.ts
> +type PascalCase<TValue extends string> =
I will go with `TName`

2023-04-20 18:09 UTC, Shinigami92 commented on src/modules/person/index.ts
> +function selectDefinition<TValue>(
I think that's okay, because this is just internal code anyway

2023-04-20 18:17 UTC, ST-DDT commented on src/modules/person/index.ts
> +function selectDefinition<TValue>(
A single `TValue` without context is the most generic name possible here and does not add any value.

2023-04-20 18:26 UTC, ST-DDT submitted a review, later dismissed

2023-05-01 10:23 UTC, ST-DDT commented
This has gotten stale over the last merges.

2023-05-03 12:45 UTC, ST-DDT approved these changes

2023-05-03 13:39 UTC, xDivisionByZerox approved these changes

2023-05-04 14:42 UTC, merged