refactor(location): street
faker-js/faker pull request #2051
Opened 2023-04-15 15:46 UTC by Shinigami92

close #2020

2023-04-15 15:47 UTC, Shinigami92 commented
1. Is this a breaking change? Do we need to add the `!` in PR title?
2. How should I name this PR/changelog entry?

2023-04-16 10:22 UTC, Shinigami92 commented
> 1. Is this a breaking change? Do we need to add the `!` in PR title?
We decided yes, just to have this at the top in the changelog

> 2. How should I name this PR/changelog entry?
Still unsure how to name this
Especially the internal stuff is not really relevant

> 3. What do we need to do for documentation?
No response yet

2023-04-16 10:25 UTC, matthewmayer requested changes, later dismissed

2023-04-16 10:25 UTC, matthewmayer commented on src/definitions/location.ts
> +  street_pattern: string[];
other definitions have plural patterns, e.g. company/name_patterns, person/bio_patterns, person/last_name_patterns

2023-04-16 11:15 UTC, Shinigami92 commented on src/definitions/location.ts
> +  street_pattern: string[];
I suggest to name everything consistently to singular because this can better read when using the fake function

`faker.helpers.faker('I'm living in {{location.street_pattern}}')`

We need a separate PR to rename everything to singular (but I think this is obvious ^^)

2023-04-16 11:19 UTC, matthewmayer commented on src/definitions/location.ts
> +  street_pattern: string[];
You shouldn't be using street_pattern/s directly though, you should just write

faker.helpers.faker('I'm living in {{location.street}}') no?

2023-04-16 11:36 UTC, Shinigami92 commented on src/definitions/location.ts
> +  street_pattern: string[];
Why do write `city` instead of `cities` but `x_patterns` instead of `x_pattern`?

2023-04-16 12:00 UTC, matthewmayer commented on src/definitions/location.ts
> +  street_pattern: string[];
company/name_patterns started the trend and the rest copied.

2023-04-16 12:09 UTC, Shinigami92 commented on src/definitions/location.ts
> +  street_pattern: string[];
So we will revert that and use singular consistently
Luckily this is currently all only in alpha v8

2023-04-16 12:57 UTC, ST-DDT reviewed
If I checked correctly the following locales have `street_name`s, but no pattern using it.

- az
- es_MX
- he
- ka_GE
- ko
- lv
- nb_NO
- ro
- ru
- sv
- uk

2023-04-16 12:57 UTC, ST-DDT commented on src/modules/location/index.ts
> +   *
```suggestion
   *
```

2023-04-16 12:57 UTC, ST-DDT commented on src/locales/th/location/street_pattern.ts
This diff confused me, because `src/locales/tr/location/street.ts` (TR) → `src/locales/th/location/street_pattern.ts` (TH), but the TH file is newly created and the moved TR file just looks identical.

But everything is fine.

2023-04-16 13:21 UTC, Shinigami92 commented on src/definitions/location.ts
> +  street_pattern: string[];
- #2059

2023-04-16 13:26 UTC, ST-DDT submitted a review, later dismissed

2023-04-16 13:33 UTC, matthewmayer commented
why is this marked as breaking in the PR desc?

2023-04-16 13:38 UTC, ST-DDT commented
Because it breaks your code if you use `fake("{{location.street}}")`.

2023-04-16 13:47 UTC, matthewmayer commented
Won't {{location.street}} grab the method not the definitions?

2023-04-16 13:56 UTC, Shinigami92 commented
> Won't {{location.street}} grab the method not the definitions?

I expect yes

2023-04-16 13:59 UTC, ST-DDT commented
Oh yeah. You are right.

2023-04-16 16:40 UTC, Shinigami92 commented
@matthewmayer you requested changes with the blocking version of a PR review
please re-evaluate your request/review

2023-04-16 16:48 UTC, matthewmayer commented
I need some more time to test this.

2023-04-18 17:52 UTC, xDivisionByZerox approved these changes

2023-04-18 22:57 UTC, matthewmayer commented
Looks ok but shouldn't be marked breaking if it isn't.

2023-04-19 02:50 UTC, matthewmayer commented
On https://next.fakerjs.dev/guide/upgrading.html#faker-address-changed-to-faker-location perhaps the row for streetName should be updated to reflect that if you are upgrading from faker.address.streetName then you should migrate straight to faker.location.street instead of faker.location.streetName?

2023-04-19 13:40 UTC, ST-DDT commented
Should we split this PR into two?
Both changes are indepent from each other.
https://github.com/faker-js/faker/pull/2070#issuecomment-1514700947

2023-04-19 15:19 UTC, xDivisionByZerox commented
> Should we split this PR into two? Both changes are indepent from each other. [#2070 (comment)](https://github.com/faker-js/faker/pull/2070#issuecomment-1514700947)

Would be a welcome change but not required since we already reviewed it IMO

2023-04-19 15:43 UTC, ST-DDT commented
> Would be a welcome change but not required since we already reviewed it IMO

The migration guide needs updating anyway so it doesnt really matter IMO.

2023-04-20 17:31 UTC, Shinigami92 commented
#2071 should be merged first, so this can be rebased

2023-04-21 17:01 UTC, ST-DDT approved these changes

2023-04-21 21:19 UTC, import-brain approved these changes

2023-04-21 21:39 UTC, merged