refactor(finance): rename account to accountNumber
faker-js/faker pull request #2054
Opened 2023-04-15 17:16 UTC by Shinigami92

references https://github.com/faker-js/faker/issues/1346#issuecomment-1407724091

2023-04-15 17:18 UTC, Shinigami92 commented on src/modules/finance/index.ts
> +   * @since 2.0.1
```suggestion
   * @since 8.0.0
```

2023-04-15 17:31 UTC, xDivisionByZerox requested changes
Please include this in the upgrading guide.

2023-04-15 17:31 UTC, xDivisionByZerox commented on src/modules/finance/index.ts
>     * @since 2.0.1
```suggestion
   * @since 8.0.0
```

2023-04-15 17:31 UTC, xDivisionByZerox commented on src/modules/finance/index.ts
>     * @since 2.0.1
```suggestion
   * @since 8.0.0
```

2023-04-15 21:41 UTC, ST-DDT commented on src/modules/finance/index.ts
> +   * @deprecated Use `faker.finance.accountNumber` instead.
This should also have a `@see` tag.

2023-04-16 10:38 UTC, ST-DDT submitted a review, later dismissed

2023-04-16 11:10 UTC, xDivisionByZerox approved these changes, later dismissed

2023-04-18 01:33 UTC, import-brain requested changes

2023-04-18 01:33 UTC, import-brain commented on test/finance.spec.ts
> +        it('should be the the length to given number', () => {
```suggestion
        it('should have same length as given length number', () => {
```

2023-04-18 01:33 UTC, import-brain commented on test/finance.spec.ts
> +        it('should be the the length to given number', () => {
```suggestion
        it('should have same length as given length number', () => {
```

2023-04-18 01:33 UTC, import-brain commented on test/finance.spec.ts
> +        it('should be the the length option to given number', () => {
```suggestion
        it('should have same length as given length object', () => {
```

2023-04-18 06:55 UTC, ST-DDT approved these changes

2023-04-18 11:43 UTC, import-brain approved these changes

2023-04-18 12:42 UTC, matthewmayer approved these changes

2023-04-18 15:26 UTC, merged