refactor(finance): rename mask to maskNumber
faker-js/faker pull request #2055
Opened 2023-04-15 17:36 UTC by Shinigami92

references https://github.com/faker-js/faker/issues/1346#issuecomment-1407724091

2023-04-15 17:52 UTC, ST-DDT commented on src/modules/finance/index.ts
> +  maskNumber(
Maybe name this `maskedNumber`? Because it doesn't mask a given number, but masks a new one.

2023-04-15 21:29 UTC, ST-DDT approved these changes

2023-04-15 21:30 UTC, ST-DDT requested changes
Please include this in the upgrading guide.

2023-04-15 21:42 UTC, ST-DDT commented on src/modules/finance/index.ts
> +   * @deprecated Use `faker.finance.maskedNumber` instead.
This should also have a `@see` tag.

2023-04-16 09:24 UTC, matthewmayer commented
> Please include this in the upgrading guide.

i dont think the upgrading guide has to mention every deprecation, only
- breaking changes
- major module renames like name to person
- unexpected behavior changes

if a method is just changed to a better name within the same module, and the deprecation workflow is used, i think its fine to just mention this as a breaking change in the v9 upgrading guide when it is actually removed.

2023-04-16 10:46 UTC, ST-DDT commented
> i dont think the upgrading guide has to mention every deprecation

Not indeividually, but maybe as a list of renamed methods.

2023-04-16 10:46 UTC, ST-DDT approved these changes, later dismissed

2023-04-16 11:17 UTC, xDivisionByZerox approved these changes, later dismissed

2023-04-16 11:17 UTC, Shinigami92 commented
@matthewmayer @ST-DDT I cannot find it right now, but I thought we have an open TODO/issue to re-evaluate the upgrading guideline in total before releasing v8.0
Then we should check everything over and unify some stuff and so on (in the upgrading.md)

2023-04-16 11:59 UTC, matthewmayer commented
It would be good to have some guidelines on what needs to be in upgrading and what doesn't per my other comment.

2023-04-16 12:08 UTC, Shinigami92 commented
> It would be good to have some guidelines on what needs to be in upgrading and what doesn't per my other comment.

I suggest moving this into its own discussion, discord chat or even issue

2023-04-16 12:19 UTC, matthewmayer commented
Let's make an issue

2023-04-18 15:56 UTC, xDivisionByZerox approved these changes

2023-04-18 20:58 UTC, ST-DDT approved these changes

2023-04-20 15:09 UTC, merged