refactor(location): merge state and stateAbbr
faker-js/faker pull request #2060
Opened 2023-04-16 12:33 UTC by xDivisionByZerox

References https://github.com/faker-js/faker/issues/1346#issuecomment-1407728227

2023-04-16 12:41 UTC, ST-DDT commented on src/modules/location/index.ts
> +  state(useAbbreviation?: boolean): string;
IMO we should only use options.

2023-04-16 12:51 UTC, matthewmayer requested changes

2023-04-16 12:51 UTC, matthewmayer commented on src/modules/location/index.ts
> +   * faker.location.state({ useAbbreviation: false }) // 'Florida'
`abbreviated: true` would be simpler

2023-04-16 12:51 UTC, matthewmayer commented on src/modules/location/index.ts
> +      ? this.faker.definitions.location.state_abbr
Not all states have abbreviations. In that case would you expect the parameter to be ignored and it falls back to providing a full state name, or an error to be thrown?

2023-04-16 12:58 UTC, xDivisionByZerox commented on src/modules/location/index.ts
> +      ? this.faker.definitions.location.state_abbr
It is expected to throw after #2045 has been merged.

2023-04-16 13:00 UTC, ST-DDT commented on src/modules/location/index.ts
> +      ? this.faker.definitions.location.state_abbr
I assume it will also throw after #2004

2023-04-16 13:01 UTC, ST-DDT commented on src/modules/location/index.ts
> +   * faker.location.state({ useAbbreviation: false }) // 'Florida'
I think we use these abbr or similar parameters elsewhere and should rename them there as well.

2023-04-16 13:14 UTC, Shinigami92 commented on src/modules/location/index.ts
> +   * faker.location.state({ useAbbreviation: false }) // 'Florida'
#2061

2023-04-16 14:02 UTC, ST-DDT requested changes

2023-04-16 14:02 UTC, ST-DDT commented on src/modules/location/index.ts
> +   * faker.location.state(false) // 'Iowa'
```suggestion
```

2023-04-16 14:02 UTC, ST-DDT commented on src/modules/location/index.ts
> +
```suggestion
```

2023-04-16 14:12 UTC, ST-DDT commented on src/modules/location/index.ts
> -   * fakerDE.location.state() // 'Nordrhein-Westfalen'
I highlight this diff to raise awareness, that while we already mentioned in the docs that this method refers to the `first-level administrative entity`, there might still be some confusion what this might actually be. Should we keep these for reference or should we let the users uncover this themselves?

2023-04-16 14:48 UTC, matthewmayer commented on src/modules/location/index.ts
> -   * fakerDE.location.state() // 'Nordrhein-Westfalen'
I think we should keep. It's helpful to see a variety of  examples from different locales

2023-04-16 20:40 UTC, xDivisionByZerox commented on src/modules/location/index.ts
> -   * fakerDE.location.state() // 'Nordrhein-Westfalen'
I just want to say that I do not see why that would be necessary, but whatever. I revered the change.

2023-04-17 02:18 UTC, matthewmayer approved these changes

2023-04-17 08:03 UTC, ST-DDT approved these changes

2023-04-17 10:49 UTC, matthewmayer approved these changes
Looks good though we should come back and review this works as expected after #2045 and #2004 are done.

2023-04-17 13:02 UTC, Shinigami92 approved these changes

2023-04-17 13:24 UTC, merged