refactor(date): rename abbr to abbreviated
faker-js/faker pull request #2068
Opened 2023-04-17 12:59 UTC by Shinigami92

reference https://github.com/faker-js/faker/pull/2061#issuecomment-1510860565

2023-04-17 13:00 UTC, Shinigami92 commented
@ST-DDT How can I fix the deprecation test **without** adding multiple signature overloads to the methods? These would be overkill in my opinion for just deprecating/renaming a property from the options.

2023-04-17 13:15 UTC, ST-DDT commented
> @ST-DDT How can I fix the deprecation test **without** adding multiple signature overloads to the methods? These would be overkill in my opinion for just deprecating/renaming a property from the options.

That is sadly not possible. When typing a method or something. Ts always takes the last signature.
This also affected the type FakerOptions = ConstructorParameter<Faker>[0]. As well as our doc generation.

2023-04-17 13:23 UTC, Shinigami92 commented
> This also affected the type FakerOptions = ConstructorParameter[0]. As well as our doc generation.

Should I add an ignore to the test or really quadruple the signature?

2023-04-17 13:33 UTC, ST-DDT commented
> Should I add an ignore to the test or really quadruple the signature?

For consistency reasons, please add the mixed signature.

2023-04-17 14:08 UTC, Shinigami92 commented
> For consistency reasons, please add the mixed signature.

done

2023-04-17 14:35 UTC, ST-DDT commented
The CI still fails.

2023-04-17 14:50 UTC, Shinigami92 commented
> The CI still fails.

~~`ts-check:tests` is not in the `preflight` script~~ 🤔 

oh it is! but it does not exit !0 👀

2023-04-17 14:58 UTC, ST-DDT requested changes

2023-04-17 14:58 UTC, ST-DDT commented on src/modules/date/index.ts
> +    deprecated({
Missing if?

2023-04-17 15:12 UTC, ST-DDT requested changes

2023-04-17 15:12 UTC, ST-DDT commented on src/modules/date/index.ts
> +   * @deprecated Use `faker.date.month({ abbreviated, ... })` instead.
```suggestion
```

2023-04-17 15:12 UTC, ST-DDT commented on src/modules/date/index.ts
> +   * @since 3.0.1
```suggestion
   * @since 8.0.0
```

2023-04-17 15:12 UTC, ST-DDT commented on src/modules/date/index.ts
> +   * @deprecated Use `faker.date.weekday({ abbreviated, ... })` instead.
```suggestion
```

2023-04-17 15:12 UTC, ST-DDT commented on src/modules/date/index.ts
> +   * @since 3.0.1
```suggestion
   * @since 8.0.0
```

2023-04-17 15:12 UTC, ST-DDT commented on src/modules/date/index.ts
> +      context = false,
Does this work?

```suggestion
      abbr,
      abbreviated = abbr ?? false,
      context = false,
```

2023-04-17 15:12 UTC, ST-DDT commented on src/modules/date/index.ts
> +    if (abbr == null) {
```suggestion
    if (abbr != null) {
```

2023-04-17 15:12 UTC, ST-DDT commented on src/modules/date/index.ts
> +    if (abbr == null) {
```suggestion
    if (abbr != null) {
```

2023-04-17 15:12 UTC, ST-DDT commented on src/modules/date/index.ts
> +      context = false,
Does this work?

```suggestion
      abbr,
      abbreviated = abbr ?? false,
      context = false,
```

2023-04-17 15:23 UTC, Shinigami92 commented on src/modules/date/index.ts
> +   * @since 3.0.1
@xDivisionByZerox can you approve if I correctly remember correctly, that we want not to change these just because option params have changes, have we?

2023-04-17 15:23 UTC, ST-DDT approved these changes

2023-04-17 15:35 UTC, xDivisionByZerox commented on src/modules/date/index.ts
> +   * @since 3.0.1
Correctly. `@since` applies to the method itself, not the concrete signature. At least currently it is done that way.

2023-04-17 21:27 UTC, xDivisionByZerox approved these changes

2023-04-18 01:28 UTC, ejcheng approved these changes

2023-04-18 06:21 UTC, merged