feat: Generate JSON file with TypeDoc
faker-js/faker pull request #207
Opened 2022-01-18 02:00 UTC by ericjeker

I rebased from main as the other branch was too far behind and also because in the meantime I deleted it from my fork to have a clean fork.

Now, here's the catch:

TypeDoc generates documentation only from directly exported types from the entrypoint:
https://github.com/TypeStrong/typedoc/issues/1657

So our sub-classes, like `Address`, are not included in the documentation except if they are exported from `index.ts`. Not sure if this is desirable.

There are workarounds, but I did not try that yet: https://github.com/Gerrit0/typedoc-plugin-missing-exports

As in `Faker` we instantiate all those sub-classes:

```typescript 
readonly address: Address = new Address(this);
```

We could imagine exporting these instances, so ideally we could then access them doing:

```TypeScript
import { Address } from '@faker-js/faker';

const cityName = Address.city();
```

This is up for discussion.

2022-01-18 07:49 UTC, Shinigami92 commented
```ts
import { Address } from '@faker-js/faker';

const cityName = Address.city();
```

It's sadly not that simple

https://github.com/faker-js/faker/blob/a973ee1ce64d2b593f64b633e927382280da8f27/src/address.ts#L97-L114

Here you can see that city is relying on definitions and the datetype module.
So you would need to always pass that from outside.

https://github.com/faker-js/faker/blob/a973ee1ce64d2b593f64b633e927382280da8f27/src/helpers.ts#L332

Also modules like e.g. `helpers` need e.g. this member function.

Beside that it would break the whole projects compatibility. So we cannot work on that before v7 or later.

---

For now we should try to find another way to generate docs out of the existing code.
Maybe there is just a configuration or we need a JSDoc "annotation".
Maybe it's also possible to export just the types at `index.ts` like `export type { Address } from './address'` :thinking: 

I will test this out a bit later this day.

2022-01-21 16:53 UTC, ST-DDT commented
We already export the global Faker instance.
Maybe we can define, that these sub instances also refer to that.
````js
export const faker: Faker = new Faker({
  locales: require('./locales'),
});

export const address = faker.address;
[...]
````

2022-01-23 04:52 UTC, ericjeker commented
Added a plugin to generate the documentation in markdown. For now I generate it under `docs/api/typedoc`.

There is a VuePress [plugin](https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/vuepress-plugin-typedoc) available to integrate all this with VuePress, but sadly VitePress doesn't support plugins the same way, they integrated plugins in "themes". 

I am really not familiar with those projects so can't really help with that.

So we have 2 solutions I guess:

1. We dump VitePress in favor of VuePress. Which seems reasonable as it works out of the box.
2. We develop a TypeDoc theme or plugin for VitePress, maybe contributing to @tgreyuk project.

2022-01-23 05:20 UTC, Shinigami92 commented
I (personally) would like to choose the hard / second way here, because we would like to bring and push VitePress and the Vite ecosystem forward.
VuePress 1 seems not in active development anymore and introduce (dev) audit vulnerability dependencies. VuePress 2 is also just in beta for more then half a year.
Knowing that in around one month there will be the new Vue 3 docs and on 7 February 2022 Vue 3 will become the new default, we should really stay with VitePress 😉

All the problems we now find will help potentially thousands other devs to not have these issues in the future.

2022-01-23 05:25 UTC, Shinigami92 requested changes

2022-01-23 05:25 UTC, Shinigami92 commented on typedoc.ts
> +import * as TypeDoc from 'typedoc';
Please move this file into the scripts folder

2022-01-23 05:25 UTC, Shinigami92 commented on package.json
> +    "typedoc": "ts-node typedoc.ts"
Just replace ts-node with esno 
And then remove the ts-node dependency because esno is just like a replacement for ts-node 🙂

2022-01-23 05:42 UTC, ericjeker commented
I already opened an issue [here](https://github.com/tgreyuk/typedoc-plugin-markdown/issues/287) to see if we can contribute to @tgreyuk repo so more people will profit from this. So far, I was able to integrate some of the generated `.md` with VitePress but some Markdown are not properly generated (e.g. the tables), or properly sanitized and VitePress doesn't like that.

2022-01-23 05:52 UTC, ericjeker commented on typedoc.ts
> +import * as TypeDoc from 'typedoc';
Done

2022-01-23 05:52 UTC, ericjeker commented on package.json
> +    "typedoc": "ts-node typedoc.ts"
Done

2022-01-23 10:00 UTC, Shinigami92 requested changes

2022-01-23 12:48 UTC, ST-DDT commented on package.json
> +    "vuepress-plugin-typedoc": "^0.10.2"
Sure, just tell me what needs to be automated.

2022-01-24 23:53 UTC, ST-DDT commented
I continued this PR in https://github.com/faker-js/faker/pull/289.

2022-01-25 05:04 UTC, ericjeker commented
This can be closed and will continue here: https://github.com/faker-js/faker/pull/289

2022-01-25 05:04 UTC, closed without merging