test: lint vitest
faker-js/faker pull request #2098
Opened 2023-04-26 20:49 UTC by Shinigami92

Lint with https://www.npmjs.com/package/eslint-plugin-vitest

2023-04-26 21:11 UTC, Shinigami92 commented
I think this is a good start

But there are more rules to explore later in future PRs like

- [prefer-each](https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/prefer-each.md)
- [prefer-lowercase-title](https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/prefer-lowercase-title.md)
- [prefer-spy-on](https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/prefer-spy-on.md)
- [prefer-to-contain](https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/prefer-to-contain.md)

2023-04-26 22:06 UTC, ST-DDT commented on test/all_functional.spec.ts
> +    describe(`${module}`, () => {
Why?

2023-04-26 22:06 UTC, ST-DDT commented on test/helpers.spec.ts
> +          ).not.throw();
Is there maybe a `not.toThrow`?

2023-04-26 22:06 UTC, ST-DDT commented on test/vehicle.spec.ts
> +      describe('color()', () => {
Why did you shuffle them around?

2023-04-27 06:56 UTC, Shinigami92 commented on test/all_functional.spec.ts
> +    describe(`${module}`, () => {
https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/valid-title.md

it is expected that `describe` and `it` always contains (compile-time) strings
in this specific example it is later anyways recommended to use `describe.each(Object.keys(modules))(`%s`, () => {})` via https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/prefer-each.md

2023-04-27 06:56 UTC, Shinigami92 commented on test/helpers.spec.ts
> +          ).not.throw();
I think yes, will check later

If I remember correctly, `toThrow()` and `throw()` behave slightly differently, but in most cases this is not relevant (but I will keep this in mind when I will check that later)

2023-04-27 06:56 UTC, Shinigami92 commented on test/vehicle.spec.ts
> +      describe('color()', () => {
https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/no-identical-title.md

reported that `describe('vin()', ...` was used twice, so I correctly merged them
then while already touching [vin](url), I moved it down above the `vrm` so they are near to each other
I recommend (for a later PR) to order all the tests again to the same order as in the modules
And additionally also order module methods in alphabetic or logical understandable order (maybe there is even a lint rule that could help us?)

2023-04-27 07:12 UTC, ST-DDT commented on test/vehicle.spec.ts
> +      describe('color()', () => {
> I recommend (for a later PR) to order all the tests again to the same order as in the modules

I think that wont be neccesary since the tree shaking refactor will split them to individual files anyway.

2023-05-06 15:30 UTC, ST-DDT requested changes
Please set the lint level to error. Since there is no point in just warning about errors and then ignoring them.

2023-05-06 15:30 UTC, ST-DDT commented on .eslintrc.js
> +
The other configs don't have the white space here.

```suggestion
```

2023-05-06 15:30 UTC, ST-DDT commented on .eslintrc.js
> +
```suggestion
```

2023-05-06 18:52 UTC, Shinigami92 commented on .eslintrc.js
> +
not directly related to this PR, but I will add a blankline in the other places
the blanklines are separating the plugin groups from each other

2023-05-06 18:55 UTC, Shinigami92 commented
> Please set the lint level to error. Since there is no point in just warning about errors and then ignoring them.

you might have read something different
there is no 'warn'?!
please point me where you have read that

2023-05-06 22:59 UTC, ST-DDT commented
You haven't done explicitly here, but implicitly.

As per https://github.com/faker-js/faker/issues/1431 we decided to use error for lint rules to prevent accidentally adding warnings, that don't get fixed.

- https://github.com/faker-js/faker/issues/1431
- https://github.com/faker-js/faker/pull/1714

To prevent cases like these that "pollute" the build logs.

![grafik](https://user-images.githubusercontent.com/1579362/236649514-4934deb6-959e-4458-aa20-06e66b63e658.png)

I don't care whether we explicitly configure them to error or consider warnings to be errors in CI.

2023-05-06 23:21 UTC, ST-DDT commented on test/all_functional.spec.ts
> +    describe(`${module}`, () => {
Then let's fix this as intended instead of bypassing the error/warning.

2023-05-07 09:15 UTC, Shinigami92 commented
> You haven't done explicitly here, but implicitly (or there is a config error somewhere).
> 
> As per #1431 we decided to use error for lint rules to prevent accidentally adding warnings, that don't get fixed.
> 
> * [Set lint warnings to error #1431](https://github.com/faker-js/faker/issues/1431)
> * [infra: set lint warnings to error #1714](https://github.com/faker-js/faker/pull/1714)
> 
> To prevent cases like these that "pollute" the build logs.
> 
> ![grafik](https://user-images.githubusercontent.com/1579362/236649514-4934deb6-959e-4458-aa20-06e66b63e658.png)
> 
> (If it is important, then it should be fixed. If it isn't important, why clutter the logs with warnings.)
> 
> I don't care whether we explicitly configure them to error or consider warnings to be errors in CI. For `preflight` it might be best, if we fail in the same cases as the CI/when there are warnings.

The issue is now open and requested at upstream

2023-05-07 12:47 UTC, Shinigami92 commented on test/all_functional.spec.ts
> +    describe(`${module}`, () => {
As discussed, I will activate `prefer-each` in a separate PR
Reason: minimize the changes already made in this PR (already 15 files changed)

The current change is necessary anyway as already commented above `valid-title`

2023-05-07 13:06 UTC, ST-DDT submitted a review, later dismissed

2023-05-08 07:24 UTC, xDivisionByZerox commented on test/finance.spec.ts
> +            ).toThrow(
According to the [maintainer](https://github.com/vitest-dev/vitest/discussions/2570?sort=top#discussioncomment-4503284) `toThrow` and `toThrowError` are the same.
Why prefer one over the other? If for consistency purposes, why prefer the less verbose one?

2023-05-08 07:24 UTC, xDivisionByZerox commented on test/helpers.spec.ts
> +          ).not.throw();
Why not `.not.toThrow` for consistency purposes?

2023-05-08 07:24 UTC, xDivisionByZerox commented on test/datatype.spec.ts
> +          }).toThrow(`Max ${max} should be greater than min ${min}.`);
This error expectation is different from all others :/

2023-05-08 07:35 UTC, Shinigami92 commented on test/finance.spec.ts
> +            ).toThrow(
Yes, they are aliases (see https://vitest.dev/api/expect.html#tothrowerror)

@ST-DDT had the argument that we mostly use `toThrow(FakerError` and therefore it already includes `Error`
In the other cases it is not relevant for us if it is an Error or anything else, just something was thrown

2023-05-08 07:36 UTC, Shinigami92 commented on test/helpers.spec.ts
> +          ).not.throw();
thx, I might just have missed that one 👍

2023-05-08 07:43 UTC, xDivisionByZerox commented on test/finance.spec.ts
> +            ).toThrow(
This explanation makes sense to me. Approved 👍

2023-05-08 07:46 UTC, xDivisionByZerox submitted a review, later dismissed

2023-05-08 07:46 UTC, Shinigami92 commented
will rebase after the dep updates

2023-05-08 08:16 UTC, ST-DDT submitted a review, later dismissed

2023-05-08 13:33 UTC, ST-DDT approved these changes

2023-05-08 15:48 UTC, xDivisionByZerox approved these changes

2023-05-09 01:22 UTC, matthewmayer approved these changes

2023-05-09 07:35 UTC, merged