refactor(locale): add city_name to city_patterns
faker-js/faker pull request #2104
Opened 2023-04-28 10:45 UTC by xDivisionByZerox

Part of  #2021.

2023-04-28 11:10 UTC, Shinigami92 approved these changes, later dismissed

2023-04-28 11:48 UTC, matthewmayer requested changes

2023-04-28 11:48 UTC, matthewmayer commented on src/locales/nb_NO/location/city_pattern.ts
> +  '{{location.city_name}}{{location.city_suffix}}',
If city_name is always a real city name it seems it should always stand alone and not be combined with a prefix or suffiX?

2023-04-28 11:48 UTC, matthewmayer commented on src/locales/ko/location/city_pattern.ts
> +  '{{location.city_name}}{{location.city_suffix}}',
Ditto

2023-04-28 13:28 UTC, xDivisionByZerox commented on src/locales/nb_NO/location/city_pattern.ts
> +  '{{location.city_name}}{{location.city_suffix}}',
As you may see from the diff, I added the standalone `location.city_name` templates. If those did exist before, there was probably a reason to include them as they are. 

I don't see why we shouldn't include those patterns as they provide more city name variants.
We need to put some work into researching if those patterns are actually harmful to the specific locale.

2023-04-28 13:38 UTC, ST-DDT commented on src/locales/nb_NO/location/city_pattern.ts
> +  '{{location.city_name}}{{location.city_suffix}}',
IMO we should fix those, but probably in a different PR to keep the PR concise.

If you have a city named Neustadt and just append a city prefix again, then you get bad names.
For street-names we also changed the pattern files to `street_name_part` to separate them from actual names.
We have to check the contents of these files to check if they contain actual city names or parts thereof.

2023-04-28 13:41 UTC, matthewmayer commented on src/locales/nb_NO/location/city_pattern.ts
> +  '{{location.city_name}}{{location.city_suffix}}',
If you look at the nb_NO city_names they are not actually real city names but fragments of the first half of names, designed to be combined with city_suffix. 

So best would be to rename city_name to city_prefix and use pattern {{city_prefix}}{{city_suffix}} instead?

2023-04-28 13:43 UTC, matthewmayer commented on src/locales/nb_NO/location/city_pattern.ts
> +  '{{location.city_name}}{{location.city_suffix}}',
This is how sv does it, for example.

2023-04-28 14:10 UTC, matthewmayer commented on src/locales/nb_NO/location/city_pattern.ts
> +  '{{location.city_name}}{{location.city_suffix}}',
i made a quick script to output what all the different city_pattern look like with examples for each locale:

https://gist.github.com/matthewmayer/f14b59d799be8ed063c3f38cdca38a6a

2023-04-30 10:08 UTC, Shinigami92 commented
What is the state of this PR? should this still be merged for v8.0?
Is it blocking?

2023-04-30 10:17 UTC, matthewmayer commented
> What is the state of this PR? should this still be merged for v8.0? Is it blocking?

i think the `no_NB` and `ko` changes should be reverted and then the rest can be merged. Then those two languages can be better handled in another PR.

2023-04-30 10:50 UTC, xDivisionByZerox commented
I reverted the changes for `ko` and `nb_NO`

2023-04-30 10:56 UTC, Shinigami92 approved these changes

2023-04-30 11:22 UTC, matthewmayer approved these changes

2023-04-30 11:27 UTC, ST-DDT approved these changes

2023-04-30 11:28 UTC, merged