feat: new plant module
faker-js/faker pull request #2126
Opened 2023-05-05 00:09 UTC by sarahtang7

Adds faker.plant.tree and faker.plant.flower as described in #2022 

Changes made:
- Added a new module, `plant`
- Added two new methods, `plant.tree` and `plant.flower` that return random tree and flower names
- Added data for tree and flower names
- Updated `en` locale data
- Added fixed seeded test class `plant.spec.ts` and snapshots

2023-05-05 04:56 UTC, matthewmayer requested changes

2023-05-05 04:56 UTC, matthewmayer commented on src/locales/en/plant/tree.ts
For the trees, i think it would be better to keep the names to simpler, mostly one-word tree names. Then those could be used in other patterns like https://github.com/faker-js/faker/blob/next/src/locales/en/location/street_pattern.ts

For example "Pine Street" or "Ash Drive" is realistic, but "Lavender Twist Redbud Avenue" is not.

2023-05-05 06:42 UTC, ST-DDT reviewed
Thanks for your contribution. Please note that we are approaching the v8.0 release and this PR likely wont make it in there.

Please run `pnpm run preflight`.

2023-05-05 06:42 UTC, ST-DDT commented on src/index.ts
> +  PlantDefinition as PlantDefinitions,
This is redundant as this is a new definition that didnt exist before.

2023-05-05 06:42 UTC, ST-DDT commented on src/modules/plant/index.ts
> +    return this.faker.helpers.fake(definition);
There is no need to call `fake()` on them since the names dont have templates attached to them.

2023-05-05 06:42 UTC, ST-DDT commented on src/modules/plant/index.ts
> +    return this.faker.helpers.fake(definition);
Same here

2023-05-05 06:44 UTC, ST-DDT commented on src/locales/en/plant/tree.ts
Maybe we should have a separate method/option for simple names?

2023-05-05 06:50 UTC, ST-DDT commented
I also noticed the issue is marked as waiting for user interest.
It currently does not have enough up votes for immediate inclusion.

2023-05-05 07:26 UTC, matthewmayer commented
I think a new contributor making a pull request should count as 5 upvotes 🤣

2023-10-07 10:19 UTC, ST-DDT commented
It looks like some lint errors have creeped in over time.

2024-06-20 15:54 UTC, ST-DDT commented
Close as stale. We can reopen this when required/updated.

2024-06-20 15:54 UTC, closed without merging