add states to vi locale and fix city name
faker-js/faker pull request #2128
Opened 2023-05-05 02:11 UTC by asharnadeem

Addresses concerns in #1977. Adds `state` support for the `vi` locale, and as part of this PR, also fixes `city_name` where the previous list included both cities and states. This PR introduces more realistic location data overall for the `vi` locale

2023-05-05 04:59 UTC, matthewmayer requested changes

2023-05-05 04:59 UTC, matthewmayer commented on src/locales/vi/location/state.ts
Should these include diacritics, like the city names? For example [Bình Phước](https://vi.wikipedia.org/wiki/B%C3%ACnh_Ph%C6%B0%E1%BB%9Bc) not `Binh Phuoc`

2023-05-05 06:21 UTC, ST-DDT commented on src/locales/vi/location/state.ts
If the real names have them, then yes.
If the user doesnt want them they can still strip them.

2023-06-17 11:35 UTC, ST-DDT commented on src/locales/vi/location/state.ts
@asharnadeem Can you please address the feedback?

2023-07-14 20:03 UTC, ST-DDT commented on src/locales/vi/location/state.ts
@asharnadeem Are you still interested in this PR?
If yes, please address the feedback. If not, please close it.

2023-07-21 19:44 UTC, matthewmayer commented on src/locales/vi/location/state.ts
i went ahead and added the diacritics in f9b51fbe

2023-07-21 19:44 UTC, matthewmayer approved these changes

2023-07-22 03:15 UTC, import-brain approved these changes

2023-07-22 14:02 UTC, ST-DDT approved these changes

2023-07-22 14:09 UTC, merged