feat(locale): add states for Croatia (hr)
faker-js/faker pull request #2142
Opened 2023-05-09 06:07 UTC by matthewmayer

Part of #1977

There are 21 counties

https://en.wikipedia.org/wiki/Counties_of_Croatia
https://hr.wikipedia.org/wiki/Hrvatske_%C5%BEupanije

2023-05-09 17:41 UTC, ST-DDT reviewed
It might be best to just call them counties here.
As for states we could use these https://en.wikipedia.org/wiki/Regions_of_Croatia or omit them entirely.

2023-05-09 17:41 UTC, ST-DDT commented on src/locales/hr/location/state.ts
> +  'Međimurska',
According to the pages you have linked I could only find: [https://hr.wikipedia.org/wiki/Me%C4%91imurska_%C5%BEupanija](Međimurska županija) which I would call a county.

![grafik](https://github.com/faker-js/faker/assets/1579362/91c2ab35-1452-4d0c-8fda-af98d5069bd5)

2023-05-11 04:09 UTC, matthewmayer commented on src/locales/hr/location/state.ts
> +  'Međimurska',
https://en.wikipedia.org/wiki/ISO_3166-2:HR ISO 3166-2 uses the counties as the 1st level administrative subdivisions, the regions seem to be more historical and not included in a typical address if i am not mistaken, so i feel they should be under `state()`

2023-05-11 07:11 UTC, ST-DDT commented on src/locales/hr/location/state.ts
> +  'Međimurska',
While technically it is the first level adminstrative subdivision, I would still use them as counties and simply mark state as being not applicable.

2023-08-31 16:54 UTC, ST-DDT commented
**Team Decision**

We will jump to a definition loophole and will put it in both state (as first level administrative unit) and in county (as county names).

We will create a separate issue to clarify that states ~= `ISO_3166-2`

2023-08-31 16:55 UTC, ST-DDT requested changes
Please put these in both state and county. County should import state.

2023-09-01 06:37 UTC, ST-DDT approved these changes

2023-09-09 21:08 UTC, xDivisionByZerox approved these changes

2023-09-09 23:41 UTC, import-brain approved these changes

2023-09-10 00:33 UTC, merged