feat(metadata): add method to access metadata
faker-js/faker pull request #2143
Opened 2023-05-09 06:23 UTC by matthewmayer

fix #1984

2023-05-09 22:09 UTC, ST-DDT commented on src/faker.ts
> +   * @returns An object including the locale title, code, language, endonym (native name), direction (left to right, or right to left), script, and optional country.
We usually dont document the return value with jsodcs, do we?

2023-05-09 22:09 UTC, ST-DDT commented on src/faker.ts
> +    return this.rawDefinitions.metadata;
```suggestion
    return this.rawDefinitions.metadata ?? {};
```

2023-05-10 07:17 UTC, ST-DDT requested changes

2023-05-10 07:17 UTC, ST-DDT commented on src/faker.ts
> +    return this.rawDefinitions.metadata ?? {};
We need a test for this method.

2023-05-10 07:54 UTC, ST-DDT approved these changes, later dismissed

2023-05-14 09:54 UTC, xDivisionByZerox commented on src/faker.ts
> +   * @returns An object including the locale title, code, language, endonym (native name), direction (left to right, or right to left), script, and optional country.
Yes, we don't. Furthermore, by explicitly listing all available properties we decouple the documentation from the actual implementation. If one changes we need to remember to change the other as well. This is not good.

I would suggest dropping this line.

2023-05-14 10:03 UTC, xDivisionByZerox reviewed
I'm a bit conflicted about why we extract the metaobject access from the definitions. Currently, you can access them fine just fine via `faker.definitions.metadata`. What is the benefit of the implementation of this PR?

2023-05-14 10:03 UTC, xDivisionByZerox commented on src/faker.ts
> +   * Returns an object with metadata about the current locale
```suggestion
   * Returns an object with metadata about the current locale.
```

2023-05-14 10:03 UTC, xDivisionByZerox commented on src/faker.ts
> +  metadata(): MetadataDefinition {
The method name and type are conflicting with the rest of the faker class. All subjects (`person`, `definitions`, etc) are properties. Methods are verbs or include prefixes like `get`/`set` (`setDefaultRefDate`). This method breaks this implicit convention and might cause confusion.

2023-05-14 10:38 UTC, matthewmayer commented on src/faker.ts
> +   * @returns An object including the locale title, code, language, endonym (native name), direction (left to right, or right to left), script, and optional country.
removed the @returns line

2023-05-14 10:39 UTC, matthewmayer commented
> I'm a bit conflicted about why we extract the metaobject access from the definitions. Currently, you can access them fine just fine via `faker.definitions.metadata`. What is the benefit of the implementation of this PR?

1. its not documented
2. we want the freedom to be able to rearrange things within `definitions` without it being a breaking change.

2023-05-14 10:40 UTC, matthewmayer commented on src/faker.ts
> +  metadata(): MetadataDefinition {
so `getMetadata()` ?

2023-05-14 10:46 UTC, xDivisionByZerox commented on src/faker.ts
> +  metadata(): MetadataDefinition {
I would suggest doing so. Alternatively, you could refactor the function to a `getter`. I don't have a preference between those  two.

2023-05-14 12:59 UTC, xDivisionByZerox approved these changes

2023-05-24 20:38 UTC, ST-DDT approved these changes

2023-05-24 20:48 UTC, Shinigami92 commented
Do not merge yet, so we can release a v8.0.2 the next few days
Generally do not merge feat+ into next, only fix, chore, test and docs

2023-06-17 06:20 UTC, merged