test: vitest prefer-each
faker-js/faker pull request #2144
Opened 2023-05-09 07:48 UTC by Shinigami92

references https://github.com/faker-js/faker/pull/2098#issuecomment-1524051531

2023-05-09 13:15 UTC, Shinigami92 commented
@ST-DDT could you have a first look and re-evaluate if I did not made any mistakes?

2023-05-09 14:12 UTC, ST-DDT commented on test/color.spec.ts
> +    { repeats: NON_SEEDED_BASED_RUN }
This is formatted differently then everything else.

2023-05-09 14:12 UTC, ST-DDT commented on test/helpers.spec.ts
> +      describe('multiple()', () => {
Why was this method used?

2023-05-09 14:59 UTC, Shinigami92 commented on test/helpers.spec.ts
> +      describe('multiple()', () => {
It moved up
Only the global store stuff was extracted out of the loop

2023-05-09 15:00 UTC, Shinigami92 commented on test/color.spec.ts
> +    { repeats: NON_SEEDED_BASED_RUN }
Good catch 👌

2023-05-09 15:57 UTC, Shinigami92 commented
I'm now experimenting a bit with the `repeats` and it looks like that the "string" description title does not get executed again (as assumed).
So we need to move the `seed()` into a `beforeAll` or we need to use `describe.each`.
I think `beforeAll` is more clear (but sadly more verbose) here

2023-05-09 16:39 UTC, Shinigami92 commented
blocked by https://github.com/vitest-dev/vitest/issues/3334

- https://github.com/vitest-dev/vitest/issues/3334

2023-05-09 21:21 UTC, Shinigami92 commented on test/locale-data.spec.ts
> +      checkLocaleData(nestedData);
@ST-DDT this never runs :thinking:

2023-05-09 21:21 UTC, ST-DDT commented on test/locale-data.spec.ts
> +      checkLocaleData(nestedData);
Why?

2023-05-09 21:22 UTC, Shinigami92 commented on test/locale-data.spec.ts
> +      checkLocaleData(nestedData);
good question, I'm asking you ^^

2023-05-09 21:29 UTC, ST-DDT commented on test/locale-data.spec.ts
> +      checkLocaleData(nestedData);
On the next ``branch``, it does get checked.

2023-05-09 21:30 UTC, Shinigami92 commented on test/locale-data.spec.ts
> +      checkLocaleData(nestedData);
okay I will check again

2023-05-09 21:32 UTC, ST-DDT requested changes

2023-05-09 21:32 UTC, ST-DDT commented on test/locale-data.spec.ts
> +    describe.each(Object.entries(data))('%s', (nestedData) => {
```suggestion
    describe.each(Object.entries(data))('%s', (_, nestedData) => {
```

2023-05-09 22:00 UTC, ST-DDT commented on test/all_functional.spec.ts
> +    describe.each(Object.keys(modules))('%s', (module) => {
Maybe

```suggestion
    describe.each(Object.entries(modules))('%s', (module, methods) => {
```

2023-05-09 22:00 UTC, ST-DDT commented on test/all_functional.spec.ts
> +      modules[module].forEach((meth) => {
Maybe

```suggestion
      methods.forEach((meth) => {
```

2023-05-09 22:00 UTC, ST-DDT commented on test/all_functional.spec.ts
> +    describe.each(Object.keys(modules))('%s', (module) => {
Same here

2023-05-09 22:00 UTC, ST-DDT commented on test/location.spec.ts
> +          )
```suggestion
          times(100).flatMap((i) => [
            { isMetric: true, radius: i },
            { isMetric: false, radius: i },
          ])
```

2023-05-09 22:00 UTC, ST-DDT commented on test/mersenne.spec.ts
> +  )('seed: %j', (seed) => {
```suggestion
  describe.each(
    [...seededRuns, [42, 1, 2], [1337, 1, 2], [1211, 1, 2]].map((v) => [v])
  )('seed: %j', (seed) => {
```

2023-05-09 22:00 UTC, ST-DDT commented on test/mersenne.spec.ts
> +  }, []);
Please use flatMap instead.

2023-05-09 22:04 UTC, ST-DDT commented on test/mersenne.spec.ts
> +  )('seed: %j', (seed) => {
The `.map((v) => [v])` is only needed due to some inconsistency in the handling of %j vs the args,

````txt
stdout | test/mersenne.spec.ts > mersenne twister > seed: 1337 > should return deterministic value for next()
seed:  1337

stdout | test/mersenne.spec.ts > mersenne twister > seed: 42 > should return deterministic value for next()
seed:  [ 42, 1, 2 ]

stdout | test/mersenne.spec.ts > mersenne twister > seed: 1211 > should return deterministic value for next()
seed:  [ 1211, 1, 2 ]

stdout | test/mersenne.spec.ts > mersenne twister > seed: 1211 > should return deterministic value for next()
seed:  1211

stdout | test/mersenne.spec.ts > mersenne twister > seed: 1337 > should return deterministic value for next()
seed:  [ 1337, 1, 2 ]

stdout | test/mersenne.spec.ts > mersenne twister > seed: 42 > should return deterministic value for next()
seed:  42
````

2023-05-09 22:06 UTC, ST-DDT commented on test/mersenne.spec.ts
> +  )('seed: %j', (seed) => {
IMO we should report that to vitest as a bug.

2023-05-09 22:07 UTC, ST-DDT commented on test/mersenne.spec.ts
> +  )('seed: %j', (seed) => {
The `.map((v) => [v])` is only needed due to some inconsistency we otherwise have in the handling of %j vs the args,

````txt
stdout | test/mersenne.spec.ts > mersenne twister > seed: 1337 > should return deterministic value for next()
seed:  1337

stdout | test/mersenne.spec.ts > mersenne twister > seed: 42 > should return deterministic value for next()
seed:  [ 42, 1, 2 ]

stdout | test/mersenne.spec.ts > mersenne twister > seed: 1211 > should return deterministic value for next()
seed:  [ 1211, 1, 2 ]

stdout | test/mersenne.spec.ts > mersenne twister > seed: 1211 > should return deterministic value for next()
seed:  1211

stdout | test/mersenne.spec.ts > mersenne twister > seed: 1337 > should return deterministic value for next()
seed:  [ 1337, 1, 2 ]

stdout | test/mersenne.spec.ts > mersenne twister > seed: 42 > should return deterministic value for next()
seed:  42
````

IMO we should report that to vitest as a bug.

2023-05-10 06:41 UTC, Shinigami92 commented on test/mersenne.spec.ts
> +  )('seed: %j', (seed) => {
I'm not sure if this is a bug upstream 🤔 
vitest expect an array of "tuple"s that are spreaded as args.

So `[1337]` becomes `(1337) => {}` but `[1337, 1, 2]` would become `(1337, 1, 2) => {}`
But we want `([1337, 1, 2]) => {}` instead, so we need to wrap them in a tuple with only one first value.

and then `.each` takes an array of tuples so we would have:

```ts
describe.each([
  [42],
  [1337],
  [1211],
  [[42, 1, 2]],
  [[1337, 1, 2]],
  [[1211, 1, 2]],
])...
```

Do you think we can somehow improve the code on our side to achieve the wanted result in a better way?

2023-05-10 07:04 UTC, ST-DDT commented on test/mersenne.spec.ts
> +  )('seed: %j', (seed) => {
> vitest expect an array of "tuple"s that are spreaded as args.

Then why doesnt it throw a type error if called otherwise?

> Do you think we can somehow improve the code on our side to achieve the wanted result in a better way?

IMO my suggestion pretty much handles this. We could shorten it further by mapping the arrays as well. :man_shrugging: 

```suggestion
  describe.each(
    [...seededRuns, ...seededRuns.map((v) => [v, 1, 2])].map((v) => [v])
  )('seed: %j', (seed) => {
```

Any maybe extract the `.map((v) => [v])` part in a separate method called tuplize or similar.

2023-05-10 07:09 UTC, ST-DDT commented on test/mersenne.spec.ts
> +    [Math.ceil(Math.random() * 1_000_000_000)],
IMO we can shorten this by extracting this in a separate method called `randomSeed()`.

2023-05-10 07:49 UTC, ST-DDT approved these changes

2023-05-10 21:06 UTC, ejcheng approved these changes

2023-05-11 17:46 UTC, xDivisionByZerox commented on test/company.spec.ts
> +    'random seeded tests for seed %i',
Sorry if this might be a noob question, but why is the difference between `%i`,`%s` and `%j`? 
I know that `%s` takes the first argument of each description as the value, in jest. Is that the same in vitest? `%i` is probably for index (?). But what does `%j` do?

2023-05-11 17:47 UTC, Shinigami92 commented on test/company.spec.ts
> +    'random seeded tests for seed %i',
https://vitest.dev/api/#test-each

2023-05-11 18:12 UTC, xDivisionByZerox commented on test/company.spec.ts
> +    'random seeded tests for seed %i',
I've searched in the docs for `descrive.each`...mb

2023-05-20 07:10 UTC, xDivisionByZerox approved these changes

2023-05-20 08:58 UTC, merged