feat(locales/ar): seed AR lorem
faker-js/faker pull request #2147
Opened 2023-05-10 15:18 UTC by ahmedrowaihi

2023-05-10 16:09 UTC, ST-DDT commented
Please run `pnpm run preflight`.
Also could you please explain how you have chosen the values for lorem?
E.g. are these actual words or just translations of the original lorems or random character sequences ?

2023-05-10 17:19 UTC, ahmedrowaihi commented
> Please run `pnpm run preflight`. Also could you please explain how you have chosen the values for lorem? E.g. are these actual words or just translations of the original lorems or random character sequences ?

YES, @ST-DDT 

- [x] I Did run `pnpm run preflight`
- [x] They are actual words, I tested them in my vs-code extension [lorem-ipsum-ar](https://github.com/ahmedrowaihi/lorem-ipsum-ar), and as an Arab myself, the generated texts are satisfying.

2023-05-11 04:25 UTC, matthewmayer commented
Not directly related to this PR, but whats the purpose of the "supplemental" vs "words" list? It seems the "supplemental" list is not used. Should they be merged into one?

2023-05-11 08:00 UTC, ahmedrowaihi commented
> Not directly related to this PR, but whats the purpose of the "supplemental" vs "words" list? It seems the "supplemental" list is not used. Should they be merged into one?


I just mimicked the EN and other locales `lorem`, but I see your point, even in the `src/definitions/lorem.ts` I don't see supplements defined.

2023-05-14 16:14 UTC, ahmedrowaihi commented
@xDivisionByZerox what info missing ?

2023-05-14 16:46 UTC, xDivisionByZerox commented
I *removed* the label that was previously added. 
Previously @ST-DDT asked for more information which [you already answered](https://github.com/faker-js/faker/pull/2147#issuecomment-1542553114).

So nothing to worry.

2023-05-14 16:49 UTC, ahmedrowaihi commented
> I _removed_ the label that was previously added. Previously @ST-DDT asked for more information which [you already answered](https://github.com/faker-js/faker/pull/2147#issuecomment-1542553114).
> 
> So nothing to worry.

Ahh I see, my bad, I haven't noticed that label was added.
Paradon me @xDivisionByZerox

2023-06-17 11:13 UTC, ST-DDT requested changes

2023-06-17 11:13 UTC, ST-DDT commented on src/locales/ar/lorem/supplemental.ts
> +  'اختطاف',
> kidnapping

I think this and similar words should not be in this list, as I don't consider it fit for professional use.

2023-06-17 13:43 UTC, ahmedrowaihi commented on src/locales/ar/lorem/supplemental.ts
> +  'اختطاف',
What professionals use for dummy text ?

2023-06-17 13:49 UTC, matthewmayer commented on src/locales/ar/lorem/supplemental.ts
> +  'اختطاف',
we try to remove words with negative connotations - see e.g. https://github.com/faker-js/faker/pull/1745/files for English

2023-06-17 13:50 UTC, ahmedrowaihi commented on src/locales/ar/lorem/supplemental.ts
> +  'اختطاف',
Ah, I get it now.
Sure I will replace all ones that has negative meanings

2023-06-17 13:50 UTC, matthewmayer commented on src/locales/ar/lorem/supplemental.ts
> +  'اختطاف',
(and more discussion at https://github.com/faker-js/faker/discussions/1631 )

2023-07-19 15:41 UTC, ahmedrowaihi commented
Here is my update, I removed all negative connotations :'D
@matthewmayer @xDivisionByZerox

2023-07-20 22:36 UTC, ST-DDT commented
In #2242 we merged supplemental into the lorem words file.

- #2242

Could you please do that here as well?

2023-07-20 22:38 UTC, ahmedrowaihi commented
Sure!

2023-07-20 22:54 UTC, ahmedrowaihi commented
@ST-DDT Here you go!

2023-07-22 16:17 UTC, ST-DDT commented on src/locales/ar/lorem/words.ts
Please sort this file alphabetically because it helps with spotting duplicates.

2023-07-22 16:17 UTC, ST-DDT commented on src/locales/ar/lorem/words.ts
> +  '-,',
Is this entry intentional?

2023-07-22 16:17 UTC, ST-DDT commented on src/locales/ar/lorem/words.ts
> +  '-',
Is this entry intentional?

2023-07-23 12:33 UTC, ahmedrowaihi commented on src/locales/ar/lorem/words.ts
> +  '-,',
Yes, they are verbs and good to be among generated texts, excepts the "-" for linking context can be used in general than using specific linking letter.

2023-07-23 12:35 UTC, ahmedrowaihi commented on src/locales/ar/lorem/words.ts
> +  '-',
Ops, I see your point is "-" and "-,"

It's a mistake, we can use "," and "-" each separately.
I will fix it

2023-07-23 12:40 UTC, ahmedrowaihi commented on src/locales/ar/lorem/words.ts
Sure

2023-07-31 21:45 UTC, ST-DDT approved these changes
Checked via google translate. Looks good to me.

2023-08-04 05:08 UTC, ahmedrowaihi commented
When is this going to be merged🥹, it's been 3 months fam, haven't felt happy for couple times

2023-08-04 06:49 UTC, Shinigami92 approved these changes

2023-08-04 07:19 UTC, xDivisionByZerox approved these changes

2023-08-04 07:39 UTC, merged

2023-08-04 07:40 UTC, ST-DDT commented
Sorry for the delay with the reviews.
It is currently holiday season and we are all busy.

2023-08-04 07:42 UTC, ahmedrowaihi commented
Thank you all!!