docs: switch doc links to stable
faker-js/faker pull request #2152
Opened 2023-05-12 12:35 UTC by Shinigami92

references #2151 

- #2151 Docs need to reference fakerjs.dev instead of next.fakerjs.dev

2023-05-12 12:37 UTC, Shinigami92 commented
somehow the links on docs already working :eyes: 

@ST-DDT and @matthewmayer did black magic in the past, did they?

2023-05-12 13:02 UTC, matthewmayer commented
In the HTML version they are converted to relative links automagically

2023-05-12 13:03 UTC, matthewmayer commented
Should this PR target v8 instead of next?

2023-05-12 13:10 UTC, ST-DDT commented
No, since the changes are now stable features, they should point to the stable docs.

2023-05-12 13:11 UTC, ST-DDT commented
> So do I even need to switch all the links?

Yes

2023-05-12 13:15 UTC, ST-DDT requested changes, later dismissed

2023-05-12 13:15 UTC, ST-DDT commented on README.md
> +|  v9 (next)  | https://next.fakerjs.dev/ |
This is not correct.

2023-05-12 13:15 UTC, ST-DDT commented on README.md
> +An in-depth overview of the API methods is available in the documentation for [v8 (stable)](https://fakerjs.dev/api/) and [v9 (next)](https://next.fakerjs.dev/api/).
Same here

2023-05-12 13:15 UTC, ST-DDT commented on src/modules/finance/index.ts
> - * For credit card related methods, use: [`creditCardNumber()`](https://next.fakerjs.dev/api/finance.html#creditcardnumber), [`creditCardCVV()`](https://next.fakerjs.dev/api/finance.html#creditcardcv
It looks like more than the links have changed.

2023-05-12 13:51 UTC, Shinigami92 commented on README.md
> +|  v9 (next)  | https://next.fakerjs.dev/ |
What would you suggest instead?

2023-05-12 13:56 UTC, Shinigami92 commented on README.md
> +|  v9 (next)  | https://next.fakerjs.dev/ |
```suggestion
|  v8.* (next)  | https://next.fakerjs.dev/ |
```

2023-05-12 13:56 UTC, Shinigami92 commented on README.md
> +An in-depth overview of the API methods is available in the documentation for [v8 (stable)](https://fakerjs.dev/api/) and [v9 (next)](https://next.fakerjs.dev/api/).
```suggestion
An in-depth overview of the API methods is available in the documentation for [v8 (stable)](https://fakerjs.dev/api/) and [v8.* (next)](https://next.fakerjs.dev/api/).
```

2023-05-12 13:57 UTC, matthewmayer commented on README.md
> +|  v9 (next)  | https://next.fakerjs.dev/ |
I guess for now next should be "v8.x"?

2023-05-12 14:01 UTC, Shinigami92 commented on src/modules/finance/index.ts
> - * For credit card related methods, use: [`creditCardNumber()`](https://next.fakerjs.dev/api/finance.html#creditcardnumber), [`creditCardCVV()`](https://next.fakerjs.dev/api/finance.html#creditcardcv
fixed

2023-05-12 14:12 UTC, matthewmayer commented on README.md
should we also keep the link to v6?

2023-05-12 14:16 UTC, Shinigami92 commented on README.md
No, I think we should not :thinking: 
This might also push more folks to use the newer stuff like v7 or better v8
The state vor v6 is very old, and we would not have the capacity to support it any further

2023-05-12 14:25 UTC, matthewmayer commented
theres a lint error now.

2023-05-12 14:30 UTC, Shinigami92 commented
> theres a lint error now.

@matthewmayer HA LOL ^^
the readme wanted a `\` escape for the `*`
thx for the ping anyway :ok_hand:

2023-05-12 16:01 UTC, xDivisionByZerox commented on README.md
Why not keep the docs link even if we do not actively support v6? We could add a `(legacy)` or `(EOL)` info.
We keep the branch anyway, so the link should still wor as well. Regardless if we show it in this list or not.

2023-05-12 16:30 UTC, Shinigami92 commented on README.md
It's already linked here
![image](https://github.com/faker-js/faker/assets/7195563/e7793c46-363e-40a1-ad13-5845007a17c6)

2023-05-12 17:22 UTC, Shinigami92 commented on README.md
@ST-DDT could you make the decision here?
Right now it feels like 1 `no` and some `yes`?!

2023-05-12 19:02 UTC, xDivisionByZerox commented on README.md
Ah ok, I didn't know this. In that case, we can get rid of it here.

2023-05-12 19:02 UTC, xDivisionByZerox approved these changes

2023-05-14 04:45 UTC, import-brain approved these changes

2023-05-14 16:59 UTC, Shinigami92 commented
This PR needs a review of a @faker-js/maintainers to get merged.
I would like to release `v8.0.1` as a Docs update release tomorrow if nothing else needs to be part of that release.

2023-05-15 06:24 UTC, prisis approved these changes

2023-05-15 06:24 UTC, merged