feat: bundle faker with microbundle
faker-js/faker pull request #217
Opened 2022-01-18 12:06 UTC by prisis

2022-01-18 14:03 UTC, Shinigami92 commented
I assume this is blocked by #152 and #169 ?

@faker-js/maintainers Could we have some reviews/approvals for these other PRs? Then we can proceed with this setup :rocket:

2022-01-18 15:49 UTC, prisis commented
Yeah, after both are merged this should work :)

2022-01-18 18:25 UTC, JessicaSachs commented
I'd like to block on this. I don't know why we would drop support for export default and make this a breaking change.

2022-01-18 18:31 UTC, Shinigami92 commented
> I'd like to block on this. I don't know why we would drop support for export default and make this a breaking change.

We don't :eyes:

2022-01-18 18:53 UTC, JessicaSachs commented
Spoke with Shini and I understand what this is about now 👍🏻

2022-01-19 16:26 UTC, Shinigami92 commented
@prisis try to at these lines to our workflow ci.yml

https://github.com/vitejs/vite/blob/56d84fb5ea454255ed07b9e01cf9f429eab11b33/.github/workflows/ci.yml#L3-L6

2022-01-19 21:52 UTC, Shinigami92 requested changes

2022-01-19 21:52 UTC, Shinigami92 commented on src/index.ts
> +} from './locales';
```suggestion
import * as allLocales from './locales';
```

2022-01-19 21:52 UTC, Shinigami92 commented on src/index.ts
> +  },
```suggestion
  locales: allLocales,
```

2022-01-21 18:08 UTC, Shinigami92 requested changes

2022-01-21 18:08 UTC, Shinigami92 commented on package.json
> +    "locale",
We don't have these files and folders anymore

```suggestion
```

2022-01-21 18:09 UTC, Shinigami92 commented
We also need to add dist and remove lib to/from some ignore files

2022-01-21 23:18 UTC, Shinigami92 requested changes

2022-01-21 23:18 UTC, Shinigami92 commented on package.json
>      "CHANGELOG_old.md",
Here in files, we can remove 
```
    "index.d.ts",
    "index.js",
    "lib",
    "locale",
```

2022-01-21 23:18 UTC, Shinigami92 commented on package.json
> +    "microbundle": "^0.14.2"
Please move it up to sorted position
Also it would be good to use `~` instead of `^`

The use `rm -Rf node_modules pnpm-lock.yaml && pnpm install` and commit both files

2022-01-21 23:22 UTC, Shinigami92 requested changes

2022-01-21 23:22 UTC, Shinigami92 commented on package.json
>      "vinyl-transform": "^1.0.0",
We should remove some dependencies:

- browserify
- gulp
- gulp-gh-pages
- gulp-rename
- gulp-uglify
- optimist
- ink-docstrap
- through2
- vinyl-buffer
- vinyl-source-stream
- vinyl-transform

2022-01-21 23:22 UTC, Shinigami92 commented on package.json
>      "vinyl-transform": "^1.0.0",
I think we can also remove the `build` folder completely
(and all references to that, like in readme/docs and ignore files)

2022-01-22 12:43 UTC, Shinigami92 commented
This PR may get stale by #257

2022-01-22 23:13 UTC, closed without merging