fix(git): limit need for Intl to specific method
faker-js/faker pull request #2172
Opened 2023-05-23 13:09 UTC by matthewmayer

#2171

2023-05-23 14:26 UTC, Shinigami92 commented
@matthewmayer you already found out how to fake that Intl does not exists, or alternatively you can also just mock it with vitest

Please add tests for this

2023-05-23 14:56 UTC, matthewmayer commented
> @matthewmayer you already found out how to fake that Intl does not exists, or alternatively you can also just mock it with vitest
> 
> Please add tests for this

Hmm, the problem is that Intl is checked only once at import time when the library is loaded. So you can't just do something like this:

```
describe('commitDate', () => {
        it('should return a random commitDate', () => {
          const commitDate = faker.git.commitDate();

          expect(commitDate).toBeTruthy();
          expect(commitDate).toBeTypeOf('string');

          const parts = commitDate.split(' ');
          expect(parts.length).toBe(6);
        });
        it('should throw if Intl is unavailable', () => {
          const oldIntl = Intl;
          (global as any).Intl = undefined;

          expect(() => {
            faker.git.commitDate();
          }).toThrow(
            new FakerError(
              'This method requires an environment which supports Intl.NumberFormat and Intl.DateTimeFormat'
            )
          );

          (global as any).Intl = oldIntl;
        });
      });
```

2023-05-23 14:59 UTC, Shinigami92 commented
@matthewmayer So this is not working? https://vitest.dev/guide/mocking.html#globals

2023-05-23 15:08 UTC, matthewmayer commented
> @matthewmayer So this is not working? https://vitest.dev/guide/mocking.html#globals If so, please report to Vitest

not really sure how that would work. seems to be for mocking globals you DON'T have, not removing globals you do have?

2023-05-23 15:12 UTC, Shinigami92 commented
get creative, try a bit around :slightly_smiling_face: 

<img src="https://github.com/faker-js/faker/assets/7195563/393396de-a362-4f23-bef1-1b7e4f4ebbc0" width="300px"/>

2023-05-23 16:40 UTC, matthewmayer commented
Can't get it to work. I can't seem to get code to run in the test before faker is imported. 

This is a way beyond my capabilities so if anyone else is available to add tests I'd appreciate it.

2023-05-23 16:55 UTC, Shinigami92 commented
@matthewmayer It took me a fraction of a second to just do this in `git.spec.ts`

<img width="982" alt="image" src="https://github.com/faker-js/faker/assets/7195563/8fb67a02-fa07-49eb-942e-6f01c23ae6ae">

Then I logged just 

<img width="791" alt="image" src="https://github.com/faker-js/faker/assets/7195563/5302eb1c-1f89-4613-94e4-66551bb23de2">

in `commitDate` function

Now you just need to move the check-logic to runtime, so you don't check `GIT_DATE_FORMAT_BASE == null` but `Intl.DateTimeFormat == null` instead of the `console.log` I did

I hope this helps to bring you forward

2023-05-23 18:06 UTC, matthewmayer commented
Ah ok moving the check logic to run time indeed makes it easy.

Glad I only wasted a fraction of a second of your time 😂

2023-05-23 19:14 UTC, Shinigami92 approved these changes, later dismissed
IMO it is okay for now to do it the dirty way and use `globalThis.Intl.DateTimeFormat = backup`
It could result in broken further test if the test does not run successfully, but common would this occur :shrug:

2023-05-23 19:30 UTC, Shinigami92 approved these changes, later dismissed

2023-05-24 01:39 UTC, import-brain submitted a review, later dismissed

2023-05-24 20:31 UTC, ST-DDT commented on src/modules/git/index.ts
> +    if (!Intl || !Intl.DateTimeFormat || !Intl.NumberFormat) {
Maybe add a comment why you check these instead of our used constants.

2023-05-25 01:41 UTC, matthewmayer commented on src/modules/git/index.ts
> +    if (!Intl || !Intl.DateTimeFormat || !Intl.NumberFormat) {
to get the tests to work? :D

2023-05-25 07:20 UTC, ST-DDT approved these changes

2023-05-25 10:13 UTC, Shinigami92 commented on src/modules/git/index.ts
> +    // We check if Intl support is missing rather than if GIT_DATE_FORMAT_BASE/GIT_TIMEZONE_FORMAT is null. This allows us to test the error case in environments that do have Intl support by temporar
How about this?

```suggestion
    // https://github.com/faker-js/faker/issues/2171
```

2023-05-25 11:07 UTC, ST-DDT commented on src/modules/git/index.ts
> +    // We check if Intl support is missing rather than if GIT_DATE_FORMAT_BASE/GIT_TIMEZONE_FORMAT is null. This allows us to test the error case in environments that do have Intl support by temporar
The linked issue is totally unrelated to why the comment is there.

2023-05-25 11:16 UTC, Shinigami92 commented on src/modules/git/index.ts
> +    // We check if Intl support is missing rather than if GIT_DATE_FORMAT_BASE/GIT_TIMEZONE_FORMAT is null. This allows us to test the error case in environments that do have Intl support by temporar
Accept of the fact that react-native is for example a real world use case

Beside that... The error message below already says why this condition exist, so why an extra comment?

Just also a random source to underly my opinion:
[YouTube Video: Don't Write Comments](https://www.youtube.com/watch?v=Bf7vDBBOBUA&ab_channel=CodeAesthetic)

2023-05-25 11:16 UTC, ST-DDT commented on src/modules/git/index.ts
> +    // We check if Intl support is missing rather than if GIT_DATE_FORMAT_BASE/GIT_TIMEZONE_FORMAT is null. This allows us to test the error case in environments that do have Intl support by temporar
Alternatively, we could use scoped imports that are loaded while `Intl` is absent.

````ts
const noIntlGitModule;

beforeAll(() => {
  const backup = Intl;
  Intl = null;
  const NoIntlGitModule = import('../src/modules/git?noIntl');
  noIntlGitModule = new NoIntlGitModule(faker);
  Intl = backup;
});

it("test", () => noIntlGitModule.commitEntry());
````

@Shinigami92 What do you think?

2023-05-25 11:23 UTC, Shinigami92 commented on src/modules/git/index.ts
> +    // We check if Intl support is missing rather than if GIT_DATE_FORMAT_BASE/GIT_TIMEZONE_FORMAT is null. This allows us to test the error case in environments that do have Intl support by temporar
looks okay to me (if this works) 🙂 

I just did not use `before/after`, because it would need to wrap the test in extra describe blocks and so on, and then I thought it overcomplexifies the test suite and the current solution just works
But if you want to do it the clean way, go on 👍

2023-05-25 13:35 UTC, matthewmayer commented on src/modules/git/index.ts
> +    // We check if Intl support is missing rather than if GIT_DATE_FORMAT_BASE/GIT_TIMEZONE_FORMAT is null. This allows us to test the error case in environments that do have Intl support by temporar
I don't think we need a particularly beautiful solution for this. It's one relatively unimportant method. More important to fix the bug.

2023-05-25 14:34 UTC, Shinigami92 commented on src/modules/git/index.ts
> +    // We check if Intl support is missing rather than if GIT_DATE_FORMAT_BASE/GIT_TIMEZONE_FORMAT is null. This allows us to test the error case in environments that do have Intl support by temporar
Yeah, this is why I recommended to keep it simple and don't need to explain in a comment what the code is doing
The reason in the comment is also unnecessary as of if you would change the if statement, the tests would fail
And if you then change the tests, you doing it wrong!
So to me the comment is 100% irrelevant and does not provide any value

So we could e.g. shorten this to just mention that we "support" environments without Intl and remove the rest left and right
But even this can be indirectly found out via git blame 👀 
If you do not have git blame or looking at the source code with Notepad, then a link to the source issue is helpful if you want to find out more

2023-05-25 15:00 UTC, matthewmayer commented on src/modules/git/index.ts
> +    // We check if Intl support is missing rather than if GIT_DATE_FORMAT_BASE/GIT_TIMEZONE_FORMAT is null. This allows us to test the error case in environments that do have Intl support by temporar
@ST-DDT what do you think? Just remove the comment again? It was not originally commented :D

I agree with the logic that, if someone came along and thought "hmm wouldnt it make more sense to check for GIT_DATE_FORMAT_BASE==null here instead that would immediately cause the tests to fail, so they wouldn't get far

2023-05-25 17:58 UTC, import-brain submitted a review, later dismissed

2023-05-25 22:39 UTC, ST-DDT commented on src/modules/git/index.ts
> +    // We check if Intl support is missing rather than if GIT_DATE_FORMAT_BASE/GIT_TIMEZONE_FORMAT is null. This allows us to test the error case in environments that do have Intl support by temporar
My idea behind the comment is to save the future `us`es/someones from wasting time even thinking about it.
I watched the video and I agree with it. But the comment is NOT there to explain what it does, but why it does this not obvious thing (one of the few exceptions the video mentions for comments).

My idea behind the test code suggestion, is to remove this hard to understand code from the source code aka having better code (also like suggested in the video). I actually prefer this over the comment as it is "more obvious".

Here is my POC:

- [Diff to this PR](https://github.com/matthewmayer/faker/compare/fix/limit-intl-error...faker-js:faker:pr/matthewmayer/2172-ST-DDT)
- [Diff to next](https://github.com/faker-js/faker/compare/pr/matthewmayer/2172-ST-DDT)

2023-05-25 22:44 UTC, ST-DDT commented on src/modules/git/index.ts
> +    // We check if Intl support is missing rather than if GIT_DATE_FORMAT_BASE/GIT_TIMEZONE_FORMAT is null. This allows us to test the error case in environments that do have Intl support by temporar
If you think this is superfluous, you can mark this as resolved.

2023-05-26 02:37 UTC, matthewmayer commented on src/modules/git/index.ts
> +    // We check if Intl support is missing rather than if GIT_DATE_FORMAT_BASE/GIT_TIMEZONE_FORMAT is null. This allows us to test the error case in environments that do have Intl support by temporar
your solution is clever, but i dont really like the way that the throw() is not longer within the commitDate method that actually throws. I'd say lets just mark resolved for now, i think all solutions here are going to involve some level of confusing code.

2023-05-26 06:09 UTC, Shinigami92 commented on src/modules/git/index.ts
> +    // We check if Intl support is missing rather than if GIT_DATE_FORMAT_BASE/GIT_TIMEZONE_FORMAT is null. This allows us to test the error case in environments that do have Intl support by temporar
In the danger of that in e.g. a year someone stumbels over the code and argument with https://caniuse.com/?search=intl.%20NumberFormat that every environment "now" supports it,
for the sake of god (and that we can just ship and satisfy our customers) I will approve...

2023-05-26 06:09 UTC, Shinigami92 approved these changes, later dismissed

2023-05-26 11:08 UTC, ST-DDT requested changes
Missing @throws jsdocs.

2023-05-27 00:52 UTC, matthewmayer commented
> Missing @throws jsdocs.

added @throws

2023-05-27 11:28 UTC, Shinigami92 approved these changes

2023-05-27 19:12 UTC, import-brain approved these changes

2023-05-27 19:42 UTC, ST-DDT approved these changes

2023-05-27 19:43 UTC, merged