feat(word): add param to enable random word capitalization
faker-js/faker pull request #2174
Opened 2023-05-24 15:09 UTC by ZweZeya

… to address issue #2165

2023-05-24 16:27 UTC, matthewmayer requested changes

2023-05-24 16:27 UTC, matthewmayer commented on src/modules/word/index.ts
> +  capitalize(
would be better to make an additional option to the `words` method than a completely seperate method

2023-05-24 16:27 UTC, matthewmayer commented on src/modules/word/index.ts
> +      .map(word => Math.random() > 0.5 ? word.charAt(0).toUpperCase() + word.slice(1) : word)
use faker.datatype.boolean instead of a raw Math.random call. This ensures it uses the faker seed for reproducible results.

2023-05-24 20:22 UTC, ST-DDT commented on src/modules/word/index.ts
> +  capitalize(
IMO it is unclear what this method does exactly. because it doesn't only capitalize but also generate random words.

2023-05-25 01:20 UTC, ZweZeya commented on src/modules/word/index.ts
> +      .map(word => Math.random() > 0.5 ? word.charAt(0).toUpperCase() + word.slice(1) : word)
okay I will take a look into it, I will also integrate this into the words method as part of the options

2023-05-25 06:09 UTC, matthewmayer requested changes
you should also add some tests in test/word.spec.ts to test the parameter works as expected

2023-05-25 06:09 UTC, matthewmayer commented on src/modules/word/index.ts
> +   * @param options.capitalize Whether the words are capatalized. Defaults to `none`
Typo "capatalized" should be "capitalized"

2023-05-25 06:09 UTC, matthewmayer commented on src/modules/word/index.ts
> +          capatilize?: 'random' | 'all' | 'none';
typo should be capitalize

2023-05-25 06:09 UTC, matthewmayer commented on src/modules/word/index.ts
> +           * Whether words are capatalized.
"capitalized". It would be good to explain what each option does, e.g. its not clear if all means "Foo Bar" or "FOO BAR"

2023-05-25 06:57 UTC, ZweZeya commented on src/modules/word/index.ts
> +           * Whether words are capatalized.
sure, I will amend the typo and try to add some tests in test/word.spec.ts

2023-05-25 07:49 UTC, ZweZeya commented
![image](https://github.com/faker-js/faker/assets/79783783/e54d260a-254f-4d81-853a-4d2bffaf43f6)

Hi, I am running into this error when I run ```pnpm run preflight```.

2023-05-25 09:07 UTC, matthewmayer commented
> ![image](https://user-images.githubusercontent.com/79783783/240840418-e54d260a-254f-4d81-853a-4d2bffaf43f6.png)
> 
> Hi, I am running into this error when I run `pnpm run preflight`.

this came up before, check you have v7 and v8 branches checked out as well, not just next branch https://github.com/faker-js/faker/pull/1871#issuecomment-1445431009

2023-05-25 09:09 UTC, matthewmayer requested changes

2023-05-25 09:09 UTC, matthewmayer commented on src/modules/word/index.ts
>        .multiple(() => this.sample(), { count })
it would probably make more sense to move the logic for capitalizing inside the function here

`() => this.sample()`

That avoids having to join, split, and then join again

2023-05-25 09:22 UTC, ZweZeya commented on src/modules/word/index.ts
>        .multiple(() => this.sample(), { count })
true, I'll give it a shot

2023-05-25 09:29 UTC, ZweZeya commented
> > ![image](https://user-images.githubusercontent.com/79783783/240840418-e54d260a-254f-4d81-853a-4d2bffaf43f6.png)
> > Hi, I am running into this error when I run `pnpm run preflight`.
> 
> this came up before, check you have v7 and v8 branches checked out as well, not just next branch [#1871 (comment)](https://github.com/faker-js/faker/pull/1871#issuecomment-1445431009)

I haven't checked other branches, but I have checked past commits. It is the same error.

2023-05-25 11:00 UTC, ST-DDT commented
> I haven't checked other branches, but I have checked past commits. It is the same error.

You probably have to run `git fetch --all` once to "download" the v6/v7 branches.

2023-05-25 21:00 UTC, ST-DDT commented on src/modules/word/index.ts
> +      options = { count: options, capitalize: 'none' };
```suggestion
      options = { count: options };
```

2023-05-25 21:00 UTC, ST-DDT commented on src/modules/word/index.ts
> +    const { count = { min: 1, max: 3 }, capitalize } = options;
```suggestion
    const { count = { min: 1, max: 3 }, capitalize = 'none' } = options;
```

2023-05-25 21:00 UTC, ST-DDT commented on src/modules/word/index.ts
> +   * @param options.capitalize Capitalize the first letter of each word. Defaults to `none`
```suggestion
   * @param options.capitalize Capitalize the first letter of each word. Defaults to `'none'`.
```

We should explain which options exists (for the non TS users) and what each option does.

2023-05-26 01:39 UTC, ZweZeya commented on src/modules/word/index.ts
> +   * @param options.capitalize Capitalize the first letter of each word. Defaults to `none`
sure, I will add a brief description in the JSDoc and change the code bits according to your suggested changes

2023-05-26 02:44 UTC, matthewmayer requested changes

2023-05-26 02:44 UTC, matthewmayer commented on src/modules/word/index.ts
> +            (capitalize === 'random' && this.faker.datatype.boolean)
shouldnt this be `this.faker.datatype.boolean()`, otherwise youre just checking for the existence of the method, not actually calling it

2023-05-26 02:44 UTC, matthewmayer commented on src/modules/word/index.ts
> +            word = word.charAt(0).toUpperCase() + word.slice(1);
it might be better to use `.toLocaleUpperCase(this.faker.definitions.metadata.code)` to handle languages which have different capitalization rules like Turkish: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleUpperCase

2023-05-26 02:44 UTC, matthewmayer commented on test/__snapshots__/word.spec.ts.snap
> +exports[`word > 42 > words > with options.count range and capitalize = random 1`] = `"Nondisclosure Stud Across Dreamily Accurate Circumvent Boo News Loftily Through Devoice About When Boohoo Graze B
this snapshot test seems wrong, probably due to the incorrect boolean check above.

2023-05-26 02:47 UTC, matthewmayer requested changes

2023-05-26 02:47 UTC, matthewmayer commented on src/modules/word/index.ts
> +           *
we should clarify what `none` actually does. For example in some locales, e.g. `de`, certain words are already capitalized (since German always capitalizes nouns)

> fakerDE.word.words()
`'stapfen Elektrizität yowza'`

So in that case would you expect "none" to make everything lowercase? Or just leave it alone.

2023-05-26 02:58 UTC, ZweZeya commented on src/modules/word/index.ts
> +           *
I see..okay, I will add a description explaining that 'none' will leave it alone.

2023-09-17 12:46 UTC, closed without merging