test(docs): disable versions check for external contributors
faker-js/faker pull request #2181
Opened 2023-05-28 15:25 UTC by ST-DDT

Fixes https://github.com/faker-js/faker/pull/2174#issuecomment-1562585163

This disables the versions check for external contributors/those that do not use the faker main repository as their origin.

2023-05-28 15:40 UTC, ST-DDT commented
Result if origin != faker main repo:

![grafik](https://github.com/faker-js/faker/assets/1579362/17e1a3db-3246-4496-90b1-d7b0752ca79e)

Result if origin = faker main repo:

![grafik](https://github.com/faker-js/faker/assets/1579362/4d85bc92-9c89-4a87-88e4-3b4bf980d32d)

2023-05-28 16:31 UTC, Shinigami92 reviewed
Will the CI still check the docs version, even when the PR is on another fork?

2023-05-28 16:31 UTC, Shinigami92 commented on test/docs/versions.spec.ts
> +      originUrl === 'git@github.com:faker-js/faker' ||
Do you think using `originUrl.includes('faker-js/faker')` is sufficient enough?

2023-05-28 17:56 UTC, ST-DDT commented
> Will the CI still check the docs version, even when the PR is on another fork?

Good point. I have to check.

2023-06-03 12:21 UTC, xDivisionByZerox commented on test/docs/versions.spec.ts
> +      originUrl === 'git@github.com:faker-js/faker' ||
I don't think it is as you can technically name your fork however you like. So some name that would match your suggestion would simply be `faker-js/faker-fork`. Correct me if I'm wrong tho.

2023-07-24 18:52 UTC, Shinigami92 commented on test/docs/versions.spec.ts
> +      originUrl === 'git@github.com:faker-js/faker' ||
Yeah, in GitLab you could have that

2023-07-24 19:07 UTC, Shinigami92 requested changes
I could be wrong, but it seems that this PR disables the test when a contributor creates a PR in their own fork. But when we then merge that PR, the test would run on our `next` branch and could then fail.

So this doesn't look like it is the right solution, but sadly I also do not have another idea right now :confused:

2023-09-15 18:59 UTC, Shinigami92 commented
Is the test in our CI always executed via a PR and therefore the origin will always be `faker-js/faker`?
Or does the CI origin run on the fork?

2023-09-15 19:14 UTC, ST-DDT commented
I created #2394 as an external contributor test.

- #2394

2023-09-15 19:20 UTC, Shinigami92 approved these changes
Yes, the test gets executed: https://github.com/faker-js/faker/actions/runs/6201950881/job/16839680435?pr=2394#step:8:110

2023-09-15 19:20 UTC, ST-DDT commented
From #2394 :

https://github.com/faker-js/faker/actions/runs/6201950881/job/16839679994?pr=2394#step:2:39

> git remote add origin https://github.com/faker-js/faker

https://github.com/faker-js/faker/actions/runs/6201950881/job/16839679994?pr=2394#step:8:108

> stdout | unknown test
> https://github.com/faker-js/faker
> 
> ✓ test/docs/versions.spec.ts  (1 test) 6ms

It uses the remote of the target repository as origin.

2023-09-16 19:33 UTC, xDivisionByZerox approved these changes

2023-09-17 12:46 UTC, merged