feat(number): support step on faker.number.int()
faker-js/faker pull request #2188
Opened 2023-05-30 13:19 UTC by leon

Fixes #2186

In faker 7 I could specify
```
faker.datatype.number({ min: 30, max: 200, precision: 10 }) // 140, 90, 180, ...
faker.datatype.number({ min: 5000, max: 20000, precision: 100 }) // 5200, 18500, 12900,...
```

But with faker 8, the precision was removed from int.

```
faker.number.int({ min: 30, max: 200 })
```

### Suggested solution

Allow passing a step to the int faker function

```
faker.number.int({ min: 30, max: 200, step: 10 })
```

2023-05-30 14:47 UTC, matthewmayer requested changes

2023-05-30 14:47 UTC, matthewmayer commented on src/modules/number/index.ts
> +      throw new FakerError(`Step should be a positive number.`);
Should we also throw on a noninteger step?

2023-05-30 14:47 UTC, matthewmayer commented on src/modules/number/index.ts
> +    return effectiveMin + rand * step;
This does not work correctly.

For example `faker.number.int({min:0, max:5, step: 2})` sometimes returns 6.

```
range is (5 - 0)/2 = 2.5
rand is say floor(0.99 * 3.5) = 3
returns 0 + 3 * 2 = 6
```

2023-05-30 15:08 UTC, matthewmayer commented on src/modules/number/index.ts
> +    return effectiveMin + rand * step;
Also per https://github.com/faker-js/faker/pull/1855#issuecomment-1443404570

`faker.number.int({min:5,  max: 100, step: 10})` should return {10, 20, ...} not {5, 15, 25...}

2023-05-30 15:40 UTC, Shinigami92 commented
Marked this for `needs decision` so we have time to discuss in a team meeting how the best way is to solve this and if the current ideas are the "right" way of doing it
The next (full/relevant) team meeting wont be before July 2023

2023-08-19 09:18 UTC, Shinigami92 commented on test/number.spec.ts
> +
line 9 should be extracted and separated together with a new `it` line

2024-01-18 11:51 UTC, ST-DDT commented
Closed in favor of #2586

2024-01-18 11:51 UTC, closed without merging