feat(locale): support street and street address for ja
faker-js/faker pull request #2193
Opened 2023-05-31 13:00 UTC by KeisukeYamashita

Fixed (added) Japanese address output. 

Previously, English addresses were generated incorrectly, but the format has been changed to the correct address format.
Street address example:

```javascript
import { fakerJA as faker } from "@faker-js/faker";

// Before
faker.location.streetAddress() // 5668 杏Square. Incorrect
faker.location.streetAddress(true) // 5668 杏Square. Incorrect

// After
faker.location.streetAddress() // 8丁目7番4号. Correct
faker.location.streetAddress(true) // 9丁目2番3号 木村768号室. Correct
```

Symbols can now be used in street addresses because street names in Japan sometimes contain numbers, but this has no other destructive effect. Of course, not all country road formats include numbers, but I believe they are used in many countries. I supported it because the use of symbols is completely restricted now.

Thank you in advance.

## Disclaimer

I am not a government official or lawyer in charge of Japanese geography. However, in its current state, it is difficult to use it for address dummy data, so a PR was created.

2023-05-31 15:03 UTC, KeisukeYamashita commented
Sorry, the CI failed.
Let me check 🙏

2023-05-31 15:17 UTC, ST-DDT commented
Looks like you forgot to run `pnpm run preflight` 😉 .

2023-05-31 16:03 UTC, matthewmayer requested changes

2023-05-31 16:03 UTC, matthewmayer commented on src/locales/ja/location/street_pattern.ts
> +export default ['#丁目#番#号'];
while it is a little ugly, you could use a pattern like:
```
'{{number.int({"max": 10, "min": 1})}}丁目{{number.int({"max": 10, "min": 1})}}番{{number.int({"max": 10, "min": 1})}}号'
```

This can be used directly by `faker.helpers.fake`, so it's not necessary to change the street() method to use replaceSymbols.

2023-05-31 16:07 UTC, matthewmayer commented
https://en.wikipedia.org/wiki/Japanese_addressing_system

2023-05-31 16:17 UTC, KeisukeYamashita commented on src/locales/ja/location/street_pattern.ts
> +export default ['#丁目#番#号'];
Thank you very much for your kind suggestion, I will update it tomorrow 🙏

2023-06-01 01:24 UTC, KeisukeYamashita commented on src/locales/ja/location/street_pattern.ts
> +export default ['#丁目#番#号'];
@matthewmayer  Thank you very much for your advice, I have updated by this commit 👉 https://github.com/faker-js/faker/pull/2193/commits/18ecd9d04bed1ec326ee520845daba7c5f5c1648

2023-06-01 01:29 UTC, KeisukeYamashita commented
> a83f75a

Thank you very much for your comment, I have ran and push  this commit 👉 https://github.com/faker-js/faker/pull/2193/commits/a83f75ac4f942ae362568294c4eb9f69ecd62551

2023-06-01 02:17 UTC, matthewmayer commented on src/locales/ja/location/street_pattern.ts
> +  '{{number.int({"max": 10, "min": 1})}}丁目{{number.int({"max": 10, "min": 1})}}番{{number.int({"max": 10, "min": 1})}}号',
Is 1...10 the most sensible range for each of these? What numbers do the 丁目, 番 and 号 numbers typically go up to?

2023-06-01 02:28 UTC, KeisukeYamashita commented on src/locales/ja/location/street_pattern.ts
> +  '{{number.int({"max": 10, "min": 1})}}丁目{{number.int({"max": 10, "min": 1})}}番{{number.int({"max": 10, "min": 1})}}号',
It is determined by the local government and can increase or decrease depending on the location, but is almost always in the around single digits.

A city located in a region called Hokkaido, there are more than 40丁目, the largest number in Japan, but it is quite special, and a single digit is a natural address.
This is same to "番地" and "号".

As far as I know, there are no clear rules; it is determined by the history of the location and its management laws.

However, it is usually one digit and I have never seen a double digit street in my life (although it exists).

2023-06-01 02:30 UTC, matthewmayer commented on src/locales/ja/location/street_pattern.ts
> +  '{{number.int({"max": 10, "min": 1})}}丁目{{number.int({"max": 10, "min": 1})}}番{{number.int({"max": 10, "min": 1})}}号',
maybe make the max 9 then?

2023-06-01 02:33 UTC, KeisukeYamashita commented on src/locales/ja/location/street_pattern.ts
> +  '{{number.int({"max": 10, "min": 1})}}丁目{{number.int({"max": 10, "min": 1})}}番{{number.int({"max": 10, "min": 1})}}号',
True, I made an update here 👉 https://github.com/faker-js/faker/pull/2193/commits/93995ded03588e9fbd09282bfb2afdde01b34985
Thank you for your suggestion 🙏

2023-06-01 06:34 UTC, matthewmayer submitted a review, later dismissed

2023-06-01 21:33 UTC, ST-DDT submitted a review, later dismissed

2023-06-01 21:33 UTC, ST-DDT commented on src/locales/ja/location/secondary_address.ts
> +export default ['{{person.last_name}}###号室'];
Here are still the `#` from the previous `replaceSymbol` implementation.

2023-06-01 21:41 UTC, ST-DDT requested changes

2023-06-01 21:41 UTC, ST-DDT commented on src/locales/ja/location/secondary_address.ts
> +export default ['{{person.last_name}}###号室'];
This does not work:

````ts
import { fakerJA } from "@faker-js/faker";

console.log(fakerJA.location.secondaryAddress()); // '{{person.last_name}}522号室'
````

2023-06-02 03:58 UTC, KeisukeYamashita commented on src/locales/ja/location/secondary_address.ts
> +export default ['{{person.last_name}}###号室'];
Oh, let me fix and test it locally 🙏

2023-06-02 05:09 UTC, KeisukeYamashita commented on src/locales/ja/location/secondary_address.ts
> +export default ['{{person.last_name}}###号室'];
@ST-DDT  Thank you very much for catching it 🙏 

As you mentioned, when the `secondaryAddress` method is called directly instead of via `street` (or any other methods that rely on secondary address), the Mustache syntaxes are not parsed.

I have updated to parse Mustache syntaxes on `secondaryAddress` method calls 👉 https://github.com/faker-js/faker/pull/2193/commits/3d5a846779c95ddd72c98b896ece1142a6c1eaca

```typescript
import {fakerJA as faker} from '../src'

console.log(faker.location.secondaryAddress()) // 佐藤167号室, Good!
```

Thank you in advance.

2023-06-04 21:57 UTC, ST-DDT commented on src/modules/location/index.ts
> +    return this.faker.helpers.fake(format);
IMO you can directly pass the template to the fake function.

```suggestion
    return this.faker.helpers
      .fake(this.faker.definitions.location.secondary_address)
      .replace(/#+/g, (m) =>
        this.faker.string.numeric({
          length: m.length,
          allowLeadingZeros: false,
        })
      );
```

2023-06-04 22:18 UTC, KeisukeYamashita commented on src/modules/location/index.ts
> +    return this.faker.helpers.fake(format);
Thank you!

2023-06-28 18:31 UTC, xDivisionByZerox commented on src/locales/ja/location/street_pattern.ts
> +export default ['#丁目#番#号'];
@matthewmayer how is your solution different from the `#` character? I saw that you used `10` as max value but now it is back to 9 which means it should be the same as `#`. Am I having an error in my thought process?

2023-06-29 12:01 UTC, matthewmayer commented on src/locales/ja/location/street_pattern.ts
> +export default ['#丁目#番#号'];
Because it doesn't require any changes to the street method. It's only a ja definitions change.

2023-10-07 09:24 UTC, ST-DDT commented
I think we have to discuss internally if the fake pattern usage here is what we want.

2024-04-04 15:37 UTC, ST-DDT commented
**Team Decision**

- We accept this change. Please rebase so that we can merge this.

2024-04-04 23:03 UTC, KeisukeYamashita commented
Thank you for your consideration!
I've fixed the conflict and updated the main branch. Thanks in advance.

2024-04-05 06:20 UTC, Shinigami92 approved these changes

2024-04-05 06:39 UTC, ST-DDT approved these changes

2024-04-06 17:51 UTC, xDivisionByZerox approved these changes

2024-04-06 17:58 UTC, merged