add browser and os as parameters
faker-js/faker pull request #2211
Opened 2023-06-14 12:52 UTC by adrian-moloca

2023-06-14 14:48 UTC, matthewmayer commented
we discussed before and there seemed to be consensus that the current userAgent implementation is excessively complex and hard to maintain - see https://github.com/faker-js/faker/pull/1761#issuecomment-1406431993 - i think this simplification should probably be prioritised over adding more parameters

2023-06-14 14:49 UTC, matthewmayer commented
btw it looks like you accidentally remove `/dist` from .gitignore which has caused a large number of files to be added to this PR

2023-06-15 06:04 UTC, ST-DDT requested changes

2023-06-15 06:04 UTC, ST-DDT commented on .gitignore
> -/dist
Please revert removing dist from the gitignore.

2023-08-17 15:50 UTC, ST-DDT commented
**Team decision**

The PR looks broken and not updated in a long time.
If you are still interested please create a new feature request issue first.

2023-08-17 15:50 UTC, closed without merging