refactor(git): don't use Intl
faker-js/faker pull request #2222
Opened 2023-06-23 11:14 UTC by matthewmayer

fix #2221 ref #2171

Removes the use of Intl in faker.git.commitDate

2023-07-01 23:55 UTC, xDivisionByZerox approved these changes, later dismissed

2023-07-01 23:55 UTC, xDivisionByZerox commented on src/modules/git/index.ts
> +    const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
I know that the previous version was English only as well. So, just the general question: Should we look into localizing this output in the future?

2023-07-02 05:08 UTC, matthewmayer commented on src/modules/git/index.ts
> +    const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
What does git do?

2023-07-02 05:39 UTC, ST-DDT reviewed
Oh, it looks like I forgot to post these.

2023-07-02 05:39 UTC, ST-DDT commented on src/modules/git/index.ts
> +    const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
Maybe move them to the top of the file as a constant and please also add a comment that these are always the English names and not just some missed i18n part.

2023-07-02 05:40 UTC, ST-DDT commented on src/modules/git/index.ts
> +    const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
See https://github.com/faker-js/faker/pull/2222#discussion_r1239729853

2023-07-02 06:59 UTC, matthewmayer commented on src/modules/git/index.ts
> +    const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
Seems git doesn't localize the dates with the default date option, see

https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-log.html
```
--date=default is the default format, and is based on ctime(3) output. It shows a single line with three-letter day of the week, three-letter month, day-of-month, hour-minute-seconds in "HH:MM:SS" format, followed by 4-digit year, plus timezone information, unless the local time zone is used, e.g. Thu Jan 1 00:00:00 1970 +0000.
```

2023-07-02 09:14 UTC, Shinigami92 requested changes

2023-07-02 09:14 UTC, Shinigami92 commented on test/git.spec.ts
> -        it('should throw if Intl is unavailable', () => {
Please add a "negative"-test case, where we check for `it should not throw or fail in an environment that does not support Intl, like react-native`
And then `mock/spy` or `delete` Intl inside that test

That way we ensure that no other contributor comes alongside and re-implement it
as well as "we officially support non-Intl environments"

2023-07-02 09:46 UTC, matthewmayer commented on test/git.spec.ts
> -        it('should throw if Intl is unavailable', () => {
I feel like this might be better as a lint rule (check there are no usages of Intl) than a test?

2023-07-02 09:48 UTC, matthewmayer commented on src/modules/git/index.ts
> +    const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
I will add a comment, but I think the arrays should probably stay inside this function? These are only used for this specific function to handle git's arcane default date format, we don't want to encourage their use elsewhere.

2023-07-02 10:07 UTC, Shinigami92 commented on test/git.spec.ts
> -        it('should throw if Intl is unavailable', () => {
Would be an acceptable option to me :+1: 

Another idea would be to do it not for this method, but in a global vitest scope, so the whole test-suite does not have access to `Intl` (maybe achievable via global setup)

2023-07-03 07:47 UTC, matthewmayer commented on src/modules/git/index.ts
> +    const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
added comment

2023-07-03 07:47 UTC, matthewmayer commented on test/git.spec.ts
> -        it('should throw if Intl is unavailable', () => {
added eslint rule

2023-07-03 18:02 UTC, Shinigami92 approved these changes

2023-07-04 23:26 UTC, ST-DDT approved these changes

2023-07-14 20:11 UTC, merged