feat(locale): support color and date for zh_CN
faker-js/faker pull request #2223
Opened 2023-06-23 14:01 UTC by Flower-F

support color and date for zh_CN

2023-06-23 17:21 UTC, ST-DDT commented on src/locales/zh_CN/date/weekday.ts
> +
```suggestion
```

2023-06-23 17:21 UTC, ST-DDT approved these changes, later dismissed

2023-06-23 17:22 UTC, ST-DDT commented
Looks good to me. Thanks for your contribution ❤️ !

2023-06-23 20:32 UTC, import-brain submitted a review, later dismissed

2023-06-23 20:33 UTC, import-brain commented
All entries are valid, lgtm

2023-06-24 04:48 UTC, matthewmayer requested changes

2023-06-24 04:48 UTC, matthewmayer commented on src/locales/zh_CN/date/month.ts
> +  abbr: [
You can remove the abbr entry if it's identical to the wide entry.

2023-06-24 05:17 UTC, Flower-F commented on src/locales/zh_CN/date/month.ts
> +  abbr: [
> You can remove the abbr entry if it's identical to the wide entry.

OK. Thanks.

2023-06-24 07:48 UTC, matthewmayer approved these changes, later dismissed

2023-06-24 13:18 UTC, ST-DDT commented on src/locales/zh_CN/date/month.ts
> +  abbr: [
I think this only applies to the *_context variants. Because now CI is red.

2023-06-24 13:25 UTC, Flower-F commented on src/locales/zh_CN/date/month.ts
> +  abbr: [
> I think this only applies to the *_context variants. Because now CI is red.

Yes. I have added the abbr back.

2023-06-24 14:13 UTC, ST-DDT approved these changes

2023-06-24 15:20 UTC, matthewmayer commented on src/locales/zh_CN/date/month.ts
> +  abbr: [
sorry, my bad

2023-06-24 22:22 UTC, import-brain approved these changes

2023-06-25 03:25 UTC, matthewmayer approved these changes

2023-06-25 07:50 UTC, merged

2023-06-25 07:50 UTC, ST-DDT commented
Once again: Thanks for your contribution ❤️

2023-06-25 09:42 UTC, Flower-F commented
> Once again: Thanks for your contribution ❤️
❤️