feat: support custom prngs
faker-js/faker pull request #2284
Opened 2023-07-31 21:26 UTC by ST-DDT

Adds the ability to Faker to use a custom prng.

- Required for #1499
- Implements #2195 

Intended use case for clone and derive:

````ts
  clone(): Faker {
    const instance = new Faker({
      locale: this.rawDefinitions,
      prng: this.prng.clone(),
    });
    instance._mersenne.copyStateFrom(this._mersenne);
    instance.setDefaultRefDate(this._defaultRefDate);
    return instance;
  }

  derive(): Faker {
    const instance = new Faker({
      locale: this.rawDefinitions,
      prng: this.prng.derive(),
    });
    instance.setDefaultRefDate(this._defaultRefDate);
    return instance;
  }
````

(Regardless of whether we will actually have either of them)

Intended use case cross compatibility with other libraries other than faker:

````ts
const prng = newPRNG();
const customFaker = new Faker({ ..., prng });
const randExp = new new RandExp(/no{1,}/, { prng });

prng.setSeed(1337);
customFaker.number.int(); // 1st seed value
randExp.gen(); // 2nd seed value
customFaker.string.sample(); // 3rd seed value
````

Note: Currently faker's internal PRNG isn't exported.

2023-08-05 14:56 UTC, xDivisionByZerox commented on src/internal/mersenne.ts
> +export function newMersennePRNG(): PRNG {
Might be me but I'd prever a name like `generateMersennePRNG` here. `newMersennePRNG` seems like you forgot the space to create a new class instance.

2023-08-06 12:43 UTC, ST-DDT commented
We have to decide whether we want to merge this in v8.x or v9.
If we merge it in v9 we can rename the option/field/type to `random` without breaking things.

2023-08-06 12:43 UTC, ST-DDT commented on src/internal/mersenne.ts
> +export function newMersennePRNG(): PRNG {
Changed

2023-09-07 16:33 UTC, ST-DDT commented
Blocked by #2361

- #2361

2023-09-15 18:53 UTC, Shinigami92 commented
This PR should not be set on-hold, but the other way around: #2361 / #2357 should be set on hold and related to this PR
See the last two days of discussion in #2357

2023-09-15 18:57 UTC, Shinigami92 requested changes

2023-09-15 18:57 UTC, Shinigami92 commented on src/faker.ts
> +    prng?: PRNG;
Please rename this and all related fields to a non abbreviation like `seeder` or `generator`

2023-09-15 19:03 UTC, ST-DDT commented
> This PR should not be set on-hold, but the other way around: #2361 / #2357 should be set on hold and related to this PR See the last two days of discussion in #2357

As mentioned in the team meeting. The exposed API is dependent on the decisions we make for those issues.
I don't like merging a public API PR, when it is likely to require changes or at least a more detailed specification.

2023-09-15 19:05 UTC, Shinigami92 commented
> > This PR should not be set on-hold, but the other way around: #2361 / #2357 should be set on hold and related to this PR See the last two days of discussion in #2357
> 
> As mentioned in the team meeting. The exposed API is dependent on the decisions we make for those issues. I don't like merging a public API PR, when it is likely to require changes or at least a more detailed specification.

Ah ok I see, you want to wait half a week until we all decide and write down that we agree with the `Math.random => [0.0,1.0)` contract 👌

2023-09-15 19:07 UTC, ST-DDT commented on src/faker.ts
> +    prng?: PRNG;
AFAICT `RandomGenerator` is the most upvoted one at this time.

- https://github.com/faker-js/faker/discussions/2308

Is there another poll where seeder/generator are ahead or a decision that I missed?

2023-09-15 19:09 UTC, Shinigami92 commented on src/faker.ts
> +    prng?: PRNG;
The keyword was `like`, I just gave examples
It's more important for me to not use an abbreviation here

2023-09-19 14:46 UTC, Shinigami92 commented on src/faker.ts
> +    prng?: PRNG;
@JessicaSachs, @danielroe and @Shinigami92 accepted `randomizer`

2023-09-20 15:31 UTC, Shinigami92 approved these changes, later dismissed
IMO theoretically this is good to go

- Maybe we need some special docs in the usage guide
- Maybe randomizer should be prefixed with _ or not be a private anymore (it's marked as readonly)
- Maybe the marked doc sentence can be enhanced

but all of that is non-blocking to me

2023-09-20 15:31 UTC, Shinigami92 commented on src/faker.ts
> +   * Only overwrite this if you want to reuse the same Randomizer in different libraries to ensure reproducible results across all of them.
I feel like somehow this sentence should be changed
How about telling that it can be used to e.g. be compatible with external libs 🤔

2023-09-21 11:04 UTC, ST-DDT commented
FFR: Here an example of a [pure-rand](https://github.com/dubzzz/pure-rand) `Randomizer`:

````ts
import { Randomizer } from '@faker-js/faker';
import { RandomGenerator, mersenne } from 'pure-rand';

function generatePureRandRandomizer(
  seed: number | number[] = Date.now() ^ (Math.random() * 0x100000000),
  factory: (seed: number) => RandomGenerator = mersenne
): Randomizer {
  const self = {
    next: () => (self.generator.unsafeNext() >>> 0) / 0x100000000,
    seed: (seed: number | number[]) => {
      self.generator = factory(typeof seed === 'number' ? seed : seed[0]);
    },
  } as Randomizer & { generator: RandomGenerator };
  self.seed(seed);
  return self;
}
````

2023-09-21 13:07 UTC, ST-DDT reviewed
I will create a Usage/Custom Randomizer page soon

2023-09-21 13:07 UTC, ST-DDT commented on docs/.vitepress/api-pages.ts
> +  { text: 'Randomizer', link: '/api/randomizer.html' },
Not sure whether this should be up here or down below next to the `Utilities`.

2023-09-21 13:07 UTC, ST-DDT commented on src/faker.ts
> +   * Only overwrite this if you want to reuse the same Randomizer in different libraries to ensure reproducible results across all of them.
Done

2023-09-21 13:12 UTC, ST-DDT commented
**Docs-Preview**

<details>
<summary>Click to expand</summary>

![grafik](https://github.com/faker-js/faker/assets/1579362/56556a58-39a1-41a3-93d9-613bc53dcb55)
![grafik](https://github.com/faker-js/faker/assets/1579362/b557a150-8e93-414f-843c-5c33cf1b2133)
![grafik](https://github.com/faker-js/faker/assets/1579362/f8256d09-e099-43e7-ba05-ce33362352dc)

</details>

2023-09-22 06:54 UTC, Shinigami92 commented on scripts/apidoc/fakerClass.ts
> +    .filter((clazz) => clazz.name === 'Randomizer')[0];
Is using `find` here not more performant? Instead of traversing the full array and then pick index 0, it would traverse the array until the element is found or reached Nth element
The result should be the same here

2023-09-22 06:54 UTC, Shinigami92 commented on src/randomizer.ts
> + *   } as Randomizer & { state: number; step: number };
```suggestion
 *   const self: Randomizer & { state: number; step: number } = {
 *     next: () => {
 *       self.state += self.step;
 *       return (self.state %= 1);
 *     },
 *     seed: (seed) => {
 *       const value = typeof seed === 'number' ? seed : seed[0];
 *       const cleaned = value.toString().replace(/[^\d]+/g, '');
 *       self.step = +('1.' + clean) / 2 + 0.26183095653171535;
 *       self.state = 0.8683615301373573 * self.step + 0.24476001502354827;
 *     },
 *   };
```

or 

```suggestion
 *   const self = {
 *     next: () => {
 *       self.state += self.step;
 *       return (self.state %= 1);
 *     },
 *     seed: (seed) => {
 *       const value = typeof seed === 'number' ? seed : seed[0];
 *       const cleaned = value.toString().replace(/[^\d]+/g, '');
 *       self.step = +('1.' + clean) / 2 + 0.26183095653171535;
 *       self.state = 0.8683615301373573 * self.step + 0.24476001502354827;
 *     },
 *   } satisfies Randomizer & { state: number; step: number };
```

2023-09-22 06:59 UTC, ST-DDT commented on scripts/apidoc/fakerClass.ts
> +    .filter((clazz) => clazz.name === 'Randomizer')[0];
Is there an lint rule for that?

2023-09-22 07:34 UTC, matthewmayer requested changes

2023-09-22 07:34 UTC, matthewmayer commented on src/randomizer.ts
> + * @example
We should explain more what these example randomizers are for. I think there is a danger people will copy-paste this code without understanding that these are toy/broken examples. We can show examples of how to hook into multiple third-party libraries, and warn that in most cases you should stick to the built-in Randomizer unless you have specific needs.

2023-09-22 09:11 UTC, ST-DDT commented on src/randomizer.ts
> + *   } as Randomizer & { state: number; step: number };
Both result in type incompatibility errors.

2023-09-22 09:21 UTC, ST-DDT commented on src/randomizer.ts
> + * @example
I'll adjust the related locations.

Should we explicitly mention one or two random libraries here?
Should we replace our current examples with one for e.g. pure-rand?

2023-09-22 12:01 UTC, Shinigami92 commented on scripts/apidoc/fakerClass.ts
> +    .filter((clazz) => clazz.name === 'Randomizer')[0];
We could try https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-array-find.md

`eslint-plugin-unicorn` is build by @fisker
He is working with me in the prettier and eslint ecosystem alot! Maybe we should consider using unicorn, I never used that plugin before, but it has official support by eslint-define-config

2023-09-22 12:03 UTC, Shinigami92 commented on src/randomizer.ts
> + * @example
You have green light from my side to mention pure-rand here ✅

2023-09-22 12:09 UTC, fisker commented on scripts/apidoc/fakerClass.ts
> +    .filter((clazz) => clazz.name === 'Randomizer')[0];
> I never used that plugin before

Give it a try, there are lots of good stuff. 😄

2023-09-22 12:14 UTC, Shinigami92 commented on src/randomizer.ts
> + *   } as Randomizer & { state: number; step: number };
Okay, I have to check this in IDE
The current (TS-safetyness) solution does not feel right to me 😕

2023-09-22 12:51 UTC, ST-DDT commented on src/randomizer.ts
> + * @example
Changed the example to use that.

2023-09-22 13:13 UTC, matthewmayer requested changes

2023-09-22 13:13 UTC, matthewmayer commented on src/randomizer.ts
> + * Created instances are expected to be seeded on creation.
what does this sentence mean? expected to be seeded on creation by ... the Randomizer? the calling code that instantiates the Randomizer? Seeded with what value?

2023-09-22 13:17 UTC, matthewmayer requested changes

2023-09-22 13:17 UTC, matthewmayer commented on src/randomizer.ts
> + * }
can we make this into a full example by then instantiating a Faker object with the newly created Randomizer?

2023-09-22 14:28 UTC, ST-DDT commented on src/randomizer.ts
> + * Created instances are expected to be seeded on creation.
How about:

```suggestion
 *
 * Instances are expected to be ready for use before being passed to any Faker constructor,
 * this includes being `seed()`ed with either a random or fixed value.
```

?

2023-09-22 14:29 UTC, ST-DDT commented on src/randomizer.ts
> + * }
Done

2023-09-22 17:13 UTC, matthewmayer submitted a review, later dismissed

2023-09-22 17:13 UTC, matthewmayer commented on src/randomizer.ts
> + * import { RandomGenerator, mersenne } from 'pure-rand';
maybe use a non-mersenne generator from pure-rand instead? e.g. xoroshiro128plus (replacing one Mersenne implementation with another doesn't seem so useful)

2023-09-22 21:37 UTC, ST-DDT commented on src/randomizer.ts
> + * import { RandomGenerator, mersenne } from 'pure-rand';
Changed

2023-09-22 21:40 UTC, ST-DDT commented
Note to self:

> I will create a Usage/Custom Randomizer page soon

2023-09-23 16:48 UTC, Shinigami92 approved these changes, later dismissed

2023-09-23 17:17 UTC, Shinigami92 commented on scripts/apidoc/fakerClass.ts
> +    .filter((clazz) => clazz.name === 'Randomizer')[0];
I'm working on it in #2417

- #2417

2023-09-23 23:07 UTC, xDivisionByZerox commented on src/randomizer.ts
> +   * Generates a random float between `[0, 1)`.
We where discussing that some developers might not know what the "P" in "PRNG" stands for, so they might get confused if we named the faker constructor property like that. Might be a bit too far but should we consider that not every developer knows this mathmatic syntax or at least get thrown off by it? I just want to make sure that dev that use our library get the best possible DX. Tell me if you think that I'm making stuff harder than it might be.

2023-09-23 23:07 UTC, xDivisionByZerox commented on src/randomizer.ts
> +   * This method is called `next` so that it could be used as an [iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterator_protocol).
This statement as t is now is not true. If you would currently try to use an object, that satisfies the `Randomizer` interface, in a `for..of` loop you will get an Error: 
`Type 'Randomizer' must have a '[Symbol.iterator]()' method that returns an iterator.ts(2488)`

Additionally, out `next()` signature is incompatible with the one of an `Iterator` as it is expected to return an object containing the keys `value` and `done`.

That being said, the original idea behind the "next" name was to align with the iterator protocol. But I#m not sure if we should mention this here for now.

2023-09-23 23:07 UTC, xDivisionByZerox commented on src/randomizer.ts
> +/**
Since this is a file that only exports an interface, should it be a `*.d.ts` file? Otherwise if would get compiled into a JS file and being included in our final bundle without actually doing anything.  Not sure how this usally works TBH.

2023-09-24 03:36 UTC, matthewmayer commented on src/randomizer.ts
> +   * Generates a random float between `[0, 1)`.
"between 0 (inclusive) and 1 (exclusive)."

"greater or equal to 0, and less than 1."

2023-09-24 14:10 UTC, ST-DDT commented on src/randomizer.ts
> +   * Generates a random float between `[0, 1)`.
Changed

2023-09-24 14:12 UTC, ST-DDT commented on src/randomizer.ts
> +   * This method is called `next` so that it could be used as an [iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterator_protocol).
I removed that section.

2023-09-24 14:20 UTC, ST-DDT commented on src/randomizer.ts
> +/**
Well, our build tools take care of that anyway.
ESM doesn't ship it, CJS ships it as an empty module, the types are generated as expected.
I think there isn't a need to rename the file right now.
Maybe we put the default and legacy generator functions in here (or maybe even the default generator instance).

2023-09-24 21:39 UTC, xDivisionByZerox submitted a review, later dismissed

2023-09-30 00:59 UTC, matthewmayer commented
Should we add an example of how you go from a prebuilt localised Faker instance (say fakerEN_GB) to a version with a custom randomizer? That may not be that intuitive as I think you'd have to drop the prebuilt instance and use manual fallback locales in order to access the Faker constructor.

2023-09-30 08:08 UTC, ST-DDT commented
Could you please write it in pseudocode? I'm not sure what you are asking for.

2023-09-30 14:53 UTC, matthewmayer commented
```
// if you are currently using a prebuilt version of Faker 
import {fakerEN_GB as faker} from '@faker-js/faker';
console.log(faker.location.city())

// you will need to manually construct a new Faker instance with the correct fallback languages
// and then you can set a custom randomizer function
import { Faker, en, en_GB, base } from '@faker-js/faker';
const faker2 = new Faker({
  locale: [en_GB, en, base],
  randomizer: yourCustomRandomizerFunction
})
console.log(faker2.location.city())
```

2023-09-30 15:15 UTC, ST-DDT commented
I think adding the Faker constructor with some ommissions should be plenty. Maybe we should add a link to the constructor though.

````ts
Const faker2 = new Faker({
  locale: ...,
  randomizer: newRandomizer(),
});
````

And `@see Faker#constructor`

2023-10-01 04:28 UTC, matthewmayer commented
It's more guiding people that they cannot simply do something like 

fakerEN_GB.randomizer = ...

2023-10-02 21:22 UTC, ST-DDT commented
Here the updated screenshots for the documentation:

<details>
<summary>Click to expand</summary>

http://localhost:5173/api/randomizer.html

![grafik](https://github.com/faker-js/faker/assets/1579362/38a3f5c1-da59-4087-9fde-218395a108fe)
![grafik](https://github.com/faker-js/faker/assets/1579362/b37f7ee7-1d64-4a5b-a2b8-66fd45b87803)
![grafik](https://github.com/faker-js/faker/assets/1579362/9c4bc3e7-cc55-49fa-9fab-3f2581a27b4f)

http://localhost:5173/guide/randomizer.html

![grafik](https://github.com/faker-js/faker/assets/1579362/b736b3b1-b295-4d05-a130-5d83f6e1059d)
![grafik](https://github.com/faker-js/faker/assets/1579362/3b834299-ae41-498f-a73b-da10536e0081)
![grafik](https://github.com/faker-js/faker/assets/1579362/a0ed6668-bab8-4609-822e-1c0ac78376c6)
![grafik](https://github.com/faker-js/faker/assets/1579362/94113f06-13d8-4d82-8e54-44766285847c)
![grafik](https://github.com/faker-js/faker/assets/1579362/aaf5e0db-57cd-4695-8929-9129491acb14)

</details>

2023-10-03 02:39 UTC, matthewmayer approved these changes

2023-10-03 06:38 UTC, dubzzz commented
From the updated documentation you sent, the API looks great. I'm looking forward to connect it 🥰

2023-10-03 12:25 UTC, xDivisionByZerox approved these changes

2023-10-04 16:13 UTC, merged

2024-07-18 15:46 UTC, dubzzz commented
I want to thank you all for this awesome feature.

It unlocks a better integration of Faker within fast-check as detailed in this [article](https://fast-check.dev/blog/2024/07/18/integrating-faker-with-fast-check/).

If you read it and have some remarks, please let me know, I'll be happy to discuss and fix them.