chore(helpers): deprecate regexpStyleStringParse
faker-js/faker pull request #2290
Opened 2023-08-05 08:52 UTC by import-brain

closes #1985

2023-08-05 15:47 UTC, xDivisionByZerox approved these changes, later dismissed

2023-08-05 18:47 UTC, matthewmayer requested changes
Should we add something to the migration guide about this? Because helpers.fromRegExp is not a complete replacement for helpers.regexpStyleStringParse

For example fromRegExp can't handle numeric ranges, it only has character ranges?
```js
faker.helpers.regexpStyleStringParse("a[1-100]") // a53 etc
faker.helpers.fromRegExp("a[1-100]") //a1 or a0
```

2023-08-06 23:20 UTC, matthewmayer requested changes

2023-08-06 23:20 UTC, matthewmayer commented on docs/guide/upgrading.md
> +faker.helpers.fromRegExp("a[1-100]") // "a1" or "a0"
I think we need to explain instead how to get back the numeric range feature if you were previously relying on that behavior.

2023-08-07 08:34 UTC, ST-DDT reviewed
Is this a breaking change? Because `replaceCreditCardSymbols` behaves different for
`"[0-100]L"` inputs now.

2023-08-07 08:34 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    string = this.fromRegExp(string); // replace [4-9] with a random number in range etc...
Have you checked whether any of our existing patterns uses the old logic?

2023-08-07 08:34 UTC, ST-DDT commented on src/modules/helpers/index.ts
>    ): string {
The description still contains ``range patterns `[4-9]` ``. IMO we should adjust that to ``regex patterns `[4-9]` ``.

2023-08-07 09:09 UTC, matthewmayer commented
replaceCreditCardSymbols should probably continue to use the old method until the next major version bump then.

2023-08-07 09:50 UTC, ST-DDT commented
> replaceCreditCardSymbols should probably continue to use the old method until the next major version bump then.

We don't call deprecated methods from non-deprecated ones. So we would have to delay this entire PR to v9 then.

2023-08-07 17:57 UTC, matthewmayer commented
Could soft deprecate it without formally marking it as deprecated. 

Add a comment to the description encouraging the use of the new method and referring to the migration guide. 

Then deprecate in v9 and remove in v10

2023-08-08 18:58 UTC, import-brain commented
> Could soft deprecate it without formally marking it as deprecated. 
> 
> Add a comment to the description encouraging the use of the new method and referring to the migration guide. 
> 
> Then deprecate in v9 and remove in v10

This is a good compromise. Should we go ahead with this?

2023-08-17 18:02 UTC, ST-DDT commented
**Team decision**

We will deprecate the method immediately and "inline" the mod in the remaining usages.
(Alternatively, using an internal helper method that isn't exported)
The original method will be removed in v9.

The inlined method might be rendered obsolete by adjusting the patterns or just switching to fromRegexp in v9 or when implementing:

- https://github.com/faker-js/faker/issues/2303

2023-08-22 19:36 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  protected regexpStyleStringParse_(string: string = ''): string {
Maybe mark this as `@internal`?

2023-08-23 04:26 UTC, matthewmayer commented on src/modules/helpers/index.ts
>    ): string {
Maybe 4-9 is a regex pattern but say 1-100 is not. You can't do numeric ranges in regex.

2023-08-26 13:54 UTC, ST-DDT commented on test/support/seededRuns.ts
> +      }
Is it possible to call `skip` instead?

2023-08-27 19:14 UTC, import-brain commented
I'm pretty sure I'm using `skip` incorrectly, I can't get the tests to pass...

2023-08-27 20:51 UTC, ST-DDT commented on test/support/seededRuns.ts
> +        this.skip('regexpStyleStringParse_');
Close, I was referring to putting it to the actual spec file instead of here 😉

2023-08-27 20:54 UTC, ST-DDT commented on test/support/seededRuns.ts
> +      // @ts-expect-error: Argument of type 'string' is not assignable to parameter of type 'MethodOf<TModule>'.
IMO this shouldn't tell what it hides but why.

```suggestion
      // @ts-expect-error: The method is protected and thus invisible in this scope
```

2023-08-27 20:56 UTC, ST-DDT commented on test/support/seededRuns.ts
> +      // @ts-expect-error: Argument of type 'string' is not assignable to parameter of type 'MethodOf<TModule>'.
Can you move this code to the actual spec file please?

2023-08-27 21:08 UTC, ST-DDT commented
> I'm pretty sure I'm using `skip` incorrectly, I can't get the tests to pass...

I think the vitest `it` block overwrites `this`.

2023-09-04 07:23 UTC, ST-DDT approved these changes, later dismissed

2023-09-04 19:22 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +  protected regexpStyleStringParse_(string: string = ''): string {
Why not use a plain function which gets a faker instance as argument? In that case we would not need the confusing test workaround.

2023-09-05 00:14 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +  protected regexpStyleStringParse_(string: string = ''): string {
Maybe also name it something like legacyRegexpStringParse so it's clearer what it does and that it will eventually be removed

2023-09-05 15:31 UTC, ST-DDT commented
I think a plain function refers to a standalone function instead of a class function here.

2023-09-06 06:27 UTC, ST-DDT reviewed
Otherwise this looks good to me. Thanks.

2023-09-06 06:27 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * This method supports both regex patterns `[4-9]` as well as the patterns used by `replaceSymbolWithNumber()`.
```suggestion
   * This method supports both range patterns `[4-9]` as well as the patterns used by `replaceSymbolWithNumber()`.
```

While this looks like regex it isnt yet.

2023-09-06 06:38 UTC, matthewmayer requested changes
Propose adding back a section into upgrading.md similar to the following:

### `faker.helpers.regexpStyleStringParse` deprecated in favor of `faker.helpers.fromRegExp`

The `regexpStyleStringParse` method in `faker.helpers` has been deprecated in Faker 8.1. A likely replacement is the more powerful `faker.helpers.fromRegExp`. 

```js
faker.helpers.regexpStyleStringParse("a{3,6}") // aaaaa
faker.helpers.fromRegExp("a{3,6}") // aaaaa
```

However, please note that `faker.helpers.fromRegExp` is not an exact replacement for `faker.helpers.regexpStyleStringParse` as `fromRegExp` cannot handle numeric ranges. This would now need to be handled seperately.

```js
faker.helpers.regexpStyleStringParse("a{3,6}[1-100]") // "aaaa53", etc.
faker.helpers.fromRegExp("a{3,6}") + faker.number.int({min:1, max:100})
```

2023-09-06 20:39 UTC, ST-DDT submitted a review, later dismissed

2023-09-10 03:23 UTC, matthewmayer approved these changes, later dismissed

2023-09-10 08:41 UTC, ST-DDT approved these changes, later dismissed

2023-09-10 08:41 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +  //TODO: implement for letters e.g. [0-9a-zA-Z] etc.
I think it is safe to remove the TODO here.

2023-09-10 11:36 UTC, matthewmayer approved these changes

2023-09-10 11:42 UTC, Shinigami92 approved these changes

2023-09-10 11:42 UTC, Shinigami92 commented on docs/guide/upgrading.md
> +faker.helpers.fromRegExp('a{3,6}'); // aaaaa
<img src="https://media.tenor.com/oQBk2zzwYBgAAAAC/aaaa-cat.gif" width="200px" />

:rofl:

2023-09-10 11:42 UTC, ST-DDT approved these changes

2023-09-10 11:53 UTC, merged