fix(module): faker.image.dataUri is not random #2307
faker-js/faker pull request #2316
Opened 2023-08-14 10:28 UTC by OmkarPednekar

If color option is not provided the code will use a randomly generated color code as default color

2023-08-14 11:02 UTC, matthewmayer commented on src/modules/image/index.ts
> +       * @default 'random color'
this makes it look as if the default value is the literal string `a random color`. I'd either change it to 

`
@default a random color
`

or omit the default value completely, and mention in the description that the color will be random unless specified.

2023-08-14 11:04 UTC, OmkarPednekar commented on src/modules/image/index.ts
> +       * @default 'random color'
Ok, will do the changes

2023-08-14 11:11 UTC, OmkarPednekar commented on src/modules/image/index.ts
> +       * @default 'random color'
![image](https://github.com/faker-js/faker/assets/74041929/047015d7-6bbb-4bd4-a66a-e67d97858b08)
 is this okay?

2023-08-14 11:11 UTC, ST-DDT commented
I just noticed, that `dataUri` doesn't have seeded tests, so I created a PR for that.

Blocked by:

- https://github.com/faker-js/faker/pull/2317

2023-08-14 11:14 UTC, OmkarPednekar commented
is this okay? 
![image](https://github.com/faker-js/faker/assets/74041929/0bc122bc-5cb8-4a71-b5da-3c99eae994dc)

2023-08-14 11:16 UTC, ST-DDT commented
> is this okay? ![image](https://user-images.githubusercontent.com/74041929/260433226-0bc122bc-5cb8-4a71-b5da-3c99eae994dc.png)

I would probably phrase it like this:

`The color of the image. Must be a color supported by svg. Defaults to a random color.`

2023-08-14 11:17 UTC, OmkarPednekar commented
Okay

2023-08-14 11:18 UTC, ST-DDT commented on src/modules/image/index.ts
> +      color = this.faker.color.rgb({ prefix: '#' }),
```suggestion
      color = this.faker.color.rgb(),
```

2023-08-14 11:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +       * @default 'random color'
Other methods use:

````ts
@default faker.color.rgb()
````

2023-08-14 11:44 UTC, OmkarPednekar commented
Please Check

2023-08-14 12:03 UTC, ST-DDT requested changes

2023-08-14 12:03 UTC, ST-DDT commented on src/modules/image/index.ts
> +       * The color of the image. Must be a color supported by svg. Defaults to a random color.
Don't forget to change the `@param` docs above.

2023-08-14 12:12 UTC, OmkarPednekar commented
Made the changes in @param as well

2023-08-14 14:04 UTC, OmkarPednekar commented on src/modules/image/index.ts
> +       * The color of the image. Must be a color supported by svg. Defaults to a random color.
Done

2023-08-14 16:36 UTC, OmkarPednekar commented
![image](https://github.com/faker-js/faker/assets/74041929/e11c9b72-7cc5-4c24-967c-9e0678b3888f)
Update the Docs

2023-08-14 19:48 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * @param options.color The color of the image. Defaults to a random color.
Both the `@param` description and the field description should be the same/similar.

```suggestion
   * @param options.color The color of the image. Must be a color supported by svg. Defaults to a random color.
```

2023-08-14 19:48 UTC, ST-DDT commented on src/modules/image/index.ts
> +       * The color of the image. Must be a color supported by svg. Defaults to a random color.
```suggestion
       * The color of the image. Must be a color supported by svg.
```

The `@default` already covers the `Defaults to` part.

2023-08-14 19:48 UTC, ST-DDT commented on test/modules/image.spec.ts
> +      expect(dataUri).toMatch(expectedPattern);
Please inline the expected pattern.

2023-08-14 19:48 UTC, ST-DDT commented on test/modules/image.spec.ts
> +      expect(dataUri).toMatch(expectedPattern);
Maybe also check that the string contains the given width and height.

2023-08-14 19:48 UTC, ST-DDT commented on test/modules/image.spec.ts
>      it('should return a background color data URI', () => {
Maybe use the `expectedPattern` like check here as well (in addition to the snapshot)?

2023-08-15 13:50 UTC, OmkarPednekar commented on src/modules/image/index.ts
> +       * The color of the image. Must be a color supported by svg. Defaults to a random color.
okay

2023-08-15 14:00 UTC, OmkarPednekar commented on test/modules/image.spec.ts
>      it('should return a background color data URI', () => {
in this testcase 'should return a background color data URI' ?

2023-08-15 14:10 UTC, OmkarPednekar commented on test/modules/image.spec.ts
>      it('should return a background color data URI', () => {
![image](https://github.com/faker-js/faker/assets/74041929/7721162c-3cec-46fd-b2f6-0567ae06fa3d)
Made changes to the description and also added the testcase for checking width and height to both tests

2023-08-15 14:15 UTC, ST-DDT commented on test/modules/image.spec.ts
> +      expect(dataUri).toMatch(/width%3D%22200%22%20height%3D%22300/);
Don't forget to check for the color.

2023-08-15 14:28 UTC, OmkarPednekar commented on test/modules/image.spec.ts
> +      expect(dataUri).toMatch(/width%3D%22200%22%20height%3D%22300/);
Added the check for color.

2023-08-15 14:53 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * @param options.color The color of the image. Defaults to a random color.
Looks like you forgot this one. Or did you mark this as resolved intentionally?

2023-08-15 15:11 UTC, OmkarPednekar commented on src/modules/image/index.ts
> +   * @param options.color The color of the image. Defaults to a random color.
Oh! So sorry I totally missed this one

2023-08-15 15:12 UTC, OmkarPednekar commented on src/modules/image/index.ts
> +   * @param options.color The color of the image. Defaults to a random color.
The color of the image. Must be a color supported by svg. it should be this right? same as description

2023-08-15 15:16 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * @param options.color The color of the image. Defaults to a random color.
Plus the `Defaults to ...` part because that's not present in the `@param` block.

2023-08-15 15:18 UTC, ST-DDT approved these changes, later dismissed

2023-08-17 10:32 UTC, OmkarPednekar commented
any updates on the review @matthewmayer

2023-08-17 11:23 UTC, matthewmayer commented
It's quite normal that PRs will take weeks or months before merging even if they are fine. Don't worry 😀

2023-08-17 12:05 UTC, OmkarPednekar commented
Okay Got It and also why is this one test failing?

2023-08-17 12:45 UTC, ST-DDT commented
> Okay Got It and also why is this one test failing?

Fixed

2023-08-17 18:15 UTC, ST-DDT commented
We added some (forgotten) seeded tests to ensure the values generated by this method are reproducible.
Please run `pnpm run preflight` to update the values.

2023-08-18 08:55 UTC, OmkarPednekar commented
> We added some (forgotten) seeded tests to ensure the values generated by this method are reproducible. Please run `pnpm run preflight` to update the values.

So i have to do this and then  commit again?

2023-08-18 10:01 UTC, OmkarPednekar commented
why are these checks failing?

2023-08-18 10:14 UTC, ST-DDT commented
> why are these checks failing?

The (new) seeded tests should highlight changed results caused by a refactoring/change.
This PR changes the behavior of the method (slightly) thus the  test snapshots need to be updated.

2023-08-18 10:14 UTC, ST-DDT approved these changes, later dismissed

2023-09-09 20:53 UTC, xDivisionByZerox submitted a review, later dismissed

2023-09-09 20:59 UTC, xDivisionByZerox commented
@OmkarPednekar Please resolve the merge conflicts if possible.

2023-09-09 23:57 UTC, import-brain submitted a review, later dismissed

2023-09-15 19:49 UTC, ST-DDT approved these changes, later dismissed

2023-09-15 19:50 UTC, ST-DDT commented
I fixed the merge conflicts myself to speed up the merge process.

2023-09-15 19:56 UTC, Shinigami92 approved these changes, later dismissed

2023-09-15 20:14 UTC, ST-DDT submitted a review, later dismissed

2023-09-15 20:17 UTC, Shinigami92 submitted a review, later dismissed

2023-09-15 20:17 UTC, Shinigami92 commented
👀

2023-09-15 20:41 UTC, OmkarPednekar commented
Why are these tests failing?

2023-09-15 20:41 UTC, ST-DDT commented
I fixed the random seeded tests using test snapshots.

2023-09-15 20:46 UTC, ST-DDT commented
> Why are these tests failing?

Because the tests use snapshots which would work fine if the result is static, but this PR changes them to be random thus failing the tests. I fixed them by not using the static snapshots and instead check via validatorjs's isDataUri.

2023-09-15 20:46 UTC, ST-DDT approved these changes

2023-09-15 20:47 UTC, OmkarPednekar commented
> > Why are these tests failing?
> 
> Because the randomized tests used snapshots which would work fine if the result is static, but this PR changes them to be random thus failing the tests. I fixed them by not using the static snapshots and instead check via validatorjs's isDataUri.

But I had removed those test cases and changed them to match the changes

2023-09-15 20:48 UTC, ST-DDT commented
> But I had removed those test cases and changed them to match the changes

https://github.com/faker-js/faker/pull/2273 added new ones.

- https://github.com/faker-js/faker/pull/2273

2023-09-15 20:50 UTC, OmkarPednekar commented
> > But I had removed those test cases and changed them to match the changes
> 
> #2273 added new ones.
> 
> * [feat(image): add image dataUri with base64 #2273](https://github.com/faker-js/faker/pull/2273)

Oh I seee so how can we fix this failing tests?

2023-09-15 20:50 UTC, ST-DDT commented
> Oh I seee so how can we fix this failing tests?

I already removed/fixed them.

2023-09-15 20:51 UTC, OmkarPednekar commented
> > Oh I seee so how can we fix this failing tests?
> 
> I already removed/fixed them.

No I meant the merge checks

2023-09-15 20:52 UTC, ST-DDT commented
> No I meant the merge checks

Not sure what you are referring to.

![grafik](https://github.com/faker-js/faker/assets/1579362/8188b54b-fe34-4d72-8e8c-d4da964b3f53)

2023-09-15 20:52 UTC, Shinigami92 approved these changes

2023-09-15 20:52 UTC, OmkarPednekar commented
> > No I meant the merge checks
> 
> Not sure what you are referring to.
> 
> ![grafik](https://user-images.githubusercontent.com/1579362/268393143-8188b54b-fe34-4d72-8e8c-d4da964b3f53.png)

Oh whatt just a moment ago they were appearing failed lol

2023-09-17 08:44 UTC, merged