feat(locale): Fully Improve zh_TW
faker-js/faker pull request #2320
Opened 2023-08-15 00:48 UTC by CoolPlayLin

# Works
- Add color module
- Add date module

2023-08-15 15:03 UTC, ST-DDT submitted a review, later dismissed

2023-08-15 15:25 UTC, ST-DDT commented
Please run `pnpm run preflight`.

2023-08-15 23:27 UTC, CoolPlayLin commented
@ST-DDT It appears this isn't my issue. It was caused in Comment

2023-08-16 15:45 UTC, ST-DDT approved these changes

2023-08-17 17:48 UTC, ST-DDT requested changes

2023-08-17 17:48 UTC, ST-DDT commented on src/locales/zh_TW/location/default_country.ts
> +export default ['中國臺灣'];
**Team decision**

We were informed that this value might be politically sensitive.
As we aren't ourselves into this topic and the file is currently unused outside of the unconfirmed use via `fake`, we would like to keep the file as is (even if it is wrong), that way we are able to merge this PR faster.
We can then change this file in a separate PR later with focused community feedback.

For now, please revert this file. Sorry, for the trouble.

2023-08-18 04:52 UTC, matthewmayer approved these changes

2023-08-18 07:20 UTC, ST-DDT approved these changes

2023-08-19 01:21 UTC, CoolPlayLin commented
@Shinigami92 @xDivisionByZerox @import-brain Could you review this for me?

2023-08-19 03:27 UTC, matthewmayer commented
It is quite normal that PRs in the Faker project can take weeks to get reviewed and merged even if they are 100% fine. 

You don't need to do anything, the maintainers will notify you if any changes are needed.

2023-08-19 07:04 UTC, import-brain approved these changes

2023-08-19 07:45 UTC, ST-DDT commented
> It is quite normal that PRs in the Faker project can take weeks to get reviewed and merged even if they are 100% fine.

I wouldnt limit this to Faker or OpenSource specifically. It is just a mater of available time and priorities.

2023-08-20 06:46 UTC, merged

2023-08-20 06:47 UTC, ST-DDT commented
Thanks for your contribution. ❤️