feat(locale): add da person category
faker-js/faker pull request #2331
Opened 2023-08-21 09:32 UTC by stonor

2023-08-21 09:38 UTC, matthewmayer requested changes
*

2023-08-21 09:38 UTC, matthewmayer commented on src/locales/da/person/female_first_name.ts
What's the source for the names? https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md#sourcing-data-for-definitions

2023-08-21 09:38 UTC, matthewmayer commented on src/locales/da/person/name.ts
> +    value: '{{person.firstName}} {{person.middleName}} {{person.lastName}}',
Are middle names typically different to first names in Danish?

2023-08-21 09:45 UTC, stonor commented on src/locales/da/person/name.ts
> +    value: '{{person.firstName}} {{person.middleName}} {{person.lastName}}',
Yes. We have a set of typical middlenames such as Nord, Skov, Holm, Jul. It is also common to have two first names and two last names.

2023-08-21 10:00 UTC, matthewmayer commented
```
> fakerDA.helpers.multiple(x=>fakerDA.person.fullName(), {count:50})
[
  'Jonathan Birk Abdi',
  'Luna Steffensen',
  'Christopher Krog Beckmann',
  'Uffe Hedegaard',
  'David Husum Dalgaard',
  'Oliver Justesen',
  'Ida Davidsen',
  'Elias Dal Schmidt',
  'Jonathan Schrøder-Munk',
  'Dorit Kjær Bertelsen',
  'Lukas Lorentzen',
  'Laila Frederiksen',
  'Ahmad Holm Thomsen',
  'Elise Fischer-Esbensen',
  'Rasmus Bak',
  'Frida Nygaard',
  'Lisbeth Esbensen',
  'Magnus Bjerre Haugaard',
  'Søren Grøn Frederiksen',
  'Jonas Iversen',
  'Tine Klit Richter',
  'Ida Esbensen',
  'Nicoline Krog Vestergaard',
  'Susanne Hald Juhl',
  'Nadia Fischer',
  'Tim Husum Jensen',
  'Emilie Klausen',
  'Maja Smed Bisgaard',
  'Erik Hald Garcia',
  'Lene Klit Møller',
  'Jørgen Dahl Dalgaard',
  'Mille Mortensen',
  'Adam Villadsen',
  'Silje Nord Mortensen',
  'Lukas Husum Blom',
  'Gry Feldt Frandsen-Johannessen',
  'Thomas Klausen',
  'Dorthe Feldt Brandt',
  'Anders Dal Dupont',
  'Pia Svendsen',
  'Jacob Andersen-Johansen',
  'Annette Bjerg Magnussen',
  'Zara Smed Jespersen',
  'Mark Kjær Jensen',
  'Sebastian Bundgaard Hjorth',
  'Frederik Nissen',
  'Hakim Rasmussen',
  'Poul Bjerg Haugaard',
  'Oscar Beckmann',
  'Hedvig Lund'
]
```
```
fakerDA.helpers.multiple(x=>fakerDA.person.fullName({sex:"female"}), {count:50})
[
  'Tine Christiansen',
  'Sandra Buhl',
  'Ruth Mose Kristensen',
  'Bente Frandsen',
  'Nadia Madsen',
  'Viktoria Klit Bang',
  'Nanna Rasmussen',
  'Maja Smed Nygaard',
  'Gitte Buhl',
  'Ruth Haugaard',
  'Alice Karlsen',
  'Alma Munk',
  'Yasmin Pallesen',
  'Britt Jeppesen',
  'Ruth Jespersen',
  'Annette Kjær Fischer',
  'Ella Marcussen',
  'Maren Mose Hjort',
  'Christina Husum Jespersen',
  'Hedvig Holm Kristensen',
  'Louise Birk Pham-Bech',
  'Malene Frost Christensen',
  'Ruth Thomsen',
  'Nadia Koch Christensen',
  'Lillian Krog Iversen',
  'Simone Rosen Dalgaard',
  'Sanne Schrøder',
  'Kirsten Dam Villadsen',
  'Ella Mølgaard Garcia',
  'Luna Østergaard Dahl',
  'Line Bundgaard Kristensen',
  'Johanne Bjerg Pallesen',
  'Lene Jensen',
  'Ditte-Marie Husum Dupont',
  'Marianne Præst Jeppesen',
  'Lisbeth Krog Laursen',
  'Liv Ravn',
  'Louise Smed Buhl',
  'Rebecca Pedersen',
  'Rebecca Kjær',
  'Rosa-Maria Foged',
  'Sofie Vestergaard',
  'Freja Bundgaard Vestergaard',
  'Rosa-Maria Linde Vinther',
  'Josefine Mose Villadsen',
  'Betina Ravn',
  'Laila Marcussen',
  'Camilla Feldt Haugaard',
  'Lillian Lorentzen',
  'Rosa-Maria Mølgaard Jeppesen'
]
```
```
> fakerDA.helpers.multiple(x=>fakerDA.person.fullName({sex:"male"}), {count:50})
[
  'Peter Marcussen-Bjerregaard',
  'Steen Vestergaard',
  'John Kristensen',
  'Linus Feldt Lauridsen',
  'Victor Smed Fischer',
  'Magnus Bundgaard Dahl',
  'Per Skov Khan',
  'Lars Marcussen',
  'Adrian Præst Fischer',
  'Jacob Klit Nguyen',
  'Peter Steffensen',
  'Viggo Birk Lorentzen',
  'Jacob Smed Blom',
  'Karl Holm Lauridsen',
  'August Laursen',
  'Philip Johannessen',
  'Ulrik Linde Bruun',
  'Søren Buch',
  'Kurt Mortensen',
  'Viktor Blom',
  'Oliver Khan',
  'Jørgen Nord Dahl',
  'Martin Skov Nygaard',
  'Oscar Kjeldsen',
  'Anton Iversen-Nissen',
  'Ib Jeppesen',
  'Linus Lund',
  'Jan Carlsen',
  'Brian Winther',
  'Ib Smed Lund',
  'Philip Jul Hermansen',
  'Victor Hjort-Bonde',
  'Max Beckmann',
  'Bjørn Østergaard Vinther',
  'Jonathan Jespersen',
  'Christopher Linde Gade',
  'Albert Richter',
  'Patrick Bundgaard Krogh',
  'Uffe Koch Pedersen',
  'Jens Mortensen',
  'Albert Jul Beckmann',
  'Tim Klausen',
  'Brian Smed Richter-Laursen',
  'Stig Østergaard Abdi-Villadsen',
  'Jonas Bjerg Karlsen',
  'Elliot Rasmussen',
  'Mohammad Hedegaard',
  'Jesper Lund Rasmussen-Hjort',
  'Sune Christiansen',
  'Kim Dalgaard'
]
```

2023-08-21 10:15 UTC, stonor commented on src/locales/da/person/female_first_name.ts
I've sampled names from:

- Most popular names from Statistics Denmark (https://www.dst.dk/da/Statistik/emner/borgere/navne/navne-i-hele-befolkningen)
- My own contacts

2023-08-21 10:57 UTC, ST-DDT commented on src/locales/da/person/male_middle_name.ts
You don't need this file, as it will fall back to `middle_name.ts`.

2023-08-21 10:57 UTC, ST-DDT commented on src/locales/da/person/female_middle_name.ts
You don't need this file, as it will fall back to `middle_name.ts`.

2023-08-21 11:49 UTC, stonor commented on src/locales/da/person/male_middle_name.ts
I've tried to remove it and now I'm getting English middle names, e.g. 


```
> faker.helpers.multiple(x=>faker.person.fullName({sex:"male"}), {count:5})
[
  'Vincent Ellis Nguyen',
  'Benjamin Owen Juhl-Krogh',
...
]
```

Neither Ellis nor Owen are on the Danish middle name list. 

However, this works:

```
> faker.helpers.multiple(x=>faker.person.middleName({sex:"male"}), {count:5})
[ 'Kjær', 'Hjorth', 'Skov', 'Feldt', 'Holm' ]

```
What to do?

2023-08-21 16:40 UTC, ST-DDT commented on src/locales/da/person/male_middle_name.ts
You can keep the file. I forgot about this issue/required future change: https://github.com/faker-js/faker/issues/1677

Sorry for my invalid review.

2023-08-21 16:40 UTC, ST-DDT approved these changes

2023-08-23 02:37 UTC, import-brain approved these changes

2023-08-23 14:38 UTC, stonor commented
> 

Hi Matt,

Maybe I'm missing something, but  could you explain a bit what kind of change you want me to do before this pull request is ready for merge?

2023-08-23 15:04 UTC, matthewmayer approved these changes

2023-08-23 15:04 UTC, matthewmayer commented
Sorry didn't see it was still blocking. Approved.

2023-08-26 09:26 UTC, Shinigami92 approved these changes
The PR title is misleading
You did not add a category to person, you added new data for person in da locale

So please adjust the PR title before merging, but then we are good to go

2023-08-26 12:52 UTC, merged