feat(locale): Add more module for zh_CN
faker-js/faker pull request #2332
Opened 2023-08-21 10:56 UTC by CoolPlayLin

# Works
- Add bio module for zh_CN
- Add animal module for zh_CN [WIP]

2023-08-21 11:00 UTC, ST-DDT submitted a review, later dismissed

2023-08-21 11:14 UTC, CoolPlayLin commented
@ST-DDT It appears the first failure is due to action itself

2023-08-21 12:00 UTC, matthewmayer requested changes

2023-08-21 12:00 UTC, matthewmayer commented on src/locales/zh_CN/person/bio_pattern.ts
> +  '{{word.noun}} {{person.bio_supporter}}, {{person.bio_part}} {{internet.emoji}}',
Probably remove the space between the noun and the bio_supporter?

2023-08-21 12:00 UTC, matthewmayer commented on src/locales/zh_CN/animal/type.ts
> +export default ['bear', 'cat', 'dog', 'fish', 'horse'];
Should be translated?

2023-08-21 12:58 UTC, matthewmayer commented
You can mark the pull request as Draft if it's still work in progress.

2023-08-22 06:52 UTC, ST-DDT commented
Please stay below 20 files.

2023-08-22 09:30 UTC, CoolPlayLin commented
@ST-DDT Done

2023-08-22 09:45 UTC, matthewmayer approved these changes

2023-08-25 02:13 UTC, CoolPlayLin commented
@ST-DDT @import-brain

2023-08-25 06:41 UTC, ST-DDT commented
> @ST-DDT @import-brain

Please be patient. We are currently busy and dont have time to review this PR. Don't worry we haven't forgotten about it and will get to it soon.

2023-08-27 20:46 UTC, ST-DDT reviewed
I found a few words that I'm unable to check.
Maybe someone with better search or translate skills can enlighten me here.

2023-08-27 20:46 UTC, ST-DDT commented on src/locales/zh_CN/word/adjective.ts
> +  '骨碌碌',
I couldn't find a translation for this. "Gululu"/"Bone Lulu"?

2023-08-27 20:46 UTC, ST-DDT commented on src/locales/zh_CN/word/verb.ts
> +  '咀',
Same here. "Tsui"?

2023-08-27 20:46 UTC, ST-DDT commented on src/locales/zh_CN/word/verb.ts
> +  '披',
Same here. "Phi"? Here there are a few alternatives, but they confuse me even more what it actually means.

2023-08-28 00:49 UTC, CoolPlayLin commented
@ST-DDT 
1. 骨碌碌：This term is often used to describe the rapid movement of the eyeballs.
2. 披：
>Wear/Wearing: "披" can mean to wear or wearing, such as wearing a robe or wearing a blanket. For example, "He is wearing a red coat."
>
>Cover/Covering: "披" can also mean to cover or covering, like wearing a cape or letting hair down. For example, "She used a cape to cover her body."
>
>Hang On: "披" can be used to indicate hanging something on the body, such as hanging a sword sheath or hanging a signboard. For example, "The soldier hung his sword sheath in preparation for departure."
>
>Take On: In some idiomatic expressions, "披" can signify taking on a role or responsibility, such as "披荆斩棘" (facing difficulties bravely) or "披星戴月" (enduring hardships). For example, "He bravely faced difficulties and completed the challenging task."
>
>Reveal/Revealing: Sometimes, "披" can also mean revealing or spreading, such as revealing information or spreading a message. For example, "He revealed an important discovery."
>
>Spread/Spreading: In some contexts, "披" can convey the idea of spreading or disseminating, such as spreading news with a cloak or spreading a message. For example, "He spread news far and wide using a cloak."
3. 咀
>Chew: "咀" can mean the action or process of chewing food. For example, "他正在咀东西" can be translated as "He is chewing something," indicating the action of chewing food.
>
>Savor/Contemplate: "咀" can also represent savoring or contemplating a problem, often used in conjunction with "味" (taste). For instance, "他在咀味这个难题" can be translated as "He is contemplating this difficult problem."
>
>Argue/Debate: In certain idiomatic expressions, "咀" can indicate arguing or debating, such as in "咀咒," which means to argue or quarrel. For example, "他们咀咒不休" can be translated as "They are constantly arguing."
>
>Oral Communication: Sometimes, "咀" can also represent oral communication, as seen in "咀咒," where "咀" signifies oral. For instance, "他们之间的咀咒是激烈的" can be translated as "The oral exchange between them is intense."

2023-08-28 00:52 UTC, CoolPlayLin commented on src/locales/zh_CN/word/adjective.ts
> +  '骨碌碌',
This is a Chinese slang, You couldn't translation directly

2023-08-28 00:57 UTC, CoolPlayLin commented
I think google it directly is a good way to find meaning
![image](https://github.com/faker-js/faker/assets/96709586/27ee8487-c97f-4b7c-834c-90ef1be6805b)

2023-08-28 12:24 UTC, ST-DDT approved these changes

2023-08-30 05:27 UTC, import-brain approved these changes

2023-08-30 06:26 UTC, merged