feat(locale): add finance module for zh_CN
faker-js/faker pull request #2338
Opened 2023-08-23 10:48 UTC by CoolPlayLin

2023-08-26 13:49 UTC, ST-DDT commented on src/locales/zh_CN/finance/credit_card/unionpay.ts
> +export default ['62##-####-####-####L', '62##-####-####-####-###L'];
> The China UnionPay credit card numbers begin with 62 or 60 and is a 16-19 digit long number. 

- The patterns for 60 are missing
- The short pattern is 17 characters and the later one is 20 characters.

According to https://docs.trellix.com/bundle/data-loss-prevention-11.10.x-classification-definitions-reference-guide/page/GUID-B8D29ECE-E70A-401E-B18D-B773F4FF71ED.html

Please also write a test that ensures that fakerZH_CN generates valid union pay credit cards using validatorjs's `isCreditCard`

2023-09-01 12:04 UTC, CoolPlayLin commented
I don't know why test fails

2023-09-01 12:27 UTC, ST-DDT commented
> creditCardNumber() > should generate a valid union pay credit card

I asked the original author of the validatorjs PR for more information:

- https://github.com/validatorjs/validator.js/pull/2008#issuecomment-1702662126

2023-09-10 01:36 UTC, CoolPlayLin commented
New replied in
- https://github.com/validatorjs/validator.js/pull/2008#issuecomment-1702885368

2023-09-10 02:10 UTC, CoolPlayLin commented
I've found the regex of union pay validation
```yaml
unionpay: /^(6[27][0-9]{14}|^(81[0-9]{14,17}))$/
```

2023-09-10 02:28 UTC, CoolPlayLin commented
I don't know how to write the first format, I only wrote the second format just now

2023-09-10 03:31 UTC, matthewmayer commented
You can just write them as two formats: 62###... and 67###...

2023-09-10 03:40 UTC, CoolPlayLin commented on src/locales/zh_CN/finance/credit_card/unionpay.ts
> +export default ['62##-####-####-####L', '62##-####-####-####-###L'];
It appears validator missed between 18 characters and 20 characters with 60 and 62 patterns

2023-09-10 07:54 UTC, matthewmayer requested changes

2023-09-10 07:54 UTC, matthewmayer commented on test/modules/finance.spec.ts
> +import validator from 'validator';
instead of importing the whole module can do 

```import isCreditCard from 'validator/lib/isCreditCard';```

2023-09-16 02:56 UTC, matthewmayer approved these changes, later dismissed

2023-09-17 02:02 UTC, CoolPlayLin commented
@ST-DDT It is able to remove `do NOT merge yet` now 🤔

2023-09-17 09:01 UTC, ST-DDT commented
Please rebase this PR to include the latest changes.

2023-09-17 21:14 UTC, import-brain submitted a review, later dismissed

2023-09-23 01:50 UTC, CoolPlayLin commented
done

2023-09-23 08:52 UTC, ST-DDT approved these changes
Assuming the validator is correct, this looks good to me.

2023-09-23 10:11 UTC, matthewmayer approved these changes

2023-09-23 17:16 UTC, import-brain approved these changes

2023-09-23 17:45 UTC, merged