feat(locale): update hacker phrases, add extras
faker-js/faker pull request #2340
Opened 2023-08-24 18:23 UTC by jamesjsdev

A minor feature update to hacker phrases.

2023-08-26 09:23 UTC, Shinigami92 commented on src/modules/hacker/index.ts
> +   * @since 8.0.2
A new function wont land in a bug-fix release. This should be at minimum 8.1.0.

2023-08-26 13:26 UTC, ST-DDT requested changes
Please split the feature update (and related locale additions) into a separate PR.

2023-10-07 09:13 UTC, ST-DDT commented
@larasoftsolutions Can you please do the requested changes please?

2023-10-07 12:36 UTC, matthewmayer requested changes

2023-10-07 12:36 UTC, matthewmayer commented on src/locales/base/hacker/abbreviation.ts
> +  'RTFM',
Let's remove this one as we normally try to avoid profanity

2023-10-30 09:47 UTC, ST-DDT commented
@jamesbuch Could you please apply the requested changes?

2023-11-07 23:38 UTC, ST-DDT commented
Closing this PR as stale. If you are still interested in this PR please update it and apply the requested changes, then we can reopen this PR or open a new one.

2023-11-07 23:38 UTC, closed without merging