fix: mersenne and number function precision loss
faker-js/faker pull request #2357
Opened 2023-08-29 21:11 UTC by ST-DDT

Fixes #2355

- #2355

## To Fix

- [x] fix/reduce duplicates returned from `faker.number.int()` and `faker.number.float()`
- [ ] fix faker.number.int() only returning even numbers

## To Check

- [ ] `MersenneTwister19937.genrandInt32()` returning `[0,2^32)` or `0` and `2^32-1` specifically
	- Maybe by try and error 
- [ ] `MersenneTwister19937.genrandInt53()` returning `[0,2^53)` or `0` and `2^53-1` specifically
	- By faking the result of `genrandInt32()`
- [ ] `MersenneTwister19937.genrandRes53CO()` returning `[0,1)` or `0` and not `1` specifically
	- By faking the result of `genrandInt53()`
- [ ] `MersenneTwister19937.genrandRes53CC()` returning `[0,1]` or `0` and `1` specifically
	- By faking the result of `genrandInt53()`
- [ ] `faker.number.int()` should return numbers with 53 bit precision `[0,2^53)` or `0` and `2^53-1` specifically + extra check for odd numbers
	- By faking the result of `faker._mersenne.next()`
- [ ] `faker.number.float()` returning `[0,1]` or `0` and `1` specifically
	- By faking the result of `faker._mersenne.next()`

2023-08-30 05:23 UTC, matthewmayer commented
Probably also worth checking if genrandRes53CC is significantly slower, or if there are any other downsides to using it.

2023-08-30 06:13 UTC, ST-DDT commented
It's twice as slow.

2023-08-30 13:37 UTC, matthewmayer commented
I think this should be probably considered a breaking change given it causes nearly every snapshot to change. That would also allow for beta testing of the change before 9.0 in case the slower algorithm causes performance problems.

2023-08-30 13:59 UTC, ST-DDT commented
The breaking of the snapshots is caused by `next()` now effectively taking 2 values from the seed.
We could reduce this if we dynamically request either 32/53 bits of precision depending on the values in use.
e.g. an array with length 15 doesn't need 53 bits of precision for the index.

2023-08-30 14:02 UTC, ST-DDT commented
I'm not that deep into math, but for some reason using two values from the seed increases the variance of the values.
Which causes the likelihood of this test to fail: https://github.com/faker-js/faker/actions/runs/6025687970/job/16346941314?pr=2357

2023-08-30 14:53 UTC, ST-DDT commented
> I'm not that deep into math, but for some reason using two values from the seed increases the variance of the values. Which increase likelihood of this test to fail: [faker-js/faker/actions/runs/6025687970/job/16346941314?pr=2357](https://github.com/faker-js/faker/actions/runs/6025687970/job/16346941314?pr=2357)

Nevermind, I found the error, currently the first and the last element aren't evenly distributed for number.int()

2023-08-31 16:19 UTC, ST-DDT commented
**Team Decision**

We will change mersenne to 53 bit precision to reduce the duplicates and create a separate PR for the float issues.

2023-08-31 18:02 UTC, ST-DDT commented on test/internal/mersenne/twister.spec.ts
> +    });
This is my favorite test in this PR. 😉 
It only took 80 CPU hours to find that seed...

Currently smallest known return value `20` for seed `147377213`.

2023-08-31 18:02 UTC, ST-DDT commented on test/internal/mersenne/twister.spec.ts
> +      expect(actual).toBeGreaterThan(0.9999999999);
Should we check for this instead?

```suggestion
      expect(actual).toBe(0.9999999999999999);
```

2023-09-01 15:38 UTC, ST-DDT commented
Reduced to only cover the most minimal required changes.

2023-09-01 15:47 UTC, Shinigami92 commented on test/modules/date.spec.ts
> +      expect(date).toMatchInlineSnapshot('2019-02-25T21:52:41.819Z');
I might have oversee something, but through these `toMatchInlineSnapshot` changes, we lost the check whether date is a string or actually a Date instance

2023-09-01 18:24 UTC, ST-DDT commented on test/modules/date.spec.ts
> +      expect(date).toMatchInlineSnapshot('2019-02-25T21:52:41.819Z');
That's not what the test is about.

2023-09-01 18:26 UTC, xDivisionByZerox commented on test/modules/date.spec.ts
> +      expect(date).toMatchInlineSnapshot('2019-02-25T21:52:41.819Z');
Then we can simply extend the test:
```suggestion
      expect(date).toBeInstanceOf(Date);
      expect(date).toMatchInlineSnapshot('2019-02-25T21:52:41.819Z');
```

2023-09-01 18:28 UTC, xDivisionByZerox commented on test/modules/helpers.spec.ts
> +      expect(unique).toMatchInlineSnapshot(`
This should now be `toStrictEqual` again, no?

2023-09-01 18:32 UTC, ST-DDT commented on test/modules/helpers.spec.ts
> +      expect(unique).toMatchInlineSnapshot(`
I'm not sure what you refer to.

2023-09-06 07:41 UTC, xDivisionByZerox commented on test/modules/date.spec.ts
> +      expect(date).toMatchInlineSnapshot('2019-02-25T21:52:41.819Z');
Why do we use inline snapshots here if all other snapshots have their own file? Is there an advantage for one or the other?

2023-09-06 07:41 UTC, xDivisionByZerox commented on test/modules/helpers.spec.ts
> +      expect(unique).toMatchInlineSnapshot(`
I was questioning why we need a snapshot test here since we set the seed manually. This means that the expected value should always stay as it is now. That's why I thought we should use `toStrictEqual` instead of a snapshot test here. Unless I'm missing something.

2023-09-06 08:19 UTC, ST-DDT commented on test/modules/date.spec.ts
> +      expect(date).toMatchInlineSnapshot('2019-02-25T21:52:41.819Z');
As you can see the value changes whenever we work on the mersenne definitions. But I can change it back if you would like.

2023-09-06 08:48 UTC, xDivisionByZerox commented on test/modules/date.spec.ts
> +      expect(date).toMatchInlineSnapshot('2019-02-25T21:52:41.819Z');
The reason why I don't want a snapshot is that it will automatically get updated with all other snapshots. That would lead to a reviewer being more likely to skip over this specific one if it will get updated for some unknown reason. That's at least what I think. Am I overthrowing thus?

2023-09-06 08:57 UTC, ST-DDT commented on test/modules/helpers.spec.ts
> +      expect(unique).toMatchInlineSnapshot(`
Thats another reason why I used inline snapshots: to have it more obvious something changed because it is in the test file and not part of the huge snapshot file.

2023-09-07 01:10 UTC, matthewmayer commented
Could we still allow access to the original 32-bit Mersenne  generator via the new #2195 feature? Then if someone prefers the original implementation (e.g. if speed is more importrant than occasional duplicates) they still have that option.

2023-09-07 16:38 UTC, ST-DDT commented
> Could we still allow access to the original 32-bit Mersenne generator via the new #2195 feature? Then if someone prefers the original implementation (e.g. if speed is more importrant than occasional duplicates) they still have that option.

Could you please describe the usecase for/idea behind this proposal?
We already have a guess why you suggest that, but we would like to know whether we might have forgotten something.

If we go that route, then this would be blocked by #2284 which is blocked by #2361.

2023-09-07 17:06 UTC, matthewmayer commented
Speed. You said this implementation is twice as slow? So if I'm generating millions of fake names I don't want it to be slower than before.

2023-09-07 17:39 UTC, dubzzz commented
> twice as slow

Why not backing the library by an official prng generator tailored for performance like: [pure-rand](https://www.npmjs.com/package/pure-rand)? It would probably allow the faker team to rather focus on generators themselves while keeping the optimization of random number generators into other libraries (this one is used by Jest).

_You can also choose to copy the implem from the lib I just shared but it sounds less sustainable. The implem is much faster than the one in faker (from my benchs)_

Cc @ST-DDT

2023-09-07 18:02 UTC, ST-DDT commented
@dubzzz A disclaimer that you are a/the maintainer of that library would have been nice.

> You can also choose to copy the implem from the lib I just shared but it sounds less sustainable. 

Copying a well maintained lib doesn't sound like a good idea to me either.

> The implem is much faster than the one in faker (from my benchs)

Does your implementation provide the full 53 bits of precision possible with JS?

2023-09-07 18:10 UTC, dubzzz commented
> A disclaimer that you are a/the maintainer of that library would have been nice.

Sorry, I forgot to underline it. There are many others if you want.

> Does your implementation provide the full 53 bits of precision possible with JS?

Not really. The generator itself generate 32bits value in an uniform way. But I do have helpers to generate values in an uniform way on larger ranges (see `unsafeUniformIntDistribution` for 53bits and the ones with ArrayInt for above).

2023-09-07 18:15 UTC, ST-DDT commented
> > A disclaimer that you are a/the maintainer of that library would have been nice.
> 
> Sorry, I forgot to underline it. There are many others if you want.

No problem. We will have to discuss the choice of library internally anyway (if we go that route).

2023-09-07 18:16 UTC, matthewmayer commented
While it looks like a very nice library it's also maintained by one person. Given the history of the project Faker deliberately has many maintainers (and currently no dependencies).

2023-09-07 18:19 UTC, ST-DDT commented
@dubzzz Do you have a test checking that the default implementation can return `0x00000000` and `0xffffffff`respectively?

e.g. https://github.com/faker-js/faker/blob/a73653436dfbaf4a005dfc6913ecf0668b134c1d/test/internal/mersenne/twister.spec.ts#L19-L23

2023-09-07 18:24 UTC, dubzzz commented
I don't think so. But I have test checking that it outputs the exact same set of values as the implementation of Mersenne Twister of the C++ standard and other tests. I can check the min/max.

2023-09-07 18:35 UTC, Shinigami92 commented
Speaking from my absolutely personal perspective:
I've looked through your profile and I like what I see :slightly_smiling_face: 
[pure-rand](https://github.com/dubzzz/pure-rand) also do not have sub-dependencies (which is a good thing :+1:)
It is purely naively written in TypeScript :sparkles: 
So the only "bad" thing is that you are a one-man army (https://github.com/dubzzz/pure-rand/graphs/contributors) and Faker and its history ... anyways ... :sweat_smile: 

But I have one question: @dubzzz why did you have such a spike suddenly in your downloads?
<img src="https://github.com/faker-js/faker/assets/7195563/93e46aca-48ac-4d38-a5bd-3a9725d4c5e1" width="300px" />

2023-09-07 21:11 UTC, dubzzz commented
> why did you have such a spike suddenly in your downloads?

@Shinigami92 The spike is due to Jest, they started to use pure-rand internally. At some point in time they have been looking for a library to generate random numbers. So I suggested to rely on pure-rand, as I contributed several times to the project and as they have been using my other library fast-check for quite some time to test some of their internals they went for pure-rand. Actually when I suggested the library I also checked the alternatives in both maintenance level and download rates and the one I found were a bit below.

> While it looks like a very nice library it's also maintained by one person. Given the history of the project Faker deliberately has many maintainers (and currently no dependencies).

> Speaking from my absolutely personal perspective: I've looked through your profile and I like what I see 🙂

@matthewmayer @Shinigami92 Honestly, it was mostly an idea: choice is definitely fully yours.

For the record, my only query was to have a way to connect an external pnrg into faker as described into https://github.com/faker-js/faker/issues/2195. The initial query is still opened whatever your choice as it may unlock some usages I can have of faker: I want to provide a plugin fast-check (my other lib) to faker, which will be able to use faker, but to do so I'll have to be able to customize the instance of prng being used by faker.

That's said, let me know if I can help.

> A disclaimer that you are a/the maintainer of that library would have been nice.

And once again, sorry @ST-DDT. By the way I updated my original message to make it clearer.

2023-09-08 10:05 UTC, matthewmayer commented
#2195 still seems like the best way to handle this. We could have a page in the docs explaining how to plug in pure-rand (or other popular libraries) to make it very easy to use without adding a dependency.

2023-09-13 23:09 UTC, ST-DDT commented
What is left to do here? AFAICT nothing.
Is this going to be v8 or v9?

2023-09-14 02:51 UTC, matthewmayer commented
Changing the default random generator should definitely be v9. Allowing opt in to a 53 bit mersenne generator using #2195 could be in v8.

2023-09-14 03:47 UTC, Shinigami92 commented
> Changing the default random generator should definitely be v9. Allowing opt in to a 53 bit mersenne generator using #2195 could be in v8. 

I slightly agree, and I would also prio it like that.

In last team meet we decided that the `generator.next()` function should fulfill `Math.random()`'s `[0.0,1.0)`, and IMO this should be documented and added first before moving on and fixing this bug, due to we then would need additional tests here in this PR.

2023-09-14 06:46 UTC, ST-DDT commented
> In last team meet we decided that the `generator.next()` function should fulfill `Math.random()`'s `[0.0,1.0)`

Did we? The meeting notes dont contain a decision for that.

2023-09-15 05:32 UTC, Shinigami92 commented
⚠️ something horrible came to my mind tonight ⚠️

I would like to kindly ask if we first could prioritize the feature to provide a custom `seeder` / `generator`, because Faker is not only used for tests, but also generating e.g. seeding data to a database instance with e.g. `faker.string.uuid()` while relying on a constant defined seed value!
So if we would just merge this PR and do not provide the functionality to switch manually back to v8.0 behavior, it would not be possible anymore at all to recreate that seeded data.

So either this PR lands in v9 as a communicated breaking feature or we first merge / prioritize the customizable `seeder` / `generator`

2023-09-15 07:06 UTC, ST-DDT commented
Sure, lets talk about the specifics in the next team meeting.

Please keep in mind that we currently do not provide a guarantee to generate the same values on updates.

2023-09-15 07:21 UTC, Shinigami92 commented
> Sure, lets talk about the specifics in the next team meeting.
> 
> 
> 
> Please keep in mind that we currently do not provide a guarantee to generate the same values on updates.

While this is true, it mostly just affected localized stuff and not fundamentally changed the ground.
I for example do not rely on generating localized values in production, but use `faker.string.uuid` or `faker.helpers.arrayElements` with own defined data for populate production database.
The more I think about it, the more I think that my approach of doing so is insecure and I should try to do backup and handmade migrations instead of relying on a seed value 🤔

2023-09-15 07:56 UTC, matthewmayer commented
Agreed. Changing the mersenne implementation causes every faker method to return different values for a fixed seed so it should definitely be considered a breaking change.

2023-09-16 02:49 UTC, matthewmayer commented
> Please keep in mind that we currently do not provide a guarantee to generate the same values on updates.

True but I think there's a big difference between "we added a few new dog breeds so now faker.animal.dog returns different values" vs "every method now returns different values"

2024-02-08 18:39 UTC, ST-DDT commented
Ready for review.

2024-02-19 21:09 UTC, Shinigami92 approved these changes, later dismissed

2024-02-20 08:48 UTC, matthewmayer requested changes

2024-02-20 08:48 UTC, matthewmayer commented on docs/guide/upgrading_v9/2357.md
> +  For `faker.number.int()` this reduces the duplicates from `1/10k` to less than `1/8kk`.
kk is not a common abbreviation. Million?

2024-02-20 08:48 UTC, matthewmayer commented on docs/guide/upgrading_v9/2357.md
> +  If then generator previously generated `1,2,3,4,5`, it now generates `1,3,5,7,9`.
This seems a weird example. It doesn't look random.

2024-02-20 13:35 UTC, matthewmayer requested changes

2024-02-20 13:35 UTC, matthewmayer commented on docs/guide/upgrading_v9/2357.md
> +  randomizer: generateMersenne32Randomizer(),
Should we show how to import generateMersenne3Randomizer()?

2024-02-21 18:02 UTC, ST-DDT commented on docs/guide/upgrading_v9/2357.md
> +  If then generator previously generated `1,2,3,4,5`, it now generates `1,3,5,7,9`.
![grafik](https://github.com/faker-js/faker/assets/1579362/8eada8fe-ac1d-48fb-8821-f326c297a054)
or
![grafik](https://github.com/faker-js/faker/assets/1579362/c503bd05-f331-490f-9c69-1f1b6f3112c8)

With or without imports?

2024-02-21 18:02 UTC, ST-DDT commented on docs/guide/upgrading_v9/2357.md
> +  randomizer: generateMersenne32Randomizer(),
If I add them above should I add them below again?

2024-02-21 18:12 UTC, ST-DDT commented
![grafik](https://github.com/faker-js/faker/assets/1579362/875dea20-c94c-40f7-96c4-6b40c8641bc0)

2024-02-26 12:32 UTC, Shinigami92 commented on test/modules/helpers.spec.ts
> +      expect(unique).toMatchInlineSnapshot(`
I think @xDivisionByZerox is right here.  
The inline snapshot would indicate to me "yeah something has changes, take the new one"
Whereas here it should fail if something has changed so we can see in vitests report what failed

2024-02-26 13:24 UTC, matthewmayer requested changes

2024-02-26 13:24 UTC, matthewmayer commented on docs/guide/randomizer.md
> +The 32bit `Randomizer` is faster, but the 53bit `Randomizer` generates better random values (with significantly less duplicates).
"less" should be "fewer"

2024-02-26 13:24 UTC, matthewmayer commented on docs/guide/upgrading_v9/2357.md
> +- Some seeded runs now return slightly different values, due to the last digits of random numbers changing,
This seems a bit vague. Does any method now return different values for a given seed?

2024-02-26 14:43 UTC, ST-DDT commented on docs/guide/randomizer.md
> +The 32bit `Randomizer` is faster, but the 53bit `Randomizer` generates better random values (with significantly less duplicates).
```suggestion
The 32bit `Randomizer` is faster, but the 53bit `Randomizer` generates better random values (with significantly fewer duplicates).
```

2024-02-26 14:49 UTC, ST-DDT commented on docs/guide/upgrading_v9/2357.md
> +- Some seeded runs now return slightly different values, due to the last digits of random numbers changing,
Yes, just have a look at all the changed snapshot files.

2024-02-26 15:15 UTC, matthewmayer commented on docs/guide/upgrading_v9/2357.md
> +- Some seeded runs now return slightly different values, due to the last digits of random numbers changing,
Maybe change last sentence to something like

Many Faker methods will return a different result in v9 compared to v8 for the same seed.

2024-02-26 15:43 UTC, ST-DDT commented on docs/guide/upgrading_v9/2357.md
> +- Some seeded runs now return slightly different values, due to the last digits of random numbers changing,
Changed and reworded

2024-02-26 16:09 UTC, Shinigami92 approved these changes, later dismissed

2024-02-27 01:05 UTC, matthewmayer approved these changes, later dismissed

2024-02-27 16:45 UTC, xDivisionByZerox submitted a review, later dismissed

2024-02-27 19:24 UTC, ST-DDT commented
3 approving reviews. Enabling auto merge.

2024-02-27 19:56 UTC, Shinigami92 approved these changes

2024-02-27 19:57 UTC, merged