feat(locale): add yo locale, start with person
faker-js/faker pull request #2363
Opened 2023-08-31 22:19 UTC by mrsimi

- added yo locale starting with the addition of the person module. 
- added a folder for location and a street_name file because the test was not passing.

2023-09-01 04:36 UTC, matthewmayer requested changes

2023-09-01 04:36 UTC, matthewmayer commented on src/locales/yo/person/first_name.ts
> +  'Busayo',
are these first names gender neutral? Or are they a mix of male and female names. If its just a mix, then we generally just do this in the first_name file:

```
import { mergeArrays } from './../../../internal/merge';
import female_first_name from './female_first_name';
import male_first_name from './male_first_name';

export default mergeArrays(female_first_name, male_first_name);
```

2023-09-01 04:36 UTC, matthewmayer commented on src/locales/yo/person/female_first_name.ts
> +  'Aanuoluwapo',
sort names alphabetically in all files unless there's a strong reason not to.

2023-09-01 04:39 UTC, matthewmayer requested changes

2023-09-01 04:39 UTC, matthewmayer commented on src/locales/yo/index.ts
> +/*
locale/folder name should be yo_NG not yo assuming there will be Nigeria-specific addresses, phone numbers etc added in future PRs

2023-09-01 06:58 UTC, ST-DDT commented on src/locales/yo/index.ts
> +/*
How many countries speak yo language?

2023-09-01 07:12 UTC, matthewmayer commented on src/locales/yo/index.ts
> +/*
Wikipedia says its spoken commonly in Benin and Togo also

2023-09-01 07:33 UTC, mrsimi commented on src/locales/yo/person/first_name.ts
> +  'Busayo',
Yes the names are gender neutral.

2023-09-01 07:42 UTC, ST-DDT commented on src/locales/yo_NG/metadata.ts
> +  title: 'Yoruba',
If this is specifically for Nigeria, this should be reflected in the title and endonym.

2023-09-01 07:44 UTC, ST-DDT commented on src/locales/yo/index.ts
> +/*
@mrsimi Do you know whether the person and street names etc are the same for most of the yo countries?

2023-09-01 07:55 UTC, mrsimi commented on src/locales/yo/index.ts
> +/*
The person names are predominantly the same, but not the street names, etc. because in the Yoruba language spoken in Nigeria for example the street names are based on the happens or an event that occurred in a particular area.

2023-09-01 07:55 UTC, mrsimi commented on src/locales/yo/person/female_first_name.ts
> +  'Aanuoluwapo',
This has been completed

2023-09-01 07:59 UTC, mrsimi commented on src/locales/yo_NG/metadata.ts
> +  title: 'Yoruba',
Completed

2023-09-01 11:47 UTC, ST-DDT approved these changes, later dismissed

2023-09-01 11:52 UTC, matthewmayer requested changes

2023-09-01 11:52 UTC, matthewmayer commented on src/locales/yo_NG/location/street_name.ts
> +export default ['Olaiya'];
instead of this dummy file you can add yo_NG to the list of excluded locales for the test in test/all_functional_spec.ts line 72

2023-09-01 11:54 UTC, matthewmayer requested changes

2023-09-01 11:54 UTC, matthewmayer commented on src/locales/yo_NG/metadata.ts
> +  endonym: 'Yoruba (Nigeria)',
endonym should be written in the language itself, ie something like `'Yorùbá (Nàìjíríà)'`

2023-09-01 15:01 UTC, mrsimi commented on src/locales/yo_NG/location/street_name.ts
> +export default ['Olaiya'];
Done.

2023-09-01 15:03 UTC, mrsimi commented on src/locales/yo_NG/metadata.ts
> +  endonym: 'Yoruba (Nigeria)',
Done

2023-09-01 15:13 UTC, matthewmayer approved these changes, later dismissed

2023-09-01 18:28 UTC, ST-DDT commented on src/locales/yo_NG/metadata.ts
> +  endonym: 'Yorùbá (Nàìjíríà)',
If the `endonym` contains all these special characters.
Why doesn't the other names contain them as well (or at least some of them)?

2023-09-01 19:36 UTC, mrsimi commented on src/locales/yo_NG/metadata.ts
> +  endonym: 'Yorùbá (Nàìjíríà)',
Names do not need to contain special characters as they are used to denote intonation which is not necessary for names. They are used when grammar is involved, so article writing, literature, etc. 

So I think to bring uniformity into it, I would rewrite this `Yorùbá (Nàìjíríà)` as `Yoruba(Naijiria)`

2023-09-01 20:57 UTC, ST-DDT approved these changes

2023-09-01 21:24 UTC, matthewmayer approved these changes

2023-09-02 20:39 UTC, import-brain approved these changes

2023-09-03 06:56 UTC, merged