feat: split SimpleFaker class from Faker
faker-js/faker pull request #2369
Opened 2023-09-01 14:15 UTC by Shinigami92

references #1351 
- #1351

2023-09-01 14:20 UTC, Shinigami92 commented
In `DateModule` we have a reference to `definitions`

https://github.com/faker-js/faker/pull/2369/files#diff-33d9552c7d1fb7f98cb50e15888b577d2609cd9b6f17a333b641752c5049629dR1001

I have multiple ideas how to solve this:
- Split a `BaseDateModule` from `DateModule` (theoretically we could do that with other modules as well)
- Add a check whether we are currently have `definitions` or not, if not the `throw Error` and indicate to use `Faker` instance instead
- open for alternative ideas

2023-09-01 17:59 UTC, xDivisionByZerox commented
> In `DateModule` we have a reference to `definitions`
> 
> [#2369 (files)](https://github.com/faker-js/faker/pull/2369/files#diff-33d9552c7d1fb7f98cb50e15888b577d2609cd9b6f17a333b641752c5049629dR1001)
> 
> I have multiple ideas how to solve this:
> 
> * Split a `BaseDateModule` from `DateModule` (theoretically we could do that with other modules as well)
> * Add a check whether we are currently have `definitions` or not, if not the `throw Error` and indicate to use `Faker` instance instead
> * open for alternative ideas

IMO we should simply exclude the date module from the `BaseFaker` class. Gernerally, if a module uses locale data, exclude it. If you want a `Date` you can still do `new Date(faker.number.int({ ... }))`. I would take the easy route here.

2023-09-01 18:25 UTC, ST-DDT commented
IMO `Date`s are very useful for everyday testing.

2023-09-01 18:28 UTC, Shinigami92 commented
Originally I just put it there because datatype uses date.between

2023-09-01 19:49 UTC, Shinigami92 commented
Okay... I tested building a `BaseDateModule`, but this is bad, because it produces faker.date conflicts between the BaseFaker and Faker class...

2023-09-01 20:37 UTC, Shinigami92 commented on src/internal/bind-this-to-member-functions.ts
> +  } while (p !== Object.prototype);
@xDivisionByZerox we would like your opinion about following suggestion brought by @ST-DDT 

He likes the assignment inside the while-loop, where I don't like assignments in conditions at all

```ts
  let p = instance;
  while ((p = Object.getPrototypeOf(p)) !== Object.prototype) {
    for (const name of Object.getOwnPropertyNames(p)) {
      if (typeof instance[name] === 'function' && name !== 'constructor') {
        instance[name] = instance[name].bind(instance);
      }
    }
  }
```

There is a eslint rule https://eslint.org/docs/latest/rules/no-cond-assign which is by default configured with `except-parens`, which allows the suggested code
But when set to `always`, it would result in an error (as I would like it)

#happyabouthavingathirdmaintainer :P

2023-09-01 20:55 UTC, Shinigami92 commented
Potentially TODOs:
- add docs about `baseFaker`/`BaseFaker`
- add tests?!
- discuss if we want a `@faker-js/faker/base`
- export type `Base*Module`

2023-09-07 15:35 UTC, ST-DDT commented
We are not sure about what the actual questions here are.

**Team Decision**

> - add docs about baseFaker/BaseFaker

Yes

> - add tests?!

Only tests that concern creating the base faker instance.

> - discuss if we want a @faker-js/faker/base

Currently, we don't see a need for that, we should rather fix the tree-shaking.
Because if we add that now and remove it in v9 this will result in bad DX.

> - export type Base*Module

Yes, only as types.

> - Additionally

- Split BaseFaker+baseFaker into it's own file

2023-09-07 17:07 UTC, Shinigami92 commented on scripts/apidoc/baseFakerClass.ts
> +import type { DeclarationReflection, ProjectReflection } from 'typedoc';
This file is nearly a 1 to 1 copy of the `scripts/apidoc/fakerClass.ts` but with `base` as prefix

2023-09-07 17:07 UTC, Shinigami92 commented on src/base-faker.ts
> +  constructor() {}
This empty constructor just exists for VitePress docs

2023-09-07 18:37 UTC, ST-DDT commented on scripts/apidoc/baseFakerClass.ts
> +  methods.push(...(await processModuleMethods(baseFakerClass, 'faker.')));
Shouldn't this be `baseFaker`?

2023-09-07 18:37 UTC, ST-DDT commented on src/base-faker.ts
> +  constructor() {}
Maybe put that comment into the code so it isn't lost?

2023-09-07 18:37 UTC, ST-DDT commented on scripts/apidoc/baseFakerClass.ts
> +import type { DeclarationReflection, ProjectReflection } from 'typedoc';
Why don't you change the original implementation and let it return a list of `*Faker`s?

2023-09-07 18:37 UTC, ST-DDT commented on src/base-faker.ts
> +  protected _defaultRefDate: () => Date = () => new Date();
Why does it have to be `protected`?

2023-09-07 18:37 UTC, ST-DDT commented on src/base-faker.ts
> +  get defaultRefDate(): () => Date {
Why is the getter up here and the setter down below?

2023-09-08 00:25 UTC, matthewmayer requested changes
It would be good to document what the difference is between fakerBASE and BaseFaker in `/guide/localization.html` since they sound confusingly similar.

2023-09-08 06:23 UTC, Shinigami92 commented
> It would be good to document what the difference is between fakerBASE and BaseFaker in `/guide/localization.html` since they sound confusingly similar.

Thanks for the reminder 👍

2023-09-10 12:06 UTC, Shinigami92 commented on scripts/apidoc/baseFakerClass.ts
> +import type { DeclarationReflection, ProjectReflection } from 'typedoc';
done

2023-09-10 12:07 UTC, Shinigami92 commented on src/base-faker.ts
> +  constructor() {}
done

2023-09-10 12:07 UTC, Shinigami92 commented on scripts/apidoc/baseFakerClass.ts
> +  methods.push(...(await processModuleMethods(baseFakerClass, 'faker.')));
done

2023-09-10 12:13 UTC, Shinigami92 commented on src/base-faker.ts
> +  protected _defaultRefDate: () => Date = () => new Date();
This is a specific TS weird thingy. When we would do `private _defaultRefDate` in `BaseFaker` and then theoretically comes along and implements a `private _defaultRefDate` in `Faker`, the classes are not compatible with each other in terms of abstraction. However, as we only use TS class modifiers here and not real JS private (`#defaultRefDate`) the field is anyway "public" at runtime!
So I instead just used `protected` to indicate that it is an "internal" field that is not exposed to the API/method calls, but if someone wants to mess around with it while extending the class, feel free.

2023-09-10 12:16 UTC, Shinigami92 commented on src/base-faker.ts
> +  get defaultRefDate(): () => Date {
Originally I just copied the fields and methods over from `Faker` in exactly the order they were.
I would argue that getters and setters are field aliases with extra-stuff and fields are above the constructor. But even that is already not consistent right now :shrug:  
Maybe you could find a lint rule to force a style? Until then, I would suggest this is not blocking.

2023-09-11 20:17 UTC, ST-DDT commented on src/base-faker.ts
> +  get defaultRefDate(): () => Date {
So you are making a distinction between the former being a property setter vs the other being a setter function?

IMO they are the same.

2023-09-11 20:30 UTC, ST-DDT reviewed
There are two things here that are troubling me:

- `fakerBASE` is very close to `baseFaker` but these two are very distinct things. We should probably change either of them.
- I would like to have an indicator somewhere in the docs, which methods are available in the `BaseFaker` and which do require an actual `Faker` (or vice versa)

2023-09-11 20:30 UTC, ST-DDT commented on docs/guide/localization.md
> +Do not confuse the `base` locale / `fakerBASE` with the `baseFaker` instance, the later being a prebuilt `Faker` instance without any locale support.
Not sure about the wording here.

2023-09-11 20:30 UTC, ST-DDT commented on scripts/apidoc/fakerClass.ts
>  export async function processFakerClass(
Maybe rename this to `processFakerClasses` because it processes more than one?

2023-09-11 20:30 UTC, ST-DDT commented on src/base-faker.ts
> + * This is Faker's base class containing only modules that can be used to generate basic data.
Maybe change this to something like:

```suggestion
 * This is Faker class that doesn't need any localized data to generate it's output. It should be used if only values are needed that can be generated on the spot.
```

2023-09-11 20:30 UTC, ST-DDT commented on src/base-faker.ts
> +  readonly string: StringModule = new StringModule(this);
What about these properties? Should we move them up to the others?

2023-09-12 11:13 UTC, matthewmayer commented on docs/guide/localization.md
> +Do not confuse the `base` locale / `fakerBASE` with the `baseFaker` instance, the later being a prebuilt `Faker` instance without any locale support.
i dont this this warning is very useful as-is. I think instead we should document somewhere how to actually use baseFaker.

2023-09-13 13:57 UTC, ST-DDT commented
We should have some documentation when and how to use the simpleFaker instead of a full Faker.

2023-09-13 14:53 UTC, matthewmayer requested changes, later dismissed

2023-09-13 14:53 UTC, matthewmayer commented on src/simple-faker.ts
> + * @example
`@example` at a module level don't show up in the generated docs. Suggest putting this in an "Overview" section like other modules

2023-09-13 14:53 UTC, matthewmayer commented on src/simple-faker.ts
> + * Please have a look at the individual modules and methods for more information and examples.
```suggestion
* This is a simplified Faker class that doesn't need any localized data to generate its output. It only includes methods from the `datatype`, `date`, `helpers` and `string` modules.
```

2023-09-13 14:53 UTC, matthewmayer commented on src/simple-faker.ts
> + * simpleFaker.string.uuid(); // 'c50e1f5c-86e8-4aa9-888e-168e0a182519'
add another example which throws, e.g. `simpleFaker.person.fullName()`

2023-09-13 18:09 UTC, Shinigami92 commented on src/simple-faker.ts
> + * @example
not related to this PR

2023-09-13 18:10 UTC, Shinigami92 commented on src/simple-faker.ts
> + * simpleFaker.string.uuid(); // 'c50e1f5c-86e8-4aa9-888e-168e0a182519'
it does not throw, it's not possible to call as TS already does not provide `simpleFaker.person`

2023-09-13 22:58 UTC, ST-DDT submitted a review, later dismissed

2023-09-14 11:45 UTC, matthewmayer commented on src/simple-faker.ts
> + * @example
<img width="750" alt="Screenshot 2023-09-14 at 18 43 14" src="https://github.com/faker-js/faker/assets/152770/40671467-67d9-44a5-8811-e89f6488d713">

i think it would be better to move any example code into the Overview section, otherwise there's no easy way to see how to use this new feature.

2023-09-14 11:51 UTC, Shinigami92 commented on src/simple-faker.ts
> + * @example
You mean except of the usage guide?

Also it looks like this already does also not apply for https://fakerjs.dev/api/faker.html, so I definitely count this as not relevant for this PR and should be done in another PR
Potentially by someone who knows how to implement that via the api-gen scripts...

2023-09-14 12:26 UTC, matthewmayer commented on src/simple-faker.ts
> + * @example
i just find this page quite confusing at the moment because it mentions the "prebuilt simpleFaker instances" and yet this is not mentioned on the page at all (because its in the invisible @example)

<img width="741" alt="image" src="https://github.com/faker-js/faker/assets/152770/b09ef3dc-498c-47ac-b7d5-3c6d9a2868a0">

2023-09-14 20:15 UTC, xDivisionByZerox commented on src/modules/date/index.ts
> +export class SimpleDateModule<TFaker extends SimpleFaker = SimpleFaker> {
Why is a generic argument required for this position? Since `Faker` extends `SimpleFaker` it should be possible to initialize this module with all arguments that derive from SimpleFaker. I think this is an over-complication, as you don't use the generic anywhere to enhance the return values of the API.

2023-09-14 20:18 UTC, Shinigami92 commented on src/modules/date/index.ts
> +export class SimpleDateModule<TFaker extends SimpleFaker = SimpleFaker> {
Please show me how you would do it. I didn't get it to work probably without this.

2023-09-15 09:15 UTC, xDivisionByZerox commented on src/modules/date/index.ts
> +export class SimpleDateModule<TFaker extends SimpleFaker = SimpleFaker> {
Take a look here: https://github.com/faker-js/faker/commit/49c4f79377e4718b2ccc24b4cb455829df40a162

2023-09-15 16:20 UTC, Shinigami92 commented on src/modules/date/index.ts
> +export class SimpleDateModule<TFaker extends SimpleFaker = SimpleFaker> {
That's interesting... I would assume that this would shadow the underlying member field 🤔 
@ST-DDT what is your opinion about this? Should we do @xDivisionByZerox way or "my" generic approach?

2023-09-15 16:49 UTC, ST-DDT commented on src/modules/date/index.ts
> +export class SimpleDateModule<TFaker extends SimpleFaker = SimpleFaker> {
We should check if this actually shadows the field. And if it does for production builds then go for the non generic one.

2023-09-15 16:55 UTC, Shinigami92 commented on src/modules/date/index.ts
> +export class SimpleDateModule<TFaker extends SimpleFaker = SimpleFaker> {
I tried 

```ts
import { faker, simpleFaker } from './src';

console.log(Object.getPrototypeOf(faker.date));
console.log(Object.getPrototypeOf(simpleFaker.date));
console.log(faker.date.month);
console.log(simpleFaker.date.month);
```

before and after, but no changes are there 🤔 
I don't know if there is a better check or how I could really check and access a field of an inheritance extension 🤷

2023-09-15 17:07 UTC, Shinigami92 commented on src/modules/date/index.ts
> +export class SimpleDateModule<TFaker extends SimpleFaker = SimpleFaker> {
Very interesting, instead of shadowing, it looks like TS is smart and redefines just the type with that
It actually checks that the type is compatible and if it's not, then there is a compile time error

2023-09-15 19:40 UTC, ST-DDT commented on src/simple-faker.ts
> + * It only includes methods from the `datatype`, `date`, `helpers` and `string` modules.
This list is missing the number module.

Maybe use an list like:

> - `datatype`
> - date (without `month` and `weekday`)
> - `helpers` (without fake)
> - number
> - string

or if the exclude list is to long/distracting just `(partially)`.

2023-09-15 19:40 UTC, ST-DDT commented on docs/guide/usage.md
> +
Maybe add a link to the api documentation to provide more information which modules are available exactly.

2023-09-15 19:40 UTC, ST-DDT commented on docs/guide/usage.md
> +This is useful if you just want to generate e.g. `uuid`s for your production environment, but don't want to initiate/load a full Faker instance, which would include locale data.
IMO we shouldn't recommend using it for production either.

```suggestion
This is useful if you just want to generate e.g. `uuid`s for your test environment, but don't want/need to initiate/load a full Faker instance, which would include at least 500KB of locale data.
```

Are 500KB correct?

2023-09-15 19:48 UTC, Shinigami92 commented on docs/guide/usage.md
> +This is useful if you just want to generate e.g. `uuid`s for your production environment, but don't want to initiate/load a full Faker instance, which would include locale data.
it's an estimation 👍

2023-09-15 20:16 UTC, ST-DDT approved these changes

2023-09-15 20:39 UTC, xDivisionByZerox commented on src/simple-faker.ts
> + * - `string`
I would not put every module that is included here. Adds unnecessary maintainance burden if we delete or add modules.

2023-09-15 20:56 UTC, Shinigami92 commented on src/simple-faker.ts
> + * - `string`
TBH we have this "burden" already with soooo many overview JSDocs like HelpersModule which could e.g. also include stuff then gets potentially deprecated

2023-09-15 20:59 UTC, ST-DDT commented on src/simple-faker.ts
> + * - `string`
I'm not sure about this manually maintained list either, but we need some kind of documentation which methods are available on baseFaker. Optimally on each method.

I thought about something like this (which might be overkill for this PR, not sure):

| | |
| --- | --- |
| ✅ BaseFaker | 15 Locales ``<hover><ul><li> 🇩🇪 </li>...`` |

Maybe between the params and the example block.

2023-09-15 21:03 UTC, Shinigami92 commented on src/simple-faker.ts
> + * - `string`
How about we just start with the current PR and if there is really a need, we can enhance later anyway

2023-09-16 19:27 UTC, xDivisionByZerox commented on src/simple-faker.ts
> + * - `string`
Not a big fan. Just want to leave this here so I can tell you "I told you" if we need to change it later xD

2023-09-16 19:30 UTC, xDivisionByZerox approved these changes

2023-09-18 03:52 UTC, merged