chore: adding cypress integration tests
faker-js/faker pull request #240
Opened 2022-01-20 02:15 UTC by JessicaSachs

- Closes #239 
- Coverage will get better when the playground comes through

2022-01-20 02:15 UTC, JessicaSachs commented on .github/workflows/ci.yml
> +
```suggestion
```

2022-01-20 03:04 UTC, import-brain approved these changes, later dismissed

2022-01-20 07:35 UTC, Shinigami92 requested changes

2022-01-20 07:35 UTC, Shinigami92 commented on .github/workflows/ci.yml
> +  test-browser:
We should move this block down and name it test-docs-e2e

2022-01-20 07:35 UTC, Shinigami92 commented on .github/workflows/ci.yml
> +          - os: macos-latest
Do we need to test on ubuntu and mac? Or can we just select one and don't use a matrix?

2022-01-20 07:35 UTC, Shinigami92 commented on .github/workflows/ci.yml
> +    name: 'Build Docs & Run E2E tests'
Maybe just `Docs E2E`?

2022-01-20 07:35 UTC, Shinigami92 commented on package.json
> +    "test:e2e:open": "start-server-and-test 'run-s docs:build docs:serve' :3000 'cypress open'"
We should name these `docs:test(:*)`

2022-01-20 07:35 UTC, Shinigami92 commented on package.json
> +    "test:e2e:run": "start-server-and-test 'run-s docs:serve' :3000 'cypress run'",
Could we try to get rid of `start-server-and-test` and just try to use `run-p --race docs:serve :3000 'cypress run'`
We may need an additional alias script like `"cypress": "cypress"`

2022-01-20 18:52 UTC, JessicaSachs commented on .github/workflows/ci.yml
> +          - os: macos-latest
Only one is fine.

2022-01-20 18:53 UTC, JessicaSachs commented on package.json
> +    "test:e2e:run": "start-server-and-test 'run-s docs:serve' :3000 'cypress run'",
Does that check for port 3000 being up?

2022-01-20 19:00 UTC, Shinigami92 commented on package.json
> +    "test:e2e:run": "start-server-and-test 'run-s docs:serve' :3000 'cypress run'",
Yeah, it works at a project in my company
It's like https://github.com/Shinigami92/quasar-vite/blob/d76b2e7a85a6ada9d0735fbc44931757af86df68/package.json#L19

It will run the dev server, cypress then checks automatically if there is something running on the defined or default port and when the dev server starts it also runs. Then when cypress is finished, the `--race` flag will kill the dev server.

2022-01-25 06:18 UTC, cronlabspl requested changes
This issue / PR needs more work.

2022-01-27 21:00 UTC, cronlabspl approved these changes
Looks good to me 👍

2022-01-27 21:19 UTC, Shinigami92 submitted a review, later dismissed

2022-01-27 23:22 UTC, cronlabspl approved these changes
All seems to be ok. Go ahead and merge it.

2022-01-28 07:45 UTC, Shinigami92 approved these changes, later dismissed

2022-01-28 09:56 UTC, ST-DDT requested changes

2022-01-28 09:56 UTC, ST-DDT commented on package.json
> +    "docs:test:e2e:open": "run-p --race docs:serve 'cypress open'"
These don't work for me (windows).

````txt
$ pnpm run docs:test:e2e:open

> @faker-js/faker@6.0.0-alpha.5 docs:test:e2e:open
> run-p --race docs:serve 'cypress open'

ERROR: Task not found: "'cypress", open'"
 ELIFECYCLE  Command failed with exit code 1.

$ pnpm run docs:test:e2e:run

> @faker-js/faker@6.0.0-alpha.5 docs:test:e2e:run 
> run-p --race docs:serve 'cypress run'

ERROR: Task not found: "'cypress", run'"
 ELIFECYCLE  Command failed with exit code 1.
````

2022-01-28 10:19 UTC, prisis submitted a review, later dismissed

2022-01-28 10:21 UTC, prisis commented on package.json
> +    "docs:test:e2e:run": "run-p --race docs:serve 'cypress run'",
```suggestion
    "docs:test:e2e:run": "run-p --race docs:serve \"cypress run\"",
```

2022-01-28 10:21 UTC, prisis commented on package.json
> +    "docs:test:e2e:open": "run-p --race docs:serve 'cypress open'"
```suggestion
    "docs:test:e2e:open": "run-p --race docs:serve \"cypress open\""
```

2022-01-28 10:22 UTC, ST-DDT commented on package.json
> +    "docs:test:e2e:open": "run-p --race docs:serve 'cypress open'"
This seems to be a windows issue. You cannot use `'` there.

2022-01-28 10:22 UTC, prisis approved these changes

2022-01-28 10:25 UTC, Shinigami92 approved these changes

2022-01-28 10:25 UTC, ST-DDT approved these changes

2022-01-28 10:27 UTC, merged