infra: add eslint unicorn
faker-js/faker pull request #2417
Opened 2023-09-23 17:16 UTC by Shinigami92

Based on https://github.com/faker-js/faker/pull/2284#discussion_r1333960666

This PR will make @fisker really happy :heart:

2023-09-23 18:02 UTC, ST-DDT commented on .eslintrc.js
> +  plugins: ['@typescript-eslint', 'prettier', 'deprecation', 'unicorn'],
This is optional/already covered by the extends config.

2023-09-23 18:02 UTC, ST-DDT commented on .eslintrc.js
> +          args: true,
Why args but not arg?

2023-09-23 18:02 UTC, ST-DDT commented on test/modules/helpers.spec.ts
> +        .it('with dynamic RegExp', /(?:[\dA-D]-){2}A/)
These are tests, we might need both variants. IIRC the new variant isnt supported yet.

2023-09-23 18:02 UTC, ST-DDT commented on test/modules/helpers.spec.ts
> +          for (let index = 0; index < 1000; index++) {
This isnt the index it is a counter.

2023-09-23 18:02 UTC, ST-DDT commented on test/modules/helpers.spec.ts
> +          const string = faker.helpers.fromRegExp(/[\dA-D]{4}-[\dA-D]{4}/);
Maybe this isnt supported yet.

2023-09-23 18:02 UTC, ST-DDT commented on .eslintrc.js
> +          obj: true,
Why obj, but not str/num?

2023-09-23 18:11 UTC, ST-DDT commented on test/modules/color.spec.ts
> +          const supportedFunction = faker.color.cssSupportedFunction();
Maybe name it actual same as in our other tests?

2023-09-23 18:11 UTC, ST-DDT commented on test/modules/date.spec.ts
> +            for (let index = 1; index < dates.length; index++) {
This seems unnessarily verbose.

2023-09-23 18:11 UTC, ST-DDT commented
Note to self. Check all the regexes again.

2023-09-23 18:12 UTC, Shinigami92 commented
@ST-DDT I highly suggest you start reviewing this when I'm actually done with it
There are more then 800 errors I need to manually go through
I'm already sitting on this more than an hour and I make a break now, playing Overwatch

2023-09-23 18:26 UTC, ST-DDT commented on test/modules/helpers.spec.ts
> +            for (let index = 0; index < 1000; index++) {
This isnt an index.

2023-09-23 18:26 UTC, ST-DDT commented on test/modules/image.spec.ts
> +        /^ht{2}ps:\/{2}via\.placeholder\.com\/\d+x\d+(?:\/[\dA-Fa-f]{6}){2}\.[a-z]{3,4}\?text=.+$/
No. `ht{2}ps:\/{2}` :no_good:

2023-09-23 18:26 UTC, ST-DDT commented on test/modules/internet.spec.ts
> +            /^Mike((\d{1,2})|([!#$%&'*+-/=?^_`{|}~]Smith\d{1,2})|([!#$%&'*+-/=?^_`{|}~]Smith))/
Note to self: Where did the dot go?

2023-09-23 18:26 UTC, ST-DDT commented on test/modules/lorem.spec.ts
> +          (number) => {
Why number here and number_ at other locations IIRC?

2023-09-23 18:26 UTC, ST-DDT commented on test/support/seeded-runs.ts
> +    for (let index = 0; index < repetitions; index++) {
This isnt an index.

2023-09-23 18:30 UTC, ST-DDT commented
> @ST-DDT I highly suggest you start reviewing this when I'm actually done with it There are more then 800 errors I need to manually go through I'm already sitting on this more than an hour and I make a break now, playing Overwatch

I'm not sure I want to review 800 changes in one PR.

2023-09-23 18:45 UTC, ST-DDT requested changes
This PR is not reviewable due to size/different kind of changes.

2023-09-23 20:52 UTC, Shinigami92 commented
As @ST-DDT already pointed out, I need to split this into several PRs, to reduce the amount of changed files in the same PR.

This PR now reflects the approximate change when everything is merged individually.

While working on this PR, I at least learned some stuff I can reuse to work on the individual PRs.
And maybe this PR gets so much reduces in diff count, that it can then be used to check the rest that is left over.

2023-09-23 20:53 UTC, Shinigami92 commented
I switched from `on hold` to `do not merge`, because `on hold` is for that the work is not going forward, which is effectively wrong in this case

2023-10-06 23:50 UTC, ST-DDT commented
This has been superseded by #2418 and individual PRs per rule.

Since Shinigami92 is no longer actively working on this. I will close this because of the merge conflicts.
The diff is visible here forever and the branch can be restored if needed as well.

2023-10-06 23:50 UTC, closed without merging