infra: enable strictNullChecks in tsconfig
faker-js/faker pull request #2435
Opened 2023-10-05 21:44 UTC by ST-DDT

Fixes #1834

- #1834

2023-10-05 22:03 UTC, ST-DDT commented on docs/.vitepress/versions.ts
> +
```suggestion
```

2023-10-05 22:03 UTC, ST-DDT commented on src/modules/date/index.ts
> +    if (options instanceof Date || typeof options !== 'object') {
Flipping this somehow fixes an ts-error in line 405 🤷‍♂️ .

2023-10-05 22:03 UTC, ST-DDT commented on src/modules/person/index.ts
> +      generic: first_name ?? undefined,
```suggestion
      generic: first_name,
```

2023-10-05 22:03 UTC, ST-DDT commented on src/modules/finance/index.ts
> +    return formatted ? result.replace(/(.{4})(?=.)/g, '$1 ') : result;
Which is easier to read?

- `result.match(/.{1,4}/g)!.join(' ')`
- `result.replace(/(.{4})(?=.)/g, '$1 ')`
- `result.replace(/(.{4})/g, '$1 ').trimRight()`

2023-10-05 22:03 UTC, ST-DDT commented on test/modules/finance_iban.spec.ts
> +          const ibanFormatted = iban.match(/.{1,4}/g)!.join(' ');
Should I adjust the code here as well?

2023-10-05 22:03 UTC, ST-DDT commented on tsconfig.json
> -    "strictNullChecks": false,
Is removing this correct, or do we have to set this to `true` instead?

2023-10-05 22:07 UTC, ST-DDT commented
Ready for review.

2023-10-05 23:11 UTC, xDivisionByZerox requested changes

2023-10-05 23:11 UTC, xDivisionByZerox commented on cypress/e2e/api.cy.ts
> +        const link = anchor.attr('href')!.split('#')[0];
I mena we wouldn't really activate this just to work around it again, would we?

```suggestion
        const link = anchor.attr('href')?.split('#')[0] ?? '';
```

2023-10-05 23:11 UTC, xDivisionByZerox commented on src/locales/ar/date/weekday.ts
> -  abbr: null,
Didn't we explicitly decide to allow `null` for "not appicable" in out locale data? I think we should have a look into our `LocaleDefinition` type before "fixing" those values. 

In the case:
Should we add conert the month property from `DateEntryDefinition` to `LocaleEntry<DateEntryDefinition>`? Or even better, should `LocaleEntry` recursivly apply itself to types which extend `object`? That why we only have to apply `LocaleEntry` ones to the actual `LocaleDefinition` type itself.

2023-10-05 23:11 UTC, xDivisionByZerox commented on tsconfig.json
> -    "strictNullChecks": false,
We have the `strict` property aboth that would usally include `strictNullChecks`. So removing it here enables it again. Kinda similar to what we doing with the unicorn plugin.

2023-10-05 23:11 UTC, xDivisionByZerox commented on docs/.vitepress/versions.ts
> +    .map(([major, tags]) => semver.maxSatisfying(tags, `^${major}`)!)
```suggestion
    .map(([major, tags]) => semver.maxSatisfying(tags, `^${major}`))
    .filter((version): version is string => typeof version === 'string')
```

2023-10-05 23:11 UTC, xDivisionByZerox commented on scripts/apidoc/fakerClass.ts
> +    .some((constructor) => constructor.signatures!.length > 0);
```suggestion
    .some((constructor) => (constructor.signatures?.length ?? 0) > 0);
```

2023-10-05 23:11 UTC, xDivisionByZerox commented on src/modules/commerce/index.ts
> +    )![1];
```suggestion
    ) ?? [0, 0])[1];
```

Sadly can't add lines which have not been touched. So I cant set the open bracket in line 387.
Alternitivly we could check if the `find` resolves to `undefined` and throw an error in that case. That would get rid of the non-null assertion.

2023-10-05 23:11 UTC, xDivisionByZerox commented on src/modules/date/index.ts
> +    if (options instanceof Date || typeof options !== 'object') {
Because the last thing to resolve here is `typeof options !== 'object'` so if this fails `options` is definitly an object; if it doesn't fail ts can infer that `options` will definitly be an object after the block statement as well. This might sound stupid but the statement before TypeScript would have been able to tell that `options` was 100% a `Date`, but could say the same for `object`. 
Although, I cant tell you an example where that would happen. Propably some prototype shenanigan.

2023-10-05 23:11 UTC, xDivisionByZerox commented on src/modules/date/index.ts
> +      options = { from: options, to: legacyTo ?? options };
Can we extend the comment to remove this workaround in v9?

```suggestion
      // We use options as fallback for legacyTo avoid TS errors for unintended usage.
      // TODO: Remove in v9
      options = { from: options, to: legacyTo ?? options };
```

2023-10-05 23:11 UTC, xDivisionByZerox commented on src/modules/date/index.ts
> +    return this.faker.helpers.arrayElement(values);
Can't we simply this by letting `arrayElement` handle the "error tha is never possible"?

```suggestion
    return this.faker.helpers.arrayElement(source[type] ?? []);
```

2023-10-05 23:11 UTC, xDivisionByZerox commented on src/modules/date/index.ts
> +    return this.faker.helpers.arrayElement(values);
Same here?

```suggestion
    return this.faker.helpers.arrayElement(source[type] ?? []);
```

2023-10-05 23:11 UTC, xDivisionByZerox commented on src/modules/finance/index.ts
> +    } while (!symbol);
I had to look up while this is even getting looped. We should make the check more percise since the symbol itself always exists (as an empty string). Alternatively we could update the `Currency` definition to allow optional or `null` values.

```suggestion
    } while (symbol.length === 0);
```

2023-10-05 23:11 UTC, xDivisionByZerox commented on test/faker.spec.ts
> +      expect(faker.rawDefinitions.metadata!.title).toBeDefined();
I mean this literally checks for the value being defined. No need to assert non-null.

```suggestion
      expect(faker.rawDefinitions.metadata?.title).toBeDefined();
```

2023-10-05 23:11 UTC, xDivisionByZerox commented on test/vitest-extensions.ts
> +        // @ts-expect-error: `isNot` is incorrectly inferred as `function`.
Maybe default `isNot` to false in the destruction? But I don't really get why the `this` scope is infered incorrectly. A workaround is no longer required in TS  5.2.x, tho.

2023-10-05 23:18 UTC, ST-DDT commented on src/locales/ar/date/weekday.ts
> -  abbr: null,
The null is only supported on the second aka entry level. Everything below needs extra handling. We cannot extend the proxying downward because we also return complex objects.

2023-10-05 23:20 UTC, ST-DDT commented on docs/.vitepress/versions.ts
> +    .map(([major, tags]) => semver.maxSatisfying(tags, `^${major}`)!)
The list is only there if there is at least one entry. So it is always there.
Not sure about the filter code that doesnt filter and only serves TS types.

2023-10-05 23:22 UTC, ST-DDT commented on scripts/apidoc/fakerClass.ts
> +    .some((constructor) => constructor.signatures!.length > 0);
I also considered this, but if there is a constructor without signature, I want to know that. Aka it shouldnt be possible unless typedoc changes their internal API.

2023-10-05 23:23 UTC, ST-DDT commented on src/modules/commerce/index.ts
> +    )![1];
This can never happen. Why write code for it?

2023-10-05 23:24 UTC, ST-DDT commented on src/modules/date/index.ts
> +      options = { from: options, to: legacyTo ?? options };
The whole deprecation block will be gone in v9.

2023-10-05 23:25 UTC, ST-DDT commented on src/modules/date/index.ts
> +    return this.faker.helpers.arrayElement(values);
Sure, but then there wouldnt be a hint which data are actually missing.

2023-10-05 23:37 UTC, ST-DDT commented on test/faker.spec.ts
> +      expect(faker.rawDefinitions.metadata!.title).toBeDefined();
AFAICT the ! is not an assertion, its a not null definition expression.
Or am I wrong?

2023-10-05 23:42 UTC, ST-DDT commented on cypress/e2e/api.cy.ts
> +        const link = anchor.attr('href')!.split('#')[0];
```suggestion
        const link = anchor.attr('href')?.split('#')[0] ?? 'MISSING';
```

2023-10-05 23:51 UTC, ST-DDT commented on test/vitest-extensions.ts
> +        // @ts-expect-error: `isNot` is incorrectly inferred as `function`.
TS claims that isNot is a function and always there thus the expression resolves to true always. But it is not.

2023-10-06 13:25 UTC, xDivisionByZerox commented on test/faker.spec.ts
> +      expect(faker.rawDefinitions.metadata!.title).toBeDefined();
The name of the operator is [Non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator). It does only assert in a TS context tho.

The problem is that `faker.rawDefinitions.metadata` might be `null` or `undefined`. This will propably never happen, but TS doesn't know that. In general you should not use the the NNA operator. See [@typescript-eslint/no-non-null-assertion](https://typescript-eslint.io/rules/no-non-null-assertion/)

2023-10-06 13:26 UTC, xDivisionByZerox commented on test/vitest-extensions.ts
> +        // @ts-expect-error: `isNot` is incorrectly inferred as `function`.
Thats why I proposed to default the the property in the destruction aboth: `const { isNot = false } = this;`. This would let TypeScript infer the type as `function | false` which ill not always resolve to true.

2023-10-06 19:08 UTC, ST-DDT commented on test/faker.spec.ts
> +      expect(faker.rawDefinitions.metadata!.title).toBeDefined();
In the end it doesn't hurt to change this. Done.

2023-10-06 19:18 UTC, ST-DDT commented on test/vitest-extensions.ts
> +        // @ts-expect-error: `isNot` is incorrectly inferred as `function`.
Thanks for the explanation. Changed.

2023-10-06 19:40 UTC, ST-DDT commented on docs/.vitepress/versions.ts
> +    .map(([major, tags]) => semver.maxSatisfying(tags, `^${major}`)!)
I found a way to avoid this code.

2023-10-06 20:44 UTC, xDivisionByZerox commented on test/modules/finance_iban.spec.ts
> +          const ibanFormatted = iban.match(/.{1,4}/g)!.join(' ');
Yes. We could consider removing this lines as they only check that we really implemented what we implemented. That would happen in another PR tho.

2023-10-06 20:52 UTC, xDivisionByZerox commented on src/locales/ar/date/weekday.ts
> -  abbr: null,
We should extend the `abbr` property with a null parameter and include a comment about the condition which is required for it to possible be null.

2023-10-06 21:03 UTC, xDivisionByZerox commented on src/modules/commerce/index.ts
> +    )![1];
We will reconsider the implementation in a different PR.

2023-10-06 21:07 UTC, xDivisionByZerox commented on src/modules/date/index.ts
> +    return this.faker.helpers.arrayElement(values);
Will be considered by solving https://github.com/faker-js/faker/pull/2435#discussion_r1349312186.

2023-10-06 21:07 UTC, xDivisionByZerox commented on src/modules/date/index.ts
> +    return this.faker.helpers.arrayElement(values);
Will be considered by solving https://github.com/faker-js/faker/pull/2435#discussion_r1349312186.

2023-10-06 22:59 UTC, ST-DDT commented on src/modules/finance/index.ts
> +    return formatted ? result.replace(/(.{4})(?=.)/g, '$1 ') : result;
Fixed

2023-10-06 22:59 UTC, ST-DDT commented on src/locales/ar/date/weekday.ts
> -  abbr: null,
Fixed

2023-10-06 22:59 UTC, ST-DDT commented on src/modules/date/index.ts
> +    return this.faker.helpers.arrayElement(values);
Fixed

2023-10-06 22:59 UTC, ST-DDT commented on src/modules/date/index.ts
> +    return this.faker.helpers.arrayElement(values);
Fixed.

2023-10-06 23:00 UTC, ST-DDT commented
Ready for review again. 😉

2023-10-07 09:50 UTC, xDivisionByZerox commented on src/locale-proxy.ts
> +  if (value == null) {
Is this outer `if` really required?

2023-10-07 10:17 UTC, ST-DDT commented on src/locale-proxy.ts
> +  if (value == null) {
No, it is not. I just considered it as the fast path, but I'm not sure whether it has any performance implications.

2023-10-07 11:04 UTC, xDivisionByZerox commented on src/locale-proxy.ts
> +  if (value == null) {
I'd say it is obsolete here TBH.

2023-10-07 11:28 UTC, ST-DDT commented on src/locale-proxy.ts
> +  if (value == null) {
Changed.

2023-10-08 17:53 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +      const tokenIndex: number = token.index!;
I thought a little bit about this. Can we not default this to `0`? Should we perhaps exit the `while` loop if it doesn't exist? Thats the two solutions I can think off. I dont really like using the NNAO here.

2023-10-09 08:30 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      const tokenIndex: number = token.index!;
We could switch from `string.match(regex)` to `regexp.exec(string)`.
That would fix that issue as well.

I don't think defaulting to 0 would do us any good. Maybe -1 or NaN so it explodes at the next usage instead doing something random.

2023-10-09 09:44 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      const tokenIndex: number = token.index!;
The index is always present, when the regex does not use the global flag.

2023-10-09 14:05 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +      const tokenIndex: number = token.index!;
> We could switch from string.match(regex) to regexp.exec(string).

How would you retrieve the index in that case? I'm a bit lost.

> I don't think defaulting to 0 would do us any good. Maybe -1 or NaN so it explodes at the next usage instead doing something random.

Well that works for me as well. I would propably prefer -1 tho.

> The index is always present, when the regex does not use the global flag.

Where did you find this information? I was searching for this when I wrote my previous comment but didn't find anything. :(

2023-10-09 18:43 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      const tokenIndex: number = token.index!;
> > We could switch from string.match(regex) to regexp.exec(string).
> 
> How would you retrieve the index in that case? I'm a bit lost.

In that case the index property is always there.

2023-10-09 18:44 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      const tokenIndex: number = token.index!;
> > The index is always present, when the regex does not use the global flag.
> 
> Where did you find this information? I was searching for this when I wrote my previous comment but didn't find anything. :(

Try and error + some stackoverflow.

2023-10-09 19:09 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      const tokenIndex: number = token.index!;
FFR: https://typescript-eslint.io/rules/prefer-regexp-exec/

2023-10-10 20:07 UTC, ST-DDT commented
See #2466 for a regex related NNA `!` relief.

- #2466 

(Technically not blocking, but might be worth merging first)

2023-10-20 08:47 UTC, ST-DDT commented
Ready to review again. 😉

2023-10-22 14:01 UTC, xDivisionByZerox approved these changes, later dismissed

2023-10-22 14:01 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +    args: Parameters<TMethod> = [] as unknown as Parameters<TMethod>,
We could probably "fix" this casting by some generic making but as the function is deprecated anyway I'd not waste time optimizing this.

2023-10-22 21:24 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    args: Parameters<TMethod> = [] as unknown as Parameters<TMethod>,
Having a default here is basically a lie because some parameters may be required... But that is something for a different PR if at all.

2023-10-31 18:37 UTC, xDivisionByZerox approved these changes, later dismissed

2023-11-06 18:57 UTC, xDivisionByZerox commented on src/modules/date/index.ts
> +export function demo(
This is propably not supposed to be here?

2023-11-06 20:56 UTC, ST-DDT commented on src/modules/date/index.ts
> +}
```suggestion

```

2023-11-06 20:59 UTC, ST-DDT commented on src/modules/date/index.ts
> +export function demo(
Yeah, I used that code to test some cases for the deprecation warnings that for some reason appeared as part of this PR.

- https://github.com/gund/eslint-plugin-deprecation/issues/74
- https://github.com/gund/eslint-plugin-deprecation/issues/75

2023-11-07 16:07 UTC, xDivisionByZerox submitted a review, later dismissed

2023-11-12 11:24 UTC, xDivisionByZerox approved these changes

2023-11-14 16:05 UTC, ST-DDT commented
**Team Decision**

This is largely unchanged since creation and has been approved for more than a week (if you ignore the minor merge conflicts).

2023-11-14 16:11 UTC, merged