docs: improve wording regarding locale selection
faker-js/faker pull request #2436
Opened 2023-10-06 19:58 UTC by ST-DDT

There is no locale to "set". You can only "pick" one. Not sure about the phrasing.

2023-10-07 12:34 UTC, matthewmayer requested changes

2023-10-07 12:34 UTC, matthewmayer commented on README.md
> +- 🌏 Localization - Pick a locale to generate realistic looking Names, Addresses, and Phone Numbers for.
I would delete the "for" at the end of the sentence it sounds awkward in English.

2023-10-07 13:21 UTC, ST-DDT commented on README.md
> +- 🌏 Localization - Pick a locale to generate realistic looking Names, Addresses, and Phone Numbers for.
Fixed

2023-10-07 21:34 UTC, xDivisionByZerox approved these changes

2023-10-08 14:19 UTC, matthewmayer approved these changes

2023-10-09 12:51 UTC, merged