infra(unicorn): no-hex-escape
faker-js/faker pull request #2440
Opened 2023-10-07 13:13 UTC by ST-DDT

Ref: #2439

- #2439

---

Enables the [unicorn/no-hex-escape](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-hex-escape.md) lint rule.

2023-10-07 21:29 UTC, xDivisionByZerox submitted a review, later dismissed
> Enforces a convention ]...[ for consistency and clarity.

Good think unicode encoding is so much more clear for me as a human than hex encoding xD

2023-10-07 23:08 UTC, import-brain submitted a review, later dismissed

2023-10-08 14:26 UTC, matthewmayer requested changes
I don't find either very readable. Could we define a constant for a non breaking space like

const nbsp = "\ua00"

2023-10-08 17:19 UTC, ST-DDT commented
> I don't find either very readable. Could we define a constant for a non breaking space like
> 
> const nbsp = "\ua00"

Done

2023-10-08 17:27 UTC, xDivisionByZerox approved these changes

2023-10-08 17:30 UTC, matthewmayer approved these changes

2023-10-09 15:40 UTC, merged