infra(unicorn): prefer-array-some
faker-js/faker pull request #2451
Opened 2023-10-09 09:54 UTC by ST-DDT

Ref: #2439

- #2439

---

Enables the [`unicorn/prefer-array-some`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-array-some.md) lint rule.

2023-10-09 12:23 UTC, matthewmayer requested changes

2023-10-09 12:23 UTC, matthewmayer commented on test/modules/system.spec.ts
>              faker.system.cron({ includeNonStandard: true })[0],
This whole test seems awkwardly written. If we're only testing the first char maybe refactor to use startsWith?

2023-10-09 12:59 UTC, ST-DDT commented on test/modules/system.spec.ts
>              faker.system.cron({ includeNonStandard: true })[0],
I'm not sure how to make it less awkward.

Maybe like this:

````ts
const validPrefixes = [...'0123456789*@'];
const actual = faker.system.cron({ includeNonStandard: true });
expect(
    validPrefixes .some((prefix) => actual.startsWith(prefix))
).toBe(true);
````

?

2023-10-09 13:02 UTC, ST-DDT commented on test/modules/system.spec.ts
>              faker.system.cron({ includeNonStandard: true })[0],
Alternatively:

````ts
const validResults = new Set('0123456789*@');
const actual = faker.system.cron({ includeNonStandard: true })[0];

expect(validResults).toContain(actual);
````

2023-10-09 19:05 UTC, ST-DDT commented on test/modules/system.spec.ts
>              faker.system.cron({ includeNonStandard: true })[0],
Done

2023-10-11 19:36 UTC, xDivisionByZerox submitted a review, later dismissed

2023-10-20 06:10 UTC, import-brain submitted a review, later dismissed

2023-10-20 06:37 UTC, matthewmayer approved these changes, later dismissed

2023-10-20 15:00 UTC, ST-DDT commented
Ready for review

2023-10-20 22:35 UTC, xDivisionByZerox approved these changes

2023-10-26 18:53 UTC, merged