infra(unicorn): prefer-ternary
faker-js/faker pull request #2464
Opened 2023-10-10 10:05 UTC by ST-DDT

Ref: #2439

- #2439

---

Enables the [`unicorn/prefer-ternary`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-ternary.md) lint rule.

2023-10-10 10:06 UTC, ST-DDT commented
This is probably one of the more controversial rules.

2023-10-10 11:40 UTC, matthewmayer requested changes
Disagree. Long ternaries are ugly and hard to read.

2023-10-15 11:41 UTC, ST-DDT commented
@matthewmayer Are there any changes that improve readability for you or would you like to revert them all?

2023-10-17 16:27 UTC, ST-DDT reviewed
We will permanently disable the rule.

2023-10-17 16:27 UTC, ST-DDT commented on src/modules/finance/index.ts
> +      : randValue.toFixed(dec);
Yes.

2023-10-17 16:27 UTC, ST-DDT commented on src/modules/finance/index.ts
> +            : this.faker.helpers.arrayElement(iban.alpha);
No.

2023-10-17 16:27 UTC, ST-DDT commented on src/modules/internet/index.ts
> +        pattern = consonant.test(prefix) ? vowel : consonant;
Yes.

2023-10-17 16:27 UTC, ST-DDT commented on src/modules/date/index.ts
> +        context && source['abbr_context'] != null ? 'abbr_context' : 'abbr';
Edit

```suggestion
      const useContext = context && source['abbr_context'] != null;
      type = useContext ? 'abbr_context' : 'abbr';
```

2023-10-17 16:27 UTC, ST-DDT commented on src/modules/person/index.ts
> +        : generic;
No.

2023-10-17 16:27 UTC, ST-DDT commented on src/simple-faker.ts
> +        : () => new Date(dateOrSource);
No

2023-10-17 16:27 UTC, ST-DDT commented on src/utils/merge-locales.ts
> +          : { ...locale[key], ...merged[key] };
No

2023-10-20 09:01 UTC, ST-DDT commented
Ready for review.

2023-10-20 11:05 UTC, matthewmayer approved these changes

2023-10-20 14:36 UTC, import-brain approved these changes

2023-10-26 22:05 UTC, xDivisionByZerox approved these changes

2023-10-26 22:12 UTC, merged