refactor(image): randomize defaults
faker-js/faker pull request #2472
Opened 2023-10-12 16:05 UTC by olrtg

Removes hard-coded defaults and randomizes them. Did this to all methods in the `image` module but didn't touch the deprecated ones.

Fixes #2314.

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * @param options.height The height of the image. Defaults to `this.faker.number.int({ min: 1, max: 3999 })`.
I would probably refer to it as Defaults to a random value between `1` and `3999`.

(although I would include 4000 as well)

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +       * @default this.faker.number.int({ min: 1, max: 3999 })
```suggestion
       * @default faker.number.int({ min: 1, max: 3999 })
```

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +       * @default this.faker.number.int({ min: 1, max: 3999 })
```suggestion
       * @default faker.number.int({ min: 1, max: 3999 })
```

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * @param options.height The height of the image. Defaults to `this.faker.number.int({ min: 1, max: 3999 })`.
Same here

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +       * @default this.faker.number.int({ min: 1, max: 3999 })
```suggestion
       * @default faker.number.int({ min: 1, max: 3999 })
```

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +       * @default this.faker.number.int({ min: 1, max: 3999 })
```suggestion
       * @default faker.number.int({ min: 1, max: 3999 })
```

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * @param options.height The height of the image. Defaults to `this.faker.number.int({ min: 1, max: 3999 })`.
Same here

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +       * @default this.faker.number.int({ min: 1, max: 3999 })
```suggestion
       * @default faker.number.int({ min: 1, max: 3999 })
```

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +       * @default this.faker.number.int({ min: 1, max: 3999 })
```suggestion
       * @default faker.number.int({ min: 1, max: 3999 })
```

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * @param options.height The height of the image. Defaults to `this.faker.number.int({ min: 1, max: 3999 })`.
Same here.

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +       * @default this.faker.number.int({ min: 1, max: 3999 })
```suggestion
       * @default faker.number.int({ min: 1, max: 3999 })
```

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +       * @default this.faker.number.int({ min: 1, max: 3999 })
```suggestion
       * @default faker.number.int({ min: 1, max: 3999 })
```

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
>        type = 'svg-uri',
Please randomize this as well.

2023-10-12 16:19 UTC, ST-DDT commented on src/modules/image/index.ts
> +      blur,
Please randomize these as well.

2023-10-12 16:29 UTC, olrtg commented on src/modules/image/index.ts
> +   * @param options.height The height of the image. Defaults to `this.faker.number.int({ min: 1, max: 3999 })`.
I saw this function and that's how I ended up doing 1 - 3999 https://fakerjs.dev/api/image.html#urlplaceholder. Ok, will change the "Defaults to" message.

2023-10-12 16:35 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * @param options.height The height of the image. Defaults to `this.faker.number.int({ min: 1, max: 3999 })`.
Good catch.

2023-10-12 16:43 UTC, olrtg commented on src/modules/image/index.ts
>        type = 'svg-uri',
This is done already I think 🤔

2023-10-12 16:43 UTC, olrtg commented on src/modules/image/index.ts
> +      blur,
This is done already I think 🤔

2023-10-12 16:47 UTC, olrtg commented
Done with the comments! Lunch time for me so please let me know if there's anything left to do on my side so I can work on that later. 🤘🏽

2023-10-12 16:53 UTC, ST-DDT commented on src/modules/image/index.ts
>        type = 'svg-uri',
It isn't yet.

2023-10-12 16:53 UTC, ST-DDT commented on src/modules/image/index.ts
> +      blur,
It isn't yet.

2023-10-12 17:41 UTC, olrtg commented on src/modules/image/index.ts
> +      blur,
Are you talking about the `grayscale` and `blur` option?

2023-10-12 17:41 UTC, olrtg commented on src/modules/image/index.ts
>        type = 'svg-uri',
Oh I think I get it now... are you talking about the `type` option?

2023-10-12 18:49 UTC, ST-DDT commented on src/modules/image/index.ts
> +      blur,
Yes

2023-10-12 18:49 UTC, ST-DDT commented on src/modules/image/index.ts
>        type = 'svg-uri',
Yes

2023-10-12 20:59 UTC, olrtg commented on src/modules/image/index.ts
>        type = 'svg-uri',
Done!

2023-10-12 21:05 UTC, olrtg commented on src/modules/image/index.ts
> +      blur,
Done! Doubting a little of the randomization of the `blur` option. `faker.number.int(10)` seemed like a great candidate since is simpler, but it has the implicit `0` and in theory, the default was `false` not `0` (not that it matters to much thought, the conditional just check for a range between `1` and `10`). Please LMK what you think. A little bit of guidance would be great.

2023-10-12 21:55 UTC, ST-DDT commented on src/modules/image/index.ts
> +      ]),
Maybe use `faker.helpers.maybe`

2023-10-13 02:16 UTC, olrtg commented on src/modules/image/index.ts
> +      ]),
Done! But now it seems that one of the tests is breaking because is not seeded. How should I approach that?

2023-10-13 08:51 UTC, ST-DDT commented on src/modules/image/index.ts
> +      ]),
You can extend the pattern to account for the new data:

````ts
/^https:\/\/picsum\.photos\/seed\/[0-9a-zA-Z]+\/\d+\/\d+(\?(grayscale&?)?(blur=\d+)?)?$/ 
````

2023-10-13 09:02 UTC, ST-DDT commented on src/modules/image/index.ts
> +       * @default faker.helpers.maybe(() => faker.number.int({ min: 1, max: 10 }))
🤔 Now there is no way to explicitly turn it off.

Maybe we must extend the type with `false` or `0`?

I have to think about it.

2023-10-13 09:05 UTC, ST-DDT commented on src/modules/image/index.ts
> +       * @default faker.helpers.maybe(() => faker.number.int({ min: 1, max: 10 }))
Yeah, maybe just allow `0` to turn blur off and to simplify the `faker.number.int` call.
Please adjust the description/jsdocs accordingly.

2023-10-13 11:58 UTC, olrtg commented on src/modules/image/index.ts
> +       * @default faker.helpers.maybe(() => faker.number.int({ min: 1, max: 10 }))
Yeah, for me allowing `0` is the right call. I have extended the type to allow `0` too.

2023-10-13 11:58 UTC, olrtg commented on src/modules/image/index.ts
> +      ]),
Done!

2023-10-14 11:30 UTC, ST-DDT commented on src/modules/image/index.ts
>         * Whether the image should be blurred.
Please mention here and above that blur 0 disables the blur.

2023-10-14 11:54 UTC, olrtg commented on src/modules/image/index.ts
>         * Whether the image should be blurred.
Done!

2023-10-14 12:59 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * @param options.blur Whether the image should be blurred. Defaults to a random integer from `0` to `10`. `0` disables the blur.
One last thing, we usually put the default sentence last.
```suggestion
   * @param options.blur Whether the image should be blurred. `0` disables the blur. Defaults to a random integer from `0` to `10`.
```

2023-10-14 13:00 UTC, olrtg commented on src/modules/image/index.ts
> +   * @param options.blur Whether the image should be blurred. Defaults to a random integer from `0` to `10`. `0` disables the blur.
Oh! got it

2023-10-14 13:18 UTC, ST-DDT submitted a review, later dismissed
Looks good to me. Please note that it still wont be merged because it is schedulled for v9.

2023-10-14 13:33 UTC, olrtg commented
Thank you so much! a pleasure working with you 🤘🏽

2023-10-26 22:00 UTC, xDivisionByZerox approved these changes, later dismissed

2023-11-25 21:21 UTC, suyashgulati approved these changes
Looks good!

2024-01-08 14:53 UTC, matthewmayer requested changes
While preparing some draft documentation for the breaking change, i found a problem, you can't prevent grey/blurred images when using `faker.image.url()`

`faker.image.url()` picks from `faker.image.urlLoremFlickr()` and `faker.image.urlPicsumPhotos()` at random.  But `faker.image.urlPicsumPhotos()` now randomly adds blur and greyscale parameters. If you don't want that you can turn it off using for example

`faker.image.urlPicsumPhotos({width:640, height:480, blur:0, grayscale:false})`

But `faker.image.url` doesn't support the blur and grayscale parameters, so

faker.image.url({width:640, height:480, blur:0, grayscale:false}) still gives you blurry or greyscale pics on the 50% of picsum photos.

Perhaps blur:0 and grayscale:false should be passed to `urlPicsumPhotos()` when called by `url()`

2024-01-17 21:23 UTC, olrtg commented
@matthewmayer From what I can see in the test snapshots the latest commit should do the trick, but I don't really know how to test this easily or how you test this (will be good to know if you don't mind sharing it).

Let me know if there's something else to fix on my end.

2024-01-18 10:37 UTC, matthewmayer commented
Per #2521 we want to prepare documentation for breaking changes in advance. Please insert this draft content at `docs/guide/upgrading_v9/2472.md` which will be inserted into the v9 migration guide once this is merged.

```
### Images now have random width, height and other options by default

`faker.image.url()` now returns an image with a random width and height by default. To obtain the previous behavior, pass `{width: 640, height: 480}`.

`faker.image.urlLoremFlickr()` now returns an image with a random width and height by default. To obtain the previous behavior, pass `{width: 640, height: 480}`.

`faker.image.urlPicsumPhotos()` now returns an image with a random width and height by default, additionally images may be converted to grayscale and blurred at random. To obtain the previous behavior, pass `{width: 640, height: 480, blur: 0, grayscale: false}`

`faker.image.dataUri()` now returns an image with a random width and height by default, additionally the type of the image is now random. To obtain the previous behavior, pass `{width: 640, height: 480, type: 'svg-uri'}`.
```

2024-01-19 18:28 UTC, olrtg commented
@matthewmayer done!

2024-01-19 20:14 UTC, ST-DDT approved these changes

2024-02-08 19:10 UTC, ST-DDT commented
Ready for review.

2024-02-11 22:52 UTC, Shinigami92 approved these changes

2024-02-11 22:58 UTC, matthewmayer approved these changes

2024-02-11 23:06 UTC, merged