docs: consistent @see jsdoc tags
faker-js/faker pull request #2473
Opened 2023-10-12 16:12 UTC by ST-DDT

Fixes #2057

- #2057

Requires that all `@see` tags that point to faker methods follow the following pattern:

````txt
@see faker.<module>.<method>(.*): [A-Z]___.
````

---

All changes are in a single PR to make it easier to cross compare the individual changes.
Feedback and re-phrasing suggestions welcome.

2023-10-12 23:04 UTC, xDivisionByZerox requested changes

2023-10-12 23:04 UTC, xDivisionByZerox commented on src/definitions/finance.ts
> +   * @see faker.helpers.replaceCreditCardSymbols(): For more information about the how the pattern is used.
```suggestion
   * @see faker.helpers.replaceCreditCardSymbols(): For more information about how the pattern is used.
```

2023-10-12 23:04 UTC, xDivisionByZerox commented on src/definitions/phone_number.ts
> +   * @see faker.helpers.replaceSymbolWithNumber(format): For more information about the how the patterns are used.
```suggestion
   * @see faker.helpers.replaceSymbolWithNumber(format): For more information about how the patterns are used.
```

2023-10-12 23:04 UTC, xDivisionByZerox commented on src/modules/datatype/index.ts
> +   * @see faker.date.between(): For the new method when generating a random date between the two dates.
```suggestion
   * @see faker.date.between(): For the new method when generating a random date in between two dates.
```

2023-10-12 23:04 UTC, xDivisionByZerox commented on src/modules/image/index.ts
> +   * @see faker.image.url(): To generate a random image url (has less options, but doesn't break when LoremFlickr is removed).
I'm not sure abou the "doesn't break when LoremFlickr is removed". This seems oddly specific. Just leaving the comment and comming back later with a suggestion.

2023-10-12 23:04 UTC, xDivisionByZerox commented on src/modules/person/index.ts
> +   * Returns a random sex type (usable in parameters).
Not sure about the parenthesis. Maybe just start a new sentence explaining the usage.

2023-10-12 23:04 UTC, xDivisionByZerox commented on src/modules/random/index.ts
> +   * @see faker.lorem.word(): To generate a random placeholder/unreadable word.
I mean it is very readable if you know how to speak latin.

```suggestion
   * @see faker.lorem.word(): To generate a random placeholder word.
```

2023-10-12 23:04 UTC, xDivisionByZerox commented on src/modules/random/index.ts
> +   * @see faker.lorem.words(): To generate a sequence of random placeholder/unreadable words.
```suggestion
   * @see faker.lorem.words(): To generate a sequence of random placeholderwords.
```

2023-10-12 23:04 UTC, xDivisionByZerox commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +                ).toMatch(/\): [A-Z].{9,}\.$/);
The length of 9 to represent a sentence is choosen randomly or based on some research you have done?

2023-10-12 23:13 UTC, ST-DDT commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +                ).toMatch(/\): [A-Z].{9,}\.$/);
It is chosen randomly => Supposedly more than 1 word.

2023-10-15 14:14 UTC, ST-DDT commented on src/modules/person/index.ts
> +   * Returns a random sex type (usable in parameters).
Replaced.

2023-10-15 14:15 UTC, ST-DDT commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +                ).toMatch(/\): [A-Z].{9,}\.$/);
I could change it to 8+capital letter dot=10 or just 10 to make it less arbitrary.

2023-10-15 14:25 UTC, matthewmayer requested changes
There's quite a lot of inconsistency in the phrasing like:

* If you wish to generate foo
* If you would like to generate foo
* For a method that returns foo
* To generate foo

2023-10-15 14:25 UTC, matthewmayer commented on src/modules/image/index.ts
> +   * @see faker.image.url(): To generate a random image url (has less options, but doesn't break when LoremFlickr is removed).
"less options" is also bad grammar, it should be "fewer options"

2023-10-16 02:43 UTC, matthewmayer commented on src/modules/image/index.ts
> +   * @see faker.image.url(): To generate a random image url (has less options, but doesn't break when LoremFlickr is removed).
How about

To generate a random image url (has fewer options, uses multiple image providers).

2023-10-18 22:52 UTC, xDivisionByZerox commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +                ).toMatch(/\): [A-Z].{9,}\.$/);
Could you split these expectation into two statements? Basically:

- Expect method reference to have a description ending with a dot
- Expect method reference to have a description to be a sentence

2023-10-20 09:27 UTC, ST-DDT commented
Here are all `@see` tags with plain text:

<details>
<summary>`@see` Tags</summary>

````ts
@see faker.company.name(): For a method that returns a complete company name.
@see faker.date.anytime(): For the new method when generating a random date in either the past or future.
@see faker.date.between(): For dates in a specific range.
@see faker.date.between(): For the new method when generating a random date in between two dates.
@see faker.date.future(): For dates explicitly in the future.
@see faker.date.future(): For dates further in the future (years instead of days).
@see faker.date.past(): For dates explicitly in the past.
@see faker.date.past(): For dates further back in time (years instead of days).
@see faker.date.recent(): For dates in the recent past (days instead of years).
@see faker.date.soon(): For dates in the near future (days instead of years).
@see faker.finance.accountNumber(): For the new method that replaces this one.
@see faker.finance.maskedNumber(): For the new method that replaces this one.
@see faker.helpers.fromRegExp(): Generates a string matching the given regex like expressions.
@see faker.helpers.mustache(): For more information about how the phrases are generated.
@see faker.helpers.mustache(): If you wish to use custom functions for resolution.
@see faker.helpers.replaceCreditCardSymbols(): For more information about how the pattern is used.
@see faker.helpers.replaceSymbolWithNumber(format): For more information about how the patterns are used.
@see faker.helpers.replaceSymbols(): For more information about how the pattern is used.
@see faker.image.url(): To generate a random image url (has less options, but doesn't break when LoremFlickr is removed).
@see faker.image.urlLoremFlickr(): To generate a random image url from LoremFlickr.
@see faker.internet.displayName(): If you wish to generate a Unicode display name.
@see faker.internet.userName(): If you wish to generate a plain ASCII username.
@see faker.location.city(): For the new method that replaces this one.
@see faker.location.street(): For the new method that replaces this one.
@see faker.location.zipCode(): For the new method that replaces this one.
@see faker.lorem.word(): To generate a random placeholder word.
@see faker.lorem.words(): To generate a sequence of random placeholder words.
@see faker.number.bigInt(): For the new method when generating a random bigint.
@see faker.number.binary(): If you would like to generate a `binary number` (within a range).
@see faker.number.float(): For the new method when generating a random floating-point number.
@see faker.number.hex(): For the new method when generating a random hexadecimal number.
@see faker.number.int(): For the new method when generating a random integer.
@see faker.number.int(): If you would like to generate a `number` (within a range).
@see faker.number.octal(): If you would like to generate an `octal number` (within a range).
@see faker.person.gender(): If you would like to generate gender related values.
@see faker.person.gender(): If you would like to use the gender value in forms.
@see faker.person.sex(): If you would like to generate binary-gender values.
@see faker.person.sex(): If you would like to use the sex value in forms.
@see faker.person.sexType(): If you would like to use the sex value as a parameter.
@see faker.seed(): If you wish to generate reproducible values.
@see faker.setDefaultRefDate(): If you wish to generate reproducible dates.
@see faker.setDefaultRefDate(): If you wish to generate reproducible relative dates.
@see faker.string.alpha(): For the new method replacing this one.
@see faker.string.alphanumeric(): For the new method replacing this one.
@see faker.string.binary(): If you would like to generate a `binary string` with a given length (range).
@see faker.string.hexadecimal(): For the new method when generating a random hexadecimal string.
@see faker.string.numeric(): For the new method replacing this one.
@see faker.string.numeric(): If you would like to generate a `string` of digits with a given length (range).
@see faker.string.octal(): If you would like to generate an `octal string` with a given length (range).
@see faker.string.sample(): For the new method when generating a random string.
@see faker.string.uuid(): For the new method when generating a random UUID.
@see faker.word.sample(): To generate a random existing word.
@see faker.word.words(): To generate a sequence of random existing words.
@see mergeLocales() For more information about how the locales are merged.
````

</details>

Any suggestion on how to simplify them to a few patterns?

2023-10-20 09:33 UTC, ST-DDT commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +                ).toMatch(/\): [A-Z].{9,}\.$/);
Changed

2023-10-20 09:34 UTC, ST-DDT commented on src/modules/image/index.ts
> +   * @see faker.image.url(): To generate a random image url (has less options, but doesn't break when LoremFlickr is removed).
Changed

2023-10-21 05:08 UTC, matthewmayer commented
As a first step we can replace "If you would like to generate" and "If you wish to generate" and "To generate" with 

"For generating"

2023-10-21 05:11 UTC, matthewmayer commented
If its an identical replacement method (just a rename, no parameter/behavior changes) i think we could standardise on "For the replacement method"

2023-10-26 21:29 UTC, ST-DDT commented on test/scripts/apidoc/verify-jsdoc-tags.spec.ts
> +                ).toMatch(/\): .{10,}$/);
Should we change it like this:

```suggestion
                expect(
                  link,
                  'Expect method reference to start with a standard description phrase'
                ).toMatch(
                  /\): (?:For generating |For more information about |For using |For the replacement method)/
                );
```

2023-10-26 21:29 UTC, ST-DDT commented
Ready for review.

2023-11-13 12:49 UTC, matthewmayer requested changes

2023-11-13 12:49 UTC, matthewmayer commented on src/modules/datatype/index.ts
> +   * @see faker.number.int(): For generating a random integer in the future.
i dont think the "in the future" is necessary

2023-11-13 12:49 UTC, matthewmayer commented on src/modules/datatype/index.ts
> +   * @see faker.number.float(): For generating a random floating-point number in the future.
i dont think the "in the future" is necessary

2023-11-13 12:49 UTC, matthewmayer commented on src/modules/datatype/index.ts
> +   * @see faker.number.hex(): For generating a random hexadecimal number in the future.
i dont think the "in the future" is necessary

2023-11-13 12:49 UTC, matthewmayer commented on src/modules/finance/index.ts
> +   * faker.finance.currencySymbol(): For generating returns specifically the currency symbol.
remove "returns" on both lines

2023-11-13 12:49 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +   * @see faker.helpers.fromRegExp(): For generating a string matching the given regex like expressions.
hyphenate regex-like

2023-11-13 12:49 UTC, matthewmayer commented on src/modules/random/index.ts
> +   * @see faker.word.sample(): For generating a random existing word.
perhaps "real" instead of "existing"

2023-11-13 12:49 UTC, matthewmayer commented on src/modules/random/index.ts
> +   * @see faker.word.words(): For generating a sequence of random existing words.
perhaps "real" instead of "existing"

2023-11-13 12:49 UTC, matthewmayer commented on src/modules/string/index.ts
> +   * @see faker.number.binary(): For generating a `binary number` (within a range).
are the backticks needed here?

2023-11-13 13:36 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +   * @see faker.number.int(): For generating a random integer in the future.
```suggestion
   * @see faker.number.int(): For generating a random integer.
```

2023-11-13 13:37 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +   * @see faker.number.float(): For generating a random floating-point number in the future.
```suggestion
   * @see faker.number.float(): For generating a random floating-point number.
```

2023-11-13 13:38 UTC, ST-DDT commented on src/modules/datatype/index.ts
> +   * @see faker.number.hex(): For generating a random hexadecimal number in the future.
```suggestion
   * @see faker.string.hexadecimal(): For generating a random hexadecimal string.
   * @see faker.number.hex(): For generating a random hexadecimal number.
```

2023-11-13 13:38 UTC, ST-DDT commented on src/modules/finance/index.ts
> +   * faker.finance.currencySymbol(): For generating returns specifically the currency symbol.
```suggestion
   * faker.finance.currencyName(): For generating specifically the currency name.
   * faker.finance.currencySymbol(): For generating specifically the currency symbol.
```

2023-11-13 13:39 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * @see faker.helpers.fromRegExp(): For generating a string matching the given regex like expressions.
```suggestion
   * @see faker.helpers.fromRegExp(): For generating a string matching the given regex-like expressions.
```

2023-11-13 13:39 UTC, ST-DDT commented on src/modules/random/index.ts
> +   * @see faker.word.sample(): For generating a random existing word.
```suggestion
   * @see faker.word.sample(): For generating a random real word.
```

2023-11-13 13:40 UTC, ST-DDT commented on src/modules/random/index.ts
> +   * @see faker.word.words(): For generating a sequence of random existing words.
```suggestion
   * @see faker.word.words(): For generating a sequence of random real words.
```

2023-11-13 13:41 UTC, ST-DDT commented on src/modules/string/index.ts
> +   * @see faker.number.binary(): For generating a `binary number` (within a range).
They have been there already.

```suggestion
   * @see faker.number.binary(): For generating a binary number (within a range).
```

2023-11-13 13:45 UTC, ST-DDT commented on src/modules/string/index.ts
> +   * @see faker.number.octal(): For generating an `octal number` (within a range).
```suggestion
   * @see faker.number.octal(): For generating an octal number (within a range).
```

2023-11-13 13:45 UTC, ST-DDT commented on src/modules/string/index.ts
> +   * @see faker.number.int(): For generating a `number` (within a range).
```suggestion
   * @see faker.number.int(): For generating a number (within a range).
```

2023-11-13 14:03 UTC, matthewmayer approved these changes

2023-11-20 23:19 UTC, xDivisionByZerox approved these changes

2023-11-20 23:23 UTC, merged