refactor(locale): remove location data index-value-binding
faker-js/faker pull request #2476
Opened 2023-10-13 23:29 UTC by xDivisionByZerox

Removes the requirement for direction locale data lists to be sorted in a specific order.

2023-10-14 08:45 UTC, ST-DDT commented
Looks good to me.
Not sure whether we should push this in v8 or v9.

2023-10-14 08:46 UTC, ST-DDT approved these changes, later dismissed

2023-10-20 02:01 UTC, matthewmayer requested changes

2023-10-20 02:01 UTC, matthewmayer commented on src/locales/fa/location/direction.ts
> +  cardinal_abbr: [],
Note this and similar changes are a behavior change, previously
fakerFA.location.direction({abbreviated:true}) would fall back to English and return say NE

Now it throws
[Error]: Cannot get value from empty dataset.

I think thats OK but it should probably be considered a breaking change for this reason

2023-10-20 02:02 UTC, matthewmayer commented on src/locales/fa/location/direction.ts
> +  cardinal_abbr: [],
Alternatively if there is no data for cardinal_abbr etc then the abbreviated option should be ignored and the full name returned.

2023-10-20 09:15 UTC, ST-DDT commented on src/locales/fa/location/direction.ts
> +  cardinal_abbr: [],
I think we should go for breaking then.

2023-10-20 22:41 UTC, xDivisionByZerox commented on src/locales/fa/location/direction.ts
> +  cardinal_abbr: [],
Good catch. I left them like this instead of making the subset undefined  or even null because I think that this data has been forgotten to be implemented. Those values are part of the legacy package. I was not able to figure out if abbreviated content is not applicable in those locales. By throwing people with knowledge about these locales can tell us the expected behavior:
- abbreviated is same as wide context
- abbreviated context does not exist in those locales
- implement the correct abbreviated data

2023-10-21 05:15 UTC, matthewmayer commented on src/locales/fa/location/direction.ts
> +  cardinal_abbr: [],
agree, though it would be better if it threw the helpful "The locale data for.... are missing in this locale" error rather than the mysterious "Cannot get value from empty dataset" error

2023-10-21 12:30 UTC, xDivisionByZerox commented on src/locales/fa/location/direction.ts
> +  cardinal_abbr: [],
In that case, I could wrap the current type in the `LocaleEntry` type to allow `undefined` (and `null`) values. `undefined` should throw the error you suggest. I would be fine with that.

2023-10-21 13:31 UTC, matthewmayer commented on src/locales/fa/location/direction.ts
> +  cardinal_abbr: [],
Note since N, E, S, W are included in CLDR (for use in geographical coordinates) its fairly easy to look up what the equivalent of "N", "E", "S", "W" is in most languages e.g.:

https://www.unicode.org/cldr/charts/42/by_type/units.coordinates.html#2e784791aa57e39c

2023-10-21 13:34 UTC, matthewmayer commented on src/locales/fa/location/direction.ts
> +  cardinal_abbr: [],
In examples like fa or ja where there is no abbreviated version, what should we do? In that case it seems more sensible to repeat the full version in the abbreviated field.

2023-11-01 16:50 UTC, matthewmayer commented on src/locales/fa/location/direction.ts
> +  cardinal_abbr: [],
Since data has now been added for the missing locales I would no longer consider this breaking.

2023-11-01 23:26 UTC, ST-DDT approved these changes

2023-11-01 23:27 UTC, ST-DDT commented
Since we change the layout of our locale data, I think we should merge this in v9.0.

2023-11-20 14:23 UTC, matthewmayer approved these changes, later dismissed

2024-02-08 17:52 UTC, ST-DDT commented
This probably needs a check whether any new locales have been added in the meantime.

2024-02-08 17:53 UTC, ST-DDT commented
Does this need a breaking change notice?

2024-02-08 19:31 UTC, ST-DDT requested changes
I checked that no new files have been added in the meantime.

2024-02-08 19:31 UTC, ST-DDT commented on src/definitions/location.ts
>     * The abbreviated names of the compass directions.
The old `direction_abbr: string[]` needs to be removed.

2024-02-09 17:20 UTC, Shinigami92 requested changes
`docs/guide/upgrading_v9/2476.md` file required

2024-03-10 00:41 UTC, xDivisionByZerox commented
Looking at #2505, would it make sense to "flatten" this definitions as well? So instead of `direction` object with nested properties, we'd have 4 files/4properties on the location definition object.

2024-03-10 01:00 UTC, ST-DDT commented
> Looking at #2505, would it make sense to "flatten" this definitions as well? So instead of `direction` object with nested properties, we'd have 4 files/4properties on the location definition object.

We could do that, but these files are so small, that it would be harder to review the files if split up.
IMO we keep them in a single file.

2024-04-06 19:36 UTC, xDivisionByZerox commented on src/definitions/location.ts
>     * The abbreviated names of the compass directions.
Done

2024-04-06 19:48 UTC, xDivisionByZerox commented
I put "needs decision" as I'd like to discuss [my last comment](https://github.com/faker-js/faker/pull/2476#issuecomment-1987025765) in the next team meeting.

2024-04-06 19:52 UTC, ST-DDT approved these changes

2024-04-08 10:50 UTC, Shinigami92 approved these changes

2024-04-11 15:20 UTC, Shinigami92 approved these changes

2024-04-11 17:40 UTC, ST-DDT commented
**Team Decision**

We will not flatten the definitions in the same way as #2505 .

Reason:
- Being a nested object ensures that all values are always present, as the type requires it. On the other hand entries in categories are optional by force and thus it might lead to cases where `abbr` is set but the full value is missing.

2024-04-14 22:27 UTC, merged