infra(unicorn): no-array-reduce
faker-js/faker pull request #2479
Opened 2023-10-15 11:25 UTC by ST-DDT

Ref: #2439

- #2439

---

Permanently disables the [`unicorn/no-array-reduce`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-reduce.md) lint rule.

Some patterns aren't easy to represent without `reduce` especially for new developers.
Unicorn currently does not provide a way to `--fix` this error automatically yet.

I simplified some of the existing usages of array reduce, that are hopefully easier to read than the previous code.

2023-10-22 13:24 UTC, xDivisionByZerox requested changes

2023-10-22 13:24 UTC, xDivisionByZerox commented on test/all_functional.spec.ts
>  }
I'd expect an object (the module object itself) as a parameter in the `isMethodOf` function. Currently, these two functions are tightly coupled. If you change the main object (fakerEN) in one function you have to change it in the other one too.

2023-10-22 13:24 UTC, xDivisionByZerox commented on .eslintrc.js
> +    'unicorn/no-array-reduce': 'off', // not easy to avoid for new contributors
I don't agree with you here. Every `.reduce()` function can be represented as can be represented by a `for` loop. On the one problem we have in our code base you even wrote a comment on how this could be refactored. Using descriptive functions instead of a `.reduce()` should be preferred in my opinion.

2023-10-22 13:24 UTC, xDivisionByZerox commented on src/modules/word/filterWordListByLength.ts
> +    // This could be replaced with Map.groupBy once it is available
Why not write a helper function for now?

```ts
function groupBy<TVal, TKey>(
  items: Iterable<TVal>,
  keyEvaluator: (value: TVal) => TKey
): Map<TKey, TVal[]> {
  const map = new Map<TKey, TVal[]>();
  for (const item of items) {
    const key = keyEvaluator(item);
    map.set(key, [...(map.get(key) ?? []), item]);
  }

  return map;
}
```

Or if you prefer object maps:
```ts
function groupBy<TVal, TKey extends string | number | symbol>(
  items: Iterable<TVal>,
  keyEvaluator: (value: TVal) => TKey
): Record<TKey, TVal[]> {
  const map = {} as Record<TKey, TVal[]>;
  for (const item of items) {
    const key = keyEvaluator(item);
    map[key] = [...(map[key] ?? []), item];
  }

  return map;
}
```

2023-10-22 21:12 UTC, ST-DDT commented on test/all_functional.spec.ts
>  }
Like this?

2023-10-22 21:12 UTC, ST-DDT commented on .eslintrc.js
> +    'unicorn/no-array-reduce': 'off', // not easy to avoid for new contributors
Changed.

2023-10-22 21:13 UTC, ST-DDT commented on src/modules/word/filterWordListByLength.ts
> +    // This could be replaced with Map.groupBy once it is available
Done.

2023-10-26 14:54 UTC, xDivisionByZerox commented on test/all_functional.spec.ts
>  }
Yes, thank you. This makes the function more pure. 👍

2023-10-26 15:03 UTC, xDivisionByZerox submitted a review, later dismissed
Remaining suggestions are optional. Thats why I'll already approve.

2023-10-26 15:03 UTC, xDivisionByZerox commented on test/all_functional.spec.ts
> +function isMethodOf(module: Faker[keyof Faker]): (method: string) => boolean {
Nitpick: The "module" technically could be any object, which allows the function to be used in a more generic context.

```suggestion
function isMethodOf(module: object): (method: string) => boolean {
```

2023-10-26 19:07 UTC, xDivisionByZerox approved these changes, later dismissed

2023-10-31 22:29 UTC, xDivisionByZerox approved these changes, later dismissed

2023-11-06 18:40 UTC, xDivisionByZerox approved these changes

2023-11-07 16:26 UTC, merged