feat: add autocomplete support for locales
faker-js/faker pull request #248
Opened 2022-01-21 15:41 UTC by ST-DDT

I will automate the generation/update for `KnownLocale`s in a later PR.

The is the TypeScript related part for https://github.com/faker-js/faker/issues/210

2022-01-21 15:44 UTC, ST-DDT commented
This doesn't work yet due to `export = locales;` in `src/locales/index.ts`.

2022-01-21 17:35 UTC, Shinigami92 requested changes

2022-01-21 17:35 UTC, Shinigami92 commented on src/index.ts
> +export type UseableLocale = LiteralUnion<KnownLocale>;
```suggestion
export type UsableLocale = LiteralUnion<KnownLocale>;
```

2022-01-21 17:35 UTC, Shinigami92 commented on src/index.ts
> +export type UseableLocale = LiteralUnion<KnownLocale>;
and all below...

2022-01-21 17:41 UTC, Shinigami92 submitted a review, later dismissed

2022-01-21 22:39 UTC, Shinigami92 approved these changes

2022-01-23 11:33 UTC, prisis approved these changes

2022-01-23 11:34 UTC, merged

2022-02-01 17:25 UTC, pkuczynski commented on src/locales/index.ts
> +export type KnownLocale =
yes, first create the locales, and then below it, create the `KnownLocale` type. There is no circular reference if they stay in the same file.

2022-02-01 17:28 UTC, pkuczynski commented on src/locales/index.ts
> +export type KnownLocale =
Something like this I had in mind:

```ts
const locales = {
  af_ZA,
  ar,
  ...
};

export type KnownLocale = keyof typeof locales

export default locales;
```

<img width="296" alt="image" src="https://user-images.githubusercontent.com/374864/152019231-5a85d2a8-50b8-4063-895f-4dd81d390f36.png">

2022-02-01 17:31 UTC, ST-DDT commented on src/locales/index.ts
> +export type KnownLocale =
Could you please create an issue (or PR) for that?
I currently work on something different and don't want to forget about it.