feat(food): new module
faker-js/faker pull request #2484
Opened 2023-10-17 20:18 UTC by xDivisionByZerox

## Description

MVP implementation for a new `FoodModule`. The locale data is based on the dataset of [the ruby Faker](https://github.com/faker-ruby/faker/blob/main/lib/locales/en/food.yml) library.

Feel free to discuss certain implementation details or locale data as you wish.

## More Context

Resolves #1593.

2023-10-17 21:34 UTC, ST-DDT commented on test.ts
This file seems to have been committed by accident.

2023-10-17 21:34 UTC, ST-DDT commented on test/modules/__snapshots__/food.spec.ts.snap
> +exports[`food > 1211 > description 1`] = `"A special turquoise Sunflower Seeds from San Marino. To support the strong flavor it is sided with a tablespoon of Chillies."`;
🤣

2023-10-17 21:34 UTC, ST-DDT commented on test/modules/food.spec.ts
> +    t.it('vegetable');
You could merge them together, by just calling `t.itEach(...)`

2023-10-17 22:04 UTC, xDivisionByZerox commented on test.ts
Wups. was testing something. Thank you.

2023-10-17 22:05 UTC, xDivisionByZerox commented on test/modules/__snapshots__/food.spec.ts.snap
> +exports[`food > 1211 > description 1`] = `"A special turquoise Sunflower Seeds from San Marino. To support the strong flavor it is sided with a tablespoon of Chillies."`;
Glad you had a good laught. Was my intention with these description. Hope it's still "professional" enougth.

2023-10-17 22:07 UTC, xDivisionByZerox commented on test/modules/food.spec.ts
> +    t.it('vegetable');
I know that this is a possibility, but had trouble with the auto completion on the keys 🤔

2023-10-18 04:48 UTC, matthewmayer requested changes

2023-10-18 04:48 UTC, matthewmayer commented on src/locales/en/food/dish.ts
> +  'Arepas',
I feel the dish definitions are very limited, given this is probably the most useful method for a lot of use cases (eg restaurant menus). I think we could add a lot of extra dishes from the Ruby version and/or use fake patterns to allow for many more dish names.

2023-10-18 04:51 UTC, matthewmayer requested changes

2023-10-18 04:51 UTC, matthewmayer commented on src/locales/en/food/fruit.ts
> +  'Apples',
We should be consistent if these are singular or plural

2023-10-18 15:25 UTC, xDivisionByZerox commented on src/locales/en/food/fruit.ts
> +  'Apples',
Any preferences? I feel like these should be sigular, but can't give reasoning for that.

2023-10-18 22:50 UTC, xDivisionByZerox commented on src/locales/en/food/dish.ts
> +  'Arepas',
Agreed. 

---

An additional thought: Should dishes be categorized? Like having a file for categories:

- pizza: Pizza Margherita, Pizza Pepperoni, New York Style Pizza, etc
- pasta: Lasagna, Spaghetti, Tagliatelle, etc
- salad: chef salad, caesar salad, potato salad

These files do not have to be exposed individually but are exposed via a fake expression in the `dish.ts` file. That why each locale can have different dish categories.

2023-10-18 23:27 UTC, ST-DDT commented on src/locales/en/food/dish.ts
> +  'Arepas',
While I think, that we should extend the list a bit, I don't see a need for fake patterns here.

> An additional thought: Should dishes be categorized? Like having a file for categories:

If there is sufficient user demand for it maybe. Not as part of the MVP.

2023-10-18 23:29 UTC, ST-DDT commented on src/locales/en/food/fruit.ts
> +  'Apples',
Just go for singular for now. Most plurals are easily achievable by just appending an `s` to the pattern.
Should they be lowercase as well?

2023-10-18 23:37 UTC, matthewmayer requested changes

2023-10-18 23:37 UTC, matthewmayer commented on src/locales/en/food/description_pattern.ts
> +  '28-day aged 300g {{animal.cow}} steak, with choice of two sides.',
Many languages including English distinguish between animal words and meat words. 

Eg beef, lamb, venison vs cow, sheep, deer

I think we could have a food.protein or food.meat method which returns popular meats or meat substitutes which can be used in other patterns eg chicken,beef,lamb,venison,veal,turkey,tofu

2023-10-18 23:38 UTC, matthewmayer commented on src/locales/en/food/fruit.ts
> +  'Apples',
Lowercase and singular seems most flexible in English

2023-10-18 23:39 UTC, matthewmayer commented on src/locales/en/food/fruit.ts
> +  'Apples',
Singular also allows for phrases like "{{food.fruit}} sauce"

2023-10-18 23:41 UTC, matthewmayer commented on src/locales/en/food/dish.ts
> +  'Arepas',
I had a few use case of needing to generate menus for hundreds of restaurants each of which would have 20-50 menu items. 

Fake patterns would allow for 1000s of unique dishes without needing 1000s of definitions. Eg if you have "{{food.ethnicCategory}} Salmon" or "{{food.fruit}} Pie" in the list you multiply your unique dishes dramatically.

2023-10-19 05:29 UTC, import-brain commented on src/locales/en/food/fruit.ts
> +  'Apples',
I would also be in favor of lowercase and singular

2023-10-24 17:01 UTC, ST-DDT commented on src/locales/en/food/dish.ts
> +  'Arepas',
**Team Decision**

- We will add both `dish` and `dish_patterns`.

2023-10-25 01:51 UTC, matthewmayer requested changes, later dismissed

2023-10-25 01:51 UTC, matthewmayer commented on src/locales/en/food/description_pattern.ts
> +  'A slow-roasted {{animal.bird}} with a crisp, golden exterior. Stuffed with {{food.fruit}} and covered in {{food.fruit}} sauce. Sides with {{food.vegetable}} puree and wild {{food.vegetable}}.',
could also be useful to have a food.adjective which is a list of adjectives commonly applied to food that can be used in dish names and descriptions, e.g.
```
[
    "crunchy",
    "delicious",
    "golden",
    "savory",
    "spicy",
    "sweet",
    "bitter",
    "tangy",
    "creamy",
    "juicy",
    "crispy",
    "tender",
    "salty",
    "sour",
    "zesty",
    "fluffy",
    "moist",
    "fresh",
    "rich",
    "smoky"
  ]
}
```

2023-10-30 09:35 UTC, ST-DDT commented
Please fix the "merge conflicts" (although I don't think there are any for local executions).

2024-01-19 08:54 UTC, matthewmayer commented
@xDivisionByZerox would you be OK with me continuing work on this to address some of the feedback and get to an MVP?

2024-01-19 09:06 UTC, xDivisionByZerox commented
> @xDivisionByZerox would you be OK with me continuing work on this to address some of the feedback and get to an MVP?

@matthewmayer I would be happy if you would continue working on this.

2024-01-19 13:50 UTC, matthewmayer commented
You can see a sample menu from the Faker Bistro here ;)

https://gist.github.com/matthewmayer/794406e8281e2c796e70495a1598ec50

Generated with:
```js
console.log(faker.helpers.multiple(a=>faker.helpers.fake("**{{food.dish}}** - {{commerce.price({\"max\":30})}}\n\n{{food.description}}\n\n"),{count:50}).join(""))
```

2024-01-19 14:23 UTC, ST-DDT commented on src/modules/food/index.ts
> +  }
```suggestion
export class FoodModule extends ModuleBase {
```

2024-01-19 14:23 UTC, ST-DDT commented on src/modules/food/index.ts
> +      d.toLowerCase().replace(/\b\w/g, (s) => s.toUpperCase());
I would probably omit the toLowercase here in case we have parts that are already capitalized e.g.

`MC Danold's delicious beacon` -> `Mc Danold'S Delicious Beacon`

Also the `'S` should probably be not capitalized.

If we capitalize the dishes anyway, should we also capitalize them in the locale data?

2024-01-20 01:12 UTC, matthewmayer commented on src/modules/food/index.ts
> +      d.toLowerCase().replace(/\b\w/g, (s) => s.toUpperCase());
No, because we don't want them capitalised in dish descriptions.

2024-01-20 01:53 UTC, matthewmayer commented on src/modules/food/index.ts
> +      d.toLowerCase().replace(/\b\w/g, (s) => s.toUpperCase());
replaced with a less aggressive capitalization function

2024-02-10 11:18 UTC, ST-DDT commented
FFR: This feature would benefit from https://github.com/faker-js/faker/issues/2584

- https://github.com/faker-js/faker/issues/2584#issuecomment-1936971449

2024-02-10 11:26 UTC, ST-DDT submitted a review, later dismissed
A little typo but otherwise good to go.

2024-02-10 11:26 UTC, ST-DDT commented on src/modules/food/index.ts
> +   * faker.food.description() // ''An exquisite ostrich roast, infused with the essence of longan, slow-roasted to bring out its natural flavors and served with a side of creamy red cabbage'
```suggestion
   * faker.food.description() // 'An exquisite ostrich roast, infused with the essence of longan, slow-roasted to bring out its natural flavors and served with a side of creamy red cabbage'
```

2024-02-10 11:49 UTC, ST-DDT approved these changes

2024-02-10 15:55 UTC, Shinigami92 approved these changes

2024-02-11 00:49 UTC, import-brain approved these changes

2024-02-11 10:29 UTC, merged

2024-02-24 17:29 UTC, IgnusG commented
Just checking out of curiosity, I see a new version with this module has not been published yet. Is that intentional?

2024-02-24 19:21 UTC, matthewmayer commented
Yes it's intentional it will appear in v9 but there are a few more things to merge before the first alpha/beta version of v9 will be released.