refactor: simplify module creation
faker-js/faker pull request #2485
Opened 2023-10-17 22:02 UTC by ST-DDT

Simplifies the modules by reusing the constructors from a shared module base.

This is a v8.x only feature, that will likely be obsolete in v9.0.

What do you think?

2023-10-18 23:01 UTC, xDivisionByZerox requested changes
Can we add extend the test factory (or write a separate one) to include automatic test for these `this` bindings on all methods? Currently I'm not 100% sure that I can do. 

```ts
const method = faker[moduleKey][methodKey]; 
method();
```

Additionally, while being a nice little addition I have a hard time seeing the advantage of introducing it now.

2023-10-18 23:01 UTC, xDivisionByZerox commented on src/modules/module-base.ts
> +export abstract class SimpleModuleBase {
Should this file not be located in `src/internal/` if it is marked as internal?

2023-10-18 23:31 UTC, ST-DDT commented
> Can we add extend the test factory (or write a separate one) to include automatic test for these `this` bindings on all methods? Currently I'm not 100% sure that I can do.
> 
> ```ts
> const method = faker[moduleKey][methodKey]; 
> method();
> ```

We already have that:

https://github.com/faker-js/faker/blob/a1936938574f574ecc137d9f718a48a2256e49c9/test/support/seededRuns.ts#L146-L147

2023-10-20 08:51 UTC, ST-DDT commented on src/modules/module-base.ts
> +export abstract class SimpleModuleBase {
Done

2023-10-22 19:51 UTC, xDivisionByZerox approved these changes, later dismissed

2023-10-31 18:36 UTC, xDivisionByZerox approved these changes

2023-11-05 02:51 UTC, import-brain approved these changes

2023-11-06 08:40 UTC, merged