docs: how to use with Playwright
faker-js/faker pull request #2489
Opened 2023-10-21 09:49 UTC by jfgreffier

Playwright is a popular end-to-end testing solution. The tests are somewhat similar to Jest, but not exactly so here is an example of Faker integration into a Playwright test.

2023-10-21 10:02 UTC, Shinigami92 commented
@debs-obrien Does this meet your requirements? Or should we improve something, such as a way of style like Playwright should best be used?

2023-10-21 19:15 UTC, xDivisionByZerox commented on docs/guide/frameworks.md
> +    await page.getByLabel('username').fill(username);
While not related to Playwrite itself it's off-putting to me that you are required to supply the username as well as the email to sign in. Usually, only one of both is required.

2023-10-21 19:15 UTC, xDivisionByZerox commented on docs/guide/frameworks.md
> +});
We don't do that in the cypress example. So I'm not sure if we should add it there as well or remove it here.
Additionally, while you write that this "re-seeds the faker instance", the seed is still random each time. So I don't see the advantage of doing it here.

2023-10-21 19:18 UTC, xDivisionByZerox commented
[There is a formatting error.](https://github.com/faker-js/faker/actions/runs/6596632739/job/17927857451?pr=2489#step:7:9) Please run the formatter locally via `pnpm run format`. 

---

Thank you for your contribution :heart:

2023-10-21 20:55 UTC, ST-DDT commented on docs/guide/frameworks.md
> +});
The vitest one has a similar block, I think we should move them to the describe block to ensure this is run only after relevant tests, because seeding is "expensive". (Potentially in a separate PR).

2023-10-22 14:17 UTC, jfgreffier commented on docs/guide/frameworks.md
> +    await page.getByLabel('username').fill(username);
Copy-paste error. My bad!

2023-10-22 14:20 UTC, jfgreffier commented on docs/guide/frameworks.md
> +});
I removed the seed, we could add it in a dedicated seed example for clarity. In another PR that is

2023-10-22 14:41 UTC, ST-DDT commented
FFR: Please avoid force pushing as it makes incremental reviews harder.

2023-10-31 22:11 UTC, xDivisionByZerox requested changes

2023-10-31 22:11 UTC, xDivisionByZerox commented on docs/guide/frameworks.md
> +    await page.getByRole('button', { name: 'Register' }).click();
This name should propably be something like "Sign In" or "Login" as you already did register an account in the previous step.

```suggestion    
    await page.getByRole('button', { name: 'Login' }).click();
```

2023-10-31 22:11 UTC, xDivisionByZerox commented on docs/guide/frameworks.md
> +    await expect(page).toHaveURL(/.*dashboard/);
Nitpick: Since you navigate in the previous steps to an absolute URL I think it would be valid to match a full URL here as well.
```suggestion
    await expect(page).toHaveURL('https://www.example.com/dashboard');
```

2023-11-01 13:44 UTC, jfgreffier commented on docs/guide/frameworks.md
> +    await expect(page).toHaveURL(/.*dashboard/);
Personnaly I would leave matching, similarly to the Cypress example using `cy.url().should('include', '/dashboard')`

2023-11-02 17:19 UTC, xDivisionByZerox commented on docs/guide/frameworks.md
> +    await expect(page).toHaveURL(/.*dashboard/);
Valid reasoning from your side. I'll accept your version.

2023-11-02 17:20 UTC, xDivisionByZerox approved these changes

2023-11-02 17:27 UTC, ST-DDT approved these changes

2023-11-03 23:34 UTC, merged

2023-11-03 23:35 UTC, ST-DDT commented
Thanks for your contribution. ❤️