fix(internet): username method to return value that always includes…
faker-js/faker pull request #2506
Opened 2023-10-27 19:16 UTC by amillwood

Updated the username method to always return a value that includes the last name when provided.

Resolves #1000

2023-10-30 09:32 UTC, ST-DDT commented
Sorry for the delay in review, we will look at it shortly.

2023-11-02 11:41 UTC, amillwood commented
No worries. No rush, just a minor contribution - hope it helps

2023-11-02 11:50 UTC, matthewmayer requested changes

2023-11-02 11:50 UTC, matthewmayer commented on src/modules/internet/index.ts
> +      })
this seems a bit awkward. Can we change case 0 to be case 2 instead? Then we can just do something like this to make it easier to read:

```js
const hasLastName = options.lastName || legacyLastName
const strategy = this.faker.number.int(hasLastName ? 1 : 2)
switch (strategy) {
```

2023-11-02 12:47 UTC, amillwood commented on src/modules/internet/index.ts
> +      })
That is cleaner, great suggestion.  Updated!  (Also updated the JSDoc for the methods)

2023-11-02 15:09 UTC, matthewmayer requested changes

2023-11-02 15:09 UTC, matthewmayer commented on src/modules/internet/index.ts
> +   * The resulting username will use the names provided or choose a random name if one is not provided.
This is not completely true. If the names are non ascii and can't be transliterated to ascii then they are not used in the resulting username.

2023-11-02 15:09 UTC, matthewmayer commented on src/modules/internet/index.ts
> +        ])}${lastName}${this.faker.number.int(99)}`;
Maybe create a variable like `separator` above the switch which is randomly . or - (shall we add empty string as a third option?) that can be reused in the cases?

2023-11-02 15:43 UTC, ST-DDT commented
One problem I see with the username method itself is that it produces very vage usernames that you might choose for private accounts.
But I think a lot of professional users of faker need usernames that companies would use and thus roughly follows the firstName.lastName strategy.

2023-11-02 15:46 UTC, amillwood commented on src/modules/internet/index.ts
> +   * The resulting username will use the names provided or choose a random name if one is not provided.
Oh, good point.  Should I revert to the previous description?  Or what do you suggest?

2023-11-03 19:39 UTC, amillwood commented on src/modules/internet/index.ts
> +        ])}${lastName}${this.faker.number.int(99)}`;
Updated.  I did not add an empty string to the array, because the `allowSpecialCharacters` uses the separator to insert the special characters.  I wasn't sure how you all would want to proceed with that (i.e. update the test cases, or update the special character logic to insert the special character in a different way)

2023-11-04 00:16 UTC, matthewmayer commented
Companies don't always use FirstName.lastname anyway though

At companies I have worked at there have been patterns like

john.smith@
john@
jsmith@
smithj@

2023-11-04 09:21 UTC, ST-DDT commented
> Companies don't always use FirstName.lastname anyway though

My point is that companies follow a more standardized approach to usernames than private persons do.

2023-11-04 11:12 UTC, matthewmayer commented
I think using both FirstName and lastname when provided makes sense, but we could have more ways to combine them for greater variety eg

More separators including empty string
Surname or firstname first
Sometimes lowercase the whole string

2023-11-07 16:30 UTC, ST-DDT commented on test/modules/internet.spec.ts
> +          expect(prefix).includes('Harann');
Please include a similar test for the username method.

2023-11-07 16:32 UTC, ST-DDT commented
**Team Decision**

- We accept this as a fix for the problem at hand, we will rethink the username method in the future.
  - (More patterns,username modes e.g.  company, private, gamer...)

2023-11-07 17:31 UTC, amillwood commented on src/modules/internet/index.ts
> +   * The resulting username will use the names provided or choose a random name if one is not provided.
Reverted to previous description

2023-11-07 17:32 UTC, amillwood commented on test/modules/internet.spec.ts
> +          expect(prefix).includes('Harann');
updated

2023-11-07 21:15 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      lastName = legacyLastName,
If lastName isn't generated here, I would also omit the firstName generation here to stay consistent.
What do the others think?

2023-11-07 21:15 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      lastName = legacyLastName,
Same here

2023-11-07 21:15 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    const hasLastName = options.lastName || legacyLastName;
IMO this should be part of the deconstructor of options.

````ts
lastName: hasLastName = legacyLastName
````

2023-11-07 21:15 UTC, ST-DDT commented on test/modules/internet.spec.ts
>              /^Aiden((\d{1,2})|([._]Harann\d{1,2})|([._](Harann)))/
In line 400 you improved the regex, maybe do that here as well.

2023-11-07 21:15 UTC, ST-DDT commented on test/modules/internet.spec.ts
>            expect(username).includes('Aiden');
Please also check for the lastName specifically as it is easier to understand the check than when it is contained in the regex.

```suggestion
          expect(username).includes('Aiden');
          expect(username).includes('Harann');
```

2023-11-07 21:15 UTC, ST-DDT commented on test/modules/internet.spec.ts
> +          expect(prefix).toMatch(/^Mike[.!#$%&'*+-/=?^_`{|}~]Smith\d*/);
AFAICT this could also use the simplified regex similar to line 351 or 400

2023-11-09 18:30 UTC, amillwood commented on src/modules/internet/index.ts
> +      lastName = legacyLastName,
That makes sense.  Updated to add first name within username method, if undefined.

2023-11-09 18:30 UTC, amillwood commented on src/modules/internet/index.ts
> +      lastName = legacyLastName,
Updated

2023-11-09 18:31 UTC, amillwood commented on src/modules/internet/index.ts
> +    const hasLastName = options.lastName || legacyLastName;
updated

2023-11-09 18:31 UTC, amillwood commented on test/modules/internet.spec.ts
>              /^Aiden((\d{1,2})|([._]Harann\d{1,2})|([._](Harann)))/
Good catch, missed this one.  Updated

2023-11-09 18:31 UTC, amillwood commented on test/modules/internet.spec.ts
>            expect(username).includes('Aiden');
added

2023-11-09 18:34 UTC, amillwood commented on test/modules/internet.spec.ts
> +          expect(prefix).toMatch(/^Mike[.!#$%&'*+-/=?^_`{|}~]Smith\d*/);
This one is for the special character test.  I think it is as simple as we can make it.  I just removed the optional part of the regex.  Because last name is provided in this test, it should now contain the special character + last name.

2023-11-09 19:44 UTC, ST-DDT approved these changes, later dismissed

2023-11-17 22:49 UTC, xDivisionByZerox approved these changes, later dismissed

2023-11-17 23:47 UTC, ST-DDT commented
@amillwood Could you please fix the merge conflict?

2023-11-18 20:57 UTC, ST-DDT approved these changes

2023-11-18 21:04 UTC, xDivisionByZerox approved these changes

2023-11-19 08:28 UTC, matthewmayer approved these changes

2023-11-19 08:31 UTC, merged

2023-11-19 08:31 UTC, ST-DDT commented
Thanks for your contribution ❤️