feat: auto generate/update locale files
faker-js/faker pull request #252
Opened 2022-01-21 20:21 UTC by ST-DDT

This PR adds a script that automatically generates
- `src/locale/*.ts`
- and `src/locales/index.ts`.

This should be merged after https://github.com/faker-js/faker/pull/248

The is the generation/update related part for #210

Currently this is not integrated in the build process.

2022-01-21 20:34 UTC, Shinigami92 requested changes

2022-01-21 20:34 UTC, Shinigami92 commented on scripts/generateLocales.ts
> +const pathLocales = 'src/locales/';
You should use `resolve` for these

```ts
import { resolve } from 'node:path'

const pathLocale = resolve(__dirname, 'src', 'locale');
```

2022-01-21 20:34 UTC, Shinigami92 commented on scripts/generateLocales.ts
> +import fs from 'fs';
We could use `import { readdirSync, writeFileSync } from 'node:fs';`

2022-01-23 12:51 UTC, ST-DDT commented
This has been split into multiple PRs and needs to be updated once #263 and #264 have been merged.

2022-01-25 00:19 UTC, ST-DDT commented
If the following change is considered breaking, then we could just temporarily remove/change it.
That way, we can still use the automation script.

````diff
- export = faker;
+ export default faker;
````

2022-01-25 08:05 UTC, Shinigami92 commented
I thing `export = faker` is currently the right way, so plain js node users can just use `const fakerDe = require('@faker-js/faker/locale/de')` instead of `const fakerDe = require('@faker-js/faker/locale/de').default`.
So indeed, for the `locale`s we have a special case here.

2022-01-27 14:19 UTC, Shinigami92 requested changes

2022-01-27 14:19 UTC, Shinigami92 commented on package.json
> +    "generate": "esno ./scripts/generateLocales.ts",
Maybe we should be a bit more explizit here and name the script like `generate:locale`

2022-01-27 14:19 UTC, Shinigami92 commented on src/locale/en.ts
> -export = faker;
I think you missed that one, is it not generated?

2022-01-27 14:39 UTC, Shinigami92 submitted a review, later dismissed
Nice work :rocket:

2022-01-27 18:46 UTC, Shinigami92 submitted a review, later dismissed

2022-01-29 11:35 UTC, Shinigami92 commented on scripts/generateLocales.ts
> +for (let locale of locales) {
```suggestion
for (const locale of locales) {
```

2022-01-29 11:35 UTC, Shinigami92 approved these changes

2022-01-29 20:56 UTC, Shinigami92 submitted a review, later dismissed

2022-01-30 21:08 UTC, Shinigami92 approved these changes

2022-01-30 21:35 UTC, ST-DDT commented
I need this in main in order to update it for #363 .
(There is no automation enabled to this yet.)

2022-02-01 16:59 UTC, prisis approved these changes

2022-02-01 16:59 UTC, prisis commented on CONTRIBUTING.md
> +- If you update the locales, make sure to run `pnpm run generate:locales` to generate/update the related files.
Can we create a ticket to add a workflow test for this? that is only running if something in the locales folder did change?

2022-02-01 17:06 UTC, merged