fix(date): ensures correct range for birthdate
faker-js/faker pull request #2535
Opened 2023-11-08 15:47 UTC by mumumilk

fixes #2534

2023-11-09 21:14 UTC, ST-DDT requested changes

2023-11-09 21:14 UTC, ST-DDT commented on src/modules/date/index.ts
> +      min = new Date(Date.UTC(0, refMonth, minDay)).setUTCFullYear(
These interfere with the usage when specifying min and max.
Because then it can only return the current date.

2023-11-09 22:09 UTC, ST-DDT commented
Please add these tests:

https://github.com/faker-js/faker/blob/022fa540106e25818936c6ebfe8d10fe9ee15b30/test/modules/date.spec.ts#L576-L603

2023-11-10 20:22 UTC, mumumilk commented on src/modules/date/index.ts
> +      min = new Date(Date.UTC(0, refMonth, minDay)).setUTCFullYear(
good catch, but as I was working on a fix, it occurred to me that the behavior is in fact correct the way it is currently.  

Maybe we should only update the docs to mention that `mode: age` will generate more accurate values (because it already uses the `refDate`) or change the default mode to age

2023-11-10 23:45 UTC, ST-DDT commented on src/modules/date/index.ts
> +      min = new Date(Date.UTC(0, refMonth, minDay)).setUTCFullYear(
One way to ensure the age is 18+ is by subtracting 19 instead of 18 for the year mode.

2023-11-10 23:46 UTC, ST-DDT commented on src/modules/date/index.ts
> +      min = new Date(Date.UTC(0, refMonth, minDay)).setUTCFullYear(
> change the default mode to age

That would be a breaking change. (We could do that, but not in a simple fix for v8.x)

2023-11-11 10:38 UTC, mumumilk commented on src/modules/date/index.ts
> +      min = new Date(Date.UTC(0, refMonth, minDay)).setUTCFullYear(
>One way to ensure the age is 18+ is by subtracting 19 instead of 18 for the year mode.

much simpler than the way I was heading to, thanks

2023-11-11 10:52 UTC, ST-DDT approved these changes

2023-11-12 15:24 UTC, xDivisionByZerox approved these changes

2023-11-13 00:47 UTC, import-brain approved these changes

2023-11-13 08:07 UTC, merged