chore: migrate vendor
faker-js/faker pull request #254
Opened 2022-01-21 23:54 UTC by Shinigami92

2022-01-22 06:39 UTC, import-brain submitted a review, later dismissed

2022-01-23 08:10 UTC, prisis approved these changes

2022-01-24 14:53 UTC, import-brain submitted a review, later dismissed

2022-01-24 17:40 UTC, prisis approved these changes

2022-01-24 17:41 UTC, griest024 requested changes

2022-01-24 17:41 UTC, griest024 commented on src/vendor/mersenne.ts
> +function MersenneTwister19937(): void {
This seems like this should be defined as a class.

2022-01-24 17:41 UTC, griest024 commented on src/vendor/unique.ts
> +    exclude?: any[];
Can we do better with `exclude`'s type? Something like `string | (string | Result)[]`? This might introduce some annoying casts later but it would at least be more accurate. On line 76 `opts.exclude` is specifically checked for a `string` value so that should at least be part of the type.

2022-01-24 17:41 UTC, griest024 commented on src/vendor/user-agent.ts
> +  function randomProc(arch: 'lin' | 'mac' | 'win') {
Maybe this should be an enum? Not a big deal either way.

2022-01-24 17:59 UTC, Shinigami92 commented on src/vendor/mersenne.ts
> +function MersenneTwister19937(): void {
I wont like to do that now, we could do in a separate PR later

2022-01-24 18:02 UTC, griest024 commented on src/vendor/mersenne.ts
> +function MersenneTwister19937(): void {
Can you add a TODO or issue for it?

2022-01-24 18:07 UTC, griest024 requested changes

2022-01-24 18:07 UTC, griest024 commented on src/vendor/unique.ts
> +  const result = method.apply(this, args);
Can we type this var as `Result`? Maybe `method` can have an even better type so that the return is a `Result`? Like `Method extends (args: Args) => Result`.

2022-01-24 18:07 UTC, Shinigami92 commented on src/vendor/mersenne.ts
> +function MersenneTwister19937(): void {
https://github.com/faker-js/faker/issues/280

2022-01-24 18:12 UTC, griest024 commented on src/vendor/unique.ts
> +  const result = method.apply(this, args);
Although it looks like `Function#apply` explicitly has `any` as its return, thats disappointing. Explicitly typing this var as `Result` introduces some type errors elsewhere.

Can result ever not be a string? Does it need to be generic?

2022-01-24 18:25 UTC, griest024 approved these changes

2022-01-24 18:25 UTC, Shinigami92 commented on src/vendor/unique.ts
> +  const result = method.apply(this, args);
We should try later to get rid of `.apply` and call it natively

2022-01-24 18:30 UTC, prisis approved these changes

2022-01-24 18:30 UTC, merged