feat(locale): Add phone number to fr_SN
faker-js/faker pull request #2545
Opened 2023-11-13 13:12 UTC by makhtar-sarr

In this PR, I've added the different phone number formats that exist in Senegal. I've also avoided using certain formats that I don't yet know in Senegal.

https://en.wikipedia.org/wiki/Telephone_numbers_in_Senegal

2023-11-13 13:48 UTC, ST-DDT commented on src/locales/fr_SN/phone_number/formats.ts
Could you please sort these?

2023-11-13 14:11 UTC, makhtar-sarr commented on src/locales/fr_SN/phone_number/formats.ts
Oui, je l'ai trié de la sorte en me basant sur le nombre d'utilisateur. e.g. `'77 ### ## ##'` est le format le plus utilisé ainsi de suite.

2024-01-18 11:47 UTC, ST-DDT commented on src/locales/fr_SN/phone_number/formats.ts
Sorry, this PR was overlooked.

Currently our data don't convey any meaning by their ordering, so please sort them alphabetically.

Also I couldn't find all of those prefixes in here https://en.wikipedia.org/wiki/Telephone_numbers_in_Senegal

Could you please provide an alternative source for this list?

https://en.wikipedia.org/wiki/Telephone_numbers_in_Senegal

We will soon begin development for v9 and would like to resolve all open PRs for that.

2024-02-01 16:51 UTC, ST-DDT requested changes
Currently our data don't convey any meaning by their ordering, so please sort them alphabetically.

Also I couldn't find all of those prefixes in here [en.wikipedia.org/wiki/Telephone_numbers_in_Senegal](https://en.wikipedia.org/wiki/Telephone_numbers_in_Senegal)
Could you please provide an alternative source for this list?
[en.wikipedia.org/wiki/Telephone_numbers_in_Senegal](https://en.wikipedia.org/wiki/Telephone_numbers_in_Senegal)

2024-04-25 17:00 UTC, ST-DDT requested changes
Please update this PR to match our new phone number format options:

- https://next.fakerjs.dev/api/phone.html#number
- https://github.com/faker-js/faker/pull/2578

2024-05-11 13:58 UTC, ST-DDT commented
This PR seems to have gotten stale.
We can reopen this once this gets updated.

2024-05-11 13:58 UTC, closed without merging