feat(helpers): add support for complex intermediate types
faker-js/faker pull request #2550
Opened 2023-11-15 13:55 UTC by ST-DDT

Implements #1850
Supersedes  #2381

- #1850
- #2381

This PR adds a new intermediate method `faker.helpers.eval` that replaces the entire fake pattern placeholder resolution that was previously located inside the `fake` method.

I extracted the resolution part in its own method because it would otherwise get too long/complex to read.

`faker.helpers.fake("{{person.firstName}})` -> `faker.helpers.eval("person.firstName") -> faker.person.firstName()`

The eval function is now also cable to resolve expressions that contain more than the previous two parts.

This is needed because of methods such as `faker.airline.airline()` that return complex objects.

2023-11-15 14:05 UTC, ST-DDT commented on src/modules/helpers/eval.ts
> +    }
I'm not sure about this implementation, because it prefers properties on the function over properties on its results:

`'airline.airline.name` -> `bound airline` = function.name

If we let it prefer prefer properties on the results, then it will be impossible to access properties on the function that have the same name as the properties in the result.

`'airline.airline.name` -> `Lufthansa`

2023-11-15 14:05 UTC, ST-DDT commented on test/modules/helpers.spec.ts
> +            faker.rawDefinitions.science?.unit?.map((value) =>
```suggestion
            faker.definitions.science.unit.map((value) =>
```

2023-11-15 14:31 UTC, matthewmayer commented
Does eval need to be public? It seems it could be an internal helper method. I don't think library users would normally have any need to use it?

2023-11-15 15:03 UTC, ST-DDT commented
> Does eval need to be public?

No, it doesnt need to be public. But it covers some usecases, that fake cannot because it is bound to be a string, whereas eval can return anything.

The eval function is useful for tools like:

- https://blog.dennisokeeffe.com/blog/2021-12-10-generating-fake-data-from-json-schema
- https://github.com/fstn/howto-typescript-data-generator

That wish to generate any data based on a schema definition, a jsdoc annotation, or a `@annotation`.

I'm fine with exposing it in a separate PR.

2023-11-15 16:13 UTC, matthewmayer commented
I think there might be logic in making it private first just because then we don't need to worry about any breaking changes, or publicly documenting it. Once we are clear it is stable and useful for third parties it could be exposed.

2023-11-15 16:48 UTC, ST-DDT commented
I agree with the publicly documenting part, but the expectations (except for the entrypoint parameters) are already defined by `fake` because it the actual implementation fake uses to resolve its stuff. IMO whether this is private or public is a small detail that can be adjusted anytime (before merge). What about the rest of the implementation?

2023-11-15 16:55 UTC, matthewmayer commented
Well if it's public that cannot be changed to private at "any time" only on a semver major release 😀

2023-11-15 19:03 UTC, xDivisionByZerox commented
I have to agree with @matthewmayer here. While there might be a use case for this method, I think it will be a really niche one. Even if not, we don't lose anything by making it internal for now. While, as already said, we might have some maintainable burdens when making it public first.

2023-11-15 22:56 UTC, ST-DDT commented
Sorry, there might have been some miscommunication here.
My issue was never whether the function was public or not, I only wanted some feedback on the actual implementation (and whether I should scrap the entire concept or whether it is worth continuing on).

I hid away the method now, so it does not cause any further confusion during reviews.

2023-11-17 19:30 UTC, xDivisionByZerox commented on test/modules/helpers.spec.ts
> -        it('does not allow missing method name', () => {
Why did this test go?

2023-11-17 19:30 UTC, xDivisionByZerox commented on test/modules/helpers.spec.ts
> +          const actual = faker.helpers.fake('{{airline.airline.iataCode}}');
I don't know if this is overengineered but should we first check whether `('{{airline.airline}}'` is of type `'object'`? I think that would make more clear what "complex" means in the test description. The same on the "does allow complex data" test.

2023-11-17 19:30 UTC, xDivisionByZerox commented on test/modules/helpers-eval.spec.ts
> +  it('supports method calls without arguments', () => {
Wouldn't it be more useful to spy on the methods here and check if the spy has been called?
This also applies to the later test cases.

2023-11-17 19:30 UTC, xDivisionByZerox commented on src/modules/helpers/eval.ts
> +    }
I'm not sure if it should access function properties at all, to be honest.

2023-11-17 19:30 UTC, xDivisionByZerox commented on src/modules/helpers/eval.ts
> + * Evaluates a function call and returns the remaining string and the mapped results.
It doesn't return the remaining string, does it? It should be the current cursor position if I understood the code correctly. I think "remaining" is kinda confusing as a name in the return tuple.

2023-11-17 19:30 UTC, xDivisionByZerox commented on src/modules/helpers/eval.ts
> +    case '(':
So this allows for functions that return functions to be called? Is that the reason for "(" to be a valid next character?

2023-11-17 19:30 UTC, xDivisionByZerox commented on src/modules/helpers/eval.ts
> +      return [index, JSON.parse(`[${params}]`) as unknown[]];
So for my option argument to work I have to use proper JSON format? Something like `faker.helpers.fake('{{internet.email({ firstName: "Foo", lastName: "Bar" })}}')` (no quoted property names) will throw an error. This might be a bad DX.
Unless I skipped over a normalization part outside of this function.

2023-11-17 19:35 UTC, ST-DDT commented on test/modules/helpers.spec.ts
> -        it('does not allow missing method name', () => {
The PR supports varying depths, that includes a depth of 1.

2023-11-17 19:49 UTC, ST-DDT commented on src/modules/helpers/eval.ts
> +      return [index, JSON.parse(`[${params}]`) as unknown[]];
Do you have a suggestion on how to fix that?

2023-11-17 19:51 UTC, ST-DDT commented on src/modules/helpers/eval.ts
> +    case '(':
Yes. Similar to plain JS `factory()()`.

2023-11-17 19:55 UTC, ST-DDT commented on src/modules/helpers/eval.ts
> + * Evaluates a function call and returns the remaining string and the mapped results.
Oh, you are right. That is some leftover from a previous iteration.

2023-11-17 22:07 UTC, xDivisionByZerox commented on src/modules/helpers/eval.ts
> +    case '(':
Alright, just wanted to be sure I understand this part correctly.

--- 

Although, now I'm thinking: Were would this be actually used in our library?

2023-11-17 22:08 UTC, xDivisionByZerox commented on test/modules/helpers.spec.ts
> -        it('does not allow missing method name', () => {
I think I saw a test in "eval" which checks for exaclty this behaviour (resolving modules). Would you say that this really desired?

2023-11-17 22:10 UTC, ST-DDT commented on src/modules/helpers/eval.ts
> +    }
Removed for now.

2023-11-17 22:11 UTC, xDivisionByZerox commented on src/modules/helpers/eval.ts
> +      return [index, JSON.parse(`[${params}]`) as unknown[]];
I'm not saying we have to support this, I felt that the acceptance criteria (what should work, what shouln't) for this feature are not that well defined. Maybe we should discuss this in the next team meeting?

2023-11-17 22:11 UTC, ST-DDT commented on src/modules/helpers/eval.ts
> + * Evaluates a function call and returns the remaining string and the mapped results.
Renamed

2023-11-17 22:12 UTC, ST-DDT commented on src/modules/helpers/eval.ts
> +    case '(':
I plan to improve the regex support to return a factory instead of parsing the regex over and over again.

2023-11-17 22:25 UTC, ST-DDT commented on test/modules/helpers-eval.spec.ts
> +  it('supports method calls without arguments', () => {
Done

2023-11-17 22:26 UTC, ST-DDT commented on test/modules/helpers.spec.ts
> +          const actual = faker.helpers.fake('{{airline.airline.iataCode}}');
This is not really possible because fake always returns a string.

2023-11-17 23:33 UTC, ST-DDT commented on src/modules/helpers/eval.ts
> +      return [index, JSON.parse(`[${params}]`) as unknown[]];
We can sure do that.
Please keep in mind, that this hasn't changed from before.

2023-11-18 11:21 UTC, xDivisionByZerox commented on test/modules/helpers.spec.ts
> +          const actual = faker.helpers.fake('{{airline.airline.iataCode}}');
You are right. I forgot this. Technically we could parse it and check, but I don't think we gain any information at that point.

2023-11-18 11:23 UTC, xDivisionByZerox commented on src/modules/helpers/eval.ts
> +      return [index, JSON.parse(`[${params}]`) as unknown[]];
> Please keep in mind, that this hasn't changed from before.

Good point. In that case we can leave it as is. Maybe we can take a look at the DX side in another PR.

2023-11-18 11:27 UTC, xDivisionByZerox approved these changes, later dismissed

2023-11-21 17:19 UTC, ST-DDT commented on src/modules/helpers/eval.ts
> +    throw new FakerError(`Expression '${expression}' cannot be resolved.`);
```suggestion
    throw new FakerError(`Cannot resolve expression '${expression}'`);
```

2023-11-26 12:49 UTC, xDivisionByZerox submitted a review, later dismissed

2023-11-26 14:41 UTC, matthewmayer requested changes

2023-11-26 14:41 UTC, matthewmayer commented on test/modules/__snapshots__/person.spec.ts.snap
> +exports[`person > 1211 > bio 1`] = `"teletype lover, dreamer 👄"`;
Do you know why this specific snapshot changes? Does it point to anything deeper?

2023-11-26 14:53 UTC, matthewmayer requested changes

2023-11-26 14:53 UTC, matthewmayer commented on src/modules/helpers/eval.ts
> + * const airlineModule = fakeEval('airline', faker); // AirlineModule
`faker.helpers.fake("{{person}}")`

gives a weird error

```
Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'B'
    |     property 'datatype' -> object with constructor 'l'
    --- property 'faker' closes the circle
    at JSON.stringify (<anonymous>)
    at Y.fake (/Users/matt/Documents/git/faker/dist/cjs/modules/helpers/index.js:1:8351)
```

2023-11-26 14:57 UTC, matthewmayer requested changes

2023-11-26 14:57 UTC, matthewmayer commented on test/modules/helpers-eval.spec.ts
> +  it('supports returning complex objects', () => {
faker.helpers.fake("{{airline.airline.}}") appears to work. Should we disallow a single trailing . like this?

2023-11-26 15:05 UTC, matthewmayer requested changes

2023-11-26 15:05 UTC, matthewmayer commented on src/modules/helpers/eval.ts
> +    `Function parameters cannot be parsed as JSON or simple string: '${input}'`
can we add a test for this? There are some behavior changes here, for example in old version

faker.helpers.fake("{{internet.email('')}}")  works, but now it throws

2023-11-26 17:32 UTC, ST-DDT commented on test/modules/__snapshots__/person.spec.ts.snap
> +exports[`person > 1211 > bio 1`] = `"teletype lover, dreamer 👄"`;
Yes, now the values are resolved in parallel, so if there is a matching method and locale data, it will resolve (arrayElement) them both before selecting the first remaining.

2023-11-30 20:06 UTC, ST-DDT commented on src/modules/helpers/eval.ts
> + * const airlineModule = fakeEval('airline', faker); // AirlineModule
Fixed

2023-11-30 20:06 UTC, ST-DDT commented on test/modules/helpers-eval.spec.ts
> +  it('supports returning complex objects', () => {
Added error test for this case

2023-12-04 09:49 UTC, matthewmayer submitted a review, later dismissed
`faker.helpers.fake("{{person.first_name()}}")` used to work but now throws. Maybe add a test to explicitly check for this?

In general due to subtle behavior changes like this i feel this should be considered breaking. I can imagine there are example in the wild of `faker.helpers.fake("{{person.first_name()}}")` instead of the correct `faker.helpers.fake("{{person.firstName()}}")` which will break.

2023-12-10 14:29 UTC, xDivisionByZerox commented
To not introduce breaking changes, could we ignore parenthesis for now?

2023-12-11 11:43 UTC, ST-DDT commented
Done

2023-12-21 17:02 UTC, xDivisionByZerox approved these changes

2023-12-22 01:12 UTC, matthewmayer approved these changes

2023-12-25 00:51 UTC, merged