feat(helpers): allow using parameters in `method` param of `multiple`
faker-js/faker pull request #2563
Opened 2023-11-30 10:11 UTC by pomali

faker.helpers.multiple() supports using mapFn like in Array.from(), but type signature of function didn't match, PR fixes this and adds test for this case 

(but since it changes declared interface I chose `feat` instead of `fix` as semantic type)

2023-11-30 10:39 UTC, xDivisionByZerox commented
I'm not sure if this fits the use case of `faker.helpers.multiple` :thinking:

If you require the parameters of the mal function, you are most likely doing some static value generation. 

I need some time to think about this in more detail.

2023-11-30 11:51 UTC, pomali commented
Yes, usecase here is generating two sets of objects with matching ids, so I can "join" them later.
Eg.

```
interface School { locationId: number }
interface Location { id: number }
```

I could create with no arguments  function that simulates this behavior, but it seemed busywork since underlying code already supports it

2023-11-30 11:56 UTC, ST-DDT requested changes
The index parameter might be useful when generating a list of entries that should have sequential ids.

However I would like to block this until v9.0 development commences, because then the method might get a new parameter (ref fakerCore) anyway.

2023-11-30 11:56 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    method: (() => TResult) | ((v: unknown, k: number) => TResult),
Since the first value is always undefined, I would omit it from the signature.
Also please name the k parameter index or something more expressive.

2023-11-30 11:59 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    method: (() => TResult) | ((v: unknown, k: number) => TResult),
If you make the parameter optional then you dont need two signatures.

2024-01-31 20:37 UTC, rtm-ctrlz commented on src/modules/helpers/index.ts
> +    method: (() => TResult) | ((v: unknown, k: number) => TResult),
There is no need for two signatures even without making parameters optional, because parameters will be passed any way, no matter how callback or types for callback parameter was defined.

And by the way, it is not an error for a function not to have parameters in case where they will passed, take event handlers for example.

2024-02-09 17:32 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +    method: (() => TResult) | ((v: unknown, k: number) => TResult),
So @ST-DDT and I discussed about this and thinking about to do something like `return Array.from({ length: count }, (_, index) => method(faker, index));`.

We will discuss this with the rest of the team in one of the next meetings.

2024-02-15 16:44 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +    method: (() => TResult) | ((v: unknown, k: number) => TResult),
**Team Decision**

We will add this and will start with this:

```suggestion
    method: (v: unknown, index: number) => TResult,
```

After/in the process of https://github.com/faker-js/faker/issues/2667 we will then replace the `v` with a proper value.

2024-02-15 16:46 UTC, ST-DDT commented
Sorry for the delay in feedback.
Could you please update this PR with the latest suggestions?

2024-02-20 17:51 UTC, pomali commented
> Sorry for the delay in feedback. Could you please update this PR with the latest suggestions?

No problem, sorry for mine delay. Updated.

2024-02-21 08:03 UTC, ST-DDT commented
Could you please fix the broken tests and examples?
The tests were already broken due to the wrong typing of the method before, but now the method actually requires proper types and thus the bad usage actually shows up.

`firstName` -> `() -> firstName()`

2024-02-21 08:05 UTC, ST-DDT commented
Please also enable `allow edits by maintainers` on this PR so we can update it ourself to the latest commits on next.

2024-03-01 22:51 UTC, ST-DDT commented on test/modules/helpers.spec.ts
> +        .it('with method using index', (_el, i) => i * 3);
```suggestion
        .it('with method using index', (_, i) => i * 3);
```

2024-03-01 22:52 UTC, ST-DDT commented on test/modules/helpers.spec.ts
> +          const result = faker.helpers.multiple((_el, i) => i * 2, {
```suggestion
          const result = faker.helpers.multiple((_, i) => i * 2, {
```

2024-03-01 22:54 UTC, ST-DDT approved these changes, later dismissed

2024-03-01 22:58 UTC, ST-DDT commented
Do we consider this breaking?

Because previously you could incorrectly pass any function reference directly to the method even, if it would be called with garbage values, so it is kind of a bugfix, but one that prevents you from doing bad things.

2024-03-01 23:04 UTC, Shinigami92 submitted a review, later dismissed

2024-03-01 23:05 UTC, Shinigami92 commented
> Do we consider this breaking?

I think it's better to mark it as breaking as not doing it and then it was breaking

2024-03-01 23:40 UTC, ST-DDT submitted a review, later dismissed

2024-03-02 00:12 UTC, rtm-ctrlz approved these changes
GitHub still asking me for review :)

In my opinion this change should be accepted and marked as breaking change.

In most cases this change should not lead to breaks, but it worth a notice.

2024-03-02 08:18 UTC, matthewmayer requested changes

2024-03-02 08:18 UTC, matthewmayer commented on docs/guide/upgrading_v9/2563.md
> +Previously it was possible to incorrectly pass any function reference to `faker.helpers.multiple`,
I think we can write this in a more friendly way. Instead of saying previously it was possible to "incorrectly" pass any function reference to faker.helpers.multiple - this is exactly how it is documented to work at the moment at https://fakerjs.dev/api/helpers#multiple 

Maybe a better example is to show a method that has a second parameter.

So for example code like:

`faker.helpers.multiple(faker.date.past, {count:2})`
//[ 1969-06-28T19:24:59.269Z, 1969-06-10T02:42:19.045Z ]
works differently to
`faker.helpers.multiple(()=>faker.date.past(), {count:2})`
// [ 2023-09-05T12:16:22.537Z, 2023-05-01T15:15:18.872Z ]

Because the 2nd parameter (refDate) is passed the indexes 0 and 1, ie relative to datetime 0, around the 1970 UNIX timestamp epoch.



[
  1969-03-07T18:23:19.963Z, 1969-06-12T21:22:55.144Zh
]

2024-03-02 08:18 UTC, matthewmayer commented on src/modules/helpers/index.ts
>     * faker.helpers.multiple(faker.person.firstName, { count: 3 }) // [ 'Santos', 'Lavinia', 'Lavinia' ]
change this to use `() => faker.person.firstName()` ?

2024-03-02 08:18 UTC, matthewmayer commented on src/modules/helpers/index.ts
>     * @example
we could also change 
`@param method The method used to generate the values.` to indicate that this will be called with (_, index)

2024-03-02 08:31 UTC, matthewmayer requested changes

2024-03-02 08:31 UTC, matthewmayer commented on docs/guide/upgrading_v9/2563.md
> +Previously it was possible to incorrectly pass any function reference to `faker.helpers.multiple`,
Suggested rewrite:

### Stricter checking for function signature passed to `faker.helpers.multiple` method

The `faker.helpers.multiple` method takes a function reference as its first parameter. Previously you may have written code like this to generate multiple values.
```ts
faker.helpers.multiple(faker.date.past, {count:2})
```

However this code has a bug - `faker.helpers.multiple` passes the loop index as the second parameter to the method, which in this case would set the `refDate` of the `faker.date.past()` call to 0, making all dates before 1970.

Instead you should generally use a lambda function like
```ts
faker.helpers.multiple(()=>faker.date.past(), {count:2})
```
to get the desired behavior. In v9.0, we use stricter type-checking in Typescript to detect when a function is called which is not compatible with `(v: unknown, index: Number)` which can cause compile-time errors in places where previously there were potential runtime errors.

**Bad**

```ts
faker.helpers.multiple(faker.person.firstName, ...); // ❗
// In Typescript, this is now a compile time error
// Argument of type '(sex?: "female" | "male" | undefined) => string'
// is not assignable to parameter of type '(v: unknown, index: number) => unknown'.
```

**Good**

```ts
faker.helpers.multiple(() => faker.person.firstName(), ...); // ✔
```

The new types also allow for easier use-cases where the index is part of the generated data e.g. as id.

```ts
faker.helpers.multiple((_, index) => ({ id: index, ...}), ...); // [{id: 0, ...}, ...]
```

2024-03-02 12:36 UTC, ST-DDT commented on docs/guide/upgrading_v9/2563.md
> +Previously it was possible to incorrectly pass any function reference to `faker.helpers.multiple`,
Thanks for these suggestions, they really help a lot.

2024-03-02 12:36 UTC, ST-DDT commented on src/modules/helpers/index.ts
>     * faker.helpers.multiple(faker.person.firstName, { count: 3 }) // [ 'Santos', 'Lavinia', 'Lavinia' ]
Good catch

2024-03-02 12:39 UTC, ST-DDT commented on src/modules/helpers/index.ts
>     * @example
Edited

2024-03-02 12:40 UTC, ST-DDT approved these changes, later dismissed

2024-03-02 13:17 UTC, matthewmayer requested changes

2024-03-02 13:17 UTC, matthewmayer commented on src/modules/helpers/index.ts
> +   * faker.helpers.multiple((_, i) => `Person ${i + 1}` ) // [ 'Person 1', 'Person 2', 'Person 3' ]
This example seems a bit artificial as there's not any fake part to the function. Maybe like `${faker.color.human()} ${i+1}`

2024-03-02 13:38 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +   * faker.helpers.multiple((_, i) => `${faker.color.human()}-${i + 1}` ) // [ 'orange-1', 'orchid-2', 'sky blue-3' ]
```suggestion
   * faker.helpers.multiple((_, i) => `${faker.color.human()}-${i + 1}`) // [ 'orange-1', 'orchid-2', 'sky blue-3' ]
```

2024-03-02 14:00 UTC, matthewmayer approved these changes

2024-03-02 14:36 UTC, ST-DDT approved these changes

2024-03-03 10:00 UTC, Shinigami92 approved these changes
Really good migration guide :+1:

2024-03-03 10:12 UTC, merged