refactor(number): deprecate precision in favor of multipleOf in float
faker-js/faker pull request #2564
Opened 2023-11-30 18:42 UTC by xDivisionByZerox

## Description

This PR deprecated the property `precision` in `faker.number.float`. Additionally, adds the property `multipleOf`. 

## Additional information

Extracted from #1855.

2023-11-30 18:56 UTC, ST-DDT reviewed
It looks like some methods still use the precision parameter.

2023-11-30 18:56 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * Returns a single random floating-point number for a given multipleOf or range and multipleOf.
This parts sounds off to me.

Maybe use just:

```suggestion
   * Returns a single random floating-point number.
```

2023-11-30 18:56 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * The lower bound is inclusive, the upper bound is exclusive, unless multipleOf is passed.
```suggestion
   * The lower bound is inclusive, the upper bound is exclusive, unless `multipleOf` is passed.
```

2023-11-30 18:56 UTC, ST-DDT commented on src/modules/number/index.ts
>     * If precision is passed, the upper bound is inclusive.
Maybe mention that it is deprecated here as well?
```suggestion
   * @param options.precision Precision of the generated number, for example `0.01` will round to 2 decimal points.
   * If precision is passed, the upper bound is inclusive.
   * This option is deprecated, please use `multipleOf` instead.
```

?

2023-11-30 18:56 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * This property can be used to achieve specific decimal points.
```suggestion
   * This property can be used to limit the result a specific number of decimal digits.
```

(I have never used/heart of `decimal points`, but that might just be me not being familiar with it)

2023-11-30 19:10 UTC, xDivisionByZerox commented on src/modules/number/index.ts
>     * If precision is passed, the upper bound is inclusive.
I searched for similar occurencens (Faker constructor) and the JSDocs do not mention the deprecation there as well 🤔

2023-12-01 00:35 UTC, matthewmayer requested changes, later dismissed

2023-12-01 00:35 UTC, matthewmayer commented on test/modules/number.spec.ts
> +            Array.from({ length: 50 }, () =>
Maybe do 100. 50 will fail every ~70000 runs.

2023-12-10 14:08 UTC, xDivisionByZerox commented on test/modules/number.spec.ts
> +          new FakerError('Multiple of should be greater than 0.')
Is this correct? Since we give "precision" and receive an error talking about "multipleOF".

2023-12-10 14:08 UTC, xDivisionByZerox commented on src/modules/number/index.ts
> +        throw new FakerError(`Multiple of should be greater than 0.`);
Should this directly recall the name of the property? So, rephrase "Multiple of" to "multipleOf"?

2023-12-11 18:58 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      multipleOf: 1e-9,
I think this is a max precision float, so we could potentially remove the option from here.

2023-12-11 18:58 UTC, ST-DDT commented on src/modules/number/index.ts
> +        throw new FakerError(`Multiple of should be greater than 0.`);
I would refer to the property, because otherwise you still have broken English.

2023-12-11 18:59 UTC, ST-DDT commented on test/modules/number.spec.ts
> +          new FakerError('Multiple of should be greater than 0.')
I think it's fine. Alternatively you could do `multipleOf/precision should be greater than 0.`

2023-12-14 14:13 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +      multipleOf: 1e-9,
Is max precision not 18? 🤔

2023-12-18 23:49 UTC, ST-DDT commented on src/modules/helpers/index.ts
> +      multipleOf: 1e-9,
I think this should/can be a max precision float. 
(It was probably just forgotten during the "default 2 precision -> max precision float" refactor)

2023-12-19 15:17 UTC, xDivisionByZerox commented on src/modules/helpers/index.ts
> +      multipleOf: 1e-9,
Ok, I misunderstood you the first time. Done.

2023-12-19 15:38 UTC, ST-DDT submitted a review, later dismissed

2023-12-28 11:52 UTC, ST-DDT commented
@xDivisionByZerox There appears to be merge conflicts.

2023-12-29 13:29 UTC, ST-DDT approved these changes

2023-12-29 16:41 UTC, matthewmayer approved these changes

2023-12-30 12:19 UTC, merged