build: bundle with esbuild
faker-js/faker pull request #257
Opened 2022-01-22 09:50 UTC by Shinigami92

2022-01-22 12:31 UTC, Shinigami92 commented
@knightly-bot build this

2022-01-22 15:12 UTC, damienwebdev commented
As I an unfamiliar with the various types of packaging mechanics in NodeJS, I found it helpful to ref this document when reviewing this

https://nodejs.org/api/packages.html#packages_package_entry_points

2022-01-22 15:27 UTC, damienwebdev commented
This is missing a README update.

2022-01-22 15:27 UTC, damienwebdev requested changes

2022-01-22 15:27 UTC, damienwebdev commented on package.json
> +    ">=4.2": {
How did you decide on this version?

2022-01-22 15:29 UTC, damienwebdev commented
This also breaks browser builds (or at least documentation for them). What should the migration path be? Is it possible to output to dist backwards compatibly?

2022-01-22 15:30 UTC, damienwebdev commented
This also breaks the docs.

2022-01-22 15:35 UTC, damienwebdev commented
@Shinigami92 I want to ensure we're clear on whether or not this drops support for es5 in browser builds.

2022-01-22 16:31 UTC, Shinigami92 commented
@damienwebdev 

> As I am unfamiliar with the various types of packaging mechanics in NodeJS, I found it helpful to ref [this packaging document](https://nodejs.org/api/packages.html#packages_package_entry_points) when reviewing this

Oh yeah, I also did know nothing about this before this PR.

> This is missing a README update.

Oh yeah, you are right. I will work on that today or tomorrow :+1: 

> This also breaks browser builds (or at least any existing documentation for them). What should the migration path be? Is it possible to output to dist backward compatibly?

Potentially yes, it could break the browser support. That's why I would like to have a `6.0.0-alpha.4` release to test out if we can do something with https://unpkg.com
If this doesn't work out of the box, we may need to add a third bundle for `iife` (See https://esbuild.github.io/api/#format-iife)
But this would mean additional around 10 MiB, because the locales needs always to be duplicated for each bundle.

I'm thinking about to drop browser support for now and bring it back in later when we found a much better way of async loading in locales. (This may not be that much difficult.)

> This also breaks the docs.

Oh :astonished:, thanks I need to have a look into that :+1: 

> I want to ensure we're clear on whether or not this drops support for es5 in browser builds, do you know if it does?

I need also to find out. But if we really provide an iife bundle, we can just target `es5`. So really easy with that :+1:.

2022-01-22 16:34 UTC, Shinigami92 commented on package.json
> +    ">=4.2": {
It's based on what's doing `rxjs` :eyes: 

<img src="https://user-images.githubusercontent.com/7195563/150647245-f9f7cd7d-e3a7-42c8-a79c-e02bca9a5a03.png" width="300px"/>

https://github.com/ReactiveX/rxjs/blob/123a0f256e0022e87dfa249c895670ee745def53/package.json#L10

2022-01-22 19:26 UTC, Shinigami92 commented
@damienwebdev Currently we provide `sourcemaps` via `esbuild`
Do we need to provide these? Because these are really big and blow up the bundle size.

2022-01-22 21:42 UTC, damienwebdev commented
@Shinigami92 can you doc here the before and after size of the the bundles so that we can compare?

2022-01-22 21:42 UTC, damienwebdev commented on package.json
> +    ">=4.2": {
I think we target the major version instead? 4.0 for safety?

2022-01-23 09:41 UTC, Shinigami92 commented
@damienwebdev 

I checked three things:

1. esbuild with sourcemaps  
   package size: 3.4 MB | unpacked size: 16.6 MB | total files: 5835  
   [esbuild-with-sourcemap.log](https://github.com/faker-js/faker/files/7920156/esbuild-with-sourcemap.log)

2. esbuild without sourcemaps  
   package size: 1.6 MB | unpacked size: 7.0 MB | total files: 3871  
   [esbuild-without-sourcemap.log](https://github.com/faker-js/faker/files/7920157/esbuild-without-sourcemap.log)

3. main with tsc + gulp browser no sourcemap (current state)  
   package size: 3.1 MB | unpacked size: 14.5 MB | total files: 3803  
   [tsc-and-gulp-browser-without-sourcemap.log](https://github.com/faker-js/faker/files/7920158/tsc-and-gulp-browser-without-sourcemap.log)

---

Please note that the esbuild process includes cjs and esm but no browser and the main includes cjs and browser but no esm
Also note that the current main doesn't provide source maps. So we could really leave them out for now and then we would reduce the bundle size by half!

And in addition to that, I'm already thinking about to split manually the locales into it's own folder and fetch them on demand.
But I assume we need to convert them then into json files or yaml if possible to make them even smaller.

But this would be definitely something for another PR

2022-01-24 17:53 UTC, prisis commented on CONTRIBUTING.md
> +- The documentation is running via VitePress. Use `pnpm run docs:dev` to edit them in live mode.
Should we add that the pnpm run build should be run before the docs?

2022-01-24 17:57 UTC, prisis commented on package.json
> +        "lib/types/*"
why use lib and not dist?

2022-01-24 17:59 UTC, prisis commented on package.json
> +      "node": "./lib/cjs/index.js",
can we not just have a different ending like index.cjs and index.js

2022-01-24 18:00 UTC, prisis commented on package.json
> +      "node": "./lib/cjs/index.js",
or index.cjs.js and index.esm.js

2022-01-24 18:01 UTC, prisis commented on test/address.spec.ts
> +import { faker } from '../lib/cjs';
so all of this changes are not needed if the ending is different

2022-01-24 18:59 UTC, Shinigami92 commented on package.json
> +      "node": "./lib/cjs/index.js",
Not possible right now, cause we have multiple entrypoints that are referencing each other

2022-01-24 19:00 UTC, damienwebdev approved these changes
lgtm

2022-01-24 19:04 UTC, prisis approved these changes

2022-01-24 19:04 UTC, merged