fix(internet): domain names should not contain spaces
faker-js/faker pull request #258
Opened 2022-01-22 10:34 UTC by ST-DDT

Fixes #256

2022-01-22 10:34 UTC, ST-DDT commented
@cduff Does your tooling consider `https://full-jalapeã±o.info` to be a valid url?
@maintainers: Should we return such values?

2022-01-22 12:17 UTC, Shinigami92 commented
If `jalapeño` is not a valid value for a URL, then we would need to normalize the URL
Maybe this is a good idea in general :thinking:

2022-01-22 14:59 UTC, damienwebdev requested changes

2022-01-22 14:59 UTC, damienwebdev commented on test/internet.spec.ts
> +          /^https?:\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?$/,
This appears to be regex magic. Perhaps we pull in a validation library? I don't trust myself well enough to know all the edge-case requirements of domain naming. https://github.com/validatorjs/validator.js/blob/master/src/lib/isFQDN.js#L12

2022-01-22 15:21 UTC, ST-DDT commented on test/internet.spec.ts
> +          /^https?:\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?$/,
I will work on that tomorrow evening.

2022-01-23 01:57 UTC, cduff commented
> @cduff Does your tooling consider `https://full-jalapeã±o.info` to be a valid url? What about `https://full-jalapeño.info`?
> 
> Or more specifically should we return such values? (Other languages might have more of them)
> 
> https://github.com/faker-js/faker/blob/60c90028ba76b7e291fdb8152425b93c41b117c9/src/locales/en/word/noun.ts#L3252

I'm using https://www.npmjs.com/package/class-validator `isUrl` for the validation. It reports the two strings you specified above as valid.

2022-01-23 11:33 UTC, ST-DDT commented on test/internet.spec.ts
> +          /^https?:\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?$/,
Done.

2022-01-23 11:33 UTC, ST-DDT commented
I also added the verification checks to the other internet module tests.

2022-01-23 12:09 UTC, Shinigami92 commented on test/internet.spec.ts
>  describe('internet.js', () => {
Oh I missed that one

```suggestion
describe('internet', () => {
```

2022-01-23 12:09 UTC, Shinigami92 commented on test/internet.spec.ts
> +      expect(validator.isURL('https://' + domain_name)).toBeTruthy();
Let's try out `isFQDN`

2022-01-23 12:09 UTC, Shinigami92 commented on test/internet.spec.ts
> +    it('ip6 to be valid', () => {
Let's call this IPv6 and the other IPv4

2022-01-23 12:09 UTC, Shinigami92 commented on test/internet.spec.ts
> +      expect(validator.isHexColor(color)).toBeTruthy();
I think you missed to remove the regex variant

2022-01-23 12:43 UTC, Shinigami92 approved these changes

2022-01-23 14:36 UTC, Shinigami92 commented
We should find a better title for the PR now :wink:

2022-01-27 16:59 UTC, Shinigami92 approved these changes

2022-01-28 14:13 UTC, Shinigami92 approved these changes

2022-01-29 11:12 UTC, ST-DDT commented
@damienwebdev Would you mind reviewing this again, so that we can merge this?
Some other PRs would benefit from the validator library added here as well.

2022-01-29 12:26 UTC, prisis submitted a review, later dismissed

2022-01-29 12:57 UTC, Shinigami92 commented
@ST-DDT you can decide if you want to merge it or wait on @damienwebdev :slightly_smiling_face:

2022-01-29 13:09 UTC, ST-DDT commented
If we want to use it for #303 or a release, then we should merge it now, otherwise we can wait a day for damien.

2022-01-29 20:01 UTC, Shinigami92 approved these changes

2022-01-30 20:10 UTC, prisis commented on test/internet.spec.ts
> +      expect(port + '').satisfy(validator.isPort);
```suggestion
      expect(String(port)).satisfy(validator.isPort);
```

2022-01-30 20:11 UTC, prisis commented on test/internet.spec.ts
> +        expect(port + '').satisfy(validator.isPort);
```suggestion
        expect(String(port)).satisfy(validator.isPort);
```

2022-01-30 20:17 UTC, Shinigami92 approved these changes

2022-01-30 20:19 UTC, prisis approved these changes

2022-01-30 20:31 UTC, merged