chore: update license year
faker-js/faker pull request #2594
Opened 2024-01-01 12:36 UTC by Shinigami92

2024-01-01 12:56 UTC, ST-DDT submitted a review, later dismissed

2024-01-01 13:28 UTC, xDivisionByZerox approved these changes, later dismissed

2024-01-01 13:53 UTC, matthewmayer requested changes
Maybe could remove the copyright statement from the user agent and mersenne files and just leave it in LICENSE so it's only in one place?

2024-01-01 19:15 UTC, ST-DDT commented
Or at least our copyright year.

2024-01-02 07:34 UTC, Shinigami92 commented
I was now shown various options for changing something that would have to be changed once a year and adjusting 3 lines. I would not like to get involved in discussions and waste potential time researching whether and where license years are required and where not. If this is really that important to you, then it's best to open your own PR and close this one if necessary.

2024-01-02 07:35 UTC, Shinigami92 commented on LICENSE
> +- http://search.cpan.org/~jasonk/Data-Faker-0.07/ - Copyright 2004-2005 by Jason Kohles
somehow my IDE formatted this file

```suggestion
 * https://github.com/stympy/faker/ - Copyright (c) 2007-2010 Benjamin Curtis
 * http://search.cpan.org/~jasonk/Data-Faker-0.07/ - Copyright 2004-2005 by Jason Kohles
```

2024-01-02 10:07 UTC, matthewmayer commented
I agree it is an annoying discussion BUT copyright is important. Rather than blindly updating the year once a year it's important we understand what the copyright statement actually means and if it applies to specific files or the whole repo.

2024-01-02 10:10 UTC, Shinigami92 commented
> I agree it is an annoying discussion BUT copyright is important. Rather than blindly updating the year once a year it's important we understand what the copyright statement actually means and if it applies to specific files or the whole repo.

So you suggest to only touch the specific files if their content changes?
And in this PR I should revert the specific files and only bump the **LICENSE** file in _root_?

2024-01-02 10:52 UTC, matthewmayer commented
I'd bump the root one and look into the history of the other files to see if there is some special reason why they have seperate copyright statements. If not they should just be removed as they don't serve any purpose.

2024-01-02 10:59 UTC, Shinigami92 commented on src/internal/mersenne.ts
> + * Copyright (c) 2022-2024 Faker
```suggestion
 * Copyright (c) 2022-2023 Faker
```

2024-01-02 10:59 UTC, Shinigami92 commented on src/modules/internet/user-agent.ts
> + * Copyright (c) 2022-2024 Faker
```suggestion
 * Copyright (c) 2022-2023 Faker
```

2024-01-02 11:00 UTC, Shinigami92 commented
> I'd bump the root one and look into the history of the other files to see if there is some special reason why they have seperate copyright statements. If not they should just be removed as they don't serve any purpose.

So I reset the specific files and left the other task to someone who has the will to do it

2024-01-02 12:46 UTC, matthewmayer approved these changes

2024-01-02 13:04 UTC, ST-DDT approved these changes

2024-01-02 13:14 UTC, merged