feat(music): add albumName and artist methods add additional genres and songs
faker-js/faker pull request #2620
Opened 2024-01-24 03:21 UTC by jeremyhofer

This PR introduces two new methods to the `music` module. `albumName` and `artist`. Additionally, the set of songs and genres in the `en` locale was extended to cover more defined genres, as well as add entries from top streamed songs on various platforms.

Data was sourced from various resources from a number of resources online, including:
- The dataset from when the `songName` method was added in https://github.com/faker-js/faker/pull/996: https://manghammath.com/80s%20Hits/The%20Top%201000%20Songs%20of%20AllTime.pdf
- Rolling Stone 500 Greatest Albums: https://www.rollingstone.com/music/music-lists/best-albums-of-all-time-1062063/arcade-fire-%ef%bb%bffuneral-1062733/
- Music Genres List: https://www.musicgenreslist.com/
- Chart Masters compiled data for Artists, Albums, and Songs: https://chartmasters.org/
- Wikipedia list of genres: https://en.wikipedia.org/wiki/List_of_music_genres_and_styles

The `@since` version on the methods was set to `8.5.0`, as it looks like the `8.4.0` tag has been created.

2024-01-24 03:46 UTC, matthewmayer requested changes
1. We normally limit to 1000 entries per file
2. Suggest splitting into two PRs, one for adding data for existing methods (since that can be done in a patch release) and one for proposing new methods
3. Some of the genres look a bit awkward like "Holiday: Other". Maybe remove ones like that.

2024-01-25 00:06 UTC, jeremyhofer commented
@matthewmayer thanks for the feedback!

I pulled the genre and song name additions out of this PR. Will raise a PR to add and clean up the additional genres. Given the song name set is near 1000 entries I'm discarding all my changes there.

I updated the added `album_name` and `artist` sets down to 1000 entries each.

2024-01-25 14:37 UTC, matthewmayer requested changes, later dismissed

2024-01-25 14:37 UTC, matthewmayer commented on src/modules/music/index.ts
> + * For a ranom artist, use [`artist()`](https://fakerjs.dev/api/music.html#artist).
typo, random

2024-01-26 00:29 UTC, matthewmayer commented
Non ascii names are OK as long as that's how they are normally written in English

2024-01-26 11:08 UTC, ST-DDT commented on src/locales/en/music/album_name.ts
> +  '.mp3',
This might cause confusion and is IMO not worth the confusion.

2024-01-26 11:08 UTC, ST-DDT commented on src/locales/en/music/album_name.ts
> +  '2000',
Same here

2024-01-26 11:08 UTC, ST-DDT commented on src/locales/en/music/album_name.ts
> +  '42',
Same here

2024-01-26 11:08 UTC, ST-DDT commented on src/locales/en/music/album_name.ts
> +  '9',
Same here

2024-01-26 11:08 UTC, ST-DDT commented on src/locales/en/music/album_name.ts
> +  '99.9%',
Same here

2024-01-26 11:08 UTC, ST-DDT commented on src/locales/en/music/album_name.ts
> +  '?',
Same here

2024-01-26 11:08 UTC, ST-DDT commented on src/locales/en/music/album_name.ts
> +  'O',
Same here

2024-01-26 11:08 UTC, ST-DDT commented on src/locales/en/music/album_name.ts
> +  'X',
Same here

2024-01-26 11:08 UTC, ST-DDT commented on src/locales/en/music/album_name.ts
> +  'xx',
I think we should use case insensitive sort

2024-01-26 11:08 UTC, ST-DDT commented on src/locales/en/music/album_name.ts
> +  "(What's The Story) Morning Glory?",
Does this refer to the thing I think it does?

2024-01-26 11:08 UTC, ST-DDT commented on src/locales/en/music/artist.ts
> +  'Cigarettes After Sex',
Should we remove this in case of value transformation by the user? (aka `value.split(' ')[2]`)
I think we have enough other values to omit this one.

2024-01-26 12:24 UTC, matthewmayer commented on src/locales/en/music/album_name.ts
> +  "(What's The Story) Morning Glory?",
It's a double entendre for sure, but it's also a pretty famous album. I don't think it's offensive.

2024-01-26 12:26 UTC, matthewmayer commented
FWIW although we would normally wait for 10 upvotes to approve a change like this this does seem a fairly sensible extension of the current music module so I'd be fine with approving this for next minor or major release.

2024-01-26 21:51 UTC, jeremyhofer commented on src/locales/en/music/artist.ts
> +  'Cigarettes After Sex',
I'm not sure about the rationale of removing due to a value transformation. However, I agree there are more than enough examples and have no issue removing this one.

2024-01-26 21:58 UTC, jeremyhofer commented
Updated to remove albums that could be confusing - the ones that were called out, as well as others I felt could similarly cause some confusion. Updated to case insensitive sort the data as well.

Thanks for considering these methods! Would it be possible to add the ask to propose and vote on new modules and methods to the docs and CONTRIBUTING.md? I was unaware this was the general expectation when I got started in the repo :smiley:

2024-01-27 06:36 UTC, matthewmayer commented
> Would it be possible to add the ask to propose and vote on new modules and methods to the docs and CONTRIBUTING.md? I was unaware this was the general expectation when I got started in the repo 😃

Its not really a hard requirement, its more to help triage the issues that are added to the project. So if someone adds an issue saying "it would be cool if we had artist names" we will normally wait until >10 upvotes to see if other people would find it useful. If someone sources suitable data, makes a PR, adds tests etc, then the threshold for inclusion is lower!

So I think being too strict about it and documenting in CONTRIBUTING might discourage people from actually contributing code, which we wouldnt want.

2024-03-07 13:12 UTC, xDivisionByZerox commented on src/locales/en/music/artist.ts
> +  'Cigarettes After Sex',
> Should we remove this in case of value transformation by the user? (aka value.split(' ')[2])

I would not consider this as custom value transformation doesn't make any sense in this context.

> I think we have enough other values to omit this one.

Fair enought. Although, with over 5 Million sold albums world wide they are far more well known than the german rapper CRO (line 182) for example. He has not even 2 Million sold albums.  
Excluding them only because they have an undired word in their name feels kinda wrong to me. While I agree on the fact that we should have somewhat of an profanity filter, I'd not agree on it being applied to names. In the worst case scenario this could potential hurt the overall diversity of values generated, as giving yourself an "outragous" name (as an artist) might a percise decision you make to guid attention to specific topics.

2024-03-07 13:27 UTC, xDivisionByZerox requested changes
Some small updates to the documentation. Otherwise this looks good to me.

2024-03-07 13:27 UTC, xDivisionByZerox commented on src/modules/music/index.ts
> +   * @since 8.5.0
We will not be releasing a version 8.5 as we already work on bringing the current codebase to v9.0. So these methods will (most likely) land in v9.0 as well.

```suggestion
   * @since 9.0.0
```

2024-03-07 13:27 UTC, xDivisionByZerox commented on src/modules/music/index.ts
> +   * @since 8.5.0
Same here.

```suggestion
   * @since 9.0.0
```

2024-04-11 17:35 UTC, ST-DDT commented
We talked about this PR in today's team meeting.
There we discussed whether the methods (and definitions) should use the `Name` suffix.
In our oppinion `album` and `albumName` convey the same information and thus we should only use `album()`.

The definitions should follow the method's name unless there is a need for disambiaguation such as with `_pattern`.
(Since we don't plan to add patterns for these methods we should use the method name for the definitions)

We will rename `songName` -> `song` in a separate PR.

@matthewmayer What do you think?

2024-04-12 01:22 UTC, matthewmayer commented
Sure. Shorter is better like city instead of cityName

2024-04-12 06:32 UTC, ST-DDT commented
@jeremyhofer Could you please apply the requested changes and fix the merge conflicts?

2024-04-26 21:14 UTC, xDivisionByZerox approved these changes, later dismissed

2024-04-26 21:26 UTC, xDivisionByZerox approved these changes, later dismissed

2024-04-26 22:04 UTC, Shinigami92 submitted a review, later dismissed

2024-04-26 23:24 UTC, ST-DDT requested changes

2024-04-26 23:24 UTC, ST-DDT commented on src/modules/music/index.ts
> + * For a random album name, use [`albumName()`](https://fakerjs.dev/api/music.html#album).
```suggestion
 * For a random album name, use [`album()`](https://fakerjs.dev/api/music.html#album).
```

2024-04-26 23:24 UTC, ST-DDT commented on src/locales/en/music/album_name.ts
The file should probably be renamed to just `album`.
same for song name.

2024-04-26 23:24 UTC, ST-DDT commented on src/definitions/music.ts
> +  album_name: string[];
This should be renamed to just album.
Same for song name.

2024-04-26 23:24 UTC, ST-DDT commented on src/modules/music/index.ts
> + * For a random song name, [`songName()`](https://fakerjs.dev/api/music.html#song).
```suggestion
 * For a random song name, [`song()`](https://fakerjs.dev/api/music.html#song).
```

2024-04-26 23:24 UTC, ST-DDT commented on src/modules/music/index.ts
> +  song(): string {
This is a breaking change

2024-04-26 23:41 UTC, xDivisionByZerox commented on src/modules/music/index.ts
> +  song(): string {
Yeah, I'll revert this. I overred the "in a separate PR" thing in [the original change request comment](https://github.com/faker-js/faker/pull/2620#issuecomment-2050181213).

2024-04-27 07:43 UTC, ST-DDT submitted a review, later dismissed

2024-04-27 07:57 UTC, Shinigami92 approved these changes, later dismissed

2024-04-27 20:25 UTC, xDivisionByZerox approved these changes, later dismissed

2024-04-29 09:04 UTC, ST-DDT approved these changes

2024-04-29 09:13 UTC, matthewmayer approved these changes

2024-04-29 09:23 UTC, Shinigami92 approved these changes

2024-04-29 09:24 UTC, merged