feat(music): add additional genres
faker-js/faker pull request #2621
Opened 2024-01-25 01:40 UTC by jeremyhofer

This PR is split off from #2620 where I originally added additional genres along with new `album` and `artistName` methods.

Genres were compiled primarily from these resources:
- https://www.musicgenreslist.com/
- https://en.wikipedia.org/wiki/List_of_music_genres_and_styles
- https://koop.org/shows/genres-definitions/
- https://www.musicgateway.com/blog/spotify/what-are-the-different-genres-of-music

Based on feedback in #2620 from the original set I added I tried to clean up some of the odd/awkward genres adopted from the sources, e.g. just specifying "Holiday" or "Classical" instead of listing some of the sub-types from the resources. Happy to clean up the list further if desired!

2024-01-25 04:26 UTC, matthewmayer requested changes

2024-01-25 04:26 UTC, matthewmayer commented on src/locales/en/music/genre.ts
> +  "Jungle/Drum’n'bass",
Split these? I am reliably informed they are not the same genre :D

https://www.youtube.com/watch?v=0thYqrBSWK4

2024-01-25 04:26 UTC, matthewmayer commented on src/locales/en/music/genre.ts
> +  'Standup Comedy',
not really a music genre?

2024-01-25 04:26 UTC, matthewmayer commented on src/locales/en/music/genre.ts
> +  'Spoken Word',
not really a music genre?

2024-01-25 04:27 UTC, matthewmayer commented on src/locales/en/music/genre.ts
> +  "Jungle/Drum’n'bass",
also insert at correct alphabetical position (regardless of the quoting style)

2024-01-25 14:08 UTC, jeremyhofer commented on src/locales/en/music/genre.ts
> +  "Jungle/Drum’n'bass",
Split and properly sorted. Thanks for the input here, a lot of references I was finding were always linking these two names tightly together. Was torn on which route to go with it.

2024-01-25 14:08 UTC, jeremyhofer commented on src/locales/en/music/genre.ts
> +  'Standup Comedy',
Removed!

2024-01-25 14:08 UTC, jeremyhofer commented on src/locales/en/music/genre.ts
> +  'Spoken Word',
Removed!

2024-01-25 14:10 UTC, jeremyhofer commented
In addition to the call outs about `Standup Comedy` and `Spoken Word`, I cleaned up other questionable genres that were in the list, trying to keep it pure to music only. This included removing items related to activities like `Study` or `Exercise`, since really any music can be used for that.

2024-01-25 14:35 UTC, matthewmayer submitted a review, later dismissed

2024-01-25 18:04 UTC, ST-DDT reviewed
I'm not sure whether we should include genres like `<any country> X`.
What do the others think?

2024-01-25 18:04 UTC, ST-DDT commented on src/locales/en/music/genre.ts
> +  'Comedy',
This doesn't sound like music to me.

2024-01-25 18:04 UTC, ST-DDT commented on src/locales/en/music/genre.ts
> +  'Disney',
Not sure about this one.

2024-01-25 18:04 UTC, ST-DDT commented on src/locales/en/music/genre.ts
> +  "Drum’n'bass",
Is the usage of two different apostrophes correct here `’` `'`?

2024-01-25 18:04 UTC, ST-DDT commented on src/locales/en/music/genre.ts
> +  'Easy Listening',
Does that count as genre?

2024-01-25 21:09 UTC, jeremyhofer commented on src/locales/en/music/genre.ts
> +  'Comedy',
Agree, will drop this one.

2024-01-25 21:10 UTC, jeremyhofer commented on src/locales/en/music/genre.ts
> +  'Disney',
This one was fairly common in the genre lists I pulled up. I don't have any strong opinions on it. I'd be fine removing it.

2024-01-25 21:11 UTC, jeremyhofer commented on src/locales/en/music/genre.ts
> +  "Drum’n'bass",
This is generally how it was styled in the resources I was looking through. Simply `Drum and Bass` is how it is listed on wikipedia. It also has some shorter forms listed like `D'n'B`. I am fine changing this up some.

https://en.wikipedia.org/wiki/Drum_and_bass

2024-01-25 21:12 UTC, jeremyhofer commented on src/locales/en/music/genre.ts
> +  'Easy Listening',
This was another common genre listed on the resources I reviewed. I agree, it's a bit odd to me. I'd be fine removing it.

2024-01-25 21:17 UTC, jeremyhofer commented
@ST-DDT I had similar thoughts on the country names. There were some examples where e.g. `France` and `French` were both included from the sources I compiled from. In that case I opted for `French`. Could do similar for other countries listed.

2024-01-25 21:20 UTC, xDivisionByZerox commented on src/locales/en/music/genre.ts
> +  "Drum’n'bass",
If you are going to change it I'm in favor of the apostrophe-free style `Drum and Bass`.

2024-01-25 22:47 UTC, ST-DDT commented on src/locales/en/music/genre.ts
> +  "Drum’n'bass",
Choose either:

```suggestion
  "Drum'n'bass",
```

```suggestion
  "Drum’n’bass",
```

```suggestion
  "Drum n bass",
```

2024-01-25 23:25 UTC, matthewmayer commented
I tend to agree that France or French is not really a genre. 

If a French is performing rock, it's Rock. If it's a classical piece, it's Classical, rather than just lumping it under French. 

So maybe let's remove all country/language genres.

2024-01-26 08:35 UTC, ST-DDT submitted a review, later dismissed

2024-01-26 08:35 UTC, ST-DDT commented on src/locales/en/music/genre.ts
> +  'Middle East',
Does this count as country as well or would you consider this separate?

2024-01-26 22:02 UTC, jeremyhofer commented on src/locales/en/music/genre.ts
> +  'Middle East',
Good catch. I think this falls in the country/region bucket as well. Will update to remove.

2024-01-26 22:44 UTC, ST-DDT approved these changes

2024-01-28 12:42 UTC, xDivisionByZerox commented
Sorry for my late feedback. The list you provided is very comprehensive. Would it be better to organize the genres into "main" and "sub" categories? I can see people requesting the possibility of only getting "common" genres. For features like this we would need to introduce a breaking change. Is that something we should consider?

2024-01-28 13:25 UTC, matthewmayer commented
> Sorry for my late feedback. The list you provided is very comprehensive. Would it be better to organize the genres into "main" and "sub" categories? I can see people requesting the possibility of only getting "common" genres. For features like this we would need to introduce a breaking change. Is that something we should consider?

i'd say we dont really do that anywhere else. You can't request "common" first names or "common" dog breeds or "common" countries. There's no standard list of what a musical genre is.

2024-01-28 13:55 UTC, xDivisionByZerox commented
> i'd say we dont really do that anywhere else. You can't request "common" first names or "common" dog breeds or "common" countries. There's no standard list of what a musical genre is.

We have:

- [commonFileExt](https://fakerjs.dev/api/system.html#commonfileext)
- [commonFileName](https://fakerjs.dev/api/system.html#commonfilename)
- [commonFileType](https://fakerjs.dev/api/system.html#commonfiletype)

I see more reason to differenciate betrween common and sub music genres as some genres are literally described as "x is a subgenre of y". For example: 

- [Acid house (also simply known as just "acid") is a subgenre of house music [...]](https://en.wikipedia.org/wiki/Acid_house)
- [Death metal is an extreme subgenre of heavy metal music [...]](https://en.wikipedia.org/wiki/Death_metal)

---

I'm just trying to think ahead to avoid potential breaking chages. If all of you think this is unnecessary I'm fine with that as well.

2024-03-28 17:34 UTC, Shinigami92 approved these changes

2024-03-28 17:34 UTC, xDivisionByZerox approved these changes

2024-03-28 17:34 UTC, ST-DDT commented
**Team Decision**

- We will add this
- If we need a selection of common genres, then we can open a new issue

2024-03-28 17:35 UTC, import-brain approved these changes

2024-03-28 18:02 UTC, merged