docs: fix missing or invalid jsdocs
faker-js/faker pull request #2630
Opened 2024-01-28 18:35 UTC by ST-DDT

During #2628 I found some issues with the existing jsdocs. This PR fixes them.
We should probably include them in a v8.x bugfix release to have a clean end to v8.

2024-01-28 18:37 UTC, Shinigami92 requested changes

2024-01-28 18:37 UTC, Shinigami92 commented on src/faker.ts
> +   * @example Why are you looking at examples here? It's deprecated!
I wont like to support passive aggressive phrases in our docs :thinking:

2024-01-28 18:49 UTC, ST-DDT commented on src/faker.ts
> +   * @example Why are you looking at examples here? It's deprecated!
Then please provide a working example.

2024-01-28 18:56 UTC, Shinigami92 commented on src/faker.ts
> +   * @example Why are you looking at examples here? It's deprecated!
the absolut minimum would be:
```suggestion
   * @example new Faker({ locales });
```

2024-01-29 09:28 UTC, Shinigami92 approved these changes

2024-02-01 16:18 UTC, xDivisionByZerox approved these changes

2024-02-01 16:27 UTC, merged