refactor(image)!: remove v8 deprecated providers
faker-js/faker pull request #2634
Opened 2024-01-29 19:20 UTC by Shinigami92

extracted from https://github.com/faker-js/faker/pull/2608

2024-01-29 19:37 UTC, xDivisionByZerox commented on docs/guide/upgrading_v9/2634.md
> +Removed deprecated image providers from `faker.image`.
Sorry if we discuss this somewhere else before. But if I see correctly we did not merge anything for v9 so far.

Should we include a list/table of API calls that are no longer supported? That why a user that is migrating can simply do a global search in their codebase when they update. I know that in an optimal world, test or build processes would fail for said user ("cannot read x of y") but better be safe I guess.

2024-01-29 20:04 UTC, Shinigami92 commented on docs/guide/upgrading_v9/2634.md
> +Removed deprecated image providers from `faker.image`.
You can already find such a table prepared in https://github.com/faker-js/faker/pull/2608#issuecomment-1901742274

However, this PR now only removes the image providers and is just a piece of many deprecation removals

The `docs/guide/upgrading_v9/*.md` are only there for us, so before merging/releasing v9 we can rework the whole migration guide. There are just temp files.

2024-01-29 20:28 UTC, xDivisionByZerox commented on docs/guide/upgrading_v9/2634.md
> +Removed deprecated image providers from `faker.image`.
> You can already find such a table prepared in https://github.com/faker-js/faker/pull/2608#issuecomment-1901742274

Thank you for pointing that out. As  far as I can see, the image modules are not in this table (at least not the full API).

> The docs/guide/upgrading_v9/*.md are only there for us, so before merging/releasing v9 we can rework the whole migration guide. There are just temp files.

I know. The point is that a single PR creates a template for the migration that is as complete as it can be. So why not include the part of the table that is actually gets removed here? If it is not included here, there is a chance that we might miss that. If you do not split the migration templates, why bother making this PR in the first place? Where does the table from the comment end up in, if all depreations are spread into different PRs?

2024-02-09 17:43 UTC, Shinigami92 commented on docs/guide/upgrading_v9/2634.md
> +Removed deprecated image providers from `faker.image`.
So first, removing all deprecations in one PR would violate our contribution guidelines because to many files are affected at the same time.

Secondly there are right now failing CI checks in the other big PR #2608 and it is ultra hard to debug out of the full clutter of that many changes to find out what the issues are right now.
So cutting these down into smaller chunks helps to already remove some deprecations until we found what is the missing and failing rest.

2024-02-09 17:46 UTC, ST-DDT commented on docs/guide/upgrading_v9/2634.md
> +Removed deprecated image providers from `faker.image`.
I think @xDivisionByZerox is asking to have the table with alternative image methods here in this document.

2024-02-09 18:22 UTC, Shinigami92 commented on docs/guide/upgrading_v9/2634.md
> +Removed deprecated image providers from `faker.image`.
I fully misunderstood you intend. I discussed with @ST-DDT and now I got you. Added.

2024-02-09 18:24 UTC, ST-DDT commented on docs/guide/upgrading_v9/2634.md
> +| faker.unsplash.buildings            | faker.image.url             |
Maybe refer to a method that supports categories?
Such as `faker.image.urlLoremFlickr({ category: 'food' })`?

2024-02-09 18:54 UTC, Shinigami92 commented on docs/guide/upgrading_v9/2634.md
> +| faker.unsplash.buildings            | faker.image.url             |
That does not exists anymore, I think because the related providers are not available anymore at all :grimacing:

2024-02-09 18:55 UTC, ST-DDT submitted a review, later dismissed

2024-02-10 02:06 UTC, matthewmayer commented on docs/guide/upgrading_v9/2634.md
> +| faker.unsplash.buildings            | faker.image.url             |
faker.image.urlLoremFlickr({ category: 'food' }) does still exist. The remaining two providers are LoremFlickr (which does support categories) and Picsum (which does not).

2024-02-10 02:09 UTC, matthewmayer requested changes

2024-02-10 02:09 UTC, matthewmayer commented on docs/guide/upgrading_v9/2634.md
> +| faker.lorempicsum.image             | faker.image.urlPicsumPhotos |
im confused by this "old" column, for example there was never a method called faker.lorempicsum.image() as far as i know?

2024-02-10 06:45 UTC, matthewmayer commented on docs/guide/upgrading_v9/2634.md
> +| faker.lorempicsum.image             | faker.image.urlPicsumPhotos |
ah i think it should be `faker.image.lorempicsum.image()` ?

2024-02-10 09:05 UTC, Shinigami92 commented on docs/guide/upgrading_v9/2634.md
> +| faker.lorempicsum.image             | faker.image.urlPicsumPhotos |
Well... I think our deprecations are wrong then :grimacing: 
https://github.com/faker-js/faker/blob/bc3ebb793666c0d7e58cf428ba12465a7b290cbe/src/modules/image/providers/lorempicsum.ts#L33-L38
I just copy pasted out of the source code

Did we not see that or do we need to release a v8.4.2 now?

2024-02-10 10:54 UTC, matthewmayer commented on docs/guide/upgrading_v9/2634.md
> +| faker.lorempicsum.image             | faker.image.urlPicsumPhotos |
I think almost no one was probably using these methods as they weren't publicly documented. They would only use them indirectly via the faker.image.foo methods?

faker.image.lorempicsum.image()

2024-02-10 11:12 UTC, ST-DDT approved these changes, later dismissed

2024-02-10 11:21 UTC, matthewmayer requested changes

2024-02-10 11:21 UTC, matthewmayer commented on docs/guide/upgrading_v9/2634.md
> +Removed deprecated image providers from `faker.image`.
Maybe we should explain that these were already returning broken image urls?

2024-02-11 18:11 UTC, Shinigami92 commented on docs/guide/upgrading_v9/2634.md
> +Removed deprecated image providers from `faker.image`.
```suggestion
Removed deprecated image providers from `faker.image`. They already returned broken image URLs anyways.
```

2024-02-11 18:46 UTC, ST-DDT approved these changes

2024-02-13 15:20 UTC, matthewmayer approved these changes

2024-02-14 19:36 UTC, merged