infra(unicorn): prefer-string-replace-all
faker-js/faker pull request #2653
Opened 2024-02-09 18:10 UTC by Shinigami92

Ref: #2439

- #2439

---

Permanently enables the [`unicorn/prefer-string-replace-all`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-string-replace-all.md) lint rule.

2024-02-09 18:19 UTC, ST-DDT commented on docs/guide/upgrading_v9/2653.md
> +https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll
For me this is redundant, we already have 

https://github.com/faker-js/faker/blob/bc3ebb793666c0d7e58cf428ba12465a7b290cbe/docs/guide/upgrading_v9/2121.md?plain=1#L1-L3

for that. IMO we don't have to explain to the users that the code breaks because of `??=` or `String.replaceAll`.
We want to use new code features, that is the reason we drop support for old versions.

2024-02-09 18:28 UTC, Shinigami92 commented on docs/guide/upgrading_v9/2653.md
> +https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll
Yeah, the upgrading guidelines will get merged before releasing `v9.0.0-alpha.0` anyways.
So this is more like an explanation why there was a `!` / breaking change marker for that PR.

Later we can then e.g. merge that together and not only write "drop v16" but also "why -> code examples / which code features are used now"

2024-02-09 19:33 UTC, ST-DDT commented on docs/guide/upgrading_v9/2653.md
> +https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll
The problem with the breaking `!` marker, is that it causes the PR to be listed in the changelog as breaking changes, and IMO it adds unnecessary noise to that section.

2024-02-09 19:35 UTC, Shinigami92 commented on docs/guide/upgrading_v9/2653.md
> +https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll
Ah :thinking: you have a point there

Okay, I will remove the ! from PR title.

Not sure yet if I should keep or remove the md file, because that still might help to explain the "why" later when we merge the migration files.
I would like to leave this decision to @matthewmayer

2024-02-10 02:13 UTC, matthewmayer commented on docs/guide/upgrading_v9/2653.md
> +https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll
i agree. updating to use Node-18 specific features is not breaking now that Node 14/16 has been dropped, and doesn't require an explanation in the upgrading guide.

2024-02-10 09:42 UTC, ST-DDT requested changes

2024-02-10 09:42 UTC, ST-DDT commented on docs/guide/upgrading_v9/2121.md
> +#### Examples of code-upgrades that are now used:
I think this is unneccessary as outlined here https://github.com/faker-js/faker/pull/2654#discussion_r1485033229

2024-02-16 15:39 UTC, ST-DDT approved these changes, later dismissed

2024-02-17 18:24 UTC, import-brain approved these changes, later dismissed

2024-02-18 22:56 UTC, ST-DDT approved these changes

2024-02-18 22:56 UTC, merged