infra(unicorn)!: prefer-at
faker-js/faker pull request #2654
Opened 2024-02-09 18:34 UTC by Shinigami92

Ref: #2439

- #2439

---

Permanently enables the [`unicorn/prefer-at`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-at.md) lint rule.

2024-02-09 18:58 UTC, Shinigami92 commented on src/modules/helpers/index.ts
> +    return array.at(-1)!.value;
Adding a test for this is not related to the PR :slightly_smiling_face:

2024-02-09 19:29 UTC, ST-DDT submitted a review, later dismissed

2024-02-09 19:31 UTC, ST-DDT commented
IMO this isn't breaking for the same reasons as outlined there: https://github.com/faker-js/faker/pull/2653#discussion_r1484660651

2024-02-10 02:11 UTC, matthewmayer commented on scripts/apidoc/typedoc.ts
> +      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
this ends up being much more verbose than the original code due to the need to disable the no-non-null-assertion. Is this temporary or is there a better way around this?

2024-02-10 02:12 UTC, matthewmayer submitted a review, later dismissed

2024-02-10 02:12 UTC, matthewmayer commented on docs/guide/upgrading_v9/2654.md
i dont think its necessary to include this if its not end-user facing.

2024-02-10 09:21 UTC, Shinigami92 commented on docs/guide/upgrading_v9/2654.md
What do you mean by not including if not end-user facing? Most if not nearly all chores and infra changes are not end-user facing :thinking: 
This enhances the code base for us, the devs. Right now we do not have `noUncheckedIndexedAccess` turned on, and so we miss many potential hidden null-safety bugs. This change does not only improve DX (developer experience) through shorter code + inline docs

![image](https://github.com/faker-js/faker/assets/7195563/9f3686da-585c-44e4-ad9b-49a52399a12b)

but also enforces the need of check for `undefined` if there was no last value (e.g. when the array was empty)
_Sadly_ TypeScript is not able to infer the code flow to check that `.at(-1)` is coming after a `array.length > 0` check, but how even could it, cause the input parameter for `at` is just a number.

2024-02-10 09:24 UTC, Shinigami92 commented on scripts/apidoc/typedoc.ts
> +      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
this is mostly because I specifically decided to put that absolutely near to the affected code part instead of just above the line

so it could also be

```ts
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
const lastSummaryPart = summary.at(-1)!;
```

2024-02-10 09:37 UTC, ST-DDT requested changes

2024-02-10 09:37 UTC, ST-DDT commented on docs/guide/upgrading_v9/2121.md
> +#### Examples of code-upgrades that are now used:
I think you can drop this section entirely.
If you think it is important to point out why we dropped support, just mention "we would like to use new features that these versions provide such as `||=` and the others are EOL anyway." One such example is sufficient.

2024-02-10 09:38 UTC, Shinigami92 commented on docs/guide/upgrading_v9/2121.md
> +#### Examples of code-upgrades that are now used:
Lets discuss internally further on or wait on next team meeting

2024-02-10 11:00 UTC, matthewmayer commented on docs/guide/upgrading_v9/2654.md
It's a good change. It just doesn't need to be in the migration guide. Because the migration guide is for people who are using Faker. If you are upgrading from v8 to v9 you just need to ensure you are using Node 18+. The fact that Faker is internally now using certain features of Node 18 should not matter to use as a consumer of the library.

2024-02-16 15:10 UTC, Shinigami92 commented on docs/guide/upgrading_v9/2121.md
> +#### Examples of code-upgrades that are now used:
We decided to only reference other migration files, but not change them directly

2024-02-16 15:41 UTC, ST-DDT approved these changes, later dismissed

2024-02-16 15:46 UTC, ST-DDT commented on docs/guide/upgrading_v9/2654.md
> +We could hint users to use polyfill or transpile-down steps.
Note from my future me: We will probably have at most a very minimum description of "how to transpile down for node < x". I won't help them shoot themselves in the foot and complain to us about it.

2024-02-17 23:28 UTC, import-brain approved these changes, later dismissed

2024-02-19 02:59 UTC, matthewmayer commented on docs/guide/upgrading_v9/2654.md
> +We could hint users to use polyfill or transpile-down steps.
If you are stuck using node 14/16 you should just stay on faker@8 rather than try to transpile things.

2024-02-19 10:06 UTC, ST-DDT approved these changes

2024-02-19 10:08 UTC, merged