feat(locale): add uzbek locale
faker-js/faker pull request #2686
Opened 2024-02-25 22:13 UTC by Mirazyzz

Added initial locale values for person in Uzbek language.

2024-02-25 22:29 UTC, ST-DDT reviewed
IMO we should rename `uz_UZ` to `uz`.

2024-02-25 22:30 UTC, ST-DDT commented
Also please run `pnpm run preflight`

2024-02-25 22:49 UTC, Mirazyzz commented
> IMO we should rename `uz_UZ` to `uz`.

Uzbek language consist of latin and cyrillic alphabets. https://en.wikipedia.org/wiki/Uzbek_alphabet

2024-02-26 02:30 UTC, matthewmayer commented
> IMO we should rename `uz_UZ` to `uz`.

For new locales i generally prefer lang_COUNTRY - as soon as you start adding addresses and phone numbers, they are typically specific for a certain country.

2024-02-26 07:49 UTC, ST-DDT commented
> > IMO we should rename `uz_UZ` to `uz`.
> 
> Uzbek language consist of latin and cyrillic alphabets. I thought we could include support for both in the future. https://en.wikipedia.org/wiki/Uzbek_alphabet

Ok, if there are two variants of the locale then we should make that visible in the name as well similar to https://github.com/faker-js/faker/tree/next/src/locales/sr_RS_latin

2024-02-26 08:12 UTC, Mirazyzz commented
> > > IMO we should rename `uz_UZ` to `uz`.
> > 
> > 
> > Uzbek language consist of latin and cyrillic alphabets. I thought we could include support for both in the future. https://en.wikipedia.org/wiki/Uzbek_alphabet
> 
> Ok, if there are two variants of the locale then we should make that visible in the name as well similar to https://github.com/faker-js/faker/tree/next/src/locales/sr_RS_latin
> 
> Or is there a different common disambiguator?

so would it be better to rename it to **uz_latin**?

2024-02-26 09:07 UTC, ST-DDT commented
I meant more like `uz_UZ_latin`

Language_country_variant

2024-02-26 09:08 UTC, matthewmayer commented
uz_UZ_latin 

Seems the most correct. Uzbek, as spoken in Uzbekistan, with Latin variant. 

That would allow for say in future 

uz_UZ_cyrillic
uz_AF_latin
uz_RU_cyrillic

2024-02-26 15:21 UTC, matthewmayer requested changes

2024-02-26 15:21 UTC, matthewmayer commented on src/locales/uz_UZ/metadata.ts
> +  code: 'uz_UZ',
Should also include `country: 'UZ'` here

2024-02-26 15:21 UTC, matthewmayer commented on src/locales/uz_UZ/person/bio_parts.ts
> +  "san'atkor",
Is there a difference between the two types of apostrophe? If not use the straight ' one everywhere.

2024-02-26 16:51 UTC, Mirazyzz commented
> uz_UZ_latin
> 
> Seems the most correct. Uzbek, as spoken in Uzbekistan, with Latin variant.
> 
> That would allow for say in future
> 
> uz_UZ_cyrillic uz_AF_latin uz_RU_cyrillic

Just for clarity, the Uzbek language does not have dialectic variations such as American English, British English, or Australian English. The differences in Uzbek primarily lie within the alphabet utilized. Historically, we used the Cyrillic alphabet but transitioned to Latin over the past three decades, which is currently recognized as the official alphabet. Nevertheless, there remains a portion of the population, predominantly individuals over the age of 50-60, who only read in Cyrillic. The important point to note is that the grammar, words, and their meanings remain consistent regardless of the alphabet used.

Given this context, I think that it might be more reasonable to use codes "uz_latin" and "uz_cyrillic" rather than associating them with specific countries, since the language does not vary from one country to another. However, I'm open to different solutions just wanted to give more context.

2024-02-26 17:03 UTC, Mirazyzz commented on src/locales/uz_UZ/person/bio_parts.ts
> +  "san'atkor",
Yes, there is a difference between them one serves as a part of a letter while the other alters sound and has potential to appear in various positions within a word. However, I'm a little hesitant of using both of them even though it would be more grammatically correct, but the future contributions might not adhere to these nuances, resulting in the indiscriminate use of **'** as a substitute for both. Let me know what you think about this, please.

2024-02-26 18:05 UTC, ST-DDT commented on src/locales/uz_UZ/person/bio_parts.ts
> +  "san'atkor",
If it is grammatically more correct (and not overly context sensitive), I think having both apostrophe variants is fine.
If future contributors, change that then we aren't any worse off than using only a single variant right now.
(And will likely spark a discussion, about the correct one again)

2024-02-26 20:48 UTC, Mirazyzz commented on src/locales/uz_UZ/metadata.ts
> +  code: 'uz_UZ',
https://github.com/faker-js/faker/pull/2686#issuecomment-1964635244

If we'll be using **uz_latin**, **uz_cyrillic** then it's not going to be **PreBuiltMetadataDefinitionForCountry**.

2024-02-27 00:13 UTC, matthewmayer commented
Adding the country code, in addition to the alphabet variant is more about indicating that say `faker.location.city()` would return cities in Uzbekistan.

2024-02-27 19:56 UTC, Mirazyzz commented on src/locales/uz_UZ/metadata.ts
> +  code: 'uz_UZ',
Done

2024-02-28 13:50 UTC, Mirazyzz commented
@matthewmayer, @ST-DDT Is there any additional changes I have to make in order be able to merge?

2024-02-28 14:19 UTC, ST-DDT commented
There are two things required.
- The team's decision on the locale id.
- The review of the actual words (if you know somebody that is familiar with the language and help review the names and approve the PR, that would help us a lot). Otherwise it might take a few more days before we have the time to check the names/words.

2024-02-28 15:12 UTC, Mirazyzz commented
> There are two things required.
> 
> * The team's decision on the locale id.
> * The review of the actual words (if you know somebody that is familiar with the language and help review the names and approve the PR, that would help us a lot). Otherwise it might take a few more days before we have the time to check the names/words.

Thanks for your response. Is a person to review the names/words should be from the Faker team or it could be any other contributor?

2024-02-28 15:37 UTC, ST-DDT commented
> Is a person to review the names/words should be from the Faker team or it could be any other contributor?

The Faker team has to review the files anyway. But any volunteers review helps.

2024-02-29 17:31 UTC, ST-DDT commented
**Team Decision**

Please use `uz_UZ_latin` to follow our localization guide.

We will extend the localization guide to include the representation `639[_3166[_variant]]` to better describe the intend behind our textual guideline.

We might change it in a future major version and then adjust all other locales as well.

2024-03-01 19:08 UTC, Mirazyzz commented
> **Team Decision**
> 
> Please use `uz_UZ_latin` to follow our [localization guide](https://fakerjs.dev/guide/localization.html#locale-codes).
> 
> We will extend the localization guide to include the representation `<ISO-639-1>[_<ISO-3166-1>[_<variant>]]` to better describe the intend behind our textual guideline.
> 
> We might change it in a future major version and then adjust all other locales as well.

Done.

2024-03-01 22:14 UTC, ST-DDT commented on src/locales/uz_UZ_latin/person/male_first_name.ts
> +  "G'ulom",
This seems to also refer to "slave". 🤔 
Is that a bad translation from Google?

2024-03-02 06:24 UTC, matthewmayer requested changes

2024-03-02 06:24 UTC, matthewmayer commented on src/locales/uz_UZ_latin/metadata.ts
>    title: 'Uzbek (Latin)',
For consistency with sr_RS_latin the title should be "Uzbek (Uzbekistan, Latin)

2024-03-03 07:32 UTC, Mirazyzz commented on src/locales/uz_UZ_latin/person/male_first_name.ts
> +  "G'ulom",
https://uz.wikipedia.org/wiki/G%CA%BBulom_Zafariy
https://en.wikipedia.org/wiki/G%CA%BBafur_G%CA%BBulom

These are all proper names. Probably bad translation from Google indeed.

2024-03-03 07:34 UTC, Mirazyzz commented on src/locales/uz_UZ_latin/metadata.ts
>    title: 'Uzbek (Latin)',
Done

2024-03-04 08:46 UTC, Mirazyzz commented
@ST-DDT what can be the reason of a failing build? Looking at the log I don't think it's related to my changes, could you assist me, please?

2024-03-04 09:05 UTC, ST-DDT approved these changes, later dismissed

2024-03-04 09:15 UTC, Shinigami92 approved these changes, later dismissed

2024-03-04 09:17 UTC, Shinigami92 commented on src/locales/uz_UZ_latin/metadata.ts
> +  endonym: "O'zbekcha",
dont we need variant here like in https://github.com/faker-js/faker/blob/c52ec8ac431debace995a4b8cf51e586b64a6483/src/locales/sr_RS_latin/metadata.ts#L8C3-L8C19 ?

2024-03-04 09:25 UTC, Mirazyzz commented on src/locales/uz_UZ_latin/metadata.ts
> +  endonym: "O'zbekcha",
What is the usage of the **variant**?

2024-03-04 09:35 UTC, ST-DDT commented on src/locales/uz_UZ_latin/metadata.ts
> +  endonym: "O'zbekcha",
It is part of the locale's metadata that we expose. And yes we should add it.

2024-03-04 14:21 UTC, Shinigami92 approved these changes

2024-03-04 14:53 UTC, matthewmayer approved these changes

2024-03-04 15:04 UTC, ST-DDT approved these changes

2024-03-04 15:05 UTC, merged