docs(finance): mention where to look up issuer names
faker-js/faker pull request #2720
Opened 2024-03-05 16:29 UTC by ST-DDT

Fixes #181 (our oldest open issue)

- #181

(I removed the jsdocs from the implementation signature, as it isn't visible to our users anyway.)

2024-03-05 16:59 UTC, matthewmayer requested changes

2024-03-05 16:59 UTC, matthewmayer commented on src/modules/finance/index.ts
> +   * You can access that value at runtime directly or from the sources on GitHub (`src/locales/<name>/finance/credit_card`).
would it be easier to just directly list them out here? there aren't many

2024-03-05 17:13 UTC, ST-DDT commented on src/modules/finance/index.ts
> +   * You can access that value at runtime directly or from the sources on GitHub (`src/locales/<name>/finance/credit_card`).
Changed

2024-03-05 20:55 UTC, Shinigami92 submitted a review, later dismissed

2024-03-05 21:22 UTC, xDivisionByZerox commented on src/modules/finance/index.ts
> +   * You can access that value at runtime directly or from the sources on GitHub (`src/locales/<name>/finance/credit_card`).
> would it be easier to just directly list them out here? there aren't many

Not a fan of this. This means we have multiple sources of truth. Additionally, if they aren't that many to list them out, why not create a separate string union entirely?

2024-03-05 21:41 UTC, ST-DDT commented on src/modules/finance/index.ts
> +   * You can access that value at runtime directly or from the sources on GitHub (`src/locales/<name>/finance/credit_card`).
I also considered that, but that would be breaking the implementation (which I feel tempted to do anyway).

I thought about using strictly

````ts
creditCardNumber(options: { issuer: format }} // without the current wildcard format support
````

2024-03-06 04:14 UTC, matthewmayer commented on src/modules/finance/index.ts
> +   * You can access that value at runtime directly or from the sources on GitHub (`src/locales/<name>/finance/credit_card`).
i think the improvement to developer experience outweighs the fact that there are multiple sources of truth. New card issuers would only appear extremely rarely (who is going to launch a visa/mastercard competitor in 2024?)

2024-03-07 13:50 UTC, xDivisionByZerox commented on src/modules/finance/index.ts
> +   * You can access that value at runtime directly or from the sources on GitHub (`src/locales/<name>/finance/credit_card`).
> i think the improvement to developer experience outweighs the fact that there are multiple sources of truth.

Despite my previous comment, I'm with you on this one 👍 

 > New card issuers would only appear extremely rarely (who is going to launch a visa/mastercard competitor in 2024?)

This makes me want to create a `CreditCardIssuer` type even more TBH.

2024-03-07 17:01 UTC, ST-DDT commented
**Team Decision**

* We will use a literal CreditCardIssuer enum.
* To check, whether the credit card patterns contain localized parts.
  * If not, remove localized patterns and only use localized data to identify which issuer is preferred in a country

````ts
creditCardNumber(options: { issuer?: CreditCardIssuer } = {}) {
  const { issuer = arrayElement(defintions.finance.preferred_credit_card_issuer) } = options;

  switch (issuer) {
   case issuer1: ...;
   case issuer2: ...;
}
````

2024-03-09 08:33 UTC, matthewmayer commented on src/modules/finance/index.ts
> +   * You can access that value at runtime directly or from the sources on GitHub (`src/locales/<name>/finance/credit_card`).
as currently issuer names are allowed to be any case, perhaps we should start logging a warning if the issuer name is not lowercase? That will make migration easier when this becomes an enum.

2024-03-09 08:48 UTC, ST-DDT commented on src/modules/finance/index.ts
> +   * You can access that value at runtime directly or from the sources on GitHub (`src/locales/<name>/finance/credit_card`).
I might just throw an error, because custom format patterns will be dropped as well.

2024-03-09 09:55 UTC, matthewmayer commented on src/modules/finance/index.ts
> +   * You can access that value at runtime directly or from the sources on GitHub (`src/locales/<name>/finance/credit_card`).
Could throw a warning in v9 and make it an enum in v10

2024-03-09 19:44 UTC, ST-DDT commented
Which variant would you prefer?

````ts
// A) Using or "options" syntax?
creditCardNumber(options: { issuer?: CreditCardIssuer } = {})
creditCardNumber({ issuer: CreditCardIssuer.Visa })
````

or

````ts
// B) Like person.firstName
creditCardNumber(issuer: CreditCardIssuer = this.creditCardIssuer())
creditCardNumber(CreditCardIssuer.Visa)
````

2024-03-09 20:14 UTC, ST-DDT commented
Should we allow passing array's of allowed issuers?
And how so?

````ts
// 2A) Forbid
... issuer: CreditCardIssuerType ...
````
or
````ts
// 2B) Allow
... issuer: CreditCardIssuerType | CreditCardIssuerType[] ...
````
or
````ts
// 2C) Require
... issuer: CreditCardIssuerType[] ...
````

2024-03-11 15:44 UTC, ST-DDT commented on test/modules/finance.spec.ts
> +          expect(
```suggestion
          // Deprecated
          expect(
```

2024-03-11 15:46 UTC, ST-DDT commented on src/modules/finance/index.ts
> +      default: {
This should throw an error (due to overly exhaustive switch): https://github.com/typescript-eslint/typescript-eslint/issues/8645

- https://github.com/typescript-eslint/typescript-eslint/issues/8645

2024-03-16 04:34 UTC, matthewmayer commented
This should be marked breaking no？ it changes the behavior when a unknown or non lower case issuer is passed.

2024-03-17 00:37 UTC, xDivisionByZerox commented on src/modules/finance/index.ts
>      }
Do we want to support this? "quick options" are a part of fakers signatures in a lot of places. 🤔

2024-03-17 00:44 UTC, xDivisionByZerox commented on test/modules/finance.spec.ts
> +        } as unknown as CreditCardIssuerType);
Why are these deprecated? `'visa' | 'mastercard'` should be included in `CreditCardIssuerType`. What am I missing?

2024-03-17 01:00 UTC, xDivisionByZerox commented on src/locales/el/finance/credit_card/maestro.ts
> -export default ['/50#{9,16}L/', '/5[6-8]#{9,16}L/', '/56##{9,16}L/'];
These patterns where actually different from the other en `maestro` ones 🤔

2024-03-17 01:00 UTC, xDivisionByZerox commented on src/modules/finance/index.ts
>    creditCardNumber(
Is the JSDoc not required here?

2024-03-17 09:21 UTC, Shinigami92 commented on src/modules/finance/index.ts
> +        deprecated: 'faker.finance.creditCardNumber(iSsUeR)',
This looks absolutely weird to me :eyes:

2024-03-17 09:21 UTC, Shinigami92 commented on src/modules/finance/index.ts
> +  DinersClub = 'diners_club',
Do we have any conventions yet? Otherwise I would be in favor of using `-` instead of `_` for the string values.

2024-03-17 09:21 UTC, Shinigami92 commented on src/modules/finance/index.ts
> +      case CreditCardIssuer.AmericanExpress: {
This wont work when the string value of the enum contains a separator like `_` or `-`, but the `actuallIssuer` is just lowercased in [line 580](https://github.com/faker-js/faker/pull/2720/files#diff-ed919e84dad7aa63abddfc6222d0c69df214a632cd29cbce6866b9a0f968d618R580).

2024-03-17 09:50 UTC, ST-DDT commented on src/modules/finance/index.ts
> +        deprecated: 'faker.finance.creditCardNumber(iSsUeR)',
Any idea how to show case insesitive is deprecated?

2024-03-17 09:50 UTC, ST-DDT commented on src/modules/finance/index.ts
> +  DinersClub = 'diners_club',
> Do we have any conventions yet?

No. I just used what we use/have already.

2024-03-17 09:52 UTC, ST-DDT commented on src/modules/finance/index.ts
> +      case CreditCardIssuer.AmericanExpress: {
Why wouldnt it? The test seem to be working fine.

2024-03-17 10:20 UTC, Shinigami92 commented on src/modules/finance/index.ts
> +      case CreditCardIssuer.AmericanExpress: {
Ah I see, its because `issuer` is now `CreditCardIssuerType` strictly typed instead of a `string`. But why do we need the `toLowerCase` then in the first place?

2024-03-17 12:29 UTC, ST-DDT commented on src/modules/finance/index.ts
> +      case CreditCardIssuer.AmericanExpress: {
Backwards compatibility.

2024-03-17 12:32 UTC, Shinigami92 commented on src/modules/finance/index.ts
> +      case CreditCardIssuer.AmericanExpress: {
Is this a discussion about #2725 again? Otherwise the type def is wrong, because arbitrary strings  are not possible anymore.

2024-03-17 12:39 UTC, ST-DDT commented on src/modules/finance/index.ts
>    creditCardNumber(
That is the implementation signature. It isn't visible to users.

2024-03-17 12:48 UTC, ST-DDT commented on src/modules/finance/index.ts
> +      case CreditCardIssuer.AmericanExpress: {
> Is this a discussion about #2725 again?

In the sense, that we follow our usual deprecation steps: Yes

That's why the following comment is there:

> // TODO @ST-DDT 2024-03-09: Remove the fallback in v10

2024-03-17 12:51 UTC, matthewmayer commented on src/modules/finance/index.ts
> +      case CreditCardIssuer.AmericanExpress: {
Wouldn't it be better to do this in two stages? In 9.0 log a runtime warning if an unknown or mixed case issuer is passed. Then in 10.0 switch to the enum.

2024-03-17 13:15 UTC, ST-DDT commented on src/modules/finance/index.ts
> +      case CreditCardIssuer.AmericanExpress: {
🤔 Not sure about that.
JS users already have the backwards compatibility code.
TS users would have more time to migrate at the cost of runtime warnings instead of compile time errors.

2024-03-18 00:33 UTC, matthewmayer commented on src/modules/finance/index.ts
> +        deprecated: 'faker.finance.creditCardNumber(iSsUeR)',
what about 

 deprecated: `faker.finance.creditCardNumber(${issuer})`,
 proposed: `faker.finance.creditCardNumber(${actualIssuer})`,

2024-03-18 14:21 UTC, xDivisionByZerox commented on src/modules/finance/index.ts
> +        deprecated: 'faker.finance.creditCardNumber(iSsUeR)',
Or maybe:

```suggestion
        deprecated: 'faker.finance.creditCardNumber(issuerWithRandomCase)',
```

2024-03-18 14:26 UTC, xDivisionByZerox commented on src/modules/finance/index.ts
> +  DinersClub = 'diners_club',
Since this change is breaking anyway, we might want to standardize these cases. I'm not that much in favor of any case, but would like to have a "rule" for these types.

2024-06-02 13:34 UTC, closed without merging