feat(locale): extend Uzbek locale for date and color
faker-js/faker pull request #2724
Opened 2024-03-07 07:53 UTC by Mirazyzz

2024-03-07 08:15 UTC, ST-DDT reviewed
I'll do the actual review later, when I have some more free time.

---

FFR: Please only do one module per PR to make things easier to review.

- https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md#adding-new-locale-or-updating-existing-one

In this case I think it is OK, but keep that in mind for future PRs.

2024-03-07 08:15 UTC, ST-DDT commented on src/locales/uz_UZ_latin/phone_number/index.ts
We are currently rewriting the phone module.

- #2578 

So this either has to wait until that is merged or you can temporarily remove this.

2024-03-07 08:48 UTC, Mirazyzz commented on src/locales/uz_UZ_latin/phone_number/index.ts
Sure, I'll remove it and add after the the PR will be merged.

2024-03-07 11:25 UTC, matthewmayer requested changes

2024-03-07 11:25 UTC, matthewmayer commented on src/locales/uz_UZ_latin/color/human.ts
> +  'qizil',
Alphabetical order please

2024-03-07 11:25 UTC, matthewmayer commented on src/locales/uz_UZ_latin/date/weekday.ts
> +  wide_context: [
You can omit the "context " versions if they are identical

2024-03-07 11:25 UTC, matthewmayer commented on src/locales/uz_UZ_latin/date/weekday.ts
> +  abbr_context: ['Ya', 'Du', 'Se', 'Ch', 'Pa', 'Ju', 'Sh'],
Same.

2024-03-07 11:26 UTC, matthewmayer commented
> I'll do the actual review later, when I have some more free time.
> 
> 
> 
> ---
> 
> 
> 
> FFR: Please only do one module per PR to make things easier to review.
> 
> 
> 
> - https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md#adding-new-locale-or-updating-existing-one
> 
> 
> 
> In this case I think it is OK, but keep that in mind for future PRs.

Also please put the module(s) in the PR title eg

Extend Uzbek locale for date and color

2024-03-12 13:27 UTC, ST-DDT commented on src/locales/uz_UZ_latin/color/human.ts
> +  'buniq',
Google translates this to "this". Is this correct?

2024-03-12 13:27 UTC, ST-DDT commented on src/locales/uz_UZ_latin/color/human.ts
> +  'fayruz rang',
AFAICT the `rang` word refers to color.
Is it normal to always refer to `blue color` instead of just `blue` in Uzbek language?
Some translations don't have that.

2024-03-12 13:27 UTC, ST-DDT commented on src/locales/uz_UZ_latin/date/month.ts
> +    'Iyl',
Google seems to be unable to properly translate these.
Do you have a source or reference, that I can use to verify these?

2024-03-12 14:14 UTC, matthewmayer commented on src/locales/uz_UZ_latin/date/month.ts
> +    'Iyl',
you can get the localized month names from ICU data in node:

```js
function getMonthNames(locale, format = 'long') {
    const monthNames = [];
    for (let month = 0; month < 12; month++) {
        // Create a date for each month of the year, arbitrarily using the 1st day
        const date = new Date(Date.UTC(2020, month, 1));
        const monthName = new Intl.DateTimeFormat(locale, { month: format }).format(date);
        monthNames.push(monthName);
    }
    return monthNames;
}

// Get short month names in Uzbek
const shortMonthNamesUz = getMonthNames('uz-UZ', 'short');
console.log('Short month names in Uzbek:', shortMonthNamesUz);

// Get long month names in Uzbek
const longMonthNamesUz = getMonthNames('uz-UZ', 'long');
console.log('Long month names in Uzbek:', longMonthNamesUz);
```

```
Short month names in Uzbek: [
  'Yan', 'Fev', 'Mar',
  'Apr', 'May', 'Iyn',
  'Iyl', 'Avg', 'Sen',
  'Okt', 'Noy', 'Dek'
]

Long month names in Uzbek: [
  'Yanvar',  'Fevral',
  'Mart',    'Aprel',
  'May',     'Iyun',
  'Iyul',    'Avgust',
  'Sentabr', 'Oktabr',
  'Noyabr',  'Dekabr'
]
```

2024-03-12 14:19 UTC, Mirazyzz commented on src/locales/uz_UZ_latin/color/human.ts
> +  'fayruz rang',
Occasionally, a singular word may carry dual meanings and to clarify its intended use within a specific context, we use the term rang as a clarificatory addition. For instance, the word "Olov" translates to "Fire" but when couched in the term "Olov rang", it means "Orange". It's not universally applicable to all colors, but used only in instances where a word possesses multiple interpretations.

2024-03-12 14:19 UTC, Mirazyzz commented on src/locales/uz_UZ_latin/date/month.ts
> +    'Iyl',
You can find it in months section below.
https://www.unicode.org/cldr/cldr-aux/charts/28/verify/dates/uz.html

2024-03-12 14:20 UTC, Mirazyzz commented on src/locales/uz_UZ_latin/color/human.ts
> +  'buniq',
Buni translates to "this", but **Buniq** is a color.

2024-03-12 14:26 UTC, matthewmayer commented on src/locales/uz_UZ_latin/color/human.ts
> +  'buniq',
which color?

chatgpt is also struggling to interpret that one

https://chat.openai.com/share/cda15592-1515-461c-8245-0f676d3b6f0e

2024-03-12 14:27 UTC, matthewmayer commented on src/locales/uz_UZ_latin/color/human.ts
> +  'fayruz rang',
i guess we dont need both:
siyoh binofsha
siyoh binofsha rang
then?

2024-03-12 14:45 UTC, Mirazyzz commented on src/locales/uz_UZ_latin/color/human.ts
> +  'fayruz rang',
Yes, we can have one of them, probably we can go with the first one.

2024-03-12 14:52 UTC, Mirazyzz commented on src/locales/uz_UZ_latin/color/human.ts
> +  'buniq',
I don't know its equivalent in English neither. We can get rid of it if we want to keep only universal colors.

2024-03-12 15:08 UTC, Mirazyzz commented
@ST-DDT @matthewmayer what is the reason for the [build to fail](https://github.com/faker-js/faker/actions/runs/8250984481/job/22566945417?pr=2724)?

2024-03-12 15:32 UTC, ST-DDT commented
> what is the reason for the [build to fail](https://github.com/faker-js/faker/actions/runs/8250984481/job/22566945417?pr=2724)?

An issue with codecov itself, that is unrelated to this PR.

- https://github.com/codecov/feedback/issues/126#issuecomment-1991913679

2024-03-12 15:38 UTC, ST-DDT submitted a review, later dismissed

2024-03-12 20:05 UTC, Shinigami92 approved these changes, later dismissed

2024-03-14 20:33 UTC, Mirazyzz commented
Apologies, instead of pushing to a new branch I pushed to the old... 
![2323](https://github.com/faker-js/faker/assets/49793609/f1535168-10c3-4275-b197-1f88ae4eadfd)

2024-03-14 20:36 UTC, ST-DDT approved these changes

2024-03-14 20:38 UTC, ST-DDT commented
> Apologies, instead of pushing to a new branch I pushed to the old...

No problem. We are just waiting for a review from @matthewmayer, and then this can be merged.

2024-03-14 23:34 UTC, matthewmayer approved these changes

2024-03-15 07:48 UTC, Shinigami92 approved these changes

2024-03-15 09:48 UTC, merged