refactor(company)!: remove v8 deprecated company methods
faker-js/faker pull request #2726
Opened 2024-03-08 22:51 UTC by Shinigami92

2024-03-09 02:10 UTC, ST-DDT approved these changes, later dismissed

2024-03-09 02:56 UTC, matthewmayer requested changes

2024-03-09 02:56 UTC, matthewmayer commented on docs/guide/upgrading_v9/2726.md
> +| `faker.company.companySuffix` | `faker.company.name`          |
these are not really direct replacements. Maybe write "Part of `faker.company.name` instead?

2024-03-09 08:50 UTC, ST-DDT approved these changes

2024-03-09 09:55 UTC, matthewmayer approved these changes

2024-03-09 23:45 UTC, xDivisionByZerox requested changes

2024-03-09 23:45 UTC, xDivisionByZerox commented on docs/guide/upgrading_v9/2726.md
This file is missing the access to the definitions property: `faker.definitions.company.suffixes` or `faker.rawDefinitions.company.suffixes`.

2024-03-09 23:45 UTC, xDivisionByZerox commented on src/definitions/company.ts
> -  suffix: string[];
According locale files should be removed.

2024-03-10 00:29 UTC, ST-DDT commented on src/definitions/company.ts
> -  suffix: string[];
They are still used in the company name patterns and will be renamed to [`legal_entity_type`](https://github.com/faker-js/faker/issues/1574) (eventually).

2024-03-10 00:52 UTC, xDivisionByZerox commented on src/definitions/company.ts
> -  suffix: string[];
Simply renaming will not work, as a lot of these files contain the value `null` (not applicable). Without having thoroughly checked this, I can't believe that this will be the actual value ending up in the file for all these locales.

2024-03-10 02:57 UTC, matthewmayer commented on docs/guide/upgrading_v9/2726.md
i dont think we should encourage accessing the definitions directly, that is prone to breaking, and that definition is likely to get renamed soon anyway https://github.com/faker-js/faker/issues/1574

2024-03-12 10:30 UTC, xDivisionByZerox commented on docs/guide/upgrading_v9/2726.md
Then please explain to me why the following PRs were/are considered breaking and (should) have listed the changes of definition files in their migration guide?

- #2476
- #2505

2024-03-12 13:16 UTC, matthewmayer commented on docs/guide/upgrading_v9/2726.md
In an ideal world, consumers would only be using public methods. Using raw definitions is a bit hacky and prone to breaking. So if we remove a public method for say "company suffix", if someone is migrating code that uses this, it would be probably better for them to just hardcode it as say `faker.helpers.arrayElement(['Inc', 'and Sons', 'LLC', 'Group'])` than introduce hacky code which relies on the raw definitions.

By contrast if you had code affected by #2476, #2505, #2033 then you were *already* using the hacky raw definitions, so we're not making your code worse by helping you migrate to the new locations of the definitions.

That said I'd be happy to omit some of these "definition only" migration guide snippets or just make them extremely brief.

2024-03-12 13:41 UTC, ST-DDT commented on docs/guide/upgrading_v9/2726.md
I think the main difference here is that the data weren't changed/moved.
We dropped support for having a method to access the data, but the data remain unchanged.
Maybe we should rename the method/data directly instead of removing the method and potentially adding it back with #1574 ? IMO we should not suggest the user to access the raw definitions here. 🤔 

- #1574

2024-03-12 14:05 UTC, matthewmayer commented on docs/guide/upgrading_v9/2726.md
> I think the main difference here is that the data weren't changed/moved.
> 
> We dropped support for having a method to access the data, but the data remain unchanged.
> 
> Maybe we should rename the method/data directly instead of removing the method and potentially adding it back with #1574 ? IMO we should not suggest the user to access the raw definitions here. 🤔 
> 
> 
> 
> - #1574 

If we think there's a need for company.legalEntityType() we could expose that yes. I'm not really sure why you'd want to use it in its own though.

2024-03-12 14:10 UTC, xDivisionByZerox commented on docs/guide/upgrading_v9/2726.md
Alright, sorry for my confusion. I thought that by removing the property from the definitions type, our build script would omit these files. That's my bad. This comment can be resolved.

2024-03-12 14:10 UTC, xDivisionByZerox approved these changes

2024-03-12 14:46 UTC, merged