refactor(helpers)!: remove v8 deprecated helpers methods
faker-js/faker pull request #2729
Opened 2024-03-10 09:27 UTC by Shinigami92

2024-03-10 10:51 UTC, ST-DDT submitted a review, later dismissed

2024-03-10 12:12 UTC, matthewmayer requested changes

2024-03-10 12:12 UTC, matthewmayer commented on docs/guide/upgrading_v9/2729.md
> +| `faker.helpers.regexpStyleStringParse`  | `faker.helpers.fromRegExp`                                     |
as this is not an exact replacement i think we should link back to https://v8.fakerjs.dev/guide/upgrading.html#faker-helpers-regexpstylestringparse-deprecated-in-favor-of-faker-helpers-fromregexp or repeat the explanation from there

2024-03-10 12:12 UTC, matthewmayer commented on docs/guide/upgrading_v9/2729.md
> +| `faker.helpers.replaceSymbolWithNumber` | `string.replace(/#+/g, (m) => faker.string.numeric(m.length))` |
similarly as this is not an exact replacement i think we should give a longer explanation that handles the ! case as well as the #

2024-03-10 14:35 UTC, Shinigami92 commented on docs/guide/upgrading_v9/2729.md
> +| `faker.helpers.replaceSymbolWithNumber` | `string.replace(/#+/g, (m) => faker.string.numeric(m.length))` |
can you please take this over and edit with your change requests?

2024-03-11 01:10 UTC, matthewmayer commented on docs/guide/upgrading_v9/2729.md
> +| `faker.helpers.replaceSymbolWithNumber` | `string.replace(/#+/g, (m) => faker.string.numeric(m.length))` |
done

2024-03-11 01:10 UTC, matthewmayer commented on docs/guide/upgrading_v9/2729.md
> +| `faker.helpers.regexpStyleStringParse`  | `faker.helpers.fromRegExp`                                     |
done

2024-03-11 10:06 UTC, ST-DDT approved these changes

2024-03-12 13:30 UTC, matthewmayer approved these changes

2024-03-13 12:28 UTC, merged