chore: fix JSDoc comments in vehicle.ts
faker-js/faker pull request #274
Opened 2022-01-23 21:14 UTC by pkuczynski

2022-01-23 21:37 UTC, prisis commented on src/vehicle.ts
> +   * Returns a random vehicle.
Can we use [https://jsdoc.app/tags-example.html](https://jsdoc.app/tags-example.html) and move the sampleResults to it?

2022-01-23 22:08 UTC, pkuczynski commented on src/vehicle.ts
> +   * Returns a random vehicle.
I was wondering if that makes sense? I can update the PR. Let me know if I should?

2022-01-23 22:40 UTC, prisis commented on src/vehicle.ts
> +   * Returns a random vehicle.
I think it's easier to see what it will return :) for new developer, lets wait what the other maintainer will say

2022-01-24 04:36 UTC, Shinigami92 commented on src/vehicle.ts
> +   * Returns a random vehicle.
This is a really good idea 👍

2022-01-24 16:26 UTC, Shinigami92 commented
Suggested edit:
```diff
diff --git a/src/vehicle.ts b/src/vehicle.ts
--- src/vehicle.ts
+++ src/vehicle.ts
@@ -13,112 +13,61 @@
         continue;
       }
       this[name] = this[name].bind(this);
     }
-
-    // TODO @Shinigami92 2022-01-13: Find better strategy
-    // @ts-expect-error
-    this.vehicle.schema = {
-      description: 'Generates a random vehicle.',
-      sampleResults: ['BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'],
-    };
-    // @ts-expect-error
-    this.manufacturer.schema = {
-      description: 'Generates a manufacturer name.',
-      sampleResults: ['Ford', 'Jeep', 'Tesla'],
-    };
-    // @ts-expect-error
-    this.model.schema = {
-      description: 'Generates a vehicle model.',
-      sampleResults: ['Explorer', 'Camry', 'Ranchero'],
-    };
-    // @ts-expect-error
-    this.type.schema = {
-      description: 'Generates a vehicle type.',
-      sampleResults: ['Coupe', 'Convertable', 'Sedan', 'SUV'],
-    };
-    // @ts-expect-error
-    this.fuel.schema = {
-      description: 'Generates a fuel type.',
-      sampleResults: ['Electric', 'Gasoline', 'Diesel'],
-    };
-    // @ts-expect-error
-    this.vin.schema = {
-      description: 'Generates a valid VIN number.',
-      sampleResults: ['YV1MH682762184654', '3C7WRMBJ2EG208836'],
-    };
-    // @ts-expect-error
-    this.color.schema = {
-      description: 'Generates a color',
-      sampleResults: ['red', 'white', 'black'],
-    };
-    // @ts-expect-error
-    this.vrm.schema = {
-      description: 'Generates a vehicle vrm',
-      sampleResults: ['MF56UPA', 'GL19AAQ', 'SF20TTA'],
-    };
-    // @ts-expect-error
-    this.bicycle.schema = {
-      description: 'Generates a type of bicycle',
-      sampleResults: [
-        'Adventure Road Bicycle',
-        'City Bicycle',
-        'Recumbent Bicycle',
-      ],
-    };
   }
 
   /**
-   * vehicle
+   * Returns a random vehicle.
    *
-   * @method faker.vehicle.vehicle
+   * @example 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
    */
   vehicle(): string {
     return fake('{{vehicle.manufacturer}} {{vehicle.model}}');
   }
 
   /**
-   * manufacturer
+   * Returns a manufacturer name.
    *
-   * @method faker.vehicle.manufacturer
+   * @example 'Ford', 'Jeep', 'Tesla'
    */
   manufacturer(): string {
     return this.faker.random.arrayElement(
       this.faker.definitions.vehicle.manufacturer
     );
   }
 
   /**
-   * model
+   * Returns a vehicle model.
    *
-   * @method faker.vehicle.model
+   * @example 'Explorer', 'Camry', 'Ranchero'
    */
   model(): string {
     return this.faker.random.arrayElement(this.faker.definitions.vehicle.model);
   }
 
   /**
-   * type
+   * Returns a vehicle type.
    *
-   * @method faker.vehicle.type
+   * @example 'Coupe', 'Convertable', 'Sedan', 'SUV'
    */
   type(): string {
     return this.faker.random.arrayElement(this.faker.definitions.vehicle.type);
   }
 
   /**
-   * fuel
+   * Returns a fuel type.
    *
-   * @method faker.vehicle.fuel
+   * @example 'Electric', 'Gasoline', 'Diesel'
    */
   fuel(): string {
     return this.faker.random.arrayElement(this.faker.definitions.vehicle.fuel);
   }
 
   /**
-   * vin
+   * Returns a valid VIN number.
    *
-   * @method faker.vehicle.vin
+   * @example 'YV1MH682762184654', '3C7WRMBJ2EG208836'
    */
   vin(): string {
     const bannedChars = ['o', 'i', 'q'];
     return (
@@ -134,20 +83,20 @@
       .toUpperCase();
   }
 
   /**
-   * color
+   * Returns a vehicle color.
    *
-   * @method faker.vehicle.color
+   * @example 'red', 'white', 'black'
    */
   color(): string {
     return fake('{{commerce.color}}');
   }
 
   /**
-   * vrm
+   * Returns a vehicle vrm.
    *
-   * @method faker.vehicle.vrm
+   * @example 'MF56UPA', 'GL19AAQ', 'SF20TTA'
    */
   vrm(): string {
     return (
       this.faker.random.alpha({ count: 2, upcase: true }) +
@@ -157,11 +106,11 @@
     ).toUpperCase();
   }
 
   /**
-   * bicycle
+   * Returns a type of bicycle.
    *
-   * @method faker.vehicle.bicycle
+   * @example 'Adventure Road Bicycle', 'City Bicycle', 'Recumbent Bicycle'
    */
   bicycle(): string {
     return this.faker.random.arrayElement(
       this.faker.definitions.vehicle.bicycle_type

```

2022-01-24 16:26 UTC, Shinigami92 commented
Suggested edit:
```diff
diff --git a/src/vehicle.ts b/src/vehicle.ts
--- src/vehicle.ts
+++ src/vehicle.ts
@@ -13,112 +13,61 @@
         continue;
       }
       this[name] = this[name].bind(this);
     }
-
-    // TODO @Shinigami92 2022-01-13: Find better strategy
-    // @ts-expect-error
-    this.vehicle.schema = {
-      description: 'Generates a random vehicle.',
-      sampleResults: ['BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'],
-    };
-    // @ts-expect-error
-    this.manufacturer.schema = {
-      description: 'Generates a manufacturer name.',
-      sampleResults: ['Ford', 'Jeep', 'Tesla'],
-    };
-    // @ts-expect-error
-    this.model.schema = {
-      description: 'Generates a vehicle model.',
-      sampleResults: ['Explorer', 'Camry', 'Ranchero'],
-    };
-    // @ts-expect-error
-    this.type.schema = {
-      description: 'Generates a vehicle type.',
-      sampleResults: ['Coupe', 'Convertable', 'Sedan', 'SUV'],
-    };
-    // @ts-expect-error
-    this.fuel.schema = {
-      description: 'Generates a fuel type.',
-      sampleResults: ['Electric', 'Gasoline', 'Diesel'],
-    };
-    // @ts-expect-error
-    this.vin.schema = {
-      description: 'Generates a valid VIN number.',
-      sampleResults: ['YV1MH682762184654', '3C7WRMBJ2EG208836'],
-    };
-    // @ts-expect-error
-    this.color.schema = {
-      description: 'Generates a color',
-      sampleResults: ['red', 'white', 'black'],
-    };
-    // @ts-expect-error
-    this.vrm.schema = {
-      description: 'Generates a vehicle vrm',
-      sampleResults: ['MF56UPA', 'GL19AAQ', 'SF20TTA'],
-    };
-    // @ts-expect-error
-    this.bicycle.schema = {
-      description: 'Generates a type of bicycle',
-      sampleResults: [
-        'Adventure Road Bicycle',
-        'City Bicycle',
-        'Recumbent Bicycle',
-      ],
-    };
   }
 
   /**
-   * vehicle
+   * Returns a random vehicle.
    *
-   * @method faker.vehicle.vehicle
+   * @example 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
    */
   vehicle(): string {
     return fake('{{vehicle.manufacturer}} {{vehicle.model}}');
   }
 
   /**
-   * manufacturer
+   * Returns a manufacturer name.
    *
-   * @method faker.vehicle.manufacturer
+   * @example 'Ford', 'Jeep', 'Tesla'
    */
   manufacturer(): string {
     return this.faker.random.arrayElement(
       this.faker.definitions.vehicle.manufacturer
     );
   }
 
   /**
-   * model
+   * Returns a vehicle model.
    *
-   * @method faker.vehicle.model
+   * @example 'Explorer', 'Camry', 'Ranchero'
    */
   model(): string {
     return this.faker.random.arrayElement(this.faker.definitions.vehicle.model);
   }
 
   /**
-   * type
+   * Returns a vehicle type.
    *
-   * @method faker.vehicle.type
+   * @example 'Coupe', 'Convertable', 'Sedan', 'SUV'
    */
   type(): string {
     return this.faker.random.arrayElement(this.faker.definitions.vehicle.type);
   }
 
   /**
-   * fuel
+   * Returns a fuel type.
    *
-   * @method faker.vehicle.fuel
+   * @example 'Electric', 'Gasoline', 'Diesel'
    */
   fuel(): string {
     return this.faker.random.arrayElement(this.faker.definitions.vehicle.fuel);
   }
 
   /**
-   * vin
+   * Returns a valid VIN number.
    *
-   * @method faker.vehicle.vin
+   * @example 'YV1MH682762184654', '3C7WRMBJ2EG208836'
    */
   vin(): string {
     const bannedChars = ['o', 'i', 'q'];
     return (
@@ -134,20 +83,20 @@
       .toUpperCase();
   }
 
   /**
-   * color
+   * Returns a vehicle color.
    *
-   * @method faker.vehicle.color
+   * @example 'red', 'white', 'black'
    */
   color(): string {
     return fake('{{commerce.color}}');
   }
 
   /**
-   * vrm
+   * Returns a vehicle vrm.
    *
-   * @method faker.vehicle.vrm
+   * @example 'MF56UPA', 'GL19AAQ', 'SF20TTA'
    */
   vrm(): string {
     return (
       this.faker.random.alpha({ count: 2, upcase: true }) +
@@ -157,11 +106,11 @@
     ).toUpperCase();
   }
 
   /**
-   * bicycle
+   * Returns a type of bicycle.
    *
-   * @method faker.vehicle.bicycle
+   * @example 'Adventure Road Bicycle', 'City Bicycle', 'Recumbent Bicycle'
    */
   bicycle(): string {
     return this.faker.random.arrayElement(
       this.faker.definitions.vehicle.bicycle_type

```

2022-01-24 16:27 UTC, Shinigami92 requested changes

2022-01-24 16:27 UTC, Shinigami92 commented on src/vehicle.ts
> +   * @returns {string}
Please remove all `@returns` due to TS already provide this out of the box

2022-01-24 16:27 UTC, Shinigami92 commented on src/vehicle.ts
> +   * 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
Please reformat these to

```suggestion
   * @example 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
```

2022-01-24 17:07 UTC, pkuczynski commented on src/vehicle.ts
> +   * 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
Done

2022-01-24 17:07 UTC, pkuczynski commented on src/vehicle.ts
> +   * @returns {string}
Done

2022-01-24 17:14 UTC, Shinigami92 approved these changes

2022-01-24 17:51 UTC, prisis commented on src/vehicle.ts
> +   * @example 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
Im relay to say it but you need to change the examples... see https://stackoverflow.com/questions/2961310/jsdoc-adding-real-code-in-documentation

the correct example would be

@example
// returns 'BMW Explorer'
faker.vehicle.vehicle()
// returns 'Ford Camry'
faker.vehicle.vehicle()

2022-01-24 18:41 UTC, pkuczynski commented on src/vehicle.ts
> +   * @example 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
I am not sure which tool are you planning to use to generate the docs, so I only tested in WebStorm IDE:

1. My original version

```
@example
'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
```

<img width="454" alt="Screenshot 2022-01-24 at 19 35 45" src="https://user-images.githubusercontent.com/374864/150843369-859151f3-b57e-4847-b95c-c21b905cc500.png">


2. After a suggestion from @Shinigami92 

```
@example 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
```

<img width="439" alt="Screenshot 2022-01-24 at 19 36 00" src="https://user-images.githubusercontent.com/374864/150843390-73141bac-863e-4f50-91d4-54f64907d6e1.png">

3. 

```
@example
faker.vehicle.vehicle() // 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
```

<img width="664" alt="Screenshot 2022-01-24 at 19 35 25" src="https://user-images.githubusercontent.com/374864/150843408-a584b708-ca66-48d3-90ad-e67456330a99.png">


4.

```
@example
// returns 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
faker.vehicle.vehicle()
```

<img width="537" alt="Screenshot 2022-01-24 at 19 35 07" src="https://user-images.githubusercontent.com/374864/150843422-3dab7fd3-9022-477a-b50f-2e6caf32eb98.png">

5. Version from @prisis 

```
@example
// returns 'BMW Explorer'
faker.vehicle.vehicle()

// returns 'Ford Camry'
faker.vehicle.vehicle()

// returns 'Lamborghini Ranchero'
faker.vehicle.vehicle()
```

<img width="332" alt="Screenshot 2022-01-24 at 19 39 20" src="https://user-images.githubusercontent.com/374864/150843774-2abd2fcc-b9e0-4f4d-b25b-0bc98fa54067.png">

So guys, could you please decide on the final format and I will then follow this suggestion?

For me the word `returns` is a bit obsolete... But also having 3 almost identical examples seems to much...

2022-01-24 18:53 UTC, Shinigami92 commented on src/vehicle.ts
> +   * @example 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
For the `@example` in VSCode it produce the same output, so use whats better for WebStorm :+1:

2022-01-24 18:56 UTC, pkuczynski commented on src/vehicle.ts
> +   * @example 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
For me 3. or 5. makes most sense but only with one example

2022-01-24 22:34 UTC, prisis commented on src/vehicle.ts
> +   * @example 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
I like 3 :D it looks good in phpstorm too

2022-01-24 23:16 UTC, pkuczynski commented on src/vehicle.ts
> +   * @example 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
One more version, which is my ultimate preference as it nicely colors strings

6. 

```
@example
faker.vehicle.vehicle()
'BMW Explorer'
```

<img width="312" alt="Screenshot 2022-01-25 at 00 14 57" src="https://user-images.githubusercontent.com/374864/150880949-026e652e-aa5f-4e3b-b405-78312feafb5b.png">

2022-01-24 23:21 UTC, pkuczynski commented on src/vehicle.ts
> +   * @example 'BMW Explorer', 'Ford Camry', 'Lamborghini Ranchero'
I changed it to 3. to get it merged faster...

2022-01-25 08:30 UTC, prisis commented on src/vehicle.ts
> +   * @example 'Explorer', 'Camry', 'Ranchero'
Did you forget this line?

2022-01-25 15:20 UTC, pkuczynski commented on src/vehicle.ts
> +   * @example 'Explorer', 'Camry', 'Ranchero'
good catch! thanks!

2022-01-25 15:43 UTC, Shinigami92 submitted a review, later dismissed

2022-01-25 15:50 UTC, ST-DDT requested changes
Looks good to me. Just some minor nit picking for non native Americans.

2022-01-25 15:50 UTC, ST-DDT commented on src/vehicle.ts
> +   * Returns a valid VIN number.
Maybe explain what a `VIN` is. Maybe like this `Vehicle Identification Number (VIN)`?

2022-01-25 15:50 UTC, ST-DDT commented on src/vehicle.ts
> +   * Returns a vehicle vrm.
Maybe explain what a VRM is. Is it a vehicle license plate?

2022-01-25 19:43 UTC, pkuczynski commented on src/vehicle.ts
> +   * Returns a valid VIN number.
VIN is international I think?. Added desc, please check again.

2022-01-25 19:44 UTC, pkuczynski commented on src/vehicle.ts
> +   * Returns a vehicle vrm.
Yes! Vehicle Registration Mark. Desc added.

2022-01-25 19:57 UTC, ST-DDT approved these changes

2022-01-25 21:15 UTC, Shinigami92 approved these changes

2022-01-25 21:16 UTC, merged