docs: improve contributing guide
faker-js/faker pull request #2747
Opened 2024-03-13 22:54 UTC by ST-DDT

Created after reading our contribution guide again for https://github.com/faker-js/faker/discussions/2746

- https://github.com/faker-js/faker/discussions/2746

2024-03-13 23:16 UTC, xDivisionByZerox commented on CONTRIBUTING.md
> +- Bug fixes or locale changes don't need an issue.
While I agree on locale changes not requiring an issue necessarily, I don't think the same should go for bugs. Having an issue with reproduction steps (as written in the next point) is super valuable. Additionally, there should be a verification whether said bug is actually a bug and not the code working as expected. Lastly, an issue can better track acceptance criteria on the expected behaviour of the code as it doesn't (always) have to bother with actual implementation details.

2024-03-13 23:33 UTC, ST-DDT commented on CONTRIBUTING.md
> +- Bug fixes or locale changes don't need an issue.
https://github.com/faker-js/faker/pull/2747/files#r1524020421

> While I agree on locale changes not requiring an issue necessarily, I don't think the same should go for bugs. Having an issue with reproduction steps (as written in the next point) is super valuable.
> Additionally, there should be a verification whether said bug is actually a bug and not the code working as expected. This can prevent situations were someone might say "it does(n't) work on my machine".
> Lastly, an issue can better track acceptance criteria on the expected behaviour of the code as it doesn't (always) have to bother with actual implementation details.

Like this?

```suggestion
- If you would like to fix a bug or propose a new feature, create an issue first.
- Locale changes don't need an issue.
```

2024-03-14 02:14 UTC, matthewmayer requested changes

2024-03-14 02:14 UTC, matthewmayer commented on CONTRIBUTING.md
> +- If you would like to propose a new feature, create an issue first.
maybe worth mentioning here that we usually wait until an issue for a new feature has some upvotes before starting development work on it?

2024-03-14 02:20 UTC, matthewmayer commented on CONTRIBUTING.md
> +- Bug fixes or locale changes don't need an issue.
Maybe we could rewrite it slightly more like:

* It's generally helpful to create an issue first:
  - if you are proposing a new feature, this allows other users to "upvote" the issue. Once an issue has enough upvotes (usually 10+) it will be reviewed for development.
  - if you notice a bug, this allows you to provide steps to reproduce, and allows other users to confirm this is actually a bug
  - it's not required to create an issue in all cases. For example for fixing a typo in documentation, or adding some new data for a locale, you could immediately create a pull request without an issue.

2024-03-15 00:07 UTC, matthewmayer requested changes

2024-03-15 00:07 UTC, matthewmayer commented on CONTRIBUTING.md
> +It's generally helpful to create an issue first:
Could "create an issue" be hyperlinked to the create issue page on GitHub?

2024-03-15 15:10 UTC, matthewmayer approved these changes

2024-03-15 15:51 UTC, Shinigami92 approved these changes

2024-03-16 00:57 UTC, xDivisionByZerox approved these changes

2024-03-16 00:58 UTC, merged