refactor(date): birthday improvements
faker-js/faker pull request #2756
Opened 2024-03-15 21:14 UTC by ST-DDT

I found this branch lying around.

- Slightly simplifies the methods implementation/bringing it closer to our standard.
- Tries to improve the error message if min > max
- Adds some additional tests

I'm unsure about the contents of the error message:

- `Max age 25 (599616000000) should be greater than or equal to min age 31 (757382400000).`
- `Max year 1990 (662515200000) should be greater than or equal to min year 2000 (946771200000).`

The value in the parenthesis is the epoch timestamp.
Should we remove it?

- `Max age 25 should be greater than or equal to min age 31.`
- `Max year 1990 should be greater than or equal to min year 2000.`

What if min or max is undefined?

- `Max age 25 should be greater than or equal to min age undefined.`
- `Max year undefined should be greater than or equal to min year 2000.`

We could omit/remove the check if the additional checks from #2719 is merged.

- #2719

2024-03-16 07:44 UTC, Shinigami92 reviewed
If we want these epoch numbers in error message, we might need to add info about that to the message itself

2024-03-16 07:44 UTC, Shinigami92 commented on test/modules/date.spec.ts
> +          expect(birthdate.toISOString()).not.toMatch(/T00:00:00.000Z/);
I dont understand this `expect` 🤔

2024-03-16 07:51 UTC, ST-DDT commented on test/modules/date.spec.ts
> +          expect(birthdate.toISOString()).not.toMatch(/T00:00:00.000Z/);
A previous version of the method returned always midnight.
This isnt a new test it just got moved a bit.

2024-03-16 07:51 UTC, matthewmayer commented
Min and max have defaults (15 and 80) so you should be allowed to omit one or the other?

2024-03-16 07:53 UTC, ST-DDT commented
> Min and max have defaults (15 and 80) so you should be allowed to omit one or the other?

As long as you dont violate the other default. Yes.

2024-03-16 07:58 UTC, matthewmayer commented
So I would expect
`faker.date.birthdate({max:25})` to work (18-25)
`faker.date.birthdate({max:15})` to throw `Max age 15 should be greater than or equal to min age 18.`

2024-03-16 08:01 UTC, Shinigami92 commented on test/modules/date.spec.ts
> +          expect(birthdate.toISOString()).not.toMatch(/T00:00:00.000Z/);
But it is a possible value? (even when really uncommon)

2024-03-16 08:03 UTC, ST-DDT commented
> So I would expect `faker.date.birthdate({max:25})` to work (18-25) `faker.date.birthdate({max:15})` to throw `Max age 15 should be greater than or equal to min age 18.`

And that would work, if it wasnt for the year mode.
Should I throw two different errors based on mode?

2024-03-16 08:08 UTC, ST-DDT commented on test/modules/date.spec.ts
> +          expect(birthdate.toISOString()).not.toMatch(/T00:00:00.000Z/);
Yes, it theoretically is possible.

2024-03-16 08:11 UTC, Shinigami92 commented on test/modules/date.spec.ts
> +          expect(birthdate.toISOString()).not.toMatch(/T00:00:00.000Z/);
Then I suggest to rewrite or add a test, so that specific case is covered.
E.g. like we did with some other methods in a for-loop or (something like that) and then `expect` that it also generates not only 0-values.

2024-03-16 08:18 UTC, matthewmayer commented
I generally think the more specific the error the better.

2024-03-16 08:22 UTC, matthewmayer commented
Looking at this again in the current docs, it's really weird that the default mode is year and yet the default for min and max are ages.

2024-03-16 16:44 UTC, ST-DDT commented
> Looking at this again in the current docs, it's really weird that the default mode is year and yet the default for min and max are ages.

Should we change that as well?

2024-03-16 16:47 UTC, ST-DDT commented on test/modules/date.spec.ts
> +          expect(birthdate.toISOString()).not.toMatch(/T00:00:00.000Z/);
I removed the test as the intention of the test cannot easily be derived just from looking at it.

2024-03-16 16:57 UTC, matthewmayer commented
I feel age mode is much more useful. Year mode isn't really much different to between()

2024-03-16 17:43 UTC, matthewmayer commented
Perhaps to help upgrades we should log a warning if you don't specify mode and min/max are say >1000 (because then you surely meant years not ages).

2024-03-17 01:06 UTC, ST-DDT commented
> Perhaps to help upgrades we should log a warning if you don't specify mode and min/max are say >1000 (because then you surely meant years not ages).

I added a check.

But I'm considering making min/max/mode all required if present.

````ts
birthdate(
    options: {
      /**
       * The date to use as reference point for the newly generated date.
       *
       * @default faker.defaultRefDate()
       */
      refDate?: string | Date | number;
    } | {
      /**
       * The minimum age or year to generate a birthdate.
       */
      min: number;
      /**
       * The maximum age or year to generate a birthdate.
       */
      max: number;
      /**
       * The mode to generate the birthdate. Supported modes are `'age'` and `'year'` .
       *
       * There are two modes available `'age'` and `'year'`:
       * - `'age'`: The min and max options define the age of the person (e.g. `18` - `42`).
       * - `'year'`: The min and max options define the range the birthdate may be in (e.g. `1900` - `2000`).
       */
      mode: 'age' | 'year';
      /**
       * The date to use as reference point for the newly generated date.
       *
       * @default faker.defaultRefDate()
       */
      refDate?: string | Date | number;
    } = {}
  ): Date
````

2024-03-17 04:00 UTC, matthewmayer commented
I think that's better.

2024-03-17 09:28 UTC, Shinigami92 commented
I assume that discriminated options based on mode would be overkill to just separate the docs?

```ts
... | {
      /**
       * The minimum age to generate a birthdate.
       */
      min: number;
      /**
       * The maximum age to generate a birthdate.
       */
      max: number;
      mode: 'age';
    } | {
      /**
       * The minimum year to generate a birthdate.
       */
      min: number;
      /**
       * The maximum year to generate a birthdate.
       */
      max: number;
      mode: 'year';
...
```

---

Does it make a difference for the tooltip and/or Vitepress docs if the `mode` is above the `min` and `max`?

2024-03-17 10:05 UTC, ST-DDT commented
This might cause issues with the apidocs as the param name is no longer unique and has a different description.

With the potential new apidocs generation, we could go for different signatures though as a future improvement.

2024-03-18 01:05 UTC, matthewmayer requested changes

2024-03-18 01:05 UTC, matthewmayer commented on src/modules/date/index.ts
> +        until: '10.0',
does this need an `until`? Seems this check would need to be permanent?

Could just have a custom error like `You must provide all of the min, max and mode parameters`.

2024-03-18 01:09 UTC, matthewmayer commented on src/modules/date/index.ts
> +        until: '10.0',
i guess this is currently a warning not an error. I think an error might be better (even though its theoretically "more" breaking) given the currnet behavior is quite unintuitiuve.

2024-03-19 07:49 UTC, Shinigami92 commented
I would like to discuss in a meeting if we want to change the default `mode` and if `age > 1000` might be allowed for an ancient Dungeons&Dragons Dragon 🐉 

Also I will re-evaluate this PR when it was rebased in the changes of #2757, so there is ensured no diff/conflict.

2024-03-19 10:44 UTC, ST-DDT commented
> to change the default `mode`

We removed the default.

> if `age > 1000` might be allowed for an ancient Dungeons&Dragons Dragon 🐉

It is allowed. We currently just require the user to fully state what they want instead of defaulting half the values to some value hoping to fix the input to something that can be generated.

2024-03-19 10:48 UTC, Shinigami92 commented
> > to change the default `mode`
> 
> 
> 
> We removed the default.
> 
> 
> 
> > if `age > 1000` might be allowed for an ancient Dungeons&Dragons Dragon 🐉
> 
> 
> 
> It is allowed. We currently just require the user to fully state what they want instead of defaulting half the values to some value hoping to fix the input to something that can be generated and makes sense.

Ah that's good, I was not up to date. But yeah for this case I also think it is better to force request a mode instead of falling back to a default and produce unexpected behavior.

2024-03-19 11:18 UTC, ST-DDT commented on src/modules/date/index.ts
> +        until: '10.0',
This is only for the migration period, after that JS users get default values at most and have to read the docs.

I might switch to an error for the migration period. Not sure about that yet.

2024-03-21 17:13 UTC, xDivisionByZerox commented
**Team Decision**:

We will implwment this method by using multiple designated signatures. Where each mode is one signature with its own default values for min and max.

---

Blocked until #2628 + follow up is merged, to verify that we can display multiple signatures in a satisfying way.

2024-03-24 15:14 UTC, ST-DDT commented
> We will implement this method by using multiple designated signatures. Where each mode is one signature with its own default values for min and max.

Done

> Blocked until #2628 + follow up is merged, to verify that we can display multiple signatures in a satisfying way.

I also added/kept the merged signature, so theoretically we could merge this independently of #2628

2024-03-24 17:43 UTC, Shinigami92 commented on src/modules/date/index.ts
> +    if (optionsSet % 3 !== 0) {
I think this can be simplified using `[].some` or similar

(Send from phone)

2024-03-24 17:51 UTC, ST-DDT commented on src/modules/date/index.ts
> +    if (optionsSet % 3 !== 0) {
Unfortunately not. It is basically: `!(all || none)` != `some`

2024-03-24 18:02 UTC, Shinigami92 commented on src/modules/date/index.ts
> +    if (optionsSet % 3 !== 0) {
🤯

2024-03-24 18:05 UTC, Shinigami92 commented
Potentially approved, currently don't have a bigger screen

2024-03-26 10:44 UTC, Shinigami92 commented on src/modules/date/index.ts
>        mode?: 'age' | 'year';
To align with the other signatures, I suggest to move this over the min,max
(inline suggestion not possible 🙁)

2024-03-27 10:34 UTC, Shinigami92 approved these changes, later dismissed

2024-03-28 08:59 UTC, import-brain approved these changes, later dismissed

2024-03-28 13:04 UTC, matthewmayer commented
Can we see the updated docs in a netlify preview? The defaults still seem a bit confusing.

2024-03-28 13:16 UTC, ST-DDT commented
> Can we see the updated docs in a netlify preview?

Updated

> The defaults still seem a bit confusing.

What do you refer to?

2024-03-28 14:21 UTC, matthewmayer commented
Looking at https://deploy-preview-2756.fakerjs.dev/api/date.html#birthdate

- "Returns a random birthdate in the given range of years." doesn't seem ideal. I think we should explain both possible modes here?

- it's not obvious what the default are if you don't pass options object. 

- max says "The maximum year to generate a birthdate in." Shouldn't that be "year or age"?

- maybe reorder the parameters mode,min,max,refDate

2024-03-28 14:51 UTC, ST-DDT commented
> * "Returns a random birthdate in the given range of years." doesn't seem ideal. I think we should explain both possible modes here?
> 
> * it's not obvious what the default are if you don't pass options object.
> 
> * max says "The maximum year to generate a birthdate in." Shouldn't that be "year or age"?

I think I might have forgotten to adjust the description after creating the merged signature.



> * maybe reorder the parameters mode,min,max,refDate

They are sorted alphabetically (per type in the union), I will not change it in the old generation, if we replace it soon anyway.

2024-03-29 07:50 UTC, matthewmayer commented
Why does the code for mode year need to use the refDate? It seems that should only be needed for age?

2024-03-29 19:31 UTC, ST-DDT commented
> Why does the code for mode year need to use the refDate? It seems that should only be needed for age?

Fixed. Ready for review.

2024-03-29 21:28 UTC, Shinigami92 commented on test/modules/date.spec.ts
>          .it('with year and refDate', {
Is the test wrong here? 🧐🤨

2024-03-29 23:34 UTC, ST-DDT commented on test/modules/date.spec.ts
>          .it('with year and refDate', {
Yes, in multiple ways. Fixed.

2024-03-30 03:06 UTC, matthewmayer requested changes

2024-03-30 03:06 UTC, matthewmayer commented on src/modules/date/index.ts
> +   * @param options.refDate The date to use as reference point for the newly generated date. Defaults to `faker.defaultRefDate()`.
should we mention this is only used in 'age' mode?

2024-03-30 03:06 UTC, matthewmayer commented on src/modules/date/index.ts
> +        const to = new Date(Date.UTC(0, 11, 30)).setUTCFullYear(max);
can't we just do:
```js
const { min , max } = options;
const from = new Date(Date.UTC(0, 0, 2)).setUTCFullYear(min);
const to = new Date(Date.UTC(0, 11, 30)).setUTCFullYear(max);
```

2024-03-30 08:06 UTC, ST-DDT commented on src/modules/date/index.ts
> +   * @param options.refDate The date to use as reference point for the newly generated date. Defaults to `faker.defaultRefDate()`.
IMO that is not neccesary. The year specific signature does not have a refDate option in the signature.
And this signature actually uses the value.

2024-03-30 08:07 UTC, ST-DDT commented on src/modules/date/index.ts
> +        const to = new Date(Date.UTC(0, 11, 30)).setUTCFullYear(max);
You mean without the defaults?
Theoretically yes, but it is currently required for backwards compatibility for JS users.

2024-03-30 08:51 UTC, matthewmayer commented on src/modules/date/index.ts
> +        const to = new Date(Date.UTC(0, 11, 30)).setUTCFullYear(max);
what code in JS would still need the old defaults now that we're throwing an error unless we get 0 or 3 of {min, max, mode} passed?

2024-03-30 08:53 UTC, matthewmayer commented on src/modules/date/index.ts
> +   * @param options.refDate The date to use as reference point for the newly generated date. Defaults to `faker.defaultRefDate()`.
it would be nice for that to appear on the web docs though.

i just noticed refDate now appears twice in the generated docs:

https://deploy-preview-2756.fakerjs.dev/api/date.html#birthdate

<img width="731" alt="image" src="https://github.com/faker-js/faker/assets/152770/d7eddc3e-d11d-40f3-8948-0245082748ae">

2024-03-30 17:02 UTC, ST-DDT commented on src/modules/date/index.ts
> +        const to = new Date(Date.UTC(0, 11, 30)).setUTCFullYear(max);
Good point, but due to the signature, it shows min and max as potentially absent => require either a default or a non null assertion.

I moved the defaults to the top, so it is consistent with the "defaults" as stated in the jsdocs.

2024-03-30 17:04 UTC, ST-DDT commented on src/modules/date/index.ts
> +   * @param options.refDate The date to use as reference point for the newly generated date. Defaults to `faker.defaultRefDate()`.
I added it to the merged signature.

> i just noticed refDate now appears twice in the generated docs:

Yeah, I know. Not going to fix this in the old docs generation though.

2024-03-30 20:07 UTC, matthewmayer approved these changes

2024-03-31 08:29 UTC, Shinigami92 approved these changes
- Not sure if we should first merge #2628

2024-03-31 09:01 UTC, ST-DDT commented
> Not sure if we should first merge #2628 

IMO that PR doesnt change much regarding this PR. A followup for both displaying/handling multiple signature might though.

I'll likely merge the other PR first, because it is bigger. Unless it is delayed a lot.

2024-04-01 08:36 UTC, merged