refactor(date)!: fail on invalid dates
faker-js/faker pull request #2757
Opened 2024-03-15 22:02 UTC by ST-DDT

If a given date is invalid, it is treated as an error instead of falling back to `refDateSource`

2024-03-16 07:41 UTC, matthewmayer requested changes

2024-03-16 07:41 UTC, matthewmayer commented on docs/guide/upgrading_v9/2757.md
> +Previously, if invalid dates where passed to the date module, it would fallback to `faker.refDateSource`.
`where` -> `were`

We should specifically list out which methods/parameters this affects

2024-03-16 07:58 UTC, ST-DDT commented on docs/guide/upgrading_v9/2757.md
> +Previously, if invalid dates where passed to the date module, it would fallback to `faker.refDateSource`.
```suggestion
Previously, if invalid dates were passed to the date module, it would fallback to `faker.refDateSource`.
```

2024-03-16 08:00 UTC, ST-DDT commented on docs/guide/upgrading_v9/2757.md
> +Previously, if invalid dates where passed to the date module, it would fallback to `faker.refDateSource`.
> We should specifically list out which methods/parameters this affects

This affects all methods in the date module that take `Date`-ish values.

2024-03-16 13:59 UTC, xDivisionByZerox commented on test/modules/date.spec.ts
> +        describe.each(['anytime', 'past', 'future', 'recent', 'soon'] as const)(
Is `'birthday'` missing in here?

2024-03-16 14:10 UTC, matthewmayer commented on docs/guide/upgrading_v9/2757.md
> +Previously, if invalid dates where passed to the date module, it would fallback to `faker.refDateSource`.
i think we could be clearer on what an "invalid" date means then.
e.g.
faker.date.soon({refDate:'2000'}) - '2000' is certainly not a valid `Date`, but its valid because we parse strings into `Date`s.

2024-03-16 14:19 UTC, matthewmayer commented on docs/guide/upgrading_v9/2757.md
> +Previously, if invalid dates where passed to the date module, it would fallback to `faker.refDateSource`.
How about something like this:

---

Various methods in the `date` module allow you to pass a `Date`-ish value: that is, either a Javascript Date, or a timestamp number or string that can be converted to a `Date` via the `new Date()` [constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date).

Previously if you passed something which could not be parsed to a `Date`, it would fall back to the current reference date. Now, this throws an error raising awareness of that bad value.

This affects the `refDate` parameter of  the `anytime()`, `birthdate()`, `past()`, `future()`, `recent()` and `soon()`, as well as the `from` and `to` parameters of `between()` and `betweens()`.

2024-03-16 16:31 UTC, ST-DDT commented on test/modules/date.spec.ts
> +        describe.each(['anytime', 'past', 'future', 'recent', 'soon'] as const)(
Changed

2024-03-16 16:37 UTC, ST-DDT commented on docs/guide/upgrading_v9/2757.md
> +Previously, if invalid dates where passed to the date module, it would fallback to `faker.refDateSource`.
Thanks for your suggestion. I changed the text accordingly.

2024-03-17 09:36 UTC, Shinigami92 commented on src/modules/date/index.ts
> +import { type Faker } from '../..';
The `@typescript-eslint/consistent-type-imports` with option `separate-type-imports` is not triggering here?!
https://typescript-eslint.io/rules/consistent-type-imports/

2024-03-17 09:36 UTC, Shinigami92 commented on src/modules/date/index.ts
>      let max: number;
Should we rename these to `epochMin/Max` and then destruct the `min/max` options like in every other place?
Also then we can remove the comment in [line 396](https://github.com/faker-js/faker/pull/2757/files#diff-33d9552c7d1fb7f98cb50e15888b577d2609cd9b6f17a333b641752c5049629dR396)

2024-03-17 09:43 UTC, ST-DDT commented on src/modules/date/index.ts
> +import { type Faker } from '../..';
I dont see a CI error so no.
Not sure why it changed in the first place.

2024-03-17 09:46 UTC, ST-DDT commented on src/modules/date/index.ts
>      let max: number;
We have a separate PR for birthdate:

- #2756

2024-03-17 09:47 UTC, ST-DDT commented on src/modules/date/index.ts
> +import { type Faker } from '../..';
```suggestion
import type { Faker } from '../..';
```

2024-03-19 01:52 UTC, matthewmayer approved these changes

2024-03-19 07:45 UTC, Shinigami92 reviewed
I wondered why the snapshots are different, but this is due to not calling `date.setTime(future/past)` anymore. This is okay to me, as it is still on the same Day, but just a different time.

So there is only one thing we can improve in the vitest test, and then I'm okay with approving this

2024-03-19 07:45 UTC, Shinigami92 commented on test/modules/date.spec.ts
> +      });
We can use vitest native spy here and check that it is not called

It would look something like this:

```ts
const mySpy = vi.spyOn(faker, defaultRefDate)

expect(mySpy).not.toHaveBeenCalled()
```

or similar

2024-03-19 10:54 UTC, ST-DDT commented
> I wondered why the snapshots are different, but this is due to not calling `date.setTime(future/past)` anymore. This is okay to me, as it is still on the same Day, but just a different time.

Both date and time are different for all methods in the past. Because we now generate the range directly instead of subtracting it. So the result is basically flipped.

2024-03-20 02:59 UTC, matthewmayer requested changes

2024-03-20 02:59 UTC, matthewmayer commented on src/modules/date/index.ts
>   * If nothing or a non-parsable value is passed, then it will take the value from the given fallback.
this line is no longer accurate.

2024-03-24 06:57 UTC, Shinigami92 approved these changes

2024-03-24 06:59 UTC, matthewmayer approved these changes

2024-03-24 12:47 UTC, xDivisionByZerox approved these changes

2024-03-24 12:51 UTC, merged