refactor(vehicle): Make VIN number generation more accurate
faker-js/faker pull request #2765
Opened 2024-03-23 02:20 UTC by lulunac27a

The last six digits of VIN (vehicle identification number) is the number and the 13th digit (last five digits) can start with number 0 (zero).

2024-03-23 05:05 UTC, matthewmayer requested changes, later dismissed

2024-03-23 05:05 UTC, matthewmayer commented on src/modules/vehicle/index.ts
> +    })}${this.faker.number.int({ min: 0, max: 99999 }).toString().padStart(5, '0'}`; // return five digit # with leading zeros
Probably better to use `faker.string.numeric` for this.

2024-03-23 11:04 UTC, matthewmayer commented on src/modules/vehicle/index.ts
> +    })}${this.faker.number.int({ min: 0, max: 99999 }).toString().padStart(5, '0'}`; // return five digit # with leading zeros
Also note there's a typo in the code the last } should be )

2024-03-23 13:44 UTC, xDivisionByZerox commented on src/modules/vehicle/index.ts
> +    })}${this.faker.number.int({ min: 0, max: 99999 }).toString().padStart(5, '0')}`; // return five digit # with leading zeros
By using a faker method, the function becomes more readable IMO.

```suggestion
    })}${this.faker.string.numeric({ length: 5, allowLeadingZeros: true })}`;
```

2024-03-23 13:46 UTC, xDivisionByZerox commented
@faker-js/maintainers Is this a `refactor` or a `fix`?

2024-03-23 16:12 UTC, ST-DDT commented
> @faker-js/maintainers Is this a `refactor` or a `fix`?

IMO `fix`

2024-03-24 07:02 UTC, Shinigami92 commented
FFR: https://en.m.wikipedia.org/wiki/Vehicle_identification_number

2024-04-25 20:16 UTC, xDivisionByZerox submitted a review, later dismissed

2024-04-25 21:07 UTC, xDivisionByZerox approved these changes

2024-04-25 22:56 UTC, ST-DDT approved these changes

2024-04-25 23:34 UTC, matthewmayer approved these changes

2024-04-26 06:14 UTC, merged

2024-04-26 06:56 UTC, RD-CL commented on src/modules/vehicle/index.ts
> +    })}${this.faker.number.int({ min: 0, max: 99999 }).toString().padStart(5, '0'}`; // return five digit # with leading zeros
Matt Mayer,

You have not responded to emails and phone calls. RDCL will provide all of your personal information and evidence to the police investigators and the relevant authorities. Your representation in Hong Kong say they have no instructions to act in this matter. Your actions are criminal and this is theft. RDCL will be relentless in the pursuit of its property and you will be notified daily through all online channels until you return what you have stolen and provide all logins and passwords associated with the accounts and turn over all information on to whom you have been illegally redirecting RDCL's confidential email, including financial data.

RDCL will communicate with you in open forum to ensure you receive these messages.