feat(locale): location
faker-js/faker pull request #2775
Opened 2024-03-27 11:41 UTC by Mirazyzz

2024-03-27 12:08 UTC, ST-DDT reviewed
Please sort the files alphabetically.

2024-03-27 12:08 UTC, ST-DDT commented on src/locales/uz_UZ_latin/location/street_pattern.ts
> +  '{{location.street_suffix}} {{location.street_name}}',
This looks strange to me.
Why does it start with the suffix?
Also IMO we should name the street_name file street_name_part or similar.

2024-03-27 12:29 UTC, Mirazyzz commented on src/locales/uz_UZ_latin/location/street_pattern.ts
> +  '{{location.street_suffix}} {{location.street_name}}',
I missed that one, suffix should be after the street name.

2024-03-27 12:30 UTC, Mirazyzz commented
> Please sort the files alphabetically.

Do you want the street names to be sorted alphabetically? They're pretty large and looking at other locales I thought it's not necessary.

2024-03-27 12:54 UTC, Shinigami92 commented
I suggest to add the locale to the PR title

2024-03-27 12:59 UTC, Shinigami92 approved these changes, later dismissed
Count me already as approved but fix the change request from @ST-DDT pls

2024-03-27 23:37 UTC, matthewmayer commented
> > Please sort the files alphabetically.
> 
> 
> 
> Do you want the street names to be sorted alphabetically? They're pretty large and looking at other locales I thought it's not necessary.

All *new* locale data should be sorted alphabetically unless there's a good reason (eg months of the year can be kept as Jan-Feb-mar...)

2024-03-30 18:49 UTC, ST-DDT requested changes
Please make the requested changes.

2024-03-31 01:06 UTC, Mirazyzz commented
> Please make the requested changes.

Ready, sorry for the delay.

2024-03-31 07:57 UTC, matthewmayer requested changes

2024-03-31 07:57 UTC, matthewmayer commented on src/locales/uz_UZ_latin/location/street_pattern.ts
> +export default ['{{location.street_name}} {{location.street_suffix}}'];
This should be changed to location.street_name_part now right?

2024-03-31 17:53 UTC, Mirazyzz commented on src/locales/uz_UZ_latin/location/street_pattern.ts
> +export default ['{{location.street_name}} {{location.street_suffix}}'];
exactly, my bad.

2024-03-31 18:19 UTC, ST-DDT approved these changes, later dismissed

2024-03-31 19:31 UTC, Shinigami92 submitted a review, later dismissed

2024-04-01 05:44 UTC, matthewmayer requested changes

2024-04-01 05:44 UTC, matthewmayer commented on src/locales/uz_UZ_latin/location/street_address.ts
> +  full: '{{location.street}}, {{location.buildingNumber}} {{location.secondaryAddress}}',
Is this correct?
If a secondary address (e.g. room/apartment number is provided) this immediately follows the building number with no comma etc?

without secondary address:
```
fakerUZ_UZ_latin.location.streetAddress()
> Munif Mahanov qishlog'i, 905
> Sobit Miranov xiyoboni, 35a
```

with secondary address:
```
fakerUZ_UZ_latin.location.streetAddress(true)
> Munif Mahanov qishlog'i, 905 972 uy
> Sobit Miranov xiyoboni, 35a 817 xonadon
```

2024-04-01 17:50 UTC, Mirazyzz commented on src/locales/uz_UZ_latin/location/street_address.ts
> +  full: '{{location.street}}, {{location.buildingNumber}} {{location.secondaryAddress}}',
Yes, you're right I think it's better to separate them with comma. By the way, it's also better to put "-" for secondary address between house number and title (uy, xonadon). In Uzbek "-" is used for ordinal numbers. Do you think I should change it too?

2024-04-01 23:34 UTC, matthewmayer commented on src/locales/uz_UZ_latin/location/street_address.ts
> +  full: '{{location.street}}, {{location.buildingNumber}} {{location.secondaryAddress}}',
Yes

2024-04-02 03:37 UTC, matthewmayer approved these changes

2024-04-02 06:41 UTC, Shinigami92 approved these changes

2024-04-02 07:07 UTC, ST-DDT approved these changes

2024-04-02 07:08 UTC, merged