Update char-mappings.ts to hebrew
faker-js/faker pull request #2781
Opened 2024-04-01 12:03 UTC by mordi-d

instead of getting such a result
15t15q15f160.15c15l16215r@hotmail.com
Following https://github.com/faker-js/faker/issues/2776

2024-04-01 12:32 UTC, ST-DDT requested changes
You might be able to automatically fix it with: `pnpm run lint --fix`

2024-04-01 12:32 UTC, ST-DDT commented on src/modules/internet/char-mappings.ts
> +    ["א", "a"],
Please fix the lint errors.

2024-04-01 13:11 UTC, matthewmayer commented
Here's 100 outputs:

```
'chnyt_kysry27@yahoo.com',
  'anbl.bytyvsph40@hotmail.com',
  'ravt77@gmail.com',
  'alksndr14@hotmail.com',
  'glbva27@hotmail.com',
  'ktyh_artsy68@hotmail.com',
  'tvm_bnravbn@gmail.com',
  'yalh37@gmail.com',
  'ntnal.glbva83@yahoo.com',
  'nykvls_lydvr84@yahoo.com',
  'mvryh_zkvt@hotmail.com',
  'tvbh_tshby@gmail.com',
  'rvnyt65@yahoo.com',
  'lvy94@yahoo.com',
  'alma98@gmail.com',
  'aylay71@yahoo.com',
  'dgn.knr68@gmail.com',
  'shavl57@hotmail.com',
  'ravt_avryh@gmail.com',
  'lb23@yahoo.com',
  'lyavn.bytyvsph@gmail.com',
  'ygal_gdrvn@yahoo.com',
  'chmy_bnyshral@hotmail.com',
  'shyrh88@hotmail.com',
  'yvab19@gmail.com',
  'adn.mshany@hotmail.com',
  'yrdn74@yahoo.com',
  'vyktvryh_alyab@gmail.com',
  'lshm.ashbl@yahoo.com',
  'rn.ydyn@yahoo.com',
  'shchr.gdvt12@yahoo.com',
  'ydyd33@hotmail.com',
  'yftch.ksht@gmail.com',
  'avfl_tsvk70@gmail.com',
  'yrdn.bchvr@hotmail.com',
  'yhvntn19@yahoo.com',
  'avrly.mshh@yahoo.com',
  'ym_knan@yahoo.com',
  'drvr_atsmvn43@hotmail.com',
  'shyrh25@hotmail.com',
  'nvah_avbdyh53@yahoo.com',
  'alchnn_adyny@hotmail.com',
  'syny_bram@yahoo.com',
  'rvn16@yahoo.com',
  'mrym_shr67@yahoo.com',
  'styv_dvtn@hotmail.com',
  'dnyalh0@yahoo.com',
  'shkmh59@hotmail.com',
  'yal_agrvn@hotmail.com',
  'yvbl35@hotmail.com',
  'aylay_tsmch97@hotmail.com',
  'avfk.bravr33@hotmail.com',
  'avz92@hotmail.com',
  'thylh29@yahoo.com',
  'lvy_fld44@hotmail.com',
  'nvah.bnaryh@yahoo.com',
  'yhl.shny96@yahoo.com',
  'dnyalh_kvrn@gmail.com',
  'yvgb88@yahoo.com',
  'afryl_bram93@hotmail.com',
  'flg29@hotmail.com',
  'ayylt16@gmail.com',
  'chmvtl_asys45@hotmail.com',
  'amlyh.mrvm@yahoo.com',
  'hll95@yahoo.com',
  'gl_ksfy86@gmail.com',
  'rgb78@gmail.com',
  'lbnh.advny@gmail.com',
  'chbyb.gbavn@gmail.com',
  'avhd_bnshchr81@hotmail.com',
  'ashr97@gmail.com',
  'syny30@gmail.com',
  'avfyrh_nshr@hotmail.com',
  'nytay.shbyb17@yahoo.com',
  'lyan8@hotmail.com',
  'gyvra33@yahoo.com',
  'mykl95@hotmail.com',
  'alvn.kynn@gmail.com',
  'adn24@gmail.com',
  'avmry_gl1@yahoo.com',
  'kvryn_abnvn@yahoo.com',
  'mgl.shlv53@hotmail.com',
  'shchk.bngl68@yahoo.com',
  'nchshvn_nvvh48@gmail.com',
  'lyrvy92@yahoo.com',
  'avzyh98@yahoo.com',
  'rvn13@hotmail.com',
  'lyrvy_lbary@yahoo.com',
  'smdr_chryph86@yahoo.com',
  'abytl_ntnal@gmail.com',
  'chnn79@hotmail.com',
  'rbyb_chryph98@yahoo.com',
  'alvmh_shvb@yahoo.com',
  'rvtm_mvryh34@yahoo.com',
  'nytay.mavz16@gmail.com',
  'rbkh5@yahoo.com',
  'dfnh86@gmail.com',
  'tyav_drvr40@yahoo.com',
  'shryt_frch@gmail.com',
  'ayb.aylt@gmail.com'
```

2024-04-04 16:25 UTC, ST-DDT approved these changes

2024-04-04 16:31 UTC, matthewmayer approved these changes
looks good to me, the resulting emails look better than before. they are a bit short on vowels, but that's just [how Hebrew works](https://judaism.stackexchange.com/questions/10370/why-does-the-hebrew-alphabet-not-have-letters-representing-vowels)

2024-04-04 20:06 UTC, Shinigami92 approved these changes

2024-04-04 20:13 UTC, merged