fix: remove word examples that contain spaces
faker-js/faker pull request #281
Opened 2022-01-24 19:22 UTC by griest024

"word" to me implies that the string does not contain spaces. This PR removes all word examples that contain spaces other than `boo hoo` which was changed to `boohoo`

2022-01-24 19:29 UTC, pkuczynski submitted a review, later dismissed
We could extend conjunction list with https://7esl.com/conjunctions-list/ (skipping those which contain spaces)

2022-01-24 19:34 UTC, griest024 commented
> We could extend conjunction list with https://7esl.com/conjunctions-list/ (skipping those which contain spaces)

done

2022-01-25 18:08 UTC, import-brain approved these changes

2022-04-06 11:59 UTC, Shinigami92 commented
@griest024 Tests are running red, I assume you need to update the expected seeded values due to index changes

2022-06-17 22:36 UTC, xDivisionByZerox approved these changes

2022-06-17 22:39 UTC, xDivisionByZerox requested changes
tests need updates

2022-08-05 13:38 UTC, ST-DDT commented
I updated this so we can either merge or discard it.

2022-08-05 13:43 UTC, Shinigami92 approved these changes

2022-08-05 16:07 UTC, pkuczynski approved these changes

2022-08-05 16:31 UTC, import-brain approved these changes

2022-08-05 17:51 UTC, merged