feat: introduce FakerCore
faker-js/faker pull request #2838
Opened 2024-04-20 14:11 UTC by ST-DDT

First part of the standalone module function feature #2667 

- #2667 

TODO

2024-04-22 07:18 UTC, Shinigami92 reviewed
I know the PR is still in draft but I would like to provide some early-feedback

1. I think the `refDate` should still be named something like `default` or `fallback` or `base`, so the intent is more clear and there might be no variable naming conflict when using an option's refDate + the ...RefDate
2. I suggest to not do something like `super({ fakerCore: fakerCore ?? { locale, randomizer, config: {} } })` but only pass the locale and randomizer so the config get's set like every other method call to a default internally. Or is there something special about that I currently overlook? 👀

2024-04-22 21:49 UTC, ST-DDT commented
1) Done
2) Changed slightly to improve readability.

2024-04-22 21:53 UTC, ST-DDT commented
Does anybody know why this test is failing with that particular error message?

>  ❯ test/simple-faker.spec.ts > simpleFaker > should not log anything on startup
     → Unexpected token ','

It seems to happen only with vitest/CJS.

2024-04-23 07:33 UTC, Shinigami92 commented
> Does anybody know why this test is failing with that particular error message?
> 
> > ❯ test/simple-faker.spec.ts > simpleFaker > should not log anything on startup
> > → Unexpected token ','
> 
> It seems to happen only with vitest/CJS.

If I set `minify: false` in `tsup.config.ts` everything runs fine. Please report a bug-issue to https://github.com/egoist/tsup

2024-05-14 18:20 UTC, ST-DDT commented
The error is caused by this part:

````js
_class.prototype.__init23.call(this);,this.definitions=_chunkWAQHUEHTcjs.d.call(void 0, this.rawDefinitions)
                                     ^
````

Which is equivalent to this source code:

https://github.com/faker-js/faker/blob/e4da2f5478e3df74ed98d4249ace561dddc9f53d/src/faker.ts#L195-L197

2024-05-14 20:10 UTC, ST-DDT commented
I created an issue in tsup with a minimal reproduction:

- https://github.com/egoist/tsup/issues/1124

And it has reeeaaally specific conditions, check the issue for more details.

2024-05-14 20:43 UTC, ST-DDT commented on src/faker.ts
> +  }
Should we deprecate this field?

2024-05-26 20:20 UTC, xDivisionByZerox commented on src/faker.ts
> +  }
Can you give reasoning on why we should  be doing that?

2024-05-26 21:23 UTC, ST-DDT commented on src/faker.ts
> +  }
Because you could access them via fakerCore directly.

I thought about potentially removing faker.definitions in favor of an explicit method call as well.
`faker.definitions.module.entry` => `requireData(fakerCore, 'module', 'entry')`

2024-05-30 16:14 UTC, Shinigami92 submitted a review, later dismissed
LGTM

2024-05-31 05:03 UTC, import-brain submitted a review, later dismissed

2024-05-31 07:41 UTC, matthewmayer requested changes
see my comment at https://github.com/faker-js/faker/issues/2667#issuecomment-2067690118 - would it make sense to delay merging this?

2024-05-31 07:42 UTC, matthewmayer approved these changes, later dismissed
changed my feedback to a comment to avoid a hard block, but i think there is still some logic in deferring this and merging together with the actual changes.

2026-03-22 19:43 UTC, ST-DDT commented
This PR contains the first part of the standalone module function PR:

- #3748

It uses a slightly different implementation then the one used in that PR but both are generally compatible.
I can modify either PR depending on which variant your prefer.

SMF PR:

- `Faker` -> `fakerToCore()` -> `FakerCore`
  https://github.com/faker-js/faker/blob/8fa7e270fdc130fa34e644dc282364e52f038baf/src/internal/faker-to-core.ts#L12-L22

This/FakerCore PR:

- `faker.fakerCore` permanent field in class
  https://github.com/faker-js/faker/blob/6dada60781938d5e76f87062abf0be9d1f9cf7b1/src/simple-faker.ts#L123-L125

2026-03-23 13:32 UTC, Shinigami92 reviewed
I already gave an LGTM here: https://github.com/faker-js/faker/pull/2838#pullrequestreview-2088771780
left a comment here and I still think this PR is in a good state to get merged 🔜™️
is there a reason why it is still in draft? have you anything planned to change in this PR?

2026-03-23 13:32 UTC, Shinigami92 commented on test/faker.spec.ts
>        });
I think it might be a good UX to throw an error here, or direct users to use simpleFaker instead

2026-03-23 13:46 UTC, ST-DDT commented on test/faker.spec.ts
>        });
Please note that there is no difference constructor param wise between simple and full faker anymore.

2026-03-23 13:58 UTC, Shinigami92 commented on test/faker.spec.ts
>        });
but maybe we could bring it back as a UX
lets wait for the third opinion -> @xDivisionByZerox

2026-03-23 14:01 UTC, ST-DDT commented
> is there a reason why it is still in draft? have you anything planned to change in this PR?

Only discussions regarding names, behaviour, API and PR contents.

2026-03-28 15:39 UTC, Shinigami92 commented on src/faker.ts
> -    }
**note (non-blocking):** we will rethink to throw an UX error in v11

2026-03-28 15:39 UTC, Shinigami92 commented on test/faker.spec.ts
>        });
-> https://github.com/faker-js/faker/pull/2838#discussion_r3004963536

2026-03-28 16:54 UTC, xDivisionByZerox commented
**Team Decision**

We take this regardless of whether we also take the standalone modules PR (#3748)

---

@ST-DDT Please rebase/merge this branch against origin/next.

2026-03-28 18:36 UTC, Shinigami92 submitted a review, later dismissed

2026-03-29 16:42 UTC, xDivisionByZerox submitted a review, later dismissed

2026-03-29 16:42 UTC, xDivisionByZerox commented on src/core.ts
> +    config: config ?? {},
The default value from these properties can be set when restructuring them from `options` in the first line of the function. 

That way the randomizer is consistently seeded in line 89 as well, since the seed does not need to be provided immediately when generating the mersenne randomizer.

2026-03-29 16:42 UTC, xDivisionByZerox commented on src/config.ts
Why did you decide to wrap the defaultRefDate into an additional "config" object? Isn't everything inside the core already kind of a "config"?

2026-03-29 16:42 UTC, xDivisionByZerox commented on src/simple-faker.ts
> +    return this.fakerCore.config.defaultRefDate ?? (() => new Date());
As [copilot mentioned in its comment](https://github.com/faker-js/faker/pull/2838/changes#r2972016602) this will create new anonymous function instances over and over again. I feel like this should be defaulted during the creation of the core, so that it contains a "required" config instance and we do not have to handle nullish values.
This kind of plays into [my question why the config wrapper exist at all](https://github.com/faker-js/faker/pull/2838/changes#r3006435416).

2026-03-29 16:42 UTC, xDivisionByZerox commented on src/faker.ts
> +  }
Lets leave it in it's current state for now. I think we should still remove the comment.

2026-03-29 18:06 UTC, ST-DDT commented on src/config.ts
To allow sharing the config instance with other core instances (similar to other randomizer/locale data)

2026-03-29 18:33 UTC, ST-DDT commented on src/config.ts
It is also typed specifically to allow other plugins/users to enhance it for their own methods.
(Although that would work for FakerCore as well)

2026-03-29 18:36 UTC, ST-DDT commented on src/simple-faker.ts
> +    return this.fakerCore.config.defaultRefDate ?? (() => new Date());
I moved the default to a const.
Since the config is exposed as public, mutable, and optional (and we previously explicitly allowed setting it to null to reset it to default), I think we should keep the default on access to avoid potential errors when using them.
(Otherwise we wouldn't need the method in the first place)

2026-03-29 18:37 UTC, ST-DDT commented on src/core.ts
> +    config: config ?? {},
It has slightly different default semantics, but I'll change it anyway.

2026-04-08 16:25 UTC, Shinigami92 commented on src/core.ts
> + * @since 10.4.0
**polish:** needs a bump, @xDivisionByZerox can you please let @ST-DDT know if he needs to do other cleanups? I won't like to get my approval constantly dismissed

2026-04-08 19:03 UTC, xDivisionByZerox approved these changes

2026-04-08 19:04 UTC, Shinigami92 approved these changes

2026-04-09 12:50 UTC, merged