test: remove mocks from address
faker-js/faker pull request #285
Opened 2022-01-24 20:18 UTC by Shinigami92

2022-01-24 23:30 UTC, pkuczynski commented on test/address.spec.ts
> +    seed: 42,
How did you get to these seed values? When `en` files will change would seed values remain the same?

2022-01-25 07:51 UTC, prisis commented on test/address.spec.ts
> +    seed: 42,
Just random number that was choosen. The idea is too have something like a snapshot of the output for the current version.

2022-01-25 07:54 UTC, Shinigami92 commented on test/address.spec.ts
> +    seed: 42,
42: https://simple.wikipedia.org/wiki/42_(answer)
1337: https://simple.wikipedia.org/wiki/Leet
1211: another number related to us :shrug:

2022-01-25 08:34 UTC, Shinigami92 commented
I will add some missing cases

2022-01-25 08:55 UTC, pkuczynski commented on test/address.spec.ts
> +    seed: 42,
That would tight the test with the dataset, right? Wouldn't it be better to mock `definitions` to avoid this?

2022-01-25 15:11 UTC, griest024 commented on test/address.spec.ts
> +    seed: 42,
So just to clarify, would these expectations need to change if the definition file contents were changed?

2022-01-25 15:37 UTC, griest024 requested changes

2022-01-25 15:37 UTC, griest024 commented on test/address.spec.ts
> +              'The precision of latitude should be had of 4 digits'
Grammar: The precision of latitude should be ~~had of~~ 4 digits | The precision of latitude should *have* ~~be had of~~ 4 digits

same in other places

2022-01-25 15:37 UTC, griest024 commented on test/address.spec.ts
> +            `The street number should had ${expectations.streetAddressDigits} digits`
grammar: The street number should ~~had~~ *have* ${expectations.streetAddressDigits} digits

same in other places

2022-01-25 15:37 UTC, griest024 commented on test/address.spec.ts
> +            'The random direction should be equals ' + expected
grammar: The random direction should be ~~equals~~ *equal to* | The random direction should ~~be equals~~ *equal*

same in other places

2022-01-25 15:37 UTC, griest024 commented on test/address.spec.ts
> +          expect(typeof coordinate[1]).toBe('string');
I think this should be a separate spec: `When the specified radius is undefined`

2022-01-25 16:52 UTC, Shinigami92 commented
The `non metric` coords test is currently flaky

We also found that we maybe should set a random seed for the non-seed-based tests, cause otherwise it would take the last set seed sequence

2022-01-25 17:04 UTC, griest024 requested changes

2022-01-25 17:04 UTC, griest024 commented on test/address.spec.ts
> +            `The random direction should be equal ${expected}`
`be equal to` or `equal`

2022-01-25 17:04 UTC, griest024 commented on test/address.spec.ts
> +            `${prefixErrorMessage} be typeof equal to ${expectedType}. Current is ${typeof cardinalDirection}`
`${prefixErrorMessage} be of type ${expectedType}` like you have on line 500

2022-01-25 21:33 UTC, Shinigami92 commented on test/address.spec.ts
> +          );
This is currently failing hard...
I don't know if the function is wrong or if my test is wrong.

2 degrees are like 200+ km and the factor 1.6 converts the 100km to miles
also `isMetric = false` should then use the miles version of the function
but the delta is very huge :thinking:

2022-01-27 08:09 UTC, Shinigami92 commented on test/address.spec.ts
> +          );
@prisis what do you think I should do here?
Currently it blocks the PR to get merged, so maybe we should mark it with `it.todo` and look into that later? Maybe even create an issue to track it?
The benefit would be, that we would have now a much better test coverage for the rest of the address module.

2022-01-27 12:26 UTC, ST-DDT commented on test/address.spec.ts
> +          );
Mark it as todo for now and maybe add an issue so it doesn't get lost.

2022-01-27 12:33 UTC, Shinigami92 commented on test/address.spec.ts
> +          );
https://github.com/faker-js/faker/issues/321

2022-01-27 12:36 UTC, ST-DDT commented
Maybe remove the `chore(deps): update vitest` commit from this PR?

2022-01-27 12:36 UTC, ST-DDT approved these changes

2022-01-27 12:38 UTC, Shinigami92 commented
> Maybe remove the `chore(deps): update vitest` commit from this PR?

I will rebase if #316 was merged

2022-01-29 18:37 UTC, ST-DDT approved these changes

2022-01-29 18:40 UTC, Shinigami92 commented on test/address.spec.ts
> +  for (let { seed, expectations } of seededRuns) {
```suggestion
  for (const { seed, expectations } of seededRuns) {
```

2022-01-29 23:12 UTC, prisis approved these changes

2022-01-30 10:52 UTC, merged