refactor(locale): normalize commerce data
faker-js/faker pull request #2868
Opened 2024-05-01 13:11 UTC by xDivisionByZerox

# Description

Follow-on to https://github.com/faker-js/faker/pull/2265.

Normalize the entries in the `commerce` module definitions in all locales.

I choose this module as locale data are somewhat limited. Furthermore, none of the datasets surpass the 1k entry limit, meaning that all modifications to locale files involve sorting entries only.

2024-05-01 14:07 UTC, ST-DDT approved these changes

2024-05-01 16:38 UTC, matthewmayer requested changes

2024-05-01 16:38 UTC, matthewmayer commented on src/locales/az/commerce/product_name.ts
> +  material: ['Ağac', 'Beton', 'Pambıq', 'Plastik', 'Polad', 'Qranit', 'Rezin'],
Should these have newlines ?

2024-05-01 16:39 UTC, matthewmayer approved these changes

2024-05-01 16:47 UTC, xDivisionByZerox commented on src/locales/az/commerce/product_name.ts
> +  material: ['Ağac', 'Beton', 'Pambıq', 'Plastik', 'Polad', 'Qranit', 'Rezin'],
Prettier is responsible for formatting, including when a line break for a new is made. So I don't think I understand what you are referring to. Could you explain further?

2024-05-01 16:56 UTC, Shinigami92 commented on src/locales/az/commerce/product_name.ts
> +  material: ['Ağac', 'Beton', 'Pambıq', 'Plastik', 'Polad', 'Qranit', 'Rezin'],
> Should these have newlines ?

Not in this case, cause < 80 cols

2024-05-02 06:45 UTC, Shinigami92 approved these changes

2024-05-03 07:00 UTC, merged