docs: automatically generate docs
faker-js/faker pull request #289
Opened 2022-01-24 23:48 UTC by ST-DDT

Automatically generates the api documentation using typedocs.

Based on PR https://github.com/faker-js/faker/pull/207 by @ericjeker

- [x] Update Sidenav (manually)
- [x] Add script to generate docs
- [x] Generate docs (automatically)
- [ ] Verify that the generated pages looks good

2022-01-25 02:38 UTC, JessicaSachs approved these changes
Pulled it down and tried it. I love this. I think we could make the parameters a little prettier, but this is so much better than what exists, I think we should merge it now.

I feel a little awkward about committing generated source code... I think we should probably have CI re-build and publish the docs instead of committing them.

BUT! Regardless, I believe it is a good first step ❤️

2022-01-25 05:06 UTC, ericjeker commented
> I feel a little awkward about committing generated source code... I think we should probably have CI re-build and publish the docs instead of committing them.

Yes, same. I think we shouldn't commit that, otherwise the CI will create changes in the repo files, which is not good.

2022-01-25 05:09 UTC, ericjeker commented
This looks great!

Can we have the sidenav automatically generated when looping on the modules maybe? IIRC we can use Frontmatter for that? Or simply generate a Javascript array that is then processed in the `.vitepress/config`?

2022-01-25 07:36 UTC, ST-DDT commented
> Can we have the sidenav automatically generated when looping on the modules maybe?

I will do that.

> I think we should probably have CI re-build and publish the docs instead of committing them.

My original idea was to attach it to a pre commit hook, but on the fly generation is probably best.

> I think we could make the parameters a little prettier

Any suggestion how it should look like?
E.g. a table?

2022-01-25 07:48 UTC, prisis commented
I would only generate the code in the ci if the docs are build, so there is always up to date version live and put the docs/api to gitignore

2022-01-25 07:52 UTC, Shinigami92 commented
> I would only generate the code in the ci if the docs are build, so there is always up to date version live and put the docs/api to gitignore

Also we have to do it like that, otherwise it could be hard to setup a CI that especially bypasses admin privileges to push into main branch

2022-01-25 07:54 UTC, JessicaSachs commented
Yeah, build it on CI and .gitignore the local files.

@ST-DDT I was looking for inspo when I did this PR review earlier... I think Styleguidist has a decent UI

https://react-kawaii.vercel.app/#/Components?id=cat
<img width="707" alt="Screen Shot 2022-01-25 at 2 53 35 AM" src="https://user-images.githubusercontent.com/2801156/150934662-a4bb705d-0273-4a92-a2f3-793845f80807.png">

2022-01-25 08:50 UTC, Shinigami92 commented
What are your thoughts about localization support for that? https://github.com/faker-js/faker/pull/196

2022-01-25 15:31 UTC, ST-DDT commented
@JessicaSachs Like this?

I changed the command to manually generate the files to `pnpm run docs:api`, 
but they are also generated during `pnpm run build`.

2022-01-25 16:00 UTC, Shinigami92 requested changes

2022-01-25 16:00 UTC, Shinigami92 commented on scripts/apidoc.ts
> +function escape(value: string) {
```suggestion
function escape(value: string): string {
```

2022-01-25 16:00 UTC, Shinigami92 commented on scripts/apidoc.ts
> +  }
```suggestion
  def = def ? '' : `\`${def}\``
```

2022-01-25 16:00 UTC, Shinigami92 commented on scripts/apidoc.ts
> +  let modulesPages: { text: string; link: string }[] = [];
```suggestion
  const modulesPages: Array<{ text: string; link: string }> = [];
```

2022-01-25 16:00 UTC, Shinigami92 commented on scripts/apidoc.ts
> +  let modulesPages: { text: string; link: string }[] = [];
```suggestion
  const modulesPages: Array<{ text: string; link: string }> = [];
```

2022-01-25 16:00 UTC, Shinigami92 commented on scripts/apidoc.ts
>  async function build() {
```suggestion
async function build(): Promise<void> {
```

2022-01-25 16:00 UTC, Shinigami92 commented on scripts/apidoc.ts
> +            '<' + parameterName + '>',
```suggestion
            `<${parameterName}>`,
```

2022-01-25 16:00 UTC, Shinigami92 commented on scripts/apidoc.ts
>            content += (example ? ' // => ' + example : '') + '\n';
```suggestion
          content += (example ? ` // => ${example}` : '') + '\n';
```

2022-01-25 16:00 UTC, Shinigami92 commented on scripts/apidoc.ts
> +      if (examples.length != 0) {
```suggestion
      if (examples.length !== 0) {
```

2022-01-25 17:34 UTC, Shinigami92 requested changes

2022-01-25 17:34 UTC, Shinigami92 commented on package.json
> +    "build": "run-s build:clean build:code build:types docs:api",
build is running on all nodes in the CI matrix
but the docs only need to be build on one node version / one runner
therefore we need to organize this in a different way :thinking:

2022-01-25 21:55 UTC, Shinigami92 commented on package.json
>      "docs:build:ci": "run-s build docs:build",
I think we just need to move the `docs:api` to here and remove it from `build`

```suggestion
    "docs:build:ci": "run-s build docs:build docs:api",
```

2022-01-25 21:55 UTC, Shinigami92 commented on package.json
> +    "build": "run-s build:clean build:code build:types docs:api",
```suggestion
    "build": "run-s build:clean build:code build:types",
```

2022-01-25 21:58 UTC, Shinigami92 commented on package.json
>      "docs:build:ci": "run-s build docs:build",
In addition to that we could document in e.g. the CONTRIBUTING.md that this `docs:api` needs to be runned once to prepare the `docs:dev`

2022-01-25 22:02 UTC, Shinigami92 commented on package.json
>      "docs:build:ci": "run-s build docs:build",
Or add two script like

```
"docs:dev": "run-s docs:dev:prepare docs:dev:run",
"docs:dev:prepare": "run-s build docs:api"
"docs:dev:run": "vitepress dev docs"
```

But 
1. it's a bit verbose
2. it would always run `build` and `docs:api` before starting the dev server, also if not need :thinking:

2022-01-27 16:24 UTC, Shinigami92 commented
I will approve that now, but we should document
- which script should be run by humans in which order
- which scripts are required by CI/netlify-toml
- which are "just" sub-scripts
Could you open an issue for that, to track it?

2022-01-27 17:13 UTC, JessicaSachs approved these changes

2022-01-27 17:13 UTC, merged