test(date):  Add Intl-Based Tests for Date Definitions to Ensure Completeness of Weekdays and Months
faker-js/faker pull request #2912
Opened 2024-05-18 14:17 UTC by sossost

This PR is about Intl-based tests for the date definitions in Faker.js. These tests ensure that the weekdays and months are correctly defined and returned across different locales, enhancing the accuracy and completeness of the data.

2024-05-18 16:13 UTC, ST-DDT commented
Is this PR ready for review yet?
Because I dont see `Intl` in the tests anywhere.

2024-05-18 17:05 UTC, sossost commented
@ST-DDT 
If you create tests with JavaScript Intl.DateTimeForamt, most of them will not pass.
Did I proceed correctly??

```javascript
     it('should use Intl.DateTimeFormat to get the month name in the correct locale', () => {
          const date = new Date(2020, 0, 1);
          const intlMonth = new Intl.DateTimeFormat(locale, {
            month: 'long',
          }).format(date);
          expect(localizedFaker.definitions.date.month.wide).toContain(
            intlMonth
          );
      });

      it('should use Intl.DateTimeFormat to get the abbreviated month name in the correct locale', () => {
          const date = new Date(2020, 0, 1);
          const intlMonth = new Intl.DateTimeFormat(locale, {
            month: 'short',
          }).format(date);
          expect(localizedFaker.definitions.date.month.abbr).toContain(
            intlMonth
          );
      });
```

2024-05-18 17:16 UTC, ST-DDT commented
I'm currently on mobile and thus cannit run the tests myself.
The tests looks correctly (although all 12 months need to be checked).
Also I'm not sure whether the current setting returns only the month or the full date string, for that I need some of the failure messages.

2024-05-18 17:33 UTC, sossost commented
@ST-DDT 
These are some failure messages.

AssertionError: expected [ 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri', 'Sâmbătă', 'Duminică' ] to include 'sâmbătă'
AssertionError: expected [ 'нед', 'пон', 'вто', 'сре', 'чет', 'пет', 'саб' ] to include 'саб.'


Failure factors can range from missing data to capitalization, dots, etc.

2024-05-18 17:44 UTC, ST-DDT commented
Please note: We want the test to ensure that we have the correct values, currently the values might be invalid.

> AssertionError: expected [ 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri', 'Sâmbătă', 'Duminică' ] to include 'sâmbătă'

If I insert `sâmbătă` or `Sâmbătă` into google translate and translate it back and forth, then I get the lowercase variant

2024-05-18 17:53 UTC, ST-DDT commented
Could you please fix the invalid values and replace it with correct ones?

Maybe using a onetime script like:

````ts
for [locale] in allLocales {
  const weekdayPath = resolve("src/locales/${locale}/date/weekday.ts");
  const storedWeekdays = await import(weekdayPath) as DateDefinition["weekday"];
  const long = [];
  const abbr = [];
  for (const i=0;i<7;i++) {
    long.push(new Intl...);
    abbr.push(new Intl....);
  }
  storedWeekdays.long = long;
  storedWeekdays.abbr = abbr;
  writeFileSync(weekdayPath, "export default "+JSON.toString(storedWeekdays));
}
````
And run `pnpm run preflight` afterwards.

2024-05-18 18:00 UTC, ST-DDT commented
Please merge `next` into your branch to avoid merge conflicts, because we recently merged #2902.

-  #2902

2024-05-18 18:22 UTC, ST-DDT commented
> **EDIT:** Please post the script here, so that we can use it during the review.

If you post the script here, we can later integrate it in our generate locale script, so that all locales always have the correct values.

Or if you want to do that directly you can add it after `generateLocaleFile`:

https://github.com/faker-js/faker/blob/7dc8a18f0b906f959670627240a6e5600bf47b75/scripts/generate-locales.ts#L414-L422

2024-05-19 01:27 UTC, sossost commented
@ST-DDT 
When I run the script that creates the files in the date folder, all tests now pass.
However, there are a few things to check.
The data previously entered for each locale is also If Intl returns English, it will be converted to English.
Also, the 'vd' code was returned by Intl in my local language, so I added an exception condition.

2024-05-19 03:52 UTC, matthewmayer commented
Rather than just overwriting the existing data, could we output a table showing where the data produced by Intl differs from what we already have in Faker? That would make it easier to see discrepancies, and loop in native speakers if needed to see why.

2024-05-19 05:45 UTC, sossost commented
@matthewmayer 
That seems like a good idea. Can someone please help?? I have other things to do, so it might take some time.

2024-05-19 08:45 UTC, matthewmayer commented
Here are the discrepancies i could find, for "wide" data (the abbr/short data has more variation), ignoring case-only differences and ignoring data where Intl doesnt seem to provide correct data eg dv and sr_RS_latin.

| data | type | locale | Faker | Intl |
| --- | --- | --- | --- | --- |
| weekday | wide | fa | پتچشنبه,جمعه,چهارشنبه,دوشنبه,سه شنبه,شنبه,یکشنبه| پنجشنبه,جمعه,چهارشنبه,دوشنبه,سه‌شنبه,شنبه,یکشنبه
| weekday | wide | he | יום חמישי,יום ראשון,יום רביעי,יום שישי,יום שלישי,יום שני,שבת| יום חמישי,יום ראשון,יום רביעי,יום שבת,יום שישי,יום שלישי,יום שני
| weekday | wide | pt_BR | Domingo,Quarta,Quinta,Sábado,Segunda,Sexta,Terça| domingo,quarta-feira,quinta-feira,sábado,segunda-feira,sexta-feira,terça-feira
| weekday | wide | pt_PT | Domingo,Quarta,Quinta,Sábado,Segunda,Sexta,Terça| domingo,quarta-feira,quinta-feira,sábado,segunda-feira,sexta-feira,terça-feira
| weekday | wide | ur | اتور,بدھ,پیر,جمعرات,جمعہ,منگل,ہفتہ| اتوار,بدھ,پیر,جمعرات,جمعہ,منگل,ہفتہ
| weekday | wide | zh_CN | 星期二,星期六,星期三,星期四,星期天,星期五,星期一| 星期二,星期六,星期日,星期三,星期四,星期五,星期一
| weekday | wide | zh_TW | 星期一,星期二,星期三,星期五,星期六,星期天,星期四| 星期一,星期二,星期三,星期五,星期六,星期日,星期四
| month | wide | ar | آب,آذَار,أَيَّار,أَيْلُول,تِشْرِين ٱلْأَوَّل,تِشْرِين ٱلثَّانِي,تَمُّوز,حَزِيرَان,شُبَاط,كَانُون ٱلْأَوَّل,كَانُون ٱلثَّانِي,نَيْسَان| أبريل,أغسطس,أكتوبر,ديسمبر,سبتمبر,فبراير,مارس,مايو,نوفمبر,يناير,يوليو,يونيو
| month | wide | ur | اپریل,اکتوبر,اگست,جنوری,جولائ,جون,دسمبر,ستمبر,فروری,مارچ,مئ,نومبر| اپریل,اکتوبر,اگست,جنوری,جولائی,جون,دسمبر,ستمبر,فروری,مارچ,مئی,نومبر
| month | wide | uz_UZ_latin | Aprel,Avgust,Dekabr,Fevral,Iyul,Iyun,Mart,May,Noyabr,Oktyabr,Sentyabr,Yanvar| Aprel,Avgust,Dekabr,Fevral,Iyul,Iyun,Mart,May,Noyabr,Oktabr,Sentabr,Yanvar
| month | wide | vi | Tháng Ba,Tháng Bảy,Tháng Chín,Tháng Giêng,Tháng Hai,Tháng Mười,Tháng Mười Hai,Tháng Mười Một,Tháng Năm,Tháng Sáu,Tháng Tám,Tháng Tư| Tháng 1,Tháng 10,Tháng 11,Tháng 12,Tháng 2,Tháng 3,Tháng 4,Tháng 5,Tháng 6,Tháng 7,Tháng 8,Tháng 9

2024-05-19 09:29 UTC, ST-DDT commented on test/modules/date.spec.ts
> -
Please restore, as this tests a different aspect/the implementation itself.

2024-05-19 09:29 UTC, ST-DDT commented on test/modules/date.spec.ts
> -
Same here

2024-05-19 09:29 UTC, ST-DDT commented on test/modules/date.spec.ts
> +            });
IMO these tests are unrelated to the months counter and thus shouldn't be in here.

2024-05-19 09:29 UTC, ST-DDT commented on test/modules/date.spec.ts
> -        });
Same here

2024-05-19 09:29 UTC, ST-DDT commented on test/modules/date.spec.ts
> -
and here

2024-05-19 09:29 UTC, ST-DDT commented on test/modules/date.spec.ts
> +            });
And here

2024-05-19 09:29 UTC, ST-DDT commented on test/modules/date.spec.ts
> +const validIntlLocales = Object.entries(allLocales).filter(([locale]) => {
Instead of using allLocales here and creating the faker instance later manually, you could use `allFakers` instead.

https://github.com/faker-js/faker/blob/7dc8a18f0b906f959670627240a6e5600bf47b75/src/locale/index.ts#L148

Or if you generate the locale data for "all" locales anyway, then you could just check the locale data itself instead of deferring it to a new Faker instance.

````ts
expect(localeData.date.month.wide).toContain(month);
````

2024-05-19 09:29 UTC, ST-DDT commented on scripts/generate-date-for-locale.ts
Please integrate this script in the main generate locales script, if possible.

2024-05-19 09:29 UTC, ST-DDT commented on scripts/generate-date-for-locale.ts
> +  if (locale === 'dv') return;
Please integrate this in the isValidLocale check and use that check here instead.

2024-05-19 09:29 UTC, ST-DDT commented on scripts/generate-date-for-locale.ts
> +  if (locale === 'dv') return;
Same here

2024-05-19 09:29 UTC, ST-DDT commented on scripts/generate-date-for-locale.ts
> +  const fileContent: string = await readFile(weekdayPath, 'utf8');
Instead of reading, stripping and `eval`ing the file, you could `import(path)` it instead. Then you don't need an access check:

````ts
let storedContent: DateDefinition["weekday"];
try {
  const imported = await import("file:"+weekdayPath)
  storedContent = imported.default; 
} catch {
  storedContent = {};
}
````

2024-05-19 09:29 UTC, ST-DDT commented on scripts/generate-date-for-locale.ts
> +      new Intl.DateTimeFormat(validLocale, { weekday: 'long' }).format(date)
You could create the `Intl.DateTimeFormat`s outside of the loop.

2024-05-19 09:29 UTC, ST-DDT commented on scripts/generate-date-for-locale.ts
> +  const validLocale: string = isValidLocale(locale) ? locale : 'en';
Please no fallbacks to en if it isn't valid, just skip it.

2024-05-19 09:29 UTC, ST-DDT commented on scripts/generate-date-for-locale.ts
> +export default ${JSON.stringify(storedWeekdays, null, 2)};`;
Please pass the data to `normalizeDataRecursive(oldData)` before saving the data to disk.
(The might might have to be extracted from its current location to be a standalone function)

https://github.com/faker-js/faker/blob/7dc8a18f0b906f959670627240a6e5600bf47b75/scripts/generate-locales.ts#L289

2024-05-19 09:29 UTC, ST-DDT commented on scripts/generate-date-for-locale.ts
> +async function createDateFolderAndIndex(locale: string): Promise<void> {
Please use `generateLocalesIndexFile` instead (after generating the weekday and month files).

https://github.com/faker-js/faker/blob/7dc8a18f0b906f959670627240a6e5600bf47b75/scripts/generate-locales.ts#L156

2024-05-19 09:29 UTC, ST-DDT commented on scripts/generate-date-for-locale.ts
> +    if (localeStat.isDirectory()) {
Please only generate the folder, if the script is able to generate data for it.

2024-05-19 10:34 UTC, Mirazyzz commented
> Here are the discrepancies i could find, for "wide" data (the abbr/short data has more variation), ignoring case-only differences and ignoring data where Intl doesnt seem to provide correct data eg dv and sr_RS_latin.
> 
> data	type	locale	Faker	Intl
> weekday	wide	fa	پتچشنبه,جمعه,چهارشنبه,دوشنبه,سه شنبه,شنبه,یکشنبه	پنجشنبه,جمعه,چهارشنبه,دوشنبه,سه‌شنبه,شنبه,یکشنبه
> weekday	wide	he	יום חמישי,יום ראשון,יום רביעי,יום שישי,יום שלישי,יום שני,שבת	יום חמישי,יום ראשון,יום רביעי,יום שבת,יום שישי,יום שלישי,יום שני
> weekday	wide	pt_BR	Domingo,Quarta,Quinta,Sábado,Segunda,Sexta,Terça	domingo,quarta-feira,quinta-feira,sábado,segunda-feira,sexta-feira,terça-feira
> weekday	wide	pt_PT	Domingo,Quarta,Quinta,Sábado,Segunda,Sexta,Terça	domingo,quarta-feira,quinta-feira,sábado,segunda-feira,sexta-feira,terça-feira
> weekday	wide	ur	اتور,بدھ,پیر,جمعرات,جمعہ,منگل,ہفتہ	اتوار,بدھ,پیر,جمعرات,جمعہ,منگل,ہفتہ
> weekday	wide	zh_CN	星期二,星期六,星期三,星期四,星期天,星期五,星期一	星期二,星期六,星期日,星期三,星期四,星期五,星期一
> weekday	wide	zh_TW	星期一,星期二,星期三,星期五,星期六,星期天,星期四	星期一,星期二,星期三,星期五,星期六,星期日,星期四
> month	wide	ar	آب,آذَار,أَيَّار,أَيْلُول,تِشْرِين ٱلْأَوَّل,تِشْرِين ٱلثَّانِي,تَمُّوز,حَزِيرَان,شُبَاط,كَانُون ٱلْأَوَّل,كَانُون ٱلثَّانِي,نَيْسَان	أبريل,أغسطس,أكتوبر,ديسمبر,سبتمبر,فبراير,مارس,مايو,نوفمبر,يناير,يوليو,يونيو
> month	wide	ur	اپریل,اکتوبر,اگست,جنوری,جولائ,جون,دسمبر,ستمبر,فروری,مارچ,مئ,نومبر	اپریل,اکتوبر,اگست,جنوری,جولائی,جون,دسمبر,ستمبر,فروری,مارچ,مئی,نومبر
> month	wide	uz_UZ_latin	Aprel,Avgust,Dekabr,Fevral,Iyul,Iyun,Mart,May,Noyabr,Oktyabr,Sentyabr,Yanvar	Aprel,Avgust,Dekabr,Fevral,Iyul,Iyun,Mart,May,Noyabr,Oktabr,Sentabr,Yanvar
> month	wide	vi	Tháng Ba,Tháng Bảy,Tháng Chín,Tháng Giêng,Tháng Hai,Tháng Mười,Tháng Mười Hai,Tháng Mười Một,Tháng Năm,Tháng Sáu,Tháng Tám,Tháng Tư	Tháng 1,Tháng 10,Tháng 11,Tháng 12,Tháng 2,Tháng 3,Tháng 4,Tháng 5,Tháng 6,Tháng 7,Tháng 8,Tháng 9
> i think you really need a language speaker to check these manually. For example, in Chinese which I do know, both 星期天 and 星期日 are both perfectly valid words for "Sunday".
> 
> In Vietnamese it looks like we are spelling out the month numbers versus using digits.
> 
> In Uzbek there seems to be some debate about the correct transliteration for September and October - see https://daryo.uz/2018/01/15/sentabr-yoziladimi-yoki-sentyabr , perhaps @Mirazyzz can help clarify!

Month names are derived from Russian, and therefore IMO the proper usage would be "sentYAbr" to reflect the Russian "сентЯбрь." Since there is no direct equivalent of the letter "Я" in our language, we use the combination of "Y" and "A." However, the debate on this matter is still ongoing, and no official approach has been decided yet. Interestingly, some official school books use both variations on different pages.

Given this uncertainty, I suggest we choose the variation that minimizes our workload and simplifies our process.

2024-05-19 12:27 UTC, ST-DDT reviewed
Thanks for reverting some of the test changes, this makes the tests way easier to review.

2024-05-19 12:27 UTC, ST-DDT commented on test/modules/date.spec.ts
> +  if (locale === 'dv') return false;
Maybe add a comment why `dv` is always false.

2024-05-19 12:47 UTC, xDivisionByZerox commented on scripts/generate-date-for-locale.ts
> +export default ${JSON.stringify(storedWeekdays, null, 2)};`;
`normalizeDataRecursive` is a scoped fucntion in `normalizeLocaleFile`. Your suggestion will not work out of the box.

2024-05-19 12:51 UTC, xDivisionByZerox commented on scripts/generate-date-for-locale.ts
I thought this script was a one time thing? The issues scope is to create test, not extend the generation script. Am I missing something?

2024-05-19 12:55 UTC, ST-DDT commented on scripts/generate-date-for-locale.ts
My idea is, that since we have tests that allow only certain values, we just let them generate automatically.
That way we don't have to manually update the values, if the Intl data ever get updated.

I do consider the script to be optional to this PR, but if it is contained as part of the PR, it should be part of the main generate locale script.

2024-05-19 13:38 UTC, sossost commented
@ST-DDT I have updated the code you reviewed. Thank you very much for your kind and detailed review. Thanks to you, I am learning a lot.

2024-05-19 15:15 UTC, ST-DDT reviewed
Please run `pnpm run preflight` to verify the script passes without errors.

2024-05-19 15:15 UTC, ST-DDT commented on scripts/generate-locales.ts
> +
```suggestion
```

2024-05-19 15:15 UTC, ST-DDT commented on scripts/generate-locales.ts
> + * - `src/locales/<locale>/date/weekDay.ts`
```suggestion
 * - `src/locales/<locale>/date/weekday.ts`
```

2024-05-19 15:15 UTC, ST-DDT commented on scripts/generate-locales.ts
> +  let storedWeekdays: { wide: string[]; abbr: string[] } = {
If possible, please use the exact type `DateDefinition["weekday"]`/`DateEntryDefinition `. Maybe use `Partial<...>` to simplify the init part, the required values are set later anyway.

https://github.com/faker-js/faker/blob/7dc8a18f0b906f959670627240a6e5600bf47b75/src/definitions/date.ts#L21

2024-05-19 15:15 UTC, ST-DDT commented on scripts/generate-locales.ts
> +  await writeFile(monthPath, await formatTypescript(updatedContent));
```suggestion
  return writeFile(monthPath, await formatTypescript(updatedContent));
```

2024-05-19 15:15 UTC, ST-DDT commented on scripts/generate-locales.ts
> +  await writeFile(weekdayPath, await formatTypescript(updatedContent));
```suggestion
  return writeFile(weekdayPath, await formatTypescript(updatedContent));
```

2024-05-19 15:15 UTC, ST-DDT commented on scripts/generate-locales.ts
> +export default ${JSON.stringify(normalizedMonths, null, 2)};`;
The following hopefully fixes the code highlighting in the browser.

```suggestion
  const updatedContent = `
    ${autoGeneratedCommentHeader}
    export default ${JSON.stringify(normalizedMonths, null, 2)};
    `;
```

2024-05-19 15:15 UTC, ST-DDT commented on scripts/generate-locales.ts
> +export default ${JSON.stringify(normalizedWeekdays, null, 2)};`;
```suggestion
  const updatedContent = `
    ${autoGeneratedCommentHeader}
    export default ${JSON.stringify(normalizedWeekdays, null, 2)};
    `;
```

2024-05-19 15:15 UTC, ST-DDT commented on scripts/generate-locales.ts
> +async function updateWeekdaysForLocale(locale: string): Promise<void> {
The other methods don't have the `forLocale` suffix.
So maybe rename this to `generateWeekdayFile`?

2024-05-19 15:15 UTC, ST-DDT commented on scripts/generate-locales.ts
> +async function updateMonthForLocale(locale: string): Promise<void> {
The other methods don't have the `forLocale` suffix.
So maybe rename this to `generateMonthFile`?

2024-05-19 15:15 UTC, ST-DDT commented on scripts/generate-locales.ts
> +    updateWeekdaysForLocale(locale),
These either need to check for or create the `date` folder.

Due to the complexity/dependencies on each step maybe create a separate method like this:

````ts
async function generateDateModule(locale) {
  if (!isValidLocale(locale)) return;
  await mkdir(pathDate);
  await generateWeekdayFile(locale);
  await generateMonthFile(locale);
  return generateRecursiveModuleIndexes(pathDate?, locale, 'DateDefinition', 2)
}
````

`pathDate` is used multiple times, so we might as well create a const for it next to the other path constants:

https://github.com/faker-js/faker/blob/7263f0d93ef748d9901732a4e6c593f7615209c9/scripts/generate-locales.ts#L30-L34

2024-05-19 15:15 UTC, ST-DDT commented on scripts/generate-locales.ts
> +export default ${JSON.stringify(normalizedWeekdays, null, 2)};`;
On the other hand I just thought about the `autoGeneratedCommentHeader`. It might be confusing, since the file is only partially auto generated.
Should we have an adjusted comment or should we skip the comment?

2024-05-20 00:25 UTC, matthewmayer requested changes
Note the script currently:
* Creates unnecessary definitions for all descendant locales, e.g. en_AU, en_GB, en_HK when these should probably just inherit from en.
* Creates definitions for base locale, which it shouldn't
* Doesn't make seperate arrays for wide and wide_context or abbr and abbr_context in locales where these are different e.g. `fr` or `ru` - see documentation of "context" parameter at https://fakerjs.dev/api/date#month
* Adds English data for certain locales where Intl has no data like yo_NG and zu_ZA

2024-05-20 12:10 UTC, sossost commented
@ST-DDT I have updated it to reflect the parts you reviewed. ynnsuis is my company account.

2024-05-20 19:44 UTC, ST-DDT commented
I reduced the diff a bit, fixed an issue with the `date/index.ts` generation and generated the missing files for preview.
Sorry, for directly interfering with your PR.

2024-05-20 19:57 UTC, ST-DDT commented
> * Creates unnecessary definitions for all descendant locales, e.g. en_AU, en_GB, en_HK when these should probably just inherit from en.
> * Creates definitions for base locale, which it shouldn't

Currently, it does not because `Intl` uses `de-de` and we use `de_DE`.
This might have to be changed and then filtered for redundancy though.

@sossost Could you please fix that? (Please pull before changing any code)

> * Doesn't make seperate arrays for wide and wide_context or abbr and abbr_context in locales where these are different e.g. `fr` or `ru` - see documentation of "context" parameter at [fakerjs.dev/api/date#month](https://fakerjs.dev/api/date#month)

I'm not sure whether I get you correctly here. The context variants arent touched or generated because AFAIK there is no Intl way to do that.

2024-05-21 00:54 UTC, sossost commented
@ST-DDT No! thank you Actually, this is a bit of a difficult issue for me because I still lack a lot. Thank you very much for your direct and indirect help.

2024-05-22 13:05 UTC, sossost commented
> > * Creates unnecessary definitions for all descendant locales, e.g. en_AU, en_GB, en_HK when these should probably just inherit from en.
> > * Creates definitions for base locale, which it shouldn't
> 
> Currently, it does not because `Intl` uses `de-de` and we use `de_DE`. This might have to be changed and then filtered for redundancy though.
> 
> @sossost Could you please fix that? (Please pull before changing any code)
> 
> > * Doesn't make seperate arrays for wide and wide_context or abbr and abbr_context in locales where these are different e.g. `fr` or `ru` - see documentation of "context" parameter at [fakerjs.dev/api/date#month](https://fakerjs.dev/api/date#month)
> 
> I'm not sure whether I get you correctly here. The context variants arent touched or generated because AFAIK there is no Intl way to do that.

Sorry I didn't understand exactly what to do. Can you give me more hints??

2024-05-22 13:29 UTC, ST-DDT commented
> Sorry I didn't understand exactly what to do. Can you give me more hints??

1. Replace all

````ts
new Intl.DateTimeFormat({ locale, ...});
````

With

````ts
new Intl.DateTimeFormat({ locale: locale.replaceAll('_', '-'), ...});
````

2. Find all instances where locale.date.weekday/month is the same as the parent locale. E.g. en is the parent of en_US and thus the locale files would be identical so it should be skipped/not created.

2024-05-23 17:58 UTC, ST-DDT reviewed
Thanks for your help. Please let us know, if this is getting to complicated/time consuming for you.

2024-05-23 17:58 UTC, ST-DDT commented on scripts/generate-locales.ts
> +    new Intl.DateTimeFormat(locale);
This also needs the locale transformation.

2024-05-23 17:58 UTC, ST-DDT commented on scripts/generate-locales.ts
> +function isValidLocale(locale: string): boolean {
I thought about moving or inlining this function inside the generateDateModule function (because it is only used there once).

Then you could store the `intlLocale` as a const and use it everywhere instead of replacing it over and over again.

2024-05-23 17:58 UTC, ST-DDT commented on scripts/generate-locales.ts
> +  async function isParentLocaleSame(
This function assumes that the parent and this file already  exists, the idea was that the child file is skipped/never created if the parent is present, unless it has different content.

So maybe change the check to this:

````ts
function shouldGenerate(): boolean {
  if (exists(thisFile)) return true;
  if (!exists(parentFile)) return true;
  if (any Intl(parentLocale).short !== Intl(thisLocale).short) return true;
  [...]
  return false;
}
````

Please note that `parentFile` might refer to more than one file: `en_AU_ocker` -> `en_AU` -> `en`.

See here for the fallback check:

https://github.com/faker-js/faker/blob/b97984c7a165df0b516cbba0806b7cd68d77fc52/scripts/generate-locales.ts#L115-L126

2024-05-24 00:28 UTC, matthewmayer commented
With a big thanks to @sosost for their work so far, but I'm starting to feel trying to do this as a script that generates everything at once is maybe a mistake. 

Instead perhaps we can modify it so it's run manually and you give it a single locale as a parameter, and it attempts to generate the days and months for that locale only. 

That way we don't need to code in lots of edge cases, and it's easy to run it for missing locales, and review the diff for one locale at a time. 

Once generated, it's not like the days of the week or months of the year will ever change ...

2024-05-24 14:06 UTC, sossost commented on scripts/generate-locales.ts
> +  async function isParentLocaleSame(
@ST-DDT thank you The two parts above were reflected and committed. However, I think this work will take some time because I am busy. I would appreciate it if you could finish the work if you wish.

2024-06-12 15:06 UTC, ST-DDT commented
Sorry, for the delay. I will tackle this once I have some free time.

2024-06-18 22:03 UTC, ST-DDT commented
Ready for review.

This can be easily reviewed by:

````sh
rm -rdf src/locales
git reset next -- src/locales
git restore src/locales

pnpm run preflight

git add src/locales
````

2024-06-18 22:03 UTC, ST-DDT approved these changes

2024-06-19 00:08 UTC, matthewmayer requested changes
I dont think this should be part of preflight

As we learned in #2906 ICU  data is not stable so we could easily have the situation where this generate different dates on different versions of node. 

I think it'll be better to have this as a separate standalone script that can be run on demand to check the data and fill in missing locales, but any discrepancies in existing locales should be checked by a native speaker.

2024-06-19 05:26 UTC, ST-DDT commented
Added to the meeting notes for discussion.

2024-06-19 07:46 UTC, matthewmayer commented
I tested with Node 20.0.0 and 22.2.0. There are differences in data for en-AU, eo, es-MX, mk, uk and vi. Mostly minor things like tweaks to the shortened versions, capitalization etc. But enough to cause havoc with people running preflight with different node versions.

2024-06-20 16:32 UTC, ST-DDT commented
**Team Notice**

We talked about it in the team meeting, but we haven't been able to decide anything yet.

2024-10-26 14:37 UTC, ST-DDT commented
**Team Decision**

- We will not merge this, as it
  - the data changes frequently
  - it breaks our CI tests
  - any variant of "only generating the data" produces unpredictable results depending on the used node version
- The data are easier to manually insert than describing how to run the custom script

Thanks for your contribution anyway ❤️

2024-10-26 14:37 UTC, closed without merging