refactor(helpers)!: fail on invocations on non-functions
faker-js/faker pull request #2913
Opened 2024-05-18 15:56 UTC by ST-DDT

This PR changes the behavior of fake to be more consistent with standard JS behavior.

```ts
faker.helpers.fake('{{person.first_name()}}'); // 'Jenny'
```

Now fails with an exception:

```txt
FakerError: Cannot resolve expression 'person.first_name()'
```

---

This PR is part of an attempt to solve some of the TODOs in our source code.

2024-05-18 15:56 UTC, ST-DDT commented on docs/guide/upgrading.md
> +faker.helpers.fake('{{person.first_name()}}''); // 'Jenny'
```suggestion
faker.helpers.fake('{{person.first_name()}}'); // 'Jenny'
```

2024-05-19 11:27 UTC, matthewmayer requested changes
I don't really like introducing this change suddenly as it's likely to only be found at runtime. 

If we don't want to support this syntax any more I think we could log a warning in v9 and error in v10 instead.

2024-05-23 15:51 UTC, ST-DDT commented
**Team Decision**

- We forgot about the deprecation -> deprecate now and "remove" in v10

2024-06-12 14:16 UTC, ST-DDT commented
Fixed - ready for review

2024-06-13 10:10 UTC, xDivisionByZerox commented on src/modules/helpers/eval.ts
> +          deprecated: 'Calling functions on non-functions',
Maybe:

```suggestion
          deprecated: 'Invoking expressions which are not functions',
```

Should we log the expression which got falsely invoked? That would help clearify the warning for users. Since this block is in a "map" function, it might be triggered multiple times without additional value.

2024-06-13 11:40 UTC, Shinigami92 commented
Having a chore! is invalid 🤔 either it did not change runtime behavior or it is a breaking change 👀

2024-06-13 11:41 UTC, matthewmayer commented on src/modules/helpers/eval.ts
> +          deprecated: 'Calling functions on non-functions',
I agree that the current error is probably going to be pretty confusing to end users

If I previously had code like 
```
faker.helpers.fake('{{person.first_name() {{person.lastName()}}'); I will probably need guidance as to what is wrong.

2024-06-13 11:44 UTC, matthewmayer commented
I think it's no longer breaking so ! Should be removed but it should get a brief write up at the bottom of the migration guide.

2024-06-13 18:17 UTC, ST-DDT commented on src/modules/helpers/eval.ts
> +          deprecated: 'Calling functions on non-functions',
Should be fixed now.

2024-06-13 18:18 UTC, ST-DDT commented
Example log:

````txt
[@faker-js/faker]: Invoking expressions which are not functions is deprecated since v9.0 and will be removed in v10.0.
Please remove the parenthesis or replace the expression with an actual function.
person.first_name()
                 ^
````

2024-06-13 18:28 UTC, xDivisionByZerox approved these changes, later dismissed

2024-06-13 20:30 UTC, Shinigami92 approved these changes, later dismissed

2024-06-13 23:44 UTC, matthewmayer commented on src/modules/helpers/eval.ts
> +Please remove the parenthesis or replace the expression with an actual function.
```suggestion
Please remove the parentheses or replace the expression with an actual function.
```
Plural

2024-06-14 07:54 UTC, xDivisionByZerox approved these changes

2024-06-14 12:17 UTC, Shinigami92 approved these changes

2024-06-14 13:20 UTC, matthewmayer approved these changes

2024-06-14 13:24 UTC, merged