used singular local keys for issue #2911
faker-js/faker pull request #2932
Opened 2024-06-01 09:41 UTC by SaurabhXRT

### Overview

This PR addresses issue #2911 by standardizing the locale definition keys to use singular naming. This change improves consistency across the codebase and aligns with the team decision discussed in the issue.

### Changes

- Renamed `words` to `word`
- Renamed `directory_paths` to `directory_path`
- Renamed `mime_types` to `mime_type`
- Updated all references and documentation to reflect these changes

### Testing

- Ran all existing tests to ensure no breakage
- Updated tests where necessary to match the new naming convention

### Additional Notes

Please review the changes and let me know if any further updates are needed.

2024-06-01 09:48 UTC, ST-DDT requested changes

2024-06-01 09:48 UTC, ST-DDT commented on src/locales/ar/lorem/index.ts
> +import word from './words';
You have to rename the files as well, because these files are auto generated.

2024-06-01 09:52 UTC, ST-DDT commented
Also please edit this section and add the renames:

https://github.com/faker-js/faker/blob/next/docs/guide/upgrading.md#renamed-locale-definitions

2024-06-01 09:54 UTC, SaurabhXRT commented on src/locales/ar/lorem/index.ts
> +import word from './words';
Thank you for pointing that out. I will proceed to rename the files to align with the singular naming convention.

2024-06-01 10:33 UTC, SaurabhXRT commented on src/locales/ar/lorem/index.ts
> +import word from './words';
I have renamed the file also and upgraded the upgrading.md file.

2024-06-01 11:12 UTC, ST-DDT commented
Please make sure to run `pnpm run preflight`

2024-06-01 11:46 UTC, xDivisionByZerox requested changes

2024-06-01 11:46 UTC, xDivisionByZerox commented on docs/guide/upgrading.md
> +The following locale definitions have been renamed to use singular keys and file names:
The information that the file names have changed should not be relevant to the end user. I think a more generic description would be fitting here.

```suggestion
The following locale definitions have been adjusted to align with fakers locale definition naming standard:
```

The title of this section should propably also be changed too 🤔

2024-06-01 12:34 UTC, SaurabhXRT commented on docs/guide/upgrading.md
> +The following locale definitions have been renamed to use singular keys and file names:
I have run but I am getting this error " ERR_PNPM_READ_FROM_STORE  Unexpected token '', ""... is not valid JSON".
I am figuring out the error after that I will update.

2024-06-05 16:30 UTC, SaurabhXRT commented
hey @matthewmayer i have some doubt i am facing error how can i connect with you ?

2024-06-05 19:44 UTC, ST-DDT commented on test/modules/lorem.spec.ts
>          );
Line 109: 

````diff
- expect(faker.definitions.lorem.words).toContain(word);
+ expect(faker.definitions.lorem.word).toContain(word);
````

2024-06-07 08:51 UTC, ST-DDT commented on docs/guide/upgrading.md
> +| Old                                         | Replacement                                  |
The other tables use locercase headers as well.

```suggestion
| old                                         | replacement                                  |
```

2024-06-07 08:51 UTC, ST-DDT commented on pnpm-lock.yaml
Please revert the change to this file.

2024-06-07 08:56 UTC, ST-DDT commented
Two more small changes and then this is good to go.

2024-06-07 10:02 UTC, matthewmayer commented on docs/guide/upgrading.md
> +The following locale definitions have been adjusted to align with fakers locale definition naming standard:
```suggestion
The following locale definitions have been adjusted to align with Faker's locale definition naming standard:
```

2024-06-10 06:50 UTC, SaurabhXRT commented on pnpm-lock.yaml
I didnt change anything in the pnpm-lock.yml I accidentally deleted that file so i have to add that again.

2024-06-10 08:24 UTC, matthewmayer submitted a review, later dismissed

2024-06-10 21:22 UTC, ST-DDT approved these changes

2024-06-11 09:25 UTC, matthewmayer approved these changes

2024-06-13 10:11 UTC, xDivisionByZerox approved these changes

2024-06-13 10:14 UTC, merged

2024-06-13 10:38 UTC, xDivisionByZerox commented
@SaurabhXRT Thank you for your contribution ❤️