feat(internet): add jwt method
faker-js/faker pull request #2936
Opened 2024-06-04 10:24 UTC by eLoyyyyy

Closes #1282

2024-06-04 11:00 UTC, ST-DDT reviewed
Could you please also comment in the linked issue so we can assign it to you so it easier to see that the issue is being worked on?

2024-06-04 11:00 UTC, ST-DDT commented on src/modules/internet/index.ts
> +  }): string {
We usually default the options object to an empty object in the method parameters.

```suggestion
  } = {}): string {
```

2024-06-04 11:00 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    const refDate = options?.refDate ?? this.faker.defaultRefDate();
We usually deconstruct the options object like this:

https://github.com/faker-js/faker/blob/badaa6d60593fe41a1afa0e9a8bef6ae5bb8a352/src/modules/date/index.ts#L95

I think you can apply the same to header options.

2024-06-04 11:00 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    const header = {
> We will have header and payload options that replace the default values

If the header option is present, it will replace the header that is generated by default.

````ts
const { header = { alg: this.jwtAlgorithm(), typ: 'JWT' }} = options.
````

2024-06-04 11:00 UTC, ST-DDT commented on src/modules/internet/index.ts
> +            ),
This should probably be it's own `jwtAlgorithm` method.

2024-06-04 11:00 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    const payload = {
Same here as with the header.

2024-06-05 20:09 UTC, ST-DDT requested changes

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +export type JwtAlgorithmType = 'alg';
I'm not sure this is needed here.

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * Generates a random JWT Algorithm
```suggestion
   * Generates a random JWT (JSON Web Token) Algorithm.
```

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * @since 8.0.0
```suggestion
   * @since 9.0.0
```

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +  jwtAlgorithm(): string {
Maybe add a `@see` link to jwt and vice versa.

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * @param options Options object.
```suggestion
   * @param options The optional options object.
```

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * @param options.header Header part of the token.
```suggestion
   * @param options.header The Header to use for the token. Defaults to a random object with the following fields: ...
```

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * @param options.payload Payload part of the token.
```suggestion
   * @param options.payload The Payload to use for the token. Defaults to a random object with the following fields: ...
```

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * faker.internet.jwt({ payload: { iss: 'Acme', sub: 'Subject', aud: 'Audience', jti: 'JWT ID' }})
IMO One example for `payload` is sufficient.

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * faker.internet.jwt({ header: { alg: 'HS256' }})
maybe also add an example with a refDate

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      };
Maybe this should accept any object?

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      };
Maybe this should accept any object?

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +        type: 'JWT',
```suggestion
        typ: 'JWT',
```

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +       * Header part of the token
```suggestion
       * The Header to use for the token. If present, it will replace any default values.
       *
       * @default { alg: faker.internet.jwtAlgorithm(), typ: 'JWT' }
```

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +       * Payload part of the token.
```suggestion
       * The Header to use for the token. If present, it will replace any default values.
       *
       * @default { iat, ... }
```

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    const encodedHeader = Buffer.from(JSON.stringify(header)).toString(
The `Buffer` API seems to be missing in browsers.
Or is it just my test setup?

2024-06-05 20:09 UTC, ST-DDT commented on test/modules/internet.spec.ts
> +        .it('with header.alg', { header: { alg: 'ES256' }, refDate })
```suggestion
        .it('with custom header', { header: { alg: 'ES256' }, refDate })
```

2024-06-05 20:09 UTC, ST-DDT commented on test/modules/internet.spec.ts
> +        .it('with payload.jti', { payload: { jti: 'jwt id' }, refDate });
One is probably enough

```suggestion
        .it('with custom payload', { payload: { iss: 'Acme' }, refDate });
```

2024-06-05 20:09 UTC, ST-DDT commented on test/modules/internet.spec.ts
> +        });
```suggestion
          expect(jwt).toBeTypeOf('string');
          expect(jwt).toSatisfy(validator.isJWT);
        });
```

2024-06-05 20:09 UTC, ST-DDT commented on test/modules/internet.spec.ts
> +      });
Please add a test with custom header and payload and ensure the values are actually present in the result.

````ts
const header = ...;
const payload = ...;

const actual = faker.internet.jwt({header, payload});

expect(actual).toBeTypeOf('string');
expect(actual).toSatisfy(validator.isJWT);

const parts = actual.split(3);

expect(parts[0]).toBe(Buffer.....)
expect(parts[1]).toBe(Buffer.....)
````

2024-06-05 20:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * @since 8.0.0
```suggestion
   * @since 9.0.0
```

2024-06-10 10:06 UTC, eLoyyyyy commented on src/modules/internet/index.ts
> +    const encodedHeader = Buffer.from(JSON.stringify(header)).toString(
I don't think there's a `Buffer` API in browsers. Best I saw was `ArrayBuffer` https://caniuse.com/?search=ArrayBuffer

2024-06-10 10:22 UTC, eLoyyyyy commented on src/modules/internet/index.ts
> +      };
I agree. But I can't find any reference that I can follow that allows any object but documents the default.

2024-06-10 10:41 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      };
Have you tried `Partial<{}> & Record<string, unknown>`?

2024-06-10 11:05 UTC, eLoyyyyy commented on src/modules/internet/index.ts
> +      };
This is what I have so far:
```ts
type JwtDefaultPayload<T> = T extends undefined
  ? Record<'iss' | 'sub' | 'aud' | 'jti', unknown>
  : T
```

2024-06-10 11:05 UTC, eLoyyyyy commented on src/modules/internet/index.ts
> +      };
> Have you tried `Partial<{}> & Record<string, unknown>`?

I'll try this. Thank you.

2024-06-10 11:25 UTC, ST-DDT commented on test/modules/internet.spec.ts
> +            iss: faker.string.alphanumeric()
Please add a key here that isnt part of the default key set. Same for header.

2024-06-10 22:52 UTC, ST-DDT reviewed
Other than the following minor issues and the `Buffer` issue above, this looks good to me.

2024-06-10 22:52 UTC, ST-DDT commented on src/definitions/internet.ts
> +  jwt: Record<'alg', string[]>;
Please add a minimalistic jsdocs description.

And maybe use an object instead of a record:

```suggestion
  jwt: {
    /** 
     * description
     */
    algorithm: string[]
  }
```

Not sure about whether we have to nest the jwt object here at all. I have to think about that some more.

2024-06-10 22:52 UTC, ST-DDT commented on src/modules/internet/index.ts
> +       * @default
```suggestion
       * The Header to use for the token. If present, it will replace any default values.
       *
       * @default
```

2024-06-10 22:52 UTC, ST-DDT commented on src/modules/internet/index.ts
> +       * @default
```suggestion
       * The Payload to use for the token. If present, it will replace any default values.
       *
       * @default
```

2024-06-10 23:09 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    const encodedHeader = Buffer.from(JSON.stringify(header)).toString(
We could the following method instead of the `Buffer`, that should work for our usecase:

````ts
function toBase64Url(input: string): string {
    // Convert UTF-8 string to a Uint8Array
    const utf8Bytes = new TextEncoder().encode(input);
    // Convert Uint8Array to binary string
    const binaryString = Array.from(utf8Bytes).map(byte => String.fromCharCode(byte)).join('');
    // Base64 encode the binary string
    const base64 = btoa(binaryString);
    // Convert base64 to base64url
   return base64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
````

2024-06-10 23:10 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    const encodedHeader = Buffer.from(JSON.stringify(header)).toString(
@faker-js/maintainers Is there a way to fail the CI if APIs are used that aren't available in all environments?

2024-06-11 07:26 UTC, xDivisionByZerox commented on src/modules/internet/index.ts
> +    const encodedHeader = Buffer.from(JSON.stringify(header)).toString(
I can have a look into this. My first thought would be to set up a "mock" application in the browser that uses faker and will be tested with cypress (or other e2e frameworks). 
That would be a lot of overhead, tho. Preferably, typescript would fail when transpil8ng "to browser".

2024-06-13 10:15 UTC, eLoyyyyy commented on src/definitions/internet.ts
> +  jwt: Record<'alg', string[]>;
I agree. I just removed the nesting, for now.

2024-06-13 10:48 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    const encodedHeader = Buffer.from(JSON.stringify(header)).toString(
Lets use the workaround `toBase64Url` for now.
I think we can add it as a new file to `src/internal` or `src/modules/internet`.

2024-06-13 11:42 UTC, Shinigami92 commented
is this up for review? or should I wait a bit?

2024-06-13 16:54 UTC, ST-DDT commented on src/modules/internet/util.ts
Please fix the lint issues in this file.

2024-06-14 20:14 UTC, xDivisionByZerox requested changes
Good work so far 👍

2024-06-14 20:14 UTC, xDivisionByZerox commented on src/locales/base/internet/jwt_algorithm.ts
"none" would actually be a valid "alg" header parameters according to [RFC 7518 - Section 3.6](https://datatracker.ietf.org/doc/html/rfc7518#section-3.6). 
I'm not sure if we should include it. I just wanted to raise awareness. What do others think?

2024-06-14 20:14 UTC, xDivisionByZerox commented on src/definitions/internet.ts
> +  jwt_algorithm: string[];
This question is propably stupid, seeing aboth that HTTP status codes have their own entry:
Why do we put the algorithms in the locales instead of coupling them to the internet module?

While I understand that the current setup allows for custom locale overrides, I'm curious if this is a common scenario. I would rather think this being an issue in most cases. When I proposed the original prototype API I had in mind that this API should be minimal yet as closely aligned with the public standard, while maintaing randomness. This would not be guaranteed when users could override these values.

Thoughts?

2024-06-14 20:14 UTC, xDivisionByZerox commented on src/modules/internet/util.ts
I'm leaning towards moving this file to `src/util/string.ts` (not sure about the file name). 

1. I don't see this file being only relevant for the internet module only (even if it is right now)
2. It may cause trouble when we split the module into separate function files in a later version (`internet/display-name.ts`, `internet/domain-name.ts`, etc).

2024-06-14 20:14 UTC, xDivisionByZerox commented on src/modules/internet/index.ts
> +       * };
All your default value are designed to be copy'pasted if read from the doc/JSDocs preview. The current syntax would be incorrect. At least to create an object that could be applied as an argument. Same goes for the header `@default` value.

```suggestion
       * {
       *    iat: faker.date.recent(),
       *    exp: faker.date.soon(),
       *    nbf: faker.date.anytime(),
       *    iss: faker.company.name(),
       *    sub: faker.string.uuid(),
       *    aud: faker.string.uuid(),
       *    jti: faker.string.uuid(),
       * };
```

2024-06-14 20:14 UTC, xDivisionByZerox commented on src/modules/internet/index.ts
> +   * faker.internet.jwt({ refDate: '2020-01-01T00:00:00.000Z' })
Our examples usually contain an example output value. This way a developer can immediatly see what values to expect. Since one of our core focuses on Faker is good DX, I think we should provide these here as well.

2024-06-14 20:14 UTC, xDivisionByZerox commented on src/modules/internet/index.ts
> +       * The Header to use for the token. If present, it will replace any default values.
```suggestion
       * The header to use for the token. If present, it will replace any default values.
```

2024-06-14 20:14 UTC, xDivisionByZerox commented on src/modules/internet/index.ts
> +       * The Payload to use for the token. If present, it will replace any default values.
```suggestion
       * The payload to use for the token. If present, it will replace any default values.
```

2024-06-14 20:14 UTC, xDivisionByZerox commented on src/modules/internet/index.ts
> +      header?: Record<string, unknown>;
We have a [`LiteralUnion`](https://github.com/faker-js/faker/blob/5f77d389a805c6527b489c699a0b517ca9b17739/src/utils/types.ts#L6-L8) that is like "any string but here are suggestion". Could we do the same for objects? That way the user **can** provide any values they want, but gets autocompletion for the most common fields? Same would apply for payload as well.

2024-06-14 20:14 UTC, xDivisionByZerox commented on src/modules/internet/index.ts
> +      },
I'm thinking about a merge strategy here instead of overriding the entire value if provided. A user that provides this is very likely to only override the "alg" property and might likely forget the "type" property.

2024-06-14 20:24 UTC, ST-DDT commented on src/locales/base/internet/jwt_algorithm.ts
Since we don't do anything with the value and don't expect our users to do anything with it either, both would work for me.

2024-06-14 20:26 UTC, ST-DDT commented on src/definitions/internet.ts
> +  jwt_algorithm: string[];
Currently we have most parts in the locales even if they are unlikely to change.
Maybe the user only supports a certain subset of algorithms, overwriting the locales would allow for reusing the default header.

2024-06-14 20:29 UTC, ST-DDT commented on src/modules/internet/util.ts
IMO this is an internal function so it should be in the internal folder.
How about `src/internal/base64.ts`?

2024-06-14 20:32 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      header?: Record<string, unknown>;
The question is whether the most common fields are useful for the user of the method or if an easier to read signature is more beneficial?
My point is, if the user is going to overwrite this value, they know which values they need and thus we don't have to suggest them ourselves.

2024-06-14 20:44 UTC, ST-DDT commented on src/modules/internet/index.ts
> +      },
Same as above, if they want specific fields, they will know which fields they want and only provide those.
If you think, that the placeholder values are important/useful to some, we could add a parameter for that:

- `default-header: 'replace' | 'merge' = random()`
- `default-payload: 'replace' | 'merge' = random()`

IMO there should be a way to not include the placeholder/default values.
What do you think?

2024-06-14 20:51 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * faker.internet.jwt({ refDate: '2020-01-01T00:00:00.000Z' })
Here an example of another method:

https://github.com/faker-js/faker/blob/5f77d389a805c6527b489c699a0b517ca9b17739/src/modules/lorem/index.ts#L229-L232

2024-06-14 21:07 UTC, xDivisionByZerox commented on src/definitions/internet.ts
> +  jwt_algorithm: string[];
The difference would be that moving other values would result in breaking changes. These don't. You think being consistent is more valuable than having to introduce breaking changes down the road? If thats the case, feel free to resolve this conversation. 👍

2024-06-14 21:13 UTC, xDivisionByZerox commented on src/modules/internet/util.ts
Interesting idea. By that definition (things from `src/util` are publically available), we would have to move `src/util/types.ts` into `src/internal/types.ts` as well, correct? (separate issue)

I'd be fine with your suggestion as it is better than mine. I'm still not super happy with the file name. Maybe we should clearify some architectur around the internal directory in a separate issue/team meeting (?).

2024-06-14 21:27 UTC, ST-DDT commented on src/definitions/internet.ts
> +  jwt_algorithm: string[];
IMO this isn't about consistency. We haven't inlined the mimeTypes (and wont do lorem) either because the user might want to overwrite it with a set that better suits their needs. The same applies here.
So I don't see the necessity of a (breaking) change later either.

2024-06-14 21:31 UTC, ST-DDT commented on src/modules/internet/util.ts
Added to the meeting notes.

2024-06-16 20:17 UTC, xDivisionByZerox commented on src/modules/internet/index.ts
> +      },
> IMO there should be a way to not include the placeholder/default values.

This argument makes sense to me. The current replace strategy is good enought for me.  
Having additional arguments that define the behaviour of the argument process feels incorrect to me.

2024-06-18 08:41 UTC, xDivisionByZerox commented
The formatting seems to be off in the documentation:

![image](https://github.com/faker-js/faker/assets/77127505/42e43f25-2f1a-4551-a379-64901e2cac71)

@ST-DDT does this problem originate from our documentation generation or is the current JSDoc not correctly formatted? Looks good to me.

---

@eLoyyyyy the test snapshots as well as some formatting needs to be updated. You can run `pnpm run preflight` to run CI locally before committing. That way you don't have to wait for results from CI. Alternativly, have a look at our [CONTRIBUTING Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md#important) for more information on how to fix common problems.

2024-06-18 09:00 UTC, ST-DDT commented
> The formatting seems to be off in the documentation:
> 
> ![image](https://private-user-images.githubusercontent.com/77127505/340604173-42e43f25-2f1a-4551-a379-64901e2cac71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDEzNzgsIm5iZiI6MTcxODcwMTA3OCwicGF0aCI6Ii83NzEyNzUwNS8zNDA2MDQxNzMtNDJlNDNmMjUtMmYxYS00NTUxLWEzNzktNjQ5MDFlMmNhYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA4NTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmY2VlZWJjYWVjZDY5MWZhNjA0ZmQwNDBiZmUzZWViNzU0NmQ5ZmJjMGM0OGEwYTNiODBlNTQ0YzgzOWZlM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pIW_73bXJgzosFaCz0YVu6Lt6K0fKFTp3hi_TqEJ1wc)

I dont see the problem. What would you expect?

2024-06-18 12:53 UTC, eLoyyyyy commented
> @eLoyyyyy the test snapshots as well as some formatting needs to be updated. You can run `pnpm run preflight` to run CI locally before committing. That way you don't have to wait for results from CI. Alternativly, have a look at our [CONTRIBUTING Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md#important) for more information on how to fix common problems.

Updated the test snapshots. My bad for not running preflight before pushing code.

2024-06-18 18:38 UTC, xDivisionByZerox reviewed
Looks really good. I have questions/suggestions for one last time.

2024-06-18 18:38 UTC, xDivisionByZerox commented on src/modules/internet/util.ts
> +  ).join('');
A little nitpicky, but if you have time this line can be written without creating a new function scope.

```suggestion
  const binaryString = Array.from(utf8Bytes, String.fromCodePoint).join('');
```

2024-06-18 18:38 UTC, xDivisionByZerox commented on src/modules/internet/util.ts
> + *
I suggest to add a desciption to the function with two essential details:

1. Emphasize that this function is tailored for handling JSON Web Tokens (JWTs), as outlined in [RFC 7515 - Appendix C](https://datatracker.ietf.org/doc/html/rfc7515#appendix-C). Alternatively, consider designing the function as a pure "to base 64" converter, with character replacement handled within the JWT-specific implementation.
2. Specify that this function is platform-agnostic, suitable for both browser and Node.js environments.

2024-06-18 18:44 UTC, xDivisionByZerox commented
> I dont see the problem. What would you expect?

The current documentation show this:

```ts
function jwt(
    options: {
      header?: Record<string, unknown>;
      payload?: Record<string, unknown>;
      refDate?: string | Date | number;
    } = {}
  ): string;
faker.internet.jwt() //...
```

I would expect standardized prettier formatting (look at the whitespaces):

```ts
function jwt(
  options: {
    header?: Record<string, unknown>;
    payload?: Record<string, unknown>;
    refDate?: string | Date | number;
  } = {}
): string;
faker.internet.jwt() //...
```

---

I can see this on other functions as well (example: [internet.mac()](https://next.fakerjs.dev/api/internet#mac), [number.bigInt()](https://next.fakerjs.dev/api/number.html#bigint)). Because of that I dismiss this topic from this PR and put it in our meeting notes.

2024-06-18 19:33 UTC, ST-DDT commented on src/modules/internet/util.ts
> + *
Maybe add that this does basically the same as Buffer.from...toString(base64url)

2024-06-19 10:21 UTC, eLoyyyyy commented on src/modules/internet/util.ts
> +  ).join('');
![Screenshot 2024-06-19 at 6 17 53 PM](https://github.com/faker-js/faker/assets/19218300/25d65ad6-b231-4440-a77d-b24c561485a7)

I think it messes with the encoding. Since `String.fromCodePoint` accepts variable args, it passes both the value and the index from the `mapFn` in `Array.from`.

2024-06-19 12:55 UTC, xDivisionByZerox commented on src/modules/internet/util.ts
> +  ).join('');
I see. Thank you for trying. I learned something new today :)

2024-06-20 15:19 UTC, ST-DDT commented on src/modules/internet/util.ts
**Team Decision**

@eLoyyyyy Please move this file to `src/internal/base64.ts`

2024-06-20 15:20 UTC, ST-DDT commented on src/modules/internet/util.ts
> + * as outlined in RFC 7515 - Appendix C.
Since we label this as generic component this is no longer necessary.

```suggestion
```

2024-06-22 13:37 UTC, ST-DDT submitted a review, later dismissed
Thanks for your contribution. :heart:

2024-06-22 14:36 UTC, xDivisionByZerox commented on src/modules/internet/index.ts
> +       * };
Usually we don't have entire objects as defautl values. Thats why I have another question regarding the current visualization in the documentation:

![image](https://github.com/faker-js/faker/assets/77127505/2a2aade8-ec41-4004-b16d-29572113e807)

While the default values in the displayed table are technically correct, they may appear unusual in the given context. Specifically, the dangling comma at the last property and the semicolon at the end stand out. No other value uses semicolons, which is why I find it somewhat unconventional. I#m not quite sure whether this is relevant, so what are your thoughts on this?

_The same issue applies to the payload property._

2024-06-22 15:02 UTC, ST-DDT commented on src/modules/internet/index.ts
> +       * };
Should we introduce jwtHeader and jwtPayload methods? I dont like that as it is a dynamic complex object.

Alternatively we could just hide the specifics of the default e.g. `{ ... }`. And put the actual property names in the description. 🤔

2024-06-22 17:58 UTC, xDivisionByZerox commented on src/modules/internet/index.ts
> +       * };
> Should we introduce jwtHeader and jwtPayload methods?

I don't see how this is related to my question. 

> Alternatively we could just hide the specifics of the default e.g. { ... }.

I don't think thats necessary. I'm not bothered by the actual default value itself, but the formatting. Simply removing the dangling comma and semicolon would already solve this (unless the documentation generation uses different formatting). Like this:

```suggestion
       * {
       *    alg: faker.internet.jwtAlgorithm(),
       *    typ: 'JWT'
       * }
```

My question was whether anyone else is botheres by that problem, or if I'm beeing nitpicky.

2024-06-22 18:42 UTC, ST-DDT commented on src/modules/internet/index.ts
> +       * };
> > Should we introduce jwtHeader and jwtPayload methods?
> 
> I don't see how this is related to my question.

Instead of defining the whole object in there, we would simply refer to the method:

````ts
 * @default faker.internet.jwtHeader()
````

> My question was whether anyone else is bothered by that problem, or if I'm being nitpicky.

I like your suggested `@default` better than the representation used by this PR, even if prettier might disagree.

1) Should we handle this case on the script side instead? E.g. `defaultValue.replaceAll(/,(\n *)}/g, '$1}')`

The trailing `;` should be removed in the code as well (as we don't have that anywhere else either).

2) And should we also use `defaultValue.replaceAll(/: ([a-z0-9"'-])/g, ': $1')` (with nbsp)?

**This PR**
![grafik](https://github.com/faker-js/faker/assets/1579362/b86941c1-33b3-4fad-9120-2c9de7bd9d0b)

**With script optimizations**
![grafik](https://github.com/faker-js/faker/assets/1579362/37a3010d-9034-4034-ac0e-84fd40fcabb2)

---

I just noticed that the default value uses an indentation of 3 spaces instead of prettier's 2.

**For script change**
```suggestion
       * {
       *   alg: faker.internet.jwtAlgorithm(),
       *   typ: 'JWT',
       * }
```

**For source code change**
```suggestion
       * {
       *   alg: faker.internet.jwtAlgorithm(),
       *   typ: 'JWT'
       * }
```

2024-10-12 23:20 UTC, ST-DDT commented
@eLoyyyyy Could you please fix the merge conflicts?

2024-10-14 06:44 UTC, ST-DDT submitted a review, later dismissed

2024-10-14 06:44 UTC, ST-DDT commented on src/internal/base64.ts
> + * This works the same as `Buffer.from(input).toString('base64url')`
This lools like a merge error to me.

2024-10-16 14:15 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * @since 9.0.0
```suggestion
   * @since 9.1.0
```

2024-10-16 14:15 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * @since 9.0.0
```suggestion
   * @since 9.1.0
```

2024-10-16 14:18 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    const encodedHeader = toBase64(JSON.stringify(header));
```suggestion
    const encodedHeader = toBase64Url(JSON.stringify(header));
```

2024-10-16 14:18 UTC, ST-DDT commented on src/modules/internet/index.ts
> +    const encodedPayload = toBase64(JSON.stringify(payload));
```suggestion
    const encodedPayload = toBase64Url(JSON.stringify(payload));
```

2024-10-16 23:25 UTC, ST-DDT requested changes

2024-10-16 23:25 UTC, ST-DDT commented on src/internal/base64.ts
> +        return btoa(binaryString);
Please don't forget the `base64url` part for the non-Buffer path from your previous PR:

https://github.com/faker-js/faker/blob/d258b33f439ae99c490648343481170e210804f8/src/modules/internet/util.ts#L14-L19

2024-10-17 08:23 UTC, ST-DDT reviewed
A few minor tweaks and then this is good to go.

2024-10-17 08:23 UTC, ST-DDT commented on src/internal/base64.ts
> +      }
IMO we can reduce the code duplication by using the existing method for the first part.

```suggestion
    ? (input) =>
        toBase64(input)
          .replaceAll('+', '-')
          .replaceAll('/', '_')
          .replaceAll(/=+$/g, '')
```

2024-10-17 08:23 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   *
```suggestion
   *
   * Please note that this method generates a random signature instead of a valid one.
   *
```

2024-10-17 08:23 UTC, ST-DDT commented on src/modules/internet/index.ts
> +       * };
```suggestion
       * {
       *   alg: faker.internet.jwtAlgorithm(),
       *   typ: 'JWT'
       * }
```

2024-10-17 08:23 UTC, ST-DDT commented on src/modules/internet/index.ts
> +       * };
```suggestion
       * {
       *   iat: faker.date.recent(),
       *   exp: faker.date.soon(),
       *   nbf: faker.date.anytime(),
       *   iss: faker.company.name(),
       *   sub: faker.string.uuid(),
       *   aud: faker.string.uuid(),
       *   jti: faker.string.uuid()
       * }
```

2024-10-17 08:23 UTC, ST-DDT commented on src/modules/internet/index.ts
> +       * };
I created https://github.com/faker-js/faker/pull/3190 to improve the visualization of the default value.

2024-10-17 11:46 UTC, ST-DDT approved these changes

2024-10-17 13:59 UTC, Shinigami92 approved these changes

2024-10-23 12:25 UTC, ST-DDT commented
@xDivisionByZerox Could you please review this PR (or dismiss your previous one)?

2024-10-23 20:02 UTC, xDivisionByZerox approved these changes

2024-10-23 21:28 UTC, merged

2024-10-23 22:01 UTC, ST-DDT commented
Thank you for you contribution. ❤️ 

This feature will be available in the upcoming v9.1 release of faker.