feat: add book module
faker-js/faker pull request #2949
Opened 2024-06-15 16:53 UTC by cieslarmichal

Added new Book module as discussed in https://github.com/faker-js/faker/issues/2310.

Changes made:

- added a new module with following methods: author, format, genre, publisher, series, title
- added en locale data
- added pl locale data
- added tests for all methods
- added new docs page

2024-06-15 17:21 UTC, ST-DDT commented on CONTRIBUTING.md
> +- `pnpm run test:update-snapshots` - runs all tests, and updates any snapshots if needed
Please fix this in a separate even if tiny PR.

2024-06-15 17:21 UTC, ST-DDT commented on src/definitions/book.ts
> +  publisher: string[];
Please add some jsdocs to the individual entries.

e.g.
````ts
/**
 * The names of actual authors.
 */
````

2024-06-15 17:21 UTC, ST-DDT commented on src/locales/en/book/publisher.ts
> +  'Brill Publishers',
Is this a duplicate or are they actually two different publishers?
IMO even if we could probably remove this because it is very close to the other.

2024-06-15 17:21 UTC, ST-DDT commented on src/modules/book/index.ts
> + * For a random title, use [`title()`](https://fakerjs.dev/api/book.html#title).
Maybe use a list `- `?

2024-06-15 18:26 UTC, cieslarmichal commented on src/modules/book/index.ts
> + * For a random title, use [`title()`](https://fakerjs.dev/api/book.html#title).
ok

2024-06-15 18:26 UTC, cieslarmichal commented on src/locales/en/book/publisher.ts
> +  'Brill Publishers',
ok

2024-06-15 18:26 UTC, cieslarmichal commented on src/definitions/book.ts
> +  publisher: string[];
ok

2024-06-15 18:27 UTC, cieslarmichal commented on CONTRIBUTING.md
> +- `pnpm run test:update-snapshots` - runs all tests, and updates any snapshots if needed
I will open separate PR with that.

2024-06-15 19:23 UTC, ST-DDT approved these changes, later dismissed

2024-06-16 04:22 UTC, import-brain submitted a review, later dismissed

2024-06-16 04:26 UTC, matthewmayer requested changes

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/author.ts
> +  'Baum, L. Frank (Lyman Frank)',
i dont think the parenthesised parts like (James Matthew) are necessary. If a author is most commonly referred to by an abbreviation, use that.

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/genre.ts
> +  'Biography/Autobiography',
I'd prefer just Biography

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/genre.ts
> +  'Comic/Graphic Novel',
I'd split Comic Book and Graphic Novel

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/genre.ts
> +  'Tall tale',
This is not a common genre

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/genre.ts
> +  'Mythopoeia',
seems too specific

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/genre.ts
> +  'Speech',
isn't this a format rather than a genre?

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/genre.ts
> +  'Legend',
Legend, Mythology and Folklore seem too overlapping

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/genre.ts
> +  'Fiction narrative',
seems too general

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/genre.ts
> +  'Fiction in verse',
Not a common genre. Could have Poetry?

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/genre.ts
> +export default [
also consider adding:

Romance
Young Adult (YA)

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/series.ts
> +  'Game of Thrones',
Game of Thrones is the same as A Song of Ice and Fire no?

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/series.ts
> +export default [
this seems very fantasy and science fiction focused? Consider some other genres:

Hercule Poirot, The Century Trilogy, Bridgerton, The Neapolitan Novels, The No. 1 Ladies' Detective Agency, Little Women Series, Captain Underpants

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/title.ts
> +  'Bunny Brown and his sister Sue on the rolling ocean',
seems very obscure

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/title.ts
> +  'The trial of Sacco and Vanzetti',
should use Title Case for all titles. 

Some of these seem quite obscure.

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/en/book/title.ts
> +];
Add some more modern classics e.g.
"To Kill a Mockingbird" 

and contemporary books like
"The Kite Runner" 
"Life of Pi"
"The Handmaid's Tale" 

non-fiction
"The Diary of a Young Girl"
"Long Walk to Freedom"
"A Brief History of Time"
"Freakonomics"

2024-06-16 04:26 UTC, matthewmayer commented on src/locales/pl/book/author.ts
> +  'Andrzej Maleszka',
we should standardise on Lastname, Firstname like in en?

2024-06-16 04:26 UTC, matthewmayer commented on src/modules/book/index.ts
> +   * Returns a random author name.
We should indicate if this is in Lastname, Firstname format.

2024-06-16 04:26 UTC, matthewmayer commented on src/modules/book/index.ts
> + * - For a random title, use [`title()`](https://fakerjs.dev/api/book.html#title).
Put the most important items first. E.g. i'd start with title and author.

2024-06-16 07:30 UTC, ST-DDT commented on src/locales/pl/book/author.ts
> +  'Andrzej Maleszka',
IMO these should be written like they are put on a book cover/publishing information.

2024-06-16 07:41 UTC, ST-DDT commented on src/modules/book/index.ts
> +   * Returns a random author name.
This may be different per language.
In Germany this appears to be mostly firstname lastname even for foreign sounding author names.
Also some authors always abbreviate or entirely omit parts of their name.
So maybe we should state that this uses the same spelling as the book cover/publication information.
IMO this produces a string that may be used as is and not explicitly split in first and lastname to be used separately.

2024-06-16 08:38 UTC, matthewmayer commented on src/modules/book/index.ts
> +   * Returns a random author name.
Yeah I'm not sure. Libraries and some online booksellers always write it LastName first. Ok the book itself and on other online booksellers it's usually FirstName first.

2024-06-16 09:11 UTC, cieslarmichal commented on src/modules/book/index.ts
> +   * Returns a random author name.
I think that for the end user first name lastname would be more natural and readable so I will go with that

2024-06-16 09:12 UTC, cieslarmichal commented on src/modules/book/index.ts
> + * - For a random title, use [`title()`](https://fakerjs.dev/api/book.html#title).
good suggestion thanks

2024-06-16 10:14 UTC, cieslarmichal commented on src/modules/book/index.ts
> + * - For a random title, use [`title()`](https://fakerjs.dev/api/book.html#title).
done

2024-06-16 10:15 UTC, cieslarmichal commented on src/locales/en/book/title.ts
> +];
done

2024-06-16 10:15 UTC, cieslarmichal commented on src/locales/en/book/title.ts
> +  'The trial of Sacco and Vanzetti',
done

2024-06-16 10:15 UTC, cieslarmichal commented on src/locales/en/book/genre.ts
> +  'Mythopoeia',
done

2024-06-16 10:15 UTC, cieslarmichal commented on src/locales/en/book/genre.ts
> +  'Tall tale',
done

2024-06-16 10:15 UTC, cieslarmichal commented on src/locales/en/book/genre.ts
> +  'Comic/Graphic Novel',
done

2024-06-16 10:15 UTC, cieslarmichal commented on src/locales/en/book/genre.ts
> +  'Biography/Autobiography',
done

2024-06-16 10:15 UTC, cieslarmichal commented on src/locales/en/book/author.ts
> +  'Baum, L. Frank (Lyman Frank)',
done

2024-06-16 14:21 UTC, matthewmayer commented on src/locales/en/book/genre.ts
> +  'Children Literature',
```suggestion
  "Children's Literature",
```

2024-06-17 13:29 UTC, cieslarmichal commented
hello guys, is there anything more I should do here? 🙂

2024-06-17 14:07 UTC, xDivisionByZerox commented
> hello guys, is there anything more I should do here? 🙂 

There might be. If there is we will write a comment. 🙂
It's not unusual in open source that PRs will take a while to be fully reviewed and merged.

Please keep in mind that all members and maintainers of FakerJS work on this project in their free time.

2024-06-17 14:26 UTC, cieslarmichal commented
I know, sure, just asking :)

2024-06-18 11:01 UTC, matthewmayer approved these changes, later dismissed
Happy with the API I think it looks good overall!

Maybe we could have a few more books for the title method, I feel 100 is not that many. We normally cap any one data type at 1000. Perhaps we could get up to 200 books?

Non urgent as this probably won't get merged until 9.1

2024-06-18 11:04 UTC, cieslarmichal commented
Ok I will add more book titles

2024-06-18 19:56 UTC, ST-DDT commented on CONTRIBUTING.md
> +- `pnpm run test:update-snapshots` - runs all tests, and updates any snapshots if needed
Done in #2955

2024-06-18 20:25 UTC, ST-DDT approved these changes, later dismissed

2024-06-18 20:40 UTC, Shinigami92 approved these changes, later dismissed

2024-06-20 07:30 UTC, import-brain approved these changes, later dismissed

2024-06-20 21:44 UTC, cieslarmichal commented
I have just added more book titles and authors (about 150 each).

2024-06-21 06:31 UTC, matthewmayer approved these changes

2024-06-22 07:43 UTC, import-brain approved these changes

2024-06-22 18:56 UTC, xDivisionByZerox approved these changes
I'll already approve. I still have the question if the addition of the polish locale should be it's own PR. That way there would be a separate entry on our reloase notes/changelog.

1. Create book module (new modules have to have applicable locale data in the default locale => en)
2. Add polish locale data for book module.

---

This is not blocking. Just a question on the process.

Edit: Also, thank you @cieslarmichal for the initial waiting, quick implementation and reasonable feedback loops. Was a pleasure reviewing your PR.

2024-06-22 19:19 UTC, ST-DDT approved these changes

2024-06-22 19:26 UTC, ST-DDT commented
> I still have the question if the addition of the polish locale should be it's own PR.

Initial data is initial data.
IMO if I consider something useful, I would try it instead of searching the changelog for my locale.
Unless, I know the feature exists and I'm just waiting for it to get available for my locale.
But I don't have a particular strong opinion on this either.

2024-06-22 21:46 UTC, Shinigami92 approved these changes

2024-06-23 03:26 UTC, matthewmayer commented
I would say if it's only 2 or 3 locales include it's better to include in the initial commit. That helps verify there are no incorrect assumptions about how the data will be localised (for example the fact that in the first version of this PR the pl and en versions of author used different FirstName surname orders. That was good, as it helped us clarify what the rule should be in general and standardise it.)

2024-06-23 16:03 UTC, cieslarmichal commented
Thank you guys for a nice word :) It was a good review process, I am happy about it, can't wait to release those changes 😎

2024-09-27 16:01 UTC, ST-DDT commented
Dear @cieslarmichal,

Thank you for your patience and contributions so far. We wanted to provide you with a brief update.

We are pleased to inform you that we have addressed all the known bugs in version 9.0. We will now take a short break and resume work around October 7, 2024, to begin merging new features for v9.1, including yours.

In the meantime, we hope you have a great time, and we sincerely appreciate your ongoing support and contributions.

Best regards,
your FakerJS Team

2024-09-27 16:07 UTC, cieslarmichal commented
Hello, thank you for giving me a chance to contribute and for the information about expected release date 💪

2024-10-10 15:57 UTC, merged