feat: update sponsors, backers references, and add index.d.ts
faker-js/faker pull request #30
Opened 2022-01-08 23:55 UTC by clarkerican

Porting over more changes from the @withshepherd fork. Main changes:

* Removes sponsors, and backers from the Readme
* Adds types in the index.d.ts file

2022-01-09 01:38 UTC, damienwebdev commented
@clarkerican can you split this diff apart? Some of this relates to:

1. README modifications from #28
2. Support for self-managed types #14 
3. Package renaming #19 

And I think we should strive to target one issue at a time.

2022-01-09 02:00 UTC, clarkerican commented
@damienwebdev I limited the scope :)

2022-01-09 04:01 UTC, damienwebdev approved these changes
lgtm

2022-01-09 10:58 UTC, Shinigami92 commented on Readme.md
> +![Faker.js](https://raw.githubusercontent.com/withshepherd/faker.js/master/logo.png)
The logo should be served from `faker-js` instead of `withshepherd`

2022-01-09 11:00 UTC, Shinigami92 commented on Readme.md
> - * <http://search.cpan.org/~jasonk/Data-Faker-0.07/> - Copyright 2004-2005 by Jason Kohles
At least we should have this history somewhere.
Maybe when we add a `LICENSE` file we should add these maintainers :thinking:

2022-01-09 11:19 UTC, Shinigami92 commented
Should we remove `.github/FUNDING.yml` also at least for now?

2022-01-09 16:48 UTC, Shinigami92 requested changes
see comments above

2022-01-10 17:10 UTC, damienwebdev commented on Readme.md
> - * <http://search.cpan.org/~jasonk/Data-Faker-0.07/> - Copyright 2004-2005 by Jason Kohles
@Shinigami92 this is held within the [LICENSE ](https://github.com/faker-js/faker/blob/main/MIT-LICENSE.txt) file.

2022-01-10 17:35 UTC, Shinigami92 commented on Readme.md
> - * <http://search.cpan.org/~jasonk/Data-Faker-0.07/> - Copyright 2004-2005 by Jason Kohles
You are right, thx :+1:

2022-01-10 17:35 UTC, Shinigami92 approved these changes

2022-01-10 19:17 UTC, Shinigami92 approved these changes

2022-01-10 20:24 UTC, prisis approved these changes

2022-01-10 21:32 UTC, damienwebdev approved these changes
lgtm

2022-01-10 21:32 UTC, merged