fix: correction of pt_PT information
faker-js/faker pull request #3020
Opened 2024-07-15 21:30 UTC by jeanpierrecarvalho

2024-07-15 21:31 UTC, jeanpierrecarvalho commented
Hi @ST-DDT, just recreated this one. Can you have a look, please?

2024-07-16 11:40 UTC, ST-DDT requested changes

2024-07-16 11:40 UTC, ST-DDT commented on src/locales/pt_PT/person/last_name.ts
> +    'Oliva',
Please sort the file alphabetically.

2024-07-16 13:51 UTC, jeanpierrecarvalho commented on src/locales/pt_PT/person/last_name.ts
> +    'Oliva',
Hi @ST-DDT, sure! I will do it!

2024-07-16 13:59 UTC, jeanpierrecarvalho commented on src/locales/pt_PT/person/last_name.ts
> +    'Oliva',
@ST-DDT done ✅

2024-07-16 14:27 UTC, Shinigami92 approved these changes

2024-07-16 14:34 UTC, ST-DDT approved these changes

2024-07-17 10:08 UTC, import-brain approved these changes

2024-08-15 16:43 UTC, xDivisionByZerox commented on src/locales/pt_PT/person/prefix.ts
> +  ],
@faker-js/maintainers Wasn't `generic` supposed to be used for gender neutral prefixes? We changed the structure in #2938. 
I remember us discussing that generic should be used to represent gender neutral assosiations and can be omitted if they do not exist in a specific language language. They can exist as a standalone entry, tho.  
Thats what the [types](https://github.com/faker-js/faker/blob/a210619c3cd6d802f8a80e3db68c96b444d15a64/src/definitions/person.ts#L3-L13) reflect as well.

I'd say that this is not the case here. Am I wrong?

2024-08-15 21:54 UTC, ST-DDT commented on src/locales/pt_PT/person/prefix.ts
> +  ],
`generic` is intended for cases that don't represent male or female specifically.
In this case it looks like it is just the union of male and female, so it can now be omitted, because it will fallback to the gendered version automatically if it cannot find generic ones.

https://github.com/faker-js/faker/blob/a210619c3cd6d802f8a80e3db68c96b444d15a64/src/definitions/person.ts#L5-L7
https://github.com/faker-js/faker/blob/a210619c3cd6d802f8a80e3db68c96b444d15a64/src/modules/person/index.ts#L21-L47

2024-08-30 21:14 UTC, ST-DDT commented on src/locales/pt_PT/person/prefix.ts
> +  ],
Since the error exists prior to this PR and this PR makes it easier to address in the future. I'm going to resolve this.
We can address this as part of #3058 later.

- #3058

2024-09-16 18:41 UTC, merged