test: remove mocks from system
faker-js/faker pull request #303
Opened 2022-01-25 22:31 UTC by prisis

2022-01-25 22:31 UTC, prisis commented
now we have correct tests for system and #300 is valid

2022-01-25 22:32 UTC, prisis commented on test/system.spec.ts
> +            expect(actual !== '').toBeTruthy();
For now i dont have a better idea how to test it

2022-01-25 22:39 UTC, Shinigami92 commented on test/system.spec.ts
> +            expect(actual !== '').toBeTruthy();
Please have a look into https://github.com/faker-js/faker/blob/9b3d6b52673d7e2e81e2c3d30685e5268e0fac85/test/commerce.spec.ts#L83

2022-01-25 22:42 UTC, Shinigami92 requested changes
Please keep the already existing test cases, rewrite them, modernize them and move them to the seeded or non-seeded section

2022-01-26 10:15 UTC, ST-DDT requested changes

2022-01-26 10:15 UTC, ST-DDT commented on test/system.spec.ts
> +          ).toBeTruthy();
Instead of `expect(list.includes(value)).toBe(true)` we should use `expect(list).toInclude/contain(value)` that way we at least see the offending value.

2022-01-26 10:15 UTC, ST-DDT commented on test/system.spec.ts
> +          ).toBeTruthy();
This should be `0<=x && x<=9`, because `2.0.6` is a valid response value.

2022-01-26 10:15 UTC, ST-DDT commented on test/system.spec.ts
> +          ).not.toBeNull();
Use expect().toMatch()

2022-01-26 10:15 UTC, ST-DDT commented on test/system.spec.ts
> +          ).toBeTruthy();
expect().toInclude/contain()

2022-01-26 10:15 UTC, ST-DDT commented on test/system.spec.ts
> +          ).toBeGreaterThan(1);
expect().toContain('.')

2022-01-26 10:15 UTC, ST-DDT commented on test/system.spec.ts
> +          ).toBe(-1);
expect().not.toContain('/')

2022-01-26 10:15 UTC, ST-DDT commented on test/system.spec.ts
> +          ).toBeGreaterThan(1);
expect().toContain('.')

2022-01-26 10:15 UTC, ST-DDT commented on test/system.spec.ts
> +          ).toBe(-1);
expect().not.toContain('/')

2022-01-26 11:02 UTC, Shinigami92 commented on test/system.spec.ts
> +  faker.seed(Math.ceil(Math.random() * 1_000_000_000));
See line 91

2022-01-26 11:03 UTC, Shinigami92 commented on test/system.spec.ts
> +          ).toBeGreaterThan(1);
Can we somehow check that it contains exactly 1?

2022-01-26 11:03 UTC, Shinigami92 commented on test/system.spec.ts
> +            'generated fileNames should have a extension'
```suggestion
            'Generated fileNames should have an extension'
```

2022-01-26 11:05 UTC, Shinigami92 commented on test/system.spec.ts
> +            'generated fileNames should have a extension'
Not sure about the capital `G`

@griest024 Should we use capital starting sentences for such messages?

2022-01-26 11:06 UTC, Shinigami92 commented on test/system.spec.ts
> +        it('returns unix fs directory full path', () => {
I personally prefer to name the `it`s to `should ...`
So it reads: _it should do stuff_

2022-01-26 11:06 UTC, ST-DDT commented on test/system.spec.ts
> +          ).toBeGreaterThan(1);
A lot of files contain more than a single dot e.g. `foobar.conf.bak`, `foobar.tar.gz` so I wouldn't check for that.

2022-01-26 11:08 UTC, Shinigami92 commented on test/system.spec.ts
> +          ).not.toBeNull();
In the other tests I currently just used `.match` instead of `.toMatch`
We should decide for one and use it in all places the same way
I will let you (I mean the team) decide which we should take, I don't have any preference from my side :slightly_smiling_face:

2022-01-26 11:09 UTC, Shinigami92 commented on test/system.spec.ts
> +            firstNumber > 0 && firstNumber < 9,
Please split these into two `expect`s with `lessThan` and `greaterThan`

2022-01-26 15:33 UTC, prisis commented on test/system.spec.ts
> +          ).toBeTruthy();
There is no toIncude but include

2022-01-26 16:07 UTC, griest024 commented on test/system.spec.ts
> +            'generated fileNames should have a extension'
How will it appear in the log output? If it appears at the beginning of a sentence, yes. I think if it was just left lowercase it wouldn't hurt readbility in either case.

2022-01-26 16:36 UTC, Shinigami92 commented on test/system.spec.ts
> +            'generated fileNames should have a extension'
it's written as
```
system > functionName() > should do stuff
Assert Error: Generated fileNames should have an extension
```

2022-01-26 16:46 UTC, griest024 commented on test/system.spec.ts
> +            'generated fileNames should have a extension'
Either way is fine

2022-01-29 07:07 UTC, prisis commented on test/system.spec.ts
> +            'generated fileNames should have a extension'
Going for small "g"

2022-01-29 11:06 UTC, Shinigami92 requested changes

2022-01-29 11:06 UTC, Shinigami92 commented on test/system.spec.ts
> +          ).toBe(0);
```suggestion
          expect(
            directoryPath.startsWith('/'),
            'generated directoryPath should start with /'
          ).toBeTruthy();
```

2022-01-29 11:06 UTC, Shinigami92 commented on test/system.spec.ts
> +          ).toBe(-1);
```suggestion
          expect(
            fileName.startsWith('/'),
            'generated fileNames should not have path separators'
          ).toBeFalsy();
```

2022-01-29 11:06 UTC, Shinigami92 commented on test/system.spec.ts
> +          ).toBe(0);
```suggestion
          expect(
            filePath.startsWith('/'),
            'generated filePath should start with /'
          ).toBeTruthy();
```

2022-01-29 11:06 UTC, Shinigami92 commented on test/system.spec.ts
> +          ).include(fileType);
```suggestion
          ).toContain(fileType);
```

2022-01-29 11:06 UTC, Shinigami92 commented on test/system.spec.ts
> +          ).lessThanOrEqual(9);
Maybe we can use just one regex matcher. I think `validator` has a `isSemver` function (see: #258)

2022-01-29 12:56 UTC, Shinigami92 submitted a review, later dismissed

2022-01-29 13:15 UTC, ST-DDT approved these changes
Please sort the seeded and non seeded tests in the same order next time.
Optimally in alphabetical order.

2022-01-31 08:06 UTC, Shinigami92 approved these changes

2022-01-31 08:48 UTC, ST-DDT requested changes

2022-01-31 08:48 UTC, ST-DDT commented on test/system.spec.ts
> +          ).match(/.+\/*./gm);
Is the pattern correct?
```suggestion
          ).match(/.+\/.+/gm);
```

2022-01-31 12:01 UTC, Shinigami92 commented on test/system.spec.ts
> +          ).match(/.+\/*./gm);
There is a `validator.isMimeType` :smiley:

2022-01-31 18:14 UTC, prisis commented
> Please sort the seeded and non seeded tests in the same order next time. Optimally in alphabetical order.

done  :)

2022-01-31 18:15 UTC, prisis commented on test/system.spec.ts
> +      filePath: '/opt/bin/directives_multi_byte_table.p10.m21',
added todo for it :+1:

2022-01-31 18:56 UTC, Shinigami92 approved these changes

2022-01-31 19:12 UTC, ST-DDT approved these changes

2022-01-31 19:13 UTC, merged