feat(location): ca postcodes by state
faker-js/faker pull request #3057
Opened 2024-08-15 22:25 UTC by matthewmayer

2024-08-16 06:12 UTC, Shinigami92 commented
FFR: This issue was originally reported by @zombiebrainz on Discord

2024-08-17 14:06 UTC, ST-DDT requested changes

2024-08-17 14:06 UTC, ST-DDT commented on src/locales/en_CA/location/postcode_by_state.ts
> +const suffix = '[0-9][A-HJ-NPRSTVW-Z] [0-9][A-HJ-NPRSTVW-Z][0-9]';
The letters D and F are not allowed.

```suggestion
const suffix = '[0-9][ABCEGHJ-NPRSTVW-Z] [0-9][ABCEGHJ-NPRSTVW-Z][0-9]';
```

2024-08-17 18:15 UTC, ST-DDT approved these changes, later dismissed

2024-08-17 18:15 UTC, ST-DDT commented on src/locales/en_CA/location/postcode_by_state.ts
> +  QC: `{{helpers.fromRegExp([HJG]${suffix})}}`, // Quebec
minor: IMO we should keep them alphabetically.

```suggestion
  QC: `{{helpers.fromRegExp([GHJ]${suffix})}}`, // Quebec
```

2024-08-18 07:57 UTC, ST-DDT approved these changes

2024-08-18 10:32 UTC, Shinigami92 commented on src/locales/en_CA/location/postcode_by_state.ts
> +  AB: `{{helpers.fromRegExp(T${suffix})}}`, // Alberta
**thought (if-minor):** I'm a bit confused that there are no added tests or at least generated snapshot results 🤔 But maybe this is really tested somehow behind the scene

However, should it be `helpers.fromRegExp('T${suffix}')` (with quotes) instead?! Or do we have some magic going on 🤔

2024-08-18 10:50 UTC, ST-DDT commented on src/locales/en_CA/location/postcode_by_state.ts
> +  AB: `{{helpers.fromRegExp(T${suffix})}}`, // Alberta
`faker.helpers.fake` "magic".
`'` does not work because it would fail json parsing. `"` would work, but it doesnt change anything here.

2024-08-18 10:53 UTC, ST-DDT commented on src/locales/en_CA/location/postcode_by_state.ts
> +  AB: `{{helpers.fromRegExp(T${suffix})}}`, // Alberta
Offtopic: For v10 I plan to replace most of our internal fake patterns with something like this `(fakerCore) -> fromRegExp(fakerCore, 'T${suffix}')`.
So we dont have to parse our own code anymore.

2024-08-18 11:02 UTC, matthewmayer commented on src/locales/en_CA/location/postcode_by_state.ts
> +  AB: `{{helpers.fromRegExp(T${suffix})}}`, // Alberta
> **thought (if-minor):** I'm a bit confused that there are no added tests or at least generated snapshot results 🤔 But maybe this is really tested somehow behind the scene
> 
> 
> 
> However, should it be `helpers.fromRegExp('T${suffix}')` (with quotes) instead?! Or do we have some magic going on 🤔 

The snapshot tests are currently nearly all for default en locale only. We could add some for non English locales but might be hard to know where to stop(presumably not every method in every locale as it would be very slow)

2024-08-18 11:22 UTC, ST-DDT commented on src/locales/en_CA/location/postcode_by_state.ts
> +  AB: `{{helpers.fromRegExp(T${suffix})}}`, // Alberta
> But maybe this is really tested somehow behind the scene

It is tested here: https://github.com/faker-js/faker/blob/next/test/all-functional.spec.ts

2024-08-18 16:48 UTC, Shinigami92 approved these changes

2024-08-19 20:14 UTC, merged