feat: add chat.fakerjs.dev subdomain redirection to discord
faker-js/faker pull request #306
Opened 2022-01-26 01:12 UTC by import-brain

Fixes #295

2022-01-26 06:16 UTC, Shinigami92 requested changes
You need to replace all links like in markdown files with new url

2022-01-26 12:14 UTC, import-brain commented
> You need to replace all links like in markdown files with new url

Could you please clarify what you mean by this? I interpreted your instructions as "replace all instances of fakerjs.dev with chat.fakerjs.dev in markdown files", but I don't think that makes sense.

2022-01-26 13:55 UTC, Shinigami92 commented
https://github.com/faker-js/faker/blob/3242dfc4b2f566931c3687173f6361a6384b6247/README.md?plain=1#L6

Just one example, please search over the whole repo

2022-01-26 17:59 UTC, import-brain commented
> [`3242dfc`/README.md?plain=1#L6](https://github.com/faker-js/faker/blob/3242dfc4b2f566931c3687173f6361a6384b6247/README.md?plain=1#L6)
> 
> Just one example, please search over the whole repo

Ohhh I see, will do.

2022-01-26 18:20 UTC, import-brain commented
Whoops, misclick.

2022-01-26 18:29 UTC, ST-DDT commented on netlify.toml
> +force = true
Is the formatting here correct?
The section above looks slightly different.

2022-01-26 19:02 UTC, import-brain commented on netlify.toml
> +force = true
@ST-DDT This is what I used to write this formatting, it looks a bit different than the sections above.

https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

2022-01-26 19:55 UTC, ST-DDT commented on netlify.toml
> +force = true
I will approve this once it uses consistent formatting. The example uses indented formatting, so we should go for that
```suggestion
[[redirects]]
  from = "https://chat.fakerjs.dev"
  to = "https://discord.com/invite/4qDjAmDj4P"
  status = 301
  force = true
```

2022-01-26 19:57 UTC, import-brain commented on netlify.toml
> +force = true
> I will approve this once it uses consistent formatting. The example uses indented formatting, so we should go for that
> 
> ```suggestion
> 
> [[redirects]]
> 
>   from = "https://chat.fakerjs.dev"
> 
>   to = "https://discord.com/invite/4qDjAmDj4P"
> 
>   status = 301
> 
>   force = true
> 
> ```

Oh, I thought you were referencing the double brackets around "redirects". Committed

2022-01-26 19:59 UTC, ST-DDT approved these changes

2022-01-27 07:38 UTC, Shinigami92 approved these changes

2022-01-28 07:30 UTC, merged