fix: some implicit return types
faker-js/faker pull request #307
Opened 2022-01-26 03:23 UTC by import-brain

Partially fixes #305

2022-01-26 08:28 UTC, Shinigami92 commented
Currently one of our problems is that `arrayElement` doesn't guarantee type-safetynes (regrading to compile-time).
Our `definitions` currently are just _mostly_ arrays, but could be anything :shrug: 
I know that there are currently mostly `string[]` and we could just take over the types of `@types/faker`, but I would like to double-check that instead of assuming.

2022-01-26 10:24 UTC, ST-DDT approved these changes, later dismissed

2022-01-26 10:25 UTC, ST-DDT commented
IMO we should set these to the expected return types. Double checking with the existing ones would still be a good idea.

2022-01-26 10:40 UTC, doughlass approved these changes, later dismissed

2022-01-26 11:17 UTC, import-brain commented
> IMO we should set these to the expected return types. Double checking with the existing ones would still be a good idea.

All of the ones in this PR were checked against @types/faker latest version, they all seem reasonable and match up.

2022-01-26 18:28 UTC, ST-DDT commented
A probably wrong commit ended up here.

2022-01-26 18:50 UTC, ST-DDT requested changes

2022-01-26 18:50 UTC, ST-DDT commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: chat.fakerjs.dev
Please remove the last commit here.

2022-01-26 19:04 UTC, import-brain commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: chat.fakerjs.dev
Accidentally committed the chat.fakerjs.dev changes to this branch, just reset and force-pushed

2022-01-26 19:17 UTC, ST-DDT approved these changes

2022-01-27 07:39 UTC, Shinigami92 approved these changes

2022-01-27 11:31 UTC, demipel8 commented
Wrong mention, sorry.

2022-01-28 07:29 UTC, merged