feat(number): add romanNumeral method
faker-js/faker pull request #3070
Opened 2024-08-22 06:43 UTC by AmaanRS

Adds #2649

- #2649

---

Adds a method for generating random romanNumerals:

````ts
faker.number.romanNumeral() // "CMXCIII"
faker.number.romanNumeral(5) // "III"
faker.number.romanNumeral({ min: 10 }) // "XCIX"
faker.number.romanNumeral({ max: 20 }) // "XVII"
faker.number.romanNumeral({ min: 5, max: 10 }) // "VII"
````

[Documentation](https://deploy-preview-3070.fakerjs.dev/api/number.html#romannumeral)

2024-08-24 11:58 UTC, import-brain requested changes, later dismissed
Please add tests for `romanNumeral`

2024-08-24 11:58 UTC, import-brain commented on src/modules/number/index.ts
> +   * Returns a Roman Numeral in [String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#string_type) format.
```suggestion
   * Returns a roman numeral in [String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#string_type) format.
```

2024-08-24 11:58 UTC, import-brain commented on src/modules/number/index.ts
> +    const DEFAULT_MAX = 4999;
What do we think about these default bounds?

2024-08-24 12:46 UTC, Shinigami92 requested changes, later dismissed

2024-08-24 12:46 UTC, Shinigami92 commented on src/modules/number/index.ts
> +   * faker.number.romanNumeral(5) // "V"
**suggestion:** ok, so some initial feedback also from my side
we should find another example value here, to make it more clear that `5 not => V`
```suggestion
   * faker.number.romanNumeral(5) // "III"
```

2024-08-24 12:46 UTC, Shinigami92 commented on src/modules/number/index.ts
> +   * faker.number.romanNumeral() // "IV"
**suggestion:** it's possible but nearly unrealistic that an example value between 1 and 4999 will result in IV
you should pick a "more random" example

2024-08-24 12:46 UTC, Shinigami92 commented on src/modules/number/index.ts
> +   * faker.number.romanNumeral({ min: 10 }) // "XI"
**suggestion:** also for this

2024-08-24 12:46 UTC, Shinigami92 commented on src/modules/number/index.ts
> +    let i = 3;
**thought:** this looks like a very magic number to me, why is this `3`?

2024-08-25 12:39 UTC, matthewmayer commented on src/modules/number/index.ts
> +    let i = 3;
This code comes from https://blog.stevenlevithan.com/archives/javascript-roman-numeral-converter

I think it would be good to extract the actual "int to roman numeral" part to a separate function and include a comment referencing the blog post.

2024-08-28 14:47 UTC, AmaanRS commented on src/modules/number/index.ts
> +    const DEFAULT_MAX = 4999;
I have changed the max to 3999, check the new draft

2024-08-28 14:49 UTC, AmaanRS commented on src/modules/number/index.ts
> +    let i = 3;
I tested the code written in https://blog.stevenlevithan.com/archives/javascript-roman-numeral-converter but i found out that it worked only for values in range 1 to 999 so i changed the code, i took the new logic from here https://www.30secondsofcode.org/js/s/to-roman-numeral/

2024-08-28 14:54 UTC, AmaanRS commented
In this commit 7abd2c7b262a31d5a699a17f99dcfab9d4650afd i created a new function intToRomanNumeral so where should i place it ?

2024-08-28 15:28 UTC, Shinigami92 commented on src/modules/number/index.ts
> +    return intToRomanNumeral(num);
**question:** why wrapping it in a function in the first place?

you could potentially just do:

```suggestion
    return lookup.reduce((acc, [k, v]) => {
        acc += k.repeat(Math.floor(num / v));
        num = num % v;
        return acc;
      }, '');
```

#nottested

2024-08-28 15:28 UTC, Shinigami92 commented on src/modules/number/index.ts
> +   * @throws When `min`,`max` is not a number.
**suggestion:** 
```suggestion
   * @throws When `min`, `max` is not a number.
```

2024-08-29 07:50 UTC, matthewmayer commented on src/modules/number/index.ts
> +    let num = DEFAULT_MIN;
this line is not needed as num is always set at line 505 or 507

2024-08-29 07:50 UTC, matthewmayer commented on src/modules/number/index.ts
> +    }
there's no need to special-case the `max==min`. just simplify down to

`let num = this.int({ min, max });`

2024-08-29 07:52 UTC, matthewmayer commented on src/modules/number/index.ts
> +    return intToRomanNumeral(num);
note we don't allow .reduce() https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-reduce.md so this should probably just be replaced with a simple loop

2024-08-29 07:54 UTC, matthewmayer commented on src/modules/number/index.ts
> +    return intToRomanNumeral(num);
```
    let result = '';
    for (const [k, v] of lookup) {
      result += k.repeat(Math.floor(num / v));
      num = num % v;
    }
    return result;
```

2024-08-29 12:53 UTC, AmaanRS commented on src/modules/number/index.ts
> +    return intToRomanNumeral(num);
> This code comes from https://blog.stevenlevithan.com/archives/javascript-roman-numeral-converter
> 
> I think it would be good to extract the actual "int to roman numeral" part to a separate function and include a comment referencing the blog post.

Should i create a new function,if yes where should i place it ?

2024-08-29 13:19 UTC, AmaanRS commented
How should i write random seeded test for "it('should generate a Roman numeral between 1 and 10')" ? Since i don't what answer will be.

2024-08-29 13:20 UTC, AmaanRS commented
And there will be no value range test ?

2024-08-29 14:13 UTC, matthewmayer commented on src/modules/number/index.ts
> +    return intToRomanNumeral(num);
You're not using that function any more so I think it's fine to inline it as suggested above

2024-08-29 14:16 UTC, matthewmayer commented
There's a few ways you could do it. For 1 to 10 you could check if it's any of the values from I to X by listing all 10 values. 

You could also check it only contains suitable characters. 

Also add tests that check hitting each of the errors and check appropriate error is thrown.

2024-08-30 05:53 UTC, AmaanRS commented
Please let me know if there are any changes with the code and test if not i will run preflight and then commit the code

2024-08-30 12:48 UTC, matthewmayer commented
Ideally please run preflight after every change. This will help catch any minor syntax errors etc so the reviewers can focus on the logic of your code rather than nitpicking.

2024-08-30 21:33 UTC, ST-DDT commented on src/modules/number/index.ts
> +   *
```suggestion
   *
   * @since 9.1.0
```

2024-08-30 21:33 UTC, ST-DDT commented on src/modules/number/index.ts
> +
```suggestion
```

2024-08-30 21:33 UTC, ST-DDT commented on src/modules/number/index.ts
> +    const max = Number(options.max ?? DEFAULT_MAX);
```suggestion
    const { min = 1, max = 3999 } = options;
```

2024-08-30 21:33 UTC, ST-DDT commented on src/modules/number/index.ts
> +    num = this.int({ min, max });
Please declare variables late/shortly before using it.

```suggestion
    let num = this.int({ min, max });
    let result = '';
```

2024-08-30 21:33 UTC, ST-DDT commented on test/modules/number.spec.ts
> +      });
We usually don't include tests for these and don't handle it in the implementation either.
The string parts aren't possible with proper usage of TypeScript (which we assume our users or their tooling use) or are able to read the resulting error messages in case of bad values.

2024-08-30 21:33 UTC, ST-DDT commented on src/modules/number/index.ts
> +    }
This is already covered by `faker.number.int()`.

2024-08-30 21:33 UTC, ST-DDT commented on src/modules/number/index.ts
> +    }
We don't include these check, since we assume that our users either use TypeScript, a type aware IDE, or are able to read the native error messages, created when a bad value is passed.

2024-09-01 13:16 UTC, AmaanRS commented
I ran into an error during preflight ```FakerApiDocsProcessingError: Failed to process parameter options at src/modules/number/index.ts:468:16 : Expected exactly one element for jsdocs, got 0```

2024-09-01 14:32 UTC, matthewmayer commented
> Expected exactly one element for jsdocs

its not a very intuitive error message but i think the problem is that you're missing a `@since` JSDoc tag

add

`@since 9.1.0` at the bottom of the JSDoc as this likely wont be in the 9.0.0 release.

2024-09-01 19:35 UTC, ST-DDT commented
> I ran into an error during preflight `FakerApiDocsProcessingError: Failed to process parameter options at src/modules/number/index.ts:468:16 : Expected exactly one element for jsdocs, got 0`

The error is not caused by `@since`. It is caused by the `options.min/max` parameter not having jsdocs.
I'll improve the error message.

````txt
FakerApiDocsProcessingError: Failed to process property 'options.min' at src/modules/number/index.ts:467:36 : Expected exactly one element for jsdocs, got 0
````

The options object should be defined like this:

````ts
  romanNumeral(
    options:
      | number
      | {
          /**
           * Lower bound for generated number.
           *
           * @default 1
           */
          min?: number;
          /**
           * Upper bound for generated number.
           *
           * @default 3999
           */
          max?: number;
        } = {}
  ): string {
````

2024-09-03 01:32 UTC, matthewmayer requested changes

2024-09-03 01:32 UTC, matthewmayer commented on src/modules/number/index.ts
> +   * Returns a roman numeral in [String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#string_type) format.
The link to the String type seems unnecessary

2024-09-03 01:32 UTC, matthewmayer commented on src/modules/number/index.ts
> +      throw new FakerError(`Max value ${max} should be 3999 or lesser.`);
lesser->less

2024-09-11 06:14 UTC, matthewmayer submitted a review, later dismissed

2024-09-20 17:13 UTC, Shinigami92 commented on src/modules/number/index.ts
> +    const DEFAULT_MAX = 3999;
**suggestion:** if we already define these default values here, we can reuse them in line 496, 499 and 503

2024-09-25 18:48 UTC, Shinigami92 commented on src/modules/number/index.ts
> +      throw new FakerError(`Min value ${min} should be 1 or greater.`);
**suggestion:** 
```suggestion
      throw new FakerError(`Min value ${min} should be ${DEFAULT_MIN} or greater.`);
```

2024-09-25 18:48 UTC, Shinigami92 commented on src/modules/number/index.ts
> +      throw new FakerError(`Max value ${max} should be 3999 or less.`);
**suggestion:** 
```suggestion
      throw new FakerError(`Max value ${max} should be ${DEFAULT_MAX} or less.`);
```

2024-09-25 19:37 UTC, ST-DDT commented on src/modules/number/index.ts
> +      num = num % v;
Maybe:

```suggestion
      num %= v;
```

2024-09-25 19:37 UTC, ST-DDT commented on test/modules/number.spec.ts
> +        expect(Object.values(values)).toContain(roman);
Are the keys of `values` used for anything?

2024-10-12 23:04 UTC, ST-DDT commented
@AmaanRS Could you please address the requested changes?

2024-10-18 15:03 UTC, AmaanRS commented on test/modules/number.spec.ts
> +        expect(Object.values(values)).toContain(roman);
Nothing, expect for returning them as roman numeral string

2024-10-18 15:35 UTC, ST-DDT commented on test/modules/number.spec.ts
> +        expect(Object.values(values)).toContain(roman);
Then maybe use an array directly.

2024-10-19 13:55 UTC, AmaanRS commented on test/modules/number.spec.ts
> +        expect(Object.values(values)).toContain(roman);
Done!!

2024-10-19 19:13 UTC, ST-DDT reviewed
One last change, then this is good to go.

2024-10-19 19:13 UTC, ST-DDT commented on test/modules/number.spec.ts
> +      });
Sorry, I didn't think of this earlier.
I changed this test to check for the actual values:

```suggestion
      it.each(
        Object.entries({
          I: 1,
          IV: 4,
          IX: 9,
          X: 10,
          XC: 90,
          XCIX: 99,
          XXVII: 27,
          CCLXIII: 263,
          DXXXVI: 536,
          DCCXIX: 719,
          MDCCCLI: 1851,
          MDCCCXCII: 1892,
          MMCLXXXIII: 2183,
          MMCMXLIII: 2943,
          MMMDCCLXVI: 3766,
          MMMDCCLXXIV: 3774,
          MMMCMXCIX: 3999,
        })
      )(
        'should generate a Roman numeral %s for value %d',
        (expected: string, value: number) => {
          const mock = vi.spyOn(faker.number, 'int');
          mock.mockReturnValue(value);

          const actual = faker.number.romanNumeral();

          mock.mockRestore();

          expect(actual).toBe(expected);
        }
      );
```

A few manually selected ones and a few random ones.

2024-10-19 19:14 UTC, ST-DDT commented
Please also change the description of the PR to something explaining the feature in more detail. A few sentences are sufficient.

2024-10-20 11:09 UTC, AmaanRS commented on test/modules/number.spec.ts
> +      });
Done!!

2024-10-20 15:34 UTC, ST-DDT approved these changes, later dismissed

2024-10-26 20:41 UTC, ST-DDT commented on src/modules/number/index.ts
> +   * @since 9.1.0
```suggestion
   * @since 9.2.0
```

2024-10-29 12:25 UTC, ST-DDT approved these changes

2024-10-29 12:26 UTC, ST-DDT commented
@Shinigami92 and @import-brain Could you please re-review this PR (or dismiss your stale reviews)?

2024-10-31 10:00 UTC, merged

2024-10-31 10:01 UTC, ST-DDT commented
@AmaanRS Thanks for your first contribution. ❤️ 
I hope you had a good experience contributing.
If you have any suggestions on how to improve things, please let us know.

This feature will be released in Faker v9.2, which will probably release shortly (a week to a few weeks).