fix: removed node v12 from the pipe, because vitest is not supporting…
faker-js/faker pull request #309
Opened 2022-01-26 09:23 UTC by prisis

… this version.

2022-01-26 09:29 UTC, Shinigami92 commented
We should do this end of march

2022-01-26 09:43 UTC, prisis commented
Please check https://github.com/faker-js/faker/runs/4947011110?check_suite_focus=true as example the pipe never runs and vitest is returning 0 as error code

2022-01-26 09:45 UTC, ST-DDT approved these changes, later dismissed

2022-01-26 09:54 UTC, ST-DDT commented
The test pipeline does not work with node 12 and AFAICT the releases aren't build with node 12 either, so there is no point in keeping it.
If you wish to ensure that it can be build with node 12, then we should at least explicit turn of the test runs.

But I don't have a strong opinion on when to remove this.

Is there anything compatibility wise we have to consider when removing it?
(Aka does our build process ensure node 12 compatibility regardless of our build setup?)

2022-01-26 10:39 UTC, doughlass approved these changes, later dismissed

2022-01-26 10:57 UTC, Shinigami92 approved these changes
@damienwebdev @JessicaSachs Please point out in next release notes that we officially drop node 12 support

2022-01-27 07:55 UTC, Shinigami92 requested changes
This line needs to be updated to v14

https://github.com/faker-js/faker/blob/3242dfc4b2f566931c3687173f6361a6384b6247/package.json#L99

2022-01-27 12:13 UTC, ST-DDT commented
Couldn't we just drop official support for node 12 but give the users at least the chance to use it?
AFAICT we don't use any node 14+ features.

2022-01-27 12:19 UTC, Shinigami92 commented
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines
As far as we don't set `engine-strict`, only a warning will show up

2022-01-28 10:25 UTC, Shinigami92 approved these changes

2022-01-28 10:33 UTC, ST-DDT approved these changes

2022-01-28 10:36 UTC, merged