chore(tooling): install knip and remove unused files / dependencies
faker-js/faker pull request #3106
Opened 2024-09-11 16:45 UTC by jeanpierrecarvalho

chore(tooling): install knip and remove unused files / dependencies

**Changes Made:**

- Installed knip to analyze unused files and dependencies
- Removed unused files and dependencies identified by knip
- Add some folders to be ignored by knip

**Details of Changes:**

- Added knip to the project as a dev dependency to improve project cleanliness and remove dead code
- Ran an analysis using knip and removed files that were no longer in use or required by the project
- Updated related configurations and documentation to reflect the changes

**Additional Details:**

- These changes help streamline the project and reduce clutter, improving overall maintainability
- No functional changes were introduced; the focus was solely on project hygiene and code cleanup

**What is next?**

- pnpm knip can run in the pre-commit hook OR / AND
- can be added to GHA on PR creation OR / AND
- can be added to release process and tag creation

2024-09-11 18:00 UTC, prisis commented on package.json
> -    "@eslint-types/unicorn": "52.0.0",
funny this is used in the eslint config, not sure if the tool works correctly

2024-09-11 18:31 UTC, Shinigami92 commented on package.json
> -    "@eslint-types/unicorn": "52.0.0",
I think not anymore, because we switched to eslint v9

2024-09-11 19:05 UTC, prisis commented on package.json
> -    "@eslint-types/unicorn": "52.0.0",
I did check the "next" branch and its still there

2024-09-11 19:08 UTC, Shinigami92 commented on package.json
> -    "@eslint-types/unicorn": "52.0.0",
where?

2024-09-11 19:09 UTC, prisis commented on package.json
> -    "@eslint-types/unicorn": "52.0.0",
https://github.com/faker-js/faker/blob/next/eslint.config.js#L8

2024-09-11 19:10 UTC, prisis commented on package.json
> -    "@eslint-types/unicorn": "52.0.0",
ah wait, this are the types

![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcm1xNG9saXNvZHZxc3FwMnFiM3lpZzltaGl6Z2c1bDE5bmlwZm5wYiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/TJawtKM6OCKkvwCIqX/giphy.gif)

2024-09-11 19:30 UTC, jeanpierrecarvalho commented on package.json
> -    "@eslint-types/unicorn": "52.0.0",
ahahahahaha 😄

2024-09-11 20:28 UTC, prisis commented on test/internal/mersenne-test-utils.ts
> -export const TWISTER_32CO_MAX_VALUE = 0.9999999997671694;
Was there a reason to change this?

2024-09-12 12:51 UTC, ST-DDT commented on knip.config.ts
> +import { type KnipConfig } from 'knip';
We usually use a different import syntax.

```suggestion
import type { KnipConfig } from 'knip';
```

2024-09-12 12:51 UTC, ST-DDT commented on knip.config.ts
> +  workspaces: {
Do we need the workspaces section. Some files I have seen don't use it.

https://github.com/mochajs/mocha/blob/7563e59ae3c78ada305d26eadb86998ab54342da/.knip.jsonc#L4

2024-09-12 12:51 UTC, ST-DDT commented on package.json
> -    "@algolia/client-search": "5.2.3",
It looks like this dependency is now, optional. It would be good if somebody could test that as well.

Thinking: I wonder when that change happened.

2024-09-12 12:51 UTC, ST-DDT commented on package.json
> +    "knip": "^5.30.1",
We use pinned versions only.

```suggestion
    "knip": "5.30.1",
```

2024-09-12 12:51 UTC, ST-DDT commented on .github/renovate.json5
> +      "matchPackageNames": ["ts-morph", "vitepress"]
We should probably add vue/vue-tsc/@vueuse/core in here too. (Different PR)

2024-09-12 12:51 UTC, ST-DDT commented on package.json
> +    "knip": "knip"
If this something we should run as part of preflight? Or in our CI to find these as early as possible?

2024-09-12 13:57 UTC, matthewmayer commented on package.json
> +    "knip": "knip"
Preflight is already slow enough 😀

2024-09-12 14:17 UTC, jeanpierrecarvalho commented on knip.config.ts
> +import { type KnipConfig } from 'knip';
Solved ✅

2024-09-12 14:18 UTC, jeanpierrecarvalho commented on knip.config.ts
> +  workspaces: {
yes, I can refactor this one

2024-09-12 14:19 UTC, jeanpierrecarvalho commented on knip.config.ts
> +  workspaces: {
Solved ✅

2024-09-12 14:19 UTC, jeanpierrecarvalho commented on package.json
> +    "knip": "^5.30.1",
Good one! Changing!

2024-09-12 14:20 UTC, jeanpierrecarvalho commented on package.json
> +    "knip": "^5.30.1",
Solved ✅

2024-09-12 14:23 UTC, jeanpierrecarvalho commented on test/internal/mersenne-test-utils.ts
> -export const TWISTER_32CO_MAX_VALUE = 0.9999999997671694;
This change ensures that constants are defined locally and are not immediately available for import when we define them. By exporting them in a single statement later, we gain better control over what and how we export, potentially improving tree-shaking and code clarity IMHO but I can change it

2024-09-12 14:27 UTC, jeanpierrecarvalho commented on package.json
> +    "knip": "knip"
Just ran the preflight and yes, it's painful ahhahahah Do we need to do this preflight like that? Why the process is not splited using git hooks e.g and run, only if needed. We can perform some tasks only in the files in stage, using lint-staged e.g, WDYT? I can draw a proposal and explain my pov better

2024-09-12 14:28 UTC, jeanpierrecarvalho commented on package.json
> +    "knip": "knip"
@matthewmayer @ST-DDT

2024-09-12 14:28 UTC, jeanpierrecarvalho commented on .github/renovate.json5
> +      "matchPackageNames": ["ts-morph", "vitepress"]
I will create a new PR for that 🙏🏻

2024-09-12 14:45 UTC, jeanpierrecarvalho commented on test/internal/mersenne-test-utils.ts
> -export const TWISTER_32CO_MAX_VALUE = 0.9999999997671694;
Just run the tool and this file triggered a duplicate exports, we are exporting the same object twice. I think it's a error wdyt?

2024-09-12 14:55 UTC, matthewmayer commented on package.json
> +    "knip": "knip"
i think it would be good to open a separate discussion on ways to speed up preflight

2024-09-12 15:30 UTC, jeanpierrecarvalho commented on package.json
> +    "knip": "knip"
Agreed! I will create that discussion and add my thought there 🙏🏻

2024-09-12 16:14 UTC, ST-DDT commented
**Team Decision**

For now, we don't see a need to keep knip permanently in the project.
But we would like to have the one time cleanup anyway.

Do you know how good the github ci integration of knip is?
aka does it show the errors only in the build logs or also as error markers in the PullRequest?

We will discuss this some more in the next team-meeting with other team members.

2024-09-16 18:48 UTC, ST-DDT requested changes

2024-09-16 18:48 UTC, ST-DDT commented on package.json
> -    "@algolia/client-search": "5.2.3",
Please create a separate PR that remove this dependency. That way it is easier to test for breaking changes.

2024-09-16 18:48 UTC, ST-DDT commented on package.json
> -    "vite": "5.4.2",
Please create a separate PR that remove this dependency. That way it is easier to test for breaking changes.

2024-10-06 20:15 UTC, xDivisionByZerox commented on package.json
> -    "@eslint-types/unicorn": "52.0.0",
FFR: This has been removed in #3044.

2024-10-06 20:37 UTC, xDivisionByZerox commented on .github/renovate.json5
> +      "matchPackageNames": ["ts-morph", "vitepress"]
FFR: I extracted this problem into #3157.

2024-10-26 14:26 UTC, ST-DDT commented
**Team Decision**

- We will not add knip
- @ST-DDT will create PRs for the remaining dependencies

Thanks for bringing this to our attention anyway.

2024-10-26 14:26 UTC, closed without merging