feat(animal): add petName method
faker-js/faker pull request #3196
Opened 2024-10-19 10:20 UTC by suyashgulati

To resolve #2206

Adds new method `petName` on animal module

2024-10-19 10:22 UTC, suyashgulati commented
Need maintainers' help on resolving the test failure:

```Error: The locale data for 'animal.petName' are missing in this locale.
  Please contribute the missing data to the project or use a locale/Faker instance that has these data.
  For more information see https://fakerjs.dev/guide/localization.html```
  
I am not sure what needs to be done for this. Do I need to add any other locale than en to resolve this?

2024-10-19 10:37 UTC, matthewmayer requested changes

2024-10-19 10:37 UTC, matthewmayer commented on src/modules/animal/index.ts
> +   * @since 5.5.0
Should be `@since 9.2.0` as that will be next minor release

2024-10-19 10:37 UTC, matthewmayer commented on test/modules/animal.spec.ts
> +  'petName',
the problem with the test failure is that these tests assume that the definition name exactly matches the method name. But in this case it (correctly) doesn't - petName vs pet_name. I would remove petName from the functionNames array and write a separeate test for it.

2024-10-19 11:34 UTC, ST-DDT commented on test/modules/animal.spec.ts
> +  'petName',
I'll have a look at it.

2024-10-19 12:18 UTC, ST-DDT commented
Blocked by: #3197

- #3197

2024-10-19 12:19 UTC, ST-DDT commented on test/modules/animal.spec.ts
> +  'petName',
-> #3197

2024-10-26 15:58 UTC, ST-DDT commented
This is no longer blocked, but you have to adjust the test file.

2024-10-28 13:48 UTC, matthewmayer requested changes

2024-10-28 13:48 UTC, matthewmayer commented on test/modules/animal.spec.ts
> +        it('should return random value from type array', () => {
From pet name array not type array?

2024-10-28 13:48 UTC, matthewmayer commented on src/locales/en/animal/pet_name.ts
> +  'Bear',
Maybe omit this just because it's confusing if this is the value (You might think you have the wrong method?)

2024-10-28 19:29 UTC, ST-DDT commented on test/modules/animal.spec.ts
> +        it('should return random value from type array', () => {
```suggestion
        it('should return random value from pet name array', () => {
```

2024-10-28 19:29 UTC, ST-DDT commented on src/locales/en/animal/pet_name.ts
> +  'Bear',
```suggestion
```

2024-10-29 12:17 UTC, ST-DDT approved these changes

2024-10-29 13:02 UTC, matthewmayer approved these changes

2024-10-29 15:41 UTC, ejcheng approved these changes

2024-10-29 15:48 UTC, merged

2024-10-29 19:24 UTC, ST-DDT commented
Thanks for your contribution. ❤️ 
Your additions will be available in Faker v9.2.0.
While I don't have an exact release date for it yet, we will likely release it somewhat soonish (a week - a few weeks).