fix: Vehicle vin is always 17 characters long
faker-js/faker pull request #320
Opened 2022-01-27 11:28 UTC by demipel8

Solves #307

2022-01-27 12:31 UTC, ST-DDT requested changes

2022-01-27 12:31 UTC, ST-DDT commented on test/vehicle.spec.ts
> +      }
This test does the same as the one above. So maybe drop the above one.

2022-01-27 17:06 UTC, MilosPaunovic requested changes

2022-01-27 17:06 UTC, MilosPaunovic commented on test/vehicle.spec.ts
> +      }
Agreed, could merge those two.

2022-01-27 19:02 UTC, import-brain submitted a review, later dismissed

2022-01-27 19:02 UTC, import-brain commented
Please merge those tests. Other than that, this lgtm!

2022-01-28 10:19 UTC, Shinigami92 commented
This is a runtime change bug => 6.1+

2022-01-28 10:59 UTC, ST-DDT submitted a review, later dismissed

2022-01-28 15:32 UTC, import-brain submitted a review, later dismissed

2022-01-31 11:06 UTC, ST-DDT submitted a review, later dismissed

2022-01-31 18:17 UTC, import-brain submitted a review, later dismissed

2022-02-06 20:58 UTC, Moosh-be commented on test/vehicle.spec.ts
> +      for (let step = 0; step < 300000; step++) {
Oula ca can have a harmful effect on the speed of execution of the tests without offering an absolute guarantee.

Why not put this test in the generator?

With something like, "if the generated value is not validated by the regular expression, then send a forced fallback value"

2022-02-06 23:42 UTC, ST-DDT commented on test/vehicle.spec.ts
> +      for (let step = 0; step < 300000; step++) {
We will reduce this number before we merge it.

> Why not put this test in the generator?

With these new changes/fixes, this will become obsolete.
We just want to make sure, that we have a test in case this ever appears again.

2022-02-07 05:22 UTC, Moosh-be commented on test/vehicle.spec.ts
> +      for (let step = 0; step < 300000; step++) {
👍

2022-03-10 19:44 UTC, Shinigami92 commented
@demipel8 This PR needs a rebase

2022-03-11 12:15 UTC, Shinigami92 commented
@demipel8 Tests are running red

2022-03-28 15:17 UTC, ST-DDT submitted a review, later dismissed

2022-03-28 16:36 UTC, pkuczynski approved these changes

2022-03-28 17:07 UTC, ST-DDT approved these changes

2022-03-28 17:20 UTC, Shinigami92 approved these changes

2022-03-28 17:24 UTC, merged