chore(finance): deprecate maskedNumber for removal
faker-js/faker pull request #3201
Opened 2024-10-20 17:22 UTC by ST-DDT

Fixes #2504

- #2504

---

The masking of important information is usually implemented in the application itself, so there is no need for us to provide a method ourselves.
This is especially true, since the method has lots of options and would need even more to actually represent real masked data.

As a workaround, you can use the following:

- `faker.finance.creditCardNumber().replaceAll(/(?<=.{4}).(?=.{2})/g, '*')`
- `faker.finance.iban().replaceAll(/(?<=.{4})\w(?=.{2})/g, '*')`

2024-11-02 13:56 UTC, xDivisionByZerox commented on src/modules/finance/index.ts
> +    const card = this.creditCardNumber().replaceAll(/(?<=.{4}).(?=.{2})/g, '*');
This will not produce the same output as you can see in the snapshot tests.

2024-11-02 13:58 UTC, xDivisionByZerox commented
Dispite [my comment in #3202](https://github.com/faker-js/faker/pull/3202#issuecomment-2452995670), I think deprecating this method is valid:

1. **Proofen** low to none actual use
2. The utility this method provides is arguably confusing and niche

2024-11-10 12:33 UTC, xDivisionByZerox submitted a review, later dismissed

2024-11-10 13:31 UTC, matthewmayer requested changes

2024-11-10 13:31 UTC, matthewmayer commented on test/modules/__snapshots__/finance.spec.ts.snap
> +exports[`finance > 1337 > transactionDescription 1`] = `"invoice transaction at Gottlieb - Koelpin using card ending with 4773*******13 for JMD 262.02 in account ***52971361"`;
the phrasing of transactionDescription "ending with" doesn't really make sense if both the start and end of the masked number are shown.

2024-11-10 13:35 UTC, matthewmayer commented on test/modules/__snapshots__/finance.spec.ts.snap
> +exports[`finance > 1337 > transactionDescription 1`] = `"invoice transaction at Gottlieb - Koelpin using card ending with 4773*******13 for JMD 262.02 in account ***52971361"`;
So I suggest either we mask all but the last digits like before, or delete "ending with".

2024-11-10 17:16 UTC, ST-DDT commented on src/modules/finance/index.ts
> +      since: '9.1.0',
```suggestion
      since: '9.3.0',
```

2024-11-10 17:17 UTC, ST-DDT commented on test/modules/__snapshots__/finance.spec.ts.snap
> +exports[`finance > 1337 > transactionDescription 1`] = `"invoice transaction at Gottlieb - Koelpin using card ending with 4773*******13 for JMD 262.02 in account ***52971361"`;
Should be fixed now.

2024-11-10 17:17 UTC, ST-DDT commented on src/modules/finance/index.ts
> +    const card = this.creditCardNumber().replaceAll(/(?<=.{4}).(?=.{2})/g, '*');
I adjusted the example in the jsdocs accordingly.

2024-11-10 17:22 UTC, matthewmayer approved these changes

2024-11-12 08:15 UTC, merged