feat (locale): add books on pt_br
faker-js/faker pull request #3218
Opened 2024-10-24 01:54 UTC by guicazaroto

It Adds the book locales to pt_BR.

2024-10-24 04:06 UTC, matthewmayer requested changes
Please sort all entries alphabetically

2024-10-24 04:57 UTC, matthewmayer commented
Also 

Error: Duplicated values are [Obra poética]

If you can run the preflight command locally that will do the sorting for you and spot minor errors like this.

2024-10-24 18:18 UTC, ST-DDT approved these changes

2024-10-24 23:48 UTC, matthewmayer approved these changes

2024-10-25 14:10 UTC, import-brain approved these changes

2024-10-25 14:11 UTC, merged