chore: fix JSDoc comments in datatype.ts
faker-js/faker pull request #337
Opened 2022-01-28 18:16 UTC by pkuczynski

Refs #203

2022-01-28 18:18 UTC, Shinigami92 commented on src/datatype.ts
> +   * the [Unix Epoch](https://en.wikipedia.org/wiki/Unix_time) (1 January 1970 UTC).
Nice idea :raised_hands:

2022-01-28 18:24 UTC, Shinigami92 commented on src/datatype.ts
> +   * @param [options] Maximum value or options object.
I think these brackets are not needed :thinking: 
Could you check how it looks in VSCode?

As far as I know, these are needed in JavaScript, but not in TypeScript

2022-01-28 18:32 UTC, Shinigami92 commented on src/datatype.ts
> +   * @param [options] Maximum value or options object.
an example:

![image](https://user-images.githubusercontent.com/7195563/151602226-216c33c4-b50d-4497-9abe-7a5671f3fdf6.png)

seems that it works, but the default values will get eaten :thinking:

2022-01-28 19:42 UTC, pkuczynski commented on src/datatype.ts
> +   * @param [options] Maximum value or options object.
Brackets means it's an optional param. See https://jsdoc.app/tags-param.html#optional-parameters-and-default-values. I can't check how it looks in VSCode, as I am using JetBrains software... Here it looks like this:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/374864/151611113-c9ba3980-ff84-4100-aac3-95158416ac26.png">

2022-01-28 20:35 UTC, Shinigami92 commented
@ST-DDT could you test out if your api docs generation script can handle this param syntax?

2022-01-28 23:00 UTC, ST-DDT commented
@Shinigami92 No it doesn't work.

The typedoc.json does not contain them either.

![grafik](https://user-images.githubusercontent.com/1579362/151632603-9863773b-5313-4e1d-bdfb-32713680c09b.png)

2022-01-28 23:06 UTC, ST-DDT commented on src/datatype.ts
> +   * Returns a single random number for the given max value or range and precision.
```suggestion
   * Returns a single random number between zero and the given max value or the given range with the specified precision.
   * The bounds are inclusive.
```

2022-01-29 07:32 UTC, pkuczynski commented
> @Shinigami92 No it doesn't work.

There is an issue reported on typedoc and a PR with a fix: https://github.com/TypeStrong/typedoc/issues/567

2022-01-29 10:38 UTC, ST-DDT commented
@pkuczynski AFAICT That issue/PR isn't going to be fixed/merged soon and even if it gets merged, it does not solve the problem for us. See https://github.com/TypeStrong/typedoc/pull/1810#pullrequestreview-866938016

So maybe we should remove the `[]` for now?

2022-01-29 10:46 UTC, Shinigami92 requested changes
Hey @pkuczynski, I also found out that the usage of square-brackets are not a good idea, cause it could be that JetBrains support it, but Microsoft doesn't support them in VSCode.
So we should try to find a solution to write docs for both worlds.

I also think you are mixing JSDoc and (what I call) TSDoc. It's kinda like JavaDoc vs KotlinDoc, they are similar but not the same.

So what I would suggest is something like
```
/**
 * @param options.min Lower bound for generated number. Defaults to `0`.
 */
```

2022-02-01 17:39 UTC, pkuczynski commented
I guess there is no other option than remove those defaults for now, and maybe add them at some point in the future when vscode and typedoc will support them. It's really a shame though, and it displays in the docs much nicer when the `default value` column is provided for a param vs when the information is embedded in the desc.

2022-02-01 17:55 UTC, pkuczynski commented
Done. Could you please re-review...?

2022-02-01 18:20 UTC, Shinigami92 submitted a review, later dismissed

2022-02-01 18:23 UTC, ST-DDT requested changes

2022-02-01 18:23 UTC, ST-DDT commented on src/datatype.ts
> +   * @param options] Precision or options object.
```suggestion
   * @param options Precision or options object.
```

2022-02-01 18:23 UTC, ST-DDT commented on src/datatype.ts
> +   * Returns UUID v4 ([Universally Unique Identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier)).
```suggestion
   * Returns a UUID v4 ([Universally Unique Identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier)).
```

2022-02-01 18:23 UTC, ST-DDT commented on src/datatype.ts
> +   * Returns boolean value true or false.
```suggestion
   * Returns the boolean value true or false.
```

2022-02-01 18:23 UTC, ST-DDT commented on src/datatype.ts
> +   * Returns [hexadecimal](https://en.wikipedia.org/wiki/Hexadecimal) number.
```suggestion
   * Returns a [hexadecimal](https://en.wikipedia.org/wiki/Hexadecimal) number.
```

2022-02-01 18:23 UTC, ST-DDT commented on src/datatype.ts
> +   * Returns string representing JSON object with 7 pre-defined properties.
```suggestion
   * Returns a string representing JSON object with 7 pre-defined properties.
```

2022-02-01 18:23 UTC, ST-DDT commented on src/datatype.ts
> +   * Returns array with random strings and numbers.
```suggestion
   * Returns an array with random strings and numbers.
```

2022-02-01 20:56 UTC, pkuczynski commented on src/datatype.ts
> +   * @param options] Precision or options object.
omg! thanks!

2022-02-01 22:34 UTC, ST-DDT approved these changes

2022-02-02 14:08 UTC, Shinigami92 approved these changes

2022-02-02 15:38 UTC, ST-DDT approved these changes

2022-02-02 15:38 UTC, merged