fix: rename hexaDecimal to hexadecimal
faker-js/faker pull request #354
Opened 2022-01-29 16:48 UTC by kupuma-ru21

https://github.com/faker-js/faker/issues/336

I have dealt with the above issues.

2022-01-30 08:27 UTC, ST-DDT requested changes
Your last commit reverts a lot of test upgrades.

Please revert/remove it and try again.

2022-01-30 08:54 UTC, kupuma-ru21 commented
> Your last commit reverts a lot of test upgrades.
> 
> Please revert/remove it and try again. If you need help with that we can help you once v6.0 is released.

Reverted the last commit.

Please confirm.

2022-01-30 09:35 UTC, ST-DDT commented
This didn't work as intended.

Please run

````sh
git fetch --all
git reset --hard 262208750b712f793e8dadae40b295248de1cc73
git rebase origin/main
# Fix any rebase conflicts
#git rebase --continue
# Fix any linting, formatting or test issues
#git commit ...
git push -f
````

2022-01-30 09:56 UTC, ST-DDT requested changes
That looks better to me. You have a minor typo though. 😉 
Did you rebase all the way? Because there are still some conflicts.

2022-01-30 09:56 UTC, ST-DDT commented on package.json
> +    "fake-data-generatgit rebase origin/mainor",
```suggestion
    "fake-data-generator",
```

2022-01-30 09:58 UTC, ST-DDT commented on test/datatype.spec.ts
> -
Please restore this whitespace between the two sections.

2022-01-30 10:09 UTC, kupuma-ru21 commented on package.json
> +    "fake-data-generatgit rebase origin/mainor",
Fixed.
https://github.com/faker-js/faker/pull/354/commits/acea4a5d189e86d248166769eb70b3531623a9a8

2022-01-30 10:09 UTC, kupuma-ru21 commented on test/datatype.spec.ts
> -
Fixed.
https://github.com/faker-js/faker/pull/354/commits/38f4a68ca6b764473a7c0668bf95feb53a8a413b

2022-01-30 10:19 UTC, Shinigami92 requested changes
The current impl would introduce a breaking API change.
We could introduce an alias that calls the other function.

2022-01-30 13:30 UTC, kupuma-ru21 commented
> The current impl would introduce a breaking API change. We could introduce an alias that calls the other function.

2022-01-30 15:32 UTC, kupuma-ru21 commented
> The current impl would introduce a breaking API change. We could introduce an alias that calls the other function.

I'm sorry.
I didn't understand your point specifically.
What correction do I need to make?

2022-01-30 16:14 UTC, damienwebdev commented
@kupuma-ru21 

We have the function `hexadecimal`. Introducing a new function provides no value to the codebase other than breaking a consuming developer's codebase when they have previously relied on `hexaDecimal`. 

Put a different way, imagine the cost/benefit analysis of this commit:

1. Cost: All-consuming developers are forced to rename usage of `hexaDecimal` to `hexadecimal`, just making upgrades that much harder.
2. Benefit: It looks nicer.

Clearly, this is not worth it. As such, I'm closing this PR.

2022-02-01 15:13 UTC, mastermatt commented
@damienwebdev could you comment/close the initialing issue please https://github.com/faker-js/faker/issues/336

2022-03-23 18:51 UTC, pkuczynski commented
@damienwebdev this is a bit weak argumentation, given the fact that we are planing other of this type changes, for example moving `random.word` to `word.any`. Fact is that `hexaDecimal` is incorrect term. And it's shame that faker would keep using it, instead of keeping things clean. Refactoring should not be such of a big deal for customers of this library...

2022-03-23 19:10 UTC, Shinigami92 commented
issues and PRs with label `s: needs decision` will be discussed in upcoming maintainer-team meeting

2022-03-25 08:34 UTC, Shinigami92 commented
In yesterdays maintainers-team-meeting we discussed that we want to add `hexadecimal` and copy over the implementation from `hexaDecimal`
Then `hexaDecimal` will call `hexadecimal` and warn the user with a deprecation message and for the alternative
Also the JSDoc tag `@deprectated` needs to be added to `hexaDecimal`

We are doing this already in other places the same way, e.g. 
https://github.com/faker-js/faker/blob/c1c60649ee554f81887ab618ae8b2e2bd5a27d55/src/random.ts#L50-L59

2022-03-25 12:01 UTC, pkuczynski commented
@kupuma-ru21 let me know if you wanna continue this way, or I should take over as the author of the original issue #336

2022-04-01 14:34 UTC, Shinigami92 commented
> @kupuma-ru21 let me know if you wanna continue this way, or I should take over as the author of the original issue #336

One week passed without any response of the author, @pkuczynski please proceed

2022-04-03 12:44 UTC, closed without merging