chore: use explicit-module-boundary-types
faker-js/faker pull request #361
Opened 2022-01-29 19:13 UTC by Shinigami92

2022-01-29 20:28 UTC, ST-DDT approved these changes

2022-01-29 20:29 UTC, ST-DDT commented
Partial duplicate of https://github.com/faker-js/faker/pull/358

2022-01-30 00:10 UTC, prisis submitted a review, later dismissed

2022-01-30 01:27 UTC, ST-DDT commented
This needs to be rebased.

2022-01-30 10:32 UTC, ST-DDT approved these changes

2022-01-30 16:34 UTC, import-brain approved these changes

2022-01-30 16:54 UTC, griest024 requested changes

2022-01-30 16:54 UTC, griest024 commented on src/lorem.ts
> +  loremText(times?: number): string {
Changing the public api should not be in chore PRs

2022-01-30 17:00 UTC, Shinigami92 commented on src/lorem.ts
> +  loremText(times?: number): string {
I did not, this is an alias

2022-01-30 17:25 UTC, griest024 commented on src/lorem.ts
> +  loremText(times?: number): string {
this adds a public function `faker.lorem.loremText` where it did not exist previously, correct?

2022-01-30 17:32 UTC, Shinigami92 commented on src/lorem.ts
> +  loremText(times?: number): string {
no, see https://github.com/faker-js/faker/pull/361/files#diff-5b65c037dc3f0bd1a1693a84ed1514a704af5382782d4556efc12729759e25d3L143
Previously it had a `text = function loremText(times?: number) {`, I splitted this now, caue the `this.faker.fake` call was trapped by the function scope

2022-01-30 17:43 UTC, griest024 approved these changes

2022-01-30 17:45 UTC, import-brain approved these changes

2022-01-30 17:54 UTC, ST-DDT approved these changes

2022-01-30 17:55 UTC, merged