test: rewrite music tests
faker-js/faker pull request #383
Opened 2022-01-31 22:12 UTC by piotrekn

2022-01-31 22:37 UTC, ST-DDT requested changes
Looks good to me, expect one small detail.

2022-01-31 22:37 UTC, ST-DDT commented on test/music.spec.ts
>    describe('genre()', () => {
AFAICT your don't use that seed here at all.

Maybe use it like this: https://github.com/faker-js/faker/blob/8bb1e6c068518c6c1ebafacc93d38cdbdb2710c5/test/date.spec.ts#L423-L428

2022-01-31 23:36 UTC, ST-DDT submitted a review, later dismissed

2022-02-01 02:39 UTC, import-brain approved these changes

2022-02-01 07:46 UTC, Shinigami92 requested changes
Please add a `NON_SEEDED_BASED_RUN = 5` like in the other new tests, so we can ensure stability

2022-02-01 09:52 UTC, ST-DDT approved these changes

2022-02-01 10:36 UTC, Shinigami92 commented on test/music.spec.ts
> +          expect(genre).toBeTruthy();
**suggestion:** I think this would be a bit better:
```suggestion
          expect(genre.length).greaterThen(0);
          expect(faker.definitions.music.genre).toContain(genre);
```

2022-02-01 18:54 UTC, piotrekn commented on test/music.spec.ts
> +          expect(genre).toBeTruthy();
Checking `faker.definitions` - good idea 👍🏻 
Could you support with an argument, when `expect(genre.length).greaterThen(0` would be better than `expect(genre).toBeTruthy()`?
I see it exactly opposite. In case of `genre = null/undefined` you'd get generic error `Cannot read property 'length' of undefined`.

2022-02-01 19:10 UTC, Shinigami92 commented on test/music.spec.ts
> +          expect(genre).toBeTruthy();
Oh... yeah, you are right with the length :astonished: 
I was **wrong** with my thought that `expect('').toBeTruthy()` would not fail

2022-02-01 19:11 UTC, ST-DDT approved these changes

2022-02-01 19:11 UTC, Shinigami92 approved these changes

2022-02-01 19:19 UTC, merged