fix: remove duplicated extension in system.filePath
faker-js/faker pull request #395
Opened 2022-02-01 21:50 UTC by pkuczynski

Includes #300 which should be merged first

2022-03-16 12:53 UTC, ST-DDT commented on src/system.ts
> +    }
Maybe move this logic into `fileName()`?

2022-03-29 15:46 UTC, pkuczynski commented on src/system.ts
> +  filePath(ext = 1): string {
Sure, why not! :) I can do that once #300 is merged, ok?

2022-03-29 15:53 UTC, ST-DDT commented on src/system.ts
> +  filePath(ext = 1): string {
Sounds good, for now stick to a fixed number for each of them.
In a later feature we can introduce `number | { min, max }` (that might be handy for multiple locations)
Words, Lorem, ...

2022-03-29 16:17 UTC, ST-DDT commented
#300 has been merged

2022-04-05 14:25 UTC, Shinigami92 commented
@pkuczynski please rebase and resolve any conflicts 🙂

2022-04-06 07:31 UTC, ST-DDT requested changes
Please implement the requested features above.

2022-04-06 07:43 UTC, pkuczynski commented
> Please implement the requested features above.

Yes yes, give me a moment :)

2022-04-06 11:55 UTC, pkuczynski commented on src/system.ts
> +  filePath(ext = 1): string {
`directoryPath` does not take any params. I would propose to extend it in a separate PR not to mix the concerns.

2022-04-06 12:03 UTC, pkuczynski commented on src/system.ts
> +    }
Good idea, let me do that...

2022-04-06 12:06 UTC, pkuczynski commented on src/system.ts
> +    }
Actually, Mayne I should do that in a separate PR not to mix concerts @ST-DDT ? It would be also better to spot on the changelog?

2022-04-06 12:24 UTC, ST-DDT commented on src/system.ts
> +  filePath(ext = 1): string {
directory path in separate PR: OK

2022-04-06 12:27 UTC, Shinigami92 commented on src/system.ts
> +    }
Maybe we just need to adjust the PR title a little bit 🤷 
But I also think it's okay to provide this in one PR

2022-04-21 18:40 UTC, import-brain reviewed
Other than these two minor changes, this LGTM!

2022-04-21 18:40 UTC, import-brain commented on src/system.ts
> +        throw new FakerError('Options.ext shall not have negative value');
```suggestion
        throw new FakerError('Options.ext should not be negative');
```
I think this phrasing would be more natural

2022-04-21 18:40 UTC, import-brain commented on test/system.spec.ts
> +            new FakerError('Options.ext shall not have negative value')
```suggestion
            new FakerError('Options.ext should not be negative')
```

2022-06-13 15:45 UTC, xDivisionByZerox commented
@pkuczynski are you still working on this? Otherwise, I would continue the development process for you.

2022-07-04 17:19 UTC, xDivisionByZerox commented
Will be continued in #1101.

2022-07-04 17:19 UTC, closed without merging