test: rewrite phone tests
faker-js/faker pull request #396
Opened 2022-02-01 22:00 UTC by piotrekn

2022-02-01 22:29 UTC, ST-DDT approved these changes

2022-02-03 08:00 UTC, Shinigami92 requested changes

2022-02-03 08:00 UTC, Shinigami92 commented on test/phone.spec.ts
> +          expect(phoneNumber).match(/\([2-9]\d\d\) [2-9]\d\d-\d\d\d\d/);
Please try to find something in `validator`

2022-02-03 08:09 UTC, ST-DDT commented on test/phone.spec.ts
> +          expect(phoneNumber).match(/\([2-9]\d\d\) [2-9]\d\d-\d\d\d\d/);
There is nothing in validators.
Phone numbers are just numbers with some "styling" to improve readability.

2022-02-03 08:16 UTC, Shinigami92 commented on test/phone.spec.ts
> +          expect(phoneNumber).match(/\([2-9]\d\d\) [2-9]\d\d-\d\d\d\d/);
:sob:

2022-02-03 22:31 UTC, ST-DDT commented on test/phone.spec.ts
> +          const fakeHelpers_replaceSymbolWithNumberSpy = vi.spyOn(
Mhh, you use the spy to check the specific implementation of the method vs its api contract.
What if we refactor the method? The test might fail then, but the api contract is still fulfilled.
E.g. the method could return a "mock phone number prefix" like 555 and then an arbitrary number.

For me this isn't a blocker, but a cannot decide on this alone.

2022-02-03 23:13 UTC, piotrekn commented on test/phone.spec.ts
> +          const fakeHelpers_replaceSymbolWithNumberSpy = vi.spyOn(
This single test kinda really more on implementation here than the API contract check, tbh. It is random number and random format, so API contract check is very limited.

I don't know the specifics why that was important to spy on in the first place. Maybe it was a way to be sure that creating a phone number of a format was done with this particular method. If it's an essential part of the implementation, it might be good to ensure its usage.

Not sure what to make of it. If you want it gone, let me know 👍🏻

2022-02-04 08:24 UTC, Shinigami92 commented on test/phone.spec.ts
> +          const fakeHelpers_replaceSymbolWithNumberSpy = vi.spyOn(
We currently try to remove all spies and mocks, so that we only test the "API" instead of implementation details.
So, yea, I would like to get this removed :slightly_smiling_face:

2022-02-04 09:21 UTC, Shinigami92 approved these changes

2022-02-04 09:22 UTC, Shinigami92 requested changes

2022-02-04 09:22 UTC, Shinigami92 commented on test/phone.spec.ts
> +import { beforeEach, describe, expect, it, vi } from 'vitest';
This should not be required anymore :thinking: 

```suggestion
import { beforeEach, describe, expect, it } from 'vitest';
```

2022-02-04 10:08 UTC, Shinigami92 approved these changes

2022-02-04 11:12 UTC, ST-DDT approved these changes

2022-02-04 11:49 UTC, merged