chore: fix JSDoc comments in phone.ts
faker-js/faker pull request #397
Opened 2022-02-01 22:07 UTC by pkuczynski

Refs #203

2022-02-01 22:28 UTC, ST-DDT requested changes

2022-02-01 22:28 UTC, ST-DDT commented on src/phone.ts
> +   * Returns phone number.
```suggestion
   * Generates a random phone number.
```

2022-02-01 22:28 UTC, ST-DDT commented on src/phone.ts
> +   * Returns phone number in a format of the given index from `faker.definitions.phone_number.formats`.
```suggestion
   * Returns a phone number format of the given index from `faker.definitions.phone_number.formats`.
```

2022-02-01 22:28 UTC, ST-DDT commented on src/phone.ts
> +   * Returns phone number format.
```suggestion
   * Returns a random phone number format.
```

2022-02-01 22:52 UTC, pkuczynski commented on src/phone.ts
> +   * Returns phone number in a format of the given index from `faker.definitions.phone_number.formats`.
It does not return the format, but the phone number in this format...

2022-02-01 22:55 UTC, ST-DDT commented on src/phone.ts
> +   * Returns phone number in a format of the given index from `faker.definitions.phone_number.formats`.
`Returns phone number in a format` sounds like it returns a phone number to me.
That's why I changed it to `Returns a phone number format `.

2022-02-01 23:24 UTC, pkuczynski commented on src/phone.ts
> +   * Returns phone number in a format of the given index from `faker.definitions.phone_number.formats`.
Because it does return phone number :) Lookup the examples below @ST-DDT

2022-02-02 07:37 UTC, ST-DDT commented on src/phone.ts
> +   * Returns phone number in a format of the given index from `faker.definitions.phone_number.formats`.
Oh you are right. I totally got confused by the method name.

2022-02-02 07:38 UTC, ST-DDT approved these changes

2022-02-02 08:17 UTC, pkuczynski commented on src/phone.ts
> +   * Returns phone number in a format of the given index from `faker.definitions.phone_number.formats`.
Yeah, the method looks very odd, that's why I left a comment to consider dropping it in the future...

2022-02-02 14:10 UTC, Shinigami92 approved these changes

2022-02-02 18:16 UTC, import-brain approved these changes

2022-02-03 08:37 UTC, Shinigami92 approved these changes

2022-02-03 08:46 UTC, merged