chore: enable eslint cache
faker-js/faker pull request #403
Opened 2022-02-02 10:33 UTC by pkuczynski

2022-02-02 10:38 UTC, ST-DDT submitted a review, later dismissed

2022-02-02 10:39 UTC, ST-DDT commented
This works really nice. Where does it store the cache if I want to delete it?

2022-02-02 10:40 UTC, pkuczynski commented
> This works really nice. Where does it store the cache if I want to delete it?

Root of the project. Its already gitignored.

2022-02-02 20:48 UTC, prisis submitted a review, later dismissed

2022-02-06 01:06 UTC, clarkerican approved these changes

2022-02-06 12:24 UTC, ST-DDT approved these changes

2022-02-06 12:32 UTC, Shinigami92 commented
Tested it locally and seems to work
Just asking myself why this is not the default behavior of eslint :thinking: 
Should we also clean the cache-file on `pnpm run clean`?

2022-02-07 12:18 UTC, import-brain approved these changes

2022-02-10 19:07 UTC, Shinigami92 requested changes

2022-02-10 19:07 UTC, Shinigami92 commented on package.json
> +    "lint": "eslint --cache --cache-strategy content .",
Let's do it this way, so users can decide to use it or not, also the CI and lint-stage will not get affected by it and always use a clean lint run

```suggestion
    "lint": "eslint .",
    "lint:cache": "eslint --cache --cache-strategy content .",
```

2022-02-10 19:25 UTC, Shinigami92 commented on package.json
> +    "lint": "eslint --cache --cache-strategy content .",
https://github.com/eslint/eslint/issues/10712#issuecomment-409748549

2022-02-10 19:32 UTC, pkuczynski commented on package.json
> +    "lint": "eslint --cache --cache-strategy content .",
First of all the issue is 4y old and we are not using any of those plugins. Saying that, I am using `node` and `import` together with enabled cache and none of them ever caused any issues. I am not sure if anything changed since the linked issue was created and that's why I am not experiencing problems. But again we do not use those plugins and I would rather like to see a proof of malfunction than just make it very slow for everyone linting locally...

2022-02-10 19:40 UTC, Shinigami92 approved these changes
If we encounter any problems in the future, we can revert it

2022-02-10 19:46 UTC, Shinigami92 commented
@pkuczynski uhm... sry, but
How will this behave when having a dependency-update? Or something similar.
So e.g. the eslint rule itself changed in behavior but the file did not change?

So maybe we should really add it to the `clean` statement :grimacing:

2022-02-10 19:51 UTC, ST-DDT commented
Is it based on the content of the file itself?
What if you change the api in your method and that causes a warning in another (untouched) file?
( Is that even possible? 🤔 )

2022-02-10 19:54 UTC, Shinigami92 commented
> In the worse case scenario CI would caught the issue as it does not have the cache enabled

Okay :+1:

2022-02-10 19:55 UTC, Shinigami92 commented
We await approval from @prisis (or a third maintainer)
So give it some minutes

2022-02-10 19:57 UTC, prisis approved these changes

2022-02-10 19:58 UTC, merged