test: rewrite image tests
faker-js/faker pull request #414
Opened 2022-02-03 19:12 UTC by Shinigami92

The tests actually looking good :slightly_smiling_face: 
We can leave them for now as is, I just did some formatting and variable naming stuff

2022-02-03 21:28 UTC, ST-DDT requested changes

2022-02-03 21:28 UTC, ST-DDT commented on test/image.spec.ts
> +        const technology = faker.image.unsplash.technology();
plea use consistent variable naming in the tests. Either always append `Url` or always omit it.

2022-02-04 18:16 UTC, Shinigami92 commented on test/image.spec.ts
> +        const technology = faker.image.unsplash.technology();
generated dynamically now

2022-02-04 18:33 UTC, ST-DDT approved these changes

2022-02-04 23:39 UTC, ST-DDT approved these changes

2022-02-06 13:34 UTC, ST-DDT approved these changes

2022-02-07 12:20 UTC, import-brain approved these changes

2022-02-10 19:13 UTC, prisis approved these changes

2022-02-10 20:19 UTC, merged