ci: configure codecov
faker-js/faker pull request #426
Opened 2022-02-04 20:24 UTC by Shinigami92

closes #387

2022-02-04 21:18 UTC, Shinigami92 commented
I would say, let's try it out
If there is something miss-configured, we can change it later

2022-02-04 21:22 UTC, prisis requested changes

2022-02-04 21:22 UTC, prisis commented on .github/workflows/ci.yml
> +      - name: Install deps
2 times install?

2022-02-04 21:24 UTC, Shinigami92 commented on .github/workflows/ci.yml
> +
```suggestion
```

2022-02-04 21:26 UTC, prisis approved these changes

2022-02-04 21:28 UTC, ST-DDT approved these changes

2022-02-04 21:29 UTC, merged

2022-09-03 03:15 UTC, 1LISA2 commented
![下载 (2)](https://user-images.githubusercontent.com/103248540/188253756-b5b5ecd2-26a6-427a-9716-9539dfb6e43f.jpeg)