fix: added curated male, female & unisex middleName  for default(en) locale (#373)
faker-js/faker pull request #440
Opened 2022-02-05 23:00 UTC by budhathokg1

@Shinigami92 review..

2022-02-06 09:25 UTC, ST-DDT reviewed
Could you please add the source of these lists to this PR?

2022-02-06 09:25 UTC, ST-DDT commented on test/name.spec.ts
> +
A few lines below this is a test that you can enable by removing the todo from it.

2022-02-06 12:21 UTC, Shinigami92 requested changes

2022-02-06 12:21 UTC, Shinigami92 commented on src/name.ts
> +        }
I think this code occurs multiple times in the name module, we should move it into a private helper method

2022-02-06 18:25 UTC, budaG commented on test/name.spec.ts
> +
@ST-DDT good catch, enabled the test case for 'uk' locale. 
https://docs.google.com/spreadsheets/d/1I2GBSy7Y63hNYYtYr_hYbhk0bCI3phW5WDnEBlHCsD8/edit?usp=sharing
here is my worksheet with source URL, I used to scrape those names.

2022-02-06 18:27 UTC, budaG commented on src/name.ts
> +        }
@Shinigami92 I agree. Isolated the duplicated code into a private method. Let me know if it looks good.

2022-02-06 19:05 UTC, ST-DDT requested changes

2022-02-06 19:05 UTC, ST-DDT commented on src/name.ts
> +  private static determineGenderByStringParam(gender: string | number) {
IMO this method should do most of the gender related stuff.
String handling, unknown number handling, undefined handling (choose random).
This method should also only ever return `0 | 1´.

2022-02-06 19:16 UTC, budaG commented on test/name.spec.ts
> +
Just realized about the permission. Changed the permission so that everyone can see. Let me know if you see it otherwise.
Also that list has been sanitized for duplicates, trimmed and ordered before it made it to the code base.

2022-02-06 19:20 UTC, budaG commented on src/name.ts
> +  private static determineGenderByStringParam(gender: string | number) {
I see what you are saying and I agree we should have methods to handle all that separately rather than handling those scenarios in every method but that touches every method. I think it should be a separate story/enhancement/chore to do that. This was to fix the default locale middle name bug.

2022-02-06 23:52 UTC, ST-DDT commented on src/name.ts
> +  private static determineGenderByStringParam(gender: string | number) {
There are three ways:
- Just fix the middle name method without adding a new helper method.
- Fix the middle name method by creating a separate method, but don't use it in the other methods yet.
- Fix all name methods by creating a separate method and using it everywhere.

I suggest going for 1 or 2 and then creating a separate PR with option 3 later once this is merged.

2022-02-07 08:13 UTC, Shinigami92 commented on src/name.ts
> +  private static determineGenderByStringParam(gender: string | number) {
In the longtime goal, I would really like to **deprecate** numeric values for **gender**.
Why is `male = 0` and `female = 1`? What's with binary genders?
The string values would not have a numeric order.

@griest024 also wanted to introduce the possibility to additionally use enum. #352

---

I would currently like to see just a switch case with default fallback.
But I'm not sure if this becomes to much for this PR and we may want to split it to another PR.
On the other side, as we already targeting 6.1 with this PR, maybe it's okay...

---

I would write it like so that we can call it this way:
```ts
export type Gender = ...;

firstName(gender?: Gender): string
  return this.<functionName>(gender, this.faker.definitions.name.<arrayToUse>);
}
```

2022-02-07 16:49 UTC, budaG commented on src/name.ts
> +  private static determineGenderByStringParam(gender: string | number) {
I like the idea of Enum, but if we are choosing between lesser of the two evils, switch vs if, for now, I would stick with if, more concise and clear. Let me know your thoughts.

2022-02-08 00:45 UTC, JessicaSachs commented on src/name.ts
> +  private static determineGenderByStringParam(gender: string | number) {
Non-technical nit: can we, like, literally remove the "gender binary" from our codebase (at some point)? I think we can still have the API, but I'd like to make an explicit effort to revamp everything surrounding gender in the lib. I feel pretty strongly about this.

2022-02-08 02:10 UTC, JessicaSachs commented on src/name.ts
> +  private static determineGenderByStringParam(gender: string | number) {
> Why is male = 0 and female = 1? What's with binary genders?

lol I love you Shini.

2022-03-10 19:40 UTC, Shinigami92 commented
@budaG This PR needs a rebase

2022-03-21 14:26 UTC, Shinigami92 approved these changes

2022-03-21 14:31 UTC, merged