docs: use vue components for api-docs
faker-js/faker pull request #446
Opened 2022-02-07 13:01 UTC by ST-DDT

2022-02-07 13:27 UTC, Shinigami92 requested changes

2022-02-07 13:27 UTC, Shinigami92 commented on docs/.vitepress/components/api-docs/method-parameters.vue
> +        <tr v-for="parameter of props.parameters" v-bind:key="parameter">
```suggestion
        <tr v-for="parameter of props.parameters" :key="parameter">
```

2022-02-07 13:27 UTC, Shinigami92 commented on docs/.vitepress/components/api-docs/method-parameters.vue
> +        <tr v-for="parameter of props.parameters" v-bind:key="parameter">
I assume `parameter` is not of type `string`. We should take a unique value as `:key`
I think we can use `:key="parameter.name"` here, cause `name` should always be a unique key

2022-02-07 13:27 UTC, Shinigami92 commented on docs/.vitepress/components/api-docs/method-parameters.vue
> +          <td v-html="parameter.description"></td>
@JessicaSachs I would like to hear your points about the usage of `v-html`
As far as I know it is mostly a security issue, is it?

2022-02-07 13:27 UTC, Shinigami92 commented on scripts/apidoc.ts
> +        if (index == 0) {
```suggestion
        if (index === 0) {
```

2022-02-07 13:40 UTC, ST-DDT commented on docs/.vitepress/components/api-docs/method-parameters.vue
> +          <td v-html="parameter.description"></td>
If requested I can also apply HTML sanitize before setting it.

2022-02-19 18:04 UTC, Shinigami92 submitted a review, later dismissed
If this is actually working and serve benefits, I will not block it just because of the usage of `v-html`
We should just keep it in mind, and if we know better we could fix it or workaround it in the future :shrug:

2022-02-20 00:12 UTC, ST-DDT commented on docs/.vitepress/components/api-docs/method-parameters.vue
> +          <td v-html="parameter.description"></td>
I now sanitize the api docs before writing the files. That should be safe enough.

2022-02-20 00:19 UTC, ST-DDT commented
The changes to `random.ts` are required, because it does get treated as html attributes.

````txt
Rejected unsafe md: Defaults to { bannedChars: [] }
Rejected unsafe html: <p bannedChars:="" []="">Defaults to</p>

Expected safe html: <p>Defaults to</p>

````

2022-02-20 00:20 UTC, ST-DDT commented
@Shinigami92 VSCode reports `string.replaceAll` to not exist in `apidoc.ts`. It runs fine though. Any idea why?

2022-02-20 05:59 UTC, Shinigami92 commented
> @Shinigami92 VSCode reports `string.replaceAll` to not exist in `apidoc.ts`. It runs fine though. Any idea why?

replaceAll is a really new js feature and was added last year, maybe not all node version support it yet
Use replace(/.../g, ...) instead

2022-02-20 17:02 UTC, Shinigami92 commented on scripts/apidoc.ts
> +      // typeParameters
If this is a section comment, maybe use not camelCase here but Title Case or just a sentence

2022-02-20 17:02 UTC, Shinigami92 commented on scripts/apidoc.ts
> +      // parameters
Same here

2022-02-20 17:02 UTC, Shinigami92 commented on scripts/apidoc.ts
> +      if (exampleTags.length !== 0) {
Should we use `>` for better readability?

2022-02-20 17:05 UTC, ST-DDT commented on scripts/apidoc.ts
> +// import vitepressConfig from '../docs/.vitepress/config';
At some point I would like to actually import that config. Sadly, I cannot do so at this point in time.
Should I add a TODO here?

2022-02-20 17:25 UTC, Shinigami92 submitted a review, later dismissed

2022-02-20 17:33 UTC, prisis approved these changes

2022-02-20 18:16 UTC, prisis approved these changes

2022-02-20 18:27 UTC, Shinigami92 approved these changes

2022-02-20 18:27 UTC, merged