test: rewrite vehicle
faker-js/faker pull request #469
Opened 2022-02-11 14:30 UTC by Shinigami92

2022-02-11 15:01 UTC, ST-DDT requested changes

2022-02-11 15:13 UTC, ST-DDT requested changes

2022-02-11 15:13 UTC, ST-DDT commented on src/locales/en/vehicle/index.ts
> +  bicycle_type: bicycle,
Do you need this change for your tests?

Either revert this change or also rename the actual files, because this file will be generated soon.

2022-02-15 14:05 UTC, prisis approved these changes

2022-02-15 14:48 UTC, merged