feat: Seperate methods for object key value
faker-js/faker pull request #503
Opened 2022-02-17 20:01 UTC by xDivisionByZerox

Thinks I have done:
- Create and implement 2 new methods `faker.random.objectValue` and `faker.random.objectKey`
- Wrote documentation for both methods
- Wrote test for both methods
- Added a deprecation flag and log for `faker.random.objectElement`

2022-02-17 21:35 UTC, ST-DDT approved these changes

2022-03-12 17:43 UTC, ST-DDT commented on src/random.ts
> +   * @deprecated
Please add `@see` references to the new methods.

2022-03-12 22:20 UTC, Shinigami92 commented on src/random.ts
> +   * @deprecated
Do we need to add this annotation and the see to both JSDocs? I think so.

2022-03-12 22:24 UTC, xDivisionByZerox commented on src/random.ts
> +   * @deprecated
I'm more concerned why there are 2 JSDocs in the first place. Is this some kind of merge problem?

2022-03-12 22:29 UTC, Shinigami92 commented on src/random.ts
> +   * @deprecated
Was added here: https://github.com/faker-js/faker/pull/596
Sadly I think I discussed with @ST-DDT in voice chat without writing a comment about the why
It was something like the one is shown in VSCode and the other is picked up from TypeDoc

2022-03-12 22:44 UTC, xDivisionByZerox commented on src/random.ts
> +   * @deprecated
Added the `@see` decorator to both JSDocs in 30711140ee4a7380853e7b4c91a0170aacfa694e

2022-03-13 08:47 UTC, ST-DDT commented on src/random.ts
> +   *
This one is missing the deprecated flag.

2022-03-13 08:52 UTC, ST-DDT commented on src/random.ts
> +   *
Please also add a `// For typedoc/api docs` comment above this jsdocs.
That way it's easy to tell why it is here.

2022-03-13 12:20 UTC, xDivisionByZerox commented on src/random.ts
> +   *
Should be done now

2022-03-13 13:17 UTC, ST-DDT submitted a review, later dismissed

2022-03-13 16:56 UTC, Shinigami92 submitted a review, later dismissed

2022-03-26 00:24 UTC, import-brain commented on src/random.ts
> +      'Deprecation Warning: faker.random.objectElement is now split into 2 seperate methods faker.datatype.objectKey and faker.datatype.objectValue'
```suggestion
      'Deprecation Warning: faker.random.objectElement() is now split into 2 separate methods: faker.datatype.objectKey() and faker.datatype.objectValue().'
```

2022-03-26 00:24 UTC, import-brain commented on src/random.ts
> +      'Deprecation Warning: faker.random.objectElement is now split into 2 seperate methods faker.datatype.objectKey and faker.datatype.objectValue'
Very small change, but I think this makes the warning slightly easier to read.

2022-03-26 10:15 UTC, xDivisionByZerox commented
The failing CI doesn't seem to be related to the changes I made, rather than with the `fake` module.
```
2022-03-26T09:57:08.4524974Z  > Fake.fake src/fake.ts:85:12
2022-03-26T09:57:08.4525598Z
2022-03-26T09:57:08.4526162Z     if (this.faker[parts[0]] == null) {
2022-03-26T09:57:08.4527269Z           throw new Error('Invalid module: ' + parts[0]);
2022-03-26T09:57:08.4527942Z                             ^
2022-03-26T09:57:08.4528536Z     }

Error: invalid module: {datatype
```

I guess a rebase could fix this. (?)

2022-03-26 10:48 UTC, Shinigami92 requested changes
1. We need to add test for the deprecation warning
2. We need to swap out all internal usages like in `finance.currencyCode` (please use search to find more occurrences)

2022-03-26 10:56 UTC, Shinigami92 commented
> The failing CI doesn't seem to be related to the changes I made, rather than with the `fake` module.
> 
> ```
> 2022-03-26T09:57:08.4524974Z  > Fake.fake src/fake.ts:85:12
> 2022-03-26T09:57:08.4525598Z
> 2022-03-26T09:57:08.4526162Z     if (this.faker[parts[0]] == null) {
> 2022-03-26T09:57:08.4527269Z           throw new Error('Invalid module: ' + parts[0]);
> 2022-03-26T09:57:08.4527942Z                             ^
> 2022-03-26T09:57:08.4528536Z     }
> 
> Error: invalid module: {datatype
> ```
> 
> I guess a rebase could fix this. (?)

I'm not totally sure what's going on here, I hope @ST-DDT has some more in-depth inside into the fake function and what could be the problem here related to this PR changes
`main` branch is green and I did not see this previously somewhere

Here is a local failed test result

```js
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/all_functional.spec.ts > faker.fake functional tests > uk > datatype > array()
Error: Invalid module: {datatype
 ❯ Fake.fake src/fake.ts:85:12
     83| 
     84|     if (this.faker[parts[0]] == null) {
     85|       throw new Error('Invalid module: ' + parts[0]);
       |            ^
     86|     }
     87| 
 ❯ Fake.fake src/fake.ts:124:16
 ❯ test/all_functional.spec.ts:96:35

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
```

2022-03-26 18:00 UTC, ST-DDT commented
I have identified the issue.
The generated string contains a `$` which causes the string replace method to insert the token again. In this case the `$` was directly after a `{` which then caused the issue.
I will provide a fix for the faker method.

2022-03-26 19:34 UTC, ST-DDT commented
Fix and test provided: https://github.com/faker-js/faker/pull/688/files#diff-d764addde9b944dba41e8666051bf020b5f44349c6043d6d7770bd58073eca25R83

2022-03-28 22:37 UTC, ST-DDT requested changes

2022-03-28 22:37 UTC, ST-DDT commented on src/random.ts
> +    );
This should use the new deprecation helper method.

2022-04-19 21:45 UTC, ST-DDT commented on src/random.ts
> +    );
@xDivisionByZerox This is almost ready to merge. Do you have time to address this soonish or should we change it for you?

2022-04-29 11:12 UTC, Shinigami92 commented
I just found out that we need JSDoc with `@deprecated` on ALL signatures!

<img src="https://user-images.githubusercontent.com/7195563/165933804-1e2fc4e0-33b7-4644-94a3-fcda864139e0.png" width="600px"/>

In the one line with not using 'key', it is not strikedthrough...

2022-04-29 12:53 UTC, ST-DDT requested changes

2022-04-29 12:53 UTC, ST-DDT commented on src/random.ts
> +    return key;
IMO you can directly return here instead of storing it in const.

2022-04-29 12:53 UTC, ST-DDT commented on src/random.ts
> +    return value;
Same here.

2022-04-29 12:53 UTC, ST-DDT commented on src/random.ts
> +    object: T = { foo: 'bar', too: 'car' } as unknown as T
IMO this method should not have a default value.

2022-04-29 12:53 UTC, ST-DDT commented on src/random.ts
> +    object: T = { foo: 'bar', too: 'car' } as unknown as T
IMO this method should not have a default value.

2022-04-29 17:24 UTC, ST-DDT approved these changes

2022-04-30 08:56 UTC, Shinigami92 approved these changes

2022-04-30 08:56 UTC, merged