feat: add internet.emoji
faker-js/faker pull request #504
Opened 2022-02-17 21:54 UTC by hugoattal

fix: https://github.com/faker-js/faker/issues/497

So I added a function `faker.internet.emoji()` that generate emojis.
You can also filter only some groups of emoji with `faker.internet.emoji(["food"])` for example.

I took all the fully-qualified emoji of Unicode : https://unicode.org/Public/emoji/14.0/emoji-test.txt

I didn't separate each subgroup, as I don't think people need that much granularity.
I also disabled prettier on the `emoji.ts` file to have a more readable file so that you can spot the group names, but I can keep the prettier format if you prefer.

For the test, I only check if the string has a length of at least 1, as the regex to check emoji are quite hacky for now.
I found using a package (such as this one: https://github.com/mathiasbynens/emoji-regex) only for this test to be unnecessary.

2022-02-17 22:38 UTC, ST-DDT commented on src/locales/en/internet/emoji.ts
> +    '👏','👏🏻','👏🏼','👏🏽','👏🏾','👏🏿','🙌','🙌🏻','🙌🏼','🙌🏽','🙌🏾','🙌🏿','🫶','🫶🏻','🫶🏼','🫶🏽','🫶🏾','🫶🏿','👐','👐🏻','👐🏼','👐🏽','👐🏾','👐🏿','🤲','🤲🏻','🤲🏼','🤲🏽','🤲🏾','🤲🏿','🤝','🤝🏻','🤝🏼','🤝🏽','🤝🏾','🤝🏿','🫱🏻‍🫲🏼','🫱🏻‍🫲🏽','🫱🏻‍🫲
Some of don't seem to work in my browser or IDE:

> '🫶','🫶🏻'

AFAICT these are added in `E14.0` . Should we exclude those then?
Or do you have an ETA when browsers/IDEs are going to add them?

2022-02-17 22:52 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +    '👏','👏🏻','👏🏼','👏🏽','👏🏾','👏🏿','🙌','🙌🏻','🙌🏼','🙌🏽','🙌🏾','🙌🏿','🫶','🫶🏻','🫶🏼','🫶🏽','🫶🏾','🫶🏿','👐','👐🏻','👐🏼','👐🏽','👐🏾','👐🏿','🤲','🤲🏻','🤲🏼','🤲🏽','🤲🏾','🤲🏿','🤝','🤝🏻','🤝🏼','🤝🏽','🤝🏾','🤝🏿','🫱🏻‍🫲🏼','🫱🏻‍🫲🏽','🫱🏻‍🫲
Or I can simply use the E12.0 : https://unicode.org/Public/emoji/12.0/emoji-test.txt

2022-02-18 07:44 UTC, Shinigami92 requested changes

2022-02-18 07:44 UTC, Shinigami92 commented on src/definitions/internet.ts
> +    [key in
This doesn't look correctly formatted with prettier

Maybe you also want to do something like `emoji: Record<EmojiGroup, string[]>`

2022-02-18 07:44 UTC, Shinigami92 commented on src/internet.ts
> +  emoji(filters?: Array<keyof InternetDefinitions['emoji']>): string {
Maybe provide an option obj like

```ts
emoji(options: {
  filters?: Array<...>
  versions?: Array<EmojiVersion>
} = {})
```

2022-02-18 08:13 UTC, ST-DDT commented on src/internet.ts
> +  emoji(filters?: Array<keyof InternetDefinitions['emoji']>): string {
I object having an emoji version parameter.

2022-02-18 08:17 UTC, Shinigami92 commented on src/internet.ts
> +  emoji(filters?: Array<keyof InternetDefinitions['emoji']>): string {
> I object having an emoji version parameter.

Any reason why?

2022-02-18 08:51 UTC, ST-DDT commented on src/internet.ts
> +  emoji(filters?: Array<keyof InternetDefinitions['emoji']>): string {
IMO this library is not about testing charsets or rendering pipelines.
If you need those, you have to use the full set of emojis/unicode anyway.
Thus we should not differenciate between versions "words". We also dont add support for switching between new or old language dictionaries.

2022-02-18 10:44 UTC, Shinigami92 commented on src/internet.ts
> +  emoji(filters?: Array<keyof InternetDefinitions['emoji']>): string {
@ST-DDT Makes sense and I accept that :+1:

2022-02-18 11:12 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +    '👏','👏🏻','👏🏼','👏🏽','👏🏾','👏🏿','🙌','🙌🏻','🙌🏼','🙌🏽','🙌🏾','🙌🏿','🫶','🫶🏻','🫶🏼','🫶🏽','🫶🏾','🫶🏿','👐','👐🏻','👐🏼','👐🏽','👐🏾','👐🏿','🤲','🤲🏻','🤲🏼','🤲🏽','🤲🏾','🤲🏿','🤝','🤝🏻','🤝🏼','🤝🏽','🤝🏾','🤝🏿','🫱🏻‍🫲🏼','🫱🏻‍🫲🏽','🫱🏻‍🫲
> Support for Emoji 14.0 is now available via Google's [Android 12L](https://emojipedia.org/google/android-12l/) update and the first beta update of Apple's [iOS 15.4](https://blog.emojipedia.org/first-look-new-emojis-in-ios-15-4/).

Source: https://emojipedia.org/emoji-14.0/

---

I'm sorry, but I really don't understand why the fact that not all tools support it means we shouldn't include it 😕. If a user can write an emoji on their Android and people on Windows can't see it, well it's "too bad", but it's a real word situation.

I believe this library is to generate/test real-world data, not narrowing down to easy situations.

2022-04-05 14:24 UTC, Shinigami92 commented
We're starting work on the `v6.2` milestone, but this PR needs a rebase.
Please rebase and resolve all conflicts. Until then, we're moving it to the `v6` milestone, which now serves as the "v6-Backlog".
If this PR no longer contains any conflicts and can certainly be a target for the next release, we will move it to the then active milestone `v6.x`.

2022-04-05 18:53 UTC, hugoattal commented
Yep sorry, kinda forgot about it... I'll do the rebase and the updates tomorrow!

2022-04-09 00:14 UTC, hugoattal commented on src/definitions/internet.ts
> +    [key in
I did that here: https://github.com/faker-js/faker/blob/8731d5c3ff4d557c3a2eae54f46ee0042e7cc966/src/definitions/internet.ts#L34

This is correctly formatted by ESLint, I find this easier to read than having everything on a single line, but I can put it on one line if you prefer!

2022-04-09 00:16 UTC, hugoattal commented
Sorry for the little mess in the commits, first time I rebased a forked repo 😅...
Everything should be good now 🙂

2022-04-09 01:00 UTC, ST-DDT submitted a review, later dismissed

2022-04-09 02:07 UTC, import-brain approved these changes, later dismissed

2022-04-09 07:33 UTC, pkuczynski commented on src/locales/en/internet/emoji.ts
> +    '👏','👏🏻','👏🏼','👏🏽','👏🏾','👏🏿','🙌','🙌🏻','🙌🏼','🙌🏽','🙌🏾','🙌🏿','🫶','🫶🏻','🫶🏼','🫶🏽','🫶🏾','🫶🏿','👐','👐🏻','👐🏼','👐🏽','👐🏾','👐🏿','🤲','🤲🏻','🤲🏼','🤲🏽','🤲🏾','🤲🏿','🤝','🤝🏻','🤝🏼','🤝🏽','🤝🏾','🤝🏿','🫱🏻‍🫲🏼','🫱🏻‍🫲🏽','🫱🏻‍🫲
I am with @ST-DDT on this and would stick to version 13. Faker does not need to generate every possible piece of data, but rather data which looks like valid and coming from a user. If those new emojis are not supported yet on peoples devices, it's unlikely someone would use them, right? So there is no pressure to include them on our side either.

2022-04-09 07:44 UTC, pkuczynski requested changes

2022-04-09 07:44 UTC, pkuczynski commented on src/definitions/internet.ts
> +export type EmojiGroups =
```suggestion
export type EmojiGroup =
```

Personally I would call it a `type` and not a `group`, but that's only a side note...

2022-04-09 07:44 UTC, pkuczynski commented on src/definitions/internet.ts
> +  | 'smileys'
```suggestion
  | 'smiley'
```

Can you keep singular form for consistency?

2022-04-09 07:44 UTC, pkuczynski commented on src/internet.ts
> +  emoji(filters?: Array<keyof InternetDefinitions['emoji']>): string {
```suggestion
  emoji(group?: Array<EmojiGroup>): string {
```

2022-04-09 07:44 UTC, pkuczynski commented on src/locales/en/internet/emoji.ts
> +export default {
Could you add a link to the source of this? And if we decide to limit on the version maybe a short note about it...

2022-04-09 07:44 UTC, pkuczynski commented on src/locales/en/internet/emoji.ts
> +// prettier-ignore
Emoji are not connected to i18n and they the same for every language, right? So is it a good place to put them here under `en` @ST-DDT @Shinigami92? Feels to me they should find a better location...

2022-04-09 07:48 UTC, pkuczynski commented on src/definitions/internet.ts
> +export type EmojiGroups =
After a bit of thinking it really feels more like a `type`: `food`, `smiley`, `body`... and in the definitions, that just grouped by type. But what you want from the user in the method definitions is to _limit emoji to a certain type_...

2022-04-09 12:51 UTC, hugoattal commented on src/definitions/internet.ts
> +  | 'smileys'
Fixed here: https://github.com/faker-js/faker/pull/504/commits/6badfaaa55667c694d80753bbb63698be463229a

2022-04-09 12:52 UTC, hugoattal commented on src/internet.ts
> +  emoji(filters?: Array<keyof InternetDefinitions['emoji']>): string {
Done here: https://github.com/faker-js/faker/pull/504/commits/82cad3d5a251ec168f8266202449feca429106cf

2022-04-09 12:54 UTC, hugoattal commented on src/definitions/internet.ts
> +export type EmojiGroups =
From the unicode source, this is call a `group`. Can you confirm that you want me to rename it to `type`?
cf https://unicode.org/Public/emoji/14.0/emoji-test.txt

![image](https://user-images.githubusercontent.com/4563971/162574972-680a2591-f267-4258-ac90-df598df19746.png)

2022-04-09 12:55 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +export default {
Added here: https://github.com/faker-js/faker/blob/82cad3d5a251ec168f8266202449feca429106cf/src/locales/en/internet/emoji.ts#L3

> And if we decide to limit on the version maybe a short note about it...

I'm not sure to understand what you mean by that... Could you elaborate?

2022-04-09 13:00 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +// prettier-ignore
I have no problem putting it somewhere else, but I couldn't find a function that were not inside the locals folder. (and the default one being `en`).

Could you point me to an example? Or should I update the architecture to have to generic functions?

2022-04-09 13:52 UTC, pkuczynski commented on src/definitions/internet.ts
> +export type EmojiGroups =
In the source file its called a group, which indeed collects emojis by type :) Its kind of like you would group cars by size: sedan, suv, etc. Collection of all SUV would be a group, but the attribute they are grouped by would be `size`. Does that make sense?

2022-04-09 14:07 UTC, pkuczynski commented on src/locales/en/internet/emoji.ts
> +export default {
@ST-DDT suggested we stick with version 13.1 which seems to have wider adoption (and I agree with this suggestion). Than we should add a note about it in case someone else stumble upon this next time. Does this make sense?

I would also link https://www.unicode.org/versions/enumeratedversions.html as primary source as the `txt` is only a partial of the whole standard...

2022-04-09 14:08 UTC, pkuczynski commented on src/locales/en/internet/emoji.ts
> +// prettier-ignore
I see your pain as there is no standard for it. I would wait for what other guys think. but maybe same folder but `internet.emoji.ts`?

2022-04-09 14:10 UTC, pkuczynski commented on src/definitions/internet.ts
> +export type EmojiGroups =
And here they call them _category_ https://home.unicode.org/emoji/emoji-frequency/

Yeah, I am pretty sure it should be called differently then `group` as its too general word. You can group emojis in many different ways...

2022-04-10 10:09 UTC, Shinigami92 commented on src/locales/en/internet/emoji.ts
> +// prettier-ignore
We are drafting that out in https://github.com/faker-js/faker/issues/823
We had unwritten plans for this for a month or two, but never wrote it down into an issue, so finally we have this issue now :slightly_smiling_face:

2022-04-10 15:02 UTC, ST-DDT requested changes
Please switch to emoji v13.0.
Other then that, it looks good to me and ready to be merged in v6.2.

2022-04-10 15:02 UTC, ST-DDT commented on src/locales/en/internet/emoji.ts
> +    '👏','👏🏻','👏🏼','👏🏽','👏🏾','👏🏿','🙌','🙌🏻','🙌🏼','🙌🏽','🙌🏾','🙌🏿','🫶','🫶🏻','🫶🏼','🫶🏽','🫶🏾','🫶🏿','👐','👐🏻','👐🏼','👐🏽','👐🏾','👐🏿','🤲','🤲🏻','🤲🏼','🤲🏽','🤲🏾','🤲🏿','🤝','🤝🏻','🤝🏼','🤝🏽','🤝🏾','🤝🏿','🫱🏻‍🫲🏼','🫱🏻‍🫲🏽','🫱🏻‍🫲
**Maintainer decision**: Please switch to emoji v13.0 for now.
For us, it is more important to generate valid/working data, then generating all possible data.
Most users use this framework in combination with existing tools/browsers and thus there is hardly anything they can do in their application to "fix" these unsupported emojis.

Tests that are intended to test compatibility with a certain new feature are best implemented using exactly that in their tests. Which also need special visual tests to very are they displayed as icon or as missing char text.

Tests that are intended to test the behavior with explicitly unknown emojis/characters are the same.

We may or may not add an option for a specific emoji versions later, but for now I consider this out of the scope of our library.

> I believe this library is to generate/test real-world data, not narrowing down to easy situations.

We do generate/use real world data, not arbitary data.
Our strings are limited to printable characters (emojis), not arbitary binary data displayed as string.
Tests for specific edge cases, should always be implemented using fixed values, not random ones, otherwise you have a test that fails 1 in 1000 or less times and you don't know why.

2022-04-10 15:03 UTC, ST-DDT commented on src/locales/en/internet/emoji.ts
> +// prettier-ignore
No need to move it yet. We will move it, once we have decided, where to put it.

2022-04-10 15:05 UTC, ST-DDT commented on src/locales/en/internet/emoji.ts
> +export default {
Yes, please add the link below the other link:

````ts
// Source: https://unicode.org/Public/emoji/14.0/emoji-test.txt 
// Other versions: https://www.unicode.org/versions/enumeratedversions.html
````

2022-04-10 15:10 UTC, ST-DDT commented on src/definitions/internet.ts
> +export type EmojiGroups =
@pkuczynski IMO since we use that source we should also stick to their names.
group and category are just synonmys. You could group/categorize them however you want, but we use the "official" groups.

If you have a better name for it, then we can decide on that then.

2022-04-10 15:15 UTC, ST-DDT commented on src/internet.ts
> +      >);
```suggestion
      (Object.keys(this.faker.definitions.internet.emoji) as Array<EmojiGroup>);
```

is the cast needed at all?

2022-04-10 15:28 UTC, hugoattal commented on src/internet.ts
> +      >);
Yes, this is needed:
![image](https://user-images.githubusercontent.com/4563971/162626951-3888e7f1-3c2d-42b4-85de-39416c6e55b6.png)

Though, I updated the type in https://github.com/faker-js/faker/pull/504/commits/faba4db059a401d45c7521ca76931e94aa6eeaef

2022-04-10 15:29 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +export default {
I updated to v13 and added the link: https://github.com/faker-js/faker/pull/504/commits/28f13af0a592f9417c11db4adf392873b2c176f0

2022-04-10 15:30 UTC, hugoattal commented on src/definitions/internet.ts
> +export type EmojiGroups =
Aaaah, I renamed it to type >< ... https://github.com/faker-js/faker/pull/504/commits/24727edfbe7c4f7863e77f91ccda147a9eba627f

Should I change it back?

2022-04-10 15:30 UTC, pkuczynski commented on src/locales/en/internet/emoji.ts
> +    '👏','👏🏻','👏🏼','👏🏽','👏🏾','👏🏿','🙌','🙌🏻','🙌🏼','🙌🏽','🙌🏾','🙌🏿','🫶','🫶🏻','🫶🏼','🫶🏽','🫶🏾','🫶🏿','👐','👐🏻','👐🏼','👐🏽','👐🏾','👐🏿','🤲','🤲🏻','🤲🏼','🤲🏽','🤲🏾','🤲🏿','🤝','🤝🏻','🤝🏼','🤝🏽','🤝🏾','🤝🏿','🫱🏻‍🫲🏼','🫱🏻‍🫲🏽','🫱🏻‍🫲
I totally support what has been written here...

2022-04-10 15:31 UTC, ST-DDT requested changes

2022-04-10 15:31 UTC, ST-DDT commented on src/internet.ts
> +   * @param types
```suggestion
   * @param types A list of the emoji types that should be used.
   *
```

2022-04-10 15:31 UTC, ST-DDT commented on src/locales/en/internet/emoji.ts
> +// Versions: https://www.unicode.org/versions/enumeratedversions.html
```suggestion
// Versions: https://unicode.org/versions/enumeratedversions.html
```

2022-04-10 15:32 UTC, pkuczynski commented on src/definitions/internet.ts
> +export type EmojiGroups =
My better name is `Type` @ST-DDT :)

2022-04-10 15:33 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +// Versions: https://www.unicode.org/versions/enumeratedversions.html
Their base domain is with the `www` and all their link use the domain with the `www`, so I let it like this.
You really want to remove the `www` ?

![image](https://user-images.githubusercontent.com/4563971/162627186-fb14fb75-060f-49a1-8240-9b07a7d65909.png)

2022-04-10 15:33 UTC, pkuczynski commented on src/definitions/internet.ts
> +export type EmojiGroups =
> Should I change it back?

Nah, I think you can keep it, unless @ST-DDT disagrees?

2022-04-10 15:47 UTC, pkuczynski submitted a review, later dismissed

2022-04-10 15:47 UTC, pkuczynski commented on src/definitions/internet.ts
> +   * List of all fully-qualified emoji ordered by groups.
```suggestion
   * List of all fully-qualified emojis.
```

2022-04-10 15:52 UTC, ST-DDT commented on src/locales/en/internet/emoji.ts
> +// Versions: https://www.unicode.org/versions/enumeratedversions.html
If they use www everywhere then please do the same in the comment. I just want all three links to be consistent.

2022-04-10 15:58 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +// Versions: https://www.unicode.org/versions/enumeratedversions.html
Oops, yep, I missed this 😅... fixed: https://github.com/faker-js/faker/pull/504/commits/213ad4497f336c34f01ca7d75fa8f9ac84513102

2022-04-10 16:21 UTC, ST-DDT approved these changes, later dismissed

2022-04-10 16:53 UTC, Shinigami92 requested changes

2022-04-10 16:53 UTC, Shinigami92 commented on src/definitions/internet.ts
> +export type EmojiType =
IMO we should move this type out of definitions into the module file
~~Also export it same as e.g. GenderType in name module~~ nevermind, already doing that :+1: just the file need to change

2022-04-10 16:53 UTC, Shinigami92 commented on src/internet.ts
> +  emoji(types?: Array<EmojiType>): string {
Just to be a bit more future safe and we already try to do this in other places, could we use options here?

```suggestion
  emoji(options: { types?: Array<EmojiType> } = {}): string {
```

These can be extended on demand in the future

2022-04-10 16:53 UTC, Shinigami92 commented on src/locales/en/internet/emoji.ts
> +// prettier-ignore
Do we really need to not format this file? It could raise potentially more git conflicts when working on this file later on.

2022-04-10 16:53 UTC, Shinigami92 commented on src/locales/en/internet/emoji.ts
> +    '😀','😃','😄','😁','😆','😅','🤣','😂','🙂','🙃','😉','😊','😇',
Is it possible to generate these emojis with code-points like `U+1F600` and then just with a range?

2022-04-10 16:53 UTC, Shinigami92 commented on test/internet.spec.ts
> +          expect(typeof emoji).toBe('string');
```suggestion
          expect(emoji).toBeTypeOf('string');
```

2022-04-10 16:53 UTC, Shinigami92 commented on test/internet.spec.ts
> +          expect(emoji.length).toBeGreaterThanOrEqual(1);
If testing against a lower bound, should we also test against a upper bound?

2022-04-10 17:00 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +    '😀','😃','😄','😁','😆','😅','🤣','😂','🙂','🙃','😉','😊','😇',
I feel like it would be a bit overengineered, and very difficult to read... Also, emojis does not always have consecutive code-points. Here are the ones you selected:

```
1F600  ; fully-qualified     # 😀 E1.0 grinning face
1F603  ; fully-qualified     # 😃 E0.6 grinning face with big eyes
1F604  ; fully-qualified     # 😄 E0.6 grinning face with smiling eyes
1F601  ; fully-qualified     # 😁 E0.6 beaming face with smiling eyes
1F606  ; fully-qualified     # 😆 E0.6 grinning squinting face
1F605  ; fully-qualified     # 😅 E0.6 grinning face with sweat
1F923  ; fully-qualified     # 🤣 E3.0 rolling on the floor laughing
1F602  ; fully-qualified     # 😂 E0.6 face with tears of joy
1F642  ; fully-qualified     # 🙂 E1.0 slightly smiling face
1F643  ; fully-qualified     # 🙃 E1.0 upside-down face
1FAE0  ; fully-qualified     # 🫠 E14.0 melting face
1F609  ; fully-qualified     # 😉 E0.6 winking face
1F60A  ; fully-qualified     # 😊 E0.6 smiling face with smiling eyes
1F607  ; fully-qualified     # 😇 E1.0 smiling face with halo
```

2022-04-10 17:03 UTC, hugoattal commented on test/internet.spec.ts
> +          expect(emoji.length).toBeGreaterThanOrEqual(1);
I don't think it's future-proof as some emojis are made of several emojis next to each others

![image](https://user-images.githubusercontent.com/4563971/162630894-20408bc0-01ea-4786-bf54-a919b9176883.png)

2022-04-10 17:05 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +// prettier-ignore
I believe it's way easier to work with this format, but I can change this if you confirm that you prefer a 5k lines file 😅.

2022-04-10 17:12 UTC, hugoattal commented on src/definitions/internet.ts
> +export type EmojiType =
Done here: https://github.com/faker-js/faker/pull/504/commits/0052ba02708cbd16cc3b538d34e074b3cd7e4ed7

2022-04-10 17:18 UTC, hugoattal commented on src/internet.ts
> +  emoji(types?: Array<EmojiType>): string {
Done here: https://github.com/faker-js/faker/pull/504/commits/af8f73bf96f5ea5bb58924b75da2829caeb02c56 !

2022-04-10 17:24 UTC, Shinigami92 commented on src/internet.ts
> +      this.faker.definitions.internet.emoji[group]
```suggestion
   * faker.internet.emoji({ types: ['food', 'nature'] }) // '🥐'
   */
  emoji(options: { types?: ReadonlyArray<EmojiType> } = {}): string {
    const {
      types = Object.keys(this.faker.definitions.internet.emoji) as Array<EmojiType>
    } = options;
    const emojiType = this.faker.random.arrayElement(types);
    return this.faker.random.arrayElement(
      this.faker.definitions.internet.emoji[group]
```

2022-04-10 17:31 UTC, hugoattal commented on src/internet.ts
> +      this.faker.definitions.internet.emoji[group]
Done: https://github.com/faker-js/faker/pull/504/commits/194604e32f9be56d21795649ca04fae19a084122

2022-04-10 17:48 UTC, Shinigami92 commented on src/locales/en/internet/emoji.ts
> +// prettier-ignore
We also already have a 8k lines file here: https://github.com/faker-js/faker/blob/main/src/locales/en/system/mimeTypes.ts
So I would aim just for consistency here and format it. It's easier to work with them in the future when comparing diffs.

2022-04-10 17:51 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +// prettier-ignore
Done here: https://github.com/faker-js/faker/pull/504/commits/cdb59221298a4b6637602c11d20163040f5d0ad3 !

2022-04-10 18:27 UTC, Shinigami92 reviewed
I found some non-emoji emojis :thinking: Not sure what to do with them or it is my system and a non-installed font
Did not saw them before, cause it was just a large chunk of icons. Now were everything is in it's own line, it's much better readable :slightly_smiling_face:

2022-04-10 18:27 UTC, Shinigami92 commented on src/locales/en/internet/emoji.ts
> +    '⚠',
This emoji is not correctly displayed on my system :thinking: 

![image](https://user-images.githubusercontent.com/7195563/162633903-887abeac-a1e2-4591-9235-7f271d3a0525.png)

2022-04-10 18:27 UTC, Shinigami92 commented on src/locales/en/internet/emoji.ts
> +    '☢',
There are some non-emoji codes here
![image](https://user-images.githubusercontent.com/7195563/162633947-1cbdc9ff-9278-4ee7-b66c-99caa27fef09.png)

2022-04-10 18:27 UTC, Shinigami92 commented on src/locales/en/internet/emoji.ts
> +    '▶️',
And here 
![image](https://user-images.githubusercontent.com/7195563/162633956-3c521285-5c7f-4fcf-b487-8bdbd1d41ed9.png)

2022-04-10 18:27 UTC, Shinigami92 commented on src/locales/en/internet/emoji.ts
> +    '☺',
These are not displayed as emoji

![image](https://user-images.githubusercontent.com/7195563/162633985-e0c372b0-2b04-49be-9261-d5474a04a77c.png)

2022-04-10 18:27 UTC, Shinigami92 commented on src/locales/en/internet/emoji.ts
> +    '☹',
And here 
![image](https://user-images.githubusercontent.com/7195563/162633994-3ff017bd-d28b-45b4-9b36-8b3613a99f65.png)

2022-04-10 18:27 UTC, Shinigami92 commented on src/locales/en/internet/emoji.ts
> +    '☠',
And here
![image](https://user-images.githubusercontent.com/7195563/162634001-fad27d33-b529-4bce-98bf-6c7aecd2c050.png)

2022-04-12 20:09 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +    '⚠',
I think it depends on the system, it's very difficult to find information about emoji implementation state.
([this link](https://developer.android.com/guide/topics/ui/look-and-feel/emoji2) suggests that Android support 13.1, but it's not even clear)

What do you suggest?
- Remove the one that does not display on my system
- Try the [12.0](https://unicode.org/Public/emoji/12.0/emoji-test.txt) (or below)
- Keep it like this

2022-04-12 22:11 UTC, import-brain commented on src/locales/en/internet/emoji.ts
> +    '✌',
Not displayed as emoji

2022-04-12 22:14 UTC, import-brain requested changes

2022-04-12 22:14 UTC, import-brain commented on src/locales/en/internet/emoji.ts
> +    '✌',
Not displayed as emoji

2022-04-12 22:14 UTC, import-brain commented on src/locales/en/internet/emoji.ts
> +    '☝',
here

2022-04-12 22:14 UTC, import-brain commented on src/locales/en/internet/emoji.ts
> +    '✍',
here

2022-04-12 22:17 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +    '✌',
Those are valid emojis and are displayed as such on some devices (android for example) 😅

But I still don't know what to do about this, cf https://github.com/faker-js/faker/pull/504#discussion_r848828082 ...

2022-04-12 22:20 UTC, import-brain commented on src/locales/en/internet/emoji.ts
> +    '✌',
> Those are valid emojis and are displayed as such on some devices (android for example) 😅
> 
> But I still don't know what to do about this, cf [#504 (comment)](https://github.com/faker-js/faker/pull/504#discussion_r848828082) ...

Hmm, this is definitely a big problem. It's pretty much impossible to ensure cross-compatibility with all systems (for example, the emojis I marked as not showing don't show on Mac).

2022-04-12 22:26 UTC, pkuczynski commented on src/locales/en/internet/emoji.ts
> +    '⚠',
I think we should go max 13.1

2022-04-12 22:26 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +    '✌',
Hum, I don't see this as a big problem, it's still displayed as a char...

Here is my point: https://github.com/faker-js/faker/pull/504#discussion_r809905180. However, the maintainers decided to use an older version of emoji (13.0): https://github.com/faker-js/faker/pull/504#discussion_r846792591

Despite the fact that I don't support this decision, I have no problem following it or doing anything to make you (the maintainers) happy with this PR.

I just need a directive concerning this issue, I listed 3 solutions here https://github.com/faker-js/faker/pull/504#discussion_r848828082, I just need someone to pick one 😅 !

2022-04-12 22:30 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +    '⚠',
This is already the case, but there's still some emoji that display as char in some system: https://unicode.org/Public/emoji/13.1/emoji-test.txt

So, should I keep it? (I'm in favor of keeping it)

2022-04-16 11:15 UTC, Shinigami92 commented on src/locales/en/internet/emoji.ts
> +    '✌',
![image](https://user-images.githubusercontent.com/7195563/163672839-3d130d0f-7035-49ff-a137-edc39757385e.png)
That's really interesting :eyes: For me (arch linux) they display as exact same emoji, so they are duplicates :thinking: 
I think we don't need duplicates.

2022-04-16 15:56 UTC, import-brain commented on src/locales/en/internet/emoji.ts
> +    '✌',
Very odd

2022-04-16 16:00 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +    '✌',
Oooooh, I understand now, it's my fault, I forgot to remove the unqualified version of emoji when I updated to 3.0!

![image](https://user-images.githubusercontent.com/4563971/163682347-3e7769c1-d8d1-452e-abed-3dc607097141.png)


I'm sorry, I'm fixing it now...

2022-04-16 17:28 UTC, hugoattal commented on src/locales/en/internet/emoji.ts
> +    '✌',
I fixed it here: https://github.com/faker-js/faker/pull/504/commits/51a29d3762eb2f6fef3e4f4b7b42390a108b65d1

2022-04-16 18:58 UTC, Shinigami92 commented
45 and 46 are duplicates but now removed both :thinking: 
51 and 68 was okay but removed now?
80 was correctly removed

I'm not sure if the _unqualified_ is the correct "filter"

![image](https://user-images.githubusercontent.com/7195563/163687940-8afc3bab-8fa1-4994-8eed-648adc32d595.png)

2022-04-17 17:39 UTC, hugoattal commented
@Shinigami92 You're right some were missing, I fixed it here: https://github.com/faker-js/faker/pull/504/commits/4e239d760ff868b35a0690b447bd94fb07b49b7b

2022-04-17 18:11 UTC, Shinigami92 commented on src/locales/en/internet/emoji.ts
> +    '✌',
> I fixed it here: [51a29d3](https://github.com/faker-js/faker/commit/51a29d3762eb2f6fef3e4f4b7b42390a108b65d1) (Sorry again...)

Hey, no need to be sorry :slightly_smiling_face: 
Actually I really like that we have so much different systems and check from multiple perspectives so that we can bring the best to our users :raised_hands:

2022-04-17 18:52 UTC, Shinigami92 commented on src/internet.ts
> +   * faker.internet.emoji({types: ['food', 'nature']}) // '🥐'
@ST-DDT will api-docs ignore such unformatted example docs? Or should we care about that this should be formatted?
```suggestion
   * faker.internet.emoji({ types: ['food', 'nature'] }) // '🥐'
```

2022-04-17 18:52 UTC, Shinigami92 commented on src/internet.ts
> +   * faker.internet.emoji({types: ['food', 'nature']}) // '🥐'
@ST-DDT will api-docs ignore such unformatted example docs? Or should we care about that this should be formatted?
```suggestion
   * faker.internet.emoji({ types: ['food', 'nature'] }) // '🥐'
```

2022-04-17 18:52 UTC, Shinigami92 commented on src/internet.ts
> +   * faker.internet.emoji({types: ['food', 'nature']}) // '🥐'
@ST-DDT will api-docs ignore such unformatted example docs? Or should we care about that this should be formatted?
```suggestion
   * faker.internet.emoji({ types: ['food', 'nature'] }) // '🥐'
```

2022-04-17 18:52 UTC, Shinigami92 commented on src/internet.ts
> +   * faker.internet.emoji({types: ['food', 'nature']}) // '🥐'
@ST-DDT will api-docs ignore such unformatted example docs? Or should we care about that this should be formatted?
```suggestion
   * faker.internet.emoji({ types: ['food', 'nature'] }) // '🥐'
```

2022-04-17 18:52 UTC, Shinigami92 commented on src/internet.ts
> +   * faker.internet.emoji({types: ['food', 'nature']}) // '🥐'
@ST-DDT will api-docs ignore such unformatted example docs? Or should we care about that this should be formatted?
```suggestion
   * faker.internet.emoji({ types: ['food', 'nature'] }) // '🥐'
```

2022-04-17 18:52 UTC, Shinigami92 commented on src/internet.ts
> +   * faker.internet.emoji({types: ['food', 'nature']}) // '🥐'
@ST-DDT will api-docs ignore such unformatted example docs? Or should we care about that this should be formatted?
```suggestion
   * faker.internet.emoji({ types: ['food', 'nature'] }) // '🥐'
```

2022-04-17 18:52 UTC, Shinigami92 commented on src/internet.ts
> +   * faker.internet.emoji({types: ['food', 'nature']}) // '🥐'
@ST-DDT will api-docs ignore such unformatted example docs? Or should we care about that this should be formatted?
```suggestion
   * faker.internet.emoji({ types: ['food', 'nature'] }) // '🥐'
```

2022-04-17 20:24 UTC, ST-DDT commented on src/internet.ts
> +   * faker.internet.emoji({types: ['food', 'nature']}) // '🥐'
It will print them as is.
https://github.com/faker-js/faker/blob/360bec7c7f3269049eb748523f2d271b6ed36d75/scripts/apidoc/signature.ts#L128-L135
The examples are highlighted for ts though.
https://github.com/faker-js/faker/blob/360bec7c7f3269049eb748523f2d271b6ed36d75/scripts/apidoc/signature.ts#L149
We probably could run them past prettier, but then maybe as a check whether they are formatted correctly instead of just formatting them for the website.

2022-04-18 07:07 UTC, Shinigami92 commented on src/internet.ts
> +   * faker.internet.emoji({types: ['food', 'nature']}) // '🥐'
Oh I just recognized we don't have them only for the docs, but actually also inline docs. So we should format these in code! ^^

2022-04-18 07:10 UTC, Shinigami92 approved these changes

2022-04-18 09:53 UTC, ST-DDT commented
I'm very busy today, so I will have a look at this tomorrow.

2022-04-18 10:10 UTC, import-brain approved these changes

2022-04-19 08:25 UTC, ST-DDT approved these changes

2022-04-19 11:50 UTC, prisis approved these changes

2022-04-19 20:27 UTC, merged