docs: deprecate randomize
faker-js/faker pull request #506
Opened 2022-02-18 17:47 UTC by xDivisionByZerox

Created in relation to #466.

What has changed:
The jsdoc of `helpers.randomize` of now includes the `@deprecated` decorator. 
Furthermore, the method will now print a `console.warn` to inform the end-user about the deprecation.

2022-02-19 12:20 UTC, ST-DDT requested changes
Please move the `@deprecated` tag down to comply with #512

2022-02-19 12:40 UTC, ST-DDT approved these changes

2022-03-10 19:38 UTC, Shinigami92 reviewed
Could you please add a check in the test that the warning is called?
We already do this for methods in random here: https://github.com/faker-js/faker/blob/2d68da1140a4f6d83a94e296506cfa5b126dd067/test/random.spec.ts#L239

2022-03-19 11:37 UTC, Shinigami92 approved these changes

2022-03-19 13:31 UTC, ST-DDT approved these changes

2022-03-21 12:44 UTC, ST-DDT approved these changes

2022-03-21 12:48 UTC, merged