Correcting the Readme File
faker-js/faker pull request #529
Opened 2022-02-21 11:55 UTC by MostlyWhat

The readme file used to say Deno but I feel like using "CDN Demo" seems more fitting.

2022-02-21 12:23 UTC, ST-DDT commented
Deno is a thing too: https://deno.land/

2022-02-21 15:10 UTC, ST-DDT requested changes

2022-02-21 15:10 UTC, ST-DDT commented on README.md
> +### CDN Demo
```suggestion
### CDN/Deno
```

2022-02-23 13:23 UTC, MostlyWhat commented on README.md
> +### CDN Demo
Thats good

2022-02-23 13:35 UTC, Shinigami92 requested changes

2022-02-23 13:35 UTC, Shinigami92 commented on README.md
> +### CDN Demo
I assume something was mixed up while merging main :thinking: 
This line should address `Deno`

2022-02-24 05:13 UTC, MostlyWhat commented on README.md
> +### CDN Demo
I thought I merged the change above

2022-02-24 05:13 UTC, MostlyWhat commented
I think I modified it.

2022-02-24 05:14 UTC, MostlyWhat reviewed
Review Please

2022-02-24 07:36 UTC, Shinigami92 approved these changes

2022-02-24 07:45 UTC, ST-DDT approved these changes

2022-02-24 07:57 UTC, merged