Adding Hungarian locale
faker-js/faker pull request #53
Opened 2022-01-10 14:14 UTC by szabolcstarnai

Added Hungarian locale for (some) animals, commerce, date, finance, internet, name, phone_number and word

2022-01-10 14:22 UTC, damienwebdev submitted a review, later dismissed
We will need someone who speaks Hungarian (other than the author) to review this prior to merging.

2022-01-10 14:22 UTC, damienwebdev commented on .gitignore
> +<<<<<<< HEAD
You committed a merge conflict.

2022-01-10 14:22 UTC, damienwebdev commented on package.json
> +    "eslint": "^6.5.1",
Remove this diff.

2022-01-10 14:22 UTC, damienwebdev commented on lib/locales/hu/animal/index.js
> +// animal.snake = require("./snake");
Don't leave comments.

2022-01-12 16:36 UTC, Shinigami92 requested changes
Just in case, please revert `examples/browser/js/faker.js` and `examples/browser/js/faker.min.js`
We will keep track of that on our side

2022-01-21 17:11 UTC, Shinigami92 commented
We now have all locales written in TypeScript.
Please have a look and rewrite your files like we have done with all other files.

2022-01-21 17:12 UTC, Shinigami92 requested changes
We now have all locales written in TypeScript.
Please have a look and rewrite your files like we have done with all other files.

2022-01-23 10:56 UTC, Shinigami92 commented
@patak-dev I hope I didn't miss-assume your language :sweat_smile: 
But could you have a quick look about this?

That would be really nice

2022-01-23 11:26 UTC, patak-dev commented
I'm Argentinian @Shinigami92, not the best for the task 😅

2022-01-23 11:55 UTC, Shinigami92 commented
> I'm Argentinian @Shinigami92, not the best for the task sweat_smile

Damnd, okay, sorry about that. Hope it's not to cold in the snow :snowflake: :snowboarder: 
Take care :wave:

2022-01-24 11:49 UTC, szabolcstarnai reviewed
In Hungarian 'prepositions' don't really exist, practically we only use postpositions.

2022-04-05 16:12 UTC, Shinigami92 submitted a review, later dismissed
We need someone that can approve this PR in terms of Hungarian

2022-04-22 10:31 UTC, Shinigami92 approved these changes

2022-04-22 10:32 UTC, ST-DDT approved these changes
Looks good format wise.

2022-04-22 10:34 UTC, Shinigami92 commented
If someone else uses these, the new locales and detect that something is wrong, they can raise a new issue / open new PR

2022-04-22 10:35 UTC, merged