feat(time): add default case in time.recent()
faker-js/faker pull request #534
Opened 2022-02-21 19:49 UTC by bl0cknumber

Add missing default case in time recent

Close #533

2022-02-21 19:57 UTC, Shinigami92 commented on src/time.ts
> +  recent(format?: 'abbr' | 'wide' | 'unix' = 'unix'): string | number {
I think this will throw a lint error
It is only supported `?: ...` or `: ... = ...` but not both

2022-02-21 19:57 UTC, Shinigami92 commented on src/time.ts
> +        break;
I think you can remove that, so it's just

```ts
case 'unix':
default:
  date = date.getTime();
  break;
```

2022-02-21 20:24 UTC, ST-DDT requested changes

2022-02-21 20:24 UTC, ST-DDT commented on test/time.spec.ts
> +          const date = faker.time.recent();
Duplicate test, this is already present in line 57.
Did you forget to add a non expected value?

2022-02-21 20:24 UTC, ST-DDT commented on src/time.ts
> +      default:
IMO this should throw an error if an unexpected value is given.

2022-02-21 20:56 UTC, bl0cknumber commented on test/time.spec.ts
> +          const date = faker.time.recent();
I'm not planning to add test for a non expected value

2022-02-21 20:57 UTC, bl0cknumber commented on test/time.spec.ts
> +          const date = faker.time.recent();
Duplicate test already removed

2022-02-21 21:04 UTC, bl0cknumber commented on src/time.ts
> +      default:
check for unexpected value added

2022-02-21 21:10 UTC, bl0cknumber commented on test/time.spec.ts
> +          const date = faker.time.recent();
Added the non expected value test in favor of throw an error if an unexpected value is given.

2022-02-21 21:16 UTC, bl0cknumber commented
Delay for few minutes for eslint, my local PC so laggy

2022-02-21 21:17 UTC, ST-DDT commented on src/time.ts
> +      default:
Instead of adding a new if statement, you could just use the default case.

2022-02-21 21:22 UTC, bl0cknumber commented on src/time.ts
> +      default:
> Instead of adding a new if statement, you could just use the default case.

format = 'unix', ahh I got it

2022-02-21 21:22 UTC, ST-DDT commented on test/time.spec.ts
> +          expect(date).toThrow();
```suggestion
          expect(() => faker.time.recent('not unix')).toThrow();
```

2022-02-21 21:42 UTC, bl0cknumber commented
@ST-DDT pass the eslint, tests and refactors 
@Shinigami92 Done with the default case

2022-02-21 22:10 UTC, ST-DDT commented on src/time.ts
> +        throw new Error('Unexpected value is given');
Please include the unexpected `format` value in the error.

2022-02-22 00:00 UTC, bl0cknumber commented on src/time.ts
> +        throw new Error('Unexpected value is given');
Hi I'm doing my company work right now, sorry for delay maybe I did this in my free time, GMT 07+00 this night maybe.. @ST-DDT

2022-02-22 10:27 UTC, Shinigami92 commented on src/time.ts
> +        throw new Error(`Unexpected value ${format} is given`);
Not sure if we should throw an error here, due to we have TypeScript types.
If the user use the function wrongly without using type checking, they are doomed anyways.
So let's just use `'unix':` and `default:` for the same code-path.

2022-02-22 10:56 UTC, bl0cknumber commented on src/time.ts
> +        throw new Error(`Unexpected value ${format} is given`);
@Shinigami92 I see, sure!

2022-02-22 11:17 UTC, ST-DDT commented
The maintainers will discuss this internally.

2022-02-24 08:36 UTC, ST-DDT commented
**Decision:** We will not add a default case.
Instead we adjust the method signature to allow for unkown string params and return dates in v6.0.

`recent(format: LiteralUnion<'abbr' | 'wide' | 'unix' | 'date'> = 'unix'): string | number | Date { ... }`

In v6.1 we deprecate the method for removal.
In v7.0 we remove the method entirely.

@bl0cknumber Would you like to change/update your PR accordingly?

2022-02-25 07:56 UTC, bl0cknumber commented
> **Decision:** We will not add a default case. Instead we adjust the method signature to allow for unkown string params and return dates in v6.0.
> 
> `recent(format: LiteralUnion<'abbr' | 'wide' | 'unix' | 'date'> = 'unix'): string | number | Date { ... }`
> 
> In v6.1 we deprecate the method for removal. In v7.0 we remove the method entirely.
> 
> @bl0cknumber Would you like to change/update your PR accordingly? (Adjust method signature)

Sorry. It's been busy weeks for me, I need to get done something for my paid work, you can takeover my PR to adjust the method signature if you want

2022-02-25 07:57 UTC, bl0cknumber commented
If anybody need this fast, I would welcome to takeover this PR.

Next week, I can work on this if it's a no.

2022-02-25 17:36 UTC, ST-DDT commented
> Sorry. It's been busy weeks for me, I need to get done something for my paid work, you can takeover my PR to adjust the method signature if you want

No problem. If you have time to adjust the signature today or saturday, then feel free to do so.
If this is not enough time, we will submit the change ourselves.

2022-03-01 21:17 UTC, ST-DDT commented
Superseded by #586

2022-03-01 21:17 UTC, closed without merging