Deprecate helpers.*Card methods
faker-js/faker pull request #543
Opened 2022-02-22 19:01 UTC by sprohaszka

Related to issue #528 

Deprecate the following methods:
* helpers.userCard
* helpers.contextualCard
* helpers.createCard

Replace example in README.

2022-02-22 19:06 UTC, ST-DDT submitted a review, later dismissed

2022-02-22 21:26 UTC, prisis approved these changes

2022-03-10 19:32 UTC, Shinigami92 requested changes
Could you add also tests to check that the warning is logged out?
You could orient yourself on tests for `random` module.

2022-03-10 19:32 UTC, Shinigami92 commented on src/helpers.ts
> +   * @deprecated If you need a some specific data object you should create your own method.
```suggestion
   * @deprecated If you need some specific object you should create your own method.
```

2022-03-10 19:32 UTC, Shinigami92 commented on src/helpers.ts
> +      'Deprecation Warning: If you need a some specific data object you should create your own method.'
```suggestion
      'Deprecation Warning: If you need some specific object you should create your own method.'
```

2022-03-10 19:32 UTC, Shinigami92 commented on src/helpers.ts
> +   * @deprecated If you need a some specific data object you should create your own method.
```suggestion
   * @deprecated If you need some specific object you should create your own method.
```

2022-03-10 19:32 UTC, Shinigami92 commented on src/helpers.ts
> +      'Deprecation Warning: If you need a some specific data object you should create your own method.'
```suggestion
      'Deprecation Warning: If you need some specific object you should create your own method.'
```

2022-03-10 19:32 UTC, Shinigami92 commented on src/helpers.ts
> +   * @deprecated If you need a some specific data object you should create your own method.
```suggestion
   * @deprecated If you need some specific object you should create your own method.
```

2022-03-10 19:32 UTC, Shinigami92 commented on src/helpers.ts
> +      'Deprecation Warning: If you need a some specific data object you should create your own method.'
```suggestion
      'Deprecation Warning: If you need some specific object you should create your own method.'
```

2022-03-11 12:01 UTC, Shinigami92 submitted a review, later dismissed

2022-03-11 18:59 UTC, ST-DDT approved these changes

2022-03-21 12:39 UTC, ST-DDT approved these changes

2022-03-21 12:39 UTC, Shinigami92 approved these changes

2022-03-21 12:43 UTC, merged