chore: move faker into own file
faker-js/faker pull request #548
Opened 2022-02-23 12:55 UTC by Shinigami92

https://github.com/faker-js/faker/issues/405#issuecomment-1048613530

2022-02-23 12:56 UTC, Shinigami92 commented
@ST-DDT Could you please have a look if this is what you expected?
Also please have a look and jump into this PR if anything is needed for documentation (automation script and so on)

2022-02-23 13:10 UTC, ST-DDT commented on src/faker.ts
> +export default faker;
This should remain in the index, as this loads all the locales.

2022-02-23 13:11 UTC, ST-DDT commented
> Also please have a look and jump into this PR if anything is needed for documentation (automation script and so on)

Will do so this evening.

2022-02-23 13:14 UTC, Shinigami92 commented on src/faker.ts
> +export default faker;
:eyes: 
I start to not understand..., so maybe we should talk via voice about this when you have time.

2022-02-23 22:25 UTC, Shinigami92 commented
Please ignore the `codecov/patch` job for this PR

2022-02-23 23:01 UTC, ST-DDT approved these changes

2022-02-24 18:34 UTC, JessicaSachs requested changes
This doesn't fix the size issues yet. `pnpm build` for a Vite project that only does 

```js
import faker from '@faker-js/faker/locale/en'
console.log(faker.locales)
```

is still the same bundle size as a project that loads all of Faker. See pics of before + after sizes.

<img width="300" alt="Screen Shot 2022-02-24 at 1 34 55 PM" src="https://user-images.githubusercontent.com/2801156/155586160-b579a292-9091-42c6-891a-2ec3c99ff0de.png">
<img width="300" alt="Screen Shot 2022-02-24 at 1 35 16 PM" src="https://user-images.githubusercontent.com/2801156/155586171-551ba1de-816a-4f9f-96bf-2a4e3de9c0a9.png">

2022-02-24 18:48 UTC, Shinigami92 commented
Please have a look into the `dist/esm` folder and lock how many chunks are generated

2022-02-24 18:50 UTC, JessicaSachs approved these changes
Ahhh. Had to rerun. It works perfectly. Down 500kb minified + gzipped.
<img width="580" alt="Screen Shot 2022-02-24 at 1 50 38 PM" src="https://user-images.githubusercontent.com/2801156/155588342-c0aebf05-2fec-4452-988f-a76f53f43976.png">
.

2022-02-24 19:07 UTC, merged