Refactor/date accept number input
faker-js/faker pull request #576
Opened 2022-02-26 22:21 UTC by xDivisionByZerox

Created in relation to #394.

I changed the way dates are created from the `Date.parse` method to the `Date.constructor` since it uses that under the hood ([MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#parameters)). This also allows adding `Date` arguments in the future (or even this PR).
The default date is assigned if the provided input creates an invalid date instance (if the value of the date is `NaN`). This was not checked till now whatsoever.

2022-02-27 00:20 UTC, ST-DDT commented on src/date.ts
>      }
This logic seems to be repeated multiple times. Maybe extract it into its own helper method.

2022-02-27 00:38 UTC, ST-DDT commented
![grafik](https://user-images.githubusercontent.com/1579362/155863492-96d911fb-e383-467c-a732-1d7711c24c84.png)

I assume the results are fluctuating by around ~1s.
For some strange reason, the new Date(string) method does discard the ms from the parsed date.
That's why [#200](https://github.com/faker-js/faker/pull/200/files#diff-cdc74ab5a2d5c1414321a9e339b60e2e79e1018a99e545d87653e3e0d972fed6R189) explicitly uses a separate method.

2022-02-27 00:38 UTC, ST-DDT requested changes
Please add tests for `number` inputs.

2022-02-27 12:34 UTC, xDivisionByZerox commented
> For some strange reason, the new Date(string) method does discard the ms from the parsed date (sometimes).
That's why [#200](https://github.com/faker-js/faker/pull/200/files#diff-cdc74ab5a2d5c1414321a9e339b60e2e79e1018a99e545d87653e3e0d972fed6R189) explicitly uses new Date(Date.parse(string)).

That doesn't make sense. The date constructor under the hood uses the Date.parse method for string inputs. You can even verify that both methods get the same result by:
```javascript
const date1 = new Date('2020-01-01T00:00:00.000Z');
const date2 = Date.parse('2020-01-01T00:00:00.000Z');

console.log(date1); // 2020-01-01T00:00:00.000Z
console.log(date2); // 1577836800000
console.log(date1.valueOf() === date2); // true
```

2022-02-27 12:47 UTC, xDivisionByZerox commented on src/date.ts
>      }
Fixed after the merge with #200

2022-02-27 13:00 UTC, xDivisionByZerox commented
Can you add a label or something that this should not get merged before #200?

2022-02-27 13:22 UTC, ST-DDT commented on src/date.ts
> +  betweens(from: string | Date, to: string | Date, num?: number): Date[] {
What about numbers here?

2022-02-27 13:31 UTC, xDivisionByZerox commented on src/date.ts
> +  betweens(from: string | Date, to: string | Date, num?: number): Date[] {
I'm sorry. Missed that during the merge.

2022-02-27 13:35 UTC, xDivisionByZerox commented on src/date.ts
> +  betweens(from: string | Date, to: string | Date, num?: number): Date[] {
fixed in 4e1d519

2022-02-27 14:07 UTC, Shinigami92 requested changes

2022-02-27 14:07 UTC, Shinigami92 commented on src/date.ts
> +type DateConstructor = number | string | Date;
Maybe it's better to use native TypeScript typing system to get the params of DateConstructor

```ts
type DateConstructorParameters = ConstructorParameters<DateConstructor>[0]; // string | number | Date
```

Also using `DateConstructor` as type name is confusing with the real native type `DateConstructor`

2022-02-27 14:11 UTC, Shinigami92 commented
> That doesn't make sense. The date constructor under the hood uses the Date.parse method for string inputs. You can even verify that both methods get the same result by:
> 
> ```js
> const date1 = new Date('2020-01-01T00:00:00.000Z');
> const date2 = Date.parse('2020-01-01T00:00:00.000Z');
> 
> console.log(date1); // 2020-01-01T00:00:00.000Z
> console.log(date2); // 1577836800000
> console.log(date1.valueOf() === date2); // true
> ```

You are checking that the milliseconds are removed but using `000` for milliseconds part?

You should compare e.g.

```ts
const date1 = new Date('2020-01-01T00:00:00.123Z');
const date2 = Date.parse('2020-01-01T00:00:00.123Z');

console.log(date1); // 2020-01-01T00:00:00.123Z
console.log(date2); // 1577836800123
console.log(date1.valueOf() === date2); // false
```

2022-02-27 14:13 UTC, xDivisionByZerox commented on src/date.ts
> +type DateConstructor = number | string | Date;
Cool feature. Didn't know about the `ConstructorParameters` utility type.
Fixed in 90a52271c725a4083472ace430b05e50ee5614ac

2022-02-27 16:58 UTC, xDivisionByZerox commented
> Please add tests for `number` inputs.

Added in a709e9d

2022-02-27 21:08 UTC, ST-DDT reviewed
For now, this looks good to me. I will re-review it once #200 is merged to main.

2022-03-23 17:26 UTC, Shinigami92 requested changes

2022-03-23 17:26 UTC, Shinigami92 commented on src/date.ts
> +  private toDate(date?: DateConstructorParameters): Date {
Due to how we handle our "module" classes, it's not possible to define `private` methods in them
So you need to extract `toDate` out of the class and define it above as a raw function (that is not exported!)
An example for that can be found here: https://github.com/faker-js/faker/pull/644/files#diff-f2b24a1df2ffea4071c80b9948ecf7ed59397468799db7ee1ec376b3c9740b06R17

2022-03-23 22:37 UTC, xDivisionByZerox commented on src/date.ts
> +  private toDate(date?: DateConstructorParameters): Date {
Done in a14f072

2022-03-24 07:09 UTC, Shinigami92 submitted a review, later dismissed

2022-03-24 07:30 UTC, Shinigami92 commented
@xDivisionByZerox we merged #200, please rebase this PR and re-evaluate if and what can still be merged from this PR

2022-03-24 19:07 UTC, xDivisionByZerox commented
I'm going to close this, make another branch based on the current main, and will open another PR since I'm somewhat of a wizard and always completely destroy the git history.

2022-03-24 19:52 UTC, xDivisionByZerox commented
I opened #670 to deprecate this PR.

2022-03-24 19:52 UTC, closed without merging