test(constructor): add failing tests for `new Faker` use
faker-js/faker pull request #580
Opened 2022-02-28 12:09 UTC by vith

I saw that there's a `Faker` class being exported now, so I tried to use it, but it doesn't seem to work.

For example, when trying to do `faker = new Faker(); faker.name.firstName()` I get: 
```
TypeError: Cannot read properties of undefined (reading 'name')
```

I didn't see any examples of using this constructor in the docs, so it's possible I'm using it wrong. Anyway, I wrote these tests to check if it was a problem in my own project, but they fail as well in the same way.

2022-02-28 12:31 UTC, Shinigami92 commented
I think it fails, because you don't provide any locales.

Maybe we need to change the type on your side to force to provide a `locales` :thinking:

2022-02-28 12:32 UTC, Shinigami92 commented
Uhm... tests are green? :eyes:

2022-02-28 16:01 UTC, ST-DDT commented
I assume since it probably returns  undefined` in the middle the fallback of  `['a', 'b', 'c']` applies and thus passes this trivial test.
Maybe change it to length > 1 (as there shouldn't be any one char names in our data).

2022-02-28 17:13 UTC, vith commented
The tests are green just because I defined them with `it.fails`. If you want I can remove that so they actually cause the suite to fail now.

I see what you mean now about not providing any locales, i.e. I need replicate something like this:

```js
import { Faker } from '../faker';
import sv from '../locales/sv';
import en from '../locales/en';

const faker = new Faker({
  locale: 'sv',
  localeFallback: 'en',
  locales: {
    sv,
    en,
  },
});

export = faker;
```

But I haven't found any way to actually import the locale data externally. I think the `exports` field of `package.json` only lets me import the pre-instantiated per-locale singletons like the one I pasted above from `src/locale/sv.ts`?

2022-02-28 17:30 UTC, ST-DDT commented
> The tests are green just because I defined them with `it.fails`. If you want I can remove that so they actually cause the suite to fail now.

Yes, that would make it more obvious for anyone looking at the tests.

> But I haven't found any way to actually import the locale data externally. I think the `exports` field of `package.json` only lets me import the pre-instantiated per-locale singletons like the one I pasted above from `src/locale/sv.ts`?

Yes, currently there isn't because it wasn't in 5.x. This is planned for a release after 6.0 when we actually start adding fixes and features.

2022-03-01 07:49 UTC, vith commented
> Yes, that would make it more obvious for anyone looking at the tests.

Done.

> Yes, currently there isn't because it wasn't in 5.x. This is planned for a release after 6.0 when we actually start adding fixes and features.

Ah, okay. I wonder if the Faker class shouldn't be exported from the package in 6.0 then, if the locale data it needs won't be?

I tried to use the class because I got it as a code completion via the TypeScript Language Server in VSCode.

Not sure if there's anything useful to make out of the tests in this PR then. I guess making the locales field required in the constructor would help like @Shinigami92 said, and/or a better error message when locale data is missing.

2022-03-10 19:10 UTC, Shinigami92 commented
> Could you adjust the constructor to not have a default and require the locales?

@vith Would you like to open a new PR to do this or maybe just use this PR?

2022-03-10 23:14 UTC, ST-DDT commented
> > Could you adjust the constructor to not have a default and require the locales?
> 
> @vith Would you like to open a new PR to do this or maybe just use this PR?

I recommend using this one, as both parts fix+test belong together anyway.

2022-03-21 19:28 UTC, Shinigami92 commented
I will jump into this PR now and fix the constructor

2022-03-21 19:55 UTC, ST-DDT requested changes

2022-03-21 19:55 UTC, ST-DDT commented on src/faker.ts
> +      throw new Error('Options with at least one locale must be provided');
Since there is also a `locale` parameter, this should refer to "one entry in locales".

2022-03-21 20:12 UTC, ST-DDT submitted a review, later dismissed

2022-03-24 09:38 UTC, ST-DDT commented
This needs to be rebased

2022-03-24 10:39 UTC, ST-DDT approved these changes

2022-03-26 12:38 UTC, xDivisionByZerox commented on src/faker.ts
> +    }
For me, this seems like unreachable code, since the constructor type was changed.

2022-03-28 16:46 UTC, xDivisionByZerox approved these changes

2022-03-28 16:52 UTC, merged