refactor: remove default param from arrayElement
faker-js/faker pull request #589
Opened 2022-03-01 23:47 UTC by xDivisionByZerox

Fixes #581.

2022-03-01 23:48 UTC, xDivisionByZerox commented
Should this change also apply to `arrayElements`?

2022-03-01 23:53 UTC, xDivisionByZerox commented
Ok cool of course I forgot to look at the test cases on such a method.
Will provide updates for test files in near future.

2022-03-02 21:31 UTC, xDivisionByZerox commented
`address.streetPrefix` implementation:
https://github.com/faker-js/faker/blob/60d3cc519cd2cab061a23fbe09164d8b59e177ff/src/address.ts#L234-L238

Meaning that if a local doesn't export a `street_prefix` it will throw an error (example 'de'). 
To fix this we would need to make all definition maps required (since its not only `address.streetPrefix` that breaks from this).

2022-03-02 21:32 UTC, xDivisionByZerox commented
How to handle this?
@ST-DDT @Shinigami92

2022-03-03 00:17 UTC, ST-DDT commented
> Meaning that if a local doesn't export a `street_prefix` it will throw an error (example 'de').

It will only fail, if both the selected and the fallback locale don't have that value.
IMO throwing an error is still better than returning abc randomly.
That way you at least notice, that it's not supported.

2022-03-03 00:20 UTC, ST-DDT commented on src/random.ts
> +    if (array.length <= 0) {
This needs to handle undefined arrays as well. When is the array length below zero?

Maybe like this?

```suggestion
    if (typeof array === 'undefined' || !array.length) {
```

2022-03-03 07:22 UTC, Shinigami92 commented on src/random.ts
> +    if (array.length <= 0) {
I would even go with `array == null || array.length === 0`

2022-03-03 18:09 UTC, xDivisionByZerox commented on src/random.ts
> +    if (array.length <= 0) {
Handled both `null` and `undefined` in f9599b6aa35cac02f2dd9e859ae930218bc1dbd1

2022-03-03 22:15 UTC, Shinigami92 commented on src/random.ts
> +    if (typeof array === 'undefined' || array === null || array.length <= 0) {
This can be shorten to
```suggestion
    if (array == null || array.length === 0) {
```

This does exactly the same but is much easier to read and shorter

2022-03-04 09:31 UTC, xDivisionByZerox commented on src/random.ts
> +    if (typeof array === 'undefined' || array === null || array.length <= 0) {
I would argue about being easier to read because you use a loosely type check `==` for bullish values and a strong type check for the array length. Furthermore, I'm a friend of abandoning the loose type check operator since it brings consistency into a project (and somewhat safety over only using `==` as a consistent check).

When on that point? Why do you use `null` as compare value instead of the more often used `undefined`? Would also do the same.

2022-03-04 09:32 UTC, xDivisionByZerox commented on src/random.ts
> +    if (typeof array === 'undefined' || array === null || array.length <= 0) {
That said, I'm not saying you are wrong. Just want to give you my opinion on that toppic.

2022-03-04 09:45 UTC, Shinigami92 commented on src/random.ts
> +    if (typeof array === 'undefined' || array === null || array.length <= 0) {
Using ` == null ` is a really common pattern in js.
I think there is even a eslint rule for that 👀 
Yeah https://eslint.org/docs/rules/eqeqeq
We can configure it like my suggested way

It's a special case when you want to compare something is `null` or `undefined`, then use `== null`

2022-03-04 09:58 UTC, xDivisionByZerox commented on src/random.ts
> +    if (typeof array === 'undefined' || array === null || array.length <= 0) {
The `eqeqeq` eslint rule is exaclty what im referring to as well. Since it disallows the loose type check operation `==` and requires you to use the strong one `===`.
But I guess you referring to the `'smart'` configuration option instead of `'always'`.

2022-03-04 09:58 UTC, ST-DDT commented on src/random.ts
> +    if (typeof array === 'undefined' || array === null || array.length <= 0) {
Having an eslint rule for that is probably good for consistency.

2022-03-04 09:58 UTC, xDivisionByZerox commented on src/random.ts
> +    if (typeof array === 'undefined' || array === null || array.length <= 0) {
I might be biased but I rarely see `== null`. `== undefined` is what I come across all the time.

2022-03-04 10:29 UTC, Shinigami92 submitted a review, later dismissed

2022-03-04 11:19 UTC, ST-DDT commented
Please also update `random.arrayElements()` accordingly + fix the tests.

E.g. by changing:

````ts
return (
      this.faker.random.arrayElement(wordList) ||
      this.faker.random.arrayElement(this.faker.definitions.word.adjective)
    );
````

to

````ts
return (
      wordList.length > 0 ? this.faker.random.arrayElement(wordList) : this.faker.random.arrayElement(this.faker.definitions.word.adjective)
    );
````

Maybe add a check that checks the array before calling arrayElement and throws an error that contains a the method/definition that caused it.

----------

For `word.ts` it might be useful to extract the entire logic into a separate private method:

````ts
adjective(length?: number): string {
    return selectOneWord(length, this.faker.definitions.word.adjective);
}

private selectOneWord(length?: number, words: string[]): string {
  let wordList = words;
    if (length) {
      wordList = words.filter((word) => word.length == length);
      if (!wordList.length) {
        wordList = words;
      }
    }

    return this.faker.random.arrayElement(words);
}
````

2022-03-06 22:25 UTC, xDivisionByZerox commented
> Maybe add a check that checks the array before calling arrayElement and throws an error that contains a the method/definition that caused it.

Can I expect intern-provided arrays (like `this.faker.definitions.word.adjective`) to be provided correctly or check them as well?

2022-03-06 22:42 UTC, ST-DDT commented
Theoretically we don't have an `intern-provided` array, `en` is just a fallback, but you can specify a different one (and might be sensible to do so, if you don't a language without latin characters).
Maybe we should use special syntax for the definitions to make this implicitly?

- `this.faker.definitions.word.adjective` throw if the entry is missing
- `this.faker.extensions.word.adjective` return undefined

(both would use the same "data source")

2022-03-10 19:08 UTC, Shinigami92 commented
@xDivisionByZerox In preparation of starting to review some v6.1 PRs, could you rebase this one and fix conflicts?

2022-03-12 10:51 UTC, xDivisionByZerox commented
Rebase is done and conflicts resolved. Haven't had time for the test and probably won't have this week either.

2022-03-12 11:00 UTC, Shinigami92 commented on src/word.ts
> +      wordList = words.filter((word) => word.length == length);
```suggestion
      wordList = words.filter((word) => word.length === length);
```

2022-03-22 14:52 UTC, Shinigami92 requested changes
Due to how we handle our "module" classes, it's not possible to define private methods in them
So you need to extract `selectOneWord` out of the class and define it above as a raw function (that is not exported!)
An example for that can be found here: https://github.com/faker-js/faker/pull/644/files#diff-f2b24a1df2ffea4071c80b9948ecf7ed59397468799db7ee1ec376b3c9740b06R17

Also this PR needs a rebase 🙂

2022-03-24 20:12 UTC, xDivisionByZerox commented
@Shinigami92 why do my rebases always put the changes from the branch I rebase to the end? Isn't it supposed to treat the rebased branch as a new source and not as a change?

2022-03-24 20:57 UTC, Shinigami92 commented
> @Shinigami92 why do my rebases always put the changes from the branch I rebase to the end? Isn't it supposed to treat the rebased branch as a new source and not as a change?

Seems you definitely do something wrong, but a rebase puts the changes to the end, that's correct
But this PR is now messed up :(
Maybe I could show you next few days how you can rebase correctly

2022-03-24 21:17 UTC, Shinigami92 commented
@xDivisionByZerox I hopefully restored this branch correctly
Please have a look and check if everything is normal again

For your local machine you now need to switch into this branch and then just run `git pull --rebase`

Additionally I already moved the private function out of the module and due to the this binding, I needed to alter the behavior a bit

2022-03-24 21:24 UTC, Shinigami92 commented
Oh damn, I hope I did not messed up myself now :slightly_frowning_face: 
There is 1 lint error and 366 failing tests :eyes: 
After I did the rebase there were no test file changes

2022-04-01 14:39 UTC, Shinigami92 commented
@xDivisionByZerox This PR is one of the last PRs that I would forcefully like to have in v6.1 milestone. Could you bring this to the finish goal or should I take it over myself?

2022-04-01 15:16 UTC, Shinigami92 commented on src/random.ts
> +      throw new Error('Cannot get random element from empty array.');
`FakerError` is already merged 😉

2022-04-01 15:16 UTC, Shinigami92 commented on src/random.ts
> +      throw new Error('Cannot get random element from empty array.');
`FakerError` is already merged 😉

2022-04-01 15:30 UTC, xDivisionByZerox commented on src/random.ts
> +      throw new Error('Cannot get random element from empty array.');
done in c0a28a2f43e5bb26277c9fdc4d151b8bafa29bc7

2022-04-01 15:37 UTC, xDivisionByZerox commented
As I said [here](https://github.com/faker-js/faker/pull/589#issuecomment-1057412956)
address.streetPrefix breaks the tests, since there are no locales in `en` for street_prefix

2022-04-01 15:37 UTC, Shinigami92 commented
@xDivisionByZerox So now we just need to fix all the failing tests (?)

2022-04-01 15:40 UTC, xDivisionByZerox commented
Not really since the problem is the same I stated 1 month ago.
Or should I change the `address.streetPrefix` to expect an error?

2022-04-01 15:41 UTC, Shinigami92 commented
> `address.streetPrefix` breaks our tests, since there are no locales in `en` for street_prefix

So yeah, but as I understand this PR: This is THE bug we want to fix!
So do we need to throw errors in this case?
@ST-DDT I would like you to decide it how to proceed

2022-04-01 15:44 UTC, xDivisionByZerox commented
I'll change the test to expect an Error and add a comment to expect a real value when locales were included.

2022-04-01 15:54 UTC, xDivisionByZerox commented
@ST-DDT Can you give insight into how the `BROKEN_LOCALE_METHODS` constant in `all_functional.spec.ts` works? Do I need to add the modules that don't work with `en` and provide an alternative local or does this object contain all functions not working in a specific local?

2022-04-01 15:56 UTC, damienwebdev commented
My opinion is that there's a no-trivial chance that this is breaking for someone. If we release this as `v6.1.2` or `v6.2` we would be breaking the semver contract.

2022-04-01 16:02 UTC, ST-DDT commented
> My opinion is that there's a non-trivial chance that this is breaking for someone. If we release this as `v6.1.2` or `v6.2` we would be breaking the semver contract.

I agree. We should move this to v7.

2022-04-01 16:03 UTC, ST-DDT commented
> @ST-DDT Can you give insight into how the `BROKEN_LOCALE_METHODS` constant in `all_functional.spec.ts` works? Do I need to add the modules that don't work with `en` and provide an alternative local or does this object contain all functions not working in a specific local?

Yes, if effectively contains all tests that are disabled for a certain locale.

2022-04-01 16:08 UTC, xDivisionByZerox commented
> > @ST-DDT Can you give insight into how the `BROKEN_LOCALE_METHODS` constant in `all_functional.spec.ts` works? Do I need to add the modules that don't work with `en` and provide an alternative local or does this object contain all functions not working in a specific local?
> 
> Yes, if effectively contains all tests that are disabled for a certain locale.

Well then this doesn't work I guess. If you have a look at the log files from node-16, ubuntu-latest line 22344:
```
2022-04-01T15:28:45.2251825Z  [31m×[39m test/all_functional.spec.ts[2m > [22mfaker.fake functional tests[2m > [22mru[2m > [22mname[2m > [22mprefix()
2022-04-01T15:28:45.2252117Z [31m   → Cannot get random element from empty array.[39m
```

Even tho we have in all_functions:
```
const BROKEN_LOCALE_METHODS = {
    ...,
    name: {
        prefix: [..., 'ru'],
        ...,
    },
    ...,
}
```

2022-04-01 16:15 UTC, xDivisionByZerox commented
Or can I remove this now since the `it.fails` doesn't apply anymore since the function will now throw an error? But for my understanding `it.fails` should be the right why to go when a function throws an error :/

2022-04-01 17:40 UTC, ST-DDT commented
The faker.fake method currently does not have an exclude handling, as it does not fail.

2022-04-26 18:42 UTC, ST-DDT commented
@xDivisionByZerox Can you split the word improvements to its own PR?
AFAICT these changes are independent and could be merged earlier.

2022-04-26 18:51 UTC, xDivisionByZerox commented
> @xDivisionByZerox Can you split the word improvements to its own PR? AFAICT these changes are independent and could be merged earlier.

Well [you yourself suggested this change](https://github.com/faker-js/faker/pull/589#issuecomment-1059073693) in this PR. This logic is not required to change if this PR is not in place. So a separate PR should IMO be dismissed because it doesn't provide any meaningful architectural refactoring/performance boosting.

2022-04-26 18:58 UTC, xDivisionByZerox commented
But yeah, I can provide a separate PR if you wish to merge this in 6.3.0.

2022-04-26 19:02 UTC, ST-DDT commented
> > @xDivisionByZerox Can you split the word improvements to its own PR? AFAICT these changes are independent and could be merged earlier.
> 
> Well [you yourself suggested this change](https://github.com/faker-js/faker/pull/589#issuecomment-1059073693) in this PR. This logic is not required to change if this PR is not in place. So a separate PR should IMO be dismissed because it doesn't provide any meaningful architectural refactoring/performance boosting.

It simplifies the code by removing duplicate code. IMO that is worth enough.
(I plan to extend the length to a range at some point, so any simplifications are welcome.)

2022-06-09 19:13 UTC, xDivisionByZerox commented
I will close this PR due to MASSIV changes in the file structure. I will provide a new PR with changes discussed in this PR.

2022-06-09 19:13 UTC, closed without merging