feat: Add MongoDB ObjectId generation
faker-js/faker pull request #616
Opened 2022-03-12 16:31 UTC by nhammond101

Adds a function to generate MongoDB [ObjectIds](https://docs.mongodb.com/manual/reference/bson-types/#std-label-objectid)

The function aims to be deliberately simple so any combination of `a-z` and `0-9` is generated as a valid ObjectId, instead of implementing ObjectIds according to the official spec

Futhermore, I was unsure where to add the function given it's a datatype for a database, so happy to refactor/move if required.

2022-03-12 16:35 UTC, Shinigami92 commented
Would this fit better into `/src/database.ts`? I think we should move it to that module.

2022-03-12 17:04 UTC, Shinigami92 commented
Not related to this PR, but IMO we should try to prepare that the datatype module only defines functions for `typeof` "return" values.
So only `string`, `number`, `boolean` and so on. But this would be something for `v7+`

2022-03-12 17:08 UTC, nhammond101 commented
@Shinigami92 agree on the moving to database, and have done so now.

Is there anything I can add to the current PR to facilitate the future `typeof` improvements?

2022-03-12 17:12 UTC, Shinigami92 requested changes

2022-03-12 17:12 UTC, Shinigami92 commented on src/database.ts
> +  objectId(value?: string): string {
What's the benefit of having this param? I think currently it doesn't provide any value to faker and should just be checked/handled outside of the usage of faker.

2022-03-12 17:14 UTC, Shinigami92 commented
> Is there anything I can add to the current PR to facilitate the future `typeof` improvements?

Mh, currently I don't think so. You can always join our discord if you haven't already, so we can communicate better there.
But for now, we would tackle all the v6.1 stuff first anyways.
We expect to release 6.0.0 on monday evening.

2022-03-12 17:45 UTC, nhammond101 commented on src/database.ts
> +  objectId(value?: string): string {
not a great deal upon reflection.  i've removed it now.

2022-03-12 18:36 UTC, ST-DDT commented on src/database.ts
> +  objectId(): string {
Maybe prefix it with mongo(DB), because object id might be used in other contexts as well.

2022-03-12 18:36 UTC, ST-DDT commented on src/database.ts
> +    const charCodeOptions = [
Why don't you use [faker.random.hexaDecimal](https://fakerjs.dev/api/random.html#hexaDecimal)

2022-03-12 19:30 UTC, nhammond101 commented on src/database.ts
> +  objectId(): string {
done

2022-03-12 19:32 UTC, nhammond101 commented on src/database.ts
> +    const charCodeOptions = [
good point, i had avoided it thus far due to the `0x` prefix.  
i've refactored to use hexadecimal and it certainly shortens the function code!

2022-03-12 19:57 UTC, ST-DDT approved these changes

2022-03-12 20:22 UTC, Shinigami92 commented on src/database.ts
> +    const charCodeOptions = [
Oh yeah, good point, we already thought about somewhere else that we want to remove the `0x` part from that function.
But this will be in v7, cause it would introduce a "big" breaking change.

2022-03-12 20:34 UTC, ST-DDT commented on src/database.ts
> +    const charCodeOptions = [
Maybe we can start with a prefix parameter in v6.2?

2022-03-12 21:16 UTC, Shinigami92 commented on src/database.ts
> +    const charCodeOptions = [
Oh yeah that could work :thinking: Good idea :+1: 
So we could add a `hexaDecimal(length = 1, prefix = '0x')`

2022-03-13 14:40 UTC, damienwebdev commented
This feels more like a plugin than a method of the main library. @Shinigami92 @ST-DDT have you seen a way to add custom user-defined methods to the Faker API?

2022-03-13 17:46 UTC, ST-DDT commented
> have you seen a way to add custom user-defined methods to the Faker API?

This is possible, but it requires casting or subclassing the faker instance. While I agree this kind of custom/specific, moving this to a plugin seems overengeneered to me. We can consider this again, if we have more of these.
We could nest these in their own submodule if you want.
`faker.database.mongodb.objectId()`

2022-03-13 18:00 UTC, Shinigami92 commented
I'm with @ST-DDT, plugins would be over engineered.
We also already had the discussion about sub module, but IMO we can move it into that if really needed.

2022-04-05 22:36 UTC, ST-DDT commented on src/database.ts
> +   * faker.database.mongodbObjectId() // e175cac316a79afdd0ad3afb
```suggestion
   * faker.database.mongodbObjectId() // 'e175cac316a79afdd0ad3afb'
```

2022-04-05 22:38 UTC, ST-DDT commented on src/database.ts
> +   * Returns an [ObjectId](https://docs.mongodb.com/manual/reference/method/ObjectId/) string
```suggestion
   * Returns a MongoDB [ObjectId](https://docs.mongodb.com/manual/reference/method/ObjectId/) string.
```

2022-04-05 22:38 UTC, ST-DDT approved these changes

2022-04-05 23:27 UTC, pkuczynski approved these changes

2022-04-06 01:01 UTC, import-brain approved these changes

2022-04-06 07:48 UTC, Shinigami92 commented on src/database.ts
> +    return this.faker.datatype.hexaDecimal(24).replace('0x', '').toLowerCase();
```suggestion
    return this.faker.datatype.hexadecimal(24).replace('0x', '').toLowerCase();
```

2022-04-06 07:49 UTC, Shinigami92 approved these changes

2022-04-06 07:49 UTC, ST-DDT commented on src/database.ts
> +    return this.faker.datatype.hexaDecimal(24).replace('0x', '').toLowerCase();
Good catch

2022-04-06 07:49 UTC, ST-DDT approved these changes

2022-04-06 08:01 UTC, merged