chore: renovate Russian states names
faker-js/faker pull request #634
Opened 2022-03-18 13:09 UTC by serembon

Updated names of Russian regions according to official government sources.

2022-03-18 13:49 UTC, ST-DDT commented
Could you please add the sources for these list for easier verification?

2022-03-18 13:58 UTC, ST-DDT commented
We need somebody to check these.

2022-03-18 14:00 UTC, serembon commented
Provided several links to government sources

2022-03-18 14:50 UTC, Shinigami92 reviewed
On first look with help of google translator, this PR looks valid to me.
But I would like if someone with russian knowledge could have a specific look over these enhancements.

2022-03-18 14:50 UTC, Shinigami92 commented on src/locales/ru/address/state.ts
> +  'Республика Дагестан',
Could you run prettier? `pnpm run format`

2022-03-18 14:50 UTC, Shinigami92 commented on src/locales/ru/internet/domain_suffix.ts
> +export default [
Now this PR addresses not only states anymore, so we may need to update the PR title to reflect correctly in the changelog

2022-03-18 20:47 UTC, serembon commented on src/locales/ru/internet/domain_suffix.ts
> +export default [
Done

2022-03-18 20:47 UTC, serembon commented on src/locales/ru/address/state.ts
> +  'Республика Дагестан',
Done

2022-03-18 21:25 UTC, Shinigami92 submitted a review, later dismissed

2022-03-18 22:45 UTC, ST-DDT approved these changes
Format wise this looks good. Haven't checked the translations yet.

2022-03-19 10:20 UTC, Shinigami92 commented
A personal russian friend approved that everything is fine 👌

2022-03-24 16:59 UTC, ST-DDT submitted a review, later dismissed

2022-03-29 08:34 UTC, serembon commented
@Shinigami92 I have added new street names and suffixes, review required.

2022-03-29 16:39 UTC, ST-DDT requested changes

2022-03-29 16:39 UTC, ST-DDT commented on src/locales/ru/address/index.ts
> -  street_title,
AFAICT this file is still there.

2022-03-29 18:27 UTC, serembon commented on src/locales/ru/address/index.ts
> -  street_title,
This import was removed by mistake, returned. Thanks!

2022-04-05 16:00 UTC, Shinigami92 approved these changes

2022-04-05 16:58 UTC, ST-DDT commented on src/locales/ru/address/street_name.ts
>  ];
This syntax is currently not supported. Not sure what we should do about this.

2022-04-05 21:58 UTC, pkuczynski requested changes

2022-04-05 21:58 UTC, pkuczynski commented on src/locales/ru/address/default_country.ts
> -export default ['Россия'];
I am not sure if this change is correct. In other files we store here _common names_, for example `Deutschland`, which full name is `Bundesrepublik Deutschland` (see https://de.wikipedia.org/wiki/Deutschland). I guess when you build address you give common country names not like official names?

2022-04-05 21:58 UTC, pkuczynski commented on src/locales/ru/address/index.ts
> +import street_suffix_ext from './street_suffix_ext';
What's the difference between `street_suffix` and `street_suffix_ex`? We do not support this in other locales and this would start to be a problem if we (eventually) merge #728

2022-04-06 17:44 UTC, serembon commented on src/locales/ru/address/default_country.ts
> -export default ['Россия'];
Debatable question. Many popular services use `Russian Federation` instead of `Russian`. For example:

Amazon offers delivery to `Russian Federations`

E-bay delivery address suggestion is `Russian Federation`

2022-04-06 17:45 UTC, serembon commented on src/locales/ru/address/street_name.ts
>  ];
I will remove these changes and try to add them with the next releases

2022-04-06 18:09 UTC, pkuczynski commented on src/locales/ru/address/default_country.ts
> -export default ['Россия'];
That's interesting what you say, because I just checked Amazon and when I try to add the address this is what I see:

![image](https://user-images.githubusercontent.com/374864/162040136-9cbb43f0-a326-4288-8b78-fe21bc91beb2.jpeg)

So it's `Rosja` and not `Federacja Rosyjska`. I could not check on Amazon.ru as it does not seem to exist?

2022-04-06 18:24 UTC, serembon commented on src/locales/ru/address/default_country.ts
> -export default ['Россия'];
Amazon:

<img width="316" alt="Screenshot 2022-04-06 at 20 42 18" src="https://user-images.githubusercontent.com/22729616/162042711-0721623c-dfb9-4232-b1dc-0f8c4097890d.png">


E-bay:

<img width="472" alt="Screenshot 2022-04-06 at 21 24 01" src="https://user-images.githubusercontent.com/22729616/162042843-c6036e55-b0eb-46ae-a40b-25be88798647.png">

2022-05-11 20:49 UTC, ST-DDT submitted a review, later dismissed
Format wise this looks good.

2022-05-12 11:44 UTC, Shinigami92 approved these changes

2022-05-18 17:13 UTC, Shinigami92 commented
@pkuczynski You may need to approve or comment if you want further changes

2022-05-18 18:15 UTC, pkuczynski approved these changes

2022-05-21 17:30 UTC, ST-DDT approved these changes

2022-05-21 17:31 UTC, ST-DDT commented
I merged the changes from main (street_title -> street_name).

2022-05-22 08:36 UTC, pkuczynski approved these changes

2022-05-22 11:07 UTC, merged