Export locales.
faker-js/faker pull request #642
Opened 2022-03-21 13:58 UTC by mshima

Locales should be exported otherwise the only way to have localeFallback is to use the default exported Faker instance.

2022-03-21 19:32 UTC, mshima commented
Thanks @Shinigami92 for the quick feedback.
Marking as ready for review, since it the requested changes have been addressed.

2022-03-21 20:10 UTC, Shinigami92 commented
It's working? omg that would be really nice, thank you @mshima for this fix, I assume you will make many happy with that

2022-03-21 20:34 UTC, Shinigami92 requested changes
Currently we need to do something like this:

```ts
import { Faker } from "@faker-js/faker";
import es from "@faker-js/faker/locales/es";
import fr from "@faker-js/faker/locales/fr";

console.log(
  "Manually loaded locale:",
  new Faker({
    locales: { es: es.default, fr: fr.default },
    locale: "es",
    localeFallback: "fr",
  }).locales.es.title
); // Manually loaded locale: Spanish
```

This is working, but it would be much better if we can somehow make it possible to omit the need of using `<locale>.default`
Or do you know a better way of importing them?

But also there are no types defined for these exports :thinking: 
![image](https://user-images.githubusercontent.com/7195563/159359113-1da74330-e7e0-4f94-9205-8a1b94cb569c.png)
So at least this needs to be fixed before we can merge this PR!

2022-03-21 20:48 UTC, Shinigami92 commented
> I think this is because of:
> 
> https://github.com/faker-js/faker/blob/56424709b7ccd7aa7fe6130c78a770a0a901d7b5/package.json#L36
> 
> This makes node esm to import cjs version. Should be `require` instead of `node`.

I was not fully aware of what each of the things are doing when I crafted all together. Feel free to fix it until it's correct and I approved that everything is working.
I have a locale faker playground where I can now test esm TS/JS and cjs TS/JS.
I use pnpm's `overrides` to link to my local `@faker-js/faker`

2022-03-21 20:56 UTC, mshima commented
I will checkout the project to see the generated code. Until now it could be done using CI 😄.

2022-03-22 12:48 UTC, mshima commented
> Currently we need to do something like this:
> 
> ```ts
> import { Faker } from "@faker-js/faker";
> import es from "@faker-js/faker/locales/es";
> import fr from "@faker-js/faker/locales/fr";
> 
> console.log(
>   "Manually loaded locale:",
>   new Faker({
>     locales: { es: es.default, fr: fr.default },
>     locale: "es",
>     localeFallback: "fr",
>   }).locales.es.title
> ); // Manually loaded locale: Spanish
> ```
> 
> This is working, but it would be much better if we can somehow make it possible to omit the need of using `<locale>.default`

Looks like this is a pattern esbuild uses.
See:
```js
node -e 'console.log(require("@faker-js/faker"));'
{ Faker: [Getter], default: [Getter], faker: [Getter] }
```

Need to change the approach

2022-03-22 13:31 UTC, mshima commented
Should work like:
```
const { Faker } = require("@faker-js/faker");
const { es, fr } = require("@faker-js/faker/locales");

console.log(
  "Manually loaded locale:",
  new Faker({
    locales: { es, fr },
    locale: "es",
    localeFallback: "fr",
  }).locales.es.title
);
```

2022-03-22 13:38 UTC, Shinigami92 commented
I will test this again this evening, due to I do not have the local playground on my workstation laptop but on my home pc

2022-03-22 18:45 UTC, Shinigami92 commented
@mshima I created a playground here: https://github.com/faker-js/playground
Feel free to ask if something is unclear

2022-05-21 18:15 UTC, Shinigami92 commented
@mshima are you still interested in this PR? Or should someone take it over?

2022-05-23 10:50 UTC, mshima commented
If someone else manages to finishes it, go ahead.
I want to finish it, I couldn’t find the time to do it yet.

The cjs part will probably need to expose a handcrafted api. I don’t think current approach will work.

2022-05-30 20:22 UTC, mshima commented
@Shinigami92 this need approach seems to do the trick.

2022-06-01 12:50 UTC, Shinigami92 commented
@mshima I see this PR and I like it, but currently our maintainer resources are a bit limited and we have a bunch of other things on our agenda. So it still could take a bit until we can proceed with this wanted feature.
We want to internally discuss if e.g. we want imports like
- `import { locale } from '@faker-js/faker/locale/de'`
- `import { de } from '@faker-js/faker/locale/de'`
- `import { de } from '@faker-js/faker/locales'`
- `import { de } from '@faker-js/faker'`
And for the long-term (not this PR) we even think about using a mono-repo structure and make possible to use
```ts
import { de } from '@faker-js/de'
import { Faker } from '@faker-js/faker'

new Faker({ /* ... use de somehow */ })
```

2022-06-01 13:12 UTC, mshima commented
@Shinigami92 no problem, I cannot use v7 for now since we need node 12 support.

2022-09-05 17:28 UTC, mshima commented
> @mshima I see this PR and I like it, but currently our maintainer resources are a bit limited and we have a bunch of other things on our agenda. So it still could take a bit until we can proceed with this wanted feature. We want to internally discuss if e.g. we want imports like
> 
> * `import { locale } from '@faker-js/faker/locale/de'`
> * `import { de } from '@faker-js/faker/locale/de'`
> * `import { de } from '@faker-js/faker/locales'`
> * `import { de } from '@faker-js/faker'`
>   And for the long-term (not this PR) we even think about using a mono-repo structure and make possible to use
> 
> ```ts
> import { de } from '@faker-js/de'
> import { Faker } from '@faker-js/faker'
> 
> new Faker({ /* ... use de somehow */ })
> ```

@Shinigami92 is there a decision about the api? We are about to start a major version, so I may work on this soon.

2022-09-05 19:22 UTC, ST-DDT commented
We will discuss this in the next team meeting again.

2022-09-08 17:04 UTC, ST-DDT commented
@Shinigami92 will tackle this in a new PR for v8.
We would like to keep this open for now, to make the discussion that happened here more visible.

2022-10-15 14:51 UTC, mshima commented
As workaround:
```
  let nativeFakerInstance;
  // Faker >=6 doesn't exports locale by itself, it only exports a faker instance with the locale.
  // We need a Faker instance for each entity, to build additional fake instances, use the locale from the exported localized faker instance.
  // See https://github.com/faker-js/faker/pull/642
  try {
    // eslint-disable-next-line import/no-dynamic-require
    nativeFakerInstance = (await import(`@faker-js/faker/locale/${nativeLanguage}`)).faker;
  } catch (error) {
    // Faker not implemented for the native language, fallback to en.
    // eslint-disable-next-line import/no-unresolved, import/no-dynamic-require
    nativeFakerInstance = (await import('@faker-js/faker/locale/en')).faker;
  }

  const faker = new Faker({
    locales: nativeFakerInstance.locales,
    locale: nativeFakerInstance.locale,
    localeFallback: nativeFakerInstance.localeFallback,
  });
```

2023-03-20 20:17 UTC, ST-DDT commented
The locales can now be imported via `import { de } from '@faker-js/faker'` and `import { fakerDE as faker } from '@faker-js/faker'`.

Superseded by #1735

2023-03-20 20:17 UTC, closed without merging