fix: corrected the Costa Rican IBAN format (#643)
faker-js/faker pull request #646
Opened 2022-03-21 15:02 UTC by MrGussio

Fixes #643 by correcting the Costa Rican IBAN formatting

2022-03-21 16:06 UTC, ST-DDT approved these changes
Checked and seems to be working according to: https://www.iban.de/iban-pruefen.html

2022-03-21 17:10 UTC, Shinigami92 requested changes
Don't we have a test case for that? Nothing failed...
But I think we should add a test case for that because we also have tests for other ibans

See: https://github.com/faker-js/faker/blob/main/test/finance_iban.spec.ts

2022-03-22 22:37 UTC, MrGussio commented
> Don't we have a test case for that? Nothing failed... But I think we should add a test case for that because we also have tests for other ibans
> 
> See: https://github.com/faker-js/faker/blob/main/test/finance_iban.spec.ts

I added the test for Costa Rica to the test file and made issue #660 for the other tests of missing IBAN country codes.

In the latest commit I also splitted the reserved character from the banking digits of the Costa Rican IBAN formatting, to really cohere to the definitions I have found online.

2022-03-22 23:18 UTC, ST-DDT commented on test/finance_iban.spec.ts
> +          ).match(/^[A-Z]{2}$/);
IMO this should be `'CR'` not some kind of regex. Or am I missing something here?

2022-03-23 07:05 UTC, MrGussio commented on test/finance_iban.spec.ts
> +          ).match(/^[A-Z]{2}$/);
You're right, that probably does make more sense. The other tests also used this regex matching for the first two characters, but I agree that matching it with the country code is more robust.

2022-03-23 08:09 UTC, ST-DDT approved these changes

2022-03-23 08:25 UTC, Shinigami92 approved these changes

2022-03-23 08:29 UTC, merged