ci: configure codecov patch threshold
faker-js/faker pull request #647
Opened 2022-03-21 17:00 UTC by Shinigami92

The threshold is not useful as it only fails PRs that are successfully but the threshold is not meet.

2022-03-21 18:01 UTC, ST-DDT submitted a review, later dismissed

2022-03-21 22:06 UTC, griest024 requested changes
2% threshold seems large. Why not 0% or at worst, 1%?

2022-03-22 07:11 UTC, Shinigami92 commented
> 2% threshold seems large. Why not 0% or at worst, 1%?

@griest024 Okay I may have misunderstood `threshold`, maybe you could try to explain me what is going on.

The initial issue here is that the CI failed several times with the `codecov/patch` action.
I found out that it doesn't take the config we set for codecov/project default, so I needed to explicitly configured it for patch.

I assume setting the threshold to 0% will not help again, cause the default may was be 0% by default previously. (I could be wrong)
But everytime we did a helpful refactoring that moved some parts, the patch action failed and marked the whole PR as ❌, were every other action was ✅ and the PR is good to go. So it just may confused people and especially maintainers that there was something broken or wrong, but it was not.

So I would like to first try and drive for a while with my proposed settings in this PR.
If something is still bad, we can change it in a future PR anyway.

2022-03-22 19:27 UTC, griest024 commented
@Shinigami92 from the [docs](https://docs.codecov.com/docs/commit-status#threshold)

> Allow the coverage to drop by X%, and posting a success status.

It's possible that there is some broken logic for `0%` that will fail PRs that should have passed. I would think that `1%` would avoid this.

2022-03-22 19:34 UTC, Shinigami92 commented on .github/.codecov.yml
> +        threshold: 2%
```suggestion
        threshold: 1%
```

2022-03-22 19:35 UTC, griest024 approved these changes

2022-03-22 19:36 UTC, ST-DDT approved these changes

2022-03-22 19:38 UTC, merged