fix: datatype.number does not produce random number when min = max + precision
faker-js/faker pull request #664
Opened 2022-03-23 21:15 UTC by pkuczynski

Fixes #329

2022-03-24 12:45 UTC, pkuczynski commented on src/datatype.ts
> +    let max = typeof opts.max === 'number' ? opts.max : min + 99999;
That is what was suggested in #329. For me, it makes sense that when max is not provided, to give it a nice, wide span. What would be your suggestion to do it differently?

2022-03-24 12:48 UTC, pkuczynski commented on src/datatype.ts
>      }
I am not sure if this is the right thing to do in this case. Imagine:

```faker.datatype.number({ min: 100, max: 10})```

I would be really surprised that values got swapped. Especially if they are not given directly as in the example above, but coming from some other parts of the code. It would just hide an error instead of surfacing it...

2022-03-24 13:17 UTC, Shinigami92 requested changes

2022-03-24 13:17 UTC, Shinigami92 commented on src/datatype.ts
> +    let max = typeof opts.max === 'number' ? opts.max : min + 99999;
Could you swap lines a bit to reduce diff-changes?

```suggestion
    const min = typeof opts.min === 'number' ? opts.min : 0;
    let max = typeof opts.max === 'number' ? opts.max : min + 99999;
    const precision = typeof opts.precision === 'number' ? opts.precision : 1;
```

min and max need to be swapped because now max uses min

2022-03-24 13:17 UTC, Shinigami92 commented on src/datatype.ts
> +      throw new Error(`Max should be larger then min: ${max} > ${min}`);
We need a test case to test this error

2022-03-24 13:19 UTC, ST-DDT commented on src/datatype.ts
> +    let max = typeof opts.max === 'number' ? opts.max : min + 99999;
ok, please update the docs accordingly

2022-03-24 13:20 UTC, ST-DDT commented on src/datatype.ts
>      }
ok, i agree except for min == max then it should return just that.

2022-03-29 15:37 UTC, pkuczynski commented on src/datatype.ts
>      }
Done

2022-03-29 15:37 UTC, pkuczynski commented on src/datatype.ts
> +    let max = typeof opts.max === 'number' ? opts.max : min + 99999;
Done

2022-03-29 20:14 UTC, pkuczynski commented on src/datatype.ts
> +      throw new Error(`Max should be larger then min: ${max} > ${min}`);
Done

2022-03-29 20:43 UTC, ST-DDT approved these changes

2022-03-29 20:43 UTC, ST-DDT commented
Please fix the failing tests.

2022-03-29 20:50 UTC, pkuczynski commented
> Please fix the failing tests.

Yeah, I was working on them :)

2022-03-29 22:18 UTC, pkuczynski commented
> Please fix the failing tests.

All fixed now...

2022-03-29 22:46 UTC, ST-DDT commented on src/address.ts
> +        min,
```suggestion
        min,
        max,
```

That way it feels more natural to me. But not really important.

2022-03-29 22:46 UTC, ST-DDT commented on test/address.spec.ts
> +            const latitude = faker.address.latitude(5, -5);
😿 🤔

2022-03-29 22:46 UTC, ST-DDT commented on src/locales/ro/address/index.ts
> +  streets,
Please revert this change.

2022-03-29 23:14 UTC, pkuczynski commented on test/address.spec.ts
> +            const latitude = faker.address.latitude(5, -5);
I know :/ The signature of this function was not really good. It should take `opts` instead of params `max, min`. Or maybe I should do the detection inside `latitude` and swap if needed? This sounds like a good idea... wdyt?

2022-03-29 23:16 UTC, pkuczynski commented on src/address.ts
> +        min,
For me too. I kept the order but simplified the signature. I will apply our suggestion.

2022-03-29 23:17 UTC, pkuczynski commented on src/locales/ro/address/index.ts
> +  streets,
It must have been my editor doing that automatically, sorry...

2022-03-30 13:50 UTC, ST-DDT commented on test/address.spec.ts
> +            const latitude = faker.address.latitude(5, -5);
Well, I'm still a fan of swapping in `datatype.number()` as well. 😉

2022-03-30 20:06 UTC, pkuczynski commented on test/address.spec.ts
> +            const latitude = faker.address.latitude(5, -5);
The params are called `max` and `min` so user should provide valid values :)

2022-03-31 07:20 UTC, Shinigami92 approved these changes

2022-03-31 07:49 UTC, ST-DDT commented
Since my expectation of `generateMeARandomNumberBetween(-5, 5)` is to work, I will not approve this.
But I will accept it, if the others want it this PR's way.

My sole requirement: Add a hint to the changelog

2022-03-31 08:04 UTC, Shinigami92 commented
> Since my expectation of `generateMeARandomNumberBetween(-5, 5)` is to work, I will not approve this. [...]

But I do understand it correctly that this PR did not introduce a change in that? And the test was just calling it wrongly in history?

2022-03-31 08:22 UTC, ST-DDT commented
> But I do understand it correctly that this PR did not introduce a change in that? And the test was just calling it wrongly in history?

It does: [src/datatype.ts:44](https://github.com/faker-js/faker/pull/664/files#diff-5699f20396717381133051426f9769465b1d8d460c942def407bb4f03907d5c3R43-R45)

2022-03-31 08:28 UTC, ST-DDT commented on src/random.ts
> +        : 0;
I think this change is no longer needed

2022-03-31 08:48 UTC, pkuczynski commented
> > Since my expectation of `generateMeARandomNumberBetween(-5, 5)` is to work, I will not approve this. [...]
> 
> But I do understand it correctly that this PR did not introduce a change in that? And the test was just calling it wrongly in history?

This PR introduced an additional check if `max > min` and throws an error when they are not. We don't have a function that takes params like `(-5, 5)`. It takes options `({ min: -5, max: 5 })`. To see the error being thrown user would have to call it with `({ min: 5, max: -5 })` which is mathematically incorrect, right? So if anything we are only giving users better support now...

2022-03-31 09:35 UTC, pkuczynski commented
> My requirements:
> 
> * Add a hint to the next changelog/release

Not sure how shall I do that?

> * Please also rename the PR to reflect the changes to behavior of the method (e.g. `be more strict with datatype.number()'s behavior`).

Done. Additionaly added some jsdoc.

2022-03-31 09:36 UTC, pkuczynski commented on src/random.ts
> +        : 0;
This change is a bit of perf optimization. Does not make sense to call `number` if the array length is 1. In such a case we should just return this element.

2022-03-31 09:46 UTC, Shinigami92 commented
@pkuczynski Could you please shorten the title of this PR to something that is max 72 chars long?
The title is taken as commit title on squash-merge

2022-03-31 11:50 UTC, pkuczynski commented
> @pkuczynski Could you please shorten the title of this PR to something that is max 72 chars long?
> The title is taken as commit title on squash-merge

Done

2022-03-31 17:36 UTC, ST-DDT approved these changes
I changed my mind. number isn't the offender, latitude is.
So all is good.

2022-03-31 17:48 UTC, merged