refactor: use number tuple as input for coordinate
faker-js/faker pull request #668
Opened 2022-03-24 11:57 UTC by Shinigami92

2022-03-24 12:14 UTC, ST-DDT requested changes

2022-03-24 12:14 UTC, ST-DDT commented on src/address.ts
> -  // TODO ST-DDT 2022-02-10: This should use either string or number coords.
This is not fixed yet. See return value.

2022-03-24 12:27 UTC, ST-DDT approved these changes

2022-03-25 18:17 UTC, import-brain approved these changes

2022-03-25 18:25 UTC, merged