docs: convert to typescript
faker-js/faker pull request #673
Opened 2022-03-25 09:49 UTC by Shinigami92

2022-03-25 10:45 UTC, ST-DDT commented
This PRs title is misleading

2022-03-25 11:08 UTC, ST-DDT requested changes
Don't forget the redirect for update

2022-03-25 11:08 UTC, ST-DDT commented on docs/.vitepress/config.ts
> +          link: '/about/announcements',
Shouldn't be `Announcements` its own top level item?

2022-03-25 11:08 UTC, ST-DDT commented on docs/about/team/members.json
> +]
IMO we should omit the resigned ones and add the new ones.

2022-03-25 11:08 UTC, ST-DDT commented on docs/about/team/members.json
> +]
Maybe honor them in a "previous members" list.

2022-03-25 11:11 UTC, ST-DDT commented
TODO for later: Consider adding SSR for team/api-docs to serve only static pages.

2022-03-25 12:19 UTC, Shinigami92 commented on docs/about/team.md
> +<TeamPage />
I'm not sure, but sadly I assume no
I orientate myself on https://github.com/vuejs/docs/tree/main/src/about

2022-03-25 12:20 UTC, Shinigami92 commented on docs/.vitepress/config.ts
> +          link: '/about/announcements',
I'm not sure about that yet, I don't want to explode the nav at the top in the docs

2022-03-25 12:38 UTC, Shinigami92 commented on docs/about/team/members.json
> +[
I orientate myself on [https://github.com/vuejs/docs/tree/main/src/about](https://github.com/vuejs/docs/tree/main/src/about)

2022-03-25 13:04 UTC, Shinigami92 commented
> TODO for later: Consider adding SSR for team/api-docs to serve only static pages.

We found out that VitePress already does successfully SSG for the about section, but the API section seems not to work correctly 🤔 
But this is not part for this PR

2022-03-25 13:40 UTC, Shinigami92 commented on docs/about/team/members.json
> +  ],
Do we want any kind of order for core?
What should be a sort criteria?

2022-03-25 13:40 UTC, Shinigami92 commented on docs/about/team/members.json
> +      "roles": []
@prisis What are your roles? 🙂

2022-03-25 13:40 UTC, Shinigami92 commented on docs/about/team/members.json
> +      "roles": []
@ericjeker What are your roles? 🙂

2022-03-25 13:50 UTC, ericjeker commented on docs/about/team/members.json
> +      "roles": []
That's probably not for me. 😂

2022-03-25 13:51 UTC, Shinigami92 commented on docs/about/team/members.json
> +      "roles": []
Ups... sorry, just hit enter to early 😅

@clarkerican ... 👋

2022-03-25 16:43 UTC, Shinigami92 commented
Currently it looks like this (4k screen):

![image](https://user-images.githubusercontent.com/7195563/160164056-ac42029a-2ae1-4667-acee-af3a26798df6.png)


Except for the roles and maybe some minor improvements here and there, I would like to call this as a good start for the team page.
You are welcome to improve it in additional PRs in the future 💫

2022-03-25 17:08 UTC, import-brain commented on docs/about/team/TeamMember.vue
> +      <img :src="'https://github.com/' + member.github + '.png'" width="140" />
These pictures look massive on my screen, perhaps change the width to 110 or 120. Just personal preference though

2022-03-25 17:08 UTC, import-brain commented on docs/about/team/TeamMember.vue
> +      <img :src="'https://github.com/' + member.github + '.png'" width="140" />
Other than this, this LGTM! Thank you so much for putting us on this page :)

2022-03-26 01:57 UTC, ST-DDT commented on docs/about/team/members.json
> +      "roles": ["Code Maintainer", "Docs Automation"]
```suggestion
      "roles": ["Code Maintainer", "Docs Automation"]
```

We should probably use no breaking spaces here (and in all role names):

<details>
<summary><strong>Old</strong></summary>

![grafik](https://user-images.githubusercontent.com/1579362/160219750-7d0d2cea-b94f-4fa4-9de2-812cbf80aca4.png)

</details>

<details>
<summary><strong>New</strong></summary>

![grafik](https://user-images.githubusercontent.com/1579362/160219771-55c829b4-66e2-4d5b-9f56-9e1f3f9b25af.png)

</details>

2022-03-26 01:57 UTC, ST-DDT commented on netlify.toml
> +  to = "https://chat.fakerjs.dev/about/2022-01-14.html"
```suggestion
  to = "https://fakerjs.dev/about/2022-01-14.html"
```

?

2022-03-26 01:57 UTC, ST-DDT commented on docs/.vitepress/config.ts
>      ],
I don't like that I cannot click on just `About` and some page (e.g. Announcements) opens.
Also the `About` sidenav looks very empty.
IMO we should at least list all announcements when `Announcements` is expanded (Similar to the api docs pages).

2022-03-26 01:57 UTC, ST-DDT commented on docs/about/announcements.md
> +- [2022-01-14 - An update from the Faker team](./2022-01-14)
IMO we should throw the announcements in their own folder (to ease a future automatic index/sidenav generation)

2022-03-26 01:57 UTC, ST-DDT commented on docs/about/team/TeamMember.vue
> +      <img :src="'https://github.com/' + member.github + '.png'" width="140" />
I agree with @import-brain

2022-03-26 10:18 UTC, Shinigami92 commented on netlify.toml
> +  to = "https://chat.fakerjs.dev/about/2022-01-14.html"
I totally not copied the above block, how dare I :eyes:

2022-03-26 14:00 UTC, import-brain approved these changes
LGTM, thank you! :)

2022-03-27 23:39 UTC, import-brain approved these changes

2022-03-28 08:12 UTC, pkuczynski submitted a review, later dismissed

2022-03-28 08:59 UTC, ST-DDT approved these changes
IMO clicking on about should already redirect the user, unfortunately vitepress doesn't support this or I don't know how.
Also the announcement page is quite empty. Maybe we can add some more pseudo content here. Or even a v6 release anouncement.

2022-03-28 10:34 UTC, Shinigami92 commented
> IMO clicking on about should already redirect the user, unfortunately vitepress doesn't support this or I don't know how.
Also the announcement page is quite empty. Maybe we can add some more pseudo content here. Or even a v6 release announcement.

Yeah, I hope that this page will be filled in the future with some more content. Right now it's just the start and that is one reason why it's so empty.

I would like to leave this to @JessicaSachs

2022-03-28 13:58 UTC, import-brain approved these changes

2022-03-31 09:07 UTC, prisis approved these changes

2022-03-31 09:09 UTC, prisis commented on docs/about/team/members.json
> +  ],
alphabetically, easy and we have a order without personal issues

2022-03-31 12:28 UTC, import-brain approved these changes

2022-03-31 17:51 UTC, ST-DDT approved these changes

2022-03-31 18:26 UTC, Shinigami92 commented on docs/about/team/members.json
> +      "roles": []
Will merge now, please edit on demand in a separate PR

2022-03-31 18:26 UTC, merged