feat(git.commitEntry): configure eol charcter
faker-js/faker pull request #681
Opened 2022-03-26 13:16 UTC by xDivisionByZerox

Fixes #679

2022-03-26 14:18 UTC, import-brain submitted a review, later dismissed

2022-03-31 21:02 UTC, import-brain commented on src/git.ts
> +   * 'CRLF' = '\r\n'
Yeah, I would want to keep that in too

2022-03-31 23:34 UTC, ST-DDT approved these changes

2022-04-01 11:11 UTC, import-brain approved these changes

2022-04-05 16:35 UTC, Shinigami92 requested changes
We need a test for the parameter

2022-04-23 09:08 UTC, ST-DDT requested changes

2022-04-23 09:08 UTC, ST-DDT commented on src/git.ts
> +    const eolChar = options.eol === 'CRLF' ? '\r\n' : '\n';
This condition doesn't look like CRLF is the default.

2022-04-23 09:27 UTC, xDivisionByZerox commented on src/git.ts
> +    const eolChar = options.eol === 'CRLF' ? '\r\n' : '\n';
Yeah, your right. Was noticing this when writing the test^^

2022-04-23 09:57 UTC, ST-DDT requested changes

2022-04-23 09:57 UTC, ST-DDT commented on test/git.spec.ts
> +        it('should return a random commitEntry with a default end of line charcter of "\n\r"', () => {
```suggestion
        it('should return a random commitEntry with a default end of line charcter of "\r\n"', () => {
```

2022-04-23 09:57 UTC, ST-DDT commented on test/git.spec.ts
> +        it('should return a random commitEntry with an explicit end of line charcter of "\n\r" with eol = CRLF', () => {
```suggestion
        it('should return a random commitEntry with a configured end of line charcter of "\r\n" with eol = CRLF', () => {
```

2022-04-23 09:57 UTC, ST-DDT commented on test/git.spec.ts
> +        it('should return a random commitEntry with a configured end of line charcter of "\n" with eol = LF', () => {
This test would still pass with eol crlf. 
Maybe add a expect.not.contains(crlf)?

2022-04-23 10:12 UTC, xDivisionByZerox commented on test/git.spec.ts
> +        it('should return a random commitEntry with a configured end of line charcter of "\n" with eol = LF', () => {
done in 0e04960

2022-04-23 10:13 UTC, xDivisionByZerox commented on test/git.spec.ts
> +        it('should return a random commitEntry with an explicit end of line charcter of "\n\r" with eol = CRLF', () => {
done in 7130cdbf2034dc75fcce451748ecfa0001d81c12

2022-04-23 10:13 UTC, xDivisionByZerox commented on test/git.spec.ts
> +        it('should return a random commitEntry with a default end of line charcter of "\n\r"', () => {
done in 7130cdbf2034dc75fcce451748ecfa0001d81c12

2022-04-23 10:33 UTC, ST-DDT approved these changes

2022-04-23 10:50 UTC, Shinigami92 approved these changes

2022-04-23 10:55 UTC, merged