fix(address.city): use string argument
faker-js/faker pull request #683
Opened 2022-03-26 13:49 UTC by xDivisionByZerox

Fixes #682

2022-03-26 13:51 UTC, xDivisionByZerox commented
Should the JSDOCs have a `@see faker.fake` line in it, since it's used to parse the formats?

2022-03-26 13:55 UTC, xDivisionByZerox commented
Should I add test for `address.city` since there are non so far.

2022-03-26 20:58 UTC, ST-DDT reviewed
What is the added benefit of using `address.prefix('format')` to just using `faker.fake('format')`?

2022-03-26 20:58 UTC, ST-DDT commented on src/address.ts
> +        return formats[this.faker.datatype.number(formats.length - 1)];
Use random.arrayElement here.

2022-03-26 21:08 UTC, xDivisionByZerox commented on src/address.ts
> +        return formats[this.faker.datatype.number(formats.length - 1)];
fixed in d6a48c128476162b6ced1fdb72ee2082ab57c206

2022-03-26 21:10 UTC, ST-DDT commented
> Should I add tests for `address.city` since there are non so far. Or should this be done in a separate PR?

Tests would be useful.

2022-03-28 16:41 UTC, Shinigami92 approved these changes

2022-03-30 23:46 UTC, ST-DDT reviewed
Did I miss the test for `city(number)` and city(string)`?

2022-03-30 23:46 UTC, ST-DDT commented on src/address.ts
>      this.Helpers = this.faker.helpers;
If you remove `f`, then also remove the `Helpers`.

2022-03-31 07:59 UTC, ST-DDT commented on src/address.ts
>      this.Helpers = this.faker.helpers;
This is what I meant.

2022-03-31 20:42 UTC, xDivisionByZerox commented on src/address.ts
>      this.Helpers = this.faker.helpers;
done in 91c011196bd2bb0df9f16bf9fb70b2c7dcb8f4ed

2022-04-01 14:47 UTC, ST-DDT requested changes
Could you please extract the tests for the other address methods into a separate PR?

2022-04-01 14:47 UTC, ST-DDT commented on src/address.ts
> +        return formats[Math.max(0, Math.min(format, formats.length - 1))];
Do not box the values. Either throw or ignore invalid values.

Please emit a deprecation warning for both string and number parameters.
Instead of hiding the actual pattern (that may change between faker version), they should hardcode the pattern in combination with faker.fake.

2022-04-01 15:00 UTC, Shinigami92 requested changes

2022-04-01 15:00 UTC, Shinigami92 commented on src/address.ts
> +    const useFormat = (() => {
Currently it feels like this PR does two things that can be separated

1. Just replace `fake` and `Helpers` with their `this.faker.` calls
2. This rework

IMO we should split them

2022-04-01 16:57 UTC, xDivisionByZerox commented on src/address.ts
> +    const useFormat = (() => {
When #748 is merged I can rebase and continue?

2022-04-01 17:15 UTC, xDivisionByZerox commented on src/address.ts
> +        return formats[Math.max(0, Math.min(format, formats.length - 1))];
> they should hardcode the pattern in combination with faker.fake.

Sorry but I don't understand what you mean by that.

2022-04-01 17:16 UTC, Shinigami92 commented on src/address.ts
> +    const useFormat = (() => {
exactly

2022-04-01 17:54 UTC, xDivisionByZerox commented
So why do the `helpers` tests fail now?

2022-04-01 18:24 UTC, Shinigami92 commented
> So why do the `helpers` tests fail now?

Seems like some seeded values need to be updated

2022-04-02 01:00 UTC, ST-DDT requested changes

2022-04-02 01:00 UTC, ST-DDT commented on src/address.ts
> +    ) {
I think the condition for the format flipped here.
Not sure whether `format` should have an impact here.

2022-04-02 01:00 UTC, ST-DDT commented on src/address.ts
> +        return formats[format];
Log a deprecation warning here because using a fixed format this way may break during updates and thus should be hardcoded using `faker.fake(format)` instead.

2022-04-02 01:00 UTC, ST-DDT commented on src/address.ts
> +        return format;
Same here

2022-04-02 08:18 UTC, xDivisionByZerox commented on src/address.ts
> +        return formats[format];
So if I understand correctly the `format` parameter, in general, should be depricated?

2022-04-02 08:23 UTC, xDivisionByZerox commented on src/address.ts
> +    ) {
The old condition was just `!format`. So if I provide a string format as a parameter `this.faker.definitions.address.city_name` was getting pushed, but we never access the formats array in that case. So we only case we need to push the definitions is when a number parameter is provided.

2022-04-02 08:34 UTC, xDivisionByZerox commented on src/address.ts
> +    ) {
Or was this by design? That you could never choose the 5th format (`{{address.cityName}}`) when providing an index.

2022-04-02 08:50 UTC, ST-DDT commented on src/address.ts
> +    ) {
I think they might have had the same intention as I have with deprecating the parameters. If you specify the index 4 then it would just be a call to cityName and they should do that directly instead.

I think it is safe to remove this limitation since we deprecate the name and index parameters anyway.

2022-04-02 08:51 UTC, ST-DDT commented on src/address.ts
> +        return formats[format];
Yes. If they want a fixed format they should specify exactly that.

2022-04-08 17:50 UTC, xDivisionByZerox commented
Yo, could it be that the dates generated by us break the test if they run on machines in different timezones? All tests pass on my end but fail here. The logs show expected date values `2012-02-01T23:00:00.000Z` instead of `2012-02-02T00:00:00.000Z`. 
My timezone is UTC+1 without daylight saving times and UTC+2 with daylight saving times included.

2022-04-08 17:53 UTC, xDivisionByZerox commented
Nvm we expect any date in `helpers.spec`. But why can they fail in this case?

2022-04-25 15:21 UTC, xDivisionByZerox commented on src/address.ts
> +        return formats[format];
So not the parameter itself but the number parameter should be deprecated?

2022-04-25 16:28 UTC, ST-DDT commented on src/address.ts
> +        return formats[format];
No, if they have a fixed format (either string or index) the should call `faker.fake` and not this method that just forwards the parameter there.

2022-04-25 16:37 UTC, xDivisionByZerox commented on src/address.ts
> +        return formats[format];
Ok I understand.

2022-04-25 17:00 UTC, xDivisionByZerox commented on src/address.ts
> +        return formats[format];
done

2022-04-25 17:29 UTC, ST-DDT commented on src/address.ts
> +    ) {
If you change this to

````ts
if (this.faker.definitions.address.city_name != null) {
````

then I think this PR is ready.

2022-04-25 18:31 UTC, xDivisionByZerox commented on src/address.ts
> +    ) {
done :)

2022-04-25 19:08 UTC, xDivisionByZerox commented
I don't get this test

2022-04-25 20:08 UTC, ST-DDT commented
@xDivisionByZerox I reran the pipeline and now its fixed. Looks like a temporarily codecov server issue. All green now.

2022-04-25 20:09 UTC, ST-DDT approved these changes

2022-04-26 07:52 UTC, Shinigami92 requested changes

2022-04-26 07:52 UTC, Shinigami92 commented on src/address.ts
> +          since: 'v6.2.0',
We are already targeting v6.3.0 as next

```suggestion
          since: 'v6.3.0',
```

Is there also a test that spies for this warning?

2022-04-26 07:52 UTC, Shinigami92 commented on src/address.ts
> +          since: 'v6.2.0',
```suggestion
          since: 'v6.3.0',
```

2022-04-26 07:52 UTC, Shinigami92 commented on src/address.ts
> +          deprecated: 'address.city(number)',
On all places where we use this function, we use `deprecated: 'faker.address.city(number)'`

```suggestion
          deprecated: 'faker.address.city(number)',
```

Also, we may provide a hint what the user should use instead.

2022-04-26 07:52 UTC, Shinigami92 commented on src/address.ts
> +          proposed: 'faker.fake(string)',
```suggestion
          deprecated: 'faker.address.city(string)',
          proposed: 'faker.fake(string)',
          since: 'v6.3.0',
          until: 'v7.0.0',
```

2022-04-26 09:15 UTC, xDivisionByZerox commented on src/address.ts
> +          deprecated: 'address.city(number)',
FYI:
https://github.com/faker-js/faker/blob/712b1de126ea6580660a320e065c35ac775f09b3/src/name.ts#L30-L35
https://github.com/faker-js/faker/blob/712b1de126ea6580660a320e065c35ac775f09b3/src/helpers.ts#L510-L515
https://github.com/faker-js/faker/blob/712b1de126ea6580660a320e065c35ac775f09b3/src/helpers.ts#L584-L588
https://github.com/faker-js/faker/blob/712b1de126ea6580660a320e065c35ac775f09b3/src/helpers.ts#L636-L641

2022-04-26 09:26 UTC, xDivisionByZerox commented on src/address.ts
> +          deprecated: 'address.city(number)',
done in 0747cb4aa2a2d0b6e49650019a018767ab8b29eb

2022-04-26 09:26 UTC, xDivisionByZerox commented on src/address.ts
> +          since: 'v6.2.0',
done in 0747cb4aa2a2d0b6e49650019a018767ab8b29eb

2022-04-26 09:26 UTC, xDivisionByZerox commented on src/address.ts
> +          since: 'v6.2.0',
version update in 0747cb4aa2a2d0b6e49650019a018767ab8b29eb
tests in 43c3d31c5a924826fe05a4a05297d2fbf736eebc

2022-04-26 10:02 UTC, xDivisionByZerox commented
@Shinigami92 can you have a look at the error in `address.nearbyGPSCoordinate` (since you wrote the test for it)? I don't get why changing a depreciation message resolves to this test failing.

2022-04-26 12:20 UTC, Shinigami92 commented
> @Shinigami92 can you have a look at the error in `address.nearbyGPSCoordinate` (since you wrote the test for it)? I don't get how changing a depreciation message leads to this test failing.

Yeah I see, the seed for the execution of the `nearbyGPSCoordinate` check changed due to that the execution order of the tests changed because you added the `city` test above it.
It is not your fault! The altered seed just now shows that we have an expectation issue for the `nearbyGPSCoordinate` check.

@ST-DDT and I working on it now and try to solve it.

2022-06-08 22:30 UTC, ST-DDT commented
Superseded by #948

2022-06-08 22:30 UTC, closed without merging