chore: use a standardized deprecated function
faker-js/faker pull request #689
Opened 2022-03-26 19:18 UTC by Shinigami92

2022-03-26 21:29 UTC, pkuczynski requested changes

2022-03-26 21:29 UTC, pkuczynski commented on src/deprecated.ts
> +export type DeprecatedOptions = string | FunctionReplacement;
Looking at your comment after team discussion: https://github.com/faker-js/faker/pull/645#issuecomment-1078783669

> It should have parameters for `version`, `alternative` and the possibility to override the default message.

2022-03-26 21:29 UTC, pkuczynski commented on src/deprecated.ts
> + * @param deprecatedOptions The options to log.
In other JSDoc we present all options with examples...

2022-03-26 21:29 UTC, pkuczynski commented on src/deprecated.ts
> +      `Deprecation Warning: ${deprecatedOptions.old} is now located in ${deprecatedOptions.new}`
A personal opinion: I think it would sound better written as: 

```js
`${deprecatedOptions.old} is deprecated. Please use ${deprecatedOptions.new} instead.`
```

Without the `Deprecation Warning:` in front.

2022-03-26 21:29 UTC, pkuczynski commented on src/helpers.ts
> +    deprecated(
I think this message might be hard to narrow down in the larger code. We should express more explicitly what's deprecated - in this case `helpers.createCard`

2022-03-26 21:29 UTC, pkuczynski commented on src/name.ts
> +    `Please use '${normalizedGender}' for gender instead of ${gender}`
Similarly here. I can imagine someone would upgrade to faker 6.1 in some bigger project and run it. I think he would struggle big time to understand that those deprecation messages come from `faker`...

2022-03-26 21:32 UTC, Shinigami92 commented on src/deprecated.ts
> + * @param deprecatedOptions The options to log.
Do we really need this also for internal APIs? This function will be never exposed publicly 🤔

But I could add `@internal`

2022-03-26 21:33 UTC, Shinigami92 commented on src/deprecated.ts
> +export type DeprecatedOptions = string | FunctionReplacement;
Yeah, I can add that tomorrow 
What would you think how a message could be structured?

2022-03-26 21:35 UTC, Shinigami92 commented on src/helpers.ts
> +    deprecated(
Great suggestion 👍
I will change that tomorrow

2022-03-26 22:27 UTC, pkuczynski commented on src/deprecated.ts
> + * @param deprecatedOptions The options to log.
If you put it like this, what's the point of writing JSDoc for it at all? :)

2022-03-26 22:31 UTC, pkuczynski commented on src/deprecated.ts
> +export type DeprecatedOptions = string | FunctionReplacement;
Maybe something like this:

```js
Faker.js: ${opts.deprecated} is deprecated.
Faker.js: ${opts.deprecated} is deprecated and will be removed in ${opts.until}
Faker.js: ${opts.deprecated} is deprecated. Please use ${opts.proposed} instead.
Faker.js: ${opts.deprecated} is deprecated since ${opts.since}. Please use ${opts.proposed} instead.
Faker.js: ${opts.deprecated} is deprecated and will be removed in ${opts.until}. Please use ${opts.proposed} instead.
Faker.js: ${opts.deprecated} is deprecated since ${opts.since} and will be removed in ${opts.until}. Please use ${opts.proposed} instead.
```

2022-03-27 10:11 UTC, Shinigami92 commented on src/deprecated.ts
> + * @param deprecatedOptions The options to log.
Make the linter happy 😏

2022-03-27 10:14 UTC, pkuczynski commented on src/deprecated.ts
> + * @param deprecatedOptions The options to log.
We can adjust the linter to expect jsdoc only on exported functions :)

2022-03-27 10:36 UTC, Shinigami92 commented on src/deprecated.ts
> + * @param deprecatedOptions The options to log.
Yes, lets do this

2022-03-27 10:37 UTC, Shinigami92 commented on src/deprecated.ts
> + * @param deprecatedOptions The options to log.
Oh, but how do we do this for this function? It is exported, but not made public via the bundling process :confused:

2022-03-27 11:12 UTC, Shinigami92 commented
Before I update the tests, @pkuczynski could you have a new look?

2022-03-27 11:42 UTC, pkuczynski commented on src/deprecated.ts
> + * @param deprecatedOptions The options to log.
Put all internal functions into a subfolder (eg. `lib`) and then use `overrides` in eslint config to tweak settings for this particular folder

2022-03-27 11:58 UTC, pkuczynski submitted a review, later dismissed

2022-03-27 11:58 UTC, pkuczynski commented on src/deprecated.ts
> +  if (opts.since && opts.until && opts.proposed) {
Functional wise it looks good, but code-wise there is a lot of repetition. You could do it way simpler I think. Something like:

```js
let message = `[@faker-js/faker]: ${opts.deprecated} is deprecated`

if (opts.since) {
  message += ` since ${opts.since}`
}

if (opts.until) {
  message += ` and will be removed in ${opts.until}`
}

if (opts.propsed) {
  message += `. Please use ${opts.proposed} instead`
}

return message + '.'
```

2022-03-27 11:58 UTC, pkuczynski commented
> Before I update the tests, @pkuczynski could you have a new look?

Except for the single comment I left, it all looks good to me! :) Still think annotation would work better ;)

2022-03-27 12:03 UTC, Shinigami92 commented on src/deprecated.ts
> + * @param deprecatedOptions The options to log.
Seems I cannot use
```
  overrides: [
    {
      files: ['src/**/*.ts', '!src/internal/**/*.ts'],
```

Results in infinit long waiting when running `pnpm run lint`

So I will ignore rules in file

2022-03-27 12:07 UTC, pkuczynski commented on src/deprecated.ts
> + * @param deprecatedOptions The options to log.
As we only need jsdoc on the _root_ files, change the line to `files: ['src/*.ts']` so it does not go deep

2022-03-27 12:10 UTC, pkuczynski commented on tsconfig.json
> +    "stripInternal": true
> This is an internal compiler option; use at your own risk, because the compiler does not check that the result is valid. If you are searching for a tool to handle additional levels of visibility within your d.ts files, look at [api-extractor](https://api-extractor.com/).

Do we really want this? Hmm, I would not do that tbh.

2022-03-27 12:20 UTC, Shinigami92 commented on src/deprecated.ts
> + * @param deprecatedOptions The options to log.
This will change later, cause we may plan to move more stuff into folder later (v7+)

2022-03-27 12:21 UTC, Shinigami92 commented on tsconfig.json
> +    "stripInternal": true
> Do not emit declarations for code that has an @internal annotation in its JSDoc comment.

It's only for type declaration files, so I think it's safe :thinking:

2022-03-27 12:31 UTC, pkuczynski commented on tsconfig.json
> +    "stripInternal": true
I am only citing official docs and it does not seem like recommended...

2022-03-28 13:54 UTC, ST-DDT commented
IMO we should always include the `()` in the message to make it easier to see that it refers to a method call

2022-03-28 17:03 UTC, xDivisionByZerox submitted a review, later dismissed

2022-03-28 17:15 UTC, ST-DDT approved these changes

2022-03-28 17:16 UTC, xDivisionByZerox approved these changes

2022-03-28 17:18 UTC, merged