feat: faker.finance.pin()
faker-js/faker pull request #695
Opened 2022-03-27 14:38 UTC by import-brain

fixes #472

2022-03-27 15:00 UTC, pkuczynski requested changes

2022-03-27 15:00 UTC, pkuczynski commented on src/finance.ts
> +    for (let i = 0; i < digits; i++) {
Why not `'#'.repeat(digits)`?

2022-03-27 15:07 UTC, xDivisionByZerox commented on src/finance.ts
> +   * faker.finance.pin() // '506'
The example should be a 4 character string since that's the default length.

2022-03-27 15:12 UTC, import-brain commented on src/finance.ts
> +   * faker.finance.pin() // '506'
Whoops, forgot to change the jsdoc😅

2022-03-27 15:12 UTC, xDivisionByZerox commented on src/finance.ts
> +    for (let i = 0; i < digits; i++) {
I'm not even sure why we need that extra step instead of choosing a random number right here and appending it.

2022-03-27 15:13 UTC, pkuczynski commented on src/finance.ts
> +    return this.faker.helpers.replaceSymbols(pin);
What this function does is `this.faker.datatype.number(9)`. So maybe instead all of this extra processing and conversion, you should simply do:

```
Array.from({ length }, () => this.faker.datatype.number(9)).join('')
```

(after renaming `digits` to `length`




```

2022-03-27 15:14 UTC, pkuczynski commented on src/finance.ts
> +    for (let i = 0; i < digits; i++) {
I agree! See my comment below...

2022-03-27 15:24 UTC, import-brain commented on src/finance.ts
> +    return this.faker.helpers.replaceSymbols(pin);
Wow, I didn't realize you could do this, thank you so much!

2022-03-27 15:31 UTC, xDivisionByZerox commented
What would be the expected behavior when a negative length is requested?

2022-03-27 16:04 UTC, import-brain commented
> What would be the expected behavior when a negative length is requested?

I didn't consider that scenario. Do you think it should throw an error?

2022-03-27 16:13 UTC, Shinigami92 submitted a review, later dismissed

2022-03-27 16:33 UTC, pkuczynski commented
> > What would be the expected behavior when a negative length is requested?
> 
> I didn't consider that scenario. Do you think it should throw an error?

I personally think it should throw when `< 1`...

2022-03-27 16:35 UTC, pkuczynski requested changes

2022-03-27 16:35 UTC, pkuczynski commented on src/finance.ts
> +   * faker.finance.pin() // '5067'
You should provide an example when `length` is given...

2022-03-27 16:35 UTC, pkuczynski commented on test/finance.spec.ts
> +        it('should have all characters be a digit', () => {
```suggestion
        it('should contain only digits', () => {
```

2022-03-27 18:01 UTC, xDivisionByZerox submitted a review, later dismissed

2022-03-27 18:16 UTC, pkuczynski commented on src/finance.ts
> +      throw new Error('PIN length must be 1 or greater');
```suggestion
      throw new Error('mnimum length is 1');
```

2022-03-27 18:17 UTC, pkuczynski submitted a review, later dismissed

2022-03-27 18:33 UTC, ST-DDT commented on src/finance.ts
> +   * @param length The length of the PIN to generate. Defaults to 4.
```suggestion
   * @param length The length of the PIN to generate. Defaults to `4`.
```

2022-03-27 18:33 UTC, ST-DDT commented on src/finance.ts
> +   * @throws Will throw an error if length is less than 1.
IIRC we usually dont document the errors.

2022-03-27 18:36 UTC, import-brain commented on src/finance.ts
> +   * @throws Will throw an error if length is less than 1.
```finance.iban()``` documents the errors, so I went with that

2022-03-27 18:56 UTC, ST-DDT approved these changes

2022-03-27 19:19 UTC, pkuczynski submitted a review, later dismissed

2022-04-05 16:23 UTC, Shinigami92 requested changes

2022-04-05 16:23 UTC, Shinigami92 commented on src/finance.ts
> +      throw new Error('minimum length is 1');
This needs to be a `FakerError`

2022-04-06 05:51 UTC, pkuczynski approved these changes

2022-04-06 07:50 UTC, Shinigami92 approved these changes

2022-04-06 07:52 UTC, ST-DDT approved these changes

2022-04-06 07:56 UTC, merged