Use require/import export map in package.json
faker-js/faker pull request #697
Opened 2022-03-27 16:12 UTC by revmischa

Closes #696 - please see there for more details

This is to make the export map compliant with NodeJS documentation and recommendations: https://nodejs.org/api/packages.html#conditional-exports

I believe the description and example there is pretty clear. It also mentions that using `node` as a mapping is usually wrong:
> "node" - matches for any Node.js environment. Can be a CommonJS or ES module file. In most cases explicitly calling out the Node.js platform is not necessary.

2022-03-27 16:24 UTC, Shinigami92 requested changes
This does not work right now :thinking: 

I get 
```node
file:///home/shinigami/OpenSource/faker.js-tests/esm/index.js:2
import { faker } from "@faker-js/faker";
         ^^^^^
SyntaxError: Named export 'faker' not found. The requested module '@faker-js/faker' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@faker-js/faker';
const { faker } = pkg;
```

Please checkout the https://github.com/faker-js/playground (and comment out the testings for #642)

2022-03-27 17:25 UTC, Shinigami92 approved these changes
Tested locally with the playground, it's working :+1:

2022-03-27 17:53 UTC, pkuczynski approved these changes

2022-03-28 16:55 UTC, Shinigami92 commented
Please unlock your repo / this PR so maintainers can make changes / rebase the main branch into it.
We wanted to release this in v6.1.0 but now we are stuck and need to wait on you :slightly_frowning_face:

2022-03-28 17:03 UTC, merged