docs: update faker.fake documentation
faker-js/faker pull request #709
Opened 2022-03-28 17:46 UTC by pkuczynski

2022-03-28 17:59 UTC, ST-DDT requested changes

2022-03-28 17:59 UTC, ST-DDT commented on src/fake.ts
> +   * const message = faker.fake(`You can call me at {{phone.phoneNumber(+!# !## #### #####!)}}.')
```suggestion
   * ```js
   * const message = faker.fake(`You can call me at {{phone.phoneNumber(+!# !## #### #####!)}}.')
   * ```
```

2022-03-28 17:59 UTC, ST-DDT commented on src/fake.ts
> +   * It is useful if you have to build a random string from a static, non-executable source
```suggestion
   * This method is useful if you have to build a random string from a static, non-executable source
```

2022-03-28 17:59 UTC, ST-DDT commented on src/fake.ts
> +   * It is also NOT possible to use any non-faker methods or plain javascript in such template.
```suggestion
   * It is also NOT possible to use any non-faker methods or plain javascript in such templates.
```

2022-03-28 18:54 UTC, ST-DDT requested changes
Not sure about my grammar change suggestions.

2022-03-28 18:54 UTC, ST-DDT commented on src/fake.ts
> +   * Note: We recommend using string template literals instead of `fake`,
```suggestion
   * Note: We recommend using string template literals instead of `fake()`,
```

2022-03-28 18:54 UTC, ST-DDT commented on src/fake.ts
> +   * e.g. `const address = `${faker.address.zipCode} ${faker.address.city}``
```suggestion
   * e.g. ``const address = `${faker.address.zipCode} ${faker.address.city}`;``
```

You have to use two `` ` `` because you use a single `` ` `` inside.

2022-03-28 18:54 UTC, ST-DDT commented on src/fake.ts
> +   * and if that isn't possible we will fall-back to string:
```suggestion
   * It is also possible to provide parameters. At first, we will parse them as json,
   * if that isn't possible, we will fall-back to a plain string:
```

2022-03-28 19:30 UTC, Shinigami92 commented on src/fake.ts
> +   * and if that isn't possible we will fall-back to string:
Yeah `to a string` or `to string` is totally enough

2022-03-28 20:18 UTC, ST-DDT submitted a review, later dismissed

2022-03-28 20:46 UTC, import-brain commented on src/fake.ts
> +   * It checks the given string for placeholders and replace them by calling faker methods:
```suggestion
   * It checks the given string for placeholders and replaces them by calling faker methods:
```

2022-03-28 20:50 UTC, xDivisionByZerox commented on src/fake.ts
> +   * e.g. ``const address = `${faker.address.zipCode} ${faker.address.city}`;``
```suggestion
   * e.g. ``const address = `${faker.address.zipCode()} ${faker.address.city()}`;``
```

2022-03-28 20:51 UTC, import-brain submitted a review, later dismissed

2022-03-28 20:52 UTC, xDivisionByZerox commented on src/fake.ts
> +   * It is also possible to provide parameters. At first, we will parse them as json,
```suggestion
   * It is also possible to provide parameters. At first, they will be parsed as json,
```

2022-03-28 21:44 UTC, xDivisionByZerox approved these changes

2022-03-28 22:39 UTC, ST-DDT approved these changes

2022-03-29 02:22 UTC, import-brain approved these changes

2022-03-29 07:14 UTC, Shinigami92 approved these changes

2022-03-29 07:24 UTC, merged