feat: new method faker.word.any
faker-js/faker pull request #714
Opened 2022-03-28 20:35 UTC by pkuczynski

Fixes #276 

Fixes #339

2022-03-28 20:42 UTC, ST-DDT requested changes

2022-03-28 20:42 UTC, ST-DDT commented on src/word.ts
> +   */
`@example`s are missing

2022-03-28 20:42 UTC, ST-DDT commented on src/word.ts
> +      result = generators[index](length);
Use `arrayElement()` instead

2022-03-28 20:44 UTC, pkuczynski commented on src/word.ts
> +      result = generators[index](length);
I am not using `arrayElement`, because if the generator can't satisfy the given length, I remove it from the list and try with another one. So it needs to stay as it is... Makes sense?

2022-03-28 20:44 UTC, pkuczynski commented on src/word.ts
> +   */
omg! Of course!

2022-03-28 20:44 UTC, pkuczynski commented on src/word.ts
> +   */
I actually copied it from the other method without noticing that all of them come without examples! I will add them in a separate PR...

2022-03-28 22:32 UTC, ST-DDT commented on src/word.ts
> +      result = generators[index](length);
The source/array selection shouldn't be impacted by this at all. 

AFAICT `arrayElement(generators)(length)` would still behave the same.

2022-03-28 22:33 UTC, ST-DDT approved these changes

2022-03-28 22:45 UTC, pkuczynski commented on src/word.ts
> +      result = generators[index](length);
Ok, let me explain then. If I call `arrayElement(generators)(length)` it will pick up a random generator, which might not be able to satisfy the given length. In such a case, I would like to eliminate this generator and try with a random one from the remaining list. How would I do that using purely `arrayElement`?

2022-03-28 22:45 UTC, pkuczynski commented on src/word.ts
> +      result = generators[index](length);
Ah, didnt noticed you added `nvm` later... Was following what come with email notification, sorry. Case closed.

2022-03-29 07:06 UTC, Shinigami92 requested changes

2022-03-29 07:06 UTC, Shinigami92 commented on src/word.ts
> +    } while (length && result.length < length && generators.length > 0);
We should extract the `length` check out of the do-while, so it doesn't run once even if length is 0

2022-03-29 07:06 UTC, Shinigami92 commented on test/word.spec.ts
> +        it('should return word with random length when given length can not be satisfied', () => {
Not for this PR, but IMO it feels a bit weird if a word with given length is not found then use random length 🤔 
IMO we should change behavior for all such cases to a min/max length and search between that. If nothing found return `undefined` or throw an error?
I will open a proposal issue for that... we need to think about how we can handle that

2022-03-29 09:44 UTC, pkuczynski commented on src/random.ts
> +      proposed: 'faker.word.any()',
Added this following your request on https://github.com/faker-js/faker/pull/276#issuecomment-1078777865

Or do you reffer to `proposed` only? Can you suggest some alternative?

2022-03-29 09:45 UTC, pkuczynski commented on src/word.ts
> +    } while (length && result.length < length && generators.length > 0);
It should run once even if length is `0`, as it needs to pick up first result regardless of length, right?

2022-03-29 09:46 UTC, pkuczynski commented on test/word.spec.ts
> +        it('should return word with random length when given length can not be satisfied', () => {
Yes, this is a bit weird I agree, but I just followed the other methods from this class. Felt that consistency here would be important? Maybe we should call this param `maxLength`?

2022-03-29 09:54 UTC, Shinigami92 commented on src/random.ts
> +      proposed: 'faker.word.any()',
Yes I only mean the `proposed` param

2022-03-29 09:56 UTC, Shinigami92 commented on test/word.spec.ts
> +        it('should return word with random length when given length can not be satisfied', () => {
We should change all at once, so for now I think it's okay to follow all the other functions

2022-03-29 09:57 UTC, Shinigami92 commented on src/word.ts
> +    } while (length && result.length < length && generators.length > 0);
Ah I see

2022-03-29 10:22 UTC, ST-DDT requested changes

2022-03-29 10:22 UTC, ST-DDT commented on src/word.ts
> +    } while (length && result.length < length && generators.length > 0);
All other methods in this module use `=== length`. This method should follow suite.

2022-03-29 10:23 UTC, ST-DDT commented on src/word.ts
> +    } while (length && result.length < length && generators.length > 0);
I'm fine with extending all methods later with a `length?: number | { min: number, max: number}` in a later PR.

2022-03-29 10:44 UTC, pkuczynski commented on src/word.ts
> +    } while (length && result.length < length && generators.length > 0);
It is using `===` for length :) So basically if the length condition is not met, it will do another loop picking up the next random generator, unless there are no more generators left and then it keeps the last result.

2022-03-29 10:49 UTC, pkuczynski commented on src/random.ts
> +      proposed: 'faker.word.any()',
I replaces with a new `deprecated` prop called `similar`. What do you think?

2022-03-29 11:08 UTC, ST-DDT requested changes

2022-03-29 11:08 UTC, ST-DDT commented on src/word.ts
> +    } while (length && result.length < length && generators.length > 0);
```suggestion
    } while (length && result.length !== length && generators.length > 0);
```

2022-03-29 12:34 UTC, ST-DDT approved these changes, later dismissed

2022-04-01 10:57 UTC, pkuczynski commented
@Shinigami92 anything else missing to get this merged?

2022-04-01 10:59 UTC, Shinigami92 commented
Yes, all the v6.1 targeted things to be merged I assume 🤔

2022-04-01 11:18 UTC, pkuczynski commented
> Yes, all the v6.1 targeted things to be merged I assume 🤔

Not sure if we should be so stick to the _6.1 is only bug fixes_ as keeping PRs open for longer time means potential conflicts and maintenance, so I would be in favor of merging things as soon as they ready...

2022-04-01 14:39 UTC, ST-DDT commented
> > Yes, all the v6.1 targeted things to be merged I assume 🤔
> 
> Not sure if we should be so stick to the _6.1 is only bug fixes_ as keeping PRs open for longer time means potential conflicts and maintenance

That is true. Is is a small feature, requiring low effort for maintaining the PR from you.

> so I would be in favor of merging things as soon as they ready...

If we merge this one, then we have to explain why we didn't merge other features.
Sure we could start merging them all, but then everyone would start creating new PRs with new super fancy features
and we have to somehow interweave the required bug fix merges with the nice to have feature requests.
Also people tend to prefer adding features over fixing bugs.

We use the milestones as a means to communicate the order we discussed on when to tackle things/fix/add...
This feature being in v6.2 has been discussed/communicated a few months ago, we don't want to discourage anyone in contributing to the project, so we don't ban PRs for future milestones, but I hope you can understand that this may cause you additional work to maintain them for the time being.

We hope to finish all fixes/PRs for 6.1 by this monday evening, so you don't have to maintain it forever either.

2022-04-01 16:49 UTC, pkuczynski commented
Fair enough :)

2022-04-04 08:58 UTC, ST-DDT commented
**To consider:** Handle "empty" locale
This method should at least not behave worse than the other word methods.
Ref: https://github.com/faker-js/faker/issues/770#issuecomment-1087249521

2022-04-06 11:58 UTC, Shinigami92 requested changes

2022-04-06 11:58 UTC, Shinigami92 commented on src/random.ts
> +      since: 'v6.1.0',
The upcoming release is v6.2.0
```suggestion
      since: 'v6.2.0',
```

2022-04-06 11:58 UTC, Shinigami92 commented on src/word.ts
> +      });
I might be wrong, but I assume this can be simplified to

```suggestion
      const index = this.faker.datatype.number(generators.length - 1);
```

2022-07-28 09:42 UTC, xDivisionByZerox commented
This PR is really outdated. I guess its easier to close this and then recreate it on the current main branch.
@pkuczynski Are you ok with this? Do you want to do that? Otherwise, I can offer you my help.

2022-08-11 17:16 UTC, Shinigami92 commented on src/random.ts
> +      since: 'v6.1.0',
That's really old :laughing:

2022-08-29 14:43 UTC, ST-DDT commented
I updated this branch to retain the original contribution references to @pkuczynski .

2022-08-29 14:46 UTC, ST-DDT commented on src/modules/word/index.ts
> +  words(count?: number): string {
Not sure about this name.

2022-08-29 14:46 UTC, ST-DDT commented on src/modules/word/index.ts
> +  random(length?: number): string {
Not sure about this name.

I eventually want a "random" method for some more modules.
(string.random, animal.random)

I prefer random over any, because it feels better when used with options.

````ts
faker.string.random({ allowedChars: [], bannedChars: []);
faker.string.any({ allowedChars: [], bannedChars: []);

faker.animal.random();
faker.animal.any();
````

2022-08-29 16:02 UTC, ST-DDT commented
Test failures -> https://github.com/faker-js/faker/issues/1317 + https://github.com/faker-js/faker/issues/1318

2022-08-31 22:00 UTC, xDivisionByZerox commented on src/modules/word/index.ts
> +  words(count?: number): string {
How about `many()`? Because it sounds nice when calling the entire thing: `faker.word.many()`.

2022-08-31 22:02 UTC, pkuczynski commented on src/modules/word/index.ts
> +  words(count?: number): string {
or `few()`

2022-08-31 22:04 UTC, pkuczynski commented on src/modules/word/index.ts
> +  random(length?: number): string {
for me `faker.string.any({ allowedChars: [], bannedChars: []})` looks totally fine. Better than `random` as everything is `random` in faker, so it would be misleading that others methods are not. It also reads kind of naturally: _hey, give me any string. but without chars_

2022-08-31 22:13 UTC, xDivisionByZerox commented on src/modules/word/index.ts
> +  random(length?: number): string {
Well, the same goes for `random`. *hey, give me a random string. but without chars.*
TBH, I don't care as long as it's consistent across (official) modules. But as a developer, I guess I would search for `random` first (intellisense and documentation).

2022-08-31 22:38 UTC, pkuczynski commented on src/modules/word/index.ts
> +  random(length?: number): string {
Wouldn't you then expect `faker.animal.bear()` not to be random? :)

2022-08-31 22:52 UTC, import-brain commented on src/modules/word/index.ts
> +  words(count?: number): string {
What about `multiple()`?

2022-09-01 08:30 UTC, xDivisionByZerox commented on src/modules/word/index.ts
> +  random(length?: number): string {
I still would. TBH I don't see your problem there. I don't understand your argument:

>[...] as everything is random in faker, so it would be misleading that others methods are not

I understand, but I don't see it this way. But that is nothing we can change if you feel this way but I don't.

2022-09-01 09:34 UTC, ST-DDT commented on src/modules/word/index.ts
> +  random(length?: number): string {
Added to the meeting notes for voting.

2022-09-11 09:40 UTC, damienwebdev commented on src/modules/word/index.ts
> +  random(length?: number): string {
I've been thinking about this a lot, and I feel like `random` does not fit within given that everything in Faker is pseudorandom. When you call `word` it's somewhat implied that what you get back is random. 

In essence, we're by calling this "random", we end up with a meaning like "random random" which to me feels meaningless. 

In addition, `any` also feels wrong because it has a namespace conflict with Typescript `any`.

I spent some time thinking about this and I feel like `sample` is a decent option.

The phrase "random sample" is a term in STEM, specifically statistics. "sample", in the context of a module, indicates that you're taking a "sample" of the module. https://en.m.wikipedia.org/wiki/Sampling_(statistics)


Ultimately, I think this word is also generic and fits well with all of our modules, however I'm unclear on how exactly to type it:

```ts
export interface FakerModule {
  sample(): unknown 
}
```

```ts
export interface FakerModule {
  sample(): UnionOfReturnTypeOfAllPublicMethodsOfImplementationclass??;
}
```

2022-09-11 11:46 UTC, ST-DDT commented on src/modules/word/index.ts
> +  random(length?: number): string {
I think sample is a good term.

As for having a sample method for all modules, I'm a little bit conflicted.
I would not add a sample method to modules that return different kind of data such as the address and number module. 
The address module returns mostly strings but these have significantly different semantics e.g. building number, street name, coutry name, gps coordinates. Which would make the output random instead of being a sample.
The "number" module returns different datatypes e.g. number, BigInt, hex strings... which renders the output mostly unusable.
For e.g. the word or animal module the sample method seems suitable.

2022-10-17 12:31 UTC, Shinigami92 commented
To be fair we would need to split this PR in two parts if @xDivisionByZerox's recommendation to have simple responsibilities by a PR counts for for this PR as well

So one PR introducing the new method `sample`
And one for deprecating the old method(s)

@xDivisionByZerox's point was also about that the commit history is more clean and if e.g. something need to be reverted, the commit in the default branch history can be better linked

2022-10-17 12:45 UTC, ST-DDT commented
@Shinigami92 I think you are mistaken here.
If we replace one thing with another, then we do it in one step (and always have been).
(Same as we did with renaming the name->person module, address->location, fake->helpers, phoneNumber->number, ...)

2022-10-17 12:49 UTC, Shinigami92 commented
> @Shinigami92 I think you are mistaken here. If we replace one thing with another, then we do it in one step (and always have been). (Same as we did with renaming the name->person module, address->location, fake->helpers, phoneNumber->number, ...)

But is this really a one to one replacement? I thought the code differ much from what the original code did.
The `wordMethods` from the old method had MUCH more possible values.
You can also see that the `random.word` snapshot results did change drastically (not only one offset but totally different results)

2022-10-17 12:54 UTC, ST-DDT commented
So you are referring to not replacing the old implementation itself?

2022-10-17 12:56 UTC, Shinigami92 commented
> referring

yes

like @xDivisionByZerox would say: this PR is doing two things
1. moving the old method to a new home
2. changing the implementation of that new method

2022-10-17 13:16 UTC, ST-DDT commented
I strongly disagree with moving the method implementation.
The old implementation is a list of random methods that have very little in common with "words".
The word module should not gain dependencies on any external module (expect for the current helpers one).

AFAICT we have two choices here:
- Deprecate the old method and replace its implementation with a delegate to the new words .sample method.
- Deprecate the old method and retain it as it is till removal.

2022-10-31 11:07 UTC, Shinigami92 commented on src/modules/word/index.ts
> +    } while (!result || bannedChars.some((char) => result.includes(char)));
Should we make this more `while(true)` safe in another PR?

2022-11-03 16:16 UTC, ST-DDT commented
**Team decision**

- This PR will only add the sample method.
- The random.word will be deprecated in a separate PR but will retain the original implementation

2022-11-03 23:20 UTC, ST-DDT submitted a review, later dismissed

2022-11-03 23:41 UTC, ST-DDT commented on src/modules/word/index.ts
> +    } while (!result || bannedChars.some((char) => result.includes(char)));
Yes, since I would like to automatically only take existing word categories into account.

````ts
    const opts = typeof options === 'number' ? { length: options } : options;
    return this.faker.helpers.arrayElement(
      filterWordListByLength({
        ...opts,
        wordList: Object.values(this.faker.definitions.word).flatMap((v: string) => v),
      })
    );
````

But `Object.values(this.faker.definitions.word)` is currently not supported.

2022-11-04 00:09 UTC, ST-DDT commented on src/modules/word/index.ts
> +    } while (!result || bannedChars.some((char) => result.includes(char)));
Nevermind. I found a solution to avoid this problem.
We might want to add an additional filter option later though.

2022-11-04 00:12 UTC, ST-DDT commented
Done. Ready for Review.

2022-11-04 00:13 UTC, ST-DDT submitted a review, later dismissed

2022-11-04 04:37 UTC, import-brain submitted a review, later dismissed

2022-11-04 16:45 UTC, Shinigami92 commented on src/modules/random/index.ts
> +   * @see faker.word.random()
```suggestion
   * @see faker.word.sample()
```

2022-11-04 16:45 UTC, Shinigami92 commented on src/modules/word/index.ts
> +    this.faker.helpers.shuffle(wordMethods);
🙅 Oh my good, we need to rewrite `helpers.shuffle` to not mutate the input array directly, but return a copy of the array.

I will open a PR for that later on

2022-11-04 16:45 UTC, Shinigami92 commented on src/modules/word/index.ts
> +    return words.join(' ');
Can we rewrite this to this?

```suggestion
    return Array.from({ lenght: count }, () => this.sample()).join(' ');
```

2022-11-08 20:34 UTC, Shinigami92 approved these changes

2022-11-08 20:36 UTC, ST-DDT approved these changes

2022-11-09 22:44 UTC, import-brain approved these changes

2022-11-10 07:53 UTC, merged