707 common faker js error
faker-js/faker pull request #718
Opened 2022-03-28 21:23 UTC by xDivisionByZerox

closes #707

2022-03-28 22:05 UTC, pkuczynski requested changes

2022-03-28 22:05 UTC, pkuczynski commented on src/internal/faker-js.error.ts
> +export class FakerJsError extends Error {
Why not `FakerError`? I find it quite odd to see the `Js` in the middle of it.

2022-03-28 22:05 UTC, pkuczynski commented on src/internal/faker-js.error.ts
> +    super('[@faker-js/faker]: ' + message);
I have doubts if we should prepend the error message with the library type. I have not seen this before. If a developer wants to know when the issue happens, he will see this in the stack trace. And such errors should not leak to end users...

2022-03-28 22:05 UTC, pkuczynski commented on test/unique.spec.ts
> +          }).toThrowError(/Exceeded maxTime:/);
In some tests we check `.toThrowError(new FakerJsError(...))` in some others we use regex. This should be aligned. If we introduce custom error, we should use the first syntax.

2022-03-28 22:14 UTC, xDivisionByZerox commented on src/internal/faker-js.error.ts
> +export class FakerJsError extends Error {
Was just going with the package name as default. I have no problems renaming it to `FakerError`.

2022-03-28 22:21 UTC, xDivisionByZerox commented on src/internal/faker-js.error.ts
> +    super('[@faker-js/faker]: ' + message);
Well, that's the entire point of this error class. It basically mimics the newly implemented [`deprecated()`](https://github.com/faker-js/faker/blob/main/src/internal/deprecated.ts#L14) log just as an error implementation. 

Well yes and no. By end-users you mean clients? Or developers? I agree on it being visible in the stack trace. But what if you use a bundler and your stack trace resolves to gibberish?

2022-03-28 22:22 UTC, xDivisionByZerox commented on test/unique.spec.ts
> +          }).toThrowError(/Exceeded maxTime:/);
The problem with providing an instance is that the error message has to match exactly (for my understanding) and not partialy.

2022-03-28 22:42 UTC, pkuczynski commented on src/internal/faker-js.error.ts
> +    super('[@faker-js/faker]: ' + message);
`deprecated` is a bit different as there is no stack trace... I would assume that anybody willing to watch such an error would use source maps, otherwise debugging is a real pain. Looking at the other libraries, I haven't really seen such prepending on error messages, but maybe you can point us to some examples?

2022-03-28 22:44 UTC, ST-DDT commented on src/internal/faker-js.error.ts
> +export class FakerJsError extends Error {
I prefer `FakerError` as well.

2022-03-29 06:53 UTC, Shinigami92 commented on src/internal/faker-js.error.ts
> +export class FakerJsError extends Error {
I also would like to name it `FakerError`, we also do **not** export the normal `faker` instance as `import { fakerJs } from '@faker-js/faker'` 🤷

2022-03-29 06:55 UTC, Shinigami92 commented on src/internal/faker-js.error.ts
> +    super('[@faker-js/faker]: ' + message);
IMO @pkuczynski has a point here, but it's still good to have this `Error` because the `name` of it will reflect the needed info.

So a stacktrace would contain `FakerError: ...message...` and then the stacktrace

Could you test somehow once if this is like I think?

2022-03-29 06:57 UTC, Shinigami92 commented on test/unique.spec.ts
> +          }).toThrowError(/Exceeded maxTime:/);
When using this own error, we should test for `.toThrowError(FakerError)` and maybe we just need to test the message in an additional step.

2022-03-29 09:51 UTC, pkuczynski commented on src/internal/faker-js.error.ts
> +    super('[@faker-js/faker]: ' + message);
Ah, I just noticed it's not exported in the main module. I think it should be exported. @Shinigami92 would you agree?

2022-03-29 15:03 UTC, xDivisionByZerox commented on src/internal/faker-js.error.ts
> +    super('[@faker-js/faker]: ' + message);
Just asking so I'm sure I did understand correctly:

> So a stacktrace would contain FakerError: ...message... and then the stacktrace

The custom error class is helpful because tt provides a unique constructor instance that:
 - can be checked against and handled appropriately
 - will be displayed in the error stack and thus can be traced back to faker

> Ah, I just noticed it's not exported in the main module. I think it should be exported

The `@interal` decorator should be removed (?)

2022-03-29 15:06 UTC, pkuczynski commented on src/internal/faker-js.error.ts
> +    super('[@faker-js/faker]: ' + message);
Yes, I think we should remove `@internal`, move it out of `internal` folder, add jsdoc and export in `index.ts`...

2022-03-29 15:12 UTC, xDivisionByZerox commented on src/internal/faker-js.error.ts
> +    super('[@faker-js/faker]: ' + message);
I think it's a bit misleading to have the error file lying between all the module files. Should I create an `src/error/` directory and store the file there (and export from index.ts)

2022-03-29 15:20 UTC, xDivisionByZerox commented on test/unique.spec.ts
> +          }).toThrowError(/Exceeded maxTime:/);
This was already done in the original push in the next test case.

2022-03-29 15:39 UTC, xDivisionByZerox commented on src/internal/faker-js.error.ts
> +    super('[@faker-js/faker]: ' + message);
`error` or `errors`? I wrote `src/error/` but its a directory/collections, so....

2022-03-29 15:43 UTC, Shinigami92 commented on src/internal/faker-js.error.ts
> +    super('[@faker-js/faker]: ' + message);
We have definitions, image_providers and locales, so I think errors is the way to go

2022-03-29 15:49 UTC, xDivisionByZerox commented on test/unique.spec.ts
> +          }).toThrowError(/Exceeded maxTime:/);
Removed `@internal` decorator in 2e9d4a956bbfe50498076c6b244242a559b81c11
Moved in ccf11cdfebb3f84daf29d8eb3ad4d7218b17cdb3

2022-03-29 15:50 UTC, xDivisionByZerox commented on src/internal/faker-js.error.ts
> +    super('[@faker-js/faker]: ' + message);
Removed `@internal` decorator in 2e9d4a956bbfe50498076c6b244242a559b81c11
Moved file to error dir in ccf11cdfebb3f84daf29d8eb3ad4d7218b17cdb3

2022-03-29 16:02 UTC, ST-DDT requested changes

2022-03-29 16:02 UTC, ST-DDT commented on test/unique.spec.ts
> +          }).toThrowError(/Exceeded maxTime:/);
IMO you can restore the original regex here and below, since we no longer have the custom prefix.

2022-03-29 16:21 UTC, xDivisionByZerox commented on test/unique.spec.ts
> +          }).toThrowError(/Exceeded maxTime:/);
Yeah, my bad. Didn't even noticed that change in the RegEx.
Fixed in 69a84d25bdafe7ca53f2908eed0ab44291f87a77

2022-03-29 16:47 UTC, Shinigami92 requested changes
Please re-export `FakerError` in `src/index.ts`

2022-03-29 20:35 UTC, ST-DDT approved these changes

2022-03-29 20:45 UTC, pkuczynski requested changes

2022-03-29 20:45 UTC, pkuczynski commented on src/errors/faker.error.ts
> +export class FakerError extends Error {
If I am not mistaken, `export class FakerError extends Error {}` should be enugh?

2022-03-29 20:45 UTC, pkuczynski commented on src/errors/faker.error.ts
> +/**
We don't really have that pattern to name files with `.` in the middle. So I would rather expect `faker-error`. It's not a major thing though...

2022-03-29 20:45 UTC, pkuczynski commented on src/fake.ts
> +      throw new FakerError('Invalid module: ' + parts[0]);
Why not use string templates like we do in other parts of the code??

```suggestion
      throw new FakerError(`Invalid module: ${parts[0]}`);
```

2022-03-29 20:45 UTC, pkuczynski commented on src/fake.ts
> +      throw new FakerError('Invalid module: ' + parts[0]);
This applies in many places...

2022-03-30 06:29 UTC, xDivisionByZerox commented on src/fake.ts
> +      throw new FakerError('Invalid module: ' + parts[0]);
We don't have the [prefer-template linter rule](https://eslint.org/docs/rules/prefer-template) so I don't see why this would be a required change. We do "normal" string concatenation all over the project.

2022-03-30 06:38 UTC, xDivisionByZerox commented on src/errors/faker.error.ts
> +/**
Change the file name in c7787c51e46b97e607384d03d04cb3fa7db2d233

2022-03-30 06:46 UTC, xDivisionByZerox commented on src/errors/faker.error.ts
> +export class FakerError extends Error {
Changed in a26bffd96aebca686c839350a7e7520ed6017497

2022-03-30 08:20 UTC, pkuczynski commented on src/fake.ts
> +      throw new FakerError('Invalid module: ' + parts[0]);
Indeed. I will propose this change in a separate PR as we currently use it in some places already...

2022-03-30 08:22 UTC, pkuczynski approved these changes

2022-03-30 08:41 UTC, xDivisionByZerox commented on src/fake.ts
> +      throw new FakerError('Invalid module: ' + parts[0]);
Or should we rework this when you propose that change?

2022-03-30 09:23 UTC, pkuczynski commented on src/fake.ts
> +      throw new FakerError('Invalid module: ' + parts[0]);
FYI https://github.com/faker-js/faker/pull/732 - easily fixable with `eslint --fix .` so no worries, we can move forward with this PR.

2022-03-30 09:33 UTC, xDivisionByZerox commented
> Please re-export `FakerError` in `src/index.ts`

How are things exported in the root `index.ts`? Is there any import/export order?
Should there be an index file in the errors directory? IMO this would make sense. If yes, would I make implicit or explicit exports in the root index file?

2022-03-30 13:21 UTC, Shinigami92 commented
@xDivisionByZerox You just want to do in `src/index.ts`

```ts
import { FakerError } from './errors/faker-error';
// ...
export { FakerError };
```

2022-03-30 13:29 UTC, Shinigami92 commented
> But you know that this can be simplified, do you?
> 
> ```ts
> export{ FakerError } from './errors/faker-error';
> ```
> 
> That's why I was asking because I have seen these redundant import => export statements...

Yeah I know, but I'm not yet used to it

2022-03-30 20:16 UTC, pkuczynski commented
The export is still missing @xDivisionByZerox right?

2022-03-31 07:22 UTC, Shinigami92 requested changes
index export still missing

2022-03-31 19:09 UTC, xDivisionByZerox commented
Yes the export was still missing but is implemented now.

2022-03-31 19:53 UTC, Shinigami92 approved these changes

2022-03-31 20:05 UTC, pkuczynski commented on src/errors/faker-error.ts
> +/**
In [this discussion](https://github.com/faker-js/faker/pull/733#issuecomment-1083158285) there was a suggestion to move it to `utils`

2022-03-31 20:06 UTC, pkuczynski approved these changes

2022-03-31 20:16 UTC, xDivisionByZerox commented on src/errors/faker-error.ts
> +/**
I didn't follow that discussion. But tbh I don't think errors should be located in utils. They should be located in their own directory, but that is my opinion. 
I would like to get an opinion  or even a specification of any @faker-js/maintainers

2022-03-31 20:41 UTC, ST-DDT approved these changes

2022-03-31 20:42 UTC, merged