feat: rewrite datatype to ts
faker-js/faker pull request #72
Opened 2022-01-10 20:36 UTC by Shinigami92

Use `tsc src/index.ts --outDir lib`
and then run `npx mocha test/datatype.unit.js`, or what every you want to test

2022-01-11 04:54 UTC, ericjeker commented
Hi @Shinigami92,

Did you already add a `tsconfig.json`? I can't see it anywhere.

2022-01-11 05:56 UTC, Shinigami92 commented
> Hi @Shinigami92,
> 
> 
> 
> Did you already add a `tsconfig.json`? I can't see it anywhere.

It's a draft PR for a reason 😅

2022-01-11 06:06 UTC, ericjeker commented
Ahah, OK no worries. 🙈 
I have set up this one below for TypeDoc if you wanna use it. Or should I put that in a separate PR so we can quickly merge it?

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es2016",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true
  },
}
```

2022-01-11 06:22 UTC, Shinigami92 commented
A PR based on this PR would be helpful here
Then we can better review it and test stuff out

2022-01-12 17:43 UTC, cjtim requested changes

2022-01-12 17:43 UTC, cjtim commented on src/datatype.ts
> +    const minMax = 8640000000000000;
```suggestion
    const minMax = Number.MAX_SAFE_INTEGER;
```

equal to 9007199254740991

2022-01-12 17:43 UTC, cjtim commented on src/mersenne.ts
> +    }
I think your code needs to check if min is `undefined` as well.
for example called with `rand(undefined, 20)`
the min will be overridden to 0

my suggest is Optional Parameters
https://flexiple.com/optional-parameter-javascript/
```suggestion
  rand(max = 32768, min = 0) {
    // TODO @Shinigami92 2022-01-11: This is buggy, cause if min is not passed but only max,
    // then min will be undefined and this result in NaN for the whole function
```

2022-01-13 19:45 UTC, Shinigami92 commented on src/mersenne.ts
> +    }
yeah, we will open PRs for each of these issues individually after the compile time migration to TS

2022-01-13 23:19 UTC, damienwebdev approved these changes
lgtm

2022-01-14 20:39 UTC, damienwebdev approved these changes
lgtm

2022-01-14 20:58 UTC, griest024 approved these changes

2022-01-14 21:03 UTC, prisis approved these changes

2022-01-14 23:40 UTC, damienwebdev commented
Closed and merged via rebase into main.

2022-01-14 23:40 UTC, closed without merging