chore: prefer string templates over string concatenation
faker-js/faker pull request #732
Opened 2022-03-30 09:22 UTC by pkuczynski

String templates are more readable, compact, and a bit faster than string concatenation. Edding eslint rule to force them.

See test results here:
https://jsben.ch/dWhr2

Or benchmark yourself:

```js
const Benchmark = require('benchmark')
const suite = new Benchmark.Suite()
const text = 'some text'
const number = 12

suite.add('concatenation', () => { const output = 'prefix' + text + 'middle' + number + 'postfix' })
suite.add('template', () => {const output = 'prefix' + text + 'middle' + number + 'postfix' })
suite.on('cycle', (event) => { console.log(String(event.target)) })
suite.on('complete', function() { console.log('Fastest is ' + this.filter('fastest').map('name')) })
suite.run({ async: true })
```

My results in node:

```
concatenation x 690,777,686 ops/sec ±1.55% (83 runs sampled)
template x 694,885,002 ops/sec ±1.58% (84 runs sampled)
Fastest is template,concatenation
```

2022-03-30 09:32 UTC, pkuczynski commented
Needs #733 no to fail...

2022-03-30 13:32 UTC, Shinigami92 requested changes
Please also update _vendor_ files, we could rename the folder later if you like to

2022-03-30 13:39 UTC, pkuczynski commented
> Please also update _vendor_ files, we could rename the folder later if you like to

Check #733 which excludes vendor from eslint... This should be sufficient, right?

2022-03-30 20:44 UTC, pkuczynski commented
> Please also update _vendor_ files, we could rename the folder later if you like to

Done...

2022-03-30 21:35 UTC, ST-DDT approved these changes
The performance gain is minimal and it has some implications on code readability.
Note sure, about it.

2022-03-30 21:53 UTC, pkuczynski commented
> The performance gain is minimal and it has some implications on code readability.
> Note sure, about it.

The performance gain is minimal, but the readability increases big time. At least to my taste.

2022-04-01 14:54 UTC, Shinigami92 submitted a review, later dismissed

2022-04-01 14:54 UTC, Shinigami92 commented on src/finance.ts
>        this.faker.random.arrayElement(vowels) +
If we already force to use it, then also use it everywhere

2022-04-01 14:54 UTC, Shinigami92 commented on src/commerce.ts
> +    return `${this.faker.commerce.productAdjective()} ${this.faker.commerce.productMaterial()} ${this.faker.commerce.product()}`;
I question myself why prettier allows this `printWidth`? It's far over 80 columns 🤔

2022-04-01 14:54 UTC, Shinigami92 commented on src/address.ts
> +          '#####'
This is not really more readable than before 😕

2022-04-01 14:54 UTC, Shinigami92 commented on scripts/verifyCommit.ts
> +      )}`
This is horrible 😱 
Also, not sure if this helps at least a little bit, but template literals allows real newlines. So try to replace the `\n` with just newlines.
To be safe in terms of indentation, this will then stick far to the left.

2022-04-01 14:54 UTC, Shinigami92 commented on scripts/generateLocales.ts
> +    }`
Should we introduce a new variable for that?

2022-04-03 23:06 UTC, pkuczynski commented on scripts/verifyCommit.ts
> +      )}`
It was quite terrible before too ;) Prettier forcing formatting also does not help :/ @Shinigami92 have a look if it is better now?

2022-04-03 23:14 UTC, pkuczynski commented on src/address.ts
> +          '#####'
This is changing in #754 so I will leave it as it is for now, ok?

2022-04-03 23:15 UTC, pkuczynski commented on src/commerce.ts
> +    return `${this.faker.commerce.productAdjective()} ${this.faker.commerce.productMaterial()} ${this.faker.commerce.product()}`;
80 columns are anyway quite narrow limit to my taste...

2022-04-03 23:27 UTC, pkuczynski commented
@ST-DDT made some improvements. Can you have a look again and comment on places that you don't like?

2022-04-04 17:39 UTC, pkuczynski commented
@Shinigami92 @ST-DDT all changes applied, ready for your re-review

2022-04-04 17:57 UTC, ST-DDT requested changes

2022-04-04 17:57 UTC, ST-DDT commented on scripts/verifyCommit.ts
> +    `  ${colors.bgRed(colors.white(' ERROR '))}${colors.red(
Is this change intentional?

![grafik](https://user-images.githubusercontent.com/1579362/161603272-3790b68f-7d36-4c46-9c6b-3bbfacb166b7.png)

2022-04-04 17:59 UTC, pkuczynski commented on scripts/verifyCommit.ts
> +    `  ${colors.bgRed(colors.white(' ERROR '))}${colors.red(
Not at all, not sure how did it happend. Thank you for a good catch!

2022-04-06 08:05 UTC, ST-DDT reviewed
One last quibble, otherwise it looks good to me.

2022-04-06 08:05 UTC, ST-DDT commented on src/internet.ts
> +    }${greenStr}${blueStr.length === 1 ? '0' : ''}${blueStr}`;
Please use one line per color here to improve readability.

2022-04-06 08:44 UTC, pkuczynski commented on src/internet.ts
> +    }${greenStr}${blueStr.length === 1 ? '0' : ''}${blueStr}`;
I fixed it like this: https://github.com/faker-js/faker/pull/732/commits/b1f44be9e6ffb76acda10978271668d922a0a861

Does this work? I think @Shinigami92 mentioned that we should not use `private` methods, not sure why? But then I needed `this.faker.datatype.number` in this function, so I could not take it out from the class...

And recommendation welcome! All in all I think it looks way cleaner now :)

2022-04-06 08:53 UTC, Shinigami92 requested changes

2022-04-06 08:55 UTC, Shinigami92 commented on src/internet.ts
> +  private colorFromBase(base: number): string {
It has something to do with the
https://github.com/faker-js/faker/blob/7017e07ca4215f00f0bc23f8a2c33b08242a4d84/src/internet.ts#L7-L16

Even if the tests are green, these private functions are not real-js private

2022-04-06 08:58 UTC, pkuczynski commented on src/internet.ts
> +  private colorFromBase(base: number): string {
Yeah, I was wondering why do we do this bind? So we can use `faker.bla.bla` without instantiating the class with `new`?

2022-04-06 09:00 UTC, pkuczynski commented on src/internet.ts
> +  private colorFromBase(base: number): string {
Then the only option I have is to define this function inside `color` but that sucks a bit, don't you think so?

2022-04-06 09:02 UTC, pkuczynski commented on src/internet.ts
> +  private colorFromBase(base: number): string {
Than why don't we export faker like:

```
const faker = new Faker();

export { faker }
export { Faker }
```

This would solve those issues and would not require this funky, counterintuitive constructor. Right?

2022-04-06 09:02 UTC, Shinigami92 commented on src/internet.ts
> +  private colorFromBase(base: number): string {
Exact, this was a historical possibility from pre 5.5.3 times. I personally don't like it really much, but folks are doing stuff like:
```ts
import { faker } from '@faker-js/faker';
const genColor = faker.internet.color; // This would not work without our class-constructor-binding-this-hack
const color = genColor();
```
😣
And we did not want to break their source code

2022-04-06 09:04 UTC, pkuczynski commented on src/internet.ts
> +  private colorFromBase(base: number): string {
Yeah, but if we would export `const faker = new Faker()` the example above wold work nicely, right?

2022-04-06 09:04 UTC, ST-DDT commented on src/internet.ts
> +  private colorFromBase(base: number): string {
IMO, the method is quite small, if you use a lambda, so its shouldn't be that much of an issue.

````ts
const colorFromBase = (base: number) => Math.floor((this.faker.datatype.number(256) + base) / 2)
      .toString(16)
      .padStart(2, '0');
````

It's at least more readable, then repeating it 3 times.

2022-04-06 09:11 UTC, pkuczynski commented on src/internet.ts
> +  private colorFromBase(base: number): string {
Yeah, I could use the lambda and size wise its fine, but I would expect it to be slower? Run the benchmark and to my surprise it was not, not sue if this is correct results: https://jsben.ch/xyjlE

2022-04-06 09:27 UTC, ST-DDT commented on src/internet.ts
> +  private colorFromBase(base: number): string {
For me lambda is ~1% faster.
But as long as the impact isn't huge I'm not that concerned about performance.
We are a lib for testing, not for production.
Please note that a console.log is 20xtimes slower than our function (not sure whether the benchmark requires a black hole) in order to be accurate.

Lambda/Static only = ~5 000 000
With Console log = ~220 000

2022-04-06 10:58 UTC, pkuczynski commented on src/internet.ts
> +  private colorFromBase(base: number): string {
I updated the benchmark to remove the console.log and all depends on the env https://jsben.ch/BqH74 Safari seems to be ~5-10% slower. In Chrome ~5%.

We are testing library which means we could be also used for performance testing to generate hundreds of millions of records, where performance would matter...

But I can do lambda if you think its better...

2022-04-06 10:59 UTC, pkuczynski commented on src/internet.ts
> +  private colorFromBase(base: number): string {
Done

2022-04-06 11:47 UTC, ST-DDT approved these changes

2022-04-18 21:49 UTC, pkuczynski commented
@ST-DDT @Shinigami92 all changes applied... Can you re-review, please?

2022-04-19 08:28 UTC, ST-DDT approved these changes

2022-04-19 11:52 UTC, prisis approved these changes

2022-04-19 20:38 UTC, Shinigami92 approved these changes

2022-04-19 20:38 UTC, merged