fix(address.nearbyGPSCoordinate): deterministic results
faker-js/faker pull request #737
Opened 2022-03-30 18:17 UTC by xDivisionByZerox

closes #736

2022-03-30 19:50 UTC, pkuczynski submitted a review, later dismissed

2022-03-30 21:01 UTC, ST-DDT commented on test/address.spec.ts
> +            inputs.nearbyGpsCoordinates
Maybe just hardcode them here? The value is always the same AFAICT.

2022-03-31 07:30 UTC, Shinigami92 requested changes

2022-03-31 07:30 UTC, Shinigami92 commented on src/address.ts
> +        }) * 360.0
I would just go with e.g. `faker.datatype.float({ min: 0, max: 360, precision: 1e-4 })`

2022-03-31 19:25 UTC, xDivisionByZerox commented on src/address.ts
> +        }) * 360.0
Updated in f81341e83c2f3f0267d882f7c05550f1907a17b2

2022-03-31 19:32 UTC, xDivisionByZerox commented on test/address.spec.ts
> +            inputs.nearbyGpsCoordinates
Updated in c0258cb4af0eaced6606689d4c4d6c8caf83d8a4

2022-03-31 19:32 UTC, xDivisionByZerox commented on test/address.spec.ts
> +      nearbyGpsCoordinates: [number, number];
Removed in c0258cb4af0eaced6606689d4c4d6c8caf83d8a4

2022-03-31 20:02 UTC, xDivisionByZerox commented
I'm testing local again to see if I forgot something, but I normally always run tests locally before pushing :/

2022-03-31 20:03 UTC, xDivisionByZerox commented
The `max = 360` implemented a rounding change on the 4th decimal place of 1 expect value :)

2022-03-31 20:08 UTC, xDivisionByZerox commented
> The `max: 360` property in datatype.number implemented a rounding change on the 4th decimal place of 1 expect value :)

Well, that's funny;
If I set up a test by myself I get `[ '-0.0394', '0.0396' ]` as result.
```
import { faker } from './src';

faker.seed(42);
console.log(faker.address.nearbyGPSCoordinate([0, 0]));
```

But if I run the test suite it gets `[ '-0.0393', '0.0396' ]`

2022-03-31 20:18 UTC, Shinigami92 commented
Should we use 1e-5 ?

2022-03-31 20:34 UTC, xDivisionByZerox commented
🎉🎉🎉

2022-03-31 20:39 UTC, ST-DDT approved these changes

2022-03-31 20:58 UTC, import-brain approved these changes

2022-04-01 14:07 UTC, Shinigami92 approved these changes

2022-04-01 14:10 UTC, merged