feat: rewrite datatype to ts
faker-js/faker pull request #74
Opened 2022-01-10 21:23 UTC by Shinigami92

2022-01-10 21:46 UTC, HonzaMac requested changes

2022-01-10 21:46 UTC, HonzaMac commented on src/time.ts
> +    let date: string | number | Date = new Date();
This ignores faker seed value. It would became non-deterministic.

2022-01-10 21:48 UTC, Shinigami92 commented on src/time.ts
> +    let date: string | number | Date = new Date();
I could add a TODO for later
We currently aim just for the migration and not for runtime changes

2022-01-10 21:59 UTC, MateusDadalto commented
I don't think the actions are validating the typescript changes here.
If you run `tsc src/index.ts --outDir lib` and then `npm run test` we get tests failing.

2022-01-11 05:37 UTC, HonzaMac commented on src/time.ts
> +    let date: string | number | Date = new Date();
Why adding feature then?

2022-01-11 05:57 UTC, Shinigami92 commented on src/time.ts
> +    let date: string | number | Date = new Date();
What do you mean?
This is just a rewrite of `lib/time.js`

2022-01-11 20:41 UTC, prisis commented on src/time.ts
> +    let date: string | number | Date = new Date();
There is no new feaure  
  
\`\`\`

self.recent = _function_ (outputType) {  
  _if_ (_typeof_ outputType === 'undefined') { // this moved to the function  
    outputType = 'unix';  
  }  
  
  _var_ date = _new_ Date();  
  _switch_ (outputType) {  
    _case_ 'abbr':  
      date = date.toLocaleTimeString();  
      _break_;  
    _case_ 'wide':  
      date = date.toTimeString();  
      _break_;  
    _case_ 'unix':  
      date = date.getTime();  
      _break_;  
  }  
  _return_ date;  
};  
\`\`\`

2022-01-11 20:50 UTC, Shinigami92 commented on src/time.ts
> +    let date: string | number | Date = new Date();
Still don't understand, as you said there is no new feature right now in this PR
It's just a migration to TS and only touched compile time code

2022-01-13 21:30 UTC, prisis approved these changes

2022-01-14 16:04 UTC, merged