ci: auto npm publish script
faker-js/faker pull request #757
Opened 2022-04-02 13:37 UTC by import-brain

fixes #268

2022-04-02 13:38 UTC, import-brain commented on .github/workflows/npm-publish.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
This needs to be configured for this workflow to work.

2022-04-02 13:48 UTC, Shinigami92 commented
This looks ridiculously easy :thinking:

2022-04-02 13:49 UTC, ST-DDT submitted a review, later dismissed
I cannot test this, but I think it looks good.
We can merge and check it Monday with our v6.1.2 release.

2022-04-02 13:52 UTC, Shinigami92 approved these changes, later dismissed
But we need @prisis or @damienwebdev to add the token

2022-04-02 13:53 UTC, import-brain commented
> This looks ridiculously easy :thinking: _sus_?

May or may not have been copy-pasted from GitHub documentation😂

2022-04-02 17:47 UTC, xDivisionByZerox commented
Isn't the point of this pipeline to ensure that things like v6.1.0 don't happen again? Well, the pipeline doesn't build the newest state of the library or did I miss something?

2022-04-02 17:51 UTC, Shinigami92 commented
> Does the `npm publish` automatically include a build?

Yes it does, since 6.1.1

https://github.com/faker-js/faker/commit/62dcfc9658e6d3ee23b9e674d10b9a229b026d0e#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R76

2022-04-02 17:58 UTC, xDivisionByZerox commented
Ok, I didn't notice that. But tbh I'm not a fan of relying on pre/post scripts for pipelines since:
1. I want to see what a pipeline does by looking at its config file
2. A change in this script can slip in too easy  without noticing it directly

Just some points you might want to consider.

2022-04-02 19:33 UTC, ST-DDT commented
@xDivisionByZerox So you would like us to explicitly call `build` or what?

2022-04-02 19:37 UTC, xDivisionByZerox commented
> @xDivisionByZerox So you would like us to explicitly call build or what?
I would do so for my pipelines, yes. But I don't think I'm in the position to demand anything. 

I guess it would be helpful enough, for anyone that might have a look at the config in the future, to add a comment over the `npm publish`, that there is a pre-publish script in place.

2022-04-02 19:45 UTC, pkuczynski requested changes

2022-04-02 19:45 UTC, pkuczynski commented on .github/workflows/npm-publish.yml
> +          registry-url: 'https://registry.npmjs.org'
Looks like it's default so does not need to be specified?

2022-04-02 19:45 UTC, pkuczynski commented on .github/workflows/npm-publish.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
Why NODE_TOKEN_AUTH and not NPM_TOKEN?

2022-04-02 19:45 UTC, pkuczynski commented on .github/workflows/npm-publish.yml
> +    runs-on: ubuntu-latest
Does it have to be Ubuntu? Alpine are usually smaller = faster execution

2022-04-02 19:45 UTC, pkuczynski commented
I am with @xDivisionByZerox on this...

2022-04-02 20:01 UTC, ST-DDT commented
> I am with @xDivisionByZerox on this...

Would something like this suffice for you?

````yaml
# Relies on the prepublishOnly hook to build the project
- run: npm publish
````

Unfortunately it isn't possible to add comments to the package.json to add a hint there too.
IMO the info in the pipeline is not really helpful, because it only state what it depends on (and that it's nothing extraordinary for an Node dev), but the other side side contains no reference to dependent steps (and AFAICT these vary greatly between projects).

2022-04-02 20:24 UTC, xDivisionByZerox commented
> Would something like this suffice for you?
> 
> ```yaml
> # Relies on the prepublishOnly hook to build the project
> - run: npm publish
> ```
> 
> Unfortunately it isn't possible to add comments to the package.json to add a hint there too. IMO the info in the pipeline is not really helpful, because it only state what it depends on (and that it's nothing extraordinary for an Node dev), but the other side contains no reference to dependent steps (and AFAICT these vary greatly between projects).

I mean if you state it that way, why not explicitly call the necessary build steps? Yes, it's a bit redundant and takes some more time to complete, on the other side this is run like once a week, so it shouldn't matter.
Even going a step further: Why not remove the `prepublish` script from the package? When a release pipeline is in place NOONE should make a manual release EVER.

2022-04-03 11:30 UTC, prisis commented
I would go more in this direction [https://www.npmjs.com/package/@changesets/cli,](https://www.npmjs.com/package/@changesets/cli,) check [https://github.com/Thinkmill/manypkg](https://github.com/Thinkmill/manypkg) as example how it works, it creates a .changeset folder with all the changes than can be than released

2022-04-03 14:06 UTC, ST-DDT commented
Looks like we won't have a pipeline by Monday.

2022-04-03 15:47 UTC, prisis commented
Nope, sorry... , we can talk about it tomorrow in the call :)

2022-08-12 20:57 UTC, Shinigami92 commented on .github/workflows/npm-publish.yml
> +          node-version: '16.x'
We might want to use node 18

```suggestion
          node-version: 18
```

2022-08-12 20:57 UTC, Shinigami92 commented on .github/workflows/npm-publish.yml
> +      - run: npm publish
We might want to use pnpm instead of npm for the automated publish process
That's because pnpm can later be used to release mono-repo structures
and so this is a preparation for when we extract locales out to own packages

2022-08-12 20:59 UTC, Shinigami92 commented on .github/workflows/npm-publish.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
Yeah that looks wrong :thinking: 

https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#set-the-token-as-an-environment-variable-on-the-cicd-server

2022-08-13 09:39 UTC, ST-DDT requested changes

2022-08-13 09:39 UTC, ST-DDT commented on .github/workflows/npm-publish.yml
> +      - run: pnpm ci
Does this command exist only in ci? I cannot run it locally.

2022-08-13 10:16 UTC, Shinigami92 commented on .github/workflows/npm-publish.yml
> +      - run: pnpm ci
I think this is the native **npm** not pnpm command
The theoretically equivalent would be something like using `--frozen-lockfile`
But this might be auto-enables in `env CI=true`
https://pnpm.io/cli/install#--frozen-lockfile

2023-01-26 18:04 UTC, import-brain commented
Superseded by #1096

2023-01-26 18:04 UTC, closed without merging

2023-01-30 00:20 UTC, ST-DDT commented
@import-brain Do you still need the branch? If not, please delete it.

2023-01-30 00:39 UTC, import-brain commented
> @import-brain Do you still need the branch? If not, please delete it.

Done