feat: add devcontainer to repo
faker-js/faker pull request #76
Opened 2022-01-11 04:31 UTC by MateusDadalto

issue #73

2022-01-11 07:21 UTC, Shinigami92 commented
Is there a way to test it (without merging it)?

2022-01-11 14:03 UTC, MateusDadalto commented
@Shinigami92 AFAIK only manual testing, and I think before merging it I should add some docs explaining how to use

2022-01-12 01:56 UTC, MateusDadalto commented
@Shinigami92 I think the docs are ready. Could you review them please? Also, would be nice to try running it yourself

2022-01-12 02:24 UTC, ericjeker commented on CONTRIBUTING.md
> +## VS Code Remote Development
I'd like to suggest we don't make this relevant only to VSCode. Remote development is working perfectly fine on other IDEs. We can move the doc for specific IDE to sub-headings under this one.

Also, this makes people think they can contribute only if they use VSCode, which is not good I think.

2022-01-12 02:50 UTC, MateusDadalto commented on CONTRIBUTING.md
> +## VS Code Remote Development
That's a good point, I don't want to close this project's scope to be VSCode only. I added it specifically to vscode because it is the one I'm used to work on.

I'll move it to a sub-heading but I'd need help to create docs and configuration for other IDE's remote development

2022-01-12 03:00 UTC, ericjeker commented on CONTRIBUTING.md
> +## VS Code Remote Development
I'll have to check how to do that with Jetbrain products. But at least this section is extensible to other IDEs.

2022-01-12 03:03 UTC, ericjeker requested changes
I think headings are not properly set.

2022-01-12 03:03 UTC, ericjeker commented on CONTRIBUTING.md
> +## Why?
This should be a H3 (###).

2022-01-12 03:03 UTC, ericjeker commented on CONTRIBUTING.md
> +## Remote Development in VS Code
This should be a H3 (###).

2022-01-12 03:03 UTC, ericjeker commented on CONTRIBUTING.md
> +### Prerequisites
This should be a H4 (####).

2022-01-12 03:03 UTC, ericjeker commented on CONTRIBUTING.md
> +### Starting up the container
This should be a H4 (####).

2022-01-12 03:08 UTC, ericjeker approved these changes

2022-01-12 16:35 UTC, Shinigami92 requested changes

2022-01-12 16:35 UTC, Shinigami92 commented on .devcontainer/devcontainer.json
> +    "extensions": [
Could your format this file with prettier? I assume you didn't do it for all the files then :thinking:

2022-01-12 16:35 UTC, Shinigami92 commented on CONTRIBUTING.md
> +Remote Development allow the contributors to leverage docker and have a standard development environment. With it, the maintainers of this repo can setup a default configuration for anyone who wants
Could we explain the benefit over just pressing period (`.`) while being on repos main page or in a PR?
=> https://github.dev/faker-js/faker

2022-01-12 20:58 UTC, MateusDadalto commented on .devcontainer/devcontainer.json
> +    "extensions": [
I thought I had, but I did not, commited a fix just now with files formatted

2022-01-12 21:05 UTC, MateusDadalto commented on CONTRIBUTING.md
> +Remote Development allow the contributors to leverage docker and have a standard development environment. With it, the maintainers of this repo can setup a default configuration for anyone who wants
I've updated it with the benefits that I see over github dev editor, which is the ability to build and run tests

2022-01-12 21:13 UTC, Shinigami92 commented on CONTRIBUTING.md
> +Remote Development allow the contributors to leverage docker and have a standard development environment. With it, the maintainers of this repo can setup a default configuration and create a complete
prettier also can format markdown :wink:

2022-01-12 21:15 UTC, Shinigami92 requested changes

2022-01-12 21:15 UTC, Shinigami92 commented on CONTRIBUTING.md
> +Make sure to have VS Code and [Microsoft's Remote Development Extension Pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) installed. Or simply in
```suggestion
Make sure to have VS Code and [Microsoft's Remote Development Extension Pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) installed. Or simply install the recommended extensions in the project's `.vscode/extensions.json` file.
```

2022-01-12 21:15 UTC, Shinigami92 commented on CONTRIBUTING.md
> +With the dependecies installed, run the **Remote-Containers: Open Folder in Container...** command from the Command Palette (F1 o Ctrl+Shift+P) and open this project's root directory. VS code should
```suggestion
With the dependecies installed, run the **Remote-Containers: Open Folder in Container...** command from the Command Palette (F1 o Ctrl+Shift+P) and open this project's root directory. VS code should detect the `.devcontainer/devcontainer.json` file automatically and start a new docker container ready to run this project. 
```

2022-01-12 21:15 UTC, Shinigami92 commented on CONTRIBUTING.md
> +Remote Development allow the contributors to leverage docker and have a standard development environment. With it, the maintainers of this repo can setup a default configuration and create a complete
```suggestion
Remote Development allow the contributors to leverage docker and have a standard development environment. With it, the maintainers of this repo can setup a default configuration and create a complete environment to build/run/tests/debug for anyone who wants to step right into the developing part.
```

2022-01-12 21:17 UTC, Shinigami92 commented
I cannot review the `.devcontainer/git-completion.bash` and `.devcontainer/git-prompt.sh` cause they are so huge

Also does this not work on windows? :thinking: 
Not a problem for me, but ... :shrug:

2022-01-12 21:20 UTC, MateusDadalto commented
@Shinigami92 they're fetched directly from git repo to give nice git functionalities to bash, you can verify the file integrity comparing it to the one at
https://github.com/git/git/tree/master/contrib/completion

2022-01-12 23:52 UTC, MateusDadalto commented on CONTRIBUTING.md
> +Remote Development allow the contributors to leverage docker and have a standard development environment. With it, the maintainers of this repo can setup a default configuration and create a complete
thx! formatted!

2022-01-14 12:38 UTC, damienwebdev requested changes

2022-01-14 12:38 UTC, damienwebdev commented on CONTRIBUTING.md
> +Make sure to have VS Code and [Microsoft's Remote Development Extension Pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) installed. Or simply in
Need a link to VSCode.

2022-01-14 12:38 UTC, damienwebdev commented on CONTRIBUTING.md
> +With the dependecies installed, run the **Remote-Containers: Open Folder in Container...** command from the Command Palette (F1 o Ctrl+Shift+P) and open this project's root directory. VS code should
Portuguese `o` "F1 o Ctrl+Shift+P"

2022-01-14 12:38 UTC, damienwebdev commented on CONTRIBUTING.md
> +Make sure to have VS Code and [Microsoft's Remote Development Extension Pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) installed. Or simply in
`Visual Studio Code` not `VS code` for proper terminology. We can (at this point) rename to VSCode, but for new users start off with the proper name to prevent confusion.

2022-01-21 17:07 UTC, ST-DDT commented
How about adding an example project to get actually started with faker?
(Or I did miss the part where faker is added to the container?)

2022-04-01 15:49 UTC, closed without merging