feat: immutable options in random.alpha methods
faker-js/faker pull request #790
Opened 2022-04-06 12:19 UTC by ST-DDT

Similar to other methods I changed `random.alpha()` and `random.alphaNumeric()` to don't alter their options.

Hints for reviewers:
- I also moved the default values to the method signature, to improve the api doc generation.
- I removed the array length check, as the called method does nothing, if the array is empty, and does so almost NO-OP. I can re-add the check, if you insist.

2022-04-06 12:28 UTC, ST-DDT commented on src/random.ts
> +    options:
Did you miss the default value?
https://github.com/faker-js/faker/blob/c8ae059dcdd7325e930fdd3d63b7217c806cd2c2/src/random.ts#L405-L409

2022-04-06 12:40 UTC, pkuczynski commented on src/random.ts
> +    options:
The default values would not work if user will pass partial `options` object, right?

2022-04-06 12:40 UTC, Shinigami92 commented on src/random.ts
> +    options:
Oh my god, seems it's horrible to read 👀 
Sry for false alarm

2022-04-06 12:42 UTC, Shinigami92 commented on src/random.ts
> +    options:
> The default values would not work if user will pass partial `options` object, right?

Yes 🙁 , but maybe line 416-418 solves this?

2022-04-06 12:45 UTC, pkuczynski commented on src/random.ts
> +    options:
> > The default values would not work if user will pass partial `options` object, right?
> 
> 
> 
> Yes 🙁 , but maybe line 416-418 solves this?

It does, but then the same logic is in two places... :/

2022-04-06 12:59 UTC, ST-DDT commented on src/random.ts
> +    options:
Actually 4:
- jsdocs
- signature
- impl
- test(s)

If js would support better syntax, then we would only need 2 (+ jsdocs can be cross-validated).

2022-04-06 13:01 UTC, ST-DDT commented on src/random.ts
> +    const bannedChars = options.bannedChars ?? [];
> In packages like VueUse we are using a more advanced syntax like

Lets discuss this later today.

> Maybe we should use `options: { bannedChars?: readonly string[] }` in line 473, as far as I know, this also allows readonly and non-readonly arrays to be passed.

Will do so.

2022-04-08 12:36 UTC, Shinigami92 requested changes
Previously there was no failing test, please add one to test that the options are not mutated

2022-04-08 16:33 UTC, Shinigami92 submitted a review, later dismissed

2022-04-08 20:07 UTC, pkuczynski commented on src/random.ts
> +    options:
I believe @Shinigami92 implemented this differently in his PR keeping the logic only in the implementation, and I must say I like it more... regardless of my opinion, we should do this consistently. Now we don't, so for me its a blocker...

2022-04-09 01:35 UTC, ST-DDT commented on src/random.ts
> +    options:
I changed it please review again.

2022-04-09 08:51 UTC, pkuczynski approved these changes

2022-04-10 10:13 UTC, Shinigami92 approved these changes

2022-04-10 10:15 UTC, merged