feat: reimplement datatype.bigInt
faker-js/faker pull request #791
Opened 2022-04-06 17:54 UTC by Shinigami92

2022-04-06 18:38 UTC, pkuczynski requested changes

2022-04-06 18:38 UTC, pkuczynski commented on src/datatype.ts
> +    const min = typeof opts.min === 'bigint' ? opts.min : BigInt(0);
So if I pass `min: 100` faker would ignore this and use 0? I would be really surprised when that happens...

2022-04-06 18:38 UTC, pkuczynski commented on src/datatype.ts
> +   * @param options Maximum value or options object.
This is a breaking change. How do we warn users about it?

2022-04-06 18:38 UTC, pkuczynski commented on src/datatype.ts
> +  bigInt(options?: bigint | { min?: bigint; max?: bigint }): bigint {
I think we should accept numbers here too, not only bigint...

2022-04-06 19:38 UTC, Shinigami92 commented on src/datatype.ts
> +    const min = typeof opts.min === 'bigint' ? opts.min : BigInt(0);
Currently it is not (TS-)possible to pass a `number`, so what you are asking for is to make it possible to pass `number`?

2022-04-06 19:38 UTC, Shinigami92 commented on src/datatype.ts
> +   * @param options Maximum value or options object.
We write in changelog that we fully reimplemented this function
I do not expect that anyone currently use the function, as it is currently totally useless :shrug:

2022-04-06 19:38 UTC, Shinigami92 commented on src/datatype.ts
> +  bigInt(options?: bigint | { min?: bigint; max?: bigint }): bigint {
So yeah, that is what I was asking with the BigIntConstructor params
Also it's the answer to https://github.com/faker-js/faker/pull/791#discussion_r844266361 :slightly_smiling_face: 

BitIntConstructor params are `number | bigint | string | boolean`

2022-04-07 00:29 UTC, ST-DDT requested changes

2022-04-07 00:29 UTC, ST-DDT commented on test/datatype.spec.ts
> +          expect(generateBigInt).toBeTypeOf('bigint');
This should check the bounds.

2022-04-07 00:29 UTC, ST-DDT commented on test/datatype.spec.ts
> +          };
Wouldn't it be easier to freeze the input and check for exceptions due to attempted mutations?

2022-04-07 00:29 UTC, ST-DDT commented on src/datatype.ts
> +    const offset = generateRandomBigInt(delta.toString(10).length) % delta;
Loops have a worst case success rate of 1/9. You might run a few loops before you get a valid value.
Not sure what is more important "no bias" or "better performance".

2022-04-07 00:36 UTC, ST-DDT commented
Please also add a test, that uses min:0, max: 1000000000000 (it is important that these are 1 and then only zeros, as these are harder to "find" for some implementations (e.g. loop based ones).

00-99 => 100% (100/100) success rate
000-100 => 10% (100/999) success rate

2022-04-07 00:39 UTC, ST-DDT commented on src/datatype.ts
> +    const offset = generateRandomBigInt(delta.toString(10).length) % delta;
We could do 10 tries via loop before we fall back to the modulo operation.

2022-04-07 11:00 UTC, Shinigami92 commented on src/datatype.ts
> +      );
I will implement this in another PR to track a specific commit message in git history

2022-04-07 11:02 UTC, Shinigami92 commented on src/datatype.ts
> +    const offset = generateRandomBigInt(delta.toString(10).length) % delta;
I would like not to call `faker.datatype.number` over and over again, because that way we waste seed sequence 🤔

2022-04-07 11:54 UTC, Shinigami92 commented on src/datatype.ts
> +      throw new Error(`Max ${max} should be larger then min ${min}`);
Needs to be FakerError

2022-04-07 15:28 UTC, ST-DDT commented on src/datatype.ts
> +    const offset = generateRandomBigInt(delta.toString(10).length) % delta;
Are they limited?

2022-04-08 06:53 UTC, Shinigami92 commented
Awaiting other PRs like #797 to be done

2022-04-08 10:29 UTC, Shinigami92 commented on src/datatype.ts
> +    const offset = generateRandomBigInt(delta.toString(10).length) % delta;
Let's start with the current implementation and if users raising issue for that, we can improve it later

2022-04-21 20:31 UTC, ST-DDT approved these changes

2022-04-22 12:37 UTC, pkuczynski submitted a review, later dismissed

2022-04-24 22:09 UTC, ST-DDT submitted a review, later dismissed

2022-05-18 22:15 UTC, ST-DDT approved these changes

2022-05-23 06:53 UTC, prisis approved these changes

2022-05-23 06:59 UTC, merged

2022-05-23 07:48 UTC, xDivisionByZerox commented on src/modules/datatype/index.ts
> +      max = BigInt(options ?? 999999999999999);
Why can you pass `options` directly here? [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/BigInt#syntax) documentation states that the value can "May be a string or an integer". So why the `boolean` (in general) or the object?

I've never worked with BigInt so sorry if this makes no sense.

2022-05-23 07:49 UTC, xDivisionByZerox commented on src/modules/datatype/index.ts
> +      | boolean
What would `faker.datatype.bigInt(false)` return? I don't understand what advantage we have from accepting a boolean parameter.

2022-05-23 07:58 UTC, Shinigami92 commented on src/modules/datatype/index.ts
> +      | boolean
<img width="121" alt="image" src="https://user-images.githubusercontent.com/7195563/169771647-82fcdb02-3a83-449e-a443-d55efff4a6e9.png">

It's just the official constructor argument