feat: special characters in emails
faker-js/faker pull request #792
Opened 2022-04-06 22:10 UTC by harsohailB

**Resolves:**

#272 

**Key Changes:**

* Added `config: EmailConfig` option to generate `email()` and `exampleEmail()`
* Used the following [source](https://en.wikipedia.org/wiki/Email_address#Local-part) to randomly replace username characters with accepted email characters ```!#$%&'*+-/=?^_`{|}~```

**Tests:**

* Added tests for both `email()` and `exampleEmail()` with the added config to test special characters in emails

2022-04-07 08:06 UTC, Shinigami92 requested changes
I would like that we also add seeded based tests for this example, so we can also test the deterministic

2022-04-07 08:06 UTC, Shinigami92 commented on src/internet.ts
> +import type { EmailConfig } from './definitions/internet';
The definitions are more for the `locales` and not for the `interface` and `type` definitions.
So sorry for the misunderstanding here, but please move this into the `src/internet.ts` above the `class` directly.

2022-04-07 08:06 UTC, Shinigami92 commented on src/internet.ts
> +    if (config && config.allowSpecialCharacters) {
This might be possible to simplify to
```suggestion
    if (config?.allowSpecialCharacters) {
```

2022-04-07 08:06 UTC, Shinigami92 commented on src/internet.ts
> +    return localPart + '@' + provider;
We have another PR were we start to try to always use template literals
```suggestion
    return `${localPart}@${provider}`;
```

2022-04-07 08:43 UTC, ST-DDT requested changes

2022-04-07 08:43 UTC, ST-DDT commented on src/internet.ts
> +import type { EmailConfig } from './definitions/internet';
@Shinigami92 Should we go for a explicit type or an inline type? AFAIK we currently use only inline types.

2022-04-07 09:51 UTC, Shinigami92 commented
> Should we go for an explicit type or an inline type? AFAIK we currently use only inline types.

I also thought about that and maybe we should just go with inline for now.

2022-04-07 09:59 UTC, ST-DDT commented on src/internet.ts
> +   * @param config The optional config to use. If not specified, configuration options will not be applied.
I tested and currently this is not supported by the api docs generator. => Please use inline types for now.

2022-04-07 15:11 UTC, harsohailB commented on src/internet.ts
> +import type { EmailConfig } from './definitions/internet';
Moved interface to `internet.ts`. I can make it an inline type if you decide to do so.

2022-04-07 15:15 UTC, harsohailB commented on src/internet.ts
> +    if (config && config.allowSpecialCharacters) {
Done!

2022-04-07 15:15 UTC, harsohailB commented on src/internet.ts
> +    config?: EmailConfig
Renamed!

2022-04-07 15:19 UTC, harsohailB commented on src/definitions/internet.ts
> +   * Enables random special characters to be present in generated email
Done!

2022-04-07 15:20 UTC, harsohailB commented on src/internet.ts
> +   * @param config The optional config to use. If not specified, configuration options will not be applied.
Oh, I see @Shinigami92 has decided to go with inline so I will push that!

2022-04-07 15:25 UTC, ST-DDT requested changes

2022-04-07 15:27 UTC, harsohailB commented on src/internet.ts
> +import type { EmailConfig } from './definitions/internet';
Moved interface to be inline.

2022-04-07 15:28 UTC, harsohailB commented on src/internet.ts
> +export interface EmailOptions {
Done in [38468e4](https://github.com/faker-js/faker/pull/792/commits/38468e4431ba7187385c4414337d4620671dc80e)

2022-04-07 15:32 UTC, harsohailB commented
> I would like that we also add seeded based tests for this example, so we can also test the deterministic

Is there an example for this that I can follow? @Shinigami92 @ST-DDT

2022-04-07 15:36 UTC, ST-DDT requested changes

2022-04-07 15:36 UTC, ST-DDT commented on src/internet.ts
> +   * as .!#$%&'*+-/=?^_`{|}~ in the email
```suggestion
   * @param options The options to use. Defaults to `{ allowSpecialCharacters: false }`.
   * @param options.allowSpecialCharacters Whether special characters such as `.!#$%&'*+-/=?^_`{|}~` should be included
   * in the email address. Defaults to `false`.
```

2022-04-07 15:36 UTC, ST-DDT commented on src/internet.ts
> +   * as .!#$%&'*+-/=?^_`{|}~ in the email
```suggestion
   * @param options The options to use. Defaults to `{ allowSpecialCharacters: false }`.
   * @param options.allowSpecialCharacters Whether special characters such as `.!#$%&'*+-/=?^_`{|}~` should be included
   * in the email address. Defaults to `false`.
```

2022-04-07 15:36 UTC, ST-DDT commented on src/internet.ts
> +   * faker.internet.email('Jeanne', 'Doe', 'example.fakerjs.dev', { allowSpecialCharacters: true }) // 'Jeanne%Doe88@example.fakerjs.dev'
Please update this example to match this method.

2022-04-07 15:41 UTC, harsohailB commented on src/internet.ts
> +   * faker.internet.email('Jeanne', 'Doe', 'example.fakerjs.dev', { allowSpecialCharacters: true }) // 'Jeanne%Doe88@example.fakerjs.dev'
Done! Thanks for pointing this out. Missed that.

2022-04-07 15:41 UTC, harsohailB commented on src/internet.ts
> +   * as .!#$%&'*+-/=?^_`{|}~ in the email
Committed!

2022-04-08 09:51 UTC, ST-DDT requested changes

2022-04-08 09:51 UTC, ST-DDT commented on src/internet.ts
> +   * faker.internet.email('Jeanne', 'Doe', { allowSpecialCharacters: true }) // 'Jeanne%Doe88@example.fakerjs.dev'
```suggestion
   * faker.internet.exampleEmail('Jeanne', 'Doe', { allowSpecialCharacters: true }) // 'Jeanne%Doe88@example.fakerjs.dev'
```

2022-04-08 16:28 UTC, Shinigami92 commented on src/internet.ts
> +   * faker.internet.exampleEmail('Jeanne', 'Doe', { allowSpecialCharacters: true }) // 'Jeanne%Doe88@example.fakerjs.dev'
```suggestion
   * faker.internet.exampleEmail('Jeanne', 'Doe', { allowSpecialCharacters: true }) // 'Jeanne%Doe88@example.com'
```

2022-04-08 16:28 UTC, ST-DDT approved these changes

2022-04-08 16:34 UTC, merged