feat: random numeric
faker-js/faker pull request #797
Opened 2022-04-07 11:27 UTC by Shinigami92

2022-04-07 15:44 UTC, ST-DDT requested changes

2022-04-07 16:58 UTC, import-brain commented on src/random.ts
> +   * @throws When `length` is less than or equals to `0`.
```suggestion
   * @throws When `length` is less than or equal to `0`.
```

2022-04-07 17:00 UTC, import-brain commented
Doesn't this do the same thing as ```finance.pin()```?

2022-04-07 18:30 UTC, pkuczynski commented on src/random.ts
> +   * Generating a string consisting of digits based on length.
Numeric in many languages and SQL databases is a number with certain precision: `NUMERIC(precision, scale)`. So having a method with this name would be misleading. If user would like to have a number with certain number of digits he could just call `faker.datatype.number({ min: 100, max: 999 })`, correct? And if he would like to make a string out of it, he could typecast it `String(faker.datatype.number(...))`.

So in principle I am a bit against this feature as it is unclear and duplicates what's already achievable by other method.

2022-04-07 18:31 UTC, pkuczynski commented on src/random.ts
> +   * Generating a string consisting of digits based on length.
As a side node, I think we could consider splitting `faker.datatype` into `faker.number`, `faker.string` etc...

2022-04-08 07:05 UTC, Shinigami92 commented
> Doesn't this do the same thing as `finance.pin()`?

@import-brain: a little bit yes, but it is more like `finance.pin` can use this function. For the UX I would like to have both functions, but with a limited option set that is specialised for generating pin numbers. Maybe we also could add something like `internet.authCode`?
`datatype.bigInt` will also use this function.

@pkuczynski: @ST-DDT and I have short communication paths via personal friendship and discord, so we sometimes implement stuff together in our private space. I understand your suggestions, but sometimes we are a little bit ahead in thinking processes (e.g. in terms of how we want to re-structure the modules in "vFuture"). Not everything of that is somewhere to read because we are just thinking by communicating. So it might be that we want to go into another direction as you suggested.
But re-structuring modules will be anyways something for that far future.

2022-04-08 07:07 UTC, Shinigami92 commented on src/random.ts
> +        '0123456789'.split('')[this.faker.datatype.number({ min: 0, max: 9 })]
I think I will make a screenshot of that, post it on twitter and say that sometimes a break could be healthy 🤣

2022-04-08 07:12 UTC, pkuczynski commented
I noticed that you have short paths of communication, which is fine of course, but keeping the community away from it, is kind of demotivating... :/

2022-04-08 08:59 UTC, ST-DDT commented
> I noticed that you have short paths of communication, which is fine of course, but keeping the community away from it, is kind of demotivating... :/

Thanks for letting us know. We try to improve on this and establish regular team-meetings.
You can always ping us, if you have a specific topic you would like to discuss.
Things like this tend to come up during our reviews and it's hard to always communicate them.
(I usually tend to create issues for those things, but since this is only at the stage of we are thinking about it, I haven't done so yet)
I created a discussion for this idea of ours now: https://github.com/faker-js/faker/discussions/805

If you notice again, that there are some things that haven't been communicated (well), then let us know.

2022-04-08 09:47 UTC, ST-DDT commented on src/random.ts
> +   * Generating a string consisting of digits based on length.
IMO this is a very basic feature, that is useful in many places. I mostly consider this to be the base for the other methods.

You have a point with this method's name being a bit ambigous for now.
Should we name it `numericString` until we restructure the modules in v7?

2022-04-08 10:17 UTC, ST-DDT requested changes

2022-04-08 10:17 UTC, ST-DDT commented on src/random.ts
> +   * Generating a string consisting of digits based on length.
```suggestion
   * Generates a string consisting of digits based on length.
```

2022-04-08 10:17 UTC, ST-DDT commented on test/random.spec.ts
> +    });
This should check that a digit has been returned.

2022-04-08 10:17 UTC, ST-DDT commented on test/random.spec.ts
> +    );
Same here

2022-04-08 10:17 UTC, ST-DDT commented on test/random.spec.ts
> +    });
This is kind of redundant. Please merge it with the above tests.

2022-04-08 10:17 UTC, ST-DDT commented on test/random.spec.ts
> +    it('should allow leading zeros via option and all other digits banned', () => {
```suggestion
    it('should fail on leading zeros via option and all other digits banned', () => {
```

2022-04-08 10:17 UTC, ST-DDT commented on test/random.spec.ts
> +    it('should ban all digits pass via bannedDigits', () => {
```suggestion
    it('should ban all digits passed via bannedDigits', () => {
```

2022-04-08 10:45 UTC, Shinigami92 commented on test/random.spec.ts
> +// TODO @Shinigami92 2022-04-08: Add seeded runs
I extracted an issue #809

2022-04-08 16:39 UTC, ST-DDT approved these changes

2022-04-08 18:31 UTC, pkuczynski commented on src/random.ts
> +   * Generating a string consisting of digits based on length.
I think we should go straight to `faker.string.numbers`. Please note that I used plural form here, as what we generate is not a number but string consisting of numbers...

2022-04-08 18:47 UTC, pkuczynski requested changes

2022-04-08 18:47 UTC, pkuczynski commented on src/random.ts
> +   * Generates a string consisting of digits based on length.
```suggestion
   * Generates a given length string of digits.
```

2022-04-08 18:47 UTC, pkuczynski commented on src/random.ts
> +      bannedDigits?: ReadonlyArray<string>;
We could make the type more strict here:

```
      bannedDigits?: ReadonlyArray<'0' | '1' | '2'...>;
```

2022-04-08 18:47 UTC, pkuczynski commented on src/random.ts
> +            .filter((char) => /^[0-9]$/.test(char))
I believe in the other (or maybe the same?) PR you said that we should not validate user input, as we do have contract defined and users are responsible to follow it. What changed your mind?

2022-04-08 18:47 UTC, pkuczynski commented on src/random.ts
> +      bannedDigits?: ReadonlyArray<string>;
We could also let users provide a string instead of array, so the can say `bannedDigits: '236'`

2022-04-08 18:47 UTC, pkuczynski commented on src/random.ts
> +        ? Array.from(new Set([...bannedDigits]))
Isn't this premature optimization? It does not make any functionally any difference if provided array is uniq or not, right?

2022-04-08 18:52 UTC, Shinigami92 commented on src/random.ts
> +      bannedDigits?: ReadonlyArray<string>;
> We could make the type more strict here:
> 
> ```
>       bannedDigits?: ReadonlyArray<'0' | '1' | '2'...>;
> ```

That is literally the TODO above that line 😉 

> We could also let users provide a string instead of array, so the can say `bannedDigits: '236'`

I currently mimic the behavior of `bannedChars` from `alpha` and `alphaNumeric`. So if we allow a string, let's change that for them consistently in a separate PR.

2022-04-08 18:58 UTC, Shinigami92 commented on src/random.ts
> +            .filter((char) => /^[0-9]$/.test(char))
This is not for validating user input, but just filtering out only the necessary chars and the user can pass just any chars they want (for better UX, not the need to especially cast a provided value forcefully with TypeScript types).

2022-04-08 18:59 UTC, ST-DDT commented on src/random.ts
> +            .filter((char) => /^[0-9]$/.test(char))
IIRC there was some code that relied on `0` being the first value in there, but I think its gone now.
IMO we can remove the `joinedBannedDigits` entirely now, as we could just use `bannedDigits.includes` in line 582.

2022-04-08 19:00 UTC, Shinigami92 commented on src/random.ts
> +        ? Array.from(new Set([...bannedDigits]))
Yeah, I assume it is just pre-optimization 🤔

2022-04-08 19:08 UTC, Shinigami92 commented on src/random.ts
> +            .filter((char) => /^[0-9]$/.test(char))
Done via https://github.com/faker-js/faker/pull/797/commits/9f6cedab0aae7d6bb5f80c1028d955fbfa0492c2

2022-04-08 19:26 UTC, Shinigami92 commented on src/random.ts
> +      bannedDigits?: ReadonlyArray<string>;
I started to draft #819

2022-04-08 19:29 UTC, ST-DDT approved these changes
The implementation looks good to me. But we still have to decide where to put it.

2022-04-08 20:24 UTC, pkuczynski commented on src/random.ts
> +      bannedDigits?: ReadonlyArray<string>;
Why not doing the proper type straight away? :)

2022-04-08 20:34 UTC, pkuczynski submitted a review, later dismissed
As suggested before I would put it in faker.string.numbers

2022-04-09 02:33 UTC, ST-DDT commented on src/random.ts
> +      bannedDigits?: ReadonlyArray<string>;
- Consistency of the code (optimally across the entire code base :flushed:), we still have to work on this one
- Traceability in the git history
- But most importantly because it is easier to spot mistakes, if you change these things in multiple places at once.
  (Both implementation and review wise)

2022-04-10 04:26 UTC, import-brain approved these changes
I think this is fine where it is, don't think there's really a need to move it

2022-04-10 09:50 UTC, Shinigami92 commented
> I think this is fine where it is, don't think there's really a need to move it

Thx, I also would like to move the module discussion into a later major and not bind it to these feature implementations

2022-04-10 09:54 UTC, pkuczynski commented
> Thx, I also would like to move the module discussion into a later major and not bind it to these feature implementations

Its a new function so it's not about moving it but rather putting in a future destination place... otherwise we will have to deprecate it and people will need to make an update on the next major release. Double the work.

2022-04-10 09:56 UTC, Shinigami92 commented
Deprecations should not be removed directly, but marked as for removal or moved to new location

2022-04-10 09:57 UTC, Shinigami92 commented
This PR adds a function in v6.2 to a module that already exists in v6
Adding a whole new module is a separate PR and targeted for v7 or later

2022-04-21 20:27 UTC, ST-DDT requested changes
Just some minor things left.

Also what about:
https://github.com/faker-js/faker/pull/797#discussion_r845942681

2022-04-21 20:27 UTC, ST-DDT commented on test/random.spec.ts
> +        expect(actual).toMatch(/[0-9]+$/);
You should merge these checks:

```suggestion
        expect(actual).toMatch(/^[1-9][0-9]+$/);
```

2022-04-21 20:27 UTC, ST-DDT commented on test/random.spec.ts
> +    });
Please add a length check.

2022-04-22 06:07 UTC, Shinigami92 commented on test/random.spec.ts
> +        expect(actual).toMatch(/[0-9]+$/);
How does this work with a given `length = 1`?

2022-04-22 06:32 UTC, ST-DDT commented on test/random.spec.ts
> +        expect(actual).toMatch(/[0-9]+$/);
Use * instead of +

2022-04-22 12:07 UTC, ST-DDT approved these changes

2022-04-24 16:51 UTC, import-brain approved these changes

2022-04-24 17:12 UTC, merged