refactor: datatype number
faker-js/faker pull request #798
Opened 2022-04-07 11:51 UTC by Shinigami92

2022-04-07 12:18 UTC, ST-DDT approved these changes

2022-04-07 12:34 UTC, pkuczynski commented on src/datatype.ts
> +      min = options.min ?? 0;
The issue with this approach is that it does not check proper type of this property. I know we are using types, but they would only be checked if someone is using TS. When he is not, he could easily call this function as `faker.datatype.number({min: 'a'}). How should it work in such case? Throw an error? Assume option is invalid and take default? Right now it will just accept it and (I think) return `NaN`... Maybe that's fine, don't know. Before it checking for the type and ignoring invalid options, so in a way its a breaking change...

2022-04-07 12:50 UTC, Shinigami92 commented on src/datatype.ts
> +      min = options.min ?? 0;
> what's the value of this refactor?

To align it to the #791 impl

> easily call this function as `faker.datatype.number({min: 'a'})`

If someone would do this, they just disrespect the API contract and we would need to check every single input parameter in every single function.
We don't do that. We do not want to do that.
If someone disrespect the API contract, they need to life with unsupported behavior.
This PR does not change the API contact / function signature.

2022-04-07 13:35 UTC, pkuczynski commented on src/datatype.ts
> +      min = options.min ?? 0;
Just my $.2 I preferred the old implementation. Felt simpler and shorter. #791 is new so it should rather align to what we had then vice versa :)

2022-04-07 14:41 UTC, ST-DDT commented on src/datatype.ts
> +      min = options.min ?? 0;
After having another look at this. I think I like the options remapping L40 (but maybe directly overwrite the options).

````ts
if (typeof options === number) {
 options = { ... }
}
````

The default should be set in the signature as well. That would remove the need for the fallback from that check too.
It would also explicitly document the default in our api docs.

After that we don't need the big if anymore either as well as allowing us to use const for the values again.
So that should hopefully solve most of @pkuczynski's issues with these changes.

However, I agree with @Shinigami92 that we don't have to check for most of out API contract.
If we do check, then we should explicitly throw an error instead of silently ignoring the wrong value.

So please revert this partially/change this to be closer to pkuczynski's implementation.

2022-04-07 14:41 UTC, ST-DDT requested changes
See my comment above.

2022-04-07 15:10 UTC, ST-DDT reviewed
Not sure if you want to fix this here, but there is a bug in this method for negative numbers.

````ts
faker.datatype.number({ min: -5, max: -4 })
````

never generates `-4` due to the if being there (should always apply)

https://github.com/faker-js/faker/blob/0b8cac057a471d1b392a44f1327df05b35c9f9b5/src/datatype.ts#L57

As an alternative you could just remove the if and its body and add +1 to the max  side of the `mersenne.rand()` call. That way `max` could be a const as well.

2022-04-07 15:45 UTC, pkuczynski commented on src/datatype.ts
> +    let max = options.max ?? min + 99999;
I like the destructuring with defaults

2022-04-08 15:19 UTC, ST-DDT approved these changes

2022-04-08 20:10 UTC, pkuczynski approved these changes

2022-04-08 20:17 UTC, merged