feat: adding documentation with vitepress
faker-js/faker pull request #80
Opened 2022-01-11 09:14 UTC by JessicaSachs

Hello! This pull request adds infrastructure for a Vitepress website. The documentation is largely copy/pasted from @jeffbeltran 's "Un-official faker.js" docs [here](https://github.com/JeffBeltran/faker.js-docs).

Should address #47 and then lay the foundation for building #46 (via the /playground/ page in `docs/playground/index.md`).

There is a `netlify.toml` file to deploy on Netlify and we have an account that will be setup tomorrow morning. Here's a preview of the site on my personal Netlify account https://61dd4313b4122d0007e9a5c4--boring-colden-7dfbbb.netlify.app/

I will say that there is a LOT of documentation that needs to be updated.

2022-01-11 09:26 UTC, Shinigami92 requested changes
Could you run prettier over the docs?

2022-01-11 09:26 UTC, Shinigami92 commented on README.md
> +# faker.js
I think we explicitly wanted to _rebrand_ it as `Faker`

2022-01-11 09:26 UTC, Shinigami92 commented on docs/.vitepress/theme/components/Badge.vue
> +import { computed } from 'vue'
Seems this import is not needed :thinking:

2022-01-11 09:26 UTC, Shinigami92 commented on docs/.vitepress/theme/components/Playground.vue
> +import { ref, computed } from 'vue'
`computed` also not needed here :thinking:

2022-01-11 09:26 UTC, Shinigami92 commented on docs/api/address.md
> +  :::
Offset may be wrong

2022-01-11 09:26 UTC, Shinigami92 commented on docs/api/address.md
> +faker.address.city({{name.lastName}}{{address.citySuffix}}) // Powlowski port
I assume this needs quotes :thinking:

2022-01-11 09:26 UTC, Shinigami92 commented on docs/guide/recent-faqs.md
> +pnpm add -D faker@5.5.3
Needs updated package name

2022-01-11 09:26 UTC, Shinigami92 commented on tsconfig.json
> +    /* Visit https://aka.ms/tsconfig.json to read more about this file */
Please remove all the comments
Let's use a simple config
It also could conflict with the config coming in #72 :thinking: Is it possible to just omit this file for now?

2022-01-11 09:44 UTC, JessicaSachs commented on README.md
> +# faker.js
OK yeah I wasn't sure because it was so inconsistent and then the logo looked a little weird. I agree a re-brand is a good idea.

2022-01-11 09:44 UTC, JessicaSachs commented on docs/.vitepress/theme/components/Badge.vue
> +import { computed } from 'vue'
Yeah, we really need a linter.

2022-01-11 09:45 UTC, JessicaSachs commented on tsconfig.json
> +    /* Visit https://aka.ms/tsconfig.json to read more about this file */
I'm not sure. I agree that it may conflict. I'm happy to use mjs/js instead of ts and let the real typescript PR come in.

2022-01-11 09:46 UTC, JessicaSachs commented on docs/api/address.md
> +faker.address.city({{name.lastName}}{{address.citySuffix}}) // Powlowski port
Yeah, I largely copy/pasted this in from the existing docs.

2022-01-11 09:51 UTC, Shinigami92 commented on docs/.vitepress/theme/components/Badge.vue
> +import { computed } from 'vue'
We have eslint, but not fully setup yet
Prio for me: TS migration

2022-01-11 10:01 UTC, JessicaSachs commented on tsconfig.json
> +    /* Visit https://aka.ms/tsconfig.json to read more about this file */
Yeah I had no problems swapping to mjs.

2022-01-11 10:37 UTC, prisis commented
Can you update the year from 2020 to 2022 :D

2022-01-11 16:44 UTC, Shinigami92 requested changes

2022-01-11 16:44 UTC, Shinigami92 commented on package-lock.json
> +  "lockfileVersion": 1,
Please recreate the lock file with node 16, npm 8

2022-01-11 17:24 UTC, Shinigami92 approved these changes

2022-01-11 20:31 UTC, prisis approved these changes

2022-01-12 16:39 UTC, Shinigami92 requested changes

2022-01-12 16:39 UTC, Shinigami92 commented on package.json
> +    "postinstall": "npm run browser"
Not sure if we want this right now
I reject currently some PRs cause they update these files and we cannot review them cause they are to huge
I don't trust folks in that and we should generate them before release or so on our side

2022-01-12 19:09 UTC, damienwebdev requested changes

2022-01-12 19:09 UTC, damienwebdev commented on package.json
> +    "postinstall": "npm run browser"
What is the purpose of this `postinstall`?

2022-01-12 19:19 UTC, JessicaSachs commented on package.json
> +    "postinstall": "npm run browser"
When building the docs + playground, we need to load faker into the browser. Until we have a way to require faker at runtime we need to require the browserified dist.

TLDR: 

Running `npm run docs:dev` and navigating to `localhost:3000/playground/` should not crash.

2022-01-12 20:41 UTC, JessicaSachs commented on package.json
> +    "postinstall": "npm run browser"
This PR needs to go out.

2022-01-12 20:44 UTC, Shinigami92 commented on package.json
> +    "postinstall": "npm run browser"
Maybe we could do `npm run browser && vitepress build docs` for now or something like this
I just wont like to do it after install, cause currently (like I said) it's not reviewable and insecure

2022-01-12 20:47 UTC, damienwebdev commented on package.json
> +    "postinstall": "npm run browser"
Can we instead run this `npm run browser` as a part of `docs:dev` then?

```
npm run browser && vitepress dev docs
```

2022-01-12 21:50 UTC, Shinigami92 approved these changes

2022-01-12 22:20 UTC, damienwebdev approved these changes
lgtm

2022-01-13 00:48 UTC, merged