feat: color module
faker-js/faker pull request #801
Opened 2022-04-07 20:05 UTC by harsohailB

**Resolves:**

#286 

**Key Changes:** RGBA, CMYK, HSL

[] Migrate color API from `commerce` to its own `color` module
[] Add random `RGBA` generation
[] Add random `CMYK` generation
[] Add random `HSL` generation
[] Migrate tests from `commerce.spec.ts` to `color.spec.ts`
[] Add tests for `RGBA` generation
[] Add tests for `CMYK` generation
[] Add tests for `HSL` generation

2022-04-08 07:31 UTC, prisis commented
Thank you very much for your Pull Request :) we a discussing in what version of faker it would make sense to put this feature into, but it looks like it will go into faker v7. We will update you on the process :)

2022-04-08 07:53 UTC, ST-DDT reviewed
I'll review it, when we start with v7.

2022-04-08 07:53 UTC, ST-DDT commented on src/locales/ar/commerce/index.ts
> +} as Partial<CommerceDefinitions>;
Please run `pnpm run generate:locales` again.

2022-04-08 07:55 UTC, Shinigami92 requested changes
We should think about if we want to go more in a direction of supporting CSS stuff or more like generating values for e.g. `three.js`.

For CSS I would also like to see something like get a [color gamut](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut) `display-p3`

But for three.js I would like to have e.g. possibility to generate colors for a specific channel or stuff like that: https://threejs.org/docs/#api/en/math/Color

And maybe there is also something else non-css/non-three.js

2022-04-08 07:55 UTC, Shinigami92 commented on src/color.ts
> +  rgb(): string {
For hex colors I would assume `rgbHex`

---

Additionally, we could provide optional options for 

- allow only upper or lower or mixed case
- prefix or not prefix with '0x'

2022-04-08 07:55 UTC, Shinigami92 commented on src/color.ts
> +   * Returns a RGB color in hex format
Please end JSDoc sentence with period `.`

2022-04-08 07:55 UTC, Shinigami92 commented on src/color.ts
> +   * Returns a RGB color in decimal format
I'm not sure about `decimal` or another wording here, because I see a difference between `[255, 255, 255]` and `[1.0, 1.0, 1.0]`.
Both could be used e.g. for something like `three.js`

2022-04-08 07:55 UTC, Shinigami92 commented on src/color.ts
> +   * faker.color.rgbaNumeric() // '[255, 255, 255, 0.54]'
Looks weird for me to suddenly treat alpha channel differently 🤔 
What were your source for relying on a base/definition?

2022-04-08 07:55 UTC, Shinigami92 commented on src/color.ts
> +  private getPercentage(): number {
We do not use `private` functions, instead inline the code or use a non-exported function above the class.

It may change on the road to v7+ 🤔 But currently we iterate in test over all member functions of a module and test them.
JS doesn't have the ability to detect that a function was marked with private due to it is just a TypeScript concept and not real-js.

2022-04-08 12:14 UTC, Shinigami92 commented on src/commerce.ts
> -      this.faker.definitions.commerce.color
Yeah, we should reuse the new color function and write a deprecation message to remove it in v8

2022-04-08 17:30 UTC, harsohailB commented on src/locales/ar/commerce/index.ts
> +} as Partial<CommerceDefinitions>;
Generated!

2022-04-08 17:33 UTC, harsohailB commented on src/color.ts
> +   * faker.color.rgbaNumeric() // '[255, 255, 255, 0.54]'
At the bottom of this source, a floating point between 0 and 1 is used to show the alpha percentage:
https://www.w3schools.com/css/css_colors_rgb.asp

2022-04-08 17:47 UTC, harsohailB commented
> We should think about if we want to go more in a direction of supporting CSS stuff or more like generating values for e.g. `three.js`.
> 
> For CSS I would also like to see something like get a [color gamut](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut) `display-p3`
> 
> But for three.js I would like to have e.g. possibility to generate colors for a specific channel or stuff like that: https://threejs.org/docs/#api/en/math/Color
> 
> And maybe there is also something else non-css/non-three.js

@Shinigami92 I will look into this further and update the PR description with new tasks.

2022-04-08 17:48 UTC, harsohailB commented on src/color.ts
> +   * Returns a RGB color in hex format
Done!

2022-04-08 18:15 UTC, harsohailB commented on src/commerce.ts
> -      this.faker.definitions.commerce.color
Completed in commit c7f255e. If someone can confirm that the change is correct, that would be awesome!

2022-04-08 18:47 UTC, harsohailB commented on src/color.ts
> +  rgb(): string {
Done!

2022-04-08 18:50 UTC, harsohailB commented on src/color.ts
> +   * Returns a RGB color in decimal format
Should we allow `options` here to specify the numeric type to be `int` or `float` for clarity (will default to `int`)? Docs can be changed to "numeric format" instead of "decimal format"?

2022-04-08 19:02 UTC, Shinigami92 requested changes

2022-04-08 19:02 UTC, Shinigami92 commented on src/commerce.ts
> +    return this.faker.random.arrayElement(this.faker.definitions.color.human);
You should call 
```suggestion
    return this.faker.color.human();
```

2022-04-08 19:10 UTC, ST-DDT commented on src/color.ts
> +   * Returns a RGB color in decimal format
How about merging rgbHex and rgbNumeric into just `rgb(options: { format: 'hex', 'number255', 'percentage' } )`?
(Not sure about naming it `'number255'`, maybe just `'number'` to work better with the other color formats?)

We would need multiple signatures to make most use of TS features though.

2022-04-08 19:28 UTC, Shinigami92 commented on src/color.ts
> +   * Returns a RGB color in decimal format
What about naming it `8bit`?

2022-04-08 19:33 UTC, ST-DDT commented on src/color.ts
> +   * Returns a RGB color in decimal format
The bit/byte representation is not exactly standardized. It can be binary, decimal or hex.

2022-04-08 20:21 UTC, harsohailB commented on src/color.ts
> +   * Returns a RGB color in decimal format
Should we split decimal into `int` and `float` though to support something like three.js as @Shinigami92 mentioned in the first comment? So format would be: `binary`, `int`, `float`, or `hex`

2022-04-08 21:29 UTC, harsohailB commented on src/color.ts
> +  private getPercentage(): number {
Created a percentage function in commerce module as I think it fits there. Used that in this color module.

2022-04-09 02:21 UTC, ST-DDT commented on src/commerce.ts
> +  percentage(percision: number): number {
This method should probably in our future `number` module.

2022-04-09 19:36 UTC, ST-DDT commented on src/color.ts
> +  return css;
Maybe return directly from with the case statements
and add a default case that throws for unsupported cases or uses rgb as default.

2022-04-09 19:36 UTC, ST-DDT commented on src/color.ts
> +   * faker.color.rgb({ format: 'decimal' }) // '[255, 255, 255]'
Does it return a string in this case? If not, remove the confusing single quotes.

2022-04-09 19:36 UTC, ST-DDT commented on src/color.ts
> +  colorSpace = colorSpace || 'rgb';
Maybe move the fallback to the signature?

2022-04-09 19:38 UTC, harsohailB commented on src/commerce.ts
> +  percentage(percision: number): number {
Is there a ticket for this where I can mention it?

2022-04-09 19:40 UTC, harsohailB commented on src/color.ts
> +  return css;
Done!

2022-04-09 19:42 UTC, harsohailB commented on src/color.ts
> +   * faker.color.rgb({ format: 'decimal' }) // '[255, 255, 255]'
Done!

2022-04-09 19:42 UTC, harsohailB commented on src/color.ts
> +  colorSpace = colorSpace || 'rgb';
I'm not quite understand what you mean here. Can you please elaborate?

2022-04-09 19:43 UTC, ST-DDT commented on src/commerce.ts
> +  percentage(percision: number): number {
https://github.com/faker-js/faker/discussions/805

2022-04-09 19:52 UTC, ST-DDT commented on src/color.ts
> +  colorSpace = colorSpace || 'rgb';
````ts
function toColorFormat(
  values: number[],
  format: 'decimal' | 'css' | 'binary',
  colorSpace: ColorSpace = 'rgb'
): string | number[] {
````

2022-04-09 19:56 UTC, harsohailB commented on src/color.ts
> +  colorSpace = colorSpace || 'rgb';
Oh yea, that would be much cleaner. Thanks for pointing that out! Done!

2022-04-10 05:33 UTC, pkuczynski commented on src/commerce.ts
> +  percentage(percision: number): number {
It really does not make a lot of sense to create a function which has almost exactly the same signature like already existing one. I can easily imagine that in not that long time someone will create a PR extending `percentage` with `min` and `max` options and then it will be identical as `float`.

If I would see `percentage` without looking at the documentation I would expect it generates something like `'25%‘`. And not a float value...

So I am against this new method. Let's keep things [stupid simple](https://en.wikipedia.org/wiki/KISS_principle)

2022-04-10 09:48 UTC, Shinigami92 commented on src/color.ts
> +type ColorSpace =
In this example, the color spaces are define much differently :thinking: 
https://www.w3.org/TR/css-color-4/#terminology

2022-04-10 17:04 UTC, harsohailB commented on src/color.ts
> +type ColorSpace =
If I understand it correctly now, is the `colorGamut()` function supported to be a `colorSpace()` generator and the CSS string generator should take in a `ColorGamut` type?

2022-04-10 17:17 UTC, Shinigami92 commented on src/color.ts
> +type ColorSpace =
> If I understand it correctly now, is the `colorGamut()` function supposed to be a `colorSpace()` generator and the CSS string generator should take in a `ColorGamut` type?

I think yes :thinking: 
But also it seems we need both, `colorGamut` (or maybe just `gamut()`, because we are already in the color module) and `colorSpace` (or maybe just `space`?)
`colorSpace` can return values that can be applies as the CSS value, so e.g. `display-p3` or `xyz`

A helpful video I can recommend it: https://www.youtube.com/watch?v=cGyLHxn16pE

2022-04-10 18:45 UTC, harsohailB commented on src/color.ts
> +type ColorSpace =
I think `gamut()` should return the values that can be applied as the CSS value as gamut is a [CSS media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut).

2022-04-10 18:47 UTC, Shinigami92 commented on src/color.ts
> +type ColorSpace =
@harsohailB Yes!

2022-04-10 18:56 UTC, harsohailB commented on src/color.ts
> +type Gamut = typeof gamut[number];
I am not sure if this is the best way to do this. If someone can advise, that would be great!

2022-04-10 18:56 UTC, harsohailB commented on src/color.ts
> +type ColorSpace =
Done in [0272c06](https://github.com/faker-js/faker/pull/801/commits/0272c06cb17fc7ef2a60387f7e554d7a94b28dd7)!

2022-04-10 18:57 UTC, harsohailB commented on src/color.ts
> +type ColorSpace =
Done in [0272c06](https://github.com/faker-js/faker/pull/801/commits/0272c06cb17fc7ef2a60387f7e554d7a94b28dd7)!

2022-04-10 19:08 UTC, Shinigami92 requested changes

2022-04-10 19:08 UTC, Shinigami92 commented on src/locales/en/color/gamut.ts
> +  'display-p3',
The [docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut.#syntax) says there are only these 3 values: 'srgb', 'p3' and 'rec2020'
From where are the others from?

2022-04-10 19:08 UTC, Shinigami92 commented on src/locales/en/color/space.ts
> +  'RGK',
I would assume that these are the values `'sRGB', 'display-p3', 'a98-rgb', 'prophoto-rgb', 'rec2020', 'xyz'` as the values described here https://drafts.csswg.org/css-color/#terminology (First param of `color`)

The current values of this file could be still shipped but under a different name :thinking: How about "space human"? like readable human colors are defined also?
Maybe `spaceTerms`?

2022-04-10 19:09 UTC, Shinigami92 commented on src/locales/en/color/gamut.ts
> +  'display-p3',
If you need the current values, they may need to be stored on a different extra place

2022-04-10 19:31 UTC, harsohailB commented on src/locales/en/color/space.ts
> +  'RGK',
I am confused because https://drafts.csswg.org/css-color/#terminology states the first param of `color` as color space but https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut states it as gamut...

2022-04-10 19:32 UTC, harsohailB commented on src/locales/en/color/gamut.ts
> +  'display-p3',
Check https://www.smashingmagazine.com/2021/11/guide-modern-css-colors/ for the additional gamuts supported by CSS.

2022-04-10 19:35 UTC, harsohailB commented on src/commerce.ts
> +  percentage(percision: number): number {
@pkuczynski You make some really good points here! @ST-DDT and @Shinigami92 what do you think about this? I am happy to revert to using `float` inline to keep it simpler.

2022-04-10 19:36 UTC, Shinigami92 commented on src/locales/en/color/space.ts
> +  'RGK',
> I am confused because [drafts.csswg.org/css-color/#terminology](https://drafts.csswg.org/css-color/#terminology) states the first param of `color` as color space but [developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut) states it as gamut...

Yes, I'm also confused by that :thinking:
But there is definitely a difference
The one is pointing out `p3` (I assume gamut) and the other `display-p3` (I assume space)

2022-04-10 19:39 UTC, Shinigami92 commented on src/locales/en/color/gamut.ts
> +  'display-p3',
Ah so I assume your actual defined values are the color "function"
But `cmyk` and `display-p3` are wrong for them

2022-04-10 19:43 UTC, harsohailB commented on src/locales/en/color/gamut.ts
> +  'display-p3',
Oh I see. I should probably not return `color(` with `display-p3`. How is CMYK wrong?

2022-04-10 19:45 UTC, harsohailB commented on src/locales/en/color/space.ts
> +  'RGK',
[Here](https://en.wikipedia.org/wiki/DCI-P3) it states the opposite :laughing: 

> **P3** is an [RGB **color space**](https://en.wikipedia.org/wiki/RGB_color_space). DCI-P3 (Digital Cinema Initiative) is used with digital theatrical motion picture distribution[[1]](https://en.wikipedia.org/wiki/DCI-P3#cite_note-Technicolor-1) ([DCDM](https://www.loc.gov/preservation/digital/formats/fdd/fdd000177.shtml)). **Display-P3** is a variant developed by [Apple Inc.](https://en.wikipedia.org/wiki/Apple_Inc.) for **wide-gamut displays**.

2022-04-10 19:46 UTC, Shinigami92 commented on src/locales/en/color/gamut.ts
> +  'display-p3',
Oh, seems like `cmyk` exists for PhotoShop :thinking: (https://www.mediaevent.de/css/color-cmyk.html)
But not sure if we should put this into here.

Also instead of `display-p3` you may want `color`
I just had a look into your description of this PR
![image](https://user-images.githubusercontent.com/7195563/162636940-7f74d15e-c024-4590-8657-a7cd633cae53.png)
And `display-p3` is the first parameter, not the function-name itself, that is `color` in this case.

2022-04-10 19:48 UTC, Shinigami92 commented on src/locales/en/color/gamut.ts
> +  'display-p3',
... https://www.w3schools.com/colors/colors_cmyk.asp :eyes: 
Why don't they have just consistent documentation at one place 😬

2022-04-10 19:54 UTC, harsohailB commented on src/locales/en/color/gamut.ts
> +  'display-p3',
The W3 is the source I used for CMYK. And I see what you mean by  `color` is needed for `display-p3`. So no changes needed?

2022-04-10 19:57 UTC, Shinigami92 commented on src/locales/en/color/gamut.ts
> +  'display-p3',
> The W3 is the source I used for CMYK. And I see what you mean by color is needed for display-p3. So no changes needed?

I assume we need to just replace `display-p3` with `color` as `display-p3` is the possible parameter and `color` is just a possible function like `rgba` or `hsla`
Then rename it file to `function` and add a `gamut` file with the 3 possible values

2022-04-10 19:59 UTC, Shinigami92 commented on src/locales/en/color/space.ts
> +  'RGK',
Oof... But I think we should stay close to CSS docs and not Wikipedia :thinking: Even if it is theoretically wrong :thinking:

2022-04-10 20:05 UTC, Shinigami92 commented on src/locales/en/color/space.ts
> +  'RGK',
![image](https://user-images.githubusercontent.com/7195563/162637583-1fc96fa4-ab12-4257-9edd-dba636da8eff.png)
These are color `space`s and the (so I call them) first parameter for the color function

---

![image](https://user-images.githubusercontent.com/7195563/162637659-b4175a0b-bf8f-4d51-819c-2dd3bca65863.png)
This is the color `gamut` (for media queries)

2022-04-10 20:08 UTC, Shinigami92 commented on src/locales/en/color/space.ts
> +  'RGK',
@harsohailB Please do not misunderstand me and accidentally throw away the current defined values, these should just be relocated into another file

2022-04-10 20:12 UTC, Shinigami92 commented on src/commerce.ts
> +  percentage(percision: number): number {
For now I think yes, using it just inline is okay for now

2022-04-10 20:14 UTC, harsohailB commented on src/locales/en/color/space.ts
> +  'RGK',
No worries! I really appreciate the clarifications you are making. I will try to take this in and hopefully get us closer in the next commit. Will re-request review from you once I make the new files for CSS functions vs spaces vs gamuts.

2022-04-10 20:27 UTC, Shinigami92 commented
@harsohailB From tomorrow on some of us in the team (also me) are in vacation, so I expect it will get very silent for the next days.
I'm back on next saturday.

2022-04-10 23:46 UTC, harsohailB commented on src/locales/en/color/space.ts
> +  'RGK',
Refactored the locales and some functions. Let me know what you think!

2022-04-11 08:31 UTC, Shinigami92 requested changes

2022-04-11 08:31 UTC, Shinigami92 commented on src/color.ts
> +      const buffer: ArrayBuffer = new ArrayBuffer(4);
Type can be inferred
```suggestion
      const buffer = new ArrayBuffer(4);
```

2022-04-11 08:31 UTC, Shinigami92 commented on src/color.ts
> + * @param space Color space to format CSS color function with. Defaults to `srgb`.
```suggestion
 * @param space Color space to format CSS color function with. Defaults to `sRGB`.
```

2022-04-11 08:31 UTC, Shinigami92 commented on src/color.ts
> + * @param space Color space to format CSS color function with. Defaults to `srgb`.
```suggestion
 * @param space Color space to format CSS color function with. Defaults to `sRGB`.
```

2022-04-11 08:31 UTC, Shinigami92 commented on src/color.ts
> +   * @param options options object.
```suggestion
   * @param options Options object.
```

2022-04-11 08:31 UTC, Shinigami92 commented on src/color.ts
> +   * @param options options object.
```suggestion
   * @param options Options object.
```

2022-04-11 08:31 UTC, Shinigami92 commented on src/color.ts
> +    );
```suggestion
    const color = Array.from({ length: 4 }, (() =>
      this.faker.commerce.percentage(0.01)
    ));
```

2022-04-11 08:31 UTC, Shinigami92 commented on src/color.ts
> +   * @param options options object.
```suggestion
   * @param options Options object.
```

2022-04-11 08:31 UTC, Shinigami92 commented on src/color.ts
> +   * Returns a HWB color.
```suggestion
   * Returns an HWB color.
```

2022-04-11 08:31 UTC, Shinigami92 commented on src/color.ts
> +   * @param options options object.
```suggestion
   * @param options Options object.
```

2022-04-11 08:31 UTC, Shinigami92 commented on src/color.ts
> +   * @param options options object.
```suggestion
   * @param options Options object.
```

2022-04-11 08:31 UTC, Shinigami92 commented on src/commerce.ts
> +   * @param percision Precision of the generated number. Defaults to `0.01`.
```suggestion
   * @param precision Precision of the generated number. Defaults to `0.01`.
```

2022-04-11 08:31 UTC, Shinigami92 commented on src/commerce.ts
> +   * with percision of two decimal place.
```suggestion
   * with precision of two decimal place.
```

2022-04-11 08:31 UTC, Shinigami92 commented on src/commerce.ts
> +  percentage(percision: number): number {
```suggestion
  percentage(precision: number = 0.01): number {
```

2022-04-11 08:31 UTC, Shinigami92 commented on src/commerce.ts
> +      precision: percision || 0.01,
```suggestion
      precision,
```

2022-04-11 17:27 UTC, harsohailB commented on src/commerce.ts
> +   * @param percision Precision of the generated number. Defaults to `0.01`.
Done!

2022-04-11 17:28 UTC, harsohailB commented on src/color.ts
> +function applyHexFormat(
Done!

2022-04-11 17:28 UTC, harsohailB commented on src/color.ts
> +    const isFloat: boolean = Number(value) === value && value % 1 !== 0;
Done!

2022-04-11 17:28 UTC, harsohailB commented on src/color.ts
> +      const buffer: ArrayBuffer = new ArrayBuffer(4);
Done!

2022-04-11 17:28 UTC, harsohailB commented on src/color.ts
> +  const percentages = values.map((value: number) => Math.round(value * 100));
Done!

2022-04-11 17:28 UTC, harsohailB commented on src/color.ts
> + * @param space Color space to format CSS color function with. Defaults to `srgb`.
Done!

2022-04-11 17:29 UTC, harsohailB commented on src/color.ts
> +   * @param options options object.
Done!

2022-04-11 17:29 UTC, harsohailB commented on src/color.ts
> +   * @param options options object.
Done!

2022-04-11 17:29 UTC, harsohailB commented on src/color.ts
> +   * Returns a HSL color.
Done!

2022-04-11 17:29 UTC, harsohailB commented on src/color.ts
> +   * Returns a HWB color.
Done!

2022-04-11 17:29 UTC, harsohailB commented on src/color.ts
> +   * @param options options object.
Done!

2022-04-11 17:29 UTC, harsohailB commented on src/color.ts
> +   * @param options options object.
Done!

2022-04-11 17:29 UTC, harsohailB commented on src/color.ts
> +   * Returns a LCH color. Even though upper bound of
Done!

2022-04-11 17:29 UTC, harsohailB commented on src/color.ts
> +   * @param options options object.
Done!

2022-04-11 17:29 UTC, harsohailB commented on src/color.ts
> +   * @param options options object.
Done!

2022-04-11 18:35 UTC, harsohailB commented on src/color.ts
> +  const percentages = values.map((value: number) => Math.round(value * 100));
Done!

2022-04-11 18:41 UTC, harsohailB commented on src/color.ts
> +    return toColorFormat(color, options.format, cssFunction);
Done!

2022-04-11 18:43 UTC, harsohailB commented on src/color.ts
> +    const color = [0, 0, 0].map(() => this.faker.commerce.percentage(0.0001));
Done!

2022-04-11 18:47 UTC, harsohailB commented on src/color.ts
> +    );
Done!

2022-04-11 18:47 UTC, harsohailB commented on src/commerce.ts
> +   * with percision of two decimal place.
Change no longer required as percentage generator is commerce is now deleted. Refer to [this](https://github.com/faker-js/faker/pull/801#discussion_r846716417).

2022-04-11 18:48 UTC, harsohailB commented on src/commerce.ts
> +  percentage(percision: number): number {
Change no longer required as percentage generator is commerce is now deleted. Refer to [this](https://github.com/faker-js/faker/pull/801#discussion_r846716417).

2022-04-11 18:48 UTC, harsohailB commented on src/commerce.ts
> +      precision: percision || 0.01,
Change no longer required as percentage generator is commerce is now deleted. Refer to [this](https://github.com/faker-js/faker/pull/801#discussion_r846716417).

2022-04-11 18:48 UTC, harsohailB commented on src/commerce.ts
> +  percentage(percision: number): number {
Changed to inline and removed from commerce.

2022-04-16 11:05 UTC, Shinigami92 requested changes

2022-04-16 11:05 UTC, Shinigami92 commented on src/color.ts
> +      return toCSS(values, 'rgb');
On the first look that looks like an infinit loop (it's not)
But I would rewrite it to e.g.

```ts
    case 'rgb':
    default:
      return `rgb(${values[0]}, ${values[1]}, ${values[2]})`;
```
And remove the first case.

2022-04-16 11:05 UTC, Shinigami92 commented on src/color.ts
> +  return result;
```suggestion
  switch (format) {
    case 'css':
      return toCSS(values, cssFunction, space);
    case 'binary':
      return toBinary(values);
    default:
      return values;
  }
```

2022-04-16 12:05 UTC, pkuczynski commented on src/color.ts
> +type CSSSpace = typeof cssSpaces[number];
Agree 100x!

2022-04-16 12:06 UTC, pkuczynski commented on src/color.ts
> +   * faker.color.rgb({ prefix: '#', case: 'lower' }) // '#ffffff'
Agree...

2022-04-16 23:45 UTC, harsohailB commented on src/color.ts
> +      return toCSS(values, 'rgb');
Done!

2022-04-16 23:45 UTC, harsohailB commented on src/color.ts
> +    const isFloat = value === value && value % 1 !== 0;
First value should be `Number(value)`. Changed!

2022-04-16 23:48 UTC, harsohailB commented on src/color.ts
> +   * faker.color.rgb({ format: 'decimal', includeAlpha: true }) // [255, 255, 255, 0.4]
Done!

2022-04-16 23:49 UTC, harsohailB commented on src/color.ts
> +   * faker.color.rgb({ prefix: '#', case: 'lower' }) // '#ffffff'
I agree. I will make this change.

2022-04-17 00:11 UTC, harsohailB commented on src/color.ts
> +type CSSSpace = typeof cssSpaces[number];
Done!

2022-04-17 00:46 UTC, harsohailB commented on src/definitions/color.ts
> +  cssSpaces: readonly string[];
This should not be an issue anymore as moved the css functions and spaces into `color.ts`

2022-04-17 01:07 UTC, harsohailB commented on src/color.ts
> +   * faker.color.rgb({ prefix: '#', case: 'lower' }) // '#ffffff'
Done!

2022-04-17 01:27 UTC, harsohailB commented on src/color.ts
> +  }): string | number[] {
Added in [11fdcc8](https://github.com/faker-js/faker/pull/801/commits/11fdcc87847eb404e3a0c6cbc464cc8bd8f0a822). Let me know if this is correct!

2022-04-17 12:03 UTC, Shinigami92 requested changes
I'm not sure about the new naming `typeCase` :thinking: 
I think we already have the option `case` for something else, but I didn't checked that yet

2022-04-17 17:05 UTC, harsohailB commented
> I'm not sure about the new naming `typeCase` thinking I think we already have the option `case` for something else, but I didn't checked that yet

Option case was giving parsing issues such as when I was trying to `const { case = 'lower' } = options` it wanted to treat case as a case in switch statement. Therefore, I renamed to `typeCase`

2022-04-17 17:07 UTC, harsohailB commented on src/color.ts
> +    const isFloat = Number(value) === value && value % 1 !== 0;
Yea I guess if we are passing in a `number[]` we do not need that first condition as it'll always be true. Will take that out.

2022-04-17 17:08 UTC, harsohailB commented on src/color.ts
> +export const cssSpaces = [
Done!

2022-04-17 17:08 UTC, harsohailB commented on src/color.ts
> +    const isFloat = Number(value) === value && value % 1 !== 0;
Done!

2022-04-17 17:26 UTC, Shinigami92 commented
> Option case was giving parsing issues such as when I was trying to `const { case = 'lower' } = options` it wanted to treat case as a case in switch statement. Therefore, I renamed to `typeCase`

Yes you are right! I checked the other places and they use `upcase: boolean` (we don't want that here)
We could use `casing`

2022-04-17 17:26 UTC, Shinigami92 commented
> Option case was giving parsing issues such as when I was trying to `const { case = 'lower' } = options` it wanted to treat case as a case in switch statement. Therefore, I renamed to `typeCase`

Yes you are right! I checked the other places and they use `upcase: boolean` (we don't want that here)
We could use `casing`

2022-04-18 00:46 UTC, harsohailB commented
> > Option case was giving parsing issues such as when I was trying to `const { case = 'lower' } = options` it wanted to treat case as a case in switch statement. Therefore, I renamed to `typeCase`
> 
> Yes you are right! I checked the other places and they use `upcase: boolean` (we don't want that here) We could use `casing`

Done!

2022-04-18 07:21 UTC, Shinigami92 submitted a review, later dismissed

2022-05-04 06:16 UTC, Shinigami92 commented
Hi @harsohailB 👋
Could you update this PR? We moved modules into `src/modules/<modulename>/index.ts`

2022-05-06 17:16 UTC, harsohailB commented
> Hi @harsohailB 👋 Could you update this PR? We moved modules into `src/modules/<modulename>/index.ts`

Will do!

2022-05-09 20:23 UTC, harsohailB commented
```
test/scripts/apidoc/examplesAndDeprecations.spec.ts > examples and deprecations > Color > cmyk
     → Color.cmyk to have examples: expected '' not to be '' // Object.is equality
```

Receiving these failures from the tests. Not sure why this is happening as there are examples for each method in the color module. If someone could point me in the right direction with this, that would be much appreciated!

2022-05-12 13:12 UTC, Shinigami92 commented
> ```
> test/scripts/apidoc/examplesAndDeprecations.spec.ts > examples and deprecations > Color > cmyk
>      → Color.cmyk to have examples: expected '' not to be '' // Object.is equality
> ```
> 
> Receiving these failures from the tests. Not sure why this is happening as there are examples for each method in the color module. If someone could point me in the right direction with this, that would be much appreciated!

Ah! @ST-DDT's test is working here, but the message is maybe a bit cryptic
It says that the JSDoc for cmyk function is missing `@example`
We are now forcefully requiring these as we want to use these code example to auto-call them in tests later on. @ST-DDT can tell you more about that if needed.
All you need to know is: add JSDoc with `@example` and orientate yourself on other already existing code 🙂

2022-05-12 15:40 UTC, harsohailB commented on src/modules/color/index.ts
> +   * @example
@Shinigami92 But all the color module function have the @example JSDoc in them already? 🤔

2022-05-12 15:51 UTC, Shinigami92 commented on src/modules/color/index.ts
> +   * @example
@ST-DDT 👀

2022-05-12 22:52 UTC, ST-DDT requested changes

2022-05-12 22:52 UTC, ST-DDT commented on src/locales/ar/commerce/index.ts
> +const commerce: Partial<CommerceDefinitions> = {
AFAICT you have to edit https://github.com/faker-js/faker/blob/main/scripts/generateLocales.ts#L50 and run `pnpm run generate:locales` again.

2022-05-12 22:52 UTC, ST-DDT commented on src/modules/color/index.ts
> +   * @example
We use the docs from the last api signature to generate the docs.
https://github.com/faker-js/faker/blob/6219c9414953021be50cb794b6658f23f2f65f0a/scripts/apidoc/moduleMethods.ts#L54
(You might have to duplicate the impl signature, because typedoc only reads api signatures.)
This is required because otherwise we would show `cmyk()` as the signature in the docs and typedoc removes tags without target. I haven't found a better way for that yet.

You can see this very easily when running `pnpm run docs:dev`:
![grafik](https://user-images.githubusercontent.com/1579362/168179587-f206aa6f-33fd-4d07-ad40-a56a8aa5c6cb.png)

Example:
https://github.com/faker-js/faker/blob/c115056e04d1e42f97c8d77daed3d9056c375953/src/random.ts#L174-L205

2022-05-12 22:58 UTC, ST-DDT commented on src/modules/color/index.ts
> +   * @param options.format Format of generated CMYK color. Defaults to `decimal`.
```suggestion
   * @param options.format Format of generated CMYK color. Defaults to `'decimal'`.
```

2022-05-18 17:45 UTC, harsohailB commented on src/modules/color/index.ts
> +   * @param options.format Format of generated CMYK color. Defaults to `decimal`.
Done!

2022-05-18 17:47 UTC, harsohailB commented on src/locales/ar/commerce/index.ts
> +const commerce: Partial<CommerceDefinitions> = {
Done!

2022-05-18 17:50 UTC, Shinigami92 commented on src/modules/color/index.ts
> +  }): number[];
I know it's odd, but every single signature needs a JSDoc
the last one will be used for TSDoc but the others are used by e.g. VSCode
You can check that by manually trying it out

2022-05-19 17:04 UTC, Shinigami92 commented
@harsohailB I will jump into this PR and fix everything until it's green

2022-05-19 17:37 UTC, harsohailB commented
> @harsohailB I will jump into this PR and fix everything until it's green

Thank you! Sorry been a little busy with school and work. I will try to contribute where ever I can still.

2022-05-21 01:58 UTC, harsohailB commented on src/modules/color/index.ts
> +   * @example
The docs issue is now resolved!

2022-05-21 14:05 UTC, Shinigami92 submitted a review, later dismissed

2022-05-21 15:27 UTC, ST-DDT requested changes
Please copy the impl signature so it will be picked up as the last api signature.
AFAICT you don't have to add the jsdocs to the impl signature.

2022-05-21 15:27 UTC, ST-DDT commented on src/modules/color/index.ts
> +  }): string | number[] {
This needs to be duplicated as api signature to be picked up by typedoc.

2022-05-21 15:27 UTC, ST-DDT commented on src/modules/color/index.ts
> +  }
Same here

2022-05-21 15:27 UTC, ST-DDT commented on src/modules/color/index.ts
> +  }): string | number[] {
And here

2022-05-21 15:27 UTC, ST-DDT commented on src/modules/color/index.ts
> +  hwb(options?: { format?: ColorFormat }): string | number[] {
And here

2022-05-21 15:27 UTC, ST-DDT commented on src/modules/color/index.ts
> +  lab(options?: { format?: ColorFormat }): string | number[] {
And here

2022-05-21 15:27 UTC, ST-DDT commented on src/modules/color/index.ts
> +  lch(options?: { format?: ColorFormat }): string | number[] {
And here

2022-05-21 15:27 UTC, ST-DDT commented on src/modules/color/index.ts
> +  }): string | number[] {
And here

2022-05-21 18:13 UTC, Shinigami92 submitted a review, later dismissed

2022-05-21 21:07 UTC, ST-DDT requested changes

2022-05-21 21:07 UTC, ST-DDT commented on src/modules/color/index.ts
> +   * @param options.casing Letter type case of the generated hex color. Only applied when 'hex' format is used. Defaults to `mixed`.
```suggestion
   * @param options.casing Letter type case of the generated hex color. Only applied when `'hex'` format is used. Defaults to `'mixed'`.
```

2022-05-21 21:07 UTC, ST-DDT commented on src/modules/color/index.ts
> +   * @param options.format Format of generated RGB color. Defaults to `hex`.
```suggestion
   * @param options.format Format of generated RGB color. Defaults to `'hex'`.
```

2022-05-21 21:07 UTC, ST-DDT commented on src/modules/color/index.ts
> + * @param options.prefix Prefix of the generated hex color. Defaults to `0x`.
```suggestion
 * @param options.prefix Prefix of the generated hex color. Defaults to `'0x'`.
```

2022-05-21 21:07 UTC, ST-DDT commented on src/modules/color/index.ts
> + * @param options.casing Letter type case of the generated hex color. Defaults to `mixed`.
```suggestion
 * @param options.casing Letter type case of the generated hex color. Defaults to `'mixed'`.
```

2022-05-21 21:13 UTC, ST-DDT commented on src/modules/color/index.ts
> +   * @param options.casing Letter type case of the generated hex color. Only applied when `'hex'` format is used. Defaults to `'mixed'`.
These will never be used in this case, so should they still be included in the signature/jsdocs here?

2022-05-21 21:13 UTC, ST-DDT commented on src/modules/color/index.ts
> +  rgb(options?: {
AFAIK implementation signatures don't need jsdocs.

2022-05-22 11:00 UTC, Shinigami92 commented on src/modules/color/index.ts
> +   * @param options.casing Letter type case of the generated hex color. Only applied when `'hex'` format is used. Defaults to `'mixed'`.
@ST-DDT please check if my update was what you had thought

2022-05-22 11:26 UTC, Shinigami92 approved these changes

2022-05-22 13:20 UTC, ST-DDT approved these changes

2022-05-22 18:16 UTC, xDivisionByZerox approved these changes

2022-05-22 19:14 UTC, merged