refactor: improve unique
faker-js/faker pull request #810
Opened 2022-04-08 11:07 UTC by Shinigami92

2022-04-08 15:38 UTC, ST-DDT requested changes

2022-04-08 15:38 UTC, ST-DDT commented on src/unique.ts
> +      startTime = new Date().getTime(),
AFAICT: This value will no longer be overwritten. Remove the line here and add it below

2022-04-08 15:38 UTC, ST-DDT commented on src/unique.ts
> +   * @param options.startTime The time this execution stared. This will be ignored/overwritten. Defaults to `new Date().getTime()`.
Since the value will be overwritten, the default does not matter. In fact you could change it to "this parameter does nothing".

2022-04-08 15:38 UTC, ST-DDT commented on src/utils/unique.ts
> + * Uniqueness for entire faker instance.
This is wrong. It is global, and not bound to a single faker instance.

2022-04-08 15:38 UTC, ST-DDT commented on src/utils/unique.ts
> + * This means that faker should *never* return duplicate values across all API methods when using `Faker.unique` without passing `options.store`.
There is no `options.store` yet.

2022-04-08 16:32 UTC, ST-DDT approved these changes

2022-04-09 18:09 UTC, import-brain approved these changes

2022-04-10 10:03 UTC, merged