feat: allow banned as string
faker-js/faker pull request #819
Opened 2022-04-08 19:25 UTC by Shinigami92

Following PRs need to be merged before this PR:

- #790
- #797

2022-04-24 22:07 UTC, import-brain approved these changes

2022-04-24 22:08 UTC, ST-DDT requested changes

2022-04-24 22:08 UTC, ST-DDT commented on src/random.ts
> +    // TODO @Shinigami92 2022-01-11: A default empty array gets assigned above, we should check the length against 0 or not here
There is no need for that IMO.

2022-04-24 22:08 UTC, ST-DDT commented on src/random.ts
> +      }
Please make all 3? instances consistent where and how you do this check.

2022-04-25 08:10 UTC, ST-DDT submitted a review, later dismissed

2022-04-25 10:11 UTC, xDivisionByZerox commented
What would be the use case of providing a string instead of an array? This would allow me to provide an option like `bannedChars: 'aaaaaaaaaaaaaaaaaaaaaaaaaaA'` where I would expect only this combination of charters to be baned.

2022-04-25 10:29 UTC, Shinigami92 commented
> What would be the use case of providing a string instead of an array? This would allow me to provide an option like `bannedChars: 'aaaaaaaaaaaaaaaaaaaaaaaaaaA'` where I would expect only this combination of charters to be baned.

Yes exactly, it's the same as `bannedChars: 'aaaaaaaaaaaaaaaaaaaaaaaaaaA'.split('')`, just a better UX

2022-04-25 12:39 UTC, Shinigami92 commented
@xDivisionByZerox Do I need to update the docs? Or maybe ask @pkuczynski what the initial thought was by his feature request.

2022-04-25 13:24 UTC, ST-DDT commented
IMO having a string is a simplification over the array (you have to write less). Having an object or indizies would require more writing/reduce readability.

I would adjust the jsdocs though (param and example).

2022-04-25 14:26 UTC, Shinigami92 commented
First I would love to let @pkuczynski come to word :slightly_smiling_face: 
Then I can work further on this PR

2022-05-04 21:29 UTC, pkuczynski commented
@Shinigami92 can you remind me when did I request this? :) I tried to click around for a while and dust off my memory, but don't recon this request? :(

2022-05-04 21:31 UTC, pkuczynski commented
And btw. with `bannedChars` option I would expect this chars will not appear in the result string. Chars, not whole string. So in the example from @xDivisionByZerox 

```
// this is fine
const result = faker.datatype.string({
    bannedChars: 'abcd',
    count: 4,
});
console.log(result); // abcz
```

I would expect that result would not contain neither `a`, `b`, `c` or `d`.

2022-05-05 08:11 UTC, Shinigami92 commented
> @Shinigami92 can you remind me when did I request this? :) I tried to click around for a while and dust off my memory, but don't recon this request? :(

https://github.com/faker-js/faker/pull/797#discussion_r846391378

2022-05-07 15:17 UTC, ST-DDT requested changes
This fails the following tests:

````ts
it('should be able to ban some characters via string', () => {
  const actual = faker.random.alpha({
    count: 5,
    bannedChars: [
      'B',
      'C',
      'D',
      'E',
      'F',
      'G',
      'H',
      'I',
      'J',
      'K',
      'L',
      'M',
      'N',
      'O',
      'P',
      'Q',
      'R',
      'S',
      'T',
      'U',
      'V',
      'W',
      'X',
      'Y',
      'Z',
    ],
    upcase: true,
  });

  expect(actual).toHaveLength(5);
  expect(actual).toMatch(/^A{5}$/);
});
````

I know this isn't directly caused by this PR, but this PR explicitly lists uppercase characters as allowed (to be banned).

2022-05-07 15:59 UTC, Shinigami92 commented
@ST-DDT You mean we need to add them to line 248 to 275?

2022-05-07 16:04 UTC, ST-DDT commented
I would like have a `case: upper|lower|mixed` parameter (mixed being the default).

2022-05-07 16:09 UTC, Shinigami92 commented
> I would like have a `case: upper|lower|mixed` parameter (mixed being the default).

okay, then this will be definitely another PR/issue

2022-05-07 16:14 UTC, ST-DDT commented
> > I would like have a `case: upper|lower|mixed` parameter (mixed being the default).
> 
> okay, then this will be definitely another PR/issue

I consider, this "fixed", if you remove the uppercase characters from the input (for now).

2022-05-07 16:18 UTC, ST-DDT commented
(and edit the jsdocs accordingly)

2022-05-07 16:24 UTC, ST-DDT commented
Could you add a hint to the jsdocs regarding that behavior?

2022-05-18 17:18 UTC, Shinigami92 commented
Await merge of #955

2022-05-18 18:12 UTC, pkuczynski commented
> > @Shinigami92 can you remind me when did I request this? :) I tried to click around for a while and dust off my memory, but don't recon this request? :(
> 
> [#797 (comment)](https://github.com/faker-js/faker/pull/797#discussion_r846391378)

Ah yes, sorry! :) Indeed I requested this :) Then I think I had only this comment https://github.com/faker-js/faker/pull/819#issuecomment-1117956389 which seems to be addressed?

2022-05-18 18:13 UTC, pkuczynski approved these changes

2022-05-21 20:33 UTC, ST-DDT approved these changes

2022-05-22 08:35 UTC, pkuczynski approved these changes

2022-05-22 10:49 UTC, merged