docs: fix lost description texts
faker-js/faker pull request #836
Opened 2022-04-12 20:09 UTC by ST-DDT

Fixes #794

Here a few examples of the changes:

<details>
<summary><strong>Old1 (Click to exand)</strong></summary>

![grafik](https://user-images.githubusercontent.com/1579362/163043672-e8bc0ac3-f602-49f7-8e9a-818918a8282d.png)

</details>

<details>
<summary><strong>New1 (Click to exand)</strong></summary>

![grafik](https://user-images.githubusercontent.com/1579362/163043739-d82d8c87-6608-4665-94a3-dbc553cc4316.png)

</details>

<details>

<summary><strong>Old2 (Click to exand)</strong></summary>

![grafik](https://user-images.githubusercontent.com/1579362/163044382-3ad79f23-e903-4b63-9227-74d4b6d5d73e.png)

</details>

<details>
<summary><strong>New2 (Click to exand)</strong></summary>

![grafik](https://user-images.githubusercontent.com/1579362/163044562-cb3ff433-4cf1-4ad5-b5e3-80a20a8794ab.png)

</details>

<details>
<summary><strong>Old3 (Click to exand)</strong></summary>

![grafik](https://user-images.githubusercontent.com/1579362/163043837-df95c27f-73cf-4596-9b78-7cf313987b1a.png)

</details>

<details>
<summary><strong>New3 (Click to exand)</strong></summary>

![grafik](https://user-images.githubusercontent.com/1579362/163043902-a23e9c9f-87ea-4095-aa7c-a36a6bad2eff.png)

</details>

I'm not sure about the CSS changes. IIRC we discussed at some point to not use it, but I don't remember why anymore.
If we don't display it as list items, then we have to remove the padding from the list though.

2022-04-12 22:16 UTC, import-brain approved these changes, later dismissed

2022-04-12 22:22 UTC, pkuczynski submitted a review, later dismissed

2022-04-16 11:18 UTC, Shinigami92 commented on scripts/apidoc/signature.ts
> +    throw new FakerError('Found unsafe html');
This is a script, not faker source code, so should we **not** use `FakerError` here?

2022-04-19 18:19 UTC, Shinigami92 requested changes

2022-04-19 18:19 UTC, Shinigami92 commented on scripts/apidoc/signature.ts
> +import { FakerError } from '../../src/errors/faker-error';
Please use FakerError only in `src/` (or `test/`) but not in `scripts/`

2022-04-19 20:17 UTC, Shinigami92 approved these changes

2022-04-19 22:09 UTC, import-brain approved these changes

2022-04-20 06:22 UTC, merged