test: introduce expectation store
faker-js/faker pull request #838
Opened 2022-04-14 17:16 UTC by ST-DDT

This PR introduces expectation stores to simplfy our seeded tests.
There are probably a lot of ways in which this can be improved,
but for now I would just like to get feedback on the concept itself.
Should we do something like this or should we scrap this idea?

Current benefits of this approach:

- Simplified tests
- Easier to add/update expected values

Potential later improvements:

- Move the seeded tests to an `expected.ts`
- Ensure that all methods in a module have a test
- Simplify tests with args
  e.g. ` .describe('direction', (f) => f.it(...).it(...).it(...))`
  -> ` .itWithParams('direction', ['normal'], ['full', false], ['abbr', true] )`
- Simplify the trivial tests to just their id
  e.g. ` .it('cityPrefix', (faker) => faker.address.cityPrefix())`
  -> ` .it('cityPrefix')`
- Generate all trivial tests
  e.g. ` .itRemaining()`
- Ensure the test ids are unique
- ...

Note: The `actual.json` file won't be committed to repo.

2022-04-15 07:18 UTC, Shinigami92 commented
Could we try snapshots first?

2022-04-15 10:53 UTC, pkuczynski commented
I must say, I am not the biggest fan of those tests, as I dont feel they really test anything. Whenever they fail, I just simply replace the value with the expected one and that's it. So what's the point? I much more prefer functional tests...

2022-04-15 11:16 UTC, ST-DDT commented
> I must say, I am not the biggest fan of those tests, as I dont feel they really test anything. Whenever they fail, I just simply replace the value with the expected one and that's it. So what's the point? I much more prefer functional tests...

The most of the functional tests are pretty vague.
Our library generates random data so there is hardly anything we can test precisely.
Most tests I have written so far anywhere consist of mostly equality checks, the seeded test are our only way to do that.
The seeded test exist to assist us, and notice changes/side effects.
E.g. if arrayElement would always return the first element, the random tests would still pass, but the seeded would fail. They won't tell you why, but at least they tell you to have a look.
Asside from notifying us, they also give us the chance to look at the returned/expected values.
Does it look like an address or phone number? Are there any unresolved parts in there?

2022-04-30 20:16 UTC, ST-DDT commented
I updated this PR to use test snapshots instead of implementing that myself.
It would be nice, if you could give me some input regarding the test setup and whether it is worth continuing (using the seededTests factory).

I'm not really happy with the test snapshot file format, but I guess it's better then using our own proprietary format.

The PR's changes to the tests are probably reviewed best on a side by side view.
The changes to the snapshot file are only caused by the changed names (to help with readability of the tests).

2022-06-18 17:43 UTC, ST-DDT commented
@Shinigami92 Why is the type check failing?

2022-06-19 20:33 UTC, ST-DDT commented
Since the new factory explicitly forces tests to be created if a method has parameters, there are some new tests.

2022-06-22 22:39 UTC, ST-DDT commented
All test converted. ~400/3 new ones added.

2022-06-23 13:37 UTC, Shinigami92 commented on test/support/seededRuns.ts
> +   * Runs the instructions for an vite `it` block.
```suggestion
   * Runs the instructions for a vitest `it` block.
```

2022-06-23 13:37 UTC, Shinigami92 commented on test/support/seededRuns.ts
> + * You may add custom vite `it` and `describe` blocks both on a module and method level,
```suggestion
 * You may add custom vitest `it` and `describe` blocks both on a module and method level,
```

2022-06-23 13:46 UTC, Shinigami92 requested changes

2022-06-23 13:46 UTC, Shinigami92 commented on test/address.spec.ts
> +    });
*nit-pick*: Is this prettier formatting? Or can we add a newline before `.desc...`?
Otherwise, could we use `t.desc...` instead to force a linebreak?

2022-06-23 13:46 UTC, Shinigami92 commented on test/datatype.spec.ts
> +      // TODO: Migrate?
OPEN TODO (with no responsible), need to be solved before merge

2022-06-23 14:31 UTC, xDivisionByZerox commented
I really have to say that I'm with @pkuczynski here. Even after the [explanation](https://github.com/faker-js/faker/pull/838#issuecomment-1100046325) I don't see how this test (the current one as well) will help us in any way.

> Most of the functional (random) tests are pretty vague and have flakey test coverage at best.

So why spend time implementing other vague tests that don really test anything. Creating solid tests that check for logical flaws is much better than 100% coverage.

> Our library generates random data so there is hardly anything we can test precisely.

Most of our functions just return a random member of the locales definitions. I don't see how we can't test this. And if we do something other than that, there you have the thing you need to test.

> Most tests I have written so far anywhere consist of mostly contains or regex checks, the seeded test are our only way to do equalitiy tests.

How is a test that consists of "Oh the current value ain't correct, lemme override it. Nice now it works." better than a RegExp check? I truly don't understand this, If a case is too complex for logical checks a RegExp should be fine. That said, it should be the last option to choose as we have written in our intern coding guidelines.

> The seeded test exist to assist us, and notice changes/side effects.

I understand this and am partially on your side for this. But this seems more like an e2e test case for me. A unit test should not be affected by any side effects since the dependency in use should be mocked in that case (what we don't do at all).

 > E.g. if arrayElement would always return the first element, the random tests would still pass, but the seeded would fail. They won't tell you why, but at least they tell you to have a look.

Why would a seeded test catch that? The example implies that the current implementation of a function is changed, otherwise, it would just generate a snapshot with the first element from the array as expectation. In that case (implementation is changed) the seeded test would fail anyway since it's very likely that the return value differs from the original implementation. I think that's what you wanted to say with "They won't tell you why, [...]", but I think that is a very weak point since any of these cases can be implemented by a concrete, random test (that checks for logic errors) instead of a seeded, snapshot test.

> Asside from notifying us, they also give us the chance to look at the returned/expected values.
Does it look like an address or phone number? Are there any unresolved parts in there?

I mean, yes, obviously. But is this the point of the unit test here? If I take the claim from before that most values are checked against RegExp, I can be very sure what my final result will look like as well.

> They are not intended to be just replaced without a thought.

If they are, I think this is very poorly executed. No one will have a deep look into a completely changed snapshot file, since I expect this things to pass against the current test suites.

2022-07-20 09:35 UTC, Shinigami92 submitted a review, later dismissed

2022-07-20 09:40 UTC, ST-DDT commented
The codecov/patch think is still failing (because I only add types to src), but this is ready to review.

2022-07-21 10:27 UTC, Shinigami92 approved these changes

2022-07-22 11:03 UTC, Shinigami92 approved these changes

2022-07-22 12:41 UTC, prisis approved these changes

2022-07-22 13:40 UTC, merged