docs: fix mersenne rand mix max confusion
faker-js/faker pull request #839
Opened 2022-04-15 17:32 UTC by gregoriomario

although mersenne automatically swap the value if min is bigger than max, but it's a good practice to clear out the confusion.

Fix #775

2022-04-15 20:39 UTC, import-brain requested changes

2022-04-15 20:39 UTC, import-brain commented on src/mersenne.ts
> +   * Generates a random number between `[max, min)`.
```suggestion
   * Generates a random number between `[min, max)`.
```
I think this should be changed back to what it was before (as seen in the suggestion block). The original description said that the function generates a number with an inclusive lower bound of ```min``` and an exclusive upper bound of ```max```, so this change will change the meaning of the JSDoc. Also, we should probably discuss putting a "max is first param" text in the JSDoc, but I'm not sure what format that would take.

2022-04-16 01:10 UTC, gregoriomario commented on src/mersenne.ts
> +   * Generates a random number between `[max, min)`.
I've been thinking about this too, which one should we change to clear out the confusion. Is it the docs that's inconsistent with the implemenetation of the param, or is it the param which might be better if we put min first instead of max. 

Maybe it's better to fix the param and keep the docs as it is before, but I'm not sure about this. Wdyt? 🤔

2022-04-16 01:50 UTC, import-brain commented on src/mersenne.ts
> +   * Generates a random number between `[max, min)`.
I think fixing the param itself would be a breaking API change, so we should just change the doc. @Shinigami92 @ST-DDT @pkuczynski What do you think?

2022-04-16 06:21 UTC, pkuczynski commented on src/mersenne.ts
> +   * Generates a random number between `[max, min)`.
Yes, this would be a breaking change so quite problematic...

2022-04-16 08:45 UTC, ST-DDT commented on src/mersenne.ts
> +   * Generates a random number between `[max, min)`.
For now, please only the jsdocs please.

2022-04-16 11:26 UTC, Shinigami92 reviewed
I assume it was implemented with max as first param, so that a user can use it with `faker.mersenne.rand(6)` so without a min argument and it just has a default min = 0

2022-04-16 11:26 UTC, Shinigami92 commented on src/mersenne.ts
> +   * faker.mersenne.rand(1000, 500) // 578
Seems the "example" not wrong, should we just add another line?

2022-04-16 11:26 UTC, Shinigami92 commented on src/mersenne.ts
> +   * Generates a random number between `[max, min)`.
Please re-check if the math symbols are correct (in-/ex-clusive)

2022-05-23 07:05 UTC, Shinigami92 commented on src/mersenne.ts
> +   * faker.mersenne.rand(1000, 500) // 578
I take somewhat back my statement

max is in first place so it can potentially used without providing manually a min argument
I personally don't like that kind of parameter usage and would like to call it with options instead of two params, but that is not related to this PR 🤷

2022-05-23 07:05 UTC, Shinigami92 approved these changes

2022-05-23 07:07 UTC, Shinigami92 requested changes

2022-05-23 07:07 UTC, Shinigami92 commented on src/mersenne.ts
>     * @param min The minimum number. Defaults to `32768`.
The default values are also wrong here 🤔 are they?

2022-05-23 17:48 UTC, Shinigami92 approved these changes

2022-05-23 17:48 UTC, ST-DDT approved these changes

2022-05-23 17:57 UTC, import-brain approved these changes

2022-05-23 17:58 UTC, xDivisionByZerox approved these changes

2022-05-23 18:01 UTC, merged