fix: access initial seed
faker-js/faker pull request #853
Opened 2022-04-20 14:35 UTC by Shinigami92

Via #851 we found out that it is not possible to access the initial seed ⚠️ 
This is a huge bug in my opinion as that way it's not possible to rerun a script with that seed

2022-04-20 15:36 UTC, ST-DDT commented
@Shinigami92 have agreed to not agree on whether the initialSeed should be accessible.
I don't think it shouldn't be because of the unknown n iterations on the seed value between setting it and using it.
I will abstain from further comments/actions on this PR. And will let the remaining team decide.

2022-04-20 15:55 UTC, pkuczynski commented on src/faker.ts
> +  public get initialSeed(): number | number[] {
Why would we shift away from `seedValue`?

2022-04-20 15:58 UTC, pkuczynski requested changes

2022-04-20 17:00 UTC, Shinigami92 commented on src/faker.ts
> +  public get initialSeed(): number | number[] {
> I would rather expect to be able to do something like:
> 
> ```
> const faker = new Faker({seed: 100})
> console.log(faker.seed); // 100
> faker.seed = 12
> console.log(faker.seed); // 12
> ```
> 
> This should be achievable with getters and setters, even if it would be a breaking change...

That is exactly what I would like to do, but it's only possible with a breaking change
I will do that in v7

2022-04-20 17:06 UTC, pkuczynski commented on src/faker.ts
> +  public get initialSeed(): number | number[] {
What's the value of bringing new prop `initialSeed` now and deprecating `seedValue`? Wouldn't it be better to make `seedValue` read only, so most of the people do not need to change their code?

2022-04-20 17:06 UTC, pkuczynski commented on src/faker.ts
> +  public get initialSeed(): number | number[] {
> I will do that in v7

Shall we create ticket for it?

2022-04-20 17:31 UTC, Shinigami92 commented on src/faker.ts
> +  public get initialSeed(): number | number[] {
> I would rather expect to be able to do something like:
> 
> ```
> const faker = new Faker({seed: 100})
> console.log(faker.seed); // 100
> faker.seed = 12
> console.log(faker.seed); // 12
> ```
> 
> This should be achievable with getters and setters, even if it would be a breaking change...

That is exactly what I would like to do, but it's only possible with a breaking change
I will do that in v7

2022-04-21 20:54 UTC, ST-DDT commented on src/faker.ts
> +  ): void {
Please split the initial seeding to a separate PR. As thats also useful for #851.

2022-04-22 12:12 UTC, ST-DDT commented on src/faker.ts
> +   * Setting the seed again resets the sequence.
Maybe change it to:

```suggestion
   * Sets or generates a new seed.
   *
   * Please note that generated values are dependent on both the seed and the number of calls that have been made since it was set.
```

2022-04-22 12:12 UTC, ST-DDT commented on src/faker.ts
> +  seed(seed?: number): number;
Should we add a `@returns` here?

2022-04-22 15:34 UTC, Shinigami92 commented on src/faker.ts
> +    this.seed();
<img src="https://user-images.githubusercontent.com/7195563/164747050-bcc7d62c-d1c9-4bcf-91f6-74ad51c9233f.png" width="400px"/>

Accessing the seed without to generate one would fail without calling `seed()` in constructor

2022-04-22 17:28 UTC, ST-DDT commented on src/faker.ts
> +    this.seed();
> So my use case: accessing the auto-generated seed of faker without calling seed() explicitly is not possible anymore with that resulting in worse UX/DX

The users aren't supposed to access the seedValue, unless they change it.
This is the exact reason why we deprecate it in the first place.
The users should not expect that they can restore any behavior, if they access seedValue.
For now it is OK, if you just add a TODO to remove the call, when seedValue is removed.

2022-04-22 18:09 UTC, ST-DDT commented on src/faker.ts
> +   */
```suggestion
  /**
   * Sets the seed or generates a new one.
   *
   * Please note that generated values are dependent on both the seed and the
   * number of calls that have been made since it was set.
   *
   * This method is intended to allow for consistent values in a tests, so you
   * might want to use hardcoded values as the seed.
   *
   * In addition to that it can be used for creating truly random tests
   * (by passing no arguments), that still can be reproduced if needed,
   * by logging the result and explicitly setting it if needed.
   *
   * @param seed The seed to use. Defaults to a random number.
   * @returns The seed that was set.
   *
   * @example
   * // Consistent values for tests:
   * faker.seed(42)
   * faker.datatype.number(10); // 4
   * faker.datatype.number(10); // 8
   *
   * faker.seed(42)
   * faker.datatype.number(10); // 4
   * faker.datatype.number(10); // 8
   *
   * @example
   * // Random but reproducible tests:
   * // Simply log the seed, and if you need to reproduce it, insert the seed here
   * console.log('Running test with seed:', faker.seed());
   */
```

2022-04-22 18:09 UTC, ST-DDT commented on src/faker.ts
> +   * Please note that generated values are dependent on both the seed and the number of calls that have been made since it was set.
I'm not sure whether we need the full block here as well.

```suggestion
   * Please note that generated values are dependent on both the seed and the
   * number of calls that have been made since it was set.
```

2022-04-22 19:44 UTC, ST-DDT submitted a review, later dismissed

2022-04-30 20:18 UTC, ST-DDT commented
This needs a rebase. Could you please update it?

2022-05-01 11:07 UTC, ST-DDT approved these changes

2022-05-01 12:40 UTC, import-brain approved these changes

2022-05-01 13:18 UTC, merged