feat: multi locale fallback
faker-js/faker pull request #858
Opened 2022-04-20 18:45 UTC by ST-DDT

This PR introduces multiple fallback locales using an array of formats.

**Old**

````ts
faker.locale = 'fr_CH';
faker.fallbackLocale = 'en';
````

**New**

````ts
faker.localeOrder = ['fr_CH', 'fr', 'en'];
````

I'm not sure about removing support for these to setters:

````ts
faker.locale = 'fr_CH';
faker.fallbackLocale = 'en';
````

and the following constructor parameters

````ts
const faker = new Faker({
    locale: 'fr_CH',
    fallbackLocale: 'en',
    locales: { ... }
});
````

2022-04-20 18:59 UTC, Shinigami92 commented on src/faker.ts
> +  localeOrder: UsableLocale[];
I assume we need to make these readonly, so we can control when setting it

2022-04-20 18:59 UTC, Shinigami92 commented on src/faker.ts
> +      const subLocale = parts.slice(0, i).join('_');
**question:** could you explain me whats going on here? if you would like via voice chat :slightly_smiling_face:

2022-04-20 19:15 UTC, ST-DDT commented on src/faker.ts
> +      const subLocale = parts.slice(0, i).join('_');
`'en_AU_ocker'` -> `['en', 'AU', 'ocker']` // L177

-> `['en', 'AU', 'ocker']` -> `'en_AU_ocker'` // L179
-> `['en', 'AU']` -> `'en_AU'` // L179
-> `['en']` -> `'en'` // L179

2022-04-20 19:57 UTC, Shinigami92 commented on src/faker.ts
> +      const subLocale = parts.slice(0, i).join('_');
Oh... I see, and it will not cause issues, if a in-between locale could not be found cause it's not defined?
Also maybe it should be documented that this exists / handle like this

2022-04-20 20:38 UTC, pkuczynski commented on src/locale/ar.ts
> +  localeOrder: ['ar', 'en'],
As `en` is presented in every locale definition, I think we should skip it and add it as default on usage. Would make the config much simpler.

2022-04-20 20:38 UTC, pkuczynski commented on src/locale/ar.ts
>    locales: {
If this would be an array and not object, you would not need the extra prop `localeOrder` right?

2022-04-20 20:38 UTC, pkuczynski commented on src/faker.ts
> +      const subLocale = parts.slice(0, i).join('_');
Side note: 

ES6 way:

```js
'en_AU_ocker'.split('_').reduce((result, _, i, parts) => {
    return result.concat(parts.slice(0, parts.length - i).join('_'))
}, [])
```

No split:

```js
'en_AU_ocker'.split('_').reduce((result, _, i, parts) => {
    parts.pop()
    return result.concat(parts.join('_'))
}, ['en_AU_ocker'])
```

2022-04-20 20:43 UTC, Shinigami92 commented on src/locale/ar.ts
> +  localeOrder: ['ar', 'en'],
https://github.com/faker-js/faker/pull/642

2022-04-20 20:46 UTC, ST-DDT commented on src/locale/ar.ts
> +  localeOrder: ['ar', 'en'],
So instead of configuring it explicitly you want to move it to a default / implicit value?
I explicitly didn't choose that approach to allow users to omit the `en` locale to avoid certain fallback mechanism issues.

2022-04-20 20:46 UTC, Shinigami92 requested changes

2022-04-20 20:46 UTC, Shinigami92 commented on src/faker.ts
> -  localeFallback?: UsableLocale;
We should somehow deprecate these with since v7 until v8 to make a smooth transition possible for users

2022-04-20 20:50 UTC, ST-DDT commented on src/faker.ts
> +  localeOrder: UsableLocale[];
There needs to be a way to set them, it may also be useful to get them.
Especially so, if you consider it in combination with seed.

2022-04-20 20:52 UTC, pkuczynski commented on src/locale/ar.ts
> +  localeOrder: ['ar', 'en'],
I don't think this should be possible tbh. `en` is the only _full_ locale and mostly maintained. If you would like to create a new feature which needs locale, we can't block it until its implemented on every locale, right?

The only interface we should offer for locales should be:

```js
const faker = new Faker({ locales: ['de_AT', 'fr'] })
```

which would mean following fallback line: `de_AT > de > fr > en`

I can't imagine someone would prefer not working feature over getting a string in English when its not supported in a locale selected by him.

2022-04-20 20:52 UTC, pkuczynski commented on src/locale/ar.ts
>    locales: {
See my comment above...

2022-04-20 20:54 UTC, ST-DDT commented on src/faker.ts
> +      const subLocale = parts.slice(0, i).join('_');
> Oh... I see, and it will not cause issues, if a in-between locale could not be found cause it's not defined?

https://github.com/faker-js/faker/blob/75ffa2ef271238fb277175c4ed6d4058432e5a12/src/faker.ts#L180

> Also maybe it should be documented that this exists / handle like this

I will try to do that.

> Side note:

IMO my "old school" approach is way easier to read for me.

2022-04-20 21:01 UTC, Shinigami92 commented on src/locale/ar.ts
> +  localeOrder: ['ar', 'en'],
`const faker = new Faker({ locales: ['de_AT', 'fr'] })`

1. `locales` is already in use and reserved for the locales itself that can be passed
2. That would resolve to `de_AT > de > fr` not `de_AT > de > fr > en`, maybe you don't want `en`, if you want it, pass it

2022-04-20 21:05 UTC, ST-DDT commented on src/locale/af_ZA.ts
> +  localeOrder: ['af_ZA', 'en'],
Why isn't this shown as covered?

https://github.com/faker-js/faker/blob/75ffa2ef271238fb277175c4ed6d4058432e5a12/test/locale-imports.spec.ts#L15-L23

2022-04-20 21:10 UTC, pkuczynski commented on src/locale/ar.ts
> +  localeOrder: ['ar', 'en'],
> 1 `locales` is already in use and reserved for the locales itself that can be passed

I am not sure if I understand? This is exactly what we want, initialise faker with locales, right?

> 2.

I think it should always add `en` no matter what. Imagine user calls `faker.animal.dog()` and there is no data for it in neither of the locales he specified. What should faker do then:

1. return empty string?
2. throw an error?
3. or return something from `en`

I would vote for 3. Better to return English name, than nothing. But maybe we should throw?

2022-04-20 21:21 UTC, pkuczynski commented on src/locale/ar.ts
>    locales: {
How do you switch between locales?

2022-04-20 21:24 UTC, pkuczynski commented on src/faker.ts
> +      const subLocale = parts.slice(0, i).join('_');
> IMO my "old school" approach is way easier to read for me.

Both fine with me. I just posted this for fun :) Possibly the _no split_ version could be understood better then `slice`, not sure...

2022-04-20 21:25 UTC, ST-DDT commented on src/locale/ar.ts
> +  localeOrder: ['ar', 'en'],
> > 1 `locales` is already in use and reserved for the locales itself that can be passed
> 
> I am not sure if I understand? This is exactly what we want, initialise faker with locales, right?

`locales` -> available data; `localeOrder` -> active data (+ their order)


> > 2.
> 
> I think it should always add `en` no matter what. Imagine user calls `faker.animal.dog()` and there is no data for it in neither of the locales he specified. What should faker do then:

We add it by default, to exactly ensure this behavior.
However, to avoid an issue like #547, we have to avoid hardcoded fallbacks.
Sometimes having an undefined/error is easier to detect, then a random english word.

See also #823

2022-04-20 21:49 UTC, ST-DDT commented on src/locale/ar.ts
>    locales: {
faker.localeOrder = ['fr'];
faker.setLocale('fr_BE');

2022-04-21 18:42 UTC, ST-DDT commented
The coverage gets fixed in #849.

2022-04-22 23:13 UTC, ST-DDT commented on src/locale/ar.ts
> +  localeOrder: ['ar', 'en'],
> Can you come up with sensible example when switching locales on single version of faker is useful?

Because its easier, otherwise we wouldn't do that in our tests.

> > locales -> available data; localeOrder -> active data (+ their order)
> 
> This is not intuitive at all.

For me it is, also I don't want to change the base logic too much with this PR.
(I intend to make this change backwards compatible, switching to ordered locale data instead of keys might make this impossible)

Please note, that this might be due to some thoughts I have regarding the locale loading.
I consider always adding all locale data to the faker instance, but load the actual contents only lazily.
See also #830 
Since that's somewhat in the future, I would like to take one step at a time and fix some of our limitations, regarding the use of multiple locales.
In this PR, I would like to mostly stick to existing API. We can replace/improve the existing API in a separate PR to make reviews easier and focused on a single change. 

I'm not really happy of how big of a change this fix actually is and think about ways to simplify it (e.g. don't replace fallbackLocale with localeOrder and just make locale a single key or array).

2022-04-24 11:22 UTC, ST-DDT commented
@pkuczynski: @Shinigami92 also wants to merge `localeOrder` and `locales` into one.
However, he doesn't want to just drop `locale` and `localeFallback` without deprecating it first.
I'll check whether I can incorporate the backwards compatibility in this PR, otherwise this would be moved to v8 (as a hard break), so we don't have to many breaking changes in a single version.

2022-07-02 20:42 UTC, ST-DDT commented
We will use a different approach.

2022-07-02 20:42 UTC, closed without merging