test: refactor random tests to use regex
faker-js/faker pull request #869
Opened 2022-04-24 23:42 UTC by import-brain

2022-04-24 23:42 UTC, import-brain commented on test/random.spec.ts
> +      expect(alphaText).toMatch(/^[0-9]*$/);
This matches numbers only.

2022-04-24 23:43 UTC, import-brain commented on test/random.spec.ts
> +      expect(alphaText).toMatch(/^([^0-9]*)$/);
This matches everything except numbers.

2022-04-25 06:16 UTC, Shinigami92 commented on test/random.spec.ts
> +      expect(alphaText).toMatch(/^[0-9]*$/);
While reading this test, I find it confusing that the variable is called `alphaText`. I assume this is a copy-paste issue from history. Should we name it maybe `actual` or `alphaNumericText`?
I would prefer `actual` for simplicity.

Applies for the part below as well.

2022-04-25 06:16 UTC, Shinigami92 commented on test/random.spec.ts
> +      expect(alphaText).toMatch(/^([^0-9]*)$/);
Should we use `\d` for this?

2022-04-25 06:16 UTC, Shinigami92 commented on test/random.spec.ts
> +      expect(alphaText).toMatch(/^[0-9]*$/);
Should we use `\d` for this?

2022-04-25 07:08 UTC, xDivisionByZerox commented
I don't know about this PR. If I remember correctly we have an unwritten rule to use as less RegExp as possible.
It can get really fast out of hand and is for most people not that readable. Furthermore (in this specific case) using the provided matcher (`not.includes`) you receive a much nicer error message to debug.

2022-04-25 07:30 UTC, Shinigami92 commented
> I don't know about this PR. If I remember correctly we have an unwritten rule to use as less RegExp as possible. It can get really fast out of hand and is for most people not that readable. Furthermore (in this specific case) using the provided matcher (`not.includes`) you receive a much nicer error message to debug.

Would you like to add this statement to our docs? And yes I also se it like you and I already thought about to suggest using `toSatisfy` with validators. But if you even say that the output message is better readable, then we may even not do anything here.

2022-08-05 13:55 UTC, ST-DDT commented on test/random.spec.ts
> +      expect(alphaText).toMatch(/^([^0-9]*)$/);
```suggestion
      expect(alphaText).toMatch(/^[a-z]*$/);
```

2022-08-05 13:56 UTC, ST-DDT commented on test/random.spec.ts
> +      expect(alphaText).toMatch(/^[0-9]*$/);
I think this is good enough.
If we rename the variables, then we should do so consistently in another PR.

2022-08-05 13:59 UTC, ST-DDT commented
Maybe instead of regex use the related validator.js methods in compination with satisfy?

2022-08-05 14:05 UTC, Shinigami92 commented on test/random.spec.ts
> +      expect(alphaText).toMatch(/^([^0-9]*)$/);
Are upper case letters also allowed? Or is that another case not covered in this test-path?

2022-08-05 17:17 UTC, import-brain commented
> Maybe instead of regex use the related validator.js methods in compination with satisfy?

I didn't use satisfy directly, but I think my method also works. There might be a better way to write this, though.

2022-08-05 17:51 UTC, ST-DDT approved these changes

2022-08-05 17:53 UTC, ST-DDT requested changes
Oh no. Now the failure message no longer contains the bad value.

2022-08-05 19:37 UTC, Shinigami92 approved these changes

2022-08-06 08:48 UTC, ST-DDT approved these changes

2022-08-11 15:17 UTC, closed without merging