fix: address.nearbyGPSCoordinate
faker-js/faker pull request #876
Opened 2022-04-26 12:32 UTC by Shinigami92

closes #321

2022-04-26 18:30 UTC, ST-DDT commented
It looks like the float values caused massive issues especially since we stacked the calls on those values.
With the simplified implementation we have far less error and use a much larger part of the circle.

**Actual**
Min: 0.00042
Avg: 0.07065
Max: 0.14406

**Expected**
Min: 0.00000
Avg: 0.07500
Max: 0.15000

That's 96% coverage vs the old ~0.08%

@Shinigami92 Anything you want to change/fix here?

2022-04-26 18:43 UTC, ST-DDT submitted a review, later dismissed

2022-04-26 18:44 UTC, Shinigami92 commented on src/address.ts
> +const kmPerDegree = 40_000 / 360; // in km/°
Script constants should be written in CONSTANT_CASE

But this should also be named with earth, cause maybe we later want to have some other circumferences for other custom planetoids

2022-04-26 18:44 UTC, Shinigami92 commented on test/address.spec.ts
> +  const EQUATORIAL_EARTH_RADIUS = 6378.137;
We should move this out of the function

2022-04-26 18:44 UTC, Shinigami92 commented on test/address.spec.ts
> +const NON_SEEDED_BASED_RUN = 1;
```suggestion
const NON_SEEDED_BASED_RUN = 5;
```

2022-04-26 18:44 UTC, Shinigami92 commented on test/address.spec.ts
> +          for (let i = 0; i < 100; i++) {
At least thousends, maybe even back to 10_000?

```suggestion
          for (let i = 0; i < 1_000; i++) {
```

```suggestion
          for (let i = 0; i < 10_000; i++) {
```

2022-04-26 18:44 UTC, Shinigami92 commented on test/address.spec.ts
> +  const a =
Could we find a better name for `a`? I currently don't know what it is :thinking:

2022-04-26 18:44 UTC, Shinigami92 commented on test/address.spec.ts
> +            const isMetric = faker.datatype.boolean();
I would like to move this out to the `it` as `it.each` and then split the runs into half for each, so maybe 5_000/5_000?

2022-04-26 18:44 UTC, Shinigami92 commented on test/address.spec.ts
> +            const radius = faker.datatype.float({ min: 1, max: 100 });
We could control this one also a bit more with it.each together with the `isMetric`

so what about e.g. `it.each(times(100).map(i=>[i+1,isMetric,radius]))` ...

Okay maybe a 3-stacked for-loop is better here?
```ts
for (const isMetric of [true, false])
  for (const radius of times(100))
    for (const run of times(1000))
      it(...)
```

2022-04-26 18:46 UTC, ST-DDT commented on test/address.spec.ts
> +          for (let i = 0; i < 100; i++) {
I wouldn't recommend that, as this just wastes time. We don't do the NON_SEEDED_BASE_RUN that often either.

2022-04-26 19:25 UTC, ST-DDT commented on test/address.spec.ts
> +  const a =
Me neither. Maybe check the internet?

2022-04-26 19:30 UTC, ST-DDT requested changes

2022-04-26 19:30 UTC, ST-DDT commented on test/address.spec.ts
> +              for (let i = 0; i < 100; i++) {
A single run is probably enough.
Otherwise we end up with too many checks:
- `runs * isMetric * radius * i`
- `5 * 2 * 100 * 100`
- `= 100000`

If you omit the i-for-loop, then we still have `1000` test runs.
Maybe leave the loop there, but just reduce it to `5`,
that way it's very easy to increment the runs if there is a need to debug it.

2022-04-26 19:57 UTC, Shinigami92 commented on src/address.ts
> +    // TODO @Shinigami92 2022-04-26: Provide an option property to provide custom circumferences.
Done https://github.com/faker-js/faker/issues/878

2022-04-26 20:05 UTC, Shinigami92 commented on test/address.spec.ts
> +  const a =
I found this https://www.movable-type.co.uk/scripts/latlong.html
But even there it is called `a`. :shrug: 
Because I don't want to stop this PR to get merged just based on that, lets move on :shrug:

2022-04-26 20:37 UTC, ST-DDT approved these changes

2022-04-27 14:43 UTC, import-brain approved these changes

2022-04-27 16:35 UTC, merged