feat: add creditCardProvider (#882)
faker-js/faker pull request #888
Opened 2022-04-29 04:03 UTC by beninsydney

Adds method for randomly selecting a credit card provider from the keys of `faker.definitions.finance.credit_card`

    > faker.finance.creditCardProvider()
    'visa'
    > faker.finance.creditCardProvider()
    'diners_club'

For pull request #882

2022-04-29 06:18 UTC, ST-DDT requested changes
Please add a test for this.

````ts
expect(Object.keys(.....credit_card)).toContain(actual)
````

2022-04-29 06:18 UTC, ST-DDT commented on src/finance.ts
> +   * Returns a random credit card provider
```suggestion
   * Returns a random credit card provider.
```

2022-04-29 07:26 UTC, ST-DDT submitted a review, later dismissed

2022-04-29 09:44 UTC, Shinigami92 commented
Should we focus and merge https://github.com/faker-js/faker/pull/503 first?

2022-04-29 10:16 UTC, ST-DDT commented on src/finance.ts
> +  creditCardProvider(): string {
@pkuczynski Should we change the name of the parameter above too?

https://github.com/beninsydney/faker/blob/f0b7d871206c22090932c0e593eb5252eeb1efc3/src/finance.ts#L256

2022-04-29 10:41 UTC, Shinigami92 requested changes

2022-04-29 10:41 UTC, Shinigami92 commented on test/finance.spec.ts
> +      describe('cardCardProvider()', () => {
```suggestion
      describe('cardCardIssuer()', () => {
```

2022-04-29 10:41 UTC, Shinigami92 commented on test/finance.spec.ts
> +            provider
```suggestion
          const issuer = faker.finance.creditCardIssuer();
          expect(issuer).toBeTypeOf('string');
          expect(Object.keys(faker.definitions.finance.credit_card)).toContain(
            issuer
```

2022-04-29 10:55 UTC, beninsydney commented
I've got this ready locally but I've noticed 'provider' is also used in `src/finance.ts` in `creditCardNumber()` and in `src/definitions/finance.ts` in a description block, do you want me to go ahead and update the nomenclature for consistency?

```
  /**
   * Generates a random credit card number.
   *
   * @param provider The name of the provider (case insensitive) or the format used to generate one.
   *
   * @example
   * faker.finance.creditCardNumber() // '4427163488668'
   * faker.finance.creditCardNumber('visa') // '4882664999003'
   * faker.finance.creditCardNumber('63[7-9]#-####-####-###L') // '6375-3265-4676-6644'
   */
  creditCardNumber(provider = ''): string {
    let format: string;
    const localeFormat = this.faker.definitions.finance.credit_card;
    const normalizedProvider = provider.toLowerCase();
    if (normalizedProvider in localeFormat) {
      format = this.faker.random.arrayElement(localeFormat[normalizedProvider]);
    } else if (provider.match(/#/)) {
      // The user chose an optional scheme
      format = provider;
    } else {
      // Choose a random provider
      // Credit cards are in an object structure
      const formats = this.faker.random.objectElement(localeFormat, 'value'); // There could be multiple formats
      format = this.faker.random.arrayElement(formats);
    }
    format = format.replace(/\//g, '');
    return this.faker.helpers.replaceCreditCardSymbols(format);
  }
```

2022-04-29 10:56 UTC, pkuczynski commented on src/finance.ts
> +  creditCardProvider(): string {
Yes, I would say so...

2022-04-29 11:29 UTC, Shinigami92 commented
test/finance.spec.ts line 397

2022-04-29 12:12 UTC, Shinigami92 submitted a review, later dismissed

2022-04-29 12:58 UTC, ST-DDT submitted a review, later dismissed

2022-04-29 14:17 UTC, pkuczynski submitted a review, later dismissed

2022-04-29 14:17 UTC, pkuczynski commented on test/finance.spec.ts
> +      describe('cardCardIssuer()', () => {
```suggestion
      describe('creditCardIssuer()', () => {
```

2022-04-29 14:27 UTC, ST-DDT approved these changes

2022-04-29 15:49 UTC, Shinigami92 submitted a review, later dismissed

2022-04-30 09:00 UTC, Shinigami92 approved these changes

2022-04-30 09:00 UTC, Shinigami92 approved these changes

2022-04-30 09:06 UTC, ST-DDT approved these changes

2022-04-30 09:06 UTC, merged