refactor: move some random methods to helpers
faker-js/faker pull request #892
Opened 2022-04-30 09:18 UTC by Shinigami92

After we discussed stuff in https://github.com/faker-js/faker/pull/874#issuecomment-1110198059 I move these into helpers

2022-04-30 09:25 UTC, Shinigami92 commented on src/helpers.ts
> +        : 0;
I'm not sure if this optimization is worth it, or if we should just generate also an index of 0 and trigger the seed sequence by that :thinking:

2022-04-30 09:39 UTC, ST-DDT commented on src/helpers.ts
> +        : 0;
IMO it adds unnecessary complexity for a very negligible performance gain.

2022-04-30 09:50 UTC, Shinigami92 commented on src/helpers.ts
> +        : 0;
nevermind

2022-04-30 09:55 UTC, Shinigami92 commented on src/helpers.ts
> +    // See https://github.com/faker-js/faker/issues/***
missing issue number

2022-04-30 09:55 UTC, Shinigami92 commented on src/helpers.ts
> +    // See https://github.com/faker-js/faker/issues/***
missing issue number

2022-05-01 12:09 UTC, ST-DDT requested changes

2022-05-01 12:09 UTC, ST-DDT commented on src/helpers.ts
> +      type: this.faker.helpers.arrayElement(
```suggestion
      type: this.arrayElement(
```

2022-05-01 12:09 UTC, ST-DDT commented on src/helpers.ts
> +    return this.faker.helpers.arrayElement(array);
```suggestion
    return this.arrayElement(array);
```

2022-05-01 12:09 UTC, ST-DDT commented on src/helpers.ts
> +          ? this.faker.helpers.arrayElement(alpha)
```suggestion
          ? this.arrayElement(alpha)
```

2022-05-01 12:09 UTC, ST-DDT commented on src/helpers.ts
> +        str += this.faker.helpers.arrayElement(alpha);
```suggestion
        str += this.arrayElement(alpha);
```

2022-05-01 12:09 UTC, ST-DDT commented on src/helpers.ts
> +    return this.faker.helpers.arrayElement(array);
```suggestion
    return this.arrayElement(array);
```

2022-05-01 12:46 UTC, ST-DDT approved these changes

2022-05-01 12:47 UTC, import-brain approved these changes

2022-05-01 13:22 UTC, merged