feat: Add `cron()` function
faker-js/faker pull request #897
Opened 2022-05-01 10:47 UTC by nhammond101

Adds new functionality to generate cron expressions.
---

**New Function:**
* faker.system.cron()

**Usage:**  

`faker.system.cron()`:

```
// generates a random cron expression
console.log(faker.system.cron()): // '45 23 * * 6'
```
supports an optional options object, which currently has a year component

```
// generates a random cron expression with a year
console.log(faker.system.cron()): // '45 23 * * 6 2067'
```

**Unit tests for the functions added.**

2022-05-01 10:58 UTC, Shinigami92 commented
Targeting it for v6.3, but I don't think it will make it so fast
We plan to work on v7 in next "sprint"

2022-05-01 11:10 UTC, Shinigami92 requested changes
Should we also try to generate some more advanced cron strings like [23 0-20/2 * * *](https://crontab.guru/#23_0-20/2_*_*_*)?

2022-05-01 11:10 UTC, Shinigami92 commented on src/system.ts
> +    const year = this.faker.random.arrayElement(years);
I think these are perfect use-cases for using `this.faker.helpers.maybe` with `?? '*'` as fallbacks

2022-05-01 11:15 UTC, ST-DDT commented
Should we add some range for the cron: E.g. `yearly`, `daily`, ...

2022-05-01 11:59 UTC, ST-DDT requested changes

2022-05-01 11:59 UTC, ST-DDT commented on src/system.ts
> +   * @param options.includeYear Whether to include a year in the generated expression.  Default to `false`
```suggestion
   * @param options.includeYear Whether to include a year in the generated expression.  Default to `false`.
```

2022-05-01 11:59 UTC, ST-DDT commented on src/system.ts
> +  cron(options?: { includeYear: boolean }): string {
```suggestion
  cron(options: { includeYear: boolean } = {}): string {
```

2022-05-01 11:59 UTC, ST-DDT commented on src/system.ts
> +    const days = [this.faker.datatype.number({ min: 1, max: 31 }), '*', '?'];
What is `?` and why is it only for days?

2022-05-01 11:59 UTC, ST-DDT commented on src/system.ts
> +    const year = this.faker.random.arrayElement(years);
Maybe, maybe not.

2022-05-01 17:42 UTC, nhammond101 commented on src/system.ts
> +    const days = [this.faker.datatype.number({ min: 1, max: 31 }), '*', '?'];
the `?` represents "no specific value" whereas `*` is any valid value. 

An example is `dayOfWeek` (ie `SAT`) specified, the `dayOfMonth` wouldn't be all values (ie 1-31), but rather a subset, and therefore the `?` is used instead.

I added it for value completeness, but logically the two properties (days, dayOfWeek) aren't linked

2022-05-01 17:44 UTC, nhammond101 commented
> Should we also try to generate some more advanced cron strings like [23 0-20/2 * * *](https://crontab.guru/#23_0-20/2_*_*_*)?

i'd like to, I wanted to get the simplest expressions generated first and potentially gauge demand

2022-05-23 19:38 UTC, ST-DDT requested changes

2022-05-23 19:38 UTC, ST-DDT commented on src/modules/system/index.ts
> +   * @param options.includeYear Whether to include a year in the generated expression. Default to `false`.
```suggestion
   * @param options.includeYear Whether to include a year in the generated expression. Defaults to `false`.
```

2022-05-23 20:00 UTC, Shinigami92 requested changes
This PR needs to update their test but we found out that to many other stuff not related to this PR within the test file is messed up
So it will not be merged in v7.0.0

2022-08-16 09:29 UTC, ST-DDT commented
@nhammond101 Could you please update this PR?

2022-08-24 07:14 UTC, Shinigami92 commented on src/modules/system/index.ts
> + */
Not sure if this comment is worth at all 🤷
Maybe just remove it

2022-08-24 07:14 UTC, Shinigami92 commented on src/modules/system/index.ts
> +   * @param options.includeYear Whether to include a year in the generated expression.  Default to `false`
```suggestion
   * @param options.includeYear Whether to include a year in the generated expression. Default to `false`.
```

2022-08-24 07:14 UTC, Shinigami92 commented on test/system.spec.ts
> +        );
Is there a reason why this is wrapped inside the `RegExp` constructor instead of just using a regex literal?

2022-08-24 07:14 UTC, Shinigami92 commented on test/system.spec.ts
> +            `generated cron, string should contain 5 space-separated values`
Maybe we should just check with `split(' ')` `length === 5`?
Alternatively the message should be changed
With split we could also check each part individually and server better readable native vitest messages with that

2022-08-24 07:14 UTC, ST-DDT requested changes

2022-08-24 07:14 UTC, ST-DDT commented on src/modules/system/index.ts
> +   * @param options.includeYear Whether to include a year in the generated expression.  Default to `false`
```suggestion
   * @param options.includeYear Whether to include a year in the generated expression.  Default to `false`.
```

2022-08-24 07:14 UTC, ST-DDT commented on src/modules/system/index.ts
> +  cron(options?: { includeYear: boolean }): string {
```suggestion
  cron(options: { includeYear: boolean } = {}): string {
    const { includeYear = false } = options;
```

2022-08-24 07:14 UTC, ST-DDT commented on src/modules/system/index.ts
> +    if (options?.includeYear) {
```suggestion
    if (includeYear) {
```

2022-08-24 07:14 UTC, ST-DDT commented on src/modules/system/index.ts
> + * cron days are only in English
```suggestion
 * Cron days are only in English.
```

2022-08-24 13:22 UTC, ST-DDT commented on src/modules/system/index.ts
> +    return this.faker.helpers.arrayElement(availableExpressions);
IMO this should use a `randomBoolean()? standardExpression : nonStandardExpression`

2022-08-24 13:56 UTC, import-brain commented on src/modules/system/index.ts
> +   * @param options.includeYear Whether to include a year in the generated expression.  Default to `false`
Wouldn't it be "defaults to" instead of "default to"?

2022-08-24 14:09 UTC, import-brain requested changes

2022-08-24 14:09 UTC, import-brain commented on src/modules/system/index.ts
> +    // create the arrays to hold the available values for each component of the expression
```suggestion
  cron(
  	options: {
      includeYear?: boolean;
      includeNonStandard?: boolean;
    } = {}
  ): string {
  	const { includeYear = false, includeNonStandard = false } = options;
    // create the arrays to hold the available values for each component of the expression
```

2022-08-24 14:09 UTC, import-brain commented on src/modules/system/index.ts
> +    if (options?.includeNonStandard) {
```suggestion
    if (includeNonStandard) {
```

2022-08-24 14:09 UTC, import-brain commented on src/modules/system/index.ts
> +    // create the arrays to hold the available values for each component of the expression
If you accept this change, please also accept the other one in this review and the change in the review here: https://github.com/faker-js/faker/pull/897/files#r953432873

2022-08-25 10:42 UTC, nhammond101 commented on src/modules/system/index.ts
> + */
Removed

2022-08-25 10:46 UTC, nhammond101 commented on test/system.spec.ts
> +        );
none that I can remember, i'll convert to literal

2022-08-25 19:29 UTC, nhammond101 commented on src/modules/system/index.ts
> +    // create the arrays to hold the available values for each component of the expression
i've changed it now

2022-08-25 19:29 UTC, nhammond101 commented on src/modules/system/index.ts
> +    if (options?.includeNonStandard) {
done

2022-08-25 19:58 UTC, nhammond101 commented on src/modules/system/index.ts
> +    return this.faker.helpers.arrayElement(availableExpressions);
Updated the lines

2022-08-25 20:51 UTC, ST-DDT submitted a review, later dismissed

2022-08-25 20:52 UTC, ST-DDT commented on src/modules/system/index.ts
> +   * @param options.includeNonStandard Whether to include a @yearly, @monthly, @daily, etc text labels in the generated expression.  Default to `false`
```suggestion
   * @param options.includeNonStandard Whether to include a @yearly, @monthly, @daily, etc text labels in the generated expression.  Default to `false`.
```

2022-08-25 21:32 UTC, ST-DDT commented
Please rebase your commit:

````sh
git fetch --all
git rebase origin/main
git push -f
````

Alternatively, we can do that for you, but then you have to reset your local checkout.

2022-08-26 08:10 UTC, Shinigami92 commented on src/modules/system/index.ts
> +   * @param options.includeNonStandard Whether to include a @yearly, @monthly, @daily, etc text labels in the generated expression.  Default to `false`.
```suggestion
   * @param options.includeNonStandard Whether to include a @yearly, @monthly, @daily, etc text labels in the generated expression. Defaults to `false`.
```

2022-08-26 08:10 UTC, Shinigami92 commented on test/system.spec.ts
> +            `generated cron, string should contain 5 space-separated values`
I think my request here is still valid, @ST-DDT what's your opinion about that?

2022-08-26 13:38 UTC, ST-DDT requested changes
I think this is the last thing that needs to be changed.
Otherwise it looks good to me.

2022-08-26 13:38 UTC, ST-DDT commented on src/modules/system/index.ts
> +   * Returns a cron expression
```suggestion
   * Returns a cron expression.
```

2022-08-26 13:40 UTC, ST-DDT commented on test/system.spec.ts
> +            `generated cron, string should contain 5 space-separated values`
@Shinigami92 Maybe write an example?

2022-08-26 13:49 UTC, Shinigami92 commented on test/system.spec.ts
> +            `generated cron, string should contain 5 space-separated values`
```ts
const actual = faker.system.cron()
const parts = actual.split(' ')
expect(parts).toHaveLength(5)

const [minute, hour, day, month, dayOfWeek] = parts
expect(minute).toMatch(/([1-9]|[1-5]\d|\*)/)
expect(hour).toMatch(/([0-9]|1\d|2[0-3]|\*)/)
// ...
```

This is longer but much more readable, understandable and produce much better vitest messages

2022-08-26 14:01 UTC, Shinigami92 approved these changes
I would have solved it differently and maybe more readably, but my case/request are tackled and solved :+1:

2022-08-26 14:02 UTC, ST-DDT approved these changes

2022-08-26 14:06 UTC, nhammond101 commented
@Shinigami92 if you get a few minutes, would you post your approach?

2022-08-26 14:07 UTC, Shinigami92 commented
> if you get a few minutes, would you post your approach?

See here: https://github.com/faker-js/faker/pull/897#discussion_r956063709

2022-08-26 20:09 UTC, import-brain approved these changes

2022-08-26 20:44 UTC, xDivisionByZerox requested changes

2022-08-26 20:44 UTC, xDivisionByZerox commented on src/modules/system/index.ts
> +      : this.faker.helpers.arrayElement(nonStandardExpressions);
This can potentially return a `nonStandardExpressions` even with `nonStandardExpressions` explicitly set to `false`.

2022-08-26 20:44 UTC, xDivisionByZerox commented on src/modules/system/index.ts
> +      : this.faker.helpers.arrayElement(nonStandardExpressions);
Or am I having trouple with my logic?

2022-08-26 20:52 UTC, xDivisionByZerox commented on src/modules/system/index.ts
> +      : this.faker.helpers.arrayElement(nonStandardExpressions);
This should have been a normal comment not a change request, my bad.

2022-08-28 20:45 UTC, nhammond101 commented on src/modules/system/index.ts
> +      : this.faker.helpers.arrayElement(nonStandardExpressions);
depends on use case.  For Cron implementations that support the non-standard values, i'd expect to be able to generate both standard and non-standard values, given that both are supported by that implementation.

2022-08-29 11:08 UTC, xDivisionByZerox approved these changes

2022-08-29 11:34 UTC, merged