refactor: rename module class names
faker-js/faker pull request #932
Opened 2022-05-07 15:27 UTC by Shinigami92

2022-05-07 16:07 UTC, ST-DDT commented
https://github.com/faker-js/faker/discussions/805#discussioncomment-2599628

2022-05-07 16:17 UTC, Shinigami92 commented
@pkuczynski Could you go through this PR/code and reevaluate if you REALLY want to have the modules renamed not to suffixed with `Module`? I still don't think your initial thought that it could conflict with node's modules is valid in any case.
Beside that, I personally find it confusing to name modules everywhere modules but then the module itself is not named module but faker were it actually is not e.g. a sub-instance of Faker.
It can be even more confusing if we have later a `MinimalFaker`, `BaseFaker`, `Faker`. (See https://github.com/faker-js/faker/discussions/805#discussioncomment-2690233)

And then we would even have a `FakeFaker` 👀 confusing like hell 🤷

2022-05-07 16:41 UTC, ST-DDT commented
> And then we would even have a `FakeFaker` 👀 confusing like hell 🤷

No, because fake -> helpers.fake

2022-08-20 22:07 UTC, pkuczynski requested changes

2022-08-20 22:07 UTC, pkuczynski commented on src/faker.ts
> +import { AddressModule } from './modules/address';
I still think they should be called `XyzFaker`, as when they imported it would be clear what they are and would never conflict with any other package. For me `AdressModule` is too general. So either `FakerAddress`, `FakeAddress` or `AddressFaker`. All equally good... Probably `FakeAddress` being my favorite. `FakeAdress.streetName` reads very nicely.

I am also under impression @ST-DDT thinks the same?

2022-08-20 22:22 UTC, Shinigami92 commented on src/faker.ts
> +import { AddressModule } from './modules/address';
FakeAddress/FakerAddress is new to me 🤔 
This might solve the problem of not getting confused with something like LocalizedFaker, BaseFaker or CoreFaker which is part of the darfted roadmap you have skipped in the last meeting(s)

Also I saw what @xDivisionByZerox did in the number and string modules, so I hoped that the discussion just came to an end and we silently just accepted that XyzModule as a name for a module in faker is just okay

2022-08-21 00:11 UTC, pkuczynski commented on src/faker.ts
> +import { AddressModule } from './modules/address';
Sorry for skipping the last 2 meetings. Not always easy to balance work, personal duties and open source.

`FakeXyz` is a new thing which came to my mind just today. But it feels like it saves the purpose very well.  Let's see what others think... :)

2022-08-21 10:07 UTC, ST-DDT commented on src/faker.ts
> +import { AddressModule } from './modules/address';
I like the Fake(r) prefix/suffixes way more than the generic Module.
I like XyzFaker the most because it puts the emphasis on it faking stuff.
Whereas Fake(r)Xyz sounds like a Faker/fake variant of Xyz. This might be a German implicit thing. It would be nice if a English native speaker could (in-)validate my impression on that.

For the same reason and to avoid naming conflicts I would name the Faker classes FakerCore/FakerBase...

There is one argument for FakerXyz and that is IDE autocompletion type Faker and the you get all variants (if you are lucky).

Please keep in mind that the later (not v8) treeshaking refactor will remove the classes in favor of factory functions. So I would like to get a quick decision on this. Ibwill open a poll later when Ibhave some spare time. EOV Thursday during the team meeting.

2022-08-21 10:19 UTC, xDivisionByZerox commented on src/faker.ts
> +import { AddressModule } from './modules/address';
I like XyzFaker, for the same reasons @ST-DDT just stated. I just used XyzModule as a working title in the string and number module. 

Just leaving this here, so you have my opinion.

2022-08-21 10:25 UTC, xDivisionByZerox commented
Would it be possible to integrate this change as a non-breaking change? Maybe with some proxy magic and deprecation of the current classes (in the constructor)?

2022-08-21 11:28 UTC, Shinigami92 commented on src/faker.ts
> +import { AddressModule } from './modules/address';
> Please keep in mind that the later (not v8) treeshaking refactor will remove the classes in favor of factory functions.

Please keep in mind that this will **NOT** solve the problem! We will not rename the module interfaces back to e.g. just `Date` because also interfaces would conflict with native JS constructors.
You cannot write code like:
```ts
function myFun(fakerDateInstance: Date) {
//                                ^^^^ this is from Faker
	const recent: Date = fakerDateInstance.recent();
//                ^^^^ This is native JS/TS
}
```

So we need a permanent final solution for the entire future of FakerJS with no turning back!

2022-08-21 13:16 UTC, ST-DDT commented
> Would it be possible to integrate this change as a non-breaking change? Maybe with some proxy magic and deprecation of the current classes (in the constructor)?

The classes have never been part of the API, so not sure if that is worth it.

2022-08-21 16:27 UTC, ST-DDT commented on src/faker.ts
> +import { AddressModule } from './modules/address';
https://github.com/faker-js/faker/discussions/1291

2022-08-21 19:50 UTC, import-brain commented on src/faker.ts
> +import { AddressModule } from './modules/address';
> I like the Fake(r) prefix/suffixes way more than the generic Module. I like XyzFaker the most because it puts the emphasis on it faking stuff. Whereas Fake(r)Xyz sounds like a Faker/fake variant of Xyz. This might be a German implicit thing. It would be nice if a English native speaker could (in-)validate my impression on that.
> 
> For the same reason and to avoid naming conflicts I would name the Faker classes FakerCore/FakerBase...
> 
> There is one argument for FakerXyz and that is IDE autocompletion type Faker and the you get all variants (if you are lucky).
> 
> Please keep in mind that the later (not v8) treeshaking refactor will remove the classes in favor of factory functions. So I would like to get a quick decision on this. I will open a poll later when I have some spare time. EOV Thursday during the team meeting.

I would also prefer XyzFaker.

2022-09-07 10:55 UTC, Shinigami92 commented on src/faker.ts
> +import { AddressModule } from './modules/address';
Current voting says 5 of 6 voters prefer suffixing with `Module`
Also Damien got some independent arguments for using this and why the other ideas are not that good
So for now I will mark this as resolved

2022-09-07 11:30 UTC, ST-DDT approved these changes

2022-09-08 15:22 UTC, ST-DDT commented
**Team decision**

We will use `XyzModule`.

2022-09-08 16:04 UTC, pkuczynski approved these changes

2022-09-08 17:11 UTC, xDivisionByZerox approved these changes

2022-09-08 17:14 UTC, import-brain approved these changes

2022-09-08 17:18 UTC, merged