feat(internet): HTTP random status code
faker-js/faker pull request #945
Opened 2022-05-11 14:31 UTC by johge201

Hi! 
This is our first commit to an open-source project. 
This feature adds some random status codes, with testing included.

Feel free to give us some feedback :)

Link to issue: [issue 906](https://github.com/faker-js/faker/issues/906)

2022-05-11 16:13 UTC, xDivisionByZerox requested changes

2022-05-11 16:13 UTC, xDivisionByZerox commented on src/definitions/internet.ts
> +  status_code: Record<HTTPStatusCodeType, string[]>;
I'm not sure about the codes being a string. Typically status codes are from the type number. I would like some feedback from @faker-js/members and @faker-js/maintainers on this.

2022-05-11 16:16 UTC, xDivisionByZerox commented
About my comment. Please wait with the implementation change until at least one other member proposed their opinion on this.
Otherwise, this looks clean to me. Thanks for contributing.

2022-05-11 18:22 UTC, ST-DDT commented on src/definitions/internet.ts
> +  status_code: Record<HTTPStatusCodeType, string[]>;
I think so too.
https://developer.mozilla.org/en-US/docs/Web/API/Response/status#value

2022-05-12 06:17 UTC, sofbe commented on src/definitions/internet.ts
> +  status_code: Record<HTTPStatusCodeType, string[]>;
Thank you for the feedback! We will fix this today.

2022-05-12 09:32 UTC, xDivisionByZerox approved these changes

2022-05-12 11:22 UTC, Shinigami92 reviewed
Count as approved after additional requested test was added 👍

2022-05-12 11:22 UTC, Shinigami92 commented on test/internet.spec.ts
> +        it('should return a random HTTP status code', () => {
I would like to have one additional test that calls it with `types`-arguemnt

2022-05-12 12:21 UTC, johge201 commented on test/internet.spec.ts
> +        it('should return a random HTTP status code', () => {
We have now added two tests for this!

2022-05-12 12:34 UTC, xDivisionByZerox approved these changes

2022-05-12 12:44 UTC, ST-DDT commented
<details>
<summary><strong>Docs-Preview (Click to expand)</strong></summary>

![grafik](https://user-images.githubusercontent.com/1579362/168077213-fe434ab6-e350-4f83-84c7-df5a41a7914c.png)

</details>

2022-05-12 12:45 UTC, ST-DDT approved these changes

2022-05-12 12:48 UTC, ST-DDT requested changes

2022-05-12 12:48 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * faker.internet.statusCode({ types: ['success', 'serverError'] }) // 400
```suggestion
   * faker.internet.statusCode({ types: ['success', 'serverError'] }) // 500
```

2022-05-12 12:50 UTC, Shinigami92 submitted a review, later dismissed

2022-05-12 12:55 UTC, xDivisionByZerox submitted a review, later dismissed

2022-05-12 12:56 UTC, Shinigami92 approved these changes

2022-05-12 12:58 UTC, pkuczynski commented on src/locales/en/internet/status_code.ts
> +  success: [200, 201, 202, 203, 204],
This listy is not complete. Please add all status codes.

2022-05-12 13:03 UTC, Shinigami92 commented on src/locales/en/internet/status_code.ts
> +  success: [200, 201, 202, 203, 204],
We wanted to start with most common once
(expect of 418 😜, that's the holy easter egg 🫖)

2022-05-12 13:06 UTC, xDivisionByZerox commented on src/locales/en/internet/status_code.ts
> +export default {
I wouldn't consider information status code as common. That's why I ignored them for now.

2022-05-12 13:08 UTC, Shinigami92 commented on src/locales/en/internet/status_code.ts
> +export default {
Should we exclude them from the defaults 🤔 But at least it would be possible to generate them when requested?

2022-05-12 13:09 UTC, ST-DDT submitted a review, later dismissed

2022-05-12 13:15 UTC, xDivisionByZerox commented on src/locales/en/internet/status_code.ts
> +export default {
> I have never used them consciously before.
 I actually have ^^

I would open another PR and refactor this to include "uncommon" codes that will include the now missing codes for the common response types.

2022-05-12 13:18 UTC, xDivisionByZerox commented on src/locales/en/internet/status_code.ts
> +export default {
I would want to include labels as well so the Meta-Data Object for status codes would look like this 
```
{ 
  name: string; // 'Continue'
  code: number; // 100
  common: boolean; // false
}
```

2022-05-12 13:33 UTC, pkuczynski commented on src/locales/en/internet/status_code.ts
> +export default {
No reason why not to have them in this PR... If you linked a link to the documentation, I found it weird that only some of them have been listed...

2022-05-12 13:34 UTC, Shinigami92 commented on src/locales/en/internet/status_code.ts
> +export default {
Uh... if we want name, do we want to decouple these from the rest? Because that way we can later put number and common flag into global and name into locale.

2022-05-12 13:50 UTC, xDivisionByZerox commented on src/locales/en/internet/status_code.ts
> +export default {
TBH I don't think the status message changes no matter what language you are in.

https://developer.mozilla.org/fr/docs/Web/HTTP/Status/100
https://developer.mozilla.org/de/docs/Web/HTTP/Status/100

2022-05-12 23:04 UTC, ST-DDT commented on src/modules/internet/index.ts
> +  statusCode(
The **http**StatusCode is a good idea, because `grpc` uses different status codes.

2022-05-16 09:31 UTC, ST-DDT requested changes

2022-05-16 09:31 UTC, ST-DDT commented on src/modules/internet/index.ts
> +   * @example
```suggestion
   *
   * @example
```

Looks like we missed this one in emoji.

2022-05-16 09:38 UTC, ST-DDT commented
Also please move this method below `httpMethod()` as they are kind of related.

2022-05-17 13:53 UTC, Shinigami92 submitted a review, later dismissed

2022-05-17 14:45 UTC, import-brain approved these changes

2022-05-17 18:27 UTC, ST-DDT requested changes

2022-05-17 18:27 UTC, ST-DDT commented on src/definitions/internet.ts
> +  status_code: Record<HTTPStatusCodeType, number[]>;
```suggestion
  http_status_code: Record<HTTPStatusCodeType, number[]>;
```

2022-05-17 22:34 UTC, Minozzzi submitted a review, later dismissed

2022-05-18 07:09 UTC, ST-DDT submitted a review, later dismissed

2022-05-18 17:12 UTC, Shinigami92 submitted a review, later dismissed

2022-05-18 17:13 UTC, Shinigami92 commented
@pkuczynski You may need to approve or comment if you want further changes

2022-05-18 18:18 UTC, pkuczynski requested changes

2022-05-18 18:18 UTC, pkuczynski commented on src/locales/ro/address/index.ts
> +  streets,
On the top of the file you will see this:

```
/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
```

So this should not be changed...

2022-05-18 18:18 UTC, pkuczynski commented on src/modules/internet/index.ts
> +   * Generates a random status code.
```suggestion
   * Generates a random HTTP status code.
```

2022-05-18 18:22 UTC, Shinigami92 commented on src/locales/ro/address/index.ts
> +  streets,
It will be changed anyways with #965

2022-05-18 18:30 UTC, pkuczynski commented on src/locales/ro/address/index.ts
> +  streets,
Still, this should not be committed, right?

2022-05-18 18:39 UTC, Shinigami92 commented on src/locales/ro/address/index.ts
> +  streets,
Depends on which PR will get merged faster :wink:

2022-05-18 19:32 UTC, Shinigami92 approved these changes

2022-05-18 19:34 UTC, pkuczynski approved these changes

2022-05-18 20:42 UTC, xDivisionByZerox approved these changes

2022-05-18 22:09 UTC, ST-DDT approved these changes

2022-05-19 02:12 UTC, import-brain approved these changes

2022-05-20 12:45 UTC, Minozzzi approved these changes

2022-05-21 14:15 UTC, merged