improve and extend fr and fr_CH locales
faker-js/faker pull request #973
Opened 2022-05-20 07:50 UTC by Yago

Adds a lot of locales to fr and fr_CH with a focus on inclusive words; mostly for nouns and adjectives.

2022-05-20 12:34 UTC, ST-DDT requested changes
Thank you very much for your contribution. This is quite a lot to review. It will probably take a few days to review it in more detail.

2022-05-20 12:34 UTC, ST-DDT commented on src/locales/fr/animal/cow.ts
> +  'Brune',
This one seems to be duplicate.

2022-05-20 12:34 UTC, ST-DDT commented on src/locales/fr/animal/lion.ts
> +  "lion d'Asie",
Is the difference in capitalization intentional?

2022-05-20 12:34 UTC, ST-DDT commented on src/locales/fr/word/interjection.ts
> +  'bang',
These words are duplicate.

2022-05-20 12:34 UTC, ST-DDT commented on src/locales/fr/word/interjection.ts
> +  'ouah',
Same here

2022-05-20 12:34 UTC, ST-DDT commented on src/locales/fr_CH/animal/lion.ts
> +  "lion d'Asie",
Is the difference in capitalization intentional?

2022-05-20 12:34 UTC, ST-DDT commented on src/locales/fr_CH/company/bs_adjective.ts
> +  'proactive',
This file looks like `en` to me.

2022-05-20 12:34 UTC, ST-DDT commented on src/locales/fr_CH/company/bs_noun.ts
> +  'markets',
same here

2022-05-20 12:34 UTC, ST-DDT commented on src/locales/fr_CH/company/bs_verb.ts
> +  'streamline',
And here

2022-05-20 12:34 UTC, ST-DDT commented on src/locales/fr_CH/company/adjective.ts
> +  'Assimilated',
This looks like english

2022-05-20 12:34 UTC, ST-DDT commented on src/locales/fr_CH/company/descriptor.ts
> +  'asymmetric',
And here

2022-05-20 12:34 UTC, ST-DDT commented on src/locales/fr_CH/company/noun.ts
> +  'algorithm',
And here

2022-05-20 12:34 UTC, ST-DDT commented on src/locales/fr_CH/word/interjection.ts
> +  'bang',
These words are duplicate.

2022-05-20 12:34 UTC, ST-DDT commented on src/locales/fr_CH/word/interjection.ts
> +  'ouah',
Same here

2022-05-21 07:00 UTC, Yago commented on src/locales/fr/animal/lion.ts
> +  "lion d'Asie",
No, thank you for the review.

2022-05-21 07:01 UTC, Yago commented on src/locales/fr_CH/company/adjective.ts
> +  'Assimilated',
It came from the fr/company source, which was already in English. I removed it, thank you for the review.

2022-05-21 07:02 UTC, Yago commented
@ST-DDT Thank you for your feedbacks, I fixed everything.

2022-05-21 07:41 UTC, ST-DDT approved these changes
I checked the translations using Google Translate.
Looks good to me.

2022-05-21 17:31 UTC, ST-DDT commented
Please rebase/merge main.

2022-05-22 07:06 UTC, Yago commented
@ST-DDT I clean the merge commit from the branch and redid it properly 😉

2022-05-22 07:19 UTC, ST-DDT requested changes

2022-05-22 07:19 UTC, ST-DDT commented on src/locales/fr_CH/address/street_name.ts
> +export default ['{{address.street_prefix}} {{address.street_suffix}}'];
These are not street names. 
We fixed some inconsistent file names/contents in all locales, so this one no longer matches.
Please either copy them over from fr again or put some real street names in here.
Sorry for the trouble.

2022-05-22 07:30 UTC, Yago commented on src/locales/fr_CH/address/street_name.ts
> +export default ['{{address.street_prefix}} {{address.street_suffix}}'];
No worries. It's fixed.

2022-05-22 11:26 UTC, Shinigami92 approved these changes

2022-05-22 12:48 UTC, pkuczynski approved these changes

2022-05-22 13:18 UTC, ST-DDT approved these changes

2022-05-22 16:12 UTC, import-brain approved these changes

2022-05-22 19:21 UTC, merged