feat: added prettier actions
faker-js/faker pull request #98
Opened 2022-01-12 13:15 UTC by prisis

2022-01-12 15:50 UTC, prisis commented
This is just a proposal

2022-01-12 16:02 UTC, Shinigami92 requested changes

2022-01-12 16:02 UTC, Shinigami92 commented on .prettierignore
> +test/mocha.opts
I think prettier as an option for ignore unknown
Maybe we can configure that with the action also

2022-01-12 16:02 UTC, Shinigami92 commented on .github/workflows/prettier.yml
> +        echo "${{steps.prettier-run.outputs.prettier_output}}"
```suggestion
        echo "${{ steps.prettier-run.outputs.prettier_output }}"
```

2022-01-12 16:02 UTC, Shinigami92 commented on .github/workflows/prettier.yml
> +      uses: rutajdash/prettier-cli-action@v1.0.0
I think we can use so, that we are always on v1 latest
```suggestion
      uses: rutajdash/prettier-cli-action@v1
```

2022-01-12 16:02 UTC, Shinigami92 commented on .prettierignore
> +test/mocha.opts
Please format this file in asc order and folders at top and files bottom

2022-01-12 16:02 UTC, Shinigami92 commented on .prettierignore
> +test/mocha.opts
I also think node_modules is ignored by default :thinking:

2022-01-12 20:01 UTC, prisis commented on .prettierignore
> +test/mocha.opts
Not sure, just added it, will not hurt :D

2022-01-12 20:01 UTC, prisis commented on .prettierignore
> +test/mocha.opts
i will check

2022-01-12 20:01 UTC, prisis commented on .prettierignore
> +test/mocha.opts
i will check

2022-01-12 20:02 UTC, Shinigami92 commented on .github/workflows/prettier.yml
> +      uses: rutajdash/prettier-cli-action@v1
```node
Error: Unable to resolve action `rutajdash/prettier-cli-action@v1`, unable to find version `v1`
```

:cry:

2022-01-12 20:03 UTC, Shinigami92 commented on .github/workflows/prettier.yml
> +      uses: rutajdash/prettier-cli-action@v1
Don't know why it works for e.g. `actions/checkout@v2` and other actions I'm used to, but this one

2022-01-12 20:05 UTC, prisis commented on .prettierignore
> +test/mocha.opts
On what files should prettier run?

2022-01-12 20:14 UTC, prisis commented on .github/workflows/prettier.yml
> +      uses: rutajdash/prettier-cli-action@v1
Ah, because you need to create a version v1 to use something like this

2022-01-12 20:20 UTC, Shinigami92 commented on .prettierignore
> +test/mocha.opts
everything but ignore unknown https://prettier.io/docs/en/cli.html#--ignore-unknown

2022-01-12 20:22 UTC, Shinigami92 requested changes

2022-01-12 20:22 UTC, Shinigami92 commented on .github/workflows/prettier.yml
> +    - name: lint
This should not be named "lint"

2022-01-12 20:28 UTC, prisis commented on .github/workflows/prettier.yml
> +    - name: lint
Than no name?

2022-01-12 20:30 UTC, Shinigami92 commented on .github/workflows/prettier.yml
> +    - name: lint
or prettify or check-formatting or something like this
it "conflicts" with (es)lint

2022-01-12 20:31 UTC, Shinigami92 commented on .github/workflows/prettier.yml
> +    - name: lint
![image](https://user-images.githubusercontent.com/7195563/149216974-4cc57bca-c22a-4683-a806-aa15be27a181.png)

this just confused me and I thought I'm in the wrong action

2022-01-12 23:21 UTC, prisis commented
@Shinigami92 i did make is simpler

2022-01-15 16:07 UTC, damienwebdev commented
@prisis I'm not sure I understand the intent of this PR. Would it ever fail? Wouldn't the lint step beforehand fail first?

2022-01-15 19:03 UTC, prisis commented
I think this can be closed, after the eslint, has a plugin for prettier, im correct @Shinigami92?

2022-01-15 19:05 UTC, Shinigami92 commented
> I think this can be closed, after the eslint, has a plugin for prettier, im correct @Shinigami92?

I think yes

2022-01-15 20:46 UTC, closed without merging